Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_aalinetemp.h File Reference
Functions
static void NAME() plot (struct gl_context *ctx, struct LineInfo *line, int ix, int iy)
static void NAME() line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
Function Documentation
static void NAME() line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1) static
References gl_texture_unit::_Current, SWcontext::_InterpMode, _swrast_write_rgba_span(), ACOMP, LineInfo::aPlane, sw_span::arrayAttribs, sw_span::arrayMask, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, LineInfo::attrPlane, gl_texture_object::BaseLevel, BCOMP, BITFIELD64_BIT, LineInfo::bPlane, CLAMP, compute_plane(), gl_context::Const, constant_plane(), LineInfo::dx, LineInfo::dy, F, sw_span::facing, GCOMP, LineInfo::gPlane, LineInfo::halfWidth, gl_texture_image::Height, if(), gl_texture_object::Image, INIT_SPAN(), IS_INF_OR_NAN, LineInfo::len, gl_context::Light, gl_context::Line, gl_constants::MaxLineWidthAA, gl_constants::MinLineWidthAA, NAME, plot(), SWcontext::PointLineFacing, RCOMP, LineInfo::rPlane, segment(), gl_light_attrib::ShadeModel, LineInfo::span, SPAN_COVERAGE, SPAN_LAMBDA, SPAN_RGBA, SPAN_XY, SPAN_Z, sqrtf, SWcontext::StippleCounter, gl_line_attrib::StippleFactor, gl_line_attrib::StippleFlag, gl_line_attrib::StipplePattern, swrast, SWRAST_CONTEXT(), LineInfo::texHeight, gl_context::Texture, LineInfo::texWidth, gl_texture_attrib::Unit, VARYING_SLOT_POS, VARYING_SLOT_TEX0, VARYING_SLOT_VAR0, gl_line_attrib::Width, gl_texture_image::Width, LineInfo::wPlane, LineInfo::x0, LineInfo::x1, LineInfo::xAdj, LineInfo::y0, LineInfo::y1, LineInfo::yAdj, and LineInfo::zPlane.
Referenced by segment().
static void NAME() plot (struct gl_context * ctx, struct LineInfo * line, int ix, int iy) static
References _swrast_use_fragment_program(), _swrast_write_rgba_span(), ACOMP, LineInfo::aPlane, sw_span::array, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span_arrays::attribs, LineInfo::attrPlane, BCOMP, LineInfo::bPlane, compute_coveragef(), compute_lambda(), sw_span_arrays::coverage, sw_span::end, GCOMP, LineInfo::gPlane, iy, sw_span_arrays::lambda, RCOMP, sw_span_arrays::rgba, LineInfo::rPlane, solve_plane(), solve_plane_chan(), solve_plane_recip(), LineInfo::span, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, LineInfo::texHeight, LineInfo::texWidth, VARYING_SLOT_TEX0, VARYING_SLOT_VAR0, void(), LineInfo::wPlane, sw_span_arrays::x, sw_span_arrays::y, sw_span_arrays::z, and LineInfo::zPlane.
Referenced by line().