Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_blend.c File Reference
software blending.
#include "main/glheader.h"
#include "main/context.h"
#include "main/colormac.h"
#include "main/macros.h"
#include "s_blend.h"
#include "s_context.h"
#include "s_span.h"
Macros
#define _BLENDAPI
#define DIV255(X) (divtemp = (X), ((divtemp << 8) + divtemp + 256) >> 16)
Integer divide by 255 Declare "int divtemp" before using.
Functions
static void _BLENDAPI blend_noop (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Special case for glBlendFunc(GL_ZERO, GL_ONE).
static void _BLENDAPI blend_replace (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Special case for glBlendFunc(GL_ONE, GL_ZERO) Any chanType ok.
static void _BLENDAPI blend_transparency_ubyte (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Common transparency blending mode: glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA).
static void _BLENDAPI blend_transparency_ushort (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
static void _BLENDAPI blend_transparency_float (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
static void _BLENDAPI blend_add (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Add src and dest: glBlendFunc(GL_ONE, GL_ONE).
static void _BLENDAPI blend_min (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Blend min function.
static void _BLENDAPI blend_max (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Blend max function.
static void _BLENDAPI blend_modulate (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLvoid *src, const GLvoid *dst, GLenum chanType)
Modulate: result = src * dest Any chanType ok.
static void blend_general_float (struct gl_context *ctx, GLuint n, const GLubyte mask[], GLfloat rgba[][4], GLfloat dest[][4], GLenum chanType)
Do any blending operation, using floating point.
static void blend_general (struct gl_context *ctx, GLuint n, const GLubyte mask[], void *src, const void *dst, GLenum chanType)
Do any blending operation, any chanType.
void _swrast_choose_blend_func (struct gl_context *ctx, GLenum chanType)
Analyze current blending parameters to pick fastest blending function.
void _swrast_blend_span (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span)
Apply the blending operator to a span of pixels.
Detailed Description
software blending.
Author
Brian Paul
Only a few blend modes have been optimized (min, max, transparency, add) more optimized cases can easily be added if needed. Celestia uses glBlendFunc(GL_SRC_ALPHA, GL_ONE), for example.
Macro Definition Documentation
#define _BLENDAPI
#define DIV255 (X) (divtemp = (X), ((divtemp << 8) + divtemp + 256) >> 16)
Integer divide by 255 Declare "int divtemp" before using.
This satisfies Glean and should be reasonably fast. Contributed by Nathan Hand.
Referenced by blend_modulate(), and blend_transparency_ubyte().
Function Documentation
void _swrast_blend_span (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span)
Apply the blending operator to a span of pixels.
We can handle horizontal runs of pixels (spans) or arrays of x/y pixel coordinates.
References _swrast_get_dest_rgba(), sw_span::array, sw_span::arrayMask, ASSERT, SWcontext::BlendFunc, sw_span_arrays::ChanType, gl_context::Color, gl_colorbuffer_attrib::ColorLogicOpEnabled, sw_span::end, sw_span_arrays::mask, sw_span_arrays::rgba, SPAN_RGBA, swrast, SWRAST_CONTEXT(), and SWRAST_MAX_WIDTH.
Referenced by _swrast_write_rgba_span().
void _swrast_choose_blend_func (struct gl_context * ctx, GLenum chanType)
Analyze current blending parameters to pick fastest blending function.
Result: the ctx->Color.BlendFunc pointer is updated.
References gl_colorbuffer_attrib::Blend, blend_add(), blend_general(), blend_max(), blend_min(), blend_modulate(), blend_noop(), blend_replace(), blend_transparency_float(), blend_transparency_ubyte(), blend_transparency_ushort(), SWcontext::BlendFunc, gl_context::Color, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_validate_blend_func().
static void _BLENDAPI blend_add (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Add src and dest: glBlendFunc(GL_ONE, GL_ONE).
Any chanType ok.
References ACOMP, ASSERT, BCOMP, gl_colorbuffer_attrib::Blend, gl_context::Color, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, GCOMP, GLshort, GLubyte, GLushort, MIN2, RCOMP, gl_colorbuffer_attrib::SrcRGB, and void().
Referenced by _swrast_choose_blend_func().
static void blend_general (struct gl_context * ctx, GLuint n, const GLubyte mask[], void * src, const void * dst, GLenum chanType) static
Do any blending operation, any chanType.
References _mesa_error(), ACOMP, BCOMP, blend_general_float(), GCOMP, GLubyte, GLushort, RCOMP, UBYTE_TO_FLOAT, UNCLAMPED_FLOAT_TO_USHORT, and USHORT_TO_FLOAT.
Referenced by _swrast_choose_blend_func().
static void blend_general_float (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLfloat rgba[][4], GLfloat dest[][4], GLenum chanType) static
Do any blending operation, using floating point.
Parameters
n number of pixels
mask fragment writemask array
rgba array of incoming (and modified) pixels
dest array of pixels from the dest color buffer
References _mesa_problem(), ACOMP, ASSIGN_4V, BCOMP, gl_colorbuffer_attrib::Blend, gl_colorbuffer_attrib::BlendColor, CLAMP, gl_context::Color, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, F, GCOMP, MAX2, MIN2, RCOMP, gl_colorbuffer_attrib::SrcA, and gl_colorbuffer_attrib::SrcRGB.
Referenced by blend_general().
static void _BLENDAPI blend_max (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Blend max function.
Any chanType ok.
References ACOMP, ASSERT, BCOMP, gl_colorbuffer_attrib::Blend, gl_context::Color, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, GCOMP, GLubyte, GLushort, MAX2, RCOMP, and void().
Referenced by _swrast_choose_blend_func().
static void _BLENDAPI blend_min (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Blend min function.
Any chanType ok.
References ACOMP, ASSERT, BCOMP, gl_colorbuffer_attrib::Blend, gl_context::Color, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, GCOMP, GLubyte, GLushort, MIN2, RCOMP, and void().
Referenced by _swrast_choose_blend_func().
static void _BLENDAPI blend_modulate (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Modulate: result = src * dest Any chanType ok.
References ACOMP, ASSERT, BCOMP, DIV255, GCOMP, GLubyte, GLushort, RCOMP, and void().
Referenced by _swrast_choose_blend_func().
static void _BLENDAPI blend_noop (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Special case for glBlendFunc(GL_ZERO, GL_ONE).
No-op means the framebuffer values remain unchanged. Any chanType ok.
References ASSERT, gl_colorbuffer_attrib::Blend, gl_context::Color, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, GLubyte, GLushort, gl_colorbuffer_attrib::SrcRGB, and void().
Referenced by _swrast_choose_blend_func().
static void _BLENDAPI blend_replace (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Special case for glBlendFunc(GL_ONE, GL_ZERO) Any chanType ok.
References ASSERT, gl_colorbuffer_attrib::Blend, gl_context::Color, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, gl_colorbuffer_attrib::SrcRGB, and void().
Referenced by _swrast_choose_blend_func().
static void _BLENDAPI blend_transparency_float (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
References ACOMP, ASSERT, ASSIGN_4V, BCOMP, gl_colorbuffer_attrib::Blend, gl_context::Color, COPY_4V, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, F, GCOMP, RCOMP, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, and void().
Referenced by _swrast_choose_blend_func().
static void _BLENDAPI blend_transparency_ubyte (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
Common transparency blending mode: glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA).
References ACOMP, ASSERT, BCOMP, gl_colorbuffer_attrib::Blend, gl_context::Color, DIV255, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, GCOMP, GLubyte, RCOMP, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, and void().
Referenced by _swrast_choose_blend_func().
static void _BLENDAPI blend_transparency_ushort (struct gl_context * ctx, GLuint n, const GLubyte mask[], GLvoid * src, const GLvoid * dst, GLenum chanType) static
References ACOMP, ASSERT, ASSIGN_4V, BCOMP, gl_colorbuffer_attrib::Blend, gl_context::Color, COPY_4V, gl_colorbuffer_attrib::DstA, gl_colorbuffer_attrib::DstRGB, gl_colorbuffer_attrib::EquationA, gl_colorbuffer_attrib::EquationRGB, F, GCOMP, GLushort, RCOMP, gl_colorbuffer_attrib::SrcA, gl_colorbuffer_attrib::SrcRGB, and void().
Referenced by _swrast_choose_blend_func().