Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_depth.h File Reference
#include "main/glheader.h"
#include "s_span.h"
Functions
GLuint _swrast_depth_test_span (struct gl_context *ctx, SWspan *span)
Apply depth (Z) buffer testing to the span.
void _swrast_depth_clamp_span (struct gl_context *ctx, SWspan *span)
Clamp fragment Z values to the depth near/far range (glDepthRange()).
GLboolean _swrast_depth_bounds_test (struct gl_context *ctx, SWspan *span)
GL_EXT_depth_bounds_test extension.
void _swrast_read_depth_span_float (struct gl_context *ctx, struct gl_renderbuffer *rb, GLint n, GLint x, GLint y, GLfloat depth[])
Read a span of depth values from the given depth renderbuffer, returning the values as GLfloats.
void _swrast_clear_depth_buffer (struct gl_context *ctx)
Clear the given z/depth renderbuffer.
void _swrast_clear_depth_stencil_buffer (struct gl_context *ctx)
Clear both depth and stencil values in a combined depth+stencil buffer.
Function Documentation
void _swrast_clear_depth_buffer (struct gl_context * ctx)
Clear the given z/depth renderbuffer.
If the buffer is a combined depth+stencil buffer, only the Z bits will be touched.
References _mesa_error(), _mesa_get_format_name(), _mesa_pack_float_z_row(), _mesa_problem(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_framebuffer::Attachment, BUFFER_DEPTH, gl_depthbuffer_attrib::Clear, gl_context::Depth, gl_context::DrawBuffer, gl_context::Driver, for(), gl_renderbuffer::Format, GLbitfield, GLubyte, GLushort, if(), dd_function_table::MapRenderbuffer, gl_depthbuffer_attrib::Mask, MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by _swrast_Clear().
void _swrast_clear_depth_stencil_buffer (struct gl_context * ctx)
Clear both depth and stencil values in a combined depth+stencil buffer.
References _mesa_error(), _mesa_get_format_name(), _mesa_pack_float_z_row(), _mesa_problem(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_depthbuffer_attrib::Clear, gl_stencil_attrib::Clear, gl_context::Depth, gl_context::DrawBuffer, gl_context::Driver, gl_renderbuffer::Format, GLbitfield, GLubyte, dd_function_table::MapRenderbuffer, MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z32_FLOAT_X24S8, gl_renderbuffer_attachment::Renderbuffer, gl_context::Stencil, gl_config::stencilBits, dd_function_table::UnmapRenderbuffer, gl_framebuffer::Visual, and gl_stencil_attrib::WriteMask.
Referenced by _swrast_Clear().
GLboolean _swrast_depth_bounds_test (struct gl_context * ctx, SWspan * span)
GL_EXT_depth_bounds_test extension.
Discard fragments depending on whether the corresponding Z-buffer values are outside the depth bounds test range. Note: we test the Z buffer values, not the fragment Z values!
Returns
GL_TRUE if any fragments pass, GL_FALSE if no fragments pass
References gl_framebuffer::_DepthMaxF, _mesa_unpack_uint_z_row(), _swrast_pixel_address(), sw_span::array, sw_span::arrayMask, gl_framebuffer::Attachment, gl_depthbuffer_attrib::BoundsMax, gl_depthbuffer_attrib::BoundsMin, BUFFER_DEPTH, gl_context::Depth, gl_context::DrawBuffer, sw_span::end, gl_renderbuffer::Format, get_z32_values(), GLubyte, sw_span_arrays::mask, MESA_FORMAT_Z32, NULL, gl_renderbuffer_attachment::Renderbuffer, SPAN_XY, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_write_rgba_span().
void _swrast_depth_clamp_span (struct gl_context * ctx, SWspan * span)
Clamp fragment Z values to the depth near/far range (glDepthRange()).
This is used when GL_ARB_depth_clamp/GL_DEPTH_CLAMP is turned on. In that case, vertexes are not clipped against the near/far planes so rasterization will produce fragment Z values outside the usual [0,1] range.
References gl_framebuffer::_DepthMaxF, sw_span::array, gl_context::DrawBuffer, sw_span::end, gl_viewport_attrib::Far, if(), gl_viewport_attrib::Near, gl_context::Viewport, and sw_span_arrays::z.
Referenced by _swrast_write_rgba_span().
GLuint _swrast_depth_test_span (struct gl_context * ctx, SWspan * span)
Apply depth (Z) buffer testing to the span.
Returns
approx number of pixels that passed (only zero is reliable)
References _mesa_get_format_bits(), _mesa_get_format_bytes(), _mesa_get_pack_uint_z_func(), _mesa_unpack_uint_z_row(), _swrast_pixel_address(), sw_span::array, sw_span::arrayMask, gl_framebuffer::Attachment, BUFFER_DEPTH, depth_test_span16(), depth_test_span32(), gl_context::DrawBuffer, sw_span::end, gl_renderbuffer::Format, get_z32_values(), GLubyte, sw_span_arrays::mask, MESA_FORMAT_Z16, MESA_FORMAT_Z32, NULL, put_z32_values(), gl_renderbuffer_attachment::Renderbuffer, SPAN_XY, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, sw_span::y, and sw_span_arrays::z.
Referenced by _swrast_stencil_and_ztest_span(), and _swrast_write_rgba_span().
void _swrast_read_depth_span_float (struct gl_context * ctx, struct gl_renderbuffer * rb, GLint n, GLint x, GLint y, GLfloat depth[])
Read a span of depth values from the given depth renderbuffer, returning the values as GLfloats.
This function does clipping to prevent reading outside the depth buffer's bounds.
References _mesa_unpack_float_z_row(), _swrast_pixel_address(), for(), gl_renderbuffer::Format, gl_renderbuffer::Height, and gl_renderbuffer::Width.
Referenced by copy_depth_pixels().