Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_feedback.c File Reference
#include "main/glheader.h"
#include "main/colormac.h"
#include "main/feedback.h"
#include "main/macros.h"
#include "s_context.h"
#include "s_feedback.h"
#include "s_triangle.h"
Functions
static void feedback_vertex (struct gl_context *ctx, const SWvertex *v, const SWvertex *pv)
void _swrast_feedback_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_feedback_line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
void _swrast_feedback_point (struct gl_context *ctx, const SWvertex *v)
void _swrast_select_triangle (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1, const SWvertex *v2)
void _swrast_select_line (struct gl_context *ctx, const SWvertex *v0, const SWvertex *v1)
void _swrast_select_point (struct gl_context *ctx, const SWvertex *v)
Function Documentation
void _swrast_feedback_line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1)
References feedback_vertex(), gl_context::Light, gl_light_attrib::ShadeModel, SWcontext::StippleCounter, swrast, and SWRAST_CONTEXT().
Referenced by _swrast_choose_line().
void _swrast_feedback_point (struct gl_context * ctx, const SWvertex * v)
References feedback_vertex().
Referenced by _swrast_choose_point().
void _swrast_feedback_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References _swrast_culltriangle(), feedback_vertex(), gl_context::Light, and gl_light_attrib::ShadeModel.
Referenced by _swrast_choose_triangle().
void _swrast_select_line (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1)
References gl_framebuffer::_DepthMaxF, _mesa_update_hitflag(), SWvertex::attrib, gl_context::DrawBuffer, and VARYING_SLOT_POS.
Referenced by _swrast_choose_line().
void _swrast_select_point (struct gl_context * ctx, const SWvertex * v)
References gl_framebuffer::_DepthMaxF, _mesa_update_hitflag(), SWvertex::attrib, gl_context::DrawBuffer, and VARYING_SLOT_POS.
Referenced by _swrast_choose_point().
void _swrast_select_triangle (struct gl_context * ctx, const SWvertex * v0, const SWvertex * v1, const SWvertex * v2)
References gl_framebuffer::_DepthMaxF, _mesa_update_hitflag(), _swrast_culltriangle(), SWvertex::attrib, gl_context::DrawBuffer, and VARYING_SLOT_POS.
Referenced by _swrast_choose_triangle().
static void feedback_vertex (struct gl_context * ctx, const SWvertex * v, const SWvertex * pv) static
References gl_framebuffer::_DepthMaxF, _mesa_feedback_vertex(), SWvertex::attrib, gl_context::DrawBuffer, VARYING_SLOT_COL0, VARYING_SLOT_POS, and VARYING_SLOT_TEX0.
Referenced by _swrast_feedback_line(), _swrast_feedback_point(), and _swrast_feedback_triangle().