Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_fog.c File Reference
#include "main/glheader.h"
#include "main/colormac.h"
#include "main/macros.h"
#include "s_context.h"
#include "s_fog.h"
Macros
#define LINEAR_FOG(f, coord) f = (fogEnd - coord) * fogScale
#define EXP_FOG(f, coord) f = EXPF(density * coord)
#define EXP2_FOG(f, coord)
#define BLEND_FOG(f, coord) f = coord
#define FOG_LOOP(TYPE, FOG_FUNC)
Template code for computing fog blend factor and applying it to colors.
Functions
GLfloat _swrast_z_to_fogfactor (struct gl_context *ctx, GLfloat z)
Used to convert current raster distance to a fog factor in [0,1].
void _swrast_fog_rgba_span (const struct gl_context *ctx, SWspan *span)
Apply fog to a span of RGBA pixels.
Macro Definition Documentation
#define BLEND_FOG (f, coord) f = coord
Referenced by _swrast_fog_rgba_span().
#define EXP2_FOG (f, coord)
Value:
do {                                                    \
   GLfloat tmp = negDensitySquared * coord * coord;     \
   if (tmp < FLT_MIN_10_EXP)                            \
      tmp = FLT_MIN_10_EXP;                             \
   f = EXPF(tmp);                                       \
 } while(0)
Referenced by _swrast_fog_rgba_span().
#define EXP_FOG (f, coord) f = EXPF(density * coord)
Referenced by _swrast_fog_rgba_span().
#define FOG_LOOP (TYPE, FOG_FUNC)
Template code for computing fog blend factor and applying it to colors.
Parameters
TYPE either GLubyte, GLushort or GLfloat.
COMPUTE_F code to compute the fog blend factor, f.
Referenced by _swrast_fog_rgba_span().
#define LINEAR_FOG (f, coord) f = (fogEnd - coord) * fogScale
Referenced by _swrast_fog_rgba_span().
Function Documentation
void _swrast_fog_rgba_span (const struct gl_context * ctx, SWspan * span)
Apply fog to a span of RGBA pixels.
The fog value are either in the span->array->fog array or interpolated from the fog/fogStep values. They fog values are either fog coordinates (Z) or fog blend factors. _PreferPixelFog should be in sync with that state!
References SWcontext::_FogEnabled, _mesa_problem(), SWcontext::_PreferPixelFog, sw_span::array, sw_span::arrayMask, ASSERT, sw_span_arrays::attribs, BCOMP, BLEND_FOG, sw_span_arrays::ChanType, gl_fog_attrib::Color, CONST_SWRAST_CONTEXT(), gl_fog_attrib::Density, gl_fog_attrib::End, EXP2_FOG, EXP_FOG, F, gl_context::Fog, FOG_LOOP, GCOMP, GLubyte, GLushort, LINEAR_FOG, gl_fog_attrib::Mode, RCOMP, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_RGBA, gl_fog_attrib::Start, swrast, and VARYING_SLOT_COL0.
Referenced by _swrast_write_rgba_span().
GLfloat _swrast_z_to_fogfactor (struct gl_context * ctx, GLfloat z)
Used to convert current raster distance to a fog factor in [0,1].
References _mesa_problem(), CLAMP, gl_fog_attrib::Density, gl_fog_attrib::End, EXPF, F, gl_context::Fog, gl_fog_attrib::Mode, and gl_fog_attrib::Start.
Referenced by _swrast_span_default_attribs().