Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_fragprog.h File Reference
#include "s_span.h"
Functions
GLboolean _swrast_use_fragment_program (struct gl_context *ctx)
Should swrast use a fragment program?
void _swrast_exec_fragment_program (struct gl_context *ctx, SWspan *span)
Execute the current fragment program for all the fragments in the given span.
Function Documentation
void _swrast_exec_fragment_program (struct gl_context * ctx, SWspan * span)
Execute the current fragment program for all the fragments in the given span.
References gl_fragment_program_state::_Current, sw_span::array, sw_span::arrayMask, ASSERT, gl_fragment_program::Base, BITFIELD64_BIT, sw_span_arrays::ChanType, sw_span::end, FRAG_RESULT_COLOR, FRAG_RESULT_DEPTH, gl_context::FragmentProgram, gl_program::InputsRead, sw_span::interpMask, gl_program::OutputsWritten, run_program(), SPAN_RGBA, SPAN_Z, and VARYING_BIT_COL0.
Referenced by shade_texture_span().
GLboolean _swrast_use_fragment_program (struct gl_context * ctx)
Should swrast use a fragment program?
Returns
true if the current fragment program exists and is not the fixed function fragment program
References gl_fragment_program_state::_Current, gl_fragment_program_state::_TexEnvProgram, gl_fragment_program::Base, gl_context::FragmentProgram, and gl_program::NumInstructions.
Referenced by _swrast_choose_aa_line_function(), _swrast_choose_line(), _swrast_choose_triangle(), _swrast_set_aa_triangle_function(), _swrast_span_default_attribs(), _swrast_update_active_attribs(), _swrast_update_deferred_texture(), _swrast_update_fog_hint(), _swrast_update_fog_state(), _swrast_update_fragment_program(), _swrast_update_rasterflags(), _swrast_update_specular_vertex_add(), _swrast_write_rgba_span(), add_specular(), interpolate_texcoords(), plot(), and shade_texture_span().