Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_fragprog.c File Reference
#include "main/glheader.h"
#include "main/colormac.h"
#include "main/samplerobj.h"
#include "program/prog_instruction.h"
#include "s_context.h"
#include "s_fragprog.h"
#include "s_span.h"
Functions
GLboolean _swrast_use_fragment_program (struct gl_context *ctx)
Should swrast use a fragment program?
static void swizzle_texel (const GLfloat texel[4], GLfloat colorOut[4], GLuint swizzle)
Apply texture object's swizzle (X/Y/Z/W/0/1) to incoming 'texel' and return results in 'colorOut'.
static void fetch_texel_lod (struct gl_context *ctx, const GLfloat texcoord[4], GLfloat lambda, GLuint unit, GLfloat color[4])
Fetch a texel with given lod.
static void fetch_texel_deriv (struct gl_context *ctx, const GLfloat texcoord[4], const GLfloat texdx[4], const GLfloat texdy[4], GLfloat lodBias, GLuint unit, GLfloat color[4])
Fetch a texel with the given partial derivatives to compute a level of detail in the mipmap.
static void init_machine (struct gl_context *ctx, struct gl_program_machine *machine, const struct gl_fragment_program *program, const SWspan *span, GLuint col)
Initialize the virtual fragment program machine state prior to running fragment program on a fragment.
static void run_program (struct gl_context *ctx, SWspan *span, GLuint start, GLuint end)
Run fragment program on the pixels in span from 'start' to 'end' - 1.
void _swrast_exec_fragment_program (struct gl_context *ctx, SWspan *span)
Execute the current fragment program for all the fragments in the given span.
Function Documentation
void _swrast_exec_fragment_program (struct gl_context * ctx, SWspan * span)
Execute the current fragment program for all the fragments in the given span.
References gl_fragment_program_state::_Current, sw_span::array, sw_span::arrayMask, ASSERT, gl_fragment_program::Base, BITFIELD64_BIT, sw_span_arrays::ChanType, sw_span::end, FRAG_RESULT_COLOR, FRAG_RESULT_DEPTH, gl_context::FragmentProgram, gl_program::InputsRead, sw_span::interpMask, gl_program::OutputsWritten, run_program(), SPAN_RGBA, SPAN_Z, and VARYING_BIT_COL0.
Referenced by shade_texture_span().
GLboolean _swrast_use_fragment_program (struct gl_context * ctx)
Should swrast use a fragment program?
Returns
true if the current fragment program exists and is not the fixed function fragment program
References gl_fragment_program_state::_Current, gl_fragment_program_state::_TexEnvProgram, gl_fragment_program::Base, gl_context::FragmentProgram, and gl_program::NumInstructions.
Referenced by _swrast_choose_aa_line_function(), _swrast_choose_line(), _swrast_choose_triangle(), _swrast_set_aa_triangle_function(), _swrast_span_default_attribs(), _swrast_update_active_attribs(), _swrast_update_deferred_texture(), _swrast_update_fog_hint(), _swrast_update_fog_state(), _swrast_update_fragment_program(), _swrast_update_rasterflags(), _swrast_update_specular_vertex_add(), _swrast_write_rgba_span(), add_specular(), interpolate_texcoords(), plot(), and shade_texture_span().
static void fetch_texel_deriv (struct gl_context * ctx, const GLfloat texcoord[4], const GLfloat texdx[4], const GLfloat texdy[4], GLfloat lodBias, GLuint unit, GLfloat color[4]) static
Fetch a texel with the given partial derivatives to compute a level of detail in the mipmap.
Called via machine->FetchTexelDeriv()
Parameters
lodBias the lod bias which may be specified by a TXB instruction, otherwise zero.
References gl_texture_unit::_Current, gl_texture_object::_Swizzle, _swrast_compute_lambda(), ASSIGN_4V, gl_texture_object::BaseLevel, CLAMP, F, swrast_texture_image::HeightScale, gl_texture_object::Image, gl_texture_unit::LodBias, gl_sampler_object::LodBias, gl_sampler_object::MaxLod, gl_sampler_object::MinLod, swizzle_texel(), swrast, SWRAST_CONTEXT(), swrast_texture_image_const(), gl_context::Texture, SWcontext::TextureSample, gl_texture_attrib::Unit, and swrast_texture_image::WidthScale.
Referenced by init_machine().
static void fetch_texel_lod (struct gl_context * ctx, const GLfloat texcoord[4], GLfloat lambda, GLuint unit, GLfloat color[4]) static
Fetch a texel with given lod.
Called via machine->FetchTexelLod()
References gl_texture_unit::_Current, gl_texture_object::_Swizzle, ASSIGN_4V, CLAMP, F, gl_sampler_object::MaxLod, gl_sampler_object::MinLod, swizzle_texel(), swrast, SWRAST_CONTEXT(), gl_context::Texture, SWcontext::TextureSample, and gl_texture_attrib::Unit.
Referenced by init_machine().
static void init_machine (struct gl_context * ctx, struct gl_program_machine * machine, const struct gl_fragment_program * program, const SWspan * span, GLuint col) static
Initialize the virtual fragment program machine state prior to running fragment program on a fragment.
This involves initializing the input registers, condition codes, etc.
Parameters
machine the virtual machine state to init
program the fragment program we're about to run
span the span of pixels we'll operate on
col which element (column) of the span we'll operate on
References sw_span::array, sw_span_arrays::attribs, sw_span::attrStepX, sw_span::attrStepY, gl_fragment_program::Base, gl_shader_state::CurrentFragmentProgram, gl_context::DrawBuffer, sw_span::facing, fetch_texel_deriv(), fetch_texel_lod(), gl_framebuffer::Height, if(), gl_fragment_program::OriginUpperLeft, gl_fragment_program::PixelCenterInteger, gl_program::SamplerUnits, gl_context::Shader, VARYING_SLOT_FACE, VARYING_SLOT_MAX, and VARYING_SLOT_POS.
Referenced by run_program().
static void run_program (struct gl_context * ctx, SWspan * span, GLuint start, GLuint end) static
Run fragment program on the pixels in span from 'start' to 'end' - 1.
References gl_fragment_program_state::_Current, gl_framebuffer::_DepthMax, gl_framebuffer::_DepthMaxF, gl_framebuffer::_NumColorDrawBuffers, sw_span::array, sw_span_arrays::attribs, gl_fragment_program::Base, BITFIELD64_BIT, COPY_4V, gl_context::DrawBuffer, FRAG_RESULT_COLOR, FRAG_RESULT_DATA0, FRAG_RESULT_DEPTH, gl_context::FragmentProgram, SWcontext::FragProgMachine, init_machine(), sw_span_arrays::mask, gl_program::OutputsWritten, swrast, SWRAST_CONTEXT(), VARYING_SLOT_COL0, sw_span::writeAll, and sw_span_arrays::z.
Referenced by _swrast_exec_fragment_program().
static void swizzle_texel (const GLfloat texel[4], GLfloat colorOut[4], GLuint swizzle) inline static
Apply texture object's swizzle (X/Y/Z/W/0/1) to incoming 'texel' and return results in 'colorOut'.
References COPY_4V.
Referenced by fetch_texel_deriv(), and fetch_texel_lod().