Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_linetemp.h File Reference
Functions
static void NAME (struct gl_context *ctx, const SWvertex *vert0, const SWvertex *vert1)
Function Documentation
static void NAME (struct gl_context * ctx, const SWvertex * vert0, const SWvertex * vert1) static
References SWcontext::_InterpMode, _swrast_pixel_address(), sw_span::alpha, sw_span::alphaStep, sw_span::array, sw_span::arrayMask, ASSERT, ASSIGN_4V, gl_framebuffer::Attachment, SWvertex::attrib, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, sw_span::blue, sw_span::blueStep, BUFFER_DEPTH, ChanToFixed, SWvertex::color, COPY_4V, DEPTH_TYPE, gl_config::depthBits, gl_context::DrawBuffer, sw_span::end, sw_span::facing, FIXED_HALF, FIXED_SHIFT, FloatToFixed, GLubyte, sw_span::green, sw_span::greenStep, gl_framebuffer::Height, INIT_SPAN(), sw_span::interpMask, IS_INF_OR_NAN, gl_context::Light, MAX2, SWcontext::PointLineFacing, sw_span::red, sw_span::redStep, RENDER_SPAN, gl_renderbuffer_attachment::Renderbuffer, SETUP_CODE, gl_light_attrib::ShadeModel, span, SPAN_RGBA, SPAN_XY, SPAN_Z, swrast, SWRAST_CONTEXT(), VARYING_SLOT_POS, gl_framebuffer::Visual, void(), gl_framebuffer::Width, sw_span_arrays::x, sw_span_arrays::y, y1, Z, sw_span::z, and sw_span::zStep.