Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_logic.h File Reference
#include "s_span.h"
Functions
void _swrast_logicop_rgba_span (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span)
Apply the current logic operator to a span of RGBA pixels.
Function Documentation
void _swrast_logicop_rgba_span (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span)
Apply the current logic operator to a span of RGBA pixels.
We can handle horizontal runs of pixels (spans) or arrays of x/y pixel coordinates.
References _swrast_get_dest_rgba(), sw_span::array, sw_span::arrayMask, ASSERT, sw_span_arrays::attribs, sw_span_arrays::ChanType, sw_span::end, logicop_uint1(), logicop_uint2(), logicop_uint4(), sw_span_arrays::mask, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_RGBA, SWRAST_MAX_WIDTH, and VARYING_SLOT_COL0.
Referenced by _swrast_write_rgba_span().