Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_masking.h File Reference
#include "main/glheader.h"
#include "s_span.h"
Functions
void _swrast_mask_rgba_span (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span, GLuint buf)
Apply the color mask to a span of rgba values.
Function Documentation
void _swrast_mask_rgba_span (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span, GLuint buf)
Apply the color mask to a span of rgba values.
References _swrast_get_dest_rgba(), ACOMP, sw_span::array, sw_span::arrayMask, ASSERT, sw_span_arrays::attribs, BCOMP, sw_span_arrays::ChanType, gl_context::Color, gl_colorbuffer_attrib::ColorMask, sw_span::end, for(), GCOMP, GLushort, RCOMP, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_RGBA, SWRAST_MAX_WIDTH, and VARYING_SLOT_COL0.
Referenced by _swrast_write_rgba_span().