Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_points.c File Reference
#include "main/glheader.h"
#include "main/colormac.h"
#include "main/macros.h"
#include "s_context.h"
#include "s_feedback.h"
#include "s_points.h"
#include "s_span.h"
Macros
#define CULL_INVALID(V)
Used to cull points with invalid coords.
Functions
static GLfloat get_size (const struct gl_context *ctx, const SWvertex *vert, GLboolean smoothed)
Get/compute the point size.
static void sprite_point (struct gl_context *ctx, const SWvertex *vert)
Draw a point sprite.
static void smooth_point (struct gl_context *ctx, const SWvertex *vert)
Draw smooth/antialiased point.
static void large_point (struct gl_context *ctx, const SWvertex *vert)
Draw large (size >= 1) non-AA point.
static void pixel_point (struct gl_context *ctx, const SWvertex *vert)
Draw size=1, single-pixel point.
void _swrast_add_spec_terms_point (struct gl_context *ctx, const SWvertex *v0)
Add specular color to primary color, draw point, restore original primary color.
void _swrast_choose_point (struct gl_context *ctx)
Examine current state to determine which point drawing function to use.
Macro Definition Documentation
#define CULL_INVALID (V)
Value:
do {                                              \
      float tmp = (V)->attrib[VARYING_SLOT_POS][0]   \
                + (V)->attrib[VARYING_SLOT_POS][1];  \
      if (IS_INF_OR_NAN(tmp))                        \
         return;                                     \
   } while(0)
Used to cull points with invalid coords.
Referenced by large_point(), pixel_point(), smooth_point(), and sprite_point().
Function Documentation
void _swrast_add_spec_terms_point (struct gl_context * ctx, const SWvertex * v0)
Add specular color to primary color, draw point, restore original primary color.
References SWvertex::attrib, CHAN_TO_FLOAT, SWvertex::color, COPY_CHAN4, SWcontext::SpecPoint, SWRAST_CONTEXT(), UNCLAMPED_FLOAT_TO_CHAN, and VARYING_SLOT_COL1.
Referenced by _swrast_validate_point().
void _swrast_choose_point (struct gl_context * ctx)
Examine current state to determine which point drawing function to use.
References gl_point_attrib::_Attenuated, _swrast_feedback_point(), _swrast_select_point(), CLAMP, large_point(), gl_point_attrib::MaxSize, gl_point_attrib::MinSize, pixel_point(), gl_context::Point, SWcontext::Point, gl_vertex_program_state::PointSizeEnabled, gl_point_attrib::PointSprite, gl_context::RenderMode, gl_point_attrib::Size, smooth_point(), gl_point_attrib::SmoothFlag, sprite_point(), swrast, SWRAST_CONTEXT(), and gl_context::VertexProgram.
Referenced by _swrast_CreateContext().
static GLfloat get_size (const struct gl_context * ctx, const SWvertex * vert, GLboolean smoothed) inline static
Get/compute the point size.
The size may come from a vertex shader, or computed with attentuation or just the glPointSize value. Must also clamp to user-defined range and implmentation limits.
References gl_point_attrib::_Attenuated, CLAMP, gl_context::Const, gl_constants::MaxPointSize, gl_constants::MaxPointSizeAA, gl_point_attrib::MaxSize, gl_constants::MinPointSize, gl_constants::MinPointSizeAA, gl_point_attrib::MinSize, gl_context::Point, SWvertex::pointSize, gl_vertex_program_state::PointSizeEnabled, gl_point_attrib::Size, and gl_context::VertexProgram.
Referenced by large_point(), smooth_point(), and sprite_point().
static void large_point (struct gl_context * ctx, const SWvertex * vert) static
Draw large (size >= 1) non-AA point.
RGB or CI mode.
References _swrast_write_rgba_span(), sw_span::alpha, sw_span::alphaStep, sw_span::array, sw_span::arrayMask, ASSIGN_4V, SWvertex::attrib, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, sw_span::blue, sw_span::blueStep, ChanToFixed, SWvertex::color, COPY_4V, CULL_INVALID, gl_config::depthBits, gl_context::DrawBuffer, sw_span::end, F, sw_span::facing, FloatToFixed, get_size(), sw_span::green, sw_span::greenStep, INIT_SPAN(), sw_span::interpMask, iy, MAX2, SWcontext::PointLineFacing, sw_span::red, sw_span::redStep, span, SPAN_RGBA, SPAN_XY, SPAN_Z, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, VARYING_SLOT_POS, gl_framebuffer::Visual, sw_span_arrays::x, sw_span_arrays::y, sw_span::z, and sw_span::zStep.
Referenced by _swrast_choose_point().
static void pixel_point (struct gl_context * ctx, const SWvertex * vert) static
Draw size=1, single-pixel point.
References SWcontext::_ActiveAttribMask, SWcontext::_RasterMask, _swrast_write_rgba_span(), ACOMP, sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, ASSERT, SWvertex::attrib, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span_arrays::attribs, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, BCOMP, BLEND_BIT, SWvertex::color, COPY_4V, CULL_INVALID, sw_span::end, sw_span::facing, GCOMP, sw_span::interpMask, LOGIC_OP_BIT, MASKING_BIT, SWcontext::PointLineFacing, SWcontext::PointSpan, RCOMP, sw_span_arrays::rgba, span, SPAN_RGBA, SPAN_XY, SPAN_Z, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, VARYING_SLOT_POS, sw_span_arrays::x, sw_span_arrays::y, and sw_span_arrays::z.
Referenced by _swrast_choose_point().
static void smooth_point (struct gl_context * ctx, const SWvertex * vert) static
Draw smooth/antialiased point.
RGB or CI mode.
References gl_multisample_attrib::_Enabled, _swrast_write_rgba_span(), sw_span::alpha, sw_span::alphaStep, sw_span::array, sw_span::arrayMask, ASSIGN_4V, SWvertex::attrib, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, sw_span::blue, sw_span::blueStep, ChanToFixed, SWvertex::color, COPY_4V, sw_span_arrays::coverage, CULL_INVALID, gl_config::depthBits, gl_context::DrawBuffer, sw_span::end, F, sw_span::facing, FloatToFixed, get_size(), sw_span::green, sw_span::greenStep, INIT_SPAN(), sw_span::interpMask, iy, sw_span_arrays::mask, MAX2, gl_context::Multisample, gl_context::Point, SWcontext::PointLineFacing, SWvertex::pointSize, sw_span::red, sw_span::redStep, span, SPAN_COVERAGE, SPAN_MASK, SPAN_RGBA, SPAN_Z, swrast, SWRAST_CONTEXT(), gl_point_attrib::Threshold, VARYING_SLOT_POS, gl_framebuffer::Visual, void(), sw_span::x, sw_span::y, sw_span::z, and sw_span::zStep.
Referenced by _swrast_choose_point().
static void sprite_point (struct gl_context * ctx, const SWvertex * vert) static
Draw a point sprite.
References _swrast_write_rgba_span(), sw_span::alpha, sw_span::alphaStep, ASSERT, ASSIGN_4V, SWvertex::attrib, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, sw_span::blue, sw_span::blueStep, ChanToFixed, SWvertex::color, gl_point_attrib::CoordReplace, COPY_4V, CULL_INVALID, gl_config::depthBits, gl_context::DrawBuffer, Elements, sw_span::end, F, sw_span::facing, FloatToFixed, get_size(), sw_span::green, sw_span::greenStep, INIT_SPAN(), sw_span::interpMask, iy, MAX2, MAX_TEXTURE_COORD_UNITS, gl_context::Point, SWcontext::PointLineFacing, sw_span::red, sw_span::redStep, span, SPAN_RGBA, SPAN_Z, gl_point_attrib::SpriteOrigin, gl_point_attrib::SpriteRMode, swrast, SWRAST_CONTEXT(), VARYING_SLOT_PNTC, VARYING_SLOT_POS, VARYING_SLOT_TEX0, VARYING_SLOT_TEX7, gl_framebuffer::Visual, sw_span::x, sw_span::y, sw_span::z, and sw_span::zStep.
Referenced by _swrast_choose_point().