Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_span.c File Reference
Span processing functions used by all rasterization functions.
#include "main/glheader.h"
#include "main/colormac.h"
#include "main/format_pack.h"
#include "main/format_unpack.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/image.h"
#include "main/samplerobj.h"
#include "s_atifragshader.h"
#include "s_alpha.h"
#include "s_blend.h"
#include "s_context.h"
#include "s_depth.h"
#include "s_fog.h"
#include "s_logic.h"
#include "s_masking.h"
#include "s_fragprog.h"
#include "s_span.h"
#include "s_stencil.h"
#include "s_texcombine.h"
#include <stdbool.h>
Macros
#define SHIFT_ARRAY(ARRAY, SHIFT, LEN) memmove(ARRAY, ARRAY + (SHIFT), (LEN) * sizeof(ARRAY[0]))
Functions
void _swrast_span_default_attribs (struct gl_context *ctx, SWspan *span)
Set default fragment attributes for the span using the current raster values.
static void interpolate_active_attribs (struct gl_context *ctx, SWspan *span, GLbitfield64 attrMask)
Interpolate the active attributes (and'd with attrMask) to fill in span->array->attribs[].
static void interpolate_int_colors (struct gl_context *ctx, SWspan *span)
Interpolate primary colors to fill in the span->array->rgba8 (or rgb16) color array.
static void interpolate_float_colors (SWspan *span)
Populate the VARYING_SLOT_COL0 array.
void _swrast_span_interpolate_z (const struct gl_context *ctx, SWspan *span)
Fill in the span.zArray array from the span->z, zStep values.
GLfloat _swrast_compute_lambda (GLfloat dsdx, GLfloat dsdy, GLfloat dtdx, GLfloat dtdy, GLfloat dqdx, GLfloat dqdy, GLfloat texW, GLfloat texH, GLfloat s, GLfloat t, GLfloat q, GLfloat invQ)
Compute mipmap LOD from partial derivatives.
static void interpolate_texcoords (struct gl_context *ctx, SWspan *span)
Compute mipmap LOD from partial derivatives.
static void interpolate_wpos (struct gl_context *ctx, SWspan *span)
Fill in the arrays->attribs[VARYING_SLOT_POS] array.
static void stipple_polygon_span (struct gl_context *ctx, SWspan *span)
Apply the current polygon stipple pattern to a span of pixels.
static GLuint clip_span (struct gl_context *ctx, SWspan *span)
Clip a pixel span to the current buffer/window boundaries: DrawBuffer->_Xmin, _Xmax, _Ymin, _Ymax.
static void add_specular (struct gl_context *ctx, SWspan *span)
Add specular colors to primary colors.
static void apply_aa_coverage (SWspan *span)
Apply antialiasing coverage value to alpha values.
static void clamp_colors (SWspan *span)
Clamp span's float colors to [0,1].
static void convert_color_type (SWspan *span, GLenum newType, GLuint output)
Convert the span's color arrays to the given type.
static void shade_texture_span (struct gl_context *ctx, SWspan *span)
Apply fragment shader, fragment program or normal texturing to span.
static void put_values (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum datatype, GLuint count, const GLint x[], const GLint y[], const void *values, const GLubyte *mask)
Put colors at x/y locations into a renderbuffer.
void _swrast_put_row (struct gl_context *ctx, struct gl_renderbuffer *rb, GLenum datatype, GLuint count, GLint x, GLint y, const void *values, const GLubyte *mask)
Put row of colors into renderbuffer.
void _swrast_write_rgba_span (struct gl_context *ctx, SWspan *span)
Apply all the per-fragment operations to a span.
void _swrast_read_rgba_span (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint n, GLint x, GLint y, GLvoid *rgba)
Read float RGBA pixels from a renderbuffer.
static void get_values (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint count, const GLint x[], const GLint y[], void *values, GLenum type)
Get colors at x/y positions with clipping.
static void get_row (struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint count, GLint x, GLint y, GLvoid *values, GLenum type)
Get row of colors with clipping.
void * _swrast_get_dest_rgba (struct gl_context *ctx, struct gl_renderbuffer *rb, SWspan *span)
Get RGBA pixels from the given renderbuffer.
Detailed Description
Span processing functions used by all rasterization functions.
This is where all the per-fragment tests are performed
Author
Brian Paul
Macro Definition Documentation
#define SHIFT_ARRAY (ARRAY, SHIFT, LEN) memmove(ARRAY, ARRAY + (SHIFT), (LEN) * sizeof(ARRAY[0]))
Referenced by clip_span().
Function Documentation
GLfloat _swrast_compute_lambda (GLfloat dsdx, GLfloat dsdy, GLfloat dtdx, GLfloat dtdy, GLfloat dqdx, GLfloat dqdy, GLfloat texW, GLfloat texH, GLfloat s, GLfloat t, GLfloat q, GLfloat invQ)
Compute mipmap LOD from partial derivatives.
This the ideal solution, as given in the OpenGL spec.
References MAX2, and sqrtf.
Referenced by fetch_texel_deriv(), and interpolate_texcoords().
void* _swrast_get_dest_rgba (struct gl_context * ctx, struct gl_renderbuffer * rb, SWspan * span)
Get RGBA pixels from the given renderbuffer.
Used by blending, logicop and masking functions.
Returns
pointer to the colors we read.
References sw_span::array, sw_span::arrayMask, sw_span_arrays::attribs, sw_span_arrays::ChanType, sw_span::end, get_row(), get_values(), SPAN_XY, VARYING_SLOT_MAX, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_blend_span(), _swrast_logicop_rgba_span(), and _swrast_mask_rgba_span().
void _swrast_put_row (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum datatype, GLuint count, GLint x, GLint y, const void * values, const GLubyte * mask)
Put row of colors into renderbuffer.
References _mesa_get_format_bytes(), _mesa_pack_float_rgba_row(), _mesa_pack_ubyte_rgba_row(), _swrast_pixel_address(), gl_renderbuffer::Format, and GLubyte.
Referenced by _swrast_write_rgba_span().
void _swrast_read_rgba_span (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint n, GLint x, GLint y, GLvoid * rgba)
Read float RGBA pixels from a renderbuffer.
Clipping will be done to prevent reading ouside the buffer's boundaries.
Parameters
rgba the returned colors
References gl_renderbuffer::_BaseFormat, _mesa_problem(), _mesa_unpack_rgba_row(), _mesa_unpack_ubyte_rgba_row(), _swrast_pixel_address(), ASSERT, gl_renderbuffer::Format, GLubyte, gl_renderbuffer::Height, swrast_renderbuffer::Map, swrast_renderbuffer(), and gl_renderbuffer::Width.
Referenced by copy_rgba_pixels().
void _swrast_span_default_attribs (struct gl_context * ctx, SWspan * span)
Set default fragment attributes for the span using the current raster values.
Used prior to glDraw/CopyPixels and glBitmap.
References gl_framebuffer::_DepthMaxF, gl_ati_fragment_shader_state::_Enabled, SWcontext::_PreferPixelFog, _swrast_use_fragment_program(), _swrast_z_to_fogfactor(), sw_span::alpha, sw_span::alphaStep, ASSIGN_4V, gl_context::ATIFragmentShader, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, sw_span::blue, sw_span::blueStep, gl_fog_attrib::ColorSumEnabled, gl_context::Const, COPY_4V, gl_context::Current, gl_config::depthBits, gl_context::DrawBuffer, gl_light_attrib::Enabled, F, FloatToFixed, gl_context::Fog, sw_span::green, sw_span::greenStep, sw_span::interpMask, IntToFixed, gl_context::Light, gl_constants::MaxTextureCoordUnits, MIN2, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_current_attrib::RasterSecondaryColor, gl_current_attrib::RasterTexCoords, sw_span::red, sw_span::redStep, SPAN_RGBA, SPAN_Z, swrast, SWRAST_CONTEXT(), UNCLAMPED_FLOAT_TO_CHAN, VARYING_SLOT_COL0, VARYING_SLOT_COL1, VARYING_SLOT_FOGC, VARYING_SLOT_POS, VARYING_SLOT_TEX0, gl_framebuffer::Visual, sw_span::z, and sw_span::zStep.
Referenced by _swrast_Bitmap(), copy_depth_pixels(), copy_rgba_pixels(), draw_depth_pixels(), and draw_rgba_pixels().
void _swrast_span_interpolate_z (const struct gl_context * ctx, SWspan * span)
Fill in the span.zArray array from the span->z, zStep values.
References sw_span::array, sw_span::arrayMask, ASSERT, gl_config::depthBits, gl_context::DrawBuffer, sw_span::end, FixedToInt, sw_span::interpMask, SPAN_Z, gl_framebuffer::Visual, sw_span_arrays::z, sw_span::z, and sw_span::zStep.
Referenced by _swrast_write_rgba_span(), and shade_texture_span().
void _swrast_write_rgba_span (struct gl_context * ctx, SWspan * span)
Apply all the per-fragment operations to a span.
This now includes texturing (_swrast_write_texture_span() is history). This function may modify any of the array values in the span. span->interpMask and span->arrayMask may be changed but will be restored to their original values before returning.
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorDrawBuffers, gl_fragment_program_state::_Current, SWcontext::_DeferredTexture, gl_ati_fragment_shader_state::_Enabled, gl_stencil_attrib::_Enabled, gl_texture_attrib::_EnabledCoordUnits, SWcontext::_FogEnabled, gl_framebuffer::_NumColorDrawBuffers, _swrast_alpha_test(), _swrast_blend_span(), _swrast_depth_bounds_test(), _swrast_depth_clamp_span(), _swrast_depth_test_span(), _swrast_fog_rgba_span(), _swrast_logicop_rgba_span(), _swrast_mask_rgba_span(), _swrast_put_row(), _swrast_span_interpolate_z(), _swrast_stencil_and_ztest_span(), _swrast_use_fragment_program(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, add_specular(), gl_colorbuffer_attrib::AlphaEnabled, apply_aa_coverage(), sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, ASSERT, gl_context::ATIFragmentShader, sw_span_arrays::attribs, gl_fragment_program::Base, gl_colorbuffer_attrib::BlendEnabled, gl_depthbuffer_attrib::BoundsTest, sw_span_arrays::ChanType, clamp_colors(), gl_colorbuffer_attrib::ClampFragmentColor, clip_span(), gl_context::Color, gl_lightmodel::ColorControl, gl_colorbuffer_attrib::ColorLogicOpEnabled, gl_colorbuffer_attrib::ColorMask, gl_fog_attrib::ColorSumEnabled, swrast_renderbuffer::ColorType, convert_color_type(), gl_query_state::CurrentOcclusionObject, gl_context::Depth, gl_config::depthBits, gl_transform_attrib::DepthClamp, gl_context::DrawBuffer, gl_light_attrib::Enabled, sw_span::end, gl_context::Fog, FRAG_RESULT_DATA0, gl_context::FragmentProgram, GLbitfield, sw_span::interpMask, interpolate_active_attribs(), interpolate_int_colors(), gl_context::Light, sw_span_arrays::mask, gl_light_attrib::Model, NULL, gl_program::OutputsWritten, gl_context::Polygon, sw_span::primitive, put_values(), gl_context::Query, gl_query_object::Result, sw_span_arrays::rgba, sw_span_arrays::rgba8, shade_texture_span(), SPAN_COVERAGE, SPAN_MASK, SPAN_RGBA, SPAN_XY, SPAN_Z, SWcontext::SpecularVertexAdd, gl_context::Stencil, stipple_polygon_span(), gl_polygon_attrib::StippleFlag, swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, gl_depthbuffer_attrib::Test, gl_context::Texture, gl_context::Transform, VARYING_BIT_COL0, VARYING_SLOT_COL0, gl_framebuffer::Visual, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_Bitmap(), _swrast_flush(), copy_depth_pixels(), copy_rgba_pixels(), draw_depth_pixels(), draw_rgba_pixels(), draw_wide_line(), for(), if(), large_point(), line(), pixel_point(), plot(), smooth_point(), sprite_point(), and zoom_span().
static void add_specular (struct gl_context * ctx, SWspan * span) inline static
Add specular colors to primary colors.
Only called during fixed-function operation. Result is float color array (VARYING_SLOT_COL0).
References SWcontext::_ActiveAttribMask, _swrast_use_fragment_program(), sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, ASSERT, sw_span_arrays::attribs, sw_span_arrays::ChanType, sw_span::end, GLubyte, interpolate_active_attribs(), interpolate_float_colors(), sw_span_arrays::mask, SPAN_RGBA, swrast, SWRAST_CONTEXT(), VARYING_BIT_COL0, VARYING_BIT_COL1, VARYING_SLOT_COL0, VARYING_SLOT_COL1, and void().
Referenced by _swrast_write_rgba_span().
static void apply_aa_coverage (SWspan * span) inline static
Apply antialiasing coverage value to alpha values.
References ACOMP, sw_span::array, ASSERT, sw_span_arrays::attribs, sw_span_arrays::ChanType, CLAMP, sw_span_arrays::coverage, sw_span::end, GLubyte, GLushort, sw_span_arrays::rgba16, sw_span_arrays::rgba8, and VARYING_SLOT_COL0.
Referenced by _swrast_write_rgba_span().
static void clamp_colors (SWspan * span) inline static
Clamp span's float colors to [0,1].
References ACOMP, sw_span::array, ASSERT, sw_span_arrays::attribs, BCOMP, sw_span_arrays::ChanType, CLAMP, sw_span::end, F, GCOMP, RCOMP, and VARYING_SLOT_COL0.
Referenced by _swrast_write_rgba_span().
static GLuint clip_span (struct gl_context * ctx, SWspan * span) inline static
Clip a pixel span to the current buffer/window boundaries: DrawBuffer->_Xmin, _Xmax, _Ymin, _Ymax.
This will accomplish window clipping and scissoring. Return: GL_TRUE some pixels still visible GL_FALSE nothing visible
References gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, sw_span::alpha, sw_span::alphaStep, sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, ASSERT, sw_span_arrays::attribs, sw_span::attrStart, sw_span::attrStepX, sw_span::blue, sw_span::blueStep, sw_span_arrays::coverage, gl_context::DrawBuffer, sw_span::end, GLubyte, sw_span::green, sw_span::greenStep, sw_span_arrays::index, sw_span::index, sw_span::indexStep, sw_span::interpMask, sw_span::intTex, sw_span::intTexStep, sw_span_arrays::lambda, sw_span::leftClip, sw_span_arrays::mask, MAX_TEXTURE_COORD_UNITS, sw_span::red, sw_span::redStep, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SHIFT_ARRAY, SPAN_MASK, SPAN_XY, VARYING_SLOT_MAX, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, sw_span::y, sw_span_arrays::z, sw_span::z, and sw_span::zStep.
Referenced by _swrast_write_rgba_span().
static void convert_color_type (SWspan * span, GLenum newType, GLuint output) inline static
Convert the span's color arrays to the given type.
The only way 'output' can be greater than zero is when we have a fragment program that writes to gl_FragData[1] or higher.
Parameters
output which fragment program color output is being processed
References _mesa_convert_colors(), sw_span::array, ASSERT, sw_span_arrays::attribs, sw_span_arrays::ChanType, sw_span::end, sw_span_arrays::mask, sw_span_arrays::rgba, sw_span_arrays::rgba16, sw_span_arrays::rgba8, and VARYING_SLOT_COL0.
Referenced by _swrast_write_rgba_span(), and shade_texture_span().
static void get_row (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint count, GLint x, GLint y, GLvoid * values, GLenum type) static
Get row of colors with clipping.
Parameters
type type of values to return
References _mesa_problem(), _mesa_unpack_rgba_row(), _mesa_unpack_ubyte_rgba_row(), _swrast_pixel_address(), gl_renderbuffer::Format, GLubyte, gl_renderbuffer::Height, and gl_renderbuffer::Width.
Referenced by _swrast_get_dest_rgba().
static void get_values (struct gl_context * ctx, struct gl_renderbuffer * rb, GLuint count, const GLint x[], const GLint y[], void * values, GLenum type) static
Get colors at x/y positions with clipping.
Parameters
type type of values to return
References _mesa_problem(), _mesa_unpack_rgba_row(), _mesa_unpack_ubyte_rgba_row(), _swrast_pixel_address(), gl_renderbuffer::Format, GLubyte, gl_renderbuffer::Height, and gl_renderbuffer::Width.
Referenced by _swrast_get_dest_rgba().
static void interpolate_active_attribs (struct gl_context * ctx, SWspan * span, GLbitfield64 attrMask) inline static
Interpolate the active attributes (and'd with attrMask) to fill in span->array->attribs[].
Perspective correction will be done. The point/line/triangle function should have computed attrStart/Step values for VARYING_SLOT_POS[3]!
References sw_span::array, sw_span::arrayAttribs, ASSERT, ATTRIB_LOOP_BEGIN, ATTRIB_LOOP_END, sw_span_arrays::attribs, sw_span::attrStart, sw_span::attrStepX, BITFIELD64_BIT, sw_span::end, sw_span::leftClip, swrast, SWRAST_CONTEXT(), and VARYING_SLOT_POS.
Referenced by _swrast_write_rgba_span(), add_specular(), interpolate_int_colors(), and shade_texture_span().
static void interpolate_float_colors (SWspan * span) inline static
Populate the VARYING_SLOT_COL0 array.
References sw_span::alpha, sw_span::alphaStep, sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, ASSERT, ASSIGN_4V, sw_span_arrays::attribs, sw_span::blue, sw_span::blueStep, sw_span_arrays::ChanType, sw_span::end, FixedToFloat, sw_span::green, sw_span::greenStep, sw_span::interpMask, sw_span::red, sw_span::redStep, sw_span_arrays::rgba8, SPAN_FLAT, SPAN_RGBA, UBYTE_TO_FLOAT, VARYING_BIT_COL0, and VARYING_SLOT_COL0.
Referenced by add_specular().
static void interpolate_int_colors (struct gl_context * ctx, SWspan * span) inline static
Interpolate primary colors to fill in the span->array->rgba8 (or rgb16) color array.
References _mesa_problem(), ACOMP, sw_span::alpha, sw_span::alphaStep, sw_span::array, sw_span::arrayMask, ASSERT, BCOMP, sw_span::blue, sw_span::blueStep, sw_span_arrays::ChanType, COPY_4V, sw_span::end, FixedToChan, FixedToInt, GCOMP, GLubyte, GLushort, sw_span::green, sw_span::greenStep, sw_span::interpMask, interpolate_active_attribs(), RCOMP, sw_span::red, sw_span::redStep, sw_span_arrays::rgba16, sw_span_arrays::rgba8, SPAN_FLAT, SPAN_RGBA, and VARYING_BIT_COL0.
Referenced by _swrast_write_rgba_span(), and shade_texture_span().
static void interpolate_texcoords (struct gl_context * ctx, SWspan * span) static
Compute mipmap LOD from partial derivatives.
This is a faster approximation than above function. Fill in the span.array->attrib[VARYING_SLOT_TEXn] arrays from the using the attrStart/Step values.
This function only used during fixed-function fragment processing.
Note: in the places where we divide by Q (or mult by invQ) we're really doing two things: perspective correction and texcoord projection. Remember, for texcoord (s,t,r,q) we need to index texels with (s/q, t/q, r/q).
References gl_texture_unit::_Current, gl_ati_fragment_shader_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, _swrast_compute_lambda(), _swrast_use_fragment_program(), sw_span::array, sw_span::arrayMask, gl_context::ATIFragmentShader, sw_span_arrays::attribs, sw_span::attrStart, sw_span::attrStepX, sw_span::attrStepY, gl_texture_object::BaseLevel, gl_context::Const, sw_span::end, F, for(), swrast_texture_image::HeightScale, gl_texture_object::Image, sw_span_arrays::lambda, sw_span::leftClip, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_constants::MaxTextureUnits, gl_sampler_object::MinFilter, SPAN_LAMBDA, swrast_texture_image_const(), gl_context::Texture, gl_texture_attrib::Unit, VARYING_SLOT_POS, VARYING_SLOT_TEX0, and swrast_texture_image::WidthScale.
Referenced by shade_texture_span().
static void interpolate_wpos (struct gl_context * ctx, SWspan * span) inline static
Fill in the arrays->attribs[VARYING_SLOT_POS] array.
References gl_framebuffer::_DepthMaxF, sw_span::array, sw_span::arrayMask, sw_span_arrays::attribs, sw_span::attrStart, sw_span::attrStepX, gl_context::DrawBuffer, sw_span::end, sw_span::leftClip, SPAN_XY, VARYING_SLOT_POS, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, sw_span::y, and sw_span_arrays::z.
Referenced by shade_texture_span().
static void put_values (struct gl_context * ctx, struct gl_renderbuffer * rb, GLenum datatype, GLuint count, const GLint x[], const GLint y[], const void * values, const GLubyte * mask) static
Put colors at x/y locations into a renderbuffer.
References _mesa_get_pack_float_rgba_function(), _mesa_get_pack_ubyte_rgba_function(), _swrast_pixel_address(), gl_renderbuffer::Format, GLubyte, and NULL.
Referenced by _swrast_write_rgba_span().
static void shade_texture_span (struct gl_context * ctx, SWspan * span) inline static
Apply fragment shader, fragment program or normal texturing to span.
References gl_ati_fragment_shader_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, _swrast_exec_fragment_program(), _swrast_exec_fragment_shader(), _swrast_span_interpolate_z(), _swrast_texture_span(), _swrast_use_fragment_program(), sw_span::array, sw_span::arrayAttribs, sw_span::arrayMask, ASSERT, gl_context::ATIFragmentShader, sw_span_arrays::attribs, sw_span_arrays::ChanType, convert_color_type(), sw_span::interpMask, interpolate_active_attribs(), interpolate_int_colors(), interpolate_texcoords(), interpolate_wpos(), gl_context::Point, gl_point_attrib::PointSprite, sw_span::primitive, sw_span_arrays::rgba, SPAN_RGBA, SPAN_Z, gl_context::Texture, VARYING_BIT_COL0, VARYING_BIT_POS, VARYING_BITS_TEX_ANY, and VARYING_SLOT_COL0.
Referenced by _swrast_write_rgba_span().
static void stipple_polygon_span (struct gl_context * ctx, SWspan * span) inline static
Apply the current polygon stipple pattern to a span of pixels.
References sw_span::array, sw_span::arrayMask, ASSERT, sw_span::end, GLubyte, sw_span_arrays::mask, gl_context::Polygon, gl_context::PolygonStipple, SPAN_XY, gl_polygon_attrib::StippleFlag, sw_span::writeAll, sw_span_arrays::x, sw_span::x, sw_span_arrays::y, and sw_span::y.
Referenced by _swrast_write_rgba_span().