Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_texcombine.h File Reference
#include "s_span.h"
Functions
void _swrast_texture_span (struct gl_context *ctx, SWspan *span)
Apply texture mapping to a span of fragments.
Function Documentation
void _swrast_texture_span (struct gl_context * ctx, SWspan * span)
Apply texture mapping to a span of fragments.
References gl_texture_unit::_Current, gl_texture_unit::_CurrentCombine, _mesa_error(), gl_texture_unit::_ReallyEnabled, SWcontext::_TextureCombinePrimary, ACOMP, sw_span::array, sw_span::arrayMask, ASSERT, sw_span_arrays::attribs, BCOMP, gl_texture_unit::BumpTarget, CHAN_TO_FLOAT, CLAMP, gl_context::Const, sw_span::end, gl_constants::FragmentProgram, GCOMP, get_texel_array(), sw_span_arrays::lambda, gl_texture_unit::LodBias, gl_program_constants::MaxTextureImageUnits, gl_constants::MaxTextureLodBias, gl_constants::MaxTextureUnits, gl_tex_env_combine_state::ModeRGB, RCOMP, sw_span_arrays::rgba, gl_texture_unit::RotMatrix, SPAN_LAMBDA, swizzle_texels(), swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, SWcontext::TexelBuffer, gl_context::Texture, texture_combine(), SWcontext::TextureSample, gl_texture_attrib::Unit, and VARYING_SLOT_TEX0.
Referenced by shade_texture_span().