Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_texfilter.h File Reference
#include "s_context.h"
Functions
texture_sample_func _swrast_choose_texture_sample_func (struct gl_context *ctx, const struct gl_texture_object *tObj, const struct gl_sampler_object *sampler)
Choose the texture sampling function for the given texture object.
Function Documentation
texture_sample_func _swrast_choose_texture_sample_func (struct gl_context * ctx, const struct gl_texture_object * tObj, const struct gl_sampler_object * sampler)
Choose the texture sampling function for the given texture object.
References swrast_texture_image::_IsPowerOfTwo, _mesa_problem(), ASSERT, gl_texture_object::BaseLevel, gl_texture_image::Border, gl_texture_object::Image, is_depth_texture(), gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, MESA_FORMAT_RGB888, MESA_FORMAT_RGBA8888, gl_sampler_object::MinFilter, null_sample_func(), opt_sample_rgb_2d(), opt_sample_rgba_2d(), sample_depth_texture(), sample_lambda_1d(), sample_lambda_1d_array(), sample_lambda_2d(), sample_lambda_2d_aniso(), sample_lambda_2d_array(), sample_lambda_3d(), sample_lambda_cube(), sample_lambda_rect(), sample_linear_1d(), sample_linear_1d_array(), sample_linear_2d(), sample_linear_2d_array(), sample_linear_3d(), sample_linear_cube(), sample_linear_rect(), sample_nearest_1d(), sample_nearest_1d_array(), sample_nearest_2d(), sample_nearest_2d_array(), sample_nearest_3d(), sample_nearest_cube(), sample_nearest_rect(), swrast_texture_image_const(), gl_texture_object::Target, gl_texture_image::TexFormat, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _swrast_update_texture_samplers().