Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_texfetch_tmp.h File Reference
Functions
static void FETCH() f_z32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_z16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgba_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgba_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgb_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgb_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_alpha_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_alpha_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_luminance_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_luminance_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_luminance_alpha_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_luminance_alpha_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_intensity_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_intensity_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_r_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_r_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rg_f32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rg_f16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgba8888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgba8888_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_argb8888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_argb8888_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgbx8888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgbx8888_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_xrgb8888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_xrgb8888_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgb888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_bgr888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgb565 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgb565_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_argb4444 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_argb4444_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgba5551 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_argb1555 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_argb1555_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_argb2101010 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_gr88 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rg88 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_al44 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_al88 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_r8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_r16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_al88_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rg1616 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rg1616_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_al1616 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_al1616_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_rgb332 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_a8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_a16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_l8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_l16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_i8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_i16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() srgb8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() srgba8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() sargb8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() sl8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() sla8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgba_int8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgba_int16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgba_int32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgba_uint8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgba_uint16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgba_uint32 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() dudv8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_r8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_a8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_l8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_i8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_rg88_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_al88 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_rgbx8888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_rgba8888 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_rgba8888_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_r16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_a16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_l16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_i16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_rg1616 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_al1616 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_rgb_16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() signed_rgba_16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgba_16 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_ycbcr (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_ycbcr_rev (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_z24_s8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() f_s8_z24 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() rgb9_e5 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() r11_g11_b10f (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
static void FETCH() z32f_x24s8 (const struct swrast_texture_image *texImage, GLint i, GLint j, GLint k, GLfloat *texel)
Function Documentation
static void FETCH() dudv8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT, GCOMP, GLbyte, and RCOMP.
static void FETCH() f_a16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_a8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_al1616 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_al1616_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_al44 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, F, GCOMP, GLubyte, and RCOMP.
static void FETCH() f_al88 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_al88_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_alpha_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_alpha_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_argb1555 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
static void FETCH() f_argb1555_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_argb2101010 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_argb4444 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
static void FETCH() f_argb4444_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
static void FETCH() f_argb8888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_argb8888_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_bgr888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_gr88 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_i16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_i8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_intensity_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_intensity_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_l16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_l8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_luminance_alpha_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_luminance_alpha_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_luminance_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_luminance_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_r16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_r8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_r_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_r_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_rg1616 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_rg1616_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() f_rg88 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_rg_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_rg_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_rgb332 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
static void FETCH() f_rgb565 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
static void FETCH() f_rgb565_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_rgb888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_rgb_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_rgb_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_rgba5551 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
static void FETCH() f_rgba8888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_rgba8888_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_rgba_f16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_rgba_f32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() f_rgbx8888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_rgbx8888_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_s8_z24 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ASSERT, swrast_texture_image::Base, F, MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, and gl_texture_image::TexFormat.
static void FETCH() f_xrgb8888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_xrgb8888_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() f_ycbcr (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, CLAMP, F, GCOMP, GLubyte, GLushort, RCOMP, and y1.
static void FETCH() f_ycbcr_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, CLAMP, F, GCOMP, GLubyte, GLushort, RCOMP, and y1.
static void FETCH() f_z16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References GLushort.
static void FETCH() f_z24_s8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ASSERT, swrast_texture_image::Base, F, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, and gl_texture_image::TexFormat.
static void FETCH() f_z32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
static void FETCH() r11_g11_b10f (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP.
static void FETCH() rgb9_e5 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP.
static void FETCH() rgba_16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
static void FETCH() rgba_int16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
static void FETCH() rgba_int32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() rgba_int8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
static void FETCH() rgba_uint16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
static void FETCH() rgba_uint32 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
static void FETCH() rgba_uint8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
static void FETCH() sargb8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, nonlinear_to_linear(), RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() signed_a16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_a8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
static void FETCH() signed_al1616 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_al88 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, GLshort, GLushort, and RCOMP.
static void FETCH() signed_i16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_i8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
static void FETCH() signed_l16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_l8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
static void FETCH() signed_r16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_r8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
static void FETCH() signed_rg1616 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_rg88_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, GLshort, GLushort, and RCOMP.
static void FETCH() signed_rgb_16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_rgba8888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
static void FETCH() signed_rgba8888_rev (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
static void FETCH() signed_rgba_16 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
static void FETCH() signed_rgbx8888 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
static void FETCH() sl8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, nonlinear_to_linear(), and RCOMP.
static void FETCH() sla8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, nonlinear_to_linear(), RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() srgb8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, nonlinear_to_linear(), and RCOMP.
static void FETCH() srgba8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, nonlinear_to_linear(), RCOMP, and UBYTE_TO_FLOAT.
static void FETCH() z32f_x24s8 (const struct swrast_texture_image * texImage, GLint i, GLint j, GLint k, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, and RCOMP.