Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
s_texcombine.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/colormac.h"
#include "main/imports.h"
#include "main/pixeltransfer.h"
#include "main/samplerobj.h"
#include "program/prog_instruction.h"
#include "s_context.h"
#include "s_texcombine.h"
Typedefs
typedef float(* float4_array)[4]
Pointer to array of float[4] This type makes the code below more concise and avoids a lot of casting.
Functions
static float4_array get_texel_array (SWcontext *swrast, GLuint unit)
Return array of texels for given unit.
static void texture_combine (struct gl_context *ctx, GLuint unit, const float4_array primary_rgba, const GLfloat *texelBuffer, SWspan *span)
Do texture application for: GL_EXT_texture_env_combine GL_ARB_texture_env_combine GL_EXT_texture_env_dot3 GL_ARB_texture_env_dot3 GL_ATI_texture_env_combine3 GL_NV_texture_env_combine4 conventional GL texture env modes.
static void swizzle_texels (GLuint swizzle, GLuint count, float4_array texels)
Apply X/Y/Z/W/0/1 swizzle to an array of colors/texels.
void _swrast_texture_span (struct gl_context *ctx, SWspan *span)
Apply texture mapping to a span of fragments.
Typedef Documentation
typedef float(* float4_array)[4]
Pointer to array of float[4] This type makes the code below more concise and avoids a lot of casting.
Function Documentation
void _swrast_texture_span (struct gl_context * ctx, SWspan * span)
Apply texture mapping to a span of fragments.
References gl_texture_unit::_Current, gl_texture_unit::_CurrentCombine, _mesa_error(), gl_texture_unit::_ReallyEnabled, SWcontext::_TextureCombinePrimary, ACOMP, sw_span::array, sw_span::arrayMask, ASSERT, sw_span_arrays::attribs, BCOMP, gl_texture_unit::BumpTarget, CHAN_TO_FLOAT, CLAMP, gl_context::Const, sw_span::end, gl_constants::FragmentProgram, GCOMP, get_texel_array(), sw_span_arrays::lambda, gl_texture_unit::LodBias, gl_program_constants::MaxTextureImageUnits, gl_constants::MaxTextureLodBias, gl_constants::MaxTextureUnits, gl_tex_env_combine_state::ModeRGB, RCOMP, sw_span_arrays::rgba, gl_texture_unit::RotMatrix, SPAN_LAMBDA, swizzle_texels(), swrast, SWRAST_CONTEXT(), SWRAST_MAX_WIDTH, SWcontext::TexelBuffer, gl_context::Texture, texture_combine(), SWcontext::TextureSample, gl_texture_attrib::Unit, and VARYING_SLOT_TEX0.
Referenced by shade_texture_span().
static float4_array get_texel_array (SWcontext * swrast, GLuint unit) inline static
Return array of texels for given unit.
References SWRAST_MAX_WIDTH, and SWcontext::TexelBuffer.
Referenced by _swrast_texture_span(), and texture_combine().
static void swizzle_texels (GLuint swizzle, GLuint count, float4_array texels) static
Apply X/Y/Z/W/0/1 swizzle to an array of colors/texels.
See GL_EXT_texture_swizzle.
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _swrast_texture_span().
static void texture_combine (struct gl_context * ctx, GLuint unit, const float4_array primary_rgba, const GLfloat * texelBuffer, SWspan * span) static
Do texture application for: GL_EXT_texture_env_combine GL_ARB_texture_env_combine GL_EXT_texture_env_dot3 GL_ARB_texture_env_dot3 GL_ATI_texture_env_combine3 GL_NV_texture_env_combine4 conventional GL texture env modes.
Parameters
ctx rendering context
unit the texture combiner unit
primary_rgba incoming fragment color array
texelBuffer pointer to texel colors for all texture units
span two fields are used in this function: span->end: number of fragments to process span->array->rgba: incoming/result fragment colors
References gl_texture_unit::_CurrentCombine, _mesa_error(), _mesa_problem(), gl_tex_env_combine_state::_NumArgsA, gl_tex_env_combine_state::_NumArgsRGB, gl_texture_unit::_ReallyEnabled, ACOMP, sw_span::array, ASSERT, ASSIGN_4V, BCOMP, CHAN_TO_FLOAT, CHAN_TYPE, sw_span_arrays::ChanType, CLAMP, sw_span::end, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, F, GCOMP, get_texel_array(), MAX_COMBINER_TERMS, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, RCOMP, sw_span_arrays::rgba, gl_tex_env_combine_state::ScaleShiftA, gl_tex_env_combine_state::ScaleShiftRGB, gl_tex_env_combine_state::SourceA, gl_tex_env_combine_state::SourceRGB, swrast, SWRAST_CONTEXT(), gl_context::Texture, UNCLAMPED_FLOAT_TO_CHAN, and gl_texture_attrib::Unit.
Referenced by _swrast_texture_span().