Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ss_tritmp.h File Reference
Functions
static void TAG() triangle (struct gl_context *ctx, GLuint e0, GLuint e1, GLuint e2)
This is where we handle assigning vertex colors based on front/back facing, compute polygon offset and handle glPolygonMode().
static void TAG() quadfunc (struct gl_context *ctx, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
static void TAG() init (void)
Function Documentation
static void TAG() init (void) static
References IND, quad_tab, quadfunc(), TAG, tri_tab, triangle(), and void.
static void TAG() quadfunc (struct gl_context * ctx, GLuint v0, GLuint v1, GLuint v2, GLuint v3) static
References vertex_buffer::EdgeFlag, GLubyte, IND, SS_UNFILLED_BIT, TAG, TNL_CONTEXT, and triangle().
Referenced by init().
static void TAG() triangle (struct gl_context * ctx, GLuint e0, GLuint e1, GLuint e2) static
This is where we handle assigning vertex colors based on front/back facing, compute polygon offset and handle glPolygonMode().
References gl_framebuffer::_DepthMaxF, gl_polygon_attrib::_FrontBit, _swrast_Triangle(), _swsetup_edge_render_line_tri(), _swsetup_edge_render_point_tri(), _swsetup_render_tri(), SWvertex::attrib, vertex_buffer::BackfaceColorPtr, vertex_buffer::BackfaceSecondaryColorPtr, gl_polygon_attrib::BackMode, CLAMP, COPY_4V, COPY_CHAN4, GLvector4f::data, gl_context::DrawBuffer, F, FABSF, facing, gl_polygon_attrib::FrontMode, IND, SScontext::intColors, MAX2, gl_polygon_attrib::OffsetFactor, gl_polygon_attrib::OffsetFill, gl_polygon_attrib::OffsetLine, gl_polygon_attrib::OffsetPoint, gl_polygon_attrib::OffsetUnits, gl_context::Polygon, SS_COLOR, SS_OFFSET_BIT, SS_SPEC, SS_TWOSIDE_BIT, SS_UNFILLED_BIT, GLvector4f::stride, SWSETUP_CONTEXT, TNL_CONTEXT, VARYING_SLOT_COL0, VARYING_SLOT_COL1, and VARYING_SLOT_POS.
Referenced by init(), and quadfunc().