Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
backend.c File Reference
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <dlfcn.h>
#include "backend.h"
Data Structures
struct backend_desc
Macros
#define ARRAY_SIZE(a) (sizeof(a)/sizeof((a)[0]))
Functions
static const void * load_backend (const struct backend_desc *backend)
static struct backend_desc * find_backend (const char *name)
struct gbm_device * _gbm_create_device (int fd)
Variables
struct gbm_backend gbm_dri_backend
static struct backend_desc backends []
Macro Definition Documentation
#define ARRAY_SIZE (a) (sizeof(a)/sizeof((a)[0]))
Referenced by _gbm_create_device(), and find_backend().
Function Documentation
struct gbm_device* _gbm_create_device (int fd) read
References ARRAY_SIZE, gbm_backend::create_device, find_backend(), load_backend(), and NULL.
Referenced by gbm_create_device().
static struct backend_desc* find_backend (const char * name) static read
References ARRAY_SIZE, and NULL.
Referenced by _gbm_create_device().
static const void* load_backend (const struct backend_desc * backend) static
References backend_desc::builtin, backend_desc::name, and NULL.
Referenced by _gbm_create_device().
Variable Documentation
struct backend_desc backends[] static
Initial value:
= {
   { "gbm_dri.so", &gbm_dri_backend },
   { "gbm_gallium_drm.so", NULL },
}
struct gbm_backend gbm_dri_backend