Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
gbm_device Struct Reference
The device used for the memory allocation.
#include <gbmint.h>
Data Fields
struct gbm_device *(* dummy)(int)
int fd
const char * name
unsigned int refcount
struct stat stat
void(* destroy)(struct gbm_device *gbm)
int(* is_format_supported)(struct gbm_device *gbm, uint32_t format, uint32_t usage)
struct gbm_bo *(* bo_create)(struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t usage)
struct gbm_bo *(* bo_import)(struct gbm_device *gbm, uint32_t type, void *buffer, uint32_t usage)
int(* bo_write)(struct gbm_bo *bo, const void *buf, size_t data)
void(* bo_destroy)(struct gbm_bo *bo)
struct gbm_surface *(* surface_create)(struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags)
struct gbm_bo *(* surface_lock_front_buffer)(struct gbm_surface *surface)
void(* surface_release_buffer)(struct gbm_surface *surface, struct gbm_bo *bo)
int(* surface_has_free_buffers)(struct gbm_surface *surface)
void(* surface_destroy)(struct gbm_surface *surface)
Detailed Description
The device used for the memory allocation.
The members of this structure should be not accessed directly
Field Documentation
struct gbm_bo*(* gbm_device::bo_create)(struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t usage) read
Referenced by gbm_bo_create().
void(* gbm_device::bo_destroy)(struct gbm_bo *bo)
Referenced by gbm_bo_destroy().
struct gbm_bo*(* gbm_device::bo_import)(struct gbm_device *gbm, uint32_t type, void *buffer, uint32_t usage) read
Referenced by gbm_bo_import().
int(* gbm_device::bo_write)(struct gbm_bo *bo, const void *buf, size_t data)
Referenced by gbm_bo_write().
void(* gbm_device::destroy)(struct gbm_device *gbm)
Referenced by gbm_device_destroy().
struct gbm_device*(* gbm_device::dummy)(int) read
Referenced by gbm_create_device().
int gbm_device::fd
Referenced by gbm_device_get_fd().
int(* gbm_device::is_format_supported)(struct gbm_device *gbm, uint32_t format, uint32_t usage)
Referenced by gbm_device_is_format_supported().
const char* gbm_device::name
Referenced by gbm_device_get_backend_name().
unsigned int gbm_device::refcount
Referenced by _gbm_mesa_get_device(), gbm_create_device(), and gbm_device_destroy().
struct stat gbm_device::stat
Referenced by _gbm_mesa_get_device(), and gbm_create_device().
struct gbm_surface*(* gbm_device::surface_create)(struct gbm_device *gbm, uint32_t width, uint32_t height, uint32_t format, uint32_t flags) read
Referenced by gbm_surface_create().
void(* gbm_device::surface_destroy)(struct gbm_surface *surface)
Referenced by gbm_surface_destroy().
int(* gbm_device::surface_has_free_buffers)(struct gbm_surface *surface)
Referenced by gbm_surface_has_free_buffers().
struct gbm_bo*(* gbm_device::surface_lock_front_buffer)(struct gbm_surface *surface) read
Referenced by gbm_surface_lock_front_buffer().
void(* gbm_device::surface_release_buffer)(struct gbm_surface *surface, struct gbm_bo *bo)
Referenced by gbm_surface_release_buffer().
The documentation for this struct was generated from the following file:
gbmint.h