Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
t_draw.c File Reference
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/condrender.h"
#include "main/context.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/enums.h"
#include "t_context.h"
#include "tnl.h"
Macros
#define CONVERT(TYPE, MACRO)
#define CLIPVERTS ((6 + MAX_CLIP_PLANES) * 2)
Functions
static GLubyte * get_space (struct gl_context *ctx, GLuint bytes)
static void free_space (struct gl_context *ctx)
static void convert_bgra_to_float (const struct gl_client_array *input, const GLubyte *ptr, GLfloat *fptr, GLuint count)
Convert array of BGRA/GLubyte[4] values to RGBA/float[4].
static void convert_half_to_float (const struct gl_client_array *input, const GLubyte *ptr, GLfloat *fptr, GLuint count, GLuint sz)
static void convert_fixed_to_float (const struct gl_client_array *input, const GLubyte *ptr, GLfloat *fptr, GLuint count)
Convert fixed-point to floating-point.
static void _tnl_import_array (struct gl_context *ctx, GLuint attrib, GLuint count, const struct gl_client_array *input, const GLubyte *ptr)
static GLboolean * _tnl_import_edgeflag (struct gl_context *ctx, const GLvector4f *input, GLuint count)
static void bind_inputs (struct gl_context *ctx, const struct gl_client_array *inputs[], GLint count, struct gl_buffer_object **bo, GLuint *nr_bo)
static void bind_indices (struct gl_context *ctx, const struct _mesa_index_buffer *ib, struct gl_buffer_object **bo, GLuint *nr_bo)
static void bind_prims (struct gl_context *ctx, const struct _mesa_prim *prim, GLuint nr_prims)
static void unmap_vbos (struct gl_context *ctx, struct gl_buffer_object **bo, GLuint nr_bo)
void _tnl_vbo_draw_prims (struct gl_context *ctx, const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *tfb_vertcount)
void _tnl_draw_prims (struct gl_context *ctx, const struct gl_client_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index)
Macro Definition Documentation
#define CLIPVERTS ((6 + MAX_CLIP_PLANES) * 2)
Referenced by _tnl_import_edgeflag().
#define CONVERT (TYPE, MACRO)
Value:
do {            \
   GLuint i, j;                                 \
   if (input->Normalized) {                     \
      for (i = 0; i < count; i++) {             \
         const TYPE *in = (TYPE *)ptr;          \
         for (j = 0; j < sz; j++) {             \
            *fptr++ = MACRO(*in);               \
        in++;                              \
         }                                      \
         ptr += input->StrideB;                 \
      }                                         \
   } else {                                     \
      for (i = 0; i < count; i++) {             \
         const TYPE *in = (TYPE *)ptr;          \
         for (j = 0; j < sz; j++) {             \
            *fptr++ = (GLfloat)(*in);           \
        in++;                              \
         }                                      \
         ptr += input->StrideB;                 \
      }                                         \
   }                                            \
} while (0)
Referenced by _tnl_import_array().
Function Documentation
void _tnl_draw_prims (struct gl_context * ctx, const struct gl_client_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index)
References __FUNCTION__, _mesa_check_conditional_render(), _mesa_lookup_enum_by_nr(), _tnl_vbo_draw_prims(), _mesa_prim::basevertex, bind_indices(), bind_inputs(), bind_prims(), TNLcontext::CurInstance, free_space(), MAX2, MAX_CLIPPED_VERTICES, split_limits::max_indices, split_limits::max_vb_size, split_limits::max_verts, gl_context::NewState, _mesa_prim::num_instances, vertex_buffer::Size, TNL_CONTEXT, unmap_vbos(), TNLcontext::vb, vbo_rebase_prims(), vbo_split_prims(), and VERT_ATTRIB_MAX.
Referenced by _tnl_vbo_draw_prims().
static void _tnl_import_array (struct gl_context * ctx, GLuint attrib, GLuint count, const struct gl_client_array * input, const GLubyte * ptr) static
References vertex_buffer::AttribPtr, BYTE_TO_FLOAT, CONVERT, convert_bgra_to_float(), convert_fixed_to_float(), convert_half_to_float(), GLvector4f::count, GLvector4f::data, GLvector4f::flags, gl_client_array::Format, get_space(), GLbyte, GLshort, GLubyte, GLushort, INT_TO_FLOAT, NULL, SHORT_TO_FLOAT, gl_client_array::Size, GLvector4f::size, GLvector4f::start, GLvector4f::storage, GLvector4f::stride, gl_client_array::StrideB, TNLcontext::tmp_inputs, TNL_CONTEXT, gl_client_array::Type, UBYTE_TO_FLOAT, UINT_TO_FLOAT, USHORT_TO_FLOAT, TNLcontext::vb, VEC_BAD_STRIDE, and VEC_NOT_WRITEABLE.
Referenced by bind_inputs().
static GLboolean* _tnl_import_edgeflag (struct gl_context * ctx, const GLvector4f * input, GLuint count) static
References CLIPVERTS, GLvector4f::data, get_space(), GLubyte, and GLvector4f::stride.
Referenced by bind_inputs().
void _tnl_vbo_draw_prims (struct gl_context * ctx, const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object * tfb_vertcount)
References gl_array_attrib::_DrawArrays, _tnl_draw_prims(), gl_context::Array, and vbo_get_minmax_indices().
Referenced by _tnl_CreateContext(), and _tnl_draw_prims().
static void bind_indices (struct gl_context * ctx, const struct _mesa_index_buffer * ib, struct gl_buffer_object ** bo, GLuint * nr_bo) static
References ADD_POINTERS, _mesa_prim::basevertex, _mesa_index_buffer::count, gl_context::Driver, vertex_buffer::Elts, get_space(), GLsizeiptr, GLubyte, GLushort, dd_function_table::MapBufferRange, NULL, _mesa_index_buffer::obj, gl_buffer_object::Pointer, vertex_buffer::Primitive, _mesa_index_buffer::ptr, TNL_CONTEXT, _mesa_index_buffer::type, and TNLcontext::vb.
Referenced by _tnl_draw_prims().
static void bind_inputs (struct gl_context * ctx, const struct gl_client_array * inputs[], GLint count, struct gl_buffer_object ** bo, GLuint * nr_bo) static
References _TNL_ATTRIB_EDGEFLAG, _tnl_import_array(), _tnl_import_edgeflag(), ADD_POINTERS, vertex_buffer::AttribPtr, vertex_buffer::BackfaceColorPtr, vertex_buffer::BackfaceIndexPtr, vertex_buffer::BackfaceSecondaryColorPtr, gl_polygon_attrib::BackMode, gl_client_array::BufferObj, vertex_buffer::Count, gl_context::Driver, vertex_buffer::EdgeFlag, gl_polygon_attrib::FrontMode, dd_function_table::MapBufferRange, NULL, gl_context::Polygon, gl_client_array::Ptr, gl_client_array::Size, TNL_CONTEXT, TNLcontext::vb, and VERT_ATTRIB_MAX.
Referenced by _tnl_draw_prims().
static void bind_prims (struct gl_context * ctx, const struct _mesa_prim * prim, GLuint nr_prims) static
References vertex_buffer::Primitive, vertex_buffer::PrimitiveCount, TNL_CONTEXT, and TNLcontext::vb.
Referenced by _tnl_draw_prims().
static void convert_bgra_to_float (const struct gl_client_array * input, const GLubyte * ptr, GLfloat * fptr, GLuint count) static
Convert array of BGRA/GLubyte[4] values to RGBA/float[4].
Parameters
ptr input/ubyte array
fptr output/float array
References GLubyte, gl_client_array::Normalized, gl_client_array::Size, gl_client_array::StrideB, and UBYTE_TO_FLOAT.
Referenced by _tnl_import_array().
static void convert_fixed_to_float (const struct gl_client_array * input, const GLubyte * ptr, GLfloat * fptr, GLuint count) static
Convert fixed-point to floating-point.
In OpenGL, a fixed-point number is a "signed 2's complement 16.16 scaled integer" (Table 2.2 of the OpenGL ES 2.0 spec).
If the buffer has the normalized flag set, the formula
normalize(x) := (2*x + 1) / (2^16 - 1)
is used to map the fixed-point numbers into the range [-1, 1].
References gl_client_array::Normalized, gl_client_array::Size, and gl_client_array::StrideB.
Referenced by _tnl_import_array().
static void convert_half_to_float (const struct gl_client_array * input, const GLubyte * ptr, GLfloat * fptr, GLuint count, GLuint sz) static
References _mesa_half_to_float(), and gl_client_array::StrideB.
Referenced by _tnl_import_array().
static void free_space (struct gl_context * ctx) static
References TNLcontext::block, TNLcontext::nr_blocks, and TNL_CONTEXT.
Referenced by _tnl_draw_prims().
static GLubyte* get_space (struct gl_context * ctx, GLuint bytes) static
References TNLcontext::block, GLubyte, TNLcontext::nr_blocks, and TNL_CONTEXT.
Referenced by _tnl_import_array(), _tnl_import_edgeflag(), and bind_indices().
static void unmap_vbos (struct gl_context * ctx, struct gl_buffer_object ** bo, GLuint nr_bo) static
References gl_context::Driver, and dd_function_table::UnmapBuffer.
Referenced by _tnl_draw_prims().