Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
t_rasterpos.c File Reference
#include "main/glheader.h"
#include "main/colormac.h"
#include "main/feedback.h"
#include "main/light.h"
#include "main/macros.h"
#include "main/simple_list.h"
#include "main/mtypes.h"
#include "math/m_matrix.h"
#include "tnl/tnl.h"
Functions
static GLuint viewclip_point_xy (const GLfloat v[])
Clip a point against the view volume.
static GLuint viewclip_point_z (const GLfloat v[])
Clip a point against the far/near Z clipping planes.
static GLuint userclip_point (struct gl_context *ctx, const GLfloat v[])
Clip a point against the user clipping planes.
static void shade_rastpos (struct gl_context *ctx, const GLfloat vertex[4], const GLfloat normal[3], GLfloat Rcolor[4], GLfloat Rspec[4])
Compute lighting for the raster position.
static void compute_texgen (struct gl_context *ctx, const GLfloat vObj[4], const GLfloat vEye[4], const GLfloat normal[3], GLuint unit, GLfloat texcoord[4])
Do texgen needed for glRasterPos.
void _tnl_RasterPos (struct gl_context *ctx, const GLfloat vObj[4])
glRasterPos transformation.
Function Documentation
void _tnl_RasterPos (struct gl_context * ctx, const GLfloat vObj[4])
glRasterPos transformation.
Typically called via ctx->Driver.RasterPos(). XXX some of this code (such as viewport xform, clip testing and setting of ctx->Current.Raster* fields) could get lifted up into the main/rasterpos.c code.
Parameters
vObj vertex position in object space
References gl_framebuffer::_DepthMaxF, gl_vertex_program_state::_Enabled, _mesa_problem(), _mesa_update_hitflag(), gl_context::_NeedEyeCoords, gl_viewport_attrib::_WindowMap, gl_current_attrib::Attrib, CLAMP, gl_transform_attrib::ClipPlanesEnabled, compute_texgen(), gl_context::Const, COPY_4V, gl_context::Current, gl_transform_attrib::DepthClamp, gl_context::DrawBuffer, gl_light_attrib::Enabled, F, gl_viewport_attrib::Far, gl_context::Fog, gl_fog_attrib::FogCoordinateSource, if(), GLmatrix::inv, gl_context::Light, GLmatrix::m, MAT_SX, MAT_SY, MAT_SZ, MAT_TX, MAT_TY, MAT_TZ, gl_constants::MaxTextureCoordUnits, gl_context::ModelviewMatrixStack, gl_viewport_attrib::Near, gl_context::ProjectionMatrixStack, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_transform_attrib::RasterPositionUnclipped, gl_current_attrib::RasterPosValid, gl_current_attrib::RasterSecondaryColor, gl_current_attrib::RasterTexCoords, gl_context::RenderMode, shade_rastpos(), sqrtf, gl_texture_unit::TexGenEnabled, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, gl_context::Transform, TRANSFORM_NORMAL, TRANSFORM_POINT, gl_texture_attrib::Unit, userclip_point(), VERT_ATTRIB_COLOR0, VERT_ATTRIB_COLOR1, VERT_ATTRIB_FOG, VERT_ATTRIB_NORMAL, VERT_ATTRIB_TEX0, gl_context::VertexProgram, viewclip_point_xy(), viewclip_point_z(), and gl_context::Viewport.
static void compute_texgen (struct gl_context * ctx, const GLfloat vObj[4], const GLfloat vEye[4], const GLfloat normal[3], GLuint unit, GLfloat texcoord[4]) static
Do texgen needed for glRasterPos.
Parameters
ctx rendering context
vObj object-space vertex coordinate
vEye eye-space vertex coordinate
normal vertex normal
unit texture unit number
texcoord incoming texcoord and resulting texcoord
References _mesa_problem(), COPY_3V, gl_texgen::EyePlane, F, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, gl_texgen::Mode, gl_texgen::ObjectPlane, Q_BIT, R_BIT, S_BIT, T_BIT, gl_texture_unit::TexGenEnabled, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _tnl_RasterPos().
static void shade_rastpos (struct gl_context * ctx, const GLfloat vertex[4], const GLfloat normal[3], GLfloat Rcolor[4], GLfloat Rspec[4]) static
Compute lighting for the raster position.
RGB modes computed.
Parameters
ctx the context
vertex vertex location
normal normal vector
Rcolor returned color
Rspec returned specular color (if separate specular enabled)
References gl_light_attrib::_BaseColor, gl_light::_CosCutoff, gl_context::_EyeZDir, gl_light::_Flags, gl_light::_h_inf_norm, gl_light::_MatAmbient, gl_light::_MatDiffuse, gl_light::_MatSpecular, gl_light::_NormSpotDirection, gl_light::_Position, gl_light::_VP_inf_norm, gl_light::_VP_inf_spot_attenuation, ACC_3V, ACC_SCALE_SCALAR_3V, ASSIGN_3V, ASSIGN_4V, gl_material::Attrib, CLAMP, gl_lightmodel::ColorControl, gl_light::ConstantAttenuation, COPY_3V, gl_light_attrib::EnabledList, F, gl_context::Light, LIGHT_POSITIONAL, LIGHT_SPOT, gl_light::LinearAttenuation, gl_lightmodel::LocalViewer, MAT_ATTRIB_FRONT_DIFFUSE, MAT_ATTRIB_FRONT_SHININESS, gl_light_attrib::Material, gl_light_attrib::Model, powf, gl_light::QuadraticAttenuation, SELF_SCALE_SCALAR_3V, gl_light::SpotExponent, and SUB_3V.
Referenced by _tnl_RasterPos().
static GLuint userclip_point (struct gl_context * ctx, const GLfloat v[]) static
Clip a point against the user clipping planes.
Parameters
ctx GL context.
v vertex vector describing the point to clip.
Returns
zero if the point was clipped, or one otherwise.
References gl_transform_attrib::_ClipUserPlane, gl_transform_attrib::ClipPlanesEnabled, gl_context::Const, F, gl_constants::MaxClipPlanes, and gl_context::Transform.
Referenced by _tnl_RasterPos().
static GLuint viewclip_point_xy (const GLfloat v[]) static
Clip a point against the view volume.
Parameters
v vertex vector describing the point to clip.
Returns
zero if outside view volume, or one if inside.
Referenced by _tnl_RasterPos().
static GLuint viewclip_point_z (const GLfloat v[]) static
Clip a point against the far/near Z clipping planes.
Parameters
v vertex vector describing the point to clip.
Returns
zero if outside view volume, or one if inside.
Referenced by _tnl_RasterPos().