Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
t_vb_program.c File Reference
Pipeline stage for executing vertex programs.
#include "main/glheader.h"
#include "main/colormac.h"
#include "main/macros.h"
#include "main/imports.h"
#include "main/samplerobj.h"
#include "math/m_xform.h"
#include "program/prog_instruction.h"
#include "program/prog_statevars.h"
#include "program/prog_execute.h"
#include "swrast/s_context.h"
#include "tnl/tnl.h"
#include "tnl/t_context.h"
#include "tnl/t_pipeline.h"
Data Structures
struct vp_stage_data
Macros
#define VP_STAGE_DATA(stage) ((struct vp_stage_data *)(stage->privatePtr))
Functions
static void userclip (struct gl_context *ctx, GLvector4f *clip, GLubyte *clipmask, GLubyte *clipormask, GLubyte *clipandmask)
static GLboolean do_ndc_cliptest (struct gl_context *ctx, struct vp_stage_data *store)
static void vp_fetch_texel (struct gl_context *ctx, const GLfloat texcoord[4], GLfloat lambda, GLuint unit, GLfloat color[4])
XXX the texture sampling code in this module is a bit of a hack.
GLboolean _tnl_program_string (struct gl_context *ctx, GLenum target, struct gl_program *program)
Called via ctx->Driver.ProgramStringNotify() after a new vertex program string has been parsed.
static void init_machine (struct gl_context *ctx, struct gl_program_machine *machine, GLuint instID)
Initialize virtual machine state prior to executing vertex program.
static void map_textures (struct gl_context *ctx, const struct gl_vertex_program *vp)
Map the texture images which the vertex program will access (if any).
static void unmap_textures (struct gl_context *ctx, const struct gl_vertex_program *vp)
Unmap the texture images which were used by the vertex program (if any).
static GLboolean run_vp (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
This function executes vertex programs.
static GLboolean init_vp (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
Called the first time stage->run is called.
static void dtr (struct tnl_pipeline_stage *stage)
Destructor for this pipeline stage.
static void validate_vp_stage (struct gl_context *ctx, struct tnl_pipeline_stage *stage)
Variables
struct tnl_pipeline_stage _tnl_vertex_program_stage
Public description of this pipeline stage.
Detailed Description
Pipeline stage for executing vertex programs.
Author
Brian Paul, Keith Whitwell
Macro Definition Documentation
#define VP_STAGE_DATA (stage) ((struct vp_stage_data *)(stage->privatePtr))
Referenced by dtr(), init_vp(), and run_vp().
Function Documentation
GLboolean _tnl_program_string (struct gl_context * ctx, GLenum target, struct gl_program * program)
Called via ctx->Driver.ProgramStringNotify() after a new vertex program string has been parsed.
static GLboolean do_ndc_cliptest (struct gl_context * ctx, struct vp_stage_data * store) static
XXX NEW_SLANG _Enabled ???
References gl_vertex_program_state::_Enabled, _mesa_clip_np_tab, _mesa_clip_tab, vp_stage_data::andmask, CLIP_FRUSTUM_BITS, vertex_buffer::ClipAndMask, vp_stage_data::clipmask, vertex_buffer::ClipMask, vertex_buffer::ClipOrMask, gl_transform_attrib::ClipPlanesEnabled, vertex_buffer::ClipPtr, gl_vertex_program_state::Current, gl_transform_attrib::DepthClamp, gl_vertex_program::IsPositionInvariant, vp_stage_data::ndcCoords, vertex_buffer::NdcPtr, TNLcontext::NeedNdcCoords, NULL, vp_stage_data::ormask, GLvector4f::size, tnl_clip_prepare(), TNL_CONTEXT, gl_context::Transform, userclip(), TNLcontext::vb, and gl_context::VertexProgram.
Referenced by run_vp().
static void dtr (struct tnl_pipeline_stage * stage) static
Destructor for this pipeline stage.
References _mesa_align_free(), _mesa_vector4f_free(), vp_stage_data::clipmask, vp_stage_data::ndcCoords, NULL, tnl_pipeline_stage::privatePtr, vp_stage_data::results, VARYING_SLOT_MAX, and VP_STAGE_DATA.
static void init_machine (struct gl_context * ctx, struct gl_program_machine * machine, GLuint instID) static
Initialize virtual machine state prior to executing vertex program.
References gl_vertex_program_state::_Current, gl_current_attrib::Attrib, gl_vertex_program::Base, gl_context::Current, MAX_VERTEX_GENERIC_ATTRIBS, NULL, gl_program::SamplerUnits, SYSTEM_VALUE_INSTANCE_ID, gl_context::VertexProgram, and vp_fetch_texel().
Referenced by run_vp().
static GLboolean init_vp (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
Called the first time stage->run is called.
In effect, don't allocate data until the first time the stage is run.
References _mesa_align_malloc(), _mesa_vector4f_alloc(), vp_stage_data::clipmask, GLubyte, vp_stage_data::ndcCoords, tnl_pipeline_stage::privatePtr, vertex_buffer::Size, TNL_CONTEXT, TNLcontext::vb, and VP_STAGE_DATA.
static void map_textures (struct gl_context * ctx, const struct gl_vertex_program * vp) static
Map the texture images which the vertex program will access (if any).
References gl_texture_unit::_Current, _swrast_map_texture(), gl_vertex_program::Base, gl_context::Const, gl_program_constants::MaxTextureImageUnits, gl_context::Texture, gl_program::TexturesUsed, gl_texture_attrib::Unit, and gl_constants::VertexProgram.
Referenced by run_vp().
static GLboolean run_vp (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
This function executes vertex programs.
References gl_vertex_program_state::_Current, _mesa_vector4f_alloc(), _mesa_vector4f_clean_elem(), gl_context::_ModelProjectMatrix, _TNL_ATTRIB_POINTSIZE, _TNL_ATTRIB_TEX0, ASSERT, vertex_buffer::AttribPtr, vertex_buffer::BackfaceColorPtr, vertex_buffer::BackfaceSecondaryColorPtr, gl_vertex_program::Base, BITFIELD64_BIT, vertex_buffer::ClipPtr, gl_context::Const, COPY_4V, COPY_CLEAN_4V, GLvector4f::count, vertex_buffer::Count, TNLcontext::CurInstance, GLvector4f::data, do_ndc_cliptest(), GLubyte, init_machine(), gl_program::InputsRead, gl_vertex_program::IsPositionInvariant, vp_stage_data::machine, map_textures(), gl_constants::MaxTextureCoordUnits, gl_constants::MaxVarying, gl_program::OutputsWritten, gl_program::Parameters, vp_stage_data::results, GLvector4f::size, vertex_buffer::Size, GLvector4f::storage, GLvector4f::stride, TNL_CONTEXT, TransformRaw, unmap_textures(), VARYING_SLOT_BFC0, VARYING_SLOT_BFC1, VARYING_SLOT_COL0, VARYING_SLOT_COL1, VARYING_SLOT_FOGC, VARYING_SLOT_MAX, VARYING_SLOT_POS, VARYING_SLOT_PSIZ, VARYING_SLOT_TEX0, VARYING_SLOT_VAR0, TNLcontext::vb, VERT_ATTRIB_COLOR0, VERT_ATTRIB_COLOR1, VERT_ATTRIB_FOG, VERT_ATTRIB_GENERIC0, VERT_ATTRIB_MAX, gl_context::VertexProgram, and VP_STAGE_DATA.
static void unmap_textures (struct gl_context * ctx, const struct gl_vertex_program * vp) static
Unmap the texture images which were used by the vertex program (if any).
References gl_texture_unit::_Current, _swrast_unmap_texture(), gl_vertex_program::Base, gl_context::Const, gl_program_constants::MaxTextureImageUnits, gl_context::Texture, gl_program::TexturesUsed, gl_texture_attrib::Unit, and gl_constants::VertexProgram.
Referenced by run_vp().
static void userclip (struct gl_context * ctx, GLvector4f * clip, GLubyte * clipmask, GLubyte * clipormask, GLubyte * clipandmask) static
References gl_transform_attrib::_ClipUserPlane, CLIP_USER_BIT, gl_transform_attrib::ClipPlanesEnabled, gl_context::Const, GLvector4f::count, GLvector4f::data, for(), gl_constants::MaxClipPlanes, GLvector4f::stride, STRIDE_F, and gl_context::Transform.
Referenced by do_ndc_cliptest().
static void validate_vp_stage (struct gl_context * ctx, struct tnl_pipeline_stage * stage) static
References gl_vertex_program_state::_Current, _swrast_update_texture_samplers(), and gl_context::VertexProgram.
static void vp_fetch_texel (struct gl_context * ctx, const GLfloat texcoord[4], GLfloat lambda, GLuint unit, GLfloat color[4]) static
XXX the texture sampling code in this module is a bit of a hack.
The texture sampling code is in swrast, though it doesn't have any real dependencies on the rest of swrast. It should probably be moved into main/ someday.
References gl_texture_unit::_Current, swrast, gl_context::Texture, SWcontext::TextureSample, and gl_texture_attrib::Unit.
Referenced by init_machine().
Variable Documentation
struct tnl_pipeline_stage _tnl_vertex_program_stage
Initial value:
=
{
   "vertex-program",
   NULL,
   init_vp,
   dtr,
   validate_vp_stage,
   run_vp
}
Public description of this pipeline stage.