Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
t_vertex.h File Reference
#include "main/glheader.h"
#include "t_context.h"
Data Structures
struct tnl_attr_map
struct tnl_format_info
Macros
#define GET_VERTEX_STATE(ctx) &(TNL_CONTEXT(ctx)->clipspace)
Enumerations
enum tnl_attr_format {
EMIT_1F, EMIT_2F, EMIT_3F, EMIT_4F,
EMIT_2F_VIEWPORT, EMIT_3F_VIEWPORT, EMIT_4F_VIEWPORT, EMIT_3F_XYW,
EMIT_1UB_1F, EMIT_3UB_3F_RGB, EMIT_3UB_3F_BGR, EMIT_4UB_4F_RGBA,
EMIT_4UB_4F_BGRA, EMIT_4UB_4F_ARGB, EMIT_4UB_4F_ABGR, EMIT_4CHAN_4F_RGBA,
EMIT_PAD, EMIT_MAX
}
Functions
void _tnl_interp (struct gl_context *ctx, GLfloat t, GLuint edst, GLuint eout, GLuint ein, GLboolean force_boundary)
void _tnl_copy_pv (struct gl_context *ctx, GLuint edst, GLuint esrc)
void _tnl_get_attr (struct gl_context *ctx, const void *vertex, GLenum attrib, GLfloat *dest)
void _tnl_set_attr (struct gl_context *ctx, void *vout, GLenum attrib, const GLfloat *src)
void * _tnl_get_vertex (struct gl_context *ctx, GLuint nr)
GLuint _tnl_install_attrs (struct gl_context *ctx, const struct tnl_attr_map *map, GLuint nr, const GLfloat *vp, GLuint unpacked_size)
void _tnl_free_vertices (struct gl_context *ctx)
void _tnl_init_vertices (struct gl_context *ctx, GLuint vb_size, GLuint max_vertex_size)
void * _tnl_emit_vertices_to_buffer (struct gl_context *ctx, GLuint start, GLuint end, void *dest)
void * _tnl_emit_indexed_vertices_to_buffer (struct gl_context *ctx, const GLuint *elts, GLuint start, GLuint end, void *dest)
void _tnl_build_vertices (struct gl_context *ctx, GLuint start, GLuint end, GLuint newinputs)
void _tnl_invalidate_vertices (struct gl_context *ctx, GLuint newinputs)
void _tnl_invalidate_vertex_state (struct gl_context *ctx, GLuint new_state)
void _tnl_notify_pipeline_output_change (struct gl_context *ctx)
void _tnl_register_fastpath (struct tnl_clipspace *vtx, GLboolean match_strides)
void _tnl_generic_copy_pv_extras (struct gl_context *ctx, GLuint dst, GLuint src)
void _tnl_generic_interp_extras (struct gl_context *ctx, GLfloat t, GLuint dst, GLuint out, GLuint in, GLboolean force_boundary)
void _tnl_generic_copy_pv (struct gl_context *ctx, GLuint edst, GLuint esrc)
void _tnl_generic_interp (struct gl_context *ctx, GLfloat t, GLuint edst, GLuint eout, GLuint ein, GLboolean force_boundary)
void _tnl_generic_emit (struct gl_context *ctx, GLuint count, GLubyte *v)
void _tnl_generate_hardwired_emit (struct gl_context *ctx)
void _tnl_generate_sse_emit (struct gl_context *ctx)
Variables
struct tnl_format_info _tnl_format_info [EMIT_MAX]
Macro Definition Documentation
#define GET_VERTEX_STATE (ctx) &(TNL_CONTEXT(ctx)->clipspace)
Referenced by _tnl_build_vertices(), _tnl_copy_pv(), _tnl_emit_indexed_vertices_to_buffer(), _tnl_emit_vertices_to_buffer(), _tnl_free_vertices(), _tnl_generate_hardwired_emit(), _tnl_generic_copy_pv(), _tnl_generic_emit(), _tnl_generic_interp(), _tnl_get_attr(), _tnl_get_vertex(), _tnl_init_vertices(), _tnl_install_attrs(), _tnl_interp(), _tnl_invalidate_vertex_state(), _tnl_invalidate_vertices(), _tnl_notify_pipeline_output_change(), _tnl_set_attr(), adjust_input_ptrs(), choose_copy_pv_func(), choose_emit_func(), choose_interp_func(), and update_input_ptrs().
Enumeration Type Documentation
enum tnl_attr_format
Enumerator
EMIT_1F
EMIT_2F
EMIT_3F
EMIT_4F
EMIT_2F_VIEWPORT
EMIT_3F_VIEWPORT
EMIT_4F_VIEWPORT
EMIT_3F_XYW
EMIT_1UB_1F
EMIT_3UB_3F_RGB
EMIT_3UB_3F_BGR
EMIT_4UB_4F_RGBA
EMIT_4UB_4F_BGRA
EMIT_4UB_4F_ARGB
EMIT_4UB_4F_ABGR
EMIT_4CHAN_4F_RGBA
EMIT_PAD
EMIT_MAX
Function Documentation
void _tnl_build_vertices (struct gl_context * ctx, GLuint start, GLuint end, GLuint newinputs)
References tnl_clipspace::emit, GET_VERTEX_STATE, GLubyte, update_input_ptrs(), tnl_clipspace::vertex_buf, and tnl_clipspace::vertex_size.
void _tnl_copy_pv (struct gl_context * ctx, GLuint edst, GLuint esrc)
References tnl_clipspace::copy_pv, and GET_VERTEX_STATE.
void* _tnl_emit_indexed_vertices_to_buffer (struct gl_context * ctx, const GLuint * elts, GLuint start, GLuint end, void * dest)
References adjust_input_ptrs(), tnl_clipspace::emit, GET_VERTEX_STATE, GLubyte, update_input_ptrs(), and tnl_clipspace::vertex_size.
void* _tnl_emit_vertices_to_buffer (struct gl_context * ctx, GLuint start, GLuint end, void * dest)
References tnl_clipspace::emit, GET_VERTEX_STATE, GLubyte, update_input_ptrs(), and tnl_clipspace::vertex_size.
void _tnl_free_vertices (struct gl_context * ctx)
References _mesa_align_free(), _mesa_exec_free(), tnl_clipspace_fastpath::attr, tnl_clipspace::fastpath, tnl_clipspace_fastpath::func, GET_VERTEX_STATE, tnl_clipspace_fastpath::next, NULL, TNL_CONTEXT, and tnl_clipspace::vertex_buf.
Referenced by _tnl_init_vertices().
void _tnl_generate_hardwired_emit (struct gl_context * ctx)
References tnl_clipspace::attr, tnl_clipspace::attr_count, tnl_clipspace_attr::emit, tnl_clipspace::emit, GET_VERTEX_STATE, and NULL.
Referenced by choose_emit_func().
void _tnl_generate_sse_emit (struct gl_context * ctx)
Referenced by _tnl_init_vertices().
void _tnl_generic_copy_pv (struct gl_context * ctx, GLuint edst, GLuint esrc)
References tnl_clipspace::attr, tnl_clipspace::attr_count, tnl_clipspace_attr::attrib, GET_VERTEX_STATE, GLubyte, VERT_ATTRIB_COLOR0, VERT_ATTRIB_COLOR1, tnl_clipspace_attr::vertattrsize, tnl_clipspace::vertex_buf, tnl_clipspace::vertex_size, and tnl_clipspace_attr::vertoffset.
Referenced by _tnl_generic_copy_pv_extras(), and choose_copy_pv_func().
void _tnl_generic_copy_pv_extras (struct gl_context * ctx, GLuint dst, GLuint src)
References _tnl_generic_copy_pv(), vertex_buffer::BackfaceColorPtr, vertex_buffer::BackfaceIndexPtr, vertex_buffer::BackfaceSecondaryColorPtr, GLvector4f::data, GLvector4f::stride, and TNL_CONTEXT.
Referenced by choose_copy_pv_func().
void _tnl_generic_emit (struct gl_context * ctx, GLuint count, GLubyte * v)
References tnl_clipspace::attr, tnl_clipspace::attr_count, tnl_clipspace_attr::emit, GET_VERTEX_STATE, tnl_clipspace_attr::inputptr, tnl_clipspace_attr::inputstride, tnl_clipspace::vertex_size, and tnl_clipspace_attr::vertoffset.
Referenced by choose_emit_func().
void _tnl_generic_interp (struct gl_context * ctx, GLfloat t, GLuint edst, GLuint eout, GLuint ein, GLboolean force_boundary)
References tnl_clipspace::attr, tnl_clipspace::attr_count, vertex_buffer::ClipPtr, GLvector4f::data, tnl_clipspace_attr::extract, GET_VERTEX_STATE, GLubyte, tnl_clipspace_attr::insert, TNLcontext::NeedNdcCoords, TNL_CONTEXT, TNLcontext::vb, tnl_clipspace::vertex_buf, tnl_clipspace::vertex_size, tnl_clipspace_attr::vertoffset, and void.
Referenced by _tnl_generic_interp_extras(), and choose_interp_func().
void _tnl_generic_interp_extras (struct gl_context * ctx, GLfloat t, GLuint dst, GLuint out, GLuint in, GLboolean force_boundary)
References _tnl_generic_interp(), vertex_buffer::BackfaceColorPtr, vertex_buffer::BackfaceIndexPtr, vertex_buffer::BackfaceSecondaryColorPtr, GLvector4f::data, vertex_buffer::EdgeFlag, GLvector4f::stride, and TNL_CONTEXT.
Referenced by choose_interp_func().
void _tnl_get_attr (struct gl_context * ctx, const void * vertex, GLenum attrib, GLfloat * dest)
References _TNL_ATTRIB_POINTSIZE, tnl_clipspace::attr, tnl_clipspace::attr_count, gl_current_attrib::Attrib, tnl_clipspace_attr::attrib, gl_context::Current, tnl_clipspace_attr::extract, GET_VERTEX_STATE, GLubyte, gl_context::Point, gl_point_attrib::Size, and tnl_clipspace_attr::vertoffset.
void* _tnl_get_vertex (struct gl_context * ctx, GLuint nr)
References GET_VERTEX_STATE, tnl_clipspace::vertex_buf, and tnl_clipspace::vertex_size.
void _tnl_init_vertices (struct gl_context * ctx, GLuint vb_size, GLuint max_vertex_size)
References _mesa_align_calloc(), _mesa_getenv(), _tnl_free_vertices(), _tnl_generate_sse_emit(), _tnl_install_attrs(), tnl_clipspace::chan_scale, CHAN_TYPE, tnl_clipspace::codegen_emit, GET_VERTEX_STATE, tnl_clipspace::identity, invalidate_funcs(), tnl_clipspace::max_vertex_size, tnl_clipspace::need_extras, NULL, and tnl_clipspace::vertex_buf.
GLuint _tnl_install_attrs (struct gl_context * ctx, const struct tnl_attr_map * map, GLuint nr, const GLfloat * vp, GLuint unpacked_size)
References _TNL_ATTRIB_MAX, _tnl_format_info, tnl_clipspace::attr, tnl_clipspace::attr_count, tnl_attr_map::attrib, tnl_clipspace_attr::attrib, tnl_format_info::attrsize, DBG, EMIT_PAD, tnl_format_info::extract, tnl_clipspace_attr::extract, tnl_attr_map::format, tnl_clipspace_attr::format, GET_VERTEX_STATE, tnl_format_info::insert, tnl_clipspace_attr::insert, invalidate_funcs(), tnl_clipspace::max_vertex_size, tnl_clipspace::need_viewport, tnl_clipspace::new_inputs, tnl_attr_map::offset, VERT_ATTRIB_POS, tnl_clipspace_attr::vertattrsize, tnl_clipspace::vertex_size, tnl_clipspace_attr::vertoffset, and tnl_clipspace_attr::vp.
Referenced by _tnl_init_vertices().
void _tnl_interp (struct gl_context * ctx, GLfloat t, GLuint edst, GLuint eout, GLuint ein, GLboolean force_boundary)
References GET_VERTEX_STATE, and tnl_clipspace::interp.
void _tnl_invalidate_vertex_state (struct gl_context * ctx, GLuint new_state)
References _NEW_LIGHT, _NEW_POLYGON, choose_copy_pv_func(), choose_interp_func(), tnl_clipspace::copy_pv, GET_VERTEX_STATE, tnl_clipspace::interp, and tnl_clipspace::new_inputs.
void _tnl_invalidate_vertices (struct gl_context * ctx, GLuint newinputs)
References GET_VERTEX_STATE, and tnl_clipspace::new_inputs.
void _tnl_notify_pipeline_output_change (struct gl_context * ctx)
References GET_VERTEX_STATE, and invalidate_funcs().
Referenced by _tnl_run_pipeline().
void _tnl_register_fastpath (struct tnl_clipspace * vtx, GLboolean match_strides)
References tnl_clipspace_fastpath::attr, tnl_clipspace::attr, tnl_clipspace_fastpath::attr_count, tnl_clipspace::attr_count, CALLOC_STRUCT, tnl_clipspace::emit, tnl_clipspace::fastpath, tnl_clipspace_attr::format, tnl_attr_type::format, tnl_clipspace_fastpath::func, tnl_clipspace_attr::inputsize, tnl_clipspace_attr::inputstride, tnl_clipspace_fastpath::match_strides, tnl_clipspace_fastpath::next, tnl_attr_type::offset, tnl_attr_type::size, tnl_attr_type::stride, tnl_clipspace_fastpath::vertex_size, tnl_clipspace::vertex_size, and tnl_clipspace_attr::vertoffset.
void _tnl_set_attr (struct gl_context * ctx, void * vout, GLenum attrib, const GLfloat * src)
References tnl_clipspace::attr, tnl_clipspace::attr_count, tnl_clipspace_attr::attrib, GET_VERTEX_STATE, GLubyte, tnl_clipspace_attr::insert, and tnl_clipspace_attr::vertoffset.
Variable Documentation
struct tnl_format_info _tnl_format_info[EMIT_MAX]
Referenced by _tnl_install_attrs().