Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
tnl.h File Reference
#include "main/glheader.h"
Functions
GLboolean _tnl_CreateContext (struct gl_context *ctx)
void _tnl_DestroyContext (struct gl_context *ctx)
void _tnl_InvalidateState (struct gl_context *ctx, GLuint new_state)
void _tnl_wakeup (struct gl_context *ctx)
void _tnl_need_projected_coords (struct gl_context *ctx, GLboolean flag)
Drivers call this function to tell the TCL module whether or not it wants Normalized Device Coords (NDC) computed.
void _tnl_allow_vertex_fog (struct gl_context *ctx, GLboolean value)
void _tnl_allow_pixel_fog (struct gl_context *ctx, GLboolean value)
GLboolean _tnl_program_string (struct gl_context *ctx, GLenum target, struct gl_program *program)
Called via ctx->Driver.ProgramStringNotify() after a new vertex program string has been parsed.
void _tnl_draw_prims (struct gl_context *ctx, const struct gl_client_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index)
void _tnl_vbo_draw_prims (struct gl_context *ctx, const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *tfb_vertcount)
void _tnl_RasterPos (struct gl_context *ctx, const GLfloat vObj[4])
glRasterPos transformation.
void _tnl_validate_shine_tables (struct gl_context *ctx)
Function Documentation
void _tnl_allow_pixel_fog (struct gl_context * ctx, GLboolean value)
References gl_fragment_program_state::_Current, TNLcontext::_DoVertexFog, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, gl_hint_attrib::Fog, gl_context::FragmentProgram, gl_context::Hint, and TNL_CONTEXT.
void _tnl_allow_vertex_fog (struct gl_context * ctx, GLboolean value)
References gl_fragment_program_state::_Current, TNLcontext::_DoVertexFog, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, gl_hint_attrib::Fog, gl_context::FragmentProgram, gl_context::Hint, and TNL_CONTEXT.
GLboolean _tnl_CreateContext (struct gl_context * ctx)
References gl_vertex_program_state::_MaintainTnlProgram, _math_init_transformation(), _math_init_translate(), TNLcontext::_ShineTabList, _tnl_default_pipeline, _tnl_install_pipeline(), _tnl_render_tab_elts, _tnl_render_tab_verts, _tnl_validate_shine_tables(), _tnl_vbo_draw_prims(), _tnl_vp_pipeline, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, gl_context::Const, TNLcontext::Driver, insert_at_tail, make_empty_list, MALLOC_STRUCT, MAX_CLIPPED_VERTICES, gl_constants::MaxArrayLockSize, TNLcontext::NeedNdcCoords, tnl_device_driver::NotifyMaterialChange, TNLcontext::nr_blocks, tnl_device_driver::PrimTabElts, tnl_device_driver::PrimTabVerts, tnl_shine_tab::refcount, tnl_device_driver::Render, tnl_shine_tab::shininess, vertex_buffer::Size, gl_context::swtnl_context, TNLcontext::vb, vbo_set_draw_func(), and gl_context::VertexProgram.
void _tnl_DestroyContext (struct gl_context * ctx)
References TNLcontext::_ShineTabList, _tnl_destroy_pipeline(), foreach_s, NULL, gl_context::swtnl_context, and TNL_CONTEXT.
void _tnl_draw_prims (struct gl_context * ctx, const struct gl_client_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index)
References __FUNCTION__, _mesa_check_conditional_render(), _mesa_lookup_enum_by_nr(), _tnl_vbo_draw_prims(), _mesa_prim::basevertex, bind_indices(), bind_inputs(), bind_prims(), TNLcontext::CurInstance, free_space(), MAX2, MAX_CLIPPED_VERTICES, split_limits::max_indices, split_limits::max_vb_size, split_limits::max_verts, gl_context::NewState, _mesa_prim::num_instances, vertex_buffer::Size, TNL_CONTEXT, unmap_vbos(), TNLcontext::vb, vbo_rebase_prims(), vbo_split_prims(), and VERT_ATTRIB_MAX.
Referenced by _tnl_vbo_draw_prims().
void _tnl_InvalidateState (struct gl_context * ctx, GLuint new_state)
References gl_point_attrib::_Attenuated, gl_vertex_program_state::_Current, gl_fragment_program_state::_Current, TNLcontext::_DoVertexFog, gl_texture_attrib::_EnabledCoordUnits, _NEW_HINT, _NEW_PROGRAM, _TNL_ATTRIB_COLOR0, _TNL_ATTRIB_COLOR1, _TNL_ATTRIB_EDGEFLAG, _TNL_ATTRIB_FOG, _TNL_ATTRIB_GENERIC, _TNL_ATTRIB_POINTSIZE, _TNL_ATTRIB_POS, _TNL_ATTRIB_TEX, _TNL_ATTRIB_TEX0, TNLcontext::AllowPixelFog, TNLcontext::AllowVertexFog, ASSERT, gl_polygon_attrib::BackMode, gl_fragment_program::Base, gl_vertex_program::Base, BITFIELD64_BIT, gl_context::Const, gl_fog_attrib::Enabled, gl_hint_attrib::Fog, gl_context::Fog, gl_context::FragmentProgram, gl_polygon_attrib::FrontMode, gl_context::Hint, gl_program::InputsRead, MAX_VARYING, gl_constants::MaxTextureCoordUnits, tnl_pipeline::new_state, NULL, gl_program::OutputsWritten, TNLcontext::pipeline, gl_context::Point, gl_vertex_program_state::PointSizeEnabled, gl_context::Polygon, TNLcontext::render_inputs_bitset, gl_context::RenderMode, gl_context::Texture, TNL_CONTEXT, VARYING_BIT_COL0, VARYING_BIT_FOGC, VARYING_BIT_TEX, VARYING_SLOT_VAR0, and gl_context::VertexProgram.
Referenced by _tnl_wakeup().
void _tnl_need_projected_coords (struct gl_context * ctx, GLboolean mode)
Drivers call this function to tell the TCL module whether or not it wants Normalized Device Coords (NDC) computed.
I.e. whether we should "Divide-by-W". Software renders will want that.
References TNLcontext::NeedNdcCoords, and TNL_CONTEXT.
GLboolean _tnl_program_string (struct gl_context * ctx, GLenum target, struct gl_program * program)
Called via ctx->Driver.ProgramStringNotify() after a new vertex program string has been parsed.
void _tnl_RasterPos (struct gl_context * ctx, const GLfloat vObj[4])
glRasterPos transformation.
Typically called via ctx->Driver.RasterPos(). XXX some of this code (such as viewport xform, clip testing and setting of ctx->Current.Raster* fields) could get lifted up into the main/rasterpos.c code.
Parameters
vObj vertex position in object space
References gl_framebuffer::_DepthMaxF, gl_vertex_program_state::_Enabled, _mesa_problem(), _mesa_update_hitflag(), gl_context::_NeedEyeCoords, gl_viewport_attrib::_WindowMap, gl_current_attrib::Attrib, CLAMP, gl_transform_attrib::ClipPlanesEnabled, compute_texgen(), gl_context::Const, COPY_4V, gl_context::Current, gl_transform_attrib::DepthClamp, gl_context::DrawBuffer, gl_light_attrib::Enabled, F, gl_viewport_attrib::Far, gl_context::Fog, gl_fog_attrib::FogCoordinateSource, if(), GLmatrix::inv, gl_context::Light, GLmatrix::m, MAT_SX, MAT_SY, MAT_SZ, MAT_TX, MAT_TY, MAT_TZ, gl_constants::MaxTextureCoordUnits, gl_context::ModelviewMatrixStack, gl_viewport_attrib::Near, gl_context::ProjectionMatrixStack, gl_current_attrib::RasterColor, gl_current_attrib::RasterDistance, gl_current_attrib::RasterPos, gl_transform_attrib::RasterPositionUnclipped, gl_current_attrib::RasterPosValid, gl_current_attrib::RasterSecondaryColor, gl_current_attrib::RasterTexCoords, gl_context::RenderMode, shade_rastpos(), sqrtf, gl_texture_unit::TexGenEnabled, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, gl_context::Transform, TRANSFORM_NORMAL, TRANSFORM_POINT, gl_texture_attrib::Unit, userclip_point(), VERT_ATTRIB_COLOR0, VERT_ATTRIB_COLOR1, VERT_ATTRIB_FOG, VERT_ATTRIB_NORMAL, VERT_ATTRIB_TEX0, gl_context::VertexProgram, viewclip_point_xy(), viewclip_point_z(), and gl_context::Viewport.
void _tnl_validate_shine_tables (struct gl_context * ctx)
References TNLcontext::_ShineTable, gl_material::Attrib, gl_context::Light, MAT_ATTRIB_BACK_SHININESS, MAT_ATTRIB_FRONT_SHININESS, gl_light_attrib::Material, tnl_shine_tab::shininess, TNL_CONTEXT, and validate_shine_table().
Referenced by _tnl_CreateContext(), prepare_materials(), and update_materials().
void _tnl_vbo_draw_prims (struct gl_context * ctx, const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object * tfb_vertcount)
References gl_array_attrib::_DrawArrays, _tnl_draw_prims(), gl_context::Array, and vbo_get_minmax_indices().
Referenced by _tnl_CreateContext(), and _tnl_draw_prims().
void _tnl_wakeup (struct gl_context * ctx)
References _mesa_update_color_material(), _tnl_InvalidateState(), gl_current_attrib::Attrib, gl_light_attrib::ColorMaterialEnabled, gl_context::Current, gl_context::Light, and VERT_ATTRIB_COLOR0.