Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
m_norm_tmp.h File Reference
Functions
static void _XFORMAPI TAG() transform_normalize_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() transform_normalize_normals_no_rot (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() transform_rescale_normals_no_rot (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() transform_rescale_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() transform_normals_no_rot (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() transform_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() normalize_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() rescale_normals (const GLmatrix *mat, GLfloat scale, const GLvector4f *in, const GLfloat *lengths, GLvector4f *dest)
static void _XFORMAPI TAG() init_c_norm_transform (void)
Function Documentation
static void _XFORMAPI TAG() init_c_norm_transform (void) static
References _mesa_normal_tab, NORM_NORMALIZE, NORM_RESCALE, NORM_TRANSFORM, NORM_TRANSFORM_NO_ROT, normalize_normals(), rescale_normals(), TAG, transform_normalize_normals(), transform_normalize_normals_no_rot(), transform_normals(), transform_normals_no_rot(), transform_rescale_normals(), and transform_rescale_normals_no_rot().
Referenced by _math_init_transformation().
static void _XFORMAPI TAG() normalize_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References STRIDE_LOOP, and void.
Referenced by init_c_norm_transform().
static void _XFORMAPI TAG() rescale_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References SCALE_SCALAR_3V, STRIDE_LOOP, and void.
Referenced by init_c_norm_transform().
static void _XFORMAPI TAG() transform_normalize_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLvector4f::count, GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().
static void _XFORMAPI TAG() transform_normalize_normals_no_rot (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLvector4f::count, GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().
static void _XFORMAPI TAG() transform_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLmatrix::inv, STRIDE_LOOP, and void.
Referenced by init_c_norm_transform().
static void _XFORMAPI TAG() transform_normals_no_rot (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLmatrix::inv, STRIDE_LOOP, and void.
Referenced by init_c_norm_transform().
static void _XFORMAPI TAG() transform_rescale_normals (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().
static void _XFORMAPI TAG() transform_rescale_normals_no_rot (const GLmatrix * mat, GLfloat scale, const GLvector4f * in, const GLfloat * lengths, GLvector4f * dest) static
References GLmatrix::inv, and STRIDE_LOOP.
Referenced by init_c_norm_transform().