Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
m_translate.h File Reference
#include "main/compiler.h"
#include "main/glheader.h"
#include "main/mtypes.h"
#include "swrast/s_chan.h"
Functions
void _math_trans_1f (GLfloat *to, const void *ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Array translation.
void _math_trans_1ui (GLuint *to, const void *ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Translate vector of values to GLuint [1].
void _math_trans_1ub (GLubyte *to, const void *ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Translate vector of values to GLubyte [1].
void _math_trans_4ub (GLubyte(*to)[4], const void *ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Translate vector of values to GLubyte [4].
void _math_trans_4chan (GLchan(*to)[4], const void *ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Translate vector of values to GLchan [4].
void _math_trans_4us (GLushort(*to)[4], const void *ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Translate vector of values to GLushort [4].
void _math_trans_4f (GLfloat(*to)[4], const void *ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Convert to floats w/out normalization (i.e.
void _math_trans_4fn (GLfloat(*to)[4], const void *ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Convert to normalized floats in [0,1] or [-1, 1].
void _math_trans_3fn (GLfloat(*to)[3], const void *ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Translate vector of values to GLfloat[3], normalized to [-1, 1].
void _math_init_translate (void)
Function Documentation
void _math_init_translate (void)
References init_translate_raw().
void _math_trans_1f (GLfloat * to, const void * ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Array translation.
For example, convert array of GLushort[3] to GLfloat[4]. The function name specifies the destination format/size.
Parameters
to the destination address
ptr the source address
stride the source stride (in bytes) between elements
type the source datatype (GL_SHORT, GL_UNSIGNED_INT, etc)
size number of values per element in source array (1,2,3 or 4)
start first element in source array to convert
n number of elements to convert
Note: "element" means a tuple like GLfloat[3] or GLubyte[4].
References _math_trans_1f_tab, and TYPE_IDX.
void _math_trans_1ub (GLubyte * to, const void * ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Translate vector of values to GLubyte [1].
References _math_trans_1ub_tab, and TYPE_IDX.
void _math_trans_1ui (GLuint * to, const void * ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Translate vector of values to GLuint [1].
References _math_trans_1ui_tab, and TYPE_IDX.
void _math_trans_3fn (GLfloat(*) to[3], const void * ptr, GLuint stride, GLenum type, GLuint start, GLuint n)
Translate vector of values to GLfloat[3], normalized to [-1, 1].
References _math_trans_3fn_tab, and TYPE_IDX.
void _math_trans_4chan (GLchan(*) to[4], const void * ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Translate vector of values to GLchan [4].
References _math_trans_4fn(), _math_trans_4ub(), and _math_trans_4us().
void _math_trans_4f (GLfloat(*) to[4], const void * ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Convert to floats w/out normalization (i.e.
just cast)
References _math_trans_4f_tab, and TYPE_IDX.
void _math_trans_4fn (GLfloat(*) to[4], const void * ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Convert to normalized floats in [0,1] or [-1, 1].
References _math_trans_4fn_tab, and TYPE_IDX.
Referenced by _math_trans_4chan().
void _math_trans_4ub (GLubyte(*) to[4], const void * ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Translate vector of values to GLubyte [4].
References _math_trans_4ub_tab, and TYPE_IDX.
Referenced by _math_trans_4chan().
void _math_trans_4us (GLushort(*) to[4], const void * ptr, GLuint stride, GLenum type, GLuint size, GLuint start, GLuint n)
Translate vector of values to GLushort [4].
References _math_trans_4us_tab, and TYPE_IDX.
Referenced by _math_trans_4chan().