Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
api_exec.c File Reference
Initialize dispatch table.
#include "main/accum.h"
#include "main/api_loopback.h"
#include "main/api_exec.h"
#include "main/arbprogram.h"
#include "main/atifragshader.h"
#include "main/attrib.h"
#include "main/blend.h"
#include "main/bufferobj.h"
#include "main/arrayobj.h"
#include "main/buffers.h"
#include "main/clear.h"
#include "main/clip.h"
#include "main/colortab.h"
#include "main/condrender.h"
#include "main/context.h"
#include "main/convolve.h"
#include "main/depth.h"
#include "main/dlist.h"
#include "main/drawpix.h"
#include "main/drawtex.h"
#include "main/rastpos.h"
#include "main/enable.h"
#include "main/errors.h"
#include "main/es1_conversion.h"
#include "main/eval.h"
#include "main/get.h"
#include "main/feedback.h"
#include "main/fog.h"
#include "main/fbobject.h"
#include "main/framebuffer.h"
#include "main/hint.h"
#include "main/histogram.h"
#include "main/imports.h"
#include "main/light.h"
#include "main/lines.h"
#include "main/matrix.h"
#include "main/multisample.h"
#include "main/pixel.h"
#include "main/pixelstore.h"
#include "main/points.h"
#include "main/polygon.h"
#include "main/querymatrix.h"
#include "main/queryobj.h"
#include "main/readpix.h"
#include "main/samplerobj.h"
#include "main/scissor.h"
#include "main/stencil.h"
#include "main/texenv.h"
#include "main/texgetimage.h"
#include "main/teximage.h"
#include "main/texgen.h"
#include "main/texobj.h"
#include "main/texparam.h"
#include "main/texstate.h"
#include "main/texstorage.h"
#include "main/texturebarrier.h"
#include "main/transformfeedback.h"
#include "main/mtypes.h"
#include "main/varray.h"
#include "main/viewport.h"
#include "main/shaderapi.h"
#include "main/uniforms.h"
#include "main/syncobj.h"
#include "main/formatquery.h"
#include "main/dispatch.h"
#include "vbo/vbo.h"
Functions
void _mesa_initialize_exec_table (struct gl_context *ctx)
Initialize a context's exec table with pointers to Mesa's supported GL functions.
Detailed Description
Initialize dispatch table.
Function Documentation
void _mesa_initialize_exec_table (struct gl_context * ctx)
Initialize a context's exec table with pointers to Mesa's supported GL functions.
This function depends on ctx->Version.
Parameters
ctx GL context to which exec belongs.
References _mesa_Accum(), _mesa_ActiveProgramEXT(), _mesa_ActiveStencilFaceEXT(), _mesa_ActiveTexture(), _mesa_AlphaFragmentOp1ATI(), _mesa_AlphaFragmentOp2ATI(), _mesa_AlphaFragmentOp3ATI(), _mesa_AlphaFunc(), _mesa_AlphaFuncx(), _mesa_AreTexturesResident(), _mesa_AttachObjectARB(), _mesa_AttachShader(), _mesa_BeginConditionalRender(), _mesa_BeginFragmentShaderATI(), _mesa_BeginQuery(), _mesa_BeginQueryIndexed(), _mesa_BeginTransformFeedback(), _mesa_BindAttribLocation(), _mesa_BindBuffer(), _mesa_BindBufferBase(), _mesa_BindBufferOffsetEXT(), _mesa_BindBufferRange(), _mesa_BindFragDataLocation(), _mesa_BindFragDataLocationIndexed(), _mesa_BindFragmentShaderATI(), _mesa_BindFramebuffer(), _mesa_BindProgramARB(), _mesa_BindRenderbuffer(), _mesa_BindSampler(), _mesa_BindTexture(), _mesa_BindTransformFeedback(), _mesa_BindVertexArray(), _mesa_BindVertexArrayAPPLE(), _mesa_Bitmap(), _mesa_BlendColor(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFunc(), _mesa_BlendFunciARB(), _mesa_BlendFuncSeparate(), _mesa_BlendFuncSeparateiARB(), _mesa_BlitFramebuffer(), _mesa_BufferData(), _mesa_BufferSubData(), _mesa_CallList(), _mesa_CallLists(), _mesa_CheckFramebufferStatus(), _mesa_ClampColor(), _mesa_Clear(), _mesa_ClearAccum(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_ClearColor(), _mesa_ClearColorIiEXT(), _mesa_ClearColorIuiEXT(), _mesa_ClearColorx(), _mesa_ClearDepth(), _mesa_ClearDepthf(), _mesa_ClearDepthx(), _mesa_ClearIndex(), _mesa_ClearStencil(), _mesa_ClientActiveTexture(), _mesa_ClientWaitSync(), _mesa_ClipPlane(), _mesa_ClipPlanef(), _mesa_ClipPlanex(), _mesa_Color3b(), _mesa_Color3bv(), _mesa_Color3d(), _mesa_Color3dv(), _mesa_Color3i(), _mesa_Color3iv(), _mesa_Color3s(), _mesa_Color3sv(), _mesa_Color3ub(), _mesa_Color3ubv(), _mesa_Color3ui(), _mesa_Color3uiv(), _mesa_Color3us(), _mesa_Color3usv(), _mesa_Color4b(), _mesa_Color4bv(), _mesa_Color4d(), _mesa_Color4dv(), _mesa_Color4i(), _mesa_Color4iv(), _mesa_Color4s(), _mesa_Color4sv(), _mesa_Color4ub(), _mesa_Color4ubv(), _mesa_Color4ui(), _mesa_Color4uiv(), _mesa_Color4us(), _mesa_Color4usv(), _mesa_Color4x(), _mesa_ColorFragmentOp1ATI(), _mesa_ColorFragmentOp2ATI(), _mesa_ColorFragmentOp3ATI(), _mesa_ColorMask(), _mesa_ColorMaski(), _mesa_ColorMaterial(), _mesa_ColorPointer(), _mesa_ColorPointerEXT(), _mesa_ColorSubTable(), _mesa_ColorTable(), _mesa_ColorTableParameterfv(), _mesa_ColorTableParameteriv(), _mesa_CompileShader(), _mesa_CompressedTexImage1D(), _mesa_CompressedTexImage2D(), _mesa_CompressedTexImage3D(), _mesa_CompressedTexSubImage1D(), _mesa_CompressedTexSubImage2D(), _mesa_CompressedTexSubImage3D(), _mesa_ConvolutionFilter1D(), _mesa_ConvolutionFilter2D(), _mesa_ConvolutionParameterf(), _mesa_ConvolutionParameterfv(), _mesa_ConvolutionParameteri(), _mesa_ConvolutionParameteriv(), _mesa_CopyBufferSubData(), _mesa_CopyColorSubTable(), _mesa_CopyColorTable(), _mesa_CopyConvolutionFilter1D(), _mesa_CopyConvolutionFilter2D(), _mesa_CopyPixels(), _mesa_CopyTexImage1D(), _mesa_CopyTexImage2D(), _mesa_CopyTexSubImage1D(), _mesa_CopyTexSubImage2D(), _mesa_CopyTexSubImage3D(), _mesa_CreateProgram(), _mesa_CreateProgramObjectARB(), _mesa_CreateShader(), _mesa_CreateShaderObjectARB(), _mesa_CreateShaderProgramEXT(), _mesa_CullFace(), _mesa_DebugMessageCallbackARB(), _mesa_DebugMessageControlARB(), _mesa_DebugMessageInsertARB(), _mesa_DeleteBuffers(), _mesa_DeleteFragmentShaderATI(), _mesa_DeleteFramebuffers(), _mesa_DeleteLists(), _mesa_DeleteObjectARB(), _mesa_DeleteProgram(), _mesa_DeleteProgramsARB(), _mesa_DeleteQueries(), _mesa_DeleteRenderbuffers(), _mesa_DeleteSamplers(), _mesa_DeleteShader(), _mesa_DeleteSync(), _mesa_DeleteTextures(), _mesa_DeleteTransformFeedbacks(), _mesa_DeleteVertexArrays(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DepthMask(), _mesa_DepthRange(), _mesa_DepthRangef(), _mesa_DepthRangex(), _mesa_DetachObjectARB(), _mesa_DetachShader(), _mesa_Disable(), _mesa_DisableClientState(), _mesa_Disablei(), _mesa_DisableVertexAttribArray(), _mesa_DiscardFramebufferEXT(), _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_DrawPixels(), _mesa_DrawTexfOES(), _mesa_DrawTexfvOES(), _mesa_DrawTexiOES(), _mesa_DrawTexivOES(), _mesa_DrawTexsOES(), _mesa_DrawTexsvOES(), _mesa_DrawTexxOES(), _mesa_DrawTexxvOES(), _mesa_EdgeFlagPointer(), _mesa_EdgeFlagPointerEXT(), _mesa_EdgeFlagv(), _mesa_EGLImageTargetRenderbufferStorageOES(), _mesa_EGLImageTargetTexture2DOES(), _mesa_Enable(), _mesa_EnableClientState(), _mesa_Enablei(), _mesa_EnableVertexAttribArray(), _mesa_EndConditionalRender(), _mesa_EndFragmentShaderATI(), _mesa_EndList(), _mesa_EndQuery(), _mesa_EndQueryIndexed(), _mesa_EndTransformFeedback(), _mesa_EvalCoord1d(), _mesa_EvalCoord1dv(), _mesa_EvalCoord1fv(), _mesa_EvalCoord2d(), _mesa_EvalCoord2dv(), _mesa_EvalCoord2fv(), _mesa_FeedbackBuffer(), _mesa_FenceSync(), _mesa_Finish(), _mesa_Flush(), _mesa_FlushMappedBufferRange(), _mesa_FogCoordd(), _mesa_FogCoorddv(), _mesa_FogCoordPointer(), _mesa_Fogf(), _mesa_Fogfv(), _mesa_Fogi(), _mesa_Fogiv(), _mesa_Fogx(), _mesa_Fogxv(), _mesa_FramebufferRenderbuffer(), _mesa_FramebufferTexture(), _mesa_FramebufferTexture1D(), _mesa_FramebufferTexture2D(), _mesa_FramebufferTexture3D(), _mesa_FramebufferTextureLayer(), _mesa_FrontFace(), _mesa_Frustum(), _mesa_Frustumf(), _mesa_Frustumx(), _mesa_GenBuffers(), _mesa_GenerateMipmap(), _mesa_GenFragmentShadersATI(), _mesa_GenFramebuffers(), _mesa_GenLists(), _mesa_GenProgramsARB(), _mesa_GenQueries(), _mesa_GenRenderbuffers(), _mesa_GenSamplers(), _mesa_GenTextures(), _mesa_GenTransformFeedbacks(), _mesa_GenVertexArrays(), _mesa_GenVertexArraysAPPLE(), _mesa_GetActiveAttrib(), _mesa_GetActiveUniform(), _mesa_GetActiveUniformBlockiv(), _mesa_GetActiveUniformBlockName(), _mesa_GetActiveUniformName(), _mesa_GetActiveUniformsiv(), _mesa_GetAttachedObjectsARB(), _mesa_GetAttachedShaders(), _mesa_GetAttribLocation(), _mesa_GetBooleani_v(), _mesa_GetBooleanv(), _mesa_GetBufferParameteri64v(), _mesa_GetBufferParameteriv(), _mesa_GetBufferPointerv(), _mesa_GetBufferSubData(), _mesa_GetClipPlane(), _mesa_GetClipPlanef(), _mesa_GetClipPlanex(), _mesa_GetColorTable(), _mesa_GetColorTableParameterfv(), _mesa_GetColorTableParameteriv(), _mesa_GetCompressedTexImage(), _mesa_GetConvolutionFilter(), _mesa_GetConvolutionParameterfv(), _mesa_GetConvolutionParameteriv(), _mesa_GetDebugMessageLogARB(), _mesa_GetDoublev(), _mesa_GetError(), _mesa_GetFixedv(), _mesa_GetFloatv(), _mesa_GetFragDataIndex(), _mesa_GetFragDataLocation(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetGraphicsResetStatusARB(), _mesa_GetHandleARB(), _mesa_GetHistogram(), _mesa_GetHistogramParameterfv(), _mesa_GetHistogramParameteriv(), _mesa_GetInfoLogARB(), _mesa_GetInteger64i_v(), _mesa_GetInteger64v(), _mesa_GetIntegeri_v(), _mesa_GetIntegerv(), _mesa_GetInternalformativ(), _mesa_GetLightfv(), _mesa_GetLightiv(), _mesa_GetLightxv(), _mesa_GetMapdv(), _mesa_GetMapfv(), _mesa_GetMapiv(), _mesa_GetMaterialfv(), _mesa_GetMaterialiv(), _mesa_GetMaterialxv(), _mesa_GetMinmax(), _mesa_GetMinmaxParameterfv(), _mesa_GetMinmaxParameteriv(), _mesa_GetMultisamplefv(), _mesa_GetnColorTableARB(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnConvolutionFilterARB(), _mesa_GetnHistogramARB(), _mesa_GetnMapdvARB(), _mesa_GetnMapfvARB(), _mesa_GetnMapivARB(), _mesa_GetnMinmaxARB(), _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), _mesa_GetnPolygonStippleARB(), _mesa_GetnSeparableFilterARB(), _mesa_GetnTexImageARB(), _mesa_GetnUniformdvARB(), _mesa_GetnUniformfvARB(), _mesa_GetnUniformivARB(), _mesa_GetnUniformuivARB(), _mesa_GetObjectParameterfvARB(), _mesa_GetObjectParameterivAPPLE(), _mesa_GetObjectParameterivARB(), _mesa_GetPixelMapfv(), _mesa_GetPixelMapuiv(), _mesa_GetPixelMapusv(), _mesa_GetPointerv(), _mesa_GetPolygonStipple(), _mesa_GetProgramBinary(), _mesa_GetProgramEnvParameterdvARB(), _mesa_GetProgramEnvParameterfvARB(), _mesa_GetProgramInfoLog(), _mesa_GetProgramiv(), _mesa_GetProgramivARB(), _mesa_GetProgramLocalParameterdvARB(), _mesa_GetProgramLocalParameterfvARB(), _mesa_GetProgramStringARB(), _mesa_GetQueryIndexediv(), _mesa_GetQueryiv(), _mesa_GetQueryObjecti64v(), _mesa_GetQueryObjectiv(), _mesa_GetQueryObjectui64v(), _mesa_GetQueryObjectuiv(), _mesa_GetRenderbufferParameteriv(), _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_GetSeparableFilter(), _mesa_GetShaderInfoLog(), _mesa_GetShaderiv(), _mesa_GetShaderPrecisionFormat(), _mesa_GetShaderSource(), _mesa_GetString(), _mesa_GetStringi(), _mesa_GetSynciv(), _mesa_GetTexBumpParameterfvATI(), _mesa_GetTexBumpParameterivATI(), _mesa_GetTexEnvfv(), _mesa_GetTexEnviv(), _mesa_GetTexEnvxv(), _mesa_GetTexGendv(), _mesa_GetTexGenfv(), _mesa_GetTexGeniv(), _mesa_GetTexGenxvOES(), _mesa_GetTexImage(), _mesa_GetTexLevelParameterfv(), _mesa_GetTexLevelParameteriv(), _mesa_GetTexParameterfv(), _mesa_GetTexParameterIiv(), _mesa_GetTexParameterIuiv(), _mesa_GetTexParameteriv(), _mesa_GetTexParameterxv(), _mesa_GetTransformFeedbackVarying(), _mesa_GetUniformBlockIndex(), _mesa_GetUniformfv(), _mesa_GetUniformIndices(), _mesa_GetUniformiv(), _mesa_GetUniformLocation(), _mesa_GetUniformuiv(), _mesa_GetVertexAttribdv(), _mesa_GetVertexAttribfv(), _mesa_GetVertexAttribIiv(), _mesa_GetVertexAttribIuiv(), _mesa_GetVertexAttribiv(), _mesa_GetVertexAttribPointerv(), _mesa_Hint(), _mesa_Histogram(), _mesa_Indexd(), _mesa_Indexdv(), _mesa_Indexi(), _mesa_Indexiv(), _mesa_IndexMask(), _mesa_IndexPointer(), _mesa_IndexPointerEXT(), _mesa_Indexs(), _mesa_Indexsv(), _mesa_Indexub(), _mesa_Indexubv(), _mesa_InitNames(), _mesa_InterleavedArrays(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_InvalidateFramebuffer(), _mesa_InvalidateSubFramebuffer(), _mesa_InvalidateTexImage(), _mesa_InvalidateTexSubImage(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_IsBuffer(), _mesa_IsEnabled(), _mesa_IsEnabledi(), _mesa_IsFramebuffer(), _mesa_IsList(), _mesa_IsProgram(), _mesa_IsProgramARB(), _mesa_IsQuery(), _mesa_IsRenderbuffer(), _mesa_IsSampler(), _mesa_IsShader(), _mesa_IsSync(), _mesa_IsTexture(), _mesa_IsTransformFeedback(), _mesa_IsVertexArray(), _mesa_Lightf(), _mesa_Lightfv(), _mesa_Lighti(), _mesa_Lightiv(), _mesa_LightModelf(), _mesa_LightModelfv(), _mesa_LightModeli(), _mesa_LightModeliv(), _mesa_LightModelx(), _mesa_LightModelxv(), _mesa_Lightx(), _mesa_Lightxv(), _mesa_LineStipple(), _mesa_LineWidth(), _mesa_LineWidthx(), _mesa_LinkProgram(), _mesa_ListBase(), _mesa_LoadIdentity(), _mesa_LoadMatrixd(), _mesa_LoadMatrixf(), _mesa_LoadMatrixx(), _mesa_LoadName(), _mesa_LoadTransposeMatrixd(), _mesa_LoadTransposeMatrixf(), _mesa_LockArraysEXT(), _mesa_LogicOp(), _mesa_Map1d(), _mesa_Map1f(), _mesa_Map2d(), _mesa_Map2f(), _mesa_MapBuffer(), _mesa_MapBufferRange(), _mesa_MapGrid1d(), _mesa_MapGrid1f(), _mesa_MapGrid2d(), _mesa_MapGrid2f(), _mesa_Materialf(), _mesa_Materiali(), _mesa_Materialiv(), _mesa_Materialx(), _mesa_Materialxv(), _mesa_MatrixMode(), _mesa_Minmax(), _mesa_MultiDrawArrays(), _mesa_MultiModeDrawArraysIBM(), _mesa_MultiModeDrawElementsIBM(), _mesa_MultiTexCoord1d(), _mesa_MultiTexCoord1dv(), _mesa_MultiTexCoord1i(), _mesa_MultiTexCoord1iv(), _mesa_MultiTexCoord1s(), _mesa_MultiTexCoord1sv(), _mesa_MultiTexCoord2d(), _mesa_MultiTexCoord2dv(), _mesa_MultiTexCoord2i(), _mesa_MultiTexCoord2iv(), _mesa_MultiTexCoord2s(), _mesa_MultiTexCoord2sv(), _mesa_MultiTexCoord3d(), _mesa_MultiTexCoord3dv(), _mesa_MultiTexCoord3i(), _mesa_MultiTexCoord3iv(), _mesa_MultiTexCoord3s(), _mesa_MultiTexCoord3sv(), _mesa_MultiTexCoord4d(), _mesa_MultiTexCoord4dv(), _mesa_MultiTexCoord4i(), _mesa_MultiTexCoord4iv(), _mesa_MultiTexCoord4s(), _mesa_MultiTexCoord4sv(), _mesa_MultiTexCoord4x(), _mesa_MultMatrixd(), _mesa_MultMatrixf(), _mesa_MultMatrixx(), _mesa_MultTransposeMatrixd(), _mesa_MultTransposeMatrixf(), _mesa_NewList(), _mesa_Normal3b(), _mesa_Normal3bv(), _mesa_Normal3d(), _mesa_Normal3dv(), _mesa_Normal3i(), _mesa_Normal3iv(), _mesa_Normal3s(), _mesa_Normal3sv(), _mesa_Normal3x(), _mesa_NormalPointer(), _mesa_NormalPointerEXT(), _mesa_ObjectPurgeableAPPLE(), _mesa_ObjectUnpurgeableAPPLE(), _mesa_Ortho(), _mesa_Orthof(), _mesa_Orthox(), _mesa_PassTexCoordATI(), _mesa_PassThrough(), _mesa_PauseTransformFeedback(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), _mesa_PixelMapusv(), _mesa_PixelStoref(), _mesa_PixelStorei(), _mesa_PixelTransferf(), _mesa_PixelTransferi(), _mesa_PixelZoom(), _mesa_PointParameterf(), _mesa_PointParameterfv(), _mesa_PointParameteri(), _mesa_PointParameteriv(), _mesa_PointParameterx(), _mesa_PointParameterxv(), _mesa_PointSize(), _mesa_PointSizePointerOES(), _mesa_PointSizex(), _mesa_PolygonMode(), _mesa_PolygonOffset(), _mesa_PolygonOffsetEXT(), _mesa_PolygonOffsetx(), _mesa_PolygonStipple(), _mesa_PopAttrib(), _mesa_PopClientAttrib(), _mesa_PopMatrix(), _mesa_PopName(), _mesa_PrimitiveRestartIndex(), _mesa_PrioritizeTextures(), _mesa_ProgramBinary(), _mesa_ProgramEnvParameter4dARB(), _mesa_ProgramEnvParameter4dvARB(), _mesa_ProgramEnvParameter4fARB(), _mesa_ProgramEnvParameter4fvARB(), _mesa_ProgramEnvParameters4fvEXT(), _mesa_ProgramLocalParameter4dARB(), _mesa_ProgramLocalParameter4dvARB(), _mesa_ProgramLocalParameter4fARB(), _mesa_ProgramLocalParameter4fvARB(), _mesa_ProgramLocalParameters4fvEXT(), _mesa_ProgramParameteri(), _mesa_ProgramStringARB(), _mesa_ProvokingVertex(), _mesa_PushAttrib(), _mesa_PushClientAttrib(), _mesa_PushMatrix(), _mesa_PushName(), _mesa_QueryCounter(), _mesa_QueryMatrixxOES(), _mesa_RasterPos2d(), _mesa_RasterPos2dv(), _mesa_RasterPos2f(), _mesa_RasterPos2fv(), _mesa_RasterPos2i(), _mesa_RasterPos2iv(), _mesa_RasterPos2s(), _mesa_RasterPos2sv(), _mesa_RasterPos3d(), _mesa_RasterPos3dv(), _mesa_RasterPos3f(), _mesa_RasterPos3fv(), _mesa_RasterPos3i(), _mesa_RasterPos3iv(), _mesa_RasterPos3s(), _mesa_RasterPos3sv(), _mesa_RasterPos4d(), _mesa_RasterPos4dv(), _mesa_RasterPos4f(), _mesa_RasterPos4fv(), _mesa_RasterPos4i(), _mesa_RasterPos4iv(), _mesa_RasterPos4s(), _mesa_RasterPos4sv(), _mesa_ReadBuffer(), _mesa_ReadnPixelsARB(), _mesa_ReadPixels(), _mesa_Rectd(), _mesa_Rectdv(), _mesa_Rectfv(), _mesa_Recti(), _mesa_Rectiv(), _mesa_Rects(), _mesa_Rectsv(), _mesa_ReleaseShaderCompiler(), _mesa_RenderbufferStorage(), _mesa_RenderbufferStorageMultisample(), _mesa_RenderMode(), _mesa_ResetHistogram(), _mesa_ResetMinmax(), _mesa_ResizeBuffersMESA(), _mesa_ResumeTransformFeedback(), _mesa_Rotated(), _mesa_Rotatef(), _mesa_Rotatex(), _mesa_SampleCoverage(), _mesa_SampleCoveragex(), _mesa_SampleMapATI(), _mesa_SampleMaski(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), _mesa_Scaled(), _mesa_Scalef(), _mesa_Scalex(), _mesa_Scissor(), _mesa_SecondaryColor3b(), _mesa_SecondaryColor3bv(), _mesa_SecondaryColor3d(), _mesa_SecondaryColor3dv(), _mesa_SecondaryColor3i(), _mesa_SecondaryColor3iv(), _mesa_SecondaryColor3s(), _mesa_SecondaryColor3sv(), _mesa_SecondaryColor3ub(), _mesa_SecondaryColor3ubv(), _mesa_SecondaryColor3ui(), _mesa_SecondaryColor3uiv(), _mesa_SecondaryColor3us(), _mesa_SecondaryColor3usv(), _mesa_SecondaryColorPointer(), _mesa_SelectBuffer(), _mesa_SeparableFilter2D(), _mesa_SetFragmentShaderConstantATI(), _mesa_ShadeModel(), _mesa_ShaderBinary(), _mesa_ShaderSource(), _mesa_StencilFunc(), _mesa_StencilFuncSeparate(), _mesa_StencilFuncSeparateATI(), _mesa_StencilMask(), _mesa_StencilMaskSeparate(), _mesa_StencilOp(), _mesa_StencilOpSeparate(), _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TexBumpParameterfvATI(), _mesa_TexBumpParameterivATI(), _mesa_TexCoord1d(), _mesa_TexCoord1dv(), _mesa_TexCoord1i(), _mesa_TexCoord1iv(), _mesa_TexCoord1s(), _mesa_TexCoord1sv(), _mesa_TexCoord2d(), _mesa_TexCoord2dv(), _mesa_TexCoord2i(), _mesa_TexCoord2iv(), _mesa_TexCoord2s(), _mesa_TexCoord2sv(), _mesa_TexCoord3d(), _mesa_TexCoord3dv(), _mesa_TexCoord3i(), _mesa_TexCoord3iv(), _mesa_TexCoord3s(), _mesa_TexCoord3sv(), _mesa_TexCoord4d(), _mesa_TexCoord4dv(), _mesa_TexCoord4i(), _mesa_TexCoord4iv(), _mesa_TexCoord4s(), _mesa_TexCoord4sv(), _mesa_TexCoordPointer(), _mesa_TexCoordPointerEXT(), _mesa_TexEnvf(), _mesa_TexEnvfv(), _mesa_TexEnvi(), _mesa_TexEnviv(), _mesa_TexEnvx(), _mesa_TexEnvxv(), _mesa_TexGend(), _mesa_TexGendv(), _mesa_TexGenf(), _mesa_TexGenfv(), _mesa_TexGeni(), _mesa_TexGeniv(), _mesa_TexGenxOES(), _mesa_TexGenxvOES(), _mesa_TexImage1D(), _mesa_TexImage2D(), _mesa_TexImage2DMultisample(), _mesa_TexImage3D(), _mesa_TexImage3DMultisample(), _mesa_TexParameterf(), _mesa_TexParameterfv(), _mesa_TexParameteri(), _mesa_TexParameterIiv(), _mesa_TexParameterIuiv(), _mesa_TexParameteriv(), _mesa_TexParameterx(), _mesa_TexParameterxv(), _mesa_TexStorage1D(), _mesa_TexStorage2D(), _mesa_TexStorage2DMultisample(), _mesa_TexStorage3D(), _mesa_TexStorage3DMultisample(), _mesa_TexSubImage1D(), _mesa_TexSubImage2D(), _mesa_TexSubImage3D(), _mesa_TextureBarrierNV(), _mesa_TextureStorage1DEXT(), _mesa_TextureStorage2DEXT(), _mesa_TextureStorage3DEXT(), _mesa_TransformFeedbackVaryings(), _mesa_Translated(), _mesa_Translatef(), _mesa_Translatex(), _mesa_Uniform1f(), _mesa_Uniform1fv(), _mesa_Uniform1i(), _mesa_Uniform1iv(), _mesa_Uniform1ui(), _mesa_Uniform1uiv(), _mesa_Uniform2f(), _mesa_Uniform2fv(), _mesa_Uniform2i(), _mesa_Uniform2iv(), _mesa_Uniform2ui(), _mesa_Uniform2uiv(), _mesa_Uniform3f(), _mesa_Uniform3fv(), _mesa_Uniform3i(), _mesa_Uniform3iv(), _mesa_Uniform3ui(), _mesa_Uniform3uiv(), _mesa_Uniform4f(), _mesa_Uniform4fv(), _mesa_Uniform4i(), _mesa_Uniform4iv(), _mesa_Uniform4ui(), _mesa_Uniform4uiv(), _mesa_UniformBlockBinding(), _mesa_UniformMatrix2fv(), _mesa_UniformMatrix2x3fv(), _mesa_UniformMatrix2x4fv(), _mesa_UniformMatrix3fv(), _mesa_UniformMatrix3x2fv(), _mesa_UniformMatrix3x4fv(), _mesa_UniformMatrix4fv(), _mesa_UniformMatrix4x2fv(), _mesa_UniformMatrix4x3fv(), _mesa_UnlockArraysEXT(), _mesa_UnmapBuffer(), _mesa_UseProgram(), _mesa_UseShaderProgramEXT(), _mesa_ValidateProgram(), _mesa_Vertex2d(), _mesa_Vertex2dv(), _mesa_Vertex2i(), _mesa_Vertex2iv(), _mesa_Vertex2s(), _mesa_Vertex2sv(), _mesa_Vertex3d(), _mesa_Vertex3dv(), _mesa_Vertex3i(), _mesa_Vertex3iv(), _mesa_Vertex3s(), _mesa_Vertex3sv(), _mesa_Vertex4d(), _mesa_Vertex4dv(), _mesa_Vertex4i(), _mesa_Vertex4iv(), _mesa_Vertex4s(), _mesa_Vertex4sv(), _mesa_VertexAttrib1d(), _mesa_VertexAttrib1dNV(), _mesa_VertexAttrib1dv(), _mesa_VertexAttrib1dvNV(), _mesa_VertexAttrib1s(), _mesa_VertexAttrib1sNV(), _mesa_VertexAttrib1sv(), _mesa_VertexAttrib1svNV(), _mesa_VertexAttrib2d(), _mesa_VertexAttrib2dNV(), _mesa_VertexAttrib2dv(), _mesa_VertexAttrib2dvNV(), _mesa_VertexAttrib2s(), _mesa_VertexAttrib2sNV(), _mesa_VertexAttrib2sv(), _mesa_VertexAttrib2svNV(), _mesa_VertexAttrib3d(), _mesa_VertexAttrib3dNV(), _mesa_VertexAttrib3dv(), _mesa_VertexAttrib3dvNV(), _mesa_VertexAttrib3s(), _mesa_VertexAttrib3sNV(), _mesa_VertexAttrib3sv(), _mesa_VertexAttrib3svNV(), _mesa_VertexAttrib4bv(), _mesa_VertexAttrib4d(), _mesa_VertexAttrib4dNV(), _mesa_VertexAttrib4dv(), _mesa_VertexAttrib4dvNV(), _mesa_VertexAttrib4iv(), _mesa_VertexAttrib4Nbv(), _mesa_VertexAttrib4Niv(), _mesa_VertexAttrib4Nsv(), _mesa_VertexAttrib4Nub(), _mesa_VertexAttrib4Nubv(), _mesa_VertexAttrib4Nuiv(), _mesa_VertexAttrib4Nusv(), _mesa_VertexAttrib4s(), _mesa_VertexAttrib4sNV(), _mesa_VertexAttrib4sv(), _mesa_VertexAttrib4svNV(), _mesa_VertexAttrib4ubNV(), _mesa_VertexAttrib4ubv(), _mesa_VertexAttrib4ubvNV(), _mesa_VertexAttrib4uiv(), _mesa_VertexAttrib4usv(), _mesa_VertexAttribDivisor(), _mesa_VertexAttribI1iv(), _mesa_VertexAttribI1uiv(), _mesa_VertexAttribI4bv(), _mesa_VertexAttribI4sv(), _mesa_VertexAttribI4ubv(), _mesa_VertexAttribI4usv(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_VertexAttribs1dvNV(), _mesa_VertexAttribs1fvNV(), _mesa_VertexAttribs1svNV(), _mesa_VertexAttribs2dvNV(), _mesa_VertexAttribs2fvNV(), _mesa_VertexAttribs2svNV(), _mesa_VertexAttribs3dvNV(), _mesa_VertexAttribs3fvNV(), _mesa_VertexAttribs3svNV(), _mesa_VertexAttribs4dvNV(), _mesa_VertexAttribs4fvNV(), _mesa_VertexAttribs4svNV(), _mesa_VertexAttribs4ubvNV(), _mesa_VertexPointer(), _mesa_VertexPointerEXT(), _mesa_Viewport(), _mesa_WaitSync(), _mesa_WindowPos2d(), _mesa_WindowPos2dv(), _mesa_WindowPos2f(), _mesa_WindowPos2fv(), _mesa_WindowPos2i(), _mesa_WindowPos2iv(), _mesa_WindowPos2s(), _mesa_WindowPos2sv(), _mesa_WindowPos3d(), _mesa_WindowPos3dv(), _mesa_WindowPos3f(), _mesa_WindowPos3fv(), _mesa_WindowPos3i(), _mesa_WindowPos3iv(), _mesa_WindowPos3s(), _mesa_WindowPos3sv(), _mesa_WindowPos4dMESA(), _mesa_WindowPos4dvMESA(), _mesa_WindowPos4fMESA(), _mesa_WindowPos4fvMESA(), _mesa_WindowPos4iMESA(), _mesa_WindowPos4ivMESA(), _mesa_WindowPos4sMESA(), _mesa_WindowPos4svMESA(), gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, API_OPENGLES2, gl_context::Exec, NULL, SET_Accum(), SET_ActiveProgramEXT(), SET_ActiveStencilFaceEXT(), SET_ActiveTexture(), SET_AlphaFragmentOp1ATI(), SET_AlphaFragmentOp2ATI(), SET_AlphaFragmentOp3ATI(), SET_AlphaFunc(), SET_AlphaFuncx(), SET_AreTexturesResident(), SET_AttachObjectARB(), SET_AttachShader(), SET_BeginConditionalRender(), SET_BeginFragmentShaderATI(), SET_BeginQuery(), SET_BeginQueryIndexed(), SET_BeginTransformFeedback(), SET_BindAttribLocation(), SET_BindBuffer(), SET_BindBufferBase(), SET_BindBufferOffsetEXT(), SET_BindBufferRange(), SET_BindFragDataLocation(), SET_BindFragDataLocationIndexed(), SET_BindFragmentShaderATI(), SET_BindFramebuffer(), SET_BindProgramARB(), SET_BindRenderbuffer(), SET_BindSampler(), SET_BindTexture(), SET_BindTransformFeedback(), SET_BindVertexArray(), SET_BindVertexArrayAPPLE(), SET_Bitmap(), SET_BlendColor(), SET_BlendEquation(), SET_BlendEquationiARB(), SET_BlendEquationSeparate(), SET_BlendEquationSeparateiARB(), SET_BlendFunc(), SET_BlendFunciARB(), SET_BlendFuncSeparate(), SET_BlendFuncSeparateiARB(), SET_BlitFramebuffer(), SET_BufferData(), SET_BufferSubData(), SET_CallList(), SET_CallLists(), SET_CheckFramebufferStatus(), SET_ClampColor(), SET_Clear(), SET_ClearAccum(), SET_ClearBufferfi(), SET_ClearBufferfv(), SET_ClearBufferiv(), SET_ClearBufferuiv(), SET_ClearColor(), SET_ClearColorIiEXT(), SET_ClearColorIuiEXT(), SET_ClearColorx(), SET_ClearDepth(), SET_ClearDepthf(), SET_ClearDepthx(), SET_ClearIndex(), SET_ClearStencil(), SET_ClientActiveTexture(), SET_ClientWaitSync(), SET_ClipPlane(), SET_ClipPlanef(), SET_ClipPlanex(), SET_Color3b(), SET_Color3bv(), SET_Color3d(), SET_Color3dv(), SET_Color3i(), SET_Color3iv(), SET_Color3s(), SET_Color3sv(), SET_Color3ub(), SET_Color3ubv(), SET_Color3ui(), SET_Color3uiv(), SET_Color3us(), SET_Color3usv(), SET_Color4b(), SET_Color4bv(), SET_Color4d(), SET_Color4dv(), SET_Color4i(), SET_Color4iv(), SET_Color4s(), SET_Color4sv(), SET_Color4ub(), SET_Color4ubv(), SET_Color4ui(), SET_Color4uiv(), SET_Color4us(), SET_Color4usv(), SET_Color4x(), SET_ColorFragmentOp1ATI(), SET_ColorFragmentOp2ATI(), SET_ColorFragmentOp3ATI(), SET_ColorMask(), SET_ColorMaski(), SET_ColorMaterial(), SET_ColorPointer(), SET_ColorPointerEXT(), SET_ColorSubTable(), SET_ColorTable(), SET_ColorTableParameterfv(), SET_ColorTableParameteriv(), SET_CompileShader(), SET_CompressedTexImage1D(), SET_CompressedTexImage2D(), SET_CompressedTexImage3D(), SET_CompressedTexSubImage1D(), SET_CompressedTexSubImage2D(), SET_CompressedTexSubImage3D(), SET_ConvolutionFilter1D(), SET_ConvolutionFilter2D(), SET_ConvolutionParameterf(), SET_ConvolutionParameterfv(), SET_ConvolutionParameteri(), SET_ConvolutionParameteriv(), SET_CopyBufferSubData(), SET_CopyColorSubTable(), SET_CopyColorTable(), SET_CopyConvolutionFilter1D(), SET_CopyConvolutionFilter2D(), SET_CopyPixels(), SET_CopyTexImage1D(), SET_CopyTexImage2D(), SET_CopyTexSubImage1D(), SET_CopyTexSubImage2D(), SET_CopyTexSubImage3D(), SET_CreateProgram(), SET_CreateProgramObjectARB(), SET_CreateShader(), SET_CreateShaderObjectARB(), SET_CreateShaderProgramEXT(), SET_CullFace(), SET_DebugMessageCallbackARB(), SET_DebugMessageControlARB(), SET_DebugMessageInsertARB(), SET_DeleteBuffers(), SET_DeleteFragmentShaderATI(), SET_DeleteFramebuffers(), SET_DeleteLists(), SET_DeleteObjectARB(), SET_DeleteProgram(), SET_DeleteProgramsARB(), SET_DeleteQueries(), SET_DeleteRenderbuffers(), SET_DeleteSamplers(), SET_DeleteShader(), SET_DeleteSync(), SET_DeleteTextures(), SET_DeleteTransformFeedbacks(), SET_DeleteVertexArrays(), SET_DepthBoundsEXT(), SET_DepthFunc(), SET_DepthMask(), SET_DepthRange(), SET_DepthRangef(), SET_DepthRangex(), SET_DetachObjectARB(), SET_DetachShader(), SET_Disable(), SET_DisableClientState(), SET_Disablei(), SET_DisableVertexAttribArray(), SET_DiscardFramebufferEXT(), SET_DrawBuffer(), SET_DrawBuffers(), SET_DrawPixels(), SET_DrawTexfOES(), SET_DrawTexfvOES(), SET_DrawTexiOES(), SET_DrawTexivOES(), SET_DrawTexsOES(), SET_DrawTexsvOES(), SET_DrawTexxOES(), SET_DrawTexxvOES(), SET_EdgeFlagPointer(), SET_EdgeFlagPointerEXT(), SET_EdgeFlagv(), SET_EGLImageTargetRenderbufferStorageOES(), SET_EGLImageTargetTexture2DOES(), SET_Enable(), SET_EnableClientState(), SET_Enablei(), SET_EnableVertexAttribArray(), SET_EndConditionalRender(), SET_EndFragmentShaderATI(), SET_EndList(), SET_EndQuery(), SET_EndQueryIndexed(), SET_EndTransformFeedback(), SET_EvalCoord1d(), SET_EvalCoord1dv(), SET_EvalCoord1fv(), SET_EvalCoord2d(), SET_EvalCoord2dv(), SET_EvalCoord2fv(), SET_FeedbackBuffer(), SET_FenceSync(), SET_Finish(), SET_Flush(), SET_FlushMappedBufferRange(), SET_FogCoordd(), SET_FogCoorddv(), SET_FogCoordPointer(), SET_Fogf(), SET_Fogfv(), SET_Fogi(), SET_Fogiv(), SET_Fogx(), SET_Fogxv(), SET_FramebufferRenderbuffer(), SET_FramebufferTexture(), SET_FramebufferTexture1D(), SET_FramebufferTexture2D(), SET_FramebufferTexture3D(), SET_FramebufferTextureLayer(), SET_FrontFace(), SET_Frustum(), SET_Frustumf(), SET_Frustumx(), SET_GenBuffers(), SET_GenerateMipmap(), SET_GenFragmentShadersATI(), SET_GenFramebuffers(), SET_GenLists(), SET_GenProgramsARB(), SET_GenQueries(), SET_GenRenderbuffers(), SET_GenSamplers(), SET_GenTextures(), SET_GenTransformFeedbacks(), SET_GenVertexArrays(), SET_GenVertexArraysAPPLE(), SET_GetActiveAttrib(), SET_GetActiveUniform(), SET_GetActiveUniformBlockiv(), SET_GetActiveUniformBlockName(), SET_GetActiveUniformName(), SET_GetActiveUniformsiv(), SET_GetAttachedObjectsARB(), SET_GetAttachedShaders(), SET_GetAttribLocation(), SET_GetBooleani_v(), SET_GetBooleanv(), SET_GetBufferParameteri64v(), SET_GetBufferParameteriv(), SET_GetBufferPointerv(), SET_GetBufferSubData(), SET_GetClipPlane(), SET_GetClipPlanef(), SET_GetClipPlanex(), SET_GetColorTable(), SET_GetColorTableParameterfv(), SET_GetColorTableParameteriv(), SET_GetCompressedTexImage(), SET_GetConvolutionFilter(), SET_GetConvolutionParameterfv(), SET_GetConvolutionParameteriv(), SET_GetDebugMessageLogARB(), SET_GetDoublev(), SET_GetError(), SET_GetFixedv(), SET_GetFloatv(), SET_GetFragDataIndex(), SET_GetFragDataLocation(), SET_GetFramebufferAttachmentParameteriv(), SET_GetGraphicsResetStatusARB(), SET_GetHandleARB(), SET_GetHistogram(), SET_GetHistogramParameterfv(), SET_GetHistogramParameteriv(), SET_GetInfoLogARB(), SET_GetInteger64i_v(), SET_GetInteger64v(), SET_GetIntegeri_v(), SET_GetIntegerv(), SET_GetInternalformativ(), SET_GetLightfv(), SET_GetLightiv(), SET_GetLightxv(), SET_GetMapdv(), SET_GetMapfv(), SET_GetMapiv(), SET_GetMaterialfv(), SET_GetMaterialiv(), SET_GetMaterialxv(), SET_GetMinmax(), SET_GetMinmaxParameterfv(), SET_GetMinmaxParameteriv(), SET_GetMultisamplefv(), SET_GetnColorTableARB(), SET_GetnCompressedTexImageARB(), SET_GetnConvolutionFilterARB(), SET_GetnHistogramARB(), SET_GetnMapdvARB(), SET_GetnMapfvARB(), SET_GetnMapivARB(), SET_GetnMinmaxARB(), SET_GetnPixelMapfvARB(), SET_GetnPixelMapuivARB(), SET_GetnPixelMapusvARB(), SET_GetnPolygonStippleARB(), SET_GetnSeparableFilterARB(), SET_GetnTexImageARB(), SET_GetnUniformdvARB(), SET_GetnUniformfvARB(), SET_GetnUniformivARB(), SET_GetnUniformuivARB(), SET_GetObjectParameterfvARB(), SET_GetObjectParameterivAPPLE(), SET_GetObjectParameterivARB(), SET_GetPixelMapfv(), SET_GetPixelMapuiv(), SET_GetPixelMapusv(), SET_GetPointerv(), SET_GetPolygonStipple(), SET_GetProgramBinary(), SET_GetProgramEnvParameterdvARB(), SET_GetProgramEnvParameterfvARB(), SET_GetProgramInfoLog(), SET_GetProgramiv(), SET_GetProgramivARB(), SET_GetProgramLocalParameterdvARB(), SET_GetProgramLocalParameterfvARB(), SET_GetProgramStringARB(), SET_GetQueryIndexediv(), SET_GetQueryiv(), SET_GetQueryObjecti64v(), SET_GetQueryObjectiv(), SET_GetQueryObjectui64v(), SET_GetQueryObjectuiv(), SET_GetRenderbufferParameteriv(), SET_GetSamplerParameterfv(), SET_GetSamplerParameterIiv(), SET_GetSamplerParameterIuiv(), SET_GetSamplerParameteriv(), SET_GetSeparableFilter(), SET_GetShaderInfoLog(), SET_GetShaderiv(), SET_GetShaderPrecisionFormat(), SET_GetShaderSource(), SET_GetString(), SET_GetStringi(), SET_GetSynciv(), SET_GetTexBumpParameterfvATI(), SET_GetTexBumpParameterivATI(), SET_GetTexEnvfv(), SET_GetTexEnviv(), SET_GetTexEnvxv(), SET_GetTexGendv(), SET_GetTexGenfv(), SET_GetTexGeniv(), SET_GetTexGenxvOES(), SET_GetTexImage(), SET_GetTexLevelParameterfv(), SET_GetTexLevelParameteriv(), SET_GetTexParameterfv(), SET_GetTexParameterIiv(), SET_GetTexParameterIuiv(), SET_GetTexParameteriv(), SET_GetTexParameterxv(), SET_GetTransformFeedbackVarying(), SET_GetUniformBlockIndex(), SET_GetUniformfv(), SET_GetUniformIndices(), SET_GetUniformiv(), SET_GetUniformLocation(), SET_GetUniformuiv(), SET_GetVertexAttribdv(), SET_GetVertexAttribfv(), SET_GetVertexAttribIiv(), SET_GetVertexAttribIuiv(), SET_GetVertexAttribiv(), SET_GetVertexAttribPointerv(), SET_Hint(), SET_Histogram(), SET_Indexd(), SET_Indexdv(), SET_Indexi(), SET_Indexiv(), SET_IndexMask(), SET_IndexPointer(), SET_IndexPointerEXT(), SET_Indexs(), SET_Indexsv(), SET_Indexub(), SET_Indexubv(), SET_InitNames(), SET_InterleavedArrays(), SET_InvalidateBufferData(), SET_InvalidateBufferSubData(), SET_InvalidateFramebuffer(), SET_InvalidateSubFramebuffer(), SET_InvalidateTexImage(), SET_InvalidateTexSubImage(), SET_IsBuffer(), SET_IsEnabled(), SET_IsEnabledi(), SET_IsFramebuffer(), SET_IsList(), SET_IsProgram(), SET_IsProgramARB(), SET_IsQuery(), SET_IsRenderbuffer(), SET_IsSampler(), SET_IsShader(), SET_IsSync(), SET_IsTexture(), SET_IsTransformFeedback(), SET_IsVertexArray(), SET_Lightf(), SET_Lightfv(), SET_Lighti(), SET_Lightiv(), SET_LightModelf(), SET_LightModelfv(), SET_LightModeli(), SET_LightModeliv(), SET_LightModelx(), SET_LightModelxv(), SET_Lightx(), SET_Lightxv(), SET_LineStipple(), SET_LineWidth(), SET_LineWidthx(), SET_LinkProgram(), SET_ListBase(), SET_LoadIdentity(), SET_LoadMatrixd(), SET_LoadMatrixf(), SET_LoadMatrixx(), SET_LoadName(), SET_LoadTransposeMatrixd(), SET_LoadTransposeMatrixf(), SET_LockArraysEXT(), SET_LogicOp(), SET_Map1d(), SET_Map1f(), SET_Map2d(), SET_Map2f(), SET_MapBuffer(), SET_MapBufferRange(), SET_MapGrid1d(), SET_MapGrid1f(), SET_MapGrid2d(), SET_MapGrid2f(), SET_Materialf(), SET_Materiali(), SET_Materialiv(), SET_Materialx(), SET_Materialxv(), SET_MatrixMode(), SET_Minmax(), SET_MultiDrawArrays(), SET_MultiModeDrawArraysIBM(), SET_MultiModeDrawElementsIBM(), SET_MultiTexCoord1d(), SET_MultiTexCoord1dv(), SET_MultiTexCoord1i(), SET_MultiTexCoord1iv(), SET_MultiTexCoord1s(), SET_MultiTexCoord1sv(), SET_MultiTexCoord2d(), SET_MultiTexCoord2dv(), SET_MultiTexCoord2i(), SET_MultiTexCoord2iv(), SET_MultiTexCoord2s(), SET_MultiTexCoord2sv(), SET_MultiTexCoord3d(), SET_MultiTexCoord3dv(), SET_MultiTexCoord3i(), SET_MultiTexCoord3iv(), SET_MultiTexCoord3s(), SET_MultiTexCoord3sv(), SET_MultiTexCoord4d(), SET_MultiTexCoord4dv(), SET_MultiTexCoord4i(), SET_MultiTexCoord4iv(), SET_MultiTexCoord4s(), SET_MultiTexCoord4sv(), SET_MultiTexCoord4x(), SET_MultMatrixd(), SET_MultMatrixf(), SET_MultMatrixx(), SET_MultTransposeMatrixd(), SET_MultTransposeMatrixf(), SET_NewList(), SET_Normal3b(), SET_Normal3bv(), SET_Normal3d(), SET_Normal3dv(), SET_Normal3i(), SET_Normal3iv(), SET_Normal3s(), SET_Normal3sv(), SET_Normal3x(), SET_NormalPointer(), SET_NormalPointerEXT(), SET_ObjectPurgeableAPPLE(), SET_ObjectUnpurgeableAPPLE(), SET_Ortho(), SET_Orthof(), SET_Orthox(), SET_PassTexCoordATI(), SET_PassThrough(), SET_PauseTransformFeedback(), SET_PixelMapfv(), SET_PixelMapuiv(), SET_PixelMapusv(), SET_PixelStoref(), SET_PixelStorei(), SET_PixelTransferf(), SET_PixelTransferi(), SET_PixelZoom(), SET_PointParameterf(), SET_PointParameterfv(), SET_PointParameteri(), SET_PointParameteriv(), SET_PointParameterx(), SET_PointParameterxv(), SET_PointSize(), SET_PointSizePointerOES(), SET_PointSizex(), SET_PolygonMode(), SET_PolygonOffset(), SET_PolygonOffsetEXT(), SET_PolygonOffsetx(), SET_PolygonStipple(), SET_PopAttrib(), SET_PopClientAttrib(), SET_PopMatrix(), SET_PopName(), SET_PrimitiveRestartIndex(), SET_PrioritizeTextures(), SET_ProgramBinary(), SET_ProgramEnvParameter4dARB(), SET_ProgramEnvParameter4dvARB(), SET_ProgramEnvParameter4fARB(), SET_ProgramEnvParameter4fvARB(), SET_ProgramEnvParameters4fvEXT(), SET_ProgramLocalParameter4dARB(), SET_ProgramLocalParameter4dvARB(), SET_ProgramLocalParameter4fARB(), SET_ProgramLocalParameter4fvARB(), SET_ProgramLocalParameters4fvEXT(), SET_ProgramParameteri(), SET_ProgramStringARB(), SET_ProvokingVertex(), SET_PushAttrib(), SET_PushClientAttrib(), SET_PushMatrix(), SET_PushName(), SET_QueryCounter(), SET_QueryMatrixxOES(), SET_RasterPos2d(), SET_RasterPos2dv(), SET_RasterPos2f(), SET_RasterPos2fv(), SET_RasterPos2i(), SET_RasterPos2iv(), SET_RasterPos2s(), SET_RasterPos2sv(), SET_RasterPos3d(), SET_RasterPos3dv(), SET_RasterPos3f(), SET_RasterPos3fv(), SET_RasterPos3i(), SET_RasterPos3iv(), SET_RasterPos3s(), SET_RasterPos3sv(), SET_RasterPos4d(), SET_RasterPos4dv(), SET_RasterPos4f(), SET_RasterPos4fv(), SET_RasterPos4i(), SET_RasterPos4iv(), SET_RasterPos4s(), SET_RasterPos4sv(), SET_ReadBuffer(), SET_ReadnPixelsARB(), SET_ReadPixels(), SET_Rectd(), SET_Rectdv(), SET_Rectfv(), SET_Recti(), SET_Rectiv(), SET_Rects(), SET_Rectsv(), SET_ReleaseShaderCompiler(), SET_RenderbufferStorage(), SET_RenderbufferStorageMultisample(), SET_RenderMode(), SET_ResetHistogram(), SET_ResetMinmax(), SET_ResizeBuffersMESA(), SET_ResumeTransformFeedback(), SET_Rotated(), SET_Rotatef(), SET_Rotatex(), SET_SampleCoverage(), SET_SampleCoveragex(), SET_SampleMapATI(), SET_SampleMaski(), SET_SamplerParameterf(), SET_SamplerParameterfv(), SET_SamplerParameteri(), SET_SamplerParameterIiv(), SET_SamplerParameterIuiv(), SET_SamplerParameteriv(), SET_Scaled(), SET_Scalef(), SET_Scalex(), SET_Scissor(), SET_SecondaryColor3b(), SET_SecondaryColor3bv(), SET_SecondaryColor3d(), SET_SecondaryColor3dv(), SET_SecondaryColor3i(), SET_SecondaryColor3iv(), SET_SecondaryColor3s(), SET_SecondaryColor3sv(), SET_SecondaryColor3ub(), SET_SecondaryColor3ubv(), SET_SecondaryColor3ui(), SET_SecondaryColor3uiv(), SET_SecondaryColor3us(), SET_SecondaryColor3usv(), SET_SecondaryColorPointer(), SET_SelectBuffer(), SET_SeparableFilter2D(), SET_SetFragmentShaderConstantATI(), SET_ShadeModel(), SET_ShaderBinary(), SET_ShaderSource(), SET_StencilFunc(), SET_StencilFuncSeparate(), SET_StencilFuncSeparateATI(), SET_StencilMask(), SET_StencilMaskSeparate(), SET_StencilOp(), SET_StencilOpSeparate(), SET_TexBuffer(), SET_TexBufferRange(), SET_TexBumpParameterfvATI(), SET_TexBumpParameterivATI(), SET_TexCoord1d(), SET_TexCoord1dv(), SET_TexCoord1i(), SET_TexCoord1iv(), SET_TexCoord1s(), SET_TexCoord1sv(), SET_TexCoord2d(), SET_TexCoord2dv(), SET_TexCoord2i(), SET_TexCoord2iv(), SET_TexCoord2s(), SET_TexCoord2sv(), SET_TexCoord3d(), SET_TexCoord3dv(), SET_TexCoord3i(), SET_TexCoord3iv(), SET_TexCoord3s(), SET_TexCoord3sv(), SET_TexCoord4d(), SET_TexCoord4dv(), SET_TexCoord4i(), SET_TexCoord4iv(), SET_TexCoord4s(), SET_TexCoord4sv(), SET_TexCoordPointer(), SET_TexCoordPointerEXT(), SET_TexEnvf(), SET_TexEnvfv(), SET_TexEnvi(), SET_TexEnviv(), SET_TexEnvx(), SET_TexEnvxv(), SET_TexGend(), SET_TexGendv(), SET_TexGenf(), SET_TexGenfv(), SET_TexGeni(), SET_TexGeniv(), SET_TexGenxOES(), SET_TexGenxvOES(), SET_TexImage1D(), SET_TexImage2D(), SET_TexImage2DMultisample(), SET_TexImage3D(), SET_TexImage3DMultisample(), SET_TexParameterf(), SET_TexParameterfv(), SET_TexParameteri(), SET_TexParameterIiv(), SET_TexParameterIuiv(), SET_TexParameteriv(), SET_TexParameterx(), SET_TexParameterxv(), SET_TexStorage1D(), SET_TexStorage2D(), SET_TexStorage2DMultisample(), SET_TexStorage3D(), SET_TexStorage3DMultisample(), SET_TexSubImage1D(), SET_TexSubImage2D(), SET_TexSubImage3D(), SET_TextureBarrierNV(), SET_TextureStorage1DEXT(), SET_TextureStorage2DEXT(), SET_TextureStorage3DEXT(), SET_TransformFeedbackVaryings(), SET_Translated(), SET_Translatef(), SET_Translatex(), SET_Uniform1f(), SET_Uniform1fv(), SET_Uniform1i(), SET_Uniform1iv(), SET_Uniform1ui(), SET_Uniform1uiv(), SET_Uniform2f(), SET_Uniform2fv(), SET_Uniform2i(), SET_Uniform2iv(), SET_Uniform2ui(), SET_Uniform2uiv(), SET_Uniform3f(), SET_Uniform3fv(), SET_Uniform3i(), SET_Uniform3iv(), SET_Uniform3ui(), SET_Uniform3uiv(), SET_Uniform4f(), SET_Uniform4fv(), SET_Uniform4i(), SET_Uniform4iv(), SET_Uniform4ui(), SET_Uniform4uiv(), SET_UniformBlockBinding(), SET_UniformMatrix2fv(), SET_UniformMatrix2x3fv(), SET_UniformMatrix2x4fv(), SET_UniformMatrix3fv(), SET_UniformMatrix3x2fv(), SET_UniformMatrix3x4fv(), SET_UniformMatrix4fv(), SET_UniformMatrix4x2fv(), SET_UniformMatrix4x3fv(), SET_UnlockArraysEXT(), SET_UnmapBuffer(), SET_UseProgram(), SET_UseShaderProgramEXT(), SET_ValidateProgram(), SET_Vertex2d(), SET_Vertex2dv(), SET_Vertex2i(), SET_Vertex2iv(), SET_Vertex2s(), SET_Vertex2sv(), SET_Vertex3d(), SET_Vertex3dv(), SET_Vertex3i(), SET_Vertex3iv(), SET_Vertex3s(), SET_Vertex3sv(), SET_Vertex4d(), SET_Vertex4dv(), SET_Vertex4i(), SET_Vertex4iv(), SET_Vertex4s(), SET_Vertex4sv(), SET_VertexAttrib1d(), SET_VertexAttrib1dNV(), SET_VertexAttrib1dv(), SET_VertexAttrib1dvNV(), SET_VertexAttrib1s(), SET_VertexAttrib1sNV(), SET_VertexAttrib1sv(), SET_VertexAttrib1svNV(), SET_VertexAttrib2d(), SET_VertexAttrib2dNV(), SET_VertexAttrib2dv(), SET_VertexAttrib2dvNV(), SET_VertexAttrib2s(), SET_VertexAttrib2sNV(), SET_VertexAttrib2sv(), SET_VertexAttrib2svNV(), SET_VertexAttrib3d(), SET_VertexAttrib3dNV(), SET_VertexAttrib3dv(), SET_VertexAttrib3dvNV(), SET_VertexAttrib3s(), SET_VertexAttrib3sNV(), SET_VertexAttrib3sv(), SET_VertexAttrib3svNV(), SET_VertexAttrib4bv(), SET_VertexAttrib4d(), SET_VertexAttrib4dNV(), SET_VertexAttrib4dv(), SET_VertexAttrib4dvNV(), SET_VertexAttrib4iv(), SET_VertexAttrib4Nbv(), SET_VertexAttrib4Niv(), SET_VertexAttrib4Nsv(), SET_VertexAttrib4Nub(), SET_VertexAttrib4Nubv(), SET_VertexAttrib4Nuiv(), SET_VertexAttrib4Nusv(), SET_VertexAttrib4s(), SET_VertexAttrib4sNV(), SET_VertexAttrib4sv(), SET_VertexAttrib4svNV(), SET_VertexAttrib4ubNV(), SET_VertexAttrib4ubv(), SET_VertexAttrib4ubvNV(), SET_VertexAttrib4uiv(), SET_VertexAttrib4usv(), SET_VertexAttribDivisor(), SET_VertexAttribI1iv(), SET_VertexAttribI1uiv(), SET_VertexAttribI4bv(), SET_VertexAttribI4sv(), SET_VertexAttribI4ubv(), SET_VertexAttribI4usv(), SET_VertexAttribIPointer(), SET_VertexAttribPointer(), SET_VertexAttribs1dvNV(), SET_VertexAttribs1fvNV(), SET_VertexAttribs1svNV(), SET_VertexAttribs2dvNV(), SET_VertexAttribs2fvNV(), SET_VertexAttribs2svNV(), SET_VertexAttribs3dvNV(), SET_VertexAttribs3fvNV(), SET_VertexAttribs3svNV(), SET_VertexAttribs4dvNV(), SET_VertexAttribs4fvNV(), SET_VertexAttribs4svNV(), SET_VertexAttribs4ubvNV(), SET_VertexPointer(), SET_VertexPointerEXT(), SET_Viewport(), SET_WaitSync(), SET_WindowPos2d(), SET_WindowPos2dv(), SET_WindowPos2f(), SET_WindowPos2fv(), SET_WindowPos2i(), SET_WindowPos2iv(), SET_WindowPos2s(), SET_WindowPos2sv(), SET_WindowPos3d(), SET_WindowPos3dv(), SET_WindowPos3f(), SET_WindowPos3fv(), SET_WindowPos3i(), SET_WindowPos3iv(), SET_WindowPos3s(), SET_WindowPos3sv(), SET_WindowPos4dMESA(), SET_WindowPos4dvMESA(), SET_WindowPos4fMESA(), SET_WindowPos4fvMESA(), SET_WindowPos4iMESA(), SET_WindowPos4ivMESA(), SET_WindowPos4sMESA(), SET_WindowPos4svMESA(), vbo_initialize_exec_dispatch(), and gl_context::Version.
Referenced by _mesa_initialize_dispatch_tables().