Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
api_validate.c File Reference
#include <stdbool.h>
#include "glheader.h"
#include "api_validate.h"
#include "bufferobj.h"
#include "context.h"
#include "imports.h"
#include "mtypes.h"
#include "enums.h"
#include "vbo/vbo.h"
#include "transformfeedback.h"
Functions
static GLsizei index_bytes (GLenum type, GLsizei count)
GLuint _mesa_max_buffer_index (struct gl_context *ctx, GLuint count, GLenum type, const void *indices, struct gl_buffer_object *elementBuf)
Find the max index in the given element/index buffer.
static GLboolean check_valid_to_render (struct gl_context *ctx, const char *function)
Check if OK to draw arrays/elements.
static GLboolean check_index_bounds (struct gl_context *ctx, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
Do bounds checking on array element indexes.
bool _mesa_is_valid_prim_mode (struct gl_context *ctx, GLenum mode)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? The set of legal values depends on whether geometry shaders/programs are supported.
GLboolean _mesa_valid_prim_mode (struct gl_context *ctx, GLenum mode, const char *name)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? Also, do additional checking related to transformation feedback.
static bool valid_elements_type (struct gl_context *ctx, GLenum type, const char *name)
Verify that the element type is valid.
GLboolean _mesa_validate_DrawElements (struct gl_context *ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
Error checking for glDrawElements().
GLboolean _mesa_validate_MultiDrawElements (struct gl_context *ctx, GLenum mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLuint primcount, const GLint *basevertex)
Error checking for glMultiDrawElements().
GLboolean _mesa_validate_DrawRangeElements (struct gl_context *ctx, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex)
Error checking for glDrawRangeElements().
GLboolean _mesa_validate_DrawArrays (struct gl_context *ctx, GLenum mode, GLint start, GLsizei count)
Called from the tnl module to error check the function parameters and verify that we really can draw something.
GLboolean _mesa_validate_DrawArraysInstanced (struct gl_context *ctx, GLenum mode, GLint first, GLsizei count, GLsizei numInstances)
GLboolean _mesa_validate_DrawElementsInstanced (struct gl_context *ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei numInstances, GLint basevertex)
GLboolean _mesa_validate_DrawTransformFeedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj, GLuint stream, GLsizei numInstances)
Function Documentation
bool _mesa_is_valid_prim_mode (struct gl_context * ctx, GLenum mode)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? The set of legal values depends on whether geometry shaders/programs are supported.
Note: This may be called during display list compilation.
References _mesa_is_desktop_gl(), gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_geometry_shader4, and gl_context::Extensions.
Referenced by _mesa_valid_prim_mode(), and save_Begin().
GLuint _mesa_max_buffer_index (struct gl_context * ctx, GLuint count, GLenum type, const void * indices, struct gl_buffer_object * elementBuf)
Find the max index in the given element/index buffer.
References _mesa_is_bufferobj(), ADD_POINTERS, ASSERT, gl_context::Driver, GLubyte, GLushort, dd_function_table::MapBufferRange, NULL, gl_buffer_object::Size, and dd_function_table::UnmapBuffer.
GLboolean _mesa_valid_prim_mode (struct gl_context * ctx, GLenum mode, const char * name)
Is 'mode' a valid value for glBegin(), glDrawArrays(), glDrawElements(), etc? Also, do additional checking related to transformation feedback.
Note: this function cannot be called during glNewList(GL_COMPILE) because this code depends on current transform feedback state.
References _mesa_error(), _mesa_is_valid_prim_mode(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_prim_by_nr(), gl_transform_feedback_state::Mode, and gl_context::TransformFeedback.
Referenced by _mesa_validate_DrawArrays(), _mesa_validate_DrawArraysInstanced(), _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), _mesa_validate_DrawTransformFeedback(), and _mesa_validate_MultiDrawElements().
GLboolean _mesa_validate_DrawArrays (struct gl_context * ctx, GLenum mode, GLint start, GLsizei count)
Called from the tnl module to error check the function parameters and verify that we really can draw something.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References gl_array_object::_MaxElement, _mesa_error(), _mesa_is_gles3(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), gl_context::Array, gl_array_attrib::ArrayObj, check_valid_to_render(), gl_constants::CheckArrayBounds, gl_context::Const, gl_transform_feedback_state::CurrentObject, FLUSH_CURRENT, gl_transform_feedback_object::GlesRemainingPrims, gl_context::TransformFeedback, and vbo_count_tessellated_primitives().
GLboolean _mesa_validate_DrawArraysInstanced (struct gl_context * ctx, GLenum mode, GLint first, GLsizei count, GLsizei numInstances)
References gl_array_object::_MaxElement, _mesa_error(), _mesa_is_gles3(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), gl_context::Array, gl_array_attrib::ArrayObj, check_valid_to_render(), gl_constants::CheckArrayBounds, gl_context::Const, gl_transform_feedback_state::CurrentObject, FLUSH_CURRENT, gl_transform_feedback_object::GlesRemainingPrims, gl_context::TransformFeedback, and vbo_count_tessellated_primitives().
GLboolean _mesa_validate_DrawElements (struct gl_context * ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex)
Error checking for glDrawElements().
Includes parameter checking and VBO bounds checking.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_gles3(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), _mesa_warning(), gl_context::Array, gl_array_attrib::ArrayObj, check_index_bounds(), check_valid_to_render(), gl_array_object::ElementArrayBufferObj, FLUSH_CURRENT, index_bytes(), gl_buffer_object::Size, and valid_elements_type().
GLboolean _mesa_validate_DrawElementsInstanced (struct gl_context * ctx, GLenum mode, GLsizei count, GLenum type, const GLvoid * indices, GLsizei numInstances, GLint basevertex)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_gles3(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), _mesa_warning(), gl_context::Array, gl_array_attrib::ArrayObj, check_index_bounds(), check_valid_to_render(), gl_array_object::ElementArrayBufferObj, FLUSH_CURRENT, index_bytes(), gl_buffer_object::Size, and valid_elements_type().
GLboolean _mesa_validate_DrawRangeElements (struct gl_context * ctx, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex)
Error checking for glDrawRangeElements().
Includes parameter checking and VBO bounds checking.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_gles3(), _mesa_is_xfb_active_and_unpaused(), _mesa_valid_prim_mode(), _mesa_warning(), gl_context::Array, gl_array_attrib::ArrayObj, check_index_bounds(), check_valid_to_render(), gl_array_object::ElementArrayBufferObj, FLUSH_CURRENT, index_bytes(), gl_buffer_object::Size, and valid_elements_type().
GLboolean _mesa_validate_DrawTransformFeedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj, GLuint stream, GLsizei numInstances)
References _mesa_error(), _mesa_valid_prim_mode(), check_valid_to_render(), gl_context::Const, gl_transform_feedback_object::EndedAnytime, FLUSH_CURRENT, and gl_constants::MaxVertexStreams.
GLboolean _mesa_validate_MultiDrawElements (struct gl_context * ctx, GLenum mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLuint primcount, const GLint * basevertex)
Error checking for glMultiDrawElements().
Includes parameter checking and VBO bounds checking.
Returns
GL_TRUE if OK to render, GL_FALSE if error found
References _mesa_error(), _mesa_is_bufferobj(), _mesa_valid_prim_mode(), _mesa_warning(), gl_context::Array, gl_array_attrib::ArrayObj, check_index_bounds(), check_valid_to_render(), gl_array_object::ElementArrayBufferObj, FLUSH_CURRENT, index_bytes(), gl_buffer_object::Size, and valid_elements_type().
static GLboolean check_index_bounds (struct gl_context * ctx, GLsizei count, GLenum type, const GLvoid * indices, GLint basevertex) static
Do bounds checking on array element indexes.
Check that the vertices pointed to by the indices don't lie outside buffer object bounds.
Returns
GL_TRUE if OK, GL_FALSE if any indexed vertex goes is out of bounds
References gl_array_object::_MaxElement, _mesa_warning(), gl_context::Array, gl_array_attrib::ArrayObj, gl_constants::CheckArrayBounds, gl_context::Const, _mesa_index_buffer::count, _mesa_prim::count, gl_array_object::ElementArrayBufferObj, _mesa_index_buffer::obj, _mesa_index_buffer::ptr, _mesa_index_buffer::type, and vbo_get_minmax_indices().
Referenced by _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), and _mesa_validate_MultiDrawElements().
static GLboolean check_valid_to_render (struct gl_context * ctx, const char * function) static
Check if OK to draw arrays/elements.
References gl_vertex_program_state::_Current, gl_array_object::_Enabled, gl_vertex_program_state::_Enabled, _mesa_valid_to_render(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_context::Array, gl_array_attrib::ArrayObj, gl_shader_state::CurrentVertexProgram, gl_client_array::Enabled, gl_shader_program::LinkStatus, gl_context::Shader, VERT_ATTRIB_GENERIC0, VERT_ATTRIB_POS, gl_array_object::VertexAttrib, and gl_context::VertexProgram.
Referenced by _mesa_validate_DrawArrays(), _mesa_validate_DrawArraysInstanced(), _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), _mesa_validate_DrawTransformFeedback(), and _mesa_validate_MultiDrawElements().
static GLsizei index_bytes (GLenum type, GLsizei count) static
Returns
number of bytes in array [count] of type.
References ASSERT, GLubyte, and GLushort.
Referenced by _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), and _mesa_validate_MultiDrawElements().
static bool valid_elements_type (struct gl_context * ctx, GLenum type, const char * name) static
Verify that the element type is valid.
Generates GL_INVALID_ENUM and returns false if it is not.
References _mesa_error(), and _mesa_lookup_enum_by_nr().
Referenced by _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), and _mesa_validate_MultiDrawElements().