Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
api_arrayelt.h File Reference
#include "main/mtypes.h"
Functions
GLboolean _ae_create_context (struct gl_context *ctx)
void _ae_destroy_context (struct gl_context *ctx)
void _ae_invalidate_state (struct gl_context *ctx, GLuint new_state)
void GLAPIENTRY _ae_ArrayElement (GLint elt)
Called via glArrayElement() and glDrawArrays().
void _ae_map_vbos (struct gl_context *ctx)
Before replaying glArrayElements calls we need to map (for reading) any VBOs referenced by the enabled vertex arrays.
void _ae_unmap_vbos (struct gl_context *ctx)
Unmap VBOs.
void _mesa_install_arrayelt_vtxfmt (struct _glapi_table *disp, const GLvertexformat *vfmt)
Function Documentation
void GLAPIENTRY _ae_ArrayElement (GLint elt)
Called via glArrayElement() and glDrawArrays().
Issue the glNormal, glVertex, glColor, glVertexAttrib, etc functions for all enabled vertex arrays (for elt-th element). Note: this may be called during display list construction.
References _ae_map_vbos(), _ae_unmap_vbos(), _ae_update_state(), ADD_POINTERS, AE_CONTEXT(), AEarray::array, AEattrib::array, AEcontext::arrays, AEcontext::attribs, gl_client_array::BufferObj, CALL_by_offset, CALL_PrimitiveRestartNV, AEattrib::func, GLubyte, AEattrib::index, AEcontext::mapped_vbos, AEcontext::NewState, AEcontext::nr_vbos, AEarray::offset, gl_buffer_object::Pointer, gl_client_array::Ptr, and gl_client_array::StrideB.
Referenced by save_vtxfmt_init().
GLboolean _ae_create_context (struct gl_context * ctx)
References _gloffset_FogCoorddv, _gloffset_FogCoordfvEXT, _gloffset_SecondaryColor3bv, _gloffset_SecondaryColor3dv, _gloffset_SecondaryColor3fvEXT, _gloffset_SecondaryColor3iv, _gloffset_SecondaryColor3sv, _gloffset_SecondaryColor3ubv, _gloffset_SecondaryColor3uiv, _gloffset_SecondaryColor3usv, AE_CONTEXT(), gl_context::aelt_context, FogCoordFuncs, AEcontext::NewState, and SecondaryColorFuncs.
void _ae_destroy_context (struct gl_context * ctx)
References AE_CONTEXT(), gl_context::aelt_context, and NULL.
void _ae_invalidate_state (struct gl_context * ctx, GLuint new_state)
References _NEW_ARRAY, _NEW_PROGRAM, AE_CONTEXT(), AEcontext::mapped_vbos, and AEcontext::NewState.
Referenced by client_state().
void _ae_map_vbos (struct gl_context * ctx)
Before replaying glArrayElements calls we need to map (for reading) any VBOs referenced by the enabled vertex arrays.
References _ae_update_state(), AE_CONTEXT(), gl_context::Driver, dd_function_table::MapBufferRange, AEcontext::mapped_vbos, AEcontext::NewState, AEcontext::nr_vbos, gl_buffer_object::Size, and AEcontext::vbo.
Referenced by _ae_ArrayElement().
void _ae_unmap_vbos (struct gl_context * ctx)
Unmap VBOs.
References AE_CONTEXT(), gl_context::Driver, AEcontext::mapped_vbos, AEcontext::NewState, AEcontext::nr_vbos, dd_function_table::UnmapBuffer, and AEcontext::vbo.
Referenced by _ae_ArrayElement().
void _mesa_install_arrayelt_vtxfmt (struct _glapi_table * disp, const GLvertexformat * vfmt)
References SET_ArrayElement().
Referenced by install_vtxfmt().