Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
api_loopback.c File Reference
#include "glheader.h"
#include "macros.h"
#include "api_loopback.h"
#include "mtypes.h"
#include "glapi/glapi.h"
#include "glapi/glthread.h"
#include "main/dispatch.h"
#include "main/context.h"
Macros
#define COLORF(r, g, b, a) CALL_Color4f(GET_DISPATCH(), (r,g,b,a))
#define VERTEX2(x, y) CALL_Vertex2f(GET_DISPATCH(), (x,y))
#define VERTEX3(x, y, z) CALL_Vertex3f(GET_DISPATCH(), (x,y,z))
#define VERTEX4(x, y, z, w) CALL_Vertex4f(GET_DISPATCH(), (x,y,z,w))
#define NORMAL(x, y, z) CALL_Normal3f(GET_DISPATCH(), (x,y,z))
#define TEXCOORD1(s) CALL_TexCoord1f(GET_DISPATCH(), (s))
#define TEXCOORD2(s, t) CALL_TexCoord2f(GET_DISPATCH(), (s,t))
#define TEXCOORD3(s, t, u) CALL_TexCoord3f(GET_DISPATCH(), (s,t,u))
#define TEXCOORD4(s, t, u, v) CALL_TexCoord4f(GET_DISPATCH(), (s,t,u,v))
#define INDEX(c) CALL_Indexf(GET_DISPATCH(), (c))
#define MULTI_TEXCOORD1(z, s) CALL_MultiTexCoord1fARB(GET_DISPATCH(), (z,s))
#define MULTI_TEXCOORD2(z, s, t) CALL_MultiTexCoord2fARB(GET_DISPATCH(), (z,s,t))
#define MULTI_TEXCOORD3(z, s, t, u) CALL_MultiTexCoord3fARB(GET_DISPATCH(), (z,s,t,u))
#define MULTI_TEXCOORD4(z, s, t, u, v) CALL_MultiTexCoord4fARB(GET_DISPATCH(), (z,s,t,u,v))
#define EVALCOORD1(x) CALL_EvalCoord1f(GET_DISPATCH(), (x))
#define EVALCOORD2(x, y) CALL_EvalCoord2f(GET_DISPATCH(), (x,y))
#define MATERIALFV(a, b, c) CALL_Materialfv(GET_DISPATCH(), (a,b,c))
#define RECTF(a, b, c, d) CALL_Rectf(GET_DISPATCH(), (a,b,c,d))
#define FOGCOORDF(x) CALL_FogCoordfEXT(GET_DISPATCH(), (x))
#define SECONDARYCOLORF(a, b, c) CALL_SecondaryColor3fEXT(GET_DISPATCH(), (a,b,c))
#define ATTRIB1NV(index, x) CALL_VertexAttrib1fNV(GET_DISPATCH(), (index,x))
#define ATTRIB2NV(index, x, y) CALL_VertexAttrib2fNV(GET_DISPATCH(), (index,x,y))
#define ATTRIB3NV(index, x, y, z) CALL_VertexAttrib3fNV(GET_DISPATCH(), (index,x,y,z))
#define ATTRIB4NV(index, x, y, z, w) CALL_VertexAttrib4fNV(GET_DISPATCH(), (index,x,y,z,w))
#define ATTRIB1ARB(index, x) CALL_VertexAttrib1fARB(GET_DISPATCH(), (index,x))
#define ATTRIB2ARB(index, x, y) CALL_VertexAttrib2fARB(GET_DISPATCH(), (index,x,y))
#define ATTRIB3ARB(index, x, y, z) CALL_VertexAttrib3fARB(GET_DISPATCH(), (index,x,y,z))
#define ATTRIB4ARB(index, x, y, z, w) CALL_VertexAttrib4fARB(GET_DISPATCH(), (index,x,y,z,w))
#define ATTRIBI_1I(index, x) CALL_VertexAttribI1iEXT(GET_DISPATCH(), (index,x))
#define ATTRIBI_1UI(index, x) CALL_VertexAttribI1uiEXT(GET_DISPATCH(), (index,x))
#define ATTRIBI_4I(index, x, y, z, w) CALL_VertexAttribI4iEXT(GET_DISPATCH(), (index,x,y,z,w))
#define ATTRIBI_4UI(index, x, y, z, w) CALL_VertexAttribI4uiEXT(GET_DISPATCH(), (index,x,y,z,w))
Functions
void GLAPIENTRY _mesa_Color3b (GLbyte red, GLbyte green, GLbyte blue)
void GLAPIENTRY _mesa_Color3d (GLdouble red, GLdouble green, GLdouble blue)
void GLAPIENTRY _mesa_Color3i (GLint red, GLint green, GLint blue)
void GLAPIENTRY _mesa_Color3s (GLshort red, GLshort green, GLshort blue)
void GLAPIENTRY _mesa_Color3ui (GLuint red, GLuint green, GLuint blue)
void GLAPIENTRY _mesa_Color3us (GLushort red, GLushort green, GLushort blue)
void GLAPIENTRY _mesa_Color3ub (GLubyte red, GLubyte green, GLubyte blue)
void GLAPIENTRY _mesa_Color3bv (const GLbyte *v)
void GLAPIENTRY _mesa_Color3dv (const GLdouble *v)
void GLAPIENTRY _mesa_Color3iv (const GLint *v)
void GLAPIENTRY _mesa_Color3sv (const GLshort *v)
void GLAPIENTRY _mesa_Color3uiv (const GLuint *v)
void GLAPIENTRY _mesa_Color3usv (const GLushort *v)
void GLAPIENTRY _mesa_Color3ubv (const GLubyte *v)
void GLAPIENTRY _mesa_Color4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
void GLAPIENTRY _mesa_Color4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
void GLAPIENTRY _mesa_Color4i (GLint red, GLint green, GLint blue, GLint alpha)
void GLAPIENTRY _mesa_Color4s (GLshort red, GLshort green, GLshort blue, GLshort alpha)
void GLAPIENTRY _mesa_Color4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha)
void GLAPIENTRY _mesa_Color4us (GLushort red, GLushort green, GLushort blue, GLushort alpha)
void GLAPIENTRY _mesa_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
void GLAPIENTRY _mesa_Color4iv (const GLint *v)
void GLAPIENTRY _mesa_Color4bv (const GLbyte *v)
void GLAPIENTRY _mesa_Color4dv (const GLdouble *v)
void GLAPIENTRY _mesa_Color4sv (const GLshort *v)
void GLAPIENTRY _mesa_Color4uiv (const GLuint *v)
void GLAPIENTRY _mesa_Color4usv (const GLushort *v)
void GLAPIENTRY _mesa_Color4ubv (const GLubyte *v)
void GLAPIENTRY _mesa_FogCoordd (GLdouble d)
void GLAPIENTRY _mesa_FogCoorddv (const GLdouble *v)
void GLAPIENTRY _mesa_Indexd (GLdouble c)
void GLAPIENTRY _mesa_Indexi (GLint c)
void GLAPIENTRY _mesa_Indexs (GLshort c)
void GLAPIENTRY _mesa_Indexub (GLubyte c)
void GLAPIENTRY _mesa_Indexdv (const GLdouble *c)
void GLAPIENTRY _mesa_Indexiv (const GLint *c)
void GLAPIENTRY _mesa_Indexsv (const GLshort *c)
void GLAPIENTRY _mesa_Indexubv (const GLubyte *c)
void GLAPIENTRY _mesa_EdgeFlagv (const GLboolean *flag)
void GLAPIENTRY _mesa_Normal3b (GLbyte nx, GLbyte ny, GLbyte nz)
void GLAPIENTRY _mesa_Normal3d (GLdouble nx, GLdouble ny, GLdouble nz)
void GLAPIENTRY _mesa_Normal3i (GLint nx, GLint ny, GLint nz)
void GLAPIENTRY _mesa_Normal3s (GLshort nx, GLshort ny, GLshort nz)
void GLAPIENTRY _mesa_Normal3bv (const GLbyte *v)
void GLAPIENTRY _mesa_Normal3dv (const GLdouble *v)
void GLAPIENTRY _mesa_Normal3iv (const GLint *v)
void GLAPIENTRY _mesa_Normal3sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord1d (GLdouble s)
void GLAPIENTRY _mesa_TexCoord1i (GLint s)
void GLAPIENTRY _mesa_TexCoord1s (GLshort s)
void GLAPIENTRY _mesa_TexCoord2d (GLdouble s, GLdouble t)
void GLAPIENTRY _mesa_TexCoord2s (GLshort s, GLshort t)
void GLAPIENTRY _mesa_TexCoord2i (GLint s, GLint t)
void GLAPIENTRY _mesa_TexCoord3d (GLdouble s, GLdouble t, GLdouble r)
void GLAPIENTRY _mesa_TexCoord3i (GLint s, GLint t, GLint r)
void GLAPIENTRY _mesa_TexCoord3s (GLshort s, GLshort t, GLshort r)
void GLAPIENTRY _mesa_TexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q)
void GLAPIENTRY _mesa_TexCoord4i (GLint s, GLint t, GLint r, GLint q)
void GLAPIENTRY _mesa_TexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q)
void GLAPIENTRY _mesa_TexCoord1dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord1iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord1sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord2dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord2iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord2sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord3dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord3iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord3sv (const GLshort *v)
void GLAPIENTRY _mesa_TexCoord4dv (const GLdouble *v)
void GLAPIENTRY _mesa_TexCoord4iv (const GLint *v)
void GLAPIENTRY _mesa_TexCoord4sv (const GLshort *v)
void GLAPIENTRY _mesa_Vertex2d (GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_Vertex2i (GLint x, GLint y)
void GLAPIENTRY _mesa_Vertex2s (GLshort x, GLshort y)
void GLAPIENTRY _mesa_Vertex3d (GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_Vertex3i (GLint x, GLint y, GLint z)
void GLAPIENTRY _mesa_Vertex3s (GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_Vertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_Vertex4i (GLint x, GLint y, GLint z, GLint w)
void GLAPIENTRY _mesa_Vertex4s (GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_Vertex2dv (const GLdouble *v)
void GLAPIENTRY _mesa_Vertex2iv (const GLint *v)
void GLAPIENTRY _mesa_Vertex2sv (const GLshort *v)
void GLAPIENTRY _mesa_Vertex3dv (const GLdouble *v)
void GLAPIENTRY _mesa_Vertex3iv (const GLint *v)
void GLAPIENTRY _mesa_Vertex3sv (const GLshort *v)
void GLAPIENTRY _mesa_Vertex4dv (const GLdouble *v)
void GLAPIENTRY _mesa_Vertex4iv (const GLint *v)
void GLAPIENTRY _mesa_Vertex4sv (const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord1d (GLenum target, GLdouble s)
void GLAPIENTRY _mesa_MultiTexCoord1dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord1i (GLenum target, GLint s)
void GLAPIENTRY _mesa_MultiTexCoord1iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord1s (GLenum target, GLshort s)
void GLAPIENTRY _mesa_MultiTexCoord1sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord2d (GLenum target, GLdouble s, GLdouble t)
void GLAPIENTRY _mesa_MultiTexCoord2dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord2i (GLenum target, GLint s, GLint t)
void GLAPIENTRY _mesa_MultiTexCoord2iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord2s (GLenum target, GLshort s, GLshort t)
void GLAPIENTRY _mesa_MultiTexCoord2sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord3d (GLenum target, GLdouble s, GLdouble t, GLdouble r)
void GLAPIENTRY _mesa_MultiTexCoord3dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord3i (GLenum target, GLint s, GLint t, GLint r)
void GLAPIENTRY _mesa_MultiTexCoord3iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord3s (GLenum target, GLshort s, GLshort t, GLshort r)
void GLAPIENTRY _mesa_MultiTexCoord3sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_MultiTexCoord4d (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
void GLAPIENTRY _mesa_MultiTexCoord4dv (GLenum target, const GLdouble *v)
void GLAPIENTRY _mesa_MultiTexCoord4i (GLenum target, GLint s, GLint t, GLint r, GLint q)
void GLAPIENTRY _mesa_MultiTexCoord4iv (GLenum target, const GLint *v)
void GLAPIENTRY _mesa_MultiTexCoord4s (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
void GLAPIENTRY _mesa_MultiTexCoord4sv (GLenum target, const GLshort *v)
void GLAPIENTRY _mesa_EvalCoord2dv (const GLdouble *u)
void GLAPIENTRY _mesa_EvalCoord2fv (const GLfloat *u)
void GLAPIENTRY _mesa_EvalCoord2d (GLdouble u, GLdouble v)
void GLAPIENTRY _mesa_EvalCoord1dv (const GLdouble *u)
void GLAPIENTRY _mesa_EvalCoord1fv (const GLfloat *u)
void GLAPIENTRY _mesa_EvalCoord1d (GLdouble u)
void GLAPIENTRY _mesa_Materialf (GLenum face, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_Materiali (GLenum face, GLenum pname, GLint param)
void GLAPIENTRY _mesa_Materialiv (GLenum face, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_Rectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
void GLAPIENTRY _mesa_Rectdv (const GLdouble *v1, const GLdouble *v2)
void GLAPIENTRY _mesa_Rectfv (const GLfloat *v1, const GLfloat *v2)
void GLAPIENTRY _mesa_Recti (GLint x1, GLint y1, GLint x2, GLint y2)
void GLAPIENTRY _mesa_Rectiv (const GLint *v1, const GLint *v2)
void GLAPIENTRY _mesa_Rects (GLshort x1, GLshort y1, GLshort x2, GLshort y2)
void GLAPIENTRY _mesa_Rectsv (const GLshort *v1, const GLshort *v2)
void GLAPIENTRY _mesa_SecondaryColor3b (GLbyte red, GLbyte green, GLbyte blue)
void GLAPIENTRY _mesa_SecondaryColor3d (GLdouble red, GLdouble green, GLdouble blue)
void GLAPIENTRY _mesa_SecondaryColor3i (GLint red, GLint green, GLint blue)
void GLAPIENTRY _mesa_SecondaryColor3s (GLshort red, GLshort green, GLshort blue)
void GLAPIENTRY _mesa_SecondaryColor3ui (GLuint red, GLuint green, GLuint blue)
void GLAPIENTRY _mesa_SecondaryColor3us (GLushort red, GLushort green, GLushort blue)
void GLAPIENTRY _mesa_SecondaryColor3ub (GLubyte red, GLubyte green, GLubyte blue)
void GLAPIENTRY _mesa_SecondaryColor3bv (const GLbyte *v)
void GLAPIENTRY _mesa_SecondaryColor3dv (const GLdouble *v)
void GLAPIENTRY _mesa_SecondaryColor3iv (const GLint *v)
void GLAPIENTRY _mesa_SecondaryColor3sv (const GLshort *v)
void GLAPIENTRY _mesa_SecondaryColor3uiv (const GLuint *v)
void GLAPIENTRY _mesa_SecondaryColor3usv (const GLushort *v)
void GLAPIENTRY _mesa_SecondaryColor3ubv (const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib1sNV (GLuint index, GLshort x)
void GLAPIENTRY _mesa_VertexAttrib1dNV (GLuint index, GLdouble x)
void GLAPIENTRY _mesa_VertexAttrib2sNV (GLuint index, GLshort x, GLshort y)
void GLAPIENTRY _mesa_VertexAttrib2dNV (GLuint index, GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_VertexAttrib3sNV (GLuint index, GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_VertexAttrib3dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_VertexAttrib4sNV (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_VertexAttrib4dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_VertexAttrib4ubNV (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
void GLAPIENTRY _mesa_VertexAttrib1svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib1dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib2svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib2dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib3svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib3dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4svNV (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib4dvNV (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4ubvNV (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttribs1svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs1fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs1dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs2svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs2fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs2dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs3svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs3fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs3dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs4svNV (GLuint index, GLsizei n, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribs4fvNV (GLuint index, GLsizei n, const GLfloat *v)
void GLAPIENTRY _mesa_VertexAttribs4dvNV (GLuint index, GLsizei n, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttribs4ubvNV (GLuint index, GLsizei n, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib1s (GLuint index, GLshort x)
void GLAPIENTRY _mesa_VertexAttrib1d (GLuint index, GLdouble x)
void GLAPIENTRY _mesa_VertexAttrib2s (GLuint index, GLshort x, GLshort y)
void GLAPIENTRY _mesa_VertexAttrib2d (GLuint index, GLdouble x, GLdouble y)
void GLAPIENTRY _mesa_VertexAttrib3s (GLuint index, GLshort x, GLshort y, GLshort z)
void GLAPIENTRY _mesa_VertexAttrib3d (GLuint index, GLdouble x, GLdouble y, GLdouble z)
void GLAPIENTRY _mesa_VertexAttrib4s (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
void GLAPIENTRY _mesa_VertexAttrib4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_VertexAttrib1sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib1dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib2sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib2dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib3sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib3dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib4dv (GLuint index, const GLdouble *v)
void GLAPIENTRY _mesa_VertexAttrib4bv (GLuint index, const GLbyte *v)
void GLAPIENTRY _mesa_VertexAttrib4iv (GLuint index, const GLint *v)
void GLAPIENTRY _mesa_VertexAttrib4ubv (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib4usv (GLuint index, const GLushort *v)
void GLAPIENTRY _mesa_VertexAttrib4uiv (GLuint index, const GLuint *v)
void GLAPIENTRY _mesa_VertexAttrib4Nbv (GLuint index, const GLbyte *v)
void GLAPIENTRY _mesa_VertexAttrib4Nsv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttrib4Niv (GLuint index, const GLint *v)
void GLAPIENTRY _mesa_VertexAttrib4Nub (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
void GLAPIENTRY _mesa_VertexAttrib4Nubv (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttrib4Nusv (GLuint index, const GLushort *v)
void GLAPIENTRY _mesa_VertexAttrib4Nuiv (GLuint index, const GLuint *v)
void GLAPIENTRY _mesa_VertexAttribI1iv (GLuint index, const GLint *v)
GL_EXT_gpu_shader / GL 3.0 signed/unsigned integer-valued attributes.
void GLAPIENTRY _mesa_VertexAttribI1uiv (GLuint index, const GLuint *v)
void GLAPIENTRY _mesa_VertexAttribI4bv (GLuint index, const GLbyte *v)
void GLAPIENTRY _mesa_VertexAttribI4sv (GLuint index, const GLshort *v)
void GLAPIENTRY _mesa_VertexAttribI4ubv (GLuint index, const GLubyte *v)
void GLAPIENTRY _mesa_VertexAttribI4usv (GLuint index, const GLushort *v)
void _mesa_loopback_init_api_table (const struct gl_context *ctx, struct _glapi_table *dest)
Detailed Description
Author
Keith Whitwell keith.nosp@m.@tun.nosp@m.gsten.nosp@m.grap.nosp@m.hics..nosp@m.com
Macro Definition Documentation
#define ATTRIB1ARB (index, x) CALL_VertexAttrib1fARB(GET_DISPATCH(), (index,x))
Referenced by _mesa_VertexAttrib1d(), _mesa_VertexAttrib1dv(), _mesa_VertexAttrib1s(), and _mesa_VertexAttrib1sv().
#define ATTRIB1NV (index, x) CALL_VertexAttrib1fNV(GET_DISPATCH(), (index,x))
Referenced by _mesa_VertexAttrib1dNV(), _mesa_VertexAttrib1dvNV(), _mesa_VertexAttrib1sNV(), _mesa_VertexAttrib1svNV(), and _mesa_VertexAttribs1fvNV().
#define ATTRIB2ARB (index, x, y) CALL_VertexAttrib2fARB(GET_DISPATCH(), (index,x,y))
Referenced by _mesa_VertexAttrib2d(), _mesa_VertexAttrib2dv(), _mesa_VertexAttrib2s(), and _mesa_VertexAttrib2sv().
#define ATTRIB2NV (index, x, y) CALL_VertexAttrib2fNV(GET_DISPATCH(), (index,x,y))
Referenced by _mesa_VertexAttrib2dNV(), _mesa_VertexAttrib2dvNV(), _mesa_VertexAttrib2sNV(), _mesa_VertexAttrib2svNV(), and _mesa_VertexAttribs2fvNV().
#define ATTRIB3ARB (index, x, y, z) CALL_VertexAttrib3fARB(GET_DISPATCH(), (index,x,y,z))
Referenced by _mesa_VertexAttrib3dv(), _mesa_VertexAttrib3s(), and _mesa_VertexAttrib3sv().
#define ATTRIB3NV (index, x, y, z) CALL_VertexAttrib3fNV(GET_DISPATCH(), (index,x,y,z))
Referenced by _mesa_VertexAttrib3dvNV(), _mesa_VertexAttrib3sNV(), _mesa_VertexAttrib3svNV(), and _mesa_VertexAttribs3fvNV().
#define ATTRIB4ARB (index, x, y, z, w) CALL_VertexAttrib4fARB(GET_DISPATCH(), (index,x,y,z,w))
Referenced by _mesa_VertexAttrib3d(), _mesa_VertexAttrib4bv(), _mesa_VertexAttrib4d(), _mesa_VertexAttrib4dv(), _mesa_VertexAttrib4iv(), _mesa_VertexAttrib4Nbv(), _mesa_VertexAttrib4Niv(), _mesa_VertexAttrib4Nsv(), _mesa_VertexAttrib4Nub(), _mesa_VertexAttrib4Nubv(), _mesa_VertexAttrib4Nuiv(), _mesa_VertexAttrib4Nusv(), _mesa_VertexAttrib4s(), _mesa_VertexAttrib4sv(), _mesa_VertexAttrib4ubv(), _mesa_VertexAttrib4uiv(), and _mesa_VertexAttrib4usv().
#define ATTRIB4NV (index, x, y, z, w) CALL_VertexAttrib4fNV(GET_DISPATCH(), (index,x,y,z,w))
Referenced by _mesa_VertexAttrib3dNV(), _mesa_VertexAttrib4dNV(), _mesa_VertexAttrib4dvNV(), _mesa_VertexAttrib4sNV(), _mesa_VertexAttrib4svNV(), _mesa_VertexAttrib4ubNV(), _mesa_VertexAttrib4ubvNV(), and _mesa_VertexAttribs4fvNV().
#define ATTRIBI_1I (index, x) CALL_VertexAttribI1iEXT(GET_DISPATCH(), (index,x))
Referenced by _mesa_VertexAttribI1iv().
#define ATTRIBI_1UI (index, x) CALL_VertexAttribI1uiEXT(GET_DISPATCH(), (index,x))
Referenced by _mesa_VertexAttribI1uiv().
#define ATTRIBI_4I (index, x, y, z, w) CALL_VertexAttribI4iEXT(GET_DISPATCH(), (index,x,y,z,w))
Referenced by _mesa_VertexAttribI4bv(), and _mesa_VertexAttribI4sv().
#define ATTRIBI_4UI (index, x, y, z, w) CALL_VertexAttribI4uiEXT(GET_DISPATCH(), (index,x,y,z,w))
Referenced by _mesa_VertexAttribI4ubv(), and _mesa_VertexAttribI4usv().
#define COLORF (r, g, b, a) CALL_Color4f(GET_DISPATCH(), (r,g,b,a))
Referenced by _mesa_Color3b(), _mesa_Color3bv(), _mesa_Color3d(), _mesa_Color3dv(), _mesa_Color3i(), _mesa_Color3iv(), _mesa_Color3s(), _mesa_Color3sv(), _mesa_Color3ub(), _mesa_Color3ubv(), _mesa_Color3ui(), _mesa_Color3uiv(), _mesa_Color3us(), _mesa_Color3usv(), _mesa_Color4b(), _mesa_Color4bv(), _mesa_Color4d(), _mesa_Color4dv(), _mesa_Color4i(), _mesa_Color4iv(), _mesa_Color4s(), _mesa_Color4sv(), _mesa_Color4ub(), _mesa_Color4ubv(), _mesa_Color4ui(), _mesa_Color4uiv(), _mesa_Color4us(), and _mesa_Color4usv().
#define EVALCOORD1 (x) CALL_EvalCoord1f(GET_DISPATCH(), (x))
Referenced by _mesa_EvalCoord1d(), _mesa_EvalCoord1dv(), and _mesa_EvalCoord1fv().
#define EVALCOORD2 (x, y) CALL_EvalCoord2f(GET_DISPATCH(), (x,y))
Referenced by _mesa_EvalCoord2d(), _mesa_EvalCoord2dv(), and _mesa_EvalCoord2fv().
#define FOGCOORDF (x) CALL_FogCoordfEXT(GET_DISPATCH(), (x))
Referenced by _mesa_FogCoordd(), and _mesa_FogCoorddv().
#define INDEX (c) CALL_Indexf(GET_DISPATCH(), (c))
Referenced by _mesa_Indexd(), _mesa_Indexdv(), _mesa_Indexi(), _mesa_Indexiv(), _mesa_Indexs(), _mesa_Indexsv(), _mesa_Indexub(), and _mesa_Indexubv().
#define MATERIALFV (a, b, c) CALL_Materialfv(GET_DISPATCH(), (a,b,c))
Referenced by _mesa_Materialf(), _mesa_Materiali(), and _mesa_Materialiv().
#define MULTI_TEXCOORD1 (z, s) CALL_MultiTexCoord1fARB(GET_DISPATCH(), (z,s))
Referenced by _mesa_MultiTexCoord1d(), _mesa_MultiTexCoord1dv(), _mesa_MultiTexCoord1i(), _mesa_MultiTexCoord1iv(), _mesa_MultiTexCoord1s(), and _mesa_MultiTexCoord1sv().
#define MULTI_TEXCOORD2 (z, s, t) CALL_MultiTexCoord2fARB(GET_DISPATCH(), (z,s,t))
Referenced by _mesa_MultiTexCoord2d(), _mesa_MultiTexCoord2dv(), _mesa_MultiTexCoord2i(), _mesa_MultiTexCoord2iv(), _mesa_MultiTexCoord2s(), and _mesa_MultiTexCoord2sv().
#define MULTI_TEXCOORD3 (z, s, t, u) CALL_MultiTexCoord3fARB(GET_DISPATCH(), (z,s,t,u))
Referenced by _mesa_MultiTexCoord3d(), _mesa_MultiTexCoord3dv(), _mesa_MultiTexCoord3i(), _mesa_MultiTexCoord3iv(), _mesa_MultiTexCoord3s(), and _mesa_MultiTexCoord3sv().
#define MULTI_TEXCOORD4 (z, s, t, u, v) CALL_MultiTexCoord4fARB(GET_DISPATCH(), (z,s,t,u,v))
Referenced by _mesa_MultiTexCoord4d(), _mesa_MultiTexCoord4dv(), _mesa_MultiTexCoord4i(), _mesa_MultiTexCoord4iv(), _mesa_MultiTexCoord4s(), and _mesa_MultiTexCoord4sv().
#define NORMAL (x, y, z) CALL_Normal3f(GET_DISPATCH(), (x,y,z))
Referenced by _mesa_Normal3b(), _mesa_Normal3bv(), _mesa_Normal3d(), _mesa_Normal3dv(), _mesa_Normal3i(), _mesa_Normal3iv(), _mesa_Normal3s(), and _mesa_Normal3sv().
#define RECTF (a, b, c, d) CALL_Rectf(GET_DISPATCH(), (a,b,c,d))
Referenced by _mesa_Rectd(), _mesa_Rectdv(), _mesa_Rectfv(), _mesa_Recti(), _mesa_Rectiv(), _mesa_Rects(), and _mesa_Rectsv().
#define SECONDARYCOLORF (a, b, c) CALL_SecondaryColor3fEXT(GET_DISPATCH(), (a,b,c))
Referenced by _mesa_SecondaryColor3b(), _mesa_SecondaryColor3bv(), _mesa_SecondaryColor3d(), _mesa_SecondaryColor3dv(), _mesa_SecondaryColor3i(), _mesa_SecondaryColor3iv(), _mesa_SecondaryColor3s(), _mesa_SecondaryColor3sv(), _mesa_SecondaryColor3ub(), _mesa_SecondaryColor3ubv(), _mesa_SecondaryColor3ui(), _mesa_SecondaryColor3uiv(), _mesa_SecondaryColor3us(), and _mesa_SecondaryColor3usv().
#define TEXCOORD1 (s) CALL_TexCoord1f(GET_DISPATCH(), (s))
Referenced by _mesa_TexCoord1d(), _mesa_TexCoord1dv(), _mesa_TexCoord1i(), _mesa_TexCoord1iv(), _mesa_TexCoord1s(), and _mesa_TexCoord1sv().
#define TEXCOORD2 (s, t) CALL_TexCoord2f(GET_DISPATCH(), (s,t))
Referenced by _mesa_TexCoord2d(), _mesa_TexCoord2dv(), _mesa_TexCoord2i(), _mesa_TexCoord2iv(), _mesa_TexCoord2s(), and _mesa_TexCoord2sv().
#define TEXCOORD3 (s, t, u) CALL_TexCoord3f(GET_DISPATCH(), (s,t,u))
Referenced by _mesa_TexCoord3d(), _mesa_TexCoord3dv(), _mesa_TexCoord3i(), _mesa_TexCoord3iv(), _mesa_TexCoord3s(), and _mesa_TexCoord3sv().
#define TEXCOORD4 (s, t, u, v) CALL_TexCoord4f(GET_DISPATCH(), (s,t,u,v))
Referenced by _mesa_TexCoord4d(), _mesa_TexCoord4dv(), _mesa_TexCoord4i(), _mesa_TexCoord4iv(), _mesa_TexCoord4s(), and _mesa_TexCoord4sv().
#define VERTEX2 (x, y) CALL_Vertex2f(GET_DISPATCH(), (x,y))
Referenced by _mesa_Vertex2d(), _mesa_Vertex2dv(), _mesa_Vertex2i(), _mesa_Vertex2iv(), _mesa_Vertex2s(), and _mesa_Vertex2sv().
#define VERTEX3 (x, y, z) CALL_Vertex3f(GET_DISPATCH(), (x,y,z))
Referenced by _mesa_Vertex3d(), _mesa_Vertex3dv(), _mesa_Vertex3i(), _mesa_Vertex3iv(), _mesa_Vertex3s(), and _mesa_Vertex3sv().
#define VERTEX4 (x, y, z, w) CALL_Vertex4f(GET_DISPATCH(), (x,y,z,w))
Referenced by _mesa_Vertex4d(), _mesa_Vertex4dv(), _mesa_Vertex4i(), _mesa_Vertex4iv(), _mesa_Vertex4s(), and _mesa_Vertex4sv().
Function Documentation
void GLAPIENTRY _mesa_Color3b (GLbyte red, GLbyte green, GLbyte blue)
References BYTE_TO_FLOAT, and COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3bv (const GLbyte * v)
References BYTE_TO_FLOAT, and COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3d (GLdouble red, GLdouble green, GLdouble blue)
References COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3dv (const GLdouble * v)
References COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3i (GLint red, GLint green, GLint blue)
References COLORF, and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3iv (const GLint * v)
References COLORF, and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3s (GLshort red, GLshort green, GLshort blue)
References COLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3sv (const GLshort * v)
References COLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3ub (GLubyte red, GLubyte green, GLubyte blue)
References COLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3ubv (const GLubyte * v)
References COLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3ui (GLuint red, GLuint green, GLuint blue)
References COLORF, and UINT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3uiv (const GLuint * v)
References COLORF, and UINT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3us (GLushort red, GLushort green, GLushort blue)
References COLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color3usv (const GLushort * v)
References COLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
References BYTE_TO_FLOAT, and COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4bv (const GLbyte * v)
References BYTE_TO_FLOAT, and COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
References COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4dv (const GLdouble * v)
References COLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4i (GLint red, GLint green, GLint blue, GLint alpha)
References COLORF, and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4iv (const GLint * v)
References COLORF, and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4s (GLshort red, GLshort green, GLshort blue, GLshort alpha)
References COLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4sv (const GLshort * v)
References COLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
References COLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4ubv (const GLubyte * v)
References COLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha)
References COLORF, and UINT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4uiv (const GLuint * v)
References COLORF, and UINT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4us (GLushort red, GLushort green, GLushort blue, GLushort alpha)
References COLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Color4usv (const GLushort * v)
References COLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_EdgeFlagv (const GLboolean * flag)
References CALL_EdgeFlag.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_EvalCoord1d (GLdouble u)
References EVALCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_EvalCoord1dv (const GLdouble * u)
References EVALCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_EvalCoord1fv (const GLfloat * u)
References EVALCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_EvalCoord2d (GLdouble u, GLdouble v)
References EVALCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_EvalCoord2dv (const GLdouble * u)
References EVALCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_EvalCoord2fv (const GLfloat * u)
References EVALCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_FogCoordd (GLdouble d)
References FOGCOORDF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_FogCoorddv (const GLdouble * v)
References FOGCOORDF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexd (GLdouble c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexdv (const GLdouble * c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexi (GLint c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexiv (const GLint * c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexs (GLshort c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexsv (const GLshort * c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexub (GLubyte c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Indexubv (const GLubyte * c)
References INDEX.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void _mesa_loopback_init_api_table (const struct gl_context * ctx, struct _glapi_table * dest)
References _mesa_Color3b(), _mesa_Color3bv(), _mesa_Color3d(), _mesa_Color3dv(), _mesa_Color3i(), _mesa_Color3iv(), _mesa_Color3s(), _mesa_Color3sv(), _mesa_Color3ub(), _mesa_Color3ubv(), _mesa_Color3ui(), _mesa_Color3uiv(), _mesa_Color3us(), _mesa_Color3usv(), _mesa_Color4b(), _mesa_Color4bv(), _mesa_Color4d(), _mesa_Color4dv(), _mesa_Color4i(), _mesa_Color4iv(), _mesa_Color4s(), _mesa_Color4sv(), _mesa_Color4ub(), _mesa_Color4ubv(), _mesa_Color4ui(), _mesa_Color4uiv(), _mesa_Color4us(), _mesa_Color4usv(), _mesa_EdgeFlagv(), _mesa_EvalCoord1d(), _mesa_EvalCoord1dv(), _mesa_EvalCoord1fv(), _mesa_EvalCoord2d(), _mesa_EvalCoord2dv(), _mesa_EvalCoord2fv(), _mesa_FogCoordd(), _mesa_FogCoorddv(), _mesa_Indexd(), _mesa_Indexdv(), _mesa_Indexi(), _mesa_Indexiv(), _mesa_Indexs(), _mesa_Indexsv(), _mesa_Indexub(), _mesa_Indexubv(), _mesa_is_desktop_gl(), _mesa_Materialf(), _mesa_Materiali(), _mesa_Materialiv(), _mesa_MultiTexCoord1d(), _mesa_MultiTexCoord1dv(), _mesa_MultiTexCoord1i(), _mesa_MultiTexCoord1iv(), _mesa_MultiTexCoord1s(), _mesa_MultiTexCoord1sv(), _mesa_MultiTexCoord2d(), _mesa_MultiTexCoord2dv(), _mesa_MultiTexCoord2i(), _mesa_MultiTexCoord2iv(), _mesa_MultiTexCoord2s(), _mesa_MultiTexCoord2sv(), _mesa_MultiTexCoord3d(), _mesa_MultiTexCoord3dv(), _mesa_MultiTexCoord3i(), _mesa_MultiTexCoord3iv(), _mesa_MultiTexCoord3s(), _mesa_MultiTexCoord3sv(), _mesa_MultiTexCoord4d(), _mesa_MultiTexCoord4dv(), _mesa_MultiTexCoord4i(), _mesa_MultiTexCoord4iv(), _mesa_MultiTexCoord4s(), _mesa_MultiTexCoord4sv(), _mesa_Normal3b(), _mesa_Normal3bv(), _mesa_Normal3d(), _mesa_Normal3dv(), _mesa_Normal3i(), _mesa_Normal3iv(), _mesa_Normal3s(), _mesa_Normal3sv(), _mesa_Rectd(), _mesa_Rectdv(), _mesa_Rectfv(), _mesa_Recti(), _mesa_Rectiv(), _mesa_Rects(), _mesa_Rectsv(), _mesa_SecondaryColor3b(), _mesa_SecondaryColor3bv(), _mesa_SecondaryColor3d(), _mesa_SecondaryColor3dv(), _mesa_SecondaryColor3i(), _mesa_SecondaryColor3iv(), _mesa_SecondaryColor3s(), _mesa_SecondaryColor3sv(), _mesa_SecondaryColor3ub(), _mesa_SecondaryColor3ubv(), _mesa_SecondaryColor3ui(), _mesa_SecondaryColor3uiv(), _mesa_SecondaryColor3us(), _mesa_SecondaryColor3usv(), _mesa_TexCoord1d(), _mesa_TexCoord1dv(), _mesa_TexCoord1i(), _mesa_TexCoord1iv(), _mesa_TexCoord1s(), _mesa_TexCoord1sv(), _mesa_TexCoord2d(), _mesa_TexCoord2dv(), _mesa_TexCoord2i(), _mesa_TexCoord2iv(), _mesa_TexCoord2s(), _mesa_TexCoord2sv(), _mesa_TexCoord3d(), _mesa_TexCoord3dv(), _mesa_TexCoord3i(), _mesa_TexCoord3iv(), _mesa_TexCoord3s(), _mesa_TexCoord3sv(), _mesa_TexCoord4d(), _mesa_TexCoord4dv(), _mesa_TexCoord4i(), _mesa_TexCoord4iv(), _mesa_TexCoord4s(), _mesa_TexCoord4sv(), _mesa_Vertex2d(), _mesa_Vertex2dv(), _mesa_Vertex2i(), _mesa_Vertex2iv(), _mesa_Vertex2s(), _mesa_Vertex2sv(), _mesa_Vertex3d(), _mesa_Vertex3dv(), _mesa_Vertex3i(), _mesa_Vertex3iv(), _mesa_Vertex3s(), _mesa_Vertex3sv(), _mesa_Vertex4d(), _mesa_Vertex4dv(), _mesa_Vertex4i(), _mesa_Vertex4iv(), _mesa_Vertex4s(), _mesa_Vertex4sv(), _mesa_VertexAttrib1d(), _mesa_VertexAttrib1dNV(), _mesa_VertexAttrib1dv(), _mesa_VertexAttrib1dvNV(), _mesa_VertexAttrib1s(), _mesa_VertexAttrib1sNV(), _mesa_VertexAttrib1sv(), _mesa_VertexAttrib1svNV(), _mesa_VertexAttrib2d(), _mesa_VertexAttrib2dNV(), _mesa_VertexAttrib2dv(), _mesa_VertexAttrib2dvNV(), _mesa_VertexAttrib2s(), _mesa_VertexAttrib2sNV(), _mesa_VertexAttrib2sv(), _mesa_VertexAttrib2svNV(), _mesa_VertexAttrib3d(), _mesa_VertexAttrib3dNV(), _mesa_VertexAttrib3dv(), _mesa_VertexAttrib3dvNV(), _mesa_VertexAttrib3s(), _mesa_VertexAttrib3sNV(), _mesa_VertexAttrib3sv(), _mesa_VertexAttrib3svNV(), _mesa_VertexAttrib4bv(), _mesa_VertexAttrib4d(), _mesa_VertexAttrib4dNV(), _mesa_VertexAttrib4dv(), _mesa_VertexAttrib4dvNV(), _mesa_VertexAttrib4iv(), _mesa_VertexAttrib4Nbv(), _mesa_VertexAttrib4Niv(), _mesa_VertexAttrib4Nsv(), _mesa_VertexAttrib4Nub(), _mesa_VertexAttrib4Nubv(), _mesa_VertexAttrib4Nuiv(), _mesa_VertexAttrib4Nusv(), _mesa_VertexAttrib4s(), _mesa_VertexAttrib4sNV(), _mesa_VertexAttrib4sv(), _mesa_VertexAttrib4svNV(), _mesa_VertexAttrib4ubNV(), _mesa_VertexAttrib4ubv(), _mesa_VertexAttrib4ubvNV(), _mesa_VertexAttrib4uiv(), _mesa_VertexAttrib4usv(), _mesa_VertexAttribI1iv(), _mesa_VertexAttribI1uiv(), _mesa_VertexAttribI4bv(), _mesa_VertexAttribI4sv(), _mesa_VertexAttribI4ubv(), _mesa_VertexAttribI4usv(), _mesa_VertexAttribs1dvNV(), _mesa_VertexAttribs1fvNV(), _mesa_VertexAttribs1svNV(), _mesa_VertexAttribs2dvNV(), _mesa_VertexAttribs2fvNV(), _mesa_VertexAttribs2svNV(), _mesa_VertexAttribs3dvNV(), _mesa_VertexAttribs3fvNV(), _mesa_VertexAttribs3svNV(), _mesa_VertexAttribs4dvNV(), _mesa_VertexAttribs4fvNV(), _mesa_VertexAttribs4svNV(), _mesa_VertexAttribs4ubvNV(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES2, SET_Color3b(), SET_Color3bv(), SET_Color3d(), SET_Color3dv(), SET_Color3i(), SET_Color3iv(), SET_Color3s(), SET_Color3sv(), SET_Color3ub(), SET_Color3ubv(), SET_Color3ui(), SET_Color3uiv(), SET_Color3us(), SET_Color3usv(), SET_Color4b(), SET_Color4bv(), SET_Color4d(), SET_Color4dv(), SET_Color4i(), SET_Color4iv(), SET_Color4s(), SET_Color4sv(), SET_Color4ub(), SET_Color4ubv(), SET_Color4ui(), SET_Color4uiv(), SET_Color4us(), SET_Color4usv(), SET_EdgeFlagv(), SET_EvalCoord1d(), SET_EvalCoord1dv(), SET_EvalCoord1fv(), SET_EvalCoord2d(), SET_EvalCoord2dv(), SET_EvalCoord2fv(), SET_FogCoordd(), SET_FogCoorddv(), SET_Indexd(), SET_Indexdv(), SET_Indexi(), SET_Indexiv(), SET_Indexs(), SET_Indexsv(), SET_Indexub(), SET_Indexubv(), SET_Materialf(), SET_Materiali(), SET_Materialiv(), SET_MultiTexCoord1d(), SET_MultiTexCoord1dv(), SET_MultiTexCoord1i(), SET_MultiTexCoord1iv(), SET_MultiTexCoord1s(), SET_MultiTexCoord1sv(), SET_MultiTexCoord2d(), SET_MultiTexCoord2dv(), SET_MultiTexCoord2i(), SET_MultiTexCoord2iv(), SET_MultiTexCoord2s(), SET_MultiTexCoord2sv(), SET_MultiTexCoord3d(), SET_MultiTexCoord3dv(), SET_MultiTexCoord3i(), SET_MultiTexCoord3iv(), SET_MultiTexCoord3s(), SET_MultiTexCoord3sv(), SET_MultiTexCoord4d(), SET_MultiTexCoord4dv(), SET_MultiTexCoord4i(), SET_MultiTexCoord4iv(), SET_MultiTexCoord4s(), SET_MultiTexCoord4sv(), SET_Normal3b(), SET_Normal3bv(), SET_Normal3d(), SET_Normal3dv(), SET_Normal3i(), SET_Normal3iv(), SET_Normal3s(), SET_Normal3sv(), SET_Rectd(), SET_Rectdv(), SET_Rectfv(), SET_Recti(), SET_Rectiv(), SET_Rects(), SET_Rectsv(), SET_SecondaryColor3b(), SET_SecondaryColor3bv(), SET_SecondaryColor3d(), SET_SecondaryColor3dv(), SET_SecondaryColor3i(), SET_SecondaryColor3iv(), SET_SecondaryColor3s(), SET_SecondaryColor3sv(), SET_SecondaryColor3ub(), SET_SecondaryColor3ubv(), SET_SecondaryColor3ui(), SET_SecondaryColor3uiv(), SET_SecondaryColor3us(), SET_SecondaryColor3usv(), SET_TexCoord1d(), SET_TexCoord1dv(), SET_TexCoord1i(), SET_TexCoord1iv(), SET_TexCoord1s(), SET_TexCoord1sv(), SET_TexCoord2d(), SET_TexCoord2dv(), SET_TexCoord2i(), SET_TexCoord2iv(), SET_TexCoord2s(), SET_TexCoord2sv(), SET_TexCoord3d(), SET_TexCoord3dv(), SET_TexCoord3i(), SET_TexCoord3iv(), SET_TexCoord3s(), SET_TexCoord3sv(), SET_TexCoord4d(), SET_TexCoord4dv(), SET_TexCoord4i(), SET_TexCoord4iv(), SET_TexCoord4s(), SET_TexCoord4sv(), SET_Vertex2d(), SET_Vertex2dv(), SET_Vertex2i(), SET_Vertex2iv(), SET_Vertex2s(), SET_Vertex2sv(), SET_Vertex3d(), SET_Vertex3dv(), SET_Vertex3i(), SET_Vertex3iv(), SET_Vertex3s(), SET_Vertex3sv(), SET_Vertex4d(), SET_Vertex4dv(), SET_Vertex4i(), SET_Vertex4iv(), SET_Vertex4s(), SET_Vertex4sv(), SET_VertexAttrib1d(), SET_VertexAttrib1dNV(), SET_VertexAttrib1dv(), SET_VertexAttrib1dvNV(), SET_VertexAttrib1s(), SET_VertexAttrib1sNV(), SET_VertexAttrib1sv(), SET_VertexAttrib1svNV(), SET_VertexAttrib2d(), SET_VertexAttrib2dNV(), SET_VertexAttrib2dv(), SET_VertexAttrib2dvNV(), SET_VertexAttrib2s(), SET_VertexAttrib2sNV(), SET_VertexAttrib2sv(), SET_VertexAttrib2svNV(), SET_VertexAttrib3d(), SET_VertexAttrib3dNV(), SET_VertexAttrib3dv(), SET_VertexAttrib3dvNV(), SET_VertexAttrib3s(), SET_VertexAttrib3sNV(), SET_VertexAttrib3sv(), SET_VertexAttrib3svNV(), SET_VertexAttrib4bv(), SET_VertexAttrib4d(), SET_VertexAttrib4dNV(), SET_VertexAttrib4dv(), SET_VertexAttrib4dvNV(), SET_VertexAttrib4iv(), SET_VertexAttrib4Nbv(), SET_VertexAttrib4Niv(), SET_VertexAttrib4Nsv(), SET_VertexAttrib4Nub(), SET_VertexAttrib4Nubv(), SET_VertexAttrib4Nuiv(), SET_VertexAttrib4Nusv(), SET_VertexAttrib4s(), SET_VertexAttrib4sNV(), SET_VertexAttrib4sv(), SET_VertexAttrib4svNV(), SET_VertexAttrib4ubNV(), SET_VertexAttrib4ubv(), SET_VertexAttrib4ubvNV(), SET_VertexAttrib4uiv(), SET_VertexAttrib4usv(), SET_VertexAttribI1iv(), SET_VertexAttribI1uiv(), SET_VertexAttribI4bv(), SET_VertexAttribI4sv(), SET_VertexAttribI4ubv(), SET_VertexAttribI4usv(), SET_VertexAttribs1dvNV(), SET_VertexAttribs1fvNV(), SET_VertexAttribs1svNV(), SET_VertexAttribs2dvNV(), SET_VertexAttribs2fvNV(), SET_VertexAttribs2svNV(), SET_VertexAttribs3dvNV(), SET_VertexAttribs3fvNV(), SET_VertexAttribs3svNV(), SET_VertexAttribs4dvNV(), SET_VertexAttribs4fvNV(), SET_VertexAttribs4svNV(), and SET_VertexAttribs4ubvNV().
Referenced by _mesa_initialize_save_table(), and create_beginend_table().
void GLAPIENTRY _mesa_Materialf (GLenum face, GLenum pname, GLfloat param)
References MATERIALFV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Materiali (GLenum face, GLenum pname, GLint param)
References MATERIALFV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Materialiv (GLenum face, GLenum pname, const GLint * params)
References INT_TO_FLOAT, and MATERIALFV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord1d (GLenum target, GLdouble s)
References MULTI_TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord1dv (GLenum target, const GLdouble * v)
References MULTI_TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord1i (GLenum target, GLint s)
References MULTI_TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord1iv (GLenum target, const GLint * v)
References MULTI_TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord1s (GLenum target, GLshort s)
References MULTI_TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord1sv (GLenum target, const GLshort * v)
References MULTI_TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord2d (GLenum target, GLdouble s, GLdouble t)
References MULTI_TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord2dv (GLenum target, const GLdouble * v)
References MULTI_TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord2i (GLenum target, GLint s, GLint t)
References MULTI_TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord2iv (GLenum target, const GLint * v)
References MULTI_TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord2s (GLenum target, GLshort s, GLshort t)
References MULTI_TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord2sv (GLenum target, const GLshort * v)
References MULTI_TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord3d (GLenum target, GLdouble s, GLdouble t, GLdouble r)
References MULTI_TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord3dv (GLenum target, const GLdouble * v)
References MULTI_TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord3i (GLenum target, GLint s, GLint t, GLint r)
References MULTI_TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord3iv (GLenum target, const GLint * v)
References MULTI_TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord3s (GLenum target, GLshort s, GLshort t, GLshort r)
References MULTI_TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord3sv (GLenum target, const GLshort * v)
References MULTI_TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord4d (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
References MULTI_TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord4dv (GLenum target, const GLdouble * v)
References MULTI_TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord4i (GLenum target, GLint s, GLint t, GLint r, GLint q)
References MULTI_TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord4iv (GLenum target, const GLint * v)
References MULTI_TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord4s (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
References MULTI_TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_MultiTexCoord4sv (GLenum target, const GLshort * v)
References MULTI_TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3b (GLbyte nx, GLbyte ny, GLbyte nz)
References BYTE_TO_FLOAT, and NORMAL.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3bv (const GLbyte * v)
References BYTE_TO_FLOAT, and NORMAL.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3d (GLdouble nx, GLdouble ny, GLdouble nz)
References NORMAL.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3dv (const GLdouble * v)
References NORMAL.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3i (GLint nx, GLint ny, GLint nz)
References INT_TO_FLOAT, and NORMAL.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3iv (const GLint * v)
References INT_TO_FLOAT, and NORMAL.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3s (GLshort nx, GLshort ny, GLshort nz)
References NORMAL, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Normal3sv (const GLshort * v)
References NORMAL, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Rectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
References RECTF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Rectdv (const GLdouble * v1, const GLdouble * v2)
References RECTF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Rectfv (const GLfloat * v1, const GLfloat * v2)
References RECTF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Recti (GLint x1, GLint y1, GLint x2, GLint y2)
References RECTF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Rectiv (const GLint * v1, const GLint * v2)
References RECTF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Rects (GLshort x1, GLshort y1, GLshort x2, GLshort y2)
References RECTF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Rectsv (const GLshort * v1, const GLshort * v2)
References RECTF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3b (GLbyte red, GLbyte green, GLbyte blue)
References BYTE_TO_FLOAT, and SECONDARYCOLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3bv (const GLbyte * v)
References BYTE_TO_FLOAT, and SECONDARYCOLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3d (GLdouble red, GLdouble green, GLdouble blue)
References SECONDARYCOLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3dv (const GLdouble * v)
References SECONDARYCOLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3i (GLint red, GLint green, GLint blue)
References INT_TO_FLOAT, and SECONDARYCOLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3iv (const GLint * v)
References INT_TO_FLOAT, and SECONDARYCOLORF.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3s (GLshort red, GLshort green, GLshort blue)
References SECONDARYCOLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3sv (const GLshort * v)
References SECONDARYCOLORF, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3ub (GLubyte red, GLubyte green, GLubyte blue)
References SECONDARYCOLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3ubv (const GLubyte * v)
References SECONDARYCOLORF, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3ui (GLuint red, GLuint green, GLuint blue)
References SECONDARYCOLORF, and UINT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3uiv (const GLuint * v)
References SECONDARYCOLORF, and UINT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3us (GLushort red, GLushort green, GLushort blue)
References SECONDARYCOLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_SecondaryColor3usv (const GLushort * v)
References SECONDARYCOLORF, and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord1d (GLdouble s)
References TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord1dv (const GLdouble * v)
References TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord1i (GLint s)
References TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord1iv (const GLint * v)
References TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord1s (GLshort s)
References TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord1sv (const GLshort * v)
References TEXCOORD1.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord2d (GLdouble s, GLdouble t)
References TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord2dv (const GLdouble * v)
References TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord2i (GLint s, GLint t)
References TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord2iv (const GLint * v)
References TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord2s (GLshort s, GLshort t)
References TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord2sv (const GLshort * v)
References TEXCOORD2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord3d (GLdouble s, GLdouble t, GLdouble r)
References TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord3dv (const GLdouble * v)
References TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord3i (GLint s, GLint t, GLint r)
References TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord3iv (const GLint * v)
References TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord3s (GLshort s, GLshort t, GLshort r)
References TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord3sv (const GLshort * v)
References TEXCOORD3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q)
References TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord4dv (const GLdouble * v)
References TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord4i (GLint s, GLint t, GLint r, GLint q)
References TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord4iv (const GLint * v)
References TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q)
References TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_TexCoord4sv (const GLshort * v)
References TEXCOORD4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex2d (GLdouble x, GLdouble y)
References VERTEX2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex2dv (const GLdouble * v)
References VERTEX2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex2i (GLint x, GLint y)
References VERTEX2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex2iv (const GLint * v)
References VERTEX2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex2s (GLshort x, GLshort y)
References VERTEX2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex2sv (const GLshort * v)
References VERTEX2.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex3d (GLdouble x, GLdouble y, GLdouble z)
References VERTEX3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex3dv (const GLdouble * v)
References VERTEX3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex3i (GLint x, GLint y, GLint z)
References VERTEX3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex3iv (const GLint * v)
References VERTEX3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex3s (GLshort x, GLshort y, GLshort z)
References VERTEX3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex3sv (const GLshort * v)
References VERTEX3.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References VERTEX4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex4dv (const GLdouble * v)
References VERTEX4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex4i (GLint x, GLint y, GLint z, GLint w)
References VERTEX4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex4iv (const GLint * v)
References VERTEX4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex4s (GLshort x, GLshort y, GLshort z, GLshort w)
References VERTEX4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_Vertex4sv (const GLshort * v)
References VERTEX4.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib1d (GLuint index, GLdouble x)
References ATTRIB1ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib1dNV (GLuint index, GLdouble x)
References ATTRIB1NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib1dv (GLuint index, const GLdouble * v)
References ATTRIB1ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib1dvNV (GLuint index, const GLdouble * v)
References ATTRIB1NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs1dvNV().
void GLAPIENTRY _mesa_VertexAttrib1s (GLuint index, GLshort x)
References ATTRIB1ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib1sNV (GLuint index, GLshort x)
References ATTRIB1NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib1sv (GLuint index, const GLshort * v)
References ATTRIB1ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib1svNV (GLuint index, const GLshort * v)
References ATTRIB1NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs1svNV().
void GLAPIENTRY _mesa_VertexAttrib2d (GLuint index, GLdouble x, GLdouble y)
References ATTRIB2ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib2dNV (GLuint index, GLdouble x, GLdouble y)
References ATTRIB2NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib2dv (GLuint index, const GLdouble * v)
References ATTRIB2ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib2dvNV (GLuint index, const GLdouble * v)
References ATTRIB2NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs2dvNV().
void GLAPIENTRY _mesa_VertexAttrib2s (GLuint index, GLshort x, GLshort y)
References ATTRIB2ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib2sNV (GLuint index, GLshort x, GLshort y)
References ATTRIB2NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib2sv (GLuint index, const GLshort * v)
References ATTRIB2ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib2svNV (GLuint index, const GLshort * v)
References ATTRIB2NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs2svNV().
void GLAPIENTRY _mesa_VertexAttrib3d (GLuint index, GLdouble x, GLdouble y, GLdouble z)
References ATTRIB4ARB, and F.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib3dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z)
References ATTRIB4NV, and F.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib3dv (GLuint index, const GLdouble * v)
References ATTRIB3ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib3dvNV (GLuint index, const GLdouble * v)
References ATTRIB3NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs3dvNV().
void GLAPIENTRY _mesa_VertexAttrib3s (GLuint index, GLshort x, GLshort y, GLshort z)
References ATTRIB3ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib3sNV (GLuint index, GLshort x, GLshort y, GLshort z)
References ATTRIB3NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib3sv (GLuint index, const GLshort * v)
References ATTRIB3ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib3svNV (GLuint index, const GLshort * v)
References ATTRIB3NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs3svNV().
void GLAPIENTRY _mesa_VertexAttrib4bv (GLuint index, const GLbyte * v)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4d (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4dNV (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References ATTRIB4NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4dv (GLuint index, const GLdouble * v)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4dvNV (GLuint index, const GLdouble * v)
References ATTRIB4NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs4dvNV().
void GLAPIENTRY _mesa_VertexAttrib4iv (GLuint index, const GLint * v)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4Nbv (GLuint index, const GLbyte * v)
References ATTRIB4ARB, and BYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4Niv (GLuint index, const GLint * v)
References ATTRIB4ARB, and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4Nsv (GLuint index, const GLshort * v)
References ATTRIB4ARB, and SHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4Nub (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
References ATTRIB4ARB, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4Nubv (GLuint index, const GLubyte * v)
References ATTRIB4ARB, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4Nuiv (GLuint index, const GLuint * v)
References ATTRIB4ARB, and UINT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4Nusv (GLuint index, const GLushort * v)
References ATTRIB4ARB, and USHORT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4s (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4sNV (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w)
References ATTRIB4NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4sv (GLuint index, const GLshort * v)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4svNV (GLuint index, const GLshort * v)
References ATTRIB4NV.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs4svNV().
void GLAPIENTRY _mesa_VertexAttrib4ubNV (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
References ATTRIB4NV, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4ubv (GLuint index, const GLubyte * v)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4ubvNV (GLuint index, const GLubyte * v)
References ATTRIB4NV, and UBYTE_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), _mesa_loopback_init_api_table(), and _mesa_VertexAttribs4ubvNV().
void GLAPIENTRY _mesa_VertexAttrib4uiv (GLuint index, const GLuint * v)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttrib4usv (GLuint index, const GLushort * v)
References ATTRIB4ARB.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribI1iv (GLuint index, const GLint * v)
GL_EXT_gpu_shader / GL 3.0 signed/unsigned integer-valued attributes.
Note that attribute indexes do NOT alias conventional attributes.
References ATTRIBI_1I.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribI1uiv (GLuint index, const GLuint * v)
References ATTRIBI_1UI.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribI4bv (GLuint index, const GLbyte * v)
References ATTRIBI_4I.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribI4sv (GLuint index, const GLshort * v)
References ATTRIBI_4I.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribI4ubv (GLuint index, const GLubyte * v)
References ATTRIBI_4UI.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribI4usv (GLuint index, const GLushort * v)
References ATTRIBI_4UI.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs1dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib1dvNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs1fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB1NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs1svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib1svNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs2dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib2dvNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs2fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB2NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs2svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib2svNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs3dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib3dvNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs3fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB3NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs3svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib3svNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs4dvNV (GLuint index, GLsizei n, const GLdouble * v)
References _mesa_VertexAttrib4dvNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs4fvNV (GLuint index, GLsizei n, const GLfloat * v)
References ATTRIB4NV.
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs4svNV (GLuint index, GLsizei n, const GLshort * v)
References _mesa_VertexAttrib4svNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().
void GLAPIENTRY _mesa_VertexAttribs4ubvNV (GLuint index, GLsizei n, const GLubyte * v)
References _mesa_VertexAttrib4ubvNV().
Referenced by _mesa_initialize_exec_table(), and _mesa_loopback_init_api_table().