Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
arbprogram.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_BindProgramARB (GLenum target, GLuint id)
Bind a program (make it current)
void GLAPIENTRY _mesa_DeleteProgramsARB (GLsizei n, const GLuint *ids)
Delete a list of programs.
void GLAPIENTRY _mesa_GenProgramsARB (GLsizei n, GLuint *ids)
Generate a list of new program identifiers.
GLboolean GLAPIENTRY _mesa_IsProgramARB (GLuint id)
Determine if id names a vertex or fragment program.
void GLAPIENTRY _mesa_ProgramStringARB (GLenum target, GLenum format, GLsizei len, const GLvoid *string)
void GLAPIENTRY _mesa_ProgramEnvParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameter4dvARB (GLenum target, GLuint index, const GLdouble *params)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameter4fvARB (GLenum target, GLuint index, const GLfloat *params)
Set a program env parameter register.
void GLAPIENTRY _mesa_ProgramEnvParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat *params)
void GLAPIENTRY _mesa_ProgramLocalParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
void GLAPIENTRY _mesa_ProgramLocalParameter4dvARB (GLenum target, GLuint index, const GLdouble *params)
void GLAPIENTRY _mesa_ProgramLocalParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _mesa_ProgramLocalParameter4fvARB (GLenum target, GLuint index, const GLfloat *params)
void GLAPIENTRY _mesa_ProgramLocalParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat *params)
void GLAPIENTRY _mesa_GetProgramEnvParameterdvARB (GLenum target, GLuint index, GLdouble *params)
void GLAPIENTRY _mesa_GetProgramEnvParameterfvARB (GLenum target, GLuint index, GLfloat *params)
void GLAPIENTRY _mesa_GetProgramLocalParameterdvARB (GLenum target, GLuint index, GLdouble *params)
void GLAPIENTRY _mesa_GetProgramLocalParameterfvARB (GLenum target, GLuint index, GLfloat *params)
void GLAPIENTRY _mesa_GetProgramivARB (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetProgramStringARB (GLenum target, GLenum pname, GLvoid *string)
Function Documentation
void GLAPIENTRY _mesa_BindProgramARB (GLenum target, GLuint id)
Bind a program (make it current)
Note
Called from the GL API dispatcher by both glBindProgramNV and glBindProgramARB.
All error checking is complete now
References _mesa_error(), _mesa_HashInsert(), _NEW_PROGRAM, _NEW_PROGRAM_CONSTANTS, ASSERT, FLUSH_VERTICES, gl_program::Id, NULL, and gl_program::Target.
Referenced by _mesa_DeleteProgramsARB(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteProgramsARB (GLsizei n, const GLuint * ids)
Delete a list of programs.
Note
Not compiled into display lists.
Called by both glDeleteProgramsNV and glDeleteProgramsARB.
References _mesa_BindProgramARB(), _mesa_error(), _mesa_HashRemove(), _mesa_problem(), FLUSH_VERTICES, NULL, and gl_program::Target.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenProgramsARB (GLsizei n, GLuint * ids)
Generate a list of new program identifiers.
Note
Not compiled into display lists.
Called by both glGenProgramsNV and glGenProgramsARB.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), and _mesa_HashInsert().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramEnvParameterdvARB (GLenum target, GLuint index, GLdouble * params)
References COPY_4V, and get_env_param_pointer().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramEnvParameterfvARB (GLenum target, GLuint index, GLfloat * params)
References COPY_4V, and get_env_param_pointer().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramivARB (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), ASSERT, gl_fragment_program::Base, gl_program::Format, gl_program::Id, gl_program_constants::MaxAddressRegs, gl_program_constants::MaxAluInstructions, gl_program_constants::MaxAttribs, gl_program_constants::MaxEnvParams, gl_program_constants::MaxInstructions, gl_program_constants::MaxLocalParams, gl_program_constants::MaxNativeAddressRegs, gl_program_constants::MaxNativeAluInstructions, gl_program_constants::MaxNativeAttribs, gl_program_constants::MaxNativeInstructions, gl_program_constants::MaxNativeParameters, gl_program_constants::MaxNativeTemps, gl_program_constants::MaxNativeTexIndirections, gl_program_constants::MaxNativeTexInstructions, gl_program_constants::MaxParameters, gl_program_constants::MaxTemps, gl_program_constants::MaxTexIndirections, gl_program_constants::MaxTexInstructions, gl_program::NumAddressRegs, gl_program::NumAluInstructions, gl_program::NumAttributes, gl_program::NumInstructions, gl_program::NumNativeAddressRegs, gl_program::NumNativeAluInstructions, gl_program::NumNativeAttributes, gl_program::NumNativeInstructions, gl_program::NumNativeParameters, gl_program::NumNativeTemporaries, gl_program::NumNativeTexIndirections, gl_program::NumNativeTexInstructions, gl_program::NumParameters, gl_program::NumTemporaries, gl_program::NumTexIndirections, gl_program::NumTexInstructions, and gl_program::String.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramLocalParameterdvARB (GLenum target, GLuint index, GLdouble * params)
References COPY_4V, and get_local_param_pointer().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramLocalParameterfvARB (GLenum target, GLuint index, GLfloat * params)
References COPY_4V, and get_local_param_pointer().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramStringARB (GLenum target, GLenum pname, GLvoid * string)
References _mesa_error(), ASSERT, and gl_program::String.
Referenced by _mesa_initialize_exec_table().
GLboolean GLAPIENTRY _mesa_IsProgramARB (GLuint id)
Determine if id names a vertex or fragment program.
Note
Not compiled into display lists.
Called from both glIsProgramNV and glIsProgramARB.
Parameters
id is the program identifier
Returns
GL_TRUE if id is a program, else GL_FALSE.
References ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramEnvParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _mesa_ProgramEnvParameter4fARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramEnvParameter4dvARB (GLenum target, GLuint index, const GLdouble * params)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _mesa_ProgramEnvParameter4fARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramEnvParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _NEW_PROGRAM_CONSTANTS, ASSIGN_4V, FLUSH_VERTICES, and get_env_param_pointer().
Referenced by _mesa_initialize_exec_table(), _mesa_ProgramEnvParameter4dARB(), and _mesa_ProgramEnvParameter4dvARB().
void GLAPIENTRY _mesa_ProgramEnvParameter4fvARB (GLenum target, GLuint index, const GLfloat * params)
Set a program env parameter register.
Note
Called from the GL API dispatcher.
References _NEW_PROGRAM_CONSTANTS, FLUSH_VERTICES, and get_env_param_pointer().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramEnvParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat * params)
References _mesa_error(), _NEW_PROGRAM_CONSTANTS, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramLocalParameter4dARB (GLenum target, GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w)
References _mesa_ProgramLocalParameter4fARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramLocalParameter4dvARB (GLenum target, GLuint index, const GLdouble * params)
References _mesa_ProgramLocalParameter4fARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramLocalParameter4fARB (GLenum target, GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References _NEW_PROGRAM_CONSTANTS, ASSERT, ASSIGN_4V, FLUSH_VERTICES, get_local_param_pointer(), and MAX_PROGRAM_LOCAL_PARAMS.
Referenced by _mesa_initialize_exec_table(), _mesa_ProgramLocalParameter4dARB(), _mesa_ProgramLocalParameter4dvARB(), and _mesa_ProgramLocalParameter4fvARB().
void GLAPIENTRY _mesa_ProgramLocalParameter4fvARB (GLenum target, GLuint index, const GLfloat * params)
References _mesa_ProgramLocalParameter4fARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramLocalParameters4fvEXT (GLenum target, GLuint index, GLsizei count, const GLfloat * params)
References _mesa_error(), _NEW_PROGRAM_CONSTANTS, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramStringARB (GLenum target, GLenum format, GLsizei len, const GLvoid * string)
References _mesa_error(), _NEW_PROGRAM, gl_vertex_program::Base, gl_fragment_program::Base, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().