Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
arrayobj.h File Reference
Functions for the GL_APPLE_vertex_array_object extension.
#include "glheader.h"
#include "mtypes.h"
#include "glformats.h"
Functions
struct gl_array_object * _mesa_new_array_object (struct gl_context *ctx, GLuint name)
Allocate and initialize a new vertex array object.
void _mesa_delete_array_object (struct gl_context *ctx, struct gl_array_object *obj)
Delete an array object.
void _mesa_reference_array_object_ (struct gl_context *ctx, struct gl_array_object **ptr, struct gl_array_object *arrayObj)
Set ptr to arrayObj w/ reference counting.
static void _mesa_reference_array_object (struct gl_context *ctx, struct gl_array_object **ptr, struct gl_array_object *arrayObj)
void _mesa_initialize_array_object (struct gl_context *ctx, struct gl_array_object *obj, GLuint name)
Initialize a gl_array_object's arrays.
void _mesa_update_array_object_max_element (struct gl_context *ctx, struct gl_array_object *arrayObj)
Examine vertex arrays to update the gl_array_object::_MaxElement field.
static GLbitfield64 _mesa_array_object_get_enabled_ff (const struct gl_array_object *arrayObj)
Returns the bitmask of all enabled arrays in fixed function mode.
static GLbitfield64 _mesa_array_object_get_enabled_arb (const struct gl_array_object *arrayObj)
Returns the bitmask of all enabled arrays in arb/glsl shader mode.
void GLAPIENTRY _mesa_BindVertexArray (GLuint id)
ARB version of glBindVertexArray() This function behaves differently from glBindVertexArrayAPPLE() in that this function requires all ids to have been previously generated by glGenVertexArrays[APPLE]().
void GLAPIENTRY _mesa_BindVertexArrayAPPLE (GLuint id)
Bind a new array.
void GLAPIENTRY _mesa_DeleteVertexArrays (GLsizei n, const GLuint *ids)
Delete a set of array objects.
void GLAPIENTRY _mesa_GenVertexArrays (GLsizei n, GLuint *arrays)
ARB version of glGenVertexArrays() All arrays will be required to live in VBOs.
void GLAPIENTRY _mesa_GenVertexArraysAPPLE (GLsizei n, GLuint *buffer)
APPLE version of glGenVertexArraysAPPLE() Arrays may live in VBOs or ordinary memory.
GLboolean GLAPIENTRY _mesa_IsVertexArray (GLuint id)
Determine if ID is the name of an array object.
Detailed Description
Functions for the GL_APPLE_vertex_array_object extension.
Author
Ian Romanick idr@u.nosp@m.s.ib.nosp@m.m.com
Brian Paul
Function Documentation
static GLbitfield64 _mesa_array_object_get_enabled_arb (const struct gl_array_object * arrayObj) inline static
Returns the bitmask of all enabled arrays in arb/glsl shader mode.
In arb/glsl shader mode all the fixed function and the arb/glsl generic arrays are available. Only the first generic array takes precedence over the legacy position array.
References gl_array_object::_Enabled, VERT_ATTRIB_GENERIC0, and VERT_BIT_POS.
Referenced by _mesa_update_array_object_max_element().
static GLbitfield64 _mesa_array_object_get_enabled_ff (const struct gl_array_object * arrayObj) inline static
Returns the bitmask of all enabled arrays in fixed function mode.
In fixed function mode only the traditional fixed function arrays are available.
References gl_array_object::_Enabled, and VERT_BIT_FF_ALL.
Referenced by _mesa_update_array_object_max_element().
void GLAPIENTRY _mesa_BindVertexArray (GLuint id)
ARB version of glBindVertexArray() This function behaves differently from glBindVertexArrayAPPLE() in that this function requires all ids to have been previously generated by glGenVertexArrays[APPLE]().
References bind_vertex_array().
Referenced by _mesa_DeleteVertexArrays(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindVertexArrayAPPLE (GLuint id)
Bind a new array.
Todo:
The binding could be done more efficiently by comparing the non-NULL pointers in the old and new objects. The only arrays that are "dirty" are the ones that are non-NULL in either object.
References bind_vertex_array().
Referenced by _mesa_initialize_exec_table(), and restore_array_attrib().
void _mesa_delete_array_object (struct gl_context * ctx, struct gl_array_object * obj)
Delete an array object.
This function is intended to be called via dd_function_table::DeleteArrayObject.
References _mesa_reference_buffer_object(), gl_array_object::ElementArrayBufferObj, gl_array_object::Mutex, NULL, unbind_array_object_vbos(), and void().
Referenced by delete_arrayobj_cb(), and free_array_attrib_data().
void GLAPIENTRY _mesa_DeleteVertexArrays (GLsizei n, const GLuint * ids)
Delete a set of array objects.
Parameters
n Number of array objects to delete.
ids Array of n array object IDs.
References _mesa_BindVertexArray(), _mesa_error(), _mesa_reference_array_object(), ASSERT, lookup_arrayobj(), gl_array_object::Name, NULL, and remove_array_object().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenVertexArrays (GLsizei n, GLuint * arrays)
ARB version of glGenVertexArrays() All arrays will be required to live in VBOs.
References gen_vertex_arrays().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenVertexArraysAPPLE (GLsizei n, GLuint * buffer)
APPLE version of glGenVertexArraysAPPLE() Arrays may live in VBOs or ordinary memory.
References gen_vertex_arrays().
Referenced by _mesa_initialize_exec_table().
void _mesa_initialize_array_object (struct gl_context * ctx, struct gl_array_object * obj, GLuint name)
Initialize a gl_array_object's arrays.
References _mesa_reference_buffer_object(), gl_array_object::ElementArrayBufferObj, Elements, init_array(), gl_array_object::Mutex, gl_array_object::Name, gl_shared_state::NullBufferObj, gl_array_object::RefCount, gl_context::Shared, VERT_ATTRIB_COLOR1, VERT_ATTRIB_COLOR_INDEX, VERT_ATTRIB_EDGEFLAG, VERT_ATTRIB_FOG, VERT_ATTRIB_NORMAL, VERT_ATTRIB_POINT_SIZE, VERT_ATTRIB_WEIGHT, and gl_array_object::VertexAttrib.
Referenced by _mesa_new_array_object(), and init_array_attrib_data().
GLboolean GLAPIENTRY _mesa_IsVertexArray (GLuint id)
Determine if ID is the name of an array object.
Parameters
id ID of the potential array object.
Returns
GL_TRUE if id is the name of a array object, GL_FALSE otherwise.
References ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_array_object::EverBound, lookup_arrayobj(), and NULL.
Referenced by _mesa_initialize_exec_table(), and restore_array_attrib().
struct gl_array_object* _mesa_new_array_object (struct gl_context * ctx, GLuint name) read
Allocate and initialize a new vertex array object.
This function is intended to be called via dd_function_table::NewArrayObject.
References _mesa_initialize_array_object(), and CALLOC_STRUCT.
static void _mesa_reference_array_object (struct gl_context * ctx, struct gl_array_object ** ptr, struct gl_array_object * arrayObj) inline static
References _mesa_reference_array_object_().
Referenced by _mesa_DeleteVertexArrays(), _mesa_free_context_data(), _mesa_init_varray(), and bind_vertex_array().
void _mesa_reference_array_object_ (struct gl_context * ctx, struct gl_array_object ** ptr, struct gl_array_object * arrayObj)
Set ptr to arrayObj w/ reference counting.
Note: this should only be called from the _mesa_reference_array_object() inline function.
References _mesa_problem(), ASSERT, dd_function_table::DeleteArrayObject, gl_context::Driver, gl_array_object::Mutex, gl_array_object::Name, NULL, and gl_array_object::RefCount.
Referenced by _mesa_reference_array_object().
void _mesa_update_array_object_max_element (struct gl_context * ctx, struct gl_array_object * arrayObj)
Examine vertex arrays to update the gl_array_object::_MaxElement field.
References gl_vertex_program_state::_Current, gl_array_object::_MaxElement, _mesa_array_object_get_enabled_arb(), _mesa_array_object_get_enabled_ff(), gl_vertex_program_state::_TnlProgram, compute_max_element(), and gl_context::VertexProgram.
Referenced by _mesa_print_arrays(), and _mesa_update_state_locked().