Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
arrayobj.c File Reference
Functions for the GL_APPLE_vertex_array_object extension.
#include "glheader.h"
#include "hash.h"
#include "image.h"
#include "imports.h"
#include "context.h"
#include "bufferobj.h"
#include "arrayobj.h"
#include "macros.h"
#include "mtypes.h"
#include "varray.h"
#include "main/dispatch.h"
Functions
static struct gl_array_object * lookup_arrayobj (struct gl_context *ctx, GLuint id)
Look up the array object for the given ID.
static void unbind_array_object_vbos (struct gl_context *ctx, struct gl_array_object *obj)
For all the vertex arrays in the array object, unbind any pointers to any buffer objects (VBOs).
struct gl_array_object * _mesa_new_array_object (struct gl_context *ctx, GLuint name)
Allocate and initialize a new vertex array object.
void _mesa_delete_array_object (struct gl_context *ctx, struct gl_array_object *obj)
Delete an array object.
void _mesa_reference_array_object_ (struct gl_context *ctx, struct gl_array_object **ptr, struct gl_array_object *arrayObj)
Set ptr to arrayObj w/ reference counting.
static void init_array (struct gl_context *ctx, struct gl_client_array *array, GLint size, GLint type)
void _mesa_initialize_array_object (struct gl_context *ctx, struct gl_array_object *obj, GLuint name)
Initialize a gl_array_object's arrays.
static void save_array_object (struct gl_context *ctx, struct gl_array_object *obj)
Add the given array object to the array object pool.
static void remove_array_object (struct gl_context *ctx, struct gl_array_object *obj)
Remove the given array object from the array object pool.
static GLuint compute_max_element (struct gl_array_object *arrayObj, GLbitfield64 enabled)
Helper for _mesa_update_array_object_max_element().
void _mesa_update_array_object_max_element (struct gl_context *ctx, struct gl_array_object *arrayObj)
Examine vertex arrays to update the gl_array_object::_MaxElement field.
static void bind_vertex_array (struct gl_context *ctx, GLuint id, GLboolean genRequired)
Helper for _mesa_BindVertexArray() and _mesa_BindVertexArrayAPPLE().
void GLAPIENTRY _mesa_BindVertexArray (GLuint id)
ARB version of glBindVertexArray() This function behaves differently from glBindVertexArrayAPPLE() in that this function requires all ids to have been previously generated by glGenVertexArrays[APPLE]().
void GLAPIENTRY _mesa_BindVertexArrayAPPLE (GLuint id)
Bind a new array.
void GLAPIENTRY _mesa_DeleteVertexArrays (GLsizei n, const GLuint *ids)
Delete a set of array objects.
static void gen_vertex_arrays (struct gl_context *ctx, GLsizei n, GLuint *arrays)
Generate a set of unique array object IDs and store them in arrays.
void GLAPIENTRY _mesa_GenVertexArrays (GLsizei n, GLuint *arrays)
ARB version of glGenVertexArrays() All arrays will be required to live in VBOs.
void GLAPIENTRY _mesa_GenVertexArraysAPPLE (GLsizei n, GLuint *arrays)
APPLE version of glGenVertexArraysAPPLE() Arrays may live in VBOs or ordinary memory.
GLboolean GLAPIENTRY _mesa_IsVertexArray (GLuint id)
Determine if ID is the name of an array object.
Detailed Description
Functions for the GL_APPLE_vertex_array_object extension.
Todo:
The code in this file borrows a lot from bufferobj.c. There's a certain amount of cruft left over from that origin that may be unnecessary.
Author
Ian Romanick idr@u.nosp@m.s.ib.nosp@m.m.com
Brian Paul
Function Documentation
void GLAPIENTRY _mesa_BindVertexArray (GLuint id)
ARB version of glBindVertexArray() This function behaves differently from glBindVertexArrayAPPLE() in that this function requires all ids to have been previously generated by glGenVertexArrays[APPLE]().
References bind_vertex_array().
Referenced by _mesa_DeleteVertexArrays(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindVertexArrayAPPLE (GLuint id)
Bind a new array.
Todo:
The binding could be done more efficiently by comparing the non-NULL pointers in the old and new objects. The only arrays that are "dirty" are the ones that are non-NULL in either object.
References bind_vertex_array().
Referenced by _mesa_initialize_exec_table(), and restore_array_attrib().
void _mesa_delete_array_object (struct gl_context * ctx, struct gl_array_object * obj)
Delete an array object.
This function is intended to be called via dd_function_table::DeleteArrayObject.
References _mesa_reference_buffer_object(), gl_array_object::ElementArrayBufferObj, gl_array_object::Mutex, NULL, unbind_array_object_vbos(), and void().
Referenced by delete_arrayobj_cb(), and free_array_attrib_data().
void GLAPIENTRY _mesa_DeleteVertexArrays (GLsizei n, const GLuint * ids)
Delete a set of array objects.
Parameters
n Number of array objects to delete.
ids Array of n array object IDs.
References _mesa_BindVertexArray(), _mesa_error(), _mesa_reference_array_object(), ASSERT, lookup_arrayobj(), gl_array_object::Name, NULL, and remove_array_object().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenVertexArrays (GLsizei n, GLuint * arrays)
ARB version of glGenVertexArrays() All arrays will be required to live in VBOs.
References gen_vertex_arrays().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenVertexArraysAPPLE (GLsizei n, GLuint * arrays)
APPLE version of glGenVertexArraysAPPLE() Arrays may live in VBOs or ordinary memory.
References gen_vertex_arrays().
Referenced by _mesa_initialize_exec_table().
void _mesa_initialize_array_object (struct gl_context * ctx, struct gl_array_object * obj, GLuint name)
Initialize a gl_array_object's arrays.
References _mesa_reference_buffer_object(), gl_array_object::ElementArrayBufferObj, Elements, init_array(), gl_array_object::Mutex, gl_array_object::Name, gl_shared_state::NullBufferObj, gl_array_object::RefCount, gl_context::Shared, VERT_ATTRIB_COLOR1, VERT_ATTRIB_COLOR_INDEX, VERT_ATTRIB_EDGEFLAG, VERT_ATTRIB_FOG, VERT_ATTRIB_NORMAL, VERT_ATTRIB_POINT_SIZE, VERT_ATTRIB_WEIGHT, and gl_array_object::VertexAttrib.
Referenced by _mesa_new_array_object(), and init_array_attrib_data().
GLboolean GLAPIENTRY _mesa_IsVertexArray (GLuint id)
Determine if ID is the name of an array object.
Parameters
id ID of the potential array object.
Returns
GL_TRUE if id is the name of a array object, GL_FALSE otherwise.
References ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_array_object::EverBound, lookup_arrayobj(), and NULL.
Referenced by _mesa_initialize_exec_table(), and restore_array_attrib().
struct gl_array_object* _mesa_new_array_object (struct gl_context * ctx, GLuint name) read
Allocate and initialize a new vertex array object.
This function is intended to be called via dd_function_table::NewArrayObject.
References _mesa_initialize_array_object(), and CALLOC_STRUCT.
void _mesa_reference_array_object_ (struct gl_context * ctx, struct gl_array_object ** ptr, struct gl_array_object * arrayObj)
Set ptr to arrayObj w/ reference counting.
Note: this should only be called from the _mesa_reference_array_object() inline function.
References _mesa_problem(), ASSERT, dd_function_table::DeleteArrayObject, gl_context::Driver, gl_array_object::Mutex, gl_array_object::Name, NULL, and gl_array_object::RefCount.
Referenced by _mesa_reference_array_object().
void _mesa_update_array_object_max_element (struct gl_context * ctx, struct gl_array_object * arrayObj)
Examine vertex arrays to update the gl_array_object::_MaxElement field.
References gl_vertex_program_state::_Current, gl_array_object::_MaxElement, _mesa_array_object_get_enabled_arb(), _mesa_array_object_get_enabled_ff(), gl_vertex_program_state::_TnlProgram, compute_max_element(), and gl_context::VertexProgram.
Referenced by _mesa_print_arrays(), and _mesa_update_state_locked().
static void bind_vertex_array (struct gl_context * ctx, GLuint id, GLboolean genRequired) static
Helper for _mesa_BindVertexArray() and _mesa_BindVertexArrayAPPLE().
Parameters
genRequired specifies behavour when id was not generated with glGenVertexArrays().
References _mesa_error(), _mesa_reference_array_object(), _NEW_ARRAY, gl_array_object::ARBsemantics, gl_context::Array, gl_array_attrib::ArrayObj, ASSERT, dd_function_table::BindArrayObject, gl_array_attrib::DefaultArrayObj, gl_context::Driver, gl_array_object::EverBound, lookup_arrayobj(), gl_array_object::Name, dd_function_table::NewArrayObject, gl_context::NewState, NULL, and save_array_object().
Referenced by _mesa_BindVertexArray(), and _mesa_BindVertexArrayAPPLE().
static GLuint compute_max_element (struct gl_array_object * arrayObj, GLbitfield64 enabled) static
Helper for _mesa_update_array_object_max_element().
Returns
min(arrayObj->VertexAttrib[*]._MaxElement).
References gl_client_array::_MaxElement, _mesa_update_array_max_element(), BITFIELD64_BIT, gl_client_array::Enabled, ffsll(), MIN2, and gl_array_object::VertexAttrib.
Referenced by _mesa_update_array_object_max_element().
static void gen_vertex_arrays (struct gl_context * ctx, GLsizei n, GLuint * arrays) static
Generate a set of unique array object IDs and store them in arrays.
Helper for _mesa_GenVertexArrays[APPLE]() functions below.
Parameters
n Number of IDs to generate.
arrays Array of n locations to store the IDs.
vboOnly Will arrays have to reside in VBOs?
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), gl_context::Array, gl_context::Driver, dd_function_table::NewArrayObject, gl_array_attrib::Objects, and save_array_object().
Referenced by _mesa_GenVertexArrays(), and _mesa_GenVertexArraysAPPLE().
static void init_array (struct gl_context * ctx, struct gl_client_array * array, GLint size, GLint type) static
References gl_client_array::_ElementSize, _mesa_reference_buffer_object(), _mesa_sizeof_type(), gl_client_array::BufferObj, gl_client_array::Enabled, gl_client_array::Format, gl_client_array::Integer, gl_client_array::Normalized, NULL, gl_shared_state::NullBufferObj, gl_client_array::Ptr, gl_context::Shared, size, gl_client_array::Size, gl_client_array::Stride, gl_client_array::StrideB, and gl_client_array::Type.
Referenced by _mesa_initialize_array_object().
static struct gl_array_object* lookup_arrayobj (struct gl_context * ctx, GLuint id) static read
Look up the array object for the given ID.
Returns
Either a pointer to the array object with the specified ID or NULL for a non-existent ID. The spec defines ID 0 as being technically non-existent.
References _mesa_HashLookup(), gl_context::Array, NULL, and gl_array_attrib::Objects.
Referenced by _mesa_DeleteVertexArrays(), _mesa_IsVertexArray(), and bind_vertex_array().
static void remove_array_object (struct gl_context * ctx, struct gl_array_object * obj) static
Remove the given array object from the array object pool.
Do not deallocate the array object though.
References _mesa_HashRemove(), gl_context::Array, gl_array_object::Name, and gl_array_attrib::Objects.
Referenced by _mesa_DeleteVertexArrays().
static void save_array_object (struct gl_context * ctx, struct gl_array_object * obj) static
Add the given array object to the array object pool.
References _mesa_HashInsert(), gl_context::Array, gl_array_object::Name, and gl_array_attrib::Objects.
Referenced by bind_vertex_array(), and gen_vertex_arrays().
static void unbind_array_object_vbos (struct gl_context * ctx, struct gl_array_object * obj) static
For all the vertex arrays in the array object, unbind any pointers to any buffer objects (VBOs).
This is done just prior to array object destruction.
References _mesa_reference_buffer_object(), gl_client_array::BufferObj, Elements, NULL, and gl_array_object::VertexAttrib.
Referenced by _mesa_delete_array_object().