Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
buffers.c File Reference
glReadBuffer, DrawBuffer functions.
#include "glheader.h"
#include "buffers.h"
#include "colormac.h"
#include "context.h"
#include "enums.h"
#include "fbobject.h"
#include "mtypes.h"
Macros
#define BAD_MASK ~0u
Functions
static GLbitfield supported_buffer_bitmask (const struct gl_context *ctx, const struct gl_framebuffer *fb)
Return bitmask of BUFFER_BIT_* flags indicating which color buffers are available to the rendering context (for drawing or reading).
static GLbitfield draw_buffer_enum_to_bitmask (const struct gl_context *ctx, GLenum buffer)
Helper routine used by glDrawBuffer and glDrawBuffersARB.
static GLint read_buffer_enum_to_index (GLenum buffer)
Helper routine used by glReadBuffer.
void GLAPIENTRY _mesa_DrawBuffer (GLenum buffer)
Called by glDrawBuffer().
void GLAPIENTRY _mesa_DrawBuffers (GLsizei n, const GLenum *buffers)
Called by glDrawBuffersARB; specifies the destination color renderbuffers for N fragment program color outputs.
static void updated_drawbuffers (struct gl_context *ctx)
Performs necessary state updates when _mesa_drawbuffers makes an actual change.
void _mesa_drawbuffers (struct gl_context *ctx, GLuint n, const GLenum *buffers, const GLbitfield *destMask)
Helper function to set the GL_DRAW_BUFFER state in the context and current FBO.
void _mesa_update_draw_buffers (struct gl_context *ctx)
Update the current drawbuffer's _ColorDrawBufferIndex[] list, etc.
void _mesa_readbuffer (struct gl_context *ctx, GLenum buffer, GLint bufferIndex)
Like.
void GLAPIENTRY _mesa_ReadBuffer (GLenum buffer)
Called by glReadBuffer to set the source renderbuffer for reading pixels.
Detailed Description
glReadBuffer, DrawBuffer functions.
Macro Definition Documentation
#define BAD_MASK ~0u
Referenced by _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_drawbuffers(), and draw_buffer_enum_to_bitmask().
Function Documentation
void GLAPIENTRY _mesa_DrawBuffer (GLenum buffer)
Called by glDrawBuffer().
Specify which renderbuffer(s) to draw into for the first color output. <buffer> can name zero, one, two or four renderbuffers!
See Also
_mesa_DrawBuffers
Parameters
buffer buffer token such as GL_LEFT or GL_FRONT_AND_BACK, etc.
Note that the behaviour of this function depends on whether the current ctx->DrawBuffer is a window-system framebuffer or a user-created framebuffer object. In the former case, we update the per-context ctx->Color.DrawBuffer state var and the FB's ColorDrawBuffer state. In the later case, we update the FB's ColorDrawBuffer state only.
Furthermore, upon a MakeCurrent() or BindFramebuffer() call, if the new FB is a window system FB, we need to re-update the FB's ColorDrawBuffer state to match the context. This is handled in _mesa_update_framebuffer().
See the GL_EXT_framebuffer_object spec for more info.
References _mesa_debug(), _mesa_drawbuffers(), _mesa_error(), _mesa_lookup_enum_by_nr(), BAD_MASK, draw_buffer_enum_to_bitmask(), FLUSH_VERTICES, GLbitfield, MESA_VERBOSE, supported_buffer_bitmask(), and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_DrawBuffers (GLsizei n, const GLenum * buffers)
Called by glDrawBuffersARB; specifies the destination color renderbuffers for N fragment program color outputs.
See Also
_mesa_DrawBuffer
Parameters
n number of outputs
buffers array [n] of renderbuffer names. Unlike glDrawBuffer, the names cannot specify more than one buffer. For example, GL_FRONT_AND_BACK is illegal.
References _mesa_bitcount(), _mesa_drawbuffers(), _mesa_error(), _mesa_is_gles3(), _mesa_is_user_fbo(), _mesa_is_winsys_fbo(), BAD_MASK, draw_buffer_enum_to_bitmask(), FLUSH_VERTICES, GLbitfield, MAX_DRAW_BUFFERS, and supported_buffer_bitmask().
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_drawbuffers (struct gl_context * ctx, GLuint n, const GLenum * buffers, const GLbitfield * destMask)
Helper function to set the GL_DRAW_BUFFER state in the context and current FBO.
Called via glDrawBuffer(), glDrawBuffersARB()
All error checking will have been done prior to calling this function so nothing should go wrong at this point.
Parameters
ctx current context
n number of color outputs to set
buffers array[n] of colorbuffer names, like GL_LEFT.
destMask array[n] of BUFFER_BIT_* bitmasks which correspond to the colorbuffer names. (i.e. GL_FRONT_AND_BACK => BUFFER_BIT_FRONT_LEFT | BUFFER_BIT_BACK_LEFT).
References gl_framebuffer::_ColorDrawBufferIndexes, _mesa_bitcount(), _mesa_is_winsys_fbo(), gl_framebuffer::_NumColorDrawBuffers, ASSERT, BAD_MASK, gl_context::Color, gl_framebuffer::ColorDrawBuffer, gl_context::Const, draw_buffer_enum_to_bitmask(), gl_colorbuffer_attrib::DrawBuffer, gl_context::DrawBuffer, ffs(), GLbitfield, MAX_DRAW_BUFFERS, gl_constants::MaxDrawBuffers, supported_buffer_bitmask(), and updated_drawbuffers().
Referenced by _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_update_draw_buffers(), and update_framebuffer().
void _mesa_readbuffer (struct gl_context * ctx, GLenum buffer, GLint bufferIndex)
Like.
See Also
_mesa_drawbuffers(), this is a helper function for setting GL_READ_BUFFER state in the context and current FBO.
Parameters
ctx the rendering context
buffer GL_FRONT, GL_BACK, GL_COLOR_ATTACHMENT0, etc.
bufferIndex the numerical index corresponding to 'buffer'
References gl_framebuffer::_ColorReadBufferIndex, _mesa_is_winsys_fbo(), _NEW_BUFFERS, gl_framebuffer::ColorReadBuffer, gl_context::NewState, gl_context::Pixel, gl_pixel_attrib::ReadBuffer, and gl_context::ReadBuffer.
Referenced by _mesa_ReadBuffer().
void GLAPIENTRY _mesa_ReadBuffer (GLenum buffer)
Called by glReadBuffer to set the source renderbuffer for reading pixels.
Parameters
mode color buffer such as GL_FRONT, GL_BACK, etc.
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_readbuffer(), FLUSH_VERTICES, GLbitfield, MESA_VERBOSE, read_buffer_enum_to_index(), supported_buffer_bitmask(), and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_update_draw_buffers (struct gl_context * ctx)
Update the current drawbuffer's _ColorDrawBufferIndex[] list, etc.
from the context's Color.DrawBuffer[] state. Use when changing contexts.
References _mesa_drawbuffers(), _mesa_is_winsys_fbo(), gl_context::Color, gl_context::Const, gl_colorbuffer_attrib::DrawBuffer, gl_context::DrawBuffer, MAX_DRAW_BUFFERS, gl_constants::MaxDrawBuffers, and NULL.
Referenced by _mesa_make_current().
static GLbitfield draw_buffer_enum_to_bitmask (const struct gl_context * ctx, GLenum buffer) static
Helper routine used by glDrawBuffer and glDrawBuffersARB.
Given a GLenum naming one or more color buffers (such as GL_FRONT_AND_BACK), return the corresponding bitmask of BUFFER_BIT_* flags.
References _mesa_is_gles3(), BAD_MASK, BUFFER_BIT_AUX0, BUFFER_BIT_BACK_LEFT, BUFFER_BIT_BACK_RIGHT, BUFFER_BIT_COLOR0, BUFFER_BIT_COLOR1, BUFFER_BIT_COLOR2, BUFFER_BIT_COLOR3, BUFFER_BIT_COLOR4, BUFFER_BIT_COLOR5, BUFFER_BIT_COLOR6, BUFFER_BIT_COLOR7, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, BUFFER_COUNT, gl_config::doubleBufferMode, gl_context::DrawBuffer, and gl_framebuffer::Visual.
Referenced by _mesa_DrawBuffer(), _mesa_DrawBuffers(), and _mesa_drawbuffers().
static GLint read_buffer_enum_to_index (GLenum buffer) static
Helper routine used by glReadBuffer.
Given a GLenum naming a color buffer, return the index of the corresponding renderbuffer (a BUFFER_* value). return -1 for an invalid buffer.
References BUFFER_AUX0, BUFFER_BACK_LEFT, BUFFER_BACK_RIGHT, BUFFER_COLOR0, BUFFER_COLOR1, BUFFER_COLOR2, BUFFER_COLOR3, BUFFER_COLOR4, BUFFER_COLOR5, BUFFER_COLOR6, BUFFER_COLOR7, BUFFER_COUNT, BUFFER_FRONT_LEFT, and BUFFER_FRONT_RIGHT.
Referenced by _mesa_ReadBuffer().
static GLbitfield supported_buffer_bitmask (const struct gl_context * ctx, const struct gl_framebuffer * fb) static
Return bitmask of BUFFER_BIT_* flags indicating which color buffers are available to the rendering context (for drawing or reading).
This depends on the type of framebuffer. For window system framebuffers we look at the framebuffer's visual. But for user-create framebuffers we look at the number of supported color attachments.
Parameters
fb the framebuffer to draw to, or read from
Returns
bitmask of BUFFER_BIT_* flags
References _mesa_is_user_fbo(), ASSERT, BUFFER_BIT_AUX0, BUFFER_BIT_BACK_LEFT, BUFFER_BIT_BACK_RIGHT, BUFFER_BIT_COLOR0, BUFFER_BIT_FRONT_LEFT, BUFFER_BIT_FRONT_RIGHT, gl_context::Const, gl_config::doubleBufferMode, gl_extensions::EXT_framebuffer_object, gl_context::Extensions, GLbitfield, gl_constants::MaxColorAttachments, gl_config::numAuxBuffers, gl_config::stereoMode, and gl_framebuffer::Visual.
Referenced by _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_drawbuffers(), and _mesa_ReadBuffer().
static void updated_drawbuffers (struct gl_context * ctx) static
Performs necessary state updates when _mesa_drawbuffers makes an actual change.
References _mesa_is_user_fbo(), _NEW_BUFFERS, gl_framebuffer::_Status, gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_ES2_compatibility, gl_context::DrawBuffer, gl_context::Extensions, and FLUSH_VERTICES.
Referenced by _mesa_drawbuffers().