Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
bufferobj.c File Reference
Functions for the GL_ARB_vertex/pixel_buffer_object extensions.
#include <stdbool.h>
#include "glheader.h"
#include "enums.h"
#include "hash.h"
#include "imports.h"
#include "image.h"
#include "context.h"
#include "bufferobj.h"
#include "fbobject.h"
#include "mtypes.h"
#include "texobj.h"
#include "transformfeedback.h"
#include "dispatch.h"
Functions
static struct gl_buffer_object ** get_buffer_target (struct gl_context *ctx, GLenum target)
Return pointer to address of a buffer object target.
static struct gl_buffer_object * get_buffer (struct gl_context *ctx, const char *func, GLenum target)
Get the buffer object bound to the specified target in a GL context.
static GLenum simplified_access_mode (struct gl_context *ctx, GLbitfield access)
Convert a GLbitfield describing the mapped buffer access flags into one of GL_READ_WRITE, GL_READ_ONLY, or GL_WRITE_ONLY.
static struct gl_buffer_object * buffer_object_subdata_range_good (struct gl_context *ctx, GLenum target, GLintptrARB offset, GLsizeiptrARB size, const char *caller)
Tests the subdata range parameters and sets the GL error code for glBufferSubDataARB and glGetBufferSubDataARB.
static struct gl_buffer_object * _mesa_new_buffer_object (struct gl_context *ctx, GLuint name, GLenum target)
Allocate and initialize a new buffer object.
static void _mesa_delete_buffer_object (struct gl_context *ctx, struct gl_buffer_object *bufObj)
Delete a buffer object.
void _mesa_reference_buffer_object_ (struct gl_context *ctx, struct gl_buffer_object **ptr, struct gl_buffer_object *bufObj)
Set ptr to bufObj w/ reference counting.
void _mesa_initialize_buffer_object (struct gl_context *ctx, struct gl_buffer_object *obj, GLuint name, GLenum target)
Initialize a buffer object to default values.
static void count_buffer_size (GLuint key, void *data, void *userData)
Callback called from _mesa_HashWalk()
GLuint _mesa_total_buffer_object_memory (struct gl_context *ctx)
Compute total size (in bytes) of all buffer objects for the given context.
static GLboolean _mesa_buffer_data (struct gl_context *ctx, GLenum target, GLsizeiptrARB size, const GLvoid *data, GLenum usage, struct gl_buffer_object *bufObj)
Allocate space for and store data in a buffer object.
static void _mesa_buffer_subdata (struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid *data, struct gl_buffer_object *bufObj)
Replace data in a subrange of buffer object.
static void _mesa_buffer_get_subdata (struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid *data, struct gl_buffer_object *bufObj)
Retrieve data from a subrange of buffer object.
static void * _mesa_buffer_map_range (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object *bufObj)
Default fallback for dd_function_table::MapBufferRange().
static void _mesa_buffer_flush_mapped_range (struct gl_context *ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object *obj)
Default fallback for dd_function_table::FlushMappedBufferRange().
static GLboolean _mesa_buffer_unmap (struct gl_context *ctx, struct gl_buffer_object *bufObj)
Default callback for dd_function_table::MapBuffer().
static void _mesa_copy_buffer_subdata (struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
Default fallback for dd_function_table::CopyBufferSubData().
void _mesa_init_buffer_objects (struct gl_context *ctx)
Initialize the state associated with buffer objects.
void _mesa_free_buffer_objects (struct gl_context *ctx)
static bool handle_bind_buffer_gen (struct gl_context *ctx, GLenum target, GLuint buffer, struct gl_buffer_object **buf_handle)
static void bind_buffer_object (struct gl_context *ctx, GLenum target, GLuint buffer)
Bind the specified target to buffer for the specified context.
void _mesa_update_default_objects_buffer_objects (struct gl_context *ctx)
Update the default buffer objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
struct gl_buffer_object * _mesa_lookup_bufferobj (struct gl_context *ctx, GLuint buffer)
Return the gl_buffer_object for the given ID.
static void unbind (struct gl_context *ctx, struct gl_buffer_object **ptr, struct gl_buffer_object *obj)
If *ptr points to obj, set ptr = the Null/default buffer object.
void _mesa_init_buffer_object_functions (struct dd_function_table *driver)
Plug default/fallback buffer object functions into the device driver hooks.
void GLAPIENTRY _mesa_BindBuffer (GLenum target, GLuint buffer)
void GLAPIENTRY _mesa_DeleteBuffers (GLsizei n, const GLuint *ids)
Delete a set of buffer objects.
void GLAPIENTRY _mesa_GenBuffers (GLsizei n, GLuint *buffer)
Generate a set of unique buffer object IDs and store them in buffer.
GLboolean GLAPIENTRY _mesa_IsBuffer (GLuint id)
Determine if ID is the name of a buffer object.
void GLAPIENTRY _mesa_BufferData (GLenum target, GLsizeiptrARB size, const GLvoid *data, GLenum usage)
void GLAPIENTRY _mesa_BufferSubData (GLenum target, GLintptrARB offset, GLsizeiptrARB size, const GLvoid *data)
void GLAPIENTRY _mesa_GetBufferSubData (GLenum target, GLintptrARB offset, GLsizeiptrARB size, void *data)
void *GLAPIENTRY _mesa_MapBuffer (GLenum target, GLenum access)
GLboolean GLAPIENTRY _mesa_UnmapBuffer (GLenum target)
void GLAPIENTRY _mesa_GetBufferParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetBufferParameteri64v (GLenum target, GLenum pname, GLint64 *params)
New in GL 3.2 This is pretty much a duplicate of GetBufferParameteriv() but the GL_BUFFER_SIZE_ARB attribute will be 64-bits on a 64-bit system.
void GLAPIENTRY _mesa_GetBufferPointerv (GLenum target, GLenum pname, GLvoid **params)
void GLAPIENTRY _mesa_CopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
void *GLAPIENTRY _mesa_MapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
See GL_ARB_map_buffer_range spec.
void GLAPIENTRY _mesa_FlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length)
See GL_ARB_map_buffer_range spec.
static GLenum buffer_object_purgeable (struct gl_context *ctx, GLuint name, GLenum option)
static GLenum renderbuffer_purgeable (struct gl_context *ctx, GLuint name, GLenum option)
static GLenum texture_object_purgeable (struct gl_context *ctx, GLuint name, GLenum option)
GLenum GLAPIENTRY _mesa_ObjectPurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
static GLenum buffer_object_unpurgeable (struct gl_context *ctx, GLuint name, GLenum option)
static GLenum renderbuffer_unpurgeable (struct gl_context *ctx, GLuint name, GLenum option)
static GLenum texture_object_unpurgeable (struct gl_context *ctx, GLuint name, GLenum option)
GLenum GLAPIENTRY _mesa_ObjectUnpurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
static void get_buffer_object_parameteriv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
static void get_renderbuffer_parameteriv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
static void get_texture_object_parameteriv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetObjectParameterivAPPLE (GLenum objectType, GLuint name, GLenum pname, GLint *params)
static void set_ubo_binding (struct gl_context *ctx, int index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize)
static void bind_buffer_range_uniform_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size)
Bind a region of a buffer object to a uniform block binding point.
static void bind_buffer_base_uniform_buffer (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj)
Bind a buffer object to a uniform block binding point.
void GLAPIENTRY _mesa_BindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
void GLAPIENTRY _mesa_BindBufferBase (GLenum target, GLuint index, GLuint buffer)
void GLAPIENTRY _mesa_InvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length)
void GLAPIENTRY _mesa_InvalidateBufferData (GLuint buffer)
Variables
static struct gl_buffer_object DummyBufferObject
Used as a placeholder for buffer objects between glGenBuffers() and glBindBuffer() so that glIsBuffer() can work correctly.
Detailed Description
Functions for the GL_ARB_vertex/pixel_buffer_object extensions.
Author
Brian Paul, Ian Romanick
Function Documentation
void GLAPIENTRY _mesa_BindBuffer (GLenum target, GLuint buffer)
References _mesa_debug(), _mesa_lookup_enum_by_nr(), bind_buffer_object(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_DeleteBuffers(), _mesa_initialize_exec_table(), and restore_array_attrib().
void GLAPIENTRY _mesa_BindBufferBase (GLenum target, GLuint index, GLuint buffer)
References _mesa_bind_buffer_base_transform_feedback(), _mesa_error(), _mesa_lookup_bufferobj(), bind_buffer_base_uniform_buffer(), and handle_bind_buffer_gen().
Referenced by _mesa_DeleteBuffers(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
References _mesa_bind_buffer_range_transform_feedback(), _mesa_error(), _mesa_lookup_bufferobj(), bind_buffer_range_uniform_buffer(), and handle_bind_buffer_gen().
Referenced by _mesa_initialize_exec_table().
static GLboolean _mesa_buffer_data (struct gl_context * ctx, GLenum target, GLsizeiptrARB size, const GLvoid * data, GLenum usage, struct gl_buffer_object * bufObj) static
Allocate space for and store data in a buffer object.
Any data that was previously stored in the buffer object is lost. If data is NULL, memory will be allocated, but no copy will occur.
This is the default callback for dd_function_table::BufferData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
target Buffer object target on which to operate.
size Size, in bytes, of the new data store.
data Pointer to the data to store in the buffer object. This pointer may be NULL.
usage Hints about how the data will be used.
bufObj Object to be used.
Returns
GL_TRUE for success, GL_FALSE for failure
See Also
glBufferDataARB, dd_function_table::BufferData.
References _mesa_realloc(), gl_buffer_object::Data, GLubyte, size, gl_buffer_object::Size, gl_buffer_object::Usage, and void().
Referenced by _mesa_init_buffer_object_functions().
static void _mesa_buffer_flush_mapped_range (struct gl_context * ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object * obj) static
Default fallback for dd_function_table::FlushMappedBufferRange().
Called via glFlushMappedBufferRange().
References void().
Referenced by _mesa_init_buffer_object_functions().
static void _mesa_buffer_get_subdata (struct gl_context * ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid * data, struct gl_buffer_object * bufObj) static
Retrieve data from a subrange of buffer object.
If the data range specified by size + offset extends beyond the end of the buffer or if data is NULL, no copy is performed.
This is the default callback for dd_function_table::GetBufferSubData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
target Buffer object target on which to operate.
offset Offset of the first byte to be fetched.
size Size, in bytes, of the data range.
data Destination for data
bufObj Object to be used.
See Also
glBufferGetSubDataARB, dd_function_table::GetBufferSubData.
References gl_buffer_object::Data, GLubyte, gl_buffer_object::Size, and void().
Referenced by _mesa_init_buffer_object_functions().
static void* _mesa_buffer_map_range (struct gl_context * ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object * bufObj) static
Default fallback for dd_function_table::MapBufferRange().
Called via glMapBufferRange().
References _mesa_bufferobj_mapped(), gl_buffer_object::AccessFlags, gl_buffer_object::Data, gl_buffer_object::Length, gl_buffer_object::Offset, gl_buffer_object::Pointer, and void().
Referenced by _mesa_init_buffer_object_functions().
static void _mesa_buffer_subdata (struct gl_context * ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid * data, struct gl_buffer_object * bufObj) static
Replace data in a subrange of buffer object.
If the data range specified by size + offset extends beyond the end of the buffer or if data is NULL, no copy is performed.
This is the default callback for dd_function_table::BufferSubData() Note that all GL error checking will have been done already.
Parameters
ctx GL context.
target Buffer object target on which to operate.
offset Offset of the first byte to be modified.
size Size, in bytes, of the data range.
data Pointer to the data to store in the buffer object.
bufObj Object to be used.
See Also
glBufferSubDataARB, dd_function_table::BufferSubData.
References ASSERT, gl_buffer_object::Data, GLubyte, gl_buffer_object::Size, and void().
Referenced by _mesa_init_buffer_object_functions().
static GLboolean _mesa_buffer_unmap (struct gl_context * ctx, struct gl_buffer_object * bufObj) static
Default callback for dd_function_table::MapBuffer().
The input parameters will have been already tested for errors.
See Also
glUnmapBufferARB, dd_function_table::UnmapBuffer
References gl_buffer_object::AccessFlags, gl_buffer_object::Length, NULL, gl_buffer_object::Offset, gl_buffer_object::Pointer, and void().
Referenced by _mesa_init_buffer_object_functions().
void GLAPIENTRY _mesa_BufferData (GLenum target, GLsizeiptrARB size, const GLvoid * data, GLenum usage)
References _mesa_bufferobj_mapped(), _mesa_debug(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_lookup_enum_by_nr(), _NEW_BUFFER_OBJECT, gl_buffer_object::AccessFlags, API_OPENGLES, ASSERT, FLUSH_VERTICES, get_buffer(), MESA_VERBOSE, gl_buffer_object::Name, NULL, gl_buffer_object::Pointer, VERBOSE_API, and gl_buffer_object::Written.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BufferSubData (GLenum target, GLintptrARB offset, GLsizeiptrARB size, const GLvoid * data)
References ASSERT, buffer_object_subdata_range_good(), and gl_buffer_object::Written.
Referenced by _mesa_initialize_exec_table().
static void _mesa_copy_buffer_subdata (struct gl_context * ctx, struct gl_buffer_object * src, struct gl_buffer_object * dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size) static
Default fallback for dd_function_table::CopyBufferSubData().
Called via glCopyBufferSubData().
References _mesa_bufferobj_mapped(), gl_context::Driver, GLubyte, dd_function_table::MapBufferRange, gl_buffer_object::Size, and dd_function_table::UnmapBuffer.
Referenced by _mesa_init_buffer_object_functions().
void GLAPIENTRY _mesa_CopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
References _mesa_bufferobj_mapped(), _mesa_error(), get_buffer(), and gl_buffer_object::Size.
Referenced by _mesa_initialize_exec_table().
static void _mesa_delete_buffer_object (struct gl_context * ctx, struct gl_buffer_object * bufObj) static
Delete a buffer object.
Default callback for the dd_function_table::DeleteBuffer() hook.
References gl_buffer_object::Data, gl_buffer_object::Mutex, gl_buffer_object::Name, gl_buffer_object::RefCount, and void().
Referenced by _mesa_init_buffer_object_functions().
void GLAPIENTRY _mesa_DeleteBuffers (GLsizei n, const GLuint * ids)
Delete a set of buffer objects.
Parameters
n Number of buffer objects to delete.
ids Array of n buffer object IDs.
References _mesa_BindBuffer(), _mesa_BindBufferBase(), _mesa_bufferobj_mapped(), _mesa_error(), _mesa_HashRemove(), _mesa_lookup_bufferobj(), _mesa_reference_buffer_object(), gl_buffer_object::AccessFlags, ASSERT, gl_client_array::BufferObj, gl_buffer_object::DeletePending, DummyBufferObject, gl_array_object::ElementArrayBufferObj, Elements, FLUSH_VERTICES, MAX_FEEDBACK_BUFFERS, gl_buffer_object::Name, NULL, gl_buffer_object::Pointer, unbind(), and gl_array_object::VertexAttrib.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length)
See GL_ARB_map_buffer_range spec.
References _mesa_bufferobj_mapped(), _mesa_error(), gl_buffer_object::AccessFlags, ASSERT, get_buffer(), and gl_buffer_object::Length.
Referenced by _mesa_initialize_exec_table().
void _mesa_free_buffer_objects (struct gl_context * ctx)
References _mesa_reference_buffer_object(), gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_uniform_buffer_binding::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, MAX_COMBINED_UNIFORM_BUFFERS, NULL, gl_context::UniformBuffer, and gl_context::UniformBufferBindings.
Referenced by _mesa_free_context_data().
void GLAPIENTRY _mesa_GenBuffers (GLsizei n, GLuint * buffer)
Generate a set of unique buffer object IDs and store them in buffer.
Parameters
n Number of IDs to generate.
buffer Array of n locations to store the IDs.
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), DummyBufferObject, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetBufferParameteri64v (GLenum target, GLenum pname, GLint64 * params)
New in GL 3.2 This is pretty much a duplicate of GetBufferParameteriv() but the GL_BUFFER_SIZE_ARB attribute will be 64-bits on a 64-bit system.
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_lookup_enum_by_nr(), gl_buffer_object::AccessFlags, get_buffer(), gl_buffer_object::Length, gl_buffer_object::Offset, simplified_access_mode(), gl_buffer_object::Size, and gl_buffer_object::Usage.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetBufferParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_lookup_enum_by_nr(), gl_buffer_object::AccessFlags, get_buffer(), gl_buffer_object::Length, gl_buffer_object::Offset, simplified_access_mode(), gl_buffer_object::Size, and gl_buffer_object::Usage.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetBufferPointerv (GLenum target, GLenum pname, GLvoid ** params)
References _mesa_error(), get_buffer(), and gl_buffer_object::Pointer.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetBufferSubData (GLenum target, GLintptrARB offset, GLsizeiptrARB size, void * data)
References ASSERT, and buffer_object_subdata_range_good().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetObjectParameterivAPPLE (GLenum objectType, GLuint name, GLenum pname, GLint * params)
References _mesa_error(), get_buffer_object_parameteriv(), get_renderbuffer_parameteriv(), and get_texture_object_parameteriv().
Referenced by _mesa_initialize_exec_table().
void _mesa_init_buffer_object_functions (struct dd_function_table * driver)
Plug default/fallback buffer object functions into the device driver hooks.
References _mesa_buffer_data(), _mesa_buffer_flush_mapped_range(), _mesa_buffer_get_subdata(), _mesa_buffer_map_range(), _mesa_buffer_subdata(), _mesa_buffer_unmap(), _mesa_copy_buffer_subdata(), _mesa_delete_buffer_object(), _mesa_new_buffer_object(), dd_function_table::BindBuffer, dd_function_table::BufferData, dd_function_table::BufferSubData, dd_function_table::CopyBufferSubData, dd_function_table::DeleteBuffer, dd_function_table::FlushMappedBufferRange, dd_function_table::GetBufferSubData, dd_function_table::MapBufferRange, dd_function_table::NewBufferObject, NULL, and dd_function_table::UnmapBuffer.
void _mesa_init_buffer_objects (struct gl_context * ctx)
Initialize the state associated with buffer objects.
References _mesa_reference_buffer_object(), gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_uniform_buffer_binding::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, DummyBufferObject, MAX_COMBINED_UNIFORM_BUFFERS, gl_buffer_object::Mutex, gl_shared_state::NullBufferObj, gl_uniform_buffer_binding::Offset, gl_buffer_object::RefCount, gl_context::Shared, gl_uniform_buffer_binding::Size, gl_context::UniformBuffer, and gl_context::UniformBufferBindings.
Referenced by init_attrib_groups().
void _mesa_initialize_buffer_object (struct gl_context * ctx, struct gl_buffer_object * obj, GLuint name, GLenum target)
Initialize a buffer object to default values.
References gl_buffer_object::AccessFlags, gl_buffer_object::Mutex, gl_buffer_object::Name, gl_buffer_object::RefCount, gl_buffer_object::Usage, and void().
Referenced by _mesa_new_buffer_object().
void GLAPIENTRY _mesa_InvalidateBufferData (GLuint buffer)
References _mesa_bufferobj_mapped(), _mesa_error(), and _mesa_lookup_bufferobj().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_InvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length)
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_lookup_bufferobj(), GLintptr, gl_buffer_object::Length, gl_buffer_object::Offset, and gl_buffer_object::Size.
Referenced by _mesa_initialize_exec_table().
GLboolean GLAPIENTRY _mesa_IsBuffer (GLuint id)
Determine if ID is the name of a buffer object.
Parameters
id ID of the potential buffer object.
Returns
GL_TRUE if id is the name of a buffer object, GL_FALSE otherwise.
References _mesa_lookup_bufferobj(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, and DummyBufferObject.
Referenced by _mesa_initialize_exec_table(), and restore_array_attrib().
struct gl_buffer_object* _mesa_lookup_bufferobj (struct gl_context * ctx, GLuint buffer) read
Return the gl_buffer_object for the given ID.
Always return NULL for ID 0.
References _mesa_HashLookup(), gl_shared_state::BufferObjects, NULL, and gl_context::Shared.
Referenced by _mesa_BindBufferBase(), _mesa_BindBufferOffsetEXT(), _mesa_BindBufferRange(), _mesa_DeleteBuffers(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_IsBuffer(), _mesa_TexBuffer(), _mesa_TexBufferRange(), bind_buffer_object(), buffer_object_purgeable(), buffer_object_unpurgeable(), and get_buffer_object_parameteriv().
void* GLAPIENTRY _mesa_MapBuffer (GLenum target, GLenum access)
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_is_desktop_gl(), gl_buffer_object::AccessFlags, ASSERT, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, get_buffer(), GLbitfield, GLubyte, gl_buffer_object::Length, gl_buffer_object::Name, NULL, gl_buffer_object::Offset, gl_buffer_object::Pointer, gl_buffer_object::Size, and gl_buffer_object::Written.
Referenced by _mesa_initialize_exec_table().
void* GLAPIENTRY _mesa_MapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
See GL_ARB_map_buffer_range spec.
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_is_gles(), gl_buffer_object::AccessFlags, ASSERT, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, get_buffer(), gl_buffer_object::Length, NULL, gl_buffer_object::Offset, gl_buffer_object::Pointer, and gl_buffer_object::Size.
Referenced by _mesa_initialize_exec_table().
static struct gl_buffer_object* _mesa_new_buffer_object (struct gl_context * ctx, GLuint name, GLenum target) static read
Allocate and initialize a new buffer object.
Default callback for the dd_function_table::NewBufferObject() hook.
References _mesa_initialize_buffer_object(), MALLOC_STRUCT, and void().
Referenced by _mesa_init_buffer_object_functions().
GLenum GLAPIENTRY _mesa_ObjectPurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, buffer_object_purgeable(), renderbuffer_purgeable(), and texture_object_purgeable().
Referenced by _mesa_initialize_exec_table().
GLenum GLAPIENTRY _mesa_ObjectUnpurgeableAPPLE (GLenum objectType, GLuint name, GLenum option)
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, buffer_object_unpurgeable(), renderbuffer_unpurgeable(), and texture_object_unpurgeable().
Referenced by _mesa_initialize_exec_table().
void _mesa_reference_buffer_object_ (struct gl_context * ctx, struct gl_buffer_object ** ptr, struct gl_buffer_object * bufObj)
Set ptr to bufObj w/ reference counting.
This is normally only called from the _mesa_reference_buffer_object() macro when there's a real pointer change.
References _mesa_problem(), gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_array_attrib::ArrayObj, ASSERT, dd_function_table::DeleteBuffer, gl_context::Driver, gl_array_object::ElementArrayBufferObj, gl_buffer_object::Mutex, gl_buffer_object::Name, NULL, and gl_buffer_object::RefCount.
Referenced by _mesa_reference_buffer_object().
GLuint _mesa_total_buffer_object_memory (struct gl_context * ctx)
Compute total size (in bytes) of all buffer objects for the given context.
For debugging purposes.
References _mesa_HashWalk(), gl_shared_state::BufferObjects, count_buffer_size(), and gl_context::Shared.
GLboolean GLAPIENTRY _mesa_UnmapBuffer (GLenum target)
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_warning(), gl_buffer_object::AccessFlags, ASSERT, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, get_buffer(), GLubyte, gl_buffer_object::Length, gl_buffer_object::Name, NULL, gl_buffer_object::Offset, gl_buffer_object::Pointer, and gl_buffer_object::Size.
Referenced by _mesa_initialize_exec_table().
void _mesa_update_default_objects_buffer_objects (struct gl_context * ctx)
Update the default buffer objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
References bind_buffer_object().
Referenced by update_default_objects().
static void bind_buffer_base_uniform_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj) static
Bind a buffer object to a uniform block binding point.
As above, but offset = 0.
References _mesa_error(), _mesa_reference_buffer_object(), gl_context::Const, gl_constants::MaxUniformBufferBindings, gl_shared_state::NullBufferObj, set_ubo_binding(), gl_context::Shared, and gl_context::UniformBuffer.
Referenced by _mesa_BindBufferBase().
static void bind_buffer_object (struct gl_context * ctx, GLenum target, GLuint buffer) static
Bind the specified target to buffer for the specified context.
Called by glBindBuffer() and other functions.
References _mesa_error(), _mesa_lookup_bufferobj(), _mesa_reference_buffer_object(), dd_function_table::BindBuffer, gl_buffer_object::DeletePending, gl_context::Driver, get_buffer_target(), handle_bind_buffer_gen(), gl_buffer_object::Name, NULL, gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by _mesa_BindBuffer(), and _mesa_update_default_objects_buffer_objects().
static void bind_buffer_range_uniform_buffer (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size) static
Bind a region of a buffer object to a uniform block binding point.
Parameters
index the uniform buffer binding point index
bufObj the buffer object
offset offset to the start of buffer object region
size size of the buffer object region
References _mesa_error(), _mesa_reference_buffer_object(), gl_context::Const, gl_constants::MaxUniformBufferBindings, gl_shared_state::NullBufferObj, set_ubo_binding(), gl_context::Shared, gl_context::UniformBuffer, and gl_constants::UniformBufferOffsetAlignment.
Referenced by _mesa_BindBufferRange().
static GLenum buffer_object_purgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_is_bufferobj(), _mesa_lookup_bufferobj(), dd_function_table::BufferObjectPurgeable, gl_context::Driver, and gl_buffer_object::Purgeable.
Referenced by _mesa_ObjectPurgeableAPPLE().
static struct gl_buffer_object* buffer_object_subdata_range_good (struct gl_context * ctx, GLenum target, GLintptrARB offset, GLsizeiptrARB size, const char * caller) static read
Tests the subdata range parameters and sets the GL error code for glBufferSubDataARB and glGetBufferSubDataARB.
Parameters
ctx GL context.
target Buffer object target on which to operate.
offset Offset of the first byte of the subdata range.
size Size, in bytes, of the subdata range.
caller Name of calling function for recording errors.
Returns
A pointer to the buffer object bound to target in the specified context or NULL if any of the parameter or state conditions for glBufferSubDataARB or glGetBufferSubDataARB are invalid.
See Also
glBufferSubDataARB, glGetBufferSubDataARB
References _mesa_bufferobj_mapped(), _mesa_error(), get_buffer(), NULL, and gl_buffer_object::Size.
Referenced by _mesa_BufferSubData(), and _mesa_GetBufferSubData().
static GLenum buffer_object_unpurgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_bufferobj(), dd_function_table::BufferObjectUnpurgeable, gl_context::Driver, and gl_buffer_object::Purgeable.
Referenced by _mesa_ObjectUnpurgeableAPPLE().
static void count_buffer_size (GLuint key, void * data, void * userData) static
Callback called from _mesa_HashWalk()
References gl_buffer_object::Size.
Referenced by _mesa_total_buffer_object_memory().
static struct gl_buffer_object* get_buffer (struct gl_context * ctx, const char * func, GLenum target) static read
Get the buffer object bound to the specified target in a GL context.
Parameters
ctx the GL context
target the buffer object target to be retrieved.
Returns
pointer to the buffer object bound to target in the specified context or NULL if target is invalid.
References _mesa_error(), _mesa_is_bufferobj(), get_buffer_target(), and NULL.
Referenced by _mesa_BufferData(), _mesa_CopyBufferSubData(), _mesa_FlushMappedBufferRange(), _mesa_GetBufferParameteri64v(), _mesa_GetBufferParameteriv(), _mesa_GetBufferPointerv(), _mesa_MapBuffer(), _mesa_MapBufferRange(), _mesa_UnmapBuffer(), and buffer_object_subdata_range_good().
static void get_buffer_object_parameteriv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
References _mesa_error(), _mesa_lookup_bufferobj(), and gl_buffer_object::Purgeable.
Referenced by _mesa_GetObjectParameterivAPPLE().
static struct gl_buffer_object** get_buffer_target (struct gl_context * ctx, GLenum target) static read
Return pointer to address of a buffer object target.
Parameters
ctx the GL context
target the buffer object target to be retrieved.
Returns
pointer to pointer to the buffer object bound to target in the specified context or NULL if target is invalid.
References _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_uniform_buffer_object, gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_array_attrib::ArrayObj, gl_pixelstore_attrib::BufferObj, gl_texture_attrib::BufferObject, gl_context::CopyReadBuffer, gl_context::CopyWriteBuffer, gl_transform_feedback_state::CurrentBuffer, gl_array_object::ElementArrayBufferObj, gl_extensions::EXT_transform_feedback, gl_context::Extensions, NULL, gl_context::Pack, gl_context::Texture, gl_context::TransformFeedback, gl_context::UniformBuffer, and gl_context::Unpack.
Referenced by bind_buffer_object(), and get_buffer().
static void get_renderbuffer_parameteriv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
References _mesa_error(), _mesa_lookup_renderbuffer(), and gl_renderbuffer::Purgeable.
Referenced by _mesa_GetObjectParameterivAPPLE().
static void get_texture_object_parameteriv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
References _mesa_error(), _mesa_lookup_texture(), and gl_texture_object::Purgeable.
Referenced by _mesa_GetObjectParameterivAPPLE().
static bool handle_bind_buffer_gen (struct gl_context * ctx, GLenum target, GLuint buffer, struct gl_buffer_object ** buf_handle) static
References _mesa_error(), _mesa_HashInsert(), gl_context::API, API_OPENGL_CORE, ASSERT, gl_shared_state::BufferObjects, gl_context::Driver, DummyBufferObject, dd_function_table::NewBufferObject, and gl_context::Shared.
Referenced by _mesa_BindBufferBase(), _mesa_BindBufferRange(), and bind_buffer_object().
static GLenum renderbuffer_purgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_renderbuffer(), gl_context::Driver, gl_renderbuffer::Purgeable, and dd_function_table::RenderObjectPurgeable.
Referenced by _mesa_ObjectPurgeableAPPLE().
static GLenum renderbuffer_unpurgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_renderbuffer(), gl_context::Driver, gl_renderbuffer::Purgeable, and dd_function_table::RenderObjectUnpurgeable.
Referenced by _mesa_ObjectUnpurgeableAPPLE().
static void set_ubo_binding (struct gl_context * ctx, int index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size, GLboolean autoSize) static
References _mesa_reference_buffer_object(), gl_uniform_buffer_binding::AutomaticSize, gl_uniform_buffer_binding::BufferObject, gl_context::DriverFlags, FLUSH_VERTICES, gl_context::NewDriverState, gl_driver_flags::NewUniformBuffer, gl_uniform_buffer_binding::Offset, size, gl_uniform_buffer_binding::Size, and gl_context::UniformBufferBindings.
Referenced by bind_buffer_base_uniform_buffer(), and bind_buffer_range_uniform_buffer().
static GLenum simplified_access_mode (struct gl_context * ctx, GLbitfield access) static
Convert a GLbitfield describing the mapped buffer access flags into one of GL_READ_WRITE, GL_READ_ONLY, or GL_WRITE_ONLY.
References _mesa_is_gles(), and GLbitfield.
Referenced by _mesa_GetBufferParameteri64v(), and _mesa_GetBufferParameteriv().
static GLenum texture_object_purgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_texture(), gl_context::Driver, gl_texture_object::Purgeable, and dd_function_table::TextureObjectPurgeable.
Referenced by _mesa_ObjectPurgeableAPPLE().
static GLenum texture_object_unpurgeable (struct gl_context * ctx, GLuint name, GLenum option) static
References _mesa_error(), _mesa_lookup_texture(), gl_context::Driver, gl_texture_object::Purgeable, and dd_function_table::TextureObjectUnpurgeable.
Referenced by _mesa_ObjectUnpurgeableAPPLE().
static void unbind (struct gl_context * ctx, struct gl_buffer_object ** ptr, struct gl_buffer_object * obj) static
If *ptr points to obj, set ptr = the Null/default buffer object.
This is a helper for buffer object deletion. The GL spec says that deleting a buffer object causes it to get unbound from all arrays in the current context.
References _mesa_reference_buffer_object(), gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by _mesa_DeleteBuffers().
Variable Documentation
struct gl_buffer_object DummyBufferObject static
Used as a placeholder for buffer objects between glGenBuffers() and glBindBuffer() so that glIsBuffer() can work correctly.
Referenced by _mesa_DeleteBuffers(), _mesa_GenBuffers(), _mesa_init_buffer_objects(), _mesa_IsBuffer(), and handle_bind_buffer_gen().