Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
buffers.h File Reference
Frame buffer management functions declarations.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_DrawBuffer (GLenum mode)
Called by glDrawBuffer().
void GLAPIENTRY _mesa_DrawBuffers (GLsizei n, const GLenum *buffers)
Called by glDrawBuffersARB; specifies the destination color renderbuffers for N fragment program color outputs.
void _mesa_drawbuffers (struct gl_context *ctx, GLuint n, const GLenum *buffers, const GLbitfield *destMask)
Helper function to set the GL_DRAW_BUFFER state in the context and current FBO.
void _mesa_readbuffer (struct gl_context *ctx, GLenum buffer, GLint bufferIndex)
Like.
void _mesa_update_draw_buffers (struct gl_context *ctx)
Update the current drawbuffer's _ColorDrawBufferIndex[] list, etc.
void GLAPIENTRY _mesa_ReadBuffer (GLenum mode)
Called by glReadBuffer to set the source renderbuffer for reading pixels.
Detailed Description
Frame buffer management functions declarations.
Function Documentation
void GLAPIENTRY _mesa_DrawBuffer (GLenum buffer)
Called by glDrawBuffer().
Specify which renderbuffer(s) to draw into for the first color output. <buffer> can name zero, one, two or four renderbuffers!
See Also
_mesa_DrawBuffers
Parameters
buffer buffer token such as GL_LEFT or GL_FRONT_AND_BACK, etc.
Note that the behaviour of this function depends on whether the current ctx->DrawBuffer is a window-system framebuffer or a user-created framebuffer object. In the former case, we update the per-context ctx->Color.DrawBuffer state var and the FB's ColorDrawBuffer state. In the later case, we update the FB's ColorDrawBuffer state only.
Furthermore, upon a MakeCurrent() or BindFramebuffer() call, if the new FB is a window system FB, we need to re-update the FB's ColorDrawBuffer state to match the context. This is handled in _mesa_update_framebuffer().
See the GL_EXT_framebuffer_object spec for more info.
References _mesa_debug(), _mesa_drawbuffers(), _mesa_error(), _mesa_lookup_enum_by_nr(), BAD_MASK, draw_buffer_enum_to_bitmask(), FLUSH_VERTICES, GLbitfield, MESA_VERBOSE, supported_buffer_bitmask(), and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_DrawBuffers (GLsizei n, const GLenum * buffers)
Called by glDrawBuffersARB; specifies the destination color renderbuffers for N fragment program color outputs.
See Also
_mesa_DrawBuffer
Parameters
n number of outputs
buffers array [n] of renderbuffer names. Unlike glDrawBuffer, the names cannot specify more than one buffer. For example, GL_FRONT_AND_BACK is illegal.
References _mesa_bitcount(), _mesa_drawbuffers(), _mesa_error(), _mesa_is_gles3(), _mesa_is_user_fbo(), _mesa_is_winsys_fbo(), BAD_MASK, draw_buffer_enum_to_bitmask(), FLUSH_VERTICES, GLbitfield, MAX_DRAW_BUFFERS, and supported_buffer_bitmask().
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_drawbuffers (struct gl_context * ctx, GLuint n, const GLenum * buffers, const GLbitfield * destMask)
Helper function to set the GL_DRAW_BUFFER state in the context and current FBO.
Called via glDrawBuffer(), glDrawBuffersARB()
All error checking will have been done prior to calling this function so nothing should go wrong at this point.
Parameters
ctx current context
n number of color outputs to set
buffers array[n] of colorbuffer names, like GL_LEFT.
destMask array[n] of BUFFER_BIT_* bitmasks which correspond to the colorbuffer names. (i.e. GL_FRONT_AND_BACK => BUFFER_BIT_FRONT_LEFT | BUFFER_BIT_BACK_LEFT).
References gl_framebuffer::_ColorDrawBufferIndexes, _mesa_bitcount(), _mesa_is_winsys_fbo(), gl_framebuffer::_NumColorDrawBuffers, ASSERT, BAD_MASK, gl_context::Color, gl_framebuffer::ColorDrawBuffer, gl_context::Const, draw_buffer_enum_to_bitmask(), gl_colorbuffer_attrib::DrawBuffer, gl_context::DrawBuffer, ffs(), GLbitfield, MAX_DRAW_BUFFERS, gl_constants::MaxDrawBuffers, supported_buffer_bitmask(), and updated_drawbuffers().
Referenced by _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_update_draw_buffers(), and update_framebuffer().
void _mesa_readbuffer (struct gl_context * ctx, GLenum buffer, GLint bufferIndex)
Like.
See Also
_mesa_drawbuffers(), this is a helper function for setting GL_READ_BUFFER state in the context and current FBO.
Parameters
ctx the rendering context
buffer GL_FRONT, GL_BACK, GL_COLOR_ATTACHMENT0, etc.
bufferIndex the numerical index corresponding to 'buffer'
References gl_framebuffer::_ColorReadBufferIndex, _mesa_is_winsys_fbo(), _NEW_BUFFERS, gl_framebuffer::ColorReadBuffer, gl_context::NewState, gl_context::Pixel, gl_pixel_attrib::ReadBuffer, and gl_context::ReadBuffer.
Referenced by _mesa_ReadBuffer().
void GLAPIENTRY _mesa_ReadBuffer (GLenum buffer)
Called by glReadBuffer to set the source renderbuffer for reading pixels.
Parameters
mode color buffer such as GL_FRONT, GL_BACK, etc.
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_readbuffer(), FLUSH_VERTICES, GLbitfield, MESA_VERBOSE, read_buffer_enum_to_index(), supported_buffer_bitmask(), and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_update_draw_buffers (struct gl_context * ctx)
Update the current drawbuffer's _ColorDrawBufferIndex[] list, etc.
from the context's Color.DrawBuffer[] state. Use when changing contexts.
References _mesa_drawbuffers(), _mesa_is_winsys_fbo(), gl_context::Color, gl_context::Const, gl_colorbuffer_attrib::DrawBuffer, gl_context::DrawBuffer, MAX_DRAW_BUFFERS, gl_constants::MaxDrawBuffers, and NULL.
Referenced by _mesa_make_current().