Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
clip.c File Reference
#include "glheader.h"
#include "clip.h"
#include "context.h"
#include "macros.h"
#include "mtypes.h"
#include "math/m_matrix.h"
Functions
void _mesa_update_clip_plane (struct gl_context *ctx, GLuint plane)
Update derived clip plane state.
void GLAPIENTRY _mesa_ClipPlane (GLenum plane, const GLdouble *eq)
void GLAPIENTRY _mesa_GetClipPlane (GLenum plane, GLdouble *equation)
Function Documentation
void GLAPIENTRY _mesa_ClipPlane (GLenum plane, const GLdouble * eq)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_error(), _mesa_transform_vector(), _mesa_update_clip_plane(), _NEW_TRANSFORM, COPY_4FV(), FLUSH_VERTICES, and TEST_EQ_4V.
Referenced by _mesa_ClipPlanef(), _mesa_ClipPlanex(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetClipPlane (GLenum plane, GLdouble * equation)
References _mesa_error().
Referenced by _mesa_GetClipPlanef(), _mesa_GetClipPlanex(), and _mesa_initialize_exec_table().
void _mesa_update_clip_plane (struct gl_context * ctx, GLuint plane)
Update derived clip plane state.
References gl_transform_attrib::_ClipUserPlane, _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_transform_vector(), gl_transform_attrib::EyeUserPlane, GLmatrix::inv, gl_context::ProjectionMatrixStack, gl_matrix_stack::Top, and gl_context::Transform.
Referenced by _mesa_ClipPlane(), and _mesa_set_enable().