Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
colortab.h File Reference
#include "compiler.h"
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_ColorTable (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table)
void GLAPIENTRY _mesa_ColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *table)
void GLAPIENTRY _mesa_CopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_GetnColorTableARB (GLenum target, GLenum format, GLenum type, GLsizei bufSize, GLvoid *data)
void GLAPIENTRY _mesa_GetColorTable (GLenum target, GLenum format, GLenum type, GLvoid *data)
void GLAPIENTRY _mesa_ColorTableParameterfv (GLenum target, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_ColorTableParameteriv (GLenum target, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_GetColorTableParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetColorTableParameteriv (GLenum target, GLenum pname, GLint *params)
Function Documentation
void GLAPIENTRY _mesa_ColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid * table)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ColorTable (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * table)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ColorTableParameterfv (GLenum target, GLenum pname, const GLfloat * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ColorTableParameteriv (GLenum target, GLenum pname, const GLint * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetColorTable (GLenum target, GLenum format, GLenum type, GLvoid * data)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetColorTableParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetColorTableParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnColorTableARB (GLenum target, GLenum format, GLenum type, GLsizei bufSize, GLvoid * data)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().