Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
context.c File Reference
Mesa context/visual/framebuffer management functions.
#include "glheader.h"
#include "imports.h"
#include "accum.h"
#include "api_exec.h"
#include "api_loopback.h"
#include "arrayobj.h"
#include "attrib.h"
#include "blend.h"
#include "buffers.h"
#include "bufferobj.h"
#include "context.h"
#include "cpuinfo.h"
#include "debug.h"
#include "depth.h"
#include "dlist.h"
#include "eval.h"
#include "extensions.h"
#include "fbobject.h"
#include "feedback.h"
#include "fog.h"
#include "formats.h"
#include "framebuffer.h"
#include "hint.h"
#include "hash.h"
#include "light.h"
#include "lines.h"
#include "macros.h"
#include "matrix.h"
#include "multisample.h"
#include "pixel.h"
#include "pixelstore.h"
#include "points.h"
#include "polygon.h"
#include "queryobj.h"
#include "syncobj.h"
#include "rastpos.h"
#include "remap.h"
#include "scissor.h"
#include "shared.h"
#include "shaderobj.h"
#include "simple_list.h"
#include "state.h"
#include "stencil.h"
#include "texcompress_s3tc.h"
#include "texstate.h"
#include "transformfeedback.h"
#include "mtypes.h"
#include "varray.h"
#include "version.h"
#include "viewport.h"
#include "vtxfmt.h"
#include "program/program.h"
#include "program/prog_print.h"
#include "math/m_matrix.h"
#include "main/dispatch.h"
#include "glsl_parser_extras.h"
#include <stdbool.h>
Macros
#define COPY_DISPATCH(func) SET_##func(table, GET_##func(ctx->Exec))
Functions
void _mesa_notifySwapBuffers (struct gl_context *ctx)
Swap buffers notification callback.
GL Visual allocation/destruction
struct gl_config * _mesa_create_visual (GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples)
Allocates a struct gl_config structure and initializes it via _mesa_initialize_visual().
GLboolean _mesa_initialize_visual (struct gl_config *vis, GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples)
Makes some sanity checks and fills in the fields of the struct gl_config object with the given parameters.
void _mesa_destroy_visual (struct gl_config *vis)
Destroy a visual and free its memory.
Context allocation, initialization, destroying
The purpose of the most initialization functions here is to provide the default state values according to the OpenGL specification.
static void dummy_enum_func (void)
This is lame.
_glthread_DECLARE_STATIC_MUTEX (OneTimeLock)
One-time initialization mutex lock.
static void one_time_init (struct gl_context *ctx)
Calls all the various one-time-init functions in Mesa.
static void _mesa_init_current (struct gl_context *ctx)
Initialize fields of gl_current_attrib (aka ctx->Current.
static void init_program_limits (struct gl_context *ctx, GLenum type, struct gl_program_constants *prog)
Init vertex/fragment/geometry program limits.
static void _mesa_init_constants (struct gl_context *ctx)
Initialize fields of gl_constants (aka ctx->Const.
static void check_context_limits (struct gl_context *ctx)
Do some sanity checks on the limits/constants for the given context.
static GLboolean init_attrib_groups (struct gl_context *ctx)
Initialize the attribute groups in a GL context.
static GLboolean update_default_objects (struct gl_context *ctx)
Update default objects in a GL context with respect to shared state.
int _mesa_generic_nop (void)
This is the default function we plug into all dispatch table slots This helps prevents a segfault when someone calls a GL function without first checking if the extension's supported.
struct _glapi_table * _mesa_alloc_dispatch_table ()
Allocate and initialize a new dispatch table.
static struct _glapi_table * create_beginend_table (const struct gl_context *ctx)
Creates a minimal dispatch table for use within glBegin()/glEnd().
void _mesa_initialize_dispatch_tables (struct gl_context *ctx)
GLboolean _mesa_initialize_context (struct gl_context *ctx, gl_api api, const struct gl_config *visual, struct gl_context *share_list, const struct dd_function_table *driverFunctions)
Initialize a struct gl_context struct (rendering context).
struct gl_context * _mesa_create_context (gl_api api, const struct gl_config *visual, struct gl_context *share_list, const struct dd_function_table *driverFunctions)
Allocate and initialize a struct gl_context structure.
void _mesa_free_context_data (struct gl_context *ctx)
Free the data associated with the given context.
void _mesa_destroy_context (struct gl_context *ctx)
Destroy a struct gl_context structure.
void _mesa_copy_context (const struct gl_context *src, struct gl_context *dst, GLuint mask)
Copy attribute groups from one context to another.
static GLboolean check_compatible (const struct gl_context *ctx, const struct gl_framebuffer *buffer)
Check if the given context can render into the given framebuffer by checking visual attributes.
static void initialize_framebuffer_size (struct gl_context *ctx, struct gl_framebuffer *fb)
Do one-time initialization for the given framebuffer.
void _mesa_check_init_viewport (struct gl_context *ctx, GLuint width, GLuint height)
Check if the viewport/scissor size has not yet been initialized.
GLboolean _mesa_make_current (struct gl_context *newCtx, struct gl_framebuffer *drawBuffer, struct gl_framebuffer *readBuffer)
Bind the given context to the given drawBuffer and readBuffer and make it the current context for the calling thread.
GLboolean _mesa_share_state (struct gl_context *ctx, struct gl_context *ctxToShare)
Make context 'ctx' share the display lists, textures and programs that are associated with 'ctxToShare'.
struct gl_context * _mesa_get_current_context (void)
struct _glapi_table * _mesa_get_dispatch (struct gl_context *ctx)
Get context's current API dispatch table.
Miscellaneous functions
void _mesa_record_error (struct gl_context *ctx, GLenum error)
Record an error.
void _mesa_finish (struct gl_context *ctx)
Flush commands and wait for completion.
void _mesa_flush (struct gl_context *ctx)
Flush commands.
void GLAPIENTRY _mesa_Finish (void)
Execute glFinish().
void GLAPIENTRY _mesa_Flush (void)
Execute glFlush().
static GLboolean _mesa_check_blend_func_error (struct gl_context *ctx)
GLboolean _mesa_valid_to_render (struct gl_context *ctx, const char *where)
Prior to drawing anything with glBegin, glDrawArrays, etc.
Variables
GLfloat _mesa_ubyte_to_float_color_tab [256]
Convert GLubyte in [0,255] to GLfloat in [0.0,1.0].
Detailed Description
Mesa context/visual/framebuffer management functions.
Author
Brian Paul
Macro Definition Documentation
#define COPY_DISPATCH (func) SET_##func(table, GET_##func(ctx->Exec))
Referenced by create_beginend_table().
Function Documentation
_glthread_DECLARE_STATIC_MUTEX (OneTimeLock)
One-time initialization mutex lock.
See Also
Used by one_time_init().
struct _glapi_table* _mesa_alloc_dispatch_table (void) read
Allocate and initialize a new dispatch table.
References _gloffset_COUNT, _mesa_generic_nop(), MAX2, and table.
Referenced by _mesa_initialize_context(), and create_beginend_table().
static GLboolean _mesa_check_blend_func_error (struct gl_context * ctx) static
References _mesa_error(), gl_colorbuffer_attrib::_UsesDualSrc, gl_colorbuffer_attrib::Blend, gl_context::Color, gl_context::Const, and gl_constants::MaxDualSourceDrawBuffers.
Referenced by _mesa_valid_to_render().
void _mesa_check_init_viewport (struct gl_context * ctx, GLuint width, GLuint height)
Check if the viewport/scissor size has not yet been initialized.
Initialize the size if the given width and height are non-zero.
References _mesa_set_scissor(), _mesa_set_viewport(), and gl_context::ViewportInitialized.
Referenced by _mesa_make_current().
void _mesa_copy_context (const struct gl_context * src, struct gl_context * dst, GLuint mask)
Copy attribute groups from one context to another.
Parameters
src source context
dst destination context
mask bitwise OR of GL_*_BIT flags
According to the bits specified in mask, copies the corresponding attributes from src into dst. For many of the attributes a simple memcpy is not enough due to the existence of internal pointers in their data structures.
References _math_matrix_copy(), _mesa_copy_texture_state(), _NEW_ALL, gl_viewport_attrib::_WindowMap, gl_context::Accum, gl_context::Color, gl_context::Current, gl_context::Depth, gl_light::Enabled, gl_light_attrib::EnabledList, gl_context::Eval, gl_viewport_attrib::Far, gl_context::Fog, gl_viewport_attrib::Height, gl_context::Hint, insert_at_tail, gl_light_attrib::Light, gl_context::Light, gl_context::Line, gl_context::List, make_empty_list, MAX_LIGHTS, gl_viewport_attrib::Near, gl_context::NewDriverState, gl_context::NewState, gl_context::Pixel, gl_context::Point, gl_context::Polygon, gl_context::PolygonStipple, gl_context::Scissor, gl_context::Stencil, gl_context::Transform, gl_context::Viewport, gl_viewport_attrib::Width, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
struct gl_context* _mesa_create_context (gl_api api, const struct gl_config * visual, struct gl_context * share_list, const struct dd_function_table * driverFunctions) read
Allocate and initialize a struct gl_context structure.
Note that the driver needs to pass in its dd_function_table here since we need to at least call driverFunctions->NewTextureObject to initialize the rendering context.
Parameters
api the GL API type to create the context for
visual a struct gl_config pointer (we copy the struct contents)
share_list another context to share display lists with or NULL
driverFunctions points to the dd_function_table into which the driver has plugged in all its special functions.
Returns
pointer to a new __struct gl_contextRec or NULL if error.
References _mesa_initialize_context(), ASSERT, and NULL.
struct gl_config* _mesa_create_visual (GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples) read
Allocates a struct gl_config structure and initializes it via _mesa_initialize_visual().
Parameters
dbFlag double buffering
stereoFlag stereo buffer
depthBits requested bits per depth buffer value. Any value in [0, 32] is acceptable but the actual depth type will be GLushort or GLuint as needed.
stencilBits requested minimum bits per stencil buffer value
accumRedBits,accumGreenBits,accumBlueBits,accumAlphaBits number of bits per color component in accum buffer.
indexBits number of bits per pixel if rgbFlag is GL_FALSE
redBits number of bits per color component in frame buffer for RGB(A) mode. We always use 8 in core Mesa though.
greenBits same as above.
blueBits same as above.
alphaBits same as above.
numSamples not really used.
Returns
pointer to new struct gl_config or NULL if requested parameters can't be met.
Note
Need to add params for level and numAuxBuffers (at least)
References _mesa_initialize_visual(), CALLOC_STRUCT, and NULL.
void _mesa_destroy_context (struct gl_context * ctx)
Destroy a struct gl_context structure.
Parameters
ctx GL context.
Calls _mesa_free_context_data() and frees the gl_context object itself.
References _mesa_free_context_data().
void _mesa_destroy_visual (struct gl_config * vis)
Destroy a visual and free its memory.
Parameters
vis visual.
Frees the visual structure.
void _mesa_finish (struct gl_context * ctx)
Flush commands and wait for completion.
References gl_context::Driver, dd_function_table::Finish, FLUSH_CURRENT, and FLUSH_VERTICES.
Referenced by _mesa_Finish().
void GLAPIENTRY _mesa_Finish (void)
Execute glFinish().
Calls the #ASSERT_OUTSIDE_BEGIN_END_AND_FLUSH macro and the dd_function_table::Finish driver callback, if not NULL.
References _mesa_finish(), and ASSERT_OUTSIDE_BEGIN_END.
Referenced by _mesa_initialize_exec_table().
void _mesa_flush (struct gl_context * ctx)
Flush commands.
References gl_context::Driver, dd_function_table::Flush, FLUSH_CURRENT, and FLUSH_VERTICES.
Referenced by _mesa_Bitmap(), _mesa_CopyPixels(), _mesa_DrawPixels(), _mesa_Flush(), and _mesa_make_current().
void GLAPIENTRY _mesa_Flush (void)
Execute glFlush().
Calls the #ASSERT_OUTSIDE_BEGIN_END_AND_FLUSH macro and the dd_function_table::Flush driver callback, if not NULL.
References _mesa_flush(), and ASSERT_OUTSIDE_BEGIN_END.
Referenced by _mesa_initialize_exec_table().
void _mesa_free_context_data (struct gl_context * ctx)
Free the data associated with the given context.
But doesn't free the struct gl_context struct itself.
See Also
_mesa_initialize_context() and init_attrib_groups().
References gl_vertex_program_state::_Current, gl_fragment_program_state::_Current, _mesa_free_attrib_data(), _mesa_free_buffer_objects(), _mesa_free_display_list_data(), _mesa_free_errors_data(), _mesa_free_eval_data(), _mesa_free_lighting_data(), _mesa_free_matrix_data(), _mesa_free_queryobj_data(), _mesa_free_shader_state(), _mesa_free_sync_data(), _mesa_free_texture_data(), _mesa_free_transform_feedback(), _mesa_free_varray_data(), _mesa_free_viewport_data(), _mesa_get_current_context(), _mesa_make_current(), _mesa_reference_array_object(), _mesa_reference_buffer_object(), _mesa_reference_framebuffer(), _mesa_reference_shared_state(), gl_fragment_program_state::_TexEnvProgram, gl_vertex_program_state::_TnlProgram, gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_array_attrib::ArrayObj, gl_context::BeginEnd, gl_pixelstore_attrib::BufferObj, gl_vertex_program_state::Current, gl_fragment_program_state::Current, gl_array_attrib::DefaultArrayObj, gl_context::DefaultPacking, gl_context::DrawBuffer, gl_context::Exec, gl_context::Extensions, gl_context::FragmentProgram, NULL, gl_context::Pack, gl_context::ReadBuffer, gl_context::Save, gl_context::Shared, gl_extensions::String, gl_context::Unpack, gl_context::VersionString, gl_context::VertexProgram, gl_context::WinSysDrawBuffer, and gl_context::WinSysReadBuffer.
Referenced by _mesa_destroy_context().
int _mesa_generic_nop (void)
This is the default function we plug into all dispatch table slots This helps prevents a segfault when someone calls a GL function without first checking if the extension's supported.
References _mesa_error().
Referenced by _mesa_alloc_dispatch_table().
struct gl_context* _mesa_get_current_context (void) read
Returns
pointer to the current GL context for this thread.
Calls _glapi_get_context(). This isn't the fastest way to get the current context. If you need speed, see the #GET_CURRENT_CONTEXT macro in context.h.
Referenced by _mesa_Fogxv(), _mesa_free_context_data(), _mesa_GetLightxv(), _mesa_GetMaterialxv(), _mesa_GetTexEnvxv(), _mesa_GetTexParameterxv(), _mesa_LightModelxv(), _mesa_Lightxv(), _mesa_make_current(), _mesa_Materialx(), _mesa_Materialxv(), _mesa_PointParameterxv(), _mesa_TexEnvx(), _mesa_TexEnvxv(), and _mesa_TexParameterxv().
struct _glapi_table* _mesa_get_dispatch (struct gl_context * ctx) read
Get context's current API dispatch table.
It'll either be the immediate-mode execute dispatcher or the display list compile dispatcher.
Parameters
ctx GL context.
Returns
pointer to dispatch_table.
Simply returns __struct gl_contextRec::CurrentDispatch.
References gl_context::CurrentDispatch.
static void _mesa_init_constants (struct gl_context * ctx) static
Initialize fields of gl_constants (aka ctx->Const.
*). Use defaults from config.h. The device drivers will often override some of these values (such as number of texture units).
GL_ARB_uniform_buffer_object
GL_EXT_gpu_shader4
References _mesa_is_desktop_gl(), _mesa_override_glsl_version(), gl_context::API, API_OPENGLES, API_OPENGLES2, gl_constants::CheckArrayBounds, gl_context::Const, gl_constants::FragmentProgram, gl_constants::GeometryProgram, gl_constants::GLSLVersion, GLuint64, init_program_limits(), LINE_WIDTH_GRANULARITY, gl_constants::LineWidthGranularity, gl_constants::Max3DTextureLevels, MAX_3D_TEXTURE_LEVELS, MAX_ARRAY_LOCK_SIZE, MAX_ARRAY_TEXTURE_LAYERS, MAX_COLOR_ATTACHMENTS, MAX_COMBINED_TEXTURE_IMAGE_UNITS, MAX_CUBE_TEXTURE_LEVELS, MAX_DRAW_BUFFERS, MAX_FEEDBACK_ATTRIBS, MAX_FEEDBACK_BUFFERS, MAX_GEOMETRY_OUTPUT_VERTICES, MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS, MAX_LIGHTS, MAX_LINE_WIDTH, MAX_POINT_SIZE, MAX_PROGRAM_MATRICES, MAX_PROGRAM_MATRIX_STACK_DEPTH, MAX_RENDERBUFFER_SIZE, MAX_TEXTURE_COORD_UNITS, MAX_TEXTURE_IMAGE_UNITS, MAX_TEXTURE_LEVELS, MAX_TEXTURE_LOD_BIAS, MAX_TEXTURE_MAX_ANISOTROPY, MAX_TEXTURE_MBYTES, MAX_TEXTURE_RECT_SIZE, MAX_VIEWPORT_HEIGHT, MAX_VIEWPORT_WIDTH, gl_constants::MaxArrayLockSize, gl_constants::MaxArrayTextureLayers, gl_constants::MaxClipPlanes, gl_constants::MaxColorAttachments, gl_constants::MaxColorTextureSamples, gl_constants::MaxCombinedTextureImageUnits, gl_constants::MaxCombinedUniformBlocks, gl_constants::MaxCubeTextureLevels, gl_constants::MaxDepthTextureSamples, gl_constants::MaxDrawBuffers, gl_constants::MaxElementIndex, gl_constants::MaxGeometryOutputVertices, gl_constants::MaxGeometryTotalOutputComponents, gl_constants::MaxIntegerSamples, gl_constants::MaxLights, gl_constants::MaxLineWidth, gl_constants::MaxLineWidthAA, gl_constants::MaxPointSize, gl_constants::MaxPointSizeAA, gl_constants::MaxProgramMatrices, gl_constants::MaxProgramMatrixStackDepth, gl_constants::MaxProgramTexelOffset, gl_constants::MaxRenderbufferSize, gl_constants::MaxSamples, gl_constants::MaxServerWaitTimeout, gl_constants::MaxShininess, gl_constants::MaxSpotExponent, gl_constants::MaxTextureBufferSize, gl_constants::MaxTextureCoordUnits, gl_program_constants::MaxTextureImageUnits, gl_constants::MaxTextureLevels, gl_constants::MaxTextureLodBias, gl_constants::MaxTextureMaxAnisotropy, gl_constants::MaxTextureMbytes, gl_constants::MaxTextureRectSize, gl_constants::MaxTextureUnits, gl_constants::MaxTransformFeedbackBuffers, gl_constants::MaxTransformFeedbackInterleavedComponents, gl_constants::MaxTransformFeedbackSeparateComponents, gl_constants::MaxUniformBlockSize, gl_constants::MaxUniformBufferBindings, gl_constants::MaxVarying, gl_constants::MaxVertexStreams, gl_constants::MaxViewportHeight, gl_constants::MaxViewportWidth, MESA_GEOMETRY_PROGRAM, MIN2, MIN_LINE_WIDTH, MIN_POINT_SIZE, gl_constants::MinLineWidth, gl_constants::MinLineWidthAA, gl_constants::MinPointSize, gl_constants::MinPointSizeAA, gl_constants::MinProgramTexelOffset, POINT_SIZE_GRANULARITY, gl_constants::PointSizeGranularity, gl_constants::PrimitiveRestartInSoftware, gl_constants::ProfileMask, gl_constants::QuadsFollowProvokingVertexConvention, gl_constants::ResetStrategy, SUB_PIXEL_BITS, gl_constants::SubPixelBits, SUPPORTED_ATI_BUMP_UNITS, gl_constants::SupportedBumpUnits, gl_constants::TextureBufferOffsetAlignment, gl_constants::UniformBufferOffsetAlignment, and gl_constants::VertexProgram.
Referenced by init_attrib_groups().
static void _mesa_init_current (struct gl_context * ctx) static
Initialize fields of gl_current_attrib (aka ctx->Current.
*)
References ASSIGN_4V, gl_current_attrib::Attrib, gl_context::Current, Elements, VERT_ATTRIB_COLOR0, VERT_ATTRIB_COLOR1, VERT_ATTRIB_COLOR_INDEX, VERT_ATTRIB_EDGEFLAG, VERT_ATTRIB_NORMAL, and VERT_ATTRIB_WEIGHT.
Referenced by init_attrib_groups().
GLboolean _mesa_initialize_context (struct gl_context * ctx, gl_api api, const struct gl_config * visual, struct gl_context * share_list, const struct dd_function_table * driverFunctions)
Initialize a struct gl_context struct (rendering context).
This includes allocating all the other structs and arrays which hang off of the context by pointers. Note that the driver needs to pass in its dd_function_table here since we need to at least call driverFunctions->NewTextureObject to create the default texture objects.
Called by _mesa_create_context().
Performs the imports and exports callback tables initialization, and miscellaneous one-time initializations. If no shared context is supplied one is allocated, and increase its reference count. Setups the GL API dispatch tables. Initialize the TNL module. Sets the maximum Z buffer depth. Finally queries the MESA_DEBUG and MESA_VERBOSE environment variables for debug flags.
Parameters
ctx the context to initialize
api the GL API type to create the context for
visual describes the visual attributes for this context
share_list points to context to share textures, display lists, etc with, or NULL
driverFunctions table of device driver functions for this context to use
GL_OES_texture_cube_map says "Initially all texture generation modes are set to REFLECTION_MAP_OES"
References gl_fragment_program_state::_MaintainTexEnvProgram, gl_vertex_program_state::_MaintainTnlProgram, _mesa_alloc_dispatch_table(), _mesa_alloc_shared_state(), _mesa_getenv(), _mesa_is_desktop_gl(), _mesa_override_gl_version(), _mesa_reference_shared_state(), gl_texgen::_ModeBit, gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_context::BeginEnd, create_beginend_table(), gl_context::CurrentDispatch, gl_context::DrawBuffer, gl_context::Driver, gl_context::Exec, gl_context::FirstTimeCurrent, gl_context::FragmentProgram, dd_function_table::FreeTextureImageBuffer, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, init_attrib_groups(), MAX_TEXTURE_UNITS, gl_texgen::Mode, dd_function_table::NewTextureObject, NULL, one_time_init(), gl_context::OutsideBeginEnd, gl_context::ReadBuffer, gl_context::Save, gl_context::Shared, TEXGEN_REFLECTION_MAP_NV, gl_context::Texture, gl_context::TextureFormatSupported, gl_texture_attrib::Unit, gl_context::VertexProgram, gl_context::Visual, gl_context::WinSysDrawBuffer, and gl_context::WinSysReadBuffer.
Referenced by _mesa_create_context().
void _mesa_initialize_dispatch_tables (struct gl_context * ctx)
References _mesa_initialize_exec_table(), _mesa_initialize_save_table(), and gl_context::Save.
GLboolean _mesa_initialize_visual (struct gl_config * vis, GLboolean dbFlag, GLboolean stereoFlag, GLint redBits, GLint greenBits, GLint blueBits, GLint alphaBits, GLint depthBits, GLint stencilBits, GLint accumRedBits, GLint accumGreenBits, GLint accumBlueBits, GLint accumAlphaBits, GLint numSamples)
Makes some sanity checks and fills in the fields of the struct gl_config object with the given parameters.
If the caller needs to set additional fields, he should just probably init the whole gl_config object himself.
Returns
GL_TRUE on success, or GL_FALSE on failure.
See Also
_mesa_create_visual() above for the parameter description.
References gl_config::accumAlphaBits, gl_config::accumBlueBits, gl_config::accumGreenBits, gl_config::accumRedBits, gl_config::alphaBits, gl_config::blueBits, gl_config::depthBits, gl_config::doubleBufferMode, gl_config::greenBits, gl_config::haveAccumBuffer, gl_config::haveDepthBuffer, gl_config::haveStencilBuffer, gl_config::indexBits, gl_config::level, gl_config::numAuxBuffers, gl_config::redBits, gl_config::rgbBits, gl_config::rgbMode, gl_config::sampleBuffers, gl_config::samples, gl_config::stencilBits, and gl_config::stereoMode.
Referenced by _mesa_create_visual().
GLboolean _mesa_make_current (struct gl_context * newCtx, struct gl_framebuffer * drawBuffer, struct gl_framebuffer * readBuffer)
Bind the given context to the given drawBuffer and readBuffer and make it the current context for the calling thread.
We'll render into the drawBuffer and read pixels from the readBuffer (i.e. glRead/CopyPixels, glCopyTexImage, etc).
We check that the context's and framebuffer's visuals are compatible and return immediately if they're not.
Parameters
newCtx the new GL context. If NULL then there will be no current GL context.
drawBuffer the drawing framebuffer
readBuffer the reading framebuffer
References _mesa_check_init_viewport(), _mesa_debug(), _mesa_flush(), _mesa_get_current_context(), _mesa_getenv(), _mesa_is_winsys_fbo(), _mesa_make_extension_string(), _mesa_print_info(), _mesa_reference_framebuffer(), _mesa_resizebuffers(), _mesa_update_draw_buffers(), _mesa_warning(), _NEW_BUFFERS, ASSERT, check_compatible(), check_context_limits(), gl_context::CurrentDispatch, gl_context::DrawBuffer, gl_context::Extensions, gl_context::FirstTimeCurrent, gl_framebuffer::Height, initialize_framebuffer_size(), gl_framebuffer::Initialized, MESA_VERBOSE, gl_context::NewState, NULL, gl_context::ReadBuffer, gl_extensions::String, VERBOSE_API, gl_context::Version, gl_framebuffer::Width, gl_context::WinSysDrawBuffer, and gl_context::WinSysReadBuffer.
Referenced by _mesa_free_context_data().
void _mesa_notifySwapBuffers (struct gl_context * ctx)
Swap buffers notification callback.
Parameters
ctx GL context.
Called by window system just before swapping buffers. We have to finish any pending rendering.
References _mesa_debug(), gl_context::Driver, dd_function_table::Flush, FLUSH_CURRENT, MESA_VERBOSE, and VERBOSE_SWAPBUFFERS.
void _mesa_record_error (struct gl_context * ctx, GLenum error)
Record an error.
Parameters
ctx GL context.
error error code.
Records the given error code and call the driver's dd_function_table::Error function if defined.
See Also
This is called via _mesa_error().
References gl_context::ErrorValue.
Referenced by _mesa_error().
GLboolean _mesa_share_state (struct gl_context * ctx, struct gl_context * ctxToShare)
Make context 'ctx' share the display lists, textures and programs that are associated with 'ctxToShare'.
Any display lists, textures or programs associated with 'ctx' will be deleted if nobody else is sharing them.
References _mesa_reference_shared_state(), NULL, gl_context::Shared, and update_default_objects().
GLboolean _mesa_valid_to_render (struct gl_context * ctx, const char * where)
Prior to drawing anything with glBegin, glDrawArrays, etc.
this function is called to see if it's valid to render. This involves checking that the current shader is valid and the framebuffer is complete. If an error is detected it'll be recorded here.
Returns
GL_TRUE if OK to render, GL_FALSE if not
References gl_vertex_program_state::_Enabled, gl_fragment_program_state::_Enabled, gl_framebuffer::_IntegerColor, gl_shader_program::_LinkedShaders, _mesa_check_blend_func_error(), _mesa_error(), _mesa_update_state(), _mesa_warning(), gl_framebuffer::_Status, gl_shader_program::_Used, gl_shader_state::CurrentFragmentProgram, gl_shader_state::CurrentGeometryProgram, gl_shader_state::CurrentVertexProgram, gl_context::DrawBuffer, gl_vertex_program_state::Enabled, gl_fragment_program_state::Enabled, gl_shader_state::Flags, gl_context::FragmentProgram, GLSL_LOG, gl_shader_program::LinkStatus, MESA_SHADER_FRAGMENT, MESA_SHADER_GEOMETRY, MESA_SHADER_TYPES, MESA_SHADER_VERTEX, gl_shader_program::Name, gl_context::NewState, NULL, gl_context::Shader, gl_context::VertexProgram, and void().
Referenced by _mesa_Bitmap(), _mesa_CopyPixels(), _mesa_DrawPixels(), and check_valid_to_render().
static GLboolean check_compatible (const struct gl_context * ctx, const struct gl_framebuffer * buffer) static
Check if the given context can render into the given framebuffer by checking visual attributes.
Most of these tests could go away because Mesa is now pretty flexible in terms of mixing rendering contexts with framebuffers. As long as RGB vs. CI mode agree, we're probably good.
Returns
GL_TRUE if compatible, GL_FALSE otherwise.
References _mesa_get_incomplete_framebuffer(), gl_config::blueMask, gl_config::depthBits, gl_config::doubleBufferMode, gl_config::greenMask, gl_config::haveAccumBuffer, gl_config::haveDepthBuffer, gl_config::haveStencilBuffer, gl_config::redMask, gl_config::stencilBits, gl_config::stereoMode, gl_framebuffer::Visual, and gl_context::Visual.
Referenced by _mesa_make_current().
static void check_context_limits (struct gl_context * ctx) static
Do some sanity checks on the limits/constants for the given context.
Only called the first time a context is bound.
References gl_vertex_program_state::_Current, gl_fragment_program_state::_Current, gl_vertex_program::Base, gl_fragment_program::Base, BUFFER_COLOR0, BUFFER_COUNT, gl_context::Const, gl_constants::FragmentProgram, gl_context::FragmentProgram, gl_program::InputsRead, gl_constants::Max3DTextureLevels, MAX_3D_TEXTURE_LEVELS, MAX_COMBINED_TEXTURE_IMAGE_UNITS, MAX_CUBE_TEXTURE_LEVELS, MAX_DRAW_BUFFERS, MAX_PROGRAM_LOCAL_PARAMS, MAX_TEXTURE_COORD_UNITS, MAX_TEXTURE_IMAGE_UNITS, MAX_TEXTURE_LEVELS, MAX_TEXTURE_RECT_SIZE, gl_constants::MaxCombinedTextureImageUnits, gl_constants::MaxCubeTextureLevels, gl_constants::MaxDrawBuffers, gl_program_constants::MaxLocalParams, gl_constants::MaxTextureCoordUnits, gl_program_constants::MaxTextureImageUnits, gl_constants::MaxTextureLevels, gl_constants::MaxTextureRectSize, gl_constants::MaxTextureUnits, gl_constants::MaxViewportHeight, gl_constants::MaxViewportWidth, MIN2, gl_program::OutputsWritten, VARYING_SLOT_MAX, gl_constants::VertexProgram, and gl_context::VertexProgram.
Referenced by _mesa_make_current().
static struct _glapi_table* create_beginend_table (const struct gl_context * ctx) static read
Creates a minimal dispatch table for use within glBegin()/glEnd().
This ensures that we generate GL_INVALID_OPERATION errors from most functions, since the set of functions that are valid within Begin/End is very small.
From the GL 1.0 specification section 2.6.3, "GL Commands within Begin/End"
"The only GL commands that are allowed within any Begin/End pairs are
 the commands for specifying vertex coordinates, vertex color, normal
 coordinates, and texture coordinates (Vertex, Color, Index, Normal,
 TexCoord), EvalCoord and EvalPoint commands (see section 5.1),
 commands for specifying lighting material parameters (Material
 commands see section 2.12.2), display list invocation commands
 (CallList and CallLists see section 5.4), and the EdgeFlag
 command. Executing Begin after Begin has already been executed but
 before an End is issued generates the INVALID OPERATION error, as does
 executing End without a previous corresponding Begin. Executing any
 other GL command within Begin/End results in the error INVALID
 OPERATION."
The table entries for specifying vertex attributes are set up by install_vtxfmt() and _mesa_loopback_init_api_table(), and End() and dlists are set by install_vtxfmt() as well.
References _mesa_alloc_dispatch_table(), _mesa_loopback_init_api_table(), COPY_DISPATCH, NULL, and table.
Referenced by _mesa_initialize_context().
static void dummy_enum_func (void) static
This is lame.
gdb only seems to recognize enum types that are actually used somewhere. We want to be able to print/use enum values such as TEXTURE_2D_INDEX in gdb. But we don't actually use the gl_texture_index type anywhere. Thus, this lame function.
References BUFFER_FRONT_LEFT, FACE_POS_X, FRAG_RESULT_DEPTH, TEXTURE_2D_ARRAY_INDEX, VARYING_SLOT_POS, VERT_ATTRIB_POS, and void().
Referenced by one_time_init().
static GLboolean init_attrib_groups (struct gl_context * ctx) static
Initialize the attribute groups in a GL context.
Parameters
ctx GL context.
Initializes all the attributes, calling the respective init* functions for the more complex data structures.
References _mesa_init_accum(), _mesa_init_attrib(), _mesa_init_buffer_objects(), _mesa_init_color(), _mesa_init_constants(), _mesa_init_current(), _mesa_init_debug(), _mesa_init_depth(), _mesa_init_display_list(), _mesa_init_errors(), _mesa_init_eval(), _mesa_init_extensions(), _mesa_init_fbobjects(), _mesa_init_feedback(), _mesa_init_fog(), _mesa_init_hint(), _mesa_init_lighting(), _mesa_init_line(), _mesa_init_matrix(), _mesa_init_multisample(), _mesa_init_pixel(), _mesa_init_pixelstore(), _mesa_init_point(), _mesa_init_polygon(), _mesa_init_queryobj(), _mesa_init_rastpos(), _mesa_init_scissor(), _mesa_init_shader_state(), _mesa_init_stencil(), _mesa_init_sync(), _mesa_init_texture(), _mesa_init_texture_s3tc(), _mesa_init_transform(), _mesa_init_transform_feedback(), _mesa_init_varray(), _mesa_init_viewport(), _NEW_ALL, gl_context::ErrorValue, gl_context::NewDriverState, gl_context::NewState, gl_context::ResetStatus, gl_context::varying_vp_inputs, and VERT_BIT_ALL.
Referenced by _mesa_initialize_context().
static void init_program_limits (struct gl_context * ctx, GLenum type, struct gl_program_constants * prog) static
Init vertex/fragment/geometry program limits.
Important: drivers should override these with actual limits.
References gl_context::Const, gl_program_constants::HighFloat, gl_program_constants::HighInt, MAX_FRAGMENT_PROGRAM_ADDRESS_REGS, MAX_GEOMETRY_UNIFORM_COMPONENTS, MAX_NV_FRAGMENT_PROGRAM_INPUTS, MAX_NV_FRAGMENT_PROGRAM_PARAMS, MAX_PROGRAM_ENV_PARAMS, MAX_PROGRAM_INSTRUCTIONS, MAX_PROGRAM_LOCAL_PARAMS, MAX_PROGRAM_TEMPS, MAX_UNIFORMS, MAX_VERTEX_GENERIC_ATTRIBS, MAX_VERTEX_PROGRAM_ADDRESS_REGS, MAX_VERTEX_PROGRAM_PARAMS, gl_program_constants::MaxAddressOffset, gl_program_constants::MaxAddressRegs, gl_program_constants::MaxAluInstructions, gl_program_constants::MaxAttribs, gl_program_constants::MaxCombinedUniformComponents, gl_program_constants::MaxEnvParams, gl_program_constants::MaxInstructions, gl_program_constants::MaxLocalParams, gl_program_constants::MaxNativeAddressRegs, gl_program_constants::MaxNativeAluInstructions, gl_program_constants::MaxNativeAttribs, gl_program_constants::MaxNativeInstructions, gl_program_constants::MaxNativeParameters, gl_program_constants::MaxNativeTemps, gl_program_constants::MaxNativeTexIndirections, gl_program_constants::MaxNativeTexInstructions, gl_program_constants::MaxParameters, gl_program_constants::MaxTemps, gl_program_constants::MaxTexIndirections, gl_program_constants::MaxTexInstructions, gl_program_constants::MaxUniformBlocks, gl_constants::MaxUniformBlockSize, gl_program_constants::MaxUniformComponents, and MESA_GEOMETRY_PROGRAM.
Referenced by _mesa_init_constants().
static void initialize_framebuffer_size (struct gl_context * ctx, struct gl_framebuffer * fb) static
Do one-time initialization for the given framebuffer.
Specifically, ask the driver for the window's current size and update the framebuffer object to match. Really, the device driver should totally take care of this.
References gl_context::Driver, dd_function_table::GetBufferSize, gl_framebuffer::Initialized, and dd_function_table::ResizeBuffers.
Referenced by _mesa_make_current().
static void one_time_init (struct gl_context * ctx) static
Calls all the various one-time-init functions in Mesa.
While holding a global mutex lock, calls several initialization functions, and sets the glapi callbacks if the MESA_DEBUG environment variable is defined.
See Also
_math_init().
References _mesa_debug(), _mesa_get_cpu_features(), _mesa_init_get_hash(), _mesa_init_remap_table(), _mesa_test_formats(), _mesa_ubyte_to_float_color_tab, gl_context::API, dummy_enum_func(), F, GLbitfield, GLbyte, GLshort, GLubyte, GLushort, and MESA_VERBOSE.
Referenced by _mesa_initialize_context().
static GLboolean update_default_objects (struct gl_context * ctx) static
Update default objects in a GL context with respect to shared state.
Parameters
ctx GL context.
Removes references to old default objects, (texture objects, program objects, etc.) and changes to reference those from the current shared state.
References _mesa_update_default_objects_buffer_objects(), and _mesa_update_default_objects_texture().
Referenced by _mesa_share_state().
Variable Documentation
GLfloat _mesa_ubyte_to_float_color_tab[256]
Convert GLubyte in [0,255] to GLfloat in [0.0,1.0].
Referenced by one_time_init().