Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
dlist.h File Reference
Display lists management.
#include "main/mtypes.h"
Functions
GLboolean GLAPIENTRY _mesa_IsList (GLuint list)
Test if a display list number is valid.
void GLAPIENTRY _mesa_DeleteLists (GLuint list, GLsizei range)
Delete a sequence of consecutive display lists.
GLuint GLAPIENTRY _mesa_GenLists (GLsizei range)
Return a display list number, n, such that lists n through n+range-1 are free.
void GLAPIENTRY _mesa_NewList (GLuint name, GLenum mode)
Begin a new display list.
void GLAPIENTRY _mesa_EndList (void)
End definition of current display list.
void GLAPIENTRY _mesa_CallList (GLuint list)
void GLAPIENTRY _mesa_CallLists (GLsizei n, GLenum type, const GLvoid *lists)
Execute glCallLists: call multiple display lists.
void GLAPIENTRY _mesa_ListBase (GLuint base)
Set the offset added to list numbers in glCallLists.
void _mesa_compile_error (struct gl_context *ctx, GLenum error, const char *s)
Compile an error into current display list.
void * _mesa_dlist_alloc (struct gl_context *ctx, GLuint opcode, GLuint sz)
Allocate space for a display list instruction.
GLint _mesa_dlist_alloc_opcode (struct gl_context *ctx, GLuint sz, void(*execute)(struct gl_context *, void *), void(*destroy)(struct gl_context *, void *), void(*print)(struct gl_context *, void *))
This function allows modules and drivers to get their own opcodes for extending display list functionality.
void _mesa_delete_list (struct gl_context *ctx, struct gl_display_list *dlist)
Delete the named display list, but don't remove from hash table.
void _mesa_initialize_save_table (const struct gl_context *)
Setup the given dispatch table to point to Mesa's display list building functions.
void _mesa_install_dlist_vtxfmt (struct _glapi_table *disp, const GLvertexformat *vfmt)
void _mesa_init_display_list (struct gl_context *ctx)
Initialize display list state for given context.
void _mesa_free_display_list_data (struct gl_context *ctx)
Detailed Description
Display lists management.
Function Documentation
void GLAPIENTRY _mesa_CallList (GLuint list)
References _mesa_debug(), _mesa_error(), gl_context::CompileFlag, gl_context::CurrentDispatch, execute_list(), FLUSH_CURRENT, mesa_print_display_list(), MESA_VERBOSE, gl_context::Save, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and save_CallList().
void GLAPIENTRY _mesa_CallLists (GLsizei n, GLenum type, const GLvoid * lists)
Execute glCallLists: call multiple display lists.
References _mesa_debug(), _mesa_error(), gl_context::CompileFlag, gl_context::CurrentDispatch, execute_list(), gl_context::List, gl_list_attrib::ListBase, MESA_VERBOSE, gl_context::Save, translate_id(), and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void _mesa_compile_error (struct gl_context * ctx, GLenum error, const char * s)
Compile an error into current display list.
References _mesa_error(), gl_context::CompileFlag, gl_context::ExecuteFlag, and save_error().
Referenced by save_Begin(), and save_Materialfv().
void _mesa_delete_list (struct gl_context * ctx, struct gl_display_list * dlist)
Delete the named display list, but don't remove from hash table.
Parameters
dlist - display list pointer
References ext_opcode_destroy(), gl_display_list::Head, InstSize, is_ext_opcode(), gl_dlist_node::opcode, OPCODE_BITMAP, OPCODE_COLOR_SUB_TABLE, OPCODE_COLOR_TABLE, OPCODE_COMPRESSED_TEX_IMAGE_1D, OPCODE_COMPRESSED_TEX_IMAGE_2D, OPCODE_COMPRESSED_TEX_IMAGE_3D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_1D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_2D, OPCODE_COMPRESSED_TEX_SUB_IMAGE_3D, OPCODE_CONTINUE, OPCODE_CONVOLUTION_FILTER_1D, OPCODE_CONVOLUTION_FILTER_2D, OPCODE_DRAW_PIXELS, OPCODE_END_OF_LIST, OPCODE_MAP1, OPCODE_MAP2, OPCODE_POLYGON_STIPPLE, OPCODE_PROGRAM_STRING_ARB, OPCODE_TEX_IMAGE1D, OPCODE_TEX_IMAGE2D, OPCODE_TEX_IMAGE3D, OPCODE_TEX_SUB_IMAGE1D, OPCODE_TEX_SUB_IMAGE2D, OPCODE_TEX_SUB_IMAGE3D, OPCODE_UNIFORM_1FV, OPCODE_UNIFORM_1IV, OPCODE_UNIFORM_1UIV, OPCODE_UNIFORM_2FV, OPCODE_UNIFORM_2IV, OPCODE_UNIFORM_2UIV, OPCODE_UNIFORM_3FV, OPCODE_UNIFORM_3IV, OPCODE_UNIFORM_3UIV, OPCODE_UNIFORM_4FV, OPCODE_UNIFORM_4IV, OPCODE_UNIFORM_4UIV, OPCODE_UNIFORM_MATRIX22, OPCODE_UNIFORM_MATRIX23, OPCODE_UNIFORM_MATRIX24, OPCODE_UNIFORM_MATRIX32, OPCODE_UNIFORM_MATRIX33, OPCODE_UNIFORM_MATRIX34, OPCODE_UNIFORM_MATRIX42, OPCODE_UNIFORM_MATRIX43, and OPCODE_UNIFORM_MATRIX44.
Referenced by delete_displaylist_cb(), and destroy_list().
void GLAPIENTRY _mesa_DeleteLists (GLuint list, GLsizei range)
Delete a sequence of consecutive display lists.
References _mesa_error(), ASSERT_OUTSIDE_BEGIN_END, destroy_list(), and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void* _mesa_dlist_alloc (struct gl_context * ctx, GLuint opcode, GLuint bytes)
Allocate space for a display list instruction.
Used by callers outside this file for things like VBO vertex data.
Parameters
opcode the instruction opcode (OPCODE_* value)
bytes instruction size in bytes, not counting opcode.
Returns
pointer to the usable data area (not including the internal opcode).
References dlist_alloc(), and NULL.
GLint _mesa_dlist_alloc_opcode (struct gl_context * ctx, GLuint size, void(*)(struct gl_context *, void *) execute, void(*)(struct gl_context *, void *) destroy, void(*)(struct gl_context *, void *) print)
This function allows modules and drivers to get their own opcodes for extending display list functionality.
Parameters
ctx the rendering context
size number of bytes for storing the new display list command
execute function to execute the new display list command
destroy function to destroy the new display list command
print function to print the new display list command
Returns
the new opcode number or -1 if error
References gl_list_instruction::Destroy, gl_list_instruction::Execute, gl_context::ListExt, MAX_DLIST_EXT_OPCODES, gl_list_extensions::NumOpcodes, gl_list_extensions::Opcode, OPCODE_EXT_0, gl_list_instruction::Print, and gl_list_instruction::Size.
void GLAPIENTRY _mesa_EndList (void)
End definition of current display list.
References _mesa_debug(), _mesa_error(), _mesa_HashInsert(), _mesa_inside_dlist_begin_end(), alloc_instruction(), gl_context::CompileFlag, gl_context::CurrentDispatch, gl_dlist_state::CurrentList, destroy_list(), gl_shared_state::DisplayList, gl_context::Driver, dd_function_table::EndList, gl_context::Exec, gl_context::ExecuteFlag, FLUSH_VERTICES, gl_context::ListState, mesa_print_display_list(), MESA_VERBOSE, gl_display_list::Name, NULL, OPCODE_END_OF_LIST, SAVE_FLUSH_VERTICES, gl_context::Shared, VERBOSE_API, VERBOSE_DISPLAY_LIST, and void().
Referenced by _mesa_initialize_exec_table().
void _mesa_free_display_list_data (struct gl_context * ctx)
References gl_context::ListExt, and NULL.
Referenced by _mesa_free_context_data().
GLuint GLAPIENTRY _mesa_GenLists (GLsizei range)
Return a display list number, n, such that lists n through n+range-1 are free.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_shared_state::DisplayList, FLUSH_VERTICES, make_list(), gl_shared_state::Mutex, and gl_context::Shared.
Referenced by _mesa_initialize_exec_table().
void _mesa_init_display_list (struct gl_context * ctx)
Initialize display list state for given context.
References gl_dlist_state::CallDepth, CALLOC_STRUCT, gl_context::CompileFlag, gl_dlist_state::CurrentBlock, gl_dlist_state::CurrentPos, gl_context::ExecuteFlag, InstSize, gl_context::List, gl_list_attrib::ListBase, gl_context::ListExt, gl_context::ListState, gl_dlist_state::ListVtxfmt, NULL, and save_vtxfmt_init().
Referenced by init_attrib_groups().
void _mesa_initialize_save_table (const struct gl_context * ctx)
Setup the given dispatch table to point to Mesa's display list building functions.
This does not include any of the tnl functions - they are initialized from _mesa_init_api_defaults and from the active vtxfmt struct.
References _gloffset_COUNT, _mesa_loopback_init_api_table(), gl_context::Exec, MAX2, gl_context::Save, save_Accum(), save_ActiveProgramEXT(), save_ActiveStencilFaceEXT(), save_ActiveTextureARB(), save_AlphaFunc(), save_BeginConditionalRender(), save_BeginQueryARB(), save_BeginQueryIndexed(), save_BeginTransformFeedback(), save_BindFragmentShaderATI(), save_BindProgramNV(), save_BindSampler(), save_BindTexture(), save_BindTransformFeedback(), save_Bitmap(), save_BlendColor(), save_BlendEquation(), save_BlendEquationi(), save_BlendEquationSeparateEXT(), save_BlendEquationSeparatei(), save_BlendFunc(), save_BlendFunci(), save_BlendFuncSeparateEXT(), save_BlendFuncSeparatei(), save_BlitFramebufferEXT(), save_CallList(), save_CallLists(), save_ClampColorARB(), save_Clear(), save_ClearAccum(), save_ClearBufferfi(), save_ClearBufferfv(), save_ClearBufferiv(), save_ClearBufferuiv(), save_ClearColor(), save_ClearColorIi(), save_ClearColorIui(), save_ClearDepth(), save_ClearIndex(), save_ClearStencil(), save_ClipPlane(), save_ColorMask(), save_ColorMaskIndexed(), save_ColorMaterial(), save_ColorSubTable(), save_ColorTable(), save_ColorTableParameterfv(), save_ColorTableParameteriv(), save_CompressedTexImage1DARB(), save_CompressedTexImage2DARB(), save_CompressedTexImage3DARB(), save_CompressedTexSubImage1DARB(), save_CompressedTexSubImage2DARB(), save_CompressedTexSubImage3DARB(), save_ConvolutionFilter1D(), save_ConvolutionFilter2D(), save_ConvolutionParameterf(), save_ConvolutionParameterfv(), save_ConvolutionParameteri(), save_ConvolutionParameteriv(), save_CopyColorSubTable(), save_CopyColorTable(), save_CopyPixels(), save_CopyTexImage1D(), save_CopyTexImage2D(), save_CopyTexSubImage1D(), save_CopyTexSubImage2D(), save_CopyTexSubImage3D(), save_CullFace(), save_DepthBoundsEXT(), save_DepthFunc(), save_DepthMask(), save_DepthRange(), save_Disable(), save_DisableIndexed(), save_DrawArraysInstancedARB(), save_DrawArraysInstancedBaseInstance(), save_DrawBuffer(), save_DrawBuffersARB(), save_DrawElementsInstancedARB(), save_DrawElementsInstancedBaseInstance(), save_DrawElementsInstancedBaseVertexARB(), save_DrawElementsInstancedBaseVertexBaseInstance(), save_DrawPixels(), save_DrawTransformFeedback(), save_DrawTransformFeedbackInstanced(), save_DrawTransformFeedbackStream(), save_DrawTransformFeedbackStreamInstanced(), save_Enable(), save_EnableIndexed(), save_EndConditionalRender(), save_EndQueryARB(), save_EndQueryIndexed(), save_EndTransformFeedback(), save_EvalMesh1(), save_EvalMesh2(), save_Fogf(), save_Fogfv(), save_Fogi(), save_Fogiv(), save_FramebufferTexture(), save_FramebufferTextureFace(), save_FrontFace(), save_Frustum(), save_Hint(), save_Histogram(), save_IndexMask(), save_InitNames(), save_Lightf(), save_Lightfv(), save_Lighti(), save_Lightiv(), save_LightModelf(), save_LightModelfv(), save_LightModeli(), save_LightModeliv(), save_LineStipple(), save_LineWidth(), save_ListBase(), save_LoadIdentity(), save_LoadMatrixd(), save_LoadMatrixf(), save_LoadName(), save_LoadTransposeMatrixdARB(), save_LoadTransposeMatrixfARB(), save_LogicOp(), save_Map1d(), save_Map1f(), save_Map2d(), save_Map2f(), save_MapGrid1d(), save_MapGrid1f(), save_MapGrid2d(), save_MapGrid2f(), save_MatrixMode(), save_Minmax(), save_MultMatrixd(), save_MultMatrixf(), save_MultTransposeMatrixdARB(), save_MultTransposeMatrixfARB(), save_NewList(), save_Ortho(), save_PassThrough(), save_PauseTransformFeedback(), save_PixelMapfv(), save_PixelMapuiv(), save_PixelMapusv(), save_PixelTransferf(), save_PixelTransferi(), save_PixelZoom(), save_PointParameterfEXT(), save_PointParameterfvEXT(), save_PointParameteriNV(), save_PointParameterivNV(), save_PointSize(), save_PolygonMode(), save_PolygonOffset(), save_PolygonOffsetEXT(), save_PolygonStipple(), save_PopAttrib(), save_PopMatrix(), save_PopName(), save_PrioritizeTextures(), save_ProgramEnvParameter4dARB(), save_ProgramEnvParameter4dvARB(), save_ProgramEnvParameter4fARB(), save_ProgramEnvParameter4fvARB(), save_ProgramEnvParameters4fvEXT(), save_ProgramLocalParameter4dARB(), save_ProgramLocalParameter4dvARB(), save_ProgramLocalParameter4fARB(), save_ProgramLocalParameter4fvARB(), save_ProgramLocalParameters4fvEXT(), save_ProgramParameteri(), save_ProgramStringARB(), save_ProvokingVertexEXT(), save_PushAttrib(), save_PushMatrix(), save_PushName(), save_QueryCounter(), save_RasterPos2d(), save_RasterPos2dv(), save_RasterPos2f(), save_RasterPos2fv(), save_RasterPos2i(), save_RasterPos2iv(), save_RasterPos2s(), save_RasterPos2sv(), save_RasterPos3d(), save_RasterPos3dv(), save_RasterPos3f(), save_RasterPos3fv(), save_RasterPos3i(), save_RasterPos3iv(), save_RasterPos3s(), save_RasterPos3sv(), save_RasterPos4d(), save_RasterPos4dv(), save_RasterPos4f(), save_RasterPos4fv(), save_RasterPos4i(), save_RasterPos4iv(), save_RasterPos4s(), save_RasterPos4sv(), save_ReadBuffer(), save_Rectf(), save_ResetHistogram(), save_ResetMinmax(), save_ResumeTransformFeedback(), save_Rotated(), save_Rotatef(), save_SampleCoverageARB(), save_SamplerParameterf(), save_SamplerParameterfv(), save_SamplerParameteri(), save_SamplerParameterIiv(), save_SamplerParameterIuiv(), save_SamplerParameteriv(), save_Scaled(), save_Scalef(), save_Scissor(), save_SetFragmentShaderConstantATI(), save_ShadeModel(), save_StencilFunc(), save_StencilFuncSeparate(), save_StencilFuncSeparateATI(), save_StencilMask(), save_StencilMaskSeparate(), save_StencilOp(), save_StencilOpSeparate(), save_TexBumpParameterfvATI(), save_TexBumpParameterivATI(), save_TexEnvf(), save_TexEnvfv(), save_TexEnvi(), save_TexEnviv(), save_TexGend(), save_TexGendv(), save_TexGenf(), save_TexGenfv(), save_TexGeni(), save_TexGeniv(), save_TexImage1D(), save_TexImage2D(), save_TexImage3D(), save_TexParameterf(), save_TexParameterfv(), save_TexParameteri(), save_TexParameterIiv(), save_TexParameterIuiv(), save_TexParameteriv(), save_TexSubImage1D(), save_TexSubImage2D(), save_TexSubImage3D(), save_TextureBarrierNV(), save_Translated(), save_Translatef(), save_Uniform1fARB(), save_Uniform1fvARB(), save_Uniform1iARB(), save_Uniform1ivARB(), save_Uniform1ui(), save_Uniform1uiv(), save_Uniform2fARB(), save_Uniform2fvARB(), save_Uniform2iARB(), save_Uniform2ivARB(), save_Uniform2ui(), save_Uniform2uiv(), save_Uniform3fARB(), save_Uniform3fvARB(), save_Uniform3iARB(), save_Uniform3ivARB(), save_Uniform3ui(), save_Uniform3uiv(), save_Uniform4fARB(), save_Uniform4fvARB(), save_Uniform4iARB(), save_Uniform4ivARB(), save_Uniform4ui(), save_Uniform4uiv(), save_UniformBlockBinding(), save_UniformMatrix2fvARB(), save_UniformMatrix2x3fv(), save_UniformMatrix2x4fv(), save_UniformMatrix3fvARB(), save_UniformMatrix3x2fv(), save_UniformMatrix3x4fv(), save_UniformMatrix4fvARB(), save_UniformMatrix4x2fv(), save_UniformMatrix4x3fv(), save_UseProgramObjectARB(), save_UseShaderProgramEXT(), save_VertexAttribDivisor(), save_Viewport(), save_WaitSync(), save_WindowPos2dMESA(), save_WindowPos2dvMESA(), save_WindowPos2fMESA(), save_WindowPos2fvMESA(), save_WindowPos2iMESA(), save_WindowPos2ivMESA(), save_WindowPos2sMESA(), save_WindowPos2svMESA(), save_WindowPos3dMESA(), save_WindowPos3dvMESA(), save_WindowPos3fMESA(), save_WindowPos3fvMESA(), save_WindowPos3iMESA(), save_WindowPos3ivMESA(), save_WindowPos3sMESA(), save_WindowPos3svMESA(), save_WindowPos4dMESA(), save_WindowPos4dvMESA(), save_WindowPos4fMESA(), save_WindowPos4fvMESA(), save_WindowPos4iMESA(), save_WindowPos4ivMESA(), save_WindowPos4sMESA(), save_WindowPos4svMESA(), SET_Accum(), SET_ActiveProgramEXT(), SET_ActiveStencilFaceEXT(), SET_ActiveTexture(), SET_AlphaFunc(), SET_BeginConditionalRender(), SET_BeginQuery(), SET_BeginQueryIndexed(), SET_BeginTransformFeedback(), SET_BindFragmentShaderATI(), SET_BindProgramARB(), SET_BindSampler(), SET_BindTexture(), SET_BindTransformFeedback(), SET_Bitmap(), SET_BlendColor(), SET_BlendEquation(), SET_BlendEquationiARB(), SET_BlendEquationSeparate(), SET_BlendEquationSeparateiARB(), SET_BlendFunc(), SET_BlendFunciARB(), SET_BlendFuncSeparate(), SET_BlendFuncSeparateiARB(), SET_BlitFramebuffer(), SET_CallList(), SET_CallLists(), SET_ClampColor(), SET_Clear(), SET_ClearAccum(), SET_ClearBufferfi(), SET_ClearBufferfv(), SET_ClearBufferiv(), SET_ClearBufferuiv(), SET_ClearColor(), SET_ClearColorIiEXT(), SET_ClearColorIuiEXT(), SET_ClearDepth(), SET_ClearIndex(), SET_ClearStencil(), SET_ClipPlane(), SET_ColorMask(), SET_ColorMaski(), SET_ColorMaterial(), SET_ColorSubTable(), SET_ColorTable(), SET_ColorTableParameterfv(), SET_ColorTableParameteriv(), SET_CompressedTexImage1D(), SET_CompressedTexImage2D(), SET_CompressedTexImage3D(), SET_CompressedTexSubImage1D(), SET_CompressedTexSubImage2D(), SET_CompressedTexSubImage3D(), SET_ConvolutionFilter1D(), SET_ConvolutionFilter2D(), SET_ConvolutionParameterf(), SET_ConvolutionParameterfv(), SET_ConvolutionParameteri(), SET_ConvolutionParameteriv(), SET_CopyColorSubTable(), SET_CopyColorTable(), SET_CopyPixels(), SET_CopyTexImage1D(), SET_CopyTexImage2D(), SET_CopyTexSubImage1D(), SET_CopyTexSubImage2D(), SET_CopyTexSubImage3D(), SET_CullFace(), SET_DepthBoundsEXT(), SET_DepthFunc(), SET_DepthMask(), SET_DepthRange(), SET_Disable(), SET_Disablei(), SET_DrawArraysInstancedARB(), SET_DrawArraysInstancedBaseInstance(), SET_DrawBuffer(), SET_DrawBuffers(), SET_DrawElementsInstancedARB(), SET_DrawElementsInstancedBaseInstance(), SET_DrawElementsInstancedBaseVertex(), SET_DrawElementsInstancedBaseVertexBaseInstance(), SET_DrawPixels(), SET_DrawTransformFeedback(), SET_DrawTransformFeedbackInstanced(), SET_DrawTransformFeedbackStream(), SET_DrawTransformFeedbackStreamInstanced(), SET_Enable(), SET_Enablei(), SET_EndConditionalRender(), SET_EndQuery(), SET_EndQueryIndexed(), SET_EndTransformFeedback(), SET_EvalMesh1(), SET_EvalMesh2(), SET_Fogf(), SET_Fogfv(), SET_Fogi(), SET_Fogiv(), SET_FramebufferTexture(), SET_FramebufferTextureFaceARB(), SET_FrontFace(), SET_Frustum(), SET_Hint(), SET_Histogram(), SET_IndexMask(), SET_InitNames(), SET_Lightf(), SET_Lightfv(), SET_Lighti(), SET_Lightiv(), SET_LightModelf(), SET_LightModelfv(), SET_LightModeli(), SET_LightModeliv(), SET_LineStipple(), SET_LineWidth(), SET_ListBase(), SET_LoadIdentity(), SET_LoadMatrixd(), SET_LoadMatrixf(), SET_LoadName(), SET_LoadTransposeMatrixd(), SET_LoadTransposeMatrixf(), SET_LogicOp(), SET_Map1d(), SET_Map1f(), SET_Map2d(), SET_Map2f(), SET_MapGrid1d(), SET_MapGrid1f(), SET_MapGrid2d(), SET_MapGrid2f(), SET_MatrixMode(), SET_Minmax(), SET_MultMatrixd(), SET_MultMatrixf(), SET_MultTransposeMatrixd(), SET_MultTransposeMatrixf(), SET_NewList(), SET_Ortho(), SET_PassThrough(), SET_PauseTransformFeedback(), SET_PixelMapfv(), SET_PixelMapuiv(), SET_PixelMapusv(), SET_PixelTransferf(), SET_PixelTransferi(), SET_PixelZoom(), SET_PointParameterf(), SET_PointParameterfv(), SET_PointParameteri(), SET_PointParameteriv(), SET_PointSize(), SET_PolygonMode(), SET_PolygonOffset(), SET_PolygonOffsetEXT(), SET_PolygonStipple(), SET_PopAttrib(), SET_PopMatrix(), SET_PopName(), SET_PrioritizeTextures(), SET_ProgramEnvParameter4dARB(), SET_ProgramEnvParameter4dvARB(), SET_ProgramEnvParameter4fARB(), SET_ProgramEnvParameter4fvARB(), SET_ProgramEnvParameters4fvEXT(), SET_ProgramLocalParameter4dARB(), SET_ProgramLocalParameter4dvARB(), SET_ProgramLocalParameter4fARB(), SET_ProgramLocalParameter4fvARB(), SET_ProgramLocalParameters4fvEXT(), SET_ProgramParameteri(), SET_ProgramStringARB(), SET_ProvokingVertex(), SET_PushAttrib(), SET_PushMatrix(), SET_PushName(), SET_QueryCounter(), SET_RasterPos2d(), SET_RasterPos2dv(), SET_RasterPos2f(), SET_RasterPos2fv(), SET_RasterPos2i(), SET_RasterPos2iv(), SET_RasterPos2s(), SET_RasterPos2sv(), SET_RasterPos3d(), SET_RasterPos3dv(), SET_RasterPos3f(), SET_RasterPos3fv(), SET_RasterPos3i(), SET_RasterPos3iv(), SET_RasterPos3s(), SET_RasterPos3sv(), SET_RasterPos4d(), SET_RasterPos4dv(), SET_RasterPos4f(), SET_RasterPos4fv(), SET_RasterPos4i(), SET_RasterPos4iv(), SET_RasterPos4s(), SET_RasterPos4sv(), SET_ReadBuffer(), SET_Rectf(), SET_ResetHistogram(), SET_ResetMinmax(), SET_ResumeTransformFeedback(), SET_Rotated(), SET_Rotatef(), SET_SampleCoverage(), SET_SamplerParameterf(), SET_SamplerParameterfv(), SET_SamplerParameteri(), SET_SamplerParameterIiv(), SET_SamplerParameterIuiv(), SET_SamplerParameteriv(), SET_Scaled(), SET_Scalef(), SET_Scissor(), SET_SetFragmentShaderConstantATI(), SET_ShadeModel(), SET_StencilFunc(), SET_StencilFuncSeparate(), SET_StencilFuncSeparateATI(), SET_StencilMask(), SET_StencilMaskSeparate(), SET_StencilOp(), SET_StencilOpSeparate(), SET_TexBumpParameterfvATI(), SET_TexBumpParameterivATI(), SET_TexEnvf(), SET_TexEnvfv(), SET_TexEnvi(), SET_TexEnviv(), SET_TexGend(), SET_TexGendv(), SET_TexGenf(), SET_TexGenfv(), SET_TexGeni(), SET_TexGeniv(), SET_TexImage1D(), SET_TexImage2D(), SET_TexImage3D(), SET_TexParameterf(), SET_TexParameterfv(), SET_TexParameteri(), SET_TexParameterIiv(), SET_TexParameterIuiv(), SET_TexParameteriv(), SET_TexSubImage1D(), SET_TexSubImage2D(), SET_TexSubImage3D(), SET_TextureBarrierNV(), SET_Translated(), SET_Translatef(), SET_Uniform1f(), SET_Uniform1fv(), SET_Uniform1i(), SET_Uniform1iv(), SET_Uniform1ui(), SET_Uniform1uiv(), SET_Uniform2f(), SET_Uniform2fv(), SET_Uniform2i(), SET_Uniform2iv(), SET_Uniform2ui(), SET_Uniform2uiv(), SET_Uniform3f(), SET_Uniform3fv(), SET_Uniform3i(), SET_Uniform3iv(), SET_Uniform3ui(), SET_Uniform3uiv(), SET_Uniform4f(), SET_Uniform4fv(), SET_Uniform4i(), SET_Uniform4iv(), SET_Uniform4ui(), SET_Uniform4uiv(), SET_UniformBlockBinding(), SET_UniformMatrix2fv(), SET_UniformMatrix2x3fv(), SET_UniformMatrix2x4fv(), SET_UniformMatrix3fv(), SET_UniformMatrix3x2fv(), SET_UniformMatrix3x4fv(), SET_UniformMatrix4fv(), SET_UniformMatrix4x2fv(), SET_UniformMatrix4x3fv(), SET_UseProgram(), SET_UseShaderProgramEXT(), SET_VertexAttribDivisor(), SET_Viewport(), SET_WaitSync(), SET_WindowPos2d(), SET_WindowPos2dv(), SET_WindowPos2f(), SET_WindowPos2fv(), SET_WindowPos2i(), SET_WindowPos2iv(), SET_WindowPos2s(), SET_WindowPos2sv(), SET_WindowPos3d(), SET_WindowPos3dv(), SET_WindowPos3f(), SET_WindowPos3fv(), SET_WindowPos3i(), SET_WindowPos3iv(), SET_WindowPos3s(), SET_WindowPos3sv(), SET_WindowPos4dMESA(), SET_WindowPos4dvMESA(), SET_WindowPos4fMESA(), SET_WindowPos4fvMESA(), SET_WindowPos4iMESA(), SET_WindowPos4ivMESA(), SET_WindowPos4sMESA(), SET_WindowPos4svMESA(), table, vbo_initialize_save_dispatch(), and void().
Referenced by _mesa_initialize_dispatch_tables().
void _mesa_install_dlist_vtxfmt (struct _glapi_table * disp, const GLvertexformat * vfmt)
References SET_CallList(), and SET_CallLists().
Referenced by install_vtxfmt().
GLboolean GLAPIENTRY _mesa_IsList (GLuint list)
Test if a display list number is valid.
References ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, FLUSH_VERTICES, and islist().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ListBase (GLuint base)
Set the offset added to list numbers in glCallLists.
References ASSERT_OUTSIDE_BEGIN_END, FLUSH_VERTICES, gl_context::List, and gl_list_attrib::ListBase.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_NewList (GLuint name, GLenum mode)
Begin a new display list.
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), ASSERT_OUTSIDE_BEGIN_END, BLOCK_SIZE, gl_context::CompileFlag, gl_dlist_state::CurrentBlock, gl_context::CurrentDispatch, gl_dlist_state::CurrentList, gl_dlist_state::CurrentPos, gl_context::Driver, gl_context::ExecuteFlag, FLUSH_CURRENT, gl_display_list::Head, invalidate_saved_current_state(), gl_context::ListState, make_list(), MESA_VERBOSE, dd_function_table::NewList, gl_context::Save, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().