Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
dlopen.h File Reference
Typedefs
typedef void(* GenericFunc)(void)
Wrapper functions for dlopen(), dlsym(), dlclose().
Functions
static void * _mesa_dlopen (const char *libname, int flags)
Wrapper for dlopen().
static GenericFunc _mesa_dlsym (void *handle, const char *fname)
Wrapper for dlsym() that does a cast to a generic function type, rather than a void *.
static void _mesa_dlclose (void *handle)
Wrapper for dlclose().
Typedef Documentation
typedef void(* GenericFunc)(void)
Wrapper functions for dlopen(), dlsym(), dlclose().
Note that the #ifdef tests for various environments should be expanded.
Function Documentation
static void _mesa_dlclose (void * handle) inline static
Wrapper for dlclose().
References void().
Referenced by _mesa_init_texture_s3tc().
static void* _mesa_dlopen (const char * libname, int flags) inline static
Wrapper for dlopen().
Note that 'flags' isn't used at this time.
References NULL.
Referenced by _mesa_init_texture_s3tc().
static GenericFunc _mesa_dlsym (void * handle, const char * fname) inline static
Wrapper for dlsym() that does a cast to a generic function type, rather than a void *.
This reduces the number of warnings that are generated.
References NULL.
Referenced by _mesa_init_texture_s3tc().