Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
drawpix.c File Reference
#include "glheader.h"
#include "imports.h"
#include "bufferobj.h"
#include "context.h"
#include "drawpix.h"
#include "enums.h"
#include "feedback.h"
#include "framebuffer.h"
#include "image.h"
#include "pbo.h"
#include "state.h"
#include "dispatch.h"
#include "glformats.h"
#include "fbobject.h"
Functions
void GLAPIENTRY _mesa_DrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_CopyPixels (GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLenum type)
void GLAPIENTRY _mesa_Bitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap)
Function Documentation
void GLAPIENTRY _mesa_Bitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap)
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_feedback_token(), _mesa_feedback_vertex(), _mesa_flush(), _mesa_is_bufferobj(), _mesa_valid_to_render(), _mesa_validate_pbo_access(), ASSERT, DEBUG_ALWAYS_FLUSH, FLUSH_CURRENT, FLUSH_VERTICES, IFLOOR(), and MESA_DEBUG_FLAGS.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyPixels (GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLenum type)
References _mesa_debug(), _mesa_dest_buffer_exists(), _mesa_error(), _mesa_feedback_token(), _mesa_feedback_vertex(), _mesa_flush(), _mesa_is_user_fbo(), _mesa_lookup_enum_by_nr(), _mesa_set_vp_override(), _mesa_source_buffer_exists(), _mesa_valid_to_render(), ASSERT, DEBUG_ALWAYS_FLUSH, FLUSH_CURRENT, FLUSH_VERTICES, IROUND(), MESA_DEBUG_FLAGS, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
References _mesa_bufferobj_mapped(), _mesa_debug(), _mesa_dest_buffer_exists(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_feedback_token(), _mesa_feedback_vertex(), _mesa_flush(), _mesa_is_bufferobj(), _mesa_is_enum_format_integer(), _mesa_lookup_enum_by_nr(), _mesa_set_vp_override(), _mesa_valid_to_render(), _mesa_validate_pbo_access(), ASSERT, DEBUG_ALWAYS_FLUSH, FLUSH_CURRENT, FLUSH_VERTICES, IROUND(), MESA_DEBUG_FLAGS, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().