Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
enums.c File Reference
#include "main/glheader.h"
#include "main/enums.h"
#include "main/imports.h"
#include "main/mtypes.h"
Data Structures
struct enum_elt
Typedefs
typedef int(* cfunc)(const void *, const void *)
Functions
static int compar_name (const char *a, const enum_elt *b)
Compare a key name to an element in the all_enums array.
static int compar_nr (const int *a, const unsigned *b)
Compare a key enum value to an element in the all_enums array.
const char * _mesa_lookup_enum_by_nr (int nr)
const char * _mesa_lookup_prim_by_nr (GLuint nr)
int _mesa_lookup_enum_by_name (const char *symbol)
Variables
static LONGSTRING const char enum_string_table []
static const enum_elt all_enums [2644]
static const unsigned reduced_enums [1838]
static char token_tmp [20]
static const char * prim_names [PRIM_MAX+3]
Primitive names.
Typedef Documentation
typedef int(* cfunc)(const void *, const void *)
Function Documentation
int _mesa_lookup_enum_by_name (const char * symbol)
References _mesa_bsearch(), compar_name(), Elements, enum_elt::n, and NULL.
const char* _mesa_lookup_enum_by_nr (int nr)
References _mesa_bsearch(), _mesa_snprintf(), compar_nr(), Elements, enum_string_table, NULL, enum_elt::offset, reduced_enums, and token_tmp.
Referenced by _mesa_ActiveTexture(), _mesa_AlphaFunc(), _mesa_BeginConditionalRender(), _mesa_BeginQueryIndexed(), _mesa_BindBuffer(), _mesa_BindTexture(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparate(), _mesa_BlitFramebuffer(), _mesa_BufferData(), _mesa_check_conditional_render(), _mesa_CheckFramebufferStatus(), _mesa_choose_tex_format(), _mesa_choose_texture_format(), _mesa_ClampColor(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_ClientActiveTexture(), _mesa_ColorMaterial(), _mesa_CopyPixels(), _mesa_CreateShader(), _mesa_CullFace(), _mesa_DepthFunc(), _mesa_DiscardFramebufferEXT(), _mesa_DrawBuffer(), _mesa_DrawPixels(), _mesa_EndFragmentShaderATI(), _mesa_EndQueryIndexed(), _mesa_error(), _mesa_FramebufferRenderbuffer(), _mesa_FramebufferTexture1D(), _mesa_FramebufferTexture2D(), _mesa_FrontFace(), _mesa_GenerateMipmap(), _mesa_GetActiveUniformBlockiv(), _mesa_GetBufferParameteri64v(), _mesa_GetBufferParameteriv(), _mesa_GetError(), _mesa_GetInternalformativ(), _mesa_GetPointerv(), _mesa_GetQueryIndexediv(), _mesa_GetQueryObjecti64v(), _mesa_GetQueryObjectiv(), _mesa_GetQueryObjectui64v(), _mesa_GetQueryObjectuiv(), _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_Hint(), _mesa_IsEnabled(), _mesa_IsEnabledi(), _mesa_LogicOp(), _mesa_NewList(), _mesa_PassTexCoordATI(), _mesa_PolygonMode(), _mesa_PopAttrib(), _mesa_PopMatrix(), _mesa_print_framebuffer(), _mesa_print_texunit_state(), _mesa_ProgramParameteri(), _mesa_PushMatrix(), _mesa_QueryCounter(), _mesa_ReadBuffer(), _mesa_ReadnPixelsARB(), _mesa_RenderMode(), _mesa_SampleMapATI(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), _mesa_set_enable(), _mesa_set_enablei(), _mesa_ShadeModel(), _mesa_TexEnvfv(), _mesa_TexGenfv(), _pack_rgba_span_from_ints_problem(), _pack_rgba_span_from_uints_problem(), check_extra(), client_state(), compute_component_mapping(), copyteximage(), copytexsubimage(), copytexsubimage_error_check(), copytexture_error_check(), dump_renderbuffer(), enum_string(), find_value(), find_value_indexed(), flush_delayed_errors(), FN_NAME(), get_component_mapping(), get_programiv(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), print_list(), renderbuffer_storage(), set_tex_parameterf(), set_tex_parameteri(), tex_storage_error_check(), teximage(), teximagemultisample(), texsubimage(), texsubimage_error_check(), texture_error_check(), update_array(), valid_elements_type(), and validate_blend_factors().
const char* _mesa_lookup_prim_by_nr (GLuint nr)
References Elements, and prim_names.
Referenced by _mesa_valid_prim_mode().
static int compar_name (const char * a, const enum_elt * b) static
Compare a key name to an element in the all_enums array.
bsearch always passes the key as the first parameter and the pointer to the array element as the second parameter. We can elimiate some extra work by taking advantage of that fact.
Parameters
a Pointer to the desired enum name.
b Pointer to an element of the all_enums array.
References enum_string_table, and enum_elt::offset.
Referenced by _mesa_lookup_enum_by_name().
static int compar_nr (const int * a, const unsigned * b) static
Compare a key enum value to an element in the all_enums array.
bsearch always passes the key as the first parameter and the pointer to the array element as the second parameter. We can elimiate some extra work by taking advantage of that fact.
Parameters
a Pointer to the desired enum name.
b Pointer to an index into the all_enums array.
References enum_elt::n.
Referenced by _mesa_lookup_enum_by_nr().
Variable Documentation
const enum_elt all_enums[2644] static
LONGSTRING const char enum_string_table[] static
Referenced by _mesa_lookup_enum_by_nr(), and compar_name().
const char* prim_names[PRIM_MAX+3] static
Initial value:
= {
   "GL_POINTS",
   "GL_LINES",
   "GL_LINE_LOOP",
   "GL_LINE_STRIP",
   "GL_TRIANGLES",
   "GL_TRIANGLE_STRIP",
   "GL_TRIANGLE_FAN",
   "GL_QUADS",
   "GL_QUAD_STRIP",
   "GL_POLYGON",
   "GL_LINES_ADJACENCY",
   "GL_LINE_STRIP_ADJACENCY",
   "GL_TRIANGLES_ADJACENCY",
   "GL_TRIANGLE_STRIP_ADJACENCY",
   "outside begin/end",
   "unknown state"
}
Primitive names.
Referenced by _mesa_lookup_prim_by_nr().
const unsigned reduced_enums[1838] static
Referenced by _mesa_lookup_enum_by_nr().
char token_tmp[20] static
Referenced by _mesa_lookup_enum_by_nr().