Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
errors.h File Reference
Mesa debugging and error handling functions.
#include "compiler.h"
#include "glheader.h"
#include "mtypes.h"
Macros
#define _mesa_perf_debug(ctx, sev,...)
Functions
void _mesa_init_errors (struct gl_context *ctx)
void _mesa_free_errors_data (struct gl_context *ctx)
void _mesa_warning (struct gl_context *gc, const char *fmtString,...) PRINTFLIKE(2
void void _mesa_problem (const struct gl_context *ctx, const char *fmtString,...) PRINTFLIKE(2
void void void _mesa_error (struct gl_context *ctx, GLenum error, const char *fmtString,...) PRINTFLIKE(3
void void void void _mesa_debug (const struct gl_context *ctx, const char *fmtString,...) PRINTFLIKE(2
void void void void void _mesa_gl_debug (struct gl_context *ctx, GLuint *id, enum mesa_debug_type type, enum mesa_debug_severity severity, const char *fmtString,...) PRINTFLIKE(5
void _mesa_shader_debug (struct gl_context *ctx, GLenum type, GLuint *id, const char *msg, int len)
Report debug information from the shader compiler via GL_ARB_debug_output.
void GLAPIENTRY _mesa_DebugMessageInsertARB (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLcharARB *buf)
GLuint GLAPIENTRY _mesa_GetDebugMessageLogARB (GLuint count, GLsizei logSize, GLenum *sources, GLenum *types, GLenum *ids, GLenum *severities, GLsizei *lengths, GLcharARB *messageLog)
void GLAPIENTRY _mesa_DebugMessageControlARB (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled)
void GLAPIENTRY _mesa_DebugMessageCallbackARB (GLDEBUGPROCARB callback, const GLvoid *userParam)
Detailed Description
Mesa debugging and error handling functions.
This file provides functions to record errors, warnings, and miscellaneous debug information.
Macro Definition Documentation
#define _mesa_perf_debug (ctx, sev, ...)
Value:
do {                              \
   static GLuint msg_id = 0;                                              \
   if (unlikely(ctx->Const.ContextFlags & GL_CONTEXT_FLAG_DEBUG_BIT)) {   \
      _mesa_gl_debug(ctx, &msg_id,                                        \
                     MESA_DEBUG_TYPE_PERFORMANCE,                         \
                     sev,                                                 \
                     __VA_ARGS__);                                        \
   }                                                                      \
} while (0)
Function Documentation
void void void void _mesa_debug (const struct gl_context * ctx, const char * fmtString, ...)
void GLAPIENTRY _mesa_DebugMessageCallbackARB (GLDEBUGPROCARB callback, const GLvoid * userParam)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DebugMessageControlARB (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint * ids, GLboolean enabled)
References _mesa_error(), CONTROL, control_app_messages(), gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), and validate_params().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DebugMessageInsertARB (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLcharARB * buf)
References _mesa_error(), _mesa_log_msg(), gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), INSERT, MAX_DEBUG_MESSAGE_LENGTH, and validate_params().
Referenced by _mesa_initialize_exec_table().
void void void _mesa_error (struct gl_context * ctx, GLenum error, const char * fmtString, ...)
void _mesa_free_errors_data (struct gl_context * ctx)
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), gl_context::Debug, do_nothing(), foreach_s, gl_debug_namespace::IDs, MESA_DEBUG_SEVERITY_COUNT, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, gl_debug_state::Namespaces, NULL, and gl_debug_namespace::Severity.
Referenced by _mesa_free_context_data().
GLuint GLAPIENTRY _mesa_GetDebugMessageLogARB (GLuint count, GLsizei logSize, GLenum * sources, GLenum * types, GLenum * ids, GLenum * severities, GLsizei * lengths, GLcharARB * messageLog)
References _mesa_error(), and _mesa_get_msg().
Referenced by _mesa_initialize_exec_table().
void void void void void _mesa_gl_debug (struct gl_context * ctx, GLuint * id, enum mesa_debug_type type, enum mesa_debug_severity severity, const char * fmtString, ...)
void _mesa_init_errors (struct gl_context * ctx)
References _mesa_NewHashTable(), gl_debug_state::Callback, gl_context::Debug, gl_debug_state::Defaults, gl_debug_namespace::IDs, gl_debug_msg::length, gl_debug_state::Log, make_empty_list, MESA_DEBUG_SEVERITY_COUNT, MESA_DEBUG_SEVERITY_HIGH, MESA_DEBUG_SEVERITY_LOW, MESA_DEBUG_SEVERITY_MEDIUM, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, gl_debug_state::Namespaces, gl_debug_state::NextMsg, gl_debug_state::NextMsgLength, NULL, gl_debug_state::NumMessages, gl_debug_namespace::Severity, and gl_debug_state::SyncOutput.
Referenced by init_attrib_groups().
void void _mesa_problem (const struct gl_context * ctx, const char * fmtString, ...)
void _mesa_shader_debug (struct gl_context * ctx, GLenum type, GLuint * id, const char * msg, int len)
Report debug information from the shader compiler via GL_ARB_debug_output.
Parameters
ctx GL context.
type The namespace to which this message belongs.
id The message ID within the given namespace.
msg The message to output. Need not be null-terminated.
len The length of 'msg'. If negative, 'msg' must be null-terminated.
References _mesa_log_msg(), debug_get_id(), MAX_DEBUG_MESSAGE_LENGTH, MESA_DEBUG_SEVERITY_HIGH, and MESA_DEBUG_SOURCE_SHADER_COMPILER.
void _mesa_warning (struct gl_context * gc, const char * fmtString, ...)