Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
errors.c File Reference
Mesa debugging and error handling functions.
#include "errors.h"
#include "enums.h"
#include "imports.h"
#include "context.h"
#include "dispatch.h"
#include "hash.h"
#include "mtypes.h"
#include "version.h"
#include "hash_table.h"
#include "glapi/glthread.h"
Data Structures
struct gl_debug_severity
Macros
#define INSERT 1
#define CONTROL 2
Enumerations
enum {
FOUND_BIT = 1 << 0, ENABLED_BIT = 1 << 1, KNOWN_SEVERITY = 1 << 2, NOT_FOUND = 0,
DISABLED = FOUND_BIT, ENABLED = ENABLED_BIT | FOUND_BIT
}
Functions
_glthread_DECLARE_STATIC_MUTEX (DynamicIDMutex)
static enum mesa_debug_source gl_enum_to_debug_source (GLenum e)
static enum mesa_debug_type gl_enum_to_debug_type (GLenum e)
static enum mesa_debug_severity gl_enum_to_debug_severity (GLenum e)
static void debug_get_id (GLuint *id)
Handles generating a GL_ARB_debug_output message ID generated by the GL or GLSL compiler.
static GLboolean should_log (struct gl_context *ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity)
Returns the state of the given message source/type/ID tuple.
static void set_message_state (struct gl_context *ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, GLboolean enabled)
Sets the state of the given message source/type/ID tuple.
static void _mesa_log_msg (struct gl_context *ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char *buf)
'buf' is not necessarily a null-terminated string.
static GLsizei _mesa_get_msg (struct gl_context *ctx, GLenum *source, GLenum *type, GLuint *id, GLenum *severity, GLsizei bufSize, char *buf)
Pop the oldest debug message out of the log.
static GLboolean validate_params (struct gl_context *ctx, unsigned caller, GLenum source, GLenum type, GLenum severity)
Verify that source, type, and severity are valid enums.
void GLAPIENTRY _mesa_DebugMessageInsertARB (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLcharARB *buf)
GLuint GLAPIENTRY _mesa_GetDebugMessageLogARB (GLuint count, GLsizei logSize, GLenum *sources, GLenum *types, GLenum *ids, GLenum *severities, GLsizei *lengths, GLcharARB *messageLog)
static void control_messages (struct gl_context *ctx, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, GLboolean enabled)
Set the state of all message IDs found in the given intersection of 'source', 'type', and 'severity'.
static void control_app_messages (struct gl_context *ctx, GLenum esource, GLenum etype, GLenum eseverity, GLsizei count, const GLuint *ids, GLboolean enabled)
Debugging-message namespaces with the source APPLICATION or THIRD_PARTY require special handling, since the IDs in them are controlled by clients, not the OpenGL implementation.
void GLAPIENTRY _mesa_DebugMessageControlARB (GLenum gl_source, GLenum gl_type, GLenum gl_severity, GLsizei count, const GLuint *ids, GLboolean enabled)
void GLAPIENTRY _mesa_DebugMessageCallbackARB (GLDEBUGPROCARB callback, const GLvoid *userParam)
void _mesa_init_errors (struct gl_context *ctx)
static void do_nothing (GLuint key, void *data, void *userData)
void _mesa_free_errors_data (struct gl_context *ctx)
Diagnostics
static void output_if_debug (const char *prefixString, const char *outputString, GLboolean newline)
static void flush_delayed_errors (struct gl_context *ctx)
When a new type of error is recorded, print a message describing previous errors which were accumulated.
void _mesa_warning (struct gl_context *ctx, const char *fmtString,...)
Report a warning (a recoverable error condition) to stderr if either DEBUG is defined or the MESA_DEBUG env var is set.
void _mesa_problem (const struct gl_context *ctx, const char *fmtString,...)
Report an internal implementation problem.
static GLboolean should_output (struct gl_context *ctx, GLenum error, const char *fmtString)
void _mesa_gl_debug (struct gl_context *ctx, GLuint *id, enum mesa_debug_type type, enum mesa_debug_severity severity, const char *fmtString,...)
void _mesa_error (struct gl_context *ctx, GLenum error, const char *fmtString,...)
Record an OpenGL state error.
void _mesa_debug (const struct gl_context *ctx, const char *fmtString,...)
Report debug information.
void _mesa_shader_debug (struct gl_context *ctx, GLenum type, GLuint *id, const char *msg, int len)
Report debug information from the shader compiler via GL_ARB_debug_output.
Variables
static GLuint NextDynamicID = 1
static char out_of_memory [] = "Debugging error: out of memory"
static const GLenum debug_source_enums []
static const GLenum debug_type_enums []
static const GLenum debug_severity_enums []
Detailed Description
Mesa debugging and error handling functions.
Macro Definition Documentation
#define CONTROL 2
Referenced by _mesa_DebugMessageControlARB(), and validate_params().
#define INSERT 1
Referenced by _mesa_DebugMessageInsertARB(), and validate_params().
Enumeration Type Documentation
anonymous enum
Enumerator
FOUND_BIT
ENABLED_BIT
KNOWN_SEVERITY
NOT_FOUND
DISABLED
ENABLED
Function Documentation
_glthread_DECLARE_STATIC_MUTEX (DynamicIDMutex)
void _mesa_debug (const struct gl_context * ctx, const char * fmtString, ...)
Report debug information.
Print error message to stderr via fprintf(). No-op if DEBUG mode not enabled.
Parameters
ctx GL context.
fmtString printf()-style format string, followed by optional args.
References _mesa_vsnprintf(), MAX_DEBUG_MESSAGE_LENGTH, output_if_debug(), and void().
Referenced by _mesa_ActiveStencilFaceEXT(), _mesa_ActiveTexture(), _mesa_AlphaFunc(), _mesa_AreTexturesResident(), _mesa_BeginQueryIndexed(), _mesa_BindBuffer(), _mesa_BindTexture(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparate(), _mesa_BlitFramebuffer(), _mesa_BufferData(), _mesa_CallList(), _mesa_CallLists(), _mesa_CheckFramebufferStatus(), _mesa_Clear(), _mesa_ClearDepth(), _mesa_ClientActiveTexture(), _mesa_ColorMask(), _mesa_ColorMaski(), _mesa_ColorMaterial(), _mesa_CompileShader(), _mesa_CopyPixels(), _mesa_CreateProgram(), _mesa_CreateShader(), _mesa_CullFace(), _mesa_DeleteObjectARB(), _mesa_DeleteQueries(), _mesa_DeleteTextures(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DepthMask(), _mesa_DepthRange(), _mesa_DrawBuffer(), _mesa_DrawPixels(), _mesa_EndList(), _mesa_EndQueryIndexed(), _mesa_FrontFace(), _mesa_GenBuffers(), _mesa_GenQueries(), _mesa_GenSamplers(), _mesa_GenTextures(), _mesa_GetError(), _mesa_GetGraphicsResetStatusARB(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnPolygonStippleARB(), _mesa_GetnTexImageARB(), _mesa_GetPointerv(), _mesa_GetQueryIndexediv(), _mesa_GetQueryObjecti64v(), _mesa_GetQueryObjectiv(), _mesa_GetQueryObjectui64v(), _mesa_GetQueryObjectuiv(), _mesa_Hint(), _mesa_InvalidateTexImage(), _mesa_InvalidateTexSubImage(), _mesa_IsQuery(), _mesa_IsTexture(), _mesa_LineStipple(), _mesa_LineWidth(), _mesa_LoadIdentity(), _mesa_LoadMatrixf(), _mesa_LockArraysEXT(), _mesa_LogicOp(), _mesa_make_current(), _mesa_make_extension_string(), _mesa_MultMatrixf(), _mesa_NewList(), _mesa_notifySwapBuffers(), _mesa_Ortho(), _mesa_PassTexCoordATI(), _mesa_PolygonMode(), _mesa_PolygonOffset(), _mesa_PolygonStipple(), _mesa_PopAttrib(), _mesa_PopMatrix(), _mesa_print_info(), _mesa_print_state(), _mesa_PrioritizeTextures(), _mesa_ProvokingVertex(), _mesa_PushAttrib(), _mesa_PushMatrix(), _mesa_QueryCounter(), _mesa_ReadBuffer(), _mesa_ReadnPixelsARB(), _mesa_RenderMode(), _mesa_resizebuffers(), _mesa_SampleMapATI(), _mesa_Scissor(), _mesa_set_enable(), _mesa_set_viewport(), _mesa_ShadeModel(), _mesa_StencilFunc(), _mesa_StencilFuncSeparate(), _mesa_StencilFuncSeparateATI(), _mesa_StencilMask(), _mesa_StencilMaskSeparate(), _mesa_StencilOp(), _mesa_StencilOpSeparate(), _mesa_TexEnvfv(), _mesa_TexGenfv(), _mesa_UnlockArraysEXT(), _mesa_update_material(), _mesa_write_renderbuffer_image(), att_incomplete(), compile_shader(), copyteximage(), copytexsubimage(), debug_print_entry(), fbo_incomplete(), incomplete(), link_program(), one_time_init(), problem(), renderbuffer_storage(), teximage(), and texsubimage().
void GLAPIENTRY _mesa_DebugMessageCallbackARB (GLDEBUGPROCARB callback, const GLvoid * userParam)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DebugMessageControlARB (GLenum gl_source, GLenum gl_type, GLenum gl_severity, GLsizei count, const GLuint * ids, GLboolean enabled)
References _mesa_error(), CONTROL, control_app_messages(), gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), and validate_params().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DebugMessageInsertARB (GLenum source, GLenum type, GLuint id, GLenum severity, GLint length, const GLcharARB * buf)
References _mesa_error(), _mesa_log_msg(), gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), INSERT, MAX_DEBUG_MESSAGE_LENGTH, and validate_params().
Referenced by _mesa_initialize_exec_table().
void _mesa_error (struct gl_context * ctx, GLenum error, const char * fmtString, ...)
Record an OpenGL state error.
These usually occur when the user passes invalid parameters to a GL function.
If debugging is enabled (either at compile-time via the DEBUG macro, or run-time via the MESA_DEBUG environment variable), report the error with _mesa_debug().
Parameters
ctx the GL context.
error the error value.
fmtString printf() style format string, followed by optional args
References _mesa_log_msg(), _mesa_lookup_enum_by_nr(), _mesa_record_error(), _mesa_snprintf(), _mesa_vsnprintf(), ASSERT, debug_get_id(), MAX_DEBUG_MESSAGE_LENGTH, MESA_DEBUG_SEVERITY_HIGH, MESA_DEBUG_SOURCE_API, MESA_DEBUG_TYPE_ERROR, output_if_debug(), should_log(), and should_output().
Referenced by _es_TexGenf(), _es_TexGenfv(), _mesa_Accum(), _mesa_active_program(), _mesa_ActiveStencilFaceEXT(), _mesa_ActiveTexture(), _mesa_AlphaFunc(), _mesa_AreTexturesResident(), _mesa_BeginConditionalRender(), _mesa_BeginFragmentShaderATI(), _mesa_BeginQueryIndexed(), _mesa_BeginTransformFeedback(), _mesa_bind_buffer_base_transform_feedback(), _mesa_bind_buffer_range_transform_feedback(), _mesa_BindBufferBase(), _mesa_BindBufferOffsetEXT(), _mesa_BindBufferRange(), _mesa_BindFragmentShaderATI(), _mesa_BindFramebuffer(), _mesa_BindProgramARB(), _mesa_BindRenderbuffer(), _mesa_BindSampler(), _mesa_BindTexture(), _mesa_BindTransformFeedback(), _mesa_Bitmap(), _mesa_BlendEquation(), _mesa_BlendEquationiARB(), _mesa_BlendEquationSeparate(), _mesa_BlendEquationSeparateiARB(), _mesa_BlendFuncSeparateiARB(), _mesa_BlitFramebuffer(), _mesa_BufferData(), _mesa_CallList(), _mesa_CallLists(), _mesa_check_blend_func_error(), _mesa_CheckFramebufferStatus(), _mesa_ClampColor(), _mesa_Clear(), _mesa_clear_accum_buffer(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_ClientActiveTexture(), _mesa_ClientWaitSync(), _mesa_ClipPlane(), _mesa_ColorMaski(), _mesa_ColorSubTable(), _mesa_ColorTable(), _mesa_ColorTableParameterfv(), _mesa_ColorTableParameteriv(), _mesa_compile_error(), _mesa_ConvolutionFilter1D(), _mesa_ConvolutionFilter2D(), _mesa_ConvolutionParameterf(), _mesa_ConvolutionParameterfv(), _mesa_ConvolutionParameteri(), _mesa_ConvolutionParameteriv(), _mesa_CopyBufferSubData(), _mesa_CopyColorSubTable(), _mesa_CopyColorTable(), _mesa_CopyConvolutionFilter1D(), _mesa_CopyConvolutionFilter2D(), _mesa_CopyPixels(), _mesa_CullFace(), _mesa_DebugMessageControlARB(), _mesa_DebugMessageInsertARB(), _mesa_DeleteBuffers(), _mesa_DeleteFragmentShaderATI(), _mesa_DeleteLists(), _mesa_DeleteProgramsARB(), _mesa_DeleteQueries(), _mesa_DeleteSamplers(), _mesa_DeleteSync(), _mesa_DeleteTransformFeedbacks(), _mesa_DeleteVertexArrays(), _mesa_DepthBoundsEXT(), _mesa_DepthFunc(), _mesa_DisableVertexAttribArray(), _mesa_DiscardFramebufferEXT(), _mesa_DrawBuffer(), _mesa_DrawBuffers(), _mesa_DrawPixels(), _mesa_EGLImageTargetRenderbufferStorageOES(), _mesa_EGLImageTargetTexture2DOES(), _mesa_EnableVertexAttribArray(), _mesa_EndConditionalRender(), _mesa_EndFragmentShaderATI(), _mesa_EndList(), _mesa_EndQueryIndexed(), _mesa_EndTransformFeedback(), _mesa_FeedbackBuffer(), _mesa_FenceSync(), _mesa_FlushMappedBufferRange(), _mesa_Fogfv(), _mesa_Fogxv(), _mesa_FragmentOpXATI(), _mesa_FramebufferRenderbuffer(), _mesa_FramebufferTexture(), _mesa_FramebufferTexture1D(), _mesa_FramebufferTexture2D(), _mesa_FramebufferTexture3D(), _mesa_FrontFace(), _mesa_Frustum(), _mesa_GenBuffers(), _mesa_GenerateMipmap(), _mesa_generic_nop(), _mesa_GenFragmentShadersATI(), _mesa_GenFramebuffers(), _mesa_GenLists(), _mesa_GenProgramsARB(), _mesa_GenQueries(), _mesa_GenRenderbuffers(), _mesa_GenSamplers(), _mesa_GenTextures(), _mesa_GenTransformFeedbacks(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_compressed_teximage(), _mesa_get_tex_image(), _mesa_get_teximage(), _mesa_GetActiveUniformBlockiv(), _mesa_GetActiveUniformBlockName(), _mesa_GetActiveUniformName(), _mesa_GetBufferParameteri64v(), _mesa_GetBufferParameteriv(), _mesa_GetBufferPointerv(), _mesa_GetClipPlane(), _mesa_GetColorTable(), _mesa_GetColorTableParameterfv(), _mesa_GetColorTableParameteriv(), _mesa_GetConvolutionParameterfv(), _mesa_GetConvolutionParameteriv(), _mesa_GetDebugMessageLogARB(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetHistogramParameterfv(), _mesa_GetHistogramParameteriv(), _mesa_GetInfoLogARB(), _mesa_GetInternalformativ(), _mesa_GetLightfv(), _mesa_GetLightiv(), _mesa_GetLightxv(), _mesa_GetMaterialfv(), _mesa_GetMaterialiv(), _mesa_GetMaterialxv(), _mesa_GetMinmaxParameterfv(), _mesa_GetMinmaxParameteriv(), _mesa_GetMultisamplefv(), _mesa_GetnColorTableARB(), _mesa_GetnConvolutionFilterARB(), _mesa_GetnHistogramARB(), _mesa_GetnMapdvARB(), _mesa_GetnMapfvARB(), _mesa_GetnMapivARB(), _mesa_GetnMinmaxARB(), _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), _mesa_GetnSeparableFilterARB(), _mesa_GetnUniformdvARB(), _mesa_GetObjectParameterivAPPLE(), _mesa_GetObjectParameterivARB(), _mesa_GetPointerv(), _mesa_GetProgramBinary(), _mesa_GetProgramivARB(), _mesa_GetProgramStringARB(), _mesa_GetQueryIndexediv(), _mesa_GetQueryObjecti64v(), _mesa_GetQueryObjectiv(), _mesa_GetQueryObjectui64v(), _mesa_GetQueryObjectuiv(), _mesa_GetRenderbufferParameteriv(), _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_GetShaderPrecisionFormat(), _mesa_GetString(), _mesa_GetStringi(), _mesa_GetSynciv(), _mesa_GetTexBumpParameterfvATI(), _mesa_GetTexBumpParameterivATI(), _mesa_GetTexEnvfv(), _mesa_GetTexEnviv(), _mesa_GetTexEnvxv(), _mesa_GetTexGendv(), _mesa_GetTexGenfv(), _mesa_GetTexGeniv(), _mesa_GetTexLevelParameteriv(), _mesa_GetTexParameterfv(), _mesa_GetTexParameteriv(), _mesa_GetTexParameterxv(), _mesa_GetTransformFeedbackVarying(), _mesa_GetUniformBlockIndex(), _mesa_GetUniformIndices(), _mesa_GetUniformLocation(), _mesa_GetVertexAttribPointerv(), _mesa_Hint(), _mesa_Histogram(), _mesa_InterleavedArrays(), _mesa_InvalidateBufferData(), _mesa_InvalidateBufferSubData(), _mesa_InvalidateTexSubImage(), _mesa_IsEnabled(), _mesa_IsEnabledi(), _mesa_Lightfv(), _mesa_LightModelfv(), _mesa_LightModelxv(), _mesa_Lightxv(), _mesa_LineWidth(), _mesa_LoadName(), _mesa_LockArraysEXT(), _mesa_LogicOp(), _mesa_lookup_shader_err(), _mesa_lookup_shader_program_err(), _mesa_map_validate_pbo_dest(), _mesa_map_validate_pbo_source(), _mesa_MapBuffer(), _mesa_MapBufferRange(), _mesa_MapGrid1f(), _mesa_MapGrid2f(), _mesa_material_bitmask(), _mesa_Materialx(), _mesa_Materialxv(), _mesa_MatrixMode(), _mesa_Minmax(), _mesa_NewList(), _mesa_ObjectPurgeableAPPLE(), _mesa_ObjectUnpurgeableAPPLE(), _mesa_Ortho(), _mesa_pack_depth_span(), _mesa_pack_depth_stencil_span(), _mesa_pack_index_span(), _mesa_pack_rgba_span_float(), _mesa_pack_stencil_span(), _mesa_PassTexCoordATI(), _mesa_PauseTransformFeedback(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), _mesa_PixelMapusv(), _mesa_PixelStorei(), _mesa_PixelTransferf(), _mesa_PointParameterfv(), _mesa_PointParameterxv(), _mesa_PointSize(), _mesa_PointSizePointerOES(), _mesa_PolygonMode(), _mesa_PopAttrib(), _mesa_PopClientAttrib(), _mesa_PopMatrix(), _mesa_PopName(), _mesa_PrimitiveRestartIndex(), _mesa_PrioritizeTextures(), _mesa_ProgramBinary(), _mesa_ProgramEnvParameters4fvEXT(), _mesa_ProgramLocalParameters4fvEXT(), _mesa_ProgramParameteri(), _mesa_ProgramStringARB(), _mesa_ProvokingVertex(), _mesa_PushAttrib(), _mesa_PushClientAttrib(), _mesa_PushMatrix(), _mesa_PushName(), _mesa_QueryCounter(), _mesa_ReadBuffer(), _mesa_ReadnPixelsARB(), _mesa_RenderMode(), _mesa_ResetHistogram(), _mesa_ResetMinmax(), _mesa_resize_framebuffer(), _mesa_ResumeTransformFeedback(), _mesa_SampleMapATI(), _mesa_SampleMaski(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), _mesa_Scissor(), _mesa_SelectBuffer(), _mesa_SeparableFilter2D(), _mesa_set_enable(), _mesa_set_enablei(), _mesa_set_viewport(), _mesa_SetFragmentShaderConstantATI(), _mesa_ShadeModel(), _mesa_ShaderBinary(), _mesa_ShaderSource(), _mesa_StencilFunc(), _mesa_StencilFuncSeparate(), _mesa_StencilFuncSeparateATI(), _mesa_StencilMaskSeparate(), _mesa_StencilOp(), _mesa_StencilOpSeparate(), _mesa_store_compressed_teximage(), _mesa_store_compressed_texsubimage(), _mesa_store_teximage(), _mesa_TexBuffer(), _mesa_TexBufferRange(), _mesa_TexBumpParameterfvATI(), _mesa_TexBumpParameterivATI(), _mesa_TexEnvfv(), _mesa_TexEnvx(), _mesa_TexEnvxv(), _mesa_TexGenfv(), _mesa_TexParameterxv(), _mesa_TransformFeedbackVaryings(), _mesa_UniformBlockBinding(), _mesa_UnlockArraysEXT(), _mesa_UnmapBuffer(), _mesa_unpack_color_span_float(), _mesa_unpack_color_span_ubyte(), _mesa_unpack_color_span_uint(), _mesa_unpack_depth_span(), _mesa_unpack_dudv_span_byte(), _mesa_unpack_index_span(), _mesa_unpack_stencil_span(), _mesa_update_texture_renderbuffer(), _mesa_UseProgram(), _mesa_UseShaderProgramEXT(), _mesa_valid_prim_mode(), _mesa_valid_to_render(), _mesa_validate_DrawArrays(), _mesa_validate_DrawArraysInstanced(), _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), _mesa_validate_DrawTransformFeedback(), _mesa_validate_MultiDrawElements(), _mesa_validate_pbo_compressed_teximage(), _mesa_validate_pbo_teximage(), _mesa_VertexAttribDivisor(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_WaitSync(), accum_or_load(), accum_return(), accum_scale_or_bias(), attach_shader(), bind_buffer_base_uniform_buffer(), bind_buffer_object(), bind_buffer_range_uniform_buffer(), bind_vertex_array(), buffer_object_purgeable(), buffer_object_subdata_range_good(), buffer_object_unpurgeable(), check_arith_arg(), check_extra(), clear_texture_fields(), client_state(), compressed_subtexture_error_check(), compressed_texture_error_check(), copy_data(), copyteximage(), copytexsubimage_error_check(), copytexture_error_check(), create_shader(), detach_shader(), dlist_alloc(), draw_texture(), emit_op3fn(), error_check_subtexture_dimensions(), execute_list(), fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), find_value(), find_value_indexed(), framebuffer_texture(), fxt1_encode(), gen_vertex_arrays(), generate_mipmap_compressed(), generate_mipmap_uncompressed(), get_buffer(), get_buffer_object_parameteriv(), get_current_attrib(), get_env_param_pointer(), get_handle(), get_local_param_pointer(), get_program_info_log(), get_programiv(), get_proxy_tex_image(), get_renderbuffer_parameteriv(), get_shader_info_log(), get_shaderiv(), get_tex_depth(), get_tex_depth_stencil(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), get_tex_memcpy(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), get_tex_ycbcr(), get_texcoord_unit(), get_texenvi(), get_texobj(), get_texture_object_parameteriv(), get_vertex_array_attrib(), getcompressedteximage_error_check(), getteximage_error_check(), handle_bind_buffer_gen(), index_error(), initialize_texture_fields(), invalidate_framebuffer_storage(), invalidate_tex_image_error_check(), link_program(), map1(), map2(), query_error_check_index(), read_depth_pixels(), read_rgba_pixels_swizzle(), read_stencil_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), renderbuffer_purgeable(), renderbuffer_storage(), renderbuffer_unpurgeable(), save_DrawArraysInstancedARB(), save_DrawArraysInstancedBaseInstance(), save_DrawElementsInstancedARB(), save_DrawElementsInstancedBaseInstance(), save_DrawElementsInstancedBaseVertexARB(), save_DrawElementsInstancedBaseVertexBaseInstance(), save_NewList(), save_ProgramStringARB(), set_combiner_scale(), set_tex_parameterf(), set_tex_parameteri(), shading_language_version(), slow_read_depth_stencil_pixels_separate(), slow_read_rgba_pixels(), store_pixelmap(), store_texsubimage(), tex_storage_error_check(), texbufferrange(), teximage(), teximagemultisample(), texstorage(), texsubimage(), texsubimage_error_check(), texture_error_check(), texture_object_purgeable(), texture_object_unpurgeable(), unpack_image(), update_array(), valid_elements_type(), validate_blend_factors(), validate_params(), validate_pbo_access(), and validate_texture_wrap_mode().
void _mesa_free_errors_data (struct gl_context * ctx)
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), gl_context::Debug, do_nothing(), foreach_s, gl_debug_namespace::IDs, MESA_DEBUG_SEVERITY_COUNT, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, gl_debug_state::Namespaces, NULL, and gl_debug_namespace::Severity.
Referenced by _mesa_free_context_data().
static GLsizei _mesa_get_msg (struct gl_context * ctx, GLenum * source, GLenum * type, GLuint * id, GLenum * severity, GLsizei bufSize, char * buf) static
Pop the oldest debug message out of the log.
Writes the message string, including the null terminator, into 'buf', using up to 'bufSize' bytes. If 'bufSize' is too small, or if 'buf' is NULL, nothing is written.
Returns the number of bytes written on success, or when 'buf' is NULL, the number that would have been written. A return value of 0 indicates failure.
References gl_context::Debug, debug_severity_enums, debug_source_enums, debug_type_enums, gl_debug_msg::id, gl_debug_msg::length, gl_debug_state::Log, MAX_DEBUG_LOGGED_MESSAGES, gl_debug_msg::message, gl_debug_state::NextMsg, gl_debug_state::NextMsgLength, NULL, gl_debug_state::NumMessages, out_of_memory, gl_debug_msg::severity, gl_debug_msg::source, gl_debug_msg::type, and void().
Referenced by _mesa_GetDebugMessageLogARB().
GLuint GLAPIENTRY _mesa_GetDebugMessageLogARB (GLuint count, GLsizei logSize, GLenum * sources, GLenum * types, GLenum * ids, GLenum * severities, GLsizei * lengths, GLcharARB * messageLog)
References _mesa_error(), and _mesa_get_msg().
Referenced by _mesa_initialize_exec_table().
void _mesa_gl_debug (struct gl_context * ctx, GLuint * id, enum mesa_debug_type type, enum mesa_debug_severity severity, const char * fmtString, ...)
References _mesa_log_msg(), _mesa_vsnprintf(), debug_get_id(), MAX_DEBUG_MESSAGE_LENGTH, and MESA_DEBUG_SOURCE_API.
void _mesa_init_errors (struct gl_context * ctx)
References _mesa_NewHashTable(), gl_debug_state::Callback, gl_context::Debug, gl_debug_state::Defaults, gl_debug_namespace::IDs, gl_debug_msg::length, gl_debug_state::Log, make_empty_list, MESA_DEBUG_SEVERITY_COUNT, MESA_DEBUG_SEVERITY_HIGH, MESA_DEBUG_SEVERITY_LOW, MESA_DEBUG_SEVERITY_MEDIUM, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, gl_debug_state::Namespaces, gl_debug_state::NextMsg, gl_debug_state::NextMsgLength, NULL, gl_debug_state::NumMessages, gl_debug_namespace::Severity, and gl_debug_state::SyncOutput.
Referenced by init_attrib_groups().
static void _mesa_log_msg (struct gl_context * ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity, GLint len, const char * buf) static
'buf' is not necessarily a null-terminated string.
When logging, copy 'len' characters from it, store them in a new, null-terminated string, and remember the number of bytes used by that string, including the null terminator this time.
References gl_debug_state::Callback, gl_debug_state::CallbackData, gl_context::Debug, debug_get_id(), debug_severity_enums, debug_source_enums, debug_type_enums, gl_debug_msg::id, gl_debug_msg::length, gl_debug_state::Log, MAX_DEBUG_LOGGED_MESSAGES, MAX_DEBUG_MESSAGE_LENGTH, MESA_DEBUG_SEVERITY_HIGH, MESA_DEBUG_SOURCE_OTHER, MESA_DEBUG_TYPE_ERROR, gl_debug_msg::message, gl_debug_state::NextMsg, gl_debug_state::NextMsgLength, gl_debug_state::NumMessages, out_of_memory, gl_debug_msg::severity, should_log(), gl_debug_msg::source, gl_debug_msg::type, and void().
Referenced by _mesa_DebugMessageInsertARB(), _mesa_error(), _mesa_gl_debug(), and _mesa_shader_debug().
void _mesa_problem (const struct gl_context * ctx, const char * fmtString, ...)
Report an internal implementation problem.
Prints the message to stderr via fprintf().
Parameters
ctx GL context.
fmtString problem description string.
References _mesa_vsnprintf(), MAX_DEBUG_MESSAGE_LENGTH, and void().
Referenced by _mesa_accum(), _mesa_check_conditional_render(), _mesa_choose_tex_format(), _mesa_compressed_format_to_glenum(), _mesa_convert_colors(), _mesa_decompress_image(), _mesa_DeleteHashTable(), _mesa_DeleteProgramsARB(), _mesa_disable_extension(), _mesa_dump_image(), _mesa_enable_extension(), _mesa_generate_mipmap_level(), _mesa_get_format_bits(), _mesa_get_pack_float_z_func(), _mesa_get_pack_ubyte_stencil_func(), _mesa_get_pack_uint_z_func(), _mesa_get_proxy_target(), _mesa_get_texture_dimensions(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetQueryIndexediv(), _mesa_HashRemove(), _mesa_init_teximage_fields(), _mesa_legal_texture_dimensions(), _mesa_light(), _mesa_map_function_array(), _mesa_pack_colormask(), _mesa_pack_depth_span(), _mesa_pack_float_z_row(), _mesa_pack_index_span(), _mesa_pack_rgba_span_float(), _mesa_pack_stencil_span(), _mesa_pack_ubyte_stencil_row(), _mesa_pack_uint_24_8_depth_stencil_row(), _mesa_pack_uint_z_row(), _mesa_PopAttrib(), _mesa_PopClientAttrib(), _mesa_print_texture(), _mesa_reference_array_object_(), _mesa_reference_buffer_object_(), _mesa_reference_sampler_object_(), _mesa_reference_texobj_(), _mesa_select_tex_object(), _mesa_store_compressed_teximage(), _mesa_store_compressed_texsubimage(), _mesa_test_texobj_completeness(), _mesa_texstore_null(), _mesa_unpack_depth_span(), _mesa_unpack_float_z_row(), _mesa_unpack_index_span(), _mesa_unpack_stencil_span(), _mesa_unpack_ubyte_stencil_row(), _mesa_unpack_uint_24_8_depth_stencil_row(), _mesa_unpack_uint_rgba_row(), _mesa_unpack_uint_z_row(), _pack_rgba_span_from_ints_problem(), _pack_rgba_span_from_uints_problem(), calculate_derived_texenv(), compute_version_es1(), compute_version_es2(), do_row(), do_row_3D(), execute_list(), extract_float_rgba(), extract_uint_indexes(), extract_uint_rgba(), find_custom_value(), FN_NAME(), get_component_mapping(), get_map_idx(), get_temp(), get_unpack_rgba_function(), legal_teximage_target(), legal_texobj_target(), legal_texsubimage_target(), reference_transform_feedback_object(), renderbuffer_exists(), set_extension(), shading_language_version(), update_tex_combine(), and valid_texture_object().
void _mesa_shader_debug (struct gl_context * ctx, GLenum type, GLuint * id, const char * msg, int len)
Report debug information from the shader compiler via GL_ARB_debug_output.
Parameters
ctx GL context.
type The namespace to which this message belongs.
id The message ID within the given namespace.
msg The message to output. Need not be null-terminated.
len The length of 'msg'. If negative, 'msg' must be null-terminated.
References _mesa_log_msg(), debug_get_id(), MAX_DEBUG_MESSAGE_LENGTH, MESA_DEBUG_SEVERITY_HIGH, and MESA_DEBUG_SOURCE_SHADER_COMPILER.
void _mesa_warning (struct gl_context * ctx, const char * fmtString, ...)
Report a warning (a recoverable error condition) to stderr if either DEBUG is defined or the MESA_DEBUG env var is set.
Parameters
ctx GL context.
fmtString printf()-like format string.
References _mesa_vsnprintf(), flush_delayed_errors(), MAX_DEBUG_MESSAGE_LENGTH, output_if_debug(), and void().
Referenced by _mesa_accum(), _mesa_base_format_has_channel(), _mesa_choose_texture_format(), _mesa_clear_accum_buffer(), _mesa_do_init_remap_table(), _mesa_GetInternalformativ(), _mesa_init_texture_s3tc(), _mesa_make_current(), _mesa_map_function_array(), _mesa_RenderMode(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_UnmapBuffer(), _mesa_valid_to_render(), _mesa_validate_DrawElements(), _mesa_validate_DrawElementsInstanced(), _mesa_validate_DrawRangeElements(), _mesa_validate_MultiDrawElements(), check_index_bounds(), and store_texsubimage().
static void control_app_messages (struct gl_context * ctx, GLenum esource, GLenum etype, GLenum eseverity, GLsizei count, const GLuint * ids, GLboolean enabled) static
Debugging-message namespaces with the source APPLICATION or THIRD_PARTY require special handling, since the IDs in them are controlled by clients, not the OpenGL implementation.
'count' is the length of the array 'ids'. If 'count' is nonzero, all the given IDs in the namespace defined by 'esource' and 'etype' will be affected.
If 'count' is zero, this sets the state of all IDs that match the combination of 'esource', 'etype', and 'eseverity'.
References control_messages(), gl_enum_to_debug_severity(), gl_enum_to_debug_source(), gl_enum_to_debug_type(), MESA_DEBUG_SEVERITY_COUNT, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, and set_message_state().
Referenced by _mesa_DebugMessageControlARB().
static void control_messages (struct gl_context * ctx, enum mesa_debug_source source, enum mesa_debug_type type, enum mesa_debug_severity severity, GLboolean enabled) static
Set the state of all message IDs found in the given intersection of 'source', 'type', and 'severity'.
The _COUNT enum can be used for GL_DONT_CARE (include all messages in the class).
This requires both setting the state of all previously seen message IDs in the hash table, and setting the default state for all applicable combinations of source/type/severity, so that all the yet-unknown message IDs that may be used in the future will be impacted as if they were already known.
References gl_context::Debug, gl_debug_state::Defaults, gl_debug_severity::ID, MESA_DEBUG_SEVERITY_COUNT, MESA_DEBUG_SOURCE_COUNT, MESA_DEBUG_TYPE_COUNT, gl_debug_state::Namespaces, set_message_state(), and gl_debug_namespace::Severity.
Referenced by control_app_messages().
static void debug_get_id (GLuint * id) static
Handles generating a GL_ARB_debug_output message ID generated by the GL or GLSL compiler.
The GL API has this "ID" mechanism, where the intention is to allow a client to filter in/out messages based on source, type, and ID. Of course, building a giant enum list of all debug output messages that Mesa might generate is ridiculous, so instead we have our caller pass us a pointer to static storage where the ID should get stored. This ID will be shared across all contexts for that message (which seems like a desirable property, even if it's not expected by the spec), but note that it won't be the same between executions if messages aren't generated in the same order.
References NextDynamicID.
Referenced by _mesa_error(), _mesa_gl_debug(), _mesa_log_msg(), and _mesa_shader_debug().
static void do_nothing (GLuint key, void * data, void * userData) static
Referenced by _mesa_free_errors_data().
static void flush_delayed_errors (struct gl_context * ctx) static
When a new type of error is recorded, print a message describing previous errors which were accumulated.
References _mesa_lookup_enum_by_nr(), _mesa_snprintf(), gl_context::ErrorDebugCount, gl_context::ErrorValue, MAX_DEBUG_MESSAGE_LENGTH, and output_if_debug().
Referenced by _mesa_warning(), and should_output().
static enum mesa_debug_severity gl_enum_to_debug_severity (GLenum e) static
References debug_severity_enums, and Elements.
Referenced by _mesa_DebugMessageControlARB(), _mesa_DebugMessageInsertARB(), and control_app_messages().
static enum mesa_debug_source gl_enum_to_debug_source (GLenum e) static
References debug_source_enums, and Elements.
Referenced by _mesa_DebugMessageControlARB(), _mesa_DebugMessageInsertARB(), and control_app_messages().
static enum mesa_debug_type gl_enum_to_debug_type (GLenum e) static
References debug_type_enums, and Elements.
Referenced by _mesa_DebugMessageControlARB(), _mesa_DebugMessageInsertARB(), and control_app_messages().
static void output_if_debug (const char * prefixString, const char * outputString, GLboolean newline) static
References _mesa_getenv(), _mesa_snprintf(), DEBUG_SILENT, MESA_DEBUG_FLAGS, and NULL.
Referenced by _mesa_debug(), _mesa_error(), _mesa_warning(), and flush_delayed_errors().
static void set_message_state (struct gl_context * ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, GLboolean enabled) static
Sets the state of the given message source/type/ID tuple.
References _mesa_HashInsert(), _mesa_HashLookup(), gl_context::Debug, DISABLED, ENABLED, ENABLED_BIT, gl_debug_namespace::IDs, gl_debug_state::Namespaces, NOT_FOUND, and gl_debug_namespace::ZeroID.
Referenced by control_app_messages(), and control_messages().
static GLboolean should_log (struct gl_context * ctx, enum mesa_debug_source source, enum mesa_debug_type type, GLuint id, enum mesa_debug_severity severity) static
Returns the state of the given message source/type/ID tuple.
References _mesa_HashInsert(), _mesa_HashLookup(), gl_context::Debug, gl_debug_state::Defaults, DISABLED, ENABLED, ENABLED_BIT, gl_debug_severity::ID, gl_debug_namespace::IDs, insert_at_tail, KNOWN_SEVERITY, gl_debug_severity::link, gl_debug_state::Namespaces, NOT_FOUND, gl_debug_namespace::Severity, and gl_debug_namespace::ZeroID.
Referenced by _mesa_error(), and _mesa_log_msg().
static GLboolean should_output (struct gl_context * ctx, GLenum error, const char * fmtString) static
References _mesa_getenv(), gl_context::ErrorDebugCount, gl_context::ErrorDebugFmtString, gl_context::ErrorValue, and flush_delayed_errors().
Referenced by _mesa_error().
static GLboolean validate_params (struct gl_context * ctx, unsigned caller, GLenum source, GLenum type, GLenum severity) static
Verify that source, type, and severity are valid enums.
glDebugMessageInsertARB only accepts two values for 'source', and glDebugMessageControlARB will additionally accept GL_DONT_CARE in any parameter, so handle those cases specially.
References _mesa_error(), CONTROL, and INSERT.
Referenced by _mesa_DebugMessageControlARB(), and _mesa_DebugMessageInsertARB().
Variable Documentation
const GLenum debug_severity_enums[] static
Initial value:
= {
   GL_DEBUG_SEVERITY_LOW,
   GL_DEBUG_SEVERITY_MEDIUM,
   GL_DEBUG_SEVERITY_HIGH,
}
Referenced by _mesa_get_msg(), _mesa_log_msg(), and gl_enum_to_debug_severity().
const GLenum debug_source_enums[] static
Initial value:
= {
   GL_DEBUG_SOURCE_API,
   GL_DEBUG_SOURCE_WINDOW_SYSTEM,
   GL_DEBUG_SOURCE_SHADER_COMPILER,
   GL_DEBUG_SOURCE_THIRD_PARTY,
   GL_DEBUG_SOURCE_APPLICATION,
   GL_DEBUG_SOURCE_OTHER,
}
Referenced by _mesa_get_msg(), _mesa_log_msg(), and gl_enum_to_debug_source().
const GLenum debug_type_enums[] static
Initial value:
= {
   GL_DEBUG_TYPE_ERROR,
   GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR,
   GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR,
   GL_DEBUG_TYPE_PORTABILITY,
   GL_DEBUG_TYPE_PERFORMANCE,
   GL_DEBUG_TYPE_OTHER,
}
Referenced by _mesa_get_msg(), _mesa_log_msg(), and gl_enum_to_debug_type().
GLuint NextDynamicID = 1 static
Referenced by debug_get_id().
char out_of_memory[] = "Debugging error: out of memory" static
Referenced by _mesa_get_msg(), and _mesa_log_msg().