Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
es1_conversion.c File Reference
#include <stdbool.h>
#include "api_loopback.h"
#include "api_exec.h"
#include "blend.h"
#include "clear.h"
#include "clip.h"
#include "context.h"
#include "depth.h"
#include "fog.h"
#include "imports.h"
#include "light.h"
#include "lines.h"
#include "matrix.h"
#include "multisample.h"
#include "pixelstore.h"
#include "points.h"
#include "polygon.h"
#include "readpix.h"
#include "texenv.h"
#include "texgen.h"
#include "texobj.h"
#include "texparam.h"
#include "mtypes.h"
#include "viewport.h"
#include "main/drawtex.h"
#include "vbo/vbo.h"
#include "main/es1_conversion.h"
Functions
void GL_APIENTRY _mesa_AlphaFuncx (GLenum func, GLclampx ref)
void GL_APIENTRY _mesa_ClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
void GL_APIENTRY _mesa_ClearDepthx (GLclampx depth)
void GL_APIENTRY _mesa_ClipPlanef (GLenum plane, const GLfloat *equation)
void GL_APIENTRY _mesa_ClipPlanex (GLenum plane, const GLfixed *equation)
void GL_APIENTRY _es_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
void GL_APIENTRY _mesa_Color4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
void GL_APIENTRY _mesa_DepthRangex (GLclampx zNear, GLclampx zFar)
void GL_APIENTRY _mesa_DrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed w, GLfixed h)
void GL_APIENTRY _mesa_DrawTexxvOES (const GLfixed *coords)
void GL_APIENTRY _mesa_Fogx (GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_Fogxv (GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_Frustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
void GL_APIENTRY _mesa_Frustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
void GL_APIENTRY _mesa_GetClipPlanef (GLenum plane, GLfloat *equation)
void GL_APIENTRY _mesa_GetClipPlanex (GLenum plane, GLfixed *equation)
void GL_APIENTRY _mesa_GetLightxv (GLenum light, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_GetMaterialxv (GLenum face, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_GetTexEnvxv (GLenum target, GLenum pname, GLfixed *params)
void GL_APIENTRY _check_GetTexGenivOES (GLenum coord, GLenum pname, GLint *params)
void GL_APIENTRY _mesa_GetTexGenxvOES (GLenum coord, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_GetTexParameterxv (GLenum target, GLenum pname, GLfixed *params)
void GL_APIENTRY _mesa_LightModelx (GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_LightModelxv (GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_Lightx (GLenum light, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_Lightxv (GLenum light, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_LineWidthx (GLfixed width)
void GL_APIENTRY _mesa_LoadMatrixx (const GLfixed *m)
void GL_APIENTRY _mesa_Materialx (GLenum face, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_Materialxv (GLenum face, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_MultMatrixx (const GLfixed *m)
void GL_APIENTRY _mesa_MultiTexCoord4x (GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
void GL_APIENTRY _mesa_Normal3x (GLfixed nx, GLfixed ny, GLfixed nz)
void GL_APIENTRY _mesa_Orthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
void GL_APIENTRY _mesa_Orthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
void GL_APIENTRY _mesa_PointParameterx (GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_PointParameterxv (GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_PointSizex (GLfixed size)
void GL_APIENTRY _mesa_PolygonOffsetx (GLfixed factor, GLfixed units)
void GL_APIENTRY _mesa_Rotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
void GL_APIENTRY _mesa_SampleCoveragex (GLclampx value, GLboolean invert)
void GL_APIENTRY _mesa_Scalex (GLfixed x, GLfixed y, GLfixed z)
void GL_APIENTRY _mesa_TexEnvx (GLenum target, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_TexEnvxv (GLenum target, GLenum pname, const GLfixed *params)
void GL_APIENTRY _check_TexGeniOES (GLenum coord, GLenum pname, GLint param)
void GL_APIENTRY _check_TexGenivOES (GLenum coord, GLenum pname, const GLint *params)
void GL_APIENTRY _mesa_TexGenxOES (GLenum coord, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_TexGenxvOES (GLenum coord, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_TexParameterx (GLenum target, GLenum pname, GLfixed param)
void GL_APIENTRY _mesa_TexParameterxv (GLenum target, GLenum pname, const GLfixed *params)
void GL_APIENTRY _mesa_Translatex (GLfixed x, GLfixed y, GLfixed z)
Function Documentation
void GL_APIENTRY _check_GetTexGenivOES (GLenum coord, GLenum pname, GLint * params)
References _mesa_GetTexGeniv().
void GL_APIENTRY _check_TexGeniOES (GLenum coord, GLenum pname, GLint param)
References _es_TexGenf().
void GL_APIENTRY _check_TexGenivOES (GLenum coord, GLenum pname, const GLint * params)
References _es_TexGenf().
void GL_APIENTRY _es_Color4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
References _es_Color4f().
void GL_APIENTRY _mesa_AlphaFuncx (GLenum func, GLclampx ref)
References _mesa_AlphaFunc(), and GLclampf.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_ClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
References _mesa_ClearColor(), and GLclampf.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_ClearDepthx (GLclampx depth)
References _mesa_ClearDepthf(), and GLclampf.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_ClipPlanef (GLenum plane, const GLfloat * equation)
References _mesa_ClipPlane(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_ClipPlanex (GLenum plane, const GLfixed * equation)
References _mesa_ClipPlane(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Color4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
References _es_Color4f().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_DepthRangex (GLclampx zNear, GLclampx zFar)
References _mesa_DepthRangef(), and GLclampf.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_DrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed w, GLfixed h)
References _mesa_DrawTexfOES().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_DrawTexxvOES (const GLfixed * coords)
References _mesa_DrawTexfvOES(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Fogx (GLenum pname, GLfixed param)
References _mesa_Fogf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Fogxv (GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_Fogfv(), and _mesa_get_current_context().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Frustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
References _mesa_Frustum().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Frustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
References _mesa_Frustum().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_GetClipPlanef (GLenum plane, GLfloat * equation)
References _mesa_GetClipPlane(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_GetClipPlanex (GLenum plane, GLfixed * equation)
References _mesa_GetClipPlane(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_GetLightxv (GLenum light, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), and _mesa_GetLightfv().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_GetMaterialxv (GLenum face, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), and _mesa_GetMaterialfv().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_GetTexEnvxv (GLenum target, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), and _mesa_GetTexEnvfv().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_GetTexGenxvOES (GLenum coord, GLenum pname, GLfixed * params)
References _mesa_GetTexGeniv().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_GetTexParameterxv (GLenum target, GLenum pname, GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_GetTexParameterfv(), GL_TEXTURE_CROP_RECT_OES, and GL_TEXTURE_EXTERNAL_OES.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_LightModelx (GLenum pname, GLfixed param)
References _mesa_LightModelf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_LightModelxv (GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), and _mesa_LightModelfv().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Lightx (GLenum light, GLenum pname, GLfixed param)
References _mesa_Lightf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Lightxv (GLenum light, GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), and _mesa_Lightfv().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_LineWidthx (GLfixed width)
References _mesa_LineWidth().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_LoadMatrixx (const GLfixed * m)
References _mesa_LoadMatrixf(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Materialx (GLenum face, GLenum pname, GLfixed param)
References _es_Materialf(), _mesa_error(), and _mesa_get_current_context().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Materialxv (GLenum face, GLenum pname, const GLfixed * params)
References _es_Materialfv(), _mesa_error(), and _mesa_get_current_context().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_MultiTexCoord4x (GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
References _es_MultiTexCoord4f().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_MultMatrixx (const GLfixed * m)
References _mesa_MultMatrixf(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Normal3x (GLfixed nx, GLfixed ny, GLfixed nz)
References _es_Normal3f().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Orthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
References _mesa_Ortho().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Orthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
References _mesa_Ortho().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_PointParameterx (GLenum pname, GLfixed param)
References _mesa_PointParameterf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_PointParameterxv (GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), and _mesa_PointParameterfv().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_PointSizex (GLfixed size)
References _mesa_PointSize().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_PolygonOffsetx (GLfixed factor, GLfixed units)
References _mesa_PolygonOffset().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Rotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
References _mesa_Rotatef().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_SampleCoveragex (GLclampx value, GLboolean invert)
References _mesa_SampleCoverage(), and GLclampf.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Scalex (GLfixed x, GLfixed y, GLfixed z)
References _mesa_Scalef().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_TexEnvx (GLenum target, GLenum pname, GLfixed param)
References _mesa_error(), _mesa_get_current_context(), and _mesa_TexEnvf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_TexEnvxv (GLenum target, GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_TexEnvf(), _mesa_TexEnvfv(), and Elements.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_TexGenxOES (GLenum coord, GLenum pname, GLfixed param)
References _es_TexGenf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_TexGenxvOES (GLenum coord, GLenum pname, const GLfixed * params)
References _es_TexGenf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_TexParameterx (GLenum target, GLenum pname, GLfixed param)
References _mesa_TexParameterf().
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_TexParameterxv (GLenum target, GLenum pname, const GLfixed * params)
References _mesa_error(), _mesa_get_current_context(), _mesa_TexParameterfv(), GL_TEXTURE_CROP_RECT_OES, and GL_TEXTURE_EXTERNAL_OES.
Referenced by _mesa_initialize_exec_table().
void GL_APIENTRY _mesa_Translatex (GLfixed x, GLfixed y, GLfixed z)
References _mesa_Translatef().
Referenced by _mesa_initialize_exec_table().