Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
extensions.c File Reference
Extension handling.
#include "glheader.h"
#include "imports.h"
#include "context.h"
#include "extensions.h"
#include "macros.h"
#include "mtypes.h"
Data Structures
struct extension
An element of the extension_table.
Macros
#define o(x) offsetof(struct gl_extensions, x)
Given a member x of struct gl_extensions, return offset of x in bytes.
Typedefs
typedef unsigned short extension_index
Enumerations
enum {
DISABLE = 0, GLL = 1 << API_OPENGL_COMPAT, GLC = 1 << API_OPENGL_CORE, GL = (1 << API_OPENGL_COMPAT) | (1 << API_OPENGL_CORE),
ES1 = 1 << API_OPENGLES, ES2 = 1 << API_OPENGLES2, ES3 = 1 << (API_OPENGL_LAST + 1)
}
Functions
static size_t name_to_offset (const char *name)
Given an extension name, lookup up the corresponding member of struct gl_extensions and return that member's offset (in bytes).
void _mesa_enable_sw_extensions (struct gl_context *ctx)
Enable all extensions suitable for a software-only renderer.
void _mesa_enable_1_3_extensions (struct gl_context *ctx)
Enable all OpenGL 1.3 features and extensions.
void _mesa_enable_1_4_extensions (struct gl_context *ctx)
Enable all OpenGL 1.4 features and extensions.
void _mesa_enable_1_5_extensions (struct gl_context *ctx)
Enable all OpenGL 1.5 features and extensions.
void _mesa_enable_2_0_extensions (struct gl_context *ctx)
Enable all OpenGL 2.0 features and extensions.
void _mesa_enable_2_1_extensions (struct gl_context *ctx)
Enable all OpenGL 2.1 features and extensions.
static GLboolean set_extension (struct gl_context *ctx, const char *name, GLboolean state)
Either enable or disable the named extension.
void _mesa_enable_extension (struct gl_context *ctx, const char *name)
Enable the named extension.
void _mesa_disable_extension (struct gl_context *ctx, const char *name)
Disable the named extension.
GLboolean _mesa_extension_is_enabled (struct gl_context *ctx, const char *name)
Test if the named extension is enabled in this context.
static char * get_extension_override (struct gl_context *ctx)
Apply the MESA_EXTENSION_OVERRIDE environment variable.
void _mesa_init_extensions (struct gl_context *ctx)
Initialize extension tables and enable default extensions.
static int extension_compare (const void *p1, const void *p2)
Compare two entries of the extensions table.
GLubyte * _mesa_make_extension_string (struct gl_context *ctx)
Construct the GL_EXTENSIONS string.
GLuint _mesa_get_extension_count (struct gl_context *ctx)
Return number of enabled extensions.
const GLubyte * _mesa_get_enabled_extension (struct gl_context *ctx, GLuint index)
Return name of i-th enabled extension.
Variables
static struct extension extension_table []
Table of supported OpenGL extensions for all API's.
Detailed Description
Extension handling.
Macro Definition Documentation
#define o (x) offsetof(struct gl_extensions, x)
Given a member x of struct gl_extensions, return offset of x in bytes.
Referenced by _mesa_init_extensions(), and set_extension().
Typedef Documentation
typedef unsigned short extension_index
Enumeration Type Documentation
anonymous enum
Enumerator
DISABLE
GLL
GLC
GL
ES1
ES2
ES3
Function Documentation
void _mesa_disable_extension (struct gl_context * ctx, const char * name)
Disable the named extension.
XXX is this really needed???
References _mesa_problem(), and set_extension().
void _mesa_enable_1_3_extensions (struct gl_context * ctx)
Enable all OpenGL 1.3 features and extensions.
A convenience function to be called by drivers.
References gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_dot3, and gl_context::Extensions.
void _mesa_enable_1_4_extensions (struct gl_context * ctx)
Enable all OpenGL 1.4 features and extensions.
A convenience function to be called by drivers.
References gl_extensions::ARB_depth_texture, gl_extensions::ARB_shadow, gl_extensions::ARB_texture_env_crossbar, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_fog_coord, gl_extensions::EXT_point_parameters, gl_extensions::EXT_secondary_color, and gl_context::Extensions.
void _mesa_enable_1_5_extensions (struct gl_context * ctx)
Enable all OpenGL 1.5 features and extensions.
A convenience function to be called by drivers.
References gl_extensions::ARB_occlusion_query, gl_extensions::EXT_shadow_funcs, and gl_context::Extensions.
void _mesa_enable_2_0_extensions (struct gl_context * ctx)
Enable all OpenGL 2.0 features and extensions.
A convenience function to be called by drivers.
References gl_extensions::ARB_fragment_shader, gl_extensions::ARB_point_sprite, gl_extensions::ARB_shader_objects, gl_extensions::ARB_shading_language_100, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_vertex_shader, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_stencil_two_side, and gl_context::Extensions.
void _mesa_enable_2_1_extensions (struct gl_context * ctx)
Enable all OpenGL 2.1 features and extensions.
A convenience function to be called by drivers.
References gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_texture_sRGB, and gl_context::Extensions.
void _mesa_enable_extension (struct gl_context * ctx, const char * name)
Enable the named extension.
Typically called by drivers.
References _mesa_problem(), and set_extension().
Referenced by _mesa_enable_sw_extensions().
void _mesa_enable_sw_extensions (struct gl_context * ctx)
Enable all extensions suitable for a software-only renderer.
This is a convenience function used by the XMesa, OSMesa, GGI drivers, etc.
References _mesa_enable_extension(), gl_extensions::ANGLE_texture_compression_dxt, gl_extensions::APPLE_object_purgeable, gl_extensions::ARB_depth_clamp, gl_extensions::ARB_depth_texture, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_explicit_attrib_location, gl_extensions::ARB_fragment_coord_conventions, gl_extensions::ARB_fragment_program, gl_extensions::ARB_fragment_program_shadow, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_geometry_shader4, gl_extensions::ARB_half_float_pixel, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_point_sprite, gl_extensions::ARB_shader_objects, gl_extensions::ARB_shading_language_100, gl_extensions::ARB_shadow, gl_extensions::ARB_sync, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ARB_texture_env_dot3, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_storage, gl_extensions::ARB_vertex_program, gl_extensions::ARB_vertex_shader, gl_extensions::ATI_envmap_bumpmap, gl_extensions::ATI_fragment_shader, gl_extensions::ATI_separate_stencil, gl_extensions::ATI_texture_compression_3dc, gl_extensions::ATI_texture_env_combine3, gl_extensions::ATI_texture_mirror_once, gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_depth_bounds_test, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_fog_coord, gl_extensions::EXT_framebuffer_blit, gl_extensions::EXT_framebuffer_object, gl_extensions::EXT_gpu_program_parameters, gl_extensions::EXT_packed_depth_stencil, gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_point_parameters, gl_extensions::EXT_provoking_vertex, gl_extensions::EXT_secondary_color, gl_extensions::EXT_separate_shader_objects, gl_extensions::EXT_shadow_funcs, gl_extensions::EXT_stencil_two_side, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_compression_latc, gl_extensions::EXT_texture_env_dot3, gl_extensions::EXT_texture_filter_anisotropic, gl_extensions::EXT_texture_mirror_clamp, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_sRGB, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, gl_context::Mesa_DXTn, gl_extensions::MESA_pack_invert, gl_extensions::MESA_resize_buffers, gl_extensions::MESA_texture_array, gl_extensions::MESA_ycbcr_texture, gl_extensions::NV_blend_square, gl_extensions::NV_conditional_render, gl_extensions::NV_fragment_program_option, gl_extensions::NV_point_sprite, gl_extensions::NV_texture_env_combine4, gl_extensions::NV_texture_rectangle, and gl_extensions::OES_standard_derivatives.
GLboolean _mesa_extension_is_enabled (struct gl_context * ctx, const char * name)
Test if the named extension is enabled in this context.
References gl_context::Extensions, name_to_offset(), and extension::offset.
const GLubyte* _mesa_get_enabled_extension (struct gl_context * ctx, GLuint index)
Return name of i-th enabled extension.
References _mesa_is_gles3(), gl_context::API, extension::api_set, ES3, gl_context::Extensions, GLubyte, extension::name, NULL, and extension::offset.
Referenced by _mesa_GetStringi().
GLuint _mesa_get_extension_count (struct gl_context * ctx)
Return number of enabled extensions.
References _mesa_is_gles3(), gl_context::API, extension::api_set, gl_extensions::Count, ES3, gl_context::Extensions, extension::name, and extension::offset.
Referenced by _mesa_GetStringi(), and find_custom_value().
void _mesa_init_extensions (struct gl_context * ctx)
Initialize extension tables and enable default extensions.
This should be called during context initialization. Note: Sets gl_extensions.dummy_true to true.
References gl_extensions::dummy_true, gl_extensions::EXT_texture3D, gl_context::Extensions, and o.
Referenced by init_attrib_groups().
GLubyte* _mesa_make_extension_string (struct gl_context * ctx)
Construct the GL_EXTENSIONS string.
Called the first time that glGetString(GL_EXTENSIONS) is called.
References _mesa_debug(), _mesa_is_gles3(), ALIGN, gl_context::API, extension::api_set, ES3, extension_compare(), extension_table, gl_context::Extensions, get_extension_override(), GLubyte, extension::name, and NULL.
Referenced by _mesa_make_current().
static int extension_compare (const void * p1, const void * p2) static
Compare two entries of the extensions table.
Sorts first by year, then by name.
Arguments are indices into extension_table.
References extension::name, and extension::year.
Referenced by _mesa_make_extension_string().
static char* get_extension_override (struct gl_context * ctx) static
Apply the MESA_EXTENSION_OVERRIDE environment variable.
MESA_EXTENSION_OVERRIDE is a space-separated list of extensions to enable or disable. The list is processed thus:
Enable recognized extension names that are prefixed with '+'.
Disable recognized extension names that are prefixed with '-'.
Enable recognized extension names that are not prefixed.
Collect unrecognized extension names in a new string.
Returns
Space-separated list of unrecognized extension names (which must be freed). Does not return NULL.
References _mesa_getenv(), ALIGN, NULL, and set_extension().
Referenced by _mesa_make_extension_string().
static size_t name_to_offset (const char * name) static
Given an extension name, lookup up the corresponding member of struct gl_extensions and return that member's offset (in bytes).
If the name is not found in the extension_table, return 0.
Parameters
name Name of extension.
Returns
Offset of member in struct gl_extensions.
References extension::name, and extension::offset.
Referenced by _mesa_extension_is_enabled(), and set_extension().
static GLboolean set_extension (struct gl_context * ctx, const char * name, GLboolean state) static
Either enable or disable the named extension.
Returns
GL_TRUE for success, GL_FALSE if invalid extension name
References _mesa_problem(), gl_context::Extensions, name_to_offset(), o, extension::offset, and gl_extensions::String.
Referenced by _mesa_disable_extension(), _mesa_enable_extension(), and get_extension_override().
Variable Documentation
struct extension extension_table[] static
Table of supported OpenGL extensions for all API's.
Referenced by _mesa_make_extension_string().