Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
fbobject.h File Reference
#include "compiler.h"
#include "glheader.h"
Functions
static GLboolean _mesa_is_user_fbo (const struct gl_framebuffer *fb)
Is the given FBO a user-created FBO?
static GLboolean _mesa_is_winsys_fbo (const struct gl_framebuffer *fb)
Is the given FBO a window system FBO (like an X window)?
void _mesa_init_fbobjects (struct gl_context *ctx)
struct gl_framebuffer * _mesa_get_incomplete_framebuffer (void)
struct gl_renderbuffer * _mesa_lookup_renderbuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_renderbuffer.
struct gl_framebuffer * _mesa_lookup_framebuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_framebuffer.
struct gl_renderbuffer_attachment * _mesa_get_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment)
Given a GL_*_ATTACHMENTn token, return a pointer to the corresponding gl_renderbuffer_attachment object.
void _mesa_remove_attachment (struct gl_context *ctx, struct gl_renderbuffer_attachment *att)
Remove any texture or renderbuffer attached to the given attachment point.
void _mesa_set_texture_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att, struct gl_texture_object *texObj, GLenum texTarget, GLuint level, GLuint zoffset, GLboolean layered)
Bind a texture object to an attachment point.
void _mesa_set_renderbuffer_attachment (struct gl_context *ctx, struct gl_renderbuffer_attachment *att, struct gl_renderbuffer *rb)
Bind a renderbuffer to an attachment point.
void _mesa_update_texture_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
void _mesa_framebuffer_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
void _mesa_validate_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer *fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
void _mesa_test_framebuffer_completeness (struct gl_context *ctx, struct gl_framebuffer *fb)
Test if the given framebuffer object is complete and update its Status field with the results.
GLboolean _mesa_is_legal_color_format (const struct gl_context *ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
GLenum _mesa_base_fbo_format (struct gl_context *ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint *renderbuffers)
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint *framebuffers)
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset)
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GenerateMipmap (GLenum target)
void GLAPIENTRY _mesa_BlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Blit rectangular region, optionally from one framebuffer to another.
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments)
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments)
Function Documentation
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
References renderbuffer_storage().
GLenum _mesa_base_fbo_format (struct gl_context * ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
This is similar to _mesa_base_tex_format() but the set of valid internal formats is different.
Note that even if a format is determined to be legal here, validation of the FBO may fail if the format is not supported by the driver/GPU.
Parameters
internalFormat as passed to glRenderbufferStorage()
Returns
the base internal format, or 0 if internalFormat is illegal
References _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::EXT_packed_depth_stencil, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_context::Extensions, and gl_context::Version.
Referenced by _mesa_GetInternalformativ(), is_renderable_texture_format(), and renderbuffer_storage().
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
References _mesa_error(), _mesa_HashInsert(), _mesa_is_desktop_gl(), _mesa_lookup_framebuffer(), _mesa_reference_framebuffer(), _NEW_BUFFERS, ASSERT, check_begin_texture_render(), check_end_texture_render(), DummyFramebuffer, FLUSH_VERTICES, and NULL.
Referenced by _mesa_DeleteFramebuffers(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
References _mesa_error(), _mesa_HashInsert(), _mesa_is_desktop_gl(), _mesa_lookup_renderbuffer(), _mesa_reference_renderbuffer(), gl_renderbuffer::AllocStorage, ASSERT, DummyRenderbuffer, NULL, and gl_renderbuffer::RefCount.
Referenced by _mesa_DeleteRenderbuffers(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Blit rectangular region, optionally from one framebuffer to another.
Note, if the src buffer is multisampled and the dest is not, this is when the samples must be resolved to a single color.
References gl_framebuffer::_ColorReadBuffer, _mesa_debug(), _mesa_error(), _mesa_get_format_bits(), _mesa_get_format_datatype(), _mesa_is_gles3(), _mesa_lookup_enum_by_nr(), _mesa_update_state(), gl_framebuffer::_Status, ASSERT, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, compatible_color_datatypes(), compatible_resolve_formats(), gl_renderbuffer_attachment::CubeMapFace, DEBUG_BLIT, find_attachment(), FLUSH_VERTICES, gl_renderbuffer::Format, GLbitfield, gl_renderbuffer::Height, is_valid_blit_filter(), MESA_VERBOSE, gl_texture_object::Name, gl_renderbuffer::Name, gl_framebuffer::Name, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_config::samples, gl_texture_object::Target, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, VERBOSE_API, gl_framebuffer::Visual, and gl_renderbuffer::Width.
Referenced by _mesa_initialize_exec_table().
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
References _mesa_debug(), _mesa_error(), _mesa_is_winsys_fbo(), _mesa_lookup_enum_by_nr(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, get_framebuffer_target(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
References _mesa_BindFramebuffer(), _mesa_HashRemove(), _mesa_lookup_framebuffer(), _mesa_reference_framebuffer(), _NEW_BUFFERS, ASSERT, DummyFramebuffer, FLUSH_VERTICES, gl_framebuffer::Name, NULL, and gl_framebuffer::RefCount.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
References _mesa_BindRenderbuffer(), _mesa_HashRemove(), _mesa_is_user_fbo(), _mesa_lookup_renderbuffer(), _mesa_reference_renderbuffer(), _NEW_BUFFERS, ASSERT, detach_renderbuffer(), DummyRenderbuffer, FLUSH_VERTICES, NULL, and gl_renderbuffer::RefCount.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References _mesa_error(), _mesa_is_user_fbo(), _mesa_is_winsys_fbo(), _mesa_lookup_enum_by_nr(), and get_framebuffer_target().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
References _mesa_error(), _NEW_BUFFERS, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void _mesa_framebuffer_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_renderbuffer * rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
References _mesa_get_attachment(), _mesa_remove_attachment(), _mesa_set_renderbuffer_attachment(), ASSERT, gl_renderbuffer::AttachedAnytime, invalidate_framebuffer(), and gl_framebuffer::Mutex.
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
References _mesa_error(), _mesa_get_attachment(), _mesa_get_format_base_format(), _mesa_is_winsys_fbo(), _mesa_lookup_enum_by_nr(), _mesa_lookup_renderbuffer(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, DummyRenderbuffer, FLUSH_VERTICES, gl_renderbuffer::Format, get_framebuffer_target(), MESA_FORMAT_NONE, and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
References _mesa_error(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References _mesa_error(), _mesa_lookup_enum_by_nr(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References _mesa_error(), _mesa_is_gles(), _mesa_lookup_enum_by_nr(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset)
References _mesa_error(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
References framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenerateMipmap (GLenum target)
References _mesa_cube_complete(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_is_depthstencil_format(), _mesa_is_enum_format_integer(), _mesa_is_gles(), _mesa_is_stencil_format(), _mesa_lock_texture(), _mesa_lookup_enum_by_nr(), _mesa_select_tex_image(), _mesa_unlock_texture(), API_OPENGLES, gl_texture_object::BaseLevel, FLUSH_VERTICES, gl_texture_image::InternalFormat, gl_texture_object::MaxLevel, and gl_texture_object::Target.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint * framebuffers)
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), and DummyFramebuffer.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint * renderbuffers)
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), and DummyRenderbuffer.
Referenced by _mesa_initialize_exec_table().
struct gl_renderbuffer_attachment* _mesa_get_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment) read
Given a GL_*_ATTACHMENTn token, return a pointer to the corresponding gl_renderbuffer_attachment object.
This function is only used for user-created FB objects, not the default / window-system FB object. If attachment is GL_DEPTH_STENCIL_ATTACHMENT, return a pointer to the depth buffer attachment point.
References _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_user_fbo(), gl_context::API, API_OPENGLES, gl_framebuffer::Attachment, BUFFER_COLOR0, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Const, gl_constants::MaxColorAttachments, and NULL.
Referenced by _mesa_framebuffer_renderbuffer(), _mesa_FramebufferRenderbuffer(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_test_framebuffer_completeness(), and framebuffer_texture().
struct gl_framebuffer* _mesa_get_incomplete_framebuffer (void) read
References IncompleteFramebuffer.
Referenced by check_compatible().
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_get_attachment(), _mesa_get_fb0_attachment(), _mesa_get_format_color_encoding(), _mesa_get_format_datatype(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_winsys_fbo(), _mesa_problem(), _mesa_select_tex_image(), API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, gl_renderbuffer_attachment::CubeMapFace, gl_renderbuffer::Format, get_component_bits(), get_framebuffer_target(), MESA_FORMAT_S8, MESA_FORMAT_Z32_FLOAT_X24S8, gl_texture_object::Name, gl_renderbuffer::Name, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
References gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_renderbuffer::Format, get_component_bits(), gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, gl_renderbuffer::NumSamples, and gl_renderbuffer::Width.
Referenced by _mesa_initialize_exec_table().
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer * fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
References gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_readpixels_needs_slow_path().
void _mesa_init_fbobjects (struct gl_context * ctx)
References gl_renderbuffer::Delete, gl_framebuffer::Delete, delete_dummy_framebuffer(), delete_dummy_renderbuffer(), DummyFramebuffer, DummyRenderbuffer, IncompleteFramebuffer, gl_renderbuffer::Mutex, and gl_framebuffer::Mutex.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References invalidate_framebuffer_storage(), MAX_VIEWPORT_HEIGHT, and MAX_VIEWPORT_WIDTH.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height)
References invalidate_framebuffer_storage().
Referenced by _mesa_initialize_exec_table().
GLboolean _mesa_is_legal_color_format (const struct gl_context * ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
References gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_rg, and gl_context::Extensions.
Referenced by _mesa_update_framebuffer_visual(), is_format_color_renderable(), and test_attachment_completeness().
static GLboolean _mesa_is_user_fbo (const struct gl_framebuffer * fb) inline static
Is the given FBO a user-created FBO?
References gl_framebuffer::Name.
Referenced by _mesa_add_renderbuffer(), _mesa_CopyPixels(), _mesa_DeleteRenderbuffers(), _mesa_DiscardFramebufferEXT(), _mesa_DrawBuffers(), _mesa_get_attachment(), _mesa_ReadnPixelsARB(), _mesa_test_framebuffer_completeness(), _mesa_update_draw_buffer_bounds(), check_rtt_cb(), copytexsubimage_error_check(), copytexture_error_check(), invalidate_rb(), supported_buffer_bitmask(), unbind_texobj_from_fbo(), update_framebuffer_size(), and updated_drawbuffers().
static GLboolean _mesa_is_winsys_fbo (const struct gl_framebuffer * fb) inline static
Is the given FBO a window system FBO (like an X window)?
References gl_framebuffer::Name.
Referenced by _mesa_CheckFramebufferStatus(), _mesa_DiscardFramebufferEXT(), _mesa_DrawBuffers(), _mesa_drawbuffers(), _mesa_FramebufferRenderbuffer(), _mesa_get_fb0_attachment(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetMultisamplefv(), _mesa_make_current(), _mesa_readbuffer(), _mesa_resize_framebuffer(), _mesa_resizebuffers(), _mesa_update_draw_buffers(), check_begin_texture_render(), check_end_texture_render(), framebuffer_texture(), invalidate_framebuffer_storage(), and update_framebuffer().
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
References _mesa_lookup_framebuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyFramebuffer, and NULL.
Referenced by _mesa_initialize_exec_table().
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
References _mesa_lookup_renderbuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyRenderbuffer, and NULL.
Referenced by _mesa_initialize_exec_table().
struct gl_framebuffer* _mesa_lookup_framebuffer (struct gl_context * ctx, GLuint id) read
Helper routine for getting a gl_framebuffer.
References _mesa_HashLookup(), gl_shared_state::FrameBuffers, NULL, and gl_context::Shared.
Referenced by _mesa_BindFramebuffer(), _mesa_DeleteFramebuffers(), and _mesa_IsFramebuffer().
struct gl_renderbuffer* _mesa_lookup_renderbuffer (struct gl_context * ctx, GLuint id) read
Helper routine for getting a gl_renderbuffer.
References _mesa_HashLookup(), NULL, gl_shared_state::RenderBuffers, and gl_context::Shared.
Referenced by _mesa_BindRenderbuffer(), _mesa_DeleteRenderbuffers(), _mesa_FramebufferRenderbuffer(), _mesa_IsRenderbuffer(), get_renderbuffer_parameteriv(), renderbuffer_purgeable(), and renderbuffer_unpurgeable().
void _mesa_remove_attachment (struct gl_context * ctx, struct gl_renderbuffer_attachment * att)
Remove any texture or renderbuffer attached to the given attachment point.
Update reference counts, etc.
References _mesa_reference_renderbuffer(), _mesa_reference_texobj(), ASSERT, gl_renderbuffer_attachment::Complete, gl_context::Driver, dd_function_table::FinishRenderTexture, gl_renderbuffer::NeedsFinishRenderTexture, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_framebuffer_renderbuffer(), _mesa_set_renderbuffer_attachment(), _mesa_set_texture_attachment(), detach_renderbuffer(), framebuffer_texture(), and unbind_texobj_from_fbo().
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
References NO_SAMPLES, and renderbuffer_storage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
References renderbuffer_storage().
Referenced by _mesa_initialize_exec_table().
void _mesa_set_renderbuffer_attachment (struct gl_context * ctx, struct gl_renderbuffer_attachment * att, struct gl_renderbuffer * rb)
Bind a renderbuffer to an attachment point.
The previous binding, if any, will be removed first.
References _mesa_reference_renderbuffer(), _mesa_remove_attachment(), gl_renderbuffer_attachment::Complete, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_framebuffer_renderbuffer().
void _mesa_set_texture_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att, struct gl_texture_object * texObj, GLenum texTarget, GLuint level, GLuint zoffset, GLboolean layered)
Bind a texture object to an attachment point.
The previous binding, if any, will be removed first.
References _mesa_reference_texobj(), _mesa_remove_attachment(), _mesa_tex_target_to_face(), _mesa_update_texture_renderbuffer(), ASSERT, gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_context::Driver, dd_function_table::FinishRenderTexture, invalidate_framebuffer(), gl_renderbuffer_attachment::Layered, gl_renderbuffer::NeedsFinishRenderTexture, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, and gl_renderbuffer_attachment::Zoffset.
Referenced by framebuffer_texture().
void _mesa_test_framebuffer_completeness (struct gl_context * ctx, struct gl_framebuffer * fb)
Test if the given framebuffer object is complete and update its Status field with the results.
Calls the ctx->Driver.ValidateFramebuffer() function to allow the driver to make hardware-specific validation/completeness checks. Also update the framebuffer's Width and Height fields if the framebuffer is complete.
References gl_framebuffer::_AllColorBuffersFixedPoint, gl_texture_image::_BaseFormat, gl_framebuffer::_HasSNormOrFloatColorBuffer, gl_framebuffer::_IntegerColor, _mesa_get_attachment(), _mesa_get_format_datatype(), _mesa_is_desktop_gl(), _mesa_is_format_integer_color(), _mesa_is_user_fbo(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, gl_framebuffer::_Status, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_object, gl_framebuffer::Attachment, BUFFER_COLOR0, BUFFER_DEPTH, BUFFER_STENCIL, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, gl_renderbuffer_attachment::Complete, gl_context::Const, gl_renderbuffer::Depth, gl_context::Driver, gl_context::Extensions, fbo_incomplete(), gl_texture_image::FixedSampleLocations, FLUSH_VERTICES, gl_renderbuffer::Format, gl_texture_image::Height, gl_renderbuffer::Height, gl_framebuffer::Height, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, is_format_color_renderable(), is_legal_depth_format(), gl_renderbuffer_attachment::Layered, gl_framebuffer::Layered, MAX2, gl_constants::MaxColorAttachments, gl_constants::MaxDrawBuffers, MESA_FORMAT_NONE, MIN2, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, test_attachment_completeness(), gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Type, dd_function_table::ValidateFramebuffer, gl_texture_image::Width, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _mesa_CheckFramebufferStatus(), copytexsubimage_error_check(), copytexture_error_check(), renderbuffer_exists(), and update_framebuffer().
void _mesa_update_texture_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
By using a gl_renderbuffer (like user-allocated renderbuffers), drivers get to share most of their framebuffer rendering code between winsys, renderbuffer, and texture attachments.
The allocated renderbuffer uses a non-zero Name so that drivers can check it for determining vertical orientation, but we use ~0 to make it fairly unambiguous with actual user (non-texture) renderbuffers.
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_reference_renderbuffer(), gl_renderbuffer::AllocStorage, gl_renderbuffer_attachment::CubeMapFace, gl_context::Driver, dd_function_table::FinishRenderTexture, gl_renderbuffer::Format, gl_renderbuffer::Height, gl_texture_image::Height2, gl_texture_object::Image, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, gl_renderbuffer::NeedsFinishRenderTexture, dd_function_table::NewRenderbuffer, NULL, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::RenderTexture, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer::Width, and gl_texture_image::Width2.
Referenced by _mesa_set_texture_attachment(), and check_rtt_cb().
void _mesa_validate_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
Drivers should probably override this.
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer::Format, MESA_FORMAT_RGB9_E5_FLOAT, and gl_renderbuffer_attachment::Renderbuffer.