Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
fbobject.c File Reference
#include <stdbool.h>
#include "buffers.h"
#include "context.h"
#include "enums.h"
#include "fbobject.h"
#include "formats.h"
#include "framebuffer.h"
#include "glformats.h"
#include "hash.h"
#include "macros.h"
#include "multisample.h"
#include "mtypes.h"
#include "renderbuffer.h"
#include "state.h"
#include "teximage.h"
#include "texobj.h"
Macros
#define DEBUG_BLIT 0
Set this to 1 to debug/log glBlitFramebuffer() calls.
#define NO_SAMPLES 1000
sentinal value, see below
Functions
static void delete_dummy_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
static void delete_dummy_framebuffer (struct gl_framebuffer *fb)
void _mesa_init_fbobjects (struct gl_context *ctx)
struct gl_framebuffer * _mesa_get_incomplete_framebuffer (void)
struct gl_renderbuffer * _mesa_lookup_renderbuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_renderbuffer.
struct gl_framebuffer * _mesa_lookup_framebuffer (struct gl_context *ctx, GLuint id)
Helper routine for getting a gl_framebuffer.
static void invalidate_framebuffer (struct gl_framebuffer *fb)
Mark the given framebuffer as invalid.
static struct gl_framebuffer * get_framebuffer_target (struct gl_context *ctx, GLenum target)
Return the gl_framebuffer object which corresponds to the given framebuffer target, such as GL_DRAW_FRAMEBUFFER.
struct gl_renderbuffer_attachment * _mesa_get_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment)
Given a GL_*_ATTACHMENTn token, return a pointer to the corresponding gl_renderbuffer_attachment object.
static struct
gl_renderbuffer_attachment * _mesa_get_fb0_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment)
As above, but only used for getting attachments of the default / window-system framebuffer (not user-created framebuffer objects).
void _mesa_remove_attachment (struct gl_context *ctx, struct gl_renderbuffer_attachment *att)
Remove any texture or renderbuffer attached to the given attachment point.
void _mesa_update_texture_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
void _mesa_set_texture_attachment (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att, struct gl_texture_object *texObj, GLenum texTarget, GLuint level, GLuint zoffset, GLboolean layered)
Bind a texture object to an attachment point.
void _mesa_set_renderbuffer_attachment (struct gl_context *ctx, struct gl_renderbuffer_attachment *att, struct gl_renderbuffer *rb)
Bind a renderbuffer to an attachment point.
void _mesa_framebuffer_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
void _mesa_validate_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer *fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
static void att_incomplete (const char *msg)
For debug only.
static void fbo_incomplete (const char *msg, int index)
For debug only.
GLboolean _mesa_is_legal_color_format (const struct gl_context *ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
static GLboolean is_format_color_renderable (const struct gl_context *ctx, gl_format format, GLenum internalFormat)
Is the given base format a legal format for a color renderbuffer?
static GLboolean is_legal_depth_format (const struct gl_context *ctx, GLenum baseFormat)
Is the given base format a legal format for a depth/stencil renderbuffer?
static void test_attachment_completeness (const struct gl_context *ctx, GLenum format, struct gl_renderbuffer_attachment *att)
Test if an attachment point is complete and update its Complete field.
void _mesa_test_framebuffer_completeness (struct gl_context *ctx, struct gl_framebuffer *fb)
Test if the given framebuffer object is complete and update its Status field with the results.
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
static void detach_renderbuffer (struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer *rb)
If the given renderbuffer is anywhere attached to the framebuffer, detach the renderbuffer.
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint *renderbuffers)
GLenum _mesa_base_fbo_format (struct gl_context *ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
static void invalidate_rb (GLuint key, void *data, void *userData)
Invalidate a renderbuffer attachment.
static void renderbuffer_storage (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples)
Helper function used by _mesa_RenderbufferStorage() and _mesa_RenderbufferStorageMultisample().
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
static GLint get_component_bits (GLenum pname, GLenum baseFormat, gl_format format)
Helper function for _mesa_GetRenderbufferParameteriv() and _mesa_GetFramebufferAttachmentParameteriv() We have to be careful to respect the base format.
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalFormat, GLsizei width, GLsizei height)
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
static void check_begin_texture_render (struct gl_context *ctx, struct gl_framebuffer *fb)
Check if any of the attachments of the given framebuffer are textures (render to texture).
static void check_end_texture_render (struct gl_context *ctx, struct gl_framebuffer *fb)
Examine all the framebuffer's attachments to see if any are textures.
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint *framebuffers)
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
static void reuse_framebuffer_texture_attachment (struct gl_framebuffer *fb, gl_buffer_index dst, gl_buffer_index src)
Replicate the src attachment point.
static void framebuffer_texture (struct gl_context *ctx, const char *caller, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset, GLboolean layered)
Common code called by glFramebufferTexture1D/2D/3DEXT() and glFramebufferTextureLayerEXT().
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset)
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbufferTarget, GLuint renderbuffer)
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GenerateMipmap (GLenum target)
static struct
gl_renderbuffer_attachment * find_attachment (const struct gl_framebuffer *fb, const struct gl_renderbuffer *rb)
static GLboolean compatible_color_datatypes (gl_format srcFormat, gl_format dstFormat)
Helper function for checking if the datatypes of color buffers are compatible for glBlitFramebuffer.
static GLboolean compatible_resolve_formats (const struct gl_renderbuffer *readRb, const struct gl_renderbuffer *drawRb)
static GLboolean is_valid_blit_filter (const struct gl_context *ctx, GLenum filter)
void GLAPIENTRY _mesa_BlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Blit rectangular region, optionally from one framebuffer to another.
static void invalidate_framebuffer_storage (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height, const char *name)
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments)
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments)
Variables
static struct gl_framebuffer DummyFramebuffer
Notes:
static struct gl_renderbuffer DummyRenderbuffer
static struct gl_framebuffer IncompleteFramebuffer
Macro Definition Documentation
#define DEBUG_BLIT 0
Set this to 1 to debug/log glBlitFramebuffer() calls.
Referenced by _mesa_BlitFramebuffer().
#define NO_SAMPLES 1000
sentinal value, see below
Referenced by _mesa_RenderbufferStorage(), and renderbuffer_storage().
Function Documentation
void GLAPIENTRY _es_RenderbufferStorageEXT (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
OpenGL ES version of glRenderBufferStorage.
References renderbuffer_storage().
GLenum _mesa_base_fbo_format (struct gl_context * ctx, GLenum internalFormat)
Given an internal format token for a render buffer, return the corresponding base format (one of GL_RGB, GL_RGBA, GL_STENCIL_INDEX, GL_DEPTH_COMPONENT, GL_DEPTH_STENCIL_EXT, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, etc).
This is similar to _mesa_base_tex_format() but the set of valid internal formats is different.
Note that even if a format is determined to be legal here, validation of the FBO may fail if the format is not supported by the driver/GPU.
Parameters
internalFormat as passed to glRenderbufferStorage()
Returns
the base internal format, or 0 if internalFormat is illegal
References _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::EXT_packed_depth_stencil, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_context::Extensions, and gl_context::Version.
Referenced by _mesa_GetInternalformativ(), is_renderable_texture_format(), and renderbuffer_storage().
void GLAPIENTRY _mesa_BindFramebuffer (GLenum target, GLuint framebuffer)
References _mesa_error(), _mesa_HashInsert(), _mesa_is_desktop_gl(), _mesa_lookup_framebuffer(), _mesa_reference_framebuffer(), _NEW_BUFFERS, ASSERT, check_begin_texture_render(), check_end_texture_render(), DummyFramebuffer, FLUSH_VERTICES, and NULL.
Referenced by _mesa_DeleteFramebuffers(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindRenderbuffer (GLenum target, GLuint renderbuffer)
References _mesa_error(), _mesa_HashInsert(), _mesa_is_desktop_gl(), _mesa_lookup_renderbuffer(), _mesa_reference_renderbuffer(), gl_renderbuffer::AllocStorage, ASSERT, DummyRenderbuffer, NULL, and gl_renderbuffer::RefCount.
Referenced by _mesa_DeleteRenderbuffers(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
Blit rectangular region, optionally from one framebuffer to another.
Note, if the src buffer is multisampled and the dest is not, this is when the samples must be resolved to a single color.
References gl_framebuffer::_ColorReadBuffer, _mesa_debug(), _mesa_error(), _mesa_get_format_bits(), _mesa_get_format_datatype(), _mesa_is_gles3(), _mesa_lookup_enum_by_nr(), _mesa_update_state(), gl_framebuffer::_Status, ASSERT, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, compatible_color_datatypes(), compatible_resolve_formats(), gl_renderbuffer_attachment::CubeMapFace, DEBUG_BLIT, find_attachment(), FLUSH_VERTICES, gl_renderbuffer::Format, GLbitfield, gl_renderbuffer::Height, is_valid_blit_filter(), MESA_VERBOSE, gl_texture_object::Name, gl_renderbuffer::Name, gl_framebuffer::Name, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_config::samples, gl_texture_object::Target, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, VERBOSE_API, gl_framebuffer::Visual, and gl_renderbuffer::Width.
Referenced by _mesa_initialize_exec_table().
GLenum GLAPIENTRY _mesa_CheckFramebufferStatus (GLenum target)
References _mesa_debug(), _mesa_error(), _mesa_is_winsys_fbo(), _mesa_lookup_enum_by_nr(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, get_framebuffer_target(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
References _mesa_BindFramebuffer(), _mesa_HashRemove(), _mesa_lookup_framebuffer(), _mesa_reference_framebuffer(), _NEW_BUFFERS, ASSERT, DummyFramebuffer, FLUSH_VERTICES, gl_framebuffer::Name, NULL, and gl_framebuffer::RefCount.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
References _mesa_BindRenderbuffer(), _mesa_HashRemove(), _mesa_is_user_fbo(), _mesa_lookup_renderbuffer(), _mesa_reference_renderbuffer(), _NEW_BUFFERS, ASSERT, detach_renderbuffer(), DummyRenderbuffer, FLUSH_VERTICES, NULL, and gl_renderbuffer::RefCount.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References _mesa_error(), _mesa_is_user_fbo(), _mesa_is_winsys_fbo(), _mesa_lookup_enum_by_nr(), and get_framebuffer_target().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_EGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
References _mesa_error(), _NEW_BUFFERS, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void _mesa_framebuffer_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment, struct gl_renderbuffer * rb)
Fallback for ctx->Driver.FramebufferRenderbuffer() Attach a renderbuffer object to a framebuffer object.
References _mesa_get_attachment(), _mesa_remove_attachment(), _mesa_set_renderbuffer_attachment(), ASSERT, gl_renderbuffer::AttachedAnytime, invalidate_framebuffer(), and gl_framebuffer::Mutex.
void GLAPIENTRY _mesa_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbufferTarget, GLuint renderbuffer)
References _mesa_error(), _mesa_get_attachment(), _mesa_get_format_base_format(), _mesa_is_winsys_fbo(), _mesa_lookup_enum_by_nr(), _mesa_lookup_renderbuffer(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, DummyRenderbuffer, FLUSH_VERTICES, gl_renderbuffer::Format, get_framebuffer_target(), MESA_FORMAT_NONE, and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level)
References _mesa_error(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References _mesa_error(), _mesa_lookup_enum_by_nr(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
References _mesa_error(), _mesa_is_gles(), _mesa_lookup_enum_by_nr(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset)
References _mesa_error(), and framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer)
References framebuffer_texture().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenerateMipmap (GLenum target)
References _mesa_cube_complete(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_is_depthstencil_format(), _mesa_is_enum_format_integer(), _mesa_is_gles(), _mesa_is_stencil_format(), _mesa_lock_texture(), _mesa_lookup_enum_by_nr(), _mesa_select_tex_image(), _mesa_unlock_texture(), API_OPENGLES, gl_texture_object::BaseLevel, FLUSH_VERTICES, gl_texture_image::InternalFormat, gl_texture_object::MaxLevel, and gl_texture_object::Target.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenFramebuffers (GLsizei n, GLuint * framebuffers)
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), and DummyFramebuffer.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenRenderbuffers (GLsizei n, GLuint * renderbuffers)
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), and DummyRenderbuffer.
Referenced by _mesa_initialize_exec_table().
struct gl_renderbuffer_attachment* _mesa_get_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment) read
Given a GL_*_ATTACHMENTn token, return a pointer to the corresponding gl_renderbuffer_attachment object.
This function is only used for user-created FB objects, not the default / window-system FB object. If attachment is GL_DEPTH_STENCIL_ATTACHMENT, return a pointer to the depth buffer attachment point.
References _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_user_fbo(), gl_context::API, API_OPENGLES, gl_framebuffer::Attachment, BUFFER_COLOR0, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Const, gl_constants::MaxColorAttachments, and NULL.
Referenced by _mesa_framebuffer_renderbuffer(), _mesa_FramebufferRenderbuffer(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_test_framebuffer_completeness(), and framebuffer_texture().
static struct gl_renderbuffer_attachment* _mesa_get_fb0_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum attachment) static read
As above, but only used for getting attachments of the default / window-system framebuffer (not user-created framebuffer objects).
References _mesa_is_gles3(), _mesa_is_winsys_fbo(), gl_framebuffer::Attachment, BUFFER_AUX0, BUFFER_BACK_LEFT, BUFFER_BACK_RIGHT, BUFFER_DEPTH, BUFFER_FRONT_LEFT, BUFFER_FRONT_RIGHT, BUFFER_STENCIL, gl_config::doubleBufferMode, gl_context::DrawBuffer, NULL, gl_config::numAuxBuffers, and gl_framebuffer::Visual.
Referenced by _mesa_GetFramebufferAttachmentParameteriv().
struct gl_framebuffer* _mesa_get_incomplete_framebuffer (void) read
References IncompleteFramebuffer.
Referenced by check_compatible().
void GLAPIENTRY _mesa_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_get_attachment(), _mesa_get_fb0_attachment(), _mesa_get_format_color_encoding(), _mesa_get_format_datatype(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_is_winsys_fbo(), _mesa_problem(), _mesa_select_tex_image(), API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, gl_renderbuffer_attachment::CubeMapFace, gl_renderbuffer::Format, get_component_bits(), get_framebuffer_target(), MESA_FORMAT_S8, MESA_FORMAT_Z32_FLOAT_X24S8, gl_texture_object::Name, gl_renderbuffer::Name, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
References gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_renderbuffer::Format, get_component_bits(), gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, gl_renderbuffer::NumSamples, and gl_renderbuffer::Width.
Referenced by _mesa_initialize_exec_table().
GLboolean _mesa_has_depthstencil_combined (const struct gl_framebuffer * fb)
Return true if the framebuffer has a combined depth/stencil renderbuffer attached.
References gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_readpixels_needs_slow_path().
void _mesa_init_fbobjects (struct gl_context * ctx)
References gl_renderbuffer::Delete, gl_framebuffer::Delete, delete_dummy_framebuffer(), delete_dummy_renderbuffer(), DummyFramebuffer, DummyRenderbuffer, IncompleteFramebuffer, gl_renderbuffer::Mutex, and gl_framebuffer::Mutex.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_InvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments)
References invalidate_framebuffer_storage(), MAX_VIEWPORT_HEIGHT, and MAX_VIEWPORT_WIDTH.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_InvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height)
References invalidate_framebuffer_storage().
Referenced by _mesa_initialize_exec_table().
GLboolean _mesa_is_legal_color_format (const struct gl_context * ctx, GLenum baseFormat)
Is the given base format a legal format for a color renderbuffer?
References gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_rg, and gl_context::Extensions.
Referenced by _mesa_update_framebuffer_visual(), is_format_color_renderable(), and test_attachment_completeness().
GLboolean GLAPIENTRY _mesa_IsFramebuffer (GLuint framebuffer)
References _mesa_lookup_framebuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyFramebuffer, and NULL.
Referenced by _mesa_initialize_exec_table().
GLboolean GLAPIENTRY _mesa_IsRenderbuffer (GLuint renderbuffer)
References _mesa_lookup_renderbuffer(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, DummyRenderbuffer, and NULL.
Referenced by _mesa_initialize_exec_table().
struct gl_framebuffer* _mesa_lookup_framebuffer (struct gl_context * ctx, GLuint id) read
Helper routine for getting a gl_framebuffer.
References _mesa_HashLookup(), gl_shared_state::FrameBuffers, NULL, and gl_context::Shared.
Referenced by _mesa_BindFramebuffer(), _mesa_DeleteFramebuffers(), and _mesa_IsFramebuffer().
struct gl_renderbuffer* _mesa_lookup_renderbuffer (struct gl_context * ctx, GLuint id) read
Helper routine for getting a gl_renderbuffer.
References _mesa_HashLookup(), NULL, gl_shared_state::RenderBuffers, and gl_context::Shared.
Referenced by _mesa_BindRenderbuffer(), _mesa_DeleteRenderbuffers(), _mesa_FramebufferRenderbuffer(), _mesa_IsRenderbuffer(), get_renderbuffer_parameteriv(), renderbuffer_purgeable(), and renderbuffer_unpurgeable().
void _mesa_remove_attachment (struct gl_context * ctx, struct gl_renderbuffer_attachment * att)
Remove any texture or renderbuffer attached to the given attachment point.
Update reference counts, etc.
References _mesa_reference_renderbuffer(), _mesa_reference_texobj(), ASSERT, gl_renderbuffer_attachment::Complete, gl_context::Driver, dd_function_table::FinishRenderTexture, gl_renderbuffer::NeedsFinishRenderTexture, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_framebuffer_renderbuffer(), _mesa_set_renderbuffer_attachment(), _mesa_set_texture_attachment(), detach_renderbuffer(), framebuffer_texture(), and unbind_texobj_from_fbo().
void GLAPIENTRY _mesa_RenderbufferStorage (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height)
References NO_SAMPLES, and renderbuffer_storage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_RenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalFormat, GLsizei width, GLsizei height)
References renderbuffer_storage().
Referenced by _mesa_initialize_exec_table().
void _mesa_set_renderbuffer_attachment (struct gl_context * ctx, struct gl_renderbuffer_attachment * att, struct gl_renderbuffer * rb)
Bind a renderbuffer to an attachment point.
The previous binding, if any, will be removed first.
References _mesa_reference_renderbuffer(), _mesa_remove_attachment(), gl_renderbuffer_attachment::Complete, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_framebuffer_renderbuffer().
void _mesa_set_texture_attachment (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att, struct gl_texture_object * texObj, GLenum texTarget, GLuint level, GLuint zoffset, GLboolean layered)
Bind a texture object to an attachment point.
The previous binding, if any, will be removed first.
References _mesa_reference_texobj(), _mesa_remove_attachment(), _mesa_tex_target_to_face(), _mesa_update_texture_renderbuffer(), ASSERT, gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_context::Driver, dd_function_table::FinishRenderTexture, invalidate_framebuffer(), gl_renderbuffer_attachment::Layered, gl_renderbuffer::NeedsFinishRenderTexture, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, and gl_renderbuffer_attachment::Zoffset.
Referenced by framebuffer_texture().
void _mesa_test_framebuffer_completeness (struct gl_context * ctx, struct gl_framebuffer * fb)
Test if the given framebuffer object is complete and update its Status field with the results.
Calls the ctx->Driver.ValidateFramebuffer() function to allow the driver to make hardware-specific validation/completeness checks. Also update the framebuffer's Width and Height fields if the framebuffer is complete.
References gl_framebuffer::_AllColorBuffersFixedPoint, gl_texture_image::_BaseFormat, gl_framebuffer::_HasSNormOrFloatColorBuffer, gl_framebuffer::_IntegerColor, _mesa_get_attachment(), _mesa_get_format_datatype(), _mesa_is_desktop_gl(), _mesa_is_format_integer_color(), _mesa_is_user_fbo(), _mesa_update_framebuffer_visual(), _NEW_BUFFERS, gl_framebuffer::_Status, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_framebuffer_object, gl_framebuffer::Attachment, BUFFER_COLOR0, BUFFER_DEPTH, BUFFER_STENCIL, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, gl_renderbuffer_attachment::Complete, gl_context::Const, gl_renderbuffer::Depth, gl_context::Driver, gl_context::Extensions, fbo_incomplete(), gl_texture_image::FixedSampleLocations, FLUSH_VERTICES, gl_renderbuffer::Format, gl_texture_image::Height, gl_renderbuffer::Height, gl_framebuffer::Height, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, is_format_color_renderable(), is_legal_depth_format(), gl_renderbuffer_attachment::Layered, gl_framebuffer::Layered, MAX2, gl_constants::MaxColorAttachments, gl_constants::MaxDrawBuffers, MESA_FORMAT_NONE, MIN2, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, test_attachment_completeness(), gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Type, dd_function_table::ValidateFramebuffer, gl_texture_image::Width, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _mesa_CheckFramebufferStatus(), copytexsubimage_error_check(), copytexture_error_check(), renderbuffer_exists(), and update_framebuffer().
void _mesa_update_texture_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer_attachment * att)
Create a renderbuffer which will be set up by the driver to wrap the texture image slice.
By using a gl_renderbuffer (like user-allocated renderbuffers), drivers get to share most of their framebuffer rendering code between winsys, renderbuffer, and texture attachments.
The allocated renderbuffer uses a non-zero Name so that drivers can check it for determining vertical orientation, but we use ~0 to make it fairly unambiguous with actual user (non-texture) renderbuffers.
References gl_texture_image::_BaseFormat, gl_renderbuffer::_BaseFormat, _mesa_error(), _mesa_reference_renderbuffer(), gl_renderbuffer::AllocStorage, gl_renderbuffer_attachment::CubeMapFace, gl_context::Driver, dd_function_table::FinishRenderTexture, gl_renderbuffer::Format, gl_renderbuffer::Height, gl_texture_image::Height2, gl_texture_object::Image, gl_texture_image::InternalFormat, gl_renderbuffer::InternalFormat, gl_renderbuffer::NeedsFinishRenderTexture, dd_function_table::NewRenderbuffer, NULL, gl_texture_image::NumSamples, gl_renderbuffer::NumSamples, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::RenderTexture, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer::Width, and gl_texture_image::Width2.
Referenced by _mesa_set_texture_attachment(), and check_rtt_cb().
void _mesa_validate_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb)
Fallback for ctx->Driver.ValidateFramebuffer() Check if the renderbuffer's formats are supported by the software renderer.
Drivers should probably override this.
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer::Format, MESA_FORMAT_RGB9_E5_FLOAT, and gl_renderbuffer_attachment::Renderbuffer.
static void att_incomplete (const char * msg) static
For debug only.
References _mesa_debug(), DEBUG_INCOMPLETE_FBO, MESA_DEBUG_FLAGS, and NULL.
Referenced by test_attachment_completeness().
static void check_begin_texture_render (struct gl_context * ctx, struct gl_framebuffer * fb) static
Check if any of the attachments of the given framebuffer are textures (render to texture).
Call ctx->Driver.RenderTexture() for such attachments.
References _mesa_is_winsys_fbo(), ASSERT, gl_framebuffer::Attachment, BUFFER_COUNT, gl_context::Driver, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::RenderTexture, gl_renderbuffer::TexImage, and gl_renderbuffer_attachment::Texture.
Referenced by _mesa_BindFramebuffer().
static void check_end_texture_render (struct gl_context * ctx, struct gl_framebuffer * fb) static
Examine all the framebuffer's attachments to see if any are textures.
If so, call ctx->Driver.FinishRenderTexture() for each texture to notify the device driver that the texture image may have changed.
References _mesa_is_winsys_fbo(), gl_framebuffer::Attachment, BUFFER_COUNT, gl_context::Driver, dd_function_table::FinishRenderTexture, gl_renderbuffer::NeedsFinishRenderTexture, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_BindFramebuffer().
static GLboolean compatible_color_datatypes (gl_format srcFormat, gl_format dstFormat) static
Helper function for checking if the datatypes of color buffers are compatible for glBlitFramebuffer.
From the 3.1 spec, page 198:
"GL_INVALID_OPERATION is generated if mask contains GL_COLOR_BUFFER_BIT and any of the following conditions hold:
The read buffer contains fixed-point or floating-point values and any draw buffer contains neither fixed-point nor floating-point values.
The read buffer contains unsigned integer values and any draw buffer does not contain unsigned integer values.
The read buffer contains signed integer values and any draw buffer does not contain signed integer values."
References _mesa_get_format_datatype().
Referenced by _mesa_BlitFramebuffer().
static GLboolean compatible_resolve_formats (const struct gl_renderbuffer * readRb, const struct gl_renderbuffer * drawRb) static
References _mesa_get_linear_internalformat(), _mesa_get_nongeneric_internalformat(), _mesa_get_srgb_format_linear(), gl_renderbuffer::Format, and gl_renderbuffer::InternalFormat.
Referenced by _mesa_BlitFramebuffer().
static void delete_dummy_framebuffer (struct gl_framebuffer * fb) static
Referenced by _mesa_init_fbobjects().
static void delete_dummy_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb) static
Referenced by _mesa_init_fbobjects().
static void detach_renderbuffer (struct gl_context * ctx, struct gl_framebuffer * fb, struct gl_renderbuffer * rb) static
If the given renderbuffer is anywhere attached to the framebuffer, detach the renderbuffer.
This is used when a renderbuffer object is deleted. The spec calls for unbinding.
References _mesa_remove_attachment(), gl_framebuffer::Attachment, BUFFER_COUNT, invalidate_framebuffer(), and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_DeleteRenderbuffers().
static void fbo_incomplete (const char * msg, int index) static
For debug only.
References _mesa_debug(), DEBUG_INCOMPLETE_FBO, MESA_DEBUG_FLAGS, and NULL.
Referenced by _mesa_test_framebuffer_completeness().
static struct gl_renderbuffer_attachment* find_attachment (const struct gl_framebuffer * fb, const struct gl_renderbuffer * rb) static read
References gl_framebuffer::Attachment, Elements, NULL, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_BlitFramebuffer().
static void framebuffer_texture (struct gl_context * ctx, const char * caller, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset, GLboolean layered) static
Common code called by glFramebufferTexture1D/2D/3DEXT() and glFramebufferTextureLayerEXT().
Note: glFramebufferTextureLayerEXT() has no textarget parameter so we'll get textarget=0 in that case.
References _mesa_error(), _mesa_get_attachment(), _mesa_is_cube_face(), _mesa_is_winsys_fbo(), _mesa_lookup_texture(), _mesa_max_texture_levels(), _mesa_remove_attachment(), _mesa_set_texture_attachment(), _mesa_tex_target_to_face(), _NEW_BUFFERS, gl_texture_object::_RenderToTexture, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Const, gl_renderbuffer_attachment::CubeMapFace, FLUSH_VERTICES, get_framebuffer_target(), invalidate_framebuffer(), gl_constants::Max3DTextureLevels, gl_constants::MaxArrayTextureLayers, gl_framebuffer::Mutex, NULL, reuse_framebuffer_texture_attachment(), gl_texture_object::Target, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_FramebufferTexture(), _mesa_FramebufferTexture1D(), _mesa_FramebufferTexture2D(), _mesa_FramebufferTexture3D(), and _mesa_FramebufferTextureLayer().
static GLint get_component_bits (GLenum pname, GLenum baseFormat, gl_format format) static
Helper function for _mesa_GetRenderbufferParameteriv() and _mesa_GetFramebufferAttachmentParameteriv() We have to be careful to respect the base format.
For example, if a renderbuffer/texture was created with internalFormat=GL_RGB but the driver actually chose a GL_RGBA format, when the user queries ALPHA_SIZE we need to return zero.
References _mesa_base_format_has_channel(), and _mesa_get_format_bits().
Referenced by _mesa_GetFramebufferAttachmentParameteriv(), and _mesa_GetRenderbufferParameteriv().
static struct gl_framebuffer* get_framebuffer_target (struct gl_context * ctx, GLenum target) static read
Return the gl_framebuffer object which corresponds to the given framebuffer target, such as GL_DRAW_FRAMEBUFFER.
Check support for GL_EXT_framebuffer_blit to determine if certain targets are legal.
Returns
gl_framebuffer pointer or NULL if target is illegal
References _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_context::DrawBuffer, gl_extensions::EXT_framebuffer_blit, gl_context::Extensions, NULL, and gl_context::ReadBuffer.
Referenced by _mesa_CheckFramebufferStatus(), _mesa_DiscardFramebufferEXT(), _mesa_FramebufferRenderbuffer(), _mesa_GetFramebufferAttachmentParameteriv(), framebuffer_texture(), and invalidate_framebuffer_storage().
static void invalidate_framebuffer (struct gl_framebuffer * fb) static
Mark the given framebuffer as invalid.
This will force the test for framebuffer completeness to be done before the framebuffer is used.
References gl_framebuffer::_Status.
Referenced by _mesa_framebuffer_renderbuffer(), _mesa_set_texture_attachment(), detach_renderbuffer(), and framebuffer_texture().
static void invalidate_framebuffer_storage (GLenum target, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height, const char * name) static
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_winsys_fbo(), API_OPENGL_COMPAT, and get_framebuffer_target().
Referenced by _mesa_InvalidateFramebuffer(), and _mesa_InvalidateSubFramebuffer().
static void invalidate_rb (GLuint key, void * data, void * userData) static
Invalidate a renderbuffer attachment.
Called from _mesa_HashWalk().
References _mesa_is_user_fbo(), gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer_attachment::Renderbuffer, and gl_renderbuffer_attachment::Type.
Referenced by renderbuffer_storage().
static GLboolean is_format_color_renderable (const struct gl_context * ctx, gl_format format, GLenum internalFormat) static
Is the given base format a legal format for a color renderbuffer?
References _mesa_get_format_base_format(), _mesa_is_desktop_gl(), _mesa_is_legal_color_format(), and MESA_FORMAT_ARGB2101010.
Referenced by _mesa_test_framebuffer_completeness().
static GLboolean is_legal_depth_format (const struct gl_context * ctx, GLenum baseFormat) static
Is the given base format a legal format for a depth/stencil renderbuffer?
Referenced by _mesa_test_framebuffer_completeness().
static GLboolean is_valid_blit_filter (const struct gl_context * ctx, GLenum filter) static
References gl_extensions::EXT_framebuffer_multisample_blit_scaled, and gl_context::Extensions.
Referenced by _mesa_BlitFramebuffer().
static void renderbuffer_storage (GLenum target, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei samples) static
Helper function used by _mesa_RenderbufferStorage() and _mesa_RenderbufferStorageMultisample().
samples will be NO_SAMPLES if called by _mesa_RenderbufferStorage().
References gl_renderbuffer::_BaseFormat, _mesa_base_fbo_format(), _mesa_check_sample_count(), _mesa_debug(), _mesa_error(), _mesa_HashWalk(), _mesa_lookup_enum_by_nr(), _NEW_BUFFERS, gl_renderbuffer::AllocStorage, ASSERT, gl_renderbuffer::AttachedAnytime, FLUSH_VERTICES, gl_renderbuffer::Format, gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, invalidate_rb(), MESA_FORMAT_NONE, MESA_VERBOSE, NO_SAMPLES, gl_renderbuffer::NumSamples, VERBOSE_API, and gl_renderbuffer::Width.
Referenced by _es_RenderbufferStorageEXT(), _mesa_RenderbufferStorage(), and _mesa_RenderbufferStorageMultisample().
static void reuse_framebuffer_texture_attachment (struct gl_framebuffer * fb, gl_buffer_index dst, gl_buffer_index src) static
Replicate the src attachment point.
Used by framebuffer_texture() when the same texture is attached at GL_DEPTH_ATTACHMENT and GL_STENCIL_ATTACHMENT.
References _mesa_reference_renderbuffer(), _mesa_reference_texobj(), gl_framebuffer::Attachment, gl_renderbuffer_attachment::Complete, NULL, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, and gl_renderbuffer_attachment::Zoffset.
Referenced by framebuffer_texture().
static void test_attachment_completeness (const struct gl_context * ctx, GLenum format, struct gl_renderbuffer_attachment * att) static
Test if an attachment point is complete and update its Complete field.
Parameters
format if GL_COLOR, this is a color attachment point, if GL_DEPTH, this is a depth component attachment point, if GL_STENCIL, this is a stencil component attachment point.
References _mesa_get_format_base_format(), _mesa_is_format_compressed(), _mesa_is_legal_color_format(), gl_extensions::ARB_depth_texture, ASSERT, att_incomplete(), gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_texture_image::Depth, gl_extensions::EXT_packed_depth_stencil, gl_context::Extensions, gl_renderbuffer::Format, gl_texture_image::Height, gl_renderbuffer::Height, gl_texture_object::Image, gl_renderbuffer::InternalFormat, gl_texture_object::Name, gl_renderbuffer_attachment::Renderbuffer, gl_texture_object::Target, gl_texture_image::TexFormat, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, gl_texture_image::Width, gl_renderbuffer::Width, and gl_renderbuffer_attachment::Zoffset.
Referenced by _mesa_test_framebuffer_completeness().
Variable Documentation
struct gl_framebuffer DummyFramebuffer static
Notes:
None of the GL_EXT_framebuffer_object functions are compiled into display lists.
Referenced by _mesa_BindFramebuffer(), _mesa_DeleteFramebuffers(), _mesa_GenFramebuffers(), _mesa_init_fbobjects(), and _mesa_IsFramebuffer().
struct gl_renderbuffer DummyRenderbuffer static
Referenced by _mesa_BindRenderbuffer(), _mesa_DeleteRenderbuffers(), _mesa_FramebufferRenderbuffer(), _mesa_GenRenderbuffers(), _mesa_init_fbobjects(), and _mesa_IsRenderbuffer().
struct gl_framebuffer IncompleteFramebuffer static
Referenced by _mesa_get_incomplete_framebuffer(), and _mesa_init_fbobjects().