Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
feedback.c File Reference
Selection and feedback modes functions.
#include "glheader.h"
#include "colormac.h"
#include "context.h"
#include "enums.h"
#include "feedback.h"
#include "macros.h"
#include "mtypes.h"
#include "main/dispatch.h"
Macros
#define FB_3D 0x01
#define FB_4D 0x02
#define FB_COLOR 0x04
#define FB_TEXTURE 0X08
Functions
void GLAPIENTRY _mesa_FeedbackBuffer (GLsizei size, GLenum type, GLfloat *buffer)
void GLAPIENTRY _mesa_PassThrough (GLfloat token)
void _mesa_feedback_vertex (struct gl_context *ctx, const GLfloat win[4], const GLfloat color[4], const GLfloat texcoord[4])
Put a vertex into the feedback buffer.
Selection
void GLAPIENTRY _mesa_SelectBuffer (GLsizei size, GLuint *buffer)
Establish a buffer for selection mode values.
static void write_record (struct gl_context *ctx, GLuint value)
Write a value of a record into the selection buffer.
void _mesa_update_hitflag (struct gl_context *ctx, GLfloat z)
Update the hit flag and the maximum and minimum depth values.
static void write_hit_record (struct gl_context *ctx)
Write the hit record.
void GLAPIENTRY _mesa_InitNames (void)
Initialize the name stack.
void GLAPIENTRY _mesa_LoadName (GLuint name)
Load the top-most name of the name stack.
void GLAPIENTRY _mesa_PushName (GLuint name)
Push a name into the name stack.
void GLAPIENTRY _mesa_PopName (void)
Pop a name into the name stack.
Render Mode
GLint GLAPIENTRY _mesa_RenderMode (GLenum mode)
Set rasterization mode.
Initialization
void _mesa_init_feedback (struct gl_context *ctx)
Initialize context feedback data.
Detailed Description
Selection and feedback modes functions.
Macro Definition Documentation
#define FB_3D 0x01
Referenced by _mesa_feedback_vertex(), and _mesa_FeedbackBuffer().
#define FB_4D 0x02
Referenced by _mesa_feedback_vertex(), and _mesa_FeedbackBuffer().
#define FB_COLOR 0x04
Referenced by _mesa_feedback_vertex(), and _mesa_FeedbackBuffer().
#define FB_TEXTURE 0X08
Referenced by _mesa_feedback_vertex(), and _mesa_FeedbackBuffer().
Function Documentation
void _mesa_feedback_vertex (struct gl_context * ctx, const GLfloat win[4], const GLfloat color[4], const GLfloat texcoord[4])
Put a vertex into the feedback buffer.
References gl_feedback::_Mask, _mesa_feedback_token(), FB_3D, FB_4D, FB_COLOR, FB_TEXTURE, and gl_context::Feedback.
Referenced by _mesa_Bitmap(), _mesa_CopyPixels(), and _mesa_DrawPixels().
void GLAPIENTRY _mesa_FeedbackBuffer (GLsizei size, GLenum type, GLfloat * buffer)
References _mesa_error(), _NEW_RENDERMODE, FB_3D, FB_4D, FB_COLOR, FB_TEXTURE, FLUSH_VERTICES, and size.
Referenced by _mesa_initialize_exec_table().
void _mesa_init_feedback (struct gl_context * ctx)
Initialize context feedback data.
References gl_feedback::Buffer, gl_selection::Buffer, gl_selection::BufferCount, gl_feedback::BufferSize, gl_selection::BufferSize, gl_feedback::Count, gl_context::Feedback, gl_selection::Hits, gl_selection::NameStackDepth, NULL, gl_context::RenderMode, gl_context::Select, and gl_feedback::Type.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_InitNames (void)
Initialize the name stack.
Verifies we are in select mode and resets the name stack depth and resets the hit record data in gl_selection. Marks new render mode in __struct gl_contextRec::NewState.
References _NEW_RENDERMODE, FLUSH_VERTICES, and write_hit_record().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_LoadName (GLuint name)
Load the top-most name of the name stack.
Parameters
name name.
Verifies we are in selection mode and that the name stack is not empty. Flushes vertices. If there is a hit flag writes it (via write_hit_record()), and replace the top-most name in the stack.
sa __struct gl_contextRec::Select.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, MAX_NAME_STACK_DEPTH, and write_hit_record().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PassThrough (GLfloat token)
References _mesa_feedback_token(), and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PopName (void)
Pop a name into the name stack.
Verifies we are in selection mode and that the name stack is not empty. Flushes vertices. If there is a hit flag writes it (via write_hit_record()), and removes top-most name in the name stack.
sa __struct gl_contextRec::Select.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, and write_hit_record().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PushName (GLuint name)
Push a name into the name stack.
Parameters
name name.
Verifies we are in selection mode and that the name stack is not full. Flushes vertices. If there is a hit flag writes it (via write_hit_record()), and adds the name to the top of the name stack.
sa __struct gl_contextRec::Select.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, MAX_NAME_STACK_DEPTH, and write_hit_record().
Referenced by _mesa_initialize_exec_table().
GLint GLAPIENTRY _mesa_RenderMode (GLenum mode)
Set rasterization mode.
Parameters
mode rasterization mode.
Note
this function can't be put in a display list.
See Also
glRenderMode().
Flushes the vertices and do the necessary cleanup according to the previous rasterization mode, such as writing the hit record or resent the select buffer index when exiting the select mode. Updates __struct gl_contextRec::RenderMode and notifies the driver via the dd_function_table::RenderMode callback.
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_warning(), _NEW_RENDERMODE, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, FLUSH_VERTICES, MESA_VERBOSE, VERBOSE_API, and write_hit_record().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_SelectBuffer (GLsizei size, GLuint * buffer)
Establish a buffer for selection mode values.
Parameters
size buffer size.
buffer buffer.
See Also
glSelectBuffer().
Note
this function can't be put in a display list.
Verifies we're not in selection mode, flushes the vertices and initialize the fields in __struct gl_contextRec::Select with the given buffer.
References _mesa_error(), _NEW_RENDERMODE, FLUSH_VERTICES, and size.
Referenced by _mesa_initialize_exec_table().
void _mesa_update_hitflag (struct gl_context * ctx, GLfloat z)
Update the hit flag and the maximum and minimum depth values.
Parameters
ctx GL context.
z depth.
Sets gl_selection::HitFlag and updates gl_selection::HitMinZ and gl_selection::HitMaxZ.
References gl_selection::HitFlag, gl_selection::HitMaxZ, gl_selection::HitMinZ, and gl_context::Select.
Referenced by window_pos3f().
static void write_hit_record (struct gl_context * ctx) static
Write the hit record.
Parameters
ctx GL context.
Write the hit record, i.e., the number of names in the stack, the minimum and maximum depth values and the number of names in the name stack at the time of the event. Resets the hit flag.
See Also
gl_selection.
References gl_selection::HitFlag, gl_selection::HitMaxZ, gl_selection::HitMinZ, gl_selection::Hits, gl_selection::NameStack, gl_selection::NameStackDepth, NULL, gl_context::Select, and write_record().
Referenced by _mesa_InitNames(), _mesa_LoadName(), _mesa_PopName(), _mesa_PushName(), and _mesa_RenderMode().
static void write_record (struct gl_context * ctx, GLuint value) inline static
Write a value of a record into the selection buffer.
Parameters
ctx GL context.
value value.
Verifies there is free space in the buffer to write the value and increments the pointer.
References gl_selection::Buffer, gl_selection::BufferCount, gl_selection::BufferSize, and gl_context::Select.
Referenced by write_hit_record().