Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ffvertex_prog.h File Reference
Functions
struct gl_vertex_program * _mesa_get_fixed_func_vertex_program (struct gl_context *ctx)
Return a vertex program which implements the current fixed-function transform/lighting/texgen operations.
Function Documentation
struct gl_vertex_program* _mesa_get_fixed_func_vertex_program (struct gl_context * ctx) read
Return a vertex program which implements the current fixed-function transform/lighting/texgen operations.
References gl_vertex_program::Base, gl_vertex_program_state::Cache, gl_context::Const, create_new_program(), gl_context::Driver, make_state_key(), gl_program_constants::MaxTemps, MESA_SHADER_VERTEX, dd_function_table::NewProgram, NULL, gl_shader_compiler_options::PreferDP4, dd_function_table::ProgramStringNotify, gl_context::ShaderCompilerOptions, gl_constants::VertexProgram, and gl_context::VertexProgram.
Referenced by update_program().