Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
fog.h File Reference
Fog operations.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_Fogf (GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_Fogi (GLenum pname, GLint param)
void GLAPIENTRY _mesa_Fogfv (GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_Fogiv (GLenum pname, const GLint *params)
void _mesa_init_fog (struct gl_context *ctx)
Detailed Description
Fog operations.
Function Documentation
void GLAPIENTRY _mesa_Fogf (GLenum pname, GLfloat param)
References _mesa_Fogfv().
Referenced by _mesa_Fogx(), _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_Fogfv (GLenum pname, const GLfloat * params)
References _mesa_error(), _NEW_FOG, API_OPENGL_COMPAT, CLAMP, F, FLUSH_VERTICES, TEST_EQ_4V, and update_fog_scale().
Referenced by _mesa_Fogf(), _mesa_Fogi(), _mesa_Fogiv(), _mesa_Fogxv(), _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_Fogi (GLenum pname, GLint param)
References _mesa_Fogfv().
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_Fogiv (GLenum pname, const GLint * params)
References _mesa_Fogfv(), ASSIGN_4V, F, and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table().
void _mesa_init_fog (struct gl_context * ctx)
References gl_fog_attrib::_Scale, ASSIGN_4V, gl_fog_attrib::Color, gl_fog_attrib::ColorSumEnabled, gl_fog_attrib::ColorUnclamped, gl_fog_attrib::Density, gl_fog_attrib::Enabled, gl_fog_attrib::End, gl_context::Fog, gl_fog_attrib::FogCoordinateSource, gl_fog_attrib::FogDistanceMode, gl_fog_attrib::Index, gl_fog_attrib::Mode, and gl_fog_attrib::Start.
Referenced by init_attrib_groups().