Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
formats.h File Reference
#include <GL/gl.h>
Macros
#define MESA_UNSIGNED_BYTE_4_4 (GL_UNSIGNED_BYTE<<1)
#define MAX_PIXEL_BYTES 16
Max number of bytes for any non-compressed pixel format below, or for intermediate pixel storage in Mesa.
Enumerations
enum gl_format {
MESA_FORMAT_NONE = 0, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_ARGB8888,
MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_XRGB8888,
MESA_FORMAT_XRGB8888_REV, MESA_FORMAT_RGB888, MESA_FORMAT_BGR888, MESA_FORMAT_RGB565,
MESA_FORMAT_RGB565_REV, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_RGBA5551,
MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_AL44, MESA_FORMAT_AL88,
MESA_FORMAT_AL88_REV, MESA_FORMAT_AL1616, MESA_FORMAT_AL1616_REV, MESA_FORMAT_RGB332,
MESA_FORMAT_A8, MESA_FORMAT_A16, MESA_FORMAT_L8, MESA_FORMAT_L16,
MESA_FORMAT_I8, MESA_FORMAT_I16, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV,
MESA_FORMAT_R8, MESA_FORMAT_GR88, MESA_FORMAT_RG88, MESA_FORMAT_R16,
MESA_FORMAT_GR1616, MESA_FORMAT_RG1616, MESA_FORMAT_ARGB2101010, MESA_FORMAT_Z24_S8,
MESA_FORMAT_S8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z24_X8,
MESA_FORMAT_Z32, MESA_FORMAT_S8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGBA8,
MESA_FORMAT_SARGB8, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB_DXT1,
MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_RGB_FXT1,
MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3,
MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGB_FLOAT32,
MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT32,
MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT32,
MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_RG_FLOAT32,
MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_ALPHA_UINT32,
MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_INTENSITY_UINT8,
MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_INTENSITY_INT16,
MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_LUMINANCE_UINT32,
MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT8,
MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_ALPHA_INT16,
MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_R_INT8, MESA_FORMAT_RG_INT8, MESA_FORMAT_RGB_INT8,
MESA_FORMAT_RGBA_INT8, MESA_FORMAT_R_INT16, MESA_FORMAT_RG_INT16, MESA_FORMAT_RGB_INT16,
MESA_FORMAT_RGBA_INT16, MESA_FORMAT_R_INT32, MESA_FORMAT_RG_INT32, MESA_FORMAT_RGB_INT32,
MESA_FORMAT_RGBA_INT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_UINT8,
MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RGB_UINT16,
MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RGB_UINT32,
MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_DUDV8, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RG88_REV,
MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, MESA_FORMAT_SIGNED_R16,
MESA_FORMAT_SIGNED_GR1616, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_RGBA_16,
MESA_FORMAT_RED_RGTC1, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_SIGNED_RG_RGTC2,
MESA_FORMAT_L_LATC1, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_SIGNED_LA_LATC2,
MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_RGBA8_EAC,
MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC,
MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_SIGNED_A8,
MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_A16,
MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_RGB9_E5_FLOAT,
MESA_FORMAT_R11_G11_B10_FLOAT, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, MESA_FORMAT_ARGB2101010_UINT,
MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_XRGB4444_UNORM, MESA_FORMAT_XRGB1555_UNORM, MESA_FORMAT_XBGR8888_SNORM,
MESA_FORMAT_XBGR8888_SRGB, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XRGB2101010_UNORM,
MESA_FORMAT_XBGR16161616_UNORM, MESA_FORMAT_XBGR16161616_SNORM, MESA_FORMAT_XBGR16161616_FLOAT, MESA_FORMAT_XBGR16161616_UINT,
MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR32323232_FLOAT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR32323232_SINT,
MESA_FORMAT_COUNT
}
Mesa texture/renderbuffer image formats.
Functions
const char * _mesa_get_format_name (gl_format format)
Return string name of format (for debugging)
GLint _mesa_get_format_bytes (gl_format format)
Return bytes needed to store a block of pixels in the given format.
GLint _mesa_get_format_bits (gl_format format, GLenum pname)
Return bits per component for the given format.
GLuint _mesa_get_format_max_bits (gl_format format)
GLenum _mesa_get_format_datatype (gl_format format)
Return the data type (or more specifically, the data representation) for the given format.
GLenum _mesa_get_format_base_format (gl_format format)
Return the basic format for the given type.
void _mesa_get_format_block_size (gl_format format, GLuint *bw, GLuint *bh)
Return the block size (in pixels) for the given format.
GLboolean _mesa_is_format_compressed (gl_format format)
Is the given format a compressed format?
GLboolean _mesa_is_format_packed_depth_stencil (gl_format format)
Determine if the given format represents a packed depth/stencil buffer.
GLboolean _mesa_is_format_integer_color (gl_format format)
Is the given format a signed/unsigned integer color format?
GLboolean _mesa_is_format_unsigned (gl_format format)
Is the given format an unsigned integer format?
GLenum _mesa_get_format_color_encoding (gl_format format)
Return color encoding for given format.
GLuint _mesa_format_image_size (gl_format format, GLsizei width, GLsizei height, GLsizei depth)
Return number of bytes needed to store an image of the given size in the given format.
uint64_t _mesa_format_image_size64 (gl_format format, GLsizei width, GLsizei height, GLsizei depth)
Same as _mesa_format_image_size() but returns a 64-bit value to accomodate very large textures.
GLint _mesa_format_row_stride (gl_format format, GLsizei width)
void _mesa_format_to_type_and_comps (gl_format format, GLenum *datatype, GLuint *comps)
void _mesa_test_formats (void)
Do sanity checking of the format info table.
gl_format _mesa_get_srgb_format_linear (gl_format format)
For an sRGB format, return the corresponding linear color space format.
gl_format _mesa_get_uncompressed_format (gl_format format)
If the given format is a compressed format, return a corresponding uncompressed format.
GLuint _mesa_format_num_components (gl_format format)
GLboolean _mesa_format_matches_format_and_type (gl_format gl_format, GLenum format, GLenum type, GLboolean swapBytes)
Check if a gl_format exactly matches a GL format/type combination such that we can use memcpy() from one to the other.
Macro Definition Documentation
#define MAX_PIXEL_BYTES 16
Max number of bytes for any non-compressed pixel format below, or for intermediate pixel storage in Mesa.
This should never be less than
Maybe 32 someday?
Referenced by _mesa_convert_colors(), _mesa_get_format_bytes(), and slow_read_rgba_pixels().
#define MESA_UNSIGNED_BYTE_4_4 (GL_UNSIGNED_BYTE<<1)
Referenced by _mesa_sizeof_packed_type(), _mesa_type_is_packed(), do_row(), and do_row_3D().
Enumeration Type Documentation
enum gl_format
Mesa texture/renderbuffer image formats.
Enumerator
MESA_FORMAT_NONE
MESA_FORMAT_RGBA8888
MESA_FORMAT_RGBA8888_REV
MESA_FORMAT_ARGB8888
MESA_FORMAT_ARGB8888_REV
MESA_FORMAT_RGBX8888
MESA_FORMAT_RGBX8888_REV
MESA_FORMAT_XRGB8888
MESA_FORMAT_XRGB8888_REV
MESA_FORMAT_RGB888
MESA_FORMAT_BGR888
MESA_FORMAT_RGB565
MESA_FORMAT_RGB565_REV
MESA_FORMAT_ARGB4444
MESA_FORMAT_ARGB4444_REV
MESA_FORMAT_RGBA5551
MESA_FORMAT_ARGB1555
MESA_FORMAT_ARGB1555_REV
MESA_FORMAT_AL44
MESA_FORMAT_AL88
MESA_FORMAT_AL88_REV
MESA_FORMAT_AL1616
MESA_FORMAT_AL1616_REV
MESA_FORMAT_RGB332
MESA_FORMAT_A8
MESA_FORMAT_A16
MESA_FORMAT_L8
MESA_FORMAT_L16
MESA_FORMAT_I8
MESA_FORMAT_I16
MESA_FORMAT_YCBCR
MESA_FORMAT_YCBCR_REV
MESA_FORMAT_R8
MESA_FORMAT_GR88
MESA_FORMAT_RG88
MESA_FORMAT_R16
MESA_FORMAT_GR1616
MESA_FORMAT_RG1616
MESA_FORMAT_ARGB2101010
MESA_FORMAT_Z24_S8
MESA_FORMAT_S8_Z24
MESA_FORMAT_Z16
MESA_FORMAT_X8_Z24
MESA_FORMAT_Z24_X8
MESA_FORMAT_Z32
MESA_FORMAT_S8
MESA_FORMAT_SRGB8
MESA_FORMAT_SRGBA8
MESA_FORMAT_SARGB8
MESA_FORMAT_SL8
MESA_FORMAT_SLA8
MESA_FORMAT_SRGB_DXT1
MESA_FORMAT_SRGBA_DXT1
MESA_FORMAT_SRGBA_DXT3
MESA_FORMAT_SRGBA_DXT5
MESA_FORMAT_RGB_FXT1
MESA_FORMAT_RGBA_FXT1
MESA_FORMAT_RGB_DXT1
MESA_FORMAT_RGBA_DXT1
MESA_FORMAT_RGBA_DXT3
MESA_FORMAT_RGBA_DXT5
MESA_FORMAT_RGBA_FLOAT32
MESA_FORMAT_RGBA_FLOAT16
MESA_FORMAT_RGB_FLOAT32
MESA_FORMAT_RGB_FLOAT16
MESA_FORMAT_ALPHA_FLOAT32
MESA_FORMAT_ALPHA_FLOAT16
MESA_FORMAT_LUMINANCE_FLOAT32
MESA_FORMAT_LUMINANCE_FLOAT16
MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32
MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16
MESA_FORMAT_INTENSITY_FLOAT32
MESA_FORMAT_INTENSITY_FLOAT16
MESA_FORMAT_R_FLOAT32
MESA_FORMAT_R_FLOAT16
MESA_FORMAT_RG_FLOAT32
MESA_FORMAT_RG_FLOAT16
MESA_FORMAT_ALPHA_UINT8
MESA_FORMAT_ALPHA_UINT16
MESA_FORMAT_ALPHA_UINT32
MESA_FORMAT_ALPHA_INT8
MESA_FORMAT_ALPHA_INT16
MESA_FORMAT_ALPHA_INT32
MESA_FORMAT_INTENSITY_UINT8
MESA_FORMAT_INTENSITY_UINT16
MESA_FORMAT_INTENSITY_UINT32
MESA_FORMAT_INTENSITY_INT8
MESA_FORMAT_INTENSITY_INT16
MESA_FORMAT_INTENSITY_INT32
MESA_FORMAT_LUMINANCE_UINT8
MESA_FORMAT_LUMINANCE_UINT16
MESA_FORMAT_LUMINANCE_UINT32
MESA_FORMAT_LUMINANCE_INT8
MESA_FORMAT_LUMINANCE_INT16
MESA_FORMAT_LUMINANCE_INT32
MESA_FORMAT_LUMINANCE_ALPHA_UINT8
MESA_FORMAT_LUMINANCE_ALPHA_UINT16
MESA_FORMAT_LUMINANCE_ALPHA_UINT32
MESA_FORMAT_LUMINANCE_ALPHA_INT8
MESA_FORMAT_LUMINANCE_ALPHA_INT16
MESA_FORMAT_LUMINANCE_ALPHA_INT32
MESA_FORMAT_R_INT8
MESA_FORMAT_RG_INT8
MESA_FORMAT_RGB_INT8
MESA_FORMAT_RGBA_INT8
MESA_FORMAT_R_INT16
MESA_FORMAT_RG_INT16
MESA_FORMAT_RGB_INT16
MESA_FORMAT_RGBA_INT16
MESA_FORMAT_R_INT32
MESA_FORMAT_RG_INT32
MESA_FORMAT_RGB_INT32
MESA_FORMAT_RGBA_INT32
MESA_FORMAT_R_UINT8
MESA_FORMAT_RG_UINT8
MESA_FORMAT_RGB_UINT8
MESA_FORMAT_RGBA_UINT8
MESA_FORMAT_R_UINT16
MESA_FORMAT_RG_UINT16
MESA_FORMAT_RGB_UINT16
MESA_FORMAT_RGBA_UINT16
MESA_FORMAT_R_UINT32
MESA_FORMAT_RG_UINT32
MESA_FORMAT_RGB_UINT32
MESA_FORMAT_RGBA_UINT32
MESA_FORMAT_DUDV8
MESA_FORMAT_SIGNED_R8
MESA_FORMAT_SIGNED_RG88_REV
MESA_FORMAT_SIGNED_RGBX8888
MESA_FORMAT_SIGNED_RGBA8888
MESA_FORMAT_SIGNED_RGBA8888_REV
MESA_FORMAT_SIGNED_R16
MESA_FORMAT_SIGNED_GR1616
MESA_FORMAT_SIGNED_RGB_16
MESA_FORMAT_SIGNED_RGBA_16
MESA_FORMAT_RGBA_16
MESA_FORMAT_RED_RGTC1
MESA_FORMAT_SIGNED_RED_RGTC1
MESA_FORMAT_RG_RGTC2
MESA_FORMAT_SIGNED_RG_RGTC2
MESA_FORMAT_L_LATC1
MESA_FORMAT_SIGNED_L_LATC1
MESA_FORMAT_LA_LATC2
MESA_FORMAT_SIGNED_LA_LATC2
MESA_FORMAT_ETC1_RGB8
MESA_FORMAT_ETC2_RGB8
MESA_FORMAT_ETC2_SRGB8
MESA_FORMAT_ETC2_RGBA8_EAC
MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC
MESA_FORMAT_ETC2_R11_EAC
MESA_FORMAT_ETC2_RG11_EAC
MESA_FORMAT_ETC2_SIGNED_R11_EAC
MESA_FORMAT_ETC2_SIGNED_RG11_EAC
MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1
MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1
MESA_FORMAT_SIGNED_A8
MESA_FORMAT_SIGNED_L8
MESA_FORMAT_SIGNED_AL88
MESA_FORMAT_SIGNED_I8
MESA_FORMAT_SIGNED_A16
MESA_FORMAT_SIGNED_L16
MESA_FORMAT_SIGNED_AL1616
MESA_FORMAT_SIGNED_I16
MESA_FORMAT_RGB9_E5_FLOAT
MESA_FORMAT_R11_G11_B10_FLOAT
MESA_FORMAT_Z32_FLOAT
MESA_FORMAT_Z32_FLOAT_X24S8
MESA_FORMAT_ARGB2101010_UINT
MESA_FORMAT_ABGR2101010_UINT
MESA_FORMAT_XRGB4444_UNORM
MESA_FORMAT_XRGB1555_UNORM
MESA_FORMAT_XBGR8888_SNORM
MESA_FORMAT_XBGR8888_SRGB
MESA_FORMAT_XBGR8888_UINT
MESA_FORMAT_XBGR8888_SINT
MESA_FORMAT_XRGB2101010_UNORM
MESA_FORMAT_XBGR16161616_UNORM
MESA_FORMAT_XBGR16161616_SNORM
MESA_FORMAT_XBGR16161616_FLOAT
MESA_FORMAT_XBGR16161616_UINT
MESA_FORMAT_XBGR16161616_SINT
MESA_FORMAT_XBGR32323232_FLOAT
MESA_FORMAT_XBGR32323232_UINT
MESA_FORMAT_XBGR32323232_SINT
MESA_FORMAT_COUNT
Function Documentation
GLuint _mesa_format_image_size (gl_format format, GLsizei width, GLsizei height, GLsizei depth)
Return number of bytes needed to store an image of the given size in the given format.
References _mesa_get_format_info(), gl_format_info::BlockHeight, gl_format_info::BlockWidth, and gl_format_info::BytesPerBlock.
Referenced by _mesa_get_compressed_teximage(), compressed_tex_size(), get_tex_level_parameter_image(), getcompressedteximage_error_check(), and texture_size().
uint64_t _mesa_format_image_size64 (gl_format format, GLsizei width, GLsizei height, GLsizei depth)
Same as _mesa_format_image_size() but returns a 64-bit value to accomodate very large textures.
References _mesa_get_format_info(), gl_format_info::BlockHeight, gl_format_info::BlockWidth, and gl_format_info::BytesPerBlock.
Referenced by _mesa_test_proxy_teximage().
GLboolean _mesa_format_matches_format_and_type (gl_format gl_format, GLenum format, GLenum type, GLboolean swapBytes)
Check if a gl_format exactly matches a GL format/type combination such that we can use memcpy() from one to the other.
Parameters
gl_format a MESA_FORMAT_x value
format the user-specified image format
type the user-specified image datatype
swapBytes typically the current pixel pack/unpack byteswap state
Returns
GL_TRUE if the formats match, GL_FALSE otherwise.
References _mesa_little_endian(), MESA_FORMAT_A16, MESA_FORMAT_A8, MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_AL1616, MESA_FORMAT_AL1616_REV, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_ALPHA_UINT32, MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB2101010_UINT, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_COUNT, MESA_FORMAT_DUDV8, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_GR1616, MESA_FORMAT_GR88, MESA_FORMAT_I16, MESA_FORMAT_I8, MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT32, MESA_FORMAT_INTENSITY_INT16, MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_INTENSITY_UINT8, MESA_FORMAT_L16, MESA_FORMAT_L8, MESA_FORMAT_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_ALPHA_INT16, MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT8, MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT32, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_LUMINANCE_UINT32, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R11_G11_B10_FLOAT, MESA_FORMAT_R16, MESA_FORMAT_R8, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_INT16, MESA_FORMAT_R_INT32, MESA_FORMAT_R_INT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_RED_RGTC1, MESA_FORMAT_RG1616, MESA_FORMAT_RG88, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_INT16, MESA_FORMAT_RG_INT32, MESA_FORMAT_RG_INT8, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGB9_E5_FLOAT, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGB_INT16, MESA_FORMAT_RGB_INT32, MESA_FORMAT_RGB_INT8, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGBA5551, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBA_16, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_SARGB8, MESA_FORMAT_SIGNED_A16, MESA_FORMAT_SIGNED_A8, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_GR1616, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_R16, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_SIGNED_RG88_REV, MESA_FORMAT_SIGNED_RG_RGTC2, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8_Z24, MESA_FORMAT_XBGR16161616_FLOAT, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_SNORM, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR16161616_UNORM, MESA_FORMAT_XBGR32323232_FLOAT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_SNORM, MESA_FORMAT_XBGR8888_SRGB, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB1555_UNORM, MESA_FORMAT_XRGB2101010_UNORM, MESA_FORMAT_XRGB4444_UNORM, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, and MESA_FORMAT_Z32_FLOAT_X24S8.
Referenced by _mesa_texstore_can_use_memcpy(), get_tex_memcpy(), and readpixels_can_use_memcpy().
GLuint _mesa_format_num_components (gl_format format)
References _mesa_get_format_info(), gl_format_info::AlphaBits, gl_format_info::BlueBits, gl_format_info::DepthBits, gl_format_info::GreenBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, gl_format_info::RedBits, and gl_format_info::StencilBits.
Referenced by generate_mipmap_compressed().
GLint _mesa_format_row_stride (gl_format format, GLsizei width)
References _mesa_get_format_info(), gl_format_info::BlockHeight, gl_format_info::BlockWidth, and gl_format_info::BytesPerBlock.
Referenced by _mesa_get_compressed_teximage(), _mesa_pack_ubyte_rgba_rect(), _mesa_store_compressed_texsubimage(), and generate_mipmap_compressed().
void _mesa_format_to_type_and_comps (gl_format format, GLenum * datatype, GLuint * comps)
Referenced by check_format_to_type_and_comps(), and generate_mipmap_uncompressed().
GLenum _mesa_get_format_base_format (gl_format format)
Return the basic format for the given type.
The result will be one of GL_RGB, GL_RGBA, GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_INTENSITY, GL_YCBCR_MESA, GL_DEPTH_COMPONENT, GL_STENCIL_INDEX, GL_DEPTH_STENCIL.
References _mesa_get_format_info(), and gl_format_info::BaseFormat.
Referenced by _mesa_FramebufferRenderbuffer(), _mesa_texstore_abgr2101010_uint(), _mesa_texstore_argb2101010_uint(), _mesa_texstore_can_use_memcpy(), _mesa_texstore_r11_g11_b10f(), _mesa_texstore_red_rgtc1(), _mesa_texstore_rg_rgtc2(), _mesa_texstore_rgb9_e5(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgb_fxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_texstore_rgba_float16(), _mesa_texstore_rgba_float32(), _mesa_texstore_rgba_fxt1(), _mesa_texstore_rgba_int16(), _mesa_texstore_rgba_int32(), _mesa_texstore_rgba_int8(), _mesa_texstore_rgba_uint16(), _mesa_texstore_rgba_uint32(), _mesa_texstore_rgba_uint8(), _mesa_texstore_signed_red_rgtc1(), _mesa_texstore_signed_rg_rgtc2(), _mesa_texstore_signed_rgba8888(), _mesa_texstore_signed_rgba_16(), _mesa_texstore_signed_rgbx8888(), _mesa_texstore_snorm16(), _mesa_texstore_snorm1616(), _mesa_texstore_snorm8(), _mesa_texstore_snorm88(), _mesa_texstore_unorm16(), _mesa_texstore_unorm1616(), _mesa_texstore_unorm44(), _mesa_texstore_unorm8(), _mesa_texstore_unorm88(), _mesa_update_framebuffer_visual(), generate_mipmap_compressed(), get_read_write_mode(), get_tex_level_parameter_buffer(), get_tex_memcpy(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), getteximage_error_check(), is_format_color_renderable(), need_rgb_to_luminance_conversion(), readpixels_can_use_memcpy(), test_attachment_completeness(), and validate_texbuffer_format().
GLint _mesa_get_format_bits (gl_format format, GLenum pname)
Return bits per component for the given format.
Parameters
format one of MESA_FORMAT_x
pname the component, such as GL_RED_BITS, GL_TEXTURE_BLUE_BITS, etc.
References _mesa_get_format_info(), _mesa_problem(), gl_format_info::AlphaBits, gl_format_info::BlueBits, gl_format_info::DepthBits, gl_format_info::GreenBits, gl_format_info::IndexBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, NULL, gl_format_info::RedBits, and gl_format_info::StencilBits.
Referenced by _mesa_BlitFramebuffer(), _mesa_update_framebuffer_visual(), get_component_bits(), get_copy_tex_image_source(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), and renderbuffer_exists().
void _mesa_get_format_block_size (gl_format format, GLuint * bw, GLuint * bh)
Return the block size (in pixels) for the given format.
Normally the block size is 1x1. But compressed formats will have block sizes of 4x4 or 8x4 pixels, etc.
Parameters
bw returns block width in pixels
bh returns block height in pixels
References _mesa_get_format_info(), gl_format_info::BlockHeight, and gl_format_info::BlockWidth.
Referenced by _mesa_compressed_image_address(), _mesa_decompress_image(), _mesa_get_compressed_teximage(), _mesa_store_compressed_texsubimage(), and error_check_subtexture_dimensions().
GLint _mesa_get_format_bytes (gl_format format)
Return bytes needed to store a block of pixels in the given format.
Normally, a block is 1x1 (a single pixel). But for compressed formats a block may be 4x4 or 8x4, etc.
Note: not GLuint, so as not to coerce math to unsigned. cf. fdo #37351
References _mesa_get_format_info(), _mesa_is_format_compressed(), ASSERT, gl_format_info::BytesPerBlock, and MAX_PIXEL_BYTES.
Referenced by _mesa_compressed_image_address(), _mesa_decompress_image(), _mesa_pack_colormask(), _mesa_pack_float_rgba_row(), _mesa_pack_ubyte_rgba_row(), _mesa_texstore_abgr2101010_uint(), _mesa_texstore_argb2101010(), _mesa_texstore_argb2101010_uint(), _mesa_texstore_argb8888(), _mesa_texstore_bgr888(), _mesa_texstore_dudv8(), _mesa_texstore_rgb565(), _mesa_texstore_rgb888(), _mesa_texstore_rgba8888(), _mesa_texstore_rgba_16(), _mesa_texstore_rgba_float16(), _mesa_texstore_rgba_float32(), _mesa_texstore_rgba_int16(), _mesa_texstore_rgba_int32(), _mesa_texstore_rgba_int8(), _mesa_texstore_rgba_uint16(), _mesa_texstore_rgba_uint32(), _mesa_texstore_rgba_uint8(), _mesa_texstore_signed_rgba8888(), _mesa_texstore_signed_rgba_16(), _mesa_texstore_signed_rgbx8888(), _mesa_texstore_snorm16(), _mesa_texstore_snorm1616(), _mesa_texstore_snorm8(), _mesa_texstore_snorm88(), _mesa_texstore_unorm16(), _mesa_texstore_unorm1616(), _mesa_texstore_unorm44(), _mesa_texstore_unorm8(), _mesa_texstore_unorm88(), _mesa_texstore_ycbcr(), _mesa_texstore_z16(), _mesa_texstore_z32(), _mesa_unpack_rgba_block(), get_tex_memcpy(), memcpy_texture(), and readpixels_memcpy().
GLenum _mesa_get_format_color_encoding (gl_format format)
Return color encoding for given format.
Returns
GL_LINEAR or GL_SRGB
References MESA_FORMAT_SARGB8, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, and MESA_FORMAT_XBGR8888_SRGB.
Referenced by _mesa_GetFramebufferAttachmentParameteriv(), _mesa_update_framebuffer_visual(), and copytexture_error_check().
GLenum _mesa_get_format_datatype (gl_format format)
Return the data type (or more specifically, the data representation) for the given format.
The return value will be one of: GL_UNSIGNED_NORMALIZED = unsigned int representing [0,1] GL_SIGNED_NORMALIZED = signed int representing [-1, 1] GL_UNSIGNED_INT = an ordinary unsigned integer GL_INT = an ordinary signed integer GL_FLOAT = an ordinary float
References _mesa_get_format_info(), and gl_format_info::DataType.
Referenced by _mesa_BlitFramebuffer(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_pack_colormask(), _mesa_readpixels_needs_slow_path(), _mesa_test_framebuffer_completeness(), _mesa_test_texobj_completeness(), _mesa_texstore_needs_transfer_ops(), _mesa_update_framebuffer_visual(), compatible_color_datatypes(), fast_read_depth_stencil_pixels_separate(), generate_mipmap_compressed(), get_readpixels_transfer_ops(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), get_tex_rgba(), read_pixels_es3_error_check(), read_uint_depth_pixels(), and validate_texbuffer_format().
GLuint _mesa_get_format_max_bits (gl_format format)
References _mesa_get_format_info(), gl_format_info::AlphaBits, gl_format_info::BlueBits, gl_format_info::DepthBits, gl_format_info::GreenBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, MAX2, gl_format_info::RedBits, and gl_format_info::StencilBits.
Referenced by _mesa_pack_colormask().
const char* _mesa_get_format_name (gl_format format)
Return string name of format (for debugging)
References _mesa_get_format_info(), and gl_format_info::StrName.
Referenced by _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), _mesa_pack_uint_24_8_depth_stencil_row(), _mesa_print_framebuffer(), _mesa_unpack_float_z_row(), _mesa_unpack_ubyte_stencil_row(), _mesa_unpack_uint_24_8_depth_stencil_row(), _mesa_unpack_uint_rgba_row(), _mesa_unpack_uint_z_row(), dump_texture(), and get_unpack_rgba_function().
gl_format _mesa_get_srgb_format_linear (gl_format format)
For an sRGB format, return the corresponding linear color space format.
For non-sRGB formats, return the format as-is.
References MESA_FORMAT_AL88, MESA_FORMAT_ARGB8888, MESA_FORMAT_L8, MESA_FORMAT_RGB888, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_SARGB8, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, and MESA_FORMAT_XBGR8888_SRGB.
Referenced by _mesa_get_render_format(), compatible_resolve_formats(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
gl_format _mesa_get_uncompressed_format (gl_format format)
If the given format is a compressed format, return a corresponding uncompressed format.
References _mesa_is_format_compressed(), MESA_FORMAT_AL88, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_GR1616, MESA_FORMAT_GR88, MESA_FORMAT_L8, MESA_FORMAT_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_R16, MESA_FORMAT_R8, MESA_FORMAT_RED_RGTC1, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_RGB888, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_SIGNED_RG88_REV, MESA_FORMAT_SIGNED_RG_RGTC2, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, and MESA_FORMAT_SRGBA_DXT5.
Referenced by generate_mipmap_compressed().
GLboolean _mesa_is_format_compressed (gl_format format)
Is the given format a compressed format?
References _mesa_get_format_info(), gl_format_info::BlockHeight, and gl_format_info::BlockWidth.
Referenced by _mesa_generate_mipmap(), _mesa_get_format_bytes(), _mesa_get_uncompressed_format(), copytexsubimage_error_check(), get_tex_level_parameter_image(), get_tex_rgba(), getcompressedteximage_error_check(), test_attachment_completeness(), and texsubimage_error_check().
GLboolean _mesa_is_format_integer_color (gl_format format)
Is the given format a signed/unsigned integer color format?
References _mesa_get_format_info(), gl_format_info::BaseFormat, and gl_format_info::DataType.
Referenced by _mesa_ReadnPixelsARB(), _mesa_test_framebuffer_completeness(), copytexsubimage_error_check(), get_tex_rgba_uncompressed(), and texsubimage_error_check().
GLboolean _mesa_is_format_packed_depth_stencil (gl_format format)
Determine if the given format represents a packed depth/stencil buffer.
References _mesa_get_format_info(), and gl_format_info::BaseFormat.
GLboolean _mesa_is_format_unsigned (gl_format format)
Is the given format an unsigned integer format?
References _mesa_get_format_info(), _mesa_is_type_unsigned(), and gl_format_info::DataType.
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_test_formats (void)
Do sanity checking of the format info table.
References _mesa_get_format_info(), gl_format_info::AlphaBits, gl_format_info::BaseFormat, gl_format_info::BlockHeight, gl_format_info::BlockWidth, gl_format_info::BlueBits, gl_format_info::BytesPerBlock, check_format_to_type_and_comps(), gl_format_info::DataType, Elements, gl_format_info::GreenBits, gl_format_info::IntensityBits, gl_format_info::LuminanceBits, MESA_FORMAT_COUNT, MESA_FORMAT_NONE, gl_format_info::Name, gl_format_info::RedBits, STATIC_ASSERT, and void().
Referenced by one_time_init().