Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
formatquery.h File Reference
#include "compiler.h"
#include "glheader.h"
Macros
#define FORMATQUERY_H
Functions
size_t _mesa_query_samples_for_format (struct gl_context *ctx, GLenum target, GLenum internalFormat, int samples[16])
void GLAPIENTRY _mesa_GetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params)
Macro Definition Documentation
#define FORMATQUERY_H
Function Documentation
void GLAPIENTRY _mesa_GetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint * params)
References _mesa_base_fbo_format(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_lookup_enum_by_nr(), _mesa_warning(), ASSERT_OUTSIDE_BEGIN_END, MIN2, and NULL.
Referenced by _mesa_initialize_exec_table().
size_t _mesa_query_samples_for_format (struct gl_context * ctx, GLenum target, GLenum internalFormat, int samples[16])
References void().