Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
format_unpack.c File Reference
#include "colormac.h"
#include "format_unpack.h"
#include "macros.h"
#include "../../gallium/auxiliary/util/u_format_rgb9e5.h"
#include "../../gallium/auxiliary/util/u_format_r11g11b10f.h"
Data Structures
struct z32f_x24s8
Color, depth, stencil packing functions.
Macros
#define EXPAND_1_8(X) ((X) ? 0xff : 0x0)
#define EXPAND_2_8(X) (((X) << 6) | ((X) << 4) | ((X) << 2) | (X))
#define EXPAND_3_8(X) (((X) << 5) | ((X) << 2) | ((X) >> 1))
#define EXPAND_4_8(X) (((X) << 4) | (X))
#define EXPAND_5_8(X) (((X) << 3) | ((X) >> 2))
#define EXPAND_6_8(X) (((X) << 2) | ((X) >> 4))
Typedefs
typedef void(* unpack_rgba_func)(const void *src, GLfloat dst[][4], GLuint n)
typedef void(* unpack_float_z_func)(GLuint n, const void *src, GLfloat *dst)
typedef void(* unpack_uint_z_func)(const void *src, GLuint *dst, GLuint n)
Functions
GLfloat _mesa_nonlinear_to_linear (GLubyte cs8)
Convert an 8-bit sRGB value from non-linear space to a linear RGB value in [0, 1].
static void unpack_RGBA8888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA8888_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB8888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB8888_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBX8888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBX8888_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XRGB8888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XRGB8888_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_BGR888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB565 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB565_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB4444 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB4444_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA5551 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB1555 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB1555_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_AL44 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_AL88 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_AL88_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_AL1616 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_AL1616_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB332 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_A8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_A16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_L8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_L16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_I8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_I16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_YCBCR (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_YCBCR_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_GR88 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG88 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_GR1616 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG1616 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB2101010 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ARGB2101010_UINT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ABGR2101010_UINT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_Z24_S8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_S8_Z24 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_Z16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_X8_Z24 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_Z24_X8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_Z32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_Z32_FLOAT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_Z32_FLOAT_X24S8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_S8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SRGB8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SRGBA8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SARGB8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SL8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SLA8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SRGB_DXT1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SRGBA_DXT1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SRGBA_DXT3 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SRGBA_DXT5 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_FXT1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_FXT1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_DXT1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_DXT1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_DXT3 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_DXT5 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_FLOAT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_FLOAT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ALPHA_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_INTENSITY_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LUMINANCE_ALPHA_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_INT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_INT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_INT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_UINT8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_UINT16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_UINT32 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_DUDV8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_R8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RG88_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RGBX8888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RGBA8888 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RGBA8888_REV (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_R16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_GR1616 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RGB_16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RGBA_16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGBA_16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RED_RGTC1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RED_RGTC1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RG_RGTC2 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_RG_RGTC2 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_L_LATC1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_L_LATC1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_LA_LATC2 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_LA_LATC2 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC1_RGB8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_RGB8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_SRGB8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_RGBA8_EAC (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_SRGB8_ALPHA8_EAC (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_R11_EAC (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_RG11_EAC (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_SIGNED_R11_EAC (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_SIGNED_RG11_EAC (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_RGB8_PUNCHTHROUGH_ALPHA1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_A8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_L8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_AL88 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_I8 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_A16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_L16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_AL1616 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_SIGNED_I16 (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_RGB9_E5_FLOAT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_R11_G11_B10_FLOAT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XRGB4444_UNORM (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XRGB1555_UNORM (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR8888_SNORM (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR8888_SRGB (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR8888_UINT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR8888_SINT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XRGB2101010_UNORM (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR16161616_UNORM (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR16161616_SNORM (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR16161616_FLOAT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR16161616_UINT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR16161616_SINT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR32323232_FLOAT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR32323232_UINT (const void *src, GLfloat dst[][4], GLuint n)
static void unpack_XBGR32323232_SINT (const void *src, GLfloat dst[][4], GLuint n)
static unpack_rgba_func get_unpack_rgba_function (gl_format format)
Return the unpacker function for the given format.
void _mesa_unpack_rgba_row (gl_format format, GLuint n, const void *src, GLfloat dst[][4])
Unpack rgba colors, returning as GLfloat values.
static void unpack_ubyte_RGBA8888 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGBA8888_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_ARGB8888 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_ARGB8888_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGBX8888 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGBX8888_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_XRGB8888 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_XRGB8888_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGB888 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_BGR888 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGB565 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGB565_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_ARGB4444 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_ARGB4444_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGBA5551 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_ARGB1555 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_ARGB1555_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_AL44 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_AL88 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_AL88_REV (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RGB332 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_A8 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_L8 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_I8 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_R8 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_GR88 (const void *src, GLubyte dst[][4], GLuint n)
static void unpack_ubyte_RG88 (const void *src, GLubyte dst[][4], GLuint n)
void _mesa_unpack_ubyte_rgba_row (gl_format format, GLuint n, const void *src, GLubyte dst[][4])
Unpack rgba colors, returning as GLubyte values.
static void unpack_int_rgba_RGBA_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGBA_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGBA_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGBA_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGBA_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ARGB8888 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_XRGB8888 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGB_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGB_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGB_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGB_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RGB_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RG_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RG_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RG_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RG_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_RG_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_R_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_R_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_R_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_R_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_R_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ALPHA_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ALPHA_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ALPHA_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ALPHA_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ALPHA_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_ALPHA_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_ALPHA_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_ALPHA_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_ALPHA_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_LUMINANCE_ALPHA_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_INTENSITY_UINT32 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_INTENSITY_UINT16 (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_INTENSITY_INT16 (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_INTENSITY_UINT8 (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_INTENSITY_INT8 (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ARGB2101010_UINT (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ABGR2101010_UINT (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_ARGB2101010 (const GLuint *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_XBGR8888_UINT (const GLubyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_XBGR8888_SINT (const GLbyte *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_XBGR16161616_UINT (const GLushort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_XBGR16161616_SINT (const GLshort *src, GLuint dst[][4], GLuint n)
static void unpack_int_rgba_XBGR32323232_UINT (const GLuint *src, GLuint dst[][4], GLuint n)
void _mesa_unpack_uint_rgba_row (gl_format format, GLuint n, const void *src, GLuint dst[][4])
void _mesa_unpack_rgba_block (gl_format format, const void *src, GLint srcRowStride, GLfloat dst[][4], GLint dstRowStride, GLuint x, GLuint y, GLuint width, GLuint height)
Unpack a 2D rect of pixels returning float RGBA colors.
static void unpack_float_z_Z24_X8 (GLuint n, const void *src, GLfloat *dst)
static void unpack_float_z_X8_Z24 (GLuint n, const void *src, GLfloat *dst)
static void unpack_float_z_Z16 (GLuint n, const void *src, GLfloat *dst)
static void unpack_float_z_Z32 (GLuint n, const void *src, GLfloat *dst)
static void unpack_float_z_Z32F (GLuint n, const void *src, GLfloat *dst)
static void unpack_float_z_Z32X24S8 (GLuint n, const void *src, GLfloat *dst)
void _mesa_unpack_float_z_row (gl_format format, GLuint n, const void *src, GLfloat *dst)
Unpack Z values.
static void unpack_uint_z_Z24_X8 (const void *src, GLuint *dst, GLuint n)
static void unpack_uint_z_X8_Z24 (const void *src, GLuint *dst, GLuint n)
static void unpack_uint_z_Z16 (const void *src, GLuint *dst, GLuint n)
static void unpack_uint_z_Z32 (const void *src, GLuint *dst, GLuint n)
static void unpack_uint_z_Z32_FLOAT (const void *src, GLuint *dst, GLuint n)
static void unpack_uint_z_Z32_FLOAT_X24S8 (const void *src, GLuint *dst, GLuint n)
void _mesa_unpack_uint_z_row (gl_format format, GLuint n, const void *src, GLuint *dst)
Unpack Z values.
static void unpack_ubyte_s_S8 (const void *src, GLubyte *dst, GLuint n)
static void unpack_ubyte_s_Z24_S8 (const void *src, GLubyte *dst, GLuint n)
static void unpack_ubyte_s_S8_Z24 (const void *src, GLubyte *dst, GLuint n)
static void unpack_ubyte_s_Z32_FLOAT_X24S8 (const void *src, GLubyte *dst, GLuint n)
void _mesa_unpack_ubyte_stencil_row (gl_format format, GLuint n, const void *src, GLubyte *dst)
static void unpack_uint_24_8_depth_stencil_S8_Z24 (const GLuint *src, GLuint *dst, GLuint n)
static void unpack_uint_24_8_depth_stencil_Z24_S8 (const GLuint *src, GLuint *dst, GLuint n)
void _mesa_unpack_uint_24_8_depth_stencil_row (gl_format format, GLuint n, const void *src, GLuint *dst)
Macro Definition Documentation
#define EXPAND_1_8 (X) ((X) ? 0xff : 0x0)
Referenced by unpack_ubyte_ARGB1555(), unpack_ubyte_ARGB1555_REV(), and unpack_ubyte_RGBA5551().
#define EXPAND_2_8 (X) (((X) << 6) | ((X) << 4) | ((X) << 2) | (X))
Referenced by unpack_ubyte_RGB332().
#define EXPAND_3_8 (X) (((X) << 5) | ((X) << 2) | ((X) >> 1))
Referenced by unpack_ubyte_RGB332().
#define EXPAND_4_8 (X) (((X) << 4) | (X))
Referenced by unpack_ubyte_AL44(), unpack_ubyte_AL88(), unpack_ubyte_AL88_REV(), unpack_ubyte_ARGB4444(), and unpack_ubyte_ARGB4444_REV().
#define EXPAND_5_8 (X) (((X) << 3) | ((X) >> 2))
Referenced by unpack_ubyte_ARGB1555(), unpack_ubyte_ARGB1555_REV(), unpack_ubyte_RGB565(), unpack_ubyte_RGB565_REV(), and unpack_ubyte_RGBA5551().
#define EXPAND_6_8 (X) (((X) << 2) | ((X) >> 4))
Referenced by unpack_ubyte_RGB565(), and unpack_ubyte_RGB565_REV().
Typedef Documentation
typedef void(* unpack_float_z_func)(GLuint n, const void *src, GLfloat *dst)
typedef void(* unpack_rgba_func)(const void *src, GLfloat dst[][4], GLuint n)
typedef void(* unpack_uint_z_func)(const void *src, GLuint *dst, GLuint n)
Function Documentation
GLfloat _mesa_nonlinear_to_linear (GLubyte cs8)
Convert an 8-bit sRGB value from non-linear space to a linear RGB value in [0, 1].
Implemented with a 256-entry lookup table.
References table, and UBYTE_TO_FLOAT.
Referenced by fetch_etc2_srgb8(), fetch_etc2_srgb8_alpha8_eac(), fetch_etc2_srgb8_punchthrough_alpha1(), fetch_srgb_dxt1(), fetch_srgba_dxt1(), fetch_srgba_dxt3(), fetch_srgba_dxt5(), unpack_SARGB8(), unpack_SL8(), unpack_SLA8(), unpack_SRGB8(), unpack_SRGBA8(), and unpack_XBGR8888_SRGB().
void _mesa_unpack_float_z_row (gl_format format, GLuint n, const void * src, GLfloat * dst)
Unpack Z values.
The returned values will always be in the range [0.0, 1.0].
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, unpack_float_z_X8_Z24(), unpack_float_z_Z16(), unpack_float_z_Z24_X8(), unpack_float_z_Z32(), unpack_float_z_Z32F(), and unpack_float_z_Z32X24S8().
Referenced by get_tex_depth(), read_depth_pixels(), and slow_read_depth_stencil_pixels_separate().
void _mesa_unpack_rgba_block (gl_format format, const void * src, GLint srcRowStride, GLfloat dst[][4], GLint dstRowStride, GLuint x, GLuint y, GLuint width, GLuint height)
Unpack a 2D rect of pixels returning float RGBA colors.
Parameters
format the source image format
src start address of the source image
srcRowStride source image row stride in bytes
dst start address of the dest image
dstRowStride dest image row stride in bytes
x source image start X pos
y source image start Y pos
width width of rect region to convert
height height of rect region to convert
References _mesa_get_format_bytes(), get_unpack_rgba_function(), and GLubyte.
void _mesa_unpack_rgba_row (gl_format format, GLuint n, const void * src, GLfloat dst[][4])
Unpack rgba colors, returning as GLfloat values.
References get_unpack_rgba_function().
Referenced by _mesa_unpack_ubyte_rgba_row(), accum_or_load(), accum_return(), get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_unpack_ubyte_rgba_row (gl_format format, GLuint n, const void * src, GLubyte dst[][4])
Unpack rgba colors, returning as GLubyte values.
This should usually only be used for unpacking formats that use 8 bits or less per channel.
References _mesa_unpack_rgba_row(), MESA_FORMAT_A8, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_GR88, MESA_FORMAT_I8, MESA_FORMAT_L8, MESA_FORMAT_R8, MESA_FORMAT_RG88, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGBA5551, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, UNCLAMPED_FLOAT_TO_UBYTE, unpack_ubyte_A8(), unpack_ubyte_AL44(), unpack_ubyte_AL88(), unpack_ubyte_AL88_REV(), unpack_ubyte_ARGB1555(), unpack_ubyte_ARGB1555_REV(), unpack_ubyte_ARGB4444(), unpack_ubyte_ARGB4444_REV(), unpack_ubyte_ARGB8888(), unpack_ubyte_ARGB8888_REV(), unpack_ubyte_BGR888(), unpack_ubyte_GR88(), unpack_ubyte_I8(), unpack_ubyte_L8(), unpack_ubyte_R8(), unpack_ubyte_RG88(), unpack_ubyte_RGB332(), unpack_ubyte_RGB565(), unpack_ubyte_RGB565_REV(), unpack_ubyte_RGB888(), unpack_ubyte_RGBA5551(), unpack_ubyte_RGBA8888(), unpack_ubyte_RGBA8888_REV(), unpack_ubyte_RGBX8888(), unpack_ubyte_RGBX8888_REV(), unpack_ubyte_XRGB8888(), and unpack_ubyte_XRGB8888_REV().
void _mesa_unpack_ubyte_stencil_row (gl_format format, GLuint n, const void * src, GLubyte * dst)
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, unpack_ubyte_s_S8(), unpack_ubyte_s_S8_Z24(), unpack_ubyte_s_Z24_S8(), and unpack_ubyte_s_Z32_FLOAT_X24S8().
Referenced by fast_read_depth_stencil_pixels_separate(), read_stencil_pixels(), and slow_read_depth_stencil_pixels_separate().
void _mesa_unpack_uint_24_8_depth_stencil_row (gl_format format, GLuint n, const void * src, GLuint * dst)
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, NULL, unpack_uint_24_8_depth_stencil_S8_Z24(), and unpack_uint_24_8_depth_stencil_Z24_S8().
Referenced by fast_read_depth_stencil_pixels().
void _mesa_unpack_uint_rgba_row (gl_format format, GLuint n, const void * src, GLuint dst[][4])
References __FUNCTION__, _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_ALPHA_UINT32, MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB2101010_UINT, MESA_FORMAT_ARGB8888, MESA_FORMAT_INTENSITY_INT16, MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_INTENSITY_UINT8, MESA_FORMAT_LUMINANCE_ALPHA_INT16, MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT8, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_LUMINANCE_UINT32, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_R_INT16, MESA_FORMAT_R_INT32, MESA_FORMAT_R_INT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_RG_INT16, MESA_FORMAT_RG_INT32, MESA_FORMAT_RG_INT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_INT16, MESA_FORMAT_RGB_INT32, MESA_FORMAT_RGB_INT8, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB8888, NULL, unpack_int_rgba_ABGR2101010_UINT(), unpack_int_rgba_ALPHA_INT16(), unpack_int_rgba_ALPHA_INT8(), unpack_int_rgba_ALPHA_UINT16(), unpack_int_rgba_ALPHA_UINT32(), unpack_int_rgba_ALPHA_UINT8(), unpack_int_rgba_ARGB2101010(), unpack_int_rgba_ARGB2101010_UINT(), unpack_int_rgba_ARGB8888(), unpack_int_rgba_INTENSITY_INT16(), unpack_int_rgba_INTENSITY_INT8(), unpack_int_rgba_INTENSITY_UINT16(), unpack_int_rgba_INTENSITY_UINT32(), unpack_int_rgba_INTENSITY_UINT8(), unpack_int_rgba_LUMINANCE_ALPHA_INT16(), unpack_int_rgba_LUMINANCE_ALPHA_INT8(), unpack_int_rgba_LUMINANCE_ALPHA_UINT16(), unpack_int_rgba_LUMINANCE_ALPHA_UINT32(), unpack_int_rgba_LUMINANCE_ALPHA_UINT8(), unpack_int_rgba_LUMINANCE_INT16(), unpack_int_rgba_LUMINANCE_INT8(), unpack_int_rgba_LUMINANCE_UINT16(), unpack_int_rgba_LUMINANCE_UINT32(), unpack_int_rgba_LUMINANCE_UINT8(), unpack_int_rgba_R_INT16(), unpack_int_rgba_R_INT8(), unpack_int_rgba_R_UINT16(), unpack_int_rgba_R_UINT32(), unpack_int_rgba_R_UINT8(), unpack_int_rgba_RG_INT16(), unpack_int_rgba_RG_INT8(), unpack_int_rgba_RG_UINT16(), unpack_int_rgba_RG_UINT32(), unpack_int_rgba_RG_UINT8(), unpack_int_rgba_RGB_INT16(), unpack_int_rgba_RGB_INT8(), unpack_int_rgba_RGB_UINT16(), unpack_int_rgba_RGB_UINT32(), unpack_int_rgba_RGB_UINT8(), unpack_int_rgba_RGBA_INT16(), unpack_int_rgba_RGBA_INT8(), unpack_int_rgba_RGBA_UINT16(), unpack_int_rgba_RGBA_UINT32(), unpack_int_rgba_RGBA_UINT8(), unpack_int_rgba_XBGR16161616_SINT(), unpack_int_rgba_XBGR16161616_UINT(), unpack_int_rgba_XBGR32323232_UINT(), unpack_int_rgba_XBGR8888_SINT(), unpack_int_rgba_XBGR8888_UINT(), and unpack_int_rgba_XRGB8888().
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_unpack_uint_z_row (gl_format format, GLuint n, const void * src, GLuint * dst)
Unpack Z values.
The returned values will always be in the range [0, 0xffffffff].
References _mesa_get_format_name(), _mesa_problem(), GLubyte, MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, unpack_uint_z_X8_Z24(), unpack_uint_z_Z16(), unpack_uint_z_Z24_X8(), unpack_uint_z_Z32(), unpack_uint_z_Z32_FLOAT(), and unpack_uint_z_Z32_FLOAT_X24S8().
Referenced by fast_read_depth_stencil_pixels_separate(), and read_uint_depth_pixels().
static unpack_rgba_func get_unpack_rgba_function (gl_format format) static
Return the unpacker function for the given format.
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_A16, MESA_FORMAT_A8, MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_AL1616, MESA_FORMAT_AL1616_REV, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_ALPHA_UINT32, MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB2101010_UINT, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_COUNT, MESA_FORMAT_DUDV8, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_GR1616, MESA_FORMAT_GR88, MESA_FORMAT_I16, MESA_FORMAT_I8, MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT32, MESA_FORMAT_INTENSITY_INT16, MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_INTENSITY_UINT8, MESA_FORMAT_L16, MESA_FORMAT_L8, MESA_FORMAT_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_ALPHA_INT16, MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT8, MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT32, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_LUMINANCE_UINT32, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R11_G11_B10_FLOAT, MESA_FORMAT_R16, MESA_FORMAT_R8, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_INT16, MESA_FORMAT_R_INT32, MESA_FORMAT_R_INT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_RED_RGTC1, MESA_FORMAT_RG1616, MESA_FORMAT_RG88, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_INT16, MESA_FORMAT_RG_INT32, MESA_FORMAT_RG_INT8, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGB9_E5_FLOAT, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGB_INT16, MESA_FORMAT_RGB_INT32, MESA_FORMAT_RGB_INT8, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGBA5551, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBA_16, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_SARGB8, MESA_FORMAT_SIGNED_A16, MESA_FORMAT_SIGNED_A8, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_GR1616, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_R16, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_SIGNED_RG88_REV, MESA_FORMAT_SIGNED_RG_RGTC2, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8_Z24, MESA_FORMAT_XBGR16161616_FLOAT, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_SNORM, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR16161616_UNORM, MESA_FORMAT_XBGR32323232_FLOAT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_SNORM, MESA_FORMAT_XBGR8888_SRGB, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB1555_UNORM, MESA_FORMAT_XRGB2101010_UNORM, MESA_FORMAT_XRGB4444_UNORM, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, table, unpack_A16(), unpack_A8(), unpack_ABGR2101010_UINT(), unpack_AL1616(), unpack_AL1616_REV(), unpack_AL44(), unpack_AL88(), unpack_AL88_REV(), unpack_ALPHA_FLOAT16(), unpack_ALPHA_FLOAT32(), unpack_ALPHA_INT16(), unpack_ALPHA_INT32(), unpack_ALPHA_INT8(), unpack_ALPHA_UINT16(), unpack_ALPHA_UINT32(), unpack_ALPHA_UINT8(), unpack_ARGB1555(), unpack_ARGB1555_REV(), unpack_ARGB2101010(), unpack_ARGB2101010_UINT(), unpack_ARGB4444(), unpack_ARGB4444_REV(), unpack_ARGB8888(), unpack_ARGB8888_REV(), unpack_BGR888(), unpack_DUDV8(), unpack_ETC1_RGB8(), unpack_ETC2_R11_EAC(), unpack_ETC2_RG11_EAC(), unpack_ETC2_RGB8(), unpack_ETC2_RGB8_PUNCHTHROUGH_ALPHA1(), unpack_ETC2_RGBA8_EAC(), unpack_ETC2_SIGNED_R11_EAC(), unpack_ETC2_SIGNED_RG11_EAC(), unpack_ETC2_SRGB8(), unpack_ETC2_SRGB8_ALPHA8_EAC(), unpack_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1(), unpack_GR1616(), unpack_GR88(), unpack_I16(), unpack_I8(), unpack_INTENSITY_FLOAT16(), unpack_INTENSITY_FLOAT32(), unpack_INTENSITY_INT16(), unpack_INTENSITY_INT32(), unpack_INTENSITY_INT8(), unpack_INTENSITY_UINT16(), unpack_INTENSITY_UINT32(), unpack_INTENSITY_UINT8(), unpack_L16(), unpack_L8(), unpack_L_LATC1(), unpack_LA_LATC2(), unpack_LUMINANCE_ALPHA_FLOAT16(), unpack_LUMINANCE_ALPHA_FLOAT32(), unpack_LUMINANCE_ALPHA_INT16(), unpack_LUMINANCE_ALPHA_INT32(), unpack_LUMINANCE_ALPHA_INT8(), unpack_LUMINANCE_ALPHA_UINT16(), unpack_LUMINANCE_ALPHA_UINT32(), unpack_LUMINANCE_ALPHA_UINT8(), unpack_LUMINANCE_FLOAT16(), unpack_LUMINANCE_FLOAT32(), unpack_LUMINANCE_INT16(), unpack_LUMINANCE_INT32(), unpack_LUMINANCE_INT8(), unpack_LUMINANCE_UINT16(), unpack_LUMINANCE_UINT32(), unpack_LUMINANCE_UINT8(), unpack_R11_G11_B10_FLOAT(), unpack_R16(), unpack_R8(), unpack_R_FLOAT16(), unpack_R_FLOAT32(), unpack_R_INT16(), unpack_R_INT32(), unpack_R_INT8(), unpack_R_UINT16(), unpack_R_UINT32(), unpack_R_UINT8(), unpack_RED_RGTC1(), unpack_RG1616(), unpack_RG88(), unpack_RG_FLOAT16(), unpack_RG_FLOAT32(), unpack_RG_INT16(), unpack_RG_INT32(), unpack_RG_INT8(), unpack_RG_RGTC2(), unpack_RG_UINT16(), unpack_RG_UINT32(), unpack_RG_UINT8(), unpack_RGB332(), unpack_RGB565(), unpack_RGB565_REV(), unpack_RGB888(), unpack_RGB9_E5_FLOAT(), unpack_RGB_DXT1(), unpack_RGB_FLOAT16(), unpack_RGB_FLOAT32(), unpack_RGB_FXT1(), unpack_RGB_INT16(), unpack_RGB_INT32(), unpack_RGB_INT8(), unpack_RGB_UINT16(), unpack_RGB_UINT32(), unpack_RGB_UINT8(), unpack_RGBA5551(), unpack_RGBA8888(), unpack_RGBA8888_REV(), unpack_RGBA_16(), unpack_RGBA_DXT1(), unpack_RGBA_DXT3(), unpack_RGBA_DXT5(), unpack_RGBA_FLOAT16(), unpack_RGBA_FLOAT32(), unpack_RGBA_FXT1(), unpack_RGBA_INT16(), unpack_RGBA_INT32(), unpack_RGBA_INT8(), unpack_RGBA_UINT16(), unpack_RGBA_UINT32(), unpack_RGBA_UINT8(), unpack_RGBX8888(), unpack_RGBX8888_REV(), unpack_S8(), unpack_S8_Z24(), unpack_SARGB8(), unpack_SIGNED_A16(), unpack_SIGNED_A8(), unpack_SIGNED_AL1616(), unpack_SIGNED_AL88(), unpack_SIGNED_GR1616(), unpack_SIGNED_I16(), unpack_SIGNED_I8(), unpack_SIGNED_L16(), unpack_SIGNED_L8(), unpack_SIGNED_L_LATC1(), unpack_SIGNED_LA_LATC2(), unpack_SIGNED_R16(), unpack_SIGNED_R8(), unpack_SIGNED_RED_RGTC1(), unpack_SIGNED_RG88_REV(), unpack_SIGNED_RG_RGTC2(), unpack_SIGNED_RGB_16(), unpack_SIGNED_RGBA8888(), unpack_SIGNED_RGBA8888_REV(), unpack_SIGNED_RGBA_16(), unpack_SIGNED_RGBX8888(), unpack_SL8(), unpack_SLA8(), unpack_SRGB8(), unpack_SRGB_DXT1(), unpack_SRGBA8(), unpack_SRGBA_DXT1(), unpack_SRGBA_DXT3(), unpack_SRGBA_DXT5(), unpack_X8_Z24(), unpack_XBGR16161616_FLOAT(), unpack_XBGR16161616_SINT(), unpack_XBGR16161616_SNORM(), unpack_XBGR16161616_UINT(), unpack_XBGR16161616_UNORM(), unpack_XBGR32323232_FLOAT(), unpack_XBGR32323232_SINT(), unpack_XBGR32323232_UINT(), unpack_XBGR8888_SINT(), unpack_XBGR8888_SNORM(), unpack_XBGR8888_SRGB(), unpack_XBGR8888_UINT(), unpack_XRGB1555_UNORM(), unpack_XRGB2101010_UNORM(), unpack_XRGB4444_UNORM(), unpack_XRGB8888(), unpack_XRGB8888_REV(), unpack_YCBCR(), unpack_YCBCR_REV(), unpack_Z16(), unpack_Z24_S8(), unpack_Z24_X8(), unpack_Z32(), unpack_Z32_FLOAT(), and unpack_Z32_FLOAT_X24S8().
Referenced by _mesa_unpack_rgba_block(), and _mesa_unpack_rgba_row().
static void unpack_A16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_A8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_ABGR2101010_UINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_AL1616 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_AL1616_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_AL44 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, F, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_AL88 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_AL88_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ALPHA_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB1555 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB1555_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB2101010 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB2101010_UINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB4444 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB4444_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB8888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_ARGB8888_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_BGR888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_DUDV8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_ETC1_RGB8 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_R11_EAC (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_RG11_EAC (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_RGB8 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_RGB8_PUNCHTHROUGH_ALPHA1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_RGBA8_EAC (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_SIGNED_R11_EAC (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_SIGNED_RG11_EAC (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_SRGB8 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_SRGB8_ALPHA8_EAC (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_float_z_X8_Z24 (GLuint n, const void * src, GLfloat * dst) static
References ASSERT, and F.
Referenced by _mesa_unpack_float_z_row().
static void unpack_float_z_Z16 (GLuint n, const void * src, GLfloat * dst) static
References GLushort.
Referenced by _mesa_unpack_float_z_row().
static void unpack_float_z_Z24_X8 (GLuint n, const void * src, GLfloat * dst) static
References ASSERT, and F.
Referenced by _mesa_unpack_float_z_row().
static void unpack_float_z_Z32 (GLuint n, const void * src, GLfloat * dst) static
Referenced by _mesa_unpack_float_z_row().
static void unpack_float_z_Z32F (GLuint n, const void * src, GLfloat * dst) static
Referenced by _mesa_unpack_float_z_row().
static void unpack_float_z_Z32X24S8 (GLuint n, const void * src, GLfloat * dst) static
References z32f_x24s8::z.
Referenced by _mesa_unpack_float_z_row().
static void unpack_GR1616 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_GR88 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_I16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_I8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_int_rgba_ABGR2101010_UINT (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ALPHA_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ALPHA_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ALPHA_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ALPHA_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ALPHA_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ARGB2101010 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ARGB2101010_UINT (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_ARGB8888 (const GLbyte * src, GLuint dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_INTENSITY_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_INTENSITY_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_INTENSITY_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_INTENSITY_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_INTENSITY_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_ALPHA_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_ALPHA_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_ALPHA_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_ALPHA_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_ALPHA_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_LUMINANCE_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_R_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_R_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_R_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_R_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_R_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RG_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RG_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RG_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RG_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RG_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGB_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGB_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGB_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGB_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGB_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGBA_INT16 (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGBA_INT8 (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGBA_UINT16 (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGBA_UINT32 (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_RGBA_UINT8 (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_XBGR16161616_SINT (const GLshort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_XBGR16161616_UINT (const GLushort * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_XBGR32323232_UINT (const GLuint * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_XBGR8888_SINT (const GLbyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_XBGR8888_UINT (const GLubyte * src, GLuint dst[][4], GLuint n) static
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_int_rgba_XRGB8888 (const GLbyte * src, GLuint dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_uint_rgba_row().
static void unpack_INTENSITY_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_INTENSITY_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_INTENSITY_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_INTENSITY_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_INTENSITY_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_INTENSITY_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_INTENSITY_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_INTENSITY_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_L16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_L8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_L_LATC1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_LA_LATC2 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_ALPHA_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_LUMINANCE_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R11_G11_B10_FLOAT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_R8 (const void * src, GLfloat dst[][4], GLuint n) static
References GLubyte, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_R_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_R_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RED_RGTC1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RG1616 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RG88 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RG_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RG_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RG_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RG_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RG_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RG_RGTC2 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RG_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RG_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RG_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB332 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB565 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB565_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RGB888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RGB9_E5_FLOAT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_DXT1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RGB_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_FXT1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RGB_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGB_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA5551 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA8888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA8888_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_DXT1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_DXT3 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_DXT5 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_FLOAT16 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_FLOAT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_FXT1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_INT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_INT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_INT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_UINT16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_UINT32 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBA_UINT8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_RGBX8888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_RGBX8888_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_S8 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_S8_Z24 (const void * src, GLfloat dst[][4], GLuint n) static
References ASSERT, and F.
Referenced by get_unpack_rgba_function(), and unpack_X8_Z24().
static void unpack_SARGB8 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_A16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_A8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_AL1616 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_AL88 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_GR1616 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_I16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_I8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_L16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_L8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_L_LATC1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_LA_LATC2 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_R16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_R8 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RED_RGTC1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RG88_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RG_RGTC2 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RGB_16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RGBA8888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RGBA8888_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RGBA_16 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_SIGNED_RGBX8888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SL8 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SLA8 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_SRGB8 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_SRGB_DXT1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_SRGBA8 (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_SRGBA_DXT1 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_SRGBA_DXT3 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_SRGBA_DXT5 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_ubyte_A8 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_AL44 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_4_8, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_AL88 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_4_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_AL88_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_4_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_ARGB1555 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_1_8, EXPAND_5_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_ARGB1555_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_1_8, EXPAND_5_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_ARGB4444 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_4_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_ARGB4444_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_4_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_ARGB8888 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_ARGB8888_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_BGR888 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_GR88 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_I8 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_L8 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_R8 (const void * src, GLubyte dst[][4], GLuint n) static
References GLubyte.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RG88 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGB332 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_2_8, EXPAND_3_8, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGB565 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_5_8, EXPAND_6_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGB565_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_5_8, EXPAND_6_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGB888 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGBA5551 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, EXPAND_1_8, EXPAND_5_8, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGBA8888 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGBA8888_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGBX8888 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_RGBX8888_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_s_S8 (const void * src, GLubyte * dst, GLuint n) static
Referenced by _mesa_unpack_ubyte_stencil_row().
static void unpack_ubyte_s_S8_Z24 (const void * src, GLubyte * dst, GLuint n) static
Referenced by _mesa_unpack_ubyte_stencil_row().
static void unpack_ubyte_s_Z24_S8 (const void * src, GLubyte * dst, GLuint n) static
Referenced by _mesa_unpack_ubyte_stencil_row().
static void unpack_ubyte_s_Z32_FLOAT_X24S8 (const void * src, GLubyte * dst, GLuint n) static
References z32f_x24s8::x24s8.
Referenced by _mesa_unpack_ubyte_stencil_row().
static void unpack_ubyte_XRGB8888 (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_ubyte_XRGB8888_REV (const void * src, GLubyte dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_unpack_ubyte_rgba_row().
static void unpack_uint_24_8_depth_stencil_S8_Z24 (const GLuint * src, GLuint * dst, GLuint n) static
Referenced by _mesa_unpack_uint_24_8_depth_stencil_row().
static void unpack_uint_24_8_depth_stencil_Z24_S8 (const GLuint * src, GLuint * dst, GLuint n) static
Referenced by _mesa_unpack_uint_24_8_depth_stencil_row().
static void unpack_uint_z_X8_Z24 (const void * src, GLuint * dst, GLuint n) static
Referenced by _mesa_unpack_uint_z_row().
static void unpack_uint_z_Z16 (const void * src, GLuint * dst, GLuint n) static
References GLushort.
Referenced by _mesa_unpack_uint_z_row().
static void unpack_uint_z_Z24_X8 (const void * src, GLuint * dst, GLuint n) static
Referenced by _mesa_unpack_uint_z_row().
static void unpack_uint_z_Z32 (const void * src, GLuint * dst, GLuint n) static
Referenced by _mesa_unpack_uint_z_row().
static void unpack_uint_z_Z32_FLOAT (const void * src, GLuint * dst, GLuint n) static
References CLAMP, F, and FLOAT_TO_UINT.
Referenced by _mesa_unpack_uint_z_row().
static void unpack_uint_z_Z32_FLOAT_X24S8 (const void * src, GLuint * dst, GLuint n) static
References CLAMP, F, FLOAT_TO_UINT, and z32f_x24s8::z.
Referenced by _mesa_unpack_uint_z_row().
static void unpack_X8_Z24 (const void * src, GLfloat dst[][4], GLuint n) static
References unpack_S8_Z24().
Referenced by get_unpack_rgba_function().
static void unpack_XBGR16161616_FLOAT (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_half_to_float(), ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR16161616_SINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR16161616_SNORM (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLshort, RCOMP, and SHORT_TO_FLOAT_TEX.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR16161616_UINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR16161616_UNORM (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and USHORT_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR32323232_FLOAT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR32323232_SINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR32323232_UINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR8888_SINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR8888_SNORM (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR8888_SRGB (const void * src, GLfloat dst[][4], GLuint n) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_XBGR8888_UINT (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLbyte, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XRGB1555_UNORM (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XRGB2101010_UNORM (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XRGB4444_UNORM (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_XRGB8888 (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_XRGB8888_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by get_unpack_rgba_function().
static void unpack_YCBCR (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, CLAMP, F, GCOMP, GLubyte, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_YCBCR_REV (const void * src, GLfloat dst[][4], GLuint n) static
References ACOMP, BCOMP, CLAMP, F, GCOMP, GLubyte, GLushort, and RCOMP.
Referenced by get_unpack_rgba_function().
static void unpack_Z16 (const void * src, GLfloat dst[][4], GLuint n) static
References GLushort.
Referenced by get_unpack_rgba_function().
static void unpack_Z24_S8 (const void * src, GLfloat dst[][4], GLuint n) static
References ASSERT, and F.
Referenced by get_unpack_rgba_function(), and unpack_Z24_X8().
static void unpack_Z24_X8 (const void * src, GLfloat dst[][4], GLuint n) static
References unpack_Z24_S8().
Referenced by get_unpack_rgba_function().
static void unpack_Z32 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_Z32_FLOAT (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().
static void unpack_Z32_FLOAT_X24S8 (const void * src, GLfloat dst[][4], GLuint n) static
Referenced by get_unpack_rgba_function().