Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
format_pack.c File Reference
#include "colormac.h"
#include "format_pack.h"
#include "macros.h"
#include "../../gallium/auxiliary/util/u_format_rgb9e5.h"
#include "../../gallium/auxiliary/util/u_format_r11g11b10f.h"
Data Structures
struct z32f_x24s8
Color, depth, stencil packing functions.
Typedefs
typedef void(* pack_ubyte_rgba_row_func)(GLuint n, const GLubyte src[][4], void *dst)
typedef void(* pack_float_rgba_row_func)(GLuint n, const GLfloat src[][4], void *dst)
Functions
static GLfloat linear_to_srgb (GLfloat cl)
static GLubyte linear_float_to_srgb_ubyte (GLfloat cl)
static GLubyte linear_ubyte_to_srgb_ubyte (GLubyte cl)
static void pack_ubyte_RGBA8888 (const GLubyte src[4], void *dst)
static void pack_float_RGBA8888 (const GLfloat src[4], void *dst)
static void pack_row_ubyte_RGBA8888 (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_RGBA8888 (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_RGBA8888_REV (const GLubyte src[4], void *dst)
static void pack_float_RGBA8888_REV (const GLfloat src[4], void *dst)
static void pack_row_ubyte_RGBA8888_REV (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_RGBA8888_REV (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_ARGB8888 (const GLubyte src[4], void *dst)
static void pack_float_ARGB8888 (const GLfloat src[4], void *dst)
static void pack_row_ubyte_ARGB8888 (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_ARGB8888 (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_ARGB8888_REV (const GLubyte src[4], void *dst)
static void pack_float_ARGB8888_REV (const GLfloat src[4], void *dst)
static void pack_row_ubyte_ARGB8888_REV (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_ARGB8888_REV (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_XRGB8888 (const GLubyte src[4], void *dst)
static void pack_float_XRGB8888 (const GLfloat src[4], void *dst)
static void pack_row_ubyte_XRGB8888 (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_XRGB8888 (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_XRGB8888_REV (const GLubyte src[4], void *dst)
static void pack_float_XRGB8888_REV (const GLfloat src[4], void *dst)
static void pack_row_ubyte_XRGB8888_REV (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_XRGB8888_REV (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_RGB888 (const GLubyte src[4], void *dst)
static void pack_float_RGB888 (const GLfloat src[4], void *dst)
static void pack_row_ubyte_RGB888 (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_RGB888 (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_BGR888 (const GLubyte src[4], void *dst)
static void pack_float_BGR888 (const GLfloat src[4], void *dst)
static void pack_row_ubyte_BGR888 (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_BGR888 (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_RGB565 (const GLubyte src[4], void *dst)
static void pack_float_RGB565 (const GLfloat src[4], void *dst)
static void pack_row_ubyte_RGB565 (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_RGB565 (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_RGB565_REV (const GLubyte src[4], void *dst)
static void pack_float_RGB565_REV (const GLfloat src[4], void *dst)
static void pack_row_ubyte_RGB565_REV (GLuint n, const GLubyte src[][4], void *dst)
static void pack_row_float_RGB565_REV (GLuint n, const GLfloat src[][4], void *dst)
static void pack_ubyte_ARGB4444 (const GLubyte src[4], void *dst)
static void pack_float_ARGB4444 (const GLfloat src[4], void *dst)
static void pack_ubyte_ARGB4444_REV (const GLubyte src[4], void *dst)
static void pack_float_ARGB4444_REV (const GLfloat src[4], void *dst)
static void pack_ubyte_RGBA5551 (const GLubyte src[4], void *dst)
static void pack_float_RGBA5551 (const GLfloat src[4], void *dst)
static void pack_ubyte_ARGB1555 (const GLubyte src[4], void *dst)
static void pack_float_ARGB1555 (const GLfloat src[4], void *dst)
static void pack_ubyte_ARGB1555_REV (const GLubyte src[4], void *dst)
static void pack_float_ARGB1555_REV (const GLfloat src[4], void *dst)
static void pack_ubyte_AL44 (const GLubyte src[4], void *dst)
static void pack_float_AL44 (const GLfloat src[4], void *dst)
static void pack_ubyte_AL88 (const GLubyte src[4], void *dst)
static void pack_float_AL88 (const GLfloat src[4], void *dst)
static void pack_ubyte_AL88_REV (const GLubyte src[4], void *dst)
static void pack_float_AL88_REV (const GLfloat src[4], void *dst)
static void pack_ubyte_AL1616 (const GLubyte src[4], void *dst)
static void pack_float_AL1616 (const GLfloat src[4], void *dst)
static void pack_ubyte_AL1616_REV (const GLubyte src[4], void *dst)
static void pack_float_AL1616_REV (const GLfloat src[4], void *dst)
static void pack_ubyte_RGB332 (const GLubyte src[4], void *dst)
static void pack_float_RGB332 (const GLfloat src[4], void *dst)
static void pack_ubyte_A8 (const GLubyte src[4], void *dst)
static void pack_float_A8 (const GLfloat src[4], void *dst)
static void pack_ubyte_A16 (const GLubyte src[4], void *dst)
static void pack_float_A16 (const GLfloat src[4], void *dst)
static void pack_ubyte_L8 (const GLubyte src[4], void *dst)
static void pack_float_L8 (const GLfloat src[4], void *dst)
static void pack_ubyte_L16 (const GLubyte src[4], void *dst)
static void pack_float_L16 (const GLfloat src[4], void *dst)
static void pack_ubyte_YCBCR (const GLubyte src[4], void *dst)
static void pack_float_YCBCR (const GLfloat src[4], void *dst)
static void pack_ubyte_YCBCR_REV (const GLubyte src[4], void *dst)
static void pack_float_YCBCR_REV (const GLfloat src[4], void *dst)
static void pack_ubyte_R8 (const GLubyte src[4], void *dst)
static void pack_float_R8 (const GLfloat src[4], void *dst)
static void pack_ubyte_GR88 (const GLubyte src[4], void *dst)
static void pack_float_GR88 (const GLfloat src[4], void *dst)
static void pack_ubyte_RG88 (const GLubyte src[4], void *dst)
static void pack_float_RG88 (const GLfloat src[4], void *dst)
static void pack_ubyte_R16 (const GLubyte src[4], void *dst)
static void pack_float_R16 (const GLfloat src[4], void *dst)
static void pack_ubyte_GR1616 (const GLubyte src[4], void *dst)
static void pack_float_GR1616 (const GLfloat src[4], void *dst)
static void pack_ubyte_RG1616 (const GLubyte src[4], void *dst)
static void pack_float_RG1616 (const GLfloat src[4], void *dst)
static void pack_ubyte_ARGB2101010 (const GLubyte src[4], void *dst)
static void pack_float_ARGB2101010 (const GLfloat src[4], void *dst)
static void pack_ubyte_ABGR2101010_UINT (const GLubyte src[4], void *dst)
static void pack_float_ABGR2101010_UINT (const GLfloat src[4], void *dst)
static void pack_ubyte_SRGB8 (const GLubyte src[4], void *dst)
static void pack_float_SRGB8 (const GLfloat src[4], void *dst)
static void pack_ubyte_SRGBA8 (const GLubyte src[4], void *dst)
static void pack_float_SRGBA8 (const GLfloat src[4], void *dst)
static void pack_ubyte_SARGB8 (const GLubyte src[4], void *dst)
static void pack_float_SARGB8 (const GLfloat src[4], void *dst)
static void pack_ubyte_SL8 (const GLubyte src[4], void *dst)
static void pack_float_SL8 (const GLfloat src[4], void *dst)
static void pack_ubyte_SLA8 (const GLubyte src[4], void *dst)
static void pack_float_SLA8 (const GLfloat src[4], void *dst)
static void pack_ubyte_RGBA_FLOAT32 (const GLubyte src[4], void *dst)
static void pack_float_RGBA_FLOAT32 (const GLfloat src[4], void *dst)
static void pack_ubyte_RGBA_FLOAT16 (const GLubyte src[4], void *dst)
static void pack_float_RGBA_FLOAT16 (const GLfloat src[4], void *dst)
static void pack_ubyte_RGB_FLOAT32 (const GLubyte src[4], void *dst)
static void pack_float_RGB_FLOAT32 (const GLfloat src[4], void *dst)
static void pack_ubyte_RGB_FLOAT16 (const GLubyte src[4], void *dst)
static void pack_float_RGB_FLOAT16 (const GLfloat src[4], void *dst)
static void pack_ubyte_ALPHA_FLOAT32 (const GLubyte src[4], void *dst)
static void pack_float_ALPHA_FLOAT32 (const GLfloat src[4], void *dst)
static void pack_ubyte_ALPHA_FLOAT16 (const GLubyte src[4], void *dst)
static void pack_float_ALPHA_FLOAT16 (const GLfloat src[4], void *dst)
static void pack_ubyte_LUMINANCE_FLOAT32 (const GLubyte src[4], void *dst)
static void pack_float_LUMINANCE_FLOAT32 (const GLfloat src[4], void *dst)
static void pack_ubyte_LUMINANCE_FLOAT16 (const GLubyte src[4], void *dst)
static void pack_float_LUMINANCE_FLOAT16 (const GLfloat src[4], void *dst)
static void pack_ubyte_LUMINANCE_ALPHA_FLOAT32 (const GLubyte src[4], void *dst)
static void pack_float_LUMINANCE_ALPHA_FLOAT32 (const GLfloat src[4], void *dst)
static void pack_ubyte_LUMINANCE_ALPHA_FLOAT16 (const GLubyte src[4], void *dst)
static void pack_float_LUMINANCE_ALPHA_FLOAT16 (const GLfloat src[4], void *dst)
static void pack_ubyte_RG_FLOAT32 (const GLubyte src[4], void *dst)
static void pack_float_RG_FLOAT32 (const GLfloat src[4], void *dst)
static void pack_ubyte_RG_FLOAT16 (const GLubyte src[4], void *dst)
static void pack_float_RG_FLOAT16 (const GLfloat src[4], void *dst)
static void pack_ubyte_DUDV8 (const GLubyte src[4], void *dst)
static void pack_float_DUDV8 (const GLfloat src[4], void *dst)
static void pack_ubyte_RGBA_16 (const GLubyte src[4], void *dst)
static void pack_float_RGBA_16 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_R8 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_RG88_REV (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_RGBX8888 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_RGBA8888 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_RGBA8888_REV (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_R16 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_GR1616 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_RGB_16 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_RGBA_16 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_A8 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_L8 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_AL88 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_A16 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_L16 (const GLfloat src[4], void *dst)
static void pack_float_SIGNED_AL1616 (const GLfloat src[4], void *dst)
static void pack_float_RGB9_E5_FLOAT (const GLfloat src[4], void *dst)
static void pack_ubyte_RGB9_E5_FLOAT (const GLubyte src[4], void *dst)
static void pack_ubyte_R11_G11_B10_FLOAT (const GLubyte src[4], void *dst)
static void pack_float_R11_G11_B10_FLOAT (const GLfloat src[4], void *dst)
static void pack_ubyte_XRGB4444_UNORM (const GLubyte src[4], void *dst)
static void pack_float_XRGB4444_UNORM (const GLfloat src[4], void *dst)
static void pack_ubyte_XRGB1555_UNORM (const GLubyte src[4], void *dst)
static void pack_float_XRGB1555_UNORM (const GLfloat src[4], void *dst)
static void pack_float_XBGR8888_SNORM (const GLfloat src[4], void *dst)
static void pack_float_XBGR8888_SRGB (const GLfloat src[4], void *dst)
static void pack_ubyte_XRGB2101010_UNORM (const GLubyte src[4], void *dst)
static void pack_float_XRGB2101010_UNORM (const GLfloat src[4], void *dst)
static void pack_ubyte_XBGR16161616_UNORM (const GLubyte src[4], void *dst)
static void pack_float_XBGR16161616_UNORM (const GLfloat src[4], void *dst)
static void pack_float_XBGR16161616_SNORM (const GLfloat src[4], void *dst)
static void pack_float_XBGR16161616_FLOAT (const GLfloat src[4], void *dst)
static void pack_float_XBGR32323232_FLOAT (const GLfloat src[4], void *dst)
gl_pack_ubyte_rgba_func _mesa_get_pack_ubyte_rgba_function (gl_format format)
Return a function that can pack a GLubyte rgba[4] color.
gl_pack_float_rgba_func _mesa_get_pack_float_rgba_function (gl_format format)
Return a function that can pack a GLfloat rgba[4] color.
static pack_float_rgba_row_func get_pack_float_rgba_row_function (gl_format format)
static pack_ubyte_rgba_row_func get_pack_ubyte_rgba_row_function (gl_format format)
void _mesa_pack_float_rgba_row (gl_format format, GLuint n, const GLfloat src[][4], void *dst)
Pack a row of GLfloat rgba[4] values to the destination.
void _mesa_pack_ubyte_rgba_row (gl_format format, GLuint n, const GLubyte src[][4], void *dst)
Pack a row of GLubyte rgba[4] values to the destination.
void _mesa_pack_ubyte_rgba_rect (gl_format format, GLuint width, GLuint height, const GLubyte *src, GLint srcRowStride, void *dst, GLint dstRowStride)
Pack a 2D image of ubyte RGBA pixels in the given format.
static void pack_float_z_Z24_S8 (const GLfloat *src, void *dst)
Pack float Z pixels.
static void pack_float_z_S8_Z24 (const GLfloat *src, void *dst)
static void pack_float_z_Z16 (const GLfloat *src, void *dst)
static void pack_float_z_Z32 (const GLfloat *src, void *dst)
static void pack_float_z_Z32_FLOAT (const GLfloat *src, void *dst)
gl_pack_float_z_func _mesa_get_pack_float_z_func (gl_format format)
static void pack_uint_z_Z24_S8 (const GLuint *src, void *dst)
Pack uint Z pixels.
static void pack_uint_z_S8_Z24 (const GLuint *src, void *dst)
static void pack_uint_z_Z16 (const GLuint *src, void *dst)
static void pack_uint_z_Z32 (const GLuint *src, void *dst)
static void pack_uint_z_Z32_FLOAT (const GLuint *src, void *dst)
static void pack_uint_z_Z32_FLOAT_X24S8 (const GLuint *src, void *dst)
gl_pack_uint_z_func _mesa_get_pack_uint_z_func (gl_format format)
static void pack_ubyte_stencil_Z24_S8 (const GLubyte *src, void *dst)
Pack ubyte stencil pixels.
static void pack_ubyte_stencil_S8_Z24 (const GLubyte *src, void *dst)
static void pack_ubyte_stencil_S8 (const GLubyte *src, void *dst)
static void pack_ubyte_stencil_Z32_FLOAT_X24S8 (const GLubyte *src, void *dst)
gl_pack_ubyte_stencil_func _mesa_get_pack_ubyte_stencil_func (gl_format format)
void _mesa_pack_float_z_row (gl_format format, GLuint n, const GLfloat *src, void *dst)
void _mesa_pack_uint_z_row (gl_format format, GLuint n, const GLuint *src, void *dst)
The incoming Z values are always in the range [0, 0xffffffff].
void _mesa_pack_ubyte_stencil_row (gl_format format, GLuint n, const GLubyte *src, void *dst)
void _mesa_pack_uint_24_8_depth_stencil_row (gl_format format, GLuint n, const GLuint *src, void *dst)
Incoming Z/stencil values are always in uint_24_8 format.
void _mesa_pack_colormask (gl_format format, const GLubyte colorMask[4], void *dst)
Convert a boolean color mask to a packed color where each channel of the packed value at dst will be 0 or ~0 depending on the colorMask.
Typedef Documentation
typedef void(* pack_float_rgba_row_func)(GLuint n, const GLfloat src[][4], void *dst)
typedef void(* pack_ubyte_rgba_row_func)(GLuint n, const GLubyte src[][4], void *dst)
Function Documentation
gl_pack_float_rgba_func _mesa_get_pack_float_rgba_function (gl_format format)
Return a function that can pack a GLfloat rgba[4] color.
References MESA_FORMAT_A16, MESA_FORMAT_A8, MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_AL1616, MESA_FORMAT_AL1616_REV, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_COUNT, MESA_FORMAT_DUDV8, MESA_FORMAT_GR1616, MESA_FORMAT_GR88, MESA_FORMAT_I16, MESA_FORMAT_I8, MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT32, MESA_FORMAT_L16, MESA_FORMAT_L8, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT32, MESA_FORMAT_NONE, MESA_FORMAT_R11_G11_B10_FLOAT, MESA_FORMAT_R16, MESA_FORMAT_R8, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_RG1616, MESA_FORMAT_RG88, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGB9_E5_FLOAT, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGBA5551, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBA_16, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_SARGB8, MESA_FORMAT_SIGNED_A16, MESA_FORMAT_SIGNED_A8, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_GR1616, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_R16, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RG88_REV, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8_Z24, MESA_FORMAT_XBGR16161616_FLOAT, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_SNORM, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR16161616_UNORM, MESA_FORMAT_XBGR32323232_FLOAT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_SNORM, MESA_FORMAT_XBGR8888_SRGB, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB1555_UNORM, MESA_FORMAT_XRGB2101010_UNORM, MESA_FORMAT_XRGB4444_UNORM, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, NULL, pack_float_A16(), pack_float_A8(), pack_float_ABGR2101010_UINT(), pack_float_AL1616(), pack_float_AL1616_REV(), pack_float_AL44(), pack_float_AL88(), pack_float_AL88_REV(), pack_float_ALPHA_FLOAT16(), pack_float_ALPHA_FLOAT32(), pack_float_ARGB1555(), pack_float_ARGB1555_REV(), pack_float_ARGB2101010(), pack_float_ARGB4444(), pack_float_ARGB4444_REV(), pack_float_ARGB8888(), pack_float_ARGB8888_REV(), pack_float_BGR888(), pack_float_DUDV8(), pack_float_GR1616(), pack_float_GR88(), pack_float_L16(), pack_float_L8(), pack_float_LUMINANCE_ALPHA_FLOAT16(), pack_float_LUMINANCE_ALPHA_FLOAT32(), pack_float_LUMINANCE_FLOAT16(), pack_float_LUMINANCE_FLOAT32(), pack_float_R11_G11_B10_FLOAT(), pack_float_R16(), pack_float_R8(), pack_float_RG1616(), pack_float_RG88(), pack_float_RG_FLOAT16(), pack_float_RG_FLOAT32(), pack_float_RGB332(), pack_float_RGB565(), pack_float_RGB565_REV(), pack_float_RGB888(), pack_float_RGB9_E5_FLOAT(), pack_float_RGB_FLOAT16(), pack_float_RGB_FLOAT32(), pack_float_RGBA5551(), pack_float_RGBA8888(), pack_float_RGBA8888_REV(), pack_float_RGBA_16(), pack_float_RGBA_FLOAT16(), pack_float_RGBA_FLOAT32(), pack_float_SARGB8(), pack_float_SIGNED_A16(), pack_float_SIGNED_A8(), pack_float_SIGNED_AL1616(), pack_float_SIGNED_AL88(), pack_float_SIGNED_GR1616(), pack_float_SIGNED_L16(), pack_float_SIGNED_L8(), pack_float_SIGNED_R16(), pack_float_SIGNED_R8(), pack_float_SIGNED_RG88_REV(), pack_float_SIGNED_RGB_16(), pack_float_SIGNED_RGBA8888(), pack_float_SIGNED_RGBA8888_REV(), pack_float_SIGNED_RGBA_16(), pack_float_SIGNED_RGBX8888(), pack_float_SL8(), pack_float_SLA8(), pack_float_SRGB8(), pack_float_SRGBA8(), pack_float_XBGR16161616_FLOAT(), pack_float_XBGR16161616_SNORM(), pack_float_XBGR16161616_UNORM(), pack_float_XBGR32323232_FLOAT(), pack_float_XBGR8888_SNORM(), pack_float_XBGR8888_SRGB(), pack_float_XRGB1555_UNORM(), pack_float_XRGB2101010_UNORM(), pack_float_XRGB4444_UNORM(), pack_float_XRGB8888(), pack_float_XRGB8888_REV(), pack_float_YCBCR(), pack_float_YCBCR_REV(), and table.
Referenced by _mesa_pack_float_rgba_row().
gl_pack_float_z_func _mesa_get_pack_float_z_func (gl_format format)
References _mesa_problem(), MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, pack_float_z_S8_Z24(), pack_float_z_Z16(), pack_float_z_Z24_S8(), pack_float_z_Z32(), and pack_float_z_Z32_FLOAT().
gl_pack_ubyte_rgba_func _mesa_get_pack_ubyte_rgba_function (gl_format format)
Return a function that can pack a GLubyte rgba[4] color.
References MESA_FORMAT_A16, MESA_FORMAT_A8, MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_AL1616, MESA_FORMAT_AL1616_REV, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_COUNT, MESA_FORMAT_DUDV8, MESA_FORMAT_GR1616, MESA_FORMAT_GR88, MESA_FORMAT_I16, MESA_FORMAT_I8, MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT32, MESA_FORMAT_L16, MESA_FORMAT_L8, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT32, MESA_FORMAT_NONE, MESA_FORMAT_R11_G11_B10_FLOAT, MESA_FORMAT_R16, MESA_FORMAT_R8, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_RG1616, MESA_FORMAT_RG88, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGB9_E5_FLOAT, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGBA5551, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBA_16, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_SARGB8, MESA_FORMAT_SIGNED_A16, MESA_FORMAT_SIGNED_A8, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_GR1616, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_R16, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RG88_REV, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8_Z24, MESA_FORMAT_XBGR16161616_FLOAT, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_SNORM, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR16161616_UNORM, MESA_FORMAT_XBGR32323232_FLOAT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_SNORM, MESA_FORMAT_XBGR8888_SRGB, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB1555_UNORM, MESA_FORMAT_XRGB2101010_UNORM, MESA_FORMAT_XRGB4444_UNORM, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, NULL, pack_ubyte_A16(), pack_ubyte_A8(), pack_ubyte_ABGR2101010_UINT(), pack_ubyte_AL1616(), pack_ubyte_AL1616_REV(), pack_ubyte_AL44(), pack_ubyte_AL88(), pack_ubyte_AL88_REV(), pack_ubyte_ALPHA_FLOAT16(), pack_ubyte_ALPHA_FLOAT32(), pack_ubyte_ARGB1555(), pack_ubyte_ARGB1555_REV(), pack_ubyte_ARGB2101010(), pack_ubyte_ARGB4444(), pack_ubyte_ARGB4444_REV(), pack_ubyte_ARGB8888(), pack_ubyte_ARGB8888_REV(), pack_ubyte_BGR888(), pack_ubyte_DUDV8(), pack_ubyte_GR1616(), pack_ubyte_GR88(), pack_ubyte_L16(), pack_ubyte_L8(), pack_ubyte_LUMINANCE_ALPHA_FLOAT16(), pack_ubyte_LUMINANCE_ALPHA_FLOAT32(), pack_ubyte_LUMINANCE_FLOAT16(), pack_ubyte_LUMINANCE_FLOAT32(), pack_ubyte_R11_G11_B10_FLOAT(), pack_ubyte_R16(), pack_ubyte_R8(), pack_ubyte_RG1616(), pack_ubyte_RG88(), pack_ubyte_RG_FLOAT16(), pack_ubyte_RG_FLOAT32(), pack_ubyte_RGB332(), pack_ubyte_RGB565(), pack_ubyte_RGB565_REV(), pack_ubyte_RGB888(), pack_ubyte_RGB9_E5_FLOAT(), pack_ubyte_RGB_FLOAT16(), pack_ubyte_RGB_FLOAT32(), pack_ubyte_RGBA5551(), pack_ubyte_RGBA8888(), pack_ubyte_RGBA8888_REV(), pack_ubyte_RGBA_16(), pack_ubyte_RGBA_FLOAT16(), pack_ubyte_RGBA_FLOAT32(), pack_ubyte_SARGB8(), pack_ubyte_SL8(), pack_ubyte_SLA8(), pack_ubyte_SRGB8(), pack_ubyte_SRGBA8(), pack_ubyte_XBGR16161616_UNORM(), pack_ubyte_XRGB1555_UNORM(), pack_ubyte_XRGB2101010_UNORM(), pack_ubyte_XRGB4444_UNORM(), pack_ubyte_XRGB8888(), pack_ubyte_XRGB8888_REV(), pack_ubyte_YCBCR(), pack_ubyte_YCBCR_REV(), and table.
Referenced by _mesa_pack_ubyte_rgba_row().
gl_pack_ubyte_stencil_func _mesa_get_pack_ubyte_stencil_func (gl_format format)
References _mesa_problem(), MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, pack_ubyte_stencil_S8(), pack_ubyte_stencil_S8_Z24(), pack_ubyte_stencil_Z24_S8(), and pack_ubyte_stencil_Z32_FLOAT_X24S8().
gl_pack_uint_z_func _mesa_get_pack_uint_z_func (gl_format format)
References _mesa_problem(), MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, pack_uint_z_S8_Z24(), pack_uint_z_Z16(), pack_uint_z_Z24_S8(), pack_uint_z_Z32(), pack_uint_z_Z32_FLOAT(), and pack_uint_z_Z32_FLOAT_X24S8().
void _mesa_pack_colormask (gl_format format, const GLubyte colorMask[4], void * dst)
Convert a boolean color mask to a packed color where each channel of the packed value at dst will be 0 or ~0 depending on the colorMask.
References _mesa_get_format_bytes(), _mesa_get_format_datatype(), _mesa_get_format_max_bits(), _mesa_pack_float_rgba_row(), _mesa_problem(), GLubyte, GLushort, and NULL.
void _mesa_pack_float_rgba_row (gl_format format, GLuint n, const GLfloat src[][4], void * dst)
Pack a row of GLfloat rgba[4] values to the destination.
References _mesa_get_format_bytes(), _mesa_get_pack_float_rgba_function(), get_pack_float_rgba_row_function(), and GLubyte.
Referenced by _mesa_pack_colormask(), and accum_return().
void _mesa_pack_float_z_row (gl_format format, GLuint n, const GLfloat * src, void * dst)
References _mesa_problem(), GLushort, MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, and z32f_x24s8::z.
void _mesa_pack_ubyte_rgba_rect (gl_format format, GLuint width, GLuint height, const GLubyte * src, GLint srcRowStride, void * dst, GLint dstRowStride)
Pack a 2D image of ubyte RGBA pixels in the given format.
Parameters
srcRowStride source image row stride in bytes
dstRowStride destination image row stride in bytes
References _mesa_format_row_stride(), _mesa_pack_ubyte_rgba_row(), get_pack_ubyte_rgba_row_function(), and GLubyte.
Referenced by store_ubyte_texture().
void _mesa_pack_ubyte_rgba_row (gl_format format, GLuint n, const GLubyte src[][4], void * dst)
Pack a row of GLubyte rgba[4] values to the destination.
References _mesa_get_format_bytes(), _mesa_get_pack_ubyte_rgba_function(), get_pack_ubyte_rgba_row_function(), and GLubyte.
Referenced by _mesa_pack_ubyte_rgba_rect().
void _mesa_pack_ubyte_stencil_row (gl_format format, GLuint n, const GLubyte * src, void * dst)
References _mesa_problem(), GLubyte, MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, z32f_x24s8::x24s8, and z32f_x24s8::z.
void _mesa_pack_uint_24_8_depth_stencil_row (gl_format format, GLuint n, const GLuint * src, void * dst)
Incoming Z/stencil values are always in uint_24_8 format.
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, z32f_x24s8::x24s8, and z32f_x24s8::z.
void _mesa_pack_uint_z_row (gl_format format, GLuint n, const GLuint * src, void * dst)
The incoming Z values are always in the range [0, 0xffffffff].
References _mesa_problem(), GLushort, MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, and z32f_x24s8::z.
static pack_float_rgba_row_func get_pack_float_rgba_row_function (gl_format format) static
References MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_COUNT, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, pack_row_float_ARGB8888(), pack_row_float_ARGB8888_REV(), pack_row_float_BGR888(), pack_row_float_RGB565(), pack_row_float_RGB565_REV(), pack_row_float_RGB888(), pack_row_float_RGBA8888(), pack_row_float_RGBA8888_REV(), pack_row_float_XRGB8888(), pack_row_float_XRGB8888_REV(), and table.
Referenced by _mesa_pack_float_rgba_row().
static pack_ubyte_rgba_row_func get_pack_ubyte_rgba_row_function (gl_format format) static
References MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_COUNT, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, pack_row_ubyte_ARGB8888(), pack_row_ubyte_ARGB8888_REV(), pack_row_ubyte_BGR888(), pack_row_ubyte_RGB565(), pack_row_ubyte_RGB565_REV(), pack_row_ubyte_RGB888(), pack_row_ubyte_RGBA8888(), pack_row_ubyte_RGBA8888_REV(), pack_row_ubyte_XRGB8888(), pack_row_ubyte_XRGB8888_REV(), and table.
Referenced by _mesa_pack_ubyte_rgba_rect(), and _mesa_pack_ubyte_rgba_row().
static GLubyte linear_float_to_srgb_ubyte (GLfloat cl) inline static
References FLOAT_TO_UBYTE, GLubyte, and linear_to_srgb().
Referenced by pack_float_SARGB8(), pack_float_SL8(), pack_float_SLA8(), pack_float_SRGB8(), pack_float_SRGBA8(), and pack_float_XBGR8888_SRGB().
static GLfloat linear_to_srgb (GLfloat cl) inline static
References powf.
Referenced by linear_float_to_srgb_ubyte(), and linear_ubyte_to_srgb_ubyte().
static GLubyte linear_ubyte_to_srgb_ubyte (GLubyte cl) inline static
References FLOAT_TO_UBYTE, GLubyte, and linear_to_srgb().
Referenced by pack_ubyte_SARGB8(), pack_ubyte_SL8(), pack_ubyte_SLA8(), pack_ubyte_SRGB8(), and pack_ubyte_SRGBA8().
static void pack_float_A16 (const GLfloat src[4], void * dst) static
References ACOMP, GLushort, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_A8 (const GLfloat src[4], void * dst) static
References ACOMP, GLubyte, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ABGR2101010_UINT (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_2101010_US, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_AL1616 (const GLfloat src[4], void * dst) static
References ACOMP, GLushort, PACK_COLOR_1616, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_AL1616_REV (const GLfloat src[4], void * dst) static
References ACOMP, GLushort, PACK_COLOR_1616, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_AL44 (const GLfloat src[4], void * dst) static
References ACOMP, GLubyte, pack_ubyte_AL44(), RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_AL88 (const GLfloat src[4], void * dst) static
References ACOMP, GLubyte, pack_ubyte_AL88(), RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_AL88_REV (const GLfloat src[4], void * dst) static
References ACOMP, GLubyte, pack_ubyte_AL88_REV(), RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ALPHA_FLOAT16 (const GLfloat src[4], void * dst) static
References _mesa_float_to_half(), and ACOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ALPHA_FLOAT32 (const GLfloat src[4], void * dst) static
References ACOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ARGB1555 (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB1555().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ARGB1555_REV (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB1555_REV().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ARGB2101010 (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_2101010_US, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ARGB4444 (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB4444().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ARGB4444_REV (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB4444_REV().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ARGB8888 (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB8888().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_ARGB8888_REV (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB8888_REV().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_BGR888 (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_DUDV8 (const GLfloat src[4], void * dst) static
References CLAMP, F, FLOAT_TO_BYTE, GLbyte, GLushort, and PACK_COLOR_88.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_GR1616 (const GLfloat src[4], void * dst) static
References GCOMP, GLushort, PACK_COLOR_1616, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_GR88 (const GLfloat src[4], void * dst) static
References GCOMP, GLubyte, GLushort, PACK_COLOR_88, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_L16 (const GLfloat src[4], void * dst) static
References GLushort, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_L8 (const GLfloat src[4], void * dst) static
References GLubyte, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_LUMINANCE_ALPHA_FLOAT16 (const GLfloat src[4], void * dst) static
References _mesa_float_to_half(), ACOMP, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_LUMINANCE_ALPHA_FLOAT32 (const GLfloat src[4], void * dst) static
References ACOMP, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_LUMINANCE_FLOAT16 (const GLfloat src[4], void * dst) static
References _mesa_float_to_half(), and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_LUMINANCE_FLOAT32 (const GLfloat src[4], void * dst) static
References RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_R11_G11_B10_FLOAT (const GLfloat src[4], void * dst) static
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_R16 (const GLfloat src[4], void * dst) static
References GLushort, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_R8 (const GLfloat src[4], void * dst) static
References GLubyte, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RG1616 (const GLfloat src[4], void * dst) static
References GCOMP, GLushort, PACK_COLOR_1616, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RG88 (const GLfloat src[4], void * dst) static
References GCOMP, GLubyte, GLushort, PACK_COLOR_88, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RG_FLOAT16 (const GLfloat src[4], void * dst) static
References _mesa_float_to_half(), GCOMP, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RG_FLOAT32 (const GLfloat src[4], void * dst) static
References GCOMP, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGB332 (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, pack_ubyte_RGB332(), RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGB565 (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, pack_ubyte_RGB565(), RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGB565_REV (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, GLushort, PACK_COLOR_565_REV, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGB888 (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGB9_E5_FLOAT (const GLfloat src[4], void * dst) static
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGB_FLOAT16 (const GLfloat src[4], void * dst) static
References _mesa_float_to_half().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGB_FLOAT32 (const GLfloat src[4], void * dst) static
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGBA5551 (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_RGBA5551().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGBA8888 (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_RGBA8888().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGBA8888_REV (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_RGBA8888_REV().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGBA_16 (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGBA_FLOAT16 (const GLfloat src[4], void * dst) static
References _mesa_float_to_half().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_RGBA_FLOAT32 (const GLfloat src[4], void * dst) static
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SARGB8 (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLubyte, linear_float_to_srgb_ubyte(), PACK_COLOR_8888, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_A16 (const GLfloat src[4], void * dst) static
References ACOMP, CLAMP, FLOAT_TO_SHORT, and GLshort.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_A8 (const GLfloat src[4], void * dst) static
References ACOMP, CLAMP, FLOAT_TO_BYTE, and GLbyte.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_AL1616 (const GLfloat src[4], void * dst) static
References ACOMP, CLAMP, FLOAT_TO_SHORT, GLshort, PACK_COLOR_1616, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_AL88 (const GLfloat src[4], void * dst) static
References ACOMP, CLAMP, FLOAT_TO_BYTE, GLbyte, GLushort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_GR1616 (const GLfloat src[4], void * dst) static
References CLAMP, FLOAT_TO_SHORT, GCOMP, GLshort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_L16 (const GLfloat src[4], void * dst) static
References CLAMP, FLOAT_TO_SHORT, GLshort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_L8 (const GLfloat src[4], void * dst) static
References CLAMP, FLOAT_TO_BYTE, GLbyte, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_R16 (const GLfloat src[4], void * dst) static
References CLAMP, FLOAT_TO_SHORT, GLshort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_R8 (const GLfloat src[4], void * dst) static
References CLAMP, FLOAT_TO_BYTE, GLbyte, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_RG88_REV (const GLfloat src[4], void * dst) static
References CLAMP, FLOAT_TO_BYTE, GCOMP, GLbyte, GLushort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_RGB_16 (const GLfloat src[4], void * dst) static
References BCOMP, CLAMP, FLOAT_TO_SHORT, GCOMP, GLshort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_RGBA8888 (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, CLAMP, FLOAT_TO_BYTE, GCOMP, GLbyte, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_RGBA8888_REV (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, CLAMP, FLOAT_TO_BYTE, GCOMP, GLbyte, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_RGBA_16 (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, CLAMP, FLOAT_TO_SHORT, GCOMP, GLshort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SIGNED_RGBX8888 (const GLfloat src[4], void * dst) static
References BCOMP, CLAMP, FLOAT_TO_BYTE, GCOMP, GLbyte, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SL8 (const GLfloat src[4], void * dst) static
References GLubyte, linear_float_to_srgb_ubyte(), and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SLA8 (const GLfloat src[4], void * dst) static
References ACOMP, CLAMPED_FLOAT_TO_UBYTE, GLubyte, GLushort, linear_float_to_srgb_ubyte(), PACK_COLOR_88, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SRGB8 (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, linear_float_to_srgb_ubyte(), and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_SRGBA8 (const GLfloat src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLubyte, linear_float_to_srgb_ubyte(), PACK_COLOR_8888, RCOMP, and UNCLAMPED_FLOAT_TO_UBYTE.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XBGR16161616_FLOAT (const GLfloat src[4], void * dst) static
References _mesa_float_to_half(), BCOMP, GCOMP, GLushort, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XBGR16161616_SNORM (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLushort, RCOMP, and UNCLAMPED_FLOAT_TO_SHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XBGR16161616_UNORM (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLushort, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XBGR32323232_FLOAT (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XBGR8888_SNORM (const GLfloat src[4], void * dst) static
References BCOMP, CLAMP, FLOAT_TO_BYTE, GCOMP, GLbyte, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XBGR8888_SRGB (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, linear_float_to_srgb_ubyte(), PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XRGB1555_UNORM (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_XRGB1555_UNORM().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XRGB2101010_UNORM (const GLfloat src[4], void * dst) static
References BCOMP, GCOMP, GLushort, PACK_COLOR_2101010_US, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XRGB4444_UNORM (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_XRGB4444_UNORM().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XRGB8888 (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_XRGB8888().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_XRGB8888_REV (const GLfloat src[4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_XRGB8888_REV().
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_YCBCR (const GLfloat src[4], void * dst) static
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_YCBCR_REV (const GLfloat src[4], void * dst) static
Referenced by _mesa_get_pack_float_rgba_function().
static void pack_float_z_S8_Z24 (const GLfloat * src, void * dst) static
Referenced by _mesa_get_pack_float_z_func().
static void pack_float_z_Z16 (const GLfloat * src, void * dst) static
References GLushort.
Referenced by _mesa_get_pack_float_z_func().
static void pack_float_z_Z24_S8 (const GLfloat * src, void * dst) static
Pack float Z pixels.
Referenced by _mesa_get_pack_float_z_func().
static void pack_float_z_Z32 (const GLfloat * src, void * dst) static
Referenced by _mesa_get_pack_float_z_func().
static void pack_float_z_Z32_FLOAT (const GLfloat * src, void * dst) static
Referenced by _mesa_get_pack_float_z_func().
static void pack_row_float_ARGB8888 (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB8888().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_ARGB8888_REV (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_ARGB8888_REV().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_BGR888 (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_RGB565 (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, GLushort, and pack_ubyte_RGB565().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_RGB565_REV (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, GLushort, and pack_ubyte_RGB565_REV().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_RGB888 (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_RGBA8888 (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_RGBA8888().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_RGBA8888_REV (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_RGBA8888_REV().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_XRGB8888 (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_XRGB8888().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_float_XRGB8888_REV (GLuint n, const GLfloat src[][4], void * dst) static
References _mesa_unclamped_float_rgba_to_ubyte(), GLubyte, and pack_ubyte_XRGB8888_REV().
Referenced by get_pack_float_rgba_row_function().
static void pack_row_ubyte_ARGB8888 (GLuint n, const GLubyte src[][4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_ARGB8888_REV (GLuint n, const GLubyte src[][4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_BGR888 (GLuint n, const GLubyte src[][4], void * dst) static
References BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_RGB565 (GLuint n, const GLubyte src[][4], void * dst) static
References GLushort, and pack_ubyte_RGB565().
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_RGB565_REV (GLuint n, const GLubyte src[][4], void * dst) static
References GLushort, and pack_ubyte_RGB565_REV().
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_RGB888 (GLuint n, const GLubyte src[][4], void * dst) static
References BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_RGBA8888 (GLuint n, const GLubyte src[][4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_RGBA8888_REV (GLuint n, const GLubyte src[][4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_XRGB8888 (GLuint n, const GLubyte src[][4], void * dst) static
References BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_row_ubyte_XRGB8888_REV (GLuint n, const GLubyte src[][4], void * dst) static
References BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by get_pack_ubyte_rgba_row_function().
static void pack_ubyte_A16 (const GLubyte src[4], void * dst) static
References ACOMP, GLushort, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_A8 (const GLubyte src[4], void * dst) static
References ACOMP, and GLubyte.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_ABGR2101010_UINT (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_2101010_US, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_AL1616 (const GLubyte src[4], void * dst) static
References ACOMP, GLushort, PACK_COLOR_1616, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_AL1616_REV (const GLubyte src[4], void * dst) static
References ACOMP, GLushort, PACK_COLOR_1616, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_AL44 (const GLubyte src[4], void * dst) static
References ACOMP, GLubyte, PACK_COLOR_44, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_AL44().
static void pack_ubyte_AL88 (const GLubyte src[4], void * dst) static
References ACOMP, GLushort, PACK_COLOR_88, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_AL88().
static void pack_ubyte_AL88_REV (const GLubyte src[4], void * dst) static
References ACOMP, GLushort, PACK_COLOR_88, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_AL88_REV().
static void pack_ubyte_ALPHA_FLOAT16 (const GLubyte src[4], void * dst) static
References _mesa_float_to_half(), ACOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_ALPHA_FLOAT32 (const GLubyte src[4], void * dst) static
References ACOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_ARGB1555 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_1555, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_ARGB1555().
static void pack_ubyte_ARGB1555_REV (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_1555, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_ARGB1555_REV().
static void pack_ubyte_ARGB2101010 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_2101010_US, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_ARGB4444 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_4444, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_ARGB4444().
static void pack_ubyte_ARGB4444_REV (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_4444, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_ARGB4444_REV().
static void pack_ubyte_ARGB8888 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_float_ARGB8888(), and pack_row_float_ARGB8888().
static void pack_ubyte_ARGB8888_REV (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_float_ARGB8888_REV(), and pack_row_float_ARGB8888_REV().
static void pack_ubyte_BGR888 (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_DUDV8 (const GLubyte src[4], void * dst) static
References GLushort, and PACK_COLOR_88.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_GR1616 (const GLubyte src[4], void * dst) static
References GCOMP, GLushort, PACK_COLOR_1616, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_GR88 (const GLubyte src[4], void * dst) static
References GCOMP, GLubyte, PACK_COLOR_88, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_L16 (const GLubyte src[4], void * dst) static
References GLushort, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_L8 (const GLubyte src[4], void * dst) static
References GLubyte, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_LUMINANCE_ALPHA_FLOAT16 (const GLubyte src[4], void * dst) static
References _mesa_float_to_half(), ACOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_LUMINANCE_ALPHA_FLOAT32 (const GLubyte src[4], void * dst) static
References ACOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_LUMINANCE_FLOAT16 (const GLubyte src[4], void * dst) static
References _mesa_float_to_half(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_LUMINANCE_FLOAT32 (const GLubyte src[4], void * dst) static
References RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_R11_G11_B10_FLOAT (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_R16 (const GLubyte src[4], void * dst) static
References GLushort, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_R8 (const GLubyte src[4], void * dst) static
References GLubyte, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RG1616 (const GLubyte src[4], void * dst) static
References GCOMP, GLushort, PACK_COLOR_1616, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RG88 (const GLubyte src[4], void * dst) static
References GCOMP, GLubyte, PACK_COLOR_88, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RG_FLOAT16 (const GLubyte src[4], void * dst) static
References _mesa_float_to_half(), GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RG_FLOAT32 (const GLubyte src[4], void * dst) static
References GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RGB332 (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, PACK_COLOR_332, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_RGB332().
static void pack_ubyte_RGB565 (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLushort, PACK_COLOR_565, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_float_RGB565(), pack_row_float_RGB565(), and pack_row_ubyte_RGB565().
static void pack_ubyte_RGB565_REV (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLushort, PACK_COLOR_565_REV, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_row_float_RGB565_REV(), and pack_row_ubyte_RGB565_REV().
static void pack_ubyte_RGB888 (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLubyte, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RGB9_E5_FLOAT (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RGB_FLOAT16 (const GLubyte src[4], void * dst) static
References _mesa_float_to_half(), and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RGB_FLOAT32 (const GLubyte src[4], void * dst) static
References UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RGBA5551 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, PACK_COLOR_5551, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_RGBA5551().
static void pack_ubyte_RGBA8888 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_float_RGBA8888(), and pack_row_float_RGBA8888().
static void pack_ubyte_RGBA8888_REV (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_float_RGBA8888_REV(), and pack_row_float_RGBA8888_REV().
static void pack_ubyte_RGBA_16 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RGBA_FLOAT16 (const GLubyte src[4], void * dst) static
References _mesa_float_to_half(), and UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_RGBA_FLOAT32 (const GLubyte src[4], void * dst) static
References UBYTE_TO_FLOAT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_SARGB8 (const GLubyte src[4], void * dst) static
References ACOMP, GLubyte, linear_ubyte_to_srgb_ubyte(), PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_SL8 (const GLubyte src[4], void * dst) static
References GLubyte, linear_ubyte_to_srgb_ubyte(), and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_SLA8 (const GLubyte src[4], void * dst) static
References ACOMP, GLubyte, GLushort, linear_ubyte_to_srgb_ubyte(), PACK_COLOR_88, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_SRGB8 (const GLubyte src[4], void * dst) static
References GLubyte, linear_ubyte_to_srgb_ubyte(), and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_SRGBA8 (const GLubyte src[4], void * dst) static
References ACOMP, BCOMP, GCOMP, GLubyte, linear_ubyte_to_srgb_ubyte(), PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_stencil_S8 (const GLubyte * src, void * dst) static
References GLubyte.
Referenced by _mesa_get_pack_ubyte_stencil_func().
static void pack_ubyte_stencil_S8_Z24 (const GLubyte * src, void * dst) static
Referenced by _mesa_get_pack_ubyte_stencil_func().
static void pack_ubyte_stencil_Z24_S8 (const GLubyte * src, void * dst) static
Pack ubyte stencil pixels.
Referenced by _mesa_get_pack_ubyte_stencil_func().
static void pack_ubyte_stencil_Z32_FLOAT_X24S8 (const GLubyte * src, void * dst) static
Referenced by _mesa_get_pack_ubyte_stencil_func().
static void pack_ubyte_XBGR16161616_UNORM (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLushort, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_XRGB1555_UNORM (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLushort, PACK_COLOR_1555, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_XRGB1555_UNORM().
static void pack_ubyte_XRGB2101010_UNORM (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLushort, PACK_COLOR_2101010_US, RCOMP, and UBYTE_TO_USHORT.
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_XRGB4444_UNORM (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, GLushort, PACK_COLOR_4444, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), and pack_float_XRGB4444_UNORM().
static void pack_ubyte_XRGB8888 (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_float_XRGB8888(), and pack_row_float_XRGB8888().
static void pack_ubyte_XRGB8888_REV (const GLubyte src[4], void * dst) static
References BCOMP, GCOMP, PACK_COLOR_8888, and RCOMP.
Referenced by _mesa_get_pack_ubyte_rgba_function(), pack_float_XRGB8888_REV(), and pack_row_float_XRGB8888_REV().
static void pack_ubyte_YCBCR (const GLubyte src[4], void * dst) static
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_ubyte_YCBCR_REV (const GLubyte src[4], void * dst) static
Referenced by _mesa_get_pack_ubyte_rgba_function().
static void pack_uint_z_S8_Z24 (const GLuint * src, void * dst) static
Referenced by _mesa_get_pack_uint_z_func().
static void pack_uint_z_Z16 (const GLuint * src, void * dst) static
References GLushort.
Referenced by _mesa_get_pack_uint_z_func().
static void pack_uint_z_Z24_S8 (const GLuint * src, void * dst) static
Pack uint Z pixels.
The incoming src value is always in the range [0, 2^32-1].
Referenced by _mesa_get_pack_uint_z_func().
static void pack_uint_z_Z32 (const GLuint * src, void * dst) static
Referenced by _mesa_get_pack_uint_z_func().
static void pack_uint_z_Z32_FLOAT (const GLuint * src, void * dst) static
Referenced by _mesa_get_pack_uint_z_func().
static void pack_uint_z_Z32_FLOAT_X24S8 (const GLuint * src, void * dst) static
Referenced by _mesa_get_pack_uint_z_func().