Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
format_unpack.h File Reference
Functions
GLfloat _mesa_nonlinear_to_linear (GLubyte cs8)
Convert an 8-bit sRGB value from non-linear space to a linear RGB value in [0, 1].
void _mesa_unpack_rgba_row (gl_format format, GLuint n, const void *src, GLfloat dst[][4])
Unpack rgba colors, returning as GLfloat values.
void _mesa_unpack_ubyte_rgba_row (gl_format format, GLuint n, const void *src, GLubyte dst[][4])
Unpack rgba colors, returning as GLubyte values.
void _mesa_unpack_uint_rgba_row (gl_format format, GLuint n, const void *src, GLuint dst[][4])
void _mesa_unpack_rgba_block (gl_format format, const void *src, GLint srcRowStride, GLfloat dst[][4], GLint dstRowStride, GLuint x, GLuint y, GLuint width, GLuint height)
Unpack a 2D rect of pixels returning float RGBA colors.
void _mesa_unpack_float_z_row (gl_format format, GLuint n, const void *src, GLfloat *dst)
Unpack Z values.
void _mesa_unpack_uint_z_row (gl_format format, GLuint n, const void *src, GLuint *dst)
Unpack Z values.
void _mesa_unpack_ubyte_stencil_row (gl_format format, GLuint n, const void *src, GLubyte *dst)
void _mesa_unpack_uint_24_8_depth_stencil_row (gl_format format, GLuint n, const void *src, GLuint *dst)
Function Documentation
GLfloat _mesa_nonlinear_to_linear (GLubyte cs8)
Convert an 8-bit sRGB value from non-linear space to a linear RGB value in [0, 1].
Implemented with a 256-entry lookup table.
References table, and UBYTE_TO_FLOAT.
Referenced by fetch_etc2_srgb8(), fetch_etc2_srgb8_alpha8_eac(), fetch_etc2_srgb8_punchthrough_alpha1(), fetch_srgb_dxt1(), fetch_srgba_dxt1(), fetch_srgba_dxt3(), fetch_srgba_dxt5(), unpack_SARGB8(), unpack_SL8(), unpack_SLA8(), unpack_SRGB8(), unpack_SRGBA8(), and unpack_XBGR8888_SRGB().
void _mesa_unpack_float_z_row (gl_format format, GLuint n, const void * src, GLfloat * dst)
Unpack Z values.
The returned values will always be in the range [0.0, 1.0].
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, unpack_float_z_X8_Z24(), unpack_float_z_Z16(), unpack_float_z_Z24_X8(), unpack_float_z_Z32(), unpack_float_z_Z32F(), and unpack_float_z_Z32X24S8().
Referenced by get_tex_depth(), read_depth_pixels(), and slow_read_depth_stencil_pixels_separate().
void _mesa_unpack_rgba_block (gl_format format, const void * src, GLint srcRowStride, GLfloat dst[][4], GLint dstRowStride, GLuint x, GLuint y, GLuint width, GLuint height)
Unpack a 2D rect of pixels returning float RGBA colors.
Parameters
format the source image format
src start address of the source image
srcRowStride source image row stride in bytes
dst start address of the dest image
dstRowStride dest image row stride in bytes
x source image start X pos
y source image start Y pos
width width of rect region to convert
height height of rect region to convert
References _mesa_get_format_bytes(), get_unpack_rgba_function(), and GLubyte.
void _mesa_unpack_rgba_row (gl_format format, GLuint n, const void * src, GLfloat dst[][4])
Unpack rgba colors, returning as GLfloat values.
References get_unpack_rgba_function().
Referenced by _mesa_unpack_ubyte_rgba_row(), accum_or_load(), accum_return(), get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_unpack_ubyte_rgba_row (gl_format format, GLuint n, const void * src, GLubyte dst[][4])
Unpack rgba colors, returning as GLubyte values.
This should usually only be used for unpacking formats that use 8 bits or less per channel.
References _mesa_unpack_rgba_row(), MESA_FORMAT_A8, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_GR88, MESA_FORMAT_I8, MESA_FORMAT_L8, MESA_FORMAT_R8, MESA_FORMAT_RG88, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGBA5551, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, UNCLAMPED_FLOAT_TO_UBYTE, unpack_ubyte_A8(), unpack_ubyte_AL44(), unpack_ubyte_AL88(), unpack_ubyte_AL88_REV(), unpack_ubyte_ARGB1555(), unpack_ubyte_ARGB1555_REV(), unpack_ubyte_ARGB4444(), unpack_ubyte_ARGB4444_REV(), unpack_ubyte_ARGB8888(), unpack_ubyte_ARGB8888_REV(), unpack_ubyte_BGR888(), unpack_ubyte_GR88(), unpack_ubyte_I8(), unpack_ubyte_L8(), unpack_ubyte_R8(), unpack_ubyte_RG88(), unpack_ubyte_RGB332(), unpack_ubyte_RGB565(), unpack_ubyte_RGB565_REV(), unpack_ubyte_RGB888(), unpack_ubyte_RGBA5551(), unpack_ubyte_RGBA8888(), unpack_ubyte_RGBA8888_REV(), unpack_ubyte_RGBX8888(), unpack_ubyte_RGBX8888_REV(), unpack_ubyte_XRGB8888(), and unpack_ubyte_XRGB8888_REV().
void _mesa_unpack_ubyte_stencil_row (gl_format format, GLuint n, const void * src, GLubyte * dst)
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, unpack_ubyte_s_S8(), unpack_ubyte_s_S8_Z24(), unpack_ubyte_s_Z24_S8(), and unpack_ubyte_s_Z32_FLOAT_X24S8().
Referenced by fast_read_depth_stencil_pixels_separate(), read_stencil_pixels(), and slow_read_depth_stencil_pixels_separate().
void _mesa_unpack_uint_24_8_depth_stencil_row (gl_format format, GLuint n, const void * src, GLuint * dst)
References _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, NULL, unpack_uint_24_8_depth_stencil_S8_Z24(), and unpack_uint_24_8_depth_stencil_Z24_S8().
Referenced by fast_read_depth_stencil_pixels().
void _mesa_unpack_uint_rgba_row (gl_format format, GLuint n, const void * src, GLuint dst[][4])
References __FUNCTION__, _mesa_get_format_name(), _mesa_problem(), MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_ALPHA_UINT32, MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB2101010_UINT, MESA_FORMAT_ARGB8888, MESA_FORMAT_INTENSITY_INT16, MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_INTENSITY_UINT8, MESA_FORMAT_LUMINANCE_ALPHA_INT16, MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT8, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_LUMINANCE_UINT32, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_R_INT16, MESA_FORMAT_R_INT32, MESA_FORMAT_R_INT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_RG_INT16, MESA_FORMAT_RG_INT32, MESA_FORMAT_RG_INT8, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_INT16, MESA_FORMAT_RGB_INT32, MESA_FORMAT_RGB_INT8, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB8888, NULL, unpack_int_rgba_ABGR2101010_UINT(), unpack_int_rgba_ALPHA_INT16(), unpack_int_rgba_ALPHA_INT8(), unpack_int_rgba_ALPHA_UINT16(), unpack_int_rgba_ALPHA_UINT32(), unpack_int_rgba_ALPHA_UINT8(), unpack_int_rgba_ARGB2101010(), unpack_int_rgba_ARGB2101010_UINT(), unpack_int_rgba_ARGB8888(), unpack_int_rgba_INTENSITY_INT16(), unpack_int_rgba_INTENSITY_INT8(), unpack_int_rgba_INTENSITY_UINT16(), unpack_int_rgba_INTENSITY_UINT32(), unpack_int_rgba_INTENSITY_UINT8(), unpack_int_rgba_LUMINANCE_ALPHA_INT16(), unpack_int_rgba_LUMINANCE_ALPHA_INT8(), unpack_int_rgba_LUMINANCE_ALPHA_UINT16(), unpack_int_rgba_LUMINANCE_ALPHA_UINT32(), unpack_int_rgba_LUMINANCE_ALPHA_UINT8(), unpack_int_rgba_LUMINANCE_INT16(), unpack_int_rgba_LUMINANCE_INT8(), unpack_int_rgba_LUMINANCE_UINT16(), unpack_int_rgba_LUMINANCE_UINT32(), unpack_int_rgba_LUMINANCE_UINT8(), unpack_int_rgba_R_INT16(), unpack_int_rgba_R_INT8(), unpack_int_rgba_R_UINT16(), unpack_int_rgba_R_UINT32(), unpack_int_rgba_R_UINT8(), unpack_int_rgba_RG_INT16(), unpack_int_rgba_RG_INT8(), unpack_int_rgba_RG_UINT16(), unpack_int_rgba_RG_UINT32(), unpack_int_rgba_RG_UINT8(), unpack_int_rgba_RGB_INT16(), unpack_int_rgba_RGB_INT8(), unpack_int_rgba_RGB_UINT16(), unpack_int_rgba_RGB_UINT32(), unpack_int_rgba_RGB_UINT8(), unpack_int_rgba_RGBA_INT16(), unpack_int_rgba_RGBA_INT8(), unpack_int_rgba_RGBA_UINT16(), unpack_int_rgba_RGBA_UINT32(), unpack_int_rgba_RGBA_UINT8(), unpack_int_rgba_XBGR16161616_SINT(), unpack_int_rgba_XBGR16161616_UINT(), unpack_int_rgba_XBGR32323232_UINT(), unpack_int_rgba_XBGR8888_SINT(), unpack_int_rgba_XBGR8888_UINT(), and unpack_int_rgba_XRGB8888().
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_unpack_uint_z_row (gl_format format, GLuint n, const void * src, GLuint * dst)
Unpack Z values.
The returned values will always be in the range [0, 0xffffffff].
References _mesa_get_format_name(), _mesa_problem(), GLubyte, MESA_FORMAT_S8_Z24, MESA_FORMAT_X8_Z24, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, NULL, unpack_uint_z_X8_Z24(), unpack_uint_z_Z16(), unpack_uint_z_Z24_X8(), unpack_uint_z_Z32(), unpack_uint_z_Z32_FLOAT(), and unpack_uint_z_Z32_FLOAT_X24S8().
Referenced by fast_read_depth_stencil_pixels_separate(), and read_uint_depth_pixels().