Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
framebuffer.c File Reference
#include "glheader.h"
#include "imports.h"
#include "blend.h"
#include "buffers.h"
#include "context.h"
#include "enums.h"
#include "formats.h"
#include "macros.h"
#include "mtypes.h"
#include "fbobject.h"
#include "framebuffer.h"
#include "renderbuffer.h"
#include "texobj.h"
#include "glformats.h"
Functions
static void compute_depth_max (struct gl_framebuffer *fb)
Functions for allocating/managing framebuffers and renderbuffers.
struct gl_framebuffer * _mesa_create_framebuffer (const struct gl_config *visual)
Create and initialize a gl_framebuffer object.
struct gl_framebuffer * _mesa_new_framebuffer (struct gl_context *ctx, GLuint name)
Allocate a new gl_framebuffer object.
void _mesa_initialize_window_framebuffer (struct gl_framebuffer *fb, const struct gl_config *visual)
Initialize a gl_framebuffer object.
void _mesa_initialize_user_framebuffer (struct gl_framebuffer *fb, GLuint name)
Initialize a user-created gl_framebuffer object.
void _mesa_destroy_framebuffer (struct gl_framebuffer *fb)
Deallocate buffer and everything attached to it.
void _mesa_free_framebuffer_data (struct gl_framebuffer *fb)
Free all the data hanging off the given gl_framebuffer, but don't free the gl_framebuffer object itself.
void _mesa_reference_framebuffer_ (struct gl_framebuffer **ptr, struct gl_framebuffer *fb)
Set *ptr to point to fb, with refcounting and locking.
void _mesa_resize_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb, GLuint width, GLuint height)
Resize the given framebuffer's renderbuffers to the new width and height.
void _mesa_resizebuffers (struct gl_context *ctx)
XXX THIS IS OBSOLETE - drivers should take care of detecting window size changes and act accordingly, likely calling _mesa_resize_framebuffer().
void GLAPIENTRY _mesa_ResizeBuffersMESA (void)
static void update_framebuffer_size (struct gl_context *ctx, struct gl_framebuffer *fb)
Examine all the framebuffer's renderbuffers to update the Width/Height fields of the framebuffer.
void _mesa_update_draw_buffer_bounds (struct gl_context *ctx)
Update the context's current drawing buffer's Xmin, Xmax, Ymin, Ymax fields.
void _mesa_update_framebuffer_visual (struct gl_context *ctx, struct gl_framebuffer *fb)
The glGet queries of the framebuffer red/green/blue size, stencil size, etc.
static void update_color_draw_buffers (struct gl_context *ctx, struct gl_framebuffer *fb)
Update the (derived) list of color drawing renderbuffer pointers.
static void update_color_read_buffer (struct gl_context *ctx, struct gl_framebuffer *fb)
Update the (derived) color read renderbuffer pointer.
static void update_framebuffer (struct gl_context *ctx, struct gl_framebuffer *fb)
Update a gl_framebuffer's derived state.
void _mesa_update_framebuffer (struct gl_context *ctx)
Update state related to the current draw/read framebuffers.
static GLboolean renderbuffer_exists (struct gl_context *ctx, struct gl_framebuffer *fb, GLenum format, GLboolean reading)
Check if the renderbuffer for a read/draw operation exists.
GLboolean _mesa_source_buffer_exists (struct gl_context *ctx, GLenum format)
Check if the renderbuffer for a read operation (glReadPixels, glCopyPixels, glCopyTex[Sub]Image, etc) exists.
GLboolean _mesa_dest_buffer_exists (struct gl_context *ctx, GLenum format)
As above, but for drawing operations.
GLenum _mesa_get_color_read_format (struct gl_context *ctx)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES query.
GLenum _mesa_get_color_read_type (struct gl_context *ctx)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_TYPE_OES query.
struct gl_renderbuffer * _mesa_get_read_renderbuffer_for_format (const struct gl_context *ctx, GLenum format)
Returns the read renderbuffer for the specified format.
void _mesa_print_framebuffer (const struct gl_framebuffer *fb)
Print framebuffer info to stderr, for debugging.
Function Documentation
struct gl_framebuffer* _mesa_create_framebuffer (const struct gl_config * visual) read
Create and initialize a gl_framebuffer object.
This is intended for creating window_system framebuffers, not generic framebuffer objects ala GL_EXT_framebuffer_object.
See Also
_mesa_new_framebuffer
References _mesa_initialize_window_framebuffer(), and CALLOC_STRUCT.
GLboolean _mesa_dest_buffer_exists (struct gl_context * ctx, GLenum format)
As above, but for drawing operations.
References gl_context::DrawBuffer, and renderbuffer_exists().
Referenced by _mesa_CopyPixels(), and _mesa_DrawPixels().
void _mesa_destroy_framebuffer (struct gl_framebuffer * fb)
Deallocate buffer and everything attached to it.
Typically called via the gl_framebuffer->Delete() method.
References _mesa_free_framebuffer_data().
Referenced by _mesa_initialize_user_framebuffer(), and _mesa_initialize_window_framebuffer().
void _mesa_free_framebuffer_data (struct gl_framebuffer * fb)
Free all the data hanging off the given gl_framebuffer, but don't free the gl_framebuffer object itself.
References _mesa_reference_renderbuffer(), _mesa_reference_texobj(), ASSERT, gl_framebuffer::Attachment, BUFFER_COUNT, gl_framebuffer::Mutex, NULL, gl_framebuffer::RefCount, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Texture, and gl_renderbuffer_attachment::Type.
Referenced by _mesa_destroy_framebuffer().
GLenum _mesa_get_color_read_format (struct gl_context * ctx)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES query.
References gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_get_format_datatype(), gl_renderbuffer::Format, MESA_FORMAT_ARGB8888, MESA_FORMAT_RGB565, and gl_context::ReadBuffer.
Referenced by _mesa_ReadnPixelsARB(), and find_custom_value().
GLenum _mesa_get_color_read_type (struct gl_context * ctx)
Used to answer the GL_IMPLEMENTATION_COLOR_READ_TYPE_OES query.
References gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_get_format_datatype(), gl_renderbuffer::Format, MESA_FORMAT_RGB565, and gl_context::ReadBuffer.
Referenced by _mesa_ReadnPixelsARB(), and find_custom_value().
struct gl_renderbuffer* _mesa_get_read_renderbuffer_for_format (const struct gl_context * ctx, GLenum format) read
Returns the read renderbuffer for the specified format.
References gl_framebuffer::_ColorReadBufferIndex, _mesa_is_color_format(), _mesa_is_depth_format(), _mesa_is_depthstencil_format(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::ReadBuffer, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by _mesa_ReadnPixelsARB(), _mesa_readpixels_needs_slow_path(), copytexture_error_check(), readpixels_can_use_memcpy(), and readpixels_memcpy().
void _mesa_initialize_user_framebuffer (struct gl_framebuffer * fb, GLuint name)
Initialize a user-created gl_framebuffer object.
See Also
_mesa_initialize_window_framebuffer
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorReadBufferIndex, _mesa_destroy_framebuffer(), gl_framebuffer::_NumColorDrawBuffers, BUFFER_COLOR0, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, gl_framebuffer::Delete, gl_framebuffer::Mutex, gl_framebuffer::Name, and gl_framebuffer::RefCount.
Referenced by _mesa_new_framebuffer().
void _mesa_initialize_window_framebuffer (struct gl_framebuffer * fb, const struct gl_config * visual)
Initialize a gl_framebuffer object.
Typically used to initialize window system-created framebuffers, not user-created framebuffers.
See Also
_mesa_initialize_user_framebuffer
References gl_framebuffer::_AllColorBuffersFixedPoint, gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorReadBufferIndex, gl_framebuffer::_HasSNormOrFloatColorBuffer, _mesa_destroy_framebuffer(), gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::_Status, BUFFER_BACK_LEFT, BUFFER_FRONT_LEFT, gl_framebuffer::ColorDrawBuffer, gl_framebuffer::ColorReadBuffer, compute_depth_max(), gl_framebuffer::Delete, gl_config::doubleBufferMode, gl_config::floatMode, gl_framebuffer::Mutex, gl_framebuffer::RefCount, and gl_framebuffer::Visual.
Referenced by _mesa_create_framebuffer().
struct gl_framebuffer* _mesa_new_framebuffer (struct gl_context * ctx, GLuint name) read
Allocate a new gl_framebuffer object.
This is the default function for ctx->Driver.NewFramebuffer(). This is for allocating user-created framebuffers, not window-system framebuffers!
See Also
_mesa_create_framebuffer
References _mesa_initialize_user_framebuffer(), CALLOC_STRUCT, and void().
void _mesa_print_framebuffer (const struct gl_framebuffer * fb)
Print framebuffer info to stderr, for debugging.
References _mesa_get_format_name(), _mesa_lookup_enum_by_nr(), gl_framebuffer::_Status, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer_attachment::Complete, gl_renderbuffer_attachment::CubeMapFace, gl_texture_image::Depth, gl_renderbuffer::Format, gl_texture_image::Height, gl_renderbuffer::Height, gl_framebuffer::Height, gl_texture_object::Name, gl_renderbuffer::Name, gl_framebuffer::Name, gl_renderbuffer_attachment::Renderbuffer, gl_texture_image::TexFormat, gl_renderbuffer::TexImage, gl_renderbuffer_attachment::Texture, gl_renderbuffer_attachment::TextureLevel, gl_renderbuffer_attachment::Type, gl_texture_image::Width, gl_renderbuffer::Width, gl_framebuffer::Width, and gl_renderbuffer_attachment::Zoffset.
void _mesa_reference_framebuffer_ (struct gl_framebuffer ** ptr, struct gl_framebuffer * fb)
Set *ptr to point to fb, with refcounting and locking.
This is normally only called from the _mesa_reference_framebuffer() macro when there's a real pointer change.
References ASSERT, gl_framebuffer::Delete, gl_framebuffer::Mutex, NULL, and gl_framebuffer::RefCount.
Referenced by _mesa_reference_framebuffer().
void _mesa_resize_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb, GLuint width, GLuint height)
Resize the given framebuffer's renderbuffers to the new width and height.
This should only be used for window-system framebuffers, not user-created renderbuffers (i.e. made with GL_EXT_framebuffer_object). This will typically be called via ctx->Driver.ResizeBuffers() or directly from a device driver.
Note
it's possible for ctx to be null since a window can be resized without a currently bound rendering context.
References _mesa_error(), _mesa_is_winsys_fbo(), _mesa_update_draw_buffer_bounds(), _NEW_BUFFERS, gl_renderbuffer::AllocStorage, ASSERT, gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer::Height, gl_framebuffer::Height, gl_renderbuffer::InternalFormat, gl_context::NewState, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer_attachment::Type, gl_renderbuffer::Width, and gl_framebuffer::Width.
void _mesa_resizebuffers (struct gl_context * ctx)
XXX THIS IS OBSOLETE - drivers should take care of detecting window size changes and act accordingly, likely calling _mesa_resize_framebuffer().
GL_MESA_resize_buffers extension.
When this function is called, we'll ask the window system how large the current window is. If it's a new size, we'll call the driver's ResizeBuffers function. The driver will then resize its color buffers as needed, and maybe call the swrast's routine for reallocating swrast-managed depth/stencil/accum/etc buffers.
Note
This function should only be called through the GL API, not from device drivers (as was done in the past).
References _mesa_debug(), _mesa_is_winsys_fbo(), _NEW_BUFFERS, gl_context::Driver, FLUSH_VERTICES, dd_function_table::GetBufferSize, gl_framebuffer::Height, MESA_VERBOSE, gl_context::NewState, dd_function_table::ResizeBuffers, VERBOSE_API, gl_framebuffer::Width, gl_context::WinSysDrawBuffer, and gl_context::WinSysReadBuffer.
Referenced by _mesa_make_current(), and _mesa_ResizeBuffersMESA().
void GLAPIENTRY _mesa_ResizeBuffersMESA (void)
References _mesa_resizebuffers().
Referenced by _mesa_initialize_exec_table().
GLboolean _mesa_source_buffer_exists (struct gl_context * ctx, GLenum format)
Check if the renderbuffer for a read operation (glReadPixels, glCopyPixels, glCopyTex[Sub]Image, etc) exists.
Parameters
format a basic image format such as GL_RGB, GL_RGBA, GL_ALPHA, GL_DEPTH_COMPONENT, etc. or GL_COLOR, GL_DEPTH, GL_STENCIL.
Returns
GL_TRUE if buffer exists, GL_FALSE otherwise
References gl_context::ReadBuffer, and renderbuffer_exists().
Referenced by _mesa_CopyPixels(), _mesa_ReadnPixelsARB(), copytexsubimage_error_check(), and copytexture_error_check().
void _mesa_update_draw_buffer_bounds (struct gl_context * ctx)
Update the context's current drawing buffer's Xmin, Xmax, Ymin, Ymax fields.
These values are computed from the buffer's width and height and the scissor box, if it's enabled.
Parameters
ctx the GL context.
References _mesa_is_user_fbo(), gl_framebuffer::_Xmax, gl_framebuffer::_Xmin, gl_framebuffer::_Ymax, gl_framebuffer::_Ymin, ASSERT, gl_context::DrawBuffer, gl_scissor_attrib::Enabled, gl_scissor_attrib::Height, gl_framebuffer::Height, gl_context::Scissor, update_framebuffer_size(), gl_scissor_attrib::Width, gl_framebuffer::Width, gl_scissor_attrib::X, and gl_scissor_attrib::Y.
Referenced by _mesa_resize_framebuffer(), and _mesa_update_state_locked().
void _mesa_update_framebuffer (struct gl_context * ctx)
Update state related to the current draw/read framebuffers.
References _mesa_update_clamp_fragment_color(), _mesa_update_clamp_vertex_color(), gl_context::DrawBuffer, gl_context::ReadBuffer, and update_framebuffer().
Referenced by _mesa_update_state_locked().
void _mesa_update_framebuffer_visual (struct gl_context * ctx, struct gl_framebuffer * fb)
The glGet queries of the framebuffer red/green/blue size, stencil size, etc.
are satisfied by the fields of ctx->DrawBuffer->Visual. These can change depending on the renderbuffer bindings. This function updates the given framebuffer's Visual from the current renderbuffer bindings.
This may apply to user-created framebuffers or window system framebuffers.
Also note: ctx->DrawBuffer->Visual.depthBits might not equal ctx->DrawBuffer->Attachment[BUFFER_DEPTH].Renderbuffer.DepthBits. The former one is used to convert floating point depth values into integer Z values.
References _mesa_get_format_base_format(), _mesa_get_format_bits(), _mesa_get_format_color_encoding(), _mesa_get_format_datatype(), _mesa_is_legal_color_format(), gl_framebuffer::_Status, gl_config::accumAlphaBits, gl_config::accumBlueBits, gl_config::accumGreenBits, gl_config::accumRedBits, gl_config::alphaBits, gl_framebuffer::Attachment, gl_config::blueBits, BUFFER_ACCUM, BUFFER_COUNT, BUFFER_DEPTH, BUFFER_STENCIL, compute_depth_max(), gl_config::depthBits, gl_extensions::EXT_framebuffer_sRGB, gl_context::Extensions, gl_config::floatMode, gl_renderbuffer::Format, gl_config::greenBits, gl_config::haveAccumBuffer, gl_config::haveDepthBuffer, gl_config::haveStencilBuffer, gl_renderbuffer::NumSamples, gl_config::redBits, gl_renderbuffer_attachment::Renderbuffer, gl_config::rgbBits, gl_config::rgbMode, gl_config::sampleBuffers, gl_config::samples, gl_config::sRGBCapable, gl_config::stencilBits, and gl_framebuffer::Visual.
Referenced by _mesa_FramebufferRenderbuffer(), and _mesa_test_framebuffer_completeness().
static void compute_depth_max (struct gl_framebuffer * fb) static
Functions for allocating/managing framebuffers and renderbuffers.
Also, routines for reading/writing renderbuffer data as ubytes, ushorts, uints, etc. Compute/set the _DepthMax field for the given framebuffer. This value depends on the Z buffer resolution.
References gl_framebuffer::_DepthMax, gl_framebuffer::_DepthMaxF, gl_framebuffer::_MRD, gl_config::depthBits, and gl_framebuffer::Visual.
Referenced by _mesa_initialize_window_framebuffer(), _mesa_update_framebuffer_visual(), and update_framebuffer().
static GLboolean renderbuffer_exists (struct gl_context * ctx, struct gl_framebuffer * fb, GLenum format, GLboolean reading) static
Check if the renderbuffer for a read/draw operation exists.
Parameters
format a basic image format such as GL_RGB, GL_RGBA, GL_ALPHA, GL_DEPTH_COMPONENT, etc. or GL_COLOR, GL_DEPTH, GL_STENCIL.
reading if TRUE, we're going to read from the buffer, if FALSE, we're going to write to the buffer.
Returns
GL_TRUE if buffer exists, GL_FALSE otherwise
References gl_framebuffer::_ColorReadBuffer, _mesa_get_format_bits(), _mesa_problem(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, ASSERT, gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, and gl_renderbuffer::Format.
Referenced by _mesa_dest_buffer_exists(), and _mesa_source_buffer_exists().
static void update_color_draw_buffers (struct gl_context * ctx, struct gl_framebuffer * fb) static
Update the (derived) list of color drawing renderbuffer pointers.
Later, when we're rendering we'll loop from 0 to _NumColorDrawBuffers writing colors.
References gl_framebuffer::_ColorDrawBufferIndexes, gl_framebuffer::_ColorDrawBuffers, gl_framebuffer::_NumColorDrawBuffers, gl_framebuffer::Attachment, NULL, and gl_renderbuffer_attachment::Renderbuffer.
Referenced by update_framebuffer().
static void update_color_read_buffer (struct gl_context * ctx, struct gl_framebuffer * fb) static
Update the (derived) color read renderbuffer pointer.
Unlike the DrawBuffer, we can only read from one (or zero) color buffers.
References gl_framebuffer::_ColorReadBuffer, gl_framebuffer::_ColorReadBufferIndex, ASSERT, gl_framebuffer::Attachment, BUFFER_COUNT, gl_framebuffer::DeletePending, gl_framebuffer::Height, NULL, gl_renderbuffer_attachment::Renderbuffer, void(), and gl_framebuffer::Width.
Referenced by update_framebuffer().
static void update_framebuffer (struct gl_context * ctx, struct gl_framebuffer * fb) static
Update a gl_framebuffer's derived state.
Specifically, update these framebuffer fields: _ColorDrawBuffers _NumColorDrawBuffers _ColorReadBuffer
If the framebuffer is user-created, make sure it's complete.
The following functions (at least) can effect framebuffer state: glReadBuffer, glDrawBuffer, glDrawBuffersARB, glFramebufferRenderbufferEXT, glRenderbufferStorageEXT.
References _mesa_drawbuffers(), _mesa_is_winsys_fbo(), _mesa_test_framebuffer_completeness(), gl_framebuffer::_Status, gl_context::Color, gl_framebuffer::ColorDrawBuffer, compute_depth_max(), gl_context::Const, gl_colorbuffer_attrib::DrawBuffer, gl_constants::MaxDrawBuffers, NULL, update_color_draw_buffers(), and update_color_read_buffer().
Referenced by _mesa_update_framebuffer().
static void update_framebuffer_size (struct gl_context * ctx, struct gl_framebuffer * fb) static
Examine all the framebuffer's renderbuffers to update the Width/Height fields of the framebuffer.
If we have renderbuffers with different sizes, set the framebuffer's width and height to the min size. Note: this is only intended for user-created framebuffers, not window-system framebuffes.
References _mesa_is_user_fbo(), gl_framebuffer::Attachment, BUFFER_COUNT, gl_renderbuffer::Height, gl_framebuffer::Height, MIN2, gl_renderbuffer_attachment::Renderbuffer, gl_renderbuffer::Width, and gl_framebuffer::Width.
Referenced by _mesa_update_draw_buffer_bounds().