Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
getstring.c File Reference
#include "glheader.h"
#include "context.h"
#include "get.h"
#include "enums.h"
#include "extensions.h"
#include "mtypes.h"
Functions
static const GLubyte * shading_language_version (struct gl_context *ctx)
Return the string for a glGetString(GL_SHADING_LANGUAGE_VERSION) query.
const GLubyte *GLAPIENTRY _mesa_GetString (GLenum name)
Query string-valued state.
const GLubyte *GLAPIENTRY _mesa_GetStringi (GLenum name, GLuint index)
GL3.
void GLAPIENTRY _mesa_GetPointerv (GLenum pname, GLvoid **params)
Return pointer-valued state, such as a vertex array pointer.
GLenum GLAPIENTRY _mesa_GetError (void)
Returns the current GL error code, or GL_NO_ERROR.
GLenum GLAPIENTRY _mesa_GetGraphicsResetStatusARB (void)
Returns an error code specified by GL_ARB_robustness, or GL_NO_ERROR.
Function Documentation
GLenum GLAPIENTRY _mesa_GetError (void)
Returns the current GL error code, or GL_NO_ERROR.
Returns
current error code
Returns __struct gl_contextRec::ErrorValue.
References _mesa_debug(), _mesa_lookup_enum_by_nr(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
GLenum GLAPIENTRY _mesa_GetGraphicsResetStatusARB (void)
Returns an error code specified by GL_ARB_robustness, or GL_NO_ERROR.
Returns
current context status
References _mesa_debug(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetPointerv (GLenum pname, GLvoid ** params)
Return pointer-valued state, such as a vertex array pointer.
Parameters
pname names state to be queried
params returns the pointer value
See Also
glGetPointerv().
Tries to get the specified pointer via dd_function_table::GetPointerv, otherwise gets the specified pointer from the current context.
References _mesa_debug(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_lookup_enum_by_nr(), API_OPENGL_COMPAT, API_OPENGLES, GL_POINT_SIZE_ARRAY_POINTER_OES, MESA_VERBOSE, VERBOSE_API, VERT_ATTRIB_COLOR0, VERT_ATTRIB_COLOR1, VERT_ATTRIB_COLOR_INDEX, VERT_ATTRIB_EDGEFLAG, VERT_ATTRIB_FOG, VERT_ATTRIB_NORMAL, VERT_ATTRIB_POINT_SIZE, VERT_ATTRIB_POS, and VERT_ATTRIB_TEX.
Referenced by _mesa_initialize_exec_table().
const GLubyte* GLAPIENTRY _mesa_GetString (GLenum name)
Query string-valued state.
The return value should not be freed by the caller.
Parameters
name the state variable to query.
See Also
glGetString().
Tries to get the string from dd_function_table::GetString, otherwise returns the hardcoded strings.
References _mesa_error(), API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GLubyte, NULL, and shading_language_version().
Referenced by _mesa_initialize_exec_table(), and _mesa_print_info().
const GLubyte* GLAPIENTRY _mesa_GetStringi (GLenum name, GLuint index)
GL3.
References _mesa_error(), _mesa_get_enabled_extension(), _mesa_get_extension_count(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, GLubyte, and NULL.
Referenced by _mesa_initialize_exec_table().
static const GLubyte* shading_language_version (struct gl_context * ctx) static
Return the string for a glGetString(GL_SHADING_LANGUAGE_VERSION) query.
References _mesa_error(), _mesa_problem(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, gl_extensions::ARB_shader_objects, gl_context::Const, gl_context::Extensions, gl_constants::GLSLVersion, GLubyte, and gl_context::Version.
Referenced by _mesa_GetString().