Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
glformats.c File Reference
#include "context.h"
#include "glformats.h"
Functions
GLboolean _mesa_type_is_packed (GLenum type)
GLint _mesa_sizeof_type (GLenum type)
Get the size of a GL data type.
GLint _mesa_sizeof_packed_type (GLenum type)
Same as _mesa_sizeof_type() but also accepting the packed pixel format data types.
GLint _mesa_components_in_format (GLenum format)
Get the number of components in a pixel format.
GLint _mesa_bytes_per_pixel (GLenum format, GLenum type)
Get the bytes per pixel of pixel format type pair.
GLint _mesa_bytes_per_vertex_attrib (GLint comps, GLenum type)
Get the number of bytes for a vertex attrib with the given number of components and type.
GLboolean _mesa_is_enum_format_unsigned_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
GLboolean _mesa_is_enum_format_signed_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
GLboolean _mesa_is_enum_format_integer (GLenum format)
Test if the given format is an integer (non-normalized) format.
GLboolean _mesa_is_type_integer (GLenum type)
Test if the given type is an integer (non-normalized) format.
GLboolean _mesa_is_enum_format_or_type_integer (GLenum format, GLenum type)
Test if the given format or type is an integer (non-normalized) format.
GLboolean _mesa_is_type_unsigned (GLenum type)
GLboolean _mesa_is_color_format (GLenum format)
Test if the given image format is a color/RGBA format (i.e., not color index, depth, stencil, etc).
GLboolean _mesa_is_depth_format (GLenum format)
Test if the given image format is a depth component format.
GLboolean _mesa_is_stencil_format (GLenum format)
Test if the given image format is a stencil format.
GLboolean _mesa_is_ycbcr_format (GLenum format)
Test if the given image format is a YCbCr format.
GLboolean _mesa_is_depthstencil_format (GLenum format)
Test if the given image format is a depth+stencil format.
GLboolean _mesa_is_depth_or_stencil_format (GLenum format)
Test if the given image format is a depth or stencil format.
GLboolean _mesa_is_dudv_format (GLenum format)
Test if the given image format is a dudv format.
GLboolean _mesa_is_compressed_format (struct gl_context *ctx, GLenum format)
Test if an image format is a supported compressed format.
GLenum _mesa_base_format_to_integer_format (GLenum format)
Convert various base formats to the cooresponding integer format.
GLboolean _mesa_base_format_has_channel (GLenum base_format, GLenum pname)
Does the given base texture/renderbuffer format have the channel named by 'pname'?
GLint _mesa_base_format_component_count (GLenum base_format)
Returns the number of channels/components for a base format.
GLenum _mesa_generic_compressed_format_to_uncompressed_format (GLenum format)
If format is a generic compressed format, return the corresponding non-compressed format.
GLenum _mesa_get_nongeneric_internalformat (GLenum format)
Return the equivalent non-generic internal format.
GLenum _mesa_get_linear_internalformat (GLenum format)
Convert an sRGB internal format to linear.
GLenum _mesa_error_check_format_and_type (const struct gl_context *ctx, GLenum format, GLenum type)
Do error checking of format/type combinations for glReadPixels, glDrawPixels and glTex[Sub]Image.
GLenum _mesa_es_error_check_format_and_type (GLenum format, GLenum type, unsigned dimensions)
Do error checking of format/type combinations for OpenGL ES glReadPixels and glTex[Sub]Image.
GLenum _mesa_es3_error_check_format_and_type (GLenum format, GLenum type, GLenum internalFormat)
Do error checking of format/type combinations for OpenGL ES 3 glTex[Sub]Image.
Function Documentation
GLint _mesa_base_format_component_count (GLenum base_format)
Returns the number of channels/components for a base format.
Referenced by copytexture_error_check().
GLboolean _mesa_base_format_has_channel (GLenum base_format, GLenum pname)
Does the given base texture/renderbuffer format have the channel named by 'pname'?
References __FUNCTION__, _mesa_warning(), and NULL.
Referenced by get_component_bits(), get_tex_level_parameter_buffer(), and get_tex_level_parameter_image().
GLenum _mesa_base_format_to_integer_format (GLenum format)
Convert various base formats to the cooresponding integer format.
GLint _mesa_bytes_per_pixel (GLenum format, GLenum type)
Get the bytes per pixel of pixel format type pair.
Parameters
format pixel format.
type pixel type.
Returns
bytes per pixel, or -1 if a bad format or type was given.
References _mesa_components_in_format(), GLshort, GLubyte, and GLushort.
Referenced by _mesa_image_image_stride(), _mesa_image_offset(), _mesa_image_row_stride(), _mesa_unpack_image(), and unpack_image().
GLint _mesa_bytes_per_vertex_attrib (GLint comps, GLenum type)
Get the number of bytes for a vertex attrib with the given number of components and type.
Parameters
comps number of components.
type data type.
Returns
bytes per attribute, or -1 if a bad comps/type combination was given.
References GLshort, and GLubyte.
Referenced by update_array().
GLint _mesa_components_in_format (GLenum format)
Get the number of components in a pixel format.
Parameters
format pixel format.
Returns
the number of components in the given format, or -1 if a bad format.
Referenced by _mesa_bytes_per_pixel(), _mesa_make_temp_float_image(), _mesa_make_temp_ubyte_image(), _mesa_pack_rgba_span_float(), _mesa_swizzle_ubyte_image(), _mesa_texstore_dudv8(), _mesa_texstore_rgba_float16(), _mesa_texstore_rgba_float32(), _mesa_texstore_rgba_int16(), _mesa_texstore_rgba_int32(), _mesa_texstore_rgba_int8(), _mesa_texstore_rgba_uint16(), _mesa_texstore_rgba_uint32(), _mesa_texstore_rgba_uint8(), _mesa_unpack_color_span_float(), _mesa_unpack_color_span_ubyte(), _mesa_unpack_color_span_uint(), _mesa_unpack_dudv_span_byte(), _mesa_unpack_image(), extract_float_rgba(), extract_uint_rgba(), and make_temp_uint_image().
GLenum _mesa_error_check_format_and_type (const struct gl_context * ctx, GLenum format, GLenum type)
Do error checking of format/type combinations for glReadPixels, glDrawPixels and glTex[Sub]Image.
Note that depending on the format and type values, we may either generate GL_INVALID_OPERATION or GL_INVALID_ENUM.
Parameters
format pixel format.
type pixel type.
Returns
GL_INVALID_ENUM, GL_INVALID_OPERATION or GL_NO_ERROR
References gl_context::API, API_OPENGLES2, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_half_float_pixel, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::ATI_envmap_bumpmap, gl_extensions::EXT_packed_depth_stencil, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_context::Extensions, gl_extensions::MESA_ycbcr_texture, and gl_context::Version.
Referenced by _mesa_DrawPixels(), _mesa_ReadnPixelsARB(), getteximage_error_check(), texsubimage_error_check(), and texture_error_check().
GLenum _mesa_es3_error_check_format_and_type (GLenum format, GLenum type, GLenum internalFormat)
Do error checking of format/type combinations for OpenGL ES 3 glTex[Sub]Image.
Returns
error code, or GL_NO_ERROR.
Referenced by texture_error_check().
GLenum _mesa_es_error_check_format_and_type (GLenum format, GLenum type, unsigned dimensions)
Do error checking of format/type combinations for OpenGL ES glReadPixels and glTex[Sub]Image.
Returns
error code, or GL_NO_ERROR.
References GL_HALF_FLOAT_OES.
Referenced by _mesa_ReadnPixelsARB(), texsubimage_error_check(), and texture_error_check().
GLenum _mesa_generic_compressed_format_to_uncompressed_format (GLenum format)
If format is a generic compressed format, return the corresponding non-compressed format.
For other formats, return the format as-is.
GLenum _mesa_get_linear_internalformat (GLenum format)
Convert an sRGB internal format to linear.
Referenced by compatible_resolve_formats(), and copytexture_error_check().
GLenum _mesa_get_nongeneric_internalformat (GLenum format)
Return the equivalent non-generic internal format.
This is useful for comparing whether two internal formats are equivalent.
Referenced by compatible_resolve_formats().
GLboolean _mesa_is_color_format (GLenum format)
Test if the given image format is a color/RGBA format (i.e., not color index, depth, stencil, etc).
Parameters
format the image format value (may by an internal texture format)
Returns
GL_TRUE if its a color/RGBA format, GL_FALSE otherwise.
References GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, and GL_ETC1_RGB8_OES.
Referenced by _mesa_get_read_renderbuffer_for_format(), _mesa_ReadnPixelsARB(), copytexsubimage_error_check(), copytexture_error_check(), getteximage_error_check(), read_pixels_es3_error_check(), and texture_error_check().
GLboolean _mesa_is_compressed_format (struct gl_context * ctx, GLenum format)
Test if an image format is a supported compressed format.
Parameters
format the internal format token provided by the user.
Returns
GL_TRUE if compressed, GL_FALSE if uncompressed
References _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_extensions::ANGLE_texture_compression_dxt, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ATI_texture_compression_3dc, gl_extensions::EXT_texture_compression_latc, gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_sRGB, gl_context::Extensions, GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, GL_ETC1_RGB8_OES, GL_PALETTE4_R5_G6_B5_OES, GL_PALETTE4_RGB5_A1_OES, GL_PALETTE4_RGB8_OES, GL_PALETTE4_RGBA4_OES, GL_PALETTE4_RGBA8_OES, GL_PALETTE8_R5_G6_B5_OES, GL_PALETTE8_RGB5_A1_OES, GL_PALETTE8_RGB8_OES, GL_PALETTE8_RGBA4_OES, GL_PALETTE8_RGBA8_OES, gl_extensions::OES_compressed_ETC1_RGB8_texture, and gl_extensions::TDFX_texture_compression_FXT1.
Referenced by compressed_subtexture_error_check(), compressed_texture_error_check(), copytexture_error_check(), and texture_error_check().
GLboolean _mesa_is_depth_format (GLenum format)
Test if the given image format is a depth component format.
Referenced by _mesa_get_read_renderbuffer_for_format(), getteximage_error_check(), and texture_error_check().
GLboolean _mesa_is_depth_or_stencil_format (GLenum format)
Test if the given image format is a depth or stencil format.
Referenced by _mesa_check_sample_count().
GLboolean _mesa_is_depthstencil_format (GLenum format)
Test if the given image format is a depth+stencil format.
Referenced by _mesa_GenerateMipmap(), _mesa_get_read_renderbuffer_for_format(), getteximage_error_check(), and texture_error_check().
GLboolean _mesa_is_dudv_format (GLenum format)
Test if the given image format is a dudv format.
Referenced by getteximage_error_check(), and texture_error_check().
GLboolean _mesa_is_enum_format_integer (GLenum format)
Test if the given format is an integer (non-normalized) format.
References _mesa_is_enum_format_signed_int(), and _mesa_is_enum_format_unsigned_int().
Referenced by _mesa_check_sample_count(), _mesa_DrawPixels(), _mesa_GenerateMipmap(), _mesa_is_enum_format_or_type_integer(), _mesa_pack_rgba_span_float(), _mesa_ReadnPixelsARB(), _mesa_unpack_color_span_float(), _mesa_unpack_color_span_ubyte(), copytexture_error_check(), extract_float_rgba(), get_readpixels_transfer_ops(), slow_read_rgba_pixels(), texsubimage_error_check(), and texture_error_check().
GLboolean _mesa_is_enum_format_or_type_integer (GLenum format, GLenum type)
Test if the given format or type is an integer (non-normalized) format.
References _mesa_is_enum_format_integer(), and _mesa_is_type_integer().
GLboolean _mesa_is_enum_format_signed_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
Referenced by _mesa_is_enum_format_integer(), and read_pixels_es3_error_check().
GLboolean _mesa_is_enum_format_unsigned_int (GLenum format)
Test if the given format is an integer (non-normalized) format.
Referenced by _mesa_is_enum_format_integer(), copytexture_error_check(), and read_pixels_es3_error_check().
GLboolean _mesa_is_stencil_format (GLenum format)
Test if the given image format is a stencil format.
Referenced by _mesa_GenerateMipmap().
GLboolean _mesa_is_type_integer (GLenum type)
Test if the given type is an integer (non-normalized) format.
Referenced by _mesa_is_enum_format_or_type_integer().
GLboolean _mesa_is_type_unsigned (GLenum type)
Referenced by _mesa_is_format_unsigned(), _mesa_texstore_abgr2101010_uint(), _mesa_texstore_argb2101010_uint(), _mesa_texstore_rgba_int16(), _mesa_texstore_rgba_int32(), _mesa_texstore_rgba_int8(), _mesa_texstore_rgba_uint16(), _mesa_texstore_rgba_uint32(), and _mesa_texstore_rgba_uint8().
GLboolean _mesa_is_ycbcr_format (GLenum format)
Test if the given image format is a YCbCr format.
Referenced by getteximage_error_check(), and texture_error_check().
GLint _mesa_sizeof_packed_type (GLenum type)
Same as _mesa_sizeof_type() but also accepting the packed pixel format data types.
References GLbyte, GLshort, GLubyte, GLushort, and MESA_UNSIGNED_BYTE_4_4.
Referenced by _mesa_pack_rgba_span_float(), _mesa_validate_pbo_access(), and bytes_per_pixel().
GLint _mesa_sizeof_type (GLenum type)
Get the size of a GL data type.
Parameters
type GL data type.
Returns
the size, in bytes, of the given data type, 0 if a GL_BITMAP, or -1 if an invalid type enum.
References GLbyte, GLshort, GLubyte, and GLushort.
Referenced by init_array().
GLboolean _mesa_type_is_packed (GLenum type)
Returns
GL_TRUE if type is packed pixel type, GL_FALSE otherwise.
References MESA_UNSIGNED_BYTE_4_4.
Referenced by _mesa_unpack_image(), and bytes_per_pixel().