Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
hash_table.c File Reference
#include <stdlib.h>
#include <string.h>
#include "main/hash_table.h"
#include "main/macros.h"
#include "ralloc.h"
Functions
static int entry_is_free (const struct hash_entry *entry)
static int entry_is_deleted (const struct hash_table *ht, struct hash_entry *entry)
static int entry_is_present (const struct hash_table *ht, struct hash_entry *entry)
struct hash_table * _mesa_hash_table_create (void *mem_ctx, bool key_equals_function(const void *a, const void *b))
void _mesa_hash_table_destroy (struct hash_table *ht, void(*delete_function)(struct hash_entry *entry))
Frees the given hash table.
void _mesa_hash_table_set_deleted_key (struct hash_table *ht, const void *deleted_key)
Sets the value of the key pointer used for deleted entries in the table.
struct hash_entry * _mesa_hash_table_search (struct hash_table *ht, uint32_t hash, const void *key)
Finds a hash table entry with the given key and hash of that key.
static void _mesa_hash_table_rehash (struct hash_table *ht, int new_size_index)
struct hash_entry * _mesa_hash_table_insert (struct hash_table *ht, uint32_t hash, const void *key, void *data)
Inserts the key with the given hash into the table.
void _mesa_hash_table_remove (struct hash_table *ht, struct hash_entry *entry)
This function deletes the given hash table entry.
struct hash_entry * _mesa_hash_table_next_entry (struct hash_table *ht, struct hash_entry *entry)
This function is an iterator over the hash table.
struct hash_entry * _mesa_hash_table_random_entry (struct hash_table *ht, bool(*predicate)(struct hash_entry *entry))
Returns a random entry from the hash table.
uint32_t _mesa_hash_data (const void *data, size_t size)
Quick FNV-1 hash implementation based on: http://www.isthe.com/chongo/tech/comp/fnv/.
uint32_t _mesa_hash_string (const char *key)
FNV-1 string hash implementation.
bool _mesa_key_string_equal (const void *a, const void *b)
String compare function for use as the comparison callback in _mesa_hash_table_create().
bool _mesa_key_pointer_equal (const void *a, const void *b)
Variables
static const uint32_t deleted_key_value
Implements an open-addressing, linear-reprobing hash table.
struct {
uint32_t max_entries
uint32_t size
uint32_t rehash
} hash_sizes []
Function Documentation
uint32_t _mesa_hash_data (const void * data, size_t size)
Quick FNV-1 hash implementation based on: http://www.isthe.com/chongo/tech/comp/fnv/.
FNV-1 is not be the best hash out there – Jenkins's lookup3 is supposed to be quite good, and it probably beats FNV. But FNV has the advantage that it involves almost no code. For an improvement on both, see Paul Hsieh's http://www.azillionmonkeys.com/qed/hash.html
References hash_entry::data, and hash_entry::hash.
Referenced by _mesa_hash_pointer().
uint32_t _mesa_hash_string (const char * key)
FNV-1 string hash implementation.
References hash_entry::hash, and hash_entry::key.
struct hash_table* _mesa_hash_table_create (void * mem_ctx, bool key_equals_functionconst void *a,const void *b) read
References hash_table::deleted_entries, hash_table::deleted_key, deleted_key_value, hash_table::entries, hash_sizes, hash_table::key_equals_function, hash_table::max_entries, hash_table::mem_ctx, NULL, hash_table::rehash, hash_table::size, hash_table::size_index, and hash_table::table.
Referenced by _mesa_NewHashTable().
void _mesa_hash_table_destroy (struct hash_table * ht, void(*)(struct hash_entry *entry) delete_function)
Frees the given hash table.
If delete_function is passed, it gets called on each entry present before freeing.
References hash_table_foreach.
Referenced by _mesa_DeleteHashTable().
struct hash_entry* _mesa_hash_table_insert (struct hash_table * ht, uint32_t hash, const void * key, void * data) read
Inserts the key with the given hash into the table.
Note that insertion may rearrange the table on a resize or rehash, so previously found hash_entries are no longer valid after this function.
References _mesa_hash_table_rehash(), hash_entry::data, hash_table::deleted_entries, hash_table::entries, entry_is_deleted(), entry_is_present(), hash_entry::hash, hash_entry::key, hash_table::key_equals_function, hash_table::max_entries, NULL, hash_table::rehash, hash_table::size, hash_table::size_index, and hash_table::table.
Referenced by _mesa_hash_table_rehash(), and _mesa_HashInsert().
struct hash_entry* _mesa_hash_table_next_entry (struct hash_table * ht, struct hash_entry * entry) read
This function is an iterator over the hash table.
Pass in NULL for the first entry, as in the start of a for loop. Note that an iteration over the table is O(table_size) not O(entries).
References entry_is_present(), NULL, hash_table::size, and hash_table::table.
Referenced by _mesa_DeleteHashTable().
struct hash_entry* _mesa_hash_table_random_entry (struct hash_table * ht, bool(*)(struct hash_entry *entry) predicate) read
Returns a random entry from the hash table.
This may be useful in implementing random replacement (as opposed to just removing everything) in caches based on this hash table implementation. may be used to filter entries, or may be set to NULL for no filtering.
References hash_table::entries, entry_is_present(), NULL, hash_table::size, and hash_table::table.
static void _mesa_hash_table_rehash (struct hash_table * ht, int new_size_index) static
References _mesa_hash_table_insert(), ARRAY_SIZE, hash_entry::data, hash_table::deleted_entries, hash_table::entries, hash_entry::hash, hash_sizes, hash_table_foreach, hash_entry::key, hash_table::max_entries, NULL, hash_table::rehash, hash_table::size, size, hash_table::size_index, hash_table::table, and table.
Referenced by _mesa_hash_table_insert().
void _mesa_hash_table_remove (struct hash_table * ht, struct hash_entry * entry)
This function deletes the given hash table entry.
Note that deletion doesn't otherwise modify the table, so an iteration over the table deleting entries is safe.
References hash_table::deleted_entries, hash_table::deleted_key, hash_table::entries, and hash_entry::key.
Referenced by _mesa_HashDeleteAll(), and _mesa_HashRemove().
struct hash_entry* _mesa_hash_table_search (struct hash_table * ht, uint32_t hash, const void * key) read
Finds a hash table entry with the given key and hash of that key.
Returns NULL if no entry is found. Note that the data pointer may be modified by the user.
References entry_is_free(), entry_is_present(), hash_entry::hash, hash_entry::key, hash_table::key_equals_function, NULL, hash_table::rehash, hash_table::size, and hash_table::table.
Referenced by _mesa_HashInsert(), _mesa_HashLookup_unlocked(), and _mesa_HashRemove().
void _mesa_hash_table_set_deleted_key (struct hash_table * ht, const void * deleted_key)
Sets the value of the key pointer used for deleted entries in the table.
The assumption is that usually keys are actual pointers, so we use a default value of a pointer to an arbitrary piece of storage in the library. But in some cases a consumer wants to store some other sort of value in the table, like a uint32_t, in which case that pointer may conflict with one of their valid keys. This lets that user select a safe value.
This must be called before any keys are actually deleted from the table.
References deleted_key, and hash_table::deleted_key.
Referenced by _mesa_NewHashTable().
bool _mesa_key_pointer_equal (const void * a, const void * b)
Referenced by _mesa_alloc_shared_state().
bool _mesa_key_string_equal (const void * a, const void * b)
String compare function for use as the comparison callback in _mesa_hash_table_create().
static int entry_is_deleted (const struct hash_table * ht, struct hash_entry * entry) static
References hash_table::deleted_key, and hash_entry::key.
Referenced by _mesa_hash_table_insert().
static int entry_is_free (const struct hash_entry * entry) static
References hash_entry::key, and NULL.
Referenced by _mesa_hash_table_search().
static int entry_is_present (const struct hash_table * ht, struct hash_entry * entry) static
References hash_table::deleted_key, hash_entry::key, and NULL.
Referenced by _mesa_hash_table_insert(), _mesa_hash_table_next_entry(), _mesa_hash_table_random_entry(), and _mesa_hash_table_search().
Variable Documentation
const uint32_t deleted_key_value static
Implements an open-addressing, linear-reprobing hash table.
For more information, see:
http://cgit.freedesktop.org/~anholt/hash_table/tree/README
Referenced by _mesa_hash_table_create().
struct { ... } hash_sizes[]
Referenced by _mesa_hash_table_create(), and _mesa_hash_table_rehash().
uint32_t max_entries
uint32_t rehash
uint32_t size
Referenced by _mesa_buffer_data(), _mesa_copy_map_points1d(), _mesa_copy_map_points1f(), _mesa_copy_map_points2d(), _mesa_copy_map_points2f(), _mesa_do_init_remap_table(), _mesa_FeedbackBuffer(), _mesa_get_compressed_teximage(), _mesa_get_tex_max_num_levels(), _mesa_GetSynciv(), _mesa_hash_table_rehash(), _mesa_PointSize(), _mesa_SelectBuffer(), _mesa_validate_pbo_access(), bind_buffer_range(), init_array(), mmAllocMem(), mmInit(), save_PointSize(), set_rehash(), set_ubo_binding(), SliceBlock(), texbufferrange(), texture_size(), and update_array().