Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
hash.c File Reference
Generic hash table.
#include "glheader.h"
#include "imports.h"
#include "glapi/glthread.h"
#include "hash.h"
#include "hash_table.h"
Data Structures
struct _mesa_HashTable
The hash table data structure.
Macros
#define DELETED_KEY_VALUE 1
Magic GLuint object name that gets stored outside of the struct hash_table.
Functions
struct _mesa_HashTable * _mesa_NewHashTable (void)
Create a new hash table.
void _mesa_DeleteHashTable (struct _mesa_HashTable *table)
Delete a hash table.
static void * _mesa_HashLookup_unlocked (struct _mesa_HashTable *table, GLuint key)
Lookup an entry in the hash table, without locking.
void * _mesa_HashLookup (struct _mesa_HashTable *table, GLuint key)
Lookup an entry in the hash table.
void _mesa_HashInsert (struct _mesa_HashTable *table, GLuint key, void *data)
Insert a key/pointer pair into the hash table.
void _mesa_HashRemove (struct _mesa_HashTable *table, GLuint key)
Remove an entry from the hash table.
void _mesa_HashDeleteAll (struct _mesa_HashTable *table, void(*callback)(GLuint key, void *data, void *userData), void *userData)
Delete all entries in a hash table, but don't delete the table itself.
void _mesa_HashWalk (const struct _mesa_HashTable *table, void(*callback)(GLuint key, void *data, void *userData), void *userData)
Walk over all entries in a hash table, calling callback function for each.
static void debug_print_entry (GLuint key, void *data, void *userData)
void _mesa_HashPrint (const struct _mesa_HashTable *table)
Dump contents of hash table for debugging.
GLuint _mesa_HashFindFreeKeyBlock (struct _mesa_HashTable *table, GLuint numKeys)
Find a block of adjacent unused hash keys.
GLuint _mesa_HashNumEntries (const struct _mesa_HashTable *table)
Return the number of entries in the hash table.
static bool uint_key_compare (const void *a, const void *b)
static uint32_t uint_hash (GLuint id)
static void * uint_key (GLuint id)
Detailed Description
Generic hash table.
Used for display lists, texture objects, vertex/fragment programs, buffer objects, etc. The hash functions are thread-safe.
Note
key=0 is illegal.
Author
Brian Paul
Macro Definition Documentation
#define DELETED_KEY_VALUE 1
Magic GLuint object name that gets stored outside of the struct hash_table.
The hash table needs a particular pointer to be the marker for a key that was deleted from the table, along with NULL for the "never allocated in the table" marker. Legacy GL allows any GLuint to be used as a GL object name, and we use a 1:1 mapping from GLuints to key pointers, so we need to be able to track a GLuint that happens to match the deleted key outside of struct hash_table. We tell the hash table to use "1" as the deleted key value, so that we test the deleted-key-in-the-table path as best we can.
Referenced by _mesa_HashDeleteAll(), _mesa_HashInsert(), _mesa_HashLookup_unlocked(), _mesa_HashPrint(), _mesa_HashRemove(), _mesa_HashWalk(), and _mesa_NewHashTable().
Function Documentation
void _mesa_DeleteHashTable (struct _mesa_HashTable * table)
Delete a hash table.
Frees each entry on the hash table and then the hash table structure itself. Note that the caller should have already traversed the table and deleted the objects in the table (i.e. We don't free the entries' data pointer).
Parameters
table the hash table to delete.
References _mesa_hash_table_destroy(), _mesa_hash_table_next_entry(), _mesa_problem(), _mesa_HashTable::ht, _mesa_HashTable::Mutex, NULL, and _mesa_HashTable::WalkMutex.
Referenced by _mesa_free_errors_data(), _mesa_free_queryobj_data(), _mesa_free_transform_feedback(), _mesa_free_varray_data(), and free_shared_state().
void _mesa_HashDeleteAll (struct _mesa_HashTable * table, void(*)(GLuint key, void *data, void *userData) callback, void * userData)
Delete all entries in a hash table, but don't delete the table itself.
Invoke the given callback function for each table entry.
Parameters
table the hash table to delete
callback the callback function
userData arbitrary pointer to pass along to the callback (this is typically a struct gl_context pointer)
References _mesa_hash_table_remove(), ASSERT, hash_entry::data, _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, hash_table_foreach, _mesa_HashTable::ht, _mesa_HashTable::InDeleteAll, hash_entry::key, _mesa_HashTable::Mutex, and NULL.
Referenced by _mesa_free_errors_data(), _mesa_free_queryobj_data(), _mesa_free_transform_feedback(), _mesa_free_varray_data(), and free_shared_state().
GLuint _mesa_HashFindFreeKeyBlock (struct _mesa_HashTable * table, GLuint numKeys)
Find a block of adjacent unused hash keys.
Parameters
table the hash table.
numKeys number of keys needed.
Returns
Starting key of free block or 0 if failure.
If there are enough free keys between the maximum key existing in the table (_mesa_HashTable::MaxKey) and the maximum key possible, then simply return the adjacent key. Otherwise do a full search for a free key block in the allowable key range.
References _mesa_HashLookup_unlocked(), hash_entry::key, _mesa_HashTable::MaxKey, and _mesa_HashTable::Mutex.
Referenced by _mesa_GenBuffers(), _mesa_GenFragmentShadersATI(), _mesa_GenFramebuffers(), _mesa_GenLists(), _mesa_GenProgramsARB(), _mesa_GenQueries(), _mesa_GenRenderbuffers(), _mesa_GenSamplers(), _mesa_GenTextures(), _mesa_GenTransformFeedbacks(), create_shader(), create_shader_program(), and gen_vertex_arrays().
void _mesa_HashInsert (struct _mesa_HashTable * table, GLuint key, void * data)
Insert a key/pointer pair into the hash table.
If an entry with this key already exists we'll replace the existing entry.
Parameters
table the hash table.
key the key (not zero).
data pointer to user data.
References _mesa_hash_table_insert(), _mesa_hash_table_search(), hash_entry::data, _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, hash_entry::hash, _mesa_HashTable::ht, hash_entry::key, _mesa_HashTable::MaxKey, _mesa_HashTable::Mutex, uint_hash(), and uint_key().
Referenced by _mesa_BeginQueryIndexed(), _mesa_BindFragmentShaderATI(), _mesa_BindFramebuffer(), _mesa_BindProgramARB(), _mesa_BindRenderbuffer(), _mesa_BindTexture(), _mesa_EndList(), _mesa_GenBuffers(), _mesa_GenFragmentShadersATI(), _mesa_GenFramebuffers(), _mesa_GenLists(), _mesa_GenProgramsARB(), _mesa_GenQueries(), _mesa_GenRenderbuffers(), _mesa_GenSamplers(), _mesa_GenTextures(), _mesa_GenTransformFeedbacks(), _mesa_QueryCounter(), create_shader(), create_shader_program(), handle_bind_buffer_gen(), save_array_object(), set_message_state(), and should_log().
void* _mesa_HashLookup (struct _mesa_HashTable * table, GLuint key)
Lookup an entry in the hash table.
Parameters
table the hash table.
key the key.
Returns
pointer to user's data or NULL if key not in table
References _mesa_HashLookup_unlocked(), and _mesa_HashTable::Mutex.
Referenced by _mesa_BindFragmentShaderATI(), _mesa_DeleteFragmentShaderATI(), _mesa_lookup_bufferobj(), _mesa_lookup_framebuffer(), _mesa_lookup_query_object(), _mesa_lookup_renderbuffer(), _mesa_lookup_samplerobj(), _mesa_lookup_shader(), _mesa_lookup_shader_err(), _mesa_lookup_shader_program(), _mesa_lookup_shader_program_err(), _mesa_lookup_texture(), _mesa_lookup_transform_feedback_object(), lookup_arrayobj(), lookup_list(), set_message_state(), and should_log().
static void* _mesa_HashLookup_unlocked (struct _mesa_HashTable * table, GLuint key) inline static
Lookup an entry in the hash table, without locking.
See Also
_mesa_HashLookup
References _mesa_hash_table_search(), hash_entry::data, _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, _mesa_HashTable::ht, NULL, uint_hash(), and uint_key().
Referenced by _mesa_HashFindFreeKeyBlock(), and _mesa_HashLookup().
GLuint _mesa_HashNumEntries (const struct _mesa_HashTable * table)
Return the number of entries in the hash table.
References _mesa_HashTable::deleted_key_data, hash_table_foreach, and _mesa_HashTable::ht.
void _mesa_HashPrint (const struct _mesa_HashTable * table)
Dump contents of hash table for debugging.
Parameters
table the hash table.
References _mesa_HashWalk(), debug_print_entry(), _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, and NULL.
void _mesa_HashRemove (struct _mesa_HashTable * table, GLuint key)
Remove an entry from the hash table.
Parameters
table the hash table.
key key of entry to remove.
While holding the hash table's lock, searches the entry with the matching key and unlinks it.
References _mesa_hash_table_remove(), _mesa_hash_table_search(), _mesa_problem(), _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, _mesa_HashTable::ht, _mesa_HashTable::InDeleteAll, _mesa_HashTable::Mutex, NULL, uint_hash(), and uint_key().
Referenced by _mesa_BindFragmentShaderATI(), _mesa_DeleteBuffers(), _mesa_DeleteFragmentShaderATI(), _mesa_DeleteFramebuffers(), _mesa_DeleteProgramsARB(), _mesa_DeleteQueries(), _mesa_DeleteRenderbuffers(), _mesa_DeleteSamplers(), _mesa_DeleteTextures(), _mesa_DeleteTransformFeedbacks(), _mesa_reference_shader(), _mesa_reference_shader_program(), destroy_list(), and remove_array_object().
void _mesa_HashWalk (const struct _mesa_HashTable * table, void(*)(GLuint key, void *data, void *userData) callback, void * userData)
Walk over all entries in a hash table, calling callback function for each.
Note: we use a separate mutex in this function to avoid a recursive locking deadlock (in case the callback calls _mesa_HashRemove()) and to prevent multiple threads/contexts from getting tangled up. A lock-less version of this function could be used when the table will not be modified.
Parameters
table the hash table to walk
callback the callback function
userData arbitrary pointer to pass along to the callback (this is typically a struct gl_context pointer)
References ASSERT, hash_entry::data, _mesa_HashTable::deleted_key_data, DELETED_KEY_VALUE, hash_table_foreach, _mesa_HashTable::ht, hash_entry::key, and _mesa_HashTable::WalkMutex.
Referenced by _mesa_dump_renderbuffers(), _mesa_dump_textures(), _mesa_HashPrint(), _mesa_total_buffer_object_memory(), _mesa_total_texture_memory(), _mesa_update_fbo_texture(), free_shared_state(), and renderbuffer_storage().
struct _mesa_HashTable* _mesa_NewHashTable (void) read
Create a new hash table.
Returns
pointer to a new, empty hash table.
References _mesa_hash_table_create(), _mesa_hash_table_set_deleted_key(), CALLOC_STRUCT, DELETED_KEY_VALUE, _mesa_HashTable::ht, _mesa_HashTable::Mutex, NULL, table, uint_key(), uint_key_compare(), and _mesa_HashTable::WalkMutex.
Referenced by _mesa_alloc_shared_state(), _mesa_init_errors(), _mesa_init_queryobj(), _mesa_init_transform_feedback(), and _mesa_init_varray().
static void debug_print_entry (GLuint key, void * data, void * userData) static
References _mesa_debug(), and NULL.
Referenced by _mesa_HashPrint().
static uint32_t uint_hash (GLuint id) static
Referenced by _mesa_HashInsert(), _mesa_HashLookup_unlocked(), and _mesa_HashRemove().
static void* uint_key (GLuint id) static
Referenced by _mesa_HashInsert(), _mesa_HashLookup_unlocked(), _mesa_HashRemove(), and _mesa_NewHashTable().
static bool uint_key_compare (const void * a, const void * b) static
Mapping from our use of GLuint as both the key and the hash value to the hash_table.h API
There exist many integer hash functions, designed to avoid collisions when the integers are spread across key space with some patterns. In GL, the pattern (in the case of glGen*()ed object IDs) is that the keys are unique contiguous integers starting from 1. Because of that, we just use the key as the hash value, to minimize the cost of the hash function. If objects are never deleted, we will never see a collision in the table, because the table resizes itself when it approaches full, and thus key % table_size == key.
The case where we could have collisions for genned objects would be something like: glGenBuffers(&a, 100); glDeleteBuffers(&a + 50, 50); glGenBuffers(&b, 100), because objects 1-50 and 101-200 are allocated at the end of that sequence, instead of 1-150. So far it doesn't appear to be a problem.
Referenced by _mesa_NewHashTable().