Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
hint.h File Reference
Hints operations.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_Hint (GLenum target, GLenum mode)
void _mesa_init_hint (struct gl_context *ctx)
Detailed Description
Hints operations.
Function Documentation
void GLAPIENTRY _mesa_Hint (GLenum target, GLenum mode)
References _mesa_debug(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_lookup_enum_by_nr(), _NEW_HINT, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, FLUSH_VERTICES, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_init_hint (struct gl_context * ctx)
References gl_hint_attrib::ClipVolumeClipping, gl_hint_attrib::Fog, gl_hint_attrib::FragmentShaderDerivative, gl_hint_attrib::GenerateMipmap, gl_context::Hint, gl_hint_attrib::LineSmooth, gl_hint_attrib::PerspectiveCorrection, gl_hint_attrib::PointSmooth, gl_hint_attrib::PolygonSmooth, and gl_hint_attrib::TextureCompression.
Referenced by init_attrib_groups().