Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
histogram.c File Reference
#include "glheader.h"
#include "bufferobj.h"
#include "colormac.h"
#include "histogram.h"
#include "macros.h"
#include "main/dispatch.h"
Functions
void GLAPIENTRY _mesa_GetnMinmaxARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid *values)
void GLAPIENTRY _mesa_GetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
void GLAPIENTRY _mesa_GetnHistogramARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid *values)
void GLAPIENTRY _mesa_GetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
void GLAPIENTRY _mesa_GetHistogramParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetHistogramParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetMinmaxParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetMinmaxParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_Histogram (GLenum target, GLsizei width, GLenum internalFormat, GLboolean sink)
void GLAPIENTRY _mesa_Minmax (GLenum target, GLenum internalFormat, GLboolean sink)
void GLAPIENTRY _mesa_ResetHistogram (GLenum target)
void GLAPIENTRY _mesa_ResetMinmax (GLenum target)
Function Documentation
void GLAPIENTRY _mesa_GetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid * values)
References _mesa_GetnHistogramARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetHistogramParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetHistogramParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid * values)
References _mesa_GetnMinmaxARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetMinmaxParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetMinmaxParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnHistogramARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid * values)
References _mesa_error().
Referenced by _mesa_GetHistogram(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnMinmaxARB (GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, GLvoid * values)
References _mesa_error().
Referenced by _mesa_GetMinmax(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Histogram (GLenum target, GLsizei width, GLenum internalFormat, GLboolean sink)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Minmax (GLenum target, GLenum internalFormat, GLboolean sink)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ResetHistogram (GLenum target)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ResetMinmax (GLenum target)
References _mesa_error().
Referenced by _mesa_initialize_exec_table().