Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
imports.c File Reference
Standard C library function wrappers.
#include "imports.h"
#include "context.h"
#include "mtypes.h"
#include "version.h"
Functions
int _mesa_vsnprintf (char *str, size_t size, const char *fmt, va_list args)
Needed due to #ifdef's, above.
int _mesa_snprintf (char *str, size_t size, const char *fmt,...)
Wrapper around vsnprintf()
Memory
void * _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
void * _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
void _mesa_align_free (void *ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
void * _mesa_align_realloc (void *oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
void * _mesa_realloc (void *oldBuffer, size_t oldSize, size_t newSize)
Reallocate memory.
Math
int ffs (int i)
Find the first bit set in a word.
int ffsll (long long int val)
Find position of first bit set in given value.
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
int _mesa_round_to_even (float val)
GLhalfARB _mesa_float_to_half (float val)
Convert a 4-byte float to a 2-byte half float.
float _mesa_half_to_float (GLhalfARB val)
Convert a 2-byte half float to a 4-byte float.
Sort & Search
void * _mesa_bsearch (const void *key, const void *base, size_t nmemb, size_t size, int(*compar)(const void *, const void *))
Wrapper for bsearch().
Environment vars
char * _mesa_getenv (const char *var)
Wrapper for getenv().
String
char * _mesa_strdup (const char *s)
Implemented using malloc() and strcpy.
float _mesa_strtof (const char *s, char **end)
Wrapper around strtof()
unsigned int _mesa_str_checksum (const char *str)
Compute simple checksum/hash for a string.
Detailed Description
Standard C library function wrappers.
Imports are services which the device driver or window system or operating system provides to the core renderer. The core renderer (Mesa) will call these functions in order to do memory allocation, simple I/O, etc.
Some drivers will want to override/replace this file with something specialized, but that'll be rare.
Eventually, I want to move roll the glheader.h file into this.
Todo:
Functions still needed:
scanf
qsort
rand and RAND_MAX
Function Documentation
void* _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
References _mesa_align_malloc(), ASSERT, NULL, and void().
void _mesa_align_free (void * ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
Parameters
ptr pointer to the memory to be freed. The actual address to free is stored in the word immediately before the address the client sees.
Referenced by _mesa_align_realloc().
void* _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
Parameters
bytes number of bytes to allocate.
alignment alignment (must be greater than zero).
Allocates extra memory to accommodate rounding up the address for alignment and to record the real malloc address.
See Also
_mesa_align_free().
References ASSERT, and NULL.
Referenced by _mesa_align_calloc(), and _mesa_align_realloc().
void* _mesa_align_realloc (void * oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
References _mesa_align_free(), _mesa_align_malloc(), and void().
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
Referenced by _mesa_DrawBuffers(), _mesa_drawbuffers(), and update_texture_state().
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
void* _mesa_bsearch (const void * key, const void * base, size_t nmemb, size_t size, int(*)(const void *, const void *) compar)
Wrapper for bsearch().
References NULL.
Referenced by _mesa_lookup_enum_by_name(), and _mesa_lookup_enum_by_nr().
GLhalfARB _mesa_float_to_half (float val)
Convert a 4-byte float to a 2-byte half float.
Not all float32 values can be represented exactly as a float16 value. We round such intermediate float32 values to the nearest float16. When the float32 lies exactly between to float16 values, we round to the one with an even mantissa.
This rounding behavior has several benefits:
It has no sign bias.
It reproduces the behavior of real hardware: opcode F32TO16 in Intel's GPU ISA.
By reproducing the behavior of the GPU (at least on Intel hardware), compile-time evaluation of constant packHalf2x16 GLSL expressions will result in the same value as if the expression were executed on the GPU.
References _mesa_round_to_even(), fi_type::f, and fi_type::i.
Referenced by _mesa_pack_depth_span(), _mesa_pack_index_span(), _mesa_pack_rgba_span_float(), _mesa_pack_stencil_span(), _mesa_texstore_rgba_float16(), do_row(), pack_float_ALPHA_FLOAT16(), pack_float_LUMINANCE_ALPHA_FLOAT16(), pack_float_LUMINANCE_FLOAT16(), pack_float_RG_FLOAT16(), pack_float_RGB_FLOAT16(), pack_float_RGBA_FLOAT16(), pack_float_XBGR16161616_FLOAT(), pack_ubyte_ALPHA_FLOAT16(), pack_ubyte_LUMINANCE_ALPHA_FLOAT16(), pack_ubyte_LUMINANCE_FLOAT16(), pack_ubyte_RG_FLOAT16(), pack_ubyte_RGB_FLOAT16(), and pack_ubyte_RGBA_FLOAT16().
char* _mesa_getenv (const char * var)
Wrapper for getenv().
References NULL.
Referenced by _mesa_init_debug(), _mesa_initialize_context(), _mesa_make_current(), get_extension_override(), get_shader_flags(), output_if_debug(), and should_output().
float _mesa_half_to_float (GLhalfARB val)
Convert a 2-byte half float to a 4-byte float.
Based on code from: http://www.opengl.org/discussion_boards/ubb/Forum3/HTML/008786.html
References fi_type::f, and fi_type::i.
Referenced by _mesa_unpack_depth_span(), clamp_half_to_uint(), do_row(), extract_float_rgba(), extract_uint_indexes(), unpack_ALPHA_FLOAT16(), unpack_INTENSITY_FLOAT16(), unpack_LUMINANCE_ALPHA_FLOAT16(), unpack_LUMINANCE_FLOAT16(), unpack_R_FLOAT16(), unpack_RG_FLOAT16(), unpack_RGB_FLOAT16(), unpack_RGBA_FLOAT16(), and unpack_XBGR16161616_FLOAT().
void* _mesa_realloc (void * oldBuffer, size_t oldSize, size_t newSize)
Reallocate memory.
Referenced by _mesa_buffer_data(), and attach_shader().
int _mesa_round_to_even (float val)
References IROUND().
Referenced by _mesa_float_to_half().
int _mesa_snprintf (char * str, size_t size, const char * fmt, ...)
Wrapper around vsnprintf()
Referenced by _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_ShaderSource(), _mesa_write_renderbuffer_image(), create_version_string(), execute_list(), flush_delayed_errors(), output_if_debug(), texture_error_check(), and write_texture_image().
unsigned int _mesa_str_checksum (const char * str)
Compute simple checksum/hash for a string.
Referenced by _mesa_ShaderSource(), and shader_source().
char* _mesa_strdup (const char * s)
Implemented using malloc() and strcpy.
Note that NULL is handled accordingly.
References NULL.
Referenced by _mesa_CreateShaderProgramEXT(), _mesa_TransformFeedbackVaryings(), and read_shader().
float _mesa_strtof (const char * s, char ** end)
Wrapper around strtof()
References NULL.
int _mesa_vsnprintf (char * str, size_t size, const char * fmt, va_list args)
Needed due to #ifdef's, above.
Referenced by _mesa_debug(), _mesa_error(), _mesa_gl_debug(), _mesa_problem(), and _mesa_warning().
int ffs (int i)
Find the first bit set in a word.
Referenced by __bitset_ffs(), _mesa_drawbuffers(), ffsll(), get_temp(), and update_texture_state().
int ffsll (long long int val)
Find position of first bit set in given value.
XXX Warning: this function can only be used on 64-bit systems!
Returns
position of least-significant bit set, starting at 1, return zero if no bits set.
References ffs().
Referenced by compute_max_element().