Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
imports.h File Reference
Standard C library function wrappers.
#include "compiler.h"
#include "glheader.h"
#include "errors.h"
Data Structures
union fi_type
Sometimes we treat GLfloats as GLints.
Macros
#define ADD_POINTERS(A, B) ((GLubyte *) (A) + (uintptr_t) (B))
#define MAX_GLUSHORT 0xffff
#define MAX_GLUINT 0xffffffff
#define DEG2RAD (M_PI/180.0)
#define signbit(x) ((x) < 0.0f)
#define IS_INF_OR_NAN(x) (!finite(x))
#define CEILF(x) ((GLfloat) ceil(x))
#define FLOORF(x) ((GLfloat) floor(x))
#define FABSF(x) ((GLfloat) fabs(x))
#define LOGF(x) ((GLfloat) log(x))
#define EXPF(x) ((GLfloat) exp(x))
#define LDEXPF(x, y) ((GLfloat) ldexp(x,y))
#define FREXPF(x, y) ((GLfloat) frexp(x,y))
#define FFS_DEFINED 1
#define MALLOC(BYTES) malloc(BYTES)
Memory macros.
#define CALLOC(BYTES) calloc(1, BYTES)
Allocate and zero BYTES bytes.
#define MALLOC_STRUCT(T) (struct T *) malloc(sizeof(struct T))
Allocate a structure of type T.
#define CALLOC_STRUCT(T) (struct T *) calloc(1, sizeof(struct T))
Allocate and zero a structure of type T.
#define FREE(PTR) free(PTR)
Free memory.
Work-arounds for platforms that lack C99 math functions
#define acosf(f) ((float) acos(f))
#define asinf(f) ((float) asin(f))
#define atan2f(x, y) ((float) atan2(x,y))
#define atanf(f) ((float) atan(f))
#define ceilf(f) ((float) ceil(f))
#define cosf(f) ((float) cos(f))
#define coshf(f) ((float) cosh(f))
#define expf(f) ((float) exp(f))
#define exp2f(f) ((float) exp2(f))
#define floorf(f) ((float) floor(f))
#define logf(f) ((float) log(f))
#define log2f(f) ((float) log2(f))
#define powf(x, y) ((float) pow(x,y))
#define sinf(f) ((float) sin(f))
#define sinhf(f) ((float) sinh(f))
#define sqrtf(f) ((float) sqrt(f))
#define tanf(f) ((float) tan(f))
#define tanhf(f) ((float) tanh(f))
#define acoshf(f) ((float) acosh(f))
#define asinhf(f) ((float) asinh(f))
#define atanhf(f) ((float) atanh(f))
Functions
static float INV_SQRTF (float x)
single-precision inverse square root
static GLfloat LOG2 (GLfloat x)
static int IROUND (float f)
Convert float to int by rounding to nearest integer, away from zero.
static GLint64 IROUND64 (float f)
Convert float to int64 by rounding to nearest integer.
static int IROUND_POS (float f)
Convert positive float to int by rounding to nearest integer.
static int F_TO_I (float f)
Convert float to int using a fast method.
static int IFLOOR (float f)
Return (as an integer) floor of float.
static int ICEIL (float f)
Return (as an integer) ceiling of float.
static int _mesa_is_pow_two (int x)
Is x a power of two?
static int32_t _mesa_next_pow_two_32 (uint32_t x)
Round given integer to next higer power of two If X is zero result is undefined.
static int64_t _mesa_next_pow_two_64 (uint64_t x)
static GLuint _mesa_logbase2 (GLuint n)
static GLboolean _mesa_little_endian (void)
Return 1 if this is a little endian machine, 0 if big endian.
void * _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
void * _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
void _mesa_align_free (void *ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
void * _mesa_align_realloc (void *oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
void * _mesa_exec_malloc (GLuint size)
void _mesa_exec_free (void *addr)
void * _mesa_realloc (void *oldBuffer, size_t oldSize, size_t newSize)
Reallocate memory.
int ffs (int i)
Find the first bit set in a word.
int ffsll (long long int i)
Find position of first bit set in given value.
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
static unsigned int _mesa_fls (unsigned int n)
Find the last (most significant) bit set in a word.
int _mesa_round_to_even (float val)
GLhalfARB _mesa_float_to_half (float f)
Convert a 4-byte float to a 2-byte half float.
float _mesa_half_to_float (GLhalfARB h)
Convert a 2-byte half float to a 4-byte float.
void * _mesa_bsearch (const void *key, const void *base, size_t nmemb, size_t size, int(*compar)(const void *, const void *))
Wrapper for bsearch().
char * _mesa_getenv (const char *var)
Wrapper for getenv().
char * _mesa_strdup (const char *s)
Implemented using malloc() and strcpy.
float _mesa_strtof (const char *s, char **end)
Wrapper around strtof()
unsigned int _mesa_str_checksum (const char *str)
Compute simple checksum/hash for a string.
int _mesa_snprintf (char *str, size_t size, const char *fmt,...) PRINTFLIKE(3
int int _mesa_vsnprintf (char *str, size_t size, const char *fmt, va_list arg)
Needed due to #ifdef's, above.
Detailed Description
Standard C library function wrappers.
This file provides wrappers for all the standard C library functions like malloc(), free(), printf(), getenv(), etc.
Macro Definition Documentation
#define acosf (f) ((float) acos(f))
#define acoshf (f) ((float) acosh(f))
#define ADD_POINTERS (A, B) ((GLubyte *) (A) + (uintptr_t) (B))
Referenced by _ae_ArrayElement(), _mesa_get_compressed_teximage(), _mesa_get_teximage(), _mesa_map_pbo_dest(), _mesa_map_pbo_source(), _mesa_max_buffer_index(), _mesa_validate_pbo_compressed_teximage(), _mesa_validate_pbo_teximage(), and unpack_image().
#define asinf (f) ((float) asin(f))
#define asinhf (f) ((float) asinh(f))
#define atan2f (x, y) ((float) atan2(x,y))
#define atanf (f) ((float) atan(f))
#define atanhf (f) ((float) atanh(f))
#define CALLOC (BYTES) calloc(1, BYTES)
Allocate and zero BYTES bytes.
#define CALLOC_STRUCT (T) (struct T *) calloc(1, sizeof(struct T))
Allocate and zero a structure of type T.
Referenced by _mesa_alloc_shared_state(), _mesa_create_framebuffer(), _mesa_create_visual(), _mesa_init_display_list(), _mesa_new_array_object(), _mesa_new_ati_fragment_shader(), _mesa_new_framebuffer(), _mesa_new_renderbuffer(), _mesa_new_sampler_object(), _mesa_new_texture_image(), _mesa_NewHashTable(), _mesa_PushAttrib(), _mesa_PushClientAttrib(), init_array_attrib_data(), make_list(), and new_transform_feedback().
#define ceilf (f) ((float) ceil(f))
#define CEILF (x) ((GLfloat) ceil(x))
#define cosf (f) ((float) cos(f))
#define coshf (f) ((float) cosh(f))
#define DEG2RAD (M_PI/180.0)
Referenced by _mesa_light().
#define exp2f (f) ((float) exp2(f))
#define expf (f) ((float) exp(f))
#define EXPF (x) ((GLfloat) exp(x))
#define FABSF (x) ((GLfloat) fabs(x))
#define FFS_DEFINED 1
#define floorf (f) ((float) floor(f))
#define FLOORF (x) ((GLfloat) floor(x))
Referenced by translate_id().
#define FREE (PTR) free(PTR)
Free memory.
#define FREXPF (x, y) ((GLfloat) frexp(x,y))
#define IS_INF_OR_NAN (x) (!finite(x))
#define LDEXPF (x, y) ((GLfloat) ldexp(x,y))
#define log2f (f) ((float) log2(f))
#define logf (f) ((float) log(f))
#define LOGF (x) ((GLfloat) log(x))
#define MALLOC (BYTES) malloc(BYTES)
Memory macros.
Allocate BYTES bytes
#define MALLOC_STRUCT (T) (struct T *) malloc(sizeof(struct T))
Allocate a structure of type T.
Referenced by _mesa_new_buffer_object(), _mesa_new_query_object(), _mesa_new_sync_object(), _mesa_new_texture_object(), _mesa_PushAttrib(), and save_attrib_data().
#define MAX_GLUINT 0xffffffff
#define MAX_GLUSHORT 0xffff
#define powf (x, y) ((float) pow(x,y))
Referenced by compute_light_positions(), and linear_to_srgb().
#define signbit (x) ((x) < 0.0f)
Referenced by DIFFERENT_SIGNS(), and IS_NEGATIVE().
#define sinf (f) ((float) sin(f))
#define sinhf (f) ((float) sinh(f))
#define sqrtf (f) ((float) sqrt(f))
Referenced by INV_SQRTF(), LEN_2FV(), LEN_3FV(), and update_modelview_scale().
#define tanf (f) ((float) tan(f))
#define tanhf (f) ((float) tanh(f))
Function Documentation
void* _mesa_align_calloc (size_t bytes, unsigned long alignment)
Same as _mesa_align_malloc(), but using calloc(1,) instead of malloc()
References _mesa_align_malloc(), ASSERT, NULL, and void().
void _mesa_align_free (void * ptr)
Free memory which was allocated with either _mesa_align_malloc() or _mesa_align_calloc().
Parameters
ptr pointer to the memory to be freed. The actual address to free is stored in the word immediately before the address the client sees.
Referenced by _mesa_align_realloc().
void* _mesa_align_malloc (size_t bytes, unsigned long alignment)
Allocate aligned memory.
Parameters
bytes number of bytes to allocate.
alignment alignment (must be greater than zero).
Allocates extra memory to accommodate rounding up the address for alignment and to record the real malloc address.
See Also
_mesa_align_free().
References ASSERT, and NULL.
Referenced by _mesa_align_calloc(), and _mesa_align_realloc().
void* _mesa_align_realloc (void * oldBuffer, size_t oldSize, size_t newSize, unsigned long alignment)
Reallocate memory, with alignment.
References _mesa_align_free(), _mesa_align_malloc(), and void().
unsigned int _mesa_bitcount (unsigned int n)
Return number of bits set in given GLuint.
Referenced by _mesa_DrawBuffers(), _mesa_drawbuffers(), and update_texture_state().
unsigned int _mesa_bitcount_64 (uint64_t n)
Return number of bits set in given 64-bit uint.
void* _mesa_bsearch (const void * key, const void * base, size_t nmemb, size_t size, int(*)(const void *, const void *) compar)
Wrapper for bsearch().
References NULL.
Referenced by _mesa_lookup_enum_by_name(), and _mesa_lookup_enum_by_nr().
void _mesa_exec_free (void * addr)
References mem_block::free.
void* _mesa_exec_malloc (GLuint size)
GLhalfARB _mesa_float_to_half (float val)
Convert a 4-byte float to a 2-byte half float.
Not all float32 values can be represented exactly as a float16 value. We round such intermediate float32 values to the nearest float16. When the float32 lies exactly between to float16 values, we round to the one with an even mantissa.
This rounding behavior has several benefits:
It has no sign bias.
It reproduces the behavior of real hardware: opcode F32TO16 in Intel's GPU ISA.
By reproducing the behavior of the GPU (at least on Intel hardware), compile-time evaluation of constant packHalf2x16 GLSL expressions will result in the same value as if the expression were executed on the GPU.
References _mesa_round_to_even(), fi_type::f, and fi_type::i.
Referenced by _mesa_pack_depth_span(), _mesa_pack_index_span(), _mesa_pack_rgba_span_float(), _mesa_pack_stencil_span(), _mesa_texstore_rgba_float16(), do_row(), pack_float_ALPHA_FLOAT16(), pack_float_LUMINANCE_ALPHA_FLOAT16(), pack_float_LUMINANCE_FLOAT16(), pack_float_RG_FLOAT16(), pack_float_RGB_FLOAT16(), pack_float_RGBA_FLOAT16(), pack_float_XBGR16161616_FLOAT(), pack_ubyte_ALPHA_FLOAT16(), pack_ubyte_LUMINANCE_ALPHA_FLOAT16(), pack_ubyte_LUMINANCE_FLOAT16(), pack_ubyte_RG_FLOAT16(), pack_ubyte_RGB_FLOAT16(), and pack_ubyte_RGBA_FLOAT16().
static unsigned int _mesa_fls (unsigned int n) inline static
Find the last (most significant) bit set in a word.
Essentially ffs() in the reverse direction.
char* _mesa_getenv (const char * var)
Wrapper for getenv().
References NULL.
Referenced by _mesa_init_debug(), _mesa_initialize_context(), _mesa_make_current(), get_extension_override(), get_shader_flags(), output_if_debug(), and should_output().
float _mesa_half_to_float (GLhalfARB val)
Convert a 2-byte half float to a 4-byte float.
Based on code from: http://www.opengl.org/discussion_boards/ubb/Forum3/HTML/008786.html
References fi_type::f, and fi_type::i.
Referenced by _mesa_unpack_depth_span(), clamp_half_to_uint(), do_row(), extract_float_rgba(), extract_uint_indexes(), unpack_ALPHA_FLOAT16(), unpack_INTENSITY_FLOAT16(), unpack_LUMINANCE_ALPHA_FLOAT16(), unpack_LUMINANCE_FLOAT16(), unpack_R_FLOAT16(), unpack_RG_FLOAT16(), unpack_RGB_FLOAT16(), unpack_RGBA_FLOAT16(), and unpack_XBGR16161616_FLOAT().
static int _mesa_is_pow_two (int x) inline static
Is x a power of two?
Referenced by _mesa_legal_texture_dimensions(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), and _mesa_PixelMapusv().
static GLboolean _mesa_little_endian (void) inline static
Return 1 if this is a little endian machine, 0 if big endian.
References GLubyte.
Referenced by _mesa_format_matches_format_and_type(), _mesa_texstore_argb8888(), _mesa_texstore_dudv8(), _mesa_texstore_rgba8888(), _mesa_texstore_unorm88(), _mesa_texstore_ycbcr(), and type_mapping().
static GLuint _mesa_logbase2 (GLuint n) inline static
Referenced by _mesa_get_tex_max_num_levels(), and _mesa_init_teximage_fields().
static int32_t _mesa_next_pow_two_32 (uint32_t x) inline static
Round given integer to next higer power of two If X is zero result is undefined.
Source for the fallback implementation is Sean Eron Anderson's webpage "Bit Twiddling Hacks" http://graphics.stanford.edu/~seander/bithacks.html
When using builtin function have to do some work for case when passed values 1 to prevent hiting undefined result from __builtin_clz. Undefined results would be different depending on optimization level used for build.
static int64_t _mesa_next_pow_two_64 (uint64_t x) inline static
void* _mesa_realloc (void * oldBuffer, size_t oldSize, size_t newSize)
Reallocate memory.
Referenced by _mesa_buffer_data(), and attach_shader().
int _mesa_round_to_even (float val)
References IROUND().
Referenced by _mesa_float_to_half().
int _mesa_snprintf (char * str, size_t size, const char * fmt, ...)
unsigned int _mesa_str_checksum (const char * str)
Compute simple checksum/hash for a string.
Referenced by _mesa_ShaderSource(), and shader_source().
char* _mesa_strdup (const char * s)
Implemented using malloc() and strcpy.
Note that NULL is handled accordingly.
References NULL.
Referenced by _mesa_CreateShaderProgramEXT(), _mesa_TransformFeedbackVaryings(), and read_shader().
float _mesa_strtof (const char * s, char ** end)
Wrapper around strtof()
References NULL.
int int _mesa_vsnprintf (char * str, size_t size, const char * fmt, va_list args)
Needed due to #ifdef's, above.
Referenced by _mesa_debug(), _mesa_error(), _mesa_gl_debug(), _mesa_problem(), and _mesa_warning().
static int F_TO_I (float f) inline static
Convert float to int using a fast method.
The rounding mode may vary. XXX We could use an x86-64/SSE2 version here.
References IROUND().
Referenced by _mesa_apply_ci_transfer_ops(), _mesa_map_rgba(), _mesa_pack_rgba_span_float(), clamp_float_to_uint(), and clamp_half_to_uint().
int ffs (int i)
Find the first bit set in a word.
Referenced by __bitset_ffs(), _mesa_drawbuffers(), ffsll(), get_temp(), and update_texture_state().
int ffsll (long long int val)
Find position of first bit set in given value.
XXX Warning: this function can only be used on 64-bit systems!
Returns
position of least-significant bit set, starting at 1, return zero if no bits set.
References ffs().
Referenced by compute_max_element().
static int ICEIL (float f) inline static
Return (as an integer) ceiling of float.
References fi_type::f, fi_type::i, and IROUND().
static int IFLOOR (float f) inline static
Return (as an integer) floor of float.
References fi_type::f, fi_type::i, and IROUND().
Referenced by _mesa_Bitmap().
static float INV_SQRTF (float x) inline static
single-precision inverse square root
References sqrtf.
Referenced by NORMALIZE_3FV(), and update_modelview_scale().
static int IROUND (float f) inline static
Convert float to int by rounding to nearest integer, away from zero.
References F.
Referenced by _mesa_CopyPixels(), _mesa_DrawPixels(), _mesa_GetIntegerv(), _mesa_GetMaterialiv(), _mesa_GetnMapivARB(), _mesa_PixelStoref(), _mesa_round_to_even(), F_TO_I(), ICEIL(), IFLOOR(), and store_pixelmap().
static GLint64 IROUND64 (float f) inline static
Convert float to int64 by rounding to nearest integer.
References F.
Referenced by _mesa_GetInteger64v().
static int IROUND_POS (float f) inline static
Convert positive float to int by rounding to nearest integer.
References F.
static GLfloat LOG2 (GLfloat x) inline static
References fi_type::f, and fi_type::i.