Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
light.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_ShadeModel (GLenum mode)
void GLAPIENTRY _mesa_ProvokingVertex (GLenum mode)
Set the provoking vertex (the vertex which specifies the prim's color when flat shading) to either the first or last vertex of the triangle or line.
void GLAPIENTRY _mesa_ColorMaterial (GLenum face, GLenum mode)
void GLAPIENTRY _mesa_Lightf (GLenum light, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_Lightfv (GLenum light, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_Lightiv (GLenum light, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_Lighti (GLenum light, GLenum pname, GLint param)
void GLAPIENTRY _mesa_LightModelf (GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_LightModelfv (GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_LightModeli (GLenum pname, GLint param)
void GLAPIENTRY _mesa_LightModeliv (GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_GetLightfv (GLenum light, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetLightiv (GLenum light, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetMaterialfv (GLenum face, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetMaterialiv (GLenum face, GLenum pname, GLint *params)
void _mesa_light (struct gl_context *ctx, GLuint lnum, GLenum pname, const GLfloat *params)
Helper function called by _mesa_Lightfv and _mesa_PopAttrib to set per-light state.
GLuint _mesa_material_bitmask (struct gl_context *ctx, GLenum face, GLenum pname, GLuint legal, const char *)
void _mesa_update_lighting (struct gl_context *ctx)
Examine current lighting parameters to determine if the optimized lighting function can be used.
void _mesa_update_tnl_spaces (struct gl_context *ctx, GLuint new_state)
Bring up to date any state that relies on _NeedEyeCoords.
void _mesa_update_material (struct gl_context *ctx, GLuint bitmask)
void _mesa_update_color_material (struct gl_context *ctx, const GLfloat rgba[4])
void _mesa_init_lighting (struct gl_context *ctx)
Initialize all lighting state for the given context.
void _mesa_free_lighting_data (struct gl_context *ctx)
Deallocate malloc'd lighting state attached to given context.
void _mesa_allow_light_in_model (struct gl_context *ctx, GLboolean flag)
Drivers may need this if the hardware tnl unit doesn't support the light-in-modelspace optimization.
Function Documentation
void _mesa_allow_light_in_model (struct gl_context * ctx, GLboolean flag)
Drivers may need this if the hardware tnl unit doesn't support the light-in-modelspace optimization.
It's also useful for debugging.
References gl_context::_ForceEyeCoords, _NEW_POINT, and gl_context::NewState.
void GLAPIENTRY _mesa_ColorMaterial (GLenum face, GLenum mode)
References _mesa_debug(), _mesa_lookup_enum_by_nr(), _mesa_material_bitmask(), _mesa_update_color_material(), _NEW_LIGHT, FLUSH_CURRENT, FLUSH_VERTICES, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_SPECULAR, MESA_VERBOSE, VERBOSE_API, and VERT_ATTRIB_COLOR0.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_free_lighting_data (struct gl_context * ctx)
Deallocate malloc'd lighting state attached to given context.
Referenced by _mesa_free_context_data().
void GLAPIENTRY _mesa_GetLightfv (GLenum light, GLenum pname, GLfloat * params)
References _mesa_error(), COPY_3V, and COPY_4V.
Referenced by _mesa_GetLightxv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetLightiv (GLenum light, GLenum pname, GLint * params)
References _mesa_error(), and FLOAT_TO_INT.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetMaterialfv (GLenum face, GLenum pname, GLfloat * params)
References _mesa_error(), API_OPENGL_COMPAT, COPY_4FV(), FLUSH_CURRENT, FLUSH_VERTICES, MAT_ATTRIB_AMBIENT, MAT_ATTRIB_DIFFUSE, MAT_ATTRIB_EMISSION, MAT_ATTRIB_INDEXES, MAT_ATTRIB_SHININESS, and MAT_ATTRIB_SPECULAR.
Referenced by _mesa_GetMaterialxv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetMaterialiv (GLenum face, GLenum pname, GLint * params)
References _mesa_error(), API_OPENGL_COMPAT, ASSERT, FLOAT_TO_INT, FLUSH_CURRENT, FLUSH_VERTICES, IROUND(), MAT_ATTRIB_AMBIENT, MAT_ATTRIB_DIFFUSE, MAT_ATTRIB_EMISSION, MAT_ATTRIB_INDEXES, MAT_ATTRIB_SHININESS, and MAT_ATTRIB_SPECULAR.
Referenced by _mesa_initialize_exec_table().
void _mesa_init_lighting (struct gl_context * ctx)
Initialize all lighting state for the given context.
References gl_light_attrib::_ClampVertexColor, gl_light_attrib::_ColorMaterialBitmask, gl_context::_ForceEyeCoords, _mesa_material_bitmask(), gl_context::_ModelViewInvScale, gl_light_attrib::_NeedEyeCoords, gl_context::_NeedEyeCoords, gl_context::API, API_OPENGL_COMPAT, gl_light_attrib::ClampVertexColor, gl_light_attrib::ColorMaterialEnabled, gl_light_attrib::ColorMaterialFace, gl_light_attrib::ColorMaterialMode, gl_light_attrib::Enabled, gl_light_attrib::EnabledList, init_light(), init_lightmodel(), init_material(), gl_light_attrib::Light, gl_context::Light, make_empty_list, gl_light_attrib::Material, MAX_LIGHTS, gl_light_attrib::Model, NULL, gl_light_attrib::ProvokingVertex, and gl_light_attrib::ShadeModel.
Referenced by init_attrib_groups().
void _mesa_light (struct gl_context * ctx, GLuint lnum, GLenum pname, const GLfloat * params)
Helper function called by _mesa_Lightfv and _mesa_PopAttrib to set per-light state.
For GL_POSITION and GL_SPOT_DIRECTION the params position/direction will have already been transformed by the modelview matrix! Also, all error checking should have already been done.
References gl_light::_CosCutoff, gl_light::_Flags, _mesa_problem(), _NEW_LIGHT, gl_light::Ambient, ASSERT, gl_context::Const, gl_light::ConstantAttenuation, COPY_3V, COPY_4V, DEG2RAD, gl_light::Diffuse, gl_context::Driver, gl_light::EyePosition, FLUSH_VERTICES, gl_light_attrib::Light, gl_context::Light, LIGHT_POSITIONAL, LIGHT_SPOT, dd_function_table::Lightfv, gl_light::LinearAttenuation, MAX_LIGHTS, gl_constants::MaxSpotExponent, gl_light::QuadraticAttenuation, gl_light::Specular, gl_light::SpotCutoff, gl_light::SpotDirection, gl_light::SpotExponent, TEST_EQ_3V, and TEST_EQ_4V.
Referenced by _mesa_Lightfv(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_Lightf (GLenum light, GLenum pname, GLfloat param)
References _mesa_Lightfv().
Referenced by _mesa_initialize_exec_table(), and _mesa_Lightx().
void GLAPIENTRY _mesa_Lightfv (GLenum light, GLenum pname, const GLfloat * params)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_error(), _mesa_light(), TRANSFORM_DIRECTION, and TRANSFORM_POINT.
Referenced by _mesa_initialize_exec_table(), _mesa_Lightf(), _mesa_Lightiv(), and _mesa_Lightxv().
void GLAPIENTRY _mesa_Lighti (GLenum light, GLenum pname, GLint param)
References _mesa_Lightiv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Lightiv (GLenum light, GLenum pname, const GLint * params)
References _mesa_Lightfv(), and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_Lighti().
void GLAPIENTRY _mesa_LightModelf (GLenum pname, GLfloat param)
References _mesa_LightModelfv().
Referenced by _mesa_initialize_exec_table(), _mesa_LightModelx(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_LightModelfv (GLenum pname, const GLfloat * params)
References _mesa_error(), _NEW_LIGHT, API_OPENGL_COMPAT, COPY_4V, FLUSH_VERTICES, and TEST_EQ_4V.
Referenced by _mesa_initialize_exec_table(), _mesa_LightModelf(), _mesa_LightModeliv(), _mesa_LightModelxv(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_LightModeli (GLenum pname, GLint param)
References _mesa_LightModeliv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_LightModeliv (GLenum pname, const GLint * params)
References _mesa_LightModelfv(), ASSIGN_4V, F, and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table(), and _mesa_LightModeli().
GLuint _mesa_material_bitmask (struct gl_context * ctx, GLenum face, GLenum pname, GLuint legal, const char *)
References _mesa_error(), BACK_MATERIAL_BITS, FRONT_MATERIAL_BITS, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_INDEXES, MAT_BIT_BACK_SHININESS, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_INDEXES, MAT_BIT_FRONT_SHININESS, and MAT_BIT_FRONT_SPECULAR.
Referenced by _mesa_ColorMaterial(), _mesa_init_lighting(), and save_Materialfv().
void GLAPIENTRY _mesa_ProvokingVertex (GLenum mode)
Set the provoking vertex (the vertex which specifies the prim's color when flat shading) to either the first or last vertex of the triangle or line.
References _mesa_debug(), _mesa_error(), _NEW_LIGHT, FLUSH_VERTICES, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and save_ProvokingVertexEXT().
void GLAPIENTRY _mesa_ShadeModel (GLenum mode)
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _NEW_LIGHT, FLUSH_VERTICES, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_update_color_material (struct gl_context * ctx, const GLfloat rgba[4])
References gl_light_attrib::_ColorMaterialBitmask, _mesa_update_material(), gl_material::Attrib, COPY_4FV(), GLbitfield, gl_context::Light, MAT_ATTRIB_MAX, and gl_light_attrib::Material.
Referenced by _mesa_ColorMaterial(), and _mesa_set_enable().
void _mesa_update_lighting (struct gl_context * ctx)
Examine current lighting parameters to determine if the optimized lighting function can be used.
Also, precompute some lighting values such as the products of light source and material ambient, diffuse and specular coefficients.
References gl_light::_Flags, _mesa_update_material(), gl_light_attrib::_NeedEyeCoords, gl_light_attrib::_NeedVertices, gl_lightmodel::ColorControl, gl_light_attrib::Enabled, gl_light_attrib::EnabledList, GLbitfield, gl_context::Light, LIGHT_POSITIONAL, LIGHT_SPOT, gl_lightmodel::LocalViewer, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_SPECULAR, gl_light_attrib::Model, and gl_lightmodel::TwoSide.
Referenced by _mesa_update_state_locked().
void _mesa_update_material (struct gl_context * ctx, GLuint bitmask)
References gl_light_attrib::_BaseColor, gl_light::_MatAmbient, gl_light::_MatDiffuse, gl_light::_MatSpecular, _mesa_debug(), ACC_SCALE_3V, gl_light::Ambient, gl_lightmodel::Ambient, gl_material::Attrib, COPY_3V, gl_light::Diffuse, gl_light_attrib::EnabledList, gl_context::Light, MAT_ATTRIB_BACK_AMBIENT, MAT_ATTRIB_BACK_DIFFUSE, MAT_ATTRIB_BACK_EMISSION, MAT_ATTRIB_BACK_SPECULAR, MAT_ATTRIB_FRONT_AMBIENT, MAT_ATTRIB_FRONT_DIFFUSE, MAT_ATTRIB_FRONT_EMISSION, MAT_ATTRIB_FRONT_SPECULAR, MAT_BIT_BACK_AMBIENT, MAT_BIT_BACK_DIFFUSE, MAT_BIT_BACK_EMISSION, MAT_BIT_BACK_SPECULAR, MAT_BIT_FRONT_AMBIENT, MAT_BIT_FRONT_DIFFUSE, MAT_BIT_FRONT_EMISSION, MAT_BIT_FRONT_SPECULAR, gl_light_attrib::Material, MESA_VERBOSE, gl_light_attrib::Model, SCALE_3V, gl_light::Specular, and VERBOSE_MATERIAL.
Referenced by _mesa_update_color_material(), and _mesa_update_lighting().
void _mesa_update_tnl_spaces (struct gl_context * ctx, GLuint new_state)
Bring up to date any state that relies on _NeedEyeCoords.
References gl_point_attrib::_Attenuated, gl_context::_ForceEyeCoords, gl_texture_attrib::_GenFlags, _math_matrix_is_length_preserving(), gl_light_attrib::_NeedEyeCoords, gl_context::_NeedEyeCoords, _NEW_LIGHT, _NEW_MODELVIEW, compute_light_positions(), gl_context::Driver, gl_light_attrib::Enabled, gl_context::Light, dd_function_table::LightingSpaceChange, gl_context::ModelviewMatrixStack, gl_context::NewState, gl_context::Point, TEXGEN_NEED_EYE_COORD, gl_context::Texture, gl_matrix_stack::Top, update_modelview_scale(), and void().
Referenced by _mesa_update_state_locked().