Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
mipmap.h File Reference
#include "mtypes.h"
Functions
void _mesa_generate_mipmap_level (GLenum target, GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte **srcData, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte **dstData, GLint dstRowStride)
Down-sample a texture image to produce the next lower mipmap level.
GLboolean _mesa_prepare_mipmap_level (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint level, GLsizei width, GLsizei height, GLsizei depth, GLsizei border, GLenum intFormat, gl_format format)
Helper function for mipmap generation.
void _mesa_generate_mipmap (struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj)
Automatic mipmap generation.
Function Documentation
void _mesa_generate_mipmap (struct gl_context * ctx, GLenum target, struct gl_texture_object * texObj)
Automatic mipmap generation.
This is the fallback/default function for ctx->Driver.GenerateMipmap(). Generate a complete set of mipmaps from texObj's BaseLevel image. Stop at texObj's MaxLevel or when we get to the 1x1 texture. For cube maps, target will be one of GL_TEXTURE_CUBE_MAP_POSITIVE/NEGATIVE_X/Y/Z; never GL_TEXTURE_CUBE_MAP.
References _mesa_is_format_compressed(), _mesa_max_texture_levels(), _mesa_select_tex_image(), ASSERT, gl_texture_object::BaseLevel, generate_mipmap_compressed(), generate_mipmap_uncompressed(), gl_texture_object::MaxLevel, MIN2, gl_texture_object::Target, and gl_texture_image::TexFormat.
void _mesa_generate_mipmap_level (GLenum target, GLenum datatype, GLuint comps, GLint border, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLubyte ** srcData, GLint srcRowStride, GLint dstWidth, GLint dstHeight, GLint dstDepth, GLubyte ** dstData, GLint dstRowStride)
Down-sample a texture image to produce the next lower mipmap level.
Parameters
comps components per texel (1, 2, 3 or 4)
srcData array[slice] of pointers to source image slices
dstData array[slice] of pointers to dest image slices
srcRowStride stride between source rows, in bytes
dstRowStride stride between destination rows, in bytes
References _mesa_problem(), GL_TEXTURE_EXTERNAL_OES, make_1d_mipmap(), make_2d_mipmap(), make_3d_mipmap(), and NULL.
Referenced by generate_mipmap_compressed(), and generate_mipmap_uncompressed().
GLboolean _mesa_prepare_mipmap_level (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint level, GLsizei width, GLsizei height, GLsizei depth, GLsizei border, GLenum intFormat, gl_format format)
Helper function for mipmap generation.
Make sure the specified destination mipmap level is the right size/format for mipmap generation. If not, (re) allocate it.
Returns
GL_TRUE if successful, GL_FALSE if mipmap generation should stop
References _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_num_tex_faces(), _mesa_update_fbo_texture(), _NEW_TEXTURE, dd_function_table::AllocTextureImageBuffer, gl_texture_image::Border, gl_texture_image::Depth, gl_context::Driver, dd_function_table::FreeTextureImageBuffer, gl_texture_image::Height, gl_texture_object::Image, gl_texture_object::Immutable, gl_texture_image::InternalFormat, gl_context::NewState, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by generate_mipmap_compressed(), and generate_mipmap_uncompressed().