Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
mm.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include "compiler.h"
#include "mm.h"
Functions
void mmDumpMemInfo (const struct mem_block *heap)
For debuging purpose.
struct mem_block * mmInit (unsigned ofs, unsigned size)
input: total size in bytes return: a heap pointer if OK, NULL if error
static struct mem_block * SliceBlock (struct mem_block *p, unsigned startofs, unsigned size, unsigned reserved, unsigned alignment)
struct mem_block * mmAllocMem (struct mem_block *heap, unsigned size, unsigned align2, unsigned startSearch)
Allocate 'size' bytes with 2^align2 bytes alignment, restrict the search to free memory after 'startSearch' depth and back buffers should be in different 4mb banks to get better page hits if possible input: size = size of block align2 = 2^align2 bytes alignment startSearch = linear offset from start of heap to begin search return: pointer to the allocated block, 0 if error.
struct mem_block * mmFindBlock (struct mem_block *heap, unsigned start)
Free block starts at offset input: pointer to a heap, start offset return: pointer to a block.
static int Join2Blocks (struct mem_block *p)
int mmFreeMem (struct mem_block *b)
Free block starts at offset input: pointer to a block return: 0 if OK, -1 if error.
void mmDestroy (struct mem_block *heap)
destroy MM
Function Documentation
static int Join2Blocks (struct mem_block * p) inline static
References mem_block::free, mem_block::next, mem_block::next_free, mem_block::ofs, mem_block::prev, mem_block::prev_free, and mem_block::size.
Referenced by mmFreeMem().
struct mem_block* mmAllocMem (struct mem_block * heap, unsigned size, unsigned align2, unsigned startSearch) read
Allocate 'size' bytes with 2^align2 bytes alignment, restrict the search to free memory after 'startSearch' depth and back buffers should be in different 4mb banks to get better page hits if possible input: size = size of block align2 = 2^align2 bytes alignment startSearch = linear offset from start of heap to begin search return: pointer to the allocated block, 0 if error.
References mem_block::free, mem_block::next_free, NULL, mem_block::ofs, mem_block::size, size, and SliceBlock().
void mmDestroy (struct mem_block * heap)
destroy MM
References mem_block::free, and mem_block::next.
void mmDumpMemInfo (const struct mem_block * heap)
For debuging purpose.
References mem_block::free, mem_block::next, mem_block::next_free, mem_block::ofs, mem_block::reserved, and mem_block::size.
struct mem_block* mmFindBlock (struct mem_block * heap, unsigned start) read
Free block starts at offset input: pointer to a heap, start offset return: pointer to a block.
References mem_block::next, NULL, and mem_block::ofs.
int mmFreeMem (struct mem_block * b)
Free block starts at offset input: pointer to a block return: 0 if OK, -1 if error.
References mem_block::free, mem_block::heap, Join2Blocks(), mem_block::next_free, mem_block::prev, mem_block::prev_free, and mem_block::reserved.
struct mem_block* mmInit (unsigned ofs, unsigned size) read
input: total size in bytes return: a heap pointer if OK, NULL if error
References mem_block::free, mem_block::heap, mem_block::next, mem_block::next_free, NULL, mem_block::ofs, mem_block::prev, mem_block::prev_free, mem_block::size, and size.
static struct mem_block* SliceBlock (struct mem_block * p, unsigned startofs, unsigned size, unsigned reserved, unsigned alignment) static read
References mem_block::free, mem_block::heap, mem_block::next, mem_block::next_free, NULL, mem_block::ofs, mem_block::prev, mem_block::prev_free, mem_block::reserved, mem_block::size, and size.
Referenced by mmAllocMem().