Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
multisample.h File Reference
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_SampleCoverage (GLclampf value, GLboolean invert)
Called via glSampleCoverageARB.
void _mesa_init_multisample (struct gl_context *ctx)
Initialize the context's multisample state.
void GLAPIENTRY _mesa_GetMultisamplefv (GLenum pname, GLuint index, GLfloat *val)
void GLAPIENTRY _mesa_SampleMaski (GLuint index, GLbitfield mask)
GLenum _mesa_check_sample_count (struct gl_context *ctx, GLenum target, GLenum internalFormat, GLsizei samples)
Function Documentation
GLenum _mesa_check_sample_count (struct gl_context * ctx, GLenum target, GLenum internalFormat, GLsizei samples)
References _mesa_is_depth_or_stencil_format(), _mesa_is_enum_format_integer(), gl_extensions::ARB_internalformat_query, gl_extensions::ARB_texture_multisample, gl_context::Const, gl_context::Driver, gl_context::Extensions, gl_constants::MaxColorTextureSamples, gl_constants::MaxDepthTextureSamples, gl_constants::MaxIntegerSamples, gl_constants::MaxSamples, and dd_function_table::QuerySamplesForFormat.
Referenced by renderbuffer_storage(), and teximagemultisample().
void GLAPIENTRY _mesa_GetMultisamplefv (GLenum pname, GLuint index, GLfloat * val)
References _mesa_error(), _mesa_is_winsys_fbo(), _mesa_update_state(), and _NEW_BUFFERS.
Referenced by _mesa_initialize_exec_table().
void _mesa_init_multisample (struct gl_context * ctx)
Initialize the context's multisample state.
Parameters
ctx the GL context.
References gl_multisample_attrib::Enabled, GLbitfield, gl_context::Multisample, gl_multisample_attrib::SampleAlphaToCoverage, gl_multisample_attrib::SampleAlphaToOne, gl_multisample_attrib::SampleCoverage, gl_multisample_attrib::SampleCoverageInvert, gl_multisample_attrib::SampleCoverageValue, gl_multisample_attrib::SampleMask, and gl_multisample_attrib::SampleMaskValue.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_SampleCoverage (GLclampf value, GLboolean invert)
Called via glSampleCoverageARB.
References _NEW_MULTISAMPLE, CLAMP, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table(), _mesa_PopAttrib(), and _mesa_SampleCoveragex().
void GLAPIENTRY _mesa_SampleMaski (GLuint index, GLbitfield mask)
References _mesa_error(), _NEW_MULTISAMPLE, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().