Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
pack.h File Reference
#include "mtypes.h"
Functions
void _mesa_unpack_polygon_stipple (const GLubyte *pattern, GLuint dest[32], const struct gl_pixelstore_attrib *unpacking)
void _mesa_pack_polygon_stipple (const GLuint pattern[32], GLubyte *dest, const struct gl_pixelstore_attrib *packing)
GLvoid * _mesa_unpack_bitmap (GLint width, GLint height, const GLubyte *pixels, const struct gl_pixelstore_attrib *packing)
void _mesa_pack_bitmap (GLint width, GLint height, const GLubyte *source, GLubyte *dest, const struct gl_pixelstore_attrib *packing)
void _mesa_pack_rgba_span_float (struct gl_context *ctx, GLuint n, GLfloat rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid *dstAddr, const struct gl_pixelstore_attrib *dstPacking, GLbitfield transferOps)
Used to pack an array [][4] of RGBA float colors as specified by the dstFormat, dstType and dstPacking.
void _mesa_unpack_color_span_ubyte (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLubyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
void _mesa_unpack_color_span_float (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLfloat dest[], GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
Same as _mesa_unpack_color_span_ubyte(), but return GLfloat data instead of GLubyte.
void _mesa_unpack_color_span_uint (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLuint *dest, GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking)
Same as _mesa_unpack_color_span_ubyte(), but return GLuint data instead of GLubyte.
void _mesa_unpack_dudv_span_byte (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLbyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
Similar to _mesa_unpack_color_span_float(), but for dudv data instead of rgba, directly return GLbyte data, no transfer ops apply.
void _mesa_unpack_index_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
void _mesa_pack_index_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, const GLuint *source, const struct gl_pixelstore_attrib *dstPacking, GLbitfield transferOps)
void _mesa_unpack_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
void _mesa_pack_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, const GLubyte *source, const struct gl_pixelstore_attrib *dstPacking)
void _mesa_unpack_depth_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLuint depthMax, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking)
Unpack a row of depth/z values from memory, returning GLushort, GLuint or GLfloat values.
void _mesa_pack_depth_span (struct gl_context *ctx, GLuint n, GLvoid *dest, GLenum dstType, const GLfloat *depthSpan, const struct gl_pixelstore_attrib *dstPacking)
void _mesa_pack_depth_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLuint *dest, const GLfloat *depthVals, const GLubyte *stencilVals, const struct gl_pixelstore_attrib *dstPacking)
Pack depth and stencil values as GL_DEPTH_STENCIL (GL_UNSIGNED_INT_24_8 etc)
void * _mesa_unpack_image (GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *unpack)
Unpack image data.
void _mesa_pack_rgba_span_from_uints (struct gl_context *ctx, GLuint n, GLuint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid *dstAddr)
void _mesa_pack_rgba_span_from_ints (struct gl_context *ctx, GLuint n, GLint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid *dstAddr)
void _mesa_rebase_rgba_float (GLuint n, GLfloat rgba[][4], GLenum baseFormat)
If we unpack colors from a luminance surface, we'll get pixel colors such as (l, l, l, a).
void _mesa_rebase_rgba_uint (GLuint n, GLuint rgba[][4], GLenum baseFormat)
As above, but GLuint components.
Function Documentation
void _mesa_pack_bitmap (GLint width, GLint height, const GLubyte * source, GLubyte * dest, const struct gl_pixelstore_attrib * packing)
References _mesa_image_address2d(), CEILING, flip_bytes(), GLubyte, gl_pixelstore_attrib::LsbFirst, and gl_pixelstore_attrib::SkipPixels.
Referenced by _mesa_pack_polygon_stipple().
void _mesa_pack_depth_span (struct gl_context * ctx, GLuint n, GLvoid * dest, GLenum dstType, const GLfloat * depthSpan, const struct gl_pixelstore_attrib * dstPacking)
References _mesa_error(), _mesa_float_to_half(), _mesa_problem(), _mesa_scale_and_bias_depth(), _mesa_swap2(), _mesa_swap4(), CLAMPED_FLOAT_TO_USHORT, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, FLOAT_TO_BYTE, FLOAT_TO_INT, FLOAT_TO_SHORT, FLOAT_TO_UBYTE, FLOAT_TO_UINT, GLbyte, GLshort, GLubyte, GLushort, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by get_tex_depth(), and read_depth_pixels().
void _mesa_pack_depth_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLuint * dest, const GLfloat * depthVals, const GLubyte * stencilVals, const struct gl_pixelstore_attrib * dstPacking)
Pack depth and stencil values as GL_DEPTH_STENCIL (GL_UNSIGNED_INT_24_8 etc)
References _mesa_apply_stencil_transfer_ops(), _mesa_error(), _mesa_scale_and_bias_depth(), _mesa_swap4(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, GLubyte, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by slow_read_depth_stencil_pixels_separate().
void _mesa_pack_index_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, const GLuint * source, const struct gl_pixelstore_attrib * dstPacking, GLbitfield transferOps)
References _mesa_apply_ci_transfer_ops(), _mesa_error(), _mesa_float_to_half(), _mesa_problem(), _mesa_swap2(), _mesa_swap4(), GLbyte, GLshort, GLubyte, GLushort, IMAGE_MAP_COLOR_BIT, IMAGE_SHIFT_OFFSET_BIT, and gl_pixelstore_attrib::SwapBytes.
void _mesa_pack_polygon_stipple (const GLuint pattern[32], GLubyte * dest, const struct gl_pixelstore_attrib * packing)
References _mesa_pack_bitmap(), and GLubyte.
Referenced by _mesa_GetnPolygonStippleARB().
void _mesa_pack_rgba_span_float (struct gl_context * ctx, GLuint n, GLfloat rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid * dstAddr, const struct gl_pixelstore_attrib * dstPacking, GLbitfield transferOps)
Used to pack an array [][4] of RGBA float colors as specified by the dstFormat, dstType and dstPacking.
Used by glReadPixels. Historically, the RGBA values were in [0,1] and rescaled to fit into GLubytes, etc. But with new integer formats, the RGBA values may have any value and we don't always rescale when converting to integers.
Note: the rgba values will be modified by this function when any pixel transfer ops are enabled.
References _mesa_apply_rgba_transfer_ops(), _mesa_components_in_format(), _mesa_error(), _mesa_float_to_half(), _mesa_is_enum_format_integer(), _mesa_problem(), _mesa_sizeof_packed_type(), _mesa_swap2(), _mesa_swap4(), ACOMP, BCOMP, CLAMP, CLAMPED_FLOAT_TO_USHORT, F, F_TO_I(), FLOAT_TO_BYTE, FLOAT_TO_INT, FLOAT_TO_SHORT, FLOAT_TO_UBYTE, FLOAT_TO_UINT, FLOAT_TO_USHORT, GCOMP, get_type_min_max(), GLbyte, GLshort, GLubyte, GLushort, IMAGE_CLAMP_BIT, NULL, RCOMP, gl_pixelstore_attrib::SwapBytes, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_pack_rgba_span_from_ints (struct gl_context * ctx, GLuint n, GLint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid * dstAddr)
References _pack_rgba_span_from_ints_problem(), ACOMP, BCOMP, CLAMP, GCOMP, GLubyte, GLushort, and RCOMP.
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_pack_rgba_span_from_uints (struct gl_context * ctx, GLuint n, GLuint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid * dstAddr)
References _pack_rgba_span_from_uints_problem(), ACOMP, BCOMP, GCOMP, GLubyte, GLushort, MIN2, and RCOMP.
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_pack_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, const GLubyte * source, const struct gl_pixelstore_attrib * dstPacking)
References _mesa_apply_stencil_transfer_ops(), _mesa_error(), _mesa_float_to_half(), _mesa_problem(), _mesa_swap2(), _mesa_swap4(), GLbyte, GLshort, GLubyte, GLushort, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixelstore_attrib::LsbFirst, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by read_stencil_pixels().
void _mesa_rebase_rgba_float (GLuint n, GLfloat rgba[][4], GLenum baseFormat)
If we unpack colors from a luminance surface, we'll get pixel colors such as (l, l, l, a).
When we call _mesa_pack_rgba_span_float(format=GL_LUMINANCE), that function will compute L=R+G+B before packing. The net effect is we'll accidentally store luminance values = 3*l. This function compensates for that by converting (aka rebasing) (l,l,l,a) to be (l,0,0,a). It's a similar story for other formats such as LUMINANCE_ALPHA, ALPHA and INTENSITY.
Finally, we also need to do this when the actual surface format does not match the logical surface format. For example, suppose the user requests a GL_LUMINANCE texture but the driver stores it as RGBA. Again, we'll get pixel values like (l,l,l,a).
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_rebase_rgba_uint (GLuint n, GLuint rgba[][4], GLenum baseFormat)
As above, but GLuint components.
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
GLvoid* _mesa_unpack_bitmap (GLint width, GLint height, const GLubyte * pixels, const struct gl_pixelstore_attrib * packing)
References _mesa_image_address2d(), CEILING, flip_bytes(), GLubyte, gl_pixelstore_attrib::LsbFirst, NULL, and gl_pixelstore_attrib::SkipPixels.
Referenced by _mesa_unpack_polygon_stipple(), and unpack_image().
void _mesa_unpack_color_span_float (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLfloat dest[], GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
Same as _mesa_unpack_color_span_ubyte(), but return GLfloat data instead of GLubyte.
References _mesa_apply_rgba_transfer_ops(), _mesa_components_in_format(), _mesa_error(), _mesa_is_enum_format_integer(), _mesa_map_ci_to_rgba(), _mesa_shift_and_offset_ci(), ACOMP, ASSERT, BCOMP, extract_float_rgba(), extract_uint_indexes(), GCOMP, get_component_indexes(), IMAGE_MAP_COLOR_BIT, IMAGE_SCALE_BIAS_BIT, IMAGE_SHIFT_OFFSET_BIT, RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_make_temp_float_image().
void _mesa_unpack_color_span_ubyte (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLubyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_apply_rgba_transfer_ops(), _mesa_components_in_format(), _mesa_error(), _mesa_is_enum_format_integer(), _mesa_map_ci_to_rgba(), _mesa_shift_and_offset_ci(), ACOMP, ASSERT, BCOMP, CLAMPED_FLOAT_TO_UBYTE, extract_float_rgba(), extract_uint_indexes(), GCOMP, get_component_indexes(), GLubyte, IMAGE_CLAMP_BIT, IMAGE_MAP_COLOR_BIT, IMAGE_SCALE_BIAS_BIT, IMAGE_SHIFT_OFFSET_BIT, RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_make_temp_ubyte_image().
void _mesa_unpack_color_span_uint (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLuint * dest, GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking)
Same as _mesa_unpack_color_span_ubyte(), but return GLuint data instead of GLubyte.
No pixel transfer ops are applied.
References _mesa_components_in_format(), _mesa_error(), ACOMP, ASSERT, BCOMP, extract_uint_rgba(), GCOMP, get_component_indexes(), RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by make_temp_uint_image().
void _mesa_unpack_depth_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLuint depthMax, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking)
Unpack a row of depth/z values from memory, returning GLushort, GLuint or GLfloat values.
The glPixelTransfer (scale/bias) params will be applied.
Parameters
dstType one of GL_UNSIGNED_SHORT, GL_UNSIGNED_INT, GL_FLOAT
depthMax max value for returned GLushort or GLuint values (ignored for GLfloat).
References _mesa_error(), _mesa_half_to_float(), _mesa_problem(), ASSERT, BYTE_TO_FLOATZ, CLAMP, DEPTH_VALUES, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, GLbyte, GLshort, GLubyte, GLushort, INT_TO_FLOAT, NULL, gl_context::Pixel, SHORT_TO_FLOATZ, SWAP2BYTE, SWAP4BYTE, gl_pixelstore_attrib::SwapBytes, UBYTE_TO_FLOAT, UINT_TO_FLOAT, and USHORT_TO_FLOAT.
Referenced by _mesa_texstore_s8_z24(), _mesa_texstore_x8_z24(), _mesa_texstore_z16(), _mesa_texstore_z24_s8(), _mesa_texstore_z24_x8(), _mesa_texstore_z32(), and _mesa_texstore_z32f_x24s8().
void _mesa_unpack_dudv_span_byte (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLbyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
Similar to _mesa_unpack_color_span_float(), but for dudv data instead of rgba, directly return GLbyte data, no transfer ops apply.
References _mesa_components_in_format(), _mesa_error(), ASSERT, extract_float_rgba(), FLOAT_TO_BYTE, GCOMP, GLbyte, RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_texstore_dudv8().
void* _mesa_unpack_image (GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * unpack)
Unpack image data.
Apply byte swapping, byte flipping (bitmap). Return all image data in a contiguous block. This is used when we compile glDrawPixels, glTexImage, etc into a display list. We need a copy of the data in a standard format.
References _mesa_bytes_per_pixel(), _mesa_components_in_format(), _mesa_image_address(), _mesa_swap2(), _mesa_swap4(), _mesa_type_is_packed(), flip_bytes(), GLubyte, GLushort, gl_pixelstore_attrib::LsbFirst, NULL, gl_pixelstore_attrib::SkipPixels, and gl_pixelstore_attrib::SwapBytes.
Referenced by unpack_image().
void _mesa_unpack_index_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_apply_ci_transfer_ops(), _mesa_error(), _mesa_problem(), ASSERT, extract_uint_indexes(), GLubyte, GLushort, IMAGE_MAP_COLOR_BIT, IMAGE_SHIFT_OFFSET_BIT, and gl_pixelstore_attrib::SwapBytes.
void _mesa_unpack_polygon_stipple (const GLubyte * pattern, GLuint dest[32], const struct gl_pixelstore_attrib * unpacking)
References _mesa_unpack_bitmap(), and GLubyte.
Referenced by _mesa_polygon_stipple().
void _mesa_unpack_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_error(), _mesa_problem(), _mesa_shift_and_offset_ci(), ASSERT, extract_uint_indexes(), GLubyte, GLushort, IMAGE_SHIFT_OFFSET_BIT, gl_pixelmap::Map, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, gl_context::PixelMaps, gl_pixelmap::Size, gl_pixelmaps::StoS, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_texstore_s8(), _mesa_texstore_s8_z24(), _mesa_texstore_z24_s8(), and _mesa_texstore_z32f_x24s8().