Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
pack.c File Reference
Image and pixel span packing and unpacking.
#include "glheader.h"
#include "colormac.h"
#include "enums.h"
#include "image.h"
#include "imports.h"
#include "macros.h"
#include "mtypes.h"
#include "pack.h"
#include "pixeltransfer.h"
#include "glformats.h"
#include "../../gallium/auxiliary/util/u_format_rgb9e5.h"
#include "../../gallium/auxiliary/util/u_format_r11g11b10f.h"
#include "pack_tmp.h"
Macros
#define SRC_TYPE GLuint
#define DST_TYPE GLuint
#define SRC_CONVERT(x) (x)
#define FN_NAME pack_uint_from_uint_rgba
#define DST_TYPE GLint
#define SRC_CONVERT(x) MIN2(x, 0x7fffffff)
#define FN_NAME pack_int_from_uint_rgba
#define DST_TYPE GLushort
#define SRC_CONVERT(x) MIN2(x, 0xffff)
#define FN_NAME pack_ushort_from_uint_rgba
#define DST_TYPE GLshort
#define SRC_CONVERT(x) CLAMP((int)x, -32768, 32767)
#define FN_NAME pack_short_from_uint_rgba
#define DST_TYPE GLubyte
#define SRC_CONVERT(x) MIN2(x, 0xff)
#define FN_NAME pack_ubyte_from_uint_rgba
#define DST_TYPE GLbyte
#define SRC_CONVERT(x) CLAMP((int)x, -128, 127)
#define FN_NAME pack_byte_from_uint_rgba
#define SRC_TYPE GLint
#define DST_TYPE GLuint
#define SRC_CONVERT(x) MAX2(x, 0)
#define FN_NAME pack_uint_from_int_rgba
#define DST_TYPE GLushort
#define SRC_CONVERT(x) MAX2(x, 0)
#define FN_NAME pack_ushort_from_int_rgba
#define DST_TYPE GLshort
#define SRC_CONVERT(x) CLAMP(x, -0x8000, 0x7fff)
#define FN_NAME pack_short_from_int_rgba
#define DST_TYPE GLubyte
#define SRC_CONVERT(x) MAX2(x, 0)
#define FN_NAME pack_ubyte_from_int_rgba
#define DST_TYPE GLbyte
#define SRC_CONVERT(x) CLAMP(x, -0x80, 0x7f)
#define FN_NAME pack_byte_from_int_rgba
#define SWAP2BYTE(VALUE)
#define SWAP4BYTE(VALUE)
#define PROCESS(SRC_INDEX, DST_INDEX, DEFAULT_FLT, DEFAULT_INT, TYPE, CONVERSION)
#define PROCESS(SRC_INDEX, DST_INDEX, DEFAULT, TYPE, CONVERSION)
#define DEPTH_VALUES(GLTYPE, GLTYPE2FLOAT)
Functions
static void flip_bytes (GLubyte *p, GLuint n)
Flip the 8 bits in each byte of the given array.
void _mesa_unpack_polygon_stipple (const GLubyte *pattern, GLuint dest[32], const struct gl_pixelstore_attrib *unpacking)
void _mesa_pack_polygon_stipple (const GLuint pattern[32], GLubyte *dest, const struct gl_pixelstore_attrib *packing)
GLvoid * _mesa_unpack_bitmap (GLint width, GLint height, const GLubyte *pixels, const struct gl_pixelstore_attrib *packing)
void _mesa_pack_bitmap (GLint width, GLint height, const GLubyte *source, GLubyte *dest, const struct gl_pixelstore_attrib *packing)
static void get_component_indexes (GLenum format, GLint *redIndex, GLint *greenIndex, GLint *blueIndex, GLint *alphaIndex, GLint *luminanceIndex, GLint *intensityIndex)
Get indexes of color components for a basic color format, such as GL_RGBA, GL_RED, GL_LUMINANCE_ALPHA, etc.
static GLboolean get_type_min_max (GLenum type, GLfloat *min, GLfloat *max)
For small integer types, return the min and max possible values.
static void _pack_rgba_span_from_uints_problem (struct gl_context *ctx, GLenum dstFormat, GLenum dstType)
void _mesa_pack_rgba_span_from_uints (struct gl_context *ctx, GLuint n, GLuint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid *dstAddr)
static void _pack_rgba_span_from_ints_problem (struct gl_context *ctx, GLenum dstFormat, GLenum dstType)
void _mesa_pack_rgba_span_from_ints (struct gl_context *ctx, GLuint n, GLint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid *dstAddr)
void _mesa_pack_rgba_span_float (struct gl_context *ctx, GLuint n, GLfloat rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid *dstAddr, const struct gl_pixelstore_attrib *dstPacking, GLbitfield transferOps)
Used to pack an array [][4] of RGBA float colors as specified by the dstFormat, dstType and dstPacking.
static void extract_uint_indexes (GLuint n, GLuint indexes[], GLenum srcFormat, GLenum srcType, const GLvoid *src, const struct gl_pixelstore_attrib *unpack)
static void get_component_mapping (GLenum format, GLint *rSrc, GLint *gSrc, GLint *bSrc, GLint *aSrc, GLint *rDst, GLint *gDst, GLint *bDst, GLint *aDst)
Return source/dest RGBA indexes for unpacking pixels.
static void extract_float_rgba (GLuint n, GLfloat rgba[][4], GLenum srcFormat, GLenum srcType, const GLvoid *src, GLboolean swapBytes)
static GLuint clamp_float_to_uint (GLfloat f)
static GLuint clamp_half_to_uint (GLhalfARB h)
static void extract_uint_rgba (GLuint n, GLuint rgba[][4], GLenum srcFormat, GLenum srcType, const GLvoid *src, GLboolean swapBytes)
void _mesa_unpack_color_span_ubyte (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLubyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
void _mesa_unpack_color_span_float (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLfloat dest[], GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
Same as _mesa_unpack_color_span_ubyte(), but return GLfloat data instead of GLubyte.
void _mesa_unpack_color_span_uint (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLuint *dest, GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking)
Same as _mesa_unpack_color_span_ubyte(), but return GLuint data instead of GLubyte.
void _mesa_unpack_dudv_span_byte (struct gl_context *ctx, GLuint n, GLenum dstFormat, GLbyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
Similar to _mesa_unpack_color_span_float(), but for dudv data instead of rgba, directly return GLbyte data, no transfer ops apply.
void _mesa_unpack_index_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
void _mesa_pack_index_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, const GLuint *source, const struct gl_pixelstore_attrib *dstPacking, GLbitfield transferOps)
void _mesa_unpack_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
void _mesa_pack_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, const GLubyte *source, const struct gl_pixelstore_attrib *dstPacking)
void _mesa_unpack_depth_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLvoid *dest, GLuint depthMax, GLenum srcType, const GLvoid *source, const struct gl_pixelstore_attrib *srcPacking)
Unpack a row of depth/z values from memory, returning GLushort, GLuint or GLfloat values.
void _mesa_pack_depth_span (struct gl_context *ctx, GLuint n, GLvoid *dest, GLenum dstType, const GLfloat *depthSpan, const struct gl_pixelstore_attrib *dstPacking)
void _mesa_pack_depth_stencil_span (struct gl_context *ctx, GLuint n, GLenum dstType, GLuint *dest, const GLfloat *depthVals, const GLubyte *stencilVals, const struct gl_pixelstore_attrib *dstPacking)
Pack depth and stencil values as GL_DEPTH_STENCIL (GL_UNSIGNED_INT_24_8 etc)
void * _mesa_unpack_image (GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *unpack)
Unpack image data.
void _mesa_rebase_rgba_float (GLuint n, GLfloat rgba[][4], GLenum baseFormat)
If we unpack colors from a luminance surface, we'll get pixel colors such as (l, l, l, a).
void _mesa_rebase_rgba_uint (GLuint n, GLuint rgba[][4], GLenum baseFormat)
As above, but GLuint components.
Detailed Description
Image and pixel span packing and unpacking.
Macro Definition Documentation
#define DEPTH_VALUES (GLTYPE, GLTYPE2FLOAT)
Value:
do {                                                                \
        GLuint i;                                                       \
        const GLTYPE *src = (const GLTYPE *)source;                     \
        for (i = 0; i < n; i++) {                                       \
            GLTYPE value = src[i];                                      \
            if (srcPacking->SwapBytes) {                                \
                if (sizeof(GLTYPE) == 2) {                              \
                    SWAP2BYTE(value);                                   \
                } else if (sizeof(GLTYPE) == 4) {                       \
                    SWAP4BYTE(value);                                   \
                }                                                       \
            }                                                           \
            depthValues[i] = GLTYPE2FLOAT(value);                       \
        }                                                               \
    } while (0)
Referenced by _mesa_unpack_depth_span().
#define DST_TYPE GLuint
#define DST_TYPE GLint
#define DST_TYPE GLushort
#define DST_TYPE GLshort
#define DST_TYPE GLubyte
#define DST_TYPE GLbyte
#define DST_TYPE GLuint
#define DST_TYPE GLushort
#define DST_TYPE GLshort
#define DST_TYPE GLubyte
#define DST_TYPE GLbyte
#define FN_NAME pack_uint_from_uint_rgba
#define FN_NAME pack_int_from_uint_rgba
#define FN_NAME pack_ushort_from_uint_rgba
#define FN_NAME pack_short_from_uint_rgba
#define FN_NAME pack_ubyte_from_uint_rgba
#define FN_NAME pack_byte_from_uint_rgba
#define FN_NAME pack_uint_from_int_rgba
#define FN_NAME pack_ushort_from_int_rgba
#define FN_NAME pack_short_from_int_rgba
#define FN_NAME pack_ubyte_from_int_rgba
#define FN_NAME pack_byte_from_int_rgba
#define PROCESS (SRC_INDEX, DST_INDEX, DEFAULT_FLT, DEFAULT_INT, TYPE, CONVERSION)
Referenced by extract_float_rgba(), and extract_uint_rgba().
#define PROCESS (SRC_INDEX, DST_INDEX, DEFAULT, TYPE, CONVERSION)
Value:
if ((SRC_INDEX) < 0) {                                          \
      GLuint i;                                                         \
      for (i = 0; i < n; i++) {                                         \
         rgba[i][DST_INDEX] = DEFAULT;                                  \
      }                                                                 \
   }                                                                    \
   else if (swapBytes) {                                                \
      const TYPE *s = (const TYPE *) src;                               \
      GLuint i;                                                         \
      for (i = 0; i < n; i++) {                                         \
         TYPE value = s[SRC_INDEX];                                     \
         if (sizeof(TYPE) == 2) {                                       \
            SWAP2BYTE(value);                                           \
         }                                                              \
         else if (sizeof(TYPE) == 4) {                                  \
            SWAP4BYTE(value);                                           \
         }                                                              \
         rgba[i][DST_INDEX] = CONVERSION(value);                        \
         s += stride;                                                   \
      }                                                                 \
   }                                                                    \
   else {                                                               \
      const TYPE *s = (const TYPE *) src;                               \
      GLuint i;                                                         \
      for (i = 0; i < n; i++) {                                         \
         rgba[i][DST_INDEX] = CONVERSION(s[SRC_INDEX]);                 \
         s += stride;                                                   \
      }                                                                 \
   }
#define SRC_CONVERT (x) (x)
Referenced by FN_NAME().
#define SRC_CONVERT (x) MIN2(x, 0x7fffffff)
#define SRC_CONVERT (x) MIN2(x, 0xffff)
#define SRC_CONVERT (x) CLAMP((int)x, -32768, 32767)
#define SRC_CONVERT (x) MIN2(x, 0xff)
#define SRC_CONVERT (x) CLAMP((int)x, -128, 127)
#define SRC_CONVERT (x) MAX2(x, 0)
#define SRC_CONVERT (x) MAX2(x, 0)
#define SRC_CONVERT (x) CLAMP(x, -0x8000, 0x7fff)
#define SRC_CONVERT (x) MAX2(x, 0)
#define SRC_CONVERT (x) CLAMP(x, -0x80, 0x7f)
#define SRC_TYPE GLuint
#define SRC_TYPE GLint
#define SWAP2BYTE (VALUE)
Value:
{                                               \
      GLubyte *bytes = (GLubyte *) &(VALUE);    \
      GLubyte tmp = bytes[0];                   \
      bytes[0] = bytes[1];                      \
      bytes[1] = tmp;                           \
   }
Referenced by _mesa_unpack_depth_span(), extract_float_rgba(), extract_uint_indexes(), and extract_uint_rgba().
#define SWAP4BYTE (VALUE)
Value:
{                                               \
      GLubyte *bytes = (GLubyte *) &(VALUE);    \
      GLubyte tmp = bytes[0];                   \
      bytes[0] = bytes[3];                      \
      bytes[3] = tmp;                           \
      tmp = bytes[1];                           \
      bytes[1] = bytes[2];                      \
      bytes[2] = tmp;                           \
   }
Referenced by _mesa_unpack_depth_span(), extract_float_rgba(), extract_uint_indexes(), and extract_uint_rgba().
Function Documentation
void _mesa_pack_bitmap (GLint width, GLint height, const GLubyte * source, GLubyte * dest, const struct gl_pixelstore_attrib * packing)
References _mesa_image_address2d(), CEILING, flip_bytes(), GLubyte, gl_pixelstore_attrib::LsbFirst, and gl_pixelstore_attrib::SkipPixels.
Referenced by _mesa_pack_polygon_stipple().
void _mesa_pack_depth_span (struct gl_context * ctx, GLuint n, GLvoid * dest, GLenum dstType, const GLfloat * depthSpan, const struct gl_pixelstore_attrib * dstPacking)
References _mesa_error(), _mesa_float_to_half(), _mesa_problem(), _mesa_scale_and_bias_depth(), _mesa_swap2(), _mesa_swap4(), CLAMPED_FLOAT_TO_USHORT, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, FLOAT_TO_BYTE, FLOAT_TO_INT, FLOAT_TO_SHORT, FLOAT_TO_UBYTE, FLOAT_TO_UINT, GLbyte, GLshort, GLubyte, GLushort, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by get_tex_depth(), and read_depth_pixels().
void _mesa_pack_depth_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLuint * dest, const GLfloat * depthVals, const GLubyte * stencilVals, const struct gl_pixelstore_attrib * dstPacking)
Pack depth and stencil values as GL_DEPTH_STENCIL (GL_UNSIGNED_INT_24_8 etc)
References _mesa_apply_stencil_transfer_ops(), _mesa_error(), _mesa_scale_and_bias_depth(), _mesa_swap4(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, GLubyte, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by slow_read_depth_stencil_pixels_separate().
void _mesa_pack_index_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, const GLuint * source, const struct gl_pixelstore_attrib * dstPacking, GLbitfield transferOps)
References _mesa_apply_ci_transfer_ops(), _mesa_error(), _mesa_float_to_half(), _mesa_problem(), _mesa_swap2(), _mesa_swap4(), GLbyte, GLshort, GLubyte, GLushort, IMAGE_MAP_COLOR_BIT, IMAGE_SHIFT_OFFSET_BIT, and gl_pixelstore_attrib::SwapBytes.
void _mesa_pack_polygon_stipple (const GLuint pattern[32], GLubyte * dest, const struct gl_pixelstore_attrib * packing)
References _mesa_pack_bitmap(), and GLubyte.
Referenced by _mesa_GetnPolygonStippleARB().
void _mesa_pack_rgba_span_float (struct gl_context * ctx, GLuint n, GLfloat rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid * dstAddr, const struct gl_pixelstore_attrib * dstPacking, GLbitfield transferOps)
Used to pack an array [][4] of RGBA float colors as specified by the dstFormat, dstType and dstPacking.
Used by glReadPixels. Historically, the RGBA values were in [0,1] and rescaled to fit into GLubytes, etc. But with new integer formats, the RGBA values may have any value and we don't always rescale when converting to integers.
Note: the rgba values will be modified by this function when any pixel transfer ops are enabled.
References _mesa_apply_rgba_transfer_ops(), _mesa_components_in_format(), _mesa_error(), _mesa_float_to_half(), _mesa_is_enum_format_integer(), _mesa_problem(), _mesa_sizeof_packed_type(), _mesa_swap2(), _mesa_swap4(), ACOMP, BCOMP, CLAMP, CLAMPED_FLOAT_TO_USHORT, F, F_TO_I(), FLOAT_TO_BYTE, FLOAT_TO_INT, FLOAT_TO_SHORT, FLOAT_TO_UBYTE, FLOAT_TO_UINT, FLOAT_TO_USHORT, GCOMP, get_type_min_max(), GLbyte, GLshort, GLubyte, GLushort, IMAGE_CLAMP_BIT, NULL, RCOMP, gl_pixelstore_attrib::SwapBytes, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_pack_rgba_span_from_ints (struct gl_context * ctx, GLuint n, GLint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid * dstAddr)
References _pack_rgba_span_from_ints_problem(), ACOMP, BCOMP, CLAMP, GCOMP, GLubyte, GLushort, and RCOMP.
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_pack_rgba_span_from_uints (struct gl_context * ctx, GLuint n, GLuint rgba[][4], GLenum dstFormat, GLenum dstType, GLvoid * dstAddr)
References _pack_rgba_span_from_uints_problem(), ACOMP, BCOMP, GCOMP, GLubyte, GLushort, MIN2, and RCOMP.
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_pack_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, const GLubyte * source, const struct gl_pixelstore_attrib * dstPacking)
References _mesa_apply_stencil_transfer_ops(), _mesa_error(), _mesa_float_to_half(), _mesa_problem(), _mesa_swap2(), _mesa_swap4(), GLbyte, GLshort, GLubyte, GLushort, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixelstore_attrib::LsbFirst, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, and gl_pixelstore_attrib::SwapBytes.
Referenced by read_stencil_pixels().
void _mesa_rebase_rgba_float (GLuint n, GLfloat rgba[][4], GLenum baseFormat)
If we unpack colors from a luminance surface, we'll get pixel colors such as (l, l, l, a).
When we call _mesa_pack_rgba_span_float(format=GL_LUMINANCE), that function will compute L=R+G+B before packing. The net effect is we'll accidentally store luminance values = 3*l. This function compensates for that by converting (aka rebasing) (l,l,l,a) to be (l,0,0,a). It's a similar story for other formats such as LUMINANCE_ALPHA, ALPHA and INTENSITY.
Finally, we also need to do this when the actual surface format does not match the logical surface format. For example, suppose the user requests a GL_LUMINANCE texture but the driver stores it as RGBA. Again, we'll get pixel values like (l,l,l,a).
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
void _mesa_rebase_rgba_uint (GLuint n, GLuint rgba[][4], GLenum baseFormat)
As above, but GLuint components.
References ACOMP, BCOMP, GCOMP, and RCOMP.
Referenced by get_tex_rgba_uncompressed(), and slow_read_rgba_pixels().
GLvoid* _mesa_unpack_bitmap (GLint width, GLint height, const GLubyte * pixels, const struct gl_pixelstore_attrib * packing)
References _mesa_image_address2d(), CEILING, flip_bytes(), GLubyte, gl_pixelstore_attrib::LsbFirst, NULL, and gl_pixelstore_attrib::SkipPixels.
Referenced by _mesa_unpack_polygon_stipple(), and unpack_image().
void _mesa_unpack_color_span_float (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLfloat dest[], GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
Same as _mesa_unpack_color_span_ubyte(), but return GLfloat data instead of GLubyte.
References _mesa_apply_rgba_transfer_ops(), _mesa_components_in_format(), _mesa_error(), _mesa_is_enum_format_integer(), _mesa_map_ci_to_rgba(), _mesa_shift_and_offset_ci(), ACOMP, ASSERT, BCOMP, extract_float_rgba(), extract_uint_indexes(), GCOMP, get_component_indexes(), IMAGE_MAP_COLOR_BIT, IMAGE_SCALE_BIAS_BIT, IMAGE_SHIFT_OFFSET_BIT, RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_make_temp_float_image().
void _mesa_unpack_color_span_ubyte (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLubyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_apply_rgba_transfer_ops(), _mesa_components_in_format(), _mesa_error(), _mesa_is_enum_format_integer(), _mesa_map_ci_to_rgba(), _mesa_shift_and_offset_ci(), ACOMP, ASSERT, BCOMP, CLAMPED_FLOAT_TO_UBYTE, extract_float_rgba(), extract_uint_indexes(), GCOMP, get_component_indexes(), GLubyte, IMAGE_CLAMP_BIT, IMAGE_MAP_COLOR_BIT, IMAGE_SCALE_BIAS_BIT, IMAGE_SHIFT_OFFSET_BIT, RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_make_temp_ubyte_image().
void _mesa_unpack_color_span_uint (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLuint * dest, GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking)
Same as _mesa_unpack_color_span_ubyte(), but return GLuint data instead of GLubyte.
No pixel transfer ops are applied.
References _mesa_components_in_format(), _mesa_error(), ACOMP, ASSERT, BCOMP, extract_uint_rgba(), GCOMP, get_component_indexes(), RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by make_temp_uint_image().
void _mesa_unpack_depth_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLuint depthMax, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking)
Unpack a row of depth/z values from memory, returning GLushort, GLuint or GLfloat values.
The glPixelTransfer (scale/bias) params will be applied.
Parameters
dstType one of GL_UNSIGNED_SHORT, GL_UNSIGNED_INT, GL_FLOAT
depthMax max value for returned GLushort or GLuint values (ignored for GLfloat).
References _mesa_error(), _mesa_half_to_float(), _mesa_problem(), ASSERT, BYTE_TO_FLOATZ, CLAMP, DEPTH_VALUES, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, GLbyte, GLshort, GLubyte, GLushort, INT_TO_FLOAT, NULL, gl_context::Pixel, SHORT_TO_FLOATZ, SWAP2BYTE, SWAP4BYTE, gl_pixelstore_attrib::SwapBytes, UBYTE_TO_FLOAT, UINT_TO_FLOAT, and USHORT_TO_FLOAT.
Referenced by _mesa_texstore_s8_z24(), _mesa_texstore_x8_z24(), _mesa_texstore_z16(), _mesa_texstore_z24_s8(), _mesa_texstore_z24_x8(), _mesa_texstore_z32(), and _mesa_texstore_z32f_x24s8().
void _mesa_unpack_dudv_span_byte (struct gl_context * ctx, GLuint n, GLenum dstFormat, GLbyte dest[], GLenum srcFormat, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
Similar to _mesa_unpack_color_span_float(), but for dudv data instead of rgba, directly return GLbyte data, no transfer ops apply.
References _mesa_components_in_format(), _mesa_error(), ASSERT, extract_float_rgba(), FLOAT_TO_BYTE, GCOMP, GLbyte, RCOMP, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_texstore_dudv8().
void* _mesa_unpack_image (GLuint dimensions, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * unpack)
Unpack image data.
Apply byte swapping, byte flipping (bitmap). Return all image data in a contiguous block. This is used when we compile glDrawPixels, glTexImage, etc into a display list. We need a copy of the data in a standard format.
References _mesa_bytes_per_pixel(), _mesa_components_in_format(), _mesa_image_address(), _mesa_swap2(), _mesa_swap4(), _mesa_type_is_packed(), flip_bytes(), GLubyte, GLushort, gl_pixelstore_attrib::LsbFirst, NULL, gl_pixelstore_attrib::SkipPixels, and gl_pixelstore_attrib::SwapBytes.
Referenced by unpack_image().
void _mesa_unpack_index_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_apply_ci_transfer_ops(), _mesa_error(), _mesa_problem(), ASSERT, extract_uint_indexes(), GLubyte, GLushort, IMAGE_MAP_COLOR_BIT, IMAGE_SHIFT_OFFSET_BIT, and gl_pixelstore_attrib::SwapBytes.
void _mesa_unpack_polygon_stipple (const GLubyte * pattern, GLuint dest[32], const struct gl_pixelstore_attrib * unpacking)
References _mesa_unpack_bitmap(), and GLubyte.
Referenced by _mesa_polygon_stipple().
void _mesa_unpack_stencil_span (struct gl_context * ctx, GLuint n, GLenum dstType, GLvoid * dest, GLenum srcType, const GLvoid * source, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
References _mesa_error(), _mesa_problem(), _mesa_shift_and_offset_ci(), ASSERT, extract_uint_indexes(), GLubyte, GLushort, IMAGE_SHIFT_OFFSET_BIT, gl_pixelmap::Map, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, gl_context::PixelMaps, gl_pixelmap::Size, gl_pixelmaps::StoS, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_texstore_s8(), _mesa_texstore_s8_z24(), _mesa_texstore_z24_s8(), and _mesa_texstore_z32f_x24s8().
static void _pack_rgba_span_from_ints_problem (struct gl_context * ctx, GLenum dstFormat, GLenum dstType) static
References _mesa_lookup_enum_by_nr(), and _mesa_problem().
Referenced by _mesa_pack_rgba_span_from_ints().
static void _pack_rgba_span_from_uints_problem (struct gl_context * ctx, GLenum dstFormat, GLenum dstType) static
References _mesa_lookup_enum_by_nr(), and _mesa_problem().
Referenced by _mesa_pack_rgba_span_from_uints().
static GLuint clamp_float_to_uint (GLfloat f) inline static
References F_TO_I().
Referenced by extract_uint_rgba().
static GLuint clamp_half_to_uint (GLhalfARB h) inline static
References _mesa_half_to_float(), and F_TO_I().
Referenced by extract_uint_rgba().
static void extract_float_rgba (GLuint n, GLfloat rgba[][4], GLenum srcFormat, GLenum srcType, const GLvoid * src, GLboolean swapBytes) static
References _mesa_components_in_format(), _mesa_half_to_float(), _mesa_is_enum_format_integer(), _mesa_problem(), ACOMP, ASSERT, BCOMP, BYTE_TO_FLOATZ, F, GCOMP, get_component_mapping(), GLbyte, GLshort, GLubyte, GLushort, INT_TO_FLOAT, NULL, PROCESS, RCOMP, SHORT_TO_FLOATZ, SWAP2BYTE, SWAP4BYTE, UBYTE_TO_FLOAT, UINT_TO_FLOAT, and USHORT_TO_FLOAT.
Referenced by _mesa_unpack_color_span_float(), _mesa_unpack_color_span_ubyte(), and _mesa_unpack_dudv_span_byte().
static void extract_uint_indexes (GLuint n, GLuint indexes[], GLenum srcFormat, GLenum srcType, const GLvoid * src, const struct gl_pixelstore_attrib * unpack) static
References _mesa_half_to_float(), _mesa_problem(), ASSERT, GLbyte, GLshort, GLubyte, GLushort, gl_pixelstore_attrib::LsbFirst, NULL, gl_pixelstore_attrib::SkipPixels, SWAP2BYTE, SWAP4BYTE, and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_unpack_color_span_float(), _mesa_unpack_color_span_ubyte(), _mesa_unpack_index_span(), and _mesa_unpack_stencil_span().
static void extract_uint_rgba (GLuint n, GLuint rgba[][4], GLenum srcFormat, GLenum srcType, const GLvoid * src, GLboolean swapBytes) static
See Also
extract_float_rgba()
References _mesa_components_in_format(), _mesa_problem(), ACOMP, ASSERT, BCOMP, clamp_float_to_uint(), clamp_half_to_uint(), GCOMP, get_component_mapping(), GLbyte, GLshort, GLubyte, GLushort, NULL, PROCESS, RCOMP, SWAP2BYTE, and SWAP4BYTE.
Referenced by _mesa_unpack_color_span_uint().
static void flip_bytes (GLubyte * p, GLuint n) static
Flip the 8 bits in each byte of the given array.
Parameters
p array.
n number of bytes.
Todo:
try this trick to flip bytes someday:
v = ((v & 0x55555555) << 1) | ((v >> 1) & 0x55555555);
v = ((v & 0x33333333) << 2) | ((v >> 2) & 0x33333333);
v = ((v & 0x0f0f0f0f) << 4) | ((v >> 4) & 0x0f0f0f0f);
References GLubyte.
Referenced by _mesa_pack_bitmap(), _mesa_unpack_bitmap(), and _mesa_unpack_image().
static void get_component_indexes (GLenum format, GLint * redIndex, GLint * greenIndex, GLint * blueIndex, GLint * alphaIndex, GLint * luminanceIndex, GLint * intensityIndex) static
Get indexes of color components for a basic color format, such as GL_RGBA, GL_RED, GL_LUMINANCE_ALPHA, etc.
Return -1 for indexes that do not apply.
Referenced by _mesa_unpack_color_span_float(), _mesa_unpack_color_span_ubyte(), and _mesa_unpack_color_span_uint().
static void get_component_mapping (GLenum format, GLint * rSrc, GLint * gSrc, GLint * bSrc, GLint * aSrc, GLint * rDst, GLint * gDst, GLint * bDst, GLint * aDst) static
Return source/dest RGBA indexes for unpacking pixels.
References _mesa_lookup_enum_by_nr(), _mesa_problem(), and NULL.
Referenced by extract_float_rgba(), and extract_uint_rgba().
static GLboolean get_type_min_max (GLenum type, GLfloat * min, GLfloat * max) static
For small integer types, return the min and max possible values.
Used for clamping floats to unscaled integer types.
Returns
GL_TRUE if type is handled, GL_FALSE otherwise.
Referenced by _mesa_pack_rgba_span_float().