Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
pixel.c File Reference
Pixel transfer functions (glPixelZoom, glPixelMap, glPixelTransfer)
#include "glheader.h"
#include "bufferobj.h"
#include "colormac.h"
#include "context.h"
#include "macros.h"
#include "pixel.h"
#include "pbo.h"
#include "mtypes.h"
#include "main/dispatch.h"
Functions
void GLAPIENTRY _mesa_PixelZoom (GLfloat xfactor, GLfloat yfactor)
static struct gl_pixelmap * get_pixelmap (struct gl_context *ctx, GLenum map)
Return pointer to a pixelmap by name.
static void store_pixelmap (struct gl_context *ctx, GLenum map, GLsizei mapsize, const GLfloat *values)
Helper routine used by the other _mesa_PixelMap() functions.
static GLboolean validate_pbo_access (struct gl_context *ctx, struct gl_pixelstore_attrib *pack, GLsizei mapsize, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid *ptr)
Convenience wrapper for _mesa_validate_pbo_access() for gl[Get]PixelMap().
void GLAPIENTRY _mesa_PixelMapfv (GLenum map, GLsizei mapsize, const GLfloat *values)
void GLAPIENTRY _mesa_PixelMapuiv (GLenum map, GLsizei mapsize, const GLuint *values)
void GLAPIENTRY _mesa_PixelMapusv (GLenum map, GLsizei mapsize, const GLushort *values)
void GLAPIENTRY _mesa_GetnPixelMapfvARB (GLenum map, GLsizei bufSize, GLfloat *values)
void GLAPIENTRY _mesa_GetPixelMapfv (GLenum map, GLfloat *values)
void GLAPIENTRY _mesa_GetnPixelMapuivARB (GLenum map, GLsizei bufSize, GLuint *values)
void GLAPIENTRY _mesa_GetPixelMapuiv (GLenum map, GLuint *values)
void GLAPIENTRY _mesa_GetnPixelMapusvARB (GLenum map, GLsizei bufSize, GLushort *values)
void GLAPIENTRY _mesa_GetPixelMapusv (GLenum map, GLushort *values)
void GLAPIENTRY _mesa_PixelTransferf (GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_PixelTransferi (GLenum pname, GLint param)
static void update_image_transfer_state (struct gl_context *ctx)
void _mesa_update_pixel (struct gl_context *ctx, GLuint new_state)
Update mesa pixel transfer derived state.
static void init_pixelmap (struct gl_pixelmap *map)
void _mesa_init_pixel (struct gl_context *ctx)
Initialize the context's PIXEL attribute group.
Detailed Description
Pixel transfer functions (glPixelZoom, glPixelMap, glPixelTransfer)
Function Documentation
void GLAPIENTRY _mesa_GetnPixelMapfvARB (GLenum map, GLsizei bufSize, GLfloat * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), get_pixelmap(), gl_pixelmap::Map, gl_pixelmap::Size, and validate_pbo_access().
Referenced by _mesa_GetPixelMapfv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnPixelMapuivARB (GLenum map, GLsizei bufSize, GLuint * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), FLOAT_TO_UINT, get_pixelmap(), gl_pixelmap::Map, gl_pixelmap::Size, and validate_pbo_access().
Referenced by _mesa_GetPixelMapuiv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnPixelMapusvARB (GLenum map, GLsizei bufSize, GLushort * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), CLAMP, CLAMPED_FLOAT_TO_USHORT, get_pixelmap(), GLushort, gl_pixelmap::Map, gl_pixelmap::Size, and validate_pbo_access().
Referenced by _mesa_GetPixelMapusv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetPixelMapfv (GLenum map, GLfloat * values)
References _mesa_GetnPixelMapfvARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetPixelMapuiv (GLenum map, GLuint * values)
References _mesa_GetnPixelMapuivARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetPixelMapusv (GLenum map, GLushort * values)
References _mesa_GetnPixelMapusvARB().
Referenced by _mesa_initialize_exec_table().
void _mesa_init_pixel (struct gl_context * ctx)
Initialize the context's PIXEL attribute group.
References gl_context::_ImageTransferState, gl_pixel_attrib::AlphaBias, gl_pixel_attrib::AlphaScale, gl_pixelmaps::AtoA, gl_pixel_attrib::BlueBias, gl_pixel_attrib::BlueScale, gl_pixelmaps::BtoB, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_config::doubleBufferMode, gl_pixel_attrib::GreenBias, gl_pixel_attrib::GreenScale, gl_pixelmaps::GtoG, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, init_pixelmap(), gl_pixelmaps::ItoA, gl_pixelmaps::ItoB, gl_pixelmaps::ItoG, gl_pixelmaps::ItoI, gl_pixelmaps::ItoR, gl_pixel_attrib::MapColorFlag, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, gl_context::PixelMaps, gl_pixel_attrib::ReadBuffer, gl_pixel_attrib::RedBias, gl_pixel_attrib::RedScale, gl_pixelmaps::RtoR, gl_pixelmaps::StoS, gl_context::Visual, gl_pixel_attrib::ZoomX, and gl_pixel_attrib::ZoomY.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_PixelMapfv (GLenum map, GLsizei mapsize, const GLfloat * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_pow_two(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _NEW_PIXEL, FLUSH_VERTICES, MAX_PIXEL_MAP_TABLE, store_pixelmap(), and validate_pbo_access().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PixelMapuiv (GLenum map, GLsizei mapsize, const GLuint * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_pow_two(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _NEW_PIXEL, FLUSH_VERTICES, MAX_PIXEL_MAP_TABLE, store_pixelmap(), UINT_TO_FLOAT, and validate_pbo_access().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PixelMapusv (GLenum map, GLsizei mapsize, const GLushort * values)
References _mesa_error(), _mesa_is_bufferobj(), _mesa_is_pow_two(), _mesa_map_pbo_source(), _mesa_unmap_pbo_source(), _NEW_PIXEL, FLUSH_VERTICES, GLushort, MAX_PIXEL_MAP_TABLE, store_pixelmap(), USHORT_TO_FLOAT, and validate_pbo_access().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PixelTransferf (GLenum pname, GLfloat param)
References _mesa_error(), _NEW_PIXEL, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table(), and _mesa_PixelTransferi().
void GLAPIENTRY _mesa_PixelTransferi (GLenum pname, GLint param)
References _mesa_PixelTransferf().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PixelZoom (GLfloat xfactor, GLfloat yfactor)
References _NEW_PIXEL, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void _mesa_update_pixel (struct gl_context * ctx, GLuint new_state)
Update mesa pixel transfer derived state.
References _NEW_PIXEL, and update_image_transfer_state().
Referenced by _mesa_update_state_locked().
static struct gl_pixelmap* get_pixelmap (struct gl_context * ctx, GLenum map) static read
Return pointer to a pixelmap by name.
References gl_pixelmaps::AtoA, gl_pixelmaps::BtoB, gl_pixelmaps::GtoG, gl_pixelmaps::ItoA, gl_pixelmaps::ItoB, gl_pixelmaps::ItoG, gl_pixelmaps::ItoI, gl_pixelmaps::ItoR, NULL, gl_context::PixelMaps, gl_pixelmaps::RtoR, and gl_pixelmaps::StoS.
Referenced by _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), and store_pixelmap().
static void init_pixelmap (struct gl_pixelmap * map) static
References gl_pixelmap::Map, and gl_pixelmap::Size.
Referenced by _mesa_init_pixel().
static void store_pixelmap (struct gl_context * ctx, GLenum map, GLsizei mapsize, const GLfloat * values) static
Helper routine used by the other _mesa_PixelMap() functions.
References _mesa_error(), CLAMP, F, get_pixelmap(), IROUND(), gl_pixelmaps::ItoI, gl_pixelmap::Map, gl_context::PixelMaps, gl_pixelmap::Size, and gl_pixelmaps::StoS.
Referenced by _mesa_PixelMapfv(), _mesa_PixelMapuiv(), and _mesa_PixelMapusv().
static void update_image_transfer_state (struct gl_context * ctx) static
References gl_context::_ImageTransferState, gl_pixel_attrib::AlphaBias, gl_pixel_attrib::AlphaScale, gl_pixel_attrib::BlueBias, gl_pixel_attrib::BlueScale, gl_pixel_attrib::GreenBias, gl_pixel_attrib::GreenScale, IMAGE_MAP_COLOR_BIT, IMAGE_SCALE_BIAS_BIT, IMAGE_SHIFT_OFFSET_BIT, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapColorFlag, gl_context::Pixel, gl_pixel_attrib::RedBias, and gl_pixel_attrib::RedScale.
Referenced by _mesa_update_pixel().
static GLboolean validate_pbo_access (struct gl_context * ctx, struct gl_pixelstore_attrib * pack, GLsizei mapsize, GLenum format, GLenum type, GLsizei clientMemSize, const GLvoid * ptr) static
Convenience wrapper for _mesa_validate_pbo_access() for gl[Get]PixelMap().
References _mesa_error(), _mesa_is_bufferobj(), _mesa_reference_buffer_object(), _mesa_validate_pbo_access(), gl_pixelstore_attrib::BufferObj, gl_context::DefaultPacking, gl_shared_state::NullBufferObj, and gl_context::Shared.
Referenced by _mesa_GetnPixelMapfvARB(), _mesa_GetnPixelMapuivARB(), _mesa_GetnPixelMapusvARB(), _mesa_PixelMapfv(), _mesa_PixelMapuiv(), and _mesa_PixelMapusv().