Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
pixelstore.h File Reference
glPixelStore functions.
#include "glheader.h"
Functions
void GLAPIENTRY _mesa_PixelStorei (GLenum pname, GLint param)
void GLAPIENTRY _mesa_PixelStoref (GLenum pname, GLfloat param)
void _mesa_init_pixelstore (struct gl_context *ctx)
Initialize the context's pixel store state.
Detailed Description
glPixelStore functions.
Function Documentation
void _mesa_init_pixelstore (struct gl_context * ctx)
Initialize the context's pixel store state.
References _mesa_reference_buffer_object(), gl_pixelstore_attrib::Alignment, gl_pixelstore_attrib::BufferObj, gl_context::DefaultPacking, gl_pixelstore_attrib::ImageHeight, gl_pixelstore_attrib::Invert, gl_pixelstore_attrib::LsbFirst, gl_shared_state::NullBufferObj, gl_context::Pack, gl_pixelstore_attrib::RowLength, gl_context::Shared, gl_pixelstore_attrib::SkipImages, gl_pixelstore_attrib::SkipPixels, gl_pixelstore_attrib::SkipRows, gl_pixelstore_attrib::SwapBytes, and gl_context::Unpack.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_PixelStoref (GLenum pname, GLfloat param)
References _mesa_PixelStorei(), and IROUND().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PixelStorei (GLenum pname, GLint param)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), and API_OPENGLES.
Referenced by _mesa_cpal_compressed_teximage2d(), _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), _mesa_dump_stencil_buffer(), _mesa_initialize_exec_table(), and _mesa_PixelStoref().