Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
querymatrix.h File Reference
#include "mtypes.h"
Functions
GLbitfield GLAPIENTRY _mesa_QueryMatrixxOES (GLfixed mantissa[16], GLint exponent[16])
Function Documentation
GLbitfield GLAPIENTRY _mesa_QueryMatrixxOES (GLfixed mantissa[16], GLint exponent[16])
References _mesa_GetFloatv(), _mesa_GetIntegerv(), FLOAT_TO_FIXED, FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, FP_ZERO, fpclassify, GLbitfield, and INT_TO_FIXED.
Referenced by _mesa_initialize_exec_table().