Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
queryobj.c File Reference
#include "glheader.h"
#include "context.h"
#include "enums.h"
#include "hash.h"
#include "imports.h"
#include "queryobj.h"
#include "mtypes.h"
#include "main/dispatch.h"
Functions
static struct gl_query_object * _mesa_new_query_object (struct gl_context *ctx, GLuint id)
Allocate a new query object.
static void _mesa_begin_query (struct gl_context *ctx, struct gl_query_object *q)
Begin a query.
static void _mesa_end_query (struct gl_context *ctx, struct gl_query_object *q)
End a query.
static void _mesa_wait_query (struct gl_context *ctx, struct gl_query_object *q)
Wait for query to complete.
static void _mesa_check_query (struct gl_context *ctx, struct gl_query_object *q)
Check if a query results are ready.
static void _mesa_delete_query (struct gl_context *ctx, struct gl_query_object *q)
Delete a query object.
void _mesa_init_query_object_functions (struct dd_function_table *driver)
static struct gl_query_object ** get_query_binding_point (struct gl_context *ctx, GLenum target)
Return pointer to the query object binding point for the given target.
void GLAPIENTRY _mesa_GenQueries (GLsizei n, GLuint *ids)
void GLAPIENTRY _mesa_DeleteQueries (GLsizei n, const GLuint *ids)
GLboolean GLAPIENTRY _mesa_IsQuery (GLuint id)
static GLboolean query_error_check_index (struct gl_context *ctx, GLenum target, GLuint index)
void GLAPIENTRY _mesa_BeginQueryIndexed (GLenum target, GLuint index, GLuint id)
void GLAPIENTRY _mesa_EndQueryIndexed (GLenum target, GLuint index)
void GLAPIENTRY _mesa_BeginQuery (GLenum target, GLuint id)
void GLAPIENTRY _mesa_EndQuery (GLenum target)
void GLAPIENTRY _mesa_QueryCounter (GLuint id, GLenum target)
void GLAPIENTRY _mesa_GetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryiv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryObjectiv (GLuint id, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint *params)
void GLAPIENTRY _mesa_GetQueryObjecti64v (GLuint id, GLenum pname, GLint64EXT *params)
New with GL_EXT_timer_query.
void GLAPIENTRY _mesa_GetQueryObjectui64v (GLuint id, GLenum pname, GLuint64EXT *params)
New with GL_EXT_timer_query.
void _mesa_init_queryobj (struct gl_context *ctx)
Allocate/init the context state related to query objects.
static void delete_queryobj_cb (GLuint id, void *data, void *userData)
Callback for deleting a query object.
void _mesa_free_queryobj_data (struct gl_context *ctx)
Free the context state related to query objects.
Function Documentation
static void _mesa_begin_query (struct gl_context * ctx, struct gl_query_object * q) static
Begin a query.
Software driver fallback. Called via ctx->Driver.BeginQuery().
References _NEW_DEPTH, and gl_context::NewState.
Referenced by _mesa_init_query_object_functions().
void GLAPIENTRY _mesa_BeginQuery (GLenum target, GLuint id)
References _mesa_BeginQueryIndexed().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BeginQueryIndexed (GLenum target, GLuint index, GLuint id)
References _mesa_debug(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_enum_by_nr(), _mesa_lookup_query_object(), gl_query_object::Active, API_OPENGL_COMPAT, gl_query_object::EverBound, FLUSH_VERTICES, get_query_binding_point(), MESA_VERBOSE, query_error_check_index(), gl_query_object::Ready, gl_query_object::Result, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_BeginQuery(), and _mesa_initialize_exec_table().
static void _mesa_check_query (struct gl_context * ctx, struct gl_query_object * q) static
Check if a query results are ready.
Software driver fallback. Called via ctx->Driver.CheckQuery().
Referenced by _mesa_init_query_object_functions().
static void _mesa_delete_query (struct gl_context * ctx, struct gl_query_object * q) static
Delete a query object.
Called via ctx->Driver.DeleteQuery(). Not removed from hash table here.
Referenced by _mesa_init_query_object_functions().
void GLAPIENTRY _mesa_DeleteQueries (GLsizei n, const GLuint * ids)
References _mesa_debug(), _mesa_error(), _mesa_HashRemove(), _mesa_lookup_query_object(), gl_query_object::Active, ASSERT, FLUSH_VERTICES, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
static void _mesa_end_query (struct gl_context * ctx, struct gl_query_object * q) static
End a query.
Software driver fallback. Called via ctx->Driver.EndQuery().
References _NEW_DEPTH, gl_context::NewState, and gl_query_object::Ready.
Referenced by _mesa_init_query_object_functions().
void GLAPIENTRY _mesa_EndQuery (GLenum target)
References _mesa_EndQueryIndexed().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_EndQueryIndexed (GLenum target, GLuint index)
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), gl_query_object::Active, FLUSH_VERTICES, get_query_binding_point(), MESA_VERBOSE, NULL, query_error_check_index(), gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_EndQuery(), and _mesa_initialize_exec_table().
void _mesa_free_queryobj_data (struct gl_context * ctx)
Free the context state related to query objects.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), delete_queryobj_cb(), gl_context::Query, and gl_query_state::QueryObjects.
Referenced by _mesa_free_context_data().
void GLAPIENTRY _mesa_GenQueries (GLsizei n, GLuint * ids)
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint * params)
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_problem(), get_query_binding_point(), gl_query_object::Id, MESA_VERBOSE, NULL, query_error_check_index(), gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_GetQueryiv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetQueryiv (GLenum target, GLenum pname, GLint * params)
References _mesa_GetQueryIndexediv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetQueryObjecti64v (GLuint id, GLenum pname, GLint64EXT * params)
New with GL_EXT_timer_query.
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_query_object(), gl_query_object::Active, MESA_VERBOSE, NULL, gl_query_object::Ready, gl_query_object::Result, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetQueryObjectiv (GLuint id, GLenum pname, GLint * params)
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_query_object(), gl_query_object::Active, MESA_VERBOSE, NULL, gl_query_object::Ready, gl_query_object::Result, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetQueryObjectui64v (GLuint id, GLenum pname, GLuint64EXT * params)
New with GL_EXT_timer_query.
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_query_object(), gl_query_object::Active, MESA_VERBOSE, NULL, gl_query_object::Ready, gl_query_object::Result, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetQueryObjectuiv (GLuint id, GLenum pname, GLuint * params)
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_query_object(), gl_query_object::Active, MESA_VERBOSE, NULL, gl_query_object::Ready, gl_query_object::Result, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void _mesa_init_query_object_functions (struct dd_function_table * driver)
References _mesa_begin_query(), _mesa_check_query(), _mesa_delete_query(), _mesa_end_query(), _mesa_new_query_object(), _mesa_wait_query(), dd_function_table::BeginQuery, dd_function_table::CheckQuery, dd_function_table::DeleteQuery, dd_function_table::EndQuery, dd_function_table::NewQueryObject, and dd_function_table::WaitQuery.
void _mesa_init_queryobj (struct gl_context * ctx)
Allocate/init the context state related to query objects.
References _mesa_NewHashTable(), gl_context::Const, gl_query_state::CurrentOcclusionObject, NULL, gl_constants::PrimitivesGenerated, gl_constants::PrimitivesWritten, gl_context::Query, gl_constants::QueryCounterBits, gl_query_state::QueryObjects, gl_constants::SamplesPassed, gl_constants::TimeElapsed, and gl_constants::Timestamp.
Referenced by init_attrib_groups().
GLboolean GLAPIENTRY _mesa_IsQuery (GLuint id)
References _mesa_debug(), _mesa_lookup_query_object(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_query_object::EverBound, MESA_VERBOSE, NULL, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
static struct gl_query_object* _mesa_new_query_object (struct gl_context * ctx, GLuint id) static read
Allocate a new query object.
This is a fallback routine called via ctx->Driver.NewQueryObject().
Parameters
ctx - rendering context
id - the new object's ID
Returns
pointer to new query_object object or NULL if out of memory.
References gl_query_object::Active, gl_query_object::EverBound, gl_query_object::Id, MALLOC_STRUCT, gl_query_object::Ready, gl_query_object::Result, and void().
Referenced by _mesa_init_query_object_functions().
void GLAPIENTRY _mesa_QueryCounter (GLuint id, GLenum target)
References _mesa_debug(), _mesa_error(), _mesa_HashInsert(), _mesa_lookup_enum_by_nr(), _mesa_lookup_query_object(), gl_query_object::Active, MESA_VERBOSE, gl_query_object::Ready, gl_query_object::Result, gl_query_object::Target, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
static void _mesa_wait_query (struct gl_context * ctx, struct gl_query_object * q) static
Wait for query to complete.
Software driver fallback. Called via ctx->Driver.WaitQuery().
References gl_query_object::Ready.
Referenced by _mesa_init_query_object_functions().
static void delete_queryobj_cb (GLuint id, void * data, void * userData) static
Callback for deleting a query object.
Called by _mesa_HashDeleteAll().
References dd_function_table::DeleteQuery, and gl_context::Driver.
Referenced by _mesa_free_queryobj_data().
static struct gl_query_object** get_query_binding_point (struct gl_context * ctx, GLenum target) static read
Return pointer to the query object binding point for the given target.
Returns
NULL if invalid target, else the address of binding point
References gl_context::API, API_OPENGLES2, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_query_state::CurrentOcclusionObject, gl_query_state::CurrentTimerObject, gl_extensions::EXT_timer_query, gl_extensions::EXT_transform_feedback, gl_context::Extensions, NULL, gl_query_state::PrimitivesGenerated, gl_query_state::PrimitivesWritten, gl_context::Query, and gl_context::Version.
Referenced by _mesa_BeginQueryIndexed(), _mesa_EndQueryIndexed(), and _mesa_GetQueryIndexediv().
static GLboolean query_error_check_index (struct gl_context * ctx, GLenum target, GLuint index) static
References _mesa_error(), gl_context::Const, and gl_constants::MaxVertexStreams.
Referenced by _mesa_BeginQueryIndexed(), _mesa_EndQueryIndexed(), and _mesa_GetQueryIndexediv().