Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
readpix.c File Reference
#include "glheader.h"
#include "imports.h"
#include "blend.h"
#include "bufferobj.h"
#include "context.h"
#include "enums.h"
#include "readpix.h"
#include "framebuffer.h"
#include "formats.h"
#include "format_unpack.h"
#include "image.h"
#include "mtypes.h"
#include "pack.h"
#include "pbo.h"
#include "state.h"
#include "glformats.h"
#include "fbobject.h"
Functions
static GLboolean need_rgb_to_luminance_conversion (gl_format texFormat, GLenum format)
Return true if the conversion L=R+G+B is needed.
static GLbitfield get_readpixels_transfer_ops (const struct gl_context *ctx, gl_format texFormat, GLenum format, GLenum type, GLboolean uses_blit)
Return transfer op flags for this ReadPixels operation.
GLboolean _mesa_readpixels_needs_slow_path (const struct gl_context *ctx, GLenum format, GLenum type, GLboolean uses_blit)
Return true if memcpy cannot be used for ReadPixels.
static GLboolean readpixels_can_use_memcpy (const struct gl_context *ctx, GLenum format, GLenum type, const struct gl_pixelstore_attrib *packing)
static GLboolean readpixels_memcpy (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
static GLboolean read_uint_depth_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Optimized path for conversion of depth values to GL_DEPTH_COMPONENT, GL_UNSIGNED_INT.
static void read_depth_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Read pixels for format=GL_DEPTH_COMPONENT.
static void read_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Read pixels for format=GL_STENCIL_INDEX.
static GLboolean read_rgba_pixels_swizzle (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Try to do glReadPixels of RGBA data using swizzle.
static void slow_read_rgba_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing, GLbitfield transferOps)
static void read_rgba_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
static GLboolean fast_read_depth_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLubyte *dst, int dstStride)
For a packed depth/stencil buffer being read as depth/stencil, just memcpy the data (possibly swapping 8/24 vs 24/8 as we go).
static GLboolean fast_read_depth_stencil_pixels_separate (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, uint32_t *dst, int dstStride)
For non-float-depth and stencil buffers being read as 24/8 depth/stencil, copy the integer data directly instead of converting depth to float and re-packing.
static void slow_read_depth_stencil_pixels_separate (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib *packing, GLubyte *dst, int dstStride)
static void read_depth_stencil_pixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Read combined depth/stencil values.
void _mesa_readpixels (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *packing, GLvoid *pixels)
Software fallback routine for ctx->Driver.ReadPixels().
static GLenum read_pixels_es3_error_check (GLenum format, GLenum type, const struct gl_renderbuffer *rb)
void GLAPIENTRY _mesa_ReadnPixelsARB (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
void GLAPIENTRY _mesa_ReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
Function Documentation
void GLAPIENTRY _mesa_ReadnPixelsARB (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
References _mesa_bufferobj_mapped(), _mesa_debug(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_es_error_check_format_and_type(), _mesa_get_color_read_format(), _mesa_get_color_read_type(), _mesa_get_read_renderbuffer_for_format(), _mesa_is_bufferobj(), _mesa_is_color_format(), _mesa_is_enum_format_integer(), _mesa_is_format_integer_color(), _mesa_is_gles(), _mesa_is_user_fbo(), _mesa_lookup_enum_by_nr(), _mesa_source_buffer_exists(), _mesa_update_state(), _mesa_validate_pbo_access(), API_OPENGLES2, FLUSH_CURRENT, FLUSH_VERTICES, gl_renderbuffer::Format, GL_HALF_FLOAT_OES, MESA_VERBOSE, NULL, read_pixels_es3_error_check(), and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_ReadPixels().
void _mesa_readpixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib * packing, GLvoid * pixels)
Software fallback routine for ctx->Driver.ReadPixels().
By time we get here, all error checking will have been done.
References _mesa_clip_readpixels(), _mesa_map_pbo_dest(), _mesa_unmap_pbo_dest(), _mesa_update_state(), gl_context::NewState, read_depth_pixels(), read_depth_stencil_pixels(), read_rgba_pixels(), read_stencil_pixels(), and readpixels_memcpy().
void GLAPIENTRY _mesa_ReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
References _mesa_ReadnPixelsARB().
Referenced by _mesa_dump_color_buffer(), _mesa_dump_depth_buffer(), _mesa_dump_stencil_buffer(), and _mesa_initialize_exec_table().
GLboolean _mesa_readpixels_needs_slow_path (const struct gl_context * ctx, GLenum format, GLenum type, GLboolean uses_blit)
Return true if memcpy cannot be used for ReadPixels.
If uses_blit is true, the function returns true if a simple 3D engine blit cannot be used for ReadPixels packing.
NOTE: This doesn't take swizzling and format conversions between the readbuffer and the pixel pack buffer into account.
References _mesa_get_format_datatype(), _mesa_get_read_renderbuffer_for_format(), _mesa_has_depthstencil_combined(), ASSERT, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_renderbuffer::Format, get_readpixels_transfer_ops(), gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, need_rgb_to_luminance_conversion(), gl_context::Pixel, and gl_context::ReadBuffer.
Referenced by readpixels_can_use_memcpy().
static GLboolean fast_read_depth_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLubyte * dst, int dstStride) static
For a packed depth/stencil buffer being read as depth/stencil, just memcpy the data (possibly swapping 8/24 vs 24/8 as we go).
References _mesa_error(), _mesa_unpack_uint_24_8_depth_stencil_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, MESA_FORMAT_S8_Z24, MESA_FORMAT_Z24_S8, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_stencil_pixels().
static GLboolean fast_read_depth_stencil_pixels_separate (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, uint32_t * dst, int dstStride) static
For non-float-depth and stencil buffers being read as 24/8 depth/stencil, copy the integer data directly instead of converting depth to float and re-packing.
References _mesa_error(), _mesa_get_format_datatype(), _mesa_unpack_ubyte_stencil_row(), _mesa_unpack_uint_z_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_stencil_pixels().
static GLbitfield get_readpixels_transfer_ops (const struct gl_context * ctx, gl_format texFormat, GLenum format, GLenum type, GLboolean uses_blit) static
Return transfer op flags for this ReadPixels operation.
References gl_context::_ImageTransferState, _mesa_get_clamp_read_color(), _mesa_get_format_datatype(), _mesa_is_enum_format_integer(), GLbitfield, IMAGE_CLAMP_BIT, and need_rgb_to_luminance_conversion().
Referenced by _mesa_readpixels_needs_slow_path(), and read_rgba_pixels().
static GLboolean need_rgb_to_luminance_conversion (gl_format texFormat, GLenum format) static
Return true if the conversion L=R+G+B is needed.
References _mesa_get_format_base_format().
Referenced by _mesa_readpixels_needs_slow_path(), and get_readpixels_transfer_ops().
static void read_depth_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Read pixels for format=GL_DEPTH_COMPONENT.
References _mesa_error(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_pack_depth_span(), _mesa_unpack_float_z_row(), ASSERT, gl_framebuffer::Attachment, BUFFER_DEPTH, gl_context::Driver, gl_renderbuffer::Format, GLubyte, gl_renderbuffer::Height, dd_function_table::MapRenderbuffer, read_uint_depth_pixels(), gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, dd_function_table::UnmapRenderbuffer, and gl_renderbuffer::Width.
Referenced by _mesa_readpixels().
static void read_depth_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Read combined depth/stencil values.
We'll have already done error checking to be sure the expected depth and stencil buffers really exist.
References _mesa_image_address2d(), _mesa_image_row_stride(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), GLubyte, gl_pixel_attrib::IndexOffset, gl_pixel_attrib::IndexShift, gl_pixel_attrib::MapStencilFlag, gl_context::Pixel, slow_read_depth_stencil_pixels_separate(), and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_readpixels().
static GLenum read_pixels_es3_error_check (GLenum format, GLenum type, const struct gl_renderbuffer * rb) static
References _mesa_get_format_datatype(), _mesa_is_color_format(), _mesa_is_enum_format_signed_int(), _mesa_is_enum_format_unsigned_int(), gl_renderbuffer::Format, and gl_renderbuffer::InternalFormat.
Referenced by _mesa_ReadnPixelsARB().
static void read_rgba_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
References gl_framebuffer::_ColorReadBuffer, gl_renderbuffer::Format, get_readpixels_transfer_ops(), GLbitfield, read_rgba_pixels_swizzle(), gl_context::ReadBuffer, and slow_read_rgba_pixels().
Referenced by _mesa_readpixels().
static GLboolean read_rgba_pixels_swizzle (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Try to do glReadPixels of RGBA data using swizzle.
Returns
GL_TRUE if successful, GL_FALSE otherwise (use the slow path)
References gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_image_address2d(), _mesa_image_row_stride(), gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_XRGB8888, gl_context::Pack, gl_context::ReadBuffer, gl_pixelstore_attrib::SwapBytes, and dd_function_table::UnmapRenderbuffer.
Referenced by read_rgba_pixels().
static void read_stencil_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Read pixels for format=GL_STENCIL_INDEX.
References _mesa_error(), _mesa_image_address2d(), _mesa_pack_stencil_span(), _mesa_unpack_ubyte_stencil_row(), gl_framebuffer::Attachment, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_readpixels().
static GLboolean read_uint_depth_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
Optimized path for conversion of depth values to GL_DEPTH_COMPONENT, GL_UNSIGNED_INT.
References _mesa_error(), _mesa_get_format_datatype(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_unpack_uint_z_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, gl_context::Pixel, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, gl_pixelstore_attrib::SwapBytes, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_pixels().
static GLboolean readpixels_can_use_memcpy (const struct gl_context * ctx, GLenum format, GLenum type, const struct gl_pixelstore_attrib * packing) static
References gl_renderbuffer::_BaseFormat, _mesa_format_matches_format_and_type(), _mesa_get_format_base_format(), _mesa_get_read_renderbuffer_for_format(), _mesa_readpixels_needs_slow_path(), ASSERT, gl_renderbuffer::Format, and gl_pixelstore_attrib::SwapBytes.
Referenced by readpixels_memcpy().
static GLboolean readpixels_memcpy (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing) static
References _mesa_error(), _mesa_get_format_bytes(), _mesa_get_read_renderbuffer_for_format(), _mesa_image_address2d(), _mesa_image_row_stride(), gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, readpixels_can_use_memcpy(), and dd_function_table::UnmapRenderbuffer.
Referenced by _mesa_readpixels().
static void slow_read_depth_stencil_pixels_separate (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum type, const struct gl_pixelstore_attrib * packing, GLubyte * dst, int dstStride) static
References _mesa_error(), _mesa_pack_depth_stencil_span(), _mesa_unpack_float_z_row(), _mesa_unpack_ubyte_stencil_row(), gl_framebuffer::Attachment, BUFFER_DEPTH, BUFFER_STENCIL, gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, gl_context::ReadBuffer, gl_renderbuffer_attachment::Renderbuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by read_depth_stencil_pixels().
static void slow_read_rgba_pixels (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels, const struct gl_pixelstore_attrib * packing, GLbitfield transferOps) static
References gl_renderbuffer::_BaseFormat, gl_framebuffer::_ColorReadBuffer, _mesa_error(), _mesa_get_srgb_format_linear(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_is_enum_format_integer(), _mesa_is_format_unsigned(), _mesa_pack_rgba_span_float(), _mesa_pack_rgba_span_from_ints(), _mesa_pack_rgba_span_from_uints(), _mesa_rebase_rgba_float(), _mesa_rebase_rgba_uint(), _mesa_unpack_rgba_row(), _mesa_unpack_uint_rgba_row(), gl_context::Driver, gl_renderbuffer::Format, GLubyte, dd_function_table::MapRenderbuffer, MAX_PIXEL_BYTES, gl_context::ReadBuffer, and dd_function_table::UnmapRenderbuffer.
Referenced by read_rgba_pixels().