Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
remap.h File Reference
#include "main/compiler.h"
Data Structures
struct gl_function_pool_remap
struct gl_function_remap
Functions
const char * _mesa_get_function_spec (int func_index)
int _mesa_map_function_spec (const char *spec)
Map a function by its spec.
void _mesa_map_function_array (const struct gl_function_remap *func_array)
Map an array of functions.
void _mesa_map_static_functions (void)
Map the functions which are already static.
void _mesa_init_remap_table (void)
Variables
struct gl_function_pool_remap fpclassify
int driDispatchRemapTable []
Function Documentation
const char* _mesa_get_function_spec (int func_index)
void _mesa_init_remap_table (void)
References _mesa_do_init_remap_table(), _mesa_function_pool, driDispatchRemapTable_size, and MESA_remap_table_functions.
Referenced by one_time_init().
void _mesa_map_function_array (const struct gl_function_remap * func_array)
Map an array of functions.
This is a convenient function for use with arrays available from including remap_helper.h.
Note that the dispatch offsets of the functions are not returned. If they are needed, _mesa_map_function_spec() should be used.
Parameters
func_array an array of function remaps.
References _mesa_get_function_spec(), _mesa_map_function_spec(), _mesa_problem(), _mesa_warning(), gl_function_remap::func_index, and NULL.
Referenced by _mesa_map_static_functions().
int _mesa_map_function_spec (const char * spec)
Map a function by its spec.
The function will be added to glapi, and the dispatch offset will be returned.
Parameters
spec a '\0'-separated string array specifying a function. It begins with the parameter signature of the function, followed by the names of the entry points. An empty entry point name terminates the array.
Returns
the offset of the (re-)mapped function in the dispatch table, or -1.
References MAX_ENTRY_POINTS, and NULL.
Referenced by _mesa_do_init_remap_table(), and _mesa_map_function_array().
void _mesa_map_static_functions (void)
Map the functions which are already static.
When a extension function are incorporated into the ABI, the extension suffix is usually stripped. Mapping such functions makes sure the alternative names are available.
Note that functions mapped by _mesa_init_remap_table() are excluded.
References _mesa_map_function_array(), and MESA_alt_functions.
Variable Documentation
int driDispatchRemapTable[]
struct gl_function_pool_remap fpclassify
Referenced by _mesa_QueryMatrixxOES().