Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
remap.c File Reference
Remap table management.
#include "remap.h"
#include "imports.h"
#include "glapi/glapi.h"
#include "main/remap_helper.h"
Macros
#define MAX_ENTRY_POINTS 16
#define need_MESA_remap_table
Functions
const char * _mesa_get_function_spec (GLint func_index)
Return the spec string associated with the given function index.
GLint _mesa_map_function_spec (const char *spec)
Map a function by its spec.
void _mesa_map_function_array (const struct gl_function_remap *func_array)
Map an array of functions.
void _mesa_map_static_functions (void)
Map the functions which are already static.
static void _mesa_do_init_remap_table (const char *pool, int size, const struct gl_function_pool_remap *remap)
Initialize the remap table.
void _mesa_init_remap_table (void)
Variables
int driDispatchRemapTable [driDispatchRemapTable_size]
Detailed Description
Remap table management.
Entries in the dispatch table are either static or dynamic. The dispatch table is shared by mesa core and glapi. When they are built separately, it is possible that a static entry in mesa core is dynamic, or assigned a different static offset, in glapi. The remap table is in charge of mapping a static entry in mesa core to a dynamic entry, or the corresponding static entry, in glapi.
Macro Definition Documentation
#define MAX_ENTRY_POINTS 16
Referenced by _mesa_map_function_spec().
#define need_MESA_remap_table
Function Documentation
static void _mesa_do_init_remap_table (const char * pool, int size, const struct gl_function_pool_remap * remap) static
Initialize the remap table.
This is called in one_time_init(). The remap table needs to be initialized before calling the CALL/GET/SET macros defined in main/dispatch.h.
References _mesa_function_pool, _mesa_map_function_spec(), _mesa_warning(), ASSERT, driDispatchRemapTable, NULL, gl_function_pool_remap::pool_index, and size.
Referenced by _mesa_init_remap_table().
const char* _mesa_get_function_spec (GLint func_index)
Return the spec string associated with the given function index.
The index is available from including remap_helper.h.
Parameters
func_index an opaque function index.
Returns
the spec string associated with the function index, or NULL.
References _mesa_function_pool, Elements, and NULL.
Referenced by _mesa_map_function_array().
void _mesa_init_remap_table (void)
References _mesa_do_init_remap_table(), _mesa_function_pool, driDispatchRemapTable_size, and MESA_remap_table_functions.
Referenced by one_time_init().
void _mesa_map_function_array (const struct gl_function_remap * func_array)
Map an array of functions.
This is a convenient function for use with arrays available from including remap_helper.h.
Note that the dispatch offsets of the functions are not returned. If they are needed, _mesa_map_function_spec() should be used.
Parameters
func_array an array of function remaps.
References _mesa_get_function_spec(), _mesa_map_function_spec(), _mesa_problem(), _mesa_warning(), gl_function_remap::func_index, and NULL.
Referenced by _mesa_map_static_functions().
GLint _mesa_map_function_spec (const char * spec)
Map a function by its spec.
The function will be added to glapi, and the dispatch offset will be returned.
Parameters
spec a '\0'-separated string array specifying a function. It begins with the parameter signature of the function, followed by the names of the entry points. An empty entry point name terminates the array.
Returns
the offset of the (re-)mapped function in the dispatch table, or -1.
References MAX_ENTRY_POINTS, and NULL.
Referenced by _mesa_do_init_remap_table(), and _mesa_map_function_array().
void _mesa_map_static_functions (void)
Map the functions which are already static.
When a extension function are incorporated into the ABI, the extension suffix is usually stripped. Mapping such functions makes sure the alternative names are available.
Note that functions mapped by _mesa_init_remap_table() are excluded.
References _mesa_map_function_array(), and MESA_alt_functions.
Variable Documentation
int driDispatchRemapTable[driDispatchRemapTable_size]
Referenced by _mesa_do_init_remap_table().