Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
renderbuffer.h File Reference
#include "glheader.h"
#include "mtypes.h"
Functions
void _mesa_init_renderbuffer (struct gl_renderbuffer *rb, GLuint name)
Initialize the fields of a gl_renderbuffer to default values.
struct gl_renderbuffer * _mesa_new_renderbuffer (struct gl_context *ctx, GLuint name)
Allocate a new gl_renderbuffer object.
void _mesa_delete_renderbuffer (struct gl_context *ctx, struct gl_renderbuffer *rb)
Delete a gl_framebuffer.
void _mesa_add_renderbuffer (struct gl_framebuffer *fb, gl_buffer_index bufferName, struct gl_renderbuffer *rb)
Attach a renderbuffer to a framebuffer.
void _mesa_remove_renderbuffer (struct gl_framebuffer *fb, gl_buffer_index bufferName)
Remove the named renderbuffer from the given framebuffer.
void _mesa_reference_renderbuffer_ (struct gl_renderbuffer **ptr, struct gl_renderbuffer *rb)
Set *ptr to point to rb.
static void _mesa_reference_renderbuffer (struct gl_renderbuffer **ptr, struct gl_renderbuffer *rb)
Function Documentation
void _mesa_add_renderbuffer (struct gl_framebuffer * fb, gl_buffer_index bufferName, struct gl_renderbuffer * rb)
Attach a renderbuffer to a framebuffer.
Parameters
bufferName one of the BUFFER_x tokens
References _mesa_is_user_fbo(), _mesa_reference_renderbuffer(), gl_framebuffer::Attachment, BUFFER_COUNT, BUFFER_DEPTH, BUFFER_STENCIL, gl_renderbuffer_attachment::Complete, gl_renderbuffer::Name, NULL, gl_renderbuffer_attachment::Renderbuffer, and gl_renderbuffer_attachment::Type.
void _mesa_delete_renderbuffer (struct gl_context * ctx, struct gl_renderbuffer * rb)
Delete a gl_framebuffer.
This is the default function for renderbuffer->Delete(). Drivers which subclass gl_renderbuffer should probably implement their own delete function. But the driver might also call this function to free the object in the end.
References gl_renderbuffer::Mutex.
Referenced by _mesa_init_renderbuffer().
void _mesa_init_renderbuffer (struct gl_renderbuffer * rb, GLuint name)
Initialize the fields of a gl_renderbuffer to default values.
References _mesa_delete_renderbuffer(), gl_renderbuffer::AllocStorage, gl_renderbuffer::ClassID, gl_renderbuffer::Delete, gl_renderbuffer::Depth, gl_renderbuffer::Format, gl_renderbuffer::Height, gl_renderbuffer::InternalFormat, MESA_FORMAT_NONE, gl_renderbuffer::Mutex, gl_renderbuffer::Name, NULL, gl_renderbuffer::RefCount, and gl_renderbuffer::Width.
Referenced by _mesa_new_renderbuffer().
struct gl_renderbuffer* _mesa_new_renderbuffer (struct gl_context * ctx, GLuint name) read
Allocate a new gl_renderbuffer object.
This can be used for user-created renderbuffers or window-system renderbuffers.
References _mesa_init_renderbuffer(), and CALLOC_STRUCT.
static void _mesa_reference_renderbuffer (struct gl_renderbuffer ** ptr, struct gl_renderbuffer * rb) inline static
References _mesa_reference_renderbuffer_().
Referenced by _mesa_add_renderbuffer(), _mesa_BindRenderbuffer(), _mesa_DeleteRenderbuffers(), _mesa_free_framebuffer_data(), _mesa_remove_attachment(), _mesa_remove_renderbuffer(), _mesa_set_renderbuffer_attachment(), _mesa_update_texture_renderbuffer(), and reuse_framebuffer_texture_attachment().
void _mesa_reference_renderbuffer_ (struct gl_renderbuffer ** ptr, struct gl_renderbuffer * rb)
Set *ptr to point to rb.
If *ptr points to another renderbuffer, dereference that buffer first. The new renderbuffer's refcount will be incremented. The old renderbuffer's refcount will be decremented. This is normally only called from the _mesa_reference_renderbuffer() macro when there's a real pointer change.
References ASSERT, gl_renderbuffer::Delete, gl_renderbuffer::Mutex, NULL, and gl_renderbuffer::RefCount.
Referenced by _mesa_reference_renderbuffer().
void _mesa_remove_renderbuffer (struct gl_framebuffer * fb, gl_buffer_index bufferName)
Remove the named renderbuffer from the given framebuffer.
Parameters
bufferName one of the BUFFER_x tokens
References _mesa_reference_renderbuffer(), gl_framebuffer::Attachment, BUFFER_COUNT, NULL, and gl_renderbuffer_attachment::Renderbuffer.