Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
samplerobj.c File Reference
Functions for the GL_ARB_sampler_objects extension.
#include "main/glheader.h"
#include "main/context.h"
#include "main/dispatch.h"
#include "main/enums.h"
#include "main/hash.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/samplerobj.h"
Macros
#define INVALID_PARAM 0x100
#define INVALID_PNAME 0x101
#define INVALID_VALUE 0x102
Functions
struct gl_sampler_object * _mesa_lookup_samplerobj (struct gl_context *ctx, GLuint name)
void _mesa_reference_sampler_object_ (struct gl_context *ctx, struct gl_sampler_object **ptr, struct gl_sampler_object *samp)
Handle reference counting.
static void _mesa_init_sampler_object (struct gl_sampler_object *sampObj, GLuint name)
Initialize the fields of the given sampler object.
struct gl_sampler_object * _mesa_new_sampler_object (struct gl_context *ctx, GLuint name)
Fallback for ctx->Driver.NewSamplerObject();.
static void _mesa_delete_sampler_object (struct gl_context *ctx, struct gl_sampler_object *sampObj)
Fallback for ctx->Driver.DeleteSamplerObject();.
void GLAPIENTRY _mesa_GenSamplers (GLsizei count, GLuint *samplers)
void GLAPIENTRY _mesa_DeleteSamplers (GLsizei count, const GLuint *samplers)
GLboolean GLAPIENTRY _mesa_IsSampler (GLuint sampler)
void GLAPIENTRY _mesa_BindSampler (GLuint unit, GLuint sampler)
static GLboolean validate_texture_wrap_mode (struct gl_context *ctx, GLenum wrap)
Check if a coordinate wrap mode is legal.
static void flush (struct gl_context *ctx)
This is called just prior to changing any sampler object state.
static GLuint set_sampler_wrap_s (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_wrap_t (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_wrap_r (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_min_filter (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_mag_filter (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_lod_bias (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_border_colorf (struct gl_context *ctx, struct gl_sampler_object *samp, const GLfloat params[4])
static GLuint set_sampler_border_colori (struct gl_context *ctx, struct gl_sampler_object *samp, const GLint params[4])
static GLuint set_sampler_border_colorui (struct gl_context *ctx, struct gl_sampler_object *samp, const GLuint params[4])
static GLuint set_sampler_min_lod (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_max_lod (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_compare_mode (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_compare_func (struct gl_context *ctx, struct gl_sampler_object *samp, GLint param)
static GLuint set_sampler_max_anisotropy (struct gl_context *ctx, struct gl_sampler_object *samp, GLfloat param)
static GLuint set_sampler_cube_map_seamless (struct gl_context *ctx, struct gl_sampler_object *samp, GLboolean param)
static GLuint set_sampler_srgb_decode (struct gl_context *ctx, struct gl_sampler_object *samp, GLenum param)
void GLAPIENTRY _mesa_SamplerParameteri (GLuint sampler, GLenum pname, GLint param)
void GLAPIENTRY _mesa_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint *params)
void GLAPIENTRY _mesa_GetSamplerParameteriv (GLuint sampler, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint *params)
void _mesa_init_sampler_object_functions (struct dd_function_table *driver)
Detailed Description
Functions for the GL_ARB_sampler_objects extension.
Author
Brian Paul
Macro Definition Documentation
#define INVALID_PARAM 0x100
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_mag_filter(), set_sampler_min_filter(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
#define INVALID_PNAME 0x101
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_max_anisotropy(), and set_sampler_srgb_decode().
#define INVALID_VALUE 0x102
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), set_sampler_cube_map_seamless(), set_sampler_max_anisotropy(), and set_sampler_srgb_decode().
Function Documentation
void GLAPIENTRY _mesa_BindSampler (GLuint unit, GLuint sampler)
References _mesa_error(), _mesa_lookup_samplerobj(), _mesa_reference_sampler_object(), _NEW_TEXTURE, FLUSH_VERTICES, and NULL.
Referenced by _mesa_initialize_exec_table().
static void _mesa_delete_sampler_object (struct gl_context * ctx, struct gl_sampler_object * sampObj) static
Fallback for ctx->Driver.DeleteSamplerObject();.
Referenced by _mesa_init_sampler_object_functions().
void GLAPIENTRY _mesa_DeleteSamplers (GLsizei count, const GLuint * samplers)
References _mesa_error(), _mesa_HashRemove(), _mesa_lookup_samplerobj(), _mesa_reference_sampler_object(), _NEW_TEXTURE, FLUSH_VERTICES, and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GenSamplers (GLsizei count, GLuint * samplers)
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::i, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_sampler_object::sRGBDecode, gl_color_union::ui, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetSamplerParameteriv (GLuint sampler, GLenum pname, GLint * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, FLOAT_TO_INT, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_initialize_exec_table().
static void _mesa_init_sampler_object (struct gl_sampler_object * sampObj, GLuint name) static
Initialize the fields of the given sampler object.
References gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_color_union::f, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_sampler_object::Name, gl_sampler_object::RefCount, gl_sampler_object::sRGBDecode, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_new_sampler_object().
void _mesa_init_sampler_object_functions (struct dd_function_table * driver)
References _mesa_delete_sampler_object(), _mesa_new_sampler_object(), dd_function_table::DeleteSamplerObject, and dd_function_table::NewSamplerObject.
GLboolean GLAPIENTRY _mesa_IsSampler (GLuint sampler)
References _mesa_lookup_samplerobj(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, and NULL.
Referenced by _mesa_initialize_exec_table().
struct gl_sampler_object* _mesa_lookup_samplerobj (struct gl_context * ctx, GLuint name) read
References _mesa_HashLookup(), NULL, gl_shared_state::SamplerObjects, and gl_context::Shared.
Referenced by _mesa_BindSampler(), _mesa_DeleteSamplers(), _mesa_GetSamplerParameterfv(), _mesa_GetSamplerParameterIiv(), _mesa_GetSamplerParameterIuiv(), _mesa_GetSamplerParameteriv(), _mesa_IsSampler(), _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), _mesa_SamplerParameteriv(), and find_custom_value().
struct gl_sampler_object* _mesa_new_sampler_object (struct gl_context * ctx, GLuint name) read
Fallback for ctx->Driver.NewSamplerObject();.
References _mesa_init_sampler_object(), and CALLOC_STRUCT.
Referenced by _mesa_init_sampler_object_functions().
void _mesa_reference_sampler_object_ (struct gl_context * ctx, struct gl_sampler_object ** ptr, struct gl_sampler_object * samp)
Handle reference counting.
References _mesa_problem(), ASSERT, dd_function_table::DeleteSamplerObject, gl_context::Driver, gl_sampler_object::Name, NULL, and gl_sampler_object::RefCount.
Referenced by _mesa_reference_sampler_object().
void GLAPIENTRY _mesa_SamplerParameterf (GLuint sampler, GLenum pname, GLfloat param)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_SamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, set_sampler_border_colorf(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_SamplerParameteri (GLuint sampler, GLenum pname, GLint param)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_SamplerParameterIiv (GLuint sampler, GLenum pname, const GLint * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, set_sampler_border_colori(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_SamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, set_sampler_border_colorui(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_SamplerParameteriv (GLuint sampler, GLenum pname, const GLint * params)
References _mesa_error(), _mesa_lookup_enum_by_nr(), _mesa_lookup_samplerobj(), INT_TO_FLOAT, INVALID_PARAM, INVALID_PNAME, INVALID_VALUE, set_sampler_border_colorf(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
Referenced by _mesa_initialize_exec_table().
static void flush (struct gl_context * ctx) inline static
This is called just prior to changing any sampler object state.
References _NEW_TEXTURE, and FLUSH_VERTICES.
Referenced by set_sampler_border_colorf(), set_sampler_border_colori(), set_sampler_border_colorui(), set_sampler_compare_func(), set_sampler_compare_mode(), set_sampler_cube_map_seamless(), set_sampler_lod_bias(), set_sampler_mag_filter(), set_sampler_max_anisotropy(), set_sampler_max_lod(), set_sampler_min_filter(), set_sampler_min_lod(), set_sampler_srgb_decode(), set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().
static GLuint set_sampler_border_colorf (struct gl_context * ctx, struct gl_sampler_object * samp, const GLfloat params[4]) static
References ACOMP, BCOMP, gl_sampler_object::BorderColor, gl_color_union::f, flush(), GCOMP, and RCOMP.
Referenced by _mesa_SamplerParameterfv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_border_colori (struct gl_context * ctx, struct gl_sampler_object * samp, const GLint params[4]) static
References ACOMP, BCOMP, gl_sampler_object::BorderColor, flush(), GCOMP, gl_color_union::i, and RCOMP.
Referenced by _mesa_SamplerParameterIiv().
static GLuint set_sampler_border_colorui (struct gl_context * ctx, struct gl_sampler_object * samp, const GLuint params[4]) static
References ACOMP, BCOMP, gl_sampler_object::BorderColor, flush(), GCOMP, RCOMP, and gl_color_union::ui.
Referenced by _mesa_SamplerParameterIuiv().
static GLuint set_sampler_compare_func (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References gl_extensions::ARB_shadow, gl_sampler_object::CompareFunc, gl_extensions::EXT_shadow_funcs, gl_context::Extensions, flush(), INVALID_PARAM, and INVALID_PNAME.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_compare_mode (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References gl_extensions::ARB_shadow, gl_sampler_object::CompareMode, gl_context::Extensions, flush(), INVALID_PARAM, and INVALID_PNAME.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_cube_map_seamless (struct gl_context * ctx, struct gl_sampler_object * samp, GLboolean param) static
References gl_extensions::AMD_seamless_cubemap_per_texture, gl_sampler_object::CubeMapSeamless, gl_context::Extensions, flush(), INVALID_PNAME, and INVALID_VALUE.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_lod_bias (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References flush(), and gl_sampler_object::LodBias.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_mag_filter (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), INVALID_PARAM, and gl_sampler_object::MagFilter.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_max_anisotropy (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References gl_context::Const, gl_extensions::EXT_texture_filter_anisotropic, gl_context::Extensions, flush(), INVALID_PNAME, INVALID_VALUE, gl_sampler_object::MaxAnisotropy, gl_constants::MaxTextureMaxAnisotropy, and MIN2.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_max_lod (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References flush(), and gl_sampler_object::MaxLod.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_min_filter (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), INVALID_PARAM, and gl_sampler_object::MinFilter.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_min_lod (struct gl_context * ctx, struct gl_sampler_object * samp, GLfloat param) static
References flush(), and gl_sampler_object::MinLod.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_srgb_decode (struct gl_context * ctx, struct gl_sampler_object * samp, GLenum param) static
References gl_extensions::EXT_texture_sRGB_decode, gl_context::Extensions, flush(), INVALID_PNAME, INVALID_VALUE, and gl_sampler_object::sRGBDecode.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_wrap_r (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), INVALID_PARAM, validate_texture_wrap_mode(), and gl_sampler_object::WrapR.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_wrap_s (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), INVALID_PARAM, validate_texture_wrap_mode(), and gl_sampler_object::WrapS.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLuint set_sampler_wrap_t (struct gl_context * ctx, struct gl_sampler_object * samp, GLint param) static
References flush(), INVALID_PARAM, validate_texture_wrap_mode(), and gl_sampler_object::WrapT.
Referenced by _mesa_SamplerParameterf(), _mesa_SamplerParameterfv(), _mesa_SamplerParameteri(), _mesa_SamplerParameterIiv(), _mesa_SamplerParameterIuiv(), and _mesa_SamplerParameteriv().
static GLboolean validate_texture_wrap_mode (struct gl_context * ctx, GLenum wrap) static
Check if a coordinate wrap mode is legal.
Returns
GL_TRUE if legal, GL_FALSE otherwise
References gl_extensions::ARB_texture_border_clamp, gl_extensions::ATI_texture_mirror_once, gl_extensions::EXT_texture_mirror_clamp, and gl_context::Extensions.
Referenced by set_sampler_wrap_r(), set_sampler_wrap_s(), and set_sampler_wrap_t().