Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
scissor.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/mtypes.h"
#include "main/scissor.h"
Functions
void GLAPIENTRY _mesa_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
Called via glScissor.
void _mesa_set_scissor (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height)
Define the scissor box.
void _mesa_init_scissor (struct gl_context *ctx)
Initialize the context's scissor state.
Function Documentation
void _mesa_init_scissor (struct gl_context * ctx)
Initialize the context's scissor state.
Parameters
ctx the GL context.
References gl_scissor_attrib::Enabled, gl_scissor_attrib::Height, gl_context::Scissor, gl_scissor_attrib::Width, gl_scissor_attrib::X, and gl_scissor_attrib::Y.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_Scissor (GLint x, GLint y, GLsizei width, GLsizei height)
Called via glScissor.
References _mesa_debug(), _mesa_error(), _mesa_set_scissor(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void _mesa_set_scissor (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height)
Define the scissor box.
Parameters
x,y coordinates of the scissor box lower-left corner.
width width of the scissor box.
height height of the scissor box.
See Also
glScissor().
Verifies the parameters and updates __struct gl_contextRec::Scissor. On a change flushes the vertices and notifies the driver via the dd_function_table::Scissor callback.
References _NEW_SCISSOR, gl_context::Driver, FLUSH_VERTICES, gl_scissor_attrib::Height, dd_function_table::Scissor, gl_context::Scissor, gl_scissor_attrib::Width, gl_scissor_attrib::X, and gl_scissor_attrib::Y.
Referenced by _mesa_check_init_viewport(), and _mesa_Scissor().