Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
set.c File Reference
#include <stdlib.h>
#include "macros.h"
#include "set.h"
#include "ralloc.h"
Functions
static int entry_is_free (struct set_entry *entry)
static int entry_is_deleted (struct set_entry *entry)
static int entry_is_present (struct set_entry *entry)
struct set * _mesa_set_create (void *mem_ctx, bool key_equals_function(const void *a, const void *b))
void _mesa_set_destroy (struct set *ht, void(*delete_function)(struct set_entry *entry))
Frees the given set.
struct set_entry * _mesa_set_search (const struct set *ht, uint32_t hash, const void *key)
Finds a set entry with the given key and hash of that key.
static void set_rehash (struct set *ht, int new_size_index)
struct set_entry * _mesa_set_add (struct set *ht, uint32_t hash, const void *key)
Inserts the key with the given hash into the table.
void _mesa_set_remove (struct set *ht, struct set_entry *entry)
This function deletes the given hash table entry.
struct set_entry * _mesa_set_next_entry (const struct set *ht, struct set_entry *entry)
This function is an iterator over the hash table.
struct set_entry * _mesa_set_random_entry (struct set *ht, int(*predicate)(struct set_entry *entry))
Variables
uint32_t deleted_key_value
const void * deleted_key = &deleted_key_value
struct {
uint32_t max_entries
uint32_t size
uint32_t rehash
} hash_sizes []
Function Documentation
struct set_entry* _mesa_set_add (struct set * ht, uint32_t hash, const void * key) read
Inserts the key with the given hash into the table.
Note that insertion may rearrange the table on a resize or rehash, so previously found hash_entries are no longer valid after this function.
References entry_is_deleted(), entry_is_present(), set_entry::hash, set_entry::key, NULL, and set_rehash().
Referenced by _mesa_FenceSync(), and set_rehash().
struct set* _mesa_set_create (void * mem_ctx, bool key_equals_functionconst void *a,const void *b) read
References set::deleted_entries, set::entries, hash_sizes, set::key_equals_function, set::max_entries, set::mem_ctx, NULL, set::rehash, set::size, set::size_index, and set::table.
Referenced by _mesa_alloc_shared_state().
void _mesa_set_destroy (struct set * ht, void(*)(struct set_entry *entry) delete_function)
Frees the given set.
If delete_function is passed, it gets called on each entry present before freeing.
References set_foreach.
Referenced by free_shared_state().
struct set_entry* _mesa_set_next_entry (const struct set * ht, struct set_entry * entry) read
This function is an iterator over the hash table.
Pass in NULL for the first entry, as in the start of a for loop. Note that an iteration over the table is O(table_size) not O(entries).
References entry_is_present(), and NULL.
struct set_entry* _mesa_set_random_entry (struct set * ht, int(*)(struct set_entry *entry) predicate) read
References entry_is_present(), and NULL.
void _mesa_set_remove (struct set * ht, struct set_entry * entry)
This function deletes the given hash table entry.
Note that deletion doesn't otherwise modify the table, so an iteration over the table deleting entries is safe.
References deleted_key, and set_entry::key.
Referenced by _mesa_unref_sync_object().
struct set_entry* _mesa_set_search (const struct set * ht, uint32_t hash, const void * key) read
Finds a set entry with the given key and hash of that key.
Returns NULL if no entry is found.
References entry_is_free(), entry_is_present(), set_entry::hash, set_entry::key, and NULL.
Referenced by _mesa_unref_sync_object(), and _mesa_validate_sync().
static int entry_is_deleted (struct set_entry * entry) static
References deleted_key, and set_entry::key.
Referenced by _mesa_set_add().
static int entry_is_free (struct set_entry * entry) static
References set_entry::key, and NULL.
Referenced by _mesa_set_search().
static int entry_is_present (struct set_entry * entry) static
References deleted_key, set_entry::key, and NULL.
Referenced by _mesa_set_add(), _mesa_set_next_entry(), _mesa_set_random_entry(), _mesa_set_search(), and set_rehash().
static void set_rehash (struct set * ht, int new_size_index) static
References _mesa_set_add(), ARRAY_SIZE, entry_is_present(), set_entry::hash, hash_sizes, set_entry::key, NULL, set::size, size, set::table, and table.
Referenced by _mesa_set_add().
Variable Documentation
const void* deleted_key = &deleted_key_value
Referenced by _mesa_hash_table_set_deleted_key(), _mesa_set_remove(), entry_is_deleted(), and entry_is_present().
uint32_t deleted_key_value
struct { ... } hash_sizes[]
Referenced by _mesa_set_create(), and set_rehash().
uint32_t max_entries
uint32_t rehash
uint32_t size