Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
set.h File Reference
#include <inttypes.h>
#include <stdbool.h>
Data Structures
struct set_entry
struct set
Macros
#define set_foreach(set, entry)
This foreach function is safe against deletion, but not against insertion (which may rehash the set, making entry a dangling pointer).
Functions
struct set * _mesa_set_create (void *mem_ctx, bool(*key_equals_function)(const void *a, const void *b))
void _mesa_set_destroy (struct set *set, void(*delete_function)(struct set_entry *entry))
Frees the given set.
struct set_entry * _mesa_set_add (struct set *set, uint32_t hash, const void *key)
Inserts the key with the given hash into the table.
struct set_entry * _mesa_set_search (const struct set *set, uint32_t hash, const void *key)
Finds a set entry with the given key and hash of that key.
void _mesa_set_remove (struct set *set, struct set_entry *entry)
This function deletes the given hash table entry.
struct set_entry * _mesa_set_next_entry (const struct set *set, struct set_entry *entry)
This function is an iterator over the hash table.
struct set_entry * _mesa_set_random_entry (struct set *set, int(*predicate)(struct set_entry *entry))
Macro Definition Documentation
#define set_foreach (set, entry)
Value:
for (entry = _mesa_set_next_entry(set, NULL);  \
        entry != NULL;                                   \
        entry = _mesa_set_next_entry(set, entry))
This foreach function is safe against deletion, but not against insertion (which may rehash the set, making entry a dangling pointer).
Referenced by _mesa_set_destroy(), and free_shared_state().
Function Documentation
struct set_entry* _mesa_set_add (struct set * ht, uint32_t hash, const void * key) read
Inserts the key with the given hash into the table.
Note that insertion may rearrange the table on a resize or rehash, so previously found hash_entries are no longer valid after this function.
References entry_is_deleted(), entry_is_present(), set_entry::hash, set_entry::key, NULL, and set_rehash().
Referenced by _mesa_FenceSync(), and set_rehash().
struct set* _mesa_set_create (void * mem_ctx, bool(*)(const void *a, const void *b) key_equals_function) read
void _mesa_set_destroy (struct set * ht, void(*)(struct set_entry *entry) delete_function)
Frees the given set.
If delete_function is passed, it gets called on each entry present before freeing.
References set_foreach.
Referenced by free_shared_state().
struct set_entry* _mesa_set_next_entry (const struct set * ht, struct set_entry * entry) read
This function is an iterator over the hash table.
Pass in NULL for the first entry, as in the start of a for loop. Note that an iteration over the table is O(table_size) not O(entries).
References entry_is_present(), and NULL.
struct set_entry* _mesa_set_random_entry (struct set * set, int(*)(struct set_entry *entry) predicate) read
References entry_is_present(), and NULL.
void _mesa_set_remove (struct set * ht, struct set_entry * entry)
This function deletes the given hash table entry.
Note that deletion doesn't otherwise modify the table, so an iteration over the table deleting entries is safe.
References deleted_key, and set_entry::key.
Referenced by _mesa_unref_sync_object().
struct set_entry* _mesa_set_search (const struct set * ht, uint32_t hash, const void * key) read
Finds a set entry with the given key and hash of that key.
Returns NULL if no entry is found.
References entry_is_free(), entry_is_present(), set_entry::hash, set_entry::key, and NULL.
Referenced by _mesa_unref_sync_object(), and _mesa_validate_sync().