Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
shaderobj.h File Reference
#include "main/compiler.h"
#include "main/glheader.h"
#include "main/mtypes.h"
#include "program/ir_to_mesa.h"
Functions
void _mesa_init_shader_state (struct gl_context *ctx)
Internal functions.
void _mesa_free_shader_state (struct gl_context *ctx)
Free the per-context shader-related state.
void _mesa_reference_shader (struct gl_context *ctx, struct gl_shader **ptr, struct gl_shader *sh)
Set ptr to point to sh.
struct gl_shader * _mesa_lookup_shader (struct gl_context *ctx, GLuint name)
Lookup a GLSL shader object.
struct gl_shader * _mesa_lookup_shader_err (struct gl_context *ctx, GLuint name, const char *caller)
As above, but record an error if shader is not found.
void _mesa_reference_shader_program (struct gl_context *ctx, struct gl_shader_program **ptr, struct gl_shader_program *shProg)
Set ptr to point to shProg.
void _mesa_init_shader (struct gl_context *ctx, struct gl_shader *shader)
struct gl_shader * _mesa_new_shader (struct gl_context *ctx, GLuint name, GLenum type)
Allocate a new gl_shader object, initialize it.
void _mesa_init_shader_program (struct gl_context *ctx, struct gl_shader_program *prog)
struct gl_shader_program * _mesa_lookup_shader_program (struct gl_context *ctx, GLuint name)
Lookup a GLSL program object.
struct gl_shader_program * _mesa_lookup_shader_program_err (struct gl_context *ctx, GLuint name, const char *caller)
As above, but record an error if program is not found.
void _mesa_clear_shader_program_data (struct gl_context *ctx, struct gl_shader_program *shProg)
Clear (free) the shader program state that gets produced by linking.
void _mesa_free_shader_program_data (struct gl_context *ctx, struct gl_shader_program *shProg)
Free all the data that hangs off a shader program object, but not the object itself.
void _mesa_init_shader_object_functions (struct dd_function_table *driver)
static gl_shader_type _mesa_shader_type_to_index (GLenum v)
static GLenum _mesa_shader_index_to_type (GLuint i)
Function Documentation
void _mesa_clear_shader_program_data (struct gl_context * ctx, struct gl_shader_program * shProg)
Clear (free) the shader program state that gets produced by linking.
References _mesa_uniform_detach_all_driver_storage(), gl_shader_program::InfoLog, NULL, gl_shader_program::NumUserUniformStorage, gl_shader_program::UniformHash, and gl_shader_program::UniformStorage.
Referenced by _mesa_free_shader_program_data().
void _mesa_free_shader_program_data (struct gl_context * ctx, struct gl_shader_program * shProg)
Free all the data that hangs off a shader program object, but not the object itself.
References gl_shader_program::_LinkedShaders, _mesa_clear_shader_program_data(), _mesa_reference_shader(), gl_shader_program::AttributeBindings, dd_function_table::DeleteShader, gl_context::Driver, gl_shader_program::FragDataBindings, gl_shader_program::FragDataIndexBindings, GL_SHADER_PROGRAM_MESA, MESA_SHADER_TYPES, NULL, gl_shader_program::NumShaders, gl_shader_program::NumVarying, gl_shader_program::Shaders, gl_shader_program::TransformFeedback, gl_shader_program::Type, and gl_shader_program::VaryingNames.
Referenced by _mesa_delete_shader_program(), and free_shader_program_data_cb().
void _mesa_free_shader_state (struct gl_context * ctx)
Free the per-context shader-related state.
References gl_shader_state::_CurrentFragmentProgram, _mesa_reference_shader_program(), gl_shader_state::ActiveProgram, gl_shader_state::CurrentFragmentProgram, gl_shader_state::CurrentGeometryProgram, gl_shader_state::CurrentVertexProgram, NULL, and gl_context::Shader.
Referenced by _mesa_free_context_data().
void _mesa_init_shader (struct gl_context * ctx, struct gl_shader * shader)
References gl_shader::RefCount.
Referenced by _mesa_new_shader().
void _mesa_init_shader_object_functions (struct dd_function_table * driver)
References _mesa_delete_shader(), _mesa_delete_shader_program(), _mesa_new_shader(), _mesa_new_shader_program(), dd_function_table::DeleteShader, dd_function_table::DeleteShaderProgram, dd_function_table::LinkShader, dd_function_table::NewShader, and dd_function_table::NewShaderProgram.
void _mesa_init_shader_program (struct gl_context * ctx, struct gl_shader_program * prog)
References gl_shader_program::AttributeBindings, gl_shader_program::BufferMode, gl_shader_program::FragDataBindings, gl_shader_program::FragDataIndexBindings, gl_shader_program::Geom, GL_SHADER_PROGRAM_MESA, gl_shader_program::InfoLog, gl_shader_program::InputType, gl_shader_program::OutputType, gl_shader_program::RefCount, gl_shader_program::TransformFeedback, gl_shader_program::Type, and gl_shader_program::VerticesOut.
Referenced by _mesa_new_shader_program().
void _mesa_init_shader_state (struct gl_context * ctx)
Internal functions.
References gl_shader_compiler_options::DefaultPragmas, gl_shader_state::Flags, get_shader_flags(), gl_shader_compiler_options::MaxIfDepth, gl_shader_compiler_options::MaxUnrollIterations, MESA_SHADER_TYPES, gl_sl_pragmas::Optimize, gl_context::Shader, and gl_context::ShaderCompilerOptions.
Referenced by init_attrib_groups().
struct gl_shader* _mesa_lookup_shader (struct gl_context * ctx, GLuint name) read
Lookup a GLSL shader object.
References _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, NULL, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader::Type.
Referenced by _mesa_CreateShaderProgramEXT(), _mesa_ShaderSource(), get_shader_info_log(), and is_shader().
struct gl_shader* _mesa_lookup_shader_err (struct gl_context * ctx, GLuint name, const char * caller) read
As above, but record an error if shader is not found.
References _mesa_error(), _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, NULL, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader::Type.
Referenced by attach_shader(), compile_shader(), delete_shader(), get_shader_source(), get_shaderiv(), and shader_source().
struct gl_shader_program* _mesa_lookup_shader_program (struct gl_context * ctx, GLuint name) read
Lookup a GLSL program object.
References _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, NULL, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader_program::Type.
Referenced by _mesa_CreateShaderProgramEXT(), _mesa_GetTransformFeedbackVarying(), _mesa_TransformFeedbackVaryings(), get_program_info_log(), get_programiv(), and is_program().
struct gl_shader_program* _mesa_lookup_shader_program_err (struct gl_context * ctx, GLuint name, const char * caller) read
As above, but record an error if program is not found.
References _mesa_error(), _mesa_HashLookup(), GL_SHADER_PROGRAM_MESA, NULL, gl_shared_state::ShaderObjects, gl_context::Shared, and gl_shader_program::Type.
Referenced by _mesa_ActiveProgramEXT(), _mesa_GetActiveUniformBlockiv(), _mesa_GetActiveUniformBlockName(), _mesa_GetActiveUniformName(), _mesa_GetProgramBinary(), _mesa_GetUniformBlockIndex(), _mesa_GetUniformIndices(), _mesa_GetUniformLocation(), _mesa_ProgramBinary(), _mesa_ProgramParameteri(), _mesa_UniformBlockBinding(), _mesa_UseProgram(), _mesa_UseShaderProgramEXT(), attach_shader(), delete_shader_program(), detach_shader(), get_attached_shaders(), link_program(), and validate_program().
struct gl_shader* _mesa_new_shader (struct gl_context * ctx, GLuint name, GLenum type) read
Allocate a new gl_shader object, initialize it.
Called via ctx->Driver.NewShader()
References _mesa_init_shader(), gl_shader::Name, NULL, and gl_shader::Type.
Referenced by _mesa_init_shader_object_functions().
void _mesa_reference_shader (struct gl_context * ctx, struct gl_shader ** ptr, struct gl_shader * sh)
Set ptr to point to sh.
If ptr is pointing to another shader, decrement its refcount (and delete if refcount hits zero). Then set ptr to point to sh, incrementing its refcount.
References _mesa_HashRemove(), ASSERT, dd_function_table::DeleteShader, gl_context::Driver, gl_shader::Name, NULL, gl_shader::RefCount, gl_shared_state::ShaderObjects, and gl_context::Shared.
Referenced by _mesa_free_shader_program_data(), attach_shader(), delete_shader(), and detach_shader().
void _mesa_reference_shader_program (struct gl_context * ctx, struct gl_shader_program ** ptr, struct gl_shader_program * shProg)
Set ptr to point to shProg.
If ptr is pointing to another object, decrement its refcount (and delete if refcount hits zero). Then set ptr to point to shProg, incrementing its refcount.
References _mesa_HashRemove(), ASSERT, dd_function_table::DeleteShaderProgram, gl_context::Driver, gl_shader_program::Name, NULL, gl_shader_program::RefCount, gl_shared_state::ShaderObjects, and gl_context::Shared.
Referenced by _mesa_active_program(), _mesa_free_shader_state(), delete_shader_program(), update_program(), and use_shader_program().
static GLenum _mesa_shader_index_to_type (GLuint i) inline static
References MESA_SHADER_TYPES.
static gl_shader_type _mesa_shader_type_to_index (GLenum v) inline static
References ASSERT, MESA_SHADER_FRAGMENT, MESA_SHADER_GEOMETRY, MESA_SHADER_TYPES, and MESA_SHADER_VERTEX.
Referenced by compile_shader().