Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
shaderapi.h File Reference
#include "glheader.h"
Functions
void _mesa_copy_string (GLchar *dst, GLsizei maxLength, GLsizei *length, const GLchar *src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
void _mesa_use_program (struct gl_context *ctx, struct gl_shader_program *shProg)
Use the named shader program for subsequent rendering.
void _mesa_active_program (struct gl_context *ctx, struct gl_shader_program *shProg, const char *caller)
Use the named shader program for subsequent glUniform calls.
unsigned _mesa_count_active_attribs (struct gl_shader_program *shProg)
size_t _mesa_longest_attribute_name_length (struct gl_shader_program *shProg)
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB, GLhandleARB)
void GLAPIENTRY _mesa_CompileShader (GLhandleARB)
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB, GLhandleARB)
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB, GLsizei, GLsizei *, GLhandleARB *)
GLint GLAPIENTRY _mesa_GetFragDataLocation (GLuint program, const GLchar *name)
GLint GLAPIENTRY _mesa_GetFragDataIndex (GLuint program, const GLchar *name)
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB, GLsizei, GLsizei *, GLcharARB *)
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB, GLenum, GLfloat *)
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB, GLenum, GLint *)
void GLAPIENTRY _mesa_GetShaderSource (GLhandleARB, GLsizei, GLsizei *, GLcharARB *)
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
void GLAPIENTRY _mesa_LinkProgram (GLhandleARB programObj)
void GLAPIENTRY _mesa_ShaderSource (GLhandleARB, GLsizei, const GLcharARB *const *, const GLint *)
Called via glShaderSource() and glShaderSourceARB() API functions.
void GLAPIENTRY _mesa_UseProgram (GLhandleARB)
void GLAPIENTRY _mesa_ValidateProgram (GLhandleARB)
void GLAPIENTRY _mesa_BindAttribLocation (GLhandleARB, GLuint, const GLcharARB *)
void GLAPIENTRY _mesa_BindFragDataLocation (GLuint program, GLuint colorNumber, const GLchar *name)
void GLAPIENTRY _mesa_BindFragDataLocationIndexed (GLuint program, GLuint colorNumber, GLuint index, const GLchar *name)
void GLAPIENTRY _mesa_GetActiveAttrib (GLhandleARB, GLuint, GLsizei, GLsizei *, GLint *, GLenum *, GLcharARB *)
GLint GLAPIENTRY _mesa_GetAttribLocation (GLhandleARB, const GLcharARB *)
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
GLuint GLAPIENTRY _mesa_CreateShader (GLenum)
GLuint GLAPIENTRY _mesa_CreateProgram (void)
void GLAPIENTRY _mesa_DeleteProgram (GLuint program)
void GLAPIENTRY _mesa_DeleteShader (GLuint shader)
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *obj)
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint *shaders, GLenum binaryformat, const void *binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, GLvoid *binary)
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid *binary, GLsizei length)
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
void _mesa_use_shader_program (struct gl_context *ctx, GLenum type, struct gl_shader_program *shProg)
void GLAPIENTRY _mesa_UseShaderProgramEXT (GLenum type, GLuint program)
For GL_EXT_separate_shader_objects.
void GLAPIENTRY _mesa_ActiveProgramEXT (GLuint program)
For GL_EXT_separate_shader_objects.
GLuint GLAPIENTRY _mesa_CreateShaderProgramEXT (GLenum type, const GLchar *string)
For GL_EXT_separate_shader_objects.
Function Documentation
void _mesa_active_program (struct gl_context * ctx, struct gl_shader_program * shProg, const char * caller)
Use the named shader program for subsequent glUniform calls.
References _mesa_error(), _mesa_reference_shader_program(), gl_shader_state::ActiveProgram, gl_shader_program::LinkStatus, gl_shader_program::Name, NULL, and gl_context::Shader.
Referenced by _mesa_ActiveProgramEXT(), and _mesa_use_program().
void GLAPIENTRY _mesa_ActiveProgramEXT (GLuint program)
For GL_EXT_separate_shader_objects.
References _mesa_active_program(), _mesa_lookup_shader_program_err(), and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB , GLhandleARB)
References attach_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
References attach_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindAttribLocation (GLhandleARB , GLuint , const GLcharARB *)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindFragDataLocation (GLuint program, GLuint colorNumber, const GLchar * name)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindFragDataLocationIndexed (GLuint program, GLuint colorNumber, GLuint index, const GLchar * name)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CompileShader (GLhandleARB)
References _mesa_debug(), compile_shader(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void _mesa_copy_string (GLchar * dst, GLsizei maxLength, GLsizei * length, const GLchar * src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
Parameters
src the strings source
maxLength max chars to copy
length returns number of chars copied
dst the string destination
Referenced by _mesa_get_uniform_name(), _mesa_GetActiveUniformBlockName(), _mesa_GetTransformFeedbackVarying(), get_program_info_log(), get_shader_info_log(), and get_shader_source().
unsigned _mesa_count_active_attribs (struct gl_shader_program * shProg)
Referenced by get_programiv().
GLuint GLAPIENTRY _mesa_CreateProgram (void)
References _mesa_debug(), create_shader_program(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
References create_shader_program().
Referenced by _mesa_initialize_exec_table().
GLuint GLAPIENTRY _mesa_CreateShader (GLenum)
References _mesa_debug(), _mesa_lookup_enum_by_nr(), create_shader(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
References create_shader().
Referenced by _mesa_initialize_exec_table().
GLuint GLAPIENTRY _mesa_CreateShaderProgramEXT (GLenum type, const GLchar * string)
For GL_EXT_separate_shader_objects.
References _mesa_lookup_shader(), _mesa_lookup_shader_program(), _mesa_strdup(), attach_shader(), compile_shader(), create_shader(), create_shader_program(), delete_shader(), detach_shader(), get_shaderiv(), gl_shader::InfoLog, gl_shader_program::InfoLog, link_program(), gl_shader_program::LinkStatus, and shader_source().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
References _mesa_debug(), delete_shader(), delete_shader_program(), FLUSH_VERTICES, is_program(), is_shader(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteProgram (GLuint program)
References delete_shader_program(), and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteShader (GLuint shader)
References delete_shader(), and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB , GLhandleARB)
References detach_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
References detach_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetActiveAttrib (GLhandleARB , GLuint , GLsizei , GLsizei * , GLint * , GLenum * , GLcharARB *)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB , GLsizei , GLsizei * , GLhandleARB *)
References get_attached_shaders().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei * count, GLuint * obj)
References get_attached_shaders().
Referenced by _mesa_initialize_exec_table().
GLint GLAPIENTRY _mesa_GetAttribLocation (GLhandleARB , const GLcharARB *)
Referenced by _mesa_initialize_exec_table().
GLint GLAPIENTRY _mesa_GetFragDataIndex (GLuint program, const GLchar * name)
Referenced by _mesa_initialize_exec_table().
GLint GLAPIENTRY _mesa_GetFragDataLocation (GLuint program, const GLchar * name)
Referenced by _mesa_initialize_exec_table().
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
References get_handle().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB , GLsizei , GLsizei * , GLcharARB *)
References _mesa_error(), get_program_info_log(), get_shader_info_log(), is_program(), and is_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB , GLenum , GLfloat *)
References _mesa_GetObjectParameterivARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB , GLenum , GLint *)
References _mesa_error(), get_programiv(), get_shaderiv(), is_program(), and is_shader().
Referenced by _mesa_GetObjectParameterfvARB(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, GLvoid * binary)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::LinkStatus, gl_shader_program::Name, NULL, and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References get_program_info_log().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint * params)
References get_programiv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References get_shader_info_log().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint * params)
References get_shaderiv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References _mesa_error(), gl_program_constants::HighFloat, gl_program_constants::HighInt, gl_precision::Precision, gl_precision::RangeMax, and gl_precision::RangeMin.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderSource (GLhandleARB , GLsizei , GLsizei * , GLcharARB *)
References get_shader_source().
Referenced by _mesa_initialize_exec_table().
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
References is_program().
Referenced by _mesa_initialize_exec_table().
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
References is_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_LinkProgram (GLhandleARB programObj)
References link_program().
Referenced by _mesa_initialize_exec_table().
size_t _mesa_longest_attribute_name_length (struct gl_shader_program * shProg)
Referenced by get_programiv().
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid * binary, GLsizei length)
References __FUNCTION__, _mesa_error(), _mesa_lookup_shader_program_err(), and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lookup_enum_by_nr(), _mesa_lookup_shader_program_err(), gl_shader_program::BinaryRetreivableHint, gl_shader_program::Geom, gl_shader_program::InputType, gl_shader_program::OutputType, and gl_shader_program::VerticesOut.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint * shaders, GLenum binaryformat, const void * binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References __FUNCTION__, _mesa_error(), and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ShaderSource (GLhandleARB shaderObj, GLsizei count, const GLcharARB *const * string, const GLint * length)
Called via glShaderSource() and glShaderSourceARB() API functions.
Basically, concatenate the source code strings into one long string and pass it to _mesa_shader_source().
References _mesa_error(), _mesa_lookup_shader(), _mesa_snprintf(), _mesa_str_checksum(), NULL, read_shader(), shader_source(), SHADER_SUBST, and gl_shader::SourceChecksum.
Referenced by _mesa_initialize_exec_table().
void _mesa_use_program (struct gl_context * ctx, struct gl_shader_program * shProg)
Use the named shader program for subsequent rendering.
References _mesa_active_program(), gl_context::Driver, use_shader_program(), and dd_function_table::UseProgram.
Referenced by _mesa_UseProgram().
void _mesa_use_shader_program (struct gl_context * ctx, GLenum type, struct gl_shader_program * shProg)
References gl_context::Driver, use_shader_program(), and dd_function_table::UseProgram.
Referenced by _mesa_UseShaderProgramEXT().
void GLAPIENTRY _mesa_UseProgram (GLhandleARB)
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_shader_program_err(), _mesa_use_program(), GLSL_USE_PROG, gl_shader_program::LinkStatus, NULL, and print_shader_info().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UseShaderProgramEXT (GLenum type, GLuint program)
For GL_EXT_separate_shader_objects.
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_shader_program_err(), _mesa_use_shader_program(), gl_shader_program::LinkStatus, NULL, and validate_shader_target().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ValidateProgram (GLhandleARB)
References validate_program().
Referenced by _mesa_initialize_exec_table().