Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
shaderapi.c File Reference
#include "main/glheader.h"
#include "main/context.h"
#include "main/dispatch.h"
#include "main/enums.h"
#include "main/hash.h"
#include "main/mtypes.h"
#include "main/shaderapi.h"
#include "main/shaderobj.h"
#include "main/transformfeedback.h"
#include "main/uniforms.h"
#include "program/program.h"
#include "program/prog_parameter.h"
#include "ralloc.h"
#include <stdbool.h>
#include "../glsl/glsl_parser_extras.h"
#include "../glsl/ir_uniform.h"
Macros
#define SHADER_SUBST 0
Define this to enable shader substitution (see below)
Functions
static GLbitfield get_shader_flags (void)
Return mask of GLSL_x flags by examining the MESA_GLSL env var.
void _mesa_init_shader_state (struct gl_context *ctx)
Initialize context's shader state.
void _mesa_free_shader_state (struct gl_context *ctx)
Free the per-context shader-related state.
void _mesa_copy_string (GLchar *dst, GLsizei maxLength, GLsizei *length, const GLchar *src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
static bool validate_shader_target (const struct gl_context *ctx, GLenum type)
Confirm that the a shader type is valid and supported by the implementation.
static GLboolean is_program (struct gl_context *ctx, GLuint name)
static GLboolean is_shader (struct gl_context *ctx, GLuint name)
static void attach_shader (struct gl_context *ctx, GLuint program, GLuint shader)
Attach shader to a shader program.
static GLuint create_shader (struct gl_context *ctx, GLenum type)
static GLuint create_shader_program (struct gl_context *ctx)
static void delete_shader_program (struct gl_context *ctx, GLuint name)
Named w/ "2" to indicate OpenGL 2.x vs GL_ARB_fragment_programs's DeleteProgramARB.
static void delete_shader (struct gl_context *ctx, GLuint shader)
static void detach_shader (struct gl_context *ctx, GLuint program, GLuint shader)
static void get_attached_shaders (struct gl_context *ctx, GLuint program, GLsizei maxCount, GLsizei *count, GLuint *obj)
Return list of shaders attached to shader program.
static GLuint get_handle (struct gl_context *ctx, GLenum pname)
glGetHandleARB() - return ID/name of currently bound shader program.
static void get_programiv (struct gl_context *ctx, GLuint program, GLenum pname, GLint *params)
glGetProgramiv() - get shader program state.
static void get_shaderiv (struct gl_context *ctx, GLuint name, GLenum pname, GLint *params)
glGetShaderiv() - get GLSL shader state
static void get_program_info_log (struct gl_context *ctx, GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
static void get_shader_info_log (struct gl_context *ctx, GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
static void get_shader_source (struct gl_context *ctx, GLuint shader, GLsizei maxLength, GLsizei *length, GLchar *sourceOut)
Return shader source code.
static void shader_source (struct gl_context *ctx, GLuint shader, const GLchar *source)
Set/replace shader source code.
static void compile_shader (struct gl_context *ctx, GLuint shaderObj)
Compile a shader.
static void link_program (struct gl_context *ctx, GLuint program)
Link a program's shaders.
static void print_shader_info (const struct gl_shader_program *shProg)
Print basic shader info (for debug).
void _mesa_active_program (struct gl_context *ctx, struct gl_shader_program *shProg, const char *caller)
Use the named shader program for subsequent glUniform calls.
static bool use_shader_program (struct gl_context *ctx, GLenum type, struct gl_shader_program *shProg)
void _mesa_use_program (struct gl_context *ctx, struct gl_shader_program *shProg)
Use the named shader program for subsequent rendering.
static GLboolean validate_shader_program (const struct gl_shader_program *shProg, char *errMsg)
Do validation of the given shader program.
static void validate_program (struct gl_context *ctx, GLuint program)
Called via glValidateProgram()
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB program, GLhandleARB shader)
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
void GLAPIENTRY _mesa_CompileShader (GLhandleARB shaderObj)
GLuint GLAPIENTRY _mesa_CreateShader (GLenum type)
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
GLuint GLAPIENTRY _mesa_CreateProgram (void)
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
void GLAPIENTRY _mesa_DeleteProgram (GLuint name)
void GLAPIENTRY _mesa_DeleteShader (GLuint name)
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB program, GLhandleARB shader)
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB container, GLsizei maxCount, GLsizei *count, GLhandleARB *obj)
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *obj)
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB object, GLsizei maxLength, GLsizei *length, GLcharARB *infoLog)
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB object, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB object, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GLAPIENTRY _mesa_GetShaderSource (GLhandleARB shader, GLsizei maxLength, GLsizei *length, GLcharARB *sourceOut)
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
void GLAPIENTRY _mesa_LinkProgram (GLhandleARB programObj)
static GLcharARB * read_shader (const char *fname)
Read shader source code from a file.
void GLAPIENTRY _mesa_ShaderSource (GLhandleARB shaderObj, GLsizei count, const GLcharARB *const *string, const GLint *length)
Called via glShaderSource() and glShaderSourceARB() API functions.
void GLAPIENTRY _mesa_UseProgram (GLhandleARB program)
void GLAPIENTRY _mesa_ValidateProgram (GLhandleARB program)
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint *shaders, GLenum binaryformat, const void *binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, GLvoid *binary)
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid *binary, GLsizei length)
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
void _mesa_use_shader_program (struct gl_context *ctx, GLenum type, struct gl_shader_program *shProg)
void GLAPIENTRY _mesa_UseShaderProgramEXT (GLenum type, GLuint program)
For GL_EXT_separate_shader_objects.
void GLAPIENTRY _mesa_ActiveProgramEXT (GLuint program)
For GL_EXT_separate_shader_objects.
GLuint GLAPIENTRY _mesa_CreateShaderProgramEXT (GLenum type, const GLchar *string)
For GL_EXT_separate_shader_objects.
Detailed Description
Author
Brian Paul
Implementation of GLSL-related API functions. The glUniform* functions are in uniforms.c
XXX things to do:
Check that the right error code is generated for all _mesa_error() calls.
Insert FLUSH_VERTICES calls in various places
Macro Definition Documentation
#define SHADER_SUBST 0
Define this to enable shader substitution (see below)
Referenced by _mesa_ShaderSource().
Function Documentation
void _mesa_active_program (struct gl_context * ctx, struct gl_shader_program * shProg, const char * caller)
Use the named shader program for subsequent glUniform calls.
References _mesa_error(), _mesa_reference_shader_program(), gl_shader_state::ActiveProgram, gl_shader_program::LinkStatus, gl_shader_program::Name, NULL, and gl_context::Shader.
Referenced by _mesa_ActiveProgramEXT(), and _mesa_use_program().
void GLAPIENTRY _mesa_ActiveProgramEXT (GLuint program)
For GL_EXT_separate_shader_objects.
References _mesa_active_program(), _mesa_lookup_shader_program_err(), and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_AttachObjectARB (GLhandleARB program, GLhandleARB shader)
References attach_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_AttachShader (GLuint program, GLuint shader)
References attach_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CompileShader (GLhandleARB shaderObj)
References _mesa_debug(), compile_shader(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void _mesa_copy_string (GLchar * dst, GLsizei maxLength, GLsizei * length, const GLchar * src)
Copy string from <src> to <dst>, up to maxLength characters, returning length of <dst> in <length>.
Parameters
src the strings source
maxLength max chars to copy
length returns number of chars copied
dst the string destination
Referenced by _mesa_get_uniform_name(), _mesa_GetActiveUniformBlockName(), _mesa_GetTransformFeedbackVarying(), get_program_info_log(), get_shader_info_log(), and get_shader_source().
GLuint GLAPIENTRY _mesa_CreateProgram (void)
References _mesa_debug(), create_shader_program(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
GLhandleARB GLAPIENTRY _mesa_CreateProgramObjectARB (void)
References create_shader_program().
Referenced by _mesa_initialize_exec_table().
GLuint GLAPIENTRY _mesa_CreateShader (GLenum type)
References _mesa_debug(), _mesa_lookup_enum_by_nr(), create_shader(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
GLhandleARB GLAPIENTRY _mesa_CreateShaderObjectARB (GLenum type)
References create_shader().
Referenced by _mesa_initialize_exec_table().
GLuint GLAPIENTRY _mesa_CreateShaderProgramEXT (GLenum type, const GLchar * string)
For GL_EXT_separate_shader_objects.
References _mesa_lookup_shader(), _mesa_lookup_shader_program(), _mesa_strdup(), attach_shader(), compile_shader(), create_shader(), create_shader_program(), delete_shader(), detach_shader(), get_shaderiv(), gl_shader::InfoLog, gl_shader_program::InfoLog, link_program(), gl_shader_program::LinkStatus, and shader_source().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteObjectARB (GLhandleARB obj)
References _mesa_debug(), delete_shader(), delete_shader_program(), FLUSH_VERTICES, is_program(), is_shader(), MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteProgram (GLuint name)
References delete_shader_program(), and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DeleteShader (GLuint name)
References delete_shader(), and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DetachObjectARB (GLhandleARB program, GLhandleARB shader)
References detach_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_DetachShader (GLuint program, GLuint shader)
References detach_shader().
Referenced by _mesa_initialize_exec_table().
void _mesa_free_shader_state (struct gl_context * ctx)
Free the per-context shader-related state.
References gl_shader_state::_CurrentFragmentProgram, _mesa_reference_shader_program(), gl_shader_state::ActiveProgram, gl_shader_state::CurrentFragmentProgram, gl_shader_state::CurrentGeometryProgram, gl_shader_state::CurrentVertexProgram, NULL, and gl_context::Shader.
Referenced by _mesa_free_context_data().
void GLAPIENTRY _mesa_GetAttachedObjectsARB (GLhandleARB container, GLsizei maxCount, GLsizei * count, GLhandleARB * obj)
References get_attached_shaders().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei * count, GLuint * obj)
References get_attached_shaders().
Referenced by _mesa_initialize_exec_table().
GLhandleARB GLAPIENTRY _mesa_GetHandleARB (GLenum pname)
References get_handle().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetInfoLogARB (GLhandleARB object, GLsizei maxLength, GLsizei * length, GLcharARB * infoLog)
References _mesa_error(), get_program_info_log(), get_shader_info_log(), is_program(), and is_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetObjectParameterfvARB (GLhandleARB object, GLenum pname, GLfloat * params)
References _mesa_GetObjectParameterivARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetObjectParameterivARB (GLhandleARB object, GLenum pname, GLint * params)
References _mesa_error(), get_programiv(), get_shaderiv(), is_program(), and is_shader().
Referenced by _mesa_GetObjectParameterfvARB(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramBinary (GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, GLvoid * binary)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_shader_program::LinkStatus, gl_shader_program::Name, NULL, and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References get_program_info_log().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetProgramiv (GLuint program, GLenum pname, GLint * params)
References get_programiv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
References get_shader_info_log().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderiv (GLuint shader, GLenum pname, GLint * params)
References get_shaderiv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References _mesa_error(), gl_program_constants::HighFloat, gl_program_constants::HighInt, gl_precision::Precision, gl_precision::RangeMax, and gl_precision::RangeMin.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetShaderSource (GLhandleARB shader, GLsizei maxLength, GLsizei * length, GLcharARB * sourceOut)
References get_shader_source().
Referenced by _mesa_initialize_exec_table().
void _mesa_init_shader_state (struct gl_context * ctx)
Initialize context's shader state.
Internal functions.
References gl_shader_compiler_options::DefaultPragmas, gl_shader_state::Flags, get_shader_flags(), gl_shader_compiler_options::MaxIfDepth, gl_shader_compiler_options::MaxUnrollIterations, MESA_SHADER_TYPES, gl_sl_pragmas::Optimize, gl_context::Shader, and gl_context::ShaderCompilerOptions.
Referenced by init_attrib_groups().
GLboolean GLAPIENTRY _mesa_IsProgram (GLuint name)
References is_program().
Referenced by _mesa_initialize_exec_table().
GLboolean GLAPIENTRY _mesa_IsShader (GLuint name)
References is_shader().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_LinkProgram (GLhandleARB programObj)
References link_program().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramBinary (GLuint program, GLenum binaryFormat, const GLvoid * binary, GLsizei length)
References __FUNCTION__, _mesa_error(), _mesa_lookup_shader_program_err(), and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ProgramParameteri (GLuint program, GLenum pname, GLint value)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_lookup_enum_by_nr(), _mesa_lookup_shader_program_err(), gl_shader_program::BinaryRetreivableHint, gl_shader_program::Geom, gl_shader_program::InputType, gl_shader_program::OutputType, and gl_shader_program::VerticesOut.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ReleaseShaderCompiler (void)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ShaderBinary (GLint n, const GLuint * shaders, GLenum binaryformat, const void * binary, GLint length)
For OpenGL ES 2.0, GL_ARB_ES2_compatibility.
References __FUNCTION__, _mesa_error(), and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ShaderSource (GLhandleARB shaderObj, GLsizei count, const GLcharARB *const * string, const GLint * length)
Called via glShaderSource() and glShaderSourceARB() API functions.
Basically, concatenate the source code strings into one long string and pass it to _mesa_shader_source().
References _mesa_error(), _mesa_lookup_shader(), _mesa_snprintf(), _mesa_str_checksum(), NULL, read_shader(), shader_source(), SHADER_SUBST, and gl_shader::SourceChecksum.
Referenced by _mesa_initialize_exec_table().
void _mesa_use_program (struct gl_context * ctx, struct gl_shader_program * shProg)
Use the named shader program for subsequent rendering.
References _mesa_active_program(), gl_context::Driver, use_shader_program(), and dd_function_table::UseProgram.
Referenced by _mesa_UseProgram().
void _mesa_use_shader_program (struct gl_context * ctx, GLenum type, struct gl_shader_program * shProg)
References gl_context::Driver, use_shader_program(), and dd_function_table::UseProgram.
Referenced by _mesa_UseShaderProgramEXT().
void GLAPIENTRY _mesa_UseProgram (GLhandleARB program)
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_shader_program_err(), _mesa_use_program(), GLSL_USE_PROG, gl_shader_program::LinkStatus, NULL, and print_shader_info().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UseShaderProgramEXT (GLenum type, GLuint program)
For GL_EXT_separate_shader_objects.
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_shader_program_err(), _mesa_use_shader_program(), gl_shader_program::LinkStatus, NULL, and validate_shader_target().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ValidateProgram (GLhandleARB program)
References validate_program().
Referenced by _mesa_initialize_exec_table().
static void attach_shader (struct gl_context * ctx, GLuint program, GLuint shader) static
Attach shader to a shader program.
References _mesa_error(), _mesa_is_gles(), _mesa_lookup_shader_err(), _mesa_lookup_shader_program_err(), _mesa_realloc(), _mesa_reference_shader(), NULL, gl_shader_program::NumShaders, gl_shader_program::Shaders, and gl_shader::Type.
Referenced by _mesa_AttachObjectARB(), _mesa_AttachShader(), and _mesa_CreateShaderProgramEXT().
static void compile_shader (struct gl_context * ctx, GLuint shaderObj) static
Compile a shader.
References _mesa_debug(), _mesa_lookup_shader_err(), _mesa_shader_type_to_index(), gl_shader::CompileStatus, gl_shader_compiler_options::DefaultPragmas, gl_shader_state::Flags, GLSL_REPORT_ERRORS, gl_shader::InfoLog, gl_shader::Name, gl_shader::Pragmas, gl_context::Shader, gl_context::ShaderCompilerOptions, and gl_shader::Type.
Referenced by _mesa_CompileShader(), and _mesa_CreateShaderProgramEXT().
static GLuint create_shader (struct gl_context * ctx, GLenum type) static
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), gl_context::Driver, dd_function_table::NewShader, gl_shared_state::ShaderObjects, gl_context::Shared, and validate_shader_target().
Referenced by _mesa_CreateShader(), _mesa_CreateShaderObjectARB(), and _mesa_CreateShaderProgramEXT().
static GLuint create_shader_program (struct gl_context * ctx) static
References _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), gl_context::Driver, dd_function_table::NewShaderProgram, gl_shader_program::RefCount, gl_shared_state::ShaderObjects, and gl_context::Shared.
Referenced by _mesa_CreateProgram(), _mesa_CreateProgramObjectARB(), and _mesa_CreateShaderProgramEXT().
static void delete_shader (struct gl_context * ctx, GLuint shader) static
References _mesa_lookup_shader_err(), _mesa_reference_shader(), gl_shader::DeletePending, and NULL.
Referenced by _mesa_CreateShaderProgramEXT(), _mesa_DeleteObjectARB(), and _mesa_DeleteShader().
static void delete_shader_program (struct gl_context * ctx, GLuint name) static
Named w/ "2" to indicate OpenGL 2.x vs GL_ARB_fragment_programs's DeleteProgramARB.
References _mesa_lookup_shader_program_err(), _mesa_reference_shader_program(), gl_shader_program::DeletePending, and NULL.
Referenced by _mesa_DeleteObjectARB(), and _mesa_DeleteProgram().
static void detach_shader (struct gl_context * ctx, GLuint program, GLuint shader) static
References _mesa_error(), _mesa_lookup_shader_program_err(), _mesa_reference_shader(), is_program(), is_shader(), gl_shader::Name, NULL, gl_shader_program::NumShaders, gl_shader::RefCount, gl_shader_program::Shaders, and gl_shader::Type.
Referenced by _mesa_CreateShaderProgramEXT(), _mesa_DetachObjectARB(), and _mesa_DetachShader().
static void get_attached_shaders (struct gl_context * ctx, GLuint program, GLsizei maxCount, GLsizei * count, GLuint * obj) static
Return list of shaders attached to shader program.
References _mesa_lookup_shader_program_err(), gl_shader::Name, gl_shader_program::NumShaders, and gl_shader_program::Shaders.
Referenced by _mesa_GetAttachedObjectsARB(), and _mesa_GetAttachedShaders().
static GLuint get_handle (struct gl_context * ctx, GLenum pname) static
glGetHandleARB() - return ID/name of currently bound shader program.
References _mesa_error(), gl_shader_state::ActiveProgram, gl_shader_program::Name, and gl_context::Shader.
Referenced by _mesa_GetHandleARB().
static void get_program_info_log (struct gl_context * ctx, GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog) static
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader_program(), and gl_shader_program::InfoLog.
Referenced by _mesa_GetInfoLogARB(), and _mesa_GetProgramInfoLog().
static void get_programiv (struct gl_context * ctx, GLuint program, GLenum pname, GLint * params) static
glGetProgramiv() - get shader program state.
Note that this is for GLSL shader programs, not ARB vertex/fragment programs (see glGetProgramivARB).
References _mesa_count_active_attribs(), _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_longest_attribute_name_length(), _mesa_lookup_enum_by_nr(), _mesa_lookup_shader_program(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, gl_extensions::ARB_geometry_shader4, gl_extensions::ARB_uniform_buffer_object, gl_shader_program::BinaryRetreivableHint, gl_shader_program::BufferMode, gl_shader_program::DeletePending, gl_extensions::EXT_transform_feedback, gl_context::Extensions, gl_shader_program::Geom, gl_shader_program::InfoLog, gl_shader_program::InputType, gl_shader_program::LinkStatus, gl_uniform_block::Name, gl_shader_program::NumShaders, gl_shader_program::NumUniformBlocks, gl_shader_program::NumUserUniformStorage, gl_shader_program::NumVarying, gl_shader_program::OutputType, gl_shader_program::TransformFeedback, gl_shader_program::UniformBlocks, gl_shader_program::UniformStorage, gl_shader_program::Validated, gl_shader_program::VaryingNames, and gl_shader_program::VerticesOut.
Referenced by _mesa_GetObjectParameterivARB(), and _mesa_GetProgramiv().
static GLbitfield get_shader_flags (void) static
Return mask of GLSL_x flags by examining the MESA_GLSL env var.
References _mesa_getenv(), GLbitfield, GLSL_DUMP, GLSL_LOG, GLSL_NO_OPT, GLSL_NOP_FRAG, GLSL_NOP_VERT, GLSL_OPT, GLSL_REPORT_ERRORS, GLSL_UNIFORMS, and GLSL_USE_PROG.
Referenced by _mesa_init_shader_state().
static void get_shader_info_log (struct gl_context * ctx, GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog) static
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader(), and gl_shader::InfoLog.
Referenced by _mesa_GetInfoLogARB(), and _mesa_GetShaderInfoLog().
static void get_shader_source (struct gl_context * ctx, GLuint shader, GLsizei maxLength, GLsizei * length, GLchar * sourceOut) static
Return shader source code.
References _mesa_copy_string(), _mesa_lookup_shader_err(), and gl_shader::Source.
Referenced by _mesa_GetShaderSource().
static void get_shaderiv (struct gl_context * ctx, GLuint name, GLenum pname, GLint * params) static
glGetShaderiv() - get GLSL shader state
References _mesa_error(), _mesa_lookup_shader_err(), gl_shader::CompileStatus, gl_shader::DeletePending, gl_shader::InfoLog, gl_shader::Source, and gl_shader::Type.
Referenced by _mesa_CreateShaderProgramEXT(), _mesa_GetObjectParameterivARB(), and _mesa_GetShaderiv().
static GLboolean is_program (struct gl_context * ctx, GLuint name) static
References _mesa_lookup_shader_program().
Referenced by _mesa_DeleteObjectARB(), _mesa_GetInfoLogARB(), _mesa_GetObjectParameterivARB(), _mesa_IsProgram(), and detach_shader().
static GLboolean is_shader (struct gl_context * ctx, GLuint name) static
References _mesa_lookup_shader().
Referenced by _mesa_DeleteObjectARB(), _mesa_GetInfoLogARB(), _mesa_GetObjectParameterivARB(), _mesa_IsShader(), and detach_shader().
static void link_program (struct gl_context * ctx, GLuint program) static
Link a program's shaders.
References _mesa_debug(), _mesa_error(), _mesa_lookup_shader_program_err(), _NEW_PROGRAM, gl_transform_feedback_object::Active, gl_shader_state::CurrentFragmentProgram, gl_shader_state::CurrentGeometryProgram, gl_transform_feedback_state::CurrentObject, gl_shader_state::CurrentVertexProgram, gl_shader_state::Flags, FLUSH_VERTICES, GLSL_REPORT_ERRORS, gl_shader_program::InfoLog, gl_shader_program::LinkStatus, gl_shader::Name, gl_shader_program::Name, gl_shader_program::NumShaders, gl_context::Shader, gl_shader_program::Shaders, gl_context::TransformFeedback, and gl_shader::Type.
Referenced by _mesa_CreateShaderProgramEXT(), and _mesa_LinkProgram().
static void print_shader_info (const struct gl_shader_program * shProg) static
Print basic shader info (for debug).
References gl_shader_program::_LinkedShaders, gl_program::Id, MESA_SHADER_FRAGMENT, MESA_SHADER_GEOMETRY, MESA_SHADER_VERTEX, gl_shader::Name, gl_shader_program::Name, gl_shader_program::NumShaders, gl_shader::Program, gl_shader_program::Shaders, gl_shader::SourceChecksum, and gl_shader::Type.
Referenced by _mesa_UseProgram().
static GLcharARB* read_shader (const char * fname) static
Read shader source code from a file.
Useful for debugging to override an app's shader.
References _mesa_strdup(), and NULL.
Referenced by _mesa_ShaderSource().
static void shader_source (struct gl_context * ctx, GLuint shader, const GLchar * source) static
Set/replace shader source code.
A helper function used by glShaderSource[ARB] and glCreateShaderProgramEXT.
References _mesa_lookup_shader_err(), _mesa_str_checksum(), gl_shader::CompileStatus, gl_shader::Source, and gl_shader::SourceChecksum.
Referenced by _mesa_CreateShaderProgramEXT(), and _mesa_ShaderSource().
static bool use_shader_program (struct gl_context * ctx, GLenum type, struct gl_shader_program * shProg) static
References gl_shader_state::_CurrentFragmentProgram, gl_shader_program::_LinkedShaders, _mesa_reference_shader_program(), _NEW_PROGRAM, _NEW_PROGRAM_CONSTANTS, gl_shader_state::CurrentFragmentProgram, gl_shader_state::CurrentGeometryProgram, gl_shader_state::CurrentVertexProgram, FLUSH_VERTICES, MESA_SHADER_FRAGMENT, MESA_SHADER_GEOMETRY, MESA_SHADER_VERTEX, NULL, and gl_context::Shader.
Referenced by _mesa_use_program(), and _mesa_use_shader_program().
static void validate_program (struct gl_context * ctx, GLuint program) static
Called via glValidateProgram()
References _mesa_lookup_shader_program_err(), gl_shader_program::InfoLog, validate_shader_program(), and gl_shader_program::Validated.
Referenced by _mesa_ValidateProgram().
static GLboolean validate_shader_program (const struct gl_shader_program * shProg, char * errMsg) static
Do validation of the given shader program.
Parameters
errMsg returns error message if validation fails.
Returns
GL_TRUE if valid, GL_FALSE if invalid (and set errMsg)
References _mesa_sampler_uniforms_are_valid(), and gl_shader_program::LinkStatus.
Referenced by validate_program().
static bool validate_shader_target (const struct gl_context * ctx, GLenum type) static
Confirm that the a shader type is valid and supported by the implementation.
Parameters
ctx Current GL context
type Shader target
References _mesa_is_desktop_gl(), gl_extensions::ARB_fragment_shader, gl_extensions::ARB_geometry_shader4, gl_extensions::ARB_vertex_shader, and gl_context::Extensions.
Referenced by _mesa_UseShaderProgramEXT(), and create_shader().