Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
state.c File Reference
State management.
#include "glheader.h"
#include "mtypes.h"
#include "arrayobj.h"
#include "context.h"
#include "debug.h"
#include "macros.h"
#include "ffvertex_prog.h"
#include "framebuffer.h"
#include "light.h"
#include "matrix.h"
#include "pixel.h"
#include "program/program.h"
#include "program/prog_parameter.h"
#include "shaderobj.h"
#include "state.h"
#include "stencil.h"
#include "texenvprogram.h"
#include "texobj.h"
#include "texstate.h"
#include "varray.h"
#include "blend.h"
Functions
static void update_program_enables (struct gl_context *ctx)
Update the following fields: ctx->VertexProgram._Enabled ctx->FragmentProgram._Enabled ctx->ATIFragmentShader._Enabled This needs to be done before texture state validation.
static GLbitfield update_program (struct gl_context *ctx)
Update the ctx->Vertex/Geometry/FragmentProgram._Current pointers to point to the current/active programs.
static GLbitfield update_program_constants (struct gl_context *ctx)
Examine shader constants and return either _NEW_PROGRAM_CONSTANTS or 0.
static void update_viewport_matrix (struct gl_context *ctx)
static void update_multisample (struct gl_context *ctx)
Update derived multisample state.
static void update_twoside (struct gl_context *ctx)
Update the ctx->VertexProgram._TwoSideEnabled flag.
void _mesa_update_state_locked (struct gl_context *ctx)
Compute derived GL state.
void _mesa_update_state (struct gl_context *ctx)
void _mesa_set_varying_vp_inputs (struct gl_context *ctx, GLbitfield64 varying_inputs)
Want to figure out which fragment program inputs are actually constant/current values from ctx->Current.
void _mesa_set_vp_override (struct gl_context *ctx, GLboolean flag)
Used by drivers to tell core Mesa that the driver is going to install/ use its own vertex program.
Detailed Description
State management.
This file manages recalculation of derived values in struct gl_context.
Function Documentation
void _mesa_set_varying_vp_inputs (struct gl_context * ctx, GLbitfield64 varying_inputs)
Want to figure out which fragment program inputs are actually constant/current values from ctx->Current.
These should be referenced as a tracked state variable rather than a fragment program input, to save the overhead of putting a constant value in every submitted vertex, transferring it to hardware, interpolating it across the triangle, etc...
When there is a VP bound, just use vp->outputs. But when we're generating vp from fixed function state, basically want to calculate:
vp_out_2_fp_in(vp_in_2_vp_out(varying_inputs) | potential_vp_outputs)
Where potential_vp_outputs is calculated by looking at enabled texgen, etc.
The generated fragment program should then only declare inputs that may vary or otherwise differ from the ctx->Current values. Otherwise, the fp should track them as state values instead.
References _NEW_VARYING_VP_INPUTS, gl_fragment_program_state::_TexEnvProgram, gl_vertex_program_state::_TnlProgram, gl_context::FragmentProgram, gl_context::NewState, gl_context::varying_vp_inputs, and gl_context::VertexProgram.
void _mesa_set_vp_override (struct gl_context * ctx, GLboolean flag)
Used by drivers to tell core Mesa that the driver is going to install/ use its own vertex program.
In particular, this will prevent generated fragment programs from using state vars instead of ordinary varyings/inputs.
References _NEW_PROGRAM, gl_vertex_program_state::_Overriden, gl_context::NewState, and gl_context::VertexProgram.
Referenced by _mesa_CopyPixels(), _mesa_DrawPixels(), and draw_texture().
void _mesa_update_state (struct gl_context * ctx)
References _mesa_lock_context_textures(), _mesa_unlock_context_textures(), and _mesa_update_state_locked().
Referenced by _mesa_Accum(), _mesa_BlitFramebuffer(), _mesa_Clear(), _mesa_ClearBufferfi(), _mesa_ClearBufferfv(), _mesa_ClearBufferiv(), _mesa_ClearBufferuiv(), _mesa_EGLImageTargetTexture2DOES(), _mesa_GetMultisamplefv(), _mesa_GetTexEnvfv(), _mesa_ReadnPixelsARB(), _mesa_readpixels(), _mesa_valid_to_render(), check_extra(), copyteximage(), copytexsubimage(), draw_texture(), rasterpos(), teximage(), and texsubimage().
void _mesa_update_state_locked (struct gl_context * ctx)
Compute derived GL state.
If __struct gl_contextRec::NewState is non-zero then this function must be called before rendering anything.
Calls dd_function_table::UpdateState to perform any internal state management necessary.
See Also
_mesa_update_modelview_project(), _mesa_update_texture(), _mesa_update_buffer_bounds(), _mesa_update_lighting() and _mesa_update_tnl_spaces().
References gl_fragment_program_state::_MaintainTexEnvProgram, gl_vertex_program_state::_MaintainTnlProgram, _MESA_NEW_NEED_EYE_COORDS, _mesa_print_state(), _mesa_update_array_object_max_element(), _mesa_update_draw_buffer_bounds(), _mesa_update_framebuffer(), _mesa_update_lighting(), _mesa_update_modelview_project(), _mesa_update_pixel(), _mesa_update_stencil(), _mesa_update_texture(), _mesa_update_tnl_spaces(), _NEW_ARRAY, _NEW_BUFFER_OBJECT, _NEW_BUFFERS, _NEW_COLOR, _NEW_CURRENT_ATTRIB, _NEW_FOG, _NEW_FRAG_CLAMP, _NEW_LIGHT, _NEW_MODELVIEW, _NEW_MULTISAMPLE, _NEW_PIXEL, _NEW_POINT, _NEW_PROGRAM, _NEW_PROJECTION, _NEW_RENDERMODE, _NEW_SCISSOR, _NEW_STENCIL, _NEW_TEXTURE, _NEW_TEXTURE_MATRIX, _NEW_TRANSFORM, _NEW_VARYING_VP_INPUTS, _NEW_VIEWPORT, gl_context::Array, gl_array_attrib::ArrayObj, gl_constants::CheckArrayBounds, gl_context::Const, gl_context::Driver, gl_context::FragmentProgram, GLbitfield, MESA_VERBOSE, gl_context::NewState, update_multisample(), update_program(), update_program_constants(), update_program_enables(), update_twoside(), update_viewport_matrix(), dd_function_table::UpdateState, VERBOSE_STATE, and gl_context::VertexProgram.
Referenced by _mesa_GetTexParameterfv(), and _mesa_update_state().
static void update_multisample (struct gl_context * ctx) static
Update derived multisample state.
References gl_multisample_attrib::_Enabled, gl_context::DrawBuffer, gl_multisample_attrib::Enabled, gl_context::Multisample, gl_config::sampleBuffers, and gl_framebuffer::Visual.
Referenced by _mesa_update_state_locked().
static GLbitfield update_program (struct gl_context * ctx) static
Update the ctx->Vertex/Geometry/FragmentProgram._Current pointers to point to the current/active programs.
Then call ctx->Driver.BindProgram() to tell the driver which programs to use.
Programs may come from 3 sources: GLSL shaders, ARB/NV_vertex/fragment programs or programs derived from fixed-function state.
This function needs to be called after texture state validation in case we're generating a fragment program from fixed-function texture state.
Returns
bitfield which will indicate _NEW_PROGRAM state if a new vertex or fragment program is being used.
References gl_vertex_program_state::_Current, gl_geometry_program_state::_Current, gl_fragment_program_state::_Current, gl_shader_state::_CurrentFragmentProgram, gl_vertex_program_state::_Enabled, gl_fragment_program_state::_Enabled, gl_shader_program::_LinkedShaders, gl_fragment_program_state::_MaintainTexEnvProgram, gl_vertex_program_state::_MaintainTnlProgram, _mesa_get_fixed_func_fragment_program(), _mesa_get_fixed_func_vertex_program(), _mesa_reference_shader_program(), _NEW_PROGRAM, gl_fragment_program_state::_TexEnvProgram, gl_vertex_program_state::_TnlProgram, dd_function_table::BindProgram, gl_vertex_program_state::Current, gl_fragment_program_state::Current, gl_shader_state::CurrentFragmentProgram, gl_shader_state::CurrentGeometryProgram, gl_shader_state::CurrentVertexProgram, gl_context::Driver, gl_context::FragmentProgram, gl_context::GeometryProgram, GLbitfield, gl_shader_program::LinkStatus, MESA_GEOMETRY_PROGRAM, MESA_SHADER_FRAGMENT, MESA_SHADER_GEOMETRY, MESA_SHADER_VERTEX, NULL, gl_shader::Program, gl_context::Shader, and gl_context::VertexProgram.
Referenced by _mesa_update_state_locked().
static GLbitfield update_program_constants (struct gl_context * ctx) static
Examine shader constants and return either _NEW_PROGRAM_CONSTANTS or 0.
References gl_vertex_program_state::_Current, gl_geometry_program_state::_Current, gl_fragment_program_state::_Current, _NEW_PROGRAM_CONSTANTS, gl_vertex_program::Base, gl_geometry_program::Base, gl_fragment_program::Base, gl_context::FragmentProgram, gl_context::GeometryProgram, GLbitfield, gl_context::NewState, gl_program::Parameters, and gl_context::VertexProgram.
Referenced by _mesa_update_state_locked().
static void update_program_enables (struct gl_context * ctx) static
Update the following fields: ctx->VertexProgram._Enabled ctx->FragmentProgram._Enabled ctx->ATIFragmentShader._Enabled This needs to be done before texture state validation.
References gl_vertex_program_state::_Enabled, gl_fragment_program_state::_Enabled, gl_ati_fragment_shader_state::_Enabled, gl_context::ATIFragmentShader, gl_vertex_program::Base, gl_fragment_program::Base, gl_vertex_program_state::Current, gl_fragment_program_state::Current, gl_ati_fragment_shader_state::Current, gl_vertex_program_state::Enabled, gl_fragment_program_state::Enabled, gl_ati_fragment_shader_state::Enabled, gl_context::FragmentProgram, gl_program::Instructions, ati_fragment_shader::Instructions, and gl_context::VertexProgram.
Referenced by _mesa_update_state_locked().
static void update_twoside (struct gl_context * ctx) static
Update the ctx->VertexProgram._TwoSideEnabled flag.
References gl_vertex_program_state::_Enabled, gl_vertex_program_state::_TwoSideEnabled, gl_shader_state::CurrentVertexProgram, gl_light_attrib::Enabled, gl_context::Light, gl_light_attrib::Model, gl_context::Shader, gl_lightmodel::TwoSide, gl_vertex_program_state::TwoSideEnabled, and gl_context::VertexProgram.
Referenced by _mesa_update_state_locked().
static void update_viewport_matrix (struct gl_context * ctx) static
References gl_framebuffer::_DepthMaxF, _math_matrix_viewport(), gl_viewport_attrib::_WindowMap, ASSERT, gl_context::DrawBuffer, gl_viewport_attrib::Far, gl_viewport_attrib::Height, gl_viewport_attrib::Near, gl_context::Viewport, gl_viewport_attrib::Width, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
Referenced by _mesa_update_state_locked().