Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
dd_function_table Struct Reference
Device driver function table.
#include <dd.h>
Data Fields
const GLubyte *(* GetString)(struct gl_context *ctx, GLenum name)
Return a string as needed by glGetString().
void(* UpdateState)(struct gl_context *ctx, GLbitfield new_state)
Notify the driver after Mesa has made some internal state changes.
void(* GetBufferSize)(struct gl_framebuffer *buffer, GLuint *width, GLuint *height)
Get the width and height of the named buffer/window.
void(* ResizeBuffers)(struct gl_context *ctx, struct gl_framebuffer *fb, GLuint width, GLuint height)
Resize the given framebuffer to the given size.
void(* Finish)(struct gl_context *ctx)
This is called whenever glFinish() is called.
void(* Flush)(struct gl_context *ctx)
This is called whenever glFlush() is called.
void(* Clear)(struct gl_context *ctx, GLbitfield buffers)
Clear the color/depth/stencil/accum buffer(s).
void(* Accum)(struct gl_context *ctx, GLenum op, GLfloat value)
Execute glAccum command.
void(* RasterPos)(struct gl_context *ctx, const GLfloat v[4])
Execute glRasterPos, updating the ctx->Current.Raster fields.
void(* BlitFramebuffer)(struct gl_context *ctx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
void(* DiscardFramebuffer)(struct gl_context *ctx, GLenum target, GLsizei numAttachments, const GLenum *attachments)
void(* BeginConditionalRender)(struct gl_context *ctx, struct gl_query_object *q, GLenum mode)
GL_NV_conditional_render.
void(* EndConditionalRender)(struct gl_context *ctx, struct gl_query_object *q)
Image-related functions
void(* DrawPixels)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Called by glDrawPixels().
void(* ReadPixels)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, GLvoid *dest)
Called by glReadPixels().
void(* CopyPixels)(struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint dstx, GLint dsty, GLenum type)
Called by glCopyPixels().
void(* Bitmap)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
Called by glBitmap().
Texture image functions
gl_format(* ChooseTextureFormat)(struct gl_context *ctx, GLenum target, GLint internalFormat, GLenum srcFormat, GLenum srcType)
Choose actual hardware texture format given the texture target, the user-provided source image format and type and the desired internal format.
size_t(* QuerySamplesForFormat)(struct gl_context *ctx, GLenum target, GLenum internalFormat, int samples[16])
Determine sample counts support for a particular target and format.
void(* TexImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexImage[123]D() and glCopyTexImage[12]D() Allocate texture memory and copy the user's image to the buffer.
void(* TexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexSubImage[123]D().
void(* GetTexImage)(struct gl_context *ctx, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
Called by glGetTexImage().
void(* CopyTexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height)
Called by glCopyTex[Sub]Image[123]D().
void(* GenerateMipmap)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj)
Called by glGenerateMipmap() or when GL_GENERATE_MIPMAP_SGIS is enabled.
GLboolean(* TestProxyTexImage)(struct gl_context *ctx, GLenum target, GLint level, gl_format format, GLint width, GLint height, GLint depth, GLint border)
Called by glTexImage, glCompressedTexImage, glCopyTexImage and glTexStorage to check if the dimensions of the texture image are too large.
Compressed texture functions
void(* CompressedTexImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexImage[123]D().
void(* CompressedTexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLint height, GLint depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexSubImage[123]D().
void(* GetCompressedTexImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLvoid *data)
Called by glGetCompressedTexImage.
Texture object / image functions
void(* BindTexture)(struct gl_context *ctx, GLenum target, struct gl_texture_object *tObj)
Called by glBindTexture().
struct gl_texture_object *(* NewTextureObject)(struct gl_context *ctx, GLuint name, GLenum target)
Called to allocate a new texture object.
void(* DeleteTexture)(struct gl_context *ctx, struct gl_texture_object *texObj)
Called to delete/free a texture object.
struct gl_texture_image *(* NewTextureImage)(struct gl_context *ctx)
Called to allocate a new texture image object.
void(* DeleteTextureImage)(struct gl_context *ctx, struct gl_texture_image *)
Called to free a texture image object returned by NewTextureImage()
GLboolean(* AllocTextureImageBuffer)(struct gl_context *ctx, struct gl_texture_image *texImage)
Called to allocate memory for a single texture image.
void(* FreeTextureImageBuffer)(struct gl_context *ctx, struct gl_texture_image *texImage)
Free the memory for a single texture image.
void(* MapTextureImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a slice of a texture image into user space.
void(* UnmapTextureImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice)
GLboolean(* AllocTextureStorage)(struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
For GL_ARB_texture_storage.
void(* MapRenderbuffer)(struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a renderbuffer into user space.
void(* UnmapRenderbuffer)(struct gl_context *ctx, struct gl_renderbuffer *rb)
Vertex/fragment program functions
void(* BindProgram)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Bind a vertex/fragment program.
struct gl_program *(* NewProgram)(struct gl_context *ctx, GLenum target, GLuint id)
Allocate a new program.
void(* DeleteProgram)(struct gl_context *ctx, struct gl_program *prog)
Delete a program.
GLboolean(* ProgramStringNotify)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that a program string (and GPU code) has been specified or modified.
void(* SamplerUniformChange)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that the sampler uniforms for the current program have changed.
GLboolean(* IsProgramNative)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Query if program can be loaded onto hardware.
GLSL shader/program functions.
GLboolean(* LinkShader)(struct gl_context *ctx, struct gl_shader_program *shader)
Called when a shader program is linked.
State-changing functions.
Note
drawing functions are above.
These functions are called by their corresponding OpenGL API functions. They are also called by the gl_PopAttrib() function!!! May add more functions like these to the device driver in the future.
void(* AlphaFunc)(struct gl_context *ctx, GLenum func, GLfloat ref)
Specify the alpha test function.
void(* BlendColor)(struct gl_context *ctx, const GLfloat color[4])
Set the blend color.
void(* BlendEquationSeparate)(struct gl_context *ctx, GLenum modeRGB, GLenum modeA)
Set the blend equation.
void(* BlendEquationSeparatei)(struct gl_context *ctx, GLuint buffer, GLenum modeRGB, GLenum modeA)
void(* BlendFuncSeparate)(struct gl_context *ctx, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Specify pixel arithmetic.
void(* BlendFuncSeparatei)(struct gl_context *ctx, GLuint buffer, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
void(* ClipPlane)(struct gl_context *ctx, GLenum plane, const GLfloat *equation)
Specify a plane against which all geometry is clipped.
void(* ColorMask)(struct gl_context *ctx, GLboolean rmask, GLboolean gmask, GLboolean bmask, GLboolean amask)
Enable and disable writing of frame buffer color components.
void(* ColorMaskIndexed)(struct gl_context *ctx, GLuint buf, GLboolean rmask, GLboolean gmask, GLboolean bmask, GLboolean amask)
void(* ColorMaterial)(struct gl_context *ctx, GLenum face, GLenum mode)
Cause a material color to track the current color.
void(* CullFace)(struct gl_context *ctx, GLenum mode)
Specify whether front- or back-facing facets can be culled.
void(* FrontFace)(struct gl_context *ctx, GLenum mode)
Define front- and back-facing polygons.
void(* DepthFunc)(struct gl_context *ctx, GLenum func)
Specify the value used for depth buffer comparisons.
void(* DepthMask)(struct gl_context *ctx, GLboolean flag)
Enable or disable writing into the depth buffer.
void(* DepthRange)(struct gl_context *ctx, GLclampd nearval, GLclampd farval)
Specify mapping of depth values from NDC to window coordinates.
void(* DrawBuffer)(struct gl_context *ctx, GLenum buffer)
Specify the current buffer for writing.
void(* DrawBuffers)(struct gl_context *ctx, GLsizei n, const GLenum *buffers)
Specify the buffers for writing for fragment programs.
void(* Enable)(struct gl_context *ctx, GLenum cap, GLboolean state)
Enable or disable server-side gl capabilities.
void(* Fogfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
Specify fog parameters.
void(* Hint)(struct gl_context *ctx, GLenum target, GLenum mode)
Specify implementation-specific hints.
void(* Lightfv)(struct gl_context *ctx, GLenum light, GLenum pname, const GLfloat *params)
Set light source parameters.
void(* LightModelfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
Set the lighting model parameters.
void(* LineStipple)(struct gl_context *ctx, GLint factor, GLushort pattern)
Specify the line stipple pattern.
void(* LineWidth)(struct gl_context *ctx, GLfloat width)
Specify the width of rasterized lines.
void(* LogicOpcode)(struct gl_context *ctx, GLenum opcode)
Specify a logical pixel operation for color index rendering.
void(* PointParameterfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
void(* PointSize)(struct gl_context *ctx, GLfloat size)
Specify the diameter of rasterized points.
void(* PolygonMode)(struct gl_context *ctx, GLenum face, GLenum mode)
Select a polygon rasterization mode.
void(* PolygonOffset)(struct gl_context *ctx, GLfloat factor, GLfloat units)
Set the scale and units used to calculate depth values.
void(* PolygonStipple)(struct gl_context *ctx, const GLubyte *mask)
Set the polygon stippling pattern.
void(* ReadBuffer)(struct gl_context *ctx, GLenum buffer)
void(* RenderMode)(struct gl_context *ctx, GLenum mode)
Set rasterization mode.
void(* Scissor)(struct gl_context *ctx, GLint x, GLint y, GLsizei w, GLsizei h)
Define the scissor box.
void(* ShadeModel)(struct gl_context *ctx, GLenum mode)
Select flat or smooth shading.
void(* StencilFuncSeparate)(struct gl_context *ctx, GLenum face, GLenum func, GLint ref, GLuint mask)
OpenGL 2.0 two-sided StencilFunc.
void(* StencilMaskSeparate)(struct gl_context *ctx, GLenum face, GLuint mask)
OpenGL 2.0 two-sided StencilMask.
void(* StencilOpSeparate)(struct gl_context *ctx, GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
OpenGL 2.0 two-sided StencilOp.
void(* TexGen)(struct gl_context *ctx, GLenum coord, GLenum pname, const GLfloat *params)
Control the generation of texture coordinates.
void(* TexEnv)(struct gl_context *ctx, GLenum target, GLenum pname, const GLfloat *param)
Set texture environment parameters.
void(* TexParameter)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, GLenum pname, const GLfloat *params)
Set texture parameters.
void(* Viewport)(struct gl_context *ctx, GLint x, GLint y, GLsizei w, GLsizei h)
Set the viewport.
Vertex/pixel buffer object functions
void(* BindBuffer)(struct gl_context *ctx, GLenum target, struct gl_buffer_object *obj)
struct gl_buffer_object *(* NewBufferObject)(struct gl_context *ctx, GLuint buffer, GLenum target)
void(* DeleteBuffer)(struct gl_context *ctx, struct gl_buffer_object *obj)
GLboolean(* BufferData)(struct gl_context *ctx, GLenum target, GLsizeiptrARB size, const GLvoid *data, GLenum usage, struct gl_buffer_object *obj)
void(* BufferSubData)(struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid *data, struct gl_buffer_object *obj)
void(* GetBufferSubData)(struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid *data, struct gl_buffer_object *obj)
void(* CopyBufferSubData)(struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
void *(* MapBufferRange)(struct gl_context *ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object *obj)
void(* FlushMappedBufferRange)(struct gl_context *ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object *obj)
GLboolean(* UnmapBuffer)(struct gl_context *ctx, struct gl_buffer_object *obj)
Functions for GL_APPLE_object_purgeable
GLenum(* BufferObjectPurgeable)(struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
GLenum(* RenderObjectPurgeable)(struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
GLenum(* TextureObjectPurgeable)(struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
GLenum(* BufferObjectUnpurgeable)(struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
GLenum(* RenderObjectUnpurgeable)(struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
GLenum(* TextureObjectUnpurgeable)(struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
Functions for GL_EXT_framebuffer_{object,blit,discard}.
struct gl_framebuffer *(* NewFramebuffer)(struct gl_context *ctx, GLuint name)
struct gl_renderbuffer *(* NewRenderbuffer)(struct gl_context *ctx, GLuint name)
void(* BindFramebuffer)(struct gl_context *ctx, GLenum target, struct gl_framebuffer *drawFb, struct gl_framebuffer *readFb)
void(* FramebufferRenderbuffer)(struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
void(* RenderTexture)(struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
void(* FinishRenderTexture)(struct gl_context *ctx, struct gl_renderbuffer *rb)
void(* ValidateFramebuffer)(struct gl_context *ctx, struct gl_framebuffer *fb)
Query objects
struct gl_query_object *(* NewQueryObject)(struct gl_context *ctx, GLuint id)
void(* DeleteQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* BeginQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* QueryCounter)(struct gl_context *ctx, struct gl_query_object *q)
void(* EndQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* CheckQuery)(struct gl_context *ctx, struct gl_query_object *q)
void(* WaitQuery)(struct gl_context *ctx, struct gl_query_object *q)
Vertex Array objects
struct gl_array_object *(* NewArrayObject)(struct gl_context *ctx, GLuint id)
void(* DeleteArrayObject)(struct gl_context *ctx, struct gl_array_object *obj)
void(* BindArrayObject)(struct gl_context *ctx, struct gl_array_object *obj)
GLSL-related functions (ARB extensions and OpenGL 2.x)
struct gl_shader *(* NewShader)(struct gl_context *ctx, GLuint name, GLenum type)
void(* DeleteShader)(struct gl_context *ctx, struct gl_shader *shader)
struct gl_shader_program *(* NewShaderProgram)(struct gl_context *ctx, GLuint name)
void(* DeleteShaderProgram)(struct gl_context *ctx, struct gl_shader_program *shProg)
void(* UseProgram)(struct gl_context *ctx, struct gl_shader_program *shProg)
Support for multiple T&L engines
GLuint CurrentExecPrimitive
Set by the driver-supplied T&L engine.
GLuint CurrentSavePrimitive
Current glBegin state of an in-progress compilation.
GLbitfield NeedFlush
Set by the driver-supplied T&L engine whenever vertices are buffered between glBegin()/glEnd() objects or __struct gl_contextRec::Current is not updated.
GLboolean SaveNeedFlush
Need to call SaveFlushVertices() upon state change?
void(* BeginVertices)(struct gl_context *ctx)
void(* FlushVertices)(struct gl_context *ctx, GLuint flags)
If inside glBegin()/glEnd(), it should ASSERT(0).
void(* SaveFlushVertices)(struct gl_context *ctx)
GLboolean(* NotifySaveBegin)(struct gl_context *ctx, GLenum mode)
Give the driver the opportunity to hook in its own vtxfmt for compiling optimized display lists.
void(* LightingSpaceChange)(struct gl_context *ctx)
Notify driver that the special derived value _NeedEyeCoords has changed.
void(* NewList)(struct gl_context *ctx, GLuint list, GLenum mode)
Called by glNewList().
void(* EndList)(struct gl_context *ctx)
Called by glEndList().
void(* BeginCallList)(struct gl_context *ctx, struct gl_display_list *dlist)
Called by glCallList(s).
void(* EndCallList)(struct gl_context *ctx)
Called by glEndCallList().
GL_ARB_sync interfaces
struct gl_sync_object *(* NewSyncObject)(struct gl_context *, GLenum)
void(* FenceSync)(struct gl_context *, struct gl_sync_object *, GLenum, GLbitfield)
void(* DeleteSyncObject)(struct gl_context *, struct gl_sync_object *)
void(* CheckSync)(struct gl_context *, struct gl_sync_object *)
void(* ClientWaitSync)(struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
void(* ServerWaitSync)(struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
GL_OES_draw_texture interface
void(* DrawTex)(struct gl_context *ctx, GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
GL_OES_EGL_image interface
void(* EGLImageTargetTexture2D)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLeglImageOES image_handle)
void(* EGLImageTargetRenderbufferStorage)(struct gl_context *ctx, struct gl_renderbuffer *rb, void *image_handle)
GL_EXT_transform_feedback interface
struct
gl_transform_feedback_object *(* NewTransformFeedback)(struct gl_context *ctx, GLuint name)
void(* DeleteTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void(* BeginTransformFeedback)(struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
void(* EndTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void(* PauseTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
void(* ResumeTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
GL_NV_texture_barrier interface
void(* TextureBarrier)(struct gl_context *ctx)
GL_ARB_sampler_objects
struct gl_sampler_object *(* NewSamplerObject)(struct gl_context *ctx, GLuint name)
void(* DeleteSamplerObject)(struct gl_context *ctx, struct gl_sampler_object *samp)
Return a timestamp in nanoseconds as defined by GL_ARB_timer_query.
This should be equivalent to glGetInteger64v(GL_TIMESTAMP);
uint64_t(* GetTimestamp)(struct gl_context *ctx)
GL_ARB_texture_multisample
void(* GetSamplePosition)(struct gl_context *ctx, struct gl_framebuffer *fb, GLuint index, GLfloat *outValue)
Detailed Description
Device driver function table.
Core Mesa uses these function pointers to call into device drivers. Most of these functions directly correspond to OpenGL state commands. Core Mesa will call these functions after error checking has been done so that the drivers don't have to worry about error testing.
Vertex transformation/clipping/lighting is patched into the T&L module. Rasterization functions are patched into the swrast module.
Note: when new functions are added here, the drivers/common/driverfuncs.c file should be updated too!!!
Field Documentation
void(* dd_function_table::Accum)(struct gl_context *ctx, GLenum op, GLfloat value)
Execute glAccum command.
GLboolean(* dd_function_table::AllocTextureImageBuffer)(struct gl_context *ctx, struct gl_texture_image *texImage)
Called to allocate memory for a single texture image.
Referenced by _mesa_alloc_texture_storage(), _mesa_prepare_mipmap_level(), _mesa_store_compressed_teximage(), _mesa_store_teximage(), and copyteximage().
GLboolean(* dd_function_table::AllocTextureStorage)(struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
For GL_ARB_texture_storage.
Allocate memory for whole mipmap stack. All the gl_texture_images in the texture object will have their dimensions, format, etc. initialized already.
void(* dd_function_table::AlphaFunc)(struct gl_context *ctx, GLenum func, GLfloat ref)
Specify the alpha test function.
void(* dd_function_table::BeginCallList)(struct gl_context *ctx, struct gl_display_list *dlist)
Called by glCallList(s).
Notify the T&L component before and after calling a display list.
Referenced by execute_list().
void(* dd_function_table::BeginConditionalRender)(struct gl_context *ctx, struct gl_query_object *q, GLenum mode)
GL_NV_conditional_render.
void(* dd_function_table::BeginQuery)(struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_init_query_object_functions().
void(* dd_function_table::BeginTransformFeedback)(struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
void(* dd_function_table::BeginVertices)(struct gl_context *ctx)
void(* dd_function_table::BindArrayObject)(struct gl_context *ctx, struct gl_array_object *obj)
Referenced by bind_vertex_array().
void(* dd_function_table::BindBuffer)(struct gl_context *ctx, GLenum target, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions(), and bind_buffer_object().
void(* dd_function_table::BindFramebuffer)(struct gl_context *ctx, GLenum target, struct gl_framebuffer *drawFb, struct gl_framebuffer *readFb)
void(* dd_function_table::BindProgram)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Bind a vertex/fragment program.
Referenced by update_program().
void(* dd_function_table::BindTexture)(struct gl_context *ctx, GLenum target, struct gl_texture_object *tObj)
Called by glBindTexture().
Referenced by _mesa_BindTexture().
void(* dd_function_table::Bitmap)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, const struct gl_pixelstore_attrib *unpack, const GLubyte *bitmap)
Called by glBitmap().
void(* dd_function_table::BlendColor)(struct gl_context *ctx, const GLfloat color[4])
Set the blend color.
void(* dd_function_table::BlendEquationSeparate)(struct gl_context *ctx, GLenum modeRGB, GLenum modeA)
Set the blend equation.
void(* dd_function_table::BlendEquationSeparatei)(struct gl_context *ctx, GLuint buffer, GLenum modeRGB, GLenum modeA)
void(* dd_function_table::BlendFuncSeparate)(struct gl_context *ctx, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
Specify pixel arithmetic.
void(* dd_function_table::BlendFuncSeparatei)(struct gl_context *ctx, GLuint buffer, GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorA, GLenum dfactorA)
void(* dd_function_table::BlitFramebuffer)(struct gl_context *ctx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
GLboolean(* dd_function_table::BufferData)(struct gl_context *ctx, GLenum target, GLsizeiptrARB size, const GLvoid *data, GLenum usage, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions().
GLenum(* dd_function_table::BufferObjectPurgeable)(struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
Referenced by buffer_object_purgeable().
GLenum(* dd_function_table::BufferObjectUnpurgeable)(struct gl_context *ctx, struct gl_buffer_object *obj, GLenum option)
Referenced by buffer_object_unpurgeable().
void(* dd_function_table::BufferSubData)(struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, const GLvoid *data, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions().
void(* dd_function_table::CheckQuery)(struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_check_conditional_render(), and _mesa_init_query_object_functions().
void(* dd_function_table::CheckSync)(struct gl_context *, struct gl_sync_object *)
Referenced by _mesa_init_sync_object_functions().
gl_format(* dd_function_table::ChooseTextureFormat)(struct gl_context *ctx, GLenum target, GLint internalFormat, GLenum srcFormat, GLenum srcType)
Choose actual hardware texture format given the texture target, the user-provided source image format and type and the desired internal format.
In some cases, srcFormat and srcType can be GL_NONE. Note: target may be GL_TEXTURE_CUBE_MAP, but never GL_TEXTURE_CUBE_MAP_[POSITIVE/NEGATIVE]_[XYZ]. Called by glTexImage(), etc.
Referenced by _mesa_choose_texture_format(), and _mesa_get_fallback_texture().
void(* dd_function_table::Clear)(struct gl_context *ctx, GLbitfield buffers)
Clear the color/depth/stencil/accum buffer(s).
Parameters
buffers a bitmask of BUFFER_BIT_* flags indicating which renderbuffers need to be cleared.
void(* dd_function_table::ClientWaitSync)(struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
Referenced by _mesa_init_sync_object_functions().
void(* dd_function_table::ClipPlane)(struct gl_context *ctx, GLenum plane, const GLfloat *equation)
Specify a plane against which all geometry is clipped.
void(* dd_function_table::ColorMask)(struct gl_context *ctx, GLboolean rmask, GLboolean gmask, GLboolean bmask, GLboolean amask)
Enable and disable writing of frame buffer color components.
void(* dd_function_table::ColorMaskIndexed)(struct gl_context *ctx, GLuint buf, GLboolean rmask, GLboolean gmask, GLboolean bmask, GLboolean amask)
void(* dd_function_table::ColorMaterial)(struct gl_context *ctx, GLenum face, GLenum mode)
Cause a material color to track the current color.
void(* dd_function_table::CompressedTexImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexImage[123]D().
Referenced by teximage().
void(* dd_function_table::CompressedTexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLint height, GLint depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Called by glCompressedTexSubImage[123]D().
void(* dd_function_table::CopyBufferSubData)(struct gl_context *ctx, struct gl_buffer_object *src, struct gl_buffer_object *dst, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
Referenced by _mesa_init_buffer_object_functions().
void(* dd_function_table::CopyPixels)(struct gl_context *ctx, GLint srcx, GLint srcy, GLsizei width, GLsizei height, GLint dstx, GLint dsty, GLenum type)
Called by glCopyPixels().
void(* dd_function_table::CopyTexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, struct gl_renderbuffer *rb, GLint x, GLint y, GLsizei width, GLsizei height)
Called by glCopyTex[Sub]Image[123]D().
Referenced by copyteximage(), and copytexsubimage().
void(* dd_function_table::CullFace)(struct gl_context *ctx, GLenum mode)
Specify whether front- or back-facing facets can be culled.
GLuint dd_function_table::CurrentExecPrimitive
Set by the driver-supplied T&L engine.
Set to PRIM_OUTSIDE_BEGIN_END when outside glBegin()/glEnd().
Referenced by _mesa_inside_begin_end().
GLuint dd_function_table::CurrentSavePrimitive
Current glBegin state of an in-progress compilation.
May be GL_POINTS, GL_TRIANGLE_STRIP, etc. or PRIM_OUTSIDE_BEGIN_END or PRIM_UNKNOWN.
Referenced by _mesa_inside_dlist_begin_end(), invalidate_saved_current_state(), save_Begin(), and save_End().
void(* dd_function_table::DeleteArrayObject)(struct gl_context *ctx, struct gl_array_object *obj)
Referenced by _mesa_reference_array_object_().
void(* dd_function_table::DeleteBuffer)(struct gl_context *ctx, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions(), and _mesa_reference_buffer_object_().
void(* dd_function_table::DeleteProgram)(struct gl_context *ctx, struct gl_program *prog)
Delete a program.
Referenced by delete_program_cb().
void(* dd_function_table::DeleteQuery)(struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_init_query_object_functions(), and delete_queryobj_cb().
void(* dd_function_table::DeleteSamplerObject)(struct gl_context *ctx, struct gl_sampler_object *samp)
Referenced by _mesa_init_sampler_object_functions(), and _mesa_reference_sampler_object_().
void(* dd_function_table::DeleteShader)(struct gl_context *ctx, struct gl_shader *shader)
Referenced by _mesa_free_shader_program_data(), _mesa_init_shader_object_functions(), _mesa_reference_shader(), and delete_shader_cb().
void(* dd_function_table::DeleteShaderProgram)(struct gl_context *ctx, struct gl_shader_program *shProg)
Referenced by _mesa_init_shader_object_functions(), _mesa_reference_shader_program(), and delete_shader_cb().
void(* dd_function_table::DeleteSyncObject)(struct gl_context *, struct gl_sync_object *)
Referenced by _mesa_init_sync_object_functions(), and _mesa_unref_sync_object().
void(* dd_function_table::DeleteTexture)(struct gl_context *ctx, struct gl_texture_object *texObj)
Called to delete/free a texture object.
Drivers should free the object and any image data it contains.
Referenced by _mesa_free_texture_data(), _mesa_reference_texobj_(), alloc_proxy_textures(), delete_texture_cb(), and free_shared_state().
void(* dd_function_table::DeleteTextureImage)(struct gl_context *ctx, struct gl_texture_image *)
Called to free a texture image object returned by NewTextureImage()
Referenced by _mesa_delete_texture_object().
void(* dd_function_table::DeleteTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_free_transform_feedback(), _mesa_init_transform_feedback_functions(), and delete_cb().
void(* dd_function_table::DepthFunc)(struct gl_context *ctx, GLenum func)
Specify the value used for depth buffer comparisons.
void(* dd_function_table::DepthMask)(struct gl_context *ctx, GLboolean flag)
Enable or disable writing into the depth buffer.
void(* dd_function_table::DepthRange)(struct gl_context *ctx, GLclampd nearval, GLclampd farval)
Specify mapping of depth values from NDC to window coordinates.
void(* dd_function_table::DiscardFramebuffer)(struct gl_context *ctx, GLenum target, GLsizei numAttachments, const GLenum *attachments)
void(* dd_function_table::DrawBuffer)(struct gl_context *ctx, GLenum buffer)
Specify the current buffer for writing.
void(* dd_function_table::DrawBuffers)(struct gl_context *ctx, GLsizei n, const GLenum *buffers)
Specify the buffers for writing for fragment programs.
void(* dd_function_table::DrawPixels)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, const GLvoid *pixels)
Called by glDrawPixels().
unpack describes how to unpack the source image data.
void(* dd_function_table::DrawTex)(struct gl_context *ctx, GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
Referenced by draw_texture().
void(* dd_function_table::EGLImageTargetRenderbufferStorage)(struct gl_context *ctx, struct gl_renderbuffer *rb, void *image_handle)
void(* dd_function_table::EGLImageTargetTexture2D)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, struct gl_texture_image *texImage, GLeglImageOES image_handle)
void(* dd_function_table::Enable)(struct gl_context *ctx, GLenum cap, GLboolean state)
Enable or disable server-side gl capabilities.
Referenced by _mesa_set_enable(), _mesa_set_framebuffer_srgb(), _mesa_set_multisample(), and client_state().
void(* dd_function_table::EndCallList)(struct gl_context *ctx)
Called by glEndCallList().
See Also
dd_function_table::BeginCallList.
Referenced by execute_list().
void(* dd_function_table::EndConditionalRender)(struct gl_context *ctx, struct gl_query_object *q)
void(* dd_function_table::EndList)(struct gl_context *ctx)
Called by glEndList().
See Also
dd_function_table::NewList.
Referenced by _mesa_EndList().
void(* dd_function_table::EndQuery)(struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_init_query_object_functions().
void(* dd_function_table::EndTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
void(* dd_function_table::FenceSync)(struct gl_context *, struct gl_sync_object *, GLenum, GLbitfield)
Referenced by _mesa_init_sync_object_functions().
void(* dd_function_table::Finish)(struct gl_context *ctx)
This is called whenever glFinish() is called.
Referenced by _mesa_finish().
void(* dd_function_table::FinishRenderTexture)(struct gl_context *ctx, struct gl_renderbuffer *rb)
Referenced by _mesa_remove_attachment(), _mesa_set_texture_attachment(), _mesa_update_texture_renderbuffer(), and check_end_texture_render().
void(* dd_function_table::Flush)(struct gl_context *ctx)
This is called whenever glFlush() is called.
Referenced by _mesa_flush(), and _mesa_notifySwapBuffers().
void(* dd_function_table::FlushMappedBufferRange)(struct gl_context *ctx, GLintptr offset, GLsizeiptr length, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions().
void(* dd_function_table::FlushVertices)(struct gl_context *ctx, GLuint flags)
If inside glBegin()/glEnd(), it should ASSERT(0).
Otherwise, if FLUSH_STORED_VERTICES bit in flags is set flushes any buffered vertices, if FLUSH_UPDATE_CURRENT bit is set updates __struct gl_contextRec::Current and gl_light_attrib::Material
Note that the default T&L engine never clears the FLUSH_UPDATE_CURRENT bit, even after performing the update.
void(* dd_function_table::Fogfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
Specify fog parameters.
void(* dd_function_table::FramebufferRenderbuffer)(struct gl_context *ctx, struct gl_framebuffer *fb, GLenum attachment, struct gl_renderbuffer *rb)
void(* dd_function_table::FreeTextureImageBuffer)(struct gl_context *ctx, struct gl_texture_image *texImage)
Free the memory for a single texture image.
Referenced by _mesa_clear_texture_image(), _mesa_delete_texture_image(), _mesa_initialize_context(), _mesa_prepare_mipmap_level(), copyteximage(), and teximage().
void(* dd_function_table::FrontFace)(struct gl_context *ctx, GLenum mode)
Define front- and back-facing polygons.
void(* dd_function_table::GenerateMipmap)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj)
Called by glGenerateMipmap() or when GL_GENERATE_MIPMAP_SGIS is enabled.
Referenced by check_gen_mipmap().
void(* dd_function_table::GetBufferSize)(struct gl_framebuffer *buffer, GLuint *width, GLuint *height)
Get the width and height of the named buffer/window.
Mesa uses this to determine when the driver's window size has changed. XXX OBSOLETE: this function will be removed in the future.
Referenced by _mesa_resizebuffers(), and initialize_framebuffer_size().
void(* dd_function_table::GetBufferSubData)(struct gl_context *ctx, GLintptrARB offset, GLsizeiptrARB size, GLvoid *data, struct gl_buffer_object *obj)
Referenced by _mesa_init_buffer_object_functions().
void(* dd_function_table::GetCompressedTexImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLvoid *data)
Called by glGetCompressedTexImage.
void(* dd_function_table::GetSamplePosition)(struct gl_context *ctx, struct gl_framebuffer *fb, GLuint index, GLfloat *outValue)
const GLubyte*(* dd_function_table::GetString)(struct gl_context *ctx, GLenum name)
Return a string as needed by glGetString().
Only the GL_RENDERER query must be implemented. Otherwise, NULL can be returned.
void(* dd_function_table::GetTexImage)(struct gl_context *ctx, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
Called by glGetTexImage().
Referenced by generate_mipmap_compressed().
uint64_t(* dd_function_table::GetTimestamp)(struct gl_context *ctx)
Referenced by find_custom_value().
void(* dd_function_table::Hint)(struct gl_context *ctx, GLenum target, GLenum mode)
Specify implementation-specific hints.
GLboolean(* dd_function_table::IsProgramNative)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Query if program can be loaded onto hardware.
void(* dd_function_table::Lightfv)(struct gl_context *ctx, GLenum light, GLenum pname, const GLfloat *params)
Set light source parameters.
Note: for GL_POSITION and GL_SPOT_DIRECTION, params will have already been transformed to eye-space.
Referenced by _mesa_light().
void(* dd_function_table::LightingSpaceChange)(struct gl_context *ctx)
Notify driver that the special derived value _NeedEyeCoords has changed.
Referenced by _mesa_update_tnl_spaces().
void(* dd_function_table::LightModelfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
Set the lighting model parameters.
void(* dd_function_table::LineStipple)(struct gl_context *ctx, GLint factor, GLushort pattern)
Specify the line stipple pattern.
void(* dd_function_table::LineWidth)(struct gl_context *ctx, GLfloat width)
Specify the width of rasterized lines.
GLboolean(* dd_function_table::LinkShader)(struct gl_context *ctx, struct gl_shader_program *shader)
Called when a shader program is linked.
This gives drivers an opportunity to clone the IR and make their own transformations on it for the purposes of code generation.
Referenced by _mesa_init_shader_object_functions().
void(* dd_function_table::LogicOpcode)(struct gl_context *ctx, GLenum opcode)
Specify a logical pixel operation for color index rendering.
void*(* dd_function_table::MapBufferRange)(struct gl_context *ctx, GLintptr offset, GLsizeiptr length, GLbitfield access, struct gl_buffer_object *obj)
Referenced by _ae_map_vbos(), _mesa_copy_buffer_subdata(), _mesa_get_compressed_teximage(), _mesa_get_teximage(), _mesa_init_buffer_object_functions(), _mesa_map_pbo_dest(), _mesa_map_pbo_source(), _mesa_max_buffer_index(), _mesa_validate_pbo_compressed_teximage(), _mesa_validate_pbo_teximage(), and unpack_image().
void(* dd_function_table::MapRenderbuffer)(struct gl_context *ctx, struct gl_renderbuffer *rb, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a renderbuffer into user space.
Parameters
mode bitmask of GL_MAP_READ_BIT, GL_MAP_WRITE_BIT and GL_MAP_INVALIDATE_RANGE_BIT (if writing)
Referenced by _mesa_clear_accum_buffer(), accum_or_load(), accum_return(), accum_scale_or_bias(), fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), read_depth_pixels(), read_rgba_pixels_swizzle(), read_stencil_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), slow_read_depth_stencil_pixels_separate(), and slow_read_rgba_pixels().
void(* dd_function_table::MapTextureImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice, GLuint x, GLuint y, GLuint w, GLuint h, GLbitfield mode, GLubyte **mapOut, GLint *rowStrideOut)
Map a slice of a texture image into user space.
Note: for GL_TEXTURE_1D_ARRAY, height must be 1, y must be 0 and slice indicates the 1D array index.
Parameters
texImage the texture image
slice the 3D image slice or array texture slice
x,y,w,h region of interest
mode bitmask of GL_MAP_READ_BIT, GL_MAP_WRITE_BIT and GL_MAP_INVALIDATE_RANGE_BIT (if writing)
mapOut returns start of mapping of region of interest
rowStrideOut returns row stride (in bytes). In the case of a compressed texture, this is the byte stride between one row of blocks and another.
Referenced by _mesa_get_compressed_teximage(), _mesa_print_texture(), _mesa_store_compressed_texsubimage(), generate_mipmap_uncompressed(), get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), get_tex_ycbcr(), and store_texsubimage().
GLbitfield dd_function_table::NeedFlush
Set by the driver-supplied T&L engine whenever vertices are buffered between glBegin()/glEnd() objects or __struct gl_contextRec::Current is not updated.
A bitmask of the FLUSH_x values above.
The dd_function_table::FlushVertices call below may be used to resolve these conditions.
struct gl_array_object*(* dd_function_table::NewArrayObject)(struct gl_context *ctx, GLuint id) read
Referenced by _mesa_init_varray(), bind_vertex_array(), and gen_vertex_arrays().
struct gl_buffer_object*(* dd_function_table::NewBufferObject)(struct gl_context *ctx, GLuint buffer, GLenum target) read
Referenced by _mesa_alloc_shared_state(), _mesa_init_buffer_object_functions(), and handle_bind_buffer_gen().
struct gl_framebuffer*(* dd_function_table::NewFramebuffer)(struct gl_context *ctx, GLuint name) read
void(* dd_function_table::NewList)(struct gl_context *ctx, GLuint list, GLenum mode)
Called by glNewList().
Let the T&L component know what is going on with display lists in time to make changes to dispatch tables, etc.
Referenced by _mesa_NewList().
struct gl_program*(* dd_function_table::NewProgram)(struct gl_context *ctx, GLenum target, GLuint id) read
Allocate a new program.
Referenced by _mesa_alloc_shared_state(), and _mesa_get_fixed_func_vertex_program().
struct gl_query_object*(* dd_function_table::NewQueryObject)(struct gl_context *ctx, GLuint id) read
Referenced by _mesa_init_query_object_functions().
struct gl_renderbuffer*(* dd_function_table::NewRenderbuffer)(struct gl_context *ctx, GLuint name) read
Referenced by _mesa_update_texture_renderbuffer().
struct gl_sampler_object*(* dd_function_table::NewSamplerObject)(struct gl_context *ctx, GLuint name) read
Referenced by _mesa_init_sampler_object_functions().
struct gl_shader*(* dd_function_table::NewShader)(struct gl_context *ctx, GLuint name, GLenum type) read
Referenced by _mesa_init_shader_object_functions(), and create_shader().
struct gl_shader_program*(* dd_function_table::NewShaderProgram)(struct gl_context *ctx, GLuint name) read
Referenced by _mesa_init_shader_object_functions(), and create_shader_program().
struct gl_sync_object*(* dd_function_table::NewSyncObject)(struct gl_context *, GLenum) read
Referenced by _mesa_init_sync_object_functions().
struct gl_texture_image*(* dd_function_table::NewTextureImage)(struct gl_context *ctx) read
Called to allocate a new texture image object.
Referenced by _mesa_get_tex_image(), and get_proxy_tex_image().
struct gl_texture_object*(* dd_function_table::NewTextureObject)(struct gl_context *ctx, GLuint name, GLenum target) read
Called to allocate a new texture object.
Drivers will usually allocate/return a subclass of gl_texture_object.
Referenced by _mesa_alloc_shared_state(), _mesa_BindTexture(), _mesa_GenTextures(), _mesa_get_fallback_texture(), _mesa_initialize_context(), and alloc_proxy_textures().
struct gl_transform_feedback_object*(* dd_function_table::NewTransformFeedback)(struct gl_context *ctx, GLuint name) read
Referenced by _mesa_free_transform_feedback(), _mesa_init_transform_feedback(), and _mesa_init_transform_feedback_functions().
GLboolean(* dd_function_table::NotifySaveBegin)(struct gl_context *ctx, GLenum mode)
Give the driver the opportunity to hook in its own vtxfmt for compiling optimized display lists.
This is called on each valid glBegin() during list compilation.
Referenced by save_Begin().
void(* dd_function_table::PauseTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
void(* dd_function_table::PointParameterfv)(struct gl_context *ctx, GLenum pname, const GLfloat *params)
void(* dd_function_table::PointSize)(struct gl_context *ctx, GLfloat size)
Specify the diameter of rasterized points.
void(* dd_function_table::PolygonMode)(struct gl_context *ctx, GLenum face, GLenum mode)
Select a polygon rasterization mode.
void(* dd_function_table::PolygonOffset)(struct gl_context *ctx, GLfloat factor, GLfloat units)
Set the scale and units used to calculate depth values.
void(* dd_function_table::PolygonStipple)(struct gl_context *ctx, const GLubyte *mask)
Set the polygon stippling pattern.
GLboolean(* dd_function_table::ProgramStringNotify)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that a program string (and GPU code) has been specified or modified.
Return GL_TRUE or GL_FALSE to indicate if the program is supported by the driver.
Referenced by _mesa_get_fixed_func_vertex_program().
void(* dd_function_table::QueryCounter)(struct gl_context *ctx, struct gl_query_object *q)
size_t(* dd_function_table::QuerySamplesForFormat)(struct gl_context *ctx, GLenum target, GLenum internalFormat, int samples[16])
Determine sample counts support for a particular target and format.
Parameters
ctx GL context
target GL target enum
internalFormat GL format enum
samples Buffer to hold the returned sample counts. Drivers must not return more than 16 counts.
Returns
The number of sample counts actually written to samples. If internaFormat is not renderable, zero is returned.
Referenced by _mesa_check_sample_count().
void(* dd_function_table::RasterPos)(struct gl_context *ctx, const GLfloat v[4])
Execute glRasterPos, updating the ctx->Current.Raster fields.
void(* dd_function_table::ReadBuffer)(struct gl_context *ctx, GLenum buffer)
void(* dd_function_table::ReadPixels)(struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, const struct gl_pixelstore_attrib *unpack, GLvoid *dest)
Called by glReadPixels().
void(* dd_function_table::RenderMode)(struct gl_context *ctx, GLenum mode)
Set rasterization mode.
GLenum(* dd_function_table::RenderObjectPurgeable)(struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
Referenced by renderbuffer_purgeable().
GLenum(* dd_function_table::RenderObjectUnpurgeable)(struct gl_context *ctx, struct gl_renderbuffer *obj, GLenum option)
Referenced by renderbuffer_unpurgeable().
void(* dd_function_table::RenderTexture)(struct gl_context *ctx, struct gl_framebuffer *fb, struct gl_renderbuffer_attachment *att)
Referenced by _mesa_update_texture_renderbuffer(), and check_begin_texture_render().
void(* dd_function_table::ResizeBuffers)(struct gl_context *ctx, struct gl_framebuffer *fb, GLuint width, GLuint height)
Resize the given framebuffer to the given size.
XXX OBSOLETE: this function will be removed in the future.
Referenced by _mesa_resizebuffers(), and initialize_framebuffer_size().
void(* dd_function_table::ResumeTransformFeedback)(struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Referenced by _mesa_init_transform_feedback_functions().
void(* dd_function_table::SamplerUniformChange)(struct gl_context *ctx, GLenum target, struct gl_program *prog)
Notify driver that the sampler uniforms for the current program have changed.
On some drivers, this may require shader recompiles.
void(* dd_function_table::SaveFlushVertices)(struct gl_context *ctx)
GLboolean dd_function_table::SaveNeedFlush
Need to call SaveFlushVertices() upon state change?
void(* dd_function_table::Scissor)(struct gl_context *ctx, GLint x, GLint y, GLsizei w, GLsizei h)
Define the scissor box.
Referenced by _mesa_set_scissor().
void(* dd_function_table::ServerWaitSync)(struct gl_context *, struct gl_sync_object *, GLbitfield, GLuint64)
Referenced by _mesa_init_sync_object_functions().
void(* dd_function_table::ShadeModel)(struct gl_context *ctx, GLenum mode)
Select flat or smooth shading.
void(* dd_function_table::StencilFuncSeparate)(struct gl_context *ctx, GLenum face, GLenum func, GLint ref, GLuint mask)
OpenGL 2.0 two-sided StencilFunc.
void(* dd_function_table::StencilMaskSeparate)(struct gl_context *ctx, GLenum face, GLuint mask)
OpenGL 2.0 two-sided StencilMask.
void(* dd_function_table::StencilOpSeparate)(struct gl_context *ctx, GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
OpenGL 2.0 two-sided StencilOp.
GLboolean(* dd_function_table::TestProxyTexImage)(struct gl_context *ctx, GLenum target, GLint level, gl_format format, GLint width, GLint height, GLint depth, GLint border)
Called by glTexImage, glCompressedTexImage, glCopyTexImage and glTexStorage to check if the dimensions of the texture image are too large.
Parameters
target any GL_PROXY_TEXTURE_x target
Returns
GL_TRUE if the image is OK, GL_FALSE if too large
Referenced by copyteximage(), and teximage().
void(* dd_function_table::TexEnv)(struct gl_context *ctx, GLenum target, GLenum pname, const GLfloat *param)
Set texture environment parameters.
void(* dd_function_table::TexGen)(struct gl_context *ctx, GLenum coord, GLenum pname, const GLfloat *params)
Control the generation of texture coordinates.
Referenced by pop_texture_group().
void(* dd_function_table::TexImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexImage[123]D() and glCopyTexImage[12]D() Allocate texture memory and copy the user's image to the buffer.
The gl_texture_image fields, etc. will be fully initialized. The parameters are the same as glTexImage3D(), plus:
Parameters
dims 1, 2, or 3 indicating glTexImage1/2/3D()
packing describes how to unpack the source data.
texImage is the destination texture image.
Referenced by _mesa_get_fallback_texture(), and teximage().
void(* dd_function_table::TexParameter)(struct gl_context *ctx, GLenum target, struct gl_texture_object *texObj, GLenum pname, const GLfloat *params)
Set texture parameters.
Referenced by finish_texture_init().
void(* dd_function_table::TexSubImage)(struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLint depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Called by glTexSubImage[123]D().
Replace a subset of the target texture with new texel data.
Referenced by generate_mipmap_compressed(), and texsubimage().
void(* dd_function_table::TextureBarrier)(struct gl_context *ctx)
Referenced by _mesa_init_texture_barrier_functions().
GLenum(* dd_function_table::TextureObjectPurgeable)(struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
Referenced by texture_object_purgeable().
GLenum(* dd_function_table::TextureObjectUnpurgeable)(struct gl_context *ctx, struct gl_texture_object *obj, GLenum option)
Referenced by texture_object_unpurgeable().
GLboolean(* dd_function_table::UnmapBuffer)(struct gl_context *ctx, struct gl_buffer_object *obj)
Referenced by _ae_unmap_vbos(), _mesa_copy_buffer_subdata(), _mesa_get_compressed_teximage(), _mesa_get_teximage(), _mesa_init_buffer_object_functions(), _mesa_max_buffer_index(), _mesa_unmap_pbo_dest(), _mesa_unmap_pbo_source(), _mesa_unmap_teximage_pbo(), delete_bufferobj_cb(), and unpack_image().
void(* dd_function_table::UnmapRenderbuffer)(struct gl_context *ctx, struct gl_renderbuffer *rb)
Referenced by _mesa_clear_accum_buffer(), accum_or_load(), accum_return(), accum_scale_or_bias(), fast_read_depth_stencil_pixels(), fast_read_depth_stencil_pixels_separate(), read_depth_pixels(), read_rgba_pixels_swizzle(), read_stencil_pixels(), read_uint_depth_pixels(), readpixels_memcpy(), slow_read_depth_stencil_pixels_separate(), and slow_read_rgba_pixels().
void(* dd_function_table::UnmapTextureImage)(struct gl_context *ctx, struct gl_texture_image *texImage, GLuint slice)
Referenced by _mesa_get_compressed_teximage(), _mesa_print_texture(), _mesa_store_compressed_texsubimage(), generate_mipmap_uncompressed(), get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), get_tex_ycbcr(), and store_texsubimage().
void(* dd_function_table::UpdateState)(struct gl_context *ctx, GLbitfield new_state)
Notify the driver after Mesa has made some internal state changes.
This is in addition to any state change callbacks Mesa may already have made.
Referenced by _mesa_update_state_locked().
void(* dd_function_table::UseProgram)(struct gl_context *ctx, struct gl_shader_program *shProg)
Referenced by _mesa_use_program(), and _mesa_use_shader_program().
void(* dd_function_table::ValidateFramebuffer)(struct gl_context *ctx, struct gl_framebuffer *fb)
Referenced by _mesa_test_framebuffer_completeness().
void(* dd_function_table::Viewport)(struct gl_context *ctx, GLint x, GLint y, GLsizei w, GLsizei h)
Set the viewport.
Referenced by _mesa_set_viewport().
void(* dd_function_table::WaitQuery)(struct gl_context *ctx, struct gl_query_object *q)
Referenced by _mesa_check_conditional_render(), and _mesa_init_query_object_functions().
The documentation for this struct was generated from the following file:
dd.h