Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texcompress_s3tc.c File Reference
GL_EXT_texture_compression_s3tc support.
#include "glheader.h"
#include "imports.h"
#include "colormac.h"
#include "dlopen.h"
#include "image.h"
#include "macros.h"
#include "mtypes.h"
#include "texcompress.h"
#include "texcompress_s3tc.h"
#include "texstore.h"
#include "format_unpack.h"
Macros
#define USE_EXTERNAL_DXTN_LIB 1
#define DXTN_LIBNAME "libtxc_dxtn.so"
Typedefs
typedef void(* dxtFetchTexelFuncExt)(GLint srcRowstride, const GLubyte *pixdata, GLint col, GLint row, GLvoid *texelOut)
typedef void(* dxtCompressTexFuncExt)(GLint srccomps, GLint width, GLint height, const GLubyte *srcPixData, GLenum destformat, GLubyte *dest, GLint dstRowStride)
Functions
void _mesa_init_texture_s3tc (struct gl_context *ctx)
GLboolean _mesa_texstore_rgb_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_dxt1 format.
GLboolean _mesa_texstore_rgba_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt1 format.
GLboolean _mesa_texstore_rgba_dxt3 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt3 format.
GLboolean _mesa_texstore_rgba_dxt5 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt5 format.
static void problem (const char *func)
Report problem with dxt texture decompression, once.
static void fetch_rgb_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rgba_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rgba_dxt3 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rgba_dxt5 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgb_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgba_dxt1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgba_dxt3 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_srgba_dxt5 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
compressed_fetch_func _mesa_get_dxt_fetch_func (gl_format format)
Variables
static dxtFetchTexelFuncExt fetch_ext_rgb_dxt1 = NULL
static dxtFetchTexelFuncExt fetch_ext_rgba_dxt1 = NULL
static dxtFetchTexelFuncExt fetch_ext_rgba_dxt3 = NULL
static dxtFetchTexelFuncExt fetch_ext_rgba_dxt5 = NULL
static dxtCompressTexFuncExt ext_tx_compress_dxtn = NULL
static void * dxtlibhandle = NULL
Detailed Description
GL_EXT_texture_compression_s3tc support.
Macro Definition Documentation
#define DXTN_LIBNAME "libtxc_dxtn.so"
Referenced by _mesa_init_texture_s3tc().
#define USE_EXTERNAL_DXTN_LIB 1
Typedef Documentation
typedef void(* dxtCompressTexFuncExt)(GLint srccomps, GLint width, GLint height, const GLubyte *srcPixData, GLenum destformat, GLubyte *dest, GLint dstRowStride)
typedef void(* dxtFetchTexelFuncExt)(GLint srcRowstride, const GLubyte *pixdata, GLint col, GLint row, GLvoid *texelOut)
Function Documentation
compressed_fetch_func _mesa_get_dxt_fetch_func (gl_format format)
References fetch_rgb_dxt1(), fetch_rgba_dxt1(), fetch_rgba_dxt3(), fetch_rgba_dxt5(), fetch_srgb_dxt1(), fetch_srgba_dxt1(), fetch_srgba_dxt3(), fetch_srgba_dxt5(), MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, and NULL.
Referenced by _mesa_get_compressed_fetch_func().
void _mesa_init_texture_s3tc (struct gl_context * ctx)
References _mesa_dlclose(), _mesa_dlopen(), _mesa_dlsym(), _mesa_warning(), dxtlibhandle, DXTN_LIBNAME, ext_tx_compress_dxtn, fetch_ext_rgb_dxt1, fetch_ext_rgba_dxt1, fetch_ext_rgba_dxt3, fetch_ext_rgba_dxt5, gl_context::Mesa_DXTn, NULL, and void().
Referenced by init_attrib_groups().
GLboolean _mesa_texstore_rgb_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgb_dxt1 format.
References _mesa_get_format_base_format(), _mesa_image_address2d(), _mesa_make_temp_ubyte_image(), _mesa_warning(), ASSERT, ext_tx_compress_dxtn, GLubyte, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_SRGB_DXT1, and NULL.
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_rgba_dxt1 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt1 format.
References _mesa_get_format_base_format(), _mesa_image_address2d(), _mesa_make_temp_ubyte_image(), _mesa_warning(), ASSERT, ext_tx_compress_dxtn, GLubyte, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_SRGBA_DXT1, and NULL.
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_rgba_dxt3 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt3 format.
References _mesa_get_format_base_format(), _mesa_image_address2d(), _mesa_make_temp_ubyte_image(), _mesa_warning(), ASSERT, ext_tx_compress_dxtn, GLubyte, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_SRGBA_DXT3, and NULL.
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_rgba_dxt5 (TEXSTORE_PARAMS)
Store user's image in rgba_dxt5 format.
References _mesa_get_format_base_format(), _mesa_image_address2d(), _mesa_make_temp_ubyte_image(), _mesa_warning(), ASSERT, ext_tx_compress_dxtn, GLubyte, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_SRGBA_DXT5, and NULL.
Referenced by _mesa_get_texstore_func().
static void fetch_rgb_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgb_dxt1, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void fetch_rgba_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt1, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void fetch_rgba_dxt3 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt3, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void fetch_rgba_dxt5 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, fetch_ext_rgba_dxt5, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void fetch_srgb_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, fetch_ext_rgb_dxt1, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void fetch_srgba_dxt1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, fetch_ext_rgba_dxt1, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void fetch_srgba_dxt3 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, fetch_ext_rgba_dxt3, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void fetch_srgba_dxt5 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References _mesa_nonlinear_to_linear(), ACOMP, BCOMP, fetch_ext_rgba_dxt5, GCOMP, GLubyte, problem(), RCOMP, and UBYTE_TO_FLOAT.
Referenced by _mesa_get_dxt_fetch_func().
static void problem (const char * func) static
Report problem with dxt texture decompression, once.
References _mesa_debug(), and NULL.
Referenced by fetch_rgb_dxt1(), fetch_rgba_dxt1(), fetch_rgba_dxt3(), fetch_rgba_dxt5(), fetch_srgb_dxt1(), fetch_srgba_dxt1(), fetch_srgba_dxt3(), and fetch_srgba_dxt5().
Variable Documentation
void* dxtlibhandle = NULL static
Referenced by _mesa_init_texture_s3tc().
dxtCompressTexFuncExt ext_tx_compress_dxtn = NULL static
Referenced by _mesa_init_texture_s3tc(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), and _mesa_texstore_rgba_dxt5().
dxtFetchTexelFuncExt fetch_ext_rgb_dxt1 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgb_dxt1(), and fetch_srgb_dxt1().
dxtFetchTexelFuncExt fetch_ext_rgba_dxt1 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgba_dxt1(), and fetch_srgba_dxt1().
dxtFetchTexelFuncExt fetch_ext_rgba_dxt3 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgba_dxt3(), and fetch_srgba_dxt3().
dxtFetchTexelFuncExt fetch_ext_rgba_dxt5 = NULL static
Referenced by _mesa_init_texture_s3tc(), fetch_rgba_dxt5(), and fetch_srgba_dxt5().