Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texcompress_rgtc.h File Reference
#include "glheader.h"
#include "texstore.h"
Functions
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
compressed_fetch_func _mesa_get_compressed_rgtc_func (gl_format format)
Function Documentation
compressed_fetch_func _mesa_get_compressed_rgtc_func (gl_format format)
References fetch_l_latc1(), fetch_la_latc2(), fetch_red_rgtc1(), fetch_rg_rgtc2(), fetch_signed_l_latc1(), fetch_signed_la_latc2(), fetch_signed_red_rgtc1(), fetch_signed_rg_rgtc2(), MESA_FORMAT_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_RED_RGTC1, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_SIGNED_RG_RGTC2, and NULL.
Referenced by _mesa_get_compressed_fetch_func().
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_ubyte_image(), ASSERT, extractsrc_u(), GLubyte, MESA_FORMAT_L_LATC1, MESA_FORMAT_RED_RGTC1, NULL, and unsigned_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_ubyte_image(), ASSERT, extractsrc_u(), GLubyte, MESA_FORMAT_LA_LATC2, MESA_FORMAT_RG_RGTC2, NULL, and unsigned_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_float_image(), ASSERT, extractsrc_s(), GLbyte, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_RED_RGTC1, NULL, and signed_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_float_image(), ASSERT, extractsrc_s(), GLbyte, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_RG_RGTC2, NULL, and signed_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().