Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texcompress_rgtc.c File Reference
GL_EXT_texture_compression_rgtc support.
#include "glheader.h"
#include "imports.h"
#include "colormac.h"
#include "image.h"
#include "macros.h"
#include "mipmap.h"
#include "texcompress.h"
#include "texcompress_rgtc.h"
#include "texstore.h"
#include "texcompress_rgtc_tmp.h"
Macros
#define RGTC_DEBUG 0
#define TAG(x) unsigned_##x
#define TYPE GLubyte
#define T_MIN 0
#define T_MAX 0xff
#define TAG(x) signed_##x
#define TYPE GLbyte
#define T_MIN (GLbyte)-128
#define T_MAX (GLbyte)127
Functions
static void unsigned_encode_rgtc_ubyte (GLubyte *blkaddr, GLubyte srccolors[4][4], GLint numxpixels, GLint numypixels)
static void signed_encode_rgtc_ubyte (GLbyte *blkaddr, GLbyte srccolors[4][4], GLint numxpixels, GLint numypixels)
static void unsigned_fetch_texel_rgtc (unsigned srcRowStride, const GLubyte *pixdata, unsigned i, unsigned j, GLubyte *value, unsigned comps)
static void signed_fetch_texel_rgtc (unsigned srcRowStride, const GLbyte *pixdata, unsigned i, unsigned j, GLbyte *value, unsigned comps)
static void extractsrc_u (GLubyte srcpixels[4][4], const GLubyte *srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps)
static void extractsrc_s (GLbyte srcpixels[4][4], const GLfloat *srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps)
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
static void fetch_red_rgtc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_l_latc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_red_rgtc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_l_latc1 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_rg_rgtc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_la_latc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_rg_rgtc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
static void fetch_signed_la_latc2 (const GLubyte *map, GLint rowStride, GLint i, GLint j, GLfloat *texel)
compressed_fetch_func _mesa_get_compressed_rgtc_func (gl_format format)
Detailed Description
GL_EXT_texture_compression_rgtc support.
Macro Definition Documentation
#define RGTC_DEBUG 0
#define T_MAX 0xff
Referenced by encode_rgtc_ubyte(), and fetch_texel_rgtc().
#define T_MAX (GLbyte)127
#define T_MIN 0
Referenced by encode_rgtc_ubyte(), and fetch_texel_rgtc().
#define T_MIN (GLbyte)-128
#define TAG (x) unsigned_##x
#define TAG (x) signed_##x
#define TYPE GLubyte
Referenced by encode_rgtc_ubyte(), and fetch_texel_rgtc().
#define TYPE GLbyte
Function Documentation
compressed_fetch_func _mesa_get_compressed_rgtc_func (gl_format format)
References fetch_l_latc1(), fetch_la_latc2(), fetch_red_rgtc1(), fetch_rg_rgtc2(), fetch_signed_l_latc1(), fetch_signed_la_latc2(), fetch_signed_red_rgtc1(), fetch_signed_rg_rgtc2(), MESA_FORMAT_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_RED_RGTC1, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_SIGNED_RG_RGTC2, and NULL.
Referenced by _mesa_get_compressed_fetch_func().
GLboolean _mesa_texstore_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_ubyte_image(), ASSERT, extractsrc_u(), GLubyte, MESA_FORMAT_L_LATC1, MESA_FORMAT_RED_RGTC1, NULL, and unsigned_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_ubyte_image(), ASSERT, extractsrc_u(), GLubyte, MESA_FORMAT_LA_LATC2, MESA_FORMAT_RG_RGTC2, NULL, and unsigned_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_signed_red_rgtc1 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_float_image(), ASSERT, extractsrc_s(), GLbyte, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_RED_RGTC1, NULL, and signed_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_signed_rg_rgtc2 (TEXSTORE_PARAMS)
References _mesa_get_format_base_format(), _mesa_make_temp_float_image(), ASSERT, extractsrc_s(), GLbyte, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_RG_RGTC2, NULL, and signed_encode_rgtc_ubyte().
Referenced by _mesa_get_texstore_func().
static void extractsrc_s (GLbyte srcpixels[4][4], const GLfloat * srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps) static
References FLOAT_TO_BYTE_TEX, and GLubyte.
Referenced by _mesa_texstore_signed_red_rgtc1(), and _mesa_texstore_signed_rg_rgtc2().
static void extractsrc_u (GLubyte srcpixels[4][4], const GLubyte * srcaddr, GLint srcRowStride, GLint numxpixels, GLint numypixels, GLint comps) static
References GLubyte.
Referenced by _mesa_texstore_red_rgtc1(), and _mesa_texstore_rg_rgtc2().
static void fetch_l_latc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, UBYTE_TO_FLOAT, and unsigned_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void fetch_la_latc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, UBYTE_TO_FLOAT, and unsigned_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void fetch_red_rgtc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, UBYTE_TO_FLOAT, and unsigned_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void fetch_rg_rgtc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, GCOMP, GLubyte, RCOMP, UBYTE_TO_FLOAT, and unsigned_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void fetch_signed_l_latc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT, GCOMP, GLbyte, RCOMP, and signed_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void fetch_signed_la_latc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, RCOMP, and signed_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void fetch_signed_red_rgtc1 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, RCOMP, and signed_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void fetch_signed_rg_rgtc2 (const GLubyte * map, GLint rowStride, GLint i, GLint j, GLfloat * texel) static
References ACOMP, BCOMP, BYTE_TO_FLOAT_TEX, GCOMP, GLbyte, RCOMP, and signed_fetch_texel_rgtc().
Referenced by _mesa_get_compressed_rgtc_func().
static void signed_encode_rgtc_ubyte (GLbyte * blkaddr, GLbyte srccolors[4][4], GLint numxpixels, GLint numypixels) static
Referenced by _mesa_texstore_signed_red_rgtc1(), and _mesa_texstore_signed_rg_rgtc2().
static void signed_fetch_texel_rgtc (unsigned srcRowStride, const GLbyte * pixdata, unsigned i, unsigned j, GLbyte * value, unsigned comps) static
Referenced by fetch_signed_l_latc1(), fetch_signed_la_latc2(), fetch_signed_red_rgtc1(), and fetch_signed_rg_rgtc2().
static void unsigned_encode_rgtc_ubyte (GLubyte * blkaddr, GLubyte srccolors[4][4], GLint numxpixels, GLint numypixels) static
Referenced by _mesa_texstore_red_rgtc1(), and _mesa_texstore_rg_rgtc2().
static void unsigned_fetch_texel_rgtc (unsigned srcRowStride, const GLubyte * pixdata, unsigned i, unsigned j, GLubyte * value, unsigned comps) static
Referenced by fetch_l_latc1(), fetch_la_latc2(), fetch_red_rgtc1(), and fetch_rg_rgtc2().