Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texcompress_cpal.h File Reference
#include "main/glheader.h"
Functions
void _mesa_cpal_compressed_teximage2d (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei imageSize, const void *palette)
Convert a call to glCompressedTexImage2D() where internalFormat is a compressed palette format into a regular GLubyte/RGBA glTexImage2D() call.
unsigned _mesa_cpal_compressed_size (int level, GLenum internalFormat, unsigned width, unsigned height)
Function Documentation
unsigned _mesa_cpal_compressed_size (int level, GLenum internalFormat, unsigned width, unsigned height)
References ASSERT, cpal_format_info::cpal_format, formats, GL_PALETTE4_RGB8_OES, GL_PALETTE8_RGB5_A1_OES, cpal_format_info::palette_size, and cpal_format_info::size.
Referenced by compressed_texture_error_check().
void _mesa_cpal_compressed_teximage2d (GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei imageSize, const void * palette)
Convert a call to glCompressedTexImage2D() where internalFormat is a compressed palette format into a regular GLubyte/RGBA glTexImage2D() call.
References _mesa_PixelStorei(), _mesa_TexImage2D(), cpal_format_info::format, formats, GL_PALETTE4_RGB8_OES, GL_PALETTE8_RGB5_A1_OES, GLubyte, NULL, cpal_format_info::palette_size, paletted_to_color(), cpal_format_info::size, and cpal_format_info::type.
Referenced by teximage().