Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texenv.c File Reference
glTexEnv-related functions
#include "main/glheader.h"
#include "main/context.h"
#include "main/blend.h"
#include "main/enums.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/state.h"
#include "main/texenv.h"
#include "main/texstate.h"
Macros
#define TE_ERROR(errCode, msg, value) _mesa_error(ctx, errCode, msg, _mesa_lookup_enum_by_nr(value));
Functions
static void set_env_mode (struct gl_context *ctx, struct gl_texture_unit *texUnit, GLenum mode)
Set texture env mode.
static void set_env_color (struct gl_context *ctx, struct gl_texture_unit *texUnit, const GLfloat *color)
static void set_combiner_mode (struct gl_context *ctx, struct gl_texture_unit *texUnit, GLenum pname, GLenum mode)
Set an RGB or A combiner mode/function.
static void set_combiner_source (struct gl_context *ctx, struct gl_texture_unit *texUnit, GLenum pname, GLenum param)
Set an RGB or A combiner source term.
static void set_combiner_operand (struct gl_context *ctx, struct gl_texture_unit *texUnit, GLenum pname, GLenum param)
Set an RGB or A combiner operand term.
static void set_combiner_scale (struct gl_context *ctx, struct gl_texture_unit *texUnit, GLenum pname, GLfloat scale)
void GLAPIENTRY _mesa_TexEnvfv (GLenum target, GLenum pname, const GLfloat *param)
void GLAPIENTRY _mesa_TexEnvf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexEnvi (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TexEnviv (GLenum target, GLenum pname, const GLint *param)
static GLint get_texenvi (struct gl_context *ctx, const struct gl_texture_unit *texUnit, GLenum pname)
Helper for glGetTexEnvi/f()
void GLAPIENTRY _mesa_GetTexEnvfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexEnviv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_TexBumpParameterivATI (GLenum pname, const GLint *param)
Why does ATI_envmap_bumpmap require new entrypoints? Should just reuse TexEnv ones...
void GLAPIENTRY _mesa_TexBumpParameterfvATI (GLenum pname, const GLfloat *param)
void GLAPIENTRY _mesa_GetTexBumpParameterivATI (GLenum pname, GLint *param)
void GLAPIENTRY _mesa_GetTexBumpParameterfvATI (GLenum pname, GLfloat *param)
Detailed Description
glTexEnv-related functions
Macro Definition Documentation
#define TE_ERROR (errCode, msg, value) _mesa_error(ctx, errCode, msg, _mesa_lookup_enum_by_nr(value));
Referenced by _mesa_TexEnvfv(), set_combiner_mode(), set_combiner_operand(), set_combiner_scale(), set_combiner_source(), and set_env_mode().
Function Documentation
void GLAPIENTRY _mesa_GetTexBumpParameterfvATI (GLenum pname, GLfloat * param)
References _mesa_error(), _mesa_get_current_tex_unit(), and gl_texture_unit::RotMatrix.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexBumpParameterivATI (GLenum pname, GLint * param)
References _mesa_error(), _mesa_get_current_tex_unit(), FLOAT_TO_INT, and gl_texture_unit::RotMatrix.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexEnvfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_get_clamp_fragment_color(), _mesa_get_current_tex_unit(), _mesa_update_state(), _NEW_BUFFERS, _NEW_FRAG_CLAMP, COPY_4FV(), gl_texture_unit::EnvColor, gl_texture_unit::EnvColorUnclamped, get_texenvi(), and gl_texture_unit::LodBias.
Referenced by _mesa_GetTexEnvxv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexEnviv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_current_tex_unit(), gl_texture_unit::EnvColor, FLOAT_TO_INT, get_texenvi(), and gl_texture_unit::LodBias.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexBumpParameterfvATI (GLenum pname, const GLfloat * param)
References _mesa_error(), _mesa_get_current_tex_unit(), _NEW_TEXTURE, COPY_4FV(), FLUSH_VERTICES, gl_texture_unit::RotMatrix, and TEST_EQ_4V.
Referenced by _mesa_initialize_exec_table(), and _mesa_TexBumpParameterivATI().
void GLAPIENTRY _mesa_TexBumpParameterivATI (GLenum pname, const GLint * param)
Why does ATI_envmap_bumpmap require new entrypoints? Should just reuse TexEnv ones...
References _mesa_error(), _mesa_TexBumpParameterfvATI(), and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexEnvf (GLenum target, GLenum pname, GLfloat param)
References _mesa_TexEnvfv().
Referenced by _mesa_initialize_exec_table(), _mesa_TexEnvx(), _mesa_TexEnvxv(), and pop_texture_group().
void GLAPIENTRY _mesa_TexEnvfv (GLenum target, GLenum pname, const GLfloat * param)
References _mesa_debug(), _mesa_error(), _mesa_get_current_tex_unit(), _mesa_lookup_enum_by_nr(), _NEW_POINT, _NEW_TEXTURE, API_OPENGL_COMPAT, gl_texture_unit::BumpTarget, FLUSH_VERTICES, gl_texture_unit::LodBias, MESA_VERBOSE, set_combiner_mode(), set_combiner_operand(), set_combiner_scale(), set_combiner_source(), set_env_color(), set_env_mode(), TE_ERROR, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table(), _mesa_TexEnvf(), _mesa_TexEnvi(), _mesa_TexEnviv(), _mesa_TexEnvxv(), and pop_texture_group().
void GLAPIENTRY _mesa_TexEnvi (GLenum target, GLenum pname, GLint param)
References _mesa_TexEnvfv().
Referenced by _mesa_initialize_exec_table(), _mesa_PopAttrib(), and pop_texture_group().
void GLAPIENTRY _mesa_TexEnviv (GLenum target, GLenum pname, const GLint * param)
References _mesa_TexEnvfv(), and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table().
static GLint get_texenvi (struct gl_context * ctx, const struct gl_texture_unit * texUnit, GLenum pname) static
Helper for glGetTexEnvi/f()
Returns
value of queried pname or -1 if error.
References _mesa_error(), gl_context::API, API_OPENGL_COMPAT, gl_extensions::ATI_envmap_bumpmap, gl_texture_unit::BumpTarget, gl_texture_unit::Combine, gl_texture_unit::EnvMode, gl_context::Extensions, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, gl_extensions::NV_texture_env_combine4, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, gl_tex_env_combine_state::ScaleShiftA, gl_tex_env_combine_state::ScaleShiftRGB, gl_tex_env_combine_state::SourceA, and gl_tex_env_combine_state::SourceRGB.
Referenced by _mesa_GetTexEnvfv(), and _mesa_GetTexEnviv().
static void set_combiner_mode (struct gl_context * ctx, struct gl_texture_unit * texUnit, GLenum pname, GLenum mode) static
Set an RGB or A combiner mode/function.
References _NEW_TEXTURE, gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_dot3, gl_extensions::ATI_envmap_bumpmap, gl_extensions::ATI_texture_env_combine3, gl_texture_unit::Combine, gl_extensions::EXT_texture_env_dot3, gl_context::Extensions, FLUSH_VERTICES, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, and TE_ERROR.
Referenced by _mesa_TexEnvfv().
static void set_combiner_operand (struct gl_context * ctx, struct gl_texture_unit * texUnit, GLenum pname, GLenum param) static
Set an RGB or A combiner operand term.
References _NEW_TEXTURE, gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_texture_env_combine, gl_texture_unit::Combine, gl_context::Extensions, FLUSH_VERTICES, MAX_COMBINER_TERMS, gl_extensions::NV_texture_env_combine4, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, and TE_ERROR.
Referenced by _mesa_TexEnvfv().
static void set_combiner_scale (struct gl_context * ctx, struct gl_texture_unit * texUnit, GLenum pname, GLfloat scale) static
References _mesa_error(), _NEW_TEXTURE, gl_texture_unit::Combine, F, FLUSH_VERTICES, gl_tex_env_combine_state::ScaleShiftA, gl_tex_env_combine_state::ScaleShiftRGB, and TE_ERROR.
Referenced by _mesa_TexEnvfv().
static void set_combiner_source (struct gl_context * ctx, struct gl_texture_unit * texUnit, GLenum pname, GLenum param) static
Set an RGB or A combiner source term.
References _NEW_TEXTURE, gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ATI_texture_env_combine3, gl_texture_unit::Combine, gl_context::Const, gl_context::Extensions, FLUSH_VERTICES, MAX_COMBINER_TERMS, gl_constants::MaxTextureUnits, gl_extensions::NV_texture_env_combine4, gl_tex_env_combine_state::SourceA, gl_tex_env_combine_state::SourceRGB, and TE_ERROR.
Referenced by _mesa_TexEnvfv().
static void set_env_color (struct gl_context * ctx, struct gl_texture_unit * texUnit, const GLfloat * color) static
References _NEW_TEXTURE, CLAMP, COPY_4FV(), gl_texture_unit::EnvColor, gl_texture_unit::EnvColorUnclamped, F, FLUSH_VERTICES, and TEST_EQ_4V.
Referenced by _mesa_TexEnvfv().
static void set_env_mode (struct gl_context * ctx, struct gl_texture_unit * texUnit, GLenum mode) static
Set texture env mode.
References _NEW_TEXTURE, gl_texture_unit::EnvMode, gl_context::Extensions, FLUSH_VERTICES, gl_extensions::NV_texture_env_combine4, and TE_ERROR.
Referenced by _mesa_TexEnvfv().