Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texenv.h File Reference
#include "main/glheader.h"
Functions
void GLAPIENTRY _mesa_GetTexEnvfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexEnviv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_TexEnvf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexEnvfv (GLenum target, GLenum pname, const GLfloat *param)
void GLAPIENTRY _mesa_TexEnvi (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TexEnviv (GLenum target, GLenum pname, const GLint *param)
void GLAPIENTRY _mesa_TexBumpParameterivATI (GLenum pname, const GLint *param)
Why does ATI_envmap_bumpmap require new entrypoints? Should just reuse TexEnv ones...
void GLAPIENTRY _mesa_TexBumpParameterfvATI (GLenum pname, const GLfloat *param)
void GLAPIENTRY _mesa_GetTexBumpParameterivATI (GLenum pname, GLint *param)
void GLAPIENTRY _mesa_GetTexBumpParameterfvATI (GLenum pname, GLfloat *param)
Function Documentation
void GLAPIENTRY _mesa_GetTexBumpParameterfvATI (GLenum pname, GLfloat * param)
References _mesa_error(), _mesa_get_current_tex_unit(), and gl_texture_unit::RotMatrix.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexBumpParameterivATI (GLenum pname, GLint * param)
References _mesa_error(), _mesa_get_current_tex_unit(), FLOAT_TO_INT, and gl_texture_unit::RotMatrix.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexEnvfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_get_clamp_fragment_color(), _mesa_get_current_tex_unit(), _mesa_update_state(), _NEW_BUFFERS, _NEW_FRAG_CLAMP, COPY_4FV(), gl_texture_unit::EnvColor, gl_texture_unit::EnvColorUnclamped, get_texenvi(), and gl_texture_unit::LodBias.
Referenced by _mesa_GetTexEnvxv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexEnviv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_current_tex_unit(), gl_texture_unit::EnvColor, FLOAT_TO_INT, get_texenvi(), and gl_texture_unit::LodBias.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexBumpParameterfvATI (GLenum pname, const GLfloat * param)
References _mesa_error(), _mesa_get_current_tex_unit(), _NEW_TEXTURE, COPY_4FV(), FLUSH_VERTICES, gl_texture_unit::RotMatrix, and TEST_EQ_4V.
Referenced by _mesa_initialize_exec_table(), and _mesa_TexBumpParameterivATI().
void GLAPIENTRY _mesa_TexBumpParameterivATI (GLenum pname, const GLint * param)
Why does ATI_envmap_bumpmap require new entrypoints? Should just reuse TexEnv ones...
References _mesa_error(), _mesa_TexBumpParameterfvATI(), and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexEnvf (GLenum target, GLenum pname, GLfloat param)
References _mesa_TexEnvfv().
Referenced by _mesa_initialize_exec_table(), _mesa_TexEnvx(), _mesa_TexEnvxv(), and pop_texture_group().
void GLAPIENTRY _mesa_TexEnvfv (GLenum target, GLenum pname, const GLfloat * param)
References _mesa_debug(), _mesa_error(), _mesa_get_current_tex_unit(), _mesa_lookup_enum_by_nr(), _NEW_POINT, _NEW_TEXTURE, API_OPENGL_COMPAT, gl_texture_unit::BumpTarget, FLUSH_VERTICES, gl_texture_unit::LodBias, MESA_VERBOSE, set_combiner_mode(), set_combiner_operand(), set_combiner_scale(), set_combiner_source(), set_env_color(), set_env_mode(), TE_ERROR, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table(), _mesa_TexEnvf(), _mesa_TexEnvi(), _mesa_TexEnviv(), _mesa_TexEnvxv(), and pop_texture_group().
void GLAPIENTRY _mesa_TexEnvi (GLenum target, GLenum pname, GLint param)
References _mesa_TexEnvfv().
Referenced by _mesa_initialize_exec_table(), _mesa_PopAttrib(), and pop_texture_group().
void GLAPIENTRY _mesa_TexEnviv (GLenum target, GLenum pname, const GLint * param)
References _mesa_TexEnvfv(), and INT_TO_FLOAT.
Referenced by _mesa_initialize_exec_table().