Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texformat.c File Reference
Texture formats.
#include "context.h"
#include "enums.h"
#include "mtypes.h"
#include "texcompress.h"
#include "texformat.h"
Macros
#define RETURN_IF_SUPPORTED(f)
Functions
gl_format _mesa_choose_tex_format (struct gl_context *ctx, GLenum target, GLint internalFormat, GLenum format, GLenum type)
Choose an appropriate texture format given the format, type and internalFormat parameters passed to glTexImage().
GLboolean _mesa_tex_target_is_array (GLenum target)
Detailed Description
Texture formats.
Author
Gareth Hughes
Brian Paul
Macro Definition Documentation
#define RETURN_IF_SUPPORTED (f)
Value:
do {            \
   if (ctx->TextureFormatSupported[f])          \
      return f;                                 \
} while (0)
Referenced by _mesa_choose_tex_format().
Function Documentation
gl_format _mesa_choose_tex_format (struct gl_context * ctx, GLenum target, GLint internalFormat, GLenum format, GLenum type)
Choose an appropriate texture format given the format, type and internalFormat parameters passed to glTexImage().
Parameters
ctx the GL context.
target a texture target (GL_TEXTURE_x)
internalFormat user's prefered internal texture format.
format incoming image pixel format.
type incoming image data type.
Returns
the closest gl_format for the given format/type arguments
This is called via dd_function_table::ChooseTextureFormat. Hardware drivers may override this function with a specialized version.
References _mesa_lookup_enum_by_nr(), _mesa_problem(), gl_extensions::ANGLE_texture_compression_dxt, ASSERT, gl_extensions::EXT_texture_compression_s3tc, gl_context::Extensions, GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, GL_ETC1_RGB8_OES, MESA_FORMAT_A16, MESA_FORMAT_A8, MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_AL1616, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_ALPHA_UINT32, MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB2101010_UINT, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_DUDV8, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_GR1616, MESA_FORMAT_GR88, MESA_FORMAT_I16, MESA_FORMAT_I8, MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT32, MESA_FORMAT_INTENSITY_INT16, MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_INTENSITY_UINT8, MESA_FORMAT_L16, MESA_FORMAT_L8, MESA_FORMAT_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_ALPHA_INT16, MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT8, MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT32, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_LUMINANCE_UINT32, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R11_G11_B10_FLOAT, MESA_FORMAT_R16, MESA_FORMAT_R8, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_INT16, MESA_FORMAT_R_INT32, MESA_FORMAT_R_INT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_RED_RGTC1, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_INT16, MESA_FORMAT_RG_INT32, MESA_FORMAT_RG_INT8, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGB9_E5_FLOAT, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGB_INT16, MESA_FORMAT_RGB_INT32, MESA_FORMAT_RGB_INT8, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA_16, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_S8_Z24, MESA_FORMAT_SARGB8, MESA_FORMAT_SIGNED_A16, MESA_FORMAT_SIGNED_A8, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_GR1616, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_R16, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_SIGNED_RG88_REV, MESA_FORMAT_SIGNED_RG_RGTC2, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8_Z24, MESA_FORMAT_XBGR16161616_FLOAT, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_SNORM, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR16161616_UNORM, MESA_FORMAT_XBGR32323232_FLOAT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB8888, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, RETURN_IF_SUPPORTED, gl_extensions::TDFX_texture_compression_FXT1, gl_context::TextureFormatSupported, and void().
GLboolean _mesa_tex_target_is_array (GLenum target)