Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texgetimage.h File Reference
#include "glheader.h"
Functions
void _mesa_get_teximage (struct gl_context *ctx, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
This is the software fallback for Driver.GetTexImage().
void _mesa_get_compressed_teximage (struct gl_context *ctx, struct gl_texture_image *texImage, GLvoid *data)
This is the software fallback for Driver.GetCompressedTexImage().
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
Get texture image.
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint lod, GLvoid *img)
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid *img)
Function Documentation
void _mesa_get_compressed_teximage (struct gl_context * ctx, struct gl_texture_image * texImage, GLvoid * img)
This is the software fallback for Driver.GetCompressedTexImage().
All error checking will have been done before this routine is called.
References _mesa_error(), _mesa_format_image_size(), _mesa_format_row_stride(), _mesa_get_format_block_size(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_texture_image::Depth, gl_context::Driver, GLubyte, gl_texture_image::Height, dd_function_table::MapBufferRange, dd_function_table::MapTextureImage, gl_context::Pack, size, gl_buffer_object::Size, gl_texture_image::TexFormat, dd_function_table::UnmapBuffer, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
void _mesa_get_teximage (struct gl_context * ctx, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage)
This is the software fallback for Driver.GetTexImage().
All error checking will have been done before this routine is called. We'll call ctx->Driver.MapTextureImage() to access the data, then unmap with ctx->Driver.UnmapTextureImage().
References _mesa_error(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba(), get_tex_ycbcr(), GLubyte, dd_function_table::MapBufferRange, gl_context::Pack, gl_buffer_object::Size, gl_texture_object::Target, gl_texture_image::TexObject, and dd_function_table::UnmapBuffer.
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint lod, GLvoid * img)
References _mesa_GetnCompressedTexImageARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid * img)
References _mesa_debug(), _mesa_get_current_tex_object(), _mesa_get_format_name(), _mesa_is_bufferobj(), _mesa_is_zero_size_texture(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), FLUSH_VERTICES, getcompressedteximage_error_check(), gl_texture_image::Height, MESA_VERBOSE, gl_texture_object::Name, gl_texture_image::TexFormat, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_GetCompressedTexImage(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
Get texture image.
Called by glGetTexImage.
Parameters
target texture target.
level image level.
format pixel data format for returned image.
type pixel data type for returned image.
bufSize size of the pixels data buffer.
pixels returned pixel data.
References _mesa_debug(), _mesa_get_current_tex_object(), _mesa_get_format_name(), _mesa_is_bufferobj(), _mesa_is_zero_size_texture(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), FLUSH_VERTICES, getteximage_error_check(), gl_texture_image::Height, MESA_VERBOSE, gl_texture_object::Name, gl_texture_image::TexFormat, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_GetTexImage(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels)
References _mesa_GetnTexImageARB().
Referenced by _mesa_initialize_exec_table().