Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texgen.c File Reference
glTexGen-related functions
#include "main/glheader.h"
#include "main/context.h"
#include "main/enums.h"
#include "main/macros.h"
#include "main/texgen.h"
#include "main/texstate.h"
#include "math/m_matrix.h"
#include "main/dispatch.h"
Functions
static struct gl_texgen * get_texgen (struct gl_context *ctx, struct gl_texture_unit *texUnit, GLenum coord)
Return texgen state for given coordinate.
void GLAPIENTRY _mesa_TexGenfv (GLenum coord, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TexGeniv (GLenum coord, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TexGend (GLenum coord, GLenum pname, GLdouble param)
void GLAPIENTRY _es_GetTexGenfv (GLenum coord, GLenum pname, GLfloat *params)
void GLAPIENTRY _es_TexGenf (GLenum coord, GLenum pname, GLfloat param)
void GLAPIENTRY _es_TexGenfv (GLenum coord, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TexGendv (GLenum coord, GLenum pname, const GLdouble *params)
void GLAPIENTRY _mesa_TexGenf (GLenum coord, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexGeni (GLenum coord, GLenum pname, GLint param)
void GLAPIENTRY _mesa_GetTexGendv (GLenum coord, GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetTexGenfv (GLenum coord, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexGeniv (GLenum coord, GLenum pname, GLint *params)
Detailed Description
glTexGen-related functions
Function Documentation
void GLAPIENTRY _es_GetTexGenfv (GLenum coord, GLenum pname, GLfloat * params)
References _mesa_GetTexGenfv().
void GLAPIENTRY _es_TexGenf (GLenum coord, GLenum pname, GLfloat param)
References _mesa_error(), _mesa_TexGenf(), and GL_TEXTURE_GEN_STR_OES.
Referenced by _check_TexGeniOES(), _check_TexGenivOES(), _mesa_TexGenxOES(), and _mesa_TexGenxvOES().
void GLAPIENTRY _es_TexGenfv (GLenum coord, GLenum pname, const GLfloat * params)
References _mesa_error(), _mesa_TexGenfv(), and GL_TEXTURE_GEN_STR_OES.
void GLAPIENTRY _mesa_GetTexGendv (GLenum coord, GLenum pname, GLdouble * params)
References _mesa_error(), _mesa_get_current_tex_unit(), COPY_4V, ENUM_TO_DOUBLE, gl_texgen::EyePlane, get_texgen(), gl_texgen::Mode, and gl_texgen::ObjectPlane.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexGenfv (GLenum coord, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_get_current_tex_unit(), API_OPENGL_COMPAT, COPY_4V, ENUM_TO_FLOAT, gl_texgen::EyePlane, get_texgen(), gl_texgen::Mode, and gl_texgen::ObjectPlane.
Referenced by _es_GetTexGenfv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexGeniv (GLenum coord, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_current_tex_unit(), API_OPENGL_COMPAT, gl_texgen::EyePlane, get_texgen(), gl_texgen::Mode, and gl_texgen::ObjectPlane.
Referenced by _check_GetTexGenivOES(), _mesa_GetTexGenxvOES(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexGend (GLenum coord, GLenum pname, GLdouble param)
References _mesa_TexGenfv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexGendv (GLenum coord, GLenum pname, const GLdouble * params)
References _mesa_TexGenfv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexGenf (GLenum coord, GLenum pname, GLfloat param)
References _mesa_TexGenfv().
Referenced by _es_TexGenf(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexGenfv (GLenum coord, GLenum pname, const GLfloat * params)
References _math_matrix_analyse(), _math_matrix_is_dirty(), _mesa_debug(), _mesa_error(), _mesa_get_current_tex_unit(), _mesa_lookup_enum_by_nr(), _mesa_transform_vector(), gl_texgen::_ModeBit, _NEW_TEXTURE, API_OPENGL_COMPAT, COPY_4FV(), gl_texgen::EyePlane, FLUSH_VERTICES, get_texgen(), GLbitfield, MESA_VERBOSE, gl_texgen::Mode, gl_texgen::ObjectPlane, TEST_EQ_4V, TEXGEN_EYE_LINEAR, TEXGEN_NORMAL_MAP_NV, TEXGEN_OBJ_LINEAR, TEXGEN_REFLECTION_MAP_NV, TEXGEN_SPHERE_MAP, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _es_TexGenfv(), _mesa_initialize_exec_table(), _mesa_TexGend(), _mesa_TexGendv(), _mesa_TexGenf(), _mesa_TexGeniv(), and pop_texture_group().
void GLAPIENTRY _mesa_TexGeni (GLenum coord, GLenum pname, GLint param)
References _mesa_TexGeniv().
Referenced by _mesa_initialize_exec_table(), and pop_texture_group().
void GLAPIENTRY _mesa_TexGeniv (GLenum coord, GLenum pname, const GLint * params)
References _mesa_TexGenfv().
Referenced by _mesa_initialize_exec_table(), and _mesa_TexGeni().
static struct gl_texgen* get_texgen (struct gl_context * ctx, struct gl_texture_unit * texUnit, GLenum coord) static read
Return texgen state for given coordinate.
References gl_context::API, API_OPENGLES, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, GL_TEXTURE_GEN_STR_OES, and NULL.
Referenced by _mesa_GetTexGendv(), _mesa_GetTexGenfv(), _mesa_GetTexGeniv(), and _mesa_TexGenfv().