Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texgetimage.c File Reference
#include "glheader.h"
#include "bufferobj.h"
#include "enums.h"
#include "context.h"
#include "formats.h"
#include "format_unpack.h"
#include "glformats.h"
#include "image.h"
#include "mtypes.h"
#include "pack.h"
#include "pbo.h"
#include "texcompress.h"
#include "texgetimage.h"
#include "teximage.h"
Functions
static GLboolean type_needs_clamping (GLenum type)
Code for glGetTexImage() and glGetCompressedTexImage().
static void get_tex_depth (struct gl_context *ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for depth/Z pixels.
static void get_tex_depth_stencil (struct gl_context *ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for depth/stencil pixels.
static void get_tex_ycbcr (struct gl_context *ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for YCbCr pixels.
static void get_tex_rgba_compressed (struct gl_context *ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage, GLbitfield transferOps)
Get a color texture image with decompression.
static GLenum _mesa_base_pack_format (GLenum format)
Return a base GL format given the user-requested format for glGetTexImage().
static void get_tex_rgba_uncompressed (struct gl_context *ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage, GLbitfield transferOps)
Get an uncompressed color texture image.
static void get_tex_rgba (struct gl_context *ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
glGetTexImage for color formats (RGBA, RGB, alpha, LA, etc).
static GLboolean get_tex_memcpy (struct gl_context *ctx, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
Try to do glGetTexImage() with simple memcpy().
void _mesa_get_teximage (struct gl_context *ctx, GLenum format, GLenum type, GLvoid *pixels, struct gl_texture_image *texImage)
This is the software fallback for Driver.GetTexImage().
void _mesa_get_compressed_teximage (struct gl_context *ctx, struct gl_texture_image *texImage, GLvoid *img)
This is the software fallback for Driver.GetCompressedTexImage().
static GLboolean legal_getteximage_target (struct gl_context *ctx, GLenum target)
Validate the texture target enum supplied to glTexImage or glCompressedTexImage.
static GLboolean getteximage_error_check (struct gl_context *ctx, GLenum target, GLint level, GLenum format, GLenum type, GLsizei clientMemSize, GLvoid *pixels)
Do error checking for a glGetTexImage() call.
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid *pixels)
Get texture image.
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
static GLboolean getcompressedteximage_error_check (struct gl_context *ctx, GLenum target, GLint level, GLsizei clientMemSize, GLvoid *img)
Do error checking for a glGetCompressedTexImage() call.
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid *img)
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint level, GLvoid *img)
Function Documentation
static GLenum _mesa_base_pack_format (GLenum format) static
Return a base GL format given the user-requested format for glGetTexImage().
Referenced by get_tex_rgba_uncompressed().
void _mesa_get_compressed_teximage (struct gl_context * ctx, struct gl_texture_image * texImage, GLvoid * img)
This is the software fallback for Driver.GetCompressedTexImage().
All error checking will have been done before this routine is called.
References _mesa_error(), _mesa_format_image_size(), _mesa_format_row_stride(), _mesa_get_format_block_size(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_texture_image::Depth, gl_context::Driver, GLubyte, gl_texture_image::Height, dd_function_table::MapBufferRange, dd_function_table::MapTextureImage, gl_context::Pack, size, gl_buffer_object::Size, gl_texture_image::TexFormat, dd_function_table::UnmapBuffer, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
void _mesa_get_teximage (struct gl_context * ctx, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage)
This is the software fallback for Driver.GetTexImage().
All error checking will have been done before this routine is called. We'll call ctx->Driver.MapTextureImage() to access the data, then unmap with ctx->Driver.UnmapTextureImage().
References _mesa_error(), _mesa_is_bufferobj(), ADD_POINTERS, gl_pixelstore_attrib::BufferObj, gl_context::Driver, get_tex_depth(), get_tex_depth_stencil(), get_tex_memcpy(), get_tex_rgba(), get_tex_ycbcr(), GLubyte, dd_function_table::MapBufferRange, gl_context::Pack, gl_buffer_object::Size, gl_texture_object::Target, gl_texture_image::TexObject, and dd_function_table::UnmapBuffer.
void GLAPIENTRY _mesa_GetCompressedTexImage (GLenum target, GLint level, GLvoid * img)
References _mesa_GetnCompressedTexImageARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnCompressedTexImageARB (GLenum target, GLint level, GLsizei bufSize, GLvoid * img)
References _mesa_debug(), _mesa_get_current_tex_object(), _mesa_get_format_name(), _mesa_is_bufferobj(), _mesa_is_zero_size_texture(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), FLUSH_VERTICES, getcompressedteximage_error_check(), gl_texture_image::Height, MESA_VERBOSE, gl_texture_object::Name, gl_texture_image::TexFormat, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_GetCompressedTexImage(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnTexImageARB (GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, GLvoid * pixels)
Get texture image.
Called by glGetTexImage.
Parameters
target texture target.
level image level.
format pixel data format for returned image.
type pixel data type for returned image.
bufSize size of the pixels data buffer.
pixels returned pixel data.
References _mesa_debug(), _mesa_get_current_tex_object(), _mesa_get_format_name(), _mesa_is_bufferobj(), _mesa_is_zero_size_texture(), _mesa_lock_texture(), _mesa_select_tex_image(), _mesa_unlock_texture(), FLUSH_VERTICES, getteximage_error_check(), gl_texture_image::Height, MESA_VERBOSE, gl_texture_object::Name, gl_texture_image::TexFormat, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_GetTexImage(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels)
References _mesa_GetnTexImageARB().
Referenced by _mesa_initialize_exec_table().
static void get_tex_depth (struct gl_context * ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for depth/Z pixels.
References _mesa_error(), _mesa_image_address(), _mesa_pack_depth_span(), _mesa_unpack_float_z_row(), gl_texture_image::Depth, gl_context::Driver, GLubyte, gl_texture_image::Height, dd_function_table::MapTextureImage, gl_context::Pack, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
Referenced by _mesa_get_teximage().
static void get_tex_depth_stencil (struct gl_context * ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for depth/stencil pixels.
References _mesa_error(), _mesa_image_address(), _mesa_swap4(), gl_texture_image::Depth, gl_context::Driver, GLubyte, gl_texture_image::Height, dd_function_table::MapTextureImage, gl_context::Pack, gl_pixelstore_attrib::SwapBytes, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
Referenced by _mesa_get_teximage().
static GLboolean get_tex_memcpy (struct gl_context * ctx, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
Try to do glGetTexImage() with simple memcpy().
Returns
GL_TRUE if done, GL_FALSE otherwise
References gl_texture_image::_BaseFormat, _mesa_error(), _mesa_format_matches_format_and_type(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_image_address2d(), _mesa_image_row_stride(), _mesa_is_cube_face(), gl_context::Driver, GLubyte, gl_texture_image::Height, dd_function_table::MapTextureImage, gl_context::Pack, gl_pixelstore_attrib::SwapBytes, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
Referenced by _mesa_get_teximage().
static void get_tex_rgba (struct gl_context * ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for color formats (RGBA, RGB, alpha, LA, etc).
Compressed textures are handled here as well.
References _mesa_get_format_datatype(), _mesa_is_format_compressed(), get_tex_rgba_compressed(), get_tex_rgba_uncompressed(), GLbitfield, IMAGE_CLAMP_BIT, gl_texture_image::TexFormat, and type_needs_clamping().
Referenced by _mesa_get_teximage().
static void get_tex_rgba_compressed (struct gl_context * ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage, GLbitfield transferOps) static
Get a color texture image with decompression.
References gl_texture_image::_BaseFormat, _mesa_base_tex_format(), _mesa_decompress_image(), _mesa_error(), _mesa_get_format_base_format(), _mesa_get_srgb_format_linear(), _mesa_image_address(), _mesa_pack_rgba_span_float(), _mesa_rebase_rgba_float(), gl_texture_image::Depth, gl_context::Driver, GLubyte, gl_texture_image::Height, dd_function_table::MapTextureImage, gl_context::Pack, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
Referenced by get_tex_rgba().
static void get_tex_rgba_uncompressed (struct gl_context * ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage, GLbitfield transferOps) static
Get an uncompressed color texture image.
References gl_texture_image::_BaseFormat, _mesa_base_pack_format(), _mesa_error(), _mesa_get_format_base_format(), _mesa_get_srgb_format_linear(), _mesa_image_address(), _mesa_is_format_integer_color(), _mesa_is_format_unsigned(), _mesa_pack_rgba_span_float(), _mesa_pack_rgba_span_from_ints(), _mesa_pack_rgba_span_from_uints(), _mesa_rebase_rgba_float(), _mesa_rebase_rgba_uint(), _mesa_unpack_rgba_row(), _mesa_unpack_uint_rgba_row(), gl_texture_image::Depth, gl_context::Driver, GLubyte, gl_texture_image::Height, dd_function_table::MapTextureImage, gl_context::Pack, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
Referenced by get_tex_rgba().
static void get_tex_ycbcr (struct gl_context * ctx, GLuint dimensions, GLenum format, GLenum type, GLvoid * pixels, struct gl_texture_image * texImage) static
glGetTexImage for YCbCr pixels.
References _mesa_error(), _mesa_image_address(), _mesa_swap2(), gl_texture_image::Depth, gl_context::Driver, GLubyte, GLushort, gl_texture_image::Height, dd_function_table::MapTextureImage, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, gl_context::Pack, gl_pixelstore_attrib::SwapBytes, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_texture_image::Width.
Referenced by _mesa_get_teximage().
static GLboolean getcompressedteximage_error_check (struct gl_context * ctx, GLenum target, GLint level, GLsizei clientMemSize, GLvoid * img) static
Do error checking for a glGetCompressedTexImage() call.
Returns
GL_TRUE if any error, GL_FALSE if no errors.
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_format_image_size(), _mesa_get_current_tex_object(), _mesa_is_bufferobj(), _mesa_is_format_compressed(), _mesa_max_texture_levels(), _mesa_select_tex_image(), gl_pixelstore_attrib::BufferObj, gl_texture_image::Depth, GLubyte, gl_texture_image::Height, legal_getteximage_target(), gl_context::Pack, gl_buffer_object::Size, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_GetnCompressedTexImageARB().
static GLboolean getteximage_error_check (struct gl_context * ctx, GLenum target, GLint level, GLenum format, GLenum type, GLsizei clientMemSize, GLvoid * pixels) static
Do error checking for a glGetTexImage() call.
Returns
GL_TRUE if any error, GL_FALSE if no errors.
References _mesa_bufferobj_mapped(), _mesa_error(), _mesa_error_check_format_and_type(), _mesa_get_current_tex_object(), _mesa_get_format_base_format(), _mesa_is_bufferobj(), _mesa_is_color_format(), _mesa_is_depth_format(), _mesa_is_depthstencil_format(), _mesa_is_dudv_format(), _mesa_is_ycbcr_format(), _mesa_max_texture_levels(), _mesa_select_tex_image(), _mesa_validate_pbo_access(), gl_pixelstore_attrib::BufferObj, gl_texture_image::Depth, gl_texture_image::Height, legal_getteximage_target(), gl_context::Pack, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_GetnTexImageARB().
static GLboolean legal_getteximage_target (struct gl_context * ctx, GLenum target) static
Validate the texture target enum supplied to glTexImage or glCompressedTexImage.
References gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::MESA_texture_array, and gl_extensions::NV_texture_rectangle.
Referenced by getcompressedteximage_error_check(), and getteximage_error_check().
static GLboolean type_needs_clamping (GLenum type) inline static
Code for glGetTexImage() and glGetCompressedTexImage().
Can the given type represent negative values?
Referenced by get_tex_rgba().