Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
teximage.h File Reference
Texture images manipulation functions.
#include "mtypes.h"
#include "formats.h"
Functions
static GLboolean _mesa_is_cube_face (GLenum target)
Is the given value one of the 6 cube faces?
static GLboolean _mesa_is_zero_size_texture (const struct gl_texture_image *texImage)
Is any of the dimensions of given texture equal to zero?
Internal functions
GLint _mesa_base_tex_format (struct gl_context *ctx, GLint internalFormat)
Return the simple base format for a given internal texture format.
GLboolean _mesa_is_proxy_texture (GLenum target)
Test if a target is a proxy target.
GLenum _mesa_get_proxy_target (GLenum target)
Return the proxy target which corresponds to the given texture target.
struct gl_texture_image * _mesa_new_texture_image (struct gl_context *ctx)
Allocate a texture image structure.
void _mesa_delete_texture_image (struct gl_context *ctx, struct gl_texture_image *teximage)
Free a gl_texture_image and associated data.
void _mesa_init_teximage_fields (struct gl_context *ctx, struct gl_texture_image *img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, gl_format format)
Initialize basic fields of the gl_texture_image struct.
gl_format _mesa_choose_texture_format (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level, GLenum internalFormat, GLenum format, GLenum type)
Choose the actual hardware format for a texture image.
void _mesa_update_fbo_texture (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint face, GLuint level)
When a texture image is specified we have to check if it's bound to any framebuffer objects (render to texture) in order to detect changes in size or format since that effects FBO completeness.
void _mesa_clear_texture_image (struct gl_context *ctx, struct gl_texture_image *texImage)
Free and clear fields of the gl_texture_image struct.
struct gl_texture_object * _mesa_select_tex_object (struct gl_context *ctx, const struct gl_texture_unit *texUnit, GLenum target)
Get the texture object that corresponds to the target of the given texture unit.
struct gl_texture_object * _mesa_get_current_tex_object (struct gl_context *ctx, GLenum target)
Return pointer to texture object for given target on current texture unit.
struct gl_texture_image * _mesa_select_tex_image (struct gl_context *ctx, const struct gl_texture_object *texObj, GLenum target, GLint level)
Get a texture image pointer from a texture object, given a texture target and mipmap level.
struct gl_texture_image * _mesa_get_tex_image (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum target, GLint level)
Like _mesa_select_tex_image() but if the image doesn't exist, allocate it and install it.
GLint _mesa_max_texture_levels (struct gl_context *ctx, GLenum target)
Get the maximum number of allowed mipmap levels.
GLboolean _mesa_test_proxy_teximage (struct gl_context *ctx, GLenum target, GLint level, gl_format format, GLint width, GLint height, GLint depth, GLint border)
This is the fallback for Driver.TestProxyTexImage() for doing device- specific texture image size checks.
GLuint _mesa_tex_target_to_face (GLenum target)
For cube map faces, return a face index in [0,5].
GLint _mesa_get_texture_dimensions (GLenum target)
Return number of dimensions per mipmap level for the given texture target.
GLsizei _mesa_get_tex_max_num_levels (GLenum target, GLsizei width, GLsizei height, GLsizei depth)
Return the maximum number of mipmap levels for the given target and the dimensions.
GLboolean _mesa_legal_texture_dimensions (struct gl_context *ctx, GLenum target, GLint level, GLint width, GLint height, GLint depth, GLint border)
Check the width, height, depth and border of a texture image are legal.
static void _mesa_lock_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
Lock a texture for updating.
static void _mesa_unlock_texture (struct gl_context *ctx, struct gl_texture_object *texObj)
API entry point functions
void GLAPIENTRY _mesa_TexImage1D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage3D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexImage3DEXT (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_EGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
void GLAPIENTRY _mesa_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
void GLAPIENTRY _mesa_CopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
void GLAPIENTRY _mesa_CopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
void GLAPIENTRY _mesa_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
void GLAPIENTRY _mesa_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_CompressedTexImage1D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_CompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
void GLAPIENTRY _mesa_TexBuffer (GLenum target, GLenum internalFormat, GLuint buffer)
GL_ARB_texture_buffer_object.
void GLAPIENTRY _mesa_TexBufferRange (GLenum target, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
GL_ARB_texture_buffer_range.
void GLAPIENTRY _mesa_TexImage2DMultisample (GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexImage3DMultisample (GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
void GLAPIENTRY _mesa_TexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
Detailed Description
Texture images manipulation functions.
Function Documentation
GLint _mesa_base_tex_format (struct gl_context * ctx, GLint internalFormat)
Return the simple base format for a given internal texture format.
For example, given GL_LUMINANCE12_ALPHA4, return GL_LUMINANCE_ALPHA.
Parameters
ctx GL context.
internalFormat the internal texture format token or 1, 2, 3, or 4.
Returns
the corresponding base internal format (GL_ALPHA, GL_LUMINANCE, GL_LUMANCE_ALPHA, GL_INTENSITY, GL_RGB, or GL_RGBA), or -1 if invalid enum.
This is the format which is used during texture application (i.e. the texture format and env mode determine the arithmetic used.
References _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_extensions::ANGLE_texture_compression_dxt, gl_context::API, API_OPENGL_CORE, API_OPENGLES, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_depth_texture, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_ES3_compatibility, gl_extensions::ARB_half_float_pixel, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_rg, gl_extensions::ATI_envmap_bumpmap, gl_extensions::ATI_texture_compression_3dc, gl_extensions::EXT_packed_depth_stencil, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_compression_latc, gl_extensions::EXT_texture_compression_s3tc, gl_extensions::EXT_texture_integer, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_texture_sRGB, gl_context::Extensions, GL_COMPRESSED_LUMINANCE_ALPHA_3DC_ATI, GL_ETC1_RGB8_OES, GL_PALETTE4_R5_G6_B5_OES, GL_PALETTE4_RGB5_A1_OES, GL_PALETTE4_RGB8_OES, GL_PALETTE4_RGBA4_OES, GL_PALETTE4_RGBA8_OES, GL_PALETTE8_R5_G6_B5_OES, GL_PALETTE8_RGB5_A1_OES, GL_PALETTE8_RGB8_OES, GL_PALETTE8_RGBA4_OES, GL_PALETTE8_RGBA8_OES, gl_extensions::MESA_ycbcr_texture, gl_extensions::OES_compressed_ETC1_RGB8_texture, gl_extensions::TDFX_texture_compression_FXT1, and gl_context::Version.
Referenced by _mesa_init_teximage_fields(), _mesa_is_legal_tex_storage_format(), compressed_texture_error_check(), copytexture_error_check(), get_tex_rgba_compressed(), and texture_error_check().
gl_format _mesa_choose_texture_format (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level, GLenum internalFormat, GLenum format, GLenum type)
Choose the actual hardware format for a texture image.
Try to use the same format as the previous image level when possible. Otherwise, ask the driver for the best format. It's important to try to choose a consistant format for all levels for efficient texture memory layout/allocation. In particular, this comes up during automatic mipmap generation.
References _mesa_lookup_enum_by_nr(), _mesa_select_tex_image(), _mesa_warning(), ASSERT, dd_function_table::ChooseTextureFormat, gl_context::Driver, gl_texture_image::InternalFormat, gl_context::Mesa_DXTn, MESA_FORMAT_NONE, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by copyteximage(), teximage(), teximagemultisample(), and texstorage().
void _mesa_clear_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free and clear fields of the gl_texture_image struct.
Parameters
ctx GL context.
texImage texture image structure to be cleared.
After the call, texImage will have no data associated with it. Its fields are cleared so that its parent object will test incomplete.
References clear_teximage_fields(), gl_context::Driver, and dd_function_table::FreeTextureImageBuffer.
Referenced by _mesa_clear_texture_object().
void GLAPIENTRY _mesa_CompressedTexImage1D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid * data)
References teximage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
References teximage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data)
References teximage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data)
References compressed_tex_sub_image().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
References compressed_tex_sub_image().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
References compressed_tex_sub_image().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
References copyteximage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
References copyteximage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
References copytexsubimage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References copytexsubimage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_CopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
References copytexsubimage().
Referenced by _mesa_initialize_exec_table().
void _mesa_delete_texture_image (struct gl_context * ctx, struct gl_texture_image * texImage)
Free a gl_texture_image and associated data.
This function is a fallback called via ctx->Driver.DeleteTextureImage().
Parameters
texImage texture image.
Free the texture image structure and the associated image data.
References ASSERT, gl_context::Driver, and dd_function_table::FreeTextureImageBuffer.
void GLAPIENTRY _mesa_EGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
References _mesa_dirty_texobj(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_get_tex_image(), _mesa_lock_texture(), _mesa_unlock_texture(), _mesa_update_state(), _NEW_PIXEL, FLUSH_VERTICES, GL_TEXTURE_EXTERNAL_OES, and gl_texture_object::Immutable.
Referenced by _mesa_initialize_exec_table().
struct gl_texture_object* _mesa_get_current_tex_object (struct gl_context * ctx, GLenum target) read
Return pointer to texture object for given target on current texture unit.
References _mesa_get_current_tex_unit(), and _mesa_select_tex_object().
Referenced by _mesa_EGLImageTargetTexture2DOES(), _mesa_GenerateMipmap(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), compressed_subtexture_error_check(), compressed_tex_sub_image(), copyteximage(), copytexsubimage(), copytexsubimage_error_check(), getcompressedteximage_error_check(), getteximage_error_check(), mutable_tex_object(), tex_storage_error_check(), texbufferrange(), teximage(), teximagemultisample(), texstorage(), texsubimage(), and texsubimage_error_check().
GLenum _mesa_get_proxy_target (GLenum target)
Return the proxy target which corresponds to the given texture target.
References _mesa_problem(), and NULL.
Referenced by copyteximage(), and teximage().
struct gl_texture_image* _mesa_get_tex_image (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum target, GLint level) read
Like _mesa_select_tex_image() but if the image doesn't exist, allocate it and install it.
Only return NULL if passed a bad parameter or run out of memory.
References _mesa_error(), _mesa_select_tex_image(), gl_context::Driver, dd_function_table::NewTextureImage, NULL, and set_tex_image().
Referenced by _mesa_EGLImageTargetTexture2DOES(), _mesa_get_fallback_texture(), _mesa_prepare_mipmap_level(), copyteximage(), generate_mipmap_compressed(), generate_mipmap_uncompressed(), get_tex_image(), teximage(), and teximagemultisample().
GLsizei _mesa_get_tex_max_num_levels (GLenum target, GLsizei width, GLsizei height, GLsizei depth)
Return the maximum number of mipmap levels for the given target and the dimensions.
The dimensions are expected not to include the border.
References _mesa_logbase2(), ASSERT, GL_TEXTURE_EXTERNAL_OES, MAX2, MAX3, and size.
Referenced by _mesa_init_teximage_fields(), and tex_storage_error_check().
GLint _mesa_get_texture_dimensions (GLenum target)
Return number of dimensions per mipmap level for the given texture target.
References _mesa_problem(), GL_TEXTURE_EXTERNAL_OES, and NULL.
void _mesa_init_teximage_fields (struct gl_context * ctx, struct gl_texture_image * img, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum internalFormat, gl_format format)
Initialize basic fields of the gl_texture_image struct.
Parameters
ctx GL context.
img texture image structure to be initialized.
width image width.
height image height.
depth image depth.
border image border.
internalFormat internal format.
format the actual hardware format (one of MESA_FORMAT_*)
Fills in the fields of img with the given information. Note: width, height and depth include the border.
References gl_texture_image::_BaseFormat, _mesa_base_tex_format(), _mesa_get_tex_max_num_levels(), _mesa_logbase2(), _mesa_problem(), ASSERT, gl_texture_image::Border, gl_texture_image::Depth, gl_texture_image::Depth2, gl_texture_image::DepthLog2, gl_texture_image::FixedSampleLocations, GL_TEXTURE_EXTERNAL_OES, gl_texture_image::Height, gl_texture_image::Height2, gl_texture_image::HeightLog2, gl_texture_image::InternalFormat, gl_texture_image::MaxNumLevels, NULL, gl_texture_image::NumSamples, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, gl_texture_image::Width, gl_texture_image::Width2, and gl_texture_image::WidthLog2.
Referenced by _mesa_get_fallback_texture(), _mesa_prepare_mipmap_level(), clear_texture_fields(), copyteximage(), initialize_texture_fields(), teximage(), and teximagemultisample().
static GLboolean _mesa_is_cube_face (GLenum target) inline static
Is the given value one of the 6 cube faces?
Referenced by _mesa_tex_target_to_face(), compressed_texture_error_check(), copytexture_error_check(), framebuffer_texture(), get_tex_memcpy(), and texture_error_check().
GLboolean _mesa_is_proxy_texture (GLenum target)
Test if a target is a proxy target.
Parameters
target texture target.
Returns
GL_TRUE if the target is a proxy target, GL_FALSE otherwise.
References NUM_TEXTURE_TARGETS.
Referenced by get_tex_level_parameter_image(), save_ColorTable(), teximage(), teximagemultisample(), and texstorage().
static GLboolean _mesa_is_zero_size_texture (const struct gl_texture_image * texImage) inline static
Is any of the dimensions of given texture equal to zero?
References gl_texture_image::Depth, gl_texture_image::Height, and gl_texture_image::Width.
Referenced by _mesa_GetnCompressedTexImageARB(), and _mesa_GetnTexImageARB().
GLboolean _mesa_legal_texture_dimensions (struct gl_context * ctx, GLenum target, GLint level, GLint width, GLint height, GLint depth, GLint border)
Check the width, height, depth and border of a texture image are legal.
Used by all the glTexImage, glCompressedTexImage and glCopyTexImage functions. The target and level parameters will have already been validated.
Returns
GL_TRUE if size is OK, GL_FALSE otherwise.
References _mesa_is_pow_two(), _mesa_problem(), gl_extensions::ARB_texture_non_power_of_two, gl_context::Const, gl_context::Extensions, gl_constants::Max3DTextureLevels, gl_constants::MaxArrayTextureLayers, gl_constants::MaxCubeTextureLevels, gl_constants::MaxTextureLevels, and gl_constants::MaxTextureRectSize.
Referenced by copyteximage(), teximage(), teximagemultisample(), and texstorage().
static void _mesa_lock_texture (struct gl_context * ctx, struct gl_texture_object * texObj) inline static
Lock a texture for updating.
See also _mesa_lock_context_textures().
References gl_context::Shared, gl_shared_state::TexMutex, gl_shared_state::TextureStateStamp, and void().
Referenced by _mesa_DeleteTextures(), _mesa_EGLImageTargetTexture2DOES(), _mesa_GenerateMipmap(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), _mesa_GetTexParameterfv(), _mesa_GetTexParameteriv(), compressed_tex_sub_image(), copyteximage(), copytexsubimage(), texbufferrange(), teximage(), and texsubimage().
GLint _mesa_max_texture_levels (struct gl_context * ctx, GLenum target)
Get the maximum number of allowed mipmap levels.
Parameters
ctx GL context.
target texture target.
Returns
the maximum number of allowed mipmap levels for the given texture target, or zero if passed a bad target.
See Also
gl_constants.
References _mesa_is_desktop_gl(), gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_multisample, gl_context::Const, gl_extensions::EXT_texture_array, gl_context::Extensions, GL_TEXTURE_EXTERNAL_OES, gl_constants::Max3DTextureLevels, gl_constants::MaxCubeTextureLevels, gl_constants::MaxTextureLevels, gl_extensions::MESA_texture_array, and gl_extensions::NV_texture_rectangle.
Referenced by _mesa_generate_mipmap(), _mesa_GetTexLevelParameteriv(), compressed_subtexture_error_check(), compressed_texture_error_check(), copytexsubimage_error_check(), copytexture_error_check(), framebuffer_texture(), getcompressedteximage_error_check(), getteximage_error_check(), tex_storage_error_check(), texsubimage_error_check(), and texture_error_check().
struct gl_texture_image* _mesa_new_texture_image (struct gl_context * ctx) read
Allocate a texture image structure.
Called via ctx->Driver.NewTextureImage() unless overriden by a device driver.
Returns
a pointer to gl_texture_image struct with all fields initialized to zero.
References CALLOC_STRUCT, and void().
struct gl_texture_image* _mesa_select_tex_image (struct gl_context * ctx, const struct gl_texture_object * texObj, GLenum target, GLint level) read
Get a texture image pointer from a texture object, given a texture target and mipmap level.
The target and level parameters should have already been error-checked.
Parameters
ctx GL context.
texObj texture unit.
target texture target.
level image level.
Returns
pointer to the texture image structure, or NULL on failure.
References _mesa_tex_target_to_face(), ASSERT, gl_texture_object::Image, and MAX_TEXTURE_LEVELS.
Referenced by _mesa_choose_texture_format(), _mesa_generate_mipmap(), _mesa_GenerateMipmap(), _mesa_get_tex_image(), _mesa_GetFramebufferAttachmentParameteriv(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), compressed_subtexture_error_check(), compressed_tex_sub_image(), copytexsubimage(), copytexsubimage_error_check(), generate_mipmap_compressed(), generate_mipmap_uncompressed(), get_tex_level_parameter_image(), getcompressedteximage_error_check(), getteximage_error_check(), texsubimage(), and texsubimage_error_check().
struct gl_texture_object* _mesa_select_tex_object (struct gl_context * ctx, const struct gl_texture_unit * texUnit, GLenum target) read
Get the texture object that corresponds to the target of the given texture unit.
The target should have already been checked for validity.
Parameters
ctx GL context.
texUnit texture unit.
target texture target.
Returns
pointer to the texture object on success, or NULL on failure.
References _mesa_problem(), gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_multisample, gl_texture_unit::CurrentTex, gl_extensions::EXT_texture_array, gl_context::Extensions, GL_TEXTURE_EXTERNAL_OES, gl_extensions::MESA_texture_array, NULL, gl_extensions::NV_texture_rectangle, gl_extensions::OES_EGL_image_external, gl_texture_attrib::ProxyTex, gl_context::Texture, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_BUFFER_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, TEXTURE_EXTERNAL_INDEX, and TEXTURE_RECT_INDEX.
Referenced by _mesa_get_current_tex_object(), and _mesa_GetTexLevelParameteriv().
GLboolean _mesa_test_proxy_teximage (struct gl_context * ctx, GLenum target, GLint level, gl_format format, GLint width, GLint height, GLint depth, GLint border)
This is the fallback for Driver.TestProxyTexImage() for doing device- specific texture image size checks.
A hardware driver might override this function if, for example, the max 3D texture size is 512x512x64 (i.e. not a cube).
Note that width, height, depth == 0 is not an error. However, a texture with zero width/height/depth will be considered "incomplete" and texturing will effectively be disabled.
Parameters
target any texture target/type
level as passed to glTexImage
format the MESA_FORMAT_x for the tex image
width as passed to glTexImage
height as passed to glTexImage
depth as passed to glTexImage
border as passed to glTexImage
Returns
GL_TRUE if the image is acceptable, GL_FALSE if not acceptable.
References _mesa_format_image_size64(), _mesa_num_tex_faces(), gl_context::Const, and gl_constants::MaxTextureMbytes.
GLuint _mesa_tex_target_to_face (GLenum target)
For cube map faces, return a face index in [0,5].
For other targets return 0;
References _mesa_is_cube_face().
Referenced by _mesa_select_tex_image(), _mesa_set_texture_attachment(), copyteximage(), framebuffer_texture(), set_tex_image(), and teximage().
void GLAPIENTRY _mesa_TexBuffer (GLenum target, GLenum internalFormat, GLuint buffer)
GL_ARB_texture_buffer_object.
References _mesa_error(), _mesa_lookup_bufferobj(), API_OPENGL_CORE, and texbufferrange().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexBufferRange (GLenum target, GLenum internalFormat, GLuint buffer, GLintptr offset, GLsizeiptr size)
GL_ARB_texture_buffer_range.
References _mesa_error(), _mesa_lookup_bufferobj(), API_OPENGL_CORE, gl_buffer_object::Size, and texbufferrange().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexImage1D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References teximage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References teximage().
Referenced by _mesa_cpal_compressed_teximage2d(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexImage2DMultisample (GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References teximagemultisample().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexImage3D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References teximage().
Referenced by _mesa_initialize_exec_table(), and _mesa_TexImage3DEXT().
void GLAPIENTRY _mesa_TexImage3DEXT (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
References _mesa_TexImage3D().
void GLAPIENTRY _mesa_TexImage3DMultisample (GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References teximagemultisample().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations)
References teximagemultisample().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations)
References teximagemultisample().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels)
References texsubimage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
References texsubimage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
References texsubimage().
Referenced by _mesa_initialize_exec_table().
static void _mesa_unlock_texture (struct gl_context * ctx, struct gl_texture_object * texObj) inline static
References gl_context::Shared, gl_shared_state::TexMutex, and void().
Referenced by _mesa_DeleteTextures(), _mesa_EGLImageTargetTexture2DOES(), _mesa_GenerateMipmap(), _mesa_GetnCompressedTexImageARB(), _mesa_GetnTexImageARB(), _mesa_GetTexParameterfv(), _mesa_GetTexParameteriv(), compressed_tex_sub_image(), copyteximage(), copytexsubimage(), texbufferrange(), teximage(), and texsubimage().
void _mesa_update_fbo_texture (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint face, GLuint level)
When a texture image is specified we have to check if it's bound to any framebuffer objects (render to texture) in order to detect changes in size or format since that effects FBO completeness.
Any FBOs rendering into the texture must be re-validated.
References _mesa_HashWalk(), gl_texture_object::_RenderToTexture, check_rtt_cb(), cb_info::ctx, cb_info::face, gl_shared_state::FrameBuffers, cb_info::level, gl_context::Shared, and cb_info::texObj.
Referenced by _mesa_prepare_mipmap_level(), copyteximage(), teximage(), and teximagemultisample().