Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texobj.h File Reference
Texture object management.
#include "compiler.h"
#include "glheader.h"
#include "mtypes.h"
#include "samplerobj.h"
Functions
Internal functions
struct gl_texture_object * _mesa_lookup_texture (struct gl_context *ctx, GLuint id)
Return the gl_texture_object for a given ID.
struct gl_texture_object * _mesa_new_texture_object (struct gl_context *ctx, GLuint name, GLenum target)
Allocate and initialize a new texture object.
void _mesa_initialize_texture_object (struct gl_texture_object *obj, GLuint name, GLenum target)
Initialize a new texture object to default values.
void _mesa_delete_texture_object (struct gl_context *ctx, struct gl_texture_object *obj)
Deallocate a texture object struct.
void _mesa_copy_texture_object (struct gl_texture_object *dest, const struct gl_texture_object *src)
Copy texture object state from one texture object to another.
void _mesa_clear_texture_object (struct gl_context *ctx, struct gl_texture_object *obj)
Free all texture images of the given texture object.
void _mesa_reference_texobj_ (struct gl_texture_object **ptr, struct gl_texture_object *tex)
Reference (or unreference) a texture object.
static void _mesa_reference_texobj (struct gl_texture_object **ptr, struct gl_texture_object *tex)
static GLuint _mesa_num_tex_faces (GLenum target)
Return number of faces for a texture target.
static GLboolean _mesa_is_texture_complete (const struct gl_texture_object *texObj, const struct gl_sampler_object *sampler)
Is the texture "complete" with respect to the given sampler state?
void _mesa_test_texobj_completeness (const struct gl_context *ctx, struct gl_texture_object *obj)
Examine a texture object to determine if it is complete.
GLboolean _mesa_cube_complete (const struct gl_texture_object *texObj)
Check if the given cube map texture is "cube complete" as defined in the OpenGL specification.
void _mesa_dirty_texobj (struct gl_context *ctx, struct gl_texture_object *texObj, GLboolean invalidate_state)
Mark a texture object dirty.
struct gl_texture_object * _mesa_get_fallback_texture (struct gl_context *ctx, gl_texture_index tex)
Return pointer to a default/fallback texture of the given type/target.
GLuint _mesa_total_texture_memory (struct gl_context *ctx)
Compute total size (in bytes) of all textures for the given context.
void _mesa_unlock_context_textures (struct gl_context *ctx)
void _mesa_lock_context_textures (struct gl_context *ctx)
Simplest implementation of texture locking: grab the shared tex mutex.
API functions
void GLAPIENTRY _mesa_GenTextures (GLsizei n, GLuint *textures)
Generate texture names.
void GLAPIENTRY _mesa_DeleteTextures (GLsizei n, const GLuint *textures)
Delete named textures.
void GLAPIENTRY _mesa_BindTexture (GLenum target, GLuint texture)
Bind a named texture to a texturing target.
void GLAPIENTRY _mesa_PrioritizeTextures (GLsizei n, const GLuint *textures, const GLclampf *priorities)
Set texture priorities.
GLboolean GLAPIENTRY _mesa_AreTexturesResident (GLsizei n, const GLuint *textures, GLboolean *residences)
See if textures are loaded in texture memory.
GLboolean GLAPIENTRY _mesa_IsTexture (GLuint texture)
See if a name corresponds to a texture.
void GLAPIENTRY _mesa_InvalidateTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_InvalidateTexImage (GLuint texture, GLint level)
Detailed Description
Texture object management.
Function Documentation
GLboolean GLAPIENTRY _mesa_AreTexturesResident (GLsizei n, const GLuint * texName, GLboolean * residences)
See if textures are loaded in texture memory.
Parameters
n number of textures to query.
texName array with the texture names.
residences array which will hold the residence status.
Returns
GL_TRUE if all textures are resident and residences is left unchanged,
Note: we assume all textures are always resident
References _mesa_debug(), _mesa_error(), _mesa_lookup_texture(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindTexture (GLenum target, GLuint texName)
Bind a named texture to a texturing target.
Parameters
target texture target.
texName texture name.
See Also
glBindTexture().
Determines the old texture object bound and returns immediately if rebinding the same texture. Get the current texture which is either a default texture if name is null, a named texture from the hash, or a new texture if the given texture name is new. Increments its reference count, binds it, and calls dd_function_table::BindTexture. Decrements the old texture reference count and deletes it if it reaches zero.
References _mesa_debug(), _mesa_error(), _mesa_get_current_tex_unit(), _mesa_HashInsert(), _mesa_lookup_enum_by_nr(), _mesa_lookup_texture(), _mesa_reference_texobj(), _NEW_TEXTURE, gl_context::API, API_OPENGL_CORE, ASSERT, dd_function_table::BindTexture, gl_texture_unit::CurrentTex, gl_shared_state::DefaultTex, gl_context::Driver, finish_texture_init(), FLUSH_VERTICES, MESA_VERBOSE, gl_shared_state::Mutex, dd_function_table::NewTextureObject, NULL, NUM_TEXTURE_TARGETS, gl_shared_state::RefCount, gl_context::Shared, gl_texture_object::Target, target_enum_to_index(), gl_shared_state::TexObjects, valid_texture_object(), VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table(), and pop_texture_group().
void _mesa_clear_texture_object (struct gl_context * ctx, struct gl_texture_object * texObj)
Free all texture images of the given texture object.
Parameters
ctx GL context.
t texture object.
See Also
_mesa_clear_texture_image().
References _mesa_clear_texture_image(), gl_texture_object::Image, MAX_FACES, MAX_TEXTURE_LEVELS, and gl_texture_object::Target.
void _mesa_copy_texture_object (struct gl_texture_object * dest, const struct gl_texture_object * src)
Copy texture object state from one texture object to another.
Use for glPush/PopAttrib.
Parameters
dest destination texture object.
src source texture object.
References gl_texture_object::_BaseComplete, gl_texture_object::_MaxLambda, gl_texture_object::_MaxLevel, gl_texture_object::_MipmapComplete, gl_texture_object::_Swizzle, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, COPY_4V, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_color_union::f, gl_texture_object::GenerateMipmap, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Name, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::Swizzle, gl_texture_object::Target, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_PushAttrib().
GLboolean _mesa_cube_complete (const struct gl_texture_object * texObj)
Check if the given cube map texture is "cube complete" as defined in the OpenGL specification.
References gl_texture_object::BaseLevel, gl_texture_image::Height, gl_texture_object::Image, MAX_TEXTURE_LEVELS, gl_texture_object::Target, gl_texture_image::TexFormat, and gl_texture_image::Width.
Referenced by _mesa_GenerateMipmap().
void _mesa_delete_texture_object (struct gl_context * ctx, struct gl_texture_object * texObj)
Deallocate a texture object struct.
It should have already been removed from the texture object pool. Called via ctx->Driver.DeleteTexture() if not overriden by a driver.
Parameters
shared the shared GL state to which the object belongs.
texObj the texture object to delete.
References _mesa_reference_buffer_object(), gl_texture_object::BufferObject, dd_function_table::DeleteTextureImage, gl_context::Driver, gl_texture_object::Image, MAX_TEXTURE_LEVELS, gl_texture_object::Mutex, NULL, and gl_texture_object::Target.
void GLAPIENTRY _mesa_DeleteTextures (GLsizei n, const GLuint * textures)
Delete named textures.
Parameters
n number of textures to be deleted.
textures array of texture IDs to be deleted.
See Also
glDeleteTextures().
If we're about to delete a texture that's currently bound to any texture unit, unbind the texture first. Decrement the reference count on the texture object and delete it if it's zero. Recall that texture objects can be shared among several rendering contexts.
References _mesa_debug(), _mesa_HashRemove(), _mesa_lock_texture(), _mesa_lookup_texture(), _mesa_reference_texobj(), _mesa_unlock_texture(), _NEW_TEXTURE, FLUSH_VERTICES, MESA_VERBOSE, gl_shared_state::Mutex, gl_texture_object::Name, gl_context::NewState, NULL, gl_context::Shared, gl_shared_state::TexObjects, unbind_texobj_from_fbo(), unbind_texobj_from_texunits(), VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table().
void _mesa_dirty_texobj (struct gl_context * ctx, struct gl_texture_object * texObj, GLboolean invalidate_state)
Mark a texture object dirty.
It forces the object to be incomplete and optionally forces the context to re-validate its state.
Parameters
ctx GL context.
texObj texture object.
invalidate_state also invalidate context state.
References gl_texture_object::_BaseComplete, gl_texture_object::_MipmapComplete, _NEW_TEXTURE, and gl_context::NewState.
Referenced by _mesa_EGLImageTargetTexture2DOES(), copyteximage(), incomplete(), and teximage().
void GLAPIENTRY _mesa_GenTextures (GLsizei n, GLuint * textures)
Generate texture names.
Parameters
n number of texture names to be generated.
textures an array in which will hold the generated texture names.
See Also
glGenTextures().
Calls _mesa_HashFindFreeKeyBlock() to find a block of free texture IDs which are stored in textures. Corresponding empty texture objects are also generated.
References _mesa_debug(), _mesa_error(), _mesa_HashFindFreeKeyBlock(), _mesa_HashInsert(), gl_context::Driver, MESA_VERBOSE, gl_shared_state::Mutex, gl_texture_object::Name, dd_function_table::NewTextureObject, gl_context::Shared, gl_shared_state::TexObjects, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table().
struct gl_texture_object* _mesa_get_fallback_texture (struct gl_context * ctx, gl_texture_index tex) read
Return pointer to a default/fallback texture of the given type/target.
The texture is an RGBA texture with all texels = (0,0,0,1). That's the value a GLSL sampler should get when sampling from an incomplete texture.
References gl_texture_object::_BaseComplete, _mesa_get_tex_image(), _mesa_init_teximage_fields(), _mesa_test_texobj_completeness(), gl_texture_object::_MipmapComplete, dd_function_table::ChooseTextureFormat, gl_context::DefaultPacking, gl_context::Driver, gl_shared_state::FallbackTex, GL_TEXTURE_EXTERNAL_OES, GLubyte, gl_sampler_object::MagFilter, gl_sampler_object::MinFilter, dd_function_table::NewTextureObject, NULL, gl_texture_object::RefCount, gl_texture_object::Sampler, gl_context::Shared, dd_function_table::TexImage, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_BUFFER_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, TEXTURE_EXTERNAL_INDEX, and TEXTURE_RECT_INDEX.
Referenced by update_texture_state().
void _mesa_initialize_texture_object (struct gl_texture_object * obj, GLuint name, GLenum target)
Initialize a new texture object to default values.
Parameters
obj the texture object
name the texture name
target the texture target
References gl_texture_object::_BufferObjectFormat, gl_texture_object::_Swizzle, ASSERT, gl_texture_object::BaseLevel, gl_texture_object::BufferObjectFormat, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, GL_TEXTURE_EXTERNAL_OES, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, MESA_FORMAT_L8, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Mutex, gl_texture_object::Name, gl_texture_object::Priority, gl_texture_object::RefCount, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::Swizzle, gl_texture_object::Target, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_new_texture_object().
void GLAPIENTRY _mesa_InvalidateTexImage (GLuint texture, GLint level)
References _mesa_debug(), invalidate_tex_image_error_check(), MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_InvalidateTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth)
References _mesa_debug(), _mesa_error(), gl_texture_image::Border, gl_texture_image::Depth, gl_texture_image::Height, gl_texture_object::Image, invalidate_tex_image_error_check(), MESA_VERBOSE, gl_texture_object::Target, VERBOSE_API, VERBOSE_TEXTURE, and gl_texture_image::Width.
Referenced by _mesa_initialize_exec_table().
static GLboolean _mesa_is_texture_complete (const struct gl_texture_object * texObj, const struct gl_sampler_object * sampler) inline static
Is the texture "complete" with respect to the given sampler state?
References gl_texture_object::_BaseComplete, gl_texture_object::_IsIntegerFormat, _mesa_is_mipmap_filter(), gl_texture_object::_MipmapComplete, gl_sampler_object::MagFilter, and gl_sampler_object::MinFilter.
Referenced by update_texture_state().
GLboolean GLAPIENTRY _mesa_IsTexture (GLuint texture)
See if a name corresponds to a texture.
Parameters
texture texture name.
Returns
GL_TRUE if texture name corresponds to a texture, or GL_FALSE otherwise.
See Also
glIsTexture().
Calls _mesa_HashLookup().
References _mesa_debug(), _mesa_lookup_texture(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, MESA_VERBOSE, gl_texture_object::Target, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table().
void _mesa_lock_context_textures (struct gl_context * ctx)
Simplest implementation of texture locking: grab the shared tex mutex.
Examine the shared context state timestamp and if there has been a change, set the appropriate bits in ctx->NewState.
This is used to deal with synchronizing things when a texture object is used/modified by different contexts (or threads) which are sharing the texture.
See also _mesa_lock/unlock_texture() in teximage.h
References _NEW_TEXTURE, gl_context::NewState, gl_context::Shared, gl_shared_state::TexMutex, gl_shared_state::TextureStateStamp, and gl_context::TextureStateTimestamp.
Referenced by _mesa_copy_texture_state(), _mesa_PushAttrib(), _mesa_update_state(), and pop_texture_group().
struct gl_texture_object* _mesa_lookup_texture (struct gl_context * ctx, GLuint id) read
Return the gl_texture_object for a given ID.
References _mesa_HashLookup(), gl_context::Shared, and gl_shared_state::TexObjects.
Referenced by _mesa_AreTexturesResident(), _mesa_BindTexture(), _mesa_DeleteTextures(), _mesa_dump_texture(), _mesa_IsTexture(), _mesa_PrioritizeTextures(), framebuffer_texture(), get_texture_object_parameteriv(), invalidate_tex_image_error_check(), texture_object_purgeable(), and texture_object_unpurgeable().
struct gl_texture_object* _mesa_new_texture_object (struct gl_context * ctx, GLuint name, GLenum target) read
Allocate and initialize a new texture object.
But don't put it into the texture object hash table.
Called via ctx->Driver.NewTextureObject, unless overridden by a device driver.
Parameters
shared the shared GL state structure to contain the texture object
name integer name for the texture object
target either GL_TEXTURE_1D, GL_TEXTURE_2D, GL_TEXTURE_3D, GL_TEXTURE_CUBE_MAP_ARB or GL_TEXTURE_RECTANGLE_NV. zero is ok for the sake of GenTextures()
Returns
pointer to new texture object.
References _mesa_initialize_texture_object(), MALLOC_STRUCT, and void().
static GLuint _mesa_num_tex_faces (GLenum target) inline static
Return number of faces for a texture target.
This will be 6 for cube maps (and cube map arrays) and 1 otherwise. NOTE: this function is not used for cube map arrays which operate more like 2D arrays than cube maps.
Referenced by _mesa_alloc_texture_storage(), _mesa_prepare_mipmap_level(), _mesa_test_proxy_teximage(), _mesa_test_texobj_completeness(), clear_texture_fields(), initialize_texture_fields(), and texture_size().
void GLAPIENTRY _mesa_PrioritizeTextures (GLsizei n, const GLuint * texName, const GLclampf * priorities)
Set texture priorities.
Parameters
n number of textures.
texName texture names.
priorities corresponding texture priorities.
See Also
glPrioritizeTextures().
Looks up each texture in the hash, clamps the corresponding priority between 0.0 and 1.0, and calls dd_function_table::PrioritizeTexture.
References _mesa_debug(), _mesa_error(), _mesa_lookup_texture(), _NEW_TEXTURE, CLAMP, F, FLUSH_VERTICES, MESA_VERBOSE, gl_context::NewState, gl_texture_object::Priority, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table().
static void _mesa_reference_texobj (struct gl_texture_object ** ptr, struct gl_texture_object * tex) inline static
References _mesa_reference_texobj_().
Referenced by _mesa_BindTexture(), _mesa_copy_texture_state(), _mesa_DeleteTextures(), _mesa_free_attrib_data(), _mesa_free_framebuffer_data(), _mesa_free_texture_data(), _mesa_PushAttrib(), _mesa_remove_attachment(), _mesa_set_texture_attachment(), _mesa_update_default_objects_texture(), init_texture_unit(), pop_texture_group(), reuse_framebuffer_texture_attachment(), unbind_texobj_from_texunits(), and update_texture_state().
void _mesa_reference_texobj_ (struct gl_texture_object ** ptr, struct gl_texture_object * tex)
Reference (or unreference) a texture object.
If '*ptr', decrement *ptr's refcount (and delete if it becomes zero). If 'tex' is non-null, increment its refcount. This is normally only called from the _mesa_reference_texobj() macro when there's a real pointer change.
References _mesa_problem(), ASSERT, dd_function_table::DeleteTexture, gl_context::Driver, gl_texture_object::Mutex, NULL, gl_texture_object::RefCount, valid_texture_object(), and void().
Referenced by _mesa_reference_texobj().
void _mesa_test_texobj_completeness (const struct gl_context * ctx, struct gl_texture_object * t)
Examine a texture object to determine if it is complete.
The gl_texture_object::Complete flag will be set to GL_TRUE or GL_FALSE accordingly.
Parameters
ctx GL context.
t texture object.
According to the texture target, verifies that each of the mipmaps is present and has the expected size.
References gl_texture_object::_BaseComplete, gl_texture_object::_IsIntegerFormat, gl_texture_object::_MaxLambda, gl_texture_object::_MaxLevel, _mesa_get_format_datatype(), _mesa_num_tex_faces(), _mesa_problem(), gl_texture_object::_MipmapComplete, ASSERT, BASE, gl_texture_object::BaseLevel, gl_texture_image::Border, gl_context::Const, gl_texture_image::Depth, gl_texture_image::Depth2, GL_TEXTURE_EXTERNAL_OES, gl_texture_image::Height, gl_texture_image::Height2, gl_texture_object::Image, gl_texture_object::Immutable, incomplete(), gl_constants::Max3DTextureLevels, MAX_TEXTURE_LEVELS, gl_constants::MaxCubeTextureLevels, gl_texture_object::MaxLevel, gl_texture_image::MaxNumLevels, gl_constants::MaxTextureLevels, MIN2, MIPMAP, NULL, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::Width, and gl_texture_image::Width2.
Referenced by _mesa_get_fallback_texture(), and update_texture_state().
GLuint _mesa_total_texture_memory (struct gl_context * ctx)
Compute total size (in bytes) of all textures for the given context.
For debugging purposes.
References _mesa_HashWalk(), count_tex_size(), gl_shared_state::DefaultTex, NUM_TEXTURE_TARGETS, gl_context::Shared, gl_shared_state::TexObjects, and texture_size().
void _mesa_unlock_context_textures (struct gl_context * ctx)
References gl_context::Shared, gl_shared_state::TexMutex, gl_shared_state::TextureStateStamp, and gl_context::TextureStateTimestamp.
Referenced by _mesa_copy_texture_state(), _mesa_PushAttrib(), _mesa_update_state(), and pop_texture_group().