Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texparam.h File Reference
#include "main/glheader.h"
Functions
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint *params)
New in GL 3.0.
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint *params)
New in GL 3.0.
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint *params)
Set tex parameter to integer value(s).
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint *params)
Set tex parameter to unsigned integer value(s).
Function Documentation
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat * params)
References _mesa_GetTexLevelParameteriv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_current_tex_unit(), _mesa_max_texture_levels(), _mesa_select_tex_object(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), and legal_get_tex_level_parameter_target().
Referenced by _mesa_GetTexLevelParameterfv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_get_clamp_fragment_color(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_lock_texture(), _mesa_unlock_texture(), _mesa_update_state_locked(), _NEW_BUFFERS, _NEW_FRAG_CLAMP, API_OPENGL_COMPAT, API_OPENGLES, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, CLAMP, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, ENUM_TO_FLOAT, gl_color_union::f, gl_texture_object::GenerateMipmap, get_texobj(), GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES, GL_TEXTURE_CROP_RECT_OES, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::Swizzle, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_GetTexParameterxv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint * params)
New in GL 3.0.
References _mesa_GetTexParameteriv(), gl_sampler_object::BorderColor, COPY_4V, get_texobj(), gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint * params)
New in GL 3.0.
References _mesa_GetTexParameteriv(), gl_sampler_object::BorderColor, COPY_4V, get_texobj(), GL_TEXTURE_CROP_RECT_OES, gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_lock_texture(), _mesa_unlock_texture(), API_OPENGL_COMPAT, API_OPENGLES, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, CLAMP, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, COPY_4V, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_color_union::f, FLOAT_TO_INT, gl_texture_object::GenerateMipmap, get_texobj(), GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES, GL_TEXTURE_CROP_RECT_OES, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::Swizzle, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_GetTexParameterIiv(), _mesa_GetTexParameterIuiv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
References get_texobj(), set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), _mesa_TexParameterx(), and pop_texture_group().
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
References get_texobj(), GL_TEXTURE_CROP_RECT_OES, set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), _mesa_TexParameterxv(), and pop_texture_group().
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
References get_texobj(), set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), and pop_texture_group().
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint * params)
Set tex parameter to integer value(s).
Primarily intended to set integer-valued texture border color (for integer-valued textures). New in GL 3.0.
References _mesa_TexParameteriv(), _NEW_TEXTURE, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, get_texobj(), gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint * params)
Set tex parameter to unsigned integer value(s).
Primarily intended to set uint-valued texture border color (for integer-valued textures). New in GL 3.0
References _mesa_TexParameteriv(), _NEW_TEXTURE, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, get_texobj(), gl_texture_object::Sampler, and gl_color_union::ui.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint * params)
References get_texobj(), GL_TEXTURE_CROP_RECT_OES, INT_TO_FLOAT, set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), _mesa_TexParameterIiv(), and _mesa_TexParameterIuiv().