Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texparam.c File Reference
glTexParameter-related functions
#include <stdbool.h>
#include "main/glheader.h"
#include "main/blend.h"
#include "main/colormac.h"
#include "main/context.h"
#include "main/enums.h"
#include "main/formats.h"
#include "main/glformats.h"
#include "main/macros.h"
#include "main/mtypes.h"
#include "main/state.h"
#include "main/texcompress.h"
#include "main/texobj.h"
#include "main/texparam.h"
#include "main/teximage.h"
#include "main/texstate.h"
#include "program/prog_instruction.h"
Functions
static GLboolean validate_texture_wrap_mode (struct gl_context *ctx, GLenum target, GLenum wrap)
Check if a coordinate wrap mode is supported for the texture target.
static struct gl_texture_object * get_texobj (struct gl_context *ctx, GLenum target, GLboolean get)
Get current texture object for given target.
static GLint comp_to_swizzle (GLenum comp)
Convert GL_RED/GREEN/BLUE/ALPHA/ZERO/ONE to SWIZZLE_X/Y/Z/W/ZERO/ONE.
static void set_swizzle_component (GLuint *swizzle, GLuint comp, GLuint swz)
static void flush (struct gl_context *ctx)
This is called just prior to changing any texture object state which will not effect texture completeness.
static void incomplete (struct gl_context *ctx, struct gl_texture_object *texObj)
This is called just prior to changing any texture object state which can effect texture completeness (texture base level, max level).
static GLboolean target_allows_setting_sampler_parameters (GLenum target)
static GLboolean set_tex_parameteri (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLint *params)
Set an integer-valued texture parameter.
static GLboolean set_tex_parameterf (struct gl_context *ctx, struct gl_texture_object *texObj, GLenum pname, const GLfloat *params)
Set a float-valued texture parameter.
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint *params)
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint *params)
Set tex parameter to integer value(s).
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint *params)
Set tex parameter to unsigned integer value(s).
static GLboolean legal_get_tex_level_parameter_target (struct gl_context *ctx, GLenum target)
static void get_tex_level_parameter_image (struct gl_context *ctx, const struct gl_texture_object *texObj, GLenum target, GLint level, GLenum pname, GLint *params)
static void get_tex_level_parameter_buffer (struct gl_context *ctx, const struct gl_texture_object *texObj, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint *params)
New in GL 3.0.
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint *params)
New in GL 3.0.
Detailed Description
glTexParameter-related functions
Function Documentation
void GLAPIENTRY _mesa_GetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat * params)
References _mesa_GetTexLevelParameteriv().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_current_tex_unit(), _mesa_max_texture_levels(), _mesa_select_tex_object(), get_tex_level_parameter_buffer(), get_tex_level_parameter_image(), and legal_get_tex_level_parameter_target().
Referenced by _mesa_GetTexLevelParameterfv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
References _mesa_error(), _mesa_get_clamp_fragment_color(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_lock_texture(), _mesa_unlock_texture(), _mesa_update_state_locked(), _NEW_BUFFERS, _NEW_FRAG_CLAMP, API_OPENGL_COMPAT, API_OPENGLES, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, CLAMP, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, ENUM_TO_FLOAT, gl_color_union::f, gl_texture_object::GenerateMipmap, get_texobj(), GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES, GL_TEXTURE_CROP_RECT_OES, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::Swizzle, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_GetTexParameterxv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameterIiv (GLenum target, GLenum pname, GLint * params)
New in GL 3.0.
References _mesa_GetTexParameteriv(), gl_sampler_object::BorderColor, COPY_4V, get_texobj(), gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameterIuiv (GLenum target, GLenum pname, GLuint * params)
New in GL 3.0.
References _mesa_GetTexParameteriv(), gl_sampler_object::BorderColor, COPY_4V, get_texobj(), GL_TEXTURE_CROP_RECT_OES, gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTexParameteriv (GLenum target, GLenum pname, GLint * params)
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), _mesa_lock_texture(), _mesa_unlock_texture(), API_OPENGL_COMPAT, API_OPENGLES, gl_texture_object::BaseLevel, gl_sampler_object::BorderColor, CLAMP, gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, COPY_4V, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_color_union::f, FLOAT_TO_INT, gl_texture_object::GenerateMipmap, get_texobj(), GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES, GL_TEXTURE_CROP_RECT_OES, gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, gl_sampler_object::LodBias, gl_sampler_object::MagFilter, gl_sampler_object::MaxAnisotropy, gl_texture_object::MaxLevel, gl_sampler_object::MaxLod, gl_sampler_object::MinFilter, gl_sampler_object::MinLod, gl_texture_object::Priority, gl_texture_object::RequiredTextureImageUnits, gl_texture_object::Sampler, gl_sampler_object::sRGBDecode, gl_texture_object::Swizzle, gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_GetTexParameterIiv(), _mesa_GetTexParameterIuiv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexParameterf (GLenum target, GLenum pname, GLfloat param)
References get_texobj(), set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), _mesa_TexParameterx(), and pop_texture_group().
void GLAPIENTRY _mesa_TexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
References get_texobj(), GL_TEXTURE_CROP_RECT_OES, set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), _mesa_TexParameterxv(), and pop_texture_group().
void GLAPIENTRY _mesa_TexParameteri (GLenum target, GLenum pname, GLint param)
References get_texobj(), set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), and pop_texture_group().
void GLAPIENTRY _mesa_TexParameterIiv (GLenum target, GLenum pname, const GLint * params)
Set tex parameter to integer value(s).
Primarily intended to set integer-valued texture border color (for integer-valued textures). New in GL 3.0.
References _mesa_TexParameteriv(), _NEW_TEXTURE, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, get_texobj(), gl_color_union::i, and gl_texture_object::Sampler.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexParameterIuiv (GLenum target, GLenum pname, const GLuint * params)
Set tex parameter to unsigned integer value(s).
Primarily intended to set uint-valued texture border color (for integer-valued textures). New in GL 3.0
References _mesa_TexParameteriv(), _NEW_TEXTURE, gl_sampler_object::BorderColor, COPY_4V, FLUSH_VERTICES, get_texobj(), gl_texture_object::Sampler, and gl_color_union::ui.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexParameteriv (GLenum target, GLenum pname, const GLint * params)
References get_texobj(), GL_TEXTURE_CROP_RECT_OES, INT_TO_FLOAT, set_tex_parameterf(), and set_tex_parameteri().
Referenced by _mesa_initialize_exec_table(), _mesa_TexParameterIiv(), and _mesa_TexParameterIuiv().
static GLint comp_to_swizzle (GLenum comp) static
Convert GL_RED/GREEN/BLUE/ALPHA/ZERO/ONE to SWIZZLE_X/Y/Z/W/ZERO/ONE.
Returns
-1 if error.
Referenced by set_tex_parameteri().
static void flush (struct gl_context * ctx) inline static
This is called just prior to changing any texture object state which will not effect texture completeness.
References _NEW_TEXTURE, and FLUSH_VERTICES.
Referenced by set_tex_parameterf(), and set_tex_parameteri().
static void get_tex_level_parameter_buffer (struct gl_context * ctx, const struct gl_texture_object * texObj, GLenum pname, GLint * params) static
References gl_texture_object::_BufferObjectFormat, _mesa_base_format_has_channel(), _mesa_error(), _mesa_get_format_base_format(), _mesa_get_format_bits(), _mesa_get_format_datatype(), _mesa_lookup_enum_by_nr(), gl_extensions::ARB_texture_buffer_range, gl_extensions::ARB_texture_float, gl_texture_object::BufferObject, gl_texture_object::BufferObjectFormat, gl_texture_object::BufferOffset, gl_texture_object::BufferSize, gl_context::Extensions, MIN2, gl_buffer_object::Name, and gl_buffer_object::Size.
Referenced by _mesa_GetTexLevelParameteriv().
static void get_tex_level_parameter_image (struct gl_context * ctx, const struct gl_texture_object * texObj, GLenum target, GLint level, GLenum pname, GLint * params) static
References gl_texture_image::_BaseFormat, _mesa_base_format_has_channel(), _mesa_compressed_format_to_glenum(), _mesa_error(), _mesa_format_image_size(), _mesa_get_format_bits(), _mesa_get_format_datatype(), _mesa_gl_compressed_format_base_format(), _mesa_is_format_compressed(), _mesa_is_proxy_texture(), _mesa_lookup_enum_by_nr(), _mesa_select_tex_image(), gl_extensions::ARB_depth_texture, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_multisample, gl_texture_image::Border, gl_texture_image::Depth, gl_extensions::EXT_packed_depth_stencil, gl_extensions::EXT_texture_shared_exponent, gl_context::Extensions, gl_texture_image::FixedSampleLocations, gl_texture_image::Height, gl_texture_image::InternalFormat, MESA_FORMAT_NONE, MESA_FORMAT_RGB9_E5_FLOAT, MIN2, NULL, gl_texture_image::NumSamples, gl_texture_image::TexFormat, gl_context::Version, and gl_texture_image::Width.
Referenced by _mesa_GetTexLevelParameteriv().
static struct gl_texture_object* get_texobj (struct gl_context * ctx, GLenum target, GLboolean get) static read
Get current texture object for given target.
Return NULL if any error (and record the error). Note that this is different from _mesa_select_tex_object() in that proxy targets are not accepted. Only the glGetTexLevelParameter() functions accept proxy targets.
References _mesa_error(), _mesa_get_current_tex_unit(), _mesa_is_desktop_gl(), _mesa_is_gles(), _mesa_is_gles3(), gl_context::API, API_OPENGLES, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::ARB_texture_storage_multisample, gl_context::Const, gl_texture_unit::CurrentTex, gl_texture_attrib::CurrentUnit, gl_extensions::EXT_texture_array, gl_context::Extensions, GL_TEXTURE_EXTERNAL_OES, gl_constants::MaxCombinedTextureImageUnits, gl_extensions::MESA_texture_array, NULL, gl_extensions::NV_texture_rectangle, gl_extensions::OES_EGL_image_external, gl_context::Texture, TEXTURE_1D_ARRAY_INDEX, TEXTURE_1D_INDEX, TEXTURE_2D_ARRAY_INDEX, TEXTURE_2D_INDEX, TEXTURE_2D_MULTISAMPLE_ARRAY_INDEX, TEXTURE_2D_MULTISAMPLE_INDEX, TEXTURE_3D_INDEX, TEXTURE_CUBE_ARRAY_INDEX, TEXTURE_CUBE_INDEX, TEXTURE_EXTERNAL_INDEX, and TEXTURE_RECT_INDEX.
Referenced by _mesa_GetTexParameterfv(), _mesa_GetTexParameterIiv(), _mesa_GetTexParameterIuiv(), _mesa_GetTexParameteriv(), _mesa_TexParameterf(), _mesa_TexParameterfv(), _mesa_TexParameteri(), _mesa_TexParameterIiv(), _mesa_TexParameterIuiv(), and _mesa_TexParameteriv().
static void incomplete (struct gl_context * ctx, struct gl_texture_object * texObj) inline static
This is called just prior to changing any texture object state which can effect texture completeness (texture base level, max level).
Any pending rendering will be flushed out, we'll set the _NEW_TEXTURE state flag and then mark the texture object as 'incomplete' so that any per-texture derived state gets recomputed.
References _mesa_dirty_texobj(), _NEW_TEXTURE, and FLUSH_VERTICES.
Referenced by set_tex_parameteri().
static GLboolean legal_get_tex_level_parameter_target (struct gl_context * ctx, GLenum target) static
References gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_multisample, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::MESA_texture_array, gl_extensions::NV_texture_rectangle, and gl_context::Version.
Referenced by _mesa_GetTexLevelParameteriv().
static void set_swizzle_component (GLuint * swizzle, GLuint comp, GLuint swz) static
References ASSERT.
Referenced by set_tex_parameteri().
static GLboolean set_tex_parameterf (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLfloat * params) static
Set a float-valued texture parameter.
Returns
GL_TRUE if legal AND the value changed, GL_FALSE otherwise
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_lookup_enum_by_nr(), ACOMP, gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_texture_float, BCOMP, gl_sampler_object::BorderColor, CLAMP, gl_context::Const, gl_extensions::EXT_texture_filter_anisotropic, gl_context::Extensions, F, gl_color_union::f, flush(), GCOMP, gl_sampler_object::LodBias, gl_sampler_object::MaxAnisotropy, gl_sampler_object::MaxLod, gl_constants::MaxTextureMaxAnisotropy, MIN2, gl_sampler_object::MinLod, gl_texture_object::Priority, RCOMP, gl_texture_object::Sampler, gl_texture_object::Target, and target_allows_setting_sampler_parameters().
Referenced by _mesa_TexParameterf(), _mesa_TexParameterfv(), _mesa_TexParameteri(), and _mesa_TexParameteriv().
static GLboolean set_tex_parameteri (struct gl_context * ctx, struct gl_texture_object * texObj, GLenum pname, const GLint * params) static
Set an integer-valued texture parameter.
Returns
GL_TRUE if legal AND the value changed, GL_FALSE otherwise
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), _mesa_lookup_enum_by_nr(), gl_texture_object::_Swizzle, gl_extensions::AMD_seamless_cubemap_per_texture, gl_context::API, API_OPENGL_COMPAT, API_OPENGLES, gl_extensions::ARB_depth_texture, gl_extensions::ARB_shadow, gl_extensions::ARB_texture_rg, ASSERT, gl_texture_object::BaseLevel, comp_to_swizzle(), gl_sampler_object::CompareFunc, gl_sampler_object::CompareMode, gl_texture_object::CropRect, gl_sampler_object::CubeMapSeamless, gl_texture_object::DepthMode, gl_extensions::EXT_shadow_funcs, gl_extensions::EXT_texture_sRGB_decode, gl_extensions::EXT_texture_swizzle, gl_context::Extensions, flush(), gl_texture_object::GenerateMipmap, GL_TEXTURE_CROP_RECT_OES, GL_TEXTURE_EXTERNAL_OES, incomplete(), gl_sampler_object::MagFilter, gl_texture_object::MaxLevel, gl_sampler_object::MinFilter, gl_extensions::OES_draw_texture, gl_texture_object::Sampler, set_swizzle_component(), gl_sampler_object::sRGBDecode, gl_texture_object::Swizzle, gl_texture_object::Target, target_allows_setting_sampler_parameters(), validate_texture_wrap_mode(), gl_sampler_object::WrapR, gl_sampler_object::WrapS, and gl_sampler_object::WrapT.
Referenced by _mesa_TexParameterf(), _mesa_TexParameterfv(), _mesa_TexParameteri(), and _mesa_TexParameteriv().
static GLboolean target_allows_setting_sampler_parameters (GLenum target) static
Referenced by set_tex_parameterf(), and set_tex_parameteri().
static GLboolean validate_texture_wrap_mode (struct gl_context * ctx, GLenum target, GLenum wrap) static
Check if a coordinate wrap mode is supported for the texture target.
Returns
GL_TRUE if legal, GL_FALSE otherwise
References _mesa_error(), _mesa_is_desktop_gl(), gl_context::API, API_OPENGL_COMPAT, gl_extensions::ARB_texture_border_clamp, gl_extensions::ATI_texture_mirror_once, gl_extensions::EXT_texture_mirror_clamp, gl_context::Extensions, and GL_TEXTURE_EXTERNAL_OES.
Referenced by set_tex_parameteri().