Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texstorage.h File Reference
Functions
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
GLboolean _mesa_is_legal_tex_storage_format (struct gl_context *ctx, GLenum internalformat)
GLboolean _mesa_alloc_texture_storage (struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
Function Documentation
GLboolean _mesa_alloc_texture_storage (struct gl_context * ctx, struct gl_texture_object * texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
The driver can override this with a more specific implementation if it desires, but this can be used to get the texture images allocated using the usual texture image handling code. The immutability of GL_ARB_texture_storage texture layouts is handled by texObj->Immutable checks at glTexImage* time.
References _mesa_num_tex_faces(), dd_function_table::AllocTextureImageBuffer, gl_context::Driver, gl_texture_object::Image, and gl_texture_object::Target.
GLboolean _mesa_is_legal_tex_storage_format (struct gl_context * ctx, GLenum internalformat)
References _mesa_base_tex_format().
Referenced by tex_storage_error_check(), and teximagemultisample().
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
References texstorage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References texstorage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References texstorage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Referenced by _mesa_initialize_exec_table().