Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texstore.c File Reference
#include "glheader.h"
#include "bufferobj.h"
#include "colormac.h"
#include "format_pack.h"
#include "image.h"
#include "macros.h"
#include "mipmap.h"
#include "mtypes.h"
#include "pack.h"
#include "pbo.h"
#include "imports.h"
#include "texcompress.h"
#include "texcompress_fxt1.h"
#include "texcompress_rgtc.h"
#include "texcompress_s3tc.h"
#include "texcompress_etc.h"
#include "teximage.h"
#include "texstore.h"
#include "enums.h"
#include "glformats.h"
#include "../../gallium/auxiliary/util/u_format_rgb9e5.h"
#include "../../gallium/auxiliary/util/u_format_r11g11b10f.h"
Macros
#define MAP1(x) MAP4(x, ZERO, ZERO, ZERO)
#define MAP2(x, y) MAP4(x, y, ZERO, ZERO)
#define MAP3(x, y, z) MAP4(x, y, z, ZERO)
#define MAP4(x, y, z, w) { x, y, z, w, ZERO, ONE }
#define SWZ_CPY(dst, src, count, dstComps, srcComps)
Typedefs
typedef GLboolean(* StoreTexImageFunc)(TEXSTORE_PARAMS)
Texture image storage function.
Enumerations
enum { ZERO = 4, ONE = 5 }
The GL texture image functions in teximage.c basically just do error checking and data structure allocation.
enum {
IDX_LUMINANCE = 0, IDX_ALPHA, IDX_INTENSITY, IDX_LUMINANCE_ALPHA,
IDX_RGB, IDX_RGBA, IDX_RED, IDX_GREEN,
IDX_BLUE, IDX_BGR, IDX_BGRA, IDX_ABGR,
IDX_RG, MAX_IDX
}
Functions
static GLboolean can_swizzle (GLenum logicalBaseFormat)
Return GL_TRUE if the given image format is one that be converted to another format by swizzling.
static int get_map_idx (GLenum value)
Convert a GL image format enum to an IDX_* value (see above).
static void compute_component_mapping (GLenum inFormat, GLenum outFormat, GLubyte *map)
When promoting texture formats (see below) we need to compute the mapping of dest components back to source components.
GLfloat * _mesa_make_temp_float_image (struct gl_context *ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid *srcAddr, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
Make a temporary (color) texture image with GLfloat components.
static GLuint * make_temp_uint_image (struct gl_context *ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid *srcAddr, const struct gl_pixelstore_attrib *srcPacking)
Make temporary image with uint pixel values.
GLubyte * _mesa_make_temp_ubyte_image (struct gl_context *ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid *srcAddr, const struct gl_pixelstore_attrib *srcPacking)
Make a temporary (color) texture image with GLubyte components.
static void swizzle_copy (GLubyte *dst, GLuint dstComponents, const GLubyte *src, GLuint srcComponents, const GLubyte *map, GLuint count)
Copy GLubyte pixels from <src> to <dst> with swizzling.
static const GLubyte * type_mapping (GLenum srcType)
For 1-byte/pixel formats (or 8_8_8_8 packed formats), return a mapping array depending on endianness.
static const GLubyte * byteswap_mapping (GLboolean swapBytes, GLenum srcType)
For 1-byte/pixel formats (or 8_8_8_8 packed formats), return a mapping array depending on pixelstore byte swapping state.
static void _mesa_swizzle_ubyte_image (struct gl_context *ctx, GLuint dimensions, GLenum srcFormat, GLenum srcType, GLenum baseInternalFormat, const GLubyte *rgba2dst, GLuint dstComponents, GLint dstRowStride, GLubyte **dstSlices, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLvoid *srcAddr, const struct gl_pixelstore_attrib *srcPacking)
Transfer a GLubyte texture image with component swizzling.
static void memcpy_texture (struct gl_context *ctx, GLuint dimensions, gl_format dstFormat, GLint dstRowStride, GLubyte **dstSlices, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid *srcAddr, const struct gl_pixelstore_attrib *srcPacking)
Teximage storage routine for when a simple memcpy will do.
static GLboolean store_ubyte_texture (TEXSTORE_PARAMS)
General-case function for storing a color texture images with components that can be represented with ubytes.
static GLboolean _mesa_texstore_z32 (TEXSTORE_PARAMS)
Store a 32-bit integer or float depth component texture image.
static GLboolean _mesa_texstore_x8_z24 (TEXSTORE_PARAMS)
Store a 24-bit integer depth component texture image.
static GLboolean _mesa_texstore_z24_x8 (TEXSTORE_PARAMS)
Store a 24-bit integer depth component texture image.
static GLboolean _mesa_texstore_z16 (TEXSTORE_PARAMS)
Store a 16-bit integer depth component texture image.
static GLboolean _mesa_texstore_rgb565 (TEXSTORE_PARAMS)
Store an rgb565 or rgb565_rev texture image.
static GLboolean _mesa_texstore_rgba8888 (TEXSTORE_PARAMS)
Store a texture in MESA_FORMAT_RGBA8888 or MESA_FORMAT_RGBA8888_REV.
static GLboolean _mesa_texstore_argb8888 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgb888 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_bgr888 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_argb2101010 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_unorm44 (TEXSTORE_PARAMS)
Do texstore for 2-channel, 4-bit/channel, unsigned normalized formats.
static GLboolean _mesa_texstore_unorm88 (TEXSTORE_PARAMS)
Do texstore for 2-channel, 8-bit/channel, unsigned normalized formats.
static GLboolean _mesa_texstore_unorm1616 (TEXSTORE_PARAMS)
Do texstore for 2-channel, 16-bit/channel, unsigned normalized formats.
static GLboolean _mesa_texstore_unorm16 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgba_16 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_signed_rgba_16 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_unorm8 (TEXSTORE_PARAMS)
Texstore for _mesa_texformat_a8, _mesa_texformat_l8, _mesa_texformat_i8.
static GLboolean _mesa_texstore_ycbcr (TEXSTORE_PARAMS)
Texstore for _mesa_texformat_ycbcr or _mesa_texformat_ycbcr_REV.
static GLboolean _mesa_texstore_dudv8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_snorm8 (TEXSTORE_PARAMS)
Store a texture in a signed normalized 8-bit format.
static GLboolean _mesa_texstore_snorm88 (TEXSTORE_PARAMS)
Store a texture in a signed normalized two-channel 16-bit format.
static GLboolean _mesa_texstore_snorm16 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_snorm1616 (TEXSTORE_PARAMS)
Do texstore for 2-channel, 16-bit/channel, signed normalized formats.
static GLboolean _mesa_texstore_signed_rgbx8888 (TEXSTORE_PARAMS)
Store a texture in MESA_FORMAT_SIGNED_RGBX8888 or MESA_FORMAT_XBGR8888_SNORM.
static GLboolean _mesa_texstore_signed_rgba8888 (TEXSTORE_PARAMS)
Store a texture in MESA_FORMAT_SIGNED_RGBA8888 or MESA_FORMAT_SIGNED_RGBA8888_REV.
static GLboolean _mesa_texstore_z24_s8 (TEXSTORE_PARAMS)
Store a combined depth/stencil texture image.
static GLboolean _mesa_texstore_s8_z24 (TEXSTORE_PARAMS)
Store a combined depth/stencil texture image.
static GLboolean _mesa_texstore_s8 (TEXSTORE_PARAMS)
Store simple 8-bit/value stencil texture data.
static GLboolean _mesa_texstore_rgba_float32 (TEXSTORE_PARAMS)
Store an image in any of the formats: _mesa_texformat_rgba_float32 _mesa_texformat_rgb_float32 _mesa_texformat_alpha_float32 _mesa_texformat_luminance_float32 _mesa_texformat_luminance_alpha_float32 _mesa_texformat_intensity_float32.
static GLboolean _mesa_texstore_rgba_float16 (TEXSTORE_PARAMS)
As above, but store 16-bit floats.
static GLboolean _mesa_texstore_rgba_int8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgba_int16 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgba_int32 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgba_uint8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgba_uint16 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgba_uint32 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_srgb8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_srgba8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_sargb8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_sl8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_sla8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_rgb9_e5 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_r11_g11_b10f (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_z32f_x24s8 (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_argb2101010_uint (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_abgr2101010_uint (TEXSTORE_PARAMS)
static GLboolean _mesa_texstore_null (TEXSTORE_PARAMS)
static StoreTexImageFunc _mesa_get_texstore_func (gl_format format)
Return the StoreTexImageFunc pointer to store an image in the given format.
GLboolean _mesa_texstore_needs_transfer_ops (struct gl_context *ctx, GLenum baseInternalFormat, gl_format dstFormat)
GLboolean _mesa_texstore_can_use_memcpy (struct gl_context *ctx, GLenum baseInternalFormat, gl_format dstFormat, GLenum srcFormat, GLenum srcType, const struct gl_pixelstore_attrib *srcPacking)
static GLboolean _mesa_texstore_memcpy (TEXSTORE_PARAMS)
GLboolean _mesa_texstore (TEXSTORE_PARAMS)
Store user data into texture memory.
static GLbitfield get_read_write_mode (GLenum userFormat, gl_format texFormat)
Normally, we'll only write texel data to a texture when we map it.
static void store_texsubimage (struct gl_context *ctx, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing, const char *caller)
Helper function for storing 1D, 2D, 3D whole and subimages into texture memory.
void _mesa_store_teximage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Fallback code for ctx->Driver.TexImage().
void _mesa_store_texsubimage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const void *pixels, const struct gl_pixelstore_attrib *packing)
void _mesa_store_compressed_teximage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLsizei imageSize, const GLvoid *data)
Fallback for Driver.CompressedTexImage()
void _mesa_store_compressed_texsubimage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Fallback for Driver.CompressedTexSubImage()
Variables
struct {
GLubyte format_idx
GLubyte to_rgba [6]
GLubyte from_rgba [6]
} mappings [MAX_IDX]
static const GLubyte map_identity [6] = { 0, 1, 2, 3, ZERO, ONE }
static const GLubyte map_3210 [6] = { 3, 2, 1, 0, ZERO, ONE }
Macro Definition Documentation
#define MAP1 (x) MAP4(x, ZERO, ZERO, ZERO)
#define MAP2 (x, y) MAP4(x, y, ZERO, ZERO)
#define MAP3 (x, y, z) MAP4(x, y, z, ZERO)
#define MAP4 (x, y, z, w) { x, y, z, w, ZERO, ONE }
#define SWZ_CPY (dst, src, count, dstComps, srcComps)
Value:
do {                                              \
      GLuint i;                                      \
      for (i = 0; i < count; i++) {                  \
         GLuint j;                                   \
         if (srcComps == 4) {                        \
            COPY_4UBV(tmp, src);                     \
         }                                           \
         else {                                      \
            for (j = 0; j < srcComps; j++) {         \
               tmp[j] = src[j];                      \
            }                                        \
         }                                           \
         src += srcComps;                            \
         for (j = 0; j < dstComps; j++) {            \
            dst[j] = tmp[map[j]];                    \
         }                                           \
         dst += dstComps;                            \
      }                                              \
   } while (0)
Referenced by swizzle_copy().
Typedef Documentation
typedef GLboolean(* StoreTexImageFunc)(TEXSTORE_PARAMS)
Texture image storage function.
Enumeration Type Documentation
anonymous enum
The GL texture image functions in teximage.c basically just do error checking and data structure allocation.
They in turn call device driver functions which actually copy/convert/store the user's texture image data.
However, most device drivers will be able to use the fallback functions in this file. That is, most drivers will have the following bit of code: ctx->Driver.TexImage = _mesa_store_teximage; ctx->Driver.TexSubImage = _mesa_store_texsubimage; etc...
Texture image processing is actually kind of complicated. We have to do: Format/type conversions pixel unpacking pixel transfer (scale, bais, lookup, etc)
These functions can handle most everything, including processing full images and sub-images.
Enumerator
ZERO
ONE
anonymous enum
Enumerator
IDX_LUMINANCE
IDX_ALPHA
IDX_INTENSITY
IDX_LUMINANCE_ALPHA
IDX_RGB
IDX_RGBA
IDX_RED
IDX_GREEN
IDX_BLUE
IDX_BGR
IDX_BGRA
IDX_ABGR
IDX_RG
MAX_IDX
Function Documentation
static StoreTexImageFunc _mesa_get_texstore_func (gl_format format) static
Return the StoreTexImageFunc pointer to store an image in the given format.
References _mesa_texstore_abgr2101010_uint(), _mesa_texstore_argb2101010(), _mesa_texstore_argb2101010_uint(), _mesa_texstore_argb8888(), _mesa_texstore_bgr888(), _mesa_texstore_dudv8(), _mesa_texstore_etc1_rgb8(), _mesa_texstore_etc2_r11_eac(), _mesa_texstore_etc2_rg11_eac(), _mesa_texstore_etc2_rgb8(), _mesa_texstore_etc2_rgb8_punchthrough_alpha1(), _mesa_texstore_etc2_rgba8_eac(), _mesa_texstore_etc2_signed_r11_eac(), _mesa_texstore_etc2_signed_rg11_eac(), _mesa_texstore_etc2_srgb8(), _mesa_texstore_etc2_srgb8_alpha8_eac(), _mesa_texstore_etc2_srgb8_punchthrough_alpha1(), _mesa_texstore_null(), _mesa_texstore_r11_g11_b10f(), _mesa_texstore_red_rgtc1(), _mesa_texstore_rg_rgtc2(), _mesa_texstore_rgb565(), _mesa_texstore_rgb888(), _mesa_texstore_rgb9_e5(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgb_fxt1(), _mesa_texstore_rgba8888(), _mesa_texstore_rgba_16(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_texstore_rgba_float16(), _mesa_texstore_rgba_float32(), _mesa_texstore_rgba_fxt1(), _mesa_texstore_rgba_int16(), _mesa_texstore_rgba_int32(), _mesa_texstore_rgba_int8(), _mesa_texstore_rgba_uint16(), _mesa_texstore_rgba_uint32(), _mesa_texstore_rgba_uint8(), _mesa_texstore_s8(), _mesa_texstore_s8_z24(), _mesa_texstore_sargb8(), _mesa_texstore_signed_red_rgtc1(), _mesa_texstore_signed_rg_rgtc2(), _mesa_texstore_signed_rgba8888(), _mesa_texstore_signed_rgba_16(), _mesa_texstore_signed_rgbx8888(), _mesa_texstore_sl8(), _mesa_texstore_sla8(), _mesa_texstore_snorm16(), _mesa_texstore_snorm1616(), _mesa_texstore_snorm8(), _mesa_texstore_snorm88(), _mesa_texstore_srgb8(), _mesa_texstore_srgba8(), _mesa_texstore_unorm16(), _mesa_texstore_unorm1616(), _mesa_texstore_unorm44(), _mesa_texstore_unorm8(), _mesa_texstore_unorm88(), _mesa_texstore_x8_z24(), _mesa_texstore_ycbcr(), _mesa_texstore_z16(), _mesa_texstore_z24_s8(), _mesa_texstore_z24_x8(), _mesa_texstore_z32(), _mesa_texstore_z32f_x24s8(), ASSERT, MESA_FORMAT_A16, MESA_FORMAT_A8, MESA_FORMAT_ABGR2101010_UINT, MESA_FORMAT_AL1616, MESA_FORMAT_AL1616_REV, MESA_FORMAT_AL44, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_ALPHA_UINT32, MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_ARGB1555, MESA_FORMAT_ARGB1555_REV, MESA_FORMAT_ARGB2101010, MESA_FORMAT_ARGB2101010_UINT, MESA_FORMAT_ARGB4444, MESA_FORMAT_ARGB4444_REV, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_BGR888, MESA_FORMAT_COUNT, MESA_FORMAT_DUDV8, MESA_FORMAT_ETC1_RGB8, MESA_FORMAT_ETC2_R11_EAC, MESA_FORMAT_ETC2_RG11_EAC, MESA_FORMAT_ETC2_RGB8, MESA_FORMAT_ETC2_RGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_ETC2_RGBA8_EAC, MESA_FORMAT_ETC2_SIGNED_R11_EAC, MESA_FORMAT_ETC2_SIGNED_RG11_EAC, MESA_FORMAT_ETC2_SRGB8, MESA_FORMAT_ETC2_SRGB8_ALPHA8_EAC, MESA_FORMAT_ETC2_SRGB8_PUNCHTHROUGH_ALPHA1, MESA_FORMAT_GR1616, MESA_FORMAT_GR88, MESA_FORMAT_I16, MESA_FORMAT_I8, MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT32, MESA_FORMAT_INTENSITY_INT16, MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_INTENSITY_UINT8, MESA_FORMAT_L16, MESA_FORMAT_L8, MESA_FORMAT_L_LATC1, MESA_FORMAT_LA_LATC2, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_ALPHA_INT16, MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT8, MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT32, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_LUMINANCE_UINT32, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_NONE, MESA_FORMAT_R11_G11_B10_FLOAT, MESA_FORMAT_R16, MESA_FORMAT_R8, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_R_INT16, MESA_FORMAT_R_INT32, MESA_FORMAT_R_INT8, MESA_FORMAT_R_UINT16, MESA_FORMAT_R_UINT32, MESA_FORMAT_R_UINT8, MESA_FORMAT_RED_RGTC1, MESA_FORMAT_RG1616, MESA_FORMAT_RG88, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RG_INT16, MESA_FORMAT_RG_INT32, MESA_FORMAT_RG_INT8, MESA_FORMAT_RG_RGTC2, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB332, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, MESA_FORMAT_RGB888, MESA_FORMAT_RGB9_E5_FLOAT, MESA_FORMAT_RGB_DXT1, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGB_FXT1, MESA_FORMAT_RGB_INT16, MESA_FORMAT_RGB_INT32, MESA_FORMAT_RGB_INT8, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGBA5551, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBA_16, MESA_FORMAT_RGBA_DXT1, MESA_FORMAT_RGBA_DXT3, MESA_FORMAT_RGBA_DXT5, MESA_FORMAT_RGBA_FLOAT16, MESA_FORMAT_RGBA_FLOAT32, MESA_FORMAT_RGBA_FXT1, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_RGBA_UINT32, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_S8, MESA_FORMAT_S8_Z24, MESA_FORMAT_SARGB8, MESA_FORMAT_SIGNED_A16, MESA_FORMAT_SIGNED_A8, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_AL88, MESA_FORMAT_SIGNED_GR1616, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_L8, MESA_FORMAT_SIGNED_L_LATC1, MESA_FORMAT_SIGNED_LA_LATC2, MESA_FORMAT_SIGNED_R16, MESA_FORMAT_SIGNED_R8, MESA_FORMAT_SIGNED_RED_RGTC1, MESA_FORMAT_SIGNED_RG88_REV, MESA_FORMAT_SIGNED_RG_RGTC2, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_SL8, MESA_FORMAT_SLA8, MESA_FORMAT_SRGB8, MESA_FORMAT_SRGB_DXT1, MESA_FORMAT_SRGBA8, MESA_FORMAT_SRGBA_DXT1, MESA_FORMAT_SRGBA_DXT3, MESA_FORMAT_SRGBA_DXT5, MESA_FORMAT_X8_Z24, MESA_FORMAT_XBGR16161616_FLOAT, MESA_FORMAT_XBGR16161616_SINT, MESA_FORMAT_XBGR16161616_SNORM, MESA_FORMAT_XBGR16161616_UINT, MESA_FORMAT_XBGR16161616_UNORM, MESA_FORMAT_XBGR32323232_FLOAT, MESA_FORMAT_XBGR32323232_SINT, MESA_FORMAT_XBGR32323232_UINT, MESA_FORMAT_XBGR8888_SINT, MESA_FORMAT_XBGR8888_SNORM, MESA_FORMAT_XBGR8888_SRGB, MESA_FORMAT_XBGR8888_UINT, MESA_FORMAT_XRGB1555_UNORM, MESA_FORMAT_XRGB2101010_UNORM, MESA_FORMAT_XRGB4444_UNORM, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, MESA_FORMAT_Z16, MESA_FORMAT_Z24_S8, MESA_FORMAT_Z24_X8, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, MESA_FORMAT_Z32_FLOAT_X24S8, store_ubyte_texture(), and table.
Referenced by _mesa_texstore().
GLfloat* _mesa_make_temp_float_image (struct gl_context * ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid * srcAddr, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
Make a temporary (color) texture image with GLfloat components.
Apply all needed pixel unpacking and pixel transfer operations. Note that there are both logicalBaseFormat and textureBaseFormat parameters. Suppose the user specifies GL_LUMINANCE as the internal texture format but the graphics hardware doesn't support luminance textures. So, we might use an RGB hardware format instead. If logicalBaseFormat != textureBaseFormat we have some extra work to do.
Parameters
ctx the rendering context
dims image dimensions: 1, 2 or 3
logicalBaseFormat basic texture derived from the user's internal texture format value
textureBaseFormat the actual basic format of the texture
srcWidth source image width
srcHeight source image height
srcDepth source image depth
srcFormat source image format
srcType source image type
srcAddr source image address
srcPacking source image pixel packing
Returns
resulting image with format = textureBaseFormat and type = GLfloat.
References _mesa_components_in_format(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_color_span_float(), ASSERT, compute_component_mapping(), GLubyte, NULL, ONE, and ZERO.
Referenced by _mesa_texstore_argb2101010(), _mesa_texstore_r11_g11_b10f(), _mesa_texstore_rgb9_e5(), _mesa_texstore_rgba_16(), _mesa_texstore_rgba_float16(), _mesa_texstore_rgba_float32(), _mesa_texstore_signed_red_rgtc1(), _mesa_texstore_signed_rg_rgtc2(), _mesa_texstore_signed_rgba8888(), _mesa_texstore_signed_rgba_16(), _mesa_texstore_signed_rgbx8888(), _mesa_texstore_snorm16(), _mesa_texstore_snorm1616(), _mesa_texstore_snorm8(), _mesa_texstore_snorm88(), _mesa_texstore_unorm16(), and _mesa_texstore_unorm1616().
GLubyte* _mesa_make_temp_ubyte_image (struct gl_context * ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid * srcAddr, const struct gl_pixelstore_attrib * srcPacking)
Make a temporary (color) texture image with GLubyte components.
Apply all needed pixel unpacking and pixel transfer operations. Note that there are both logicalBaseFormat and textureBaseFormat parameters. Suppose the user specifies GL_LUMINANCE as the internal texture format but the graphics hardware doesn't support luminance textures. So, we might use an RGB hardware format instead. If logicalBaseFormat != textureBaseFormat we have some extra work to do.
Parameters
ctx the rendering context
dims image dimensions: 1, 2 or 3
logicalBaseFormat basic texture derived from the user's internal texture format value
textureBaseFormat the actual basic format of the texture
srcWidth source image width
srcHeight source image height
srcDepth source image depth
srcFormat source image format
srcType source image type
srcAddr source image address
srcPacking source image pixel packing
Returns
resulting image with format = textureBaseFormat and type = GLubyte.
References gl_context::_ImageTransferState, _mesa_components_in_format(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_color_span_ubyte(), ASSERT, compute_component_mapping(), GLubyte, NULL, ONE, and ZERO.
Referenced by _mesa_texstore_red_rgtc1(), _mesa_texstore_rg_rgtc2(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgb_fxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_texstore_rgba_fxt1(), _mesa_texstore_unorm44(), _mesa_texstore_unorm8(), _mesa_texstore_unorm88(), and store_ubyte_texture().
void _mesa_store_compressed_teximage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLsizei imageSize, const GLvoid * data)
Fallback for Driver.CompressedTexImage()
References _mesa_error(), _mesa_problem(), _mesa_store_compressed_texsubimage(), dd_function_table::AllocTextureImageBuffer, ASSERT, gl_texture_image::Depth, gl_context::Driver, gl_texture_image::Height, gl_texture_image::TexFormat, and gl_texture_image::Width.
void _mesa_store_compressed_texsubimage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
Fallback for Driver.CompressedTexSubImage()
References _mesa_error(), _mesa_format_row_stride(), _mesa_get_format_block_size(), _mesa_problem(), _mesa_unmap_teximage_pbo(), _mesa_validate_pbo_compressed_teximage(), gl_context::Driver, GLubyte, dd_function_table::MapTextureImage, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_context::Unpack.
Referenced by _mesa_store_compressed_teximage().
void _mesa_store_teximage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing)
Fallback code for ctx->Driver.TexImage().
Basically, allocate storage for the texture image, then copy the user's image into it.
References _mesa_error(), dd_function_table::AllocTextureImageBuffer, gl_texture_image::Depth, gl_context::Driver, gl_texture_image::Height, store_texsubimage(), and gl_texture_image::Width.
void _mesa_store_texsubimage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const void * pixels, const struct gl_pixelstore_attrib * packing)
References store_texsubimage().
static void _mesa_swizzle_ubyte_image (struct gl_context * ctx, GLuint dimensions, GLenum srcFormat, GLenum srcType, GLenum baseInternalFormat, const GLubyte * rgba2dst, GLuint dstComponents, GLint dstRowStride, GLubyte ** dstSlices, GLint srcWidth, GLint srcHeight, GLint srcDepth, const GLvoid * srcAddr, const struct gl_pixelstore_attrib * srcPacking) static
Transfer a GLubyte texture image with component swizzling.
References _mesa_components_in_format(), _mesa_image_address(), _mesa_image_image_stride(), _mesa_image_row_stride(), byteswap_mapping(), compute_component_mapping(), GLubyte, gl_pixelstore_attrib::SwapBytes, swizzle_copy(), type_mapping(), and void().
Referenced by _mesa_texstore_argb8888(), _mesa_texstore_bgr888(), _mesa_texstore_dudv8(), _mesa_texstore_rgb888(), _mesa_texstore_rgba8888(), _mesa_texstore_unorm8(), and _mesa_texstore_unorm88().
GLboolean _mesa_texstore (TEXSTORE_PARAMS)
Store user data into texture memory.
Called via glTex[Sub]Image1/2/3D()
References _mesa_get_texstore_func(), and _mesa_texstore_memcpy().
Referenced by store_texsubimage().
static GLboolean _mesa_texstore_abgr2101010_uint (TEXSTORE_PARAMS) static
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ACOMP, ASSERT, BCOMP, CLAMP, GCOMP, GLubyte, GLushort, make_temp_uint_image(), MESA_FORMAT_ABGR2101010_UINT, MIN2, and RCOMP.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_argb2101010 (TEXSTORE_PARAMS) static
References _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ACOMP, ASSERT, BCOMP, GCOMP, GLubyte, GLushort, MESA_FORMAT_ARGB2101010, MESA_FORMAT_XRGB2101010_UNORM, PACK_COLOR_2101010_US, RCOMP, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_argb2101010_uint (TEXSTORE_PARAMS) static
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ACOMP, ASSERT, BCOMP, CLAMP, GCOMP, GLubyte, GLushort, make_temp_uint_image(), MESA_FORMAT_ARGB2101010_UINT, MIN2, and RCOMP.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_argb8888 (TEXSTORE_PARAMS) static
References _mesa_get_format_bytes(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_little_endian(), _mesa_swizzle_ubyte_image(), ACOMP, ASSERT, BCOMP, can_swizzle(), GCOMP, GLubyte, MESA_FORMAT_ARGB8888, MESA_FORMAT_ARGB8888_REV, MESA_FORMAT_XRGB8888, MESA_FORMAT_XRGB8888_REV, PACK_COLOR_8888, RCOMP, and store_ubyte_texture().
Referenced by _mesa_get_texstore_func(), and _mesa_texstore_sargb8().
static GLboolean _mesa_texstore_bgr888 (TEXSTORE_PARAMS) static
References _mesa_get_format_bytes(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_swizzle_ubyte_image(), ASSERT, BCOMP, can_swizzle(), GCOMP, GLubyte, MESA_FORMAT_BGR888, ONE, RCOMP, and store_ubyte_texture().
Referenced by _mesa_get_texstore_func().
GLboolean _mesa_texstore_can_use_memcpy (struct gl_context * ctx, GLenum baseInternalFormat, gl_format dstFormat, GLenum srcFormat, GLenum srcType, const struct gl_pixelstore_attrib * srcPacking)
References _mesa_format_matches_format_and_type(), _mesa_get_format_base_format(), _mesa_texstore_needs_transfer_ops(), and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_texstore_memcpy().
static GLboolean _mesa_texstore_dudv8 (TEXSTORE_PARAMS) static
References _mesa_components_in_format(), _mesa_get_format_bytes(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_little_endian(), _mesa_swizzle_ubyte_image(), _mesa_unpack_dudv_span_byte(), ASSERT, GLbyte, GLubyte, MESA_FORMAT_DUDV8, ONE, and ZERO.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_memcpy (TEXSTORE_PARAMS) static
References _mesa_texstore_can_use_memcpy(), and memcpy_texture().
Referenced by _mesa_texstore().
GLboolean _mesa_texstore_needs_transfer_ops (struct gl_context * ctx, GLenum baseInternalFormat, gl_format dstFormat)
References gl_context::_ImageTransferState, _mesa_get_format_datatype(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, and gl_context::Pixel.
Referenced by _mesa_texstore_can_use_memcpy().
static GLboolean _mesa_texstore_null (TEXSTORE_PARAMS) static
References _mesa_problem(), NULL, and void().
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_r11_g11_b10f (TEXSTORE_PARAMS) static
References _mesa_get_format_base_format(), _mesa_make_temp_float_image(), ASSERT, GLubyte, and MESA_FORMAT_R11_G11_B10_FLOAT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgb565 (TEXSTORE_PARAMS) static
Store an rgb565 or rgb565_rev texture image.
References _mesa_get_format_bytes(), _mesa_image_address(), _mesa_image_row_stride(), ASSERT, GLubyte, GLushort, MESA_FORMAT_RGB565, MESA_FORMAT_RGB565_REV, PACK_COLOR_565, PACK_COLOR_565_REV, and store_ubyte_texture().
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgb888 (TEXSTORE_PARAMS) static
References _mesa_get_format_bytes(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_swizzle_ubyte_image(), ASSERT, BCOMP, can_swizzle(), GCOMP, GLubyte, MESA_FORMAT_RGB888, ONE, RCOMP, and store_ubyte_texture().
Referenced by _mesa_get_texstore_func(), and _mesa_texstore_srgb8().
static GLboolean _mesa_texstore_rgb9_e5 (TEXSTORE_PARAMS) static
References _mesa_get_format_base_format(), _mesa_make_temp_float_image(), ASSERT, GLubyte, and MESA_FORMAT_RGB9_E5_FLOAT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba8888 (TEXSTORE_PARAMS) static
Store a texture in MESA_FORMAT_RGBA8888 or MESA_FORMAT_RGBA8888_REV.
References _mesa_get_format_bytes(), _mesa_little_endian(), _mesa_swizzle_ubyte_image(), ASSERT, can_swizzle(), GLubyte, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBA8888_REV, MESA_FORMAT_RGBX8888, MESA_FORMAT_RGBX8888_REV, and store_ubyte_texture().
Referenced by _mesa_get_texstore_func(), and _mesa_texstore_srgba8().
static GLboolean _mesa_texstore_rgba_16 (TEXSTORE_PARAMS) static
References _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLubyte, GLushort, MESA_FORMAT_RGBA_16, MESA_FORMAT_XBGR16161616_UNORM, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_float16 (TEXSTORE_PARAMS) static
As above, but store 16-bit floats.
References _mesa_components_in_format(), _mesa_float_to_half(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLubyte, MESA_FORMAT_ALPHA_FLOAT16, MESA_FORMAT_INTENSITY_FLOAT16, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT16, MESA_FORMAT_LUMINANCE_FLOAT16, MESA_FORMAT_R_FLOAT16, MESA_FORMAT_RG_FLOAT16, MESA_FORMAT_RGB_FLOAT16, MESA_FORMAT_RGBA_FLOAT16, and MESA_FORMAT_XBGR16161616_FLOAT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_float32 (TEXSTORE_PARAMS) static
Store an image in any of the formats: _mesa_texformat_rgba_float32 _mesa_texformat_rgb_float32 _mesa_texformat_alpha_float32 _mesa_texformat_luminance_float32 _mesa_texformat_luminance_alpha_float32 _mesa_texformat_intensity_float32.
References _mesa_components_in_format(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLubyte, MESA_FORMAT_ALPHA_FLOAT32, MESA_FORMAT_INTENSITY_FLOAT32, MESA_FORMAT_LUMINANCE_ALPHA_FLOAT32, MESA_FORMAT_LUMINANCE_FLOAT32, MESA_FORMAT_R_FLOAT32, MESA_FORMAT_RG_FLOAT32, MESA_FORMAT_RGB_FLOAT32, MESA_FORMAT_RGBA_FLOAT32, and MESA_FORMAT_XBGR32323232_FLOAT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_int16 (TEXSTORE_PARAMS) static
References _mesa_components_in_format(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ASSERT, CLAMP, GLshort, GLubyte, make_temp_uint_image(), MESA_FORMAT_ALPHA_INT16, MESA_FORMAT_INTENSITY_INT16, MESA_FORMAT_LUMINANCE_ALPHA_INT16, MESA_FORMAT_LUMINANCE_INT16, MESA_FORMAT_R_INT16, MESA_FORMAT_RG_INT16, MESA_FORMAT_RGB_INT16, MESA_FORMAT_RGBA_INT16, MESA_FORMAT_XBGR16161616_SINT, and MIN2.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_int32 (TEXSTORE_PARAMS) static
References _mesa_components_in_format(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ASSERT, GLubyte, make_temp_uint_image(), MESA_FORMAT_ALPHA_INT32, MESA_FORMAT_INTENSITY_INT32, MESA_FORMAT_LUMINANCE_ALPHA_INT32, MESA_FORMAT_LUMINANCE_INT32, MESA_FORMAT_R_INT32, MESA_FORMAT_RG_INT32, MESA_FORMAT_RGB_INT32, MESA_FORMAT_RGBA_INT32, MESA_FORMAT_XBGR32323232_SINT, and MIN2.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_int8 (TEXSTORE_PARAMS) static
References _mesa_components_in_format(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ASSERT, CLAMP, GLbyte, GLubyte, make_temp_uint_image(), MESA_FORMAT_ALPHA_INT8, MESA_FORMAT_INTENSITY_INT8, MESA_FORMAT_LUMINANCE_ALPHA_INT8, MESA_FORMAT_LUMINANCE_INT8, MESA_FORMAT_R_INT8, MESA_FORMAT_RG_INT8, MESA_FORMAT_RGB_INT8, MESA_FORMAT_RGBA_INT8, MESA_FORMAT_XBGR8888_SINT, and MIN2.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_uint16 (TEXSTORE_PARAMS) static
References _mesa_components_in_format(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ASSERT, CLAMP, GLubyte, GLushort, make_temp_uint_image(), MESA_FORMAT_ALPHA_UINT16, MESA_FORMAT_INTENSITY_UINT16, MESA_FORMAT_LUMINANCE_ALPHA_UINT16, MESA_FORMAT_LUMINANCE_UINT16, MESA_FORMAT_R_UINT16, MESA_FORMAT_RG_UINT16, MESA_FORMAT_RGB_UINT16, MESA_FORMAT_RGBA_UINT16, MESA_FORMAT_XBGR16161616_UINT, and MIN2.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_uint32 (TEXSTORE_PARAMS) static
References _mesa_components_in_format(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ASSERT, GLubyte, make_temp_uint_image(), MAX2, MESA_FORMAT_ALPHA_UINT32, MESA_FORMAT_INTENSITY_UINT32, MESA_FORMAT_LUMINANCE_ALPHA_UINT32, MESA_FORMAT_LUMINANCE_UINT32, MESA_FORMAT_R_UINT32, MESA_FORMAT_RG_UINT32, MESA_FORMAT_RGB_UINT32, MESA_FORMAT_RGBA_UINT32, and MESA_FORMAT_XBGR32323232_UINT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_rgba_uint8 (TEXSTORE_PARAMS) static
References _mesa_components_in_format(), _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_is_type_unsigned(), ASSERT, CLAMP, GLubyte, make_temp_uint_image(), MESA_FORMAT_ALPHA_UINT8, MESA_FORMAT_INTENSITY_UINT8, MESA_FORMAT_LUMINANCE_ALPHA_UINT8, MESA_FORMAT_LUMINANCE_UINT8, MESA_FORMAT_R_UINT8, MESA_FORMAT_RG_UINT8, MESA_FORMAT_RGB_UINT8, MESA_FORMAT_RGBA_UINT8, MESA_FORMAT_XBGR8888_UINT, and MIN2.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_s8 (TEXSTORE_PARAMS) static
Store simple 8-bit/value stencil texture data.
References _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_stencil_span(), ASSERT, GLubyte, and MESA_FORMAT_S8.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_s8_z24 (TEXSTORE_PARAMS) static
Store a combined depth/stencil texture image.
References _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_depth_span(), _mesa_unpack_stencil_span(), ASSERT, GLubyte, and MESA_FORMAT_S8_Z24.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_sargb8 (TEXSTORE_PARAMS) static
References _mesa_texstore_argb8888(), ASSERT, MESA_FORMAT_ARGB8888, and MESA_FORMAT_SARGB8.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_signed_rgba8888 (TEXSTORE_PARAMS) static
Store a texture in MESA_FORMAT_SIGNED_RGBA8888 or MESA_FORMAT_SIGNED_RGBA8888_REV.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ACOMP, ASSERT, BCOMP, FLOAT_TO_BYTE_TEX, GCOMP, GLbyte, MESA_FORMAT_SIGNED_RGBA8888, MESA_FORMAT_SIGNED_RGBA8888_REV, and RCOMP.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_signed_rgba_16 (TEXSTORE_PARAMS) static
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLshort, GLubyte, MESA_FORMAT_SIGNED_RGB_16, MESA_FORMAT_SIGNED_RGBA_16, MESA_FORMAT_XBGR16161616_SNORM, and UNCLAMPED_FLOAT_TO_SHORT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_signed_rgbx8888 (TEXSTORE_PARAMS) static
Store a texture in MESA_FORMAT_SIGNED_RGBX8888 or MESA_FORMAT_XBGR8888_SNORM.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, BCOMP, FLOAT_TO_BYTE_TEX, GCOMP, GLbyte, MESA_FORMAT_SIGNED_RGBX8888, MESA_FORMAT_XBGR8888_SNORM, and RCOMP.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_sl8 (TEXSTORE_PARAMS) static
References _mesa_texstore_unorm8(), ASSERT, MESA_FORMAT_L8, and MESA_FORMAT_SL8.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_sla8 (TEXSTORE_PARAMS) static
References _mesa_texstore_unorm88(), ASSERT, MESA_FORMAT_AL88, and MESA_FORMAT_SLA8.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_snorm16 (TEXSTORE_PARAMS) static
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLshort, GLubyte, GLushort, MESA_FORMAT_SIGNED_A16, MESA_FORMAT_SIGNED_I16, MESA_FORMAT_SIGNED_L16, MESA_FORMAT_SIGNED_R16, and UNCLAMPED_FLOAT_TO_SHORT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_snorm1616 (TEXSTORE_PARAMS) static
Do texstore for 2-channel, 16-bit/channel, signed normalized formats.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLshort, GLubyte, GLushort, MESA_FORMAT_SIGNED_AL1616, MESA_FORMAT_SIGNED_GR1616, and UNCLAMPED_FLOAT_TO_SHORT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_snorm8 (TEXSTORE_PARAMS) static
Store a texture in a signed normalized 8-bit format.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, FLOAT_TO_BYTE_TEX, GLbyte, MESA_FORMAT_SIGNED_A8, MESA_FORMAT_SIGNED_I8, MESA_FORMAT_SIGNED_L8, and MESA_FORMAT_SIGNED_R8.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_snorm88 (TEXSTORE_PARAMS) static
Store a texture in a signed normalized two-channel 16-bit format.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, FLOAT_TO_BYTE_TEX, GLbyte, MESA_FORMAT_SIGNED_AL88, and MESA_FORMAT_SIGNED_RG88_REV.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_srgb8 (TEXSTORE_PARAMS) static
References _mesa_texstore_rgb888(), ASSERT, MESA_FORMAT_RGB888, and MESA_FORMAT_SRGB8.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_srgba8 (TEXSTORE_PARAMS) static
References _mesa_texstore_rgba8888(), ASSERT, MESA_FORMAT_RGBA8888, MESA_FORMAT_RGBX8888_REV, MESA_FORMAT_SRGBA8, and MESA_FORMAT_XBGR8888_SRGB.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_unorm16 (TEXSTORE_PARAMS) static
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLubyte, GLushort, MESA_FORMAT_A16, MESA_FORMAT_I16, MESA_FORMAT_L16, MESA_FORMAT_R16, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_unorm1616 (TEXSTORE_PARAMS) static
Do texstore for 2-channel, 16-bit/channel, unsigned normalized formats.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_float_image(), ASSERT, GLubyte, GLushort, MESA_FORMAT_AL1616, MESA_FORMAT_AL1616_REV, MESA_FORMAT_GR1616, MESA_FORMAT_RG1616, PACK_COLOR_1616, PACK_COLOR_1616_REV, and UNCLAMPED_FLOAT_TO_USHORT.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_unorm44 (TEXSTORE_PARAMS) static
Do texstore for 2-channel, 4-bit/channel, unsigned normalized formats.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_ubyte_image(), ASSERT, GLubyte, MESA_FORMAT_AL44, and PACK_COLOR_44.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_unorm8 (TEXSTORE_PARAMS) static
Texstore for _mesa_texformat_a8, _mesa_texformat_l8, _mesa_texformat_i8.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_make_temp_ubyte_image(), _mesa_swizzle_ubyte_image(), ASSERT, can_swizzle(), GLubyte, MESA_FORMAT_A8, MESA_FORMAT_I8, MESA_FORMAT_L8, MESA_FORMAT_R8, ONE, and ZERO.
Referenced by _mesa_get_texstore_func(), and _mesa_texstore_sl8().
static GLboolean _mesa_texstore_unorm88 (TEXSTORE_PARAMS) static
Do texstore for 2-channel, 8-bit/channel, unsigned normalized formats.
References _mesa_get_format_base_format(), _mesa_get_format_bytes(), _mesa_little_endian(), _mesa_make_temp_ubyte_image(), _mesa_swizzle_ubyte_image(), ASSERT, can_swizzle(), GLubyte, GLushort, MESA_FORMAT_AL88, MESA_FORMAT_AL88_REV, MESA_FORMAT_GR88, MESA_FORMAT_RG88, ONE, PACK_COLOR_88, PACK_COLOR_88_REV, and ZERO.
Referenced by _mesa_get_texstore_func(), and _mesa_texstore_sla8().
static GLboolean _mesa_texstore_x8_z24 (TEXSTORE_PARAMS) static
Store a 24-bit integer depth component texture image.
References _mesa_image_address(), _mesa_unpack_depth_span(), ASSERT, GLubyte, MESA_FORMAT_X8_Z24, and void().
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_ycbcr (TEXSTORE_PARAMS) static
Texstore for _mesa_texformat_ycbcr or _mesa_texformat_ycbcr_REV.
References _mesa_get_format_bytes(), _mesa_little_endian(), _mesa_swap2(), ASSERT, GLubyte, GLushort, memcpy_texture(), MESA_FORMAT_YCBCR, MESA_FORMAT_YCBCR_REV, and void().
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_z16 (TEXSTORE_PARAMS) static
Store a 16-bit integer depth component texture image.
References _mesa_get_format_bytes(), _mesa_image_address(), _mesa_unpack_depth_span(), ASSERT, GLubyte, GLushort, MESA_FORMAT_Z16, and void().
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_z24_s8 (TEXSTORE_PARAMS) static
Store a combined depth/stencil texture image.
References _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_depth_span(), _mesa_unpack_stencil_span(), ASSERT, GLubyte, and MESA_FORMAT_Z24_S8.
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_z24_x8 (TEXSTORE_PARAMS) static
Store a 24-bit integer depth component texture image.
References _mesa_image_address(), _mesa_unpack_depth_span(), ASSERT, GLubyte, MESA_FORMAT_Z24_X8, and void().
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_z32 (TEXSTORE_PARAMS) static
Store a 32-bit integer or float depth component texture image.
References _mesa_get_format_bytes(), _mesa_image_address(), _mesa_unpack_depth_span(), ASSERT, GLubyte, MESA_FORMAT_Z32, MESA_FORMAT_Z32_FLOAT, and void().
Referenced by _mesa_get_texstore_func().
static GLboolean _mesa_texstore_z32f_x24s8 (TEXSTORE_PARAMS) static
References _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_depth_span(), _mesa_unpack_stencil_span(), ASSERT, and MESA_FORMAT_Z32_FLOAT_X24S8.
Referenced by _mesa_get_texstore_func().
static const GLubyte* byteswap_mapping (GLboolean swapBytes, GLenum srcType) static
For 1-byte/pixel formats (or 8_8_8_8 packed formats), return a mapping array depending on pixelstore byte swapping state.
References map_3210, map_identity, and NULL.
Referenced by _mesa_swizzle_ubyte_image().
static GLboolean can_swizzle (GLenum logicalBaseFormat) static
Return GL_TRUE if the given image format is one that be converted to another format by swizzling.
Referenced by _mesa_texstore_argb8888(), _mesa_texstore_bgr888(), _mesa_texstore_rgb888(), _mesa_texstore_rgba8888(), _mesa_texstore_unorm8(), and _mesa_texstore_unorm88().
static void compute_component_mapping (GLenum inFormat, GLenum outFormat, GLubyte * map) static
When promoting texture formats (see below) we need to compute the mapping of dest components back to source components.
This function does that.
Parameters
inFormat the incoming format of the texture
outFormat the final texture format
Returns
map[6] a full 6-component map
References _mesa_lookup_enum_by_nr(), get_map_idx(), GLubyte, mappings, ONE, and ZERO.
Referenced by _mesa_make_temp_float_image(), _mesa_make_temp_ubyte_image(), _mesa_swizzle_ubyte_image(), and make_temp_uint_image().
static int get_map_idx (GLenum value) static
Convert a GL image format enum to an IDX_* value (see above).
References _mesa_problem(), IDX_ABGR, IDX_ALPHA, IDX_BGR, IDX_BGRA, IDX_BLUE, IDX_GREEN, IDX_INTENSITY, IDX_LUMINANCE, IDX_LUMINANCE_ALPHA, IDX_RED, IDX_RG, IDX_RGB, IDX_RGBA, and NULL.
Referenced by compute_component_mapping().
static GLbitfield get_read_write_mode (GLenum userFormat, gl_format texFormat) static
Normally, we'll only write texel data to a texture when we map it.
But if the user is providing depth or stencil values and the texture image is a combined depth/stencil format, we'll actually read from the texture buffer too (in order to insert the depth or stencil values.
Parameters
userFormat the user-provided image format
texFormat the destination texture format
References _mesa_get_format_base_format().
Referenced by store_texsubimage().
static GLuint* make_temp_uint_image (struct gl_context * ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid * srcAddr, const struct gl_pixelstore_attrib * srcPacking) static
Make temporary image with uint pixel values.
Used for unsigned integer-valued textures.
References _mesa_components_in_format(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_color_span_uint(), ASSERT, compute_component_mapping(), GLubyte, NULL, ONE, and ZERO.
Referenced by _mesa_texstore_abgr2101010_uint(), _mesa_texstore_argb2101010_uint(), _mesa_texstore_rgba_int16(), _mesa_texstore_rgba_int32(), _mesa_texstore_rgba_int8(), _mesa_texstore_rgba_uint16(), _mesa_texstore_rgba_uint32(), and _mesa_texstore_rgba_uint8().
static void memcpy_texture (struct gl_context * ctx, GLuint dimensions, gl_format dstFormat, GLint dstRowStride, GLubyte ** dstSlices, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid * srcAddr, const struct gl_pixelstore_attrib * srcPacking) static
Teximage storage routine for when a simple memcpy will do.
No pixel transfer operations or special texel encodings allowed. 1D, 2D and 3D images supported.
References _mesa_get_format_bytes(), _mesa_image_address(), _mesa_image_image_stride(), _mesa_image_row_stride(), and GLubyte.
Referenced by _mesa_texstore_memcpy(), and _mesa_texstore_ycbcr().
static void store_texsubimage (struct gl_context * ctx, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing, const char * caller) static
Helper function for storing 1D, 2D, 3D whole and subimages into texture memory.
The source of the image data may be user memory or a PBO. In the later case, we'll map the PBO, copy from it, then unmap it.
References gl_texture_image::_BaseFormat, _mesa_error(), _mesa_image_image_stride(), _mesa_image_row_stride(), _mesa_texstore(), _mesa_unmap_teximage_pbo(), _mesa_validate_pbo_teximage(), _mesa_warning(), gl_context::Driver, get_read_write_mode(), GLbitfield, GLubyte, dd_function_table::MapTextureImage, gl_texture_object::Target, gl_texture_image::TexFormat, gl_texture_image::TexObject, and dd_function_table::UnmapTextureImage.
Referenced by _mesa_store_teximage(), and _mesa_store_texsubimage().
static GLboolean store_ubyte_texture (TEXSTORE_PARAMS) static
General-case function for storing a color texture images with components that can be represented with ubytes.
Example destination texture formats are MESA_FORMAT_ARGB888, ARGB4444, RGB565.
References _mesa_make_temp_ubyte_image(), _mesa_pack_ubyte_rgba_rect(), and GLubyte.
Referenced by _mesa_get_texstore_func(), _mesa_texstore_argb8888(), _mesa_texstore_bgr888(), _mesa_texstore_rgb565(), _mesa_texstore_rgb888(), and _mesa_texstore_rgba8888().
static void swizzle_copy (GLubyte * dst, GLuint dstComponents, const GLubyte * src, GLuint srcComponents, const GLubyte * map, GLuint count) static
Copy GLubyte pixels from <src> to <dst> with swizzling.
Parameters
dst destination pixels
dstComponents number of color components in destination pixels
src source pixels
srcComponents number of color components in source pixels
map the swizzle mapping. map[X] says where to find the X component in the source image's pixels. For example, if the source image is GL_BGRA and X = red, map[0] yields 2.
count number of pixels to copy/swizzle.
References ASSERT, GLubyte, ONE, SWZ_CPY, and ZERO.
Referenced by _mesa_swizzle_ubyte_image().
static const GLubyte* type_mapping (GLenum srcType) static
For 1-byte/pixel formats (or 8_8_8_8 packed formats), return a mapping array depending on endianness.
References _mesa_little_endian(), map_3210, map_identity, and NULL.
Referenced by _mesa_swizzle_ubyte_image().
Variable Documentation
GLubyte format_idx
GLubyte from_rgba[6]
const GLubyte map_3210[6] = { 3, 2, 1, 0, ZERO, ONE } static
Referenced by byteswap_mapping(), and type_mapping().
const GLubyte map_identity[6] = { 0, 1, 2, 3, ZERO, ONE } static
Referenced by byteswap_mapping(), and type_mapping().
struct { ... } mappings[MAX_IDX]
Referenced by compute_component_mapping().
GLubyte to_rgba[6]