Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texstate.c File Reference
Texture state handling.
#include "glheader.h"
#include "bufferobj.h"
#include "colormac.h"
#include "colortab.h"
#include "context.h"
#include "enums.h"
#include "macros.h"
#include "texobj.h"
#include "teximage.h"
#include "texstate.h"
#include "mtypes.h"
Functions
void _mesa_copy_texture_state (const struct gl_context *src, struct gl_context *dst)
Used by glXCopyContext to copy texture state from one context to another.
void _mesa_print_texunit_state (struct gl_context *ctx, GLuint unit)
static void calculate_derived_texenv (struct gl_tex_env_combine_state *state, GLenum mode, GLenum texBaseFormat)
Convert "classic" texture environment to ARB_texture_env_combine style environments.
void GLAPIENTRY _mesa_ActiveTexture (GLenum texture)
void GLAPIENTRY _mesa_ClientActiveTexture (GLenum texture)
static void update_texture_matrices (struct gl_context *ctx)
static void update_tex_combine (struct gl_context *ctx, struct gl_texture_unit *texUnit)
Examine texture unit's combine/env state to update derived state.
static void update_texgen (struct gl_context *ctx)
static void update_texture_state (struct gl_context *ctx)
void _mesa_update_texture (struct gl_context *ctx, GLuint new_state)
Update texture-related derived state.
static GLboolean alloc_proxy_textures (struct gl_context *ctx)
Allocate the proxy textures for the given context.
static void init_texture_unit (struct gl_context *ctx, GLuint unit)
Initialize a texture unit.
GLboolean _mesa_init_texture (struct gl_context *ctx)
Initialize texture state for the given context.
void _mesa_free_texture_data (struct gl_context *ctx)
Free dynamically-allocted texture data attached to the given context.
void _mesa_update_default_objects_texture (struct gl_context *ctx)
Update the default texture objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
Variables
static struct
gl_tex_env_combine_state default_combine_state
Default texture combine environment state.
Detailed Description
Texture state handling.
Function Documentation
void GLAPIENTRY _mesa_ActiveTexture (GLenum texture)
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _NEW_TEXTURE, ASSERT, Elements, FLUSH_VERTICES, MAX2, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table(), pop_enable_group(), and pop_texture_group().
void GLAPIENTRY _mesa_ClientActiveTexture (GLenum texture)
References _mesa_debug(), _mesa_error(), _mesa_lookup_enum_by_nr(), _NEW_ARRAY, FLUSH_VERTICES, MESA_VERBOSE, VERBOSE_API, and VERBOSE_TEXTURE.
Referenced by _mesa_initialize_exec_table().
void _mesa_copy_texture_state (const struct gl_context * src, struct gl_context * dst)
Used by glXCopyContext to copy texture state from one context to another.
References gl_texture_attrib::_GenFlags, _mesa_lock_context_textures(), _mesa_reference_texobj(), _mesa_unlock_context_textures(), gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, ASSERT, gl_texture_unit::BumpTarget, gl_texture_unit::Combine, gl_context::Const, COPY_4V, gl_texture_unit::CurrentTex, gl_texture_attrib::CurrentUnit, gl_texture_unit::Enabled, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, gl_texture_unit::LodBias, gl_constants::MaxCombinedTextureImageUnits, NUM_TEXTURE_TARGETS, gl_texture_unit::RotMatrix, gl_context::Shared, gl_texture_unit::TexGenEnabled, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_copy_context().
void _mesa_free_texture_data (struct gl_context * ctx)
Free dynamically-allocted texture data attached to the given context.
References gl_texture_unit::_Current, _mesa_reference_buffer_object(), _mesa_reference_sampler_object(), _mesa_reference_texobj(), gl_texture_attrib::BufferObject, gl_texture_unit::CurrentTex, dd_function_table::DeleteTexture, gl_context::Driver, Elements, NULL, NUM_TEXTURE_TARGETS, gl_texture_attrib::ProxyTex, gl_texture_unit::Sampler, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_free_context_data().
GLboolean _mesa_init_texture (struct gl_context * ctx)
Initialize texture state for the given context.
References gl_texture_attrib::_EnabledUnits, _mesa_reference_buffer_object(), alloc_proxy_textures(), gl_texture_attrib::BufferObject, gl_texture_attrib::CurrentUnit, gl_shared_state::DefaultTex, Elements, init_texture_unit(), MAX_COMBINED_TEXTURE_IMAGE_UNITS, gl_shared_state::NullBufferObj, gl_texture_object::RefCount, gl_context::Shared, gl_context::Texture, TEXTURE_1D_INDEX, and gl_texture_attrib::Unit.
Referenced by init_attrib_groups().
void _mesa_print_texunit_state (struct gl_context * ctx, GLuint unit)
References _mesa_lookup_enum_by_nr(), gl_texture_unit::Combine, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, gl_tex_env_combine_state::ScaleShiftA, gl_tex_env_combine_state::ScaleShiftRGB, gl_tex_env_combine_state::SourceA, gl_tex_env_combine_state::SourceRGB, gl_context::Texture, and gl_texture_attrib::Unit.
void _mesa_update_default_objects_texture (struct gl_context * ctx)
Update the default texture objects in the given context to reference those specified in the shared state and release those referencing the old shared state.
References _mesa_reference_texobj(), gl_texture_unit::CurrentTex, gl_shared_state::DefaultTex, Elements, NUM_TEXTURE_TARGETS, gl_context::Shared, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by update_default_objects().
void _mesa_update_texture (struct gl_context * ctx, GLuint new_state)
Update texture-related derived state.
References _NEW_PROGRAM, _NEW_TEXTURE, _NEW_TEXTURE_MATRIX, update_texture_matrices(), and update_texture_state().
Referenced by _mesa_update_state_locked().
static GLboolean alloc_proxy_textures (struct gl_context * ctx) static
Allocate the proxy textures for the given context.
Parameters
ctx the context to allocate proxies for.
Returns
GL_TRUE on success, or GL_FALSE on failure
If run out of memory part way through the allocations, clean up and return GL_FALSE.
References dd_function_table::DeleteTexture, gl_context::Driver, Elements, GL_TEXTURE_EXTERNAL_OES, dd_function_table::NewTextureObject, NUM_TEXTURE_TARGETS, gl_texture_attrib::ProxyTex, gl_texture_object::RefCount, STATIC_ASSERT, gl_context::Texture, TEXTURE_2D_INDEX, and TEXTURE_CUBE_INDEX.
Referenced by _mesa_init_texture().
static void calculate_derived_texenv (struct gl_tex_env_combine_state * state, GLenum mode, GLenum texBaseFormat) static
Convert "classic" texture environment to ARB_texture_env_combine style environments.
Parameters
state texture_env_combine state vector to be filled-in.
mode Classic texture environment mode (i.e., GL_REPLACE, GL_BLEND, GL_DECAL, etc.).
texBaseFormat Base format of the texture associated with the texture unit.
References _mesa_problem(), default_combine_state, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, NULL, gl_tex_env_combine_state::OperandA, gl_tex_env_combine_state::OperandRGB, gl_tex_env_combine_state::SourceA, and gl_tex_env_combine_state::SourceRGB.
Referenced by update_tex_combine().
static void init_texture_unit (struct gl_context * ctx, GLuint unit) static
Initialize a texture unit.
Parameters
ctx GL context.
unit texture unit number to be initialized.
References gl_texture_unit::_CurrentCombine, gl_texture_unit::_EnvMode, _mesa_reference_texobj(), gl_texgen::_ModeBit, ASSIGN_4V, gl_texture_unit::BumpTarget, gl_texture_unit::Combine, gl_texture_unit::CurrentTex, default_combine_state, gl_shared_state::DefaultTex, gl_texture_unit::EnvColor, gl_texture_unit::EnvMode, gl_texgen::EyePlane, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, gl_texgen::Mode, NUM_TEXTURE_TARGETS, gl_texgen::ObjectPlane, gl_texture_unit::RotMatrix, gl_context::Shared, TEXGEN_EYE_LINEAR, gl_texture_unit::TexGenEnabled, gl_context::Texture, and gl_texture_attrib::Unit.
Referenced by _mesa_init_texture().
static void update_tex_combine (struct gl_context * ctx, struct gl_texture_unit * texUnit) static
Examine texture unit's combine/env state to update derived state.
References gl_texture_image::_BaseFormat, gl_texture_unit::_Current, gl_texture_unit::_CurrentCombine, gl_texture_unit::_EnvMode, _mesa_problem(), gl_tex_env_combine_state::_NumArgsA, gl_tex_env_combine_state::_NumArgsRGB, gl_texture_object::BaseLevel, calculate_derived_texenv(), gl_texture_unit::Combine, gl_texture_object::DepthMode, gl_texture_unit::EnvMode, gl_texture_object::Image, gl_tex_env_combine_state::ModeA, gl_tex_env_combine_state::ModeRGB, and gl_texture_object::Target.
Referenced by update_texture_state().
static void update_texgen (struct gl_context * ctx) static
References gl_texture_attrib::_EnabledCoordUnits, gl_texture_unit::_GenFlags, gl_texture_attrib::_GenFlags, gl_texgen::_ModeBit, gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, ASSERT, gl_context::Const, Elements, ENABLE_TEXGEN, ENABLE_TEXMAT, gl_texture_unit::GenQ, gl_texture_unit::GenR, gl_texture_unit::GenS, gl_texture_unit::GenT, MATRIX_IDENTITY, gl_constants::MaxTextureCoordUnits, Q_BIT, R_BIT, S_BIT, T_BIT, gl_texture_unit::TexGenEnabled, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, GLmatrix::type, and gl_texture_attrib::Unit.
Referenced by update_texture_state().
static void update_texture_matrices (struct gl_context * ctx) static
Note
This routine refers to derived texture attribute values to compute the ENABLE_TEXMAT flags, but is only called on _NEW_TEXTURE_MATRIX. On changes to _NEW_TEXTURE, the ENABLE_TEXMAT flags are updated by _mesa_update_textures(), below.
Parameters
ctx GL context.
References _math_matrix_analyse(), _math_matrix_is_dirty(), gl_texture_unit::_ReallyEnabled, gl_texture_attrib::_TexMatEnabled, ASSERT, gl_context::Const, Elements, ENABLE_TEXMAT, MATRIX_IDENTITY, gl_constants::MaxTextureCoordUnits, gl_context::Texture, gl_context::TextureMatrixStack, gl_matrix_stack::Top, GLmatrix::type, and gl_texture_attrib::Unit.
Referenced by _mesa_update_texture().
static void update_texture_state (struct gl_context * ctx) static
Note
This routine refers to derived texture matrix values to compute the ENABLE_TEXMAT flags, but is only called on _NEW_TEXTURE. On changes to _NEW_TEXTURE_MATRIX, the ENABLE_TEXMAT flags are updated by _mesa_update_texture_matrices, above.
Parameters
ctx GL context.
References gl_texture_unit::_Current, gl_fragment_program_state::_Enabled, gl_texture_attrib::_EnabledCoordUnits, gl_texture_attrib::_EnabledUnits, gl_texture_attrib::_GenFlags, gl_shader_program::_LinkedShaders, _mesa_bitcount(), _mesa_get_fallback_texture(), _mesa_is_texture_complete(), _mesa_reference_texobj(), _mesa_test_texobj_completeness(), _NEW_TEXTURE, gl_texture_unit::_ReallyEnabled, gl_texture_attrib::_TexGenEnabled, gl_texture_attrib::_TexMatEnabled, gl_fragment_program::Base, gl_context::Const, gl_fragment_program_state::Current, gl_shader_state::CurrentFragmentProgram, gl_texture_unit::CurrentTex, gl_shader_state::CurrentVertexProgram, gl_texture_unit::Enabled, ffs(), gl_context::FragmentProgram, GLbitfield, gl_program::InputsRead, gl_shader_program::LinkStatus, MAX_TEXTURE_COORD_UNITS, gl_constants::MaxCombinedTextureImageUnits, MESA_SHADER_FRAGMENT, MESA_SHADER_VERTEX, gl_context::NewState, NULL, NUM_TEXTURE_TARGETS, gl_shader::Program, gl_texture_object::Sampler, gl_texture_unit::Sampler, gl_context::Shader, gl_context::Texture, gl_program::TexturesUsed, gl_texture_attrib::Unit, update_tex_combine(), update_texgen(), and VARYING_SLOT_TEX0.
Referenced by _mesa_update_texture().
Variable Documentation
struct gl_tex_env_combine_state default_combine_state static
Initial value:
= {
   GL_MODULATE, GL_MODULATE,
   { GL_TEXTURE, GL_PREVIOUS, GL_CONSTANT, GL_CONSTANT },
   { GL_TEXTURE, GL_PREVIOUS, GL_CONSTANT, GL_CONSTANT },
   { GL_SRC_COLOR, GL_SRC_COLOR, GL_SRC_ALPHA, GL_SRC_ALPHA },
   { GL_SRC_ALPHA, GL_SRC_ALPHA, GL_SRC_ALPHA, GL_SRC_ALPHA },
   0, 0,
   2, 2
}
Default texture combine environment state.
This is used to initialize a context's texture units and as the basis for converting "classic" texture environmnets to ARB_texture_env_combine style values.
Referenced by calculate_derived_texenv(), and init_texture_unit().