Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texstorage.c File Reference
GL_ARB_texture_storage functions.
#include "glheader.h"
#include "context.h"
#include "enums.h"
#include "imports.h"
#include "macros.h"
#include "teximage.h"
#include "texobj.h"
#include "texstorage.h"
#include "mtypes.h"
Functions
static GLboolean legal_texobj_target (struct gl_context *ctx, GLuint dims, GLenum target)
Check if the given texture target is a legal texture object target for a glTexStorage() command.
static void next_mipmap_level_size (GLenum target, GLint *width, GLint *height, GLint *depth)
Compute the size of the next mipmap level.
static struct gl_texture_image * get_tex_image (struct gl_context *ctx, struct gl_texture_object *texObj, GLuint face, GLuint level)
Helper to get a particular texture image in a texture object.
static GLboolean initialize_texture_fields (struct gl_context *ctx, struct gl_texture_object *texObj, GLint levels, GLsizei width, GLsizei height, GLsizei depth, GLenum internalFormat, gl_format texFormat)
static void clear_texture_fields (struct gl_context *ctx, struct gl_texture_object *texObj)
Clear all fields of texture object to zeros.
GLboolean _mesa_is_legal_tex_storage_format (struct gl_context *ctx, GLenum internalformat)
GLboolean _mesa_alloc_texture_storage (struct gl_context *ctx, struct gl_texture_object *texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
static GLboolean tex_storage_error_check (struct gl_context *ctx, GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Do error checking for calls to glTexStorage1/2/3D().
static void texstorage (GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Helper used by _mesa_TexStorage1/2/3D().
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Detailed Description
GL_ARB_texture_storage functions.
Function Documentation
GLboolean _mesa_alloc_texture_storage (struct gl_context * ctx, struct gl_texture_object * texObj, GLsizei levels, GLsizei width, GLsizei height, GLsizei depth)
Default ctx->Driver.AllocTextureStorage() handler.
The driver can override this with a more specific implementation if it desires, but this can be used to get the texture images allocated using the usual texture image handling code. The immutability of GL_ARB_texture_storage texture layouts is handled by texObj->Immutable checks at glTexImage* time.
References _mesa_num_tex_faces(), dd_function_table::AllocTextureImageBuffer, gl_context::Driver, gl_texture_object::Image, and gl_texture_object::Target.
GLboolean _mesa_is_legal_tex_storage_format (struct gl_context * ctx, GLenum internalformat)
References _mesa_base_tex_format().
Referenced by tex_storage_error_check(), and teximagemultisample().
void GLAPIENTRY _mesa_TexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
References texstorage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
References texstorage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
References texstorage().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TextureStorage1DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TextureStorage2DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TextureStorage3DEXT (GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth)
Referenced by _mesa_initialize_exec_table().
static void clear_texture_fields (struct gl_context * ctx, struct gl_texture_object * texObj) static
Clear all fields of texture object to zeros.
Used for proxy texture tests. Used for proxy texture tests (and to clean up when a texture memory allocation fails).
References _mesa_error(), _mesa_init_teximage_fields(), _mesa_num_tex_faces(), Elements, get_tex_image(), gl_texture_object::Image, MESA_FORMAT_NONE, and gl_texture_object::Target.
Referenced by texstorage().
static struct gl_texture_image* get_tex_image (struct gl_context * ctx, struct gl_texture_object * texObj, GLuint face, GLuint level) static read
Helper to get a particular texture image in a texture object.
References _mesa_get_tex_image(), and gl_texture_object::Target.
Referenced by clear_texture_fields(), and initialize_texture_fields().
static GLboolean initialize_texture_fields (struct gl_context * ctx, struct gl_texture_object * texObj, GLint levels, GLsizei width, GLsizei height, GLsizei depth, GLenum internalFormat, gl_format texFormat) static
References _mesa_error(), _mesa_init_teximage_fields(), _mesa_num_tex_faces(), get_tex_image(), next_mipmap_level_size(), and gl_texture_object::Target.
Referenced by texstorage().
static GLboolean legal_texobj_target (struct gl_context * ctx, GLuint dims, GLenum target) static
Check if the given texture target is a legal texture object target for a glTexStorage() command.
This is a bit different than legal_teximage_target() when it comes to cube maps.
References _mesa_problem(), gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_cube_map_array, gl_extensions::EXT_texture_array, gl_context::Extensions, gl_extensions::MESA_texture_array, and gl_extensions::NV_texture_rectangle.
Referenced by tex_storage_error_check().
static void next_mipmap_level_size (GLenum target, GLint * width, GLint * height, GLint * depth) static
Compute the size of the next mipmap level.
Referenced by initialize_texture_fields().
static GLboolean tex_storage_error_check (struct gl_context * ctx, GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) static
Do error checking for calls to glTexStorage1/2/3D().
If an error is found, record it with _mesa_error(), unless the target is a proxy texture.
Returns
GL_TRUE if any error, GL_FALSE otherwise.
References _mesa_error(), _mesa_get_current_tex_object(), _mesa_get_tex_max_num_levels(), _mesa_is_legal_tex_storage_format(), _mesa_lookup_enum_by_nr(), _mesa_max_texture_levels(), gl_texture_object::Immutable, legal_texobj_target(), and gl_texture_object::Name.
Referenced by texstorage().
static void texstorage (GLuint dims, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) static
Helper used by _mesa_TexStorage1/2/3D().
References _mesa_choose_texture_format(), _mesa_error(), _mesa_get_current_tex_object(), _mesa_is_proxy_texture(), _mesa_legal_texture_dimensions(), clear_texture_fields(), gl_texture_object::Immutable, gl_texture_object::ImmutableLevels, initialize_texture_fields(), MESA_FORMAT_NONE, gl_texture_object::Target, and tex_storage_error_check().
Referenced by _mesa_TexStorage1D(), _mesa_TexStorage2D(), and _mesa_TexStorage3D().