Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texstore.h File Reference
Texture image storage routines.
#include "mtypes.h"
#include "formats.h"
Macros
#define TEXSTORE_PARAMS
This macro defines the (many) parameters to the texstore functions.
Functions
GLboolean _mesa_texstore (TEXSTORE_PARAMS)
Store user data into texture memory.
GLboolean _mesa_texstore_needs_transfer_ops (struct gl_context *ctx, GLenum baseInternalFormat, gl_format dstFormat)
GLboolean _mesa_texstore_can_use_memcpy (struct gl_context *ctx, GLenum baseInternalFormat, gl_format dstFormat, GLenum srcFormat, GLenum srcType, const struct gl_pixelstore_attrib *srcPacking)
GLubyte * _mesa_make_temp_ubyte_image (struct gl_context *ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid *srcAddr, const struct gl_pixelstore_attrib *srcPacking)
Make a temporary (color) texture image with GLubyte components.
GLfloat * _mesa_make_temp_float_image (struct gl_context *ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid *srcAddr, const struct gl_pixelstore_attrib *srcPacking, GLbitfield transferOps)
Make a temporary (color) texture image with GLfloat components.
void _mesa_store_teximage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
Fallback code for ctx->Driver.TexImage().
void _mesa_store_texsubimage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const GLvoid *pixels, const struct gl_pixelstore_attrib *packing)
void _mesa_store_compressed_teximage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLsizei imageSize, const GLvoid *data)
Fallback for Driver.CompressedTexImage()
void _mesa_store_compressed_texsubimage (struct gl_context *ctx, GLuint dims, struct gl_texture_image *texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
Fallback for Driver.CompressedTexSubImage()
Detailed Description
Texture image storage routines.
Author
Brian Paul
Macro Definition Documentation
#define TEXSTORE_PARAMS
Value:
struct gl_context *ctx, GLuint dims, \
    GLenum baseInternalFormat, \
    gl_format dstFormat, \
        GLint dstRowStride, \
        GLubyte **dstSlices, \
    GLint srcWidth, GLint srcHeight, GLint srcDepth, \
    GLenum srcFormat, GLenum srcType, \
        const GLvoid *srcAddr, \
        const struct gl_pixelstore_attrib *srcPacking
This macro defines the (many) parameters to the texstore functions.
Parameters
dims either 1 or 2 or 3
baseInternalFormat user-specified base internal format
dstFormat destination Mesa texture format
dstX/Y/Zoffset destination x/y/z offset (ala TexSubImage), in texels
dstRowStride destination image row stride, in bytes
dstSlices array of addresses of image slices (for 3D, array texture)
srcWidth/Height/Depth source image size, in pixels
srcFormat incoming image format
srcType incoming image data type
srcAddr source image address
srcPacking source image packing parameters
Function Documentation
GLfloat* _mesa_make_temp_float_image (struct gl_context * ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid * srcAddr, const struct gl_pixelstore_attrib * srcPacking, GLbitfield transferOps)
Make a temporary (color) texture image with GLfloat components.
Apply all needed pixel unpacking and pixel transfer operations. Note that there are both logicalBaseFormat and textureBaseFormat parameters. Suppose the user specifies GL_LUMINANCE as the internal texture format but the graphics hardware doesn't support luminance textures. So, we might use an RGB hardware format instead. If logicalBaseFormat != textureBaseFormat we have some extra work to do.
Parameters
ctx the rendering context
dims image dimensions: 1, 2 or 3
logicalBaseFormat basic texture derived from the user's internal texture format value
textureBaseFormat the actual basic format of the texture
srcWidth source image width
srcHeight source image height
srcDepth source image depth
srcFormat source image format
srcType source image type
srcAddr source image address
srcPacking source image pixel packing
Returns
resulting image with format = textureBaseFormat and type = GLfloat.
References _mesa_components_in_format(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_color_span_float(), ASSERT, compute_component_mapping(), GLubyte, NULL, ONE, and ZERO.
Referenced by _mesa_texstore_argb2101010(), _mesa_texstore_r11_g11_b10f(), _mesa_texstore_rgb9_e5(), _mesa_texstore_rgba_16(), _mesa_texstore_rgba_float16(), _mesa_texstore_rgba_float32(), _mesa_texstore_signed_red_rgtc1(), _mesa_texstore_signed_rg_rgtc2(), _mesa_texstore_signed_rgba8888(), _mesa_texstore_signed_rgba_16(), _mesa_texstore_signed_rgbx8888(), _mesa_texstore_snorm16(), _mesa_texstore_snorm1616(), _mesa_texstore_snorm8(), _mesa_texstore_snorm88(), _mesa_texstore_unorm16(), and _mesa_texstore_unorm1616().
GLubyte* _mesa_make_temp_ubyte_image (struct gl_context * ctx, GLuint dims, GLenum logicalBaseFormat, GLenum textureBaseFormat, GLint srcWidth, GLint srcHeight, GLint srcDepth, GLenum srcFormat, GLenum srcType, const GLvoid * srcAddr, const struct gl_pixelstore_attrib * srcPacking)
Make a temporary (color) texture image with GLubyte components.
Apply all needed pixel unpacking and pixel transfer operations. Note that there are both logicalBaseFormat and textureBaseFormat parameters. Suppose the user specifies GL_LUMINANCE as the internal texture format but the graphics hardware doesn't support luminance textures. So, we might use an RGB hardware format instead. If logicalBaseFormat != textureBaseFormat we have some extra work to do.
Parameters
ctx the rendering context
dims image dimensions: 1, 2 or 3
logicalBaseFormat basic texture derived from the user's internal texture format value
textureBaseFormat the actual basic format of the texture
srcWidth source image width
srcHeight source image height
srcDepth source image depth
srcFormat source image format
srcType source image type
srcAddr source image address
srcPacking source image pixel packing
Returns
resulting image with format = textureBaseFormat and type = GLubyte.
References gl_context::_ImageTransferState, _mesa_components_in_format(), _mesa_image_address(), _mesa_image_row_stride(), _mesa_unpack_color_span_ubyte(), ASSERT, compute_component_mapping(), GLubyte, NULL, ONE, and ZERO.
Referenced by _mesa_texstore_red_rgtc1(), _mesa_texstore_rg_rgtc2(), _mesa_texstore_rgb_dxt1(), _mesa_texstore_rgb_fxt1(), _mesa_texstore_rgba_dxt1(), _mesa_texstore_rgba_dxt3(), _mesa_texstore_rgba_dxt5(), _mesa_texstore_rgba_fxt1(), _mesa_texstore_unorm44(), _mesa_texstore_unorm8(), _mesa_texstore_unorm88(), and store_ubyte_texture().
void _mesa_store_compressed_teximage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLsizei imageSize, const GLvoid * data)
Fallback for Driver.CompressedTexImage()
References _mesa_error(), _mesa_problem(), _mesa_store_compressed_texsubimage(), dd_function_table::AllocTextureImageBuffer, ASSERT, gl_texture_image::Depth, gl_context::Driver, gl_texture_image::Height, gl_texture_image::TexFormat, and gl_texture_image::Width.
void _mesa_store_compressed_texsubimage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
Fallback for Driver.CompressedTexSubImage()
References _mesa_error(), _mesa_format_row_stride(), _mesa_get_format_block_size(), _mesa_problem(), _mesa_unmap_teximage_pbo(), _mesa_validate_pbo_compressed_teximage(), gl_context::Driver, GLubyte, dd_function_table::MapTextureImage, gl_texture_image::TexFormat, dd_function_table::UnmapTextureImage, and gl_context::Unpack.
Referenced by _mesa_store_compressed_teximage().
void _mesa_store_teximage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing)
Fallback code for ctx->Driver.TexImage().
Basically, allocate storage for the texture image, then copy the user's image into it.
References _mesa_error(), dd_function_table::AllocTextureImageBuffer, gl_texture_image::Depth, gl_context::Driver, gl_texture_image::Height, store_texsubimage(), and gl_texture_image::Width.
void _mesa_store_texsubimage (struct gl_context * ctx, GLuint dims, struct gl_texture_image * texImage, GLint xoffset, GLint yoffset, GLint zoffset, GLint width, GLint height, GLint depth, GLenum format, GLenum type, const GLvoid * pixels, const struct gl_pixelstore_attrib * packing)
GLboolean _mesa_texstore (TEXSTORE_PARAMS)
Store user data into texture memory.
Called via glTex[Sub]Image1/2/3D()
References _mesa_get_texstore_func(), and _mesa_texstore_memcpy().
Referenced by store_texsubimage().
GLboolean _mesa_texstore_can_use_memcpy (struct gl_context * ctx, GLenum baseInternalFormat, gl_format dstFormat, GLenum srcFormat, GLenum srcType, const struct gl_pixelstore_attrib * srcPacking)
References _mesa_format_matches_format_and_type(), _mesa_get_format_base_format(), _mesa_texstore_needs_transfer_ops(), and gl_pixelstore_attrib::SwapBytes.
Referenced by _mesa_texstore_memcpy().
GLboolean _mesa_texstore_needs_transfer_ops (struct gl_context * ctx, GLenum baseInternalFormat, gl_format dstFormat)
References gl_context::_ImageTransferState, _mesa_get_format_datatype(), gl_pixel_attrib::DepthBias, gl_pixel_attrib::DepthScale, and gl_context::Pixel.
Referenced by _mesa_texstore_can_use_memcpy().