Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
texturebarrier.c File Reference
Implementation of glTextureBarrierNV.
#include "context.h"
#include "texturebarrier.h"
Functions
static void _mesa_texture_barrier (struct gl_context *ctx)
void _mesa_init_texture_barrier_functions (struct dd_function_table *driver)
void GLAPIENTRY _mesa_TextureBarrierNV (void)
Detailed Description
Implementation of glTextureBarrierNV.
Author
Marek Olšák marae.nosp@m.o@gm.nosp@m.ail.c.nosp@m.om
Function Documentation
void _mesa_init_texture_barrier_functions (struct dd_function_table * driver)
References _mesa_texture_barrier(), and dd_function_table::TextureBarrier.
static void _mesa_texture_barrier (struct gl_context * ctx) static
Referenced by _mesa_init_texture_barrier_functions().
void GLAPIENTRY _mesa_TextureBarrierNV (void)
Referenced by _mesa_initialize_exec_table().