Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
transformfeedback.c File Reference
#include "buffers.h"
#include "bufferobj.h"
#include "context.h"
#include "hash.h"
#include "macros.h"
#include "mtypes.h"
#include "transformfeedback.h"
#include "shaderapi.h"
#include "shaderobj.h"
#include "main/dispatch.h"
#include "program/prog_parameter.h"
Functions
static void reference_transform_feedback_object (struct gl_transform_feedback_object **ptr, struct gl_transform_feedback_object *obj)
Do reference counting of transform feedback buffers.
GLboolean _mesa_validate_transform_feedback_buffers (struct gl_context *ctx)
Check that all the buffer objects currently bound for transform feedback actually exist.
void _mesa_init_transform_feedback (struct gl_context *ctx)
Per-context init for transform feedback.
static void delete_cb (GLuint key, void *data, void *userData)
Callback for _mesa_HashDeleteAll().
void _mesa_free_transform_feedback (struct gl_context *ctx)
Per-context free/clean-up for transform feedback.
static struct
gl_transform_feedback_object * new_transform_feedback (struct gl_context *ctx, GLuint name)
Default fallback for ctx->Driver.NewTransformFeedback()
static void delete_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.DeleteTransformFeedback()
static void begin_transform_feedback (struct gl_context *ctx, GLenum mode, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.BeginTransformFeedback()
static void end_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.EndTransformFeedback()
static void pause_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.PauseTransformFeedback()
static void resume_transform_feedback (struct gl_context *ctx, struct gl_transform_feedback_object *obj)
Default fallback for ctx->Driver.ResumeTransformFeedback()
void _mesa_init_transform_feedback_functions (struct dd_function_table *driver)
Plug in default device driver functions for transform feedback.
static void compute_transform_feedback_buffer_sizes (struct gl_transform_feedback_object *obj)
Fill in the correct Size value for each buffer in obj.
unsigned _mesa_compute_max_transform_feedback_vertices (const struct gl_transform_feedback_object *obj, const struct gl_transform_feedback_info *info)
Compute the maximum number of vertices that can be written to the currently enabled transform feedback buffers without overflowing any of them.
void GLAPIENTRY _mesa_BeginTransformFeedback (GLenum mode)
Begin API functions.
void GLAPIENTRY _mesa_EndTransformFeedback (void)
static void bind_buffer_range (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size)
Helper used by BindBufferRange() and BindBufferBase().
void _mesa_bind_buffer_range_transform_feedback (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj, GLintptr offset, GLsizeiptr size)
Specify a buffer object to receive vertex shader results.
void _mesa_bind_buffer_base_transform_feedback (struct gl_context *ctx, GLuint index, struct gl_buffer_object *bufObj)
Specify a buffer object to receive vertex shader results.
void GLAPIENTRY _mesa_BindBufferOffsetEXT (GLenum target, GLuint index, GLuint buffer, GLintptr offset)
Specify a buffer object to receive vertex shader results, plus the offset in the buffer to start placing results.
void GLAPIENTRY _mesa_TransformFeedbackVaryings (GLuint program, GLsizei count, const GLchar *const *varyings, GLenum bufferMode)
This function specifies the vertex shader outputs to be written to the feedback buffer(s), and in what order.
void GLAPIENTRY _mesa_GetTransformFeedbackVarying (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name)
Get info about the vertex shader's outputs which are to be written to the feedback buffer(s).
struct
gl_transform_feedback_object * _mesa_lookup_transform_feedback_object (struct gl_context *ctx, GLuint name)
void GLAPIENTRY _mesa_GenTransformFeedbacks (GLsizei n, GLuint *names)
Create new transform feedback objects.
GLboolean GLAPIENTRY _mesa_IsTransformFeedback (GLuint name)
Is the given ID a transform feedback object? Part of GL_ARB_transform_feedback2.
void GLAPIENTRY _mesa_BindTransformFeedback (GLenum target, GLuint name)
Bind the given transform feedback object.
void GLAPIENTRY _mesa_DeleteTransformFeedbacks (GLsizei n, const GLuint *names)
Delete the given transform feedback objects.
void GLAPIENTRY _mesa_PauseTransformFeedback (void)
Pause transform feedback.
void GLAPIENTRY _mesa_ResumeTransformFeedback (void)
Resume transform feedback.
Function Documentation
void GLAPIENTRY _mesa_BeginTransformFeedback (GLenum mode)
Begin API functions.
References _mesa_compute_max_transform_feedback_vertices(), _mesa_error(), _mesa_is_gles3(), gl_transform_feedback_object::Active, gl_transform_feedback_object::BufferNames, compute_transform_feedback_buffer_sizes(), FLUSH_VERTICES, gl_transform_feedback_object::GlesRemainingPrims, NULL, gl_transform_feedback_info::NumBuffers, and gl_transform_feedback_info::NumOutputs.
Referenced by _mesa_initialize_exec_table().
void _mesa_bind_buffer_base_transform_feedback (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj)
Specify a buffer object to receive vertex shader results.
As above, but start at offset = 0. Called from the glBindBufferBase() function.
References _mesa_error(), gl_transform_feedback_object::Active, bind_buffer_range(), gl_context::Const, gl_transform_feedback_state::CurrentObject, gl_constants::MaxTransformFeedbackBuffers, and gl_context::TransformFeedback.
Referenced by _mesa_BindBufferBase().
void _mesa_bind_buffer_range_transform_feedback (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size)
Specify a buffer object to receive vertex shader results.
Plus, specify the starting offset to place the results, and max size. Called from the glBindBufferRange() function.
References _mesa_error(), gl_transform_feedback_object::Active, bind_buffer_range(), gl_context::Const, gl_transform_feedback_state::CurrentObject, gl_constants::MaxTransformFeedbackBuffers, and gl_context::TransformFeedback.
Referenced by _mesa_BindBufferRange().
void GLAPIENTRY _mesa_BindBufferOffsetEXT (GLenum target, GLuint index, GLuint buffer, GLintptr offset)
Specify a buffer object to receive vertex shader results, plus the offset in the buffer to start placing results.
This function is part of GL_EXT_transform_feedback, but not GL3.
References _mesa_error(), _mesa_lookup_bufferobj(), gl_transform_feedback_object::Active, and bind_buffer_range().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_BindTransformFeedback (GLenum target, GLuint name)
Bind the given transform feedback object.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), _mesa_lookup_transform_feedback_object(), and reference_transform_feedback_object().
Referenced by _mesa_initialize_exec_table().
unsigned _mesa_compute_max_transform_feedback_vertices (const struct gl_transform_feedback_object * obj, const struct gl_transform_feedback_info * info)
Compute the maximum number of vertices that can be written to the currently enabled transform feedback buffers without overflowing any of them.
References gl_transform_feedback_info::BufferStride, MIN2, gl_transform_feedback_info::NumBuffers, and gl_transform_feedback_object::Size.
Referenced by _mesa_BeginTransformFeedback().
void GLAPIENTRY _mesa_DeleteTransformFeedbacks (GLsizei n, const GLuint * names)
Delete the given transform feedback objects.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), _mesa_HashRemove(), _mesa_lookup_transform_feedback_object(), gl_transform_feedback_object::Active, NULL, and reference_transform_feedback_object().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_EndTransformFeedback (void)
References _mesa_error(), gl_transform_feedback_object::Active, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void _mesa_free_transform_feedback (struct gl_context * ctx)
Per-context free/clean-up for transform feedback.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), _mesa_reference_buffer_object(), ASSERT, gl_transform_feedback_state::CurrentBuffer, gl_transform_feedback_state::CurrentObject, gl_transform_feedback_state::DefaultObject, delete_cb(), dd_function_table::DeleteTransformFeedback, gl_context::Driver, dd_function_table::NewTransformFeedback, NULL, gl_transform_feedback_state::Objects, and gl_context::TransformFeedback.
Referenced by _mesa_free_context_data().
void GLAPIENTRY _mesa_GenTransformFeedbacks (GLsizei n, GLuint * names)
Create new transform feedback objects.
Transform feedback objects encapsulate the state related to transform feedback to allow quickly switching state (and drawing the results, below). Part of GL_ARB_transform_feedback2.
References _mesa_error(), _mesa_HashFindFreeKeyBlock(), and _mesa_HashInsert().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetTransformFeedbackVarying (GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLsizei * size, GLenum * type, GLchar * name)
Get info about the vertex shader's outputs which are to be written to the feedback buffer(s).
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader_program(), gl_shader_program::LinkedTransformFeedback, gl_transform_feedback_varying_info::Name, gl_transform_feedback_info::NumVarying, gl_transform_feedback_varying_info::Size, gl_transform_feedback_varying_info::Type, and gl_transform_feedback_info::Varyings.
Referenced by _mesa_initialize_exec_table().
void _mesa_init_transform_feedback (struct gl_context * ctx)
Per-context init for transform feedback.
References _mesa_NewHashTable(), _mesa_reference_buffer_object(), ASSERT, gl_transform_feedback_state::CurrentBuffer, gl_transform_feedback_state::CurrentObject, gl_transform_feedback_state::DefaultObject, gl_context::Driver, dd_function_table::NewTransformFeedback, gl_shared_state::NullBufferObj, gl_transform_feedback_state::Objects, gl_transform_feedback_object::RefCount, reference_transform_feedback_object(), gl_context::Shared, and gl_context::TransformFeedback.
Referenced by init_attrib_groups().
void _mesa_init_transform_feedback_functions (struct dd_function_table * driver)
Plug in default device driver functions for transform feedback.
Most drivers will override some/all of these.
References begin_transform_feedback(), dd_function_table::BeginTransformFeedback, delete_transform_feedback(), dd_function_table::DeleteTransformFeedback, end_transform_feedback(), dd_function_table::EndTransformFeedback, new_transform_feedback(), dd_function_table::NewTransformFeedback, pause_transform_feedback(), dd_function_table::PauseTransformFeedback, resume_transform_feedback(), and dd_function_table::ResumeTransformFeedback.
GLboolean GLAPIENTRY _mesa_IsTransformFeedback (GLuint name)
Is the given ID a transform feedback object? Part of GL_ARB_transform_feedback2.
References _mesa_lookup_transform_feedback_object(), ASSERT_OUTSIDE_BEGIN_END_WITH_RETVAL, gl_transform_feedback_object::EverBound, and NULL.
Referenced by _mesa_initialize_exec_table().
struct gl_transform_feedback_object* _mesa_lookup_transform_feedback_object (struct gl_context * ctx, GLuint name) read
References _mesa_HashLookup(), gl_transform_feedback_state::DefaultObject, gl_transform_feedback_state::Objects, and gl_context::TransformFeedback.
Referenced by _mesa_BindTransformFeedback(), _mesa_DeleteTransformFeedbacks(), and _mesa_IsTransformFeedback().
void GLAPIENTRY _mesa_PauseTransformFeedback (void)
Pause transform feedback.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), _mesa_is_xfb_active_and_unpaused(), FLUSH_VERTICES, and gl_transform_feedback_object::Paused.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_ResumeTransformFeedback (void)
Resume transform feedback.
Part of GL_ARB_transform_feedback2.
References _mesa_error(), gl_transform_feedback_object::Active, FLUSH_VERTICES, and gl_transform_feedback_object::Paused.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TransformFeedbackVaryings (GLuint program, GLsizei count, const GLchar *const * varyings, GLenum bufferMode)
This function specifies the vertex shader outputs to be written to the feedback buffer(s), and in what order.
References _mesa_error(), _mesa_lookup_shader_program(), _mesa_strdup(), gl_shader_program::BufferMode, gl_shader_program::NumVarying, gl_shader_program::TransformFeedback, and gl_shader_program::VaryingNames.
Referenced by _mesa_initialize_exec_table().
GLboolean _mesa_validate_transform_feedback_buffers (struct gl_context * ctx)
Check that all the buffer objects currently bound for transform feedback actually exist.
Raise a GL_INVALID_OPERATION error if any buffers are missing.
Returns
GL_TRUE for success, GL_FALSE if error
static void begin_transform_feedback (struct gl_context * ctx, GLenum mode, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.BeginTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().
static void bind_buffer_range (struct gl_context * ctx, GLuint index, struct gl_buffer_object * bufObj, GLintptr offset, GLsizeiptr size) static
Helper used by BindBufferRange() and BindBufferBase().
References _mesa_reference_buffer_object(), gl_transform_feedback_object::BufferNames, gl_transform_feedback_object::Buffers, gl_transform_feedback_state::CurrentBuffer, gl_transform_feedback_state::CurrentObject, gl_buffer_object::Name, gl_transform_feedback_object::Offset, gl_transform_feedback_object::RequestedSize, size, and gl_context::TransformFeedback.
Referenced by _mesa_bind_buffer_base_transform_feedback(), _mesa_bind_buffer_range_transform_feedback(), and _mesa_BindBufferOffsetEXT().
static void compute_transform_feedback_buffer_sizes (struct gl_transform_feedback_object * obj) static
Fill in the correct Size value for each buffer in obj.
From the GL 4.3 spec, section 6.1.1 ("Binding Buffer Objects to Indexed Targets"):
BindBufferBase binds the entire buffer, even when the size of the buffer is changed after the binding is established. It is equivalent to calling BindBufferRange with offset zero, while size is determined by the size of the bound buffer at the time the binding is used.
Regardless of the size specified with BindBufferRange, or indirectly with BindBufferBase, the GL will never read or write beyond the end of a bound buffer. In some cases this constraint may result in visibly different behavior when a buffer overflow would otherwise result, such as described for transform feedback operations in section 13.2.2.
References gl_transform_feedback_object::Buffers, GLintptr, GLsizeiptr, MAX_FEEDBACK_BUFFERS, MIN2, NULL, gl_transform_feedback_object::Offset, gl_transform_feedback_object::RequestedSize, gl_buffer_object::Size, and gl_transform_feedback_object::Size.
Referenced by _mesa_BeginTransformFeedback().
static void delete_cb (GLuint key, void * data, void * userData) static
Callback for _mesa_HashDeleteAll().
References dd_function_table::DeleteTransformFeedback, and gl_context::Driver.
Referenced by _mesa_free_transform_feedback().
static void delete_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.DeleteTransformFeedback()
References _mesa_reference_buffer_object(), gl_transform_feedback_object::Buffers, Elements, and NULL.
Referenced by _mesa_init_transform_feedback_functions().
static void end_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.EndTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().
static struct gl_transform_feedback_object* new_transform_feedback (struct gl_context * ctx, GLuint name) static read
Default fallback for ctx->Driver.NewTransformFeedback()
References CALLOC_STRUCT, gl_transform_feedback_object::EverBound, gl_transform_feedback_object::Name, and gl_transform_feedback_object::RefCount.
Referenced by _mesa_init_transform_feedback_functions().
static void pause_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.PauseTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().
static void reference_transform_feedback_object (struct gl_transform_feedback_object ** ptr, struct gl_transform_feedback_object * obj) static
Do reference counting of transform feedback buffers.
References _mesa_problem(), ASSERT, gl_transform_feedback_object::EverBound, NULL, and gl_transform_feedback_object::RefCount.
Referenced by _mesa_BindTransformFeedback(), _mesa_DeleteTransformFeedbacks(), and _mesa_init_transform_feedback().
static void resume_transform_feedback (struct gl_context * ctx, struct gl_transform_feedback_object * obj) static
Default fallback for ctx->Driver.ResumeTransformFeedback()
Referenced by _mesa_init_transform_feedback_functions().