Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
uniforms.c File Reference
Functions related to GLSL uniform variables.
#include "main/glheader.h"
#include "main/context.h"
#include "main/dispatch.h"
#include "main/shaderapi.h"
#include "main/shaderobj.h"
#include "main/uniforms.h"
#include "main/enums.h"
#include "ir_uniform.h"
#include "glsl_types.h"
#include "program/program.h"
Functions
void _mesa_update_shader_textures_used (struct gl_shader_program *shProg, struct gl_program *prog)
XXX things to do:
void _mesa_uniform_attach_driver_storage (struct gl_uniform_storage *uni, unsigned element_stride, unsigned vector_stride, enum gl_uniform_driver_format format, void *data)
Connect a piece of driver storage with a part of a uniform.
void _mesa_uniform_detach_all_driver_storage (struct gl_uniform_storage *uni)
Sever all connections with all pieces of driver storage for all uniforms.
void GLAPIENTRY _mesa_Uniform1f (GLint location, GLfloat v0)
void GLAPIENTRY _mesa_Uniform2f (GLint location, GLfloat v0, GLfloat v1)
void GLAPIENTRY _mesa_Uniform3f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
void GLAPIENTRY _mesa_Uniform4f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
void GLAPIENTRY _mesa_Uniform1i (GLint location, GLint v0)
void GLAPIENTRY _mesa_Uniform2i (GLint location, GLint v0, GLint v1)
void GLAPIENTRY _mesa_Uniform3i (GLint location, GLint v0, GLint v1, GLint v2)
void GLAPIENTRY _mesa_Uniform4i (GLint location, GLint v0, GLint v1, GLint v2, GLint v3)
void GLAPIENTRY _mesa_Uniform1fv (GLint location, GLsizei count, const GLfloat *value)
void GLAPIENTRY _mesa_Uniform2fv (GLint location, GLsizei count, const GLfloat *value)
void GLAPIENTRY _mesa_Uniform3fv (GLint location, GLsizei count, const GLfloat *value)
void GLAPIENTRY _mesa_Uniform4fv (GLint location, GLsizei count, const GLfloat *value)
void GLAPIENTRY _mesa_Uniform1iv (GLint location, GLsizei count, const GLint *value)
void GLAPIENTRY _mesa_Uniform2iv (GLint location, GLsizei count, const GLint *value)
void GLAPIENTRY _mesa_Uniform3iv (GLint location, GLsizei count, const GLint *value)
void GLAPIENTRY _mesa_Uniform4iv (GLint location, GLsizei count, const GLint *value)
void GLAPIENTRY _mesa_Uniform1ui (GLint location, GLuint v0)
OpenGL 3.0 GLuint-valued functions.
void GLAPIENTRY _mesa_Uniform2ui (GLint location, GLuint v0, GLuint v1)
void GLAPIENTRY _mesa_Uniform3ui (GLint location, GLuint v0, GLuint v1, GLuint v2)
void GLAPIENTRY _mesa_Uniform4ui (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
void GLAPIENTRY _mesa_Uniform1uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_Uniform2uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_Uniform3uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_Uniform4uiv (GLint location, GLsizei count, const GLuint *value)
void GLAPIENTRY _mesa_UniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
Non-square UniformMatrix are OpenGL 2.1.
void GLAPIENTRY _mesa_UniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_UniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GLAPIENTRY _mesa_GetnUniformfvARB (GLhandleARB program, GLint location, GLsizei bufSize, GLfloat *params)
void GLAPIENTRY _mesa_GetUniformfv (GLhandleARB program, GLint location, GLfloat *params)
void GLAPIENTRY _mesa_GetnUniformivARB (GLhandleARB program, GLint location, GLsizei bufSize, GLint *params)
void GLAPIENTRY _mesa_GetUniformiv (GLhandleARB program, GLint location, GLint *params)
void GLAPIENTRY _mesa_GetnUniformuivARB (GLhandleARB program, GLint location, GLsizei bufSize, GLuint *params)
void GLAPIENTRY _mesa_GetUniformuiv (GLhandleARB program, GLint location, GLuint *params)
void GLAPIENTRY _mesa_GetnUniformdvARB (GLhandleARB program, GLint location, GLsizei bufSize, GLdouble *params)
void GLAPIENTRY _mesa_GetUniformdv (GLhandleARB program, GLint location, GLdouble *params)
GLint GLAPIENTRY _mesa_GetUniformLocation (GLhandleARB programObj, const GLcharARB *name)
GLuint GLAPIENTRY _mesa_GetUniformBlockIndex (GLuint program, const GLchar *uniformBlockName)
void GLAPIENTRY _mesa_GetUniformIndices (GLuint program, GLsizei uniformCount, const GLchar *const *uniformNames, GLuint *uniformIndices)
void GLAPIENTRY _mesa_UniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
void GLAPIENTRY _mesa_GetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetActiveUniformBlockName (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName)
void GLAPIENTRY _mesa_GetActiveUniformName (GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName)
void _mesa_get_uniform_name (const struct gl_uniform_storage *uni, GLsizei maxLength, GLsizei *length, GLchar *nameOut)
Detailed Description
Functions related to GLSL uniform variables.
Author
Brian Paul
Function Documentation
void _mesa_get_uniform_name (const struct gl_uniform_storage * uni, GLsizei maxLength, GLsizei * length, GLchar * nameOut)
References _mesa_copy_string(), and NULL.
Referenced by _mesa_GetActiveUniformName().
void GLAPIENTRY _mesa_GetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint * params)
References _mesa_error(), _mesa_get_uniform_location(), _mesa_lookup_enum_by_nr(), _mesa_lookup_shader_program_err(), gl_uniform_block::Binding, gl_uniform_buffer_variable::IndexName, MESA_SHADER_FRAGMENT, MESA_SHADER_GEOMETRY, MESA_SHADER_VERTEX, gl_uniform_block::Name, gl_shader_program::NumUniformBlocks, gl_uniform_block::NumUniforms, gl_shader_program::UniformBlocks, gl_shader_program::UniformBlockStageIndex, gl_uniform_block::UniformBufferSize, and gl_uniform_block::Uniforms.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetActiveUniformBlockName (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformBlockName)
References _mesa_copy_string(), _mesa_error(), _mesa_lookup_shader_program_err(), gl_uniform_block::Name, gl_shader_program::NumUniformBlocks, and gl_shader_program::UniformBlocks.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetActiveUniformName (GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformName)
References _mesa_error(), _mesa_get_uniform_name(), _mesa_lookup_shader_program_err(), gl_shader_program::NumUserUniformStorage, and gl_shader_program::UniformStorage.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnUniformdvARB (GLhandleARB program, GLint location, GLsizei bufSize, GLdouble * params)
References _mesa_error(), and void().
Referenced by _mesa_GetUniformdv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnUniformfvARB (GLhandleARB program, GLint location, GLsizei bufSize, GLfloat * params)
References _mesa_get_uniform().
Referenced by _mesa_GetUniformfv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnUniformivARB (GLhandleARB program, GLint location, GLsizei bufSize, GLint * params)
References _mesa_get_uniform().
Referenced by _mesa_GetUniformiv(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetnUniformuivARB (GLhandleARB program, GLint location, GLsizei bufSize, GLuint * params)
References _mesa_get_uniform().
Referenced by _mesa_GetUniformuiv(), and _mesa_initialize_exec_table().
GLuint GLAPIENTRY _mesa_GetUniformBlockIndex (GLuint program, const GLchar * uniformBlockName)
References _mesa_error(), _mesa_lookup_shader_program_err(), gl_uniform_block::Name, gl_shader_program::NumUniformBlocks, and gl_shader_program::UniformBlocks.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetUniformdv (GLhandleARB program, GLint location, GLdouble * params)
References _mesa_GetnUniformdvARB().
void GLAPIENTRY _mesa_GetUniformfv (GLhandleARB program, GLint location, GLfloat * params)
References _mesa_GetnUniformfvARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetUniformIndices (GLuint program, GLsizei uniformCount, const GLchar *const * uniformNames, GLuint * uniformIndices)
References _mesa_error(), _mesa_get_uniform_location(), and _mesa_lookup_shader_program_err().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetUniformiv (GLhandleARB program, GLint location, GLint * params)
References _mesa_GetnUniformivARB().
Referenced by _mesa_initialize_exec_table().
GLint GLAPIENTRY _mesa_GetUniformLocation (GLhandleARB programObj, const GLcharARB * name)
References _mesa_error(), _mesa_get_uniform_location(), _mesa_lookup_shader_program_err(), _mesa_uniform_merge_location_offset(), gl_shader_program::LinkStatus, and gl_shader_program::UniformStorage.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetUniformuiv (GLhandleARB program, GLint location, GLuint * params)
References _mesa_GetnUniformuivARB().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform1f (GLint location, GLfloat v0)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform1fv (GLint location, GLsizei count, const GLfloat * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform1i (GLint location, GLint v0)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform1iv (GLint location, GLsizei count, const GLint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform1ui (GLint location, GLuint v0)
OpenGL 3.0 GLuint-valued functions.
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform1uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform2f (GLint location, GLfloat v0, GLfloat v1)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform2fv (GLint location, GLsizei count, const GLfloat * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform2i (GLint location, GLint v0, GLint v1)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform2iv (GLint location, GLsizei count, const GLint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform2ui (GLint location, GLuint v0, GLuint v1)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform2uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform3f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform3fv (GLint location, GLsizei count, const GLfloat * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform3i (GLint location, GLint v0, GLint v1, GLint v2)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform3iv (GLint location, GLsizei count, const GLint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform3ui (GLint location, GLuint v0, GLuint v1, GLuint v2)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform3uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform4f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform4fv (GLint location, GLsizei count, const GLfloat * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform4i (GLint location, GLint v0, GLint v1, GLint v2, GLint v3)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform4iv (GLint location, GLsizei count, const GLint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform4ui (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_Uniform4uiv (GLint location, GLsizei count, const GLuint * value)
References _mesa_uniform().
Referenced by _mesa_initialize_exec_table().
void _mesa_uniform_attach_driver_storage (struct gl_uniform_storage * uni, unsigned element_stride, unsigned vector_stride, enum gl_uniform_driver_format format, void * data)
Connect a piece of driver storage with a part of a uniform.
Parameters
uni The uniform with which the storage will be associated
element_stride Byte-stride between array elements.
See Also
gl_uniform_driver_storage::element_stride.
Parameters
vector_stride Byte-stride between vectors (in a matrix).
See Also
gl_uniform_driver_storage::vector_stride.
Parameters
format Conversion from native format to driver format required by the driver.
data Location to dump the data.
void _mesa_uniform_detach_all_driver_storage (struct gl_uniform_storage * uni)
Sever all connections with all pieces of driver storage for all uniforms.
Warning
This function does not release any of the data pointers previously passed in to _mesa_uniform_attach_driver_stoarge.
References NULL.
Referenced by _mesa_clear_shader_program_data().
void GLAPIENTRY _mesa_UniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
References gl_shader_program::_LinkedShaders, _mesa_error(), _mesa_lookup_shader_program_err(), gl_uniform_block::Binding, FLUSH_VERTICES, MESA_SHADER_TYPES, gl_shader_program::NumUniformBlocks, gl_shader::UniformBlocks, gl_shader_program::UniformBlocks, and gl_shader_program::UniformBlockStageIndex.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Non-square UniformMatrix are OpenGL 2.1.
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
References _mesa_uniform_matrix().
Referenced by _mesa_initialize_exec_table().
void _mesa_update_shader_textures_used (struct gl_shader_program * shProg, struct gl_program * prog)
XXX things to do:
Check that the right error code is generated for all _mesa_error() calls.
Insert FLUSH_VERTICES calls in various places Update the vertex/fragment program's TexturesUsed array.
This needs to be called after glUniform(set sampler var) is called. A call to glUniform(samplerVar, value) causes a sampler to point to a particular texture unit. We know the sampler's texture target (1D/2D/3D/etc) from compile time but the sampler's texture unit is set by glUniform() calls.
So, scan the program->SamplerUnits[] and program->SamplerTargets[] information to update the prog->TexturesUsed[] values. Each value of TexturesUsed[unit] is one of zero, TEXTURE_1D_INDEX, TEXTURE_2D_INDEX, TEXTURE_3D_INDEX, etc. We'll use that info for state validation before rendering.
References gl_shader_program::_LinkedShaders, Elements, MAX_SAMPLERS, NUM_TEXTURE_TARGETS, gl_program::SamplersUsed, gl_shader::SamplerTargets, gl_program::SamplerUnits, gl_shader::SamplerUnits, gl_program::Target, and gl_program::TexturesUsed.