Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
varray.c File Reference
#include "glheader.h"
#include "imports.h"
#include "bufferobj.h"
#include "context.h"
#include "enable.h"
#include "enums.h"
#include "hash.h"
#include "image.h"
#include "macros.h"
#include "mtypes.h"
#include "varray.h"
#include "arrayobj.h"
#include "main/dispatch.h"
Macros
#define BGRA_OR_4 5
Used to do error checking for GL_EXT_vertex_array_bgra.
#define BOOL_BIT 0x1
Used to indicate which GL datatypes are accepted by each of the glVertex/Color/Attrib/EtcPointer() functions.
#define BYTE_BIT 0x2
#define UNSIGNED_BYTE_BIT 0x4
#define SHORT_BIT 0x8
#define UNSIGNED_SHORT_BIT 0x10
#define INT_BIT 0x20
#define UNSIGNED_INT_BIT 0x40
#define HALF_BIT 0x80
#define FLOAT_BIT 0x100
#define DOUBLE_BIT 0x200
#define FIXED_ES_BIT 0x400
#define FIXED_GL_BIT 0x800
#define UNSIGNED_INT_2_10_10_10_REV_BIT 0x1000
#define INT_2_10_10_10_REV_BIT 0x2000
Functions
static GLbitfield type_to_bit (const struct gl_context *ctx, GLenum type)
Convert GL datatype enum into a <type>_BIT value seen above.
static void update_array (struct gl_context *ctx, const char *func, GLuint attrib, GLbitfield legalTypesMask, GLint sizeMin, GLint sizeMax, GLint size, GLenum type, GLsizei stride, GLboolean normalized, GLboolean integer, const GLvoid *ptr)
Do error checking and update state for glVertex/Color/TexCoord/...Pointer functions.
void GLAPIENTRY _mesa_VertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_NormalPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_ColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_FogCoordPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_IndexPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_SecondaryColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_TexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_EdgeFlagPointer (GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_PointSizePointerOES (GLenum type, GLsizei stride, const GLvoid *ptr)
void GLAPIENTRY _mesa_VertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *ptr)
Set a generic vertex attribute array.
void GLAPIENTRY _mesa_VertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
GL_EXT_gpu_shader4 / GL 3.0.
void GLAPIENTRY _mesa_EnableVertexAttribArray (GLuint index)
void GLAPIENTRY _mesa_DisableVertexAttribArray (GLuint index)
static GLuint get_vertex_array_attrib (struct gl_context *ctx, GLuint index, GLenum pname, const char *caller)
Return info for a vertex attribute array (no alias with legacy vertex attributes (pos, normal, color, etc)).
static const GLfloat * get_current_attrib (struct gl_context *ctx, GLuint index, const char *function)
void GLAPIENTRY _mesa_GetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params)
void GLAPIENTRY _mesa_GetVertexAttribdv (GLuint index, GLenum pname, GLdouble *params)
void GLAPIENTRY _mesa_GetVertexAttribiv (GLuint index, GLenum pname, GLint *params)
void GLAPIENTRY _mesa_GetVertexAttribIiv (GLuint index, GLenum pname, GLint *params)
GL 3.0.
void GLAPIENTRY _mesa_GetVertexAttribIuiv (GLuint index, GLenum pname, GLuint *params)
GL 3.0.
void GLAPIENTRY _mesa_GetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid **pointer)
void GLAPIENTRY _mesa_VertexPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_NormalPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_ColorPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_IndexPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_TexCoordPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *ptr)
void GLAPIENTRY _mesa_EdgeFlagPointerEXT (GLsizei stride, GLsizei count, const GLboolean *ptr)
void GLAPIENTRY _mesa_InterleavedArrays (GLenum format, GLsizei stride, const GLvoid *pointer)
void GLAPIENTRY _mesa_LockArraysEXT (GLint first, GLsizei count)
void GLAPIENTRY _mesa_UnlockArraysEXT (void)
void GLAPIENTRY _mesa_MultiDrawArrays (GLenum mode, const GLint *first, const GLsizei *count, GLsizei primcount)
void GLAPIENTRY _mesa_MultiModeDrawArraysIBM (const GLenum *mode, const GLint *first, const GLsizei *count, GLsizei primcount, GLint modestride)
void GLAPIENTRY _mesa_MultiModeDrawElementsIBM (const GLenum *mode, const GLsizei *count, GLenum type, const GLvoid *const *indices, GLsizei primcount, GLint modestride)
void GLAPIENTRY _mesa_PrimitiveRestartIndex (GLuint index)
GL_NV_primitive_restart and GL 3.1.
void GLAPIENTRY _mesa_VertexAttribDivisor (GLuint index, GLuint divisor)
See GL_ARB_instanced_arrays.
unsigned _mesa_primitive_restart_index (const struct gl_context *ctx, GLenum ib_type)
void _mesa_copy_client_array (struct gl_context *ctx, struct gl_client_array *dst, struct gl_client_array *src)
Copy one client vertex array to another.
static void print_array (const char *name, GLint index, const struct gl_client_array *array)
Print vertex array's fields.
void _mesa_print_arrays (struct gl_context *ctx)
Print current vertex object/array info.
void _mesa_init_varray (struct gl_context *ctx)
Initialize vertex array state for given context.
static void delete_arrayobj_cb (GLuint id, void *data, void *userData)
Callback for deleting an array object.
void _mesa_free_varray_data (struct gl_context *ctx)
Free vertex array state for given context.
Macro Definition Documentation
#define BGRA_OR_4 5
Used to do error checking for GL_EXT_vertex_array_bgra.
Referenced by _mesa_ColorPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexAttribPointer(), and update_array().
#define BOOL_BIT 0x1
Used to indicate which GL datatypes are accepted by each of the glVertex/Color/Attrib/EtcPointer() functions.
Referenced by type_to_bit().
#define BYTE_BIT 0x2
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), and type_to_bit().
#define DOUBLE_BIT 0x200
Referenced by _mesa_ColorPointer(), _mesa_FogCoordPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), type_to_bit(), and update_array().
#define FIXED_ES_BIT 0x400
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_PointSizePointerOES(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), type_to_bit(), and update_array().
#define FIXED_GL_BIT 0x800
Referenced by _mesa_VertexAttribPointer(), type_to_bit(), and update_array().
#define FLOAT_BIT 0x100
Referenced by _mesa_ColorPointer(), _mesa_FogCoordPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_PointSizePointerOES(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), and type_to_bit().
#define HALF_BIT 0x80
Referenced by _mesa_ColorPointer(), _mesa_FogCoordPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), type_to_bit(), and update_array().
#define INT_2_10_10_10_REV_BIT 0x2000
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), type_to_bit(), and update_array().
#define INT_BIT 0x20
Referenced by _mesa_ColorPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), type_to_bit(), and update_array().
#define SHORT_BIT 0x8
Referenced by _mesa_ColorPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), and type_to_bit().
#define UNSIGNED_BYTE_BIT 0x4
Referenced by _mesa_ColorPointer(), _mesa_EdgeFlagPointer(), _mesa_IndexPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), and type_to_bit().
#define UNSIGNED_INT_2_10_10_10_REV_BIT 0x1000
Referenced by _mesa_ColorPointer(), _mesa_NormalPointer(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribPointer(), _mesa_VertexPointer(), type_to_bit(), and update_array().
#define UNSIGNED_INT_BIT 0x40
Referenced by _mesa_ColorPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), type_to_bit(), and update_array().
#define UNSIGNED_SHORT_BIT 0x10
Referenced by _mesa_ColorPointer(), _mesa_SecondaryColorPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), and type_to_bit().
Function Documentation
void GLAPIENTRY _mesa_ColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, update_array(), and VERT_ATTRIB_COLOR0.
Referenced by _mesa_ColorPointerEXT(), _mesa_initialize_exec_table(), and _mesa_InterleavedArrays().
void GLAPIENTRY _mesa_ColorPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_ColorPointer(), and void().
Referenced by _mesa_initialize_exec_table().
void _mesa_copy_client_array (struct gl_context * ctx, struct gl_client_array * dst, struct gl_client_array * src)
Copy one client vertex array to another.
References gl_client_array::_ElementSize, gl_client_array::_MaxElement, _mesa_reference_buffer_object(), gl_client_array::BufferObj, gl_client_array::Enabled, gl_client_array::Format, gl_client_array::InstanceDivisor, gl_client_array::Integer, gl_client_array::Normalized, gl_client_array::Ptr, gl_client_array::Size, gl_client_array::Stride, gl_client_array::StrideB, and gl_client_array::Type.
Referenced by copy_array_object().
void GLAPIENTRY _mesa_DisableVertexAttribArray (GLuint index)
References gl_array_object::_Enabled, _mesa_error(), _NEW_ARRAY, ASSERT, Elements, gl_client_array::Enabled, FLUSH_VERTICES, VERT_ATTRIB_GENERIC, VERT_BIT_GENERIC, and gl_array_object::VertexAttrib.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_EdgeFlagPointer (GLsizei stride, const GLvoid * ptr)
References FLUSH_VERTICES, GLbitfield, UNSIGNED_BYTE_BIT, update_array(), and VERT_ATTRIB_EDGEFLAG.
Referenced by _mesa_EdgeFlagPointerEXT(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_EdgeFlagPointerEXT (GLsizei stride, GLsizei count, const GLboolean * ptr)
References _mesa_EdgeFlagPointer(), and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_EnableVertexAttribArray (GLuint index)
References gl_array_object::_Enabled, _mesa_error(), _NEW_ARRAY, ASSERT, Elements, gl_client_array::Enabled, FLUSH_VERTICES, VERT_ATTRIB_GENERIC, VERT_BIT_GENERIC, and gl_array_object::VertexAttrib.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_FogCoordPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, HALF_BIT, update_array(), and VERT_ATTRIB_FOG.
Referenced by _mesa_initialize_exec_table().
void _mesa_free_varray_data (struct gl_context * ctx)
Free vertex array state for given context.
References _mesa_DeleteHashTable(), _mesa_HashDeleteAll(), gl_context::Array, delete_arrayobj_cb(), and gl_array_attrib::Objects.
Referenced by _mesa_free_context_data().
void GLAPIENTRY _mesa_GetVertexAttribdv (GLuint index, GLenum pname, GLdouble * params)
References get_current_attrib(), get_vertex_array_attrib(), and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetVertexAttribfv (GLuint index, GLenum pname, GLfloat * params)
References COPY_4V, get_current_attrib(), get_vertex_array_attrib(), and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetVertexAttribIiv (GLuint index, GLenum pname, GLint * params)
GL 3.0.
References COPY_4V, get_current_attrib(), get_vertex_array_attrib(), and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetVertexAttribIuiv (GLuint index, GLenum pname, GLuint * params)
GL 3.0.
References COPY_4V, get_current_attrib(), get_vertex_array_attrib(), and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetVertexAttribiv (GLuint index, GLenum pname, GLint * params)
References get_current_attrib(), get_vertex_array_attrib(), and NULL.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_GetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid ** pointer)
References _mesa_error(), ASSERT, Elements, and VERT_ATTRIB_GENERIC.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_IndexPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, update_array(), and VERT_ATTRIB_COLOR_INDEX.
Referenced by _mesa_IndexPointerEXT(), and _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_IndexPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_IndexPointer(), and void().
Referenced by _mesa_initialize_exec_table().
void _mesa_init_varray (struct gl_context * ctx)
Initialize vertex array state for given context.
References _mesa_NewHashTable(), _mesa_reference_array_object(), gl_array_attrib::ActiveTexture, gl_context::Array, gl_array_attrib::ArrayObj, gl_array_attrib::DefaultArrayObj, gl_context::Driver, dd_function_table::NewArrayObject, and gl_array_attrib::Objects.
Referenced by init_attrib_groups().
void GLAPIENTRY _mesa_InterleavedArrays (GLenum format, GLsizei stride, const GLvoid * pointer)
References _mesa_ColorPointer(), _mesa_DisableClientState(), _mesa_EnableClientState(), _mesa_error(), _mesa_NormalPointer(), _mesa_TexCoordPointer(), _mesa_VertexPointer(), FLUSH_VERTICES, and GLubyte.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_LockArraysEXT (GLint first, GLsizei count)
References _mesa_debug(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_MultiDrawArrays (GLenum mode, const GLint * first, const GLsizei * count, GLsizei primcount)
References CALL_DrawArrays, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_MultiModeDrawArraysIBM (const GLenum * mode, const GLint * first, const GLsizei * count, GLsizei primcount, GLint modestride)
References CALL_DrawArrays, FLUSH_VERTICES, and GLubyte.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_MultiModeDrawElementsIBM (const GLenum * mode, const GLsizei * count, GLenum type, const GLvoid *const * indices, GLsizei primcount, GLint modestride)
References CALL_DrawElements, FLUSH_VERTICES, and GLubyte.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_NormalPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, update_array(), and VERT_ATTRIB_NORMAL.
Referenced by _mesa_initialize_exec_table(), _mesa_InterleavedArrays(), and _mesa_NormalPointerEXT().
void GLAPIENTRY _mesa_NormalPointerEXT (GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_NormalPointer(), and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_PointSizePointerOES (GLenum type, GLsizei stride, const GLvoid * ptr)
References _mesa_error(), API_OPENGLES, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, update_array(), and VERT_ATTRIB_POINT_SIZE.
Referenced by _mesa_initialize_exec_table().
unsigned _mesa_primitive_restart_index (const struct gl_context * ctx, GLenum ib_type)
References gl_context::Array, gl_array_attrib::PrimitiveRestartFixedIndex, and gl_array_attrib::RestartIndex.
void GLAPIENTRY _mesa_PrimitiveRestartIndex (GLuint index)
GL_NV_primitive_restart and GL 3.1.
References _mesa_error(), _NEW_TRANSFORM, and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table().
void _mesa_print_arrays (struct gl_context * ctx)
Print current vertex object/array info.
For debug.
References gl_array_object::_MaxElement, _mesa_update_array_object_max_element(), gl_context::Array, gl_array_attrib::ArrayObj, gl_context::Const, gl_client_array::Enabled, gl_constants::MaxTextureCoordUnits, gl_array_object::Name, print_array(), VERT_ATTRIB_COLOR0, VERT_ATTRIB_GENERIC, VERT_ATTRIB_GENERIC_MAX, VERT_ATTRIB_NORMAL, VERT_ATTRIB_POS, VERT_ATTRIB_TEX, and gl_array_object::VertexAttrib.
void GLAPIENTRY _mesa_SecondaryColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, update_array(), and VERT_ATTRIB_COLOR1.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_TexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, update_array(), and VERT_ATTRIB_TEX.
Referenced by _mesa_initialize_exec_table(), _mesa_InterleavedArrays(), and _mesa_TexCoordPointerEXT().
void GLAPIENTRY _mesa_TexCoordPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_TexCoordPointer(), and void().
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_UnlockArraysEXT (void)
References _mesa_debug(), _mesa_error(), _NEW_ARRAY, FLUSH_VERTICES, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_VertexAttribDivisor (GLuint index, GLuint divisor)
See GL_ARB_instanced_arrays.
Note that the instance divisor only applies to generic arrays, not the legacy vertex arrays.
References _mesa_error(), _NEW_ARRAY, ASSERT, Elements, FLUSH_VERTICES, gl_client_array::InstanceDivisor, and VERT_ATTRIB_GENERIC.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_VertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
GL_EXT_gpu_shader4 / GL 3.0.
Set an integer-valued vertex attribute array. Note that these arrays DO NOT alias the conventional GL vertex arrays (position, normal, color, fog, texcoord, etc).
References _mesa_error(), BYTE_BIT, GLbitfield, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, update_array(), and VERT_ATTRIB_GENERIC.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_VertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * ptr)
Set a generic vertex attribute array.
Note that these arrays DO NOT alias the conventional GL vertex arrays (position, normal, color, fog, texcoord, etc).
References _mesa_error(), BGRA_OR_4, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FIXED_GL_BIT, FLOAT_BIT, GLbitfield, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, UNSIGNED_SHORT_BIT, update_array(), and VERT_ATTRIB_GENERIC.
Referenced by _mesa_initialize_exec_table().
void GLAPIENTRY _mesa_VertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
References API_OPENGLES, BYTE_BIT, DOUBLE_BIT, FIXED_ES_BIT, FLOAT_BIT, FLUSH_VERTICES, GLbitfield, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, update_array(), and VERT_ATTRIB_POS.
Referenced by _mesa_initialize_exec_table(), _mesa_InterleavedArrays(), and _mesa_VertexPointerEXT().
void GLAPIENTRY _mesa_VertexPointerEXT (GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid * ptr)
References _mesa_VertexPointer(), and void().
Referenced by _mesa_initialize_exec_table().
static void delete_arrayobj_cb (GLuint id, void * data, void * userData) static
Callback for deleting an array object.
Called by _mesa_HashDeleteAll().
References _mesa_delete_array_object().
Referenced by _mesa_free_varray_data().
static const GLfloat* get_current_attrib (struct gl_context * ctx, GLuint index, const char * function) static
References _mesa_error(), gl_context::API, API_OPENGL_CORE, API_OPENGLES2, gl_context::Array, gl_array_attrib::ArrayObj, ASSERT, gl_current_attrib::Attrib, gl_context::Const, gl_context::Current, Elements, FLUSH_CURRENT, gl_program_constants::MaxAttribs, NULL, gl_context::Version, VERT_ATTRIB_GENERIC, gl_array_object::VertexAttrib, and gl_constants::VertexProgram.
Referenced by _mesa_GetVertexAttribdv(), _mesa_GetVertexAttribfv(), _mesa_GetVertexAttribIiv(), _mesa_GetVertexAttribIuiv(), and _mesa_GetVertexAttribiv().
static GLuint get_vertex_array_attrib (struct gl_context * ctx, GLuint index, GLenum pname, const char * caller) static
Return info for a vertex attribute array (no alias with legacy vertex attributes (pos, normal, color, etc)).
This function does not handle the 4-element GL_CURRENT_VERTEX_ATTRIB_ARB query.
References _mesa_error(), _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_extensions::ARB_instanced_arrays, gl_context::Array, gl_array_attrib::ArrayObj, ASSERT, gl_client_array::BufferObj, gl_context::Const, Elements, gl_client_array::Enabled, gl_extensions::EXT_gpu_shader4, gl_context::Extensions, gl_client_array::InstanceDivisor, gl_client_array::Integer, gl_program_constants::MaxAttribs, gl_buffer_object::Name, gl_client_array::Normalized, gl_client_array::Size, gl_client_array::Stride, gl_client_array::Type, gl_context::Version, VERT_ATTRIB_GENERIC, gl_array_object::VertexAttrib, and gl_constants::VertexProgram.
Referenced by _mesa_GetVertexAttribdv(), _mesa_GetVertexAttribfv(), _mesa_GetVertexAttribIiv(), _mesa_GetVertexAttribIuiv(), and _mesa_GetVertexAttribiv().
static void print_array (const char * name, GLint index, const struct gl_client_array * array) static
Print vertex array's fields.
References gl_client_array::_ElementSize, gl_client_array::_MaxElement, gl_client_array::BufferObj, gl_buffer_object::Name, gl_client_array::Ptr, gl_buffer_object::Size, gl_client_array::Size, gl_client_array::StrideB, and gl_client_array::Type.
Referenced by _mesa_print_arrays().
static GLbitfield type_to_bit (const struct gl_context * ctx, GLenum type) static
Convert GL datatype enum into a <type>_BIT value seen above.
References _mesa_is_desktop_gl(), gl_extensions::ARB_half_float_vertex, BOOL_BIT, BYTE_BIT, DOUBLE_BIT, gl_context::Extensions, FIXED_ES_BIT, FIXED_GL_BIT, FLOAT_BIT, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, SHORT_BIT, UNSIGNED_BYTE_BIT, UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, and UNSIGNED_SHORT_BIT.
Referenced by update_array().
static void update_array (struct gl_context * ctx, const char * func, GLuint attrib, GLbitfield legalTypesMask, GLint sizeMin, GLint sizeMax, GLint size, GLenum type, GLsizei stride, GLboolean normalized, GLboolean integer, const GLvoid * ptr) static
Do error checking and update state for glVertex/Color/TexCoord/...Pointer functions.
Parameters
func name of calling function used for error reporting
attrib the attribute array index to update
legalTypes bitmask of *_BIT above indicating legal datatypes
sizeMin min allowable size value
sizeMax max allowable size value (may also be BGRA_OR_4)
size components per element (1, 2, 3 or 4)
type datatype of each component (GL_FLOAT, GL_INT, etc)
stride stride between elements, in elements
normalized are integer types converted to floats in [-1, 1]?
integer integer-valued values (will not be normalized to [-1,1])
ptr the address (or offset inside VBO) of the array data
References gl_client_array::_ElementSize, _mesa_bytes_per_vertex_attrib(), _mesa_error(), _mesa_is_bufferobj(), _mesa_is_gles(), _mesa_lookup_enum_by_nr(), _mesa_reference_buffer_object(), _NEW_ARRAY, gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_ES2_compatibility, gl_extensions::ARB_vertex_type_2_10_10_10_rev, gl_array_object::ARBsemantics, gl_context::Array, gl_array_attrib::ArrayBufferObj, gl_array_attrib::ArrayObj, ASSERT, BGRA_OR_4, gl_client_array::BufferObj, gl_array_attrib::DefaultArrayObj, DOUBLE_BIT, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, FIXED_ES_BIT, FIXED_GL_BIT, gl_client_array::Format, GLbitfield, GLubyte, HALF_BIT, INT_2_10_10_10_REV_BIT, INT_BIT, gl_client_array::Integer, gl_context::NewState, gl_client_array::Normalized, NULL, gl_client_array::Ptr, size, gl_client_array::Size, gl_client_array::Stride, gl_client_array::StrideB, gl_client_array::Type, type_to_bit(), UNSIGNED_INT_2_10_10_10_REV_BIT, UNSIGNED_INT_BIT, gl_context::Version, and gl_array_object::VertexAttrib.
Referenced by _mesa_ColorPointer(), _mesa_EdgeFlagPointer(), _mesa_FogCoordPointer(), _mesa_IndexPointer(), _mesa_NormalPointer(), _mesa_PointSizePointerOES(), _mesa_SecondaryColorPointer(), _mesa_TexCoordPointer(), _mesa_VertexAttribIPointer(), _mesa_VertexAttribPointer(), and _mesa_VertexPointer().