Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
version.c File Reference
#include "imports.h"
#include "mtypes.h"
#include "version.h"
#include "git_sha1.h"
Functions
static GLboolean check_for_ending (const char *string, const char *ending)
Scans 'string' to see if it ends with 'ending'.
static void get_gl_override (int *version, GLboolean *fwd_context)
Returns the gl override data.
static void create_version_string (struct gl_context *ctx, const char *prefix)
Builds the MESA version string.
void _mesa_override_gl_version (struct gl_context *ctx)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
int _mesa_get_gl_version_override (void)
Returns the gl override value.
void _mesa_override_glsl_version (struct gl_context *ctx)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
static void compute_version (struct gl_context *ctx)
Examine enabled GL extensions to determine GL version.
static void compute_version_es1 (struct gl_context *ctx)
static void compute_version_es2 (struct gl_context *ctx)
void _mesa_compute_version (struct gl_context *ctx)
Set the context's Version and VersionString fields.
Function Documentation
void _mesa_compute_version (struct gl_context * ctx)
Set the context's Version and VersionString fields.
This should only be called once as part of context initialization or to perform version check for GLX_ARB_create_context_profile.
References gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, compute_version(), compute_version_es1(), compute_version_es2(), gl_context::Const, gl_constants::GLSLVersion, and gl_context::Version.
int _mesa_get_gl_version_override (void)
Returns the gl override value.
version > 0 indicates there is an override requested
References get_gl_override().
void _mesa_override_gl_version (struct gl_context * ctx)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
Example uses of MESA_GL_VERSION_OVERRIDE:
2.1: select a compatibility (non-Core) profile with GL version 2.1 3.0: select a compatibility (non-Core) profile with GL version 3.0 3.0FC: select a Core+Forward Compatible profile with GL version 3.0 3.1: select a Core profile with GL version 3.1 3.1FC: select a Core+Forward Compatible profile with GL version 3.1
References gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, gl_context::Const, gl_constants::ContextFlags, create_version_string(), get_gl_override(), and gl_context::Version.
Referenced by _mesa_initialize_context().
void _mesa_override_glsl_version (struct gl_context * ctx)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
Valid values for MESA_GLSL_VERSION_OVERRIDE are integers, such as "130".
References gl_context::Const, and gl_constants::GLSLVersion.
Referenced by _mesa_init_constants().
static GLboolean check_for_ending (const char * string, const char * ending) static
Scans 'string' to see if it ends with 'ending'.
Referenced by get_gl_override().
static void compute_version (struct gl_context * ctx) static
Examine enabled GL extensions to determine GL version.
References gl_context::API, API_OPENGL_CORE, gl_extensions::ARB_blend_func_extended, gl_extensions::ARB_color_buffer_float, gl_extensions::ARB_depth_buffer_float, gl_extensions::ARB_depth_clamp, gl_extensions::ARB_depth_texture, gl_extensions::ARB_draw_elements_base_vertex, gl_extensions::ARB_draw_instanced, gl_extensions::ARB_explicit_attrib_location, gl_extensions::ARB_fragment_coord_conventions, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_framebuffer_object, gl_extensions::ARB_geometry_shader4, gl_extensions::ARB_half_float_pixel, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_instanced_arrays, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_occlusion_query, gl_extensions::ARB_occlusion_query2, gl_extensions::ARB_point_sprite, gl_extensions::ARB_seamless_cube_map, gl_extensions::ARB_shader_bit_encoding, gl_extensions::ARB_shader_objects, gl_extensions::ARB_shader_texture_lod, gl_extensions::ARB_shadow, gl_extensions::ARB_sync, gl_extensions::ARB_texture_border_clamp, gl_extensions::ARB_texture_buffer_object, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_crossbar, gl_extensions::ARB_texture_env_dot3, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_multisample, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_rg, gl_extensions::ARB_texture_rgb10_a2ui, gl_extensions::ARB_timer_query, gl_extensions::ARB_uniform_buffer_object, gl_extensions::ARB_vertex_shader, gl_extensions::ARB_vertex_type_2_10_10_10_rev, gl_extensions::ATI_separate_stencil, gl_context::Const, create_version_string(), gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_fog_coord, gl_extensions::EXT_framebuffer_sRGB, gl_extensions::EXT_packed_float, gl_extensions::EXT_pixel_buffer_object, gl_extensions::EXT_point_parameters, gl_extensions::EXT_provoking_vertex, gl_extensions::EXT_secondary_color, gl_extensions::EXT_shadow_funcs, gl_extensions::EXT_stencil_two_side, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_texture_sRGB, gl_extensions::EXT_texture_swizzle, gl_extensions::EXT_transform_feedback, gl_extensions::EXT_vertex_array_bgra, gl_context::Extensions, gl_constants::GLSLVersion, gl_constants::MaxSamples, gl_program_constants::MaxTextureImageUnits, gl_extensions::NV_conditional_render, gl_extensions::NV_primitive_restart, gl_extensions::NV_texture_rectangle, gl_context::Version, and gl_constants::VertexProgram.
Referenced by _mesa_compute_version().
static void compute_version_es1 (struct gl_context * ctx) static
References _mesa_problem(), gl_extensions::ARB_texture_env_combine, gl_extensions::ARB_texture_env_dot3, create_version_string(), gl_extensions::EXT_point_parameters, gl_context::Extensions, and gl_context::Version.
Referenced by _mesa_compute_version().
static void compute_version_es2 (struct gl_context * ctx) static
References _mesa_problem(), gl_extensions::ARB_draw_instanced, gl_extensions::ARB_fragment_shader, gl_extensions::ARB_half_float_vertex, gl_extensions::ARB_internalformat_query, gl_extensions::ARB_map_buffer_range, gl_extensions::ARB_shader_objects, gl_extensions::ARB_shader_texture_lod, gl_extensions::ARB_texture_compression_rgtc, gl_extensions::ARB_texture_cube_map, gl_extensions::ARB_texture_float, gl_extensions::ARB_texture_non_power_of_two, gl_extensions::ARB_texture_rg, gl_extensions::ARB_uniform_buffer_object, gl_extensions::ARB_vertex_shader, create_version_string(), gl_extensions::EXT_blend_color, gl_extensions::EXT_blend_equation_separate, gl_extensions::EXT_blend_func_separate, gl_extensions::EXT_blend_minmax, gl_extensions::EXT_draw_buffers2, gl_extensions::EXT_framebuffer_sRGB, gl_extensions::EXT_packed_float, gl_extensions::EXT_texture_array, gl_extensions::EXT_texture_shared_exponent, gl_extensions::EXT_texture_snorm, gl_extensions::EXT_transform_feedback, gl_context::Extensions, gl_extensions::NV_conditional_render, gl_extensions::NV_primitive_restart, gl_extensions::OES_depth_texture_cube_map, and gl_context::Version.
Referenced by _mesa_compute_version().
static void create_version_string (struct gl_context * ctx, const char * prefix) static
Builds the MESA version string.
References _mesa_snprintf(), gl_context::API, API_OPENGL_CORE, MESA_GIT_SHA1, gl_context::Version, and gl_context::VersionString.
Referenced by _mesa_override_gl_version(), compute_version(), compute_version_es1(), and compute_version_es2().
static void get_gl_override (int * version, GLboolean * fwd_context) static
Returns the gl override data.
version > 0 indicates there is an override requested fwd_context is only valid if version > 0
References check_for_ending().
Referenced by _mesa_get_gl_version_override(), and _mesa_override_gl_version().