Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
version.h File Reference
Functions
void _mesa_compute_version (struct gl_context *ctx)
Set the context's Version and VersionString fields.
void _mesa_override_gl_version (struct gl_context *ctx)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
void _mesa_override_glsl_version (struct gl_context *ctx)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
int _mesa_get_gl_version_override (void)
Returns the gl override value.
Function Documentation
void _mesa_compute_version (struct gl_context * ctx)
Set the context's Version and VersionString fields.
This should only be called once as part of context initialization or to perform version check for GLX_ARB_create_context_profile.
References gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, compute_version(), compute_version_es1(), compute_version_es2(), gl_context::Const, gl_constants::GLSLVersion, and gl_context::Version.
int _mesa_get_gl_version_override (void)
Returns the gl override value.
version > 0 indicates there is an override requested
References get_gl_override().
void _mesa_override_gl_version (struct gl_context * ctx)
Override the context's version and/or API type if the environment variable MESA_GL_VERSION_OVERRIDE is set.
Example uses of MESA_GL_VERSION_OVERRIDE:
2.1: select a compatibility (non-Core) profile with GL version 2.1 3.0: select a compatibility (non-Core) profile with GL version 3.0 3.0FC: select a Core+Forward Compatible profile with GL version 3.0 3.1: select a Core profile with GL version 3.1 3.1FC: select a Core+Forward Compatible profile with GL version 3.1
References gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, gl_context::Const, gl_constants::ContextFlags, create_version_string(), get_gl_override(), and gl_context::Version.
Referenced by _mesa_initialize_context().
void _mesa_override_glsl_version (struct gl_context * ctx)
Override the context's GLSL version if the environment variable MESA_GLSL_VERSION_OVERRIDE is set.
Valid values for MESA_GLSL_VERSION_OVERRIDE are integers, such as "130".
References gl_context::Const, and gl_constants::GLSLVersion.
Referenced by _mesa_init_constants().