Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
viewport.c File Reference
glViewport and glDepthRange functions.
#include "context.h"
#include "macros.h"
#include "mtypes.h"
#include "viewport.h"
Functions
void GLAPIENTRY _mesa_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set the viewport.
void _mesa_set_viewport (struct gl_context *ctx, GLint x, GLint y, GLsizei width, GLsizei height)
Set new viewport parameters and update derived state (the _WindowMap matrix).
void GLAPIENTRY _mesa_DepthRange (GLclampd nearval, GLclampd farval)
Called by glDepthRange.
void GLAPIENTRY _mesa_DepthRangef (GLclampf nearval, GLclampf farval)
void _mesa_init_viewport (struct gl_context *ctx)
Initialize the context viewport attribute group.
void _mesa_free_viewport_data (struct gl_context *ctx)
Free the context viewport attribute group data.
Detailed Description
glViewport and glDepthRange functions.
Function Documentation
void GLAPIENTRY _mesa_DepthRange (GLclampd nearval, GLclampd farval)
Called by glDepthRange.
Parameters
nearval specifies the Z buffer value which should correspond to the near clip plane
farval specifies the Z buffer value which should correspond to the far clip plane
References _math_matrix_viewport(), _mesa_debug(), _NEW_VIEWPORT, CLAMP, FLUSH_VERTICES, MESA_VERBOSE, and VERBOSE_API.
Referenced by _mesa_DepthRangef(), _mesa_initialize_exec_table(), and _mesa_PopAttrib().
void GLAPIENTRY _mesa_DepthRangef (GLclampf nearval, GLclampf farval)
References _mesa_DepthRange().
Referenced by _mesa_DepthRangex(), and _mesa_initialize_exec_table().
void _mesa_free_viewport_data (struct gl_context * ctx)
Free the context viewport attribute group data.
Parameters
ctx the GL context.
References _math_matrix_dtr(), gl_viewport_attrib::_WindowMap, and gl_context::Viewport.
Referenced by _mesa_free_context_data().
void _mesa_init_viewport (struct gl_context * ctx)
Initialize the context viewport attribute group.
Parameters
ctx the GL context.
References _math_matrix_ctr(), _math_matrix_viewport(), gl_viewport_attrib::_WindowMap, gl_viewport_attrib::Far, gl_viewport_attrib::Height, gl_viewport_attrib::Near, gl_context::Viewport, gl_viewport_attrib::Width, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
Referenced by init_attrib_groups().
void _mesa_set_viewport (struct gl_context * ctx, GLint x, GLint y, GLsizei width, GLsizei height)
Set new viewport parameters and update derived state (the _WindowMap matrix).
Usually called from _mesa_Viewport().
Parameters
ctx GL context.
x,y coordinates of the lower left corner of the viewport rectangle.
width width of the viewport rectangle.
height height of the viewport rectangle.
References gl_framebuffer::_DepthMaxF, _math_matrix_viewport(), _mesa_debug(), _mesa_error(), _NEW_VIEWPORT, gl_viewport_attrib::_WindowMap, gl_context::Const, gl_context::DrawBuffer, gl_context::Driver, gl_viewport_attrib::Far, gl_viewport_attrib::Height, gl_constants::MaxViewportHeight, gl_constants::MaxViewportWidth, MESA_VERBOSE, MIN2, gl_viewport_attrib::Near, gl_context::NewState, VERBOSE_API, dd_function_table::Viewport, gl_context::Viewport, gl_viewport_attrib::Width, gl_viewport_attrib::X, and gl_viewport_attrib::Y.
Referenced by _mesa_check_init_viewport(), and _mesa_Viewport().
void GLAPIENTRY _mesa_Viewport (GLint x, GLint y, GLsizei width, GLsizei height)
Set the viewport.
See Also
Called via glViewport() or display list execution.
Flushes the vertices and calls _mesa_set_viewport() with the given parameters.
References _mesa_set_viewport(), and FLUSH_VERTICES.
Referenced by _mesa_initialize_exec_table(), and _mesa_PopAttrib().