Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vtxfmt.c File Reference
#include "glheader.h"
#include "api_arrayelt.h"
#include "context.h"
#include "imports.h"
#include "mtypes.h"
#include "vtxfmt.h"
#include "eval.h"
#include "dlist.h"
#include "main/dispatch.h"
#include "vbo/vbo_context.h"
Functions
static void install_vtxfmt (struct gl_context *ctx, struct _glapi_table *tab, const GLvertexformat *vfmt)
Copy the functions found in the GLvertexformat object into the dispatch table.
void _mesa_install_exec_vtxfmt (struct gl_context *ctx, const GLvertexformat *vfmt)
Install per-vertex functions into the API dispatch table for execution.
void _mesa_install_save_vtxfmt (struct gl_context *ctx, const GLvertexformat *vfmt)
Install per-vertex functions into the API dispatch table for display list compilation.
void _mesa_initialize_vbo_vtxfmt (struct gl_context *ctx)
Install VBO vtxfmt functions.
Function Documentation
void _mesa_initialize_vbo_vtxfmt (struct gl_context * ctx)
Install VBO vtxfmt functions.
This function depends on ctx->Version.
References _mesa_install_exec_vtxfmt(), _mesa_install_save_vtxfmt(), gl_context::API, API_OPENGL_COMPAT, vbo_context::exec, gl_context::ListState, gl_dlist_state::ListVtxfmt, and vbo_exec_context::vtxfmt.
void _mesa_install_exec_vtxfmt (struct gl_context * ctx, const GLvertexformat * vfmt)
Install per-vertex functions into the API dispatch table for execution.
References gl_context::BeginEnd, gl_context::Exec, and install_vtxfmt().
Referenced by _mesa_initialize_vbo_vtxfmt().
void _mesa_install_save_vtxfmt (struct gl_context * ctx, const GLvertexformat * vfmt)
Install per-vertex functions into the API dispatch table for display list compilation.
References _mesa_is_desktop_gl(), install_vtxfmt(), and gl_context::Save.
Referenced by _mesa_initialize_vbo_vtxfmt().
static void install_vtxfmt (struct gl_context * ctx, struct _glapi_table * tab, const GLvertexformat * vfmt) static
Copy the functions found in the GLvertexformat object into the dispatch table.
References _mesa_install_arrayelt_vtxfmt(), _mesa_install_dlist_vtxfmt(), _mesa_install_eval_vtxfmt(), _mesa_is_desktop_gl(), _mesa_is_gles3(), gl_context::API, API_OPENGL_COMPAT, API_OPENGL_CORE, API_OPENGLES, API_OPENGLES2, SET_Begin(), SET_Color3f(), SET_Color3fv(), SET_Color4f(), SET_Color4fv(), SET_ColorP3ui(), SET_ColorP3uiv(), SET_ColorP4ui(), SET_ColorP4uiv(), SET_EdgeFlag(), SET_End(), SET_FogCoordfEXT(), SET_FogCoordfvEXT(), SET_Indexf(), SET_Indexfv(), SET_Materialfv(), SET_MultiTexCoord1fARB(), SET_MultiTexCoord1fvARB(), SET_MultiTexCoord2fARB(), SET_MultiTexCoord2fvARB(), SET_MultiTexCoord3fARB(), SET_MultiTexCoord3fvARB(), SET_MultiTexCoord4fARB(), SET_MultiTexCoord4fvARB(), SET_MultiTexCoordP1ui(), SET_MultiTexCoordP1uiv(), SET_MultiTexCoordP2ui(), SET_MultiTexCoordP2uiv(), SET_MultiTexCoordP3ui(), SET_MultiTexCoordP3uiv(), SET_MultiTexCoordP4ui(), SET_MultiTexCoordP4uiv(), SET_Normal3f(), SET_Normal3fv(), SET_NormalP3ui(), SET_NormalP3uiv(), SET_PrimitiveRestartNV(), SET_SecondaryColor3fEXT(), SET_SecondaryColor3fvEXT(), SET_SecondaryColorP3ui(), SET_SecondaryColorP3uiv(), SET_TexCoord1f(), SET_TexCoord1fv(), SET_TexCoord2f(), SET_TexCoord2fv(), SET_TexCoord3f(), SET_TexCoord3fv(), SET_TexCoord4f(), SET_TexCoord4fv(), SET_TexCoordP1ui(), SET_TexCoordP1uiv(), SET_TexCoordP2ui(), SET_TexCoordP2uiv(), SET_TexCoordP3ui(), SET_TexCoordP3uiv(), SET_TexCoordP4ui(), SET_TexCoordP4uiv(), SET_Vertex2f(), SET_Vertex2fv(), SET_Vertex3f(), SET_Vertex3fv(), SET_Vertex4f(), SET_Vertex4fv(), SET_VertexAttrib1fARB(), SET_VertexAttrib1fNV(), SET_VertexAttrib1fvARB(), SET_VertexAttrib1fvNV(), SET_VertexAttrib2fARB(), SET_VertexAttrib2fNV(), SET_VertexAttrib2fvARB(), SET_VertexAttrib2fvNV(), SET_VertexAttrib3fARB(), SET_VertexAttrib3fNV(), SET_VertexAttrib3fvARB(), SET_VertexAttrib3fvNV(), SET_VertexAttrib4fARB(), SET_VertexAttrib4fNV(), SET_VertexAttrib4fvARB(), SET_VertexAttrib4fvNV(), SET_VertexAttribI1iEXT(), SET_VertexAttribI1uiEXT(), SET_VertexAttribI2iEXT(), SET_VertexAttribI2ivEXT(), SET_VertexAttribI2uiEXT(), SET_VertexAttribI2uivEXT(), SET_VertexAttribI3iEXT(), SET_VertexAttribI3ivEXT(), SET_VertexAttribI3uiEXT(), SET_VertexAttribI3uivEXT(), SET_VertexAttribI4iEXT(), SET_VertexAttribI4ivEXT(), SET_VertexAttribI4uiEXT(), SET_VertexAttribI4uivEXT(), SET_VertexAttribP1ui(), SET_VertexAttribP1uiv(), SET_VertexAttribP2ui(), SET_VertexAttribP2uiv(), SET_VertexAttribP3ui(), SET_VertexAttribP3uiv(), SET_VertexAttribP4ui(), SET_VertexAttribP4uiv(), SET_VertexP2ui(), SET_VertexP2uiv(), SET_VertexP3ui(), SET_VertexP3uiv(), SET_VertexP4ui(), SET_VertexP4uiv(), and gl_context::Version.
Referenced by _mesa_install_exec_vtxfmt(), and _mesa_install_save_vtxfmt().