Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_to_hir.cpp File Reference
#include "main/core.h"
#include "glsl_symbol_table.h"
#include "glsl_parser_extras.h"
#include "ast.h"
#include "glsl_types.h"
#include "program/hash_table.h"
#include "ir.h"
Functions
static void detect_conflicting_assignments (struct _mesa_glsl_parse_state *state, exec_list *instructions)
void _mesa_ast_to_hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
bool apply_implicit_conversion (const glsl_type *to, ir_rvalue *&from, struct _mesa_glsl_parse_state *state)
If a conversion is available, convert one operand to a different type.
static struct glsl_type * arithmetic_result_type (ir_rvalue *&value_a, ir_rvalue *&value_b, bool multiply, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static struct glsl_type * unary_arithmetic_result_type (const struct glsl_type *type, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static struct glsl_type * bit_logic_result_type (const struct glsl_type *type_a, const struct glsl_type *type_b, ast_operators op, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
Return the result type of a bit-logic operation.
static struct glsl_type * modulus_result_type (const struct glsl_type *type_a, const struct glsl_type *type_b, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static struct glsl_type * relational_result_type (ir_rvalue *&value_a, ir_rvalue *&value_b, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
static struct glsl_type * shift_result_type (const struct glsl_type *type_a, const struct glsl_type *type_b, ast_operators op, struct _mesa_glsl_parse_state *state, YYLTYPE *loc)
Return the result type of a bit-shift operation.
ir_rvalue * validate_assignment (struct _mesa_glsl_parse_state *state, const glsl_type *lhs_type, ir_rvalue *rhs, bool is_initializer)
Validates that a value can be assigned to a location with a specified type.
static void mark_whole_array_access (ir_rvalue *access)
ir_rvalue * do_assignment (exec_list *instructions, struct _mesa_glsl_parse_state *state, const char *non_lvalue_description, ir_rvalue *lhs, ir_rvalue *rhs, bool is_initializer, YYLTYPE lhs_loc)
static ir_rvalue * get_lvalue_copy (exec_list *instructions, ir_rvalue *lvalue)
static ir_rvalue * do_comparison (void *mem_ctx, int operation, ir_rvalue *op0, ir_rvalue *op1)
ir_rvalue * get_scalar_boolean_operand (exec_list *instructions, struct _mesa_glsl_parse_state *state, ast_expression *parent_expr, int operand, const char *operand_name, bool *error_emitted)
void check_builtin_array_max_size (const char *name, unsigned size, YYLTYPE loc, struct _mesa_glsl_parse_state *state)
If name refers to a builtin array whose maximum allowed size is less than size, report an error and return true.
static ir_rvalue * constant_one_for_inc_dec (void *ctx, const glsl_type *type)
Create the constant 1, of a which is appropriate for incrementing and decrementing values of the given GLSL type.
static const glsl_type * process_array_type (YYLTYPE *loc, const glsl_type *base, ast_node *array_size, struct _mesa_glsl_parse_state *state)
static bool is_varying_var (ir_variable *var, _mesa_glsl_parser_targets target)
Determine whether a toplevel variable declaration declares a varying.
static void validate_matrix_layout_for_type (struct _mesa_glsl_parse_state *state, YYLTYPE *loc, const glsl_type *type)
Matrix layout qualifiers are only allowed on certain types.
static void apply_type_qualifier_to_variable (const struct ast_type_qualifier *qual, ir_variable *var, struct _mesa_glsl_parse_state *state, YYLTYPE *loc, bool ubo_qualifiers_valid, bool is_parameter)
ir_variable * get_variable_being_redeclared (ir_variable *var, ast_declaration *decl, struct _mesa_glsl_parse_state *state)
Get the variable that is being redeclared by this declaration.
ir_rvalue * process_initializer (ir_variable *var, ast_declaration *decl, ast_fully_specified_type *type, exec_list *initializer_instructions, struct _mesa_glsl_parse_state *state)
Generate the IR for an initializer in a variable declaration.
void emit_function (_mesa_glsl_parse_state *state, ir_function *f)
static bool is_valid_default_precision_type (const struct _mesa_glsl_parse_state *state, const char *type_name)
Determine if the given type is valid for establishing a default precision qualifier.
unsigned ast_process_structure_or_interface_block (exec_list *instructions, struct _mesa_glsl_parse_state *state, exec_list *declarations, YYLTYPE &loc, glsl_struct_field **fields_ret, bool is_interface, bool block_row_major)
Process a structure or interface block tree into an array of structure fields.
Function Documentation
void _mesa_ast_to_hir (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References _mesa_glsl_initialize_variables(), detect_conflicting_assignments(), detect_recursion_unlinked(), and foreach_list_typed.
Referenced by compile_shader(), and test_optpass().
bool apply_implicit_conversion (const glsl_type * to, ir_rvalue *& from, struct _mesa_glsl_parse_state * state)
If a conversion is available, convert one operand to a different type.
The from ir_rvalue is converted "in place".
Parameters
to Type that the operand it to be converted to
from Operand that is being converted
state GLSL compiler state
Returns
If a conversion is possible (or unnecessary), true is returned. Otherwise false is returned.
References GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_unop_b2f, ir_unop_i2f, ir_unop_u2f, and ir_rvalue::type.
Referenced by arithmetic_result_type(), ast_expression::hir(), ast_function_expression::hir(), relational_result_type(), and validate_assignment().
static void apply_type_qualifier_to_variable (const struct ast_type_qualifier * qual, ir_variable * var, struct _mesa_glsl_parse_state * state, YYLTYPE * loc, bool ubo_qualifiers_valid, bool is_parameter) static
References _mesa_glsl_error(), _mesa_glsl_shader_target_name(), _mesa_glsl_warning(), ir_variable::centroid, ir_variable::depth_layout, ir_variable::explicit_index, ir_variable::explicit_location, ast_type_qualifier::flags, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_STRUCT, GLSL_TYPE_UINT, ast_type_qualifier::index, ir_variable::index, ir_variable::interpolation, ir_variable::interpolation_string(), ir_variable::invariant, ir_depth_layout_any, ir_depth_layout_greater, ir_depth_layout_less, ir_depth_layout_none, ir_depth_layout_unchanged, ir_var_function_in, ir_var_function_inout, ir_var_function_out, ir_var_shader_in, ir_var_shader_out, ir_var_uniform, is_varying_var(), ast_type_qualifier::location, ir_variable::location, ir_variable::mode, ir_variable::name, ir_variable::origin_upper_left, ir_variable::pixel_center_integer, ast_type_qualifier::q, ir_variable::read_only, ir_variable::type, ir_variable::used, and validate_matrix_layout_for_type().
Referenced by ast_declarator_list::hir(), and ast_parameter_declarator::hir().
static struct glsl_type* arithmetic_result_type (ir_rvalue *& value_a, ir_rvalue *& value_b, bool multiply, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static read
References _mesa_glsl_error(), apply_implicit_conversion(), GLSL_TYPE_FLOAT, and ir_rvalue::type.
Referenced by ast_expression::hir().
unsigned ast_process_structure_or_interface_block (exec_list * instructions, struct _mesa_glsl_parse_state * state, exec_list * declarations, YYLTYPE & loc, glsl_struct_field ** fields_ret, bool is_interface, bool block_row_major)
Process a structure or interface block tree into an array of structure fields.
After parsing, where there are some syntax differnces, structures and interface blocks are almost identical. They are similar enough that the AST for each can be processed the same way into a set of glsl_struct_field to describe the members.
Returns
The number of fields processed. A pointer to the array structure fields is stored in *fields_ret.
References _mesa_glsl_error(), ast_type_qualifier::flags, foreach_list_const, foreach_list_typed, ast_type_qualifier::has_interpolation(), ast_type_qualifier::i, process_array_type(), ast_type_qualifier::q, ralloc_array, and validate_matrix_layout_for_type().
Referenced by ast_struct_specifier::hir(), and ast_interface_block::hir().
static struct glsl_type* bit_logic_result_type (const struct glsl_type * type_a, const struct glsl_type * type_b, ast_operators op, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static read
Return the result type of a bit-logic operation.
If the given types to the bit-logic operator are invalid, return glsl_type::error_type.
Parameters
type_a Type of LHS of bit-logic op
type_b Type of RHS of bit-logic op
References _mesa_glsl_error(), and ast_expression::operator_string().
Referenced by ast_expression::hir().
void check_builtin_array_max_size (const char * name, unsigned size, YYLTYPE loc, struct _mesa_glsl_parse_state * state)
If name refers to a builtin array whose maximum allowed size is less than size, report an error and return true.
Otherwise return false.
References _mesa_glsl_error().
Referenced by _mesa_ast_array_index_to_hir(), and get_variable_being_redeclared().
static ir_rvalue* constant_one_for_inc_dec (void * ctx, const glsl_type * type) static
Create the constant 1, of a which is appropriate for incrementing and decrementing values of the given GLSL type.
For example, if type is vec4, this creates a constant value of 1.0 having type float.
If the given type is invalid for increment and decrement operators, return a floating point 1–the error will be detected later.
References GLSL_TYPE_FLOAT, GLSL_TYPE_INT, and GLSL_TYPE_UINT.
Referenced by ast_expression::hir().
static void detect_conflicting_assignments (struct _mesa_glsl_parse_state * state, exec_list * instructions) static
References _mesa_glsl_error(), ir_variable::as_variable(), ir_variable::assigned, foreach_list, ir_var_shader_out, ir_variable::mode, and ir_variable::name.
Referenced by _mesa_ast_to_hir().
ir_rvalue* do_assignment (exec_list * instructions, struct _mesa_glsl_parse_state * state, const char * non_lvalue_description, ir_rvalue * lhs, ir_rvalue * rhs, bool is_initializer, YYLTYPE lhs_loc)
References _mesa_glsl_error(), ir_instruction::as_dereference(), ir_instruction::as_expression(), ir_variable::assigned, ir_rvalue::clone(), ir_builder::expr(), ir_binop_vector_extract, ir_triop_vector_insert, ir_instruction::ir_type, ir_type_expression, ir_var_temporary, ir_rvalue::is_lvalue(), mark_whole_array_access(), ir_variable::max_array_access, ir_variable::name, ir_expression::operands, ir_expression::operation, ir_variable::read_only, ir_rvalue::type, ir_variable::type, validate_assignment(), ir_rvalue::variable_referenced(), and ir_dereference::variable_referenced().
Referenced by ast_expression::hir(), and process_initializer().
static ir_rvalue* do_comparison (void * mem_ctx, int operation, ir_rvalue * op0, ir_rvalue * op1) static
References ir_rvalue::clone(), GLSL_TYPE_ARRAY, GLSL_TYPE_BOOL, GLSL_TYPE_ERROR, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_INTERFACE, GLSL_TYPE_SAMPLER, GLSL_TYPE_STRUCT, GLSL_TYPE_UINT, GLSL_TYPE_VOID, ir_binop_all_equal, ir_binop_logic_and, ir_binop_logic_or, mark_whole_array_access(), and ir_rvalue::type.
Referenced by ast_expression::hir().
void emit_function (_mesa_glsl_parse_state * state, ir_function * f)
Referenced by ast_function::hir(), and match_function_by_name().
static ir_rvalue* get_lvalue_copy (exec_list * instructions, ir_rvalue * lvalue) static
References ir_var_auto, ir_var_temporary, ir_variable::mode, ralloc_parent(), and ir_rvalue::type.
Referenced by ast_expression::hir().
ir_rvalue* get_scalar_boolean_operand (exec_list * instructions, struct _mesa_glsl_parse_state * state, ast_expression * parent_expr, int operand, const char * operand_name, bool * error_emitted)
References _mesa_glsl_error(), ir_builder::expr(), ast_node::get_location(), ast_expression::hir(), ast_expression::oper, ast_expression::operator_string(), ast_expression::subexpressions, and ir_rvalue::type.
Referenced by ast_expression::hir().
ir_variable* get_variable_being_redeclared (ir_variable * var, ast_declaration * decl, struct _mesa_glsl_parse_state * state)
Get the variable that is being redeclared by this declaration.
Semantic checks to verify the validity of the redeclaration are also performed. If semantic checks fail, compilation error will be emitted via _mesa_glsl_error, but a non-NULL pointer will still be returned.
Returns
A pointer to an existing variable in the current scope if the declaration is a redeclaration, NULL otherwise.
From the AMD_conservative_depth spec: Within any shader, the first redeclarations of gl_FragDepth must appear before any use of gl_FragDepth.
References _mesa_glsl_error(), check_builtin_array_max_size(), ir_variable::depth_layout, depth_layout_string(), ast_node::get_location(), ast_declaration::identifier, ir_variable::interpolation, ir_depth_layout_none, ir_variable::max_array_access, ir_variable::mode, ir_variable::name, ir_variable::origin_upper_left, ir_variable::pixel_center_integer, ir_variable::type, and ir_variable::used.
Referenced by ast_declarator_list::hir().
static bool is_valid_default_precision_type (const struct _mesa_glsl_parse_state * state, const char * type_name) static
Determine if the given type is valid for establishing a default precision qualifier.
From GLSL ES 3.00 section 4.5.4 ("Default Precision Qualifiers"):
"The precision statement
    precision precision-qualifier type;
can be used to establish a default precision qualifier. The type field
can be either int or float or any of the sampler types, and the
precision-qualifier can be lowp, mediump, or highp."
GLSL ES 1.00 has similar language. GLSL 1.30 doesn't allow precision qualifiers on sampler types, but this seems like an oversight (since the intention of including these in GLSL 1.30 is to allow compatibility with ES shaders). So we allow int, float, and all sampler types regardless of GLSL version.
References GLSL_TYPE_FLOAT, GLSL_TYPE_INT, and GLSL_TYPE_SAMPLER.
Referenced by ast_type_specifier::hir().
static bool is_varying_var (ir_variable * var, _mesa_glsl_parser_targets target) static
Determine whether a toplevel variable declaration declares a varying.
This function operates by examining the variable's mode and the shader target, so it correctly identifies linkage variables regardless of whether they are declared using the deprecated "varying" syntax or the new "in/out" syntax.
Passing a non-toplevel variable declaration (e.g. a function parameter) to this function will produce undefined results.
References ir_var_shader_in, ir_var_shader_out, and ir_variable::mode.
Referenced by apply_type_qualifier_to_variable().
static void mark_whole_array_access (ir_rvalue * access) static
References ir_instruction::as_dereference_variable(), ir_variable::max_array_access, ir_rvalue::type, and ir_dereference_variable::var.
Referenced by do_assignment(), and do_comparison().
static struct glsl_type* modulus_result_type (const struct glsl_type * type_a, const struct glsl_type * type_b, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static read
References _mesa_glsl_error().
Referenced by ast_expression::hir().
static const glsl_type* process_array_type (YYLTYPE * loc, const glsl_type * base, ast_node * array_size, struct _mesa_glsl_parse_state * state) static
References _mesa_glsl_error(), ir_rvalue::constant_expression_value(), ast_node::get_location(), ast_node::hir(), ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and ir_constant::value.
Referenced by ast_process_structure_or_interface_block(), ast_type_specifier::glsl_type(), ast_declarator_list::hir(), ast_parameter_declarator::hir(), and ast_interface_block::hir().
ir_rvalue* process_initializer (ir_variable * var, ast_declaration * decl, ast_fully_specified_type * type, exec_list * initializer_instructions, struct _mesa_glsl_parse_state * state)
Generate the IR for an initializer in a variable declaration.
References _mesa_glsl_error(), _mesa_glsl_shader_target_name(), ir_rvalue::constant_expression_value(), ir_variable::constant_initializer, ir_variable::constant_value, do_assignment(), ast_type_qualifier::flags, ast_node::get_location(), ir_variable::has_initializer, ast_expression::hir(), ast_declaration::identifier, ast_declaration::initializer, ir_var_shader_in, ir_var_uniform, ir_variable::mode, ast_type_qualifier::q, ast_fully_specified_type::qualifier, ir_variable::read_only, ir_rvalue::type, ir_variable::type, validate_assignment(), and ir_constant::zero().
Referenced by ast_declarator_list::hir().
static struct glsl_type* relational_result_type (ir_rvalue *& value_a, ir_rvalue *& value_b, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static read
References _mesa_glsl_error(), apply_implicit_conversion(), and ir_rvalue::type.
Referenced by ast_expression::hir().
static struct glsl_type* shift_result_type (const struct glsl_type * type_a, const struct glsl_type * type_b, ast_operators op, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static read
Return the result type of a bit-shift operation.
If the given types to the bit-shift operator are invalid, return glsl_type::error_type.
Parameters
type_a Type of LHS of bit-shift op
type_b Type of RHS of bit-shift op
References _mesa_glsl_error(), and ast_expression::operator_string().
Referenced by ast_expression::hir().
static struct glsl_type* unary_arithmetic_result_type (const struct glsl_type * type, struct _mesa_glsl_parse_state * state, YYLTYPE * loc) static read
References _mesa_glsl_error().
Referenced by ast_expression::hir().
ir_rvalue* validate_assignment (struct _mesa_glsl_parse_state * state, const glsl_type * lhs_type, ir_rvalue * rhs, bool is_initializer)
Validates that a value can be assigned to a location with a specified type.
Validates that rhs can be assigned to some location. If the types are not an exact match but an automatic conversion is possible, rhs will be converted.
Returns
NULL if rhs cannot be assigned to a location with type lhs_type. Otherwise the actual RHS to be assigned will be returned. This may be rhs, or it may be rhs after some type conversion.
Note
In addition to being used for assignments, this function is used to type-check return values.
References apply_implicit_conversion(), and ir_rvalue::type.
Referenced by do_assignment(), and process_initializer().
static void validate_matrix_layout_for_type (struct _mesa_glsl_parse_state * state, YYLTYPE * loc, const glsl_type * type) static
Matrix layout qualifiers are only allowed on certain types.
References _mesa_glsl_error(), and _mesa_glsl_warning().
Referenced by apply_type_qualifier_to_variable(), and ast_process_structure_or_interface_block().