Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
builtin_variables.cpp File Reference
#include "ir.h"
#include "glsl_parser_extras.h"
#include "glsl_symbol_table.h"
#include "main/core.h"
#include "main/uniforms.h"
#include "program/prog_parameter.h"
#include "program/prog_statevars.h"
#include "program/prog_instruction.h"
Data Structures
struct builtin_variable
Macros
#define MATRIX(name, statevar, modifier)
#define STATEVAR(name) {#name, name ## _elements, Elements(name ## _elements)}
Functions
static void generate_ARB_draw_buffers_variables (exec_list *, struct _mesa_glsl_parse_state *, bool, _mesa_glsl_parser_targets)
static void generate_ARB_draw_instanced_variables (exec_list *, struct _mesa_glsl_parse_state *, bool, _mesa_glsl_parser_targets)
static void generate_AMD_vertex_shader_layer_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool warn, _mesa_glsl_parser_targets target)
MATRIX (gl_ModelViewMatrix, STATE_MODELVIEW_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ModelViewMatrixInverse, STATE_MODELVIEW_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_ModelViewMatrixTranspose, STATE_MODELVIEW_MATRIX, 0)
MATRIX (gl_ModelViewMatrixInverseTranspose, STATE_MODELVIEW_MATRIX, STATE_MATRIX_INVERSE)
MATRIX (gl_ProjectionMatrix, STATE_PROJECTION_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ProjectionMatrixInverse, STATE_PROJECTION_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_ProjectionMatrixTranspose, STATE_PROJECTION_MATRIX, 0)
MATRIX (gl_ProjectionMatrixInverseTranspose, STATE_PROJECTION_MATRIX, STATE_MATRIX_INVERSE)
MATRIX (gl_ModelViewProjectionMatrix, STATE_MVP_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ModelViewProjectionMatrixInverse, STATE_MVP_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_ModelViewProjectionMatrixTranspose, STATE_MVP_MATRIX, 0)
MATRIX (gl_ModelViewProjectionMatrixInverseTranspose, STATE_MVP_MATRIX, STATE_MATRIX_INVERSE)
MATRIX (gl_TextureMatrix, STATE_TEXTURE_MATRIX, STATE_MATRIX_TRANSPOSE)
MATRIX (gl_TextureMatrixInverse, STATE_TEXTURE_MATRIX, STATE_MATRIX_INVTRANS)
MATRIX (gl_TextureMatrixTranspose, STATE_TEXTURE_MATRIX, 0)
MATRIX (gl_TextureMatrixInverseTranspose, STATE_TEXTURE_MATRIX, STATE_MATRIX_INVERSE)
static ir_variable * add_variable (exec_list *instructions, glsl_symbol_table *symtab, const char *name, const glsl_type *type, enum ir_variable_mode mode, int slot)
static ir_variable * add_uniform (exec_list *instructions, glsl_symbol_table *symtab, const char *name, const glsl_type *type)
static void add_builtin_variable (exec_list *instructions, glsl_symbol_table *symtab, const builtin_variable *proto)
static ir_variable * add_builtin_constant (exec_list *instructions, glsl_symbol_table *symtab, const char *name, int value)
static void generate_common_ES_uniforms (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Uniforms that are common to all GLSL ES implementations.
static void generate_100ES_uniforms (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_300ES_uniforms (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_110_uniforms (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool add_deprecated)
static void generate_100ES_vs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_300ES_vs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_110_vs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool add_deprecated)
static void generate_120_vs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool add_deprecated)
static void generate_130_uniforms (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_130_vs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool add_deprecated)
static void initialize_vs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_100ES_fs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_300ES_fs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_110_fs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool add_deprecated)
static void generate_ARB_shader_stencil_export_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool warn)
static void generate_AMD_shader_stencil_export_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool warn)
static void generate_120_fs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state, bool add_deprecated)
static void generate_fs_clipdistance (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_130_fs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void generate_140_fs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
static void initialize_fs_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
void _mesa_glsl_initialize_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Variables
static const builtin_variable builtin_core_vs_variables []
static const builtin_variable builtin_core_fs_variables []
static const builtin_variable builtin_100ES_fs_variables []
static const builtin_variable builtin_300ES_vs_variables []
static const builtin_variable builtin_300ES_fs_variables []
static const builtin_variable builtin_110_fs_variables []
static const builtin_variable builtin_110_deprecated_fs_variables []
static const builtin_variable builtin_110_deprecated_vs_variables []
static const builtin_variable builtin_120_fs_variables []
static const builtin_variable builtin_130_vs_variables []
static const builtin_variable builtin_110_deprecated_uniforms []
static struct
gl_builtin_uniform_element gl_DepthRange_elements []
static struct
gl_builtin_uniform_element gl_ClipPlane_elements []
static struct
gl_builtin_uniform_element gl_Point_elements []
static struct
gl_builtin_uniform_element gl_FrontMaterial_elements []
static struct
gl_builtin_uniform_element gl_BackMaterial_elements []
static struct
gl_builtin_uniform_element gl_LightSource_elements []
static struct
gl_builtin_uniform_element gl_LightModel_elements []
static struct
gl_builtin_uniform_element gl_FrontLightModelProduct_elements []
static struct
gl_builtin_uniform_element gl_BackLightModelProduct_elements []
static struct
gl_builtin_uniform_element gl_FrontLightProduct_elements []
static struct
gl_builtin_uniform_element gl_BackLightProduct_elements []
static struct
gl_builtin_uniform_element gl_TextureEnvColor_elements []
static struct
gl_builtin_uniform_element gl_EyePlaneS_elements []
static struct
gl_builtin_uniform_element gl_EyePlaneT_elements []
static struct
gl_builtin_uniform_element gl_EyePlaneR_elements []
static struct
gl_builtin_uniform_element gl_EyePlaneQ_elements []
static struct
gl_builtin_uniform_element gl_ObjectPlaneS_elements []
static struct
gl_builtin_uniform_element gl_ObjectPlaneT_elements []
static struct
gl_builtin_uniform_element gl_ObjectPlaneR_elements []
static struct
gl_builtin_uniform_element gl_ObjectPlaneQ_elements []
static struct
gl_builtin_uniform_element gl_Fog_elements []
static struct
gl_builtin_uniform_element gl_NormalScale_elements []
static struct
gl_builtin_uniform_element gl_BumpRotMatrix0MESA_elements []
static struct
gl_builtin_uniform_element gl_BumpRotMatrix1MESA_elements []
static struct
gl_builtin_uniform_element gl_FogParamsOptimizedMESA_elements []
static struct
gl_builtin_uniform_element gl_CurrentAttribVertMESA_elements []
static struct
gl_builtin_uniform_element gl_CurrentAttribFragMESA_elements []
static struct
gl_builtin_uniform_element gl_NormalMatrix_elements []
static struct
gl_builtin_uniform_desc _mesa_builtin_uniform_desc []
Macro Definition Documentation
#define MATRIX (name, statevar, modifier)
Value:
static struct gl_builtin_uniform_element name ## _elements[] = {        \
      { NULL, { statevar, 0, 0, 0, modifier}, SWIZZLE_XYZW },           \
      { NULL, { statevar, 0, 1, 1, modifier}, SWIZZLE_XYZW },           \
      { NULL, { statevar, 0, 2, 2, modifier}, SWIZZLE_XYZW },           \
      { NULL, { statevar, 0, 3, 3, modifier}, SWIZZLE_XYZW },           \
   }
#define STATEVAR (name) {#name, name ## _elements, Elements(name ## _elements)}
Function Documentation
void _mesa_glsl_initialize_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References initialize_fs_variables(), and initialize_vs_variables().
Referenced by _mesa_ast_to_hir().
static ir_variable* add_builtin_constant (exec_list * instructions, glsl_symbol_table * symtab, const char * name, int value) static
References add_variable(), ir_variable::constant_initializer, ir_variable::constant_value, ir_variable::has_initializer, and ir_var_auto.
Referenced by generate_100ES_uniforms(), generate_110_uniforms(), generate_130_uniforms(), generate_300ES_uniforms(), generate_ARB_draw_buffers_variables(), and generate_common_ES_uniforms().
static void add_builtin_variable (exec_list * instructions, glsl_symbol_table * symtab, const builtin_variable * proto) static
References add_uniform(), add_variable(), glsl_symbol_table::get_type(), ir_var_uniform, builtin_variable::mode, builtin_variable::name, builtin_variable::slot, and builtin_variable::type.
Referenced by generate_100ES_fs_variables(), generate_100ES_vs_variables(), generate_110_fs_variables(), generate_110_uniforms(), generate_110_vs_variables(), generate_120_fs_variables(), generate_130_vs_variables(), generate_300ES_fs_variables(), and generate_300ES_vs_variables().
static ir_variable* add_uniform (exec_list * instructions, glsl_symbol_table * symtab, const char * name, const glsl_type * type) static
References _mesa_builtin_uniform_desc, add_variable(), ir_var_uniform, ir_variable::num_state_slots, ralloc_array, ir_variable::state_slots, ir_state_slot::swizzle, and ir_state_slot::tokens.
Referenced by add_builtin_variable(), generate_110_uniforms(), and generate_common_ES_uniforms().
static ir_variable* add_variable (exec_list * instructions, glsl_symbol_table * symtab, const char * name, const glsl_type * type, enum ir_variable_mode mode, int slot) static
References glsl_symbol_table::add_variable(), ir_variable::explicit_index, ir_variable::explicit_location, ir_var_auto, ir_var_shader_in, ir_var_shader_out, ir_var_system_value, ir_var_uniform, ir_variable::location, ir_variable::mode, and ir_variable::read_only.
Referenced by add_builtin_constant(), add_builtin_variable(), add_uniform(), generate_110_fs_variables(), generate_110_vs_variables(), generate_130_vs_variables(), generate_AMD_shader_stencil_export_variables(), generate_AMD_vertex_shader_layer_variables(), generate_ARB_draw_buffers_variables(), generate_ARB_draw_instanced_variables(), generate_ARB_shader_stencil_export_variables(), and generate_fs_clipdistance().
static void generate_100ES_fs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_builtin_variable(), generate_100ES_uniforms(), and generate_ARB_draw_buffers_variables().
Referenced by initialize_fs_variables().
static void generate_100ES_uniforms (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_builtin_constant(), and generate_common_ES_uniforms().
Referenced by generate_100ES_fs_variables(), and generate_100ES_vs_variables().
static void generate_100ES_vs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_builtin_variable(), generate_100ES_uniforms(), and generate_ARB_draw_buffers_variables().
Referenced by initialize_vs_variables().
static void generate_110_fs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool add_deprecated) static
References add_builtin_variable(), add_variable(), generate_110_uniforms(), generate_ARB_draw_buffers_variables(), and ir_var_shader_in.
Referenced by generate_120_fs_variables(), and initialize_fs_variables().
static void generate_110_uniforms (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool add_deprecated) static
References add_builtin_constant(), add_builtin_variable(), add_uniform(), and glsl_symbol_table::get_type().
Referenced by generate_110_fs_variables(), and generate_110_vs_variables().
static void generate_110_vs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool add_deprecated) static
References add_builtin_variable(), add_variable(), generate_110_uniforms(), generate_ARB_draw_buffers_variables(), and ir_var_shader_out.
Referenced by generate_120_vs_variables(), and initialize_vs_variables().
static void generate_120_fs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool add_deprecated) static
References add_builtin_variable(), and generate_110_fs_variables().
Referenced by generate_130_fs_variables(), generate_140_fs_variables(), and initialize_fs_variables().
static void generate_120_vs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool add_deprecated) static
References generate_110_vs_variables().
Referenced by generate_130_vs_variables(), and initialize_vs_variables().
static void generate_130_fs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References generate_120_fs_variables(), generate_130_uniforms(), and generate_fs_clipdistance().
Referenced by initialize_fs_variables().
static void generate_130_uniforms (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_builtin_constant().
Referenced by generate_130_fs_variables(), generate_130_vs_variables(), and generate_140_fs_variables().
static void generate_130_vs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool add_deprecated) static
References add_builtin_variable(), add_variable(), generate_120_vs_variables(), generate_130_uniforms(), generate_AMD_vertex_shader_layer_variables(), and ir_var_shader_out.
Referenced by initialize_vs_variables().
static void generate_140_fs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References generate_120_fs_variables(), generate_130_uniforms(), and generate_fs_clipdistance().
Referenced by initialize_fs_variables().
static void generate_300ES_fs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_builtin_variable(), generate_300ES_uniforms(), and generate_ARB_draw_buffers_variables().
Referenced by initialize_fs_variables().
static void generate_300ES_uniforms (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_builtin_constant(), and generate_common_ES_uniforms().
Referenced by generate_300ES_fs_variables(), and generate_300ES_vs_variables().
static void generate_300ES_vs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_builtin_variable(), generate_300ES_uniforms(), and generate_ARB_draw_buffers_variables().
Referenced by initialize_vs_variables().
static void generate_AMD_shader_stencil_export_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool warn) static
References add_variable(), ir_var_shader_out, and ir_variable::warn_extension.
Referenced by initialize_fs_variables().
static void generate_AMD_vertex_shader_layer_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool warn, _mesa_glsl_parser_targets target) static
References add_variable(), ir_var_shader_out, and ir_variable::warn_extension.
Referenced by generate_130_vs_variables().
static void generate_ARB_draw_buffers_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool warn, _mesa_glsl_parser_targets target) static
References add_builtin_constant(), add_variable(), ir_var_shader_out, and ir_variable::warn_extension.
Referenced by generate_100ES_fs_variables(), generate_100ES_vs_variables(), generate_110_fs_variables(), generate_110_vs_variables(), generate_300ES_fs_variables(), and generate_300ES_vs_variables().
static void generate_ARB_draw_instanced_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool warn, _mesa_glsl_parser_targets target) static
References add_variable(), ir_var_system_value, and ir_variable::warn_extension.
Referenced by initialize_vs_variables().
static void generate_ARB_shader_stencil_export_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state, bool warn) static
References add_variable(), ir_var_shader_out, and ir_variable::warn_extension.
Referenced by initialize_fs_variables().
static void generate_common_ES_uniforms (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
Uniforms that are common to all GLSL ES implementations.
Several constants in GLSL ES have different names than normal desktop GLSL. Therefore, this function should only be called on the ES path.
References add_builtin_constant(), add_uniform(), and glsl_symbol_table::get_type().
Referenced by generate_100ES_uniforms(), and generate_300ES_uniforms().
static void generate_fs_clipdistance (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References add_variable(), and ir_var_shader_in.
Referenced by generate_130_fs_variables(), and generate_140_fs_variables().
static void initialize_fs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References generate_100ES_fs_variables(), generate_110_fs_variables(), generate_120_fs_variables(), generate_130_fs_variables(), generate_140_fs_variables(), generate_300ES_fs_variables(), generate_AMD_shader_stencil_export_variables(), and generate_ARB_shader_stencil_export_variables().
Referenced by _mesa_glsl_initialize_variables().
static void initialize_vs_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state) static
References generate_100ES_vs_variables(), generate_110_vs_variables(), generate_120_vs_variables(), generate_130_vs_variables(), generate_300ES_vs_variables(), and generate_ARB_draw_instanced_variables().
Referenced by _mesa_glsl_initialize_variables().
MATRIX (gl_ModelViewMatrix , STATE_MODELVIEW_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ModelViewMatrixInverse , STATE_MODELVIEW_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX (gl_ModelViewMatrixTranspose , STATE_MODELVIEW_MATRIX , 0)
MATRIX (gl_ModelViewMatrixInverseTranspose , STATE_MODELVIEW_MATRIX , STATE_MATRIX_INVERSE)
MATRIX (gl_ProjectionMatrix , STATE_PROJECTION_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ProjectionMatrixInverse , STATE_PROJECTION_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX (gl_ProjectionMatrixTranspose , STATE_PROJECTION_MATRIX , 0)
MATRIX (gl_ProjectionMatrixInverseTranspose , STATE_PROJECTION_MATRIX , STATE_MATRIX_INVERSE)
MATRIX (gl_ModelViewProjectionMatrix , STATE_MVP_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX (gl_ModelViewProjectionMatrixInverse , STATE_MVP_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX (gl_ModelViewProjectionMatrixTranspose , STATE_MVP_MATRIX , 0)
MATRIX (gl_ModelViewProjectionMatrixInverseTranspose , STATE_MVP_MATRIX , STATE_MATRIX_INVERSE)
MATRIX (gl_TextureMatrix , STATE_TEXTURE_MATRIX , STATE_MATRIX_TRANSPOSE)
MATRIX (gl_TextureMatrixInverse , STATE_TEXTURE_MATRIX , STATE_MATRIX_INVTRANS)
MATRIX (gl_TextureMatrixTranspose , STATE_TEXTURE_MATRIX , 0)
MATRIX (gl_TextureMatrixInverseTranspose , STATE_TEXTURE_MATRIX , STATE_MATRIX_INVERSE)
Variable Documentation
struct gl_builtin_uniform_desc _mesa_builtin_uniform_desc[] static
Referenced by add_uniform().
const builtin_variable builtin_100ES_fs_variables[] static
Initial value:
= {
   { ir_var_shader_in,  VARYING_SLOT_PNTC,   "vec2",   "gl_PointCoord" },
}
const builtin_variable builtin_110_deprecated_fs_variables[] static
Initial value:
= {
   { ir_var_shader_in,  VARYING_SLOT_COL0,  "vec4",  "gl_Color" },
   { ir_var_shader_in,  VARYING_SLOT_COL1,  "vec4",  "gl_SecondaryColor" },
   { ir_var_shader_in,  VARYING_SLOT_FOGC,  "float", "gl_FogFragCoord" },
}
const builtin_variable builtin_110_deprecated_uniforms[] static
Initial value:
= {
   { ir_var_uniform, -1, "mat4", "gl_ModelViewMatrix" },
   { ir_var_uniform, -1, "mat4", "gl_ProjectionMatrix" },
   { ir_var_uniform, -1, "mat4", "gl_ModelViewProjectionMatrix" },
   { ir_var_uniform, -1, "mat3", "gl_NormalMatrix" },
   { ir_var_uniform, -1, "mat4", "gl_ModelViewMatrixInverse" },
   { ir_var_uniform, -1, "mat4", "gl_ProjectionMatrixInverse" },
   { ir_var_uniform, -1, "mat4", "gl_ModelViewProjectionMatrixInverse" },
   { ir_var_uniform, -1, "mat4", "gl_ModelViewMatrixTranspose" },
   { ir_var_uniform, -1, "mat4", "gl_ProjectionMatrixTranspose" },
   { ir_var_uniform, -1, "mat4", "gl_ModelViewProjectionMatrixTranspose" },
   { ir_var_uniform, -1, "mat4", "gl_ModelViewMatrixInverseTranspose" },
   { ir_var_uniform, -1, "mat4", "gl_ProjectionMatrixInverseTranspose" },
   { ir_var_uniform, -1, "mat4", "gl_ModelViewProjectionMatrixInverseTranspose" },
   { ir_var_uniform, -1, "float", "gl_NormalScale" },
   { ir_var_uniform, -1, "gl_LightModelParameters", "gl_LightModel"},
   { ir_var_uniform, -1, "vec2", "gl_BumpRotMatrix0MESA"},
   { ir_var_uniform, -1, "vec2", "gl_BumpRotMatrix1MESA"},
   { ir_var_uniform, -1, "vec4", "gl_FogParamsOptimizedMESA"},
}
const builtin_variable builtin_110_deprecated_vs_variables[] static
Initial value:
= {
   { ir_var_shader_in,  VERT_ATTRIB_POS,         "vec4",  "gl_Vertex" },
   { ir_var_shader_in,  VERT_ATTRIB_NORMAL,      "vec3",  "gl_Normal" },
   { ir_var_shader_in,  VERT_ATTRIB_COLOR0,      "vec4",  "gl_Color" },
   { ir_var_shader_in,  VERT_ATTRIB_COLOR1,      "vec4",  "gl_SecondaryColor" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX0,        "vec4",  "gl_MultiTexCoord0" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX1,        "vec4",  "gl_MultiTexCoord1" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX2,        "vec4",  "gl_MultiTexCoord2" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX3,        "vec4",  "gl_MultiTexCoord3" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX4,        "vec4",  "gl_MultiTexCoord4" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX5,        "vec4",  "gl_MultiTexCoord5" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX6,        "vec4",  "gl_MultiTexCoord6" },
   { ir_var_shader_in,  VERT_ATTRIB_TEX7,        "vec4",  "gl_MultiTexCoord7" },
   { ir_var_shader_in,  VERT_ATTRIB_FOG,         "float", "gl_FogCoord" },
   { ir_var_shader_out, VARYING_SLOT_CLIP_VERTEX, "vec4",  "gl_ClipVertex" },
   { ir_var_shader_out, VARYING_SLOT_COL0,        "vec4",  "gl_FrontColor" },
   { ir_var_shader_out, VARYING_SLOT_BFC0,        "vec4",  "gl_BackColor" },
   { ir_var_shader_out, VARYING_SLOT_COL1,        "vec4",  "gl_FrontSecondaryColor" },
   { ir_var_shader_out, VARYING_SLOT_BFC1,        "vec4",  "gl_BackSecondaryColor" },
   { ir_var_shader_out, VARYING_SLOT_FOGC,        "float", "gl_FogFragCoord" },
}
const builtin_variable builtin_110_fs_variables[] static
Initial value:
= {
   { ir_var_shader_out, FRAG_RESULT_DEPTH, "float", "gl_FragDepth" },
}
const builtin_variable builtin_120_fs_variables[] static
Initial value:
= {
   { ir_var_shader_in,  VARYING_SLOT_PNTC,   "vec2",   "gl_PointCoord" },
}
const builtin_variable builtin_130_vs_variables[] static
Initial value:
= {
   { ir_var_system_value,  SYSTEM_VALUE_VERTEX_ID, "int",   "gl_VertexID" },
}
const builtin_variable builtin_300ES_fs_variables[] static
Initial value:
= {
   { ir_var_shader_in,  VARYING_SLOT_POS,  "vec4",  "gl_FragCoord" },
   { ir_var_shader_in,  VARYING_SLOT_FACE, "bool",  "gl_FrontFacing" },
   { ir_var_shader_out, FRAG_RESULT_DEPTH, "float", "gl_FragDepth" },
   { ir_var_shader_in,  VARYING_SLOT_PNTC, "vec2",  "gl_PointCoord" },
}
const builtin_variable builtin_300ES_vs_variables[] static
Initial value:
= {
   { ir_var_system_value,  SYSTEM_VALUE_VERTEX_ID, "int",   "gl_VertexID" },
}
const builtin_variable builtin_core_fs_variables[] static
Initial value:
= {
   { ir_var_shader_in,  VARYING_SLOT_POS,  "vec4",  "gl_FragCoord" },
   { ir_var_shader_in,  VARYING_SLOT_FACE, "bool",  "gl_FrontFacing" },
   { ir_var_shader_out, FRAG_RESULT_COLOR, "vec4",  "gl_FragColor" },
}
const builtin_variable builtin_core_vs_variables[] static
Initial value:
= {
   { ir_var_shader_out, VARYING_SLOT_POS,  "vec4",  "gl_Position" },
   { ir_var_shader_out, VARYING_SLOT_PSIZ, "float", "gl_PointSize" },
}
struct gl_builtin_uniform_element gl_BackLightModelProduct_elements[] static
Initial value:
= {
   {"sceneColor", {STATE_LIGHTMODEL_SCENECOLOR, 1}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_BackLightProduct_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHTPROD, 0, 1, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_LIGHTPROD, 0, 1, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_LIGHTPROD, 0, 1, STATE_SPECULAR}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_BackMaterial_elements[] static
Initial value:
= {
   {"emission", {STATE_MATERIAL, 1, STATE_EMISSION}, SWIZZLE_XYZW},
   {"ambient", {STATE_MATERIAL, 1, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_MATERIAL, 1, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_MATERIAL, 1, STATE_SPECULAR}, SWIZZLE_XYZW},
   {"shininess", {STATE_MATERIAL, 1, STATE_SHININESS}, SWIZZLE_XXXX},
}
struct gl_builtin_uniform_element gl_BumpRotMatrix0MESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_ROT_MATRIX_0}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_BumpRotMatrix1MESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_ROT_MATRIX_1}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_ClipPlane_elements[] static
Initial value:
= {
   {NULL, {STATE_CLIPPLANE, 0, 0}, SWIZZLE_XYZW}
}
struct gl_builtin_uniform_element gl_CurrentAttribFragMESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_CURRENT_ATTRIB_MAYBE_VP_CLAMPED, 0}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_CurrentAttribVertMESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_CURRENT_ATTRIB, 0}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_DepthRange_elements[] static
Initial value:
= {
   {"near", {STATE_DEPTH_RANGE, 0, 0}, SWIZZLE_XXXX},
   {"far", {STATE_DEPTH_RANGE, 0, 0}, SWIZZLE_YYYY},
   {"diff", {STATE_DEPTH_RANGE, 0, 0}, SWIZZLE_ZZZZ},
}
struct gl_builtin_uniform_element gl_EyePlaneQ_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_Q}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_EyePlaneR_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_R}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_EyePlaneS_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_S}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_EyePlaneT_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_EYE_T}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_Fog_elements[] static
Initial value:
= {
   {"color", {STATE_FOG_COLOR}, SWIZZLE_XYZW},
   {"density", {STATE_FOG_PARAMS}, SWIZZLE_XXXX},
   {"start", {STATE_FOG_PARAMS}, SWIZZLE_YYYY},
   {"end", {STATE_FOG_PARAMS}, SWIZZLE_ZZZZ},
   {"scale", {STATE_FOG_PARAMS}, SWIZZLE_WWWW},
}
struct gl_builtin_uniform_element gl_FogParamsOptimizedMESA_elements[] static
Initial value:
= {
   {NULL, {STATE_INTERNAL, STATE_FOG_PARAMS_OPTIMIZED}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_FrontLightModelProduct_elements[] static
Initial value:
= {
   {"sceneColor", {STATE_LIGHTMODEL_SCENECOLOR, 0}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_FrontLightProduct_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHTPROD, 0, 0, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_LIGHTPROD, 0, 0, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_LIGHTPROD, 0, 0, STATE_SPECULAR}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_FrontMaterial_elements[] static
Initial value:
= {
   {"emission", {STATE_MATERIAL, 0, STATE_EMISSION}, SWIZZLE_XYZW},
   {"ambient", {STATE_MATERIAL, 0, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_MATERIAL, 0, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_MATERIAL, 0, STATE_SPECULAR}, SWIZZLE_XYZW},
   {"shininess", {STATE_MATERIAL, 0, STATE_SHININESS}, SWIZZLE_XXXX},
}
struct gl_builtin_uniform_element gl_LightModel_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHTMODEL_AMBIENT, 0}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_LightSource_elements[] static
Initial value:
= {
   {"ambient", {STATE_LIGHT, 0, STATE_AMBIENT}, SWIZZLE_XYZW},
   {"diffuse", {STATE_LIGHT, 0, STATE_DIFFUSE}, SWIZZLE_XYZW},
   {"specular", {STATE_LIGHT, 0, STATE_SPECULAR}, SWIZZLE_XYZW},
   {"position", {STATE_LIGHT, 0, STATE_POSITION}, SWIZZLE_XYZW},
   {"halfVector", {STATE_LIGHT, 0, STATE_HALF_VECTOR}, SWIZZLE_XYZW},
   {"spotDirection", {STATE_LIGHT, 0, STATE_SPOT_DIRECTION},
    MAKE_SWIZZLE4(SWIZZLE_X,
                  SWIZZLE_Y,
                  SWIZZLE_Z,
                  SWIZZLE_Z)},
   {"spotCosCutoff", {STATE_LIGHT, 0, STATE_SPOT_DIRECTION}, SWIZZLE_WWWW},
   {"spotCutoff", {STATE_LIGHT, 0, STATE_SPOT_CUTOFF}, SWIZZLE_XXXX},
   {"spotExponent", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_WWWW},
   {"constantAttenuation", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_XXXX},
   {"linearAttenuation", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_YYYY},
   {"quadraticAttenuation", {STATE_LIGHT, 0, STATE_ATTENUATION}, SWIZZLE_ZZZZ},
}
struct gl_builtin_uniform_element gl_NormalMatrix_elements[] static
Initial value:
= {
   { NULL, { STATE_MODELVIEW_MATRIX, 0, 0, 0, STATE_MATRIX_INVERSE},
     MAKE_SWIZZLE4(SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_Z) },
   { NULL, { STATE_MODELVIEW_MATRIX, 0, 1, 1, STATE_MATRIX_INVERSE},
     MAKE_SWIZZLE4(SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_Z) },
   { NULL, { STATE_MODELVIEW_MATRIX, 0, 2, 2, STATE_MATRIX_INVERSE},
     MAKE_SWIZZLE4(SWIZZLE_X, SWIZZLE_Y, SWIZZLE_Z, SWIZZLE_Z) },
}
struct gl_builtin_uniform_element gl_NormalScale_elements[] static
Initial value:
= {
   {NULL, {STATE_NORMAL_SCALE}, SWIZZLE_XXXX},
}
struct gl_builtin_uniform_element gl_ObjectPlaneQ_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_Q}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_ObjectPlaneR_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_R}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_ObjectPlaneS_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_S}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_ObjectPlaneT_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXGEN, 0, STATE_TEXGEN_OBJECT_T}, SWIZZLE_XYZW},
}
struct gl_builtin_uniform_element gl_Point_elements[] static
Initial value:
= {
   {"size", {STATE_POINT_SIZE}, SWIZZLE_XXXX},
   {"sizeMin", {STATE_POINT_SIZE}, SWIZZLE_YYYY},
   {"sizeMax", {STATE_POINT_SIZE}, SWIZZLE_ZZZZ},
   {"fadeThresholdSize", {STATE_POINT_SIZE}, SWIZZLE_WWWW},
   {"distanceConstantAttenuation", {STATE_POINT_ATTENUATION}, SWIZZLE_XXXX},
   {"distanceLinearAttenuation", {STATE_POINT_ATTENUATION}, SWIZZLE_YYYY},
   {"distanceQuadraticAttenuation", {STATE_POINT_ATTENUATION}, SWIZZLE_ZZZZ},
}
struct gl_builtin_uniform_element gl_TextureEnvColor_elements[] static
Initial value:
= {
   {NULL, {STATE_TEXENV_COLOR, 0}, SWIZZLE_XYZW},
}