Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_vector_visitor Class Reference
Public Member Functions
lower_vector_visitor ()
void handle_rvalue (ir_rvalue **rvalue)
Public Member Functions inherited from ir_rvalue_visitor
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
Data Fields
bool dont_lower_swz
Should SWZ-like expressions be lowered?
bool progress
Constructor & Destructor Documentation
lower_vector_visitor::lower_vector_visitor () inline
Member Function Documentation
void lower_vector_visitor::handle_rvalue (ir_rvalue ** rvalue) virtual
Implements ir_rvalue_base_visitor.
References ir_instruction::as_constant(), ir_expression::as_expression(), ir_builder::assign(), ir_constant_data::b, ir_hierarchical_visitor::base_ir, dont_lower_swz, ir_builder::expr(), ir_constant_data::f, ir_expression::get_num_operands(), GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_quadop_vector, ir_instruction::ir_type, ir_type_constant, ir_var_temporary, is_extended_swizzle(), ir_expression::operands, ir_expression::operation, progress, ir_rvalue::type, ir_constant_data::u, and ir_constant::value.
Field Documentation
bool lower_vector_visitor::dont_lower_swz
Should SWZ-like expressions be lowered?
Referenced by handle_rvalue(), and lower_quadop_vector().
bool lower_vector_visitor::progress
Referenced by handle_rvalue(), and lower_quadop_vector().
The documentation for this class was generated from the following file:
lower_vector.cpp