Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_vec_index_to_swizzle_visitor Class Reference
Visitor class for replacing expressions with ir_constant values.
Public Member Functions
ir_vec_index_to_swizzle_visitor ()
ir_rvalue * convert_vector_extract_to_swizzle (ir_rvalue *val)
virtual ir_visitor_status visit_enter (ir_expression *)
virtual ir_visitor_status visit_enter (ir_swizzle *)
virtual ir_visitor_status visit_enter (ir_assignment *)
virtual ir_visitor_status visit_enter (ir_return *)
virtual ir_visitor_status visit_enter (ir_call *)
virtual ir_visitor_status visit_enter (ir_if *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
bool progress
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Detailed Description
Visitor class for replacing expressions with ir_constant values.
Constructor & Destructor Documentation
ir_vec_index_to_swizzle_visitor::ir_vec_index_to_swizzle_visitor () inline
References progress.
Member Function Documentation
ir_rvalue * ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle (ir_rvalue * val)
References ir_instruction::as_expression(), ir_rvalue::constant_expression_value(), ir_builder::expr(), ir_constant_data::i, ir_binop_vector_extract, ir_expression::operands, ir_expression::operation, progress, ralloc_parent(), ir_rvalue::type, and ir_constant::value.
Referenced by visit_enter().
ir_visitor_status ir_vec_index_to_swizzle_visitor::visit_enter (ir_expression * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_swizzle(), ir_expression::get_num_operands(), ir_expression::operands, and visit_continue.
ir_visitor_status ir_vec_index_to_swizzle_visitor::visit_enter (ir_swizzle * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_swizzle(), ir_swizzle::val, and visit_continue.
ir_visitor_status ir_vec_index_to_swizzle_visitor::visit_enter (ir_assignment * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_swizzle(), ir_assignment::rhs, and visit_continue.
ir_visitor_status ir_vec_index_to_swizzle_visitor::visit_enter (ir_return * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_swizzle(), ir_return::value, and visit_continue.
ir_visitor_status ir_vec_index_to_swizzle_visitor::visit_enter (ir_call * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_swizzle(), and visit_continue.
ir_visitor_status ir_vec_index_to_swizzle_visitor::visit_enter (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_if::condition, convert_vector_extract_to_swizzle(), and visit_continue.
Field Documentation
bool ir_vec_index_to_swizzle_visitor::progress
Referenced by convert_vector_extract_to_swizzle(), do_vec_index_to_swizzle(), and ir_vec_index_to_swizzle_visitor().
The documentation for this class was generated from the following file:
lower_vec_index_to_swizzle.cpp