Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vector_insert_visitor Class Reference
Public Member Functions
vector_insert_visitor (bool lower_nonconstant_index)
virtual ~vector_insert_visitor ()
virtual void handle_rvalue (ir_rvalue **rv)
Public Member Functions inherited from ir_rvalue_visitor
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
Data Fields
ir_factory factory
exec_list factory_instructions
bool progress
bool lower_nonconstant_index
Constructor & Destructor Documentation
vector_insert_visitor::vector_insert_visitor (bool lower_nonconstant_index) inline
virtual vector_insert_visitor::~vector_insert_visitor () inline virtual
Member Function Documentation
void vector_insert_visitor::handle_rvalue (ir_rvalue ** rv) virtual
Implements ir_rvalue_base_visitor.
References ir_builder::assign(), ir_rvalue::clone(), ir_rvalue::constant_expression_value(), ir_builder::equal(), ir_builder::expr(), ir_constant_data::i, ir_builder::if_tree(), ir_triop_vector_insert, ir_instruction::ir_type, ir_type_expression, ir_expression::operands, ir_expression::operation, ralloc_parent(), ir_rvalue::type, ir_constant::value, and ir_builder::WRITEMASK_X.
Field Documentation
ir_factory vector_insert_visitor::factory
exec_list vector_insert_visitor::factory_instructions
bool vector_insert_visitor::lower_nonconstant_index
bool vector_insert_visitor::progress
Referenced by lower_vector_insert().
The documentation for this class was generated from the following file:
lower_vector_insert.cpp