Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_uniform_block_active_visitor Class Reference
#include <link_uniform_block_active_visitor.h>
Public Member Functions
link_uniform_block_active_visitor (void *mem_ctx, struct hash_table *ht, struct gl_shader_program *prog)
virtual ir_visitor_status visit_enter (ir_dereference_array *)
virtual ir_visitor_status visit (ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
bool success
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
link_uniform_block_active_visitor::link_uniform_block_active_visitor (void * mem_ctx, struct hash_table * ht, struct gl_shader_program * prog) inline
Member Function Documentation
ir_visitor_status link_uniform_block_active_visitor::visit (ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References ir_variable::interface_type, ir_variable::is_in_uniform_block(), ir_variable::is_interface_instance(), linker_error(), process_block(), success, ir_variable::type, ir_dereference_variable::var, visit_continue, and visit_stop.
ir_visitor_status link_uniform_block_active_visitor::visit_enter (ir_dereference_array * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_dereference_array::array, link_uniform_block_active::array_elements, ir_dereference_array::array_index, ir_instruction::as_constant(), ir_instruction::as_dereference_variable(), ir_constant::get_uint_component(), link_uniform_block_active::has_instance_name, ir_variable::interface_type, ir_variable::is_in_uniform_block(), ir_variable::is_interface_instance(), linker_error(), link_uniform_block_active::num_array_elements, process_block(), reralloc, success, link_uniform_block_active::type, ir_dereference_variable::var, visit_continue, visit_continue_with_parent, and visit_stop.
Field Documentation
bool link_uniform_block_active_visitor::success
Referenced by visit(), and visit_enter().
The documentation for this class was generated from the following files:
link_uniform_block_active_visitor.h
link_uniform_block_active_visitor.cpp