Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_node Class Reference
Abstract syntax tree node definitions
Base class of all abstract syntax tree nodes.
#include <ast.h>
Public Member Functions
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
Static Public Member Functions
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Data Fields
struct {
unsigned source
GLSL source number.
unsigned line
Line number within the source string.
unsigned column
Column in the line.
} location
exec_node link
Protected Member Functions
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Detailed Description
Base class of all abstract syntax tree nodes.
Constructor & Destructor Documentation
ast_node::ast_node (void) protected
The only constructor is protected so that only derived class objects can be created.
References location.
Member Function Documentation
struct YYLTYPE ast_node::get_location (void) const inline read
Retrieve the source location of an AST node.
This function is primarily used to get the source position of an AST node into a form that can be passed to _mesa_glsl_error.
See Also
_mesa_glsl_error, ast_node::set_location
References location.
Referenced by _mesa_ast_field_selection_to_hir(), get_scalar_boolean_operand(), get_variable_being_redeclared(), ast_type_specifier::glsl_type(), ast_expression::hir(), ast_function_expression::hir(), ast_struct_specifier::hir(), ast_type_specifier::hir(), ast_declarator_list::hir(), ast_parameter_declarator::hir(), ast_function::hir(), ast_case_label::hir(), ast_jump_statement::hir(), ast_function_definition::hir(), ast_interface_block::hir(), ast_parameter_declarator::parameters_to_hir(), process_array_type(), process_initializer(), and verify_parameter_modes().
ir_rvalue * ast_node::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented in ast_interface_block, ast_function_definition, ast_jump_statement, ast_iteration_statement, ast_switch_statement, ast_selection_statement, ast_switch_body, ast_case_statement_list, ast_case_statement, ast_case_label_list, ast_case_label, ast_expression_statement, ast_function, ast_parameter_declarator, ast_declarator_list, ast_type_specifier, ast_struct_specifier, ast_compound_statement, ast_function_expression, and ast_expression.
Referenced by ast_function_expression::hir(), ast_selection_statement::hir(), ast_switch_statement::hir(), ast_iteration_statement::hir(), process_array_type(), and process_parameters().
static void ast_node::operator delete (void * table) inline static
References ralloc_free().
static void* ast_node::operator new (size_t size, void * ctx) inline static
References rzalloc_size().
void ast_node::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented in ast_function_definition, ast_jump_statement, ast_iteration_statement, ast_switch_statement, ast_selection_statement, ast_switch_body, ast_case_statement_list, ast_case_statement, ast_case_label_list, ast_case_label, ast_expression_statement, ast_function, ast_parameter_declarator, ast_declarator_list, ast_fully_specified_type, ast_type_specifier, ast_struct_specifier, ast_declaration, ast_compound_statement, ast_expression_bin, and ast_expression.
Referenced by compile_shader(), ast_expression::print(), ast_compound_statement::print(), ast_struct_specifier::print(), ast_declarator_list::print(), ast_function::print(), ast_case_label_list::print(), ast_case_statement::print(), ast_case_statement_list::print(), ast_selection_statement::print(), ast_switch_statement::print(), and ast_iteration_statement::print().
void ast_node::set_location (const struct YYLTYPE & locp) inline
Set the source location of an AST node from a parser location.
See Also
ast_node::get_location
References location.
Field Documentation
unsigned ast_node::column
Column in the line.
unsigned ast_node::line
Line number within the source string.
exec_node ast_node::link
Referenced by ast_compound_statement::ast_compound_statement(), ast_struct_specifier::ast_struct_specifier(), ast_expression::hir(), ast_function_expression::hir(), ast_compound_statement::hir(), ast_declarator_list::hir(), ast_case_label_list::hir(), ast_case_statement::hir(), ast_case_statement_list::hir(), ast_parameter_declarator::parameters_to_hir(), ast_expression::print(), ast_compound_statement::print(), ast_struct_specifier::print(), ast_declarator_list::print(), ast_function::print(), ast_case_label_list::print(), ast_case_statement::print(), and ast_case_statement_list::print().
struct { ... } ast_node::location
Referenced by ast_node(), get_location(), and set_location().
unsigned ast_node::source
GLSL source number.
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp