Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
deref_replacer Class Reference
Replace a dereference of a variable with a specified r-value.
Public Member Functions
deref_replacer (const ir_variable *variable_to_replace, ir_rvalue *value)
virtual void handle_rvalue (ir_rvalue **rvalue)
Public Member Functions inherited from ir_rvalue_visitor
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
Data Fields
const ir_variable * variable_to_replace
ir_rvalue * value
bool progress
Detailed Description
Replace a dereference of a variable with a specified r-value.
Each time a dereference of the specified value is replaced, the r-value tree is cloned.
Constructor & Destructor Documentation
deref_replacer::deref_replacer (const ir_variable * variable_to_replace, ir_rvalue * value) inline
Member Function Documentation
virtual void deref_replacer::handle_rvalue (ir_rvalue ** rvalue) inline virtual
Implements ir_rvalue_base_visitor.
References ir_dereference_variable::as_dereference_variable(), ir_rvalue::clone(), progress, ralloc_parent(), value, and ir_dereference_variable::var.
Field Documentation
bool deref_replacer::progress
Referenced by assignment_generator::generate(), and handle_rvalue().
ir_rvalue* deref_replacer::value
Referenced by handle_rvalue().
const ir_variable* deref_replacer::variable_to_replace
The documentation for this class was generated from the following file:
lower_variable_index_to_cond_assign.cpp