Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_array_reference_visitor Class Reference
This class does a walk over the tree, coming up with the set of variables that could be split by looking to see if they are arrays that are only ever constant-index dereferenced.
Public Member Functions
ir_array_reference_visitor (void)
~ir_array_reference_visitor (void)
bool get_split_list (exec_list *instructions, bool linked)
virtual ir_visitor_status visit (ir_variable *)
virtual ir_visitor_status visit (ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (ir_dereference_array *)
virtual ir_visitor_status visit_enter (ir_function_signature *)
variable_entry * get_variable_entry (ir_variable *var)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
exec_list variable_list
void * mem_ctx
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Detailed Description
This class does a walk over the tree, coming up with the set of variables that could be split by looking to see if they are arrays that are only ever constant-index dereferenced.
Constructor & Destructor Documentation
ir_array_reference_visitor::ir_array_reference_visitor (void) inline
References ralloc_context().
ir_array_reference_visitor::~ir_array_reference_visitor (void) inline
References ralloc_free().
Member Function Documentation
bool ir_array_reference_visitor::get_split_list (exec_list * instructions, bool linked)
References ir_variable::as_variable(), debug, opt_array_splitting::variable_entry::declaration, foreach_list, ir_variable::name, opt_array_splitting::variable_entry::split, opt_array_splitting::variable_entry::var, and visit_list_elements().
Referenced by optimize_split_arrays().
variable_entry * ir_array_reference_visitor::get_variable_entry (ir_variable * var)
References ir_var_auto, ir_var_temporary, ir_variable::mode, ir_variable::type, and opt_array_splitting::variable_entry::var.
ir_visitor_status ir_array_reference_visitor::visit (ir_variable * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References opt_array_splitting::variable_entry::declaration, and visit_continue.
ir_visitor_status ir_array_reference_visitor::visit (ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References opt_array_splitting::variable_entry::split, ir_dereference_variable::var, and visit_continue.
ir_visitor_status ir_array_reference_visitor::visit_enter (ir_dereference_array * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_dereference_array::array, ir_dereference_array::array_index, ir_instruction::as_constant(), ir_instruction::as_dereference_variable(), opt_array_splitting::variable_entry::split, ir_dereference_variable::var, visit_continue, and visit_continue_with_parent.
ir_visitor_status ir_array_reference_visitor::visit_enter (ir_function_signature * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_function_signature::body, visit_continue_with_parent, and visit_list_elements().
Field Documentation
void* ir_array_reference_visitor::mem_ctx
exec_list ir_array_reference_visitor::variable_list
Referenced by optimize_split_arrays().
The documentation for this class was generated from the following file:
opt_array_splitting.cpp