Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
count_uniform_size Class Reference
Class to help calculate the storage requirements for a set of uniforms.
Public Member Functions
count_uniform_size (struct string_to_uint_map *map)
void start_shader ()
void process (ir_variable *var)
Public Member Functions inherited from program_resource_visitor
void process (ir_variable *var)
Begin processing a variable.
void process (const glsl_type *type, const char *name)
Begin processing a variable of a structured type.
Data Fields
unsigned num_active_uniforms
Total number of active uniforms counted.
unsigned num_values
Number of data values required to back the storage for the active uniforms.
unsigned num_shader_samplers
Number of samplers used.
unsigned num_shader_uniform_components
Number of uniforms used in the current shader.
Additional Inherited Members
Protected Member Functions inherited from program_resource_visitor
virtual void visit_field (const glsl_struct_field *field)
Visit a record before visiting its fields.
Detailed Description
Class to help calculate the storage requirements for a set of uniforms.
As uniforms are added to the active set the number of active uniforms and the storage requirements for those uniforms are accumulated. The active uniforms are added the the hash table supplied to the constructor.
If the same uniform is added multiple times (i.e., once for each shader target), it will only be accounted once.
Constructor & Destructor Documentation
count_uniform_size::count_uniform_size (struct string_to_uint_map * map) inline
Member Function Documentation
void count_uniform_size::process (ir_variable * var) inline
References ir_variable::interface_type, ir_variable::is_interface_instance(), and program_resource_visitor::process().
Referenced by link_assign_uniform_locations().
void count_uniform_size::start_shader () inline
References num_shader_samplers, and num_shader_uniform_components.
Referenced by link_assign_uniform_locations().
Field Documentation
unsigned count_uniform_size::num_active_uniforms
Total number of active uniforms counted.
Referenced by link_assign_uniform_locations().
unsigned count_uniform_size::num_shader_samplers
Number of samplers used.
Referenced by link_assign_uniform_locations(), and start_shader().
unsigned count_uniform_size::num_shader_uniform_components
Number of uniforms used in the current shader.
Referenced by link_assign_uniform_locations(), and start_shader().
unsigned count_uniform_size::num_values
Number of data values required to back the storage for the active uniforms.
Referenced by link_assign_uniform_locations().
The documentation for this class was generated from the following file:
link_uniforms.cpp