Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_expression Class Reference
Intermediate representation nodes
#include <ir.h>
Public Member Functions
ir_expression (int op, const struct glsl_type *type, ir_rvalue *op0, ir_rvalue *op1=NULL, ir_rvalue *op2=NULL, ir_rvalue *op3=NULL)
ir_expression (int op, ir_rvalue *)
Constructor for unary operation expressions.
ir_expression (int op, ir_rvalue *op0, ir_rvalue *op1)
Constructor for binary operation expressions.
virtual ir_expression * as_expression ()
virtual ir_expression * clone (void *mem_ctx, struct hash_table *ht) const
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
Attempt to constant-fold the expression.
unsigned int get_num_operands () const
Determine the number of operands used by an expression.
const char * operator_string ()
Return a string representing this expression's operator.
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
Public Member Functions inherited from ir_rvalue
virtual ir_rvalue * as_rvalue ()
ir_rvalue * as_rvalue_to_saturate ()
virtual bool is_lvalue () const
virtual ir_variable * variable_referenced () const
Get the variable that is ultimately referenced by an r-value.
virtual ir_variable * whole_variable_referenced ()
If an r-value is a reference to a whole variable, get that variable.
virtual bool is_zero () const
Determine if an r-value has the value zero.
virtual bool is_one () const
Determine if an r-value has the value one.
virtual bool is_negative_one () const
Determine if an r-value has the value negative one.
virtual bool is_basis () const
Determine if an r-value is a basis vector.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Static Public Member Functions
static unsigned int get_num_operands (ir_expression_operation)
Determine the number of operands used by an expression.
static const char * operator_string (ir_expression_operation)
Return a string representing this expression's operator.
static ir_expression_operation get_operator (const char *)
Do a reverse-lookup to translate the given string into an operator.
Static Public Member Functions inherited from ir_rvalue
static ir_rvalue * error_value (void *mem_ctx)
Return a generic value of error_type.
Data Fields
ir_expression_operation operation
ir_rvalue * operands [4]
Data Fields inherited from ir_rvalue
struct glsl_type * type
Data Fields inherited from ir_instruction
enum ir_node_type ir_type
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Additional Inherited Members
Protected Member Functions inherited from ir_rvalue
ir_rvalue ()
Constructor & Destructor Documentation
ir_expression::ir_expression (int op, const struct glsl_type * type, ir_rvalue * op0, ir_rvalue * op1 = NULL, ir_rvalue * op2 = NULL, ir_rvalue * op3 = NULL)
References get_num_operands(), ir_instruction::ir_type, ir_type_expression, operands, operation, and ir_rvalue::type.
Referenced by clone().
ir_expression::ir_expression (int op, ir_rvalue * op0)
Constructor for unary operation expressions.
References GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_last_unop, ir_instruction::ir_type, ir_type_expression, ir_unop_abs, ir_unop_any, ir_unop_b2f, ir_unop_b2i, ir_unop_bit_not, ir_unop_bitcast_f2i, ir_unop_bitcast_f2u, ir_unop_bitcast_i2f, ir_unop_bitcast_u2f, ir_unop_ceil, ir_unop_cos, ir_unop_cos_reduced, ir_unop_dFdx, ir_unop_dFdy, ir_unop_exp, ir_unop_exp2, ir_unop_f2b, ir_unop_f2i, ir_unop_f2u, ir_unop_floor, ir_unop_fract, ir_unop_i2b, ir_unop_i2f, ir_unop_i2u, ir_unop_log, ir_unop_log2, ir_unop_logic_not, ir_unop_neg, ir_unop_noise, ir_unop_pack_half_2x16, ir_unop_pack_snorm_2x16, ir_unop_pack_snorm_4x8, ir_unop_pack_unorm_2x16, ir_unop_pack_unorm_4x8, ir_unop_rcp, ir_unop_round_even, ir_unop_rsq, ir_unop_sign, ir_unop_sin, ir_unop_sin_reduced, ir_unop_sqrt, ir_unop_trunc, ir_unop_u2f, ir_unop_u2i, ir_unop_unpack_half_2x16, ir_unop_unpack_half_2x16_split_x, ir_unop_unpack_half_2x16_split_y, ir_unop_unpack_snorm_2x16, ir_unop_unpack_snorm_4x8, ir_unop_unpack_unorm_2x16, ir_unop_unpack_unorm_4x8, operands, operation, and ir_rvalue::type.
ir_expression::ir_expression (int op, ir_rvalue * op0, ir_rvalue * op1)
Constructor for binary operation expressions.
References GLSL_TYPE_BOOL, ir_binop_add, ir_binop_all_equal, ir_binop_any_nequal, ir_binop_bit_and, ir_binop_bit_or, ir_binop_bit_xor, ir_binop_div, ir_binop_dot, ir_binop_equal, ir_binop_gequal, ir_binop_greater, ir_binop_lequal, ir_binop_less, ir_binop_logic_and, ir_binop_logic_or, ir_binop_logic_xor, ir_binop_lshift, ir_binop_max, ir_binop_min, ir_binop_mod, ir_binop_mul, ir_binop_nequal, ir_binop_pack_half_2x16_split, ir_binop_pow, ir_binop_rshift, ir_binop_sub, ir_binop_vector_extract, ir_last_unop, ir_instruction::ir_type, ir_type_expression, operands, operation, and ir_rvalue::type.
Member Function Documentation
virtual void ir_expression::accept (ir_visitor * v) inline virtual
Reimplemented from ir_rvalue.
References ir_visitor::visit().
Referenced by accept().
ir_visitor_status ir_expression::accept (ir_hierarchical_visitor * v) virtual
Reimplemented from ir_rvalue.
References accept(), get_num_operands(), operands, visit_continue, visit_continue_with_parent, ir_hierarchical_visitor::visit_enter(), ir_hierarchical_visitor::visit_leave(), and visit_stop.
virtual ir_expression* ir_expression::as_expression () inline virtual
Reimplemented from ir_instruction.
Referenced by lower_vector_visitor::handle_rvalue(), lower_noise_visitor::handle_rvalue(), and verify_parameter_modes().
ir_expression * ir_expression::clone (void * mem_ctx, struct hash_table * ht) const virtual
Reimplemented from ir_rvalue.
References ir_rvalue::clone(), get_num_operands(), ir_expression(), operands, operation, and ir_rvalue::type.
ir_constant * ir_expression::constant_expression_value (struct hash_table * variable_context = NULL) virtual
Attempt to constant-fold the expression.
The "variable_context" hash table links ir_variable * to ir_constant * that represent the variables' values. NULL represents an empty context.
If the expression cannot be constant folded, this method will return NULL.
Reimplemented from ir_rvalue.
References ir_constant_data::b, bitcast_f2u(), bitcast_u2f(), ir_rvalue::constant_expression_value(), dot(), ir_constant_data::f, get_num_operands(), GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant::has_value(), ir_constant_data::i, ir_binop_add, ir_binop_all_equal, ir_binop_any_nequal, ir_binop_bit_and, ir_binop_bit_or, ir_binop_bit_xor, ir_binop_div, ir_binop_dot, ir_binop_equal, ir_binop_gequal, ir_binop_greater, ir_binop_lequal, ir_binop_less, ir_binop_logic_and, ir_binop_logic_or, ir_binop_logic_xor, ir_binop_lshift, ir_binop_max, ir_binop_min, ir_binop_mod, ir_binop_mul, ir_binop_nequal, ir_binop_pow, ir_binop_rshift, ir_binop_sub, ir_binop_vector_extract, ir_quadop_bitfield_insert, ir_quadop_vector, ir_triop_bitfield_extract, ir_triop_lrp, ir_triop_vector_insert, ir_unop_abs, ir_unop_any, ir_unop_b2f, ir_unop_b2i, ir_unop_bit_count, ir_unop_bit_not, ir_unop_bitcast_f2i, ir_unop_bitcast_f2u, ir_unop_bitcast_i2f, ir_unop_bitcast_u2f, ir_unop_bitfield_reverse, ir_unop_ceil, ir_unop_cos, ir_unop_cos_reduced, ir_unop_dFdx, ir_unop_dFdy, ir_unop_exp, ir_unop_exp2, ir_unop_f2b, ir_unop_f2i, ir_unop_f2u, ir_unop_find_lsb, ir_unop_find_msb, ir_unop_floor, ir_unop_fract, ir_unop_i2b, ir_unop_i2f, ir_unop_i2u, ir_unop_log, ir_unop_log2, ir_unop_logic_not, ir_unop_neg, ir_unop_pack_half_2x16, ir_unop_pack_snorm_2x16, ir_unop_pack_snorm_4x8, ir_unop_pack_unorm_2x16, ir_unop_pack_unorm_4x8, ir_unop_rcp, ir_unop_round_even, ir_unop_rsq, ir_unop_sign, ir_unop_sin, ir_unop_sin_reduced, ir_unop_sqrt, ir_unop_trunc, ir_unop_u2f, ir_unop_u2i, ir_unop_unpack_half_2x16, ir_unop_unpack_snorm_2x16, ir_unop_unpack_snorm_4x8, ir_unop_unpack_unorm_2x16, ir_unop_unpack_unorm_4x8, operands, operation, pack_2x16(), pack_4x8(), pack_half_1x16(), pack_snorm_1x16(), pack_snorm_1x8(), pack_unorm_1x16(), pack_unorm_1x8(), ralloc_parent(), ir_rvalue::type, ir_constant_data::u, unpack_2x16(), unpack_4x8(), unpack_half_1x16(), unpack_snorm_1x16(), unpack_snorm_1x8(), unpack_unorm_1x16(), unpack_unorm_1x8(), and ir_constant::value.
Referenced by calculate_iterations(), and convert_component().
unsigned int ir_expression::get_num_operands (ir_expression_operation op) static
Determine the number of operands used by an expression.
References ir_last_binop, ir_last_opcode, ir_last_quadop, ir_last_triop, and ir_last_unop.
Referenced by lower_vector_visitor::handle_rvalue(), has_matrix_operand(), mat_op_to_vec_predicate(), ir_rvalue_base_visitor::rvalue_visit(), ir_print_visitor::visit(), ir_vec_index_to_swizzle_visitor::visit_enter(), ir_vec_index_to_cond_assign_visitor::visit_enter(), and ir_mat_op_to_vec_visitor::visit_leave().
unsigned int ir_expression::get_num_operands () const inline
Determine the number of operands used by an expression.
References ir_quadop_vector, and operation.
Referenced by accept(), clone(), constant_expression_value(), and ir_expression().
ir_expression_operation ir_expression::get_operator (const char * str) static
Do a reverse-lookup to translate the given string into an operator.
References operator_strs.
const char * ir_expression::operator_string ()
Return a string representing this expression's operator.
References operation.
Referenced by ir_print_visitor::visit(), and ir_mat_op_to_vec_visitor::visit_leave().
const char * ir_expression::operator_string (ir_expression_operation op) static
Return a string representing this expression's operator.
References ir_quadop_vector, and operator_strs.
Field Documentation
ir_rvalue* ir_expression::operands[4]
Referenced by accept(), clone(), constant_expression_value(), ir_vec_index_to_cond_assign_visitor::convert_vector_extract_to_cond_assign(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), do_assignment(), lower_clip_distance_visitor::fix_lhs(), fix_parameter(), get_basic_induction_increment(), lower_vector_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), has_matrix_operand(), ir_expression(), is_extended_swizzle(), mat_op_to_vec_predicate(), ir_rvalue_base_visitor::rvalue_visit(), try_max_zero(), try_min_one(), update_type(), verify_parameter_modes(), ir_print_visitor::visit(), ir_vec_index_to_swizzle_visitor::visit_enter(), ir_vec_index_to_cond_assign_visitor::visit_enter(), ir_mat_op_to_vec_visitor::visit_leave(), ir_validate::visit_leave(), lower_instructions_visitor::visit_leave(), and loop_control_visitor::visit_leave().
ir_expression_operation ir_expression::operation
Referenced by clone(), constant_expression_value(), ir_vec_index_to_cond_assign_visitor::convert_vector_extract_to_cond_assign(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), do_assignment(), lower_clip_distance_visitor::fix_lhs(), fix_parameter(), get_basic_induction_increment(), get_num_operands(), lower_vector_visitor::handle_rvalue(), lower_noise_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), ir_expression(), is_extended_swizzle(), operator_string(), try_max_zero(), try_min_one(), verify_parameter_modes(), ir_set_program_inouts_visitor::visit_enter(), ir_mat_op_to_vec_visitor::visit_leave(), ir_validate::visit_leave(), lower_instructions_visitor::visit_leave(), and loop_control_visitor::visit_leave().
The documentation for this class was generated from the following files:
ir.h
ir.cpp
ir_clone.cpp
ir_constant_expression.cpp
ir_hv_accept.cpp