Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
call_link_visitor Class Reference
Public Member Functions
call_link_visitor (gl_shader_program *prog, gl_shader *linked, gl_shader **shader_list, unsigned num_shaders)
~call_link_visitor ()
virtual ir_visitor_status visit (ir_variable *ir)
virtual ir_visitor_status visit_enter (ir_call *ir)
virtual ir_visitor_status visit (ir_dereference_variable *ir)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
bool success
Was function linking successful?
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
call_link_visitor::call_link_visitor (gl_shader_program * prog, gl_shader * linked, gl_shader ** shader_list, unsigned num_shaders) inline
References success.
call_link_visitor::~call_link_visitor () inline
Member Function Documentation
virtual ir_visitor_status call_link_visitor::visit (ir_variable * ir) inline virtual
Reimplemented from ir_hierarchical_visitor.
References visit_continue.
virtual ir_visitor_status call_link_visitor::visit (ir_dereference_variable * ir) inline virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References ir_variable::clone(), ir_variable::max_array_access, ir_variable::name, ir_variable::type, ir_dereference_variable::var, and visit_continue.
virtual ir_visitor_status call_link_visitor::visit_enter (ir_call * ir) inline virtual
Reimplemented from ir_hierarchical_visitor.
References ir_function_signature::accept(), ir_call::actual_parameters, ir_function::add_signature(), ir_function_signature::body, ir_call::callee, ir_instruction::clone(), copy(), ir_function::exact_matching_signature(), find_matching_signature(), foreach_list_const, ir_function_signature::function_name(), ir_function_signature::is_builtin, ir_function_signature::is_defined, linker_error(), ir_function_signature::parameters, ir_function_signature::replace_parameters(), ir_function_signature::return_type, success, ir_call::use_builtin, visit_continue, and visit_stop.
Field Documentation
bool call_link_visitor::success
Was function linking successful?
Referenced by call_link_visitor(), link_function_calls(), and visit_enter().
The documentation for this class was generated from the following file:
link_functions.cpp