Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_dereference_array Class Reference
Intermediate representation nodes
#include <ir.h>
Public Member Functions
ir_dereference_array (ir_rvalue *value, ir_rvalue *array_index)
ir_dereference_array (ir_variable *var, ir_rvalue *array_index)
virtual ir_dereference_array * clone (void *mem_ctx, struct hash_table *) const
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
virtual ir_dereference_array * as_dereference_array ()
virtual ir_variable * variable_referenced () const
Get the variable that is ultimately referenced by an r-value.
virtual void constant_referenced (struct hash_table *variable_context, ir_constant *&store, int &offset) const
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
Public Member Functions inherited from ir_dereference
virtual ir_dereference * as_dereference ()
bool is_lvalue () const
Public Member Functions inherited from ir_rvalue
virtual ir_rvalue * as_rvalue ()
ir_rvalue * as_rvalue_to_saturate ()
virtual ir_variable * whole_variable_referenced ()
If an r-value is a reference to a whole variable, get that variable.
virtual bool is_zero () const
Determine if an r-value has the value zero.
virtual bool is_one () const
Determine if an r-value has the value one.
virtual bool is_negative_one () const
Determine if an r-value has the value negative one.
virtual bool is_basis () const
Determine if an r-value is a basis vector.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Data Fields
ir_rvalue * array
ir_rvalue * array_index
Additional Inherited Members
Static Public Member Functions inherited from ir_rvalue
static ir_rvalue * error_value (void *mem_ctx)
Return a generic value of error_type.
Protected Member Functions inherited from ir_rvalue
ir_rvalue ()
Constructor & Destructor Documentation
ir_dereference_array::ir_dereference_array (ir_rvalue * value, ir_rvalue * array_index)
References array_index, ir_instruction::ir_type, and ir_type_dereference_array.
Referenced by clone().
ir_dereference_array::ir_dereference_array (ir_variable * var, ir_rvalue * array_index)
References array_index, ir_instruction::ir_type, ir_type_dereference_array, and ralloc_parent().
Member Function Documentation
virtual void ir_dereference_array::accept (ir_visitor * v) inline virtual
Reimplemented from ir_rvalue.
References ir_visitor::visit().
ir_visitor_status ir_dereference_array::accept (ir_hierarchical_visitor * v) virtual
Reimplemented from ir_rvalue.
References ir_rvalue::accept(), array, array_index, ir_hierarchical_visitor::in_assignee, visit_continue, visit_continue_with_parent, ir_hierarchical_visitor::visit_enter(), ir_hierarchical_visitor::visit_leave(), and visit_stop.
virtual ir_dereference_array* ir_dereference_array::as_dereference_array () inline virtual
Reimplemented from ir_instruction.
Referenced by lower_clip_distance_visitor::handle_rvalue(), variable_index_to_cond_assign_visitor::handle_rvalue(), and ir_array_splitting_visitor::split_deref().
ir_dereference_array * ir_dereference_array::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_dereference.
References array, array_index, ir_rvalue::clone(), and ir_dereference_array().
ir_constant * ir_dereference_array::constant_expression_value (struct hash_table * variable_context = NULL) virtual
Reimplemented from ir_rvalue.
References array, array_index, ir_constant::clone(), ir_rvalue::constant_expression_value(), ir_constant::constant_expression_value(), ir_constant_data::f, ir_constant::get_array_element(), GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ralloc_parent(), ir_rvalue::type, ir_constant_data::u, and ir_constant::value.
void ir_dereference_array::constant_referenced (struct hash_table * variable_context, ir_constant *& store, int & offset) const virtual
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
The offset is used when the reference is to a specific column of a matrix.
Implements ir_dereference.
References array, array_index, ir_instruction::as_dereference(), ir_rvalue::constant_expression_value(), ir_dereference::constant_referenced(), ir_constant::get_array_element(), ir_constant::get_int_component(), ir_constant::get_uint_component(), GLSL_TYPE_INT, and ir_rvalue::type.
virtual ir_variable* ir_dereference_array::variable_referenced () const inline virtual
Get the variable that is ultimately referenced by an r-value.
Implements ir_dereference.
References array, and ir_rvalue::variable_referenced().
Field Documentation
ir_rvalue* ir_dereference_array::array
Referenced by accept(), clone(), constant_expression_value(), constant_referenced(), variable_index_to_cond_assign_visitor::convert_dereference_array(), lower_clip_distance_visitor::handle_rvalue(), variable_index_to_cond_assign_visitor::needs_lowering(), ir_rvalue_base_visitor::rvalue_visit(), ir_array_splitting_visitor::split_deref(), variable_index_to_cond_assign_visitor::storage_type_needs_lowering(), variable_referenced(), ir_print_visitor::visit(), link_uniform_block_active_visitor::visit_enter(), ir_set_program_inouts_visitor::visit_enter(), ir_validate::visit_enter(), ir_array_reference_visitor::visit_enter(), find_variable_index::visit_enter(), and ir_sampler_replacement_visitor::visit_leave().
ir_rvalue* ir_dereference_array::array_index
Referenced by accept(), clone(), constant_expression_value(), constant_referenced(), variable_index_to_cond_assign_visitor::convert_dereference_array(), lower_clip_distance_visitor::handle_rvalue(), flatten_named_interface_blocks_declarations::handle_rvalue(), ir_dereference_array(), variable_index_to_cond_assign_visitor::needs_lowering(), ir_rvalue_base_visitor::rvalue_visit(), ir_array_splitting_visitor::split_deref(), ir_print_visitor::visit(), link_uniform_block_active_visitor::visit_enter(), ir_set_program_inouts_visitor::visit_enter(), ir_validate::visit_enter(), ir_array_reference_visitor::visit_enter(), and find_variable_index::visit_enter().
The documentation for this class was generated from the following files:
ir.h
ir.cpp
ir_clone.cpp
ir_constant_expression.cpp
ir_hv_accept.cpp