Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_switch_statement Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_switch_statement (ast_expression *test_expression, ast_node *body)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
Data Fields
ast_expression * test_expression
ast_node * body
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned line
Line number within the source string.
unsigned column
Column in the line.
} location
exec_node link
Protected Member Functions
void test_to_hir (exec_list *, struct _mesa_glsl_parse_state *)
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Additional Inherited Members
Static Public Member Functions inherited from ast_node
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Constructor & Destructor Documentation
ast_switch_statement::ast_switch_statement (ast_expression * test_expression, ast_node * body)
References body, and test_expression.
Member Function Documentation
ir_rvalue * ast_switch_statement::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), body, ast_node::hir(), ir_var_temporary, test_expression, test_to_hir(), and ir_rvalue::type.
void ast_switch_statement::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References body, ast_node::print(), ast_expression::print(), and test_expression.
void ast_switch_statement::test_to_hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) protected
References ast_expression::hir(), ir_var_temporary, test_expression, and ir_rvalue::type.
Referenced by hir().
Field Documentation
ast_node* ast_switch_statement::body
Referenced by ast_switch_statement(), hir(), and print().
ast_expression* ast_switch_statement::test_expression
Referenced by ast_switch_statement(), hir(), print(), and test_to_hir().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp