Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_type_specifier Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_type_specifier (const char *name)
Construct a type specifier from a type name.
ast_type_specifier (ast_struct_specifier *s)
Construct a type specifier from a structure definition.
struct glsl_type * glsl_type (const char **name, struct _mesa_glsl_parse_state *state) const
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
ir_rvalue * hir (exec_list *, struct _mesa_glsl_parse_state *)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
Data Fields
const char * type_name
ast_struct_specifier * structure
int is_array
ast_expression * array_size
unsigned precision:2
bool is_precision_statement
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned line
Line number within the source string.
unsigned column
Column in the line.
} location
exec_node link
Additional Inherited Members
Static Public Member Functions inherited from ast_node
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_type_specifier::ast_type_specifier (const char * name) inline
Construct a type specifier from a type name.
ast_type_specifier::ast_type_specifier (ast_struct_specifier * s) inline
Construct a type specifier from a structure definition.
Member Function Documentation
const glsl_type * ast_type_specifier::glsl_type (const char ** name, struct _mesa_glsl_parse_state * state) const read
References array_size, ast_node::get_location(), is_array, process_array_type(), and type_name.
Referenced by ast_function_expression::hir(), ast_declarator_list::hir(), and ast_function::hir().
ir_rvalue * ast_type_specifier::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), ast_precision_none, ast_node::get_location(), ast_struct_specifier::hir(), is_array, is_precision_statement, is_valid_default_precision_type(), precision, structure, and type_name.
Referenced by ast_declarator_list::hir().
void ast_type_specifier::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References array_size, is_array, ast_expression::print(), ast_struct_specifier::print(), structure, and type_name.
Referenced by ast_fully_specified_type::print().
Field Documentation
ast_expression* ast_type_specifier::array_size
Referenced by glsl_type(), and print().
int ast_type_specifier::is_array
Referenced by glsl_type(), hir(), and print().
bool ast_type_specifier::is_precision_statement
Referenced by hir().
unsigned ast_type_specifier::precision
Referenced by hir(), and ast_declarator_list::hir().
ast_struct_specifier* ast_type_specifier::structure
Referenced by hir(), ast_declarator_list::hir(), and print().
const char* ast_type_specifier::type_name
Referenced by glsl_type(), ast_function_expression::hir(), hir(), and print().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
ast_type.cpp