Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_print_visitor Class Reference
Abstract base class of visitors of IR instruction trees.
#include <ir_print_visitor.h>
Public Member Functions
ir_print_visitor ()
virtual ~ir_print_visitor ()
void indent (void)
Visit methods
As typical for the visitor pattern, there must be one visit method for each concrete subclass of ir_instruction.
Virtual base classes within the hierarchy should not have visit methods.
virtual void visit (ir_rvalue *)
virtual void visit (ir_variable *)
virtual void visit (ir_function_signature *)
virtual void visit (ir_function *)
virtual void visit (ir_expression *)
virtual void visit (ir_texture *)
virtual void visit (ir_swizzle *)
virtual void visit (ir_dereference_variable *)
virtual void visit (ir_dereference_array *)
virtual void visit (ir_dereference_record *)
virtual void visit (ir_assignment *)
virtual void visit (ir_constant *)
virtual void visit (ir_call *)
virtual void visit (ir_return *)
virtual void visit (ir_discard *)
virtual void visit (ir_if *)
virtual void visit (ir_loop *)
virtual void visit (ir_loop_jump *)
Public Member Functions inherited from ir_visitor
virtual ~ir_visitor ()
Detailed Description
Abstract base class of visitors of IR instruction trees.
Constructor & Destructor Documentation
ir_print_visitor::ir_print_visitor ()
References ralloc_context().
ir_print_visitor::~ir_print_visitor () virtual
References ralloc_free().
Member Function Documentation
void ir_print_visitor::indent (void)
Referenced by visit().
void ir_print_visitor::visit (ir_rvalue * ir) virtual
Reimplemented from ir_visitor.
void ir_print_visitor::visit (ir_variable * ir) virtual
Implements ir_visitor.
References ir_variable::centroid, ir_variable::interpolation, ir_variable::invariant, ir_var_mode_count, ir_variable::mode, print_type(), and ir_variable::type.
void ir_print_visitor::visit (ir_function_signature * ir) virtual
Implements ir_visitor.
References ir_instruction::accept(), ir_variable::accept(), ir_function_signature::body, indent(), ir_function_signature::parameters, print_type(), and ir_function_signature::return_type.
void ir_print_visitor::visit (ir_function * ir) virtual
Implements ir_visitor.
References ir_function_signature::accept(), indent(), and ir_function::name.
void ir_print_visitor::visit (ir_expression * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), ir_expression::get_num_operands(), ir_expression::operands, ir_expression::operator_string(), print_type(), and ir_rvalue::type.
void ir_print_visitor::visit (ir_texture * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), ir_texture::bias, ir_texture::coordinate, ir_texture::grad, ir_lod, ir_tex, ir_txb, ir_txd, ir_txf, ir_txf_ms, ir_txl, ir_txs, ir_texture::lod, ir_texture::lod_info, ir_texture::offset, ir_texture::op, ir_texture::opcode_string(), print_type(), ir_texture::projector, ir_texture::sample_index, ir_texture::sampler, ir_texture::shadow_comparitor, and ir_rvalue::type.
void ir_print_visitor::visit (ir_swizzle * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), ir_swizzle::mask, ir_swizzle_mask::num_components, ir_swizzle::val, ir_swizzle_mask::w, ir_swizzle_mask::x, ir_swizzle_mask::y, and ir_swizzle_mask::z.
void ir_print_visitor::visit (ir_dereference_variable * ir) virtual
Implements ir_visitor.
References ir_dereference_variable::variable_referenced().
void ir_print_visitor::visit (ir_dereference_array * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), ir_dereference_array::array, and ir_dereference_array::array_index.
void ir_print_visitor::visit (ir_dereference_record * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), ir_dereference_record::field, and ir_dereference_record::record.
void ir_print_visitor::visit (ir_assignment * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), ir_assignment::condition, ir_assignment::lhs, ir_assignment::rhs, and ir_assignment::write_mask.
void ir_print_visitor::visit (ir_constant * ir) virtual
Implements ir_visitor.
References ir_constant::accept(), ir_constant_data::b, ir_constant::components, ir_constant_data::f, ir_constant::get_array_element(), GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, exec_node::next, print_type(), ir_rvalue::type, ir_constant_data::u, and ir_constant::value.
void ir_print_visitor::visit (ir_call * ir) virtual
Implements ir_visitor.
References ir_instruction::accept(), ir_dereference_variable::accept(), ir_call::callee_name(), and ir_call::return_deref.
void ir_print_visitor::visit (ir_return * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), and ir_return::get_value().
void ir_print_visitor::visit (ir_discard * ir) virtual
Implements ir_visitor.
References ir_rvalue::accept(), and ir_discard::condition.
void ir_print_visitor::visit (ir_if * ir) virtual
Implements ir_visitor.
References ir_instruction::accept(), ir_rvalue::accept(), ir_if::condition, ir_if::else_instructions, indent(), and ir_if::then_instructions.
void ir_print_visitor::visit (ir_loop * ir) virtual
Implements ir_visitor.
References ir_instruction::accept(), ir_rvalue::accept(), ir_variable::accept(), ir_loop::body_instructions, ir_loop::counter, ir_loop::from, ir_loop::increment, indent(), and ir_loop::to.
void ir_print_visitor::visit (ir_loop_jump * ir) virtual
Implements ir_visitor.
References ir_loop_jump::is_break().
The documentation for this class was generated from the following files:
ir_print_visitor.h
ir_print_visitor.cpp