Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
flatten_named_interface_blocks_declarations Class Reference
Public Member Functions
flatten_named_interface_blocks_declarations (void *mem_ctx)
void run (exec_list *instructions)
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual void handle_rvalue (ir_rvalue **rvalue)
Public Member Functions inherited from ir_rvalue_visitor
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
Data Fields
void *const mem_ctx
hash_table * interface_namespace
Constructor & Destructor Documentation
flatten_named_interface_blocks_declarations::flatten_named_interface_blocks_declarations (void * mem_ctx) inline
Member Function Documentation
void flatten_named_interface_blocks_declarations::handle_rvalue (ir_rvalue ** rvalue) virtual
Implements ir_rvalue_base_visitor.
References ir_dereference_array::array_index, ir_instruction::as_dereference_array(), ir_dereference_record::as_dereference_record(), ir_dereference_record::field, interface_namespace, ir_variable::interface_type, ir_var_uniform, ir_variable::is_interface_instance(), mem_ctx, ir_variable::mode, ralloc_asprintf(), ir_dereference_record::record, and ir_dereference_record::variable_referenced().
Referenced by visit_leave().
void flatten_named_interface_blocks_declarations::run (exec_list * instructions)
References ir_variable::as_variable(), foreach_list_safe, interface_namespace, ir_variable::interface_type, ir_var_uniform, ir_variable::is_interface_instance(), mem_ctx, ir_variable::mode, ir_variable::name, ralloc_asprintf(), ralloc_strdup(), ir_variable::type, and visit_list_elements().
Referenced by lower_named_interface_blocks().
ir_visitor_status flatten_named_interface_blocks_declarations::visit_leave (ir_assignment * ir) virtual
Reimplemented from ir_rvalue_visitor.
References ir_instruction::as_dereference_record(), handle_rvalue(), ir_assignment::lhs, ir_rvalue_base_visitor::rvalue_visit(), and ir_assignment::set_lhs().
Field Documentation
hash_table* flatten_named_interface_blocks_declarations::interface_namespace
Referenced by handle_rvalue(), and run().
void* const flatten_named_interface_blocks_declarations::mem_ctx
Referenced by handle_rvalue(), and run().
The documentation for this class was generated from the following file:
lower_named_interface_blocks.cpp