Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_swizzle Class Reference
Intermediate representation nodes
#include <ir.h>
Public Member Functions
ir_swizzle (ir_rvalue *, unsigned x, unsigned y, unsigned z, unsigned w, unsigned count)
ir_swizzle (ir_rvalue *val, const unsigned *components, unsigned count)
ir_swizzle (ir_rvalue *val, ir_swizzle_mask mask)
virtual ir_swizzle * clone (void *mem_ctx, struct hash_table *) const
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
virtual ir_swizzle * as_swizzle ()
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
bool is_lvalue () const
virtual ir_variable * variable_referenced () const
Get the variable that is ultimately referenced by an r-value.
Public Member Functions inherited from ir_rvalue
virtual ir_rvalue * as_rvalue ()
ir_rvalue * as_rvalue_to_saturate ()
virtual ir_variable * whole_variable_referenced ()
If an r-value is a reference to a whole variable, get that variable.
virtual bool is_zero () const
Determine if an r-value has the value zero.
virtual bool is_one () const
Determine if an r-value has the value one.
virtual bool is_negative_one () const
Determine if an r-value has the value negative one.
virtual bool is_basis () const
Determine if an r-value is a basis vector.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Static Public Member Functions
static ir_swizzle * create (ir_rvalue *, const char *, unsigned vector_length)
Construct an ir_swizzle from the textual representation.
Static Public Member Functions inherited from ir_rvalue
static ir_rvalue * error_value (void *mem_ctx)
Return a generic value of error_type.
Data Fields
ir_rvalue * val
ir_swizzle_mask mask
Data Fields inherited from ir_rvalue
struct glsl_type * type
Data Fields inherited from ir_instruction
enum ir_node_type ir_type
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Additional Inherited Members
Protected Member Functions inherited from ir_rvalue
ir_rvalue ()
Constructor & Destructor Documentation
ir_swizzle::ir_swizzle (ir_rvalue * val, unsigned x, unsigned y, unsigned z, unsigned w, unsigned count)
References ir_instruction::ir_type, and ir_type_swizzle.
Referenced by clone(), and create().
ir_swizzle::ir_swizzle (ir_rvalue * val, const unsigned * components, unsigned count)
References ir_instruction::ir_type, and ir_type_swizzle.
ir_swizzle::ir_swizzle (ir_rvalue * val, ir_swizzle_mask mask)
References ir_instruction::ir_type, ir_type_swizzle, mask, ir_swizzle_mask::num_components, ir_rvalue::type, and val.
Member Function Documentation
virtual void ir_swizzle::accept (ir_visitor * v) inline virtual
Reimplemented from ir_rvalue.
References ir_visitor::visit().
ir_visitor_status ir_swizzle::accept (ir_hierarchical_visitor * v) virtual
Reimplemented from ir_rvalue.
References ir_rvalue::accept(), val, visit_continue, visit_continue_with_parent, ir_hierarchical_visitor::visit_enter(), ir_hierarchical_visitor::visit_leave(), and visit_stop.
virtual ir_swizzle* ir_swizzle::as_swizzle () inline virtual
Reimplemented from ir_instruction.
ir_swizzle * ir_swizzle::clone (void * mem_ctx, struct hash_table * ht) const virtual
Reimplemented from ir_rvalue.
References ir_rvalue::clone(), ir_swizzle(), mask, and val.
ir_constant * ir_swizzle::constant_expression_value (struct hash_table * variable_context = NULL) virtual
Reimplemented from ir_rvalue.
References ir_constant_data::b, ir_rvalue::constant_expression_value(), ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, mask, ir_swizzle_mask::num_components, ralloc_parent(), ir_rvalue::type, ir_constant_data::u, val, ir_constant::value, ir_swizzle_mask::w, ir_swizzle_mask::x, ir_swizzle_mask::y, and ir_swizzle_mask::z.
ir_swizzle * ir_swizzle::create (ir_rvalue * val, const char * str, unsigned vector_length) static
Construct an ir_swizzle from the textual representation.
Can fail.
References I, ir_swizzle(), R, ralloc_parent(), S, and X.
Referenced by _mesa_ast_field_selection_to_hir().
bool ir_swizzle::is_lvalue () const inline virtual
Reimplemented from ir_rvalue.
References ir_swizzle_mask::has_duplicates, and ir_rvalue::is_lvalue().
ir_variable * ir_swizzle::variable_referenced () const virtual
Get the variable that is ultimately referenced by an r-value.
Reimplemented from ir_rvalue.
References val, and ir_rvalue::variable_referenced().
Field Documentation
ir_swizzle_mask ir_swizzle::mask
Referenced by clone(), constant_expression_value(), ir_swizzle(), ir_assignment::set_lhs(), ir_print_visitor::visit(), and ir_validate::visit_leave().
ir_rvalue* ir_swizzle::val
Referenced by accept(), clone(), constant_expression_value(), ir_swizzle(), ir_rvalue_base_visitor::rvalue_visit(), ir_assignment::set_lhs(), variable_referenced(), ir_print_visitor::visit(), ir_vec_index_to_swizzle_visitor::visit_enter(), ir_vec_index_to_cond_assign_visitor::visit_enter(), and ir_validate::visit_leave().
The documentation for this class was generated from the following files:
ir.h
ir.cpp
ir_clone.cpp
ir_constant_expression.cpp
ir_hv_accept.cpp