Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_rvalue_enter_visitor Class Reference
#include <ir_rvalue_visitor.h>
Public Member Functions
virtual ir_visitor_status visit_enter (ir_assignment *)
virtual ir_visitor_status visit_enter (ir_call *)
virtual ir_visitor_status visit_enter (ir_dereference_array *)
virtual ir_visitor_status visit_enter (ir_dereference_record *)
virtual ir_visitor_status visit_enter (ir_expression *)
virtual ir_visitor_status visit_enter (ir_if *)
virtual ir_visitor_status visit_enter (ir_return *)
virtual ir_visitor_status visit_enter (ir_swizzle *)
virtual ir_visitor_status visit_enter (ir_texture *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
virtual void handle_rvalue (ir_rvalue **rvalue)=0
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_if *)
Additional Inherited Members
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Member Function Documentation
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_assignment * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_call * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_dereference_array * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_dereference_record * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_expression * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_return * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_swizzle * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
ir_visitor_status ir_rvalue_enter_visitor::visit_enter (ir_texture * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_rvalue_base_visitor::rvalue_visit().
The documentation for this class was generated from the following files:
ir_rvalue_visitor.h
ir_rvalue_visitor.cpp