Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_hierarchical_visitor Class Reference
Base class of hierarchical visitors of IR instruction trees.
#include <ir_hierarchical_visitor.h>
Public Member Functions
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
Visit methods for leaf-node classes
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
Visit methods for internal-node classes
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Detailed Description
Base class of hierarchical visitors of IR instruction trees.
Hierarchical visitors differ from traditional visitors in a couple of important ways. Rather than having a single visit method for each subclass in the composite, there are three kinds of visit methods. Leaf-node classes have a traditional visit method. Internal-node classes have a visit_enter method, which is invoked just before processing child nodes, and a visit_leave method which is invoked just after processing child nodes.
In addition, each visit method and the accept methods in the composite have a return value which guides the navigation. Any of the visit methods can choose to continue visiting the tree as normal (by returning visit_continue), terminate visiting any further nodes immediately (by returning visit_stop), or stop visiting sibling nodes (by returning visit_continue_with_parent).
These two changes combine to allow nagivation of children to be implemented in the composite's accept method. The accept method for a leaf-node class will simply call the visit method, as usual, and pass its return value on. The accept method for internal-node classes will call the visit_enter method, call the accpet method of each child node, and, finally, call the visit_leave method. If any of these return a value other that visit_continue, the correct action must be taken.
The final benefit is that the hierarchical visitor base class need not be abstract. Default implementations of every visit, visit_enter, and visit_leave method can be provided. By default each of these methods simply returns visit_continue. This allows a significant reduction in derived class code.
For more information about hierarchical visitors, see:
http://c2.com/cgi/wiki?HierarchicalVisitorPattern http://c2.com/cgi/wiki?HierarchicalVisitorDiscussion
Constructor & Destructor Documentation
ir_hierarchical_visitor::ir_hierarchical_visitor ()
References base_ir, callback, data, and in_assignee.
Member Function Documentation
void ir_hierarchical_visitor::run (struct exec_list * instructions)
Utility function to process a linked list of instructions with a visitor.
References visit_list_elements().
Referenced by analyze_loop_variables(), assign_attribute_or_color_locations(), can_inline(), detect_recursion_linked(), detect_recursion_unlinked(), do_dead_code(), do_vec_index_to_swizzle(), fixup_function_calls(), import_prototypes(), link_function_calls(), link_intrastage_shaders(), loop_unroll_count::loop_unroll_count(), set_loop_controls(), unroll_loops(), validate_fragment_shader_executable(), validate_ir_tree(), and validate_vertex_shader_executable().
ir_visitor_status ir_hierarchical_visitor::visit (class ir_rvalue * ir) virtual
References callback, data, and visit_continue.
Referenced by ir_rvalue::accept(), ir_variable::accept(), ir_loop_jump::accept(), ir_dereference_variable::accept(), ir_constant::accept(), and remap_variables().
ir_visitor_status ir_hierarchical_visitor::visit (class ir_variable * ir) virtual
Reimplemented in array_sizing_visitor, ir_array_reference_visitor, lower_clip_distance_visitor, ir_validate, ir_variable_refcount_visitor, and call_link_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit (class ir_constant * ir) virtual
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit (class ir_loop_jump * ir) virtual
Reimplemented in loop_analysis.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit (class ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented in examine_rhs, call_link_visitor, find_deref_visitor, loop_analysis, ir_array_reference_visitor, ir_set_program_inouts_visitor, ir_validate, ir_variable_refcount_visitor, link_uniform_block_active_visitor, and output_read_remover.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_loop * ir) virtual
Reimplemented in loop_analysis, loop_unroll_count, and lower_discard_flow_visitor.
References callback, data, and visit_continue.
Referenced by ir_function_signature::accept(), ir_function::accept(), ir_if::accept(), ir_loop::accept(), ir_assignment::accept(), ir_expression::accept(), ir_call::accept(), ir_return::accept(), ir_discard::accept(), ir_texture::accept(), ir_swizzle::accept(), ir_dereference_array::accept(), and ir_dereference_record::accept().
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_function_signature * ir) virtual
Reimplemented in has_recursion_visitor, ir_array_reference_visitor, import_prototype_visitor, ir_validate, lower_discard_flow_visitor, ir_variable_refcount_visitor, and ir_set_program_inouts_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_function * ir) virtual
Reimplemented in ir_validate, and import_prototype_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_expression * ir) virtual
Reimplemented in loop_unroll_count, ir_rvalue_enter_visitor, ir_vec_index_to_cond_assign_visitor, ir_set_program_inouts_visitor, and ir_vec_index_to_swizzle_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_texture * ir) virtual
Reimplemented in ir_rvalue_enter_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_swizzle * ir) virtual
Reimplemented in ir_rvalue_enter_visitor, ir_vec_index_to_cond_assign_visitor, and ir_vec_index_to_swizzle_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_dereference_array * ir) virtual
Reimplemented in find_variable_index, ir_array_reference_visitor, ir_validate, ir_rvalue_enter_visitor, ir_set_program_inouts_visitor, and link_uniform_block_active_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_dereference_record * ir) virtual
Reimplemented in ir_rvalue_enter_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_assignment * ir) virtual
Reimplemented in loop_analysis, find_assignment_visitor, ir_validate, loop_unroll_count, ir_rvalue_enter_visitor, and ir_vec_index_to_swizzle_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_call * ir) virtual
Reimplemented in fixup_ir_call_visitor, has_recursion_visitor, loop_analysis, find_assignment_visitor, ir_validate, ir_rvalue_enter_visitor, ir_vec_index_to_cond_assign_visitor, call_link_visitor, and ir_vec_index_to_swizzle_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_return * ir) virtual
Reimplemented in ir_rvalue_enter_visitor, ir_vec_index_to_cond_assign_visitor, ir_vec_index_to_swizzle_visitor, and ir_function_can_inline_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_discard * ir) virtual
Reimplemented in lower_discard_flow_visitor, and ir_set_program_inouts_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_enter (class ir_if * ir) virtual
Reimplemented in loop_analysis, ir_rvalue_enter_visitor, ir_if_to_cond_assign_visitor, ir_vec_index_to_cond_assign_visitor, ir_validate, and ir_vec_index_to_swizzle_visitor.
References callback, data, and visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_loop * ir) virtual
Reimplemented in loop_control_visitor, loop_analysis, ir_validate, and loop_unroll_visitor.
References visit_continue.
Referenced by ir_function_signature::accept(), ir_function::accept(), ir_if::accept(), ir_loop::accept(), ir_assignment::accept(), ir_expression::accept(), ir_call::accept(), ir_return::accept(), ir_discard::accept(), ir_texture::accept(), ir_swizzle::accept(), ir_dereference_array::accept(), and ir_dereference_record::accept().
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_function_signature * ir) virtual
Reimplemented in has_recursion_visitor, and output_read_remover.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_function * ir) virtual
Reimplemented in import_prototype_visitor, and ir_validate.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_expression * ir) virtual
Reimplemented in lower_instructions_visitor, ir_validate, and ir_rvalue_visitor.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_texture * ir) virtual
Reimplemented in ir_sampler_replacement_visitor, ir_rvalue_visitor, and lower_texture_projection_visitor.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_swizzle * ir) virtual
Reimplemented in ir_validate, and ir_rvalue_visitor.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_dereference_array * ir) virtual
Reimplemented in ir_sampler_replacement_visitor, and ir_rvalue_visitor.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_dereference_record * ir) virtual
Reimplemented in ir_sampler_replacement_visitor, and ir_rvalue_visitor.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_assignment * ir) virtual
Reimplemented in variable_index_to_cond_assign_visitor, ir_array_splitting_visitor, loop_analysis, flatten_named_interface_blocks_declarations, ir_vec_index_to_cond_assign_visitor, lower_clip_distance_visitor, ir_variable_refcount_visitor, ir_rvalue_visitor, and ir_mat_op_to_vec_visitor.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_call * ir) virtual
Reimplemented in ir_sampler_replacement_visitor, lower_clip_distance_visitor, and ir_rvalue_visitor.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_return * ir) virtual
Reimplemented in ir_rvalue_visitor, and output_read_remover.
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_discard * ir) virtual
References visit_continue.
ir_visitor_status ir_hierarchical_visitor::visit_leave (class ir_if * ir) virtual
Reimplemented in loop_analysis, lower_discard_visitor, ir_if_to_cond_assign_visitor, and ir_rvalue_visitor.
References visit_continue.
Field Documentation
class ir_instruction* ir_hierarchical_visitor::base_ir
Referenced by variable_index_to_cond_assign_visitor::convert_dereference_array(), ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign(), lower_clip_distance_visitor::create_indices(), ir_mat_op_to_vec_visitor::do_equal_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_scalar(), ir_mat_op_to_vec_visitor::do_mul_mat_vec(), ir_mat_op_to_vec_visitor::do_mul_vec_mat(), lower_vector_visitor::handle_rvalue(), ir_expression_flattening_visitor::handle_rvalue(), variable_index_to_cond_assign_visitor::handle_rvalue(), ir_hierarchical_visitor(), ir_mat_op_to_vec_visitor::visit_leave(), lower_texture_projection_visitor::visit_leave(), lower_clip_distance_visitor::visit_leave(), visit_list_elements(), and lower_clip_distance_visitor::visit_new_assignment().
void(* ir_hierarchical_visitor::callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
Warning
Visitor classes derived from ir_hierarchical_visitor may not invoke this function. This can be used, for example, to cause the callback to be invoked on every node type execpt one.
Referenced by ir_hierarchical_visitor(), ir_validate::ir_validate(), visit(), visit_enter(), and visit_tree().
void* ir_hierarchical_visitor::data
Extra data parameter passed to the per-node callback function.
Referenced by ir_hierarchical_visitor(), ir_validate::ir_validate(), ir_validate::visit(), visit(), ir_validate::visit_enter(), visit_enter(), and visit_tree().
bool ir_hierarchical_visitor::in_assignee
Currently in the LHS of an assignment?
This is set and cleared by the ir_assignment::accept method.
Referenced by ir_assignment::accept(), ir_call::accept(), ir_dereference_array::accept(), variable_index_to_cond_assign_visitor::handle_rvalue(), ir_hierarchical_visitor(), ir_rvalue_base_visitor::rvalue_visit(), and loop_analysis::visit().
The documentation for this class was generated from the following files:
ir_hierarchical_visitor.h
ir_hierarchical_visitor.cpp