Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_sampler_replacement_visitor Class Reference
Replaces references to the "sampler" variable with a clone of "deref.".
Public Member Functions
ir_sampler_replacement_visitor (ir_variable *sampler, ir_dereference *deref)
virtual ~ir_sampler_replacement_visitor ()
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_texture *)
void replace_deref (ir_dereference **deref)
void replace_rvalue (ir_rvalue **rvalue)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
ir_variable * sampler
ir_dereference * deref
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Detailed Description
Replaces references to the "sampler" variable with a clone of "deref.".
From the spec, samplers can appear in the tree as function (non-out) parameters and as the result of array indexing and structure field selection. In our builtin implementation, they also appear in the sampler field of an ir_tex instruction.
Constructor & Destructor Documentation
ir_sampler_replacement_visitor::ir_sampler_replacement_visitor (ir_variable * sampler, ir_dereference * deref) inline
References deref, and sampler.
virtual ir_sampler_replacement_visitor::~ir_sampler_replacement_visitor () inline virtual
Member Function Documentation
void ir_sampler_replacement_visitor::replace_deref (ir_dereference ** deref)
References ir_dereference_variable::as_dereference_variable(), ir_dereference::clone(), ralloc_parent(), and ir_dereference_variable::var.
Referenced by replace_rvalue(), and visit_leave().
void ir_sampler_replacement_visitor::replace_rvalue (ir_rvalue ** rvalue)
References ir_dereference::as_dereference(), deref, and replace_deref().
Referenced by visit_leave().
ir_visitor_status ir_sampler_replacement_visitor::visit_leave (ir_call * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References replace_rvalue(), and visit_continue.
ir_visitor_status ir_sampler_replacement_visitor::visit_leave (ir_dereference_array * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_dereference_array::array, replace_rvalue(), and visit_continue.
ir_visitor_status ir_sampler_replacement_visitor::visit_leave (ir_dereference_record * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_dereference_record::record, replace_rvalue(), and visit_continue.
ir_visitor_status ir_sampler_replacement_visitor::visit_leave (ir_texture * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References replace_deref(), ir_texture::sampler, and visit_continue.
Field Documentation
ir_dereference* ir_sampler_replacement_visitor::deref
Referenced by ir_sampler_replacement_visitor(), and replace_rvalue().
ir_variable* ir_sampler_replacement_visitor::sampler
Referenced by ir_sampler_replacement_visitor().
The documentation for this class was generated from the following file:
opt_function_inlining.cpp