Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_instruction Class Reference abstract
Intermediate representation nodes
Base class of all IR instructions.
#include <ir.h>
Public Member Functions
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual void accept (ir_visitor *)=0
virtual ir_visitor_status accept (ir_hierarchical_visitor *)=0
virtual ir_instruction * clone (void *mem_ctx, struct hash_table *ht) const =0
IR instruction downcast functions
These functions either cast the object to a derived class or return NULL if the object's type does not match the specified derived class.
Additional downcast functions will be added as needed.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_rvalue * as_rvalue ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Data Fields
enum ir_node_type ir_type
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Protected Member Functions
ir_instruction ()
Detailed Description
Base class of all IR instructions.
Constructor & Destructor Documentation
virtual ir_instruction::~ir_instruction () inline virtual
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
Because we almost universally use ralloc for our memory management of ir_instructions, the destructor doesn't need to do any work.
ir_instruction::ir_instruction () inline protected
References ir_type, and ir_type_unset.
Member Function Documentation
virtual void ir_instruction::accept (ir_visitor *) pure virtual
Implemented in ir_constant, ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_swizzle, ir_texture, ir_discard, ir_loop_jump, ir_return, ir_call, ir_expression, ir_assignment, ir_loop, ir_if, ir_function, ir_function_signature, ir_variable, and ir_rvalue.
Referenced by dead_code_local_basic_block(), do_expression_flattening(), print(), remap_variables(), ir_print_visitor::visit(), visit_list_elements(), and visit_tree().
virtual ir_visitor_status ir_instruction::accept (ir_hierarchical_visitor *) pure virtual
Implemented in ir_constant, ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_swizzle, ir_texture, ir_discard, ir_loop_jump, ir_return, ir_call, ir_expression, ir_assignment, ir_loop, ir_if, ir_function, ir_function_signature, ir_variable, and ir_rvalue.
virtual class ir_assignment* ir_instruction::as_assignment () inline virtual
Reimplemented in ir_assignment.
Referenced by dead_code_local_basic_block(), find_initial_value(), and move_non_declarations().
virtual class ir_call* ir_instruction::as_call () inline virtual
Reimplemented in ir_call.
Referenced by call_for_basic_blocks(), and move_non_declarations().
virtual class ir_constant* ir_instruction::as_constant () inline virtual
Reimplemented in ir_constant.
Referenced by dereference_component(), emit_inline_vector_constructor(), get_basic_induction_increment(), lower_vector_visitor::handle_rvalue(), is_extended_swizzle(), variable_index_to_cond_assign_visitor::needs_lowering(), ir_array_splitting_visitor::split_deref(), steal_memory(), link_uniform_block_active_visitor::visit_enter(), ir_set_program_inouts_visitor::visit_enter(), ir_array_reference_visitor::visit_enter(), find_variable_index::visit_enter(), ir_validate::visit_leave(), and loop_control_visitor::visit_leave().
virtual class ir_dereference* ir_instruction::as_dereference () inline virtual
Reimplemented in ir_dereference.
Referenced by ir_dereference_array::constant_referenced(), ir_dereference_record::constant_referenced(), do_assignment(), ir_call::generate_inline(), ir_assignment::set_lhs(), ir_mat_op_to_vec_visitor::visit_leave(), and ir_array_splitting_visitor::visit_leave().
virtual class ir_dereference_array* ir_instruction::as_dereference_array () inline virtual
Reimplemented in ir_dereference_array.
Referenced by flatten_named_interface_blocks_declarations::handle_rvalue().
virtual class ir_dereference_record* ir_instruction::as_dereference_record () inline virtual
Reimplemented in ir_dereference_record.
Referenced by flatten_named_interface_blocks_declarations::visit_leave().
virtual class ir_dereference_variable* ir_instruction::as_dereference_variable () inline virtual
Reimplemented in ir_dereference_variable.
Referenced by lower_clip_distance_visitor::handle_rvalue(), mark_whole_array_access(), process_assignment(), ir_array_splitting_visitor::split_deref(), ir_lower_jumps_visitor::visit(), link_uniform_block_active_visitor::visit_enter(), ir_set_program_inouts_visitor::visit_enter(), ir_array_reference_visitor::visit_enter(), ir_mat_op_to_vec_visitor::visit_leave(), lower_clip_distance_visitor::visit_leave(), and loop_control_visitor::visit_leave().
virtual class ir_discard* ir_instruction::as_discard () inline virtual
Reimplemented in ir_discard.
virtual class ir_expression* ir_instruction::as_expression () inline virtual
Reimplemented in ir_expression.
Referenced by ir_rvalue::as_rvalue_to_saturate(), ir_vec_index_to_cond_assign_visitor::convert_vector_extract_to_cond_assign(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), do_assignment(), fix_parameter(), get_basic_induction_increment(), mat_op_to_vec_predicate(), try_max_zero(), try_min_one(), ir_mat_op_to_vec_visitor::visit_leave(), and loop_control_visitor::visit_leave().
virtual class ir_function* ir_instruction::as_function () inline virtual
Reimplemented in ir_function.
Referenced by call_for_basic_blocks(), do_constant_variable_unlinked(), do_dead_code_unlinked(), do_dead_functions(), move_non_declarations(), and populate_symbol_table().
virtual class ir_if* ir_instruction::as_if () inline virtual
Reimplemented in ir_if.
Referenced by call_for_basic_blocks(), ir_lower_jumps_visitor::lower_final_breaks(), move_non_declarations(), ir_lower_jumps_visitor::visit(), and loop_unroll_visitor::visit_leave().
virtual class ir_jump* ir_instruction::as_jump () inline virtual
Reimplemented in ir_jump.
Referenced by call_for_basic_blocks().
virtual class ir_loop* ir_instruction::as_loop () inline virtual
Reimplemented in ir_loop.
Referenced by call_for_basic_blocks().
virtual class ir_return* ir_instruction::as_return () inline virtual
Reimplemented in ir_return.
Referenced by can_inline(), and replace_return_with_assignment().
virtual class ir_rvalue* ir_instruction::as_rvalue () inline virtual
Reimplemented in ir_rvalue.
Referenced by check_node_type(), and ir_call::generate_inline().
virtual class ir_swizzle* ir_instruction::as_swizzle () inline virtual
Reimplemented in ir_swizzle.
Referenced by ir_assignment::set_lhs().
virtual class ir_variable* ir_instruction::as_variable () inline virtual
Reimplemented in ir_variable.
Referenced by ir_function_signature::clone_prototype(), move_non_declarations(), populate_symbol_table(), ir_function_signature::replace_parameters(), and steal_memory().
virtual ir_instruction* ir_instruction::clone (void * mem_ctx, struct hash_table * ht) const pure virtual
Implemented in ir_constant, ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_dereference, ir_swizzle, ir_texture, ir_discard, ir_loop_jump, ir_return, ir_call, ir_expression, ir_assignment, ir_loop, ir_if, ir_function, ir_function_signature, ir_variable, and ir_rvalue.
Referenced by ir_function_signature::clone(), ir_if::clone(), ir_loop::clone(), ir_call::clone(), clone_ir_list(), ir_call::generate_inline(), move_non_declarations(), and call_link_visitor::visit_enter().
void ir_instruction::print (void) const
ir_print_visitor helper for debugging.
References accept().
Referenced by _mesa_print_ir(), check_node_type(), dead_code_local_basic_block(), ir_validate::validate_ir(), ir_validate::visit(), ir_validate::visit_enter(), and ir_validate::visit_leave().
Field Documentation
enum ir_node_type ir_instruction::ir_type
Referenced by _mesa_print_ir(), check_control_flow(), check_node_type(), do_assignment(), find_initial_value(), lower_clip_distance_visitor::fix_lhs(), ir_lower_jumps_visitor::get_jump_strength(), lower_vector_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), ir_assignment::ir_assignment(), ir_call::ir_call(), ir_constant::ir_constant(), ir_dereference_array::ir_dereference_array(), ir_dereference_record::ir_dereference_record(), ir_dereference_variable::ir_dereference_variable(), ir_discard::ir_discard(), ir_expression::ir_expression(), ir_function::ir_function(), ir_function_signature::ir_function_signature(), ir_if::ir_if(), ir_instruction(), ir_jump::ir_jump(), ir_loop::ir_loop(), ir_loop_jump::ir_loop_jump(), ir_return::ir_return(), ir_swizzle::ir_swizzle(), ir_texture::ir_texture(), ir_variable::ir_variable(), is_break(), is_extended_swizzle(), is_loop_terminator(), move_block_to_cond_assign(), verify_parameter_modes(), ir_lower_jumps_visitor::visit(), and ir_validate::visit_enter().
The documentation for this class was generated from the following files:
ir.h
ir_print_visitor.cpp