Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_clip_distance_visitor Class Reference
Public Member Functions
lower_clip_distance_visitor ()
virtual ir_visitor_status visit (ir_variable *)
Replace any declaration of gl_ClipDistance as an array of floats with a declaration of gl_ClipDistanceMESA as an array of vec4's.
void create_indices (ir_rvalue *, ir_rvalue *&, ir_rvalue *&)
Create the necessary GLSL rvalues to index into gl_ClipDistanceMESA based on the rvalue previously used to index into gl_ClipDistance.
virtual ir_visitor_status visit_leave (ir_assignment *)
Replace any assignment having gl_ClipDistance (undereferenced) as its LHS or RHS with a sequence of assignments, one for each component of the array.
void visit_new_assignment (ir_assignment *ir)
Set up base_ir properly and call visit_leave() on a newly created ir_assignment node.
virtual ir_visitor_status visit_leave (ir_call *)
If gl_ClipDistance appears as an argument in an ir_call expression, replace it with a temporary variable, and make sure the ir_call is preceded and/or followed by assignments that copy the contents of the temporary variable to and/or from gl_ClipDistance.
virtual void handle_rvalue (ir_rvalue **rvalue)
void fix_lhs (ir_assignment *)
Public Member Functions inherited from ir_rvalue_visitor
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
Data Fields
bool progress
ir_variable * old_clip_distance_var
Pointer to the declaration of gl_ClipDistance, if found.
ir_variable * new_clip_distance_var
Pointer to the newly-created gl_ClipDistanceMESA variable.
Constructor & Destructor Documentation
lower_clip_distance_visitor::lower_clip_distance_visitor () inline
Member Function Documentation
void lower_clip_distance_visitor::create_indices (ir_rvalue * old_index, ir_rvalue *& array_index, ir_rvalue *& swizzle_index)
Create the necessary GLSL rvalues to index into gl_ClipDistanceMESA based on the rvalue previously used to index into gl_ClipDistance.
Parameters
array_index Selects one of the vec4's in gl_ClipDistanceMESA
swizzle_index Selects a component within the vec4 selected by array_index.
References ir_hierarchical_visitor::base_ir, ir_rvalue::constant_expression_value(), ir_constant::get_int_component(), ir_binop_bit_and, ir_binop_rshift, ir_unop_u2i, ir_var_temporary, ralloc_parent(), and ir_rvalue::type.
Referenced by handle_rvalue().
void lower_clip_distance_visitor::fix_lhs (ir_assignment * ir)
References ir_dereference::clone(), ir_builder::expr(), ir_binop_vector_extract, ir_triop_vector_insert, ir_instruction::ir_type, ir_type_dereference_array, ir_type_expression, ir_assignment::lhs, ir_expression::operands, ir_expression::operation, ralloc_parent(), ir_assignment::rhs, ir_assignment::set_lhs(), ir_rvalue::type, and ir_assignment::write_mask.
Referenced by visit_leave().
void lower_clip_distance_visitor::handle_rvalue (ir_rvalue ** rvalue) virtual
Implements ir_rvalue_base_visitor.
References ir_dereference_array::array, ir_dereference_array::array_index, ir_dereference_array::as_dereference_array(), ir_instruction::as_dereference_variable(), create_indices(), ir_builder::expr(), ir_binop_vector_extract, new_clip_distance_var, old_clip_distance_var, progress, ralloc_parent(), and ir_dereference_variable::var.
Referenced by visit_leave().
ir_visitor_status lower_clip_distance_visitor::visit (ir_variable * ir) virtual
Replace any declaration of gl_ClipDistance as an array of floats with a declaration of gl_ClipDistanceMESA as an array of vec4's.
Reimplemented from ir_hierarchical_visitor.
References ir_variable::clone(), ir_variable::max_array_access, ir_variable::name, new_clip_distance_var, old_clip_distance_var, progress, ralloc_parent(), ralloc_strdup(), ir_variable::type, and visit_continue.
ir_visitor_status lower_clip_distance_visitor::visit_leave (ir_assignment * ir) virtual
Replace any assignment having gl_ClipDistance (undereferenced) as its LHS or RHS with a sequence of assignments, one for each component of the array.
Each of these assignments is lowered to refer to gl_ClipDistanceMESA as appropriate.
Reimplemented from ir_rvalue_visitor.
References ir_instruction::as_dereference_variable(), ir_builder::assign(), ir_hierarchical_visitor::base_ir, ir_rvalue::clone(), ir_dereference::clone(), fix_lhs(), handle_rvalue(), ir_assignment::lhs, old_clip_distance_var, ralloc_parent(), ir_assignment::rhs, ir_rvalue_base_visitor::rvalue_visit(), ir_variable::type, ir_dereference_variable::var, and visit_continue.
ir_visitor_status lower_clip_distance_visitor::visit_leave (ir_call * ir) virtual
If gl_ClipDistance appears as an argument in an ir_call expression, replace it with a temporary variable, and make sure the ir_call is preceded and/or followed by assignments that copy the contents of the temporary variable to and/or from gl_ClipDistance.
Each of these assignments is then lowered to refer to gl_ClipDistanceMESA.
Reimplemented from ir_rvalue_visitor.
References ir_call::actual_parameters, ir_instruction::as_dereference_variable(), ir_hierarchical_visitor::base_ir, ir_call::callee, exec_list::head, ir_var_function_in, ir_var_function_inout, ir_var_function_out, ir_var_temporary, ir_variable::mode, exec_node::next, old_clip_distance_var, ir_function_signature::parameters, ralloc_parent(), ir_rvalue_base_visitor::rvalue_visit(), ir_rvalue::type, ir_dereference_variable::var, and visit_new_assignment().
void lower_clip_distance_visitor::visit_new_assignment (ir_assignment * ir)
Set up base_ir properly and call visit_leave() on a newly created ir_assignment node.
This is used in cases where we have to insert an ir_assignment in a place where we know the hierarchical visitor won't see it.
References ir_assignment::accept(), and ir_hierarchical_visitor::base_ir.
Referenced by visit_leave().
Field Documentation
ir_variable* lower_clip_distance_visitor::new_clip_distance_var
Pointer to the newly-created gl_ClipDistanceMESA variable.
Referenced by handle_rvalue(), lower_clip_distance(), and visit().
ir_variable* lower_clip_distance_visitor::old_clip_distance_var
Pointer to the declaration of gl_ClipDistance, if found.
Referenced by handle_rvalue(), visit(), and visit_leave().
bool lower_clip_distance_visitor::progress
Referenced by handle_rvalue(), lower_clip_distance(), and visit().
The documentation for this class was generated from the following file:
lower_clip_distance.cpp