Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
tfeedback_decl Class Reference
Data structure tracking information about a transform feedback declaration during linking.
#include <link_varyings.h>
Public Member Functions
void init (struct gl_context *ctx, struct gl_shader_program *prog, const void *mem_ctx, const char *input)
Initialize this object based on a string that was passed to glTransformFeedbackVaryings.
bool assign_location (struct gl_context *ctx, struct gl_shader_program *prog)
Assign a location for this tfeedback_decl object based on the transform feedback candidate found by find_candidate.
unsigned get_num_outputs () const
bool store (struct gl_context *ctx, struct gl_shader_program *prog, struct gl_transform_feedback_info *info, unsigned buffer, const unsigned max_outputs) const
Update gl_transform_feedback_info to reflect this tfeedback_decl.
const tfeedback_candidate * find_candidate (gl_shader_program *prog, hash_table *tfeedback_candidates)
bool is_next_buffer_separator () const
bool is_varying () const
unsigned num_components () const
The total number of varying components taken up by this variable.
Static Public Member Functions
static bool is_same (const tfeedback_decl &x, const tfeedback_decl &y)
Determine whether two tfeedback_decl objects refer to the same variable and array index (if applicable).
Detailed Description
Data structure tracking information about a transform feedback declaration during linking.
Member Function Documentation
bool tfeedback_decl::assign_location (struct gl_context * ctx, struct gl_shader_program * prog)
Assign a location for this tfeedback_decl object based on the transform feedback candidate found by find_candidate.
If an error occurs, the error is reported through linker_error() and false is returned.
References is_varying(), linker_error(), ir_variable::location, ir_variable::location_frac, tfeedback_candidate::offset, tfeedback_candidate::toplevel_var, and tfeedback_candidate::type.
const tfeedback_candidate * tfeedback_decl::find_candidate (gl_shader_program * prog, hash_table * tfeedback_candidates)
References linker_error().
Referenced by assign_varying_locations().
unsigned tfeedback_decl::get_num_outputs () const
References is_varying(), and num_components().
void tfeedback_decl::init (struct gl_context * ctx, struct gl_shader_program * prog, const void * mem_ctx, const char * input)
Initialize this object based on a string that was passed to glTransformFeedbackVaryings.
If the input is mal-formed, this call still succeeds, but it sets this->var_name to a mal-formed input, so tfeedback_decl::find_output_var() will fail to find any matching variable.
References parse_program_resource_name(), and ralloc_strndup().
Referenced by parse_tfeedback_decls().
bool tfeedback_decl::is_next_buffer_separator () const inline
bool tfeedback_decl::is_same (const tfeedback_decl & x, const tfeedback_decl & y) static
Determine whether two tfeedback_decl objects refer to the same variable and array index (if applicable).
References is_varying().
Referenced by parse_tfeedback_decls().
bool tfeedback_decl::is_varying () const inline
Referenced by assign_location(), get_num_outputs(), and is_same().
unsigned tfeedback_decl::num_components () const inline
The total number of varying components taken up by this variable.
Only valid if assign_location() has been called.
Referenced by get_num_outputs(), and store().
bool tfeedback_decl::store (struct gl_context * ctx, struct gl_shader_program * prog, struct gl_transform_feedback_info * info, unsigned buffer, const unsigned max_outputs) const
Update gl_transform_feedback_info to reflect this tfeedback_decl.
If an error occurs, the error is reported through linker_error() and false is returned.
References linker_error(), num_components(), and ralloc_strdup().
The documentation for this class was generated from the following files:
link_varyings.h
link_varyings.cpp