Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_rvalue_base_visitor Class Reference abstract
#include <ir_rvalue_visitor.h>
Public Member Functions
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
virtual void handle_rvalue (ir_rvalue **rvalue)=0
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Additional Inherited Members
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Member Function Documentation
virtual void ir_rvalue_base_visitor::handle_rvalue (ir_rvalue ** rvalue) pure virtual
Implemented in variable_index_to_cond_assign_visitor, ir_array_splitting_visitor, deref_replacer, flatten_named_interface_blocks_declarations, lower_clip_distance_visitor, ir_expression_flattening_visitor, vector_insert_visitor, lower_noise_visitor, and lower_vector_visitor.
Referenced by rvalue_visit().
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_assignment * ir)
References ir_assignment::condition, handle_rvalue(), ir_assignment::rhs, and visit_continue.
Referenced by ir_rvalue_enter_visitor::visit_enter(), ir_rvalue_visitor::visit_leave(), lower_clip_distance_visitor::visit_leave(), and flatten_named_interface_blocks_declarations::visit_leave().
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_call * ir)
References handle_rvalue(), and visit_continue.
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_dereference_array * ir)
References ir_dereference_array::array, ir_dereference_array::array_index, handle_rvalue(), ir_hierarchical_visitor::in_assignee, and visit_continue.
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_dereference_record * ir)
References handle_rvalue(), ir_dereference_record::record, and visit_continue.
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_expression * ir)
References ir_expression::get_num_operands(), handle_rvalue(), ir_expression::operands, and visit_continue.
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_if * ir)
References ir_if::condition, handle_rvalue(), and visit_continue.
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_return * ir)
References handle_rvalue(), ir_return::value, and visit_continue.
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_swizzle * ir)
References handle_rvalue(), ir_swizzle::val, and visit_continue.
ir_visitor_status ir_rvalue_base_visitor::rvalue_visit (ir_texture * ir)
References ir_texture::bias, ir_texture::coordinate, ir_texture::grad, handle_rvalue(), ir_lod, ir_tex, ir_txb, ir_txd, ir_txf, ir_txf_ms, ir_txl, ir_txs, ir_texture::lod, ir_texture::lod_info, ir_texture::offset, ir_texture::op, ir_texture::projector, ir_texture::sample_index, ir_texture::shadow_comparitor, and visit_continue.
The documentation for this class was generated from the following files:
ir_rvalue_visitor.h
ir_rvalue_visitor.cpp