Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
varying_matches Class Reference
Data structure recording the relationship between outputs of one shader stage (the "producer") and inputs of another (the "consumer").
Public Member Functions
varying_matches (bool disable_varying_packing, bool consumer_is_fs)
~varying_matches ()
void record (ir_variable *producer_var, ir_variable *consumer_var)
Record the given producer/consumer variable pair in the list of variables that should later be assigned locations.
unsigned assign_locations ()
Choose locations for all of the variable matches that were previously passed to varying_matches::record().
void store_locations (unsigned producer_base, unsigned consumer_base) const
Update the producer and consumer shaders to reflect the locations assignments that were made by varying_matches::assign_locations().
Detailed Description
Data structure recording the relationship between outputs of one shader stage (the "producer") and inputs of another (the "consumer").
Constructor & Destructor Documentation
varying_matches::varying_matches (bool disable_varying_packing, bool consumer_is_fs)
varying_matches::~varying_matches ()
Member Function Documentation
unsigned varying_matches::assign_locations ()
Choose locations for all of the variable matches that were previously passed to varying_matches::record().
Referenced by assign_varying_locations().
void varying_matches::record (ir_variable * producer_var, ir_variable * consumer_var)
Record the given producer/consumer variable pair in the list of variables that should later be assigned locations.
It is permissible for consumer_var to be NULL (this happens if a variable is output by the producer and consumed by transform feedback, but not consumed by the consumer).
If producer_var has already been paired up with a consumer_var, or producer_var is part of fixed pipeline functionality (and hence already has a location assigned), this function has no effect.
Note: as a side effect this function may change the interpolation type of producer_var, but only when the change couldn't possibly affect rendering.
References ir_variable::centroid, ir_variable::interpolation, ir_variable::is_unmatched_generic_inout, and ir_variable::type.
Referenced by assign_varying_locations().
void varying_matches::store_locations (unsigned producer_base, unsigned consumer_base) const
Update the producer and consumer shaders to reflect the locations assignments that were made by varying_matches::assign_locations().
References ir_variable::location, and ir_variable::location_frac.
Referenced by assign_varying_locations().
The documentation for this class was generated from the following file:
link_varyings.cpp