Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_struct_specifier Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_struct_specifier (const char *identifier, ast_declarator_list *declarator_list)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
Data Fields
const char * name
exec_list declarations
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned line
Line number within the source string.
unsigned column
Column in the line.
} location
exec_node link
Additional Inherited Members
Static Public Member Functions inherited from ast_node
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_struct_specifier::ast_struct_specifier (const char * identifier, ast_declarator_list * declarator_list)
References declarations, ast_node::link, name, and ralloc_asprintf().
Member Function Documentation
ir_rvalue * ast_struct_specifier::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), ast_process_structure_or_interface_block(), declarations, ast_node::get_location(), name, and reralloc.
Referenced by ast_type_specifier::hir().
void ast_struct_specifier::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References declarations, exec_node_data, foreach_list_const, ast_node::link, name, and ast_node::print().
Referenced by ast_type_specifier::print().
Field Documentation
exec_list ast_struct_specifier::declarations
Referenced by ast_struct_specifier(), hir(), and print().
const char* ast_struct_specifier::name
Referenced by ast_struct_specifier(), hir(), and print().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp