Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
loop_control_visitor Class Reference
Public Member Functions
loop_control_visitor (loop_state *state)
virtual ir_visitor_status visit_leave (ir_loop *ir)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
loop_state * state
bool progress
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
loop_control_visitor::loop_control_visitor (loop_state * state) inline
References progress, and state.
Member Function Documentation
ir_visitor_status loop_control_visitor::visit_leave (ir_loop * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_instruction::as_constant(), ir_instruction::as_dereference_variable(), ir_instruction::as_expression(), calculate_iterations(), ir_rvalue::clone(), ir_constant::clone(), ir_loop::cmp, ir_if::condition, ir_loop::counter, find_initial_value(), foreach_list, ir_loop::from, loop_state::get(), loop_variable::increment, ir_loop::increment, loop_variable_state::induction_variables, loop_terminator::ir, ir_binop_gequal, ir_binop_greater, ir_binop_lequal, ir_binop_less, loop_variable_state::max_iterations, loop_variable_state::num_loop_jumps, ir_expression::operands, ir_expression::operation, progress, state, loop_variable_state::terminators, ir_loop::to, loop_variable::var, ir_rvalue::variable_referenced(), and visit_continue.
Field Documentation
bool loop_control_visitor::progress
Referenced by loop_control_visitor(), set_loop_controls(), and visit_leave().
loop_state* loop_control_visitor::state
Referenced by loop_control_visitor(), and visit_leave().
The documentation for this class was generated from the following file:
loop_controls.cpp