Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_if_to_cond_assign_visitor Class Reference
Public Member Functions
ir_if_to_cond_assign_visitor (unsigned max_depth)
~ir_if_to_cond_assign_visitor ()
ir_visitor_status visit_enter (ir_if *)
ir_visitor_status visit_leave (ir_if *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
Data Fields
bool progress
unsigned max_depth
unsigned depth
struct hash_table * condition_variables
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
ir_if_to_cond_assign_visitor::ir_if_to_cond_assign_visitor (unsigned max_depth) inline
References condition_variables, depth, max_depth, and progress.
ir_if_to_cond_assign_visitor::~ir_if_to_cond_assign_visitor () inline
References condition_variables.
Member Function Documentation
ir_visitor_status ir_if_to_cond_assign_visitor::visit_enter (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References depth, and visit_continue.
ir_visitor_status ir_if_to_cond_assign_visitor::visit_leave (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_builder::assign(), check_control_flow(), ir_dereference_variable::clone(), ir_if::condition, condition_variables, depth, ir_if::else_instructions, ir_unop_logic_not, ir_var_temporary, max_depth, move_block_to_cond_assign(), progress, ralloc_parent(), ir_if::then_instructions, visit_continue, and visit_tree().
Field Documentation
struct hash_table* ir_if_to_cond_assign_visitor::condition_variables
Referenced by ir_if_to_cond_assign_visitor(), visit_leave(), and ~ir_if_to_cond_assign_visitor().
unsigned ir_if_to_cond_assign_visitor::depth
Referenced by ir_if_to_cond_assign_visitor(), visit_enter(), and visit_leave().
unsigned ir_if_to_cond_assign_visitor::max_depth
Referenced by ir_if_to_cond_assign_visitor(), and visit_leave().
bool ir_if_to_cond_assign_visitor::progress
Referenced by ir_if_to_cond_assign_visitor(), lower_if_to_cond_assign(), and visit_leave().
The documentation for this class was generated from the following file:
lower_if_to_cond_assign.cpp