Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_reader Class Reference
Public Member Functions
ir_reader (_mesa_glsl_parse_state *)
void read (exec_list *instructions, const char *src, bool scan_for_protos)
Constructor & Destructor Documentation
ir_reader::ir_reader (_mesa_glsl_parse_state * state)
Member Function Documentation
void ir_reader::read (exec_list * instructions, const char * src, bool scan_for_protos)
References debug, ir_builder::expr(), ralloc_context(), ralloc_free(), s_expression::read_expression(), and validate_ir_tree().
Referenced by _mesa_glsl_read_ir().
The documentation for this class was generated from the following file:
ir_reader.cpp