Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_function Class Reference
Intermediate representation nodes
Header for tracking multiple overloaded functions with the same name.
#include <ir.h>
Public Member Functions
ir_function (const char *name)
virtual ir_function * clone (void *mem_ctx, struct hash_table *ht) const
virtual ir_function * as_function ()
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
void add_signature (ir_function_signature *sig)
exec_list_iterator iterator ()
Get an iterator for the set of function signatures.
ir_function_signature * matching_signature (const exec_list *actual_param, bool *match_is_exact)
Find a signature that matches a set of actual parameters, taking implicit conversions into account.
ir_function_signature * matching_signature (const exec_list *actual_param)
Find a signature that matches a set of actual parameters, taking implicit conversions into account.
ir_function_signature * exact_matching_signature (const exec_list *actual_ps)
Find a signature that exactly matches a set of actual parameters without any implicit type conversions.
bool has_user_signature ()
Whether or not this function has a signature that isn't a built-in.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_rvalue * as_rvalue ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Data Fields
const char * name
Name of the function.
struct exec_list signatures
List of ir_function_signature for each overloaded function with this name.
Data Fields inherited from ir_instruction
enum ir_node_type ir_type
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Additional Inherited Members
Protected Member Functions inherited from ir_instruction
ir_instruction ()
Detailed Description
Header for tracking multiple overloaded functions with the same name.
Contains a list of ir_function_signatures representing each of the actual functions.
Constructor & Destructor Documentation
ir_function::ir_function (const char * name)
References ir_instruction::ir_type, ir_type_function, and ralloc_strdup().
Referenced by clone().
Member Function Documentation
virtual void ir_function::accept (ir_visitor * v) inline virtual
Implements ir_instruction.
References ir_visitor::visit().
ir_visitor_status ir_function::accept (ir_hierarchical_visitor * v) virtual
Implements ir_instruction.
References signatures, visit_continue, visit_continue_with_parent, ir_hierarchical_visitor::visit_enter(), ir_hierarchical_visitor::visit_leave(), visit_list_elements(), and visit_stop.
void ir_function::add_signature (ir_function_signature * sig) inline
References signatures.
Referenced by clone(), ast_function::hir(), match_function_by_name(), and call_link_visitor::visit_enter().
virtual ir_function* ir_function::as_function () inline virtual
Reimplemented from ir_instruction.
Referenced by link_intrastage_shaders().
ir_function * ir_function::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_instruction.
References add_signature(), ir_function_signature::clone(), copy(), foreach_list_const, ir_function(), name, and signatures.
ir_function_signature * ir_function::exact_matching_signature (const exec_list * actual_ps)
Find a signature that exactly matches a set of actual parameters without any implicit type conversions.
References parameter_lists_match_exact(), ir_function_signature::parameters, and signatures.
Referenced by ast_function::hir(), link_intrastage_shaders(), and call_link_visitor::visit_enter().
bool ir_function::has_user_signature ()
Whether or not this function has a signature that isn't a built-in.
References foreach_list, ir_function_signature::is_builtin, and signatures.
Referenced by ast_function::hir(), and match_function_by_name().
exec_list_iterator ir_function::iterator () inline
Get an iterator for the set of function signatures.
References signatures.
ir_function_signature * ir_function::matching_signature (const exec_list * actual_param, bool * match_is_exact)
Find a signature that matches a set of actual parameters, taking implicit conversions into account.
Also flags whether the match was exact.
References PARAMETER_LIST_EXACT_MATCH, PARAMETER_LIST_INEXACT_MATCH, PARAMETER_LIST_NO_MATCH, parameter_lists_match(), ir_function_signature::parameters, and signatures.
Referenced by find_matching_signature(), get_main_function_signature(), lower_packed_varyings(), match_function_by_name(), and matching_signature().
ir_function_signature * ir_function::matching_signature (const exec_list * actual_param)
Find a signature that matches a set of actual parameters, taking implicit conversions into account.
References matching_signature().
Field Documentation
const char* ir_function::name
Name of the function.
Referenced by glsl_symbol_table::add_function(), glsl_symbol_table::add_global_function(), clone(), ir_function_signature::function_name(), link_intrastage_shaders(), no_matching_function_error(), ir_print_visitor::visit(), import_prototype_visitor::visit_enter(), ir_validate::visit_enter(), and ir_validate::visit_leave().
struct exec_list ir_function::signatures
List of ir_function_signature for each overloaded function with this name.
Referenced by accept(), add_signature(), clone(), do_dead_functions(), exact_matching_signature(), has_user_signature(), iterator(), matching_signature(), no_matching_function_error(), ir_lower_jumps_visitor::visit(), and ir_validate::visit_enter().
The documentation for this class was generated from the following files:
ir.h
ir.cpp
ir_clone.cpp
ir_function.cpp
ir_hv_accept.cpp