Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_call Class Reference
Intermediate representation nodes
HIR instruction representing a high-level function call, containing a list of parameters and returning a value in the supplied temporary.
#include <ir.h>
Public Member Functions
ir_call (ir_function_signature *callee, ir_dereference_variable *return_deref, exec_list *actual_parameters)
virtual ir_call * clone (void *mem_ctx, struct hash_table *ht) const
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
virtual ir_call * as_call ()
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
exec_list_iterator iterator ()
Get an iterator for the set of acutal parameters.
const char * callee_name () const
Get the name of the function being called.
void generate_inline (ir_instruction *ir)
Generates an inline version of the function before , storing the return value in return_deref.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_rvalue * as_rvalue ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Data Fields
ir_dereference_variable * return_deref
Storage for the function's return value.
ir_function_signature * callee
The specific function signature being called.
exec_list actual_parameters
bool use_builtin
Should this call only bind to a built-in function?
Data Fields inherited from ir_instruction
enum ir_node_type ir_type
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Additional Inherited Members
Protected Member Functions inherited from ir_instruction
ir_instruction ()
Detailed Description
HIR instruction representing a high-level function call, containing a list of parameters and returning a value in the supplied temporary.
Constructor & Destructor Documentation
ir_call::ir_call (ir_function_signature * callee, ir_dereference_variable * return_deref, exec_list * actual_parameters) inline
References ir_instruction::ir_type, ir_type_call, ir_function_signature::is_builtin, ir_function_signature::return_type, and use_builtin.
Referenced by clone().
Member Function Documentation
virtual void ir_call::accept (ir_visitor * v) inline virtual
Implements ir_instruction.
References ir_visitor::visit().
ir_visitor_status ir_call::accept (ir_hierarchical_visitor * v) virtual
Implements ir_instruction.
References ir_dereference_variable::accept(), actual_parameters, ir_hierarchical_visitor::in_assignee, return_deref, visit_continue, visit_continue_with_parent, ir_hierarchical_visitor::visit_enter(), ir_hierarchical_visitor::visit_leave(), visit_list_elements(), and visit_stop.
virtual ir_call* ir_call::as_call () inline virtual
Reimplemented from ir_instruction.
const char* ir_call::callee_name () const inline
Get the name of the function being called.
References callee, and ir_function_signature::function_name().
Referenced by ir_print_visitor::visit().
ir_call * ir_call::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_instruction.
References actual_parameters, callee, ir_instruction::clone(), ir_dereference_variable::clone(), ir_call(), and return_deref.
ir_constant * ir_call::constant_expression_value (struct hash_table * variable_context = NULL) virtual
References actual_parameters, callee, and ir_function_signature::constant_expression_value().
void ir_call::generate_inline (ir_instruction * ir)
Generates an inline version of the function before , storing the return value in return_deref.
References actual_parameters, ir_instruction::as_dereference(), ir_instruction::as_rvalue(), ir_builder::assign(), ir_function_signature::body, callee, ir_instruction::clone(), ir_variable::clone(), do_sampler_replacement(), GLSL_TYPE_SAMPLER, ir_var_auto, ir_var_const_in, ir_var_function_in, ir_var_function_inout, ir_var_function_out, ir_variable::mode, exec_node::next, ir_function_signature::parameters, ralloc_parent(), ir_variable::read_only, replace_return_with_assignment(), return_deref, ir_variable::type, and visit_tree().
exec_list_iterator ir_call::iterator () inline
Get an iterator for the set of acutal parameters.
References actual_parameters.
Field Documentation
exec_list ir_call::actual_parameters
Referenced by accept(), clone(), constant_expression_value(), generate_inline(), iterator(), call_link_visitor::visit_enter(), ir_validate::visit_enter(), and lower_clip_distance_visitor::visit_leave().
ir_function_signature* ir_call::callee
The specific function signature being called.
Referenced by callee_name(), can_inline(), clone(), constant_expression_value(), generate_inline(), call_link_visitor::visit_enter(), ir_validate::visit_enter(), find_assignment_visitor::visit_enter(), has_recursion_visitor::visit_enter(), fixup_ir_call_visitor::visit_enter(), and lower_clip_distance_visitor::visit_leave().
ir_dereference_variable* ir_call::return_deref
Storage for the function's return value.
This must be NULL if the return type is void.
Referenced by accept(), clone(), generate_inline(), ir_print_visitor::visit(), ir_validate::visit_enter(), and find_assignment_visitor::visit_enter().
bool ir_call::use_builtin
Should this call only bind to a built-in function?
Referenced by ir_call(), and call_link_visitor::visit_enter().
The documentation for this class was generated from the following files:
ir.h
ir_clone.cpp
ir_constant_expression.cpp
ir_hv_accept.cpp
opt_function_inlining.cpp