Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_function Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_function (void)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
Data Fields
ast_fully_specified_type * return_type
const char * identifier
exec_list parameters
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned line
Line number within the source string.
unsigned column
Column in the line.
} location
exec_node link
Friends
class ast_function_definition
Additional Inherited Members
Static Public Member Functions inherited from ast_node
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_function::ast_function (void)
Member Function Documentation
ir_rvalue * ast_function::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), ir_function::add_signature(), emit_function(), ir_function::exact_matching_signature(), ast_node::get_location(), ast_type_specifier::glsl_type(), ir_function::has_user_signature(), identifier, ir_function_signature::is_defined, parameters, ast_parameter_declarator::parameters_to_hir(), ir_function_signature::qualifiers_match(), ir_function_signature::replace_parameters(), return_type, ir_function_signature::return_type, and ast_fully_specified_type::specifier.
Referenced by ast_function_definition::hir().
void ast_function::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References exec_node_data, foreach_list_const, identifier, ast_node::link, parameters, ast_node::print(), ast_fully_specified_type::print(), and return_type.
Referenced by ast_function_definition::print().
Friends And Related Function Documentation
friend class ast_function_definition friend
Field Documentation
const char* ast_function::identifier
Referenced by hir(), and print().
exec_list ast_function::parameters
Referenced by hir(), and print().
ast_fully_specified_type* ast_function::return_type
Referenced by hir(), and print().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp