Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_set_program_inouts_visitor Class Reference
Public Member Functions
ir_set_program_inouts_visitor (struct gl_program *prog, bool is_fragment_shader)
~ir_set_program_inouts_visitor ()
virtual ir_visitor_status visit_enter (ir_dereference_array *)
virtual ir_visitor_status visit_enter (ir_function_signature *)
virtual ir_visitor_status visit_enter (ir_expression *)
virtual ir_visitor_status visit_enter (ir_discard *)
virtual ir_visitor_status visit (ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
struct gl_program * prog
bool is_fragment_shader
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
ir_set_program_inouts_visitor::ir_set_program_inouts_visitor (struct gl_program * prog, bool is_fragment_shader) inline
References is_fragment_shader, and prog.
ir_set_program_inouts_visitor::~ir_set_program_inouts_visitor () inline
Member Function Documentation
ir_visitor_status ir_set_program_inouts_visitor::visit (ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References is_shader_inout(), mark(), prog, ir_rvalue::type, ir_dereference_variable::var, and visit_continue.
ir_visitor_status ir_set_program_inouts_visitor::visit_enter (ir_dereference_array * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_dereference_array::array, ir_dereference_array::array_index, ir_instruction::as_constant(), ir_instruction::as_dereference_variable(), ir_constant_data::i, is_shader_inout(), mark(), prog, ir_rvalue::type, ir_constant::value, ir_dereference_variable::var, visit_continue, and visit_continue_with_parent.
ir_visitor_status ir_set_program_inouts_visitor::visit_enter (ir_function_signature * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_function_signature::body, visit_continue_with_parent, and visit_list_elements().
ir_visitor_status ir_set_program_inouts_visitor::visit_enter (ir_expression * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_unop_dFdy, is_fragment_shader, ir_expression::operation, prog, and visit_continue.
ir_visitor_status ir_set_program_inouts_visitor::visit_enter (ir_discard *) virtual
Reimplemented from ir_hierarchical_visitor.
References is_fragment_shader, prog, and visit_continue.
Field Documentation
bool ir_set_program_inouts_visitor::is_fragment_shader
Referenced by ir_set_program_inouts_visitor(), and visit_enter().
struct gl_program* ir_set_program_inouts_visitor::prog
Referenced by ir_set_program_inouts_visitor(), visit(), and visit_enter().
The documentation for this class was generated from the following file:
ir_set_program_inouts.cpp