Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
program_resource_visitor Class Reference abstract
Class for processing all of the leaf fields of a variable that corresponds to a program resource.
#include <linker.h>
Public Member Functions
void process (ir_variable *var)
Begin processing a variable.
void process (const glsl_type *type, const char *name)
Begin processing a variable of a structured type.
Protected Member Functions
virtual void visit_field (const glsl_type *type, const char *name, bool row_major)=0
Method invoked for each leaf of the variable.
virtual void visit_field (const glsl_struct_field *field)
Visit a record before visiting its fields.
Detailed Description
Class for processing all of the leaf fields of a variable that corresponds to a program resource.
The leaf fields are all the parts of the variable that the application could query using glGetProgramResourceIndex (or that could be returned by glGetProgramResourceName).
Classes my derive from this class to implement specific functionality. This class only provides the mechanism to iterate over the leaves. Derived classes must implement ::visit_field and may override ::process.
Member Function Documentation
void program_resource_visitor::process (ir_variable * var)
Begin processing a variable.
Classes that overload this function should call ::process from the base class to start the recursive processing of the variable.
Parameters
var The variable that is to be processed
Calls ::visit_field for each leaf of the variable.
Warning
When processing a uniform block, this entry should only be used in cases where the row / column ordering of matrices in the block does not matter. For example, enumerating the names of members of the block, but not for determining the offsets of members.
References ir_variable::name, ralloc_free(), ralloc_strdup(), ir_variable::type, and visit_field().
Referenced by link_uniform_blocks(), ubo_visitor::process(), count_uniform_size::process(), tfeedback_candidate_generator::process(), and parcel_out_uniform_storage::set_and_process().
void program_resource_visitor::process (const glsl_type * type, const char * name)
Begin processing a variable of a structured type.
This flavor of process should be used to handle structured types (i.e., structures, interfaces, or arrays there of) that need special name handling. A common usage is to handle cases where the block name (instead of the instance name) is used for an interface block.
Parameters
type Type that is to be processed, associated with name
name Base name of the structured variable being processed
Note
type must be GLSL_TYPE_RECORD, GLSL_TYPE_INTERFACE, or an array there of.
References ralloc_free(), and ralloc_strdup().
virtual void program_resource_visitor::visit_field (const glsl_type * type, const char * name, bool row_major) protected pure virtual
Method invoked for each leaf of the variable.
Parameters
type Type of the field.
name Fully qualified name of the field.
row_major For a matrix type, is it stored row-major.
Referenced by process().
void program_resource_visitor::visit_field (const glsl_struct_field * field) protected virtual
Visit a record before visiting its fields.
For structures-of-structures or interfaces-of-structures, this visits the inner structure before visiting its fields.
The default implementation does nothing.
The documentation for this class was generated from the following files:
linker.h
link_uniforms.cpp