Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_fully_specified_type Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
bool has_qualifiers () const
Public Member Functions inherited from ast_node
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
Data Fields
ast_type_qualifier qualifier
ast_type_specifier * specifier
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned line
Line number within the source string.
unsigned column
Column in the line.
} location
exec_node link
Additional Inherited Members
Static Public Member Functions inherited from ast_node
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Member Function Documentation
bool ast_fully_specified_type::has_qualifiers () const
References ast_type_qualifier::flags, ast_type_qualifier::i, and qualifier.
void ast_fully_specified_type::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References _mesa_ast_type_qualifier_print(), ast_type_specifier::print(), qualifier, and specifier.
Referenced by ast_declarator_list::print(), ast_parameter_declarator::print(), and ast_function::print().
Field Documentation
ast_type_qualifier ast_fully_specified_type::qualifier
Referenced by has_qualifiers(), ast_declarator_list::hir(), print(), and process_initializer().
ast_type_specifier* ast_fully_specified_type::specifier
Referenced by ast_declarator_list::hir(), ast_function::hir(), and print().
The documentation for this class was generated from the following files:
ast.h
ast_type.cpp
glsl_parser_extras.cpp