Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
variable_index_to_cond_assign_visitor Class Reference
Visitor class for replacing expressions with ir_constant values.
Public Member Functions
variable_index_to_cond_assign_visitor (bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform)
bool storage_type_needs_lowering (ir_dereference_array *deref) const
bool needs_lowering (ir_dereference_array *deref) const
ir_variable * convert_dereference_array (ir_dereference_array *orig_deref, ir_assignment *orig_assign, ir_dereference *orig_base)
virtual void handle_rvalue (ir_rvalue **pir)
ir_visitor_status visit_leave (ir_assignment *ir)
Public Member Functions inherited from ir_rvalue_visitor
virtual ir_visitor_status visit_leave (ir_call *)
virtual ir_visitor_status visit_leave (ir_dereference_array *)
virtual ir_visitor_status visit_leave (ir_dereference_record *)
virtual ir_visitor_status visit_leave (ir_expression *)
virtual ir_visitor_status visit_leave (ir_if *)
virtual ir_visitor_status visit_leave (ir_return *)
virtual ir_visitor_status visit_leave (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_texture *)
Public Member Functions inherited from ir_rvalue_base_visitor
ir_visitor_status rvalue_visit (ir_assignment *)
ir_visitor_status rvalue_visit (ir_call *)
ir_visitor_status rvalue_visit (ir_dereference_array *)
ir_visitor_status rvalue_visit (ir_dereference_record *)
ir_visitor_status rvalue_visit (ir_expression *)
ir_visitor_status rvalue_visit (ir_if *)
ir_visitor_status rvalue_visit (ir_return *)
ir_visitor_status rvalue_visit (ir_swizzle *)
ir_visitor_status rvalue_visit (ir_texture *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
Data Fields
bool progress
bool lower_inputs
bool lower_outputs
bool lower_temps
bool lower_uniforms
Detailed Description
Visitor class for replacing expressions with ir_constant values.
Constructor & Destructor Documentation
variable_index_to_cond_assign_visitor::variable_index_to_cond_assign_visitor (bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform) inline
References lower_inputs, lower_outputs, lower_temps, lower_uniforms, and progress.
Member Function Documentation
ir_variable* variable_index_to_cond_assign_visitor::convert_dereference_array (ir_dereference_array * orig_deref, ir_assignment * orig_assign, ir_dereference * orig_base) inline
References ir_dereference_array::array, ir_dereference_array::array_index, ir_builder::assign(), ir_hierarchical_visitor::base_ir, assignment_generator::base_ir, ir_dereference::clone(), ir_assignment::condition, switch_generator::generate(), ir_var_temporary, is_array_or_matrix(), assignment_generator::is_write, assignment_generator::old_index, ralloc_parent(), ir_assignment::rhs, assignment_generator::rvalue, ir_if::then_instructions, ir_rvalue::type, assignment_generator::var, assignment_generator::write_mask, and ir_assignment::write_mask.
Referenced by handle_rvalue(), and visit_leave().
virtual void variable_index_to_cond_assign_visitor::handle_rvalue (ir_rvalue ** pir) inline virtual
Implements ir_rvalue_base_visitor.
References ir_dereference_array::as_dereference_array(), ir_hierarchical_visitor::base_ir, convert_dereference_array(), ir_hierarchical_visitor::in_assignee, needs_lowering(), progress, and ralloc_parent().
bool variable_index_to_cond_assign_visitor::needs_lowering (ir_dereference_array * deref) const inline
References ir_dereference_array::array, ir_dereference_array::array_index, ir_instruction::as_constant(), is_array_or_matrix(), and storage_type_needs_lowering().
Referenced by handle_rvalue().
bool variable_index_to_cond_assign_visitor::storage_type_needs_lowering (ir_dereference_array * deref) const inline
References ir_dereference_array::array, ir_var_auto, ir_var_const_in, ir_var_function_in, ir_var_function_inout, ir_var_function_out, ir_var_shader_in, ir_var_shader_out, ir_var_temporary, ir_var_uniform, lower_inputs, lower_outputs, lower_temps, lower_uniforms, ir_variable::mode, and ir_rvalue::variable_referenced().
Referenced by needs_lowering(), and visit_leave().
ir_visitor_status variable_index_to_cond_assign_visitor::visit_leave (ir_assignment * ir) inline virtual
Reimplemented from ir_rvalue_visitor.
References ir_rvalue::accept(), convert_dereference_array(), find_variable_index::deref, ir_assignment::lhs, progress, storage_type_needs_lowering(), visit_continue, and ir_rvalue_visitor::visit_leave().
Field Documentation
bool variable_index_to_cond_assign_visitor::lower_inputs
Referenced by storage_type_needs_lowering(), and variable_index_to_cond_assign_visitor().
bool variable_index_to_cond_assign_visitor::lower_outputs
Referenced by storage_type_needs_lowering(), and variable_index_to_cond_assign_visitor().
bool variable_index_to_cond_assign_visitor::lower_temps
Referenced by storage_type_needs_lowering(), and variable_index_to_cond_assign_visitor().
bool variable_index_to_cond_assign_visitor::lower_uniforms
Referenced by storage_type_needs_lowering(), and variable_index_to_cond_assign_visitor().
bool variable_index_to_cond_assign_visitor::progress
Referenced by handle_rvalue(), lower_variable_index_to_cond_assign(), variable_index_to_cond_assign_visitor(), and visit_leave().
The documentation for this class was generated from the following file:
lower_variable_index_to_cond_assign.cpp