Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_loop_jump Class Reference
Intermediate representation nodes
Jump instructions used inside loops.
#include <ir.h>
Public Types
enum jump_mode { jump_break, jump_continue }
Public Member Functions
ir_loop_jump (jump_mode mode)
virtual ir_loop_jump * clone (void *mem_ctx, struct hash_table *) const
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
bool is_break () const
bool is_continue () const
Public Member Functions inherited from ir_jump
virtual ir_jump * as_jump ()
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_rvalue * as_rvalue ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
Data Fields
enum jump_mode mode
Mode selector for the jump instruction.
Additional Inherited Members
Protected Member Functions inherited from ir_jump
ir_jump ()
Detailed Description
Jump instructions used inside loops.
These include break and continue. The break within a loop is different from the break within a switch-statement.
See Also
ir_switch_jump
Member Enumeration Documentation
enum ir_loop_jump::jump_mode
Enumerator
jump_break
jump_continue
Constructor & Destructor Documentation
ir_loop_jump::ir_loop_jump (jump_mode mode) inline
References ir_instruction::ir_type, ir_type_loop_jump, and mode.
Referenced by clone().
Member Function Documentation
virtual void ir_loop_jump::accept (ir_visitor * v) inline virtual
Implements ir_instruction.
References ir_visitor::visit().
ir_visitor_status ir_loop_jump::accept (ir_hierarchical_visitor * v) virtual
Implements ir_instruction.
References ir_hierarchical_visitor::visit().
ir_loop_jump * ir_loop_jump::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_instruction.
References ir_loop_jump(), and mode.
bool ir_loop_jump::is_break () const inline
References jump_break, and mode.
Referenced by ir_print_visitor::visit(), and ir_lower_jumps_visitor::visit().
bool ir_loop_jump::is_continue () const inline
References jump_continue, and mode.
Field Documentation
enum jump_mode ir_loop_jump::mode
Mode selector for the jump instruction.
Referenced by clone(), ir_loop_jump(), is_break(), is_continue(), is_loop_terminator(), and lower_discard_flow_visitor::visit_enter().
The documentation for this class was generated from the following files:
ir.h
ir_clone.cpp
ir_hv_accept.cpp