Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_discard Class Reference
Intermediate representation nodes
IR instruction representing discard statements.
#include <ir.h>
Public Member Functions
ir_discard ()
ir_discard (ir_rvalue *cond)
virtual ir_discard * clone (void *mem_ctx, struct hash_table *ht) const
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
virtual ir_discard * as_discard ()
Public Member Functions inherited from ir_jump
virtual ir_jump * as_jump ()
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_rvalue * as_rvalue ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
Data Fields
ir_rvalue * condition
Additional Inherited Members
Protected Member Functions inherited from ir_jump
ir_jump ()
Detailed Description
IR instruction representing discard statements.
Constructor & Destructor Documentation
ir_discard::ir_discard () inline
References condition, ir_instruction::ir_type, and ir_type_discard.
Referenced by clone().
ir_discard::ir_discard (ir_rvalue * cond) inline
References condition, ir_instruction::ir_type, and ir_type_discard.
Member Function Documentation
virtual void ir_discard::accept (ir_visitor * v) inline virtual
Implements ir_instruction.
References ir_visitor::visit().
ir_visitor_status ir_discard::accept (ir_hierarchical_visitor * v) virtual
Implements ir_instruction.
References ir_rvalue::accept(), condition, visit_continue, visit_continue_with_parent, ir_hierarchical_visitor::visit_enter(), and ir_hierarchical_visitor::visit_leave().
virtual ir_discard* ir_discard::as_discard () inline virtual
Reimplemented from ir_instruction.
Referenced by find_discard().
ir_discard * ir_discard::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_instruction.
References ir_rvalue::clone(), condition, and ir_discard().
Field Documentation
ir_rvalue* ir_discard::condition
Referenced by accept(), clone(), ir_discard(), replace_discard(), ir_print_visitor::visit(), and lower_discard_visitor::visit_leave().
The documentation for this class was generated from the following files:
ir.h
ir_clone.cpp
ir_hv_accept.cpp