Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_visitor Class Reference abstract
Abstract base class of visitors of IR instruction trees.
#include <ir_visitor.h>
Public Member Functions
virtual ~ir_visitor ()
Visit methods
As typical for the visitor pattern, there must be one visit method for each concrete subclass of ir_instruction.
Virtual base classes within the hierarchy should not have visit methods.
virtual void visit (class ir_rvalue *)
virtual void visit (class ir_variable *)=0
virtual void visit (class ir_function_signature *)=0
virtual void visit (class ir_function *)=0
virtual void visit (class ir_expression *)=0
virtual void visit (class ir_texture *)=0
virtual void visit (class ir_swizzle *)=0
virtual void visit (class ir_dereference_variable *)=0
virtual void visit (class ir_dereference_array *)=0
virtual void visit (class ir_dereference_record *)=0
virtual void visit (class ir_assignment *)=0
virtual void visit (class ir_constant *)=0
virtual void visit (class ir_call *)=0
virtual void visit (class ir_return *)=0
virtual void visit (class ir_discard *)=0
virtual void visit (class ir_if *)=0
virtual void visit (class ir_loop *)=0
virtual void visit (class ir_loop_jump *)=0
Detailed Description
Abstract base class of visitors of IR instruction trees.
Constructor & Destructor Documentation
virtual ir_visitor::~ir_visitor () inline virtual
Member Function Documentation
virtual void ir_visitor::visit (class ir_rvalue *) inline virtual
Reimplemented in ir_print_visitor.
Referenced by ir_rvalue::accept(), ir_variable::accept(), ir_function_signature::accept(), ir_function::accept(), ir_if::accept(), ir_loop::accept(), ir_assignment::accept(), ir_expression::accept(), ir_call::accept(), ir_return::accept(), ir_loop_jump::accept(), ir_discard::accept(), ir_texture::accept(), ir_swizzle::accept(), ir_dereference_variable::accept(), ir_dereference_array::accept(), ir_dereference_record::accept(), and ir_constant::accept().
virtual void ir_visitor::visit (class ir_variable *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_function_signature *) pure virtual
Implemented in ir_lower_jumps_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_function *) pure virtual
Implemented in ir_lower_jumps_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_expression *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_texture *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_swizzle *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_dereference_variable *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_dereference_array *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_dereference_record *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_assignment *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_constant *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_call *) pure virtual
Implemented in ir_control_flow_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_return *) pure virtual
Implemented in ir_lower_jumps_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_discard *) pure virtual
Implemented in ir_lower_jumps_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_if *) pure virtual
Implemented in ir_lower_jumps_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_loop *) pure virtual
Implemented in ir_lower_jumps_visitor, and ir_print_visitor.
virtual void ir_visitor::visit (class ir_loop_jump *) pure virtual
Implemented in ir_lower_jumps_visitor, and ir_print_visitor.
The documentation for this class was generated from the following file:
ir_visitor.h