Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
output_read_remover Class Reference
Public Member Functions
output_read_remover ()
~output_read_remover ()
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Protected Attributes
hash_table * replacements
A hash table mapping from the original ir_variable shader outputs (ir_var_shader_out mode) to the new temporaries to be used instead.
void * mem_ctx
Additional Inherited Members
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
output_read_remover::output_read_remover ()
References hash_table_var_hash(), mem_ctx, ralloc_context(), and replacements.
output_read_remover::~output_read_remover ()
References mem_ctx, ralloc_free(), and replacements.
Member Function Documentation
ir_visitor_status output_read_remover::visit (class ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References ir_var_shader_out, ir_var_temporary, ir_variable::mode, ir_variable::name, ralloc_parent(), replacements, ir_variable::type, ir_dereference_variable::var, and visit_continue.
ir_visitor_status output_read_remover::visit_leave (class ir_return * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References emit_return_copy(), replacements, and visit_continue.
ir_visitor_status output_read_remover::visit_leave (class ir_function_signature * sig) virtual
Reimplemented from ir_hierarchical_visitor.
References emit_main_copy(), ir_function_signature::function_name(), replacements, and visit_continue.
Field Documentation
void* output_read_remover::mem_ctx protected
Referenced by output_read_remover(), and ~output_read_remover().
hash_table* output_read_remover::replacements protected
A hash table mapping from the original ir_variable shader outputs (ir_var_shader_out mode) to the new temporaries to be used instead.
Referenced by output_read_remover(), visit(), visit_leave(), and ~output_read_remover().
The documentation for this class was generated from the following file:
lower_output_reads.cpp