Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_variable_refcount_visitor Class Reference
#include <ir_variable_refcount.h>
Public Member Functions
ir_variable_refcount_visitor (void)
~ir_variable_refcount_visitor (void)
virtual ir_visitor_status visit (ir_variable *)
virtual ir_visitor_status visit (ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (ir_function_signature *)
virtual ir_visitor_status visit_leave (ir_assignment *)
ir_variable_refcount_entry * get_variable_entry (ir_variable *var)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
struct hash_table * ht
void * mem_ctx
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
ir_variable_refcount_visitor::ir_variable_refcount_visitor (void)
References ht, mem_ctx, and ralloc_context().
ir_variable_refcount_visitor::~ir_variable_refcount_visitor (void)
References free_entry(), ht, mem_ctx, and ralloc_free().
Member Function Documentation
ir_variable_refcount_entry * ir_variable_refcount_visitor::get_variable_entry (ir_variable * var)
References ht, and ir_variable_refcount_entry::referenced_count.
Referenced by visit(), and visit_leave().
ir_visitor_status ir_variable_refcount_visitor::visit (ir_variable * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_variable_refcount_entry::declaration, get_variable_entry(), and visit_continue.
ir_visitor_status ir_variable_refcount_visitor::visit (ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References get_variable_entry(), ir_variable_refcount_entry::referenced_count, ir_dereference_variable::variable_referenced(), and visit_continue.
ir_visitor_status ir_variable_refcount_visitor::visit_enter (ir_function_signature * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_function_signature::body, visit_continue_with_parent, and visit_list_elements().
ir_visitor_status ir_variable_refcount_visitor::visit_leave (ir_assignment * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_variable_refcount_entry::assign, ir_variable_refcount_entry::assigned_count, get_variable_entry(), ir_assignment::lhs, ir_dereference::variable_referenced(), and visit_continue.
Field Documentation
struct hash_table* ir_variable_refcount_visitor::ht
Referenced by do_dead_code(), get_variable_entry(), ir_variable_refcount_visitor(), and ~ir_variable_refcount_visitor().
void* ir_variable_refcount_visitor::mem_ctx
Referenced by ir_variable_refcount_visitor(), and ~ir_variable_refcount_visitor().
The documentation for this class was generated from the following files:
ir_variable_refcount.h
ir_variable_refcount.cpp