Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
loop_analysis Class Reference
Public Member Functions
loop_analysis (loop_state *loops)
virtual ir_visitor_status visit (ir_loop_jump *)
virtual ir_visitor_status visit (ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (ir_call *)
virtual ir_visitor_status visit_enter (ir_loop *)
virtual ir_visitor_status visit_leave (ir_loop *)
virtual ir_visitor_status visit_enter (ir_assignment *)
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual ir_visitor_status visit_enter (ir_if *)
virtual ir_visitor_status visit_leave (ir_if *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
Data Fields
loop_state * loops
int if_statement_depth
ir_assignment * current_assignment
exec_list state
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
loop_analysis::loop_analysis (loop_state * loops)
Member Function Documentation
ir_visitor_status loop_analysis::visit (ir_loop_jump * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References state, and visit_continue.
ir_visitor_status loop_analysis::visit (ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References ir_assignment::condition, loop_variable::conditional_assignment, current_assignment, loop_variable::first_assignment, loop_variable_state::get(), if_statement_depth, ir_hierarchical_visitor::in_assignee, loop_variable_state::insert(), loop_variable::num_assignments, loop_variable::read_before_write, state, ir_dereference_variable::variable_referenced(), and visit_continue.
ir_visitor_status loop_analysis::visit_enter (ir_call * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References loop_variable_state::contains_calls, state, visit_continue, and visit_continue_with_parent.
ir_visitor_status loop_analysis::visit_enter (ir_loop * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References loop_state::insert(), loops, state, and visit_continue.
ir_visitor_status loop_analysis::visit_enter (ir_assignment * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References current_assignment, state, visit_continue, and visit_continue_with_parent.
ir_visitor_status loop_analysis::visit_enter (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References if_statement_depth, state, and visit_continue.
ir_visitor_status loop_analysis::visit_leave (ir_loop * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References all_expression_operands_are_loop_constant(), ir_if::as_if(), loop_variable::biv, ir_loop::body_instructions, loop_variable::conditional_assignment, loop_variable_state::constants, loop_variable_state::contains_calls, loop_variable::first_assignment, foreach_list, foreach_list_safe, get_basic_induction_increment(), loop_variable::increment, loop_variable_state::induction_variables, loop_variable_state::insert(), loop_variable::is_loop_constant(), is_loop_terminator(), loop_variable::iv_scale, loop_variable::num_assignments, ir_assignment::rhs, loop_variable::rhs_clean, state, loop_variable::var, loop_variable_state::var_hash, loop_variable_state::variables, and visit_continue.
ir_visitor_status loop_analysis::visit_leave (ir_assignment * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References current_assignment, state, and visit_continue.
ir_visitor_status loop_analysis::visit_leave (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References if_statement_depth, state, and visit_continue.
Field Documentation
ir_assignment* loop_analysis::current_assignment
Referenced by visit(), visit_enter(), and visit_leave().
int loop_analysis::if_statement_depth
Referenced by visit(), visit_enter(), and visit_leave().
loop_state* loop_analysis::loops
Referenced by analyze_loop_variables(), and visit_enter().
exec_list loop_analysis::state
Referenced by visit(), visit_enter(), and visit_leave().
The documentation for this class was generated from the following file:
loop_analysis.cpp