Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_vec_index_to_cond_assign_visitor Class Reference
Visitor class for replacing expressions with ir_constant values.
Public Member Functions
ir_vec_index_to_cond_assign_visitor ()
ir_rvalue * convert_vec_index_to_cond_assign (void *mem_ctx, ir_rvalue *orig_vector, ir_rvalue *orig_index, const glsl_type *type)
ir_rvalue * convert_vector_extract_to_cond_assign (ir_rvalue *ir)
virtual ir_visitor_status visit_enter (ir_expression *)
virtual ir_visitor_status visit_enter (ir_swizzle *)
virtual ir_visitor_status visit_leave (ir_assignment *)
virtual ir_visitor_status visit_enter (ir_return *)
virtual ir_visitor_status visit_enter (ir_call *)
virtual ir_visitor_status visit_enter (ir_if *)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_enter (class ir_function_signature *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
bool progress
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Detailed Description
Visitor class for replacing expressions with ir_constant values.
Constructor & Destructor Documentation
ir_vec_index_to_cond_assign_visitor::ir_vec_index_to_cond_assign_visitor () inline
References progress.
Member Function Documentation
ir_rvalue * ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign (void * mem_ctx, ir_rvalue * orig_vector, ir_rvalue * orig_index, const glsl_type * type)
References ir_builder::assign(), ir_hierarchical_visitor::base_ir, ir_rvalue::clone(), ir_dereference::clone(), compare_index_block(), ir_var_temporary, progress, ir_builder::swizzle(), and ir_rvalue::type.
Referenced by convert_vector_extract_to_cond_assign().
ir_rvalue * ir_vec_index_to_cond_assign_visitor::convert_vector_extract_to_cond_assign (ir_rvalue * ir)
References ir_instruction::as_expression(), convert_vec_index_to_cond_assign(), ir_builder::expr(), ir_binop_vector_extract, ir_expression::operands, ir_expression::operation, ralloc_parent(), and ir_rvalue::type.
Referenced by visit_enter(), and visit_leave().
ir_visitor_status ir_vec_index_to_cond_assign_visitor::visit_enter (ir_expression * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_cond_assign(), ir_expression::get_num_operands(), ir_expression::operands, and visit_continue.
ir_visitor_status ir_vec_index_to_cond_assign_visitor::visit_enter (ir_swizzle * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_cond_assign(), ir_swizzle::val, and visit_continue.
ir_visitor_status ir_vec_index_to_cond_assign_visitor::visit_enter (ir_return * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_cond_assign(), ir_return::value, and visit_continue.
ir_visitor_status ir_vec_index_to_cond_assign_visitor::visit_enter (ir_call * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References convert_vector_extract_to_cond_assign(), and visit_continue.
ir_visitor_status ir_vec_index_to_cond_assign_visitor::visit_enter (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_if::condition, convert_vector_extract_to_cond_assign(), and visit_continue.
ir_visitor_status ir_vec_index_to_cond_assign_visitor::visit_leave (ir_assignment * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_assignment::condition, convert_vector_extract_to_cond_assign(), ir_assignment::rhs, and visit_continue.
Field Documentation
bool ir_vec_index_to_cond_assign_visitor::progress
Referenced by convert_vec_index_to_cond_assign(), do_vec_index_to_cond_assign(), and ir_vec_index_to_cond_assign_visitor().
The documentation for this class was generated from the following file:
lower_vec_index_to_cond_assign.cpp