Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_dereference Class Reference abstract
Intermediate representation nodes
#include <ir.h>
Public Member Functions
virtual ir_dereference * clone (void *mem_ctx, struct hash_table *) const =0
virtual ir_dereference * as_dereference ()
bool is_lvalue () const
virtual ir_variable * variable_referenced () const =0
Get the variable that is ultimately referenced by an r-value.
virtual void constant_referenced (struct hash_table *variable_context, ir_constant *&store, int &offset) const =0
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
Public Member Functions inherited from ir_rvalue
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
virtual ir_rvalue * as_rvalue ()
ir_rvalue * as_rvalue_to_saturate ()
virtual ir_variable * whole_variable_referenced ()
If an r-value is a reference to a whole variable, get that variable.
virtual bool is_zero () const
Determine if an r-value has the value zero.
virtual bool is_one () const
Determine if an r-value has the value one.
virtual bool is_negative_one () const
Determine if an r-value has the value negative one.
virtual bool is_basis () const
Determine if an r-value is a basis vector.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Additional Inherited Members
Static Public Member Functions inherited from ir_rvalue
static ir_rvalue * error_value (void *mem_ctx)
Return a generic value of error_type.
Data Fields inherited from ir_rvalue
struct glsl_type * type
Protected Member Functions inherited from ir_rvalue
ir_rvalue ()
Member Function Documentation
virtual ir_dereference* ir_dereference::as_dereference () inline virtual
Reimplemented from ir_instruction.
Referenced by ir_array_splitting_visitor::handle_rvalue(), and ir_sampler_replacement_visitor::replace_rvalue().
virtual ir_dereference* ir_dereference::clone (void * mem_ctx, struct hash_table *) const pure virtual
Reimplemented from ir_rvalue.
Implemented in ir_dereference_record, ir_dereference_array, and ir_dereference_variable.
Referenced by ir_assignment::clone(), ir_texture::clone(), variable_index_to_cond_assign_visitor::convert_dereference_array(), ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign(), ir_mat_op_to_vec_visitor::do_equal_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_scalar(), ir_mat_op_to_vec_visitor::do_mul_mat_vec(), ir_mat_op_to_vec_visitor::do_mul_vec_mat(), lower_clip_distance_visitor::fix_lhs(), assignment_generator::generate(), ir_mat_op_to_vec_visitor::get_column(), ir_sampler_replacement_visitor::replace_deref(), replace_return_with_assignment(), and lower_clip_distance_visitor::visit_leave().
virtual void ir_dereference::constant_referenced (struct hash_table * variable_context, ir_constant *& store, int & offset) const pure virtual
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
The offset is used when the reference is to a specific column of a matrix.
Implemented in ir_dereference_record, ir_dereference_array, and ir_dereference_variable.
Referenced by ir_dereference_array::constant_referenced(), and ir_dereference_record::constant_referenced().
bool ir_dereference::is_lvalue () const virtual
Reimplemented from ir_rvalue.
References ir_variable::read_only, ir_rvalue::type, and variable_referenced().
virtual ir_variable* ir_dereference::variable_referenced () const pure virtual
Get the variable that is ultimately referenced by an r-value.
Reimplemented from ir_rvalue.
Implemented in ir_dereference_record, ir_dereference_array, and ir_dereference_variable.
Referenced by do_assignment(), get_basic_induction_increment(), is_lvalue(), move_block_to_cond_assign(), process_assignment(), find_assignment_visitor::visit_enter(), ir_mat_op_to_vec_visitor::visit_leave(), and ir_variable_refcount_visitor::visit_leave().
The documentation for this class was generated from the following files:
ir.h
ir.cpp