Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_discard_flow_visitor Class Reference
Public Member Functions
lower_discard_flow_visitor (ir_variable *discarded)
~lower_discard_flow_visitor ()
ir_visitor_status visit_enter (ir_discard *ir)
ir_visitor_status visit_enter (ir_loop_jump *ir)
ir_visitor_status visit_enter (ir_loop *ir)
ir_visitor_status visit_enter (ir_function_signature *ir)
ir_if * generate_discard_break ()
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_variable *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit (class ir_dereference_variable *)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_leave (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_function *)
virtual ir_visitor_status visit_leave (class ir_function *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_leave (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_swizzle *)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_enter (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_enter (class ir_call *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_enter (class ir_if *)
virtual ir_visitor_status visit_leave (class ir_if *)
Data Fields
ir_variable * discarded
void * mem_ctx
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
lower_discard_flow_visitor::lower_discard_flow_visitor (ir_variable * discarded) inline
References mem_ctx, and ralloc_parent().
lower_discard_flow_visitor::~lower_discard_flow_visitor () inline
Member Function Documentation
ir_if * lower_discard_flow_visitor::generate_discard_break ()
References discarded, ir_loop_jump::jump_break, mem_ctx, and ir_if::then_instructions.
Referenced by visit_enter().
ir_visitor_status lower_discard_flow_visitor::visit_enter (ir_discard * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_builder::assign(), discarded, mem_ctx, and visit_continue.
ir_visitor_status lower_discard_flow_visitor::visit_enter (ir_loop_jump * ir)
References generate_discard_break(), ir_loop_jump::jump_continue, ir_loop_jump::mode, and visit_continue.
ir_visitor_status lower_discard_flow_visitor::visit_enter (ir_loop * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_loop::body_instructions, generate_discard_break(), and visit_continue.
ir_visitor_status lower_discard_flow_visitor::visit_enter (ir_function_signature * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_builder::assign(), ir_function_signature::body, discarded, ir_function_signature::function_name(), mem_ctx, and visit_continue.
Field Documentation
ir_variable* lower_discard_flow_visitor::discarded
Referenced by generate_discard_break(), and visit_enter().
void* lower_discard_flow_visitor::mem_ctx
Referenced by generate_discard_break(), lower_discard_flow_visitor(), and visit_enter().
The documentation for this class was generated from the following file:
lower_discard_flow.cpp