Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ast_declarator_list Class Reference
Abstract syntax tree node definitions
#include <ast.h>
Public Member Functions
ast_declarator_list (ast_fully_specified_type *)
virtual void print (void) const
Print an AST node in something approximating the original GLSL code.
virtual ir_rvalue * hir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Convert the AST node to the high-level intermediate representation.
Public Member Functions inherited from ast_node
struct YYLTYPE get_location (void) const
Retrieve the source location of an AST node.
void set_location (const struct YYLTYPE &locp)
Set the source location of an AST node from a parser location.
Data Fields
ast_fully_specified_type * type
exec_list declarations
int invariant
Special flag for vertex shader "invariant" declarations.
bool ubo_qualifiers_valid
Flag indicating that these declarators are in a uniform block, allowing UBO type qualifiers.
Data Fields inherited from ast_node
struct {
unsigned source
GLSL source number.
unsigned line
Line number within the source string.
unsigned column
Column in the line.
} location
exec_node link
Additional Inherited Members
Static Public Member Functions inherited from ast_node
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Protected Member Functions inherited from ast_node
ast_node (void)
The only constructor is protected so that only derived class objects can be created.
Constructor & Destructor Documentation
ast_declarator_list::ast_declarator_list (ast_fully_specified_type * type)
References invariant, type, and ubo_qualifiers_valid.
Member Function Documentation
ir_rvalue * ast_declarator_list::hir (exec_list * instructions, struct _mesa_glsl_parse_state * state) virtual
Convert the AST node to the high-level intermediate representation.
Reimplemented from ast_node.
References _mesa_glsl_error(), _mesa_glsl_warning(), apply_type_qualifier_to_variable(), ast_precision_none, declarations, ast_type_qualifier::flags, foreach_list_typed, ast_node::get_location(), get_variable_being_redeclared(), ast_type_specifier::glsl_type(), GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ast_type_qualifier::has_interpolation(), ast_type_specifier::hir(), ir_variable::interpolation, ast_type_qualifier::interpolation_string(), ir_variable::invariant, invariant, ir_var_auto, ir_var_shader_in, ir_var_shader_out, ast_node::link, ir_variable::mode, ir_variable::name, ast_type_specifier::precision, process_array_type(), process_initializer(), ast_type_qualifier::q, ast_fully_specified_type::qualifier, ir_variable::read_only, ast_fully_specified_type::specifier, ast_type_specifier::structure, ir_variable::type, type, and ir_variable::used.
void ast_declarator_list::print (void) const virtual
Print an AST node in something approximating the original GLSL code.
Reimplemented from ast_node.
References declarations, exec_node_data, foreach_list_const, invariant, ast_node::link, ast_node::print(), ast_fully_specified_type::print(), and type.
Field Documentation
exec_list ast_declarator_list::declarations
Referenced by hir(), and print().
int ast_declarator_list::invariant
Special flag for vertex shader "invariant" declarations.
Vertex shaders can contain "invariant" variable redeclarations that do not include a type. For example, "invariant gl_Position;". This flag is used to note these cases when no type is specified.
Referenced by ast_declarator_list(), hir(), and print().
ast_fully_specified_type* ast_declarator_list::type
Referenced by ast_declarator_list(), hir(), and print().
bool ast_declarator_list::ubo_qualifiers_valid
Flag indicating that these declarators are in a uniform block, allowing UBO type qualifiers.
Referenced by ast_declarator_list().
The documentation for this class was generated from the following files:
ast.h
ast_to_hir.cpp
glsl_parser_extras.cpp