Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_validate Class Reference
Public Member Functions
ir_validate ()
~ir_validate ()
virtual ir_visitor_status visit (ir_variable *v)
virtual ir_visitor_status visit (ir_dereference_variable *ir)
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
virtual ir_visitor_status visit_enter (ir_if *ir)
virtual ir_visitor_status visit_leave (ir_loop *ir)
virtual ir_visitor_status visit_enter (ir_function *ir)
virtual ir_visitor_status visit_leave (ir_function *ir)
virtual ir_visitor_status visit_enter (ir_function_signature *ir)
virtual ir_visitor_status visit_leave (ir_expression *ir)
virtual ir_visitor_status visit_leave (ir_swizzle *ir)
virtual ir_visitor_status visit_enter (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (ir_assignment *ir)
virtual ir_visitor_status visit_enter (ir_call *ir)
Public Member Functions inherited from ir_hierarchical_visitor
ir_hierarchical_visitor ()
void run (struct exec_list *instructions)
Utility function to process a linked list of instructions with a visitor.
virtual ir_visitor_status visit (class ir_rvalue *)
virtual ir_visitor_status visit (class ir_constant *)
virtual ir_visitor_status visit (class ir_loop_jump *)
virtual ir_visitor_status visit_enter (class ir_loop *)
virtual ir_visitor_status visit_leave (class ir_function_signature *)
virtual ir_visitor_status visit_enter (class ir_expression *)
virtual ir_visitor_status visit_enter (class ir_texture *)
virtual ir_visitor_status visit_leave (class ir_texture *)
virtual ir_visitor_status visit_enter (class ir_swizzle *)
virtual ir_visitor_status visit_leave (class ir_dereference_array *)
virtual ir_visitor_status visit_enter (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_dereference_record *)
virtual ir_visitor_status visit_leave (class ir_assignment *)
virtual ir_visitor_status visit_leave (class ir_call *)
virtual ir_visitor_status visit_enter (class ir_return *)
virtual ir_visitor_status visit_leave (class ir_return *)
virtual ir_visitor_status visit_enter (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_discard *)
virtual ir_visitor_status visit_leave (class ir_if *)
Static Public Member Functions
static void validate_ir (ir_instruction *ir, void *data)
Data Fields
ir_function * current_function
struct hash_table * ht
Data Fields inherited from ir_hierarchical_visitor
class ir_instruction * base_ir
void(* callback)(class ir_instruction *ir, void *data)
Callback function that is invoked on entry to each node visited.
void * data
Extra data parameter passed to the per-node callback function.
bool in_assignee
Currently in the LHS of an assignment?
Constructor & Destructor Documentation
ir_validate::ir_validate () inline
References ir_hierarchical_visitor::callback, current_function, ir_hierarchical_visitor::data, ht, and validate_ir().
ir_validate::~ir_validate () inline
References ht.
Member Function Documentation
void ir_validate::validate_ir (ir_instruction * ir, void * data) static
References ht, and ir_instruction::print().
Referenced by ir_validate(), visit(), and visit_enter().
ir_visitor_status ir_validate::visit (ir_variable * v) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_variable::constant_initializer, ir_variable::has_initializer, ht, ir_variable::max_array_access, ir_variable::name, ir_instruction::print(), ralloc_parent(), ir_variable::type, and visit_continue.
ir_visitor_status ir_validate::visit (ir_dereference_variable * ir) virtual
ir_dereference_variable isn't technically a leaf, but it is treated as a leaf here for a couple reasons.
By not automatically visiting the one child ir_variable node from the ir_dereference_variable, ir_variable nodes can always be handled as variable declarations. Code that used non-hierarchical visitors had to set an "in a dereference" flag to determine how to handle an ir_variable. By forcing the visitor to handle the ir_variable within the ir_dereference_variable visitor, this kludge can be avoided.
In addition, I can envision no use for having separate enter and leave methods. Anything that could be done in the enter and leave methods that couldn't just be done in the visit method.
Reimplemented from ir_hierarchical_visitor.
References ir_variable::as_variable(), ir_hierarchical_visitor::data, ht, ir_variable::name, validate_ir(), ir_dereference_variable::var, and visit_continue.
ir_visitor_status ir_validate::visit_enter (ir_if * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_if::condition, ir_instruction::print(), ir_rvalue::type, and visit_continue.
ir_visitor_status ir_validate::visit_enter (ir_function * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References current_function, ir_hierarchical_visitor::data, foreach_list, ir_instruction::ir_type, ir_type_function_signature, ir_function::name, ir_function::signatures, validate_ir(), and visit_continue.
ir_visitor_status ir_validate::visit_enter (ir_function_signature * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References current_function, ir_hierarchical_visitor::data, ir_function_signature::function(), ir_function_signature::function_name(), ir_function::name, ir_function_signature::return_type, validate_ir(), and visit_continue.
ir_visitor_status ir_validate::visit_enter (class ir_dereference_array * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_dereference_array::array, ir_dereference_array::array_index, ir_instruction::print(), ir_rvalue::type, and visit_continue.
ir_visitor_status ir_validate::visit_enter (ir_assignment * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_hierarchical_visitor::data, ir_assignment::lhs, ir_instruction::print(), ir_assignment::rhs, ir_rvalue::type, validate_ir(), visit_continue, and ir_assignment::write_mask.
ir_visitor_status ir_validate::visit_enter (ir_call * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_call::actual_parameters, ir_call::callee, exec_list::head, ir_instruction::ir_type, ir_type_function_signature, ir_var_function_inout, ir_var_function_out, ir_rvalue::is_lvalue(), ir_variable::mode, exec_node::next, ir_function_signature::parameters, ir_instruction::print(), ir_call::return_deref, ir_function_signature::return_type, ir_rvalue::type, ir_variable::type, visit_continue, and visit_stop.
ir_visitor_status ir_validate::visit_leave (ir_loop * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_loop::cmp, ir_loop::counter, ir_loop::from, ir_loop::increment, ir_binop_less, ir_binop_nequal, ir_loop::to, and visit_continue.
ir_visitor_status ir_validate::visit_leave (ir_function * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References current_function, ir_function::name, ralloc_parent(), and visit_continue.
ir_visitor_status ir_validate::visit_leave (ir_expression * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_instruction::as_constant(), GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_binop_add, ir_binop_all_equal, ir_binop_any_nequal, ir_binop_bfm, ir_binop_bit_and, ir_binop_bit_or, ir_binop_bit_xor, ir_binop_div, ir_binop_dot, ir_binop_equal, ir_binop_gequal, ir_binop_greater, ir_binop_lequal, ir_binop_less, ir_binop_logic_and, ir_binop_logic_or, ir_binop_logic_xor, ir_binop_lshift, ir_binop_max, ir_binop_min, ir_binop_mod, ir_binop_mul, ir_binop_nequal, ir_binop_pack_half_2x16_split, ir_binop_pow, ir_binop_rshift, ir_binop_sub, ir_binop_ubo_load, ir_binop_vector_extract, ir_quadop_bitfield_insert, ir_quadop_vector, ir_triop_bfi, ir_triop_bitfield_extract, ir_triop_lrp, ir_triop_vector_insert, ir_unop_abs, ir_unop_any, ir_unop_b2f, ir_unop_b2i, ir_unop_bit_count, ir_unop_bit_not, ir_unop_bitcast_f2i, ir_unop_bitcast_f2u, ir_unop_bitcast_i2f, ir_unop_bitcast_u2f, ir_unop_bitfield_reverse, ir_unop_ceil, ir_unop_cos, ir_unop_cos_reduced, ir_unop_dFdx, ir_unop_dFdy, ir_unop_exp, ir_unop_exp2, ir_unop_f2b, ir_unop_f2i, ir_unop_f2u, ir_unop_find_lsb, ir_unop_find_msb, ir_unop_floor, ir_unop_fract, ir_unop_i2b, ir_unop_i2f, ir_unop_i2u, ir_unop_log, ir_unop_log2, ir_unop_logic_not, ir_unop_neg, ir_unop_noise, ir_unop_pack_half_2x16, ir_unop_pack_snorm_2x16, ir_unop_pack_snorm_4x8, ir_unop_pack_unorm_2x16, ir_unop_pack_unorm_4x8, ir_unop_rcp, ir_unop_round_even, ir_unop_rsq, ir_unop_sign, ir_unop_sin, ir_unop_sin_reduced, ir_unop_sqrt, ir_unop_trunc, ir_unop_u2f, ir_unop_u2i, ir_unop_unpack_half_2x16, ir_unop_unpack_half_2x16_split_x, ir_unop_unpack_half_2x16_split_y, ir_unop_unpack_snorm_2x16, ir_unop_unpack_snorm_4x8, ir_unop_unpack_unorm_2x16, ir_unop_unpack_unorm_4x8, ir_expression::operands, ir_expression::operation, ir_rvalue::type, and visit_continue.
ir_visitor_status ir_validate::visit_leave (ir_swizzle * ir) virtual
Reimplemented from ir_hierarchical_visitor.
References ir_swizzle::mask, ir_instruction::print(), ir_rvalue::type, ir_swizzle::val, visit_continue, ir_swizzle_mask::w, ir_swizzle_mask::x, ir_swizzle_mask::y, and ir_swizzle_mask::z.
Field Documentation
ir_function* ir_validate::current_function
Referenced by ir_validate(), visit_enter(), and visit_leave().
struct hash_table* ir_validate::ht
Referenced by ir_validate(), validate_ir(), visit(), and ~ir_validate().
The documentation for this class was generated from the following file:
ir_validate.cpp