Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_return Class Reference
Intermediate representation nodes
#include <ir.h>
Public Member Functions
ir_return ()
ir_return (ir_rvalue *value)
virtual ir_return * clone (void *mem_ctx, struct hash_table *) const
virtual ir_return * as_return ()
ir_rvalue * get_value () const
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
Public Member Functions inherited from ir_jump
virtual ir_jump * as_jump ()
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_rvalue * as_rvalue ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
Data Fields
ir_rvalue * value
Additional Inherited Members
Protected Member Functions inherited from ir_jump
ir_jump ()
Constructor & Destructor Documentation
ir_return::ir_return () inline
References ir_instruction::ir_type, and ir_type_return.
Referenced by clone().
ir_return::ir_return (ir_rvalue * value) inline
References ir_instruction::ir_type, and ir_type_return.
Member Function Documentation
virtual void ir_return::accept (ir_visitor * v) inline virtual
Implements ir_instruction.
References ir_visitor::visit().
ir_visitor_status ir_return::accept (ir_hierarchical_visitor * v) virtual
Implements ir_instruction.
References ir_rvalue::accept(), get_value(), visit_continue, visit_continue_with_parent, ir_hierarchical_visitor::visit_enter(), and ir_hierarchical_visitor::visit_leave().
virtual ir_return* ir_return::as_return () inline virtual
Reimplemented from ir_instruction.
ir_return * ir_return::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_instruction.
References ir_rvalue::clone(), ir_return(), and value.
ir_rvalue* ir_return::get_value () const inline
References value.
Referenced by accept(), and ir_print_visitor::visit().
Field Documentation
ir_rvalue* ir_return::value
Referenced by clone(), get_value(), ir_lower_jumps_visitor::insert_lowered_return(), replace_return_with_assignment(), ir_rvalue_base_visitor::rvalue_visit(), ir_vec_index_to_swizzle_visitor::visit_enter(), and ir_vec_index_to_cond_assign_visitor::visit_enter().
The documentation for this class was generated from the following files:
ir.h
ir_clone.cpp
ir_hv_accept.cpp