Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
loop_state Class Reference
#include <loop_analysis.h>
Public Member Functions
~loop_state ()
loop_variable_state * get (const ir_loop *)
Get the loop variable state data for a particular loop.
loop_variable_state * insert (ir_loop *ir)
Data Fields
bool loop_found
Friends
loop_state * analyze_loop_variables (exec_list *instructions)
Analyze and classify all variables used in all loops in the instruction list.
Constructor & Destructor Documentation
loop_state::~loop_state ()
References ralloc_free().
Member Function Documentation
loop_variable_state * loop_state::get (const ir_loop * ir)
Get the loop variable state data for a particular loop.
Referenced by loop_unroll_visitor::visit_leave(), and loop_control_visitor::visit_leave().
loop_variable_state * loop_state::insert (ir_loop * ir)
References loop_found.
Referenced by loop_analysis::visit_enter().
Friends And Related Function Documentation
loop_state* analyze_loop_variables (exec_list * instructions) friend
Analyze and classify all variables used in all loops in the instruction list.
Field Documentation
bool loop_state::loop_found
Referenced by do_common_optimization(), and insert().
The documentation for this class was generated from the following files:
loop_analysis.h
loop_analysis.cpp