Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_rvalue Class Reference
Intermediate representation nodes
The base class for all "values"/expression trees.
#include <ir.h>
Public Member Functions
virtual ir_rvalue * clone (void *mem_ctx, struct hash_table *) const
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
virtual ir_rvalue * as_rvalue ()
ir_rvalue * as_rvalue_to_saturate ()
virtual bool is_lvalue () const
virtual ir_variable * variable_referenced () const
Get the variable that is ultimately referenced by an r-value.
virtual ir_variable * whole_variable_referenced ()
If an r-value is a reference to a whole variable, get that variable.
virtual bool is_zero () const
Determine if an r-value has the value zero.
virtual bool is_one () const
Determine if an r-value has the value one.
virtual bool is_negative_one () const
Determine if an r-value has the value negative one.
virtual bool is_basis () const
Determine if an r-value is a basis vector.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Static Public Member Functions
static ir_rvalue * error_value (void *mem_ctx)
Return a generic value of error_type.
Data Fields
struct glsl_type * type
Data Fields inherited from ir_instruction
enum ir_node_type ir_type
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Protected Member Functions
ir_rvalue ()
Protected Member Functions inherited from ir_instruction
ir_instruction ()
Detailed Description
The base class for all "values"/expression trees.
Constructor & Destructor Documentation
ir_rvalue::ir_rvalue () protected
References type.
Member Function Documentation
virtual void ir_rvalue::accept (ir_visitor * v) inline virtual
Implements ir_instruction.
Reimplemented in ir_constant, ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_swizzle, ir_texture, and ir_expression.
References ir_visitor::visit().
Referenced by ir_if::accept(), ir_loop::accept(), ir_assignment::accept(), ir_return::accept(), ir_discard::accept(), ir_texture::accept(), ir_swizzle::accept(), ir_dereference_array::accept(), ir_dereference_record::accept(), all_expression_operands_are_loop_constant(), assignment_generator::generate(), process_assignment(), ir_print_visitor::visit(), ir_array_splitting_visitor::visit_leave(), and variable_index_to_cond_assign_visitor::visit_leave().
ir_visitor_status ir_rvalue::accept (ir_hierarchical_visitor * v) virtual
Implements ir_instruction.
Reimplemented in ir_constant, ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_swizzle, ir_texture, and ir_expression.
References ir_hierarchical_visitor::visit().
virtual ir_rvalue* ir_rvalue::as_rvalue () inline virtual
Reimplemented from ir_instruction.
Referenced by emit_inline_record_constructor(), and ast_function_expression::hir().
ir_rvalue * ir_rvalue::as_rvalue_to_saturate ()
References ir_instruction::as_expression(), ir_builder::expr(), try_max_zero(), and try_min_one().
ir_rvalue * ir_rvalue::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_instruction.
Reimplemented in ir_constant, ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_dereference, ir_swizzle, ir_texture, and ir_expression.
References error_value().
Referenced by ir_if::clone(), ir_loop::clone(), ir_assignment::clone(), ir_expression::clone(), ir_return::clone(), ir_discard::clone(), ir_texture::clone(), ir_swizzle::clone(), ir_dereference_array::clone(), ir_dereference_record::clone(), ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign(), do_assignment(), do_comparison(), fix_parameter(), get_basic_induction_increment(), vector_insert_visitor::handle_rvalue(), deref_replacer::handle_rvalue(), switch_generator::linear_sequence(), move_block_to_cond_assign(), lower_clip_distance_visitor::visit_leave(), and loop_control_visitor::visit_leave().
ir_constant * ir_rvalue::constant_expression_value (struct hash_table * variable_context = NULL) virtual
Reimplemented in ir_constant, ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_swizzle, ir_texture, and ir_expression.
References type.
Referenced by _mesa_ast_array_index_to_hir(), calculate_iterations(), ir_expression::constant_expression_value(), ir_swizzle::constant_expression_value(), ir_dereference_array::constant_expression_value(), ir_dereference_record::constant_expression_value(), ir_dereference_array::constant_referenced(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), lower_clip_distance_visitor::create_indices(), vector_insert_visitor::handle_rvalue(), ast_expression::hir(), ast_function_expression::hir(), ast_case_label::hir(), process_array_constructor(), process_array_type(), process_initializer(), and process_parameters().
ir_rvalue * ir_rvalue::error_value (void * mem_ctx) static
Return a generic value of error_type.
Allocation will be performed with 'mem_ctx' as ralloc owner.
References type.
Referenced by _mesa_ast_field_selection_to_hir(), clone(), ast_expression::hir(), ast_function_expression::hir(), and process_array_constructor().
bool ir_rvalue::is_basis () const virtual
Determine if an r-value is a basis vector.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have one element set to the value one, and the other elements set to the value zero. For boolean types, the result is always false.
See Also
ir_constant::has_value, ir_rvalue::is_zero, ir_rvalue::is_one, is_constant::is_negative_one
Reimplemented in ir_constant.
virtual bool ir_rvalue::is_lvalue () const inline virtual
Reimplemented in ir_dereference, and ir_swizzle.
Referenced by do_assignment(), ir_swizzle::is_lvalue(), verify_parameter_modes(), and ir_validate::visit_enter().
bool ir_rvalue::is_negative_one () const virtual
Determine if an r-value has the value negative one.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have all elements set to the value negative one. For boolean types, the result is always false.
See Also
ir_constant::has_value, ir_rvalue::is_zero, ir_rvalue::is_one ir_constant::is_basis
Reimplemented in ir_constant.
bool ir_rvalue::is_one () const virtual
Determine if an r-value has the value one.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have all elements set to the value one (or true for booleans).
See Also
ir_constant::has_value, ir_rvalue::is_zero, ir_rvalue::is_negative_one, ir_constant::is_basis
Reimplemented in ir_constant.
Referenced by try_min_one().
bool ir_rvalue::is_zero () const virtual
Determine if an r-value has the value zero.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have all elements set to the value zero (or false for booleans).
See Also
ir_constant::has_value, ir_rvalue::is_one, ir_rvalue::is_negative_one, ir_constant::is_basis
Reimplemented in ir_constant.
Referenced by try_max_zero().
virtual ir_variable* ir_rvalue::variable_referenced () const inline virtual
Get the variable that is ultimately referenced by an r-value.
Reimplemented in ir_dereference_record, ir_dereference_array, ir_dereference_variable, ir_dereference, and ir_swizzle.
Referenced by do_assignment(), get_basic_induction_increment(), variable_index_to_cond_assign_visitor::storage_type_needs_lowering(), ir_swizzle::variable_referenced(), ir_dereference_array::variable_referenced(), ir_dereference_record::variable_referenced(), verify_parameter_modes(), find_assignment_visitor::visit_enter(), and loop_control_visitor::visit_leave().
virtual ir_variable* ir_rvalue::whole_variable_referenced () inline virtual
If an r-value is a reference to a whole variable, get that variable.
Returns
Pointer to a variable that is completely dereferenced by the r-value. If the r-value is not a dereference or the dereference does not access the entire variable (i.e., it's just one array element, struct field), NULL is returned.
Reimplemented in ir_dereference_variable.
Referenced by _mesa_ast_array_index_to_hir(), find_initial_value(), and ir_assignment::whole_variable_written().
Field Documentation
struct glsl_type* ir_rvalue::type
Referenced by _mesa_ast_array_index_to_hir(), _mesa_ast_field_selection_to_hir(), apply_implicit_conversion(), arithmetic_result_type(), ir_builder::assign(), assign_to_matrix_column(), calculate_iterations(), check_node_type(), ir_expression::clone(), ir_texture::clone(), ir_constant::clone(), compare_index_block(), constant_expression_value(), ir_expression::constant_expression_value(), ir_swizzle::constant_expression_value(), ir_dereference_array::constant_expression_value(), ir_dereference_array::constant_referenced(), convert_component(), variable_index_to_cond_assign_visitor::convert_dereference_array(), ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign(), ir_vec_index_to_cond_assign_visitor::convert_vector_extract_to_cond_assign(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), ir_constant::copy_masked_offset(), ir_constant::copy_offset(), lower_clip_distance_visitor::create_indices(), dereference_component(), do_assignment(), do_comparison(), ir_mat_op_to_vec_visitor::do_equal_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_scalar(), ir_mat_op_to_vec_visitor::do_mul_mat_vec(), ir_mat_op_to_vec_visitor::do_mul_vec_mat(), dot(), emit_inline_matrix_constructor(), emit_inline_vector_constructor(), error_value(), lower_clip_distance_visitor::fix_lhs(), fix_parameter(), ir_constant::get_array_element(), get_basic_induction_increment(), ir_constant::get_bool_component(), ir_mat_op_to_vec_visitor::get_column(), ir_constant::get_float_component(), ir_constant::get_int_component(), get_lvalue_copy(), ir_constant::get_record_field(), get_scalar_boolean_operand(), ir_constant::get_uint_component(), lower_vector_visitor::handle_rvalue(), lower_noise_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), ir_expression_flattening_visitor::handle_rvalue(), has_matrix_operand(), ir_constant::has_value(), ast_expression::hir(), ast_function_expression::hir(), ast_selection_statement::hir(), ast_switch_statement::hir(), ast_jump_statement::hir(), ir_assignment::ir_assignment(), ir_constant::ir_constant(), ir_dereference_record::ir_dereference_record(), ir_dereference_variable::ir_dereference_variable(), ir_expression::ir_expression(), ir_rvalue(), ir_swizzle::ir_swizzle(), is_array_or_matrix(), ir_constant::is_basis(), is_extended_swizzle(), ir_dereference::is_lvalue(), ir_constant::is_negative_one(), ir_constant::is_one(), ir_constant::is_zero(), mark_whole_array_access(), mat_op_to_vec_predicate(), parameter_lists_match(), process_array_constructor(), process_array_type(), process_initializer(), relational_result_type(), ir_texture::set_sampler(), linker::set_uniform_initializer(), single_scalar_parameter(), ir_array_splitting_visitor::split_deref(), steal_memory(), ir_builder::swizzle_for_size(), ast_switch_statement::test_to_hir(), update_type(), validate_assignment(), ir_set_program_inouts_visitor::visit(), ir_print_visitor::visit(), ir_set_program_inouts_visitor::visit_enter(), ir_validate::visit_enter(), ir_mat_op_to_vec_visitor::visit_leave(), lower_texture_projection_visitor::visit_leave(), lower_clip_distance_visitor::visit_leave(), ir_validate::visit_leave(), lower_instructions_visitor::visit_leave(), and ir_constant::zero().
The documentation for this class was generated from the following files:
ir.h
ir.cpp
ir_clone.cpp
ir_constant_expression.cpp
ir_hv_accept.cpp