Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_constant Class Reference
Intermediate representation nodes
#include <ir.h>
Public Member Functions
ir_constant (const struct glsl_type *type, const ir_constant_data *data)
ir_constant (bool b)
ir_constant (unsigned int u)
ir_constant (int i)
ir_constant (float f)
ir_constant (const struct glsl_type *type, exec_list *values)
Construct an ir_constant from a list of ir_constant values.
ir_constant (const ir_constant *c, unsigned i)
Construct an ir_constant from a scalar component of another ir_constant.
virtual ir_constant * clone (void *mem_ctx, struct hash_table *) const
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
virtual ir_constant * as_constant ()
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
ir_constant * get_array_element (unsigned i) const
ir_constant * get_record_field (const char *name)
void copy_offset (ir_constant *src, int offset)
Copy the values on another constant at a given offset.
void copy_masked_offset (ir_constant *src, int offset, unsigned int mask)
Copy the values on another constant at a given offset and following an assign-like mask.
bool has_value (const ir_constant *) const
Determine whether a constant has the same value as another constant.
virtual bool is_zero () const
Determine if an r-value has the value zero.
virtual bool is_one () const
Determine if an r-value has the value one.
virtual bool is_negative_one () const
Determine if an r-value has the value negative one.
virtual bool is_basis () const
Determine if an r-value is a basis vector.
bool get_bool_component (unsigned i) const
Get a particular component of a constant as a specific type.
float get_float_component (unsigned i) const
int get_int_component (unsigned i) const
unsigned get_uint_component (unsigned i) const
Public Member Functions inherited from ir_rvalue
virtual ir_rvalue * as_rvalue ()
ir_rvalue * as_rvalue_to_saturate ()
virtual bool is_lvalue () const
virtual ir_variable * variable_referenced () const
Get the variable that is ultimately referenced by an r-value.
virtual ir_variable * whole_variable_referenced ()
If an r-value is a reference to a whole variable, get that variable.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class ir_dereference * as_dereference ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_variable * as_dereference_variable ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Static Public Member Functions
static ir_constant * zero (void *mem_ctx, const glsl_type *type)
Return a new ir_constant of the specified type containing all zeros.
Static Public Member Functions inherited from ir_rvalue
static ir_rvalue * error_value (void *mem_ctx)
Return a generic value of error_type.
Data Fields
union ir_constant_data value
Value of the constant.
ir_constant ** array_elements
exec_list components
Data Fields inherited from ir_rvalue
struct glsl_type * type
Data Fields inherited from ir_instruction
enum ir_node_type ir_type
Data Fields inherited from exec_node
struct exec_node * next
struct exec_node * prev
Additional Inherited Members
Protected Member Functions inherited from ir_rvalue
ir_rvalue ()
Constructor & Destructor Documentation
ir_constant::ir_constant (const struct glsl_type * type, const ir_constant_data * data)
References GLSL_TYPE_BOOL, GLSL_TYPE_UINT, ir_constant(), ir_instruction::ir_type, ir_type_constant, ir_rvalue::type, and value.
Referenced by ir_constant().
ir_constant::ir_constant (bool b)
References ir_constant_data::b, ir_constant(), ir_instruction::ir_type, ir_type_constant, ir_rvalue::type, and value.
ir_constant::ir_constant (unsigned int u)
References ir_constant(), ir_instruction::ir_type, ir_type_constant, ir_rvalue::type, ir_constant_data::u, and value.
ir_constant::ir_constant (int i)
References ir_constant_data::i, ir_constant(), ir_instruction::ir_type, ir_type_constant, ir_rvalue::type, and value.
ir_constant::ir_constant (float f)
References ir_constant_data::f, ir_constant(), ir_instruction::ir_type, ir_type_constant, ir_rvalue::type, and value.
ir_constant::ir_constant (const struct glsl_type * type, exec_list * values)
Construct an ir_constant from a list of ir_constant values.
References array_elements, as_constant(), ir_constant_data::b, components, ir_constant_data::f, foreach_list, get_bool_component(), get_float_component(), get_int_component(), get_uint_component(), GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, exec_list::head, ir_constant(), ir_instruction::ir_type, ir_type_constant, exec_node::next, ralloc_array, ir_rvalue::type, ir_constant_data::u, and value.
ir_constant::ir_constant (const ir_constant * c, unsigned i)
Construct an ir_constant from a scalar component of another ir_constant.
The new ir_constant inherits the type of the component from the source constant.
Note
In the case of a matrix constant, the new constant is a scalar, not a vector.
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_constant(), ir_instruction::ir_type, ir_type_constant, ir_rvalue::type, ir_constant_data::u, and value.
Member Function Documentation
virtual void ir_constant::accept (ir_visitor * v) inline virtual
Reimplemented from ir_rvalue.
References ir_visitor::visit().
Referenced by ir_print_visitor::visit().
ir_visitor_status ir_constant::accept (ir_hierarchical_visitor * v) virtual
Reimplemented from ir_rvalue.
References ir_hierarchical_visitor::visit().
virtual ir_constant* ir_constant::as_constant () inline virtual
Reimplemented from ir_instruction.
Referenced by constant_record_constructor(), and ir_constant().
ir_constant * ir_constant::clone (void * mem_ctx, struct hash_table * ht) const virtual
Reimplemented from ir_rvalue.
References array_elements, clone(), components, GLSL_TYPE_ARRAY, GLSL_TYPE_BOOL, GLSL_TYPE_ERROR, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_INTERFACE, GLSL_TYPE_SAMPLER, GLSL_TYPE_STRUCT, GLSL_TYPE_UINT, GLSL_TYPE_VOID, exec_list::head, exec_node::next, ralloc_array, ir_rvalue::type, and value.
Referenced by ir_variable::clone(), clone(), ir_function_signature::constant_expression_value(), ir_dereference_variable::constant_expression_value(), ir_dereference_array::constant_expression_value(), copy_offset(), cross_validate_globals(), and loop_control_visitor::visit_leave().
ir_constant * ir_constant::constant_expression_value (struct hash_table * variable_context = NULL) virtual
Reimplemented from ir_rvalue.
Referenced by ir_function_signature::constant_expression_value(), and ir_dereference_array::constant_expression_value().
void ir_constant::copy_masked_offset (ir_constant * src, int offset, unsigned int mask)
Copy the values on another constant at a given offset and following an assign-like mask.
The mask is ignored for scalars.
Note that this function only handles what assign can handle, i.e. at most a vector as source and a column of a matrix as destination.
References ir_constant_data::b, ir_constant_data::f, get_bool_component(), get_float_component(), get_int_component(), get_uint_component(), GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
void ir_constant::copy_offset (ir_constant * src, int offset)
Copy the values on another constant at a given offset.
The offset is ignored for array or struct copies, it's only for scalars or vectors into vectors or matrices.
With identical types on both sides and zero offset it's clone() without creating a new object.
References array_elements, ir_constant_data::b, clone(), components, ir_constant_data::f, foreach_list, get_bool_component(), get_float_component(), get_int_component(), get_uint_component(), GLSL_TYPE_ARRAY, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_STRUCT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
ir_constant * ir_constant::get_array_element (unsigned i) const
References array_elements, and ir_rvalue::type.
Referenced by ir_dereference_array::constant_expression_value(), ir_dereference_array::constant_referenced(), and ir_print_visitor::visit().
bool ir_constant::get_bool_component (unsigned i) const
Get a particular component of a constant as a specific type.
This is useful, for example, to get a value from an integer constant as a float or bool. This appears frequently when constructors are called with all constant parameters.
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by calculate_iterations(), copy_masked_offset(), copy_offset(), emit_inline_vector_constructor(), and ir_constant().
float ir_constant::get_float_component (unsigned i) const
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by copy_masked_offset(), copy_offset(), emit_inline_vector_constructor(), and ir_constant().
int ir_constant::get_int_component (unsigned i) const
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by calculate_iterations(), ir_dereference_array::constant_referenced(), copy_masked_offset(), copy_offset(), lower_clip_distance_visitor::create_indices(), emit_inline_vector_constructor(), and ir_constant().
ir_constant * ir_constant::get_record_field (const char * name)
References components, exec_list::head, exec_node::next, and ir_rvalue::type.
Referenced by ir_dereference_record::constant_expression_value(), and ir_dereference_record::constant_referenced().
unsigned ir_constant::get_uint_component (unsigned i) const
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by ir_dereference_array::constant_referenced(), copy_masked_offset(), copy_offset(), emit_inline_vector_constructor(), ir_constant(), and link_uniform_block_active_visitor::visit_enter().
bool ir_constant::has_value (const ir_constant * c) const
Determine whether a constant has the same value as another constant.
See Also
ir_constant::is_zero, ir_constant::is_one, ir_constant::is_negative_one, ir_constant::is_basis
References array_elements, ir_constant_data::b, components, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_STRUCT, GLSL_TYPE_UINT, exec_list::head, ir_constant_data::i, exec_node::next, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by ir_expression::constant_expression_value(), and cross_validate_globals().
bool ir_constant::is_basis () const virtual
Determine if an r-value is a basis vector.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have one element set to the value one, and the other elements set to the value zero. For boolean types, the result is always false.
See Also
ir_constant::has_value, ir_rvalue::is_zero, ir_rvalue::is_one, is_constant::is_negative_one
Reimplemented from ir_rvalue.
References ir_constant_data::f, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by is_vec_basis().
bool ir_constant::is_negative_one () const virtual
Determine if an r-value has the value negative one.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have all elements set to the value negative one. For boolean types, the result is always false.
See Also
ir_constant::has_value, ir_rvalue::is_zero, ir_rvalue::is_one ir_constant::is_basis
Reimplemented from ir_rvalue.
References ir_constant_data::f, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by is_extended_swizzle().
bool ir_constant::is_one () const virtual
Determine if an r-value has the value one.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have all elements set to the value one (or true for booleans).
See Also
ir_constant::has_value, ir_rvalue::is_zero, ir_rvalue::is_negative_one, ir_constant::is_basis
Reimplemented from ir_rvalue.
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by is_extended_swizzle(), and is_vec_one().
bool ir_constant::is_zero () const virtual
Determine if an r-value has the value zero.
The base implementation of this function always returns false. The ir_constant class over-rides this function to return true only for vector and scalar types that have all elements set to the value zero (or false for booleans).
See Also
ir_constant::has_value, ir_rvalue::is_one, ir_rvalue::is_negative_one, ir_constant::is_basis
Reimplemented from ir_rvalue.
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_BOOL, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_UINT, ir_constant_data::i, ir_rvalue::type, ir_constant_data::u, and value.
Referenced by is_extended_swizzle(), and is_vec_zero().
ir_constant * ir_constant::zero (void * mem_ctx, const glsl_type * type) static
Return a new ir_constant of the specified type containing all zeros.
References ralloc_array, and ir_rvalue::type.
Referenced by lower_noise_visitor::handle_rvalue(), and process_initializer().
Field Documentation
ir_constant** ir_constant::array_elements
Referenced by clone(), copy_offset(), get_array_element(), has_value(), ir_constant(), linker::set_uniform_initializer(), and steal_memory().
exec_list ir_constant::components
Referenced by clone(), copy_offset(), get_record_field(), has_value(), ir_constant(), linker::set_uniform_initializer(), steal_memory(), and ir_print_visitor::visit().
union ir_constant_data ir_constant::value
Value of the constant.
The field used to back the values supplied by the constant is determined by the type associated with the ir_instruction. Constants may be scalars, vectors, or matrices.
Referenced by _mesa_ast_array_index_to_hir(), clone(), ir_expression::constant_expression_value(), ir_swizzle::constant_expression_value(), ir_dereference_array::constant_expression_value(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), linker::copy_constant_to_storage(), copy_masked_offset(), copy_offset(), dot(), get_bool_component(), get_float_component(), get_int_component(), get_uint_component(), lower_vector_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), has_value(), ast_expression::hir(), ast_case_label::hir(), ir_constant(), is_basis(), is_negative_one(), is_one(), is_zero(), process_array_type(), ir_array_splitting_visitor::split_deref(), ir_print_visitor::visit(), and ir_set_program_inouts_visitor::visit_enter().
The documentation for this class was generated from the following files:
ir.h
ir.cpp
ir_clone.cpp
ir_constant_expression.cpp
ir_hv_accept.cpp