Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_dereference_variable Class Reference
Intermediate representation nodes
#include <ir.h>
Public Member Functions
ir_dereference_variable (ir_variable *var)
virtual ir_dereference_variable * clone (void *mem_ctx, struct hash_table *) const
virtual ir_constant * constant_expression_value (struct hash_table *variable_context=NULL)
virtual ir_dereference_variable * as_dereference_variable ()
virtual ir_variable * variable_referenced () const
Get the variable that is ultimately referenced by an r-value.
virtual void constant_referenced (struct hash_table *variable_context, ir_constant *&store, int &offset) const
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
virtual ir_variable * whole_variable_referenced ()
If an r-value is a reference to a whole variable, get that variable.
virtual void accept (ir_visitor *v)
virtual ir_visitor_status accept (ir_hierarchical_visitor *)
Public Member Functions inherited from ir_dereference
virtual ir_dereference * as_dereference ()
bool is_lvalue () const
Public Member Functions inherited from ir_rvalue
virtual ir_rvalue * as_rvalue ()
ir_rvalue * as_rvalue_to_saturate ()
virtual bool is_zero () const
Determine if an r-value has the value zero.
virtual bool is_one () const
Determine if an r-value has the value one.
virtual bool is_negative_one () const
Determine if an r-value has the value negative one.
virtual bool is_basis () const
Determine if an r-value is a basis vector.
Public Member Functions inherited from ir_instruction
virtual ~ir_instruction ()
GCC 4.7+ and clang warn when deleting an ir_instruction unless there's a virtual destructor present.
void print (void) const
ir_print_visitor helper for debugging.
virtual class ir_variable * as_variable ()
virtual class ir_function * as_function ()
virtual class
ir_dereference_array * as_dereference_array ()
virtual class
ir_dereference_record * as_dereference_record ()
virtual class ir_expression * as_expression ()
virtual class ir_loop * as_loop ()
virtual class ir_assignment * as_assignment ()
virtual class ir_call * as_call ()
virtual class ir_return * as_return ()
virtual class ir_if * as_if ()
virtual class ir_swizzle * as_swizzle ()
virtual class ir_constant * as_constant ()
virtual class ir_discard * as_discard ()
virtual class ir_jump * as_jump ()
Data Fields
ir_variable * var
Object being dereferenced.
Additional Inherited Members
Static Public Member Functions inherited from ir_rvalue
static ir_rvalue * error_value (void *mem_ctx)
Return a generic value of error_type.
Protected Member Functions inherited from ir_rvalue
ir_rvalue ()
Constructor & Destructor Documentation
ir_dereference_variable::ir_dereference_variable (ir_variable * var)
References ir_instruction::ir_type, ir_type_dereference_variable, ir_rvalue::type, ir_variable::type, and var.
Referenced by clone().
Member Function Documentation
virtual void ir_dereference_variable::accept (ir_visitor * v) inline virtual
Reimplemented from ir_rvalue.
References ir_visitor::visit().
Referenced by ir_call::accept(), and ir_print_visitor::visit().
ir_visitor_status ir_dereference_variable::accept (ir_hierarchical_visitor * v) virtual
Reimplemented from ir_rvalue.
References ir_hierarchical_visitor::visit().
virtual ir_dereference_variable* ir_dereference_variable::as_dereference_variable () inline virtual
Reimplemented from ir_instruction.
Referenced by deref_replacer::handle_rvalue(), and ir_sampler_replacement_visitor::replace_deref().
ir_dereference_variable * ir_dereference_variable::clone (void * mem_ctx, struct hash_table * ht) const virtual
Implements ir_dereference.
References ir_dereference_variable(), and var.
Referenced by ir_call::clone(), emit_inline_record_constructor(), generate_call(), and ir_if_to_cond_assign_visitor::visit_leave().
ir_constant * ir_dereference_variable::constant_expression_value (struct hash_table * variable_context = NULL) virtual
Reimplemented from ir_rvalue.
References ir_constant::clone(), ir_variable::constant_value, ir_var_uniform, ir_variable::mode, ralloc_parent(), and var.
void ir_dereference_variable::constant_referenced (struct hash_table * variable_context, ir_constant *& store, int & offset) const virtual
Get the constant that is ultimately referenced by an r-value, in a constant expression evaluation context.
The offset is used when the reference is to a specific column of a matrix.
Implements ir_dereference.
References var.
virtual ir_variable* ir_dereference_variable::variable_referenced () const inline virtual
Get the variable that is ultimately referenced by an r-value.
Implements ir_dereference.
References var.
Referenced by ir_variable_refcount_visitor::visit(), ir_print_visitor::visit(), loop_analysis::visit(), find_assignment_visitor::visit_enter(), and ir_mat_op_to_vec_visitor::visit_leave().
virtual ir_variable* ir_dereference_variable::whole_variable_referenced () inline virtual
If an r-value is a reference to a whole variable, get that variable.
Returns
Pointer to a variable that is completely dereferenced by the r-value. If the r-value is not a dereference or the dereference does not access the entire variable (i.e., it's just one array element, struct field), NULL is returned.
Reimplemented from ir_rvalue.
References var.
Field Documentation
ir_variable* ir_dereference_variable::var
Object being dereferenced.
Referenced by clone(), constant_expression_value(), constant_referenced(), lower_clip_distance_visitor::handle_rvalue(), deref_replacer::handle_rvalue(), ir_dereference_variable(), is_extended_swizzle(), mark_whole_array_access(), process_assignment(), remap_variables(), ir_sampler_replacement_visitor::replace_deref(), ir_array_splitting_visitor::split_deref(), variable_referenced(), output_read_remover::visit(), link_uniform_block_active_visitor::visit(), ir_validate::visit(), ir_set_program_inouts_visitor::visit(), ir_array_reference_visitor::visit(), find_deref_visitor::visit(), call_link_visitor::visit(), examine_rhs::visit(), ir_lower_jumps_visitor::visit(), link_uniform_block_active_visitor::visit_enter(), ir_set_program_inouts_visitor::visit_enter(), ir_array_reference_visitor::visit_enter(), lower_clip_distance_visitor::visit_leave(), and whole_variable_referenced().
The documentation for this class was generated from the following files:
ir.h
ir.cpp
ir_clone.cpp
ir_constant_expression.cpp
ir_hv_accept.cpp