Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
glsl_types.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include "main/core.h"
#include "glsl_symbol_table.h"
#include "glsl_parser_extras.h"
#include "glsl_types.h"
#include "builtin_types.h"
#include "program/hash_table.h"
Macros
#define IDX(c, r) (((c-1)*3) + (r-1))
Functions
static void add_types_to_symbol_table (glsl_symbol_table *symtab, const struct glsl_type *types, unsigned num_types, bool warn, bool skip_1d)
void _mesa_glsl_initialize_types (struct _mesa_glsl_parse_state *state)
void _mesa_glsl_release_types (void)
Macro Definition Documentation
#define IDX (c, r) (((c-1)*3) + (r-1))
Function Documentation
void _mesa_glsl_initialize_types (struct _mesa_glsl_parse_state * state)
Referenced by read_builtins(), and test_optpass().
void _mesa_glsl_release_types (void)
Referenced by _mesa_destroy_shader_compiler(), and main().
static void add_types_to_symbol_table (glsl_symbol_table * symtab, const struct glsl_type * types, unsigned num_types, bool warn, bool skip_1d) static
References glsl_symbol_table::add_type(), GLSL_SAMPLER_DIM_1D, and GLSL_TYPE_SAMPLER.