Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
glsl_types.h File Reference
#include <string.h>
#include <assert.h>
#include "main/mtypes.h"
Macros
#define GLSL_TYPES_H
Enumerations
enum glsl_base_type {
GLSL_TYPE_UINT = 0, GLSL_TYPE_INT, GLSL_TYPE_FLOAT, GLSL_TYPE_BOOL,
GLSL_TYPE_SAMPLER, GLSL_TYPE_STRUCT, GLSL_TYPE_INTERFACE, GLSL_TYPE_ARRAY,
GLSL_TYPE_VOID, GLSL_TYPE_ERROR
}
enum glsl_sampler_dim {
GLSL_SAMPLER_DIM_1D = 0, GLSL_SAMPLER_DIM_2D, GLSL_SAMPLER_DIM_3D, GLSL_SAMPLER_DIM_CUBE,
GLSL_SAMPLER_DIM_RECT, GLSL_SAMPLER_DIM_BUF, GLSL_SAMPLER_DIM_EXTERNAL, GLSL_SAMPLER_DIM_MS
}
enum glsl_interface_packing { GLSL_INTERFACE_PACKING_STD140, GLSL_INTERFACE_PACKING_SHARED, GLSL_INTERFACE_PACKING_PACKED }
Functions
void _mesa_glsl_initialize_types (struct _mesa_glsl_parse_state *state)
void _mesa_glsl_release_types (void)
Macro Definition Documentation
#define GLSL_TYPES_H
Enumeration Type Documentation
enum glsl_base_type
Enumerator
GLSL_TYPE_UINT
GLSL_TYPE_INT
GLSL_TYPE_FLOAT
GLSL_TYPE_BOOL
GLSL_TYPE_SAMPLER
GLSL_TYPE_STRUCT
GLSL_TYPE_INTERFACE
GLSL_TYPE_ARRAY
GLSL_TYPE_VOID
GLSL_TYPE_ERROR
enum glsl_interface_packing
Enumerator
GLSL_INTERFACE_PACKING_STD140
GLSL_INTERFACE_PACKING_SHARED
GLSL_INTERFACE_PACKING_PACKED
enum glsl_sampler_dim
Enumerator
GLSL_SAMPLER_DIM_1D
GLSL_SAMPLER_DIM_2D
GLSL_SAMPLER_DIM_3D
GLSL_SAMPLER_DIM_CUBE
GLSL_SAMPLER_DIM_RECT
GLSL_SAMPLER_DIM_BUF
GLSL_SAMPLER_DIM_EXTERNAL
GLSL_SAMPLER_DIM_MS
Function Documentation
void _mesa_glsl_initialize_types (struct _mesa_glsl_parse_state * state)
Referenced by read_builtins(), and test_optpass().
void _mesa_glsl_release_types (void)
Referenced by _mesa_destroy_shader_compiler(), and main().