Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
Intermediate representation nodes
Data Structures
class ir_instruction
Base class of all IR instructions.
class ir_rvalue
The base class for all "values"/expression trees.
struct ir_state_slot
Description of built-in state associated with a uniform.
class ir_variable
class ir_function_signature
The representation of a function instance; may be the full definition or simply a prototype.
class ir_function
Header for tracking multiple overloaded functions with the same name.
class ir_if
IR instruction representing high-level if-statements.
class ir_loop
IR instruction representing a high-level loop structure.
class ir_assignment
class ir_expression
class ir_call
HIR instruction representing a high-level function call, containing a list of parameters and returning a value in the supplied temporary.
class ir_jump
class ir_return
class ir_loop_jump
Jump instructions used inside loops.
class ir_discard
IR instruction representing discard statements.
class ir_texture
IR instruction to sample a texture.
struct ir_swizzle_mask
class ir_swizzle
class ir_dereference
class ir_dereference_variable
class ir_dereference_array
class ir_dereference_record
union ir_constant_data
Data stored in an ir_constant.
class ir_constant
Enumerations
enum ir_node_type {
ir_type_unset, ir_type_variable, ir_type_assignment, ir_type_call,
ir_type_constant, ir_type_dereference_array, ir_type_dereference_record, ir_type_dereference_variable,
ir_type_discard, ir_type_expression, ir_type_function, ir_type_function_signature,
ir_type_if, ir_type_loop, ir_type_loop_jump, ir_type_return,
ir_type_swizzle, ir_type_texture, ir_type_max
}
Class tags.
enum ir_variable_mode {
ir_var_auto = 0, ir_var_uniform, ir_var_shader_in, ir_var_shader_out,
ir_var_function_in, ir_var_function_out, ir_var_function_inout, ir_var_const_in,
ir_var_system_value, ir_var_temporary, ir_var_mode_count
}
Variable storage classes.
enum ir_depth_layout {
ir_depth_layout_none, ir_depth_layout_any, ir_depth_layout_greater, ir_depth_layout_less,
ir_depth_layout_unchanged
}
Layout qualifiers for gl_FragDepth.
enum ir_expression_operation {
ir_unop_bit_not, ir_unop_logic_not, ir_unop_neg, ir_unop_abs,
ir_unop_sign, ir_unop_rcp, ir_unop_rsq, ir_unop_sqrt,
ir_unop_exp, ir_unop_log, ir_unop_exp2, ir_unop_log2,
ir_unop_f2i, ir_unop_f2u, ir_unop_i2f, ir_unop_f2b,
ir_unop_b2f, ir_unop_i2b, ir_unop_b2i, ir_unop_u2f,
ir_unop_i2u, ir_unop_u2i, ir_unop_bitcast_i2f, ir_unop_bitcast_f2i,
ir_unop_bitcast_u2f, ir_unop_bitcast_f2u, ir_unop_any, ir_unop_trunc,
ir_unop_ceil, ir_unop_floor, ir_unop_fract, ir_unop_round_even,
ir_unop_sin, ir_unop_cos, ir_unop_sin_reduced, ir_unop_cos_reduced,
ir_unop_dFdx, ir_unop_dFdy, ir_unop_pack_snorm_2x16, ir_unop_pack_snorm_4x8,
ir_unop_pack_unorm_2x16, ir_unop_pack_unorm_4x8, ir_unop_pack_half_2x16, ir_unop_unpack_snorm_2x16,
ir_unop_unpack_snorm_4x8, ir_unop_unpack_unorm_2x16, ir_unop_unpack_unorm_4x8, ir_unop_unpack_half_2x16,
ir_unop_unpack_half_2x16_split_x, ir_unop_unpack_half_2x16_split_y, ir_unop_bitfield_reverse, ir_unop_bit_count,
ir_unop_find_msb, ir_unop_find_lsb, ir_unop_noise, ir_last_unop = ir_unop_noise,
ir_binop_add, ir_binop_sub, ir_binop_mul, ir_binop_div,
ir_binop_mod, ir_binop_less, ir_binop_greater, ir_binop_lequal,
ir_binop_gequal, ir_binop_equal, ir_binop_nequal, ir_binop_all_equal,
ir_binop_any_nequal, ir_binop_lshift, ir_binop_rshift, ir_binop_bit_and,
ir_binop_bit_xor, ir_binop_bit_or, ir_binop_logic_and, ir_binop_logic_xor,
ir_binop_logic_or, ir_binop_dot, ir_binop_min, ir_binop_max,
ir_binop_pow, ir_binop_pack_half_2x16_split, ir_binop_bfm, ir_binop_ubo_load,
ir_binop_vector_extract, ir_last_binop = ir_binop_vector_extract, ir_triop_lrp, ir_triop_bfi,
ir_triop_bitfield_extract, ir_triop_vector_insert, ir_last_triop = ir_triop_vector_insert, ir_quadop_bitfield_insert,
ir_quadop_vector, ir_last_quadop = ir_quadop_vector, ir_last_opcode = ir_quadop_vector
}
enum ir_texture_opcode {
ir_tex, ir_txb, ir_txl, ir_txd,
ir_txf, ir_txf_ms, ir_txs, ir_lod
}
Texture sampling opcodes used in ir_texture.
Functions
const char * depth_layout_string (ir_depth_layout layout)
Convert depth layout qualifier to string.
const char * ir_function_signature::function_name () const
Get the name of the function for which this is a signature.
Detailed Description
Enumeration Type Documentation
enum ir_depth_layout
Layout qualifiers for gl_FragDepth.
The AMD/ARB_conservative_depth extensions allow gl_FragDepth to be redeclared with a layout qualifier.
Enumerator
ir_depth_layout_none
No depth layout is specified.
ir_depth_layout_any
ir_depth_layout_greater
ir_depth_layout_less
ir_depth_layout_unchanged
enum ir_expression_operation
Enumerator
ir_unop_bit_not
ir_unop_logic_not
ir_unop_neg
ir_unop_abs
ir_unop_sign
ir_unop_rcp
ir_unop_rsq
ir_unop_sqrt
ir_unop_exp
Log base e on gentype.
ir_unop_log
Natural log on gentype.
ir_unop_exp2
ir_unop_log2
ir_unop_f2i
Float-to-integer conversion.
ir_unop_f2u
Float-to-unsigned conversion.
ir_unop_i2f
Integer-to-float conversion.
ir_unop_f2b
Float-to-boolean conversion.
ir_unop_b2f
Boolean-to-float conversion.
ir_unop_i2b
int-to-boolean conversion
ir_unop_b2i
Boolean-to-int conversion.
ir_unop_u2f
Unsigned-to-float conversion.
ir_unop_i2u
Integer-to-unsigned conversion.
ir_unop_u2i
Unsigned-to-integer conversion.
ir_unop_bitcast_i2f
Bit-identical int-to-float "conversion".
ir_unop_bitcast_f2i
Bit-identical float-to-int "conversion".
ir_unop_bitcast_u2f
Bit-identical uint-to-float "conversion".
ir_unop_bitcast_f2u
Bit-identical float-to-uint "conversion".
ir_unop_any
ir_unop_trunc
ir_unop_ceil
ir_unop_floor
ir_unop_fract
ir_unop_round_even
ir_unop_sin
ir_unop_cos
ir_unop_sin_reduced
Reduced range sin.
[-pi, pi]
ir_unop_cos_reduced
Reduced range cos.
[-pi, pi]
ir_unop_dFdx
ir_unop_dFdy
ir_unop_pack_snorm_2x16
ir_unop_pack_snorm_4x8
ir_unop_pack_unorm_2x16
ir_unop_pack_unorm_4x8
ir_unop_pack_half_2x16
ir_unop_unpack_snorm_2x16
ir_unop_unpack_snorm_4x8
ir_unop_unpack_unorm_2x16
ir_unop_unpack_unorm_4x8
ir_unop_unpack_half_2x16
ir_unop_unpack_half_2x16_split_x
ir_unop_unpack_half_2x16_split_y
ir_unop_bitfield_reverse
ir_unop_bit_count
ir_unop_find_msb
ir_unop_find_lsb
ir_unop_noise
ir_last_unop
A sentinel marking the last of the unary operations.
ir_binop_add
ir_binop_sub
ir_binop_mul
ir_binop_div
ir_binop_mod
Takes one of two combinations of arguments:
mod(vecN, vecN)
mod(vecN, float)
Does not take integer types.
ir_binop_less
ir_binop_greater
ir_binop_lequal
ir_binop_gequal
ir_binop_equal
ir_binop_nequal
ir_binop_all_equal
Returns single boolean for whether all components of operands[0] equal the components of operands[1].
ir_binop_any_nequal
Returns single boolean for whether any component of operands[0] is not equal to the corresponding component of operands[1].
ir_binop_lshift
ir_binop_rshift
ir_binop_bit_and
ir_binop_bit_xor
ir_binop_bit_or
ir_binop_logic_and
ir_binop_logic_xor
ir_binop_logic_or
ir_binop_dot
ir_binop_min
ir_binop_max
ir_binop_pow
ir_binop_pack_half_2x16_split
ir_binop_bfm
ir_binop_ubo_load
Load a value the size of a given GLSL type from a uniform block.
operand0 is the ir_constant uniform block index in the linked shader. operand1 is a byte offset within the uniform block.
ir_binop_vector_extract
Extract a scalar from a vector.
operand0 is the vector operand1 is the index of the field to read from operand0
ir_last_binop
A sentinel marking the last of the binary operations.
ir_triop_lrp
ir_triop_bfi
ir_triop_bitfield_extract
ir_triop_vector_insert
Generate a value with one field of a vector changed.
operand0 is the vector operand1 is the value to write into the vector result operand2 is the index in operand0 to be modified
ir_last_triop
A sentinel marking the last of the ternary operations.
ir_quadop_bitfield_insert
ir_quadop_vector
ir_last_quadop
A sentinel marking the last of the ternary operations.
ir_last_opcode
A sentinel marking the last of all operations.
enum ir_node_type
Class tags.
Each concrete class derived from ir_instruction has a value in this enumerant. The value for the type is stored in ir_instruction::ir_type by the constructor. While using type tags is not very C++, it is extremely convenient. For example, during debugging you can simply inspect ir_instruction::ir_type to find out the actual type of the object.
In addition, it is possible to use a switch-statement based on ir_instruction::ir_type to select different behavior for different object types. For functions that have only slight differences for several object types, this allows writing very straightforward, readable code.
Enumerator
ir_type_unset
Zero is unused so that the IR validator can detect cases where ir_instruction::ir_type has not been initialized.
ir_type_variable
ir_type_assignment
ir_type_call
ir_type_constant
ir_type_dereference_array
ir_type_dereference_record
ir_type_dereference_variable
ir_type_discard
ir_type_expression
ir_type_function
ir_type_function_signature
ir_type_if
ir_type_loop
ir_type_loop_jump
ir_type_return
ir_type_swizzle
ir_type_texture
ir_type_max
maximum ir_type enum number, for validation
enum ir_texture_opcode
Texture sampling opcodes used in ir_texture.
Enumerator
ir_tex
Regular texture look-up.
ir_txb
Texture look-up with LOD bias.
ir_txl
Texture look-up with explicit LOD.
ir_txd
Texture look-up with partial derivatvies.
ir_txf
Texel fetch with explicit LOD.
ir_txf_ms
Multisample texture fetch.
ir_txs
Texture size.
ir_lod
Texture lod query.
enum ir_variable_mode
Variable storage classes.
Enumerator
ir_var_auto
Function local variables and globals.
ir_var_uniform
Variable declared as a uniform.
ir_var_shader_in
ir_var_shader_out
ir_var_function_in
ir_var_function_out
ir_var_function_inout
ir_var_const_in
"in" param that must be a constant expression
ir_var_system_value
Ex: front-face, instance-id, etc.
ir_var_temporary
Temporary variable generated during compilation.
ir_var_mode_count
Number of variable modes.
Function Documentation
const char* depth_layout_string (ir_depth_layout layout)
Convert depth layout qualifier to string.
References ir_depth_layout_any, ir_depth_layout_greater, ir_depth_layout_less, ir_depth_layout_none, and ir_depth_layout_unchanged.
Referenced by get_variable_being_redeclared().
const char * ir_function_signature::function_name () const inline
Get the name of the function for which this is a signature.
References ir_function::name.
Referenced by ir_call::callee_name(), generate_call(), ast_function_definition::hir(), ir_lower_jumps_visitor::visit(), call_link_visitor::visit_enter(), lower_discard_flow_visitor::visit_enter(), ir_validate::visit_enter(), and output_read_remover::visit_leave().