Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
hir_field_selection.cpp File Reference
#include "ir.h"
#include "program/symbol_table.h"
#include "glsl_parser_extras.h"
#include "ast.h"
#include "glsl_types.h"
Functions
ir_rvalue * _mesa_ast_field_selection_to_hir (const ast_expression *expr, exec_list *instructions, struct _mesa_glsl_parse_state *state)
Function Documentation
ir_rvalue* _mesa_ast_field_selection_to_hir (const ast_expression * expr, exec_list * instructions, struct _mesa_glsl_parse_state * state)
References _mesa_glsl_error(), ast_function_call, ir_swizzle::create(), ir_rvalue::error_value(), ast_expression::expressions, ast_node::get_location(), GLSL_TYPE_INTERFACE, GLSL_TYPE_STRUCT, ast_expression::hir(), ast_expression::identifier, ast_expression::oper, ast_expression::primary_expression, ast_expression::subexpressions, and ir_rvalue::type.
Referenced by ast_expression::hir().