Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir.cpp File Reference
#include <string.h>
#include "main/core.h"
#include "ir.h"
#include "ir_visitor.h"
#include "glsl_types.h"
Macros
#define X 1
#define R 5
#define S 9
#define I 13
Functions
static void update_rhs_swizzle (ir_swizzle_mask &m, unsigned from, unsigned to)
Modify the swizzle make to move one component to another.
const char * depth_layout_string (ir_depth_layout layout)
Convert depth layout qualifier to string.
static bool modes_match (unsigned a, unsigned b)
void visit_exec_list (exec_list *list, ir_visitor *visitor)
Apply a visitor to each IR node in a list.
static void steal_memory (ir_instruction *ir, void *new_ctx)
void reparent_ir (exec_list *list, void *mem_ctx)
static ir_rvalue * try_min_one (ir_rvalue *ir)
static ir_rvalue * try_max_zero (ir_rvalue *ir)
Variables
static const char *const operator_strs []
static const char * tex_opcode_strs [] = { "tex", "txb", "txl", "txd", "txf", "txf_ms", "txs", "lod" }
Macro Definition Documentation
#define I 13
Referenced by ir_swizzle::create().
#define R 5
Referenced by ir_swizzle::create().
#define S 9
Referenced by ir_swizzle::create().
#define X 1
Referenced by ir_swizzle::create().
Function Documentation
static bool modes_match (unsigned a, unsigned b) static
References ir_var_const_in, and ir_var_function_in.
Referenced by ir_function_signature::qualifiers_match().
void reparent_ir (exec_list * list, void * mem_ctx)
References foreach_list, steal_memory(), and visit_tree().
Referenced by compile_shader(), link_shaders(), and read_builtins().
static void steal_memory (ir_instruction * ir, void * new_ctx) static
References ir_constant::array_elements, ir_instruction::as_constant(), ir_instruction::as_variable(), ir_constant::components, ir_variable::constant_initializer, ir_variable::constant_value, ralloc_steal(), and ir_rvalue::type.
Referenced by reparent_ir().
static ir_rvalue* try_max_zero (ir_rvalue * ir) static
References ir_instruction::as_expression(), ir_builder::expr(), ir_binop_max, ir_rvalue::is_zero(), ir_expression::operands, and ir_expression::operation.
Referenced by ir_rvalue::as_rvalue_to_saturate().
static ir_rvalue* try_min_one (ir_rvalue * ir) static
References ir_instruction::as_expression(), ir_builder::expr(), ir_binop_min, ir_rvalue::is_one(), ir_expression::operands, and ir_expression::operation.
Referenced by ir_rvalue::as_rvalue_to_saturate().
static void update_rhs_swizzle (ir_swizzle_mask & m, unsigned from, unsigned to) static
Modify the swizzle make to move one component to another.
Parameters
m IR swizzle to be modified
from Component in the RHS that is to be swizzled
to Desired swizzle location of from
References ir_swizzle_mask::num_components, ir_swizzle_mask::w, ir_swizzle_mask::x, ir_swizzle_mask::y, and ir_swizzle_mask::z.
Referenced by ir_assignment::set_lhs().
void visit_exec_list (exec_list * list, ir_visitor * visitor)
Apply a visitor to each IR node in a list.
Referenced by do_lower_jumps().
Variable Documentation
const char* const operator_strs[] static
Referenced by ir_expression::get_operator(), and ir_expression::operator_string().
const char* tex_opcode_strs[] = { "tex", "txb", "txl", "txd", "txf", "txf_ms", "txs", "lod" } static
Referenced by ir_texture::get_opcode().