Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "ralloc.h"
#include "glsl_types.h"
#include "list.h"
#include "ir_visitor.h"
#include "ir_hierarchical_visitor.h"
#include "main/mtypes.h"
Data Structures
class ir_instruction
Base class of all IR instructions.
class ir_rvalue
The base class for all "values"/expression trees.
struct ir_state_slot
Description of built-in state associated with a uniform.
class ir_variable
class ir_function_signature
The representation of a function instance; may be the full definition or simply a prototype.
class ir_function
Header for tracking multiple overloaded functions with the same name.
class ir_if
IR instruction representing high-level if-statements.
class ir_loop
IR instruction representing a high-level loop structure.
class ir_assignment
class ir_expression
class ir_call
HIR instruction representing a high-level function call, containing a list of parameters and returning a value in the supplied temporary.
class ir_jump
class ir_return
class ir_loop_jump
Jump instructions used inside loops.
class ir_discard
IR instruction representing discard statements.
class ir_texture
IR instruction to sample a texture.
struct ir_swizzle_mask
class ir_swizzle
class ir_dereference
class ir_dereference_variable
class ir_dereference_array
class ir_dereference_record
union ir_constant_data
Data stored in an ir_constant.
class ir_constant
Macros
#define IR_H
Enumerations
enum ir_node_type {
ir_type_unset, ir_type_variable, ir_type_assignment, ir_type_call,
ir_type_constant, ir_type_dereference_array, ir_type_dereference_record, ir_type_dereference_variable,
ir_type_discard, ir_type_expression, ir_type_function, ir_type_function_signature,
ir_type_if, ir_type_loop, ir_type_loop_jump, ir_type_return,
ir_type_swizzle, ir_type_texture, ir_type_max
}
Class tags.
enum ir_variable_mode {
ir_var_auto = 0, ir_var_uniform, ir_var_shader_in, ir_var_shader_out,
ir_var_function_in, ir_var_function_out, ir_var_function_inout, ir_var_const_in,
ir_var_system_value, ir_var_temporary, ir_var_mode_count
}
Variable storage classes.
enum ir_depth_layout {
ir_depth_layout_none, ir_depth_layout_any, ir_depth_layout_greater, ir_depth_layout_less,
ir_depth_layout_unchanged
}
Layout qualifiers for gl_FragDepth.
enum ir_expression_operation {
ir_unop_bit_not, ir_unop_logic_not, ir_unop_neg, ir_unop_abs,
ir_unop_sign, ir_unop_rcp, ir_unop_rsq, ir_unop_sqrt,
ir_unop_exp, ir_unop_log, ir_unop_exp2, ir_unop_log2,
ir_unop_f2i, ir_unop_f2u, ir_unop_i2f, ir_unop_f2b,
ir_unop_b2f, ir_unop_i2b, ir_unop_b2i, ir_unop_u2f,
ir_unop_i2u, ir_unop_u2i, ir_unop_bitcast_i2f, ir_unop_bitcast_f2i,
ir_unop_bitcast_u2f, ir_unop_bitcast_f2u, ir_unop_any, ir_unop_trunc,
ir_unop_ceil, ir_unop_floor, ir_unop_fract, ir_unop_round_even,
ir_unop_sin, ir_unop_cos, ir_unop_sin_reduced, ir_unop_cos_reduced,
ir_unop_dFdx, ir_unop_dFdy, ir_unop_pack_snorm_2x16, ir_unop_pack_snorm_4x8,
ir_unop_pack_unorm_2x16, ir_unop_pack_unorm_4x8, ir_unop_pack_half_2x16, ir_unop_unpack_snorm_2x16,
ir_unop_unpack_snorm_4x8, ir_unop_unpack_unorm_2x16, ir_unop_unpack_unorm_4x8, ir_unop_unpack_half_2x16,
ir_unop_unpack_half_2x16_split_x, ir_unop_unpack_half_2x16_split_y, ir_unop_bitfield_reverse, ir_unop_bit_count,
ir_unop_find_msb, ir_unop_find_lsb, ir_unop_noise, ir_last_unop = ir_unop_noise,
ir_binop_add, ir_binop_sub, ir_binop_mul, ir_binop_div,
ir_binop_mod, ir_binop_less, ir_binop_greater, ir_binop_lequal,
ir_binop_gequal, ir_binop_equal, ir_binop_nequal, ir_binop_all_equal,
ir_binop_any_nequal, ir_binop_lshift, ir_binop_rshift, ir_binop_bit_and,
ir_binop_bit_xor, ir_binop_bit_or, ir_binop_logic_and, ir_binop_logic_xor,
ir_binop_logic_or, ir_binop_dot, ir_binop_min, ir_binop_max,
ir_binop_pow, ir_binop_pack_half_2x16_split, ir_binop_bfm, ir_binop_ubo_load,
ir_binop_vector_extract, ir_last_binop = ir_binop_vector_extract, ir_triop_lrp, ir_triop_bfi,
ir_triop_bitfield_extract, ir_triop_vector_insert, ir_last_triop = ir_triop_vector_insert, ir_quadop_bitfield_insert,
ir_quadop_vector, ir_last_quadop = ir_quadop_vector, ir_last_opcode = ir_quadop_vector
}
enum ir_texture_opcode {
ir_tex, ir_txb, ir_txl, ir_txd,
ir_txf, ir_txf_ms, ir_txs, ir_lod
}
Texture sampling opcodes used in ir_texture.
Functions
const char * depth_layout_string (ir_depth_layout layout)
Convert depth layout qualifier to string.
void visit_exec_list (exec_list *list, ir_visitor *visitor)
Apply a visitor to each IR node in a list.
void validate_ir_tree (exec_list *instructions)
Validate invariants on each IR node in a list.
void detect_recursion_unlinked (struct _mesa_glsl_parse_state *state, exec_list *instructions)
Detect whether an unlinked shader contains static recursion.
void detect_recursion_linked (struct gl_shader_program *prog, exec_list *instructions)
Detect whether a linked shader contains static recursion.
void clone_ir_list (void *mem_ctx, exec_list *out, const exec_list *in)
Make a clone of each IR instruction in a list.
void _mesa_glsl_initialize_variables (exec_list *instructions, struct _mesa_glsl_parse_state *state)
void _mesa_glsl_initialize_functions (_mesa_glsl_parse_state *state)
void _mesa_glsl_release_functions (void)
void reparent_ir (exec_list *list, void *mem_ctx)
void import_prototypes (const exec_list *source, exec_list *dest, struct glsl_symbol_table *symbols, void *mem_ctx)
Import function prototypes from one IR tree into another.
bool ir_has_call (ir_instruction *ir)
void do_set_program_inouts (exec_list *instructions, struct gl_program *prog, bool is_fragment_shader)
char * prototype_string (const glsl_type *return_type, const char *name, exec_list *parameters)
Generate a source prototype for a function signature.
Macro Definition Documentation
#define IR_H
Function Documentation
void _mesa_glsl_initialize_functions (_mesa_glsl_parse_state * state)
References _mesa_read_profile(), builtin_mem_ctx, builtin_profiles, functions_for_100es_frag, functions_for_100es_glsl, functions_for_100es_vert, functions_for_110_frag, functions_for_110_glsl, functions_for_110_vert, functions_for_120_frag, functions_for_120_glsl, functions_for_120_vert, functions_for_130_frag, functions_for_130_glsl, functions_for_130_vert, functions_for_140_frag, functions_for_140_glsl, functions_for_150_frag, functions_for_150_glsl, functions_for_300es_frag, functions_for_300es_glsl, functions_for_ARB_gpu_shader5_glsl, functions_for_ARB_shader_bit_encoding_glsl, functions_for_ARB_shader_texture_lod_frag, functions_for_ARB_shader_texture_lod_glsl, functions_for_ARB_shading_language_packing_glsl, functions_for_ARB_texture_cube_map_array_glsl, functions_for_ARB_texture_multisample_glsl, functions_for_ARB_texture_query_lod_frag, functions_for_ARB_texture_rectangle_glsl, functions_for_EXT_texture_array_frag, functions_for_EXT_texture_array_vert, functions_for_OES_EGL_image_external_glsl, functions_for_OES_standard_derivatives_frag, functions_for_OES_texture_3D_frag, functions_for_OES_texture_3D_vert, prototypes_for_100es_frag, prototypes_for_100es_glsl, prototypes_for_100es_vert, prototypes_for_110_frag, prototypes_for_110_glsl, prototypes_for_110_vert, prototypes_for_120_frag, prototypes_for_120_glsl, prototypes_for_120_vert, prototypes_for_130_frag, prototypes_for_130_glsl, prototypes_for_130_vert, prototypes_for_140_frag, prototypes_for_140_glsl, prototypes_for_150_frag, prototypes_for_150_glsl, prototypes_for_300es_frag, prototypes_for_300es_glsl, prototypes_for_ARB_gpu_shader5_glsl, prototypes_for_ARB_shader_bit_encoding_glsl, prototypes_for_ARB_shader_texture_lod_frag, prototypes_for_ARB_shader_texture_lod_glsl, prototypes_for_ARB_shading_language_packing_glsl, prototypes_for_ARB_texture_cube_map_array_glsl, prototypes_for_ARB_texture_multisample_glsl, prototypes_for_ARB_texture_query_lod_frag, prototypes_for_ARB_texture_rectangle_glsl, prototypes_for_EXT_texture_array_frag, prototypes_for_EXT_texture_array_vert, prototypes_for_OES_EGL_image_external_glsl, prototypes_for_OES_standard_derivatives_frag, prototypes_for_OES_texture_3D_frag, prototypes_for_OES_texture_3D_vert, and ralloc_context().
Referenced by match_function_by_name().
void _mesa_glsl_initialize_variables (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References initialize_fs_variables(), and initialize_vs_variables().
Referenced by _mesa_ast_to_hir().
void _mesa_glsl_release_functions (void)
References builtin_mem_ctx, builtin_profiles, and ralloc_free().
Referenced by _mesa_destroy_shader_compiler_caches(), and main().
void clone_ir_list (void * mem_ctx, exec_list * out, const exec_list * in)
Make a clone of each IR instruction in a list.
Parameters
in List of IR instructions that are to be cloned
out List to hold the cloned instructions
References ir_instruction::clone(), copy(), fixup_function_calls(), and foreach_list_const.
Referenced by link_intrastage_shaders(), and loop_unroll_visitor::visit_leave().
void detect_recursion_linked (struct gl_shader_program * prog, exec_list * instructions)
Detect whether a linked shader contains static recursion.
If the list of instructions is determined to contain static recursion, link_error_printf will be called to emit error messages for each function that is in the recursion cycle. In addition, gl_shader_program::LinkStatus will be set to false.
References emit_errors_linked(), has_recursion_visitor::function_hash, has_recursion_visitor::progress, remove_unlinked_functions(), and ir_hierarchical_visitor::run().
Referenced by link_shaders().
void detect_recursion_unlinked (struct _mesa_glsl_parse_state * state, exec_list * instructions)
Detect whether an unlinked shader contains static recursion.
If the list of instructions is determined to contain static recursion, _mesa_glsl_error will be called to emit error messages for each function that is in the recursion cycle.
References emit_errors_unlinked(), has_recursion_visitor::function_hash, has_recursion_visitor::progress, remove_unlinked_functions(), and ir_hierarchical_visitor::run().
Referenced by _mesa_ast_to_hir().
void do_set_program_inouts (exec_list * instructions, struct gl_program * prog, bool is_fragment_shader)
References visit_list_elements().
void import_prototypes (const exec_list * source, exec_list * dest, glsl_symbol_table * symbols, void * mem_ctx)
Import function prototypes from one IR tree into another.
Parameters
source Source instruction stream containing functions whose prototypes are to be imported
dest Destination instruction stream where new ir_function and ir_function_signature nodes will be stored
symbols Symbol table where new functions will be stored
mem_ctx ralloc memory context used for new allocations
References ir_hierarchical_visitor::run().
bool ir_has_call (ir_instruction * ir)
char* prototype_string (const glsl_type * return_type, const char * name, exec_list * parameters)
Generate a source prototype for a function signature.
Parameters
return_type Return type of the function. May be NULL.
name Name of the function.
parameters List of ir_instruction nodes representing the parameter list for the function. This may be either a formal (ir_variable) or actual (ir_rvalue) parameter list. Only the type is used.
Returns
A ralloced string representing the prototype of the function.
References foreach_list, ralloc_asprintf(), ralloc_asprintf_append(), ralloc_strcat(), and ir_variable::type.
Referenced by emit_errors_linked(), emit_errors_unlinked(), and no_matching_function_error().
void reparent_ir (exec_list * list, void * mem_ctx)
References foreach_list, steal_memory(), and visit_tree().
Referenced by compile_shader(), link_shaders(), and read_builtins().
void validate_ir_tree (exec_list * instructions)
Validate invariants on each IR node in a list.
References check_node_type(), ir_hierarchical_visitor::run(), and visit_tree().
Referenced by compile_shader(), do_optimization_passes(), link_intrastage_shaders(), and ir_reader::read().
void visit_exec_list (exec_list * list, ir_visitor * visitor)
Apply a visitor to each IR node in a list.
Referenced by do_lower_jumps().