Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_print_visitor.h File Reference
#include "ir.h"
#include "ir_visitor.h"
#include "program/symbol_table.h"
Data Structures
class ir_print_visitor
Abstract base class of visitors of IR instruction trees.
Macros
#define IR_PRINT_VISITOR_H
Functions
void _mesa_print_ir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Macro Definition Documentation
#define IR_PRINT_VISITOR_H
Function Documentation
void _mesa_print_ir (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References ir_instruction::ir_type, ir_type_function, ir_instruction::print(), and print_type().
Referenced by compile_shader(), optimize_split_arrays(), and test_optpass().