Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_set_program_inouts.cpp File Reference
Sets the InputsRead and OutputsWritten of Mesa programs.
#include "main/core.h"
#include "ir.h"
#include "ir_visitor.h"
#include "glsl_types.h"
Data Structures
class ir_set_program_inouts_visitor
Functions
static bool is_shader_inout (ir_variable *var)
static void mark (struct gl_program *prog, ir_variable *var, int offset, int len, bool is_fragment_shader)
void do_set_program_inouts (exec_list *instructions, struct gl_program *prog, bool is_fragment_shader)
Detailed Description
Sets the InputsRead and OutputsWritten of Mesa programs.
Additionally, for fragment shaders, sets the InterpQualifier array, the IsCentroid bitfield, and the UsesDFdy flag.
Mesa programs (gl_program, not gl_shader_program) have a set of flags indicating which varyings are read and written. Computing which are actually read from some sort of backend code can be tricky when variable array indexing involved. So this pass provides support for setting InputsRead and OutputsWritten right from the GLSL IR.
Function Documentation
void do_set_program_inouts (exec_list * instructions, struct gl_program * prog, bool is_fragment_shader)
References visit_list_elements().
static bool is_shader_inout (ir_variable * var) inline static
References ir_var_shader_in, ir_var_shader_out, ir_var_system_value, and ir_variable::mode.
Referenced by ir_set_program_inouts_visitor::visit(), and ir_set_program_inouts_visitor::visit_enter().
static void mark (struct gl_program * prog, ir_variable * var, int offset, int len, bool is_fragment_shader) static
References ir_variable::centroid, ir_variable::index, ir_variable::interpolation, ir_var_shader_in, ir_var_shader_out, ir_var_system_value, ir_variable::location, and ir_variable::mode.
Referenced by ir_set_program_inouts_visitor::visit(), and ir_set_program_inouts_visitor::visit_enter().