Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_clone.cpp File Reference
#include <string.h>
#include "main/compiler.h"
#include "ir.h"
#include "glsl_types.h"
#include "program/hash_table.h"
Data Structures
class fixup_ir_call_visitor
Functions
static void fixup_function_calls (struct hash_table *ht, exec_list *instructions)
void clone_ir_list (void *mem_ctx, exec_list *out, const exec_list *in)
Make a clone of each IR instruction in a list.
Function Documentation
void clone_ir_list (void * mem_ctx, exec_list * out, const exec_list * in)
Make a clone of each IR instruction in a list.
Parameters
in List of IR instructions that are to be cloned
out List to hold the cloned instructions
References ir_instruction::clone(), copy(), fixup_function_calls(), and foreach_list_const.
Referenced by link_intrastage_shaders(), and loop_unroll_visitor::visit_leave().
static void fixup_function_calls (struct hash_table * ht, exec_list * instructions) static
References ir_hierarchical_visitor::run().
Referenced by clone_ir_list().