Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_hierarchical_visitor.h File Reference
Data Structures
class ir_hierarchical_visitor
Base class of hierarchical visitors of IR instruction trees.
Macros
#define IR_HIERARCHICAL_VISITOR_H
Enumerations
enum ir_visitor_status { visit_continue, visit_continue_with_parent, visit_stop }
Enumeration values returned by visit methods to guide processing.
Functions
void visit_tree (ir_instruction *ir, void(*callback)(class ir_instruction *ir, void *data), void *data)
ir_visitor_status visit_list_elements (ir_hierarchical_visitor *v, exec_list *l, bool statement_list=true)
Process a list of nodes using a hierarchical vistor.
Macro Definition Documentation
#define IR_HIERARCHICAL_VISITOR_H
Enumeration Type Documentation
enum ir_visitor_status
Enumeration values returned by visit methods to guide processing.
Enumerator
visit_continue
Continue visiting as normal.
visit_continue_with_parent
Don't visit siblings, continue w/parent.
visit_stop
Stop visiting immediately.
Function Documentation
ir_visitor_status visit_list_elements (ir_hierarchical_visitor * v, exec_list * l, bool statement_list)
Process a list of nodes using a hierarchical vistor.
If statement_list is true (the default), this is a list of statements, so v->base_ir will be set to point to each statement just before iterating over it, and restored after iteration is complete. If statement_list is false, this is a list that appears inside a statement (e.g. a parameter list), so v->base_ir will be left alone.
Warning
This function will operate correctly if a node being processed is removed from the list. However, if nodes are added to the list after the node being processed, some of the added nodes may not be processed.
References ir_instruction::accept(), ir_hierarchical_visitor::base_ir, foreach_list_safe, and visit_continue.
Referenced by ir_function_signature::accept(), ir_function::accept(), ir_if::accept(), ir_loop::accept(), ir_call::accept(), do_algebraic(), do_constant_folding(), do_constant_propagation(), do_copy_propagation(), do_copy_propagation_elements(), do_dead_functions(), do_lower_texture_projection(), do_mat_op_to_vec(), do_noop_swizzle(), do_sampler_replacement(), do_set_program_inouts(), do_structure_splitting(), do_tree_grafting(), do_vec_index_to_cond_assign(), ir_array_reference_visitor::get_split_list(), link_uniform_blocks(), lower_clip_distance(), lower_discard(), lower_discard_flow(), lower_if_to_cond_assign(), lower_instructions(), lower_noise(), lower_output_reads(), lower_packing_builtins(), lower_quadop_vector(), lower_ubo_reference(), lower_variable_index_to_cond_assign(), lower_vector_insert(), opt_flip_matrices(), optimize_split_arrays(), flatten_named_interface_blocks_declarations::run(), ir_hierarchical_visitor::run(), ir_set_program_inouts_visitor::visit_enter(), ir_variable_refcount_visitor::visit_enter(), and ir_array_reference_visitor::visit_enter().
void visit_tree (ir_instruction * ir, void(*)(class ir_instruction *ir, void *data) callback, void * data)
References ir_instruction::accept(), ir_hierarchical_visitor::callback, and ir_hierarchical_visitor::data.
Referenced by ir_call::generate_inline(), reparent_ir(), validate_ir_tree(), and ir_if_to_cond_assign_visitor::visit_leave().