Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_optimization.h File Reference
Prototypes for optimization passes to be called by the compiler and drivers.
Macros
#define SUB_TO_ADD_NEG 0x01
#define DIV_TO_MUL_RCP 0x02
#define EXP_TO_EXP2 0x04
#define POW_TO_EXP2 0x08
#define LOG_TO_LOG2 0x10
#define MOD_TO_FRACT 0x20
#define INT_DIV_TO_MUL_RCP 0x40
#define LRP_TO_ARITH 0x80
#define BITFIELD_INSERT_TO_BFM_BFI 0x100
Enumerations
enum lower_packing_builtins_op {
LOWER_PACK_UNPACK_NONE = 0x0000, LOWER_PACK_SNORM_2x16 = 0x0001, LOWER_UNPACK_SNORM_2x16 = 0x0002, LOWER_PACK_UNORM_2x16 = 0x0004,
LOWER_UNPACK_UNORM_2x16 = 0x0008, LOWER_PACK_HALF_2x16 = 0x0010, LOWER_UNPACK_HALF_2x16 = 0x0020, LOWER_PACK_HALF_2x16_TO_SPLIT = 0x0040,
LOWER_UNPACK_HALF_2x16_TO_SPLIT = 0x0080, LOWER_PACK_SNORM_4x8 = 0x0100, LOWER_UNPACK_SNORM_4x8 = 0x0200, LOWER_PACK_UNORM_4x8 = 0x0400,
LOWER_UNPACK_UNORM_4x8 = 0x0800
}
Functions
bool do_common_optimization (exec_list *ir, bool linked, bool uniform_locations_assigned, unsigned max_unroll_iterations, const struct gl_shader_compiler_options *options)
Do the set of common optimizations passes.
bool do_algebraic (exec_list *instructions)
bool do_constant_folding (exec_list *instructions)
bool do_constant_variable (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_constant_variable_unlinked (exec_list *instructions)
bool do_copy_propagation (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_copy_propagation_elements (exec_list *instructions)
bool do_constant_propagation (exec_list *instructions)
Does a constant propagation pass on the code present in the instruction stream.
bool do_dead_code (exec_list *instructions, bool uniform_locations_assigned)
Do a dead code pass over instructions and everything that instructions references.
bool do_dead_code_local (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_dead_code_unlinked (exec_list *instructions)
Does a dead code pass on the functions present in the instruction stream.
bool do_dead_functions (exec_list *instructions)
bool opt_flip_matrices (exec_list *instructions)
bool do_function_inlining (exec_list *instructions)
bool do_lower_jumps (exec_list *instructions, bool pull_out_jumps=true, bool lower_sub_return=true, bool lower_main_return=false, bool lower_continue=false, bool lower_break=false)
bool do_lower_texture_projection (exec_list *instructions)
bool do_if_simplification (exec_list *instructions)
bool opt_flatten_nested_if_blocks (exec_list *instructions)
bool do_discard_simplification (exec_list *instructions)
bool lower_if_to_cond_assign (exec_list *instructions, unsigned max_depth=0)
bool do_mat_op_to_vec (exec_list *instructions)
bool do_noop_swizzle (exec_list *instructions)
bool do_structure_splitting (exec_list *instructions)
bool do_swizzle_swizzle (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_tree_grafting (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_vec_index_to_cond_assign (exec_list *instructions)
bool do_vec_index_to_swizzle (exec_list *instructions)
bool lower_discard (exec_list *instructions)
void lower_discard_flow (exec_list *instructions)
bool lower_instructions (exec_list *instructions, unsigned what_to_lower)
bool lower_noise (exec_list *instructions)
bool lower_variable_index_to_cond_assign (exec_list *instructions, bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform)
bool lower_quadop_vector (exec_list *instructions, bool dont_lower_swz)
bool lower_clip_distance (gl_shader *shader)
void lower_output_reads (exec_list *instructions)
bool lower_packing_builtins (exec_list *instructions, int op_mask)
Lower the builtin packing functions.
void lower_ubo_reference (struct gl_shader *shader, exec_list *instructions)
void lower_packed_varyings (void *mem_ctx, unsigned location_base, unsigned locations_used, ir_variable_mode mode, gl_shader *shader)
bool lower_vector_insert (exec_list *instructions, bool lower_nonconstant_index)
void lower_named_interface_blocks (void *mem_ctx, gl_shader *shader)
bool optimize_redundant_jumps (exec_list *instructions)
bool optimize_split_arrays (exec_list *instructions, bool linked)
ir_rvalue * compare_index_block (exec_list *instructions, ir_variable *index, unsigned base, unsigned components, void *mem_ctx)
Generate a comparison value for a block of indices.
Detailed Description
Prototypes for optimization passes to be called by the compiler and drivers.
Macro Definition Documentation
#define BITFIELD_INSERT_TO_BFM_BFI 0x100
Referenced by lower_instructions_visitor::visit_leave().
#define DIV_TO_MUL_RCP 0x02
Referenced by lower_instructions_visitor::visit_leave().
#define EXP_TO_EXP2 0x04
Referenced by lower_instructions_visitor::visit_leave().
#define INT_DIV_TO_MUL_RCP 0x40
Referenced by lower_instructions_visitor::visit_leave().
#define LOG_TO_LOG2 0x10
Referenced by lower_instructions_visitor::visit_leave().
#define LRP_TO_ARITH 0x80
Referenced by lower_instructions_visitor::visit_leave().
#define MOD_TO_FRACT 0x20
Referenced by lower_instructions_visitor::visit_leave().
#define POW_TO_EXP2 0x08
Referenced by lower_instructions_visitor::visit_leave().
#define SUB_TO_ADD_NEG 0x01
Referenced by do_common_optimization(), and lower_instructions_visitor::visit_leave().
Enumeration Type Documentation
enum lower_packing_builtins_op
See Also
class lower_packing_builtins_visitor
Enumerator
LOWER_PACK_UNPACK_NONE
LOWER_PACK_SNORM_2x16
LOWER_UNPACK_SNORM_2x16
LOWER_PACK_UNORM_2x16
LOWER_UNPACK_UNORM_2x16
LOWER_PACK_HALF_2x16
LOWER_UNPACK_HALF_2x16
LOWER_PACK_HALF_2x16_TO_SPLIT
LOWER_UNPACK_HALF_2x16_TO_SPLIT
LOWER_PACK_SNORM_4x8
LOWER_UNPACK_SNORM_4x8
LOWER_PACK_UNORM_4x8
LOWER_UNPACK_UNORM_4x8
Function Documentation
ir_rvalue* compare_index_block (exec_list * instructions, ir_variable * index, unsigned base, unsigned components, void * mem_ctx)
Generate a comparison value for a block of indices.
Lowering passes for non-constant indexing of arrays, matrices, or vectors can use this to generate blocks of index comparison values.
Parameters
instructions List where new instructions will be appended
index ir_variable containing the desired index
base Base value for this block of comparisons
components Number of unique index values to compare. This must be on the range [1, 4].
mem_ctx ralloc memory context to be used for all allocations.
Returns
An ir_rvalue that must be cloned for each use in conditional assignments, etc.
References GLSL_TYPE_INT, ir_constant_data::i, ir_binop_equal, ir_var_temporary, ir_rvalue::type, and ir_variable::type.
Referenced by ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign(), and switch_generator::linear_sequence().
bool do_algebraic (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_common_optimization (exec_list * ir, bool linked, bool uniform_locations_assigned, unsigned max_unroll_iterations, const struct gl_shader_compiler_options * options)
Do the set of common optimizations passes.
Parameters
ir List of instructions to be optimized
linked Is the shader linked? This enables optimizations passes that remove code at global scope and could cause linking to fail.
uniform_locations_assigned Have locations already been assigned for uniforms? This prevents the declarations of unused uniforms from being removed. The setting of this flag only matters if linked is true.
max_unroll_iterations Maximum number of loop iterations to be unrolled. Setting to 0 disables loop unrolling.
options The driver's preferred shader options.
References analyze_loop_variables(), do_algebraic(), do_constant_folding(), do_constant_propagation(), do_constant_variable(), do_constant_variable_unlinked(), do_copy_propagation(), do_copy_propagation_elements(), do_dead_code(), do_dead_code_local(), do_dead_code_unlinked(), do_dead_functions(), do_function_inlining(), do_if_simplification(), do_lower_jumps(), do_noop_swizzle(), do_structure_splitting(), do_swizzle_swizzle(), do_tree_grafting(), do_vec_index_to_swizzle(), loop_state::loop_found, lower_instructions(), lower_vector_insert(), opt_flatten_nested_if_blocks(), opt_flip_matrices(), optimize_redundant_jumps(), optimize_split_arrays(), set_loop_controls(), SUB_TO_ADD_NEG, and unroll_loops().
Referenced by compile_shader(), do_optimization(), and link_shaders().
bool do_constant_folding (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_constant_propagation (exec_list * instructions)
Does a constant propagation pass on the code present in the instruction stream.
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_constant_variable (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References exec_node_data.
Referenced by do_common_optimization(), do_constant_variable_unlinked(), and do_optimization().
bool do_constant_variable_unlinked (exec_list * instructions)
References ir_instruction::as_function(), ir_function_signature::body, and do_constant_variable().
Referenced by do_common_optimization(), and do_optimization().
bool do_copy_propagation (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_copy_propagation_elements (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_dead_code (exec_list * instructions, bool uniform_locations_assigned)
Do a dead code pass over instructions and everything that instructions references.
Note that this will remove assignments to globals, so it is not suitable for usage on an unlinked instruction stream.
References ir_variable_refcount_entry::assign, ir_variable_refcount_entry::assigned_count, ir_variable::constant_value, debug, ir_variable_refcount_entry::declaration, ir_variable_refcount_visitor::ht, ir_var_function_inout, ir_var_function_out, ir_var_shader_out, ir_var_uniform, ir_variable::mode, ir_variable::name, ir_variable_refcount_entry::referenced_count, ir_hierarchical_visitor::run(), and ir_variable_refcount_entry::var.
Referenced by do_common_optimization(), do_dead_code_unlinked(), do_optimization(), and link_shaders().
bool do_dead_code_local (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References call_for_basic_blocks(), and dead_code_local_basic_block().
Referenced by do_common_optimization(), and do_optimization().
bool do_dead_code_unlinked (exec_list * instructions)
Does a dead code pass on the functions present in the instruction stream.
This is suitable for use while the program is not linked, as it will ignore variable declarations (and the assignments to them) for variables with global scope.
References ir_instruction::as_function(), ir_function_signature::body, and do_dead_code().
Referenced by do_common_optimization(), and do_optimization().
bool do_dead_functions (exec_list * instructions)
References ir_instruction::as_function(), ir_function::signatures, and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_discard_simplification (exec_list * instructions)
bool do_function_inlining (exec_list * instructions)
Referenced by do_common_optimization(), and do_optimization().
bool do_if_simplification (exec_list * instructions)
Referenced by do_common_optimization(), and do_optimization().
bool do_lower_jumps (exec_list * instructions, bool pull_out_jumps = true, bool lower_sub_return = true, bool lower_main_return = false, bool lower_continue = false, bool lower_break = false)
References ir_lower_jumps_visitor::lower_break, ir_lower_jumps_visitor::lower_continue, ir_lower_jumps_visitor::lower_main_return, ir_lower_jumps_visitor::lower_sub_return, ir_lower_jumps_visitor::progress, ir_lower_jumps_visitor::pull_out_jumps, and visit_exec_list().
Referenced by do_common_optimization(), and do_optimization().
bool do_lower_texture_projection (exec_list * instructions)
References lower_texture_projection_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
bool do_mat_op_to_vec (exec_list * instructions)
References do_expression_flattening(), ir_mat_op_to_vec_visitor::made_progress, mat_op_to_vec_predicate(), and visit_list_elements().
Referenced by do_optimization().
bool do_noop_swizzle (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_structure_splitting (exec_list * instructions)
References ir_var_temporary, ralloc_array, ralloc_asprintf(), ralloc_context(), ralloc_free(), ralloc_parent(), and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_swizzle_swizzle (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
Referenced by do_common_optimization(), and do_optimization().
bool do_tree_grafting (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References call_for_basic_blocks(), and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
bool do_vec_index_to_cond_assign (exec_list * instructions)
References ir_vec_index_to_cond_assign_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
bool do_vec_index_to_swizzle (exec_list * instructions)
References ir_vec_index_to_swizzle_visitor::progress, and ir_hierarchical_visitor::run().
Referenced by do_common_optimization(), and do_optimization().
bool lower_clip_distance (gl_shader * shader)
References lower_clip_distance_visitor::new_clip_distance_var, lower_clip_distance_visitor::progress, and visit_list_elements().
Referenced by link_shaders().
bool lower_discard (exec_list * instructions)
References lower_discard_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
void lower_discard_flow (exec_list * instructions)
References ir_var_temporary, and visit_list_elements().
Referenced by link_shaders().
bool lower_if_to_cond_assign (exec_list * instructions, unsigned max_depth = 0)
References ir_if_to_cond_assign_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
bool lower_instructions (exec_list * instructions, unsigned what_to_lower)
References lower_instructions_visitor::progress, and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().
void lower_named_interface_blocks (void * mem_ctx, gl_shader * shader)
References flatten_named_interface_blocks_declarations::run().
Referenced by link_shaders().
bool lower_noise (exec_list * instructions)
References lower_noise_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
void lower_output_reads (exec_list * instructions)
References visit_list_elements().
void lower_packed_varyings (void * mem_ctx, unsigned location_base, unsigned locations_used, ir_variable_mode mode, gl_shader * shader)
References ir_function_signature::body, ir_function::matching_signature(), and lower_packed_varyings_visitor::run().
Referenced by assign_varying_locations().
bool lower_packing_builtins (exec_list * instructions, int op_mask)
Lower the builtin packing functions.
Parameters
op_mask is a bitmask of enum lower_packing_builtins_op.
References visit_list_elements().
bool lower_quadop_vector (exec_list * instructions, bool dont_lower_swz)
References lower_vector_visitor::dont_lower_swz, lower_vector_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
void lower_ubo_reference (struct gl_shader * shader, exec_list * instructions)
References visit_list_elements().
bool lower_variable_index_to_cond_assign (exec_list * instructions, bool lower_input, bool lower_output, bool lower_temp, bool lower_uniform)
References variable_index_to_cond_assign_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
bool lower_vector_insert (exec_list * instructions, bool lower_nonconstant_index)
References vector_insert_visitor::progress, and visit_list_elements().
Referenced by do_common_optimization().
bool opt_flatten_nested_if_blocks (exec_list * instructions)
Referenced by do_common_optimization().
bool opt_flip_matrices (exec_list * instructions)
References visit_list_elements().
Referenced by do_common_optimization().
bool optimize_redundant_jumps (exec_list * instructions)
Referenced by do_common_optimization(), and do_optimization().
bool optimize_split_arrays (exec_list * instructions, bool linked)
References _mesa_print_ir(), opt_array_splitting::variable_entry::components, debug, ir_array_reference_visitor::get_split_list(), ir_var_temporary, opt_array_splitting::variable_entry::mem_ctx, ir_variable::name, ralloc_array, ralloc_asprintf(), ralloc_context(), ralloc_free(), ralloc_parent(), opt_array_splitting::variable_entry::size, ir_variable::type, opt_array_splitting::variable_entry::var, ir_array_reference_visitor::variable_list, and visit_list_elements().
Referenced by do_common_optimization().