Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_basic_block.cpp File Reference
Basic block analysis of instruction streams.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_basic_block.h"
#include "glsl_types.h"
Functions
void call_for_basic_blocks (exec_list *instructions, void(*callback)(ir_instruction *first, ir_instruction *last, void *data), void *data)
Calls a user function for every basic block in the instruction stream.
Detailed Description
Basic block analysis of instruction streams.
Function Documentation
void call_for_basic_blocks (exec_list * instructions, void(*)(ir_instruction *first, ir_instruction *last, void *data) callback, void * data)
Calls a user function for every basic block in the instruction stream.
Basic block analysis is pretty easy in our IR thanks to the lack of unstructured control flow. We've got:
ir_loop (for () {}, while () {}, do {} while ()) ir_loop_jump (ir_if () {} ir_return ir_call()
Note that the basic blocks returned by this don't encompass all operations performed by the program – for example, if conditions don't get returned, nor do the assignments that will be generated for ir_call parameters.
References ir_instruction::as_call(), ir_instruction::as_function(), ir_instruction::as_if(), ir_instruction::as_jump(), ir_instruction::as_loop(), ir_function_signature::body, ir_loop::body_instructions, call_for_basic_blocks(), ir_if::else_instructions, and ir_if::then_instructions.
Referenced by call_for_basic_blocks(), do_dead_code_local(), and do_tree_grafting().