Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_function_detect_recursion.cpp File Reference
Determine whether a shader contains static recursion.
#include "main/core.h"
#include "ir.h"
#include "glsl_parser_extras.h"
#include "linker.h"
#include "program/hash_table.h"
#include "program.h"
Data Structures
struct call_node
class function
class has_recursion_visitor
Functions
static void destroy_links (exec_list *list, function *f)
static void remove_unlinked_functions (const void *key, void *data, void *closure)
Remove a function if it has either no in or no out links.
static void emit_errors_unlinked (const void *key, void *data, void *closure)
static void emit_errors_linked (const void *key, void *data, void *closure)
void detect_recursion_unlinked (struct _mesa_glsl_parse_state *state, exec_list *instructions)
Detect whether an unlinked shader contains static recursion.
void detect_recursion_linked (struct gl_shader_program *prog, exec_list *instructions)
Detect whether a linked shader contains static recursion.
Detailed Description
Determine whether a shader contains static recursion.
Consider the (possibly disjoint) graph of function calls in a shader. If a program contains recursion, this graph will contain a cycle. If a function is part of a cycle, it will have a caller and it will have a callee (it calls another function).
To detect recursion, the function call graph is constructed. The graph is repeatedly reduced by removing any function that either has no callees (leaf functions) or has no caller. Eventually the only functions that remain will be the functions in the cycles.
The GLSL spec is a bit wishy-washy about recursion.
From page 39 (page 45 of the PDF) of the GLSL 1.10 spec:
"Behavior is undefined if recursion is used. Recursion means having any
function appearing more than once at any one time in the run-time stack
of function calls. That is, a function may not call itself either
directly or indirectly. Compilers may give diagnostic messages when
this is detectable at compile time, but not all such cases can be
detected at compile time."
From page 79 (page 85 of the PDF):
"22) Should recursion be supported?
 DISCUSSION: Probably not necessary, but another example of limiting
 the language based on how it would directly map to hardware. One
 thought is that recursion would benefit ray tracing shaders. On the
 other hand, many recursion operations can also be implemented with the
 user managing the recursion through arrays. RenderMan doesn't support
 recursion. This could be added at a later date, if it proved to be
 necessary.
 RESOLVED on September 10, 2002: Implementations are not required to
 support recursion.
 CLOSED on September 10, 2002."
From page 79 (page 85 of the PDF):
"56) Is it an error for an implementation to support recursion if the
specification says recursion is not supported?
ADDED on September 10, 2002.
DISCUSSION: This issues is related to Issue (22). If we say that
recursion (or some other piece of functionality) is not supported, is
it an error for an implementation to support it? Perhaps the
specification should remain silent on these kind of things so that they
could be gracefully added later as an extension or as part of the
standard.
RESOLUTION: Languages, in general, have programs that are not
well-formed in ways a compiler cannot detect. Portability is only
ensured for well-formed programs. Detecting recursion is an example of
this. The language will say a well-formed program may not recurse, but
compilers are not forced to detect that recursion may happen.
CLOSED: November 29, 2002."
In GLSL 1.10 the behavior of recursion is undefined. Compilers don't have to reject shaders (at compile-time or link-time) that contain recursion. Instead they could work, or crash, or kill a kitten.
From page 44 (page 50 of the PDF) of the GLSL 1.20 spec:
"Recursion is not allowed, not even statically. Static recursion is
present if the static function call graph of the program contains
cycles."
This langauge clears things up a bit, but it still leaves a lot of questions unanswered.
- Is the error generated at compile-time or link-time?
- Is it an error to have a recursive function that is never statically
  called by main or any function called directly or indirectly by main?
  Technically speaking, such a function is not in the "static function
  call graph of the program" at all.
Bug:
If a shader has multiple cycles, this algorithm may erroneously complain about functions that aren't in any cycle, but are in the part of the call tree that connects them. For example, if the call graph consists of a cycle between A and B, and a cycle between D and E, and B also calls C which calls D, then this algorithm will report C as a function which "has static recursion" even though it is not part of any cycle.
A better algorithm for cycle detection that doesn't have this drawback can be found here:
http://en.wikipedia.org/wiki/Tarjan%E2%80%99s_strongly_connected_components_algorithm
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Function Documentation
static void destroy_links (exec_list * list, function * f) static
References foreach_list_safe, and call_node::func.
Referenced by remove_unlinked_functions().
void detect_recursion_linked (struct gl_shader_program * prog, exec_list * instructions)
Detect whether a linked shader contains static recursion.
If the list of instructions is determined to contain static recursion, link_error_printf will be called to emit error messages for each function that is in the recursion cycle. In addition, gl_shader_program::LinkStatus will be set to false.
References emit_errors_linked(), has_recursion_visitor::function_hash, has_recursion_visitor::progress, remove_unlinked_functions(), and ir_hierarchical_visitor::run().
Referenced by link_shaders().
void detect_recursion_unlinked (struct _mesa_glsl_parse_state * state, exec_list * instructions)
Detect whether an unlinked shader contains static recursion.
If the list of instructions is determined to contain static recursion, _mesa_glsl_error will be called to emit error messages for each function that is in the recursion cycle.
References emit_errors_unlinked(), has_recursion_visitor::function_hash, has_recursion_visitor::progress, remove_unlinked_functions(), and ir_hierarchical_visitor::run().
Referenced by _mesa_ast_to_hir().
static void emit_errors_linked (const void * key, void * data, void * closure) static
References linker_error(), prototype_string(), and ralloc_free().
Referenced by detect_recursion_linked().
static void emit_errors_unlinked (const void * key, void * data, void * closure) static
References _mesa_glsl_error(), prototype_string(), and ralloc_free().
Referenced by detect_recursion_unlinked().
static void remove_unlinked_functions (const void * key, void * data, void * closure) static
Remove a function if it has either no in or no out links.
References function::callees, function::callers, destroy_links(), call_node::func, has_recursion_visitor::function_hash, and has_recursion_visitor::progress.
Referenced by detect_recursion_linked(), and detect_recursion_unlinked().