Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_print_visitor.cpp File Reference
#include "ir_print_visitor.h"
#include "glsl_types.h"
#include "glsl_parser_extras.h"
#include "main/macros.h"
#include "program/hash_table.h"
Functions
static void print_type (const glsl_type *t)
void _mesa_print_ir (exec_list *instructions, struct _mesa_glsl_parse_state *state)
Function Documentation
void _mesa_print_ir (exec_list * instructions, struct _mesa_glsl_parse_state * state)
References ir_instruction::ir_type, ir_type_function, ir_instruction::print(), and print_type().
Referenced by compile_shader(), optimize_split_arrays(), and test_optpass().
static void print_type (const glsl_type * t) static
References GLSL_TYPE_ARRAY, and GLSL_TYPE_STRUCT.
Referenced by _mesa_print_ir(), and ir_print_visitor::visit().