Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_validate.cpp File Reference
Attempts to verify that various invariants of the IR tree are true.
#include "ir.h"
#include "ir_hierarchical_visitor.h"
#include "program/hash_table.h"
#include "glsl_types.h"
Data Structures
class ir_validate
Functions
void check_node_type (ir_instruction *ir, void *data)
void validate_ir_tree (exec_list *instructions)
Validate invariants on each IR node in a list.
Detailed Description
Attempts to verify that various invariants of the IR tree are true.
In particular, at the moment it makes sure that no single ir_instruction node except for ir_variable appears multiple times in the ir tree. ir_variable does appear multiple times: Once as a declaration in an exec_list, and multiple times as the endpoint of a dereference chain.
Function Documentation
void check_node_type (ir_instruction * ir, void * data)
References ir_instruction::as_rvalue(), ir_instruction::ir_type, ir_type_max, ir_type_unset, ir_instruction::print(), and ir_rvalue::type.
Referenced by validate_ir_tree().
void validate_ir_tree (exec_list * instructions)
Validate invariants on each IR node in a list.
References check_node_type(), ir_hierarchical_visitor::run(), and visit_tree().
Referenced by compile_shader(), do_optimization_passes(), link_intrastage_shaders(), and ir_reader::read().