Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_uniform_blocks.cpp File Reference
#include "main/core.h"
#include "ir.h"
#include "linker.h"
#include "ir_uniform.h"
#include "link_uniform_block_active_visitor.h"
#include "main/hash_table.h"
#include "program.h"
Data Structures
class ubo_visitor
class count_block_size
struct block
Functions
int link_uniform_blocks (void *mem_ctx, struct gl_shader_program *prog, struct gl_shader **shader_list, unsigned num_shaders, struct gl_uniform_block **blocks_ret)
bool link_uniform_blocks_are_compatible (const gl_uniform_block *a, const gl_uniform_block *b)
Function Documentation
int link_uniform_blocks (void * mem_ctx, struct gl_shader_program * prog, struct gl_shader ** shader_list, unsigned num_shaders, struct gl_uniform_block ** blocks_ret)
References link_uniform_block_active::array_elements, ubo_visitor::buffer_size, GLSL_INTERFACE_PACKING_PACKED, GLSL_INTERFACE_PACKING_SHARED, GLSL_INTERFACE_PACKING_STD140, link_uniform_block_active::has_instance_name, ubo_visitor::index, count_block_size::num_active_uniforms, link_uniform_block_active::num_array_elements, ubo_visitor::process(), program_resource_visitor::process(), ralloc_array, ralloc_asprintf(), ralloc_strdup(), link_uniform_block_active::type, and visit_list_elements().
Referenced by link_intrastage_shaders().
bool link_uniform_blocks_are_compatible (const gl_uniform_block * a, const gl_uniform_block * b)
Referenced by link_cross_validate_uniform_block().