Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
linker.cpp File Reference
GLSL linker implementation.
#include "main/core.h"
#include "glsl_symbol_table.h"
#include "ir.h"
#include "program.h"
#include "program/hash_table.h"
#include "linker.h"
#include "link_varyings.h"
#include "ir_optimization.h"
#include "main/shaderobj.h"
Data Structures
class find_assignment_visitor
Visitor that determines whether or not a variable is ever written.
class find_deref_visitor
Visitor that determines whether or not a variable is ever read.
class array_sizing_visitor
This class is only used in link_intrastage_shaders() below but declaring it inside that function leads to compiler warnings with some versions of gcc.
Functions
void linker_error (gl_shader_program *prog, const char *fmt,...)
void linker_warning (gl_shader_program *prog, const char *fmt,...)
long parse_program_resource_name (const GLchar *name, const GLchar **out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
void link_invalidate_variable_locations (gl_shader *sh, int input_base, int output_base)
unsigned count_attribute_slots (const glsl_type *t)
Determine the number of attribute slots required for a particular type.
bool validate_vertex_shader_executable (struct gl_shader_program *prog, struct gl_shader *shader)
Verify that a vertex shader executable meets all semantic requirements.
bool validate_fragment_shader_executable (struct gl_shader_program *prog, struct gl_shader *shader)
Verify that a fragment shader executable meets all semantic requirements.
static const char * mode_string (const ir_variable *var)
Generate a string describing the mode of a variable.
bool cross_validate_globals (struct gl_shader_program *prog, struct gl_shader **shader_list, unsigned num_shaders, bool uniforms_only)
Perform validation of global variables used across multiple shaders.
bool cross_validate_uniforms (struct gl_shader_program *prog)
Perform validation of uniforms used across multiple shader stages.
static bool interstage_cross_validate_uniform_blocks (struct gl_shader_program *prog)
Accumulates the array of prog->UniformBlocks and checks that all definitons of blocks agree on their contents.
static void populate_symbol_table (gl_shader *sh)
Populates a shaders symbol table with all global declarations.
void remap_variables (ir_instruction *inst, struct gl_shader *target, hash_table *temps)
Remap variables referenced in an instruction tree.
exec_node * move_non_declarations (exec_list *instructions, exec_node *last, bool make_copies, gl_shader *target)
Move non-declarations from one instruction stream to another.
static ir_function_signature * get_main_function_signature (gl_shader *sh)
Get the function signature for main from a shader.
static struct gl_shader * link_intrastage_shaders (void *mem_ctx, struct gl_context *ctx, struct gl_shader_program *prog, struct gl_shader **shader_list, unsigned num_shaders)
Combine a group of shaders for a single stage to generate a linked shader.
static void update_array_sizes (struct gl_shader_program *prog)
Update the sizes of linked shader uniform arrays to the maximum array index used.
int find_available_slots (unsigned used_mask, unsigned needed_count)
Find a contiguous set of available bits in a bitmask.
bool assign_attribute_or_color_locations (gl_shader_program *prog, unsigned target_index, unsigned max_index)
Assign locations for either VS inputs for FS outputs.
void demote_shader_inputs_and_outputs (gl_shader *sh, enum ir_variable_mode mode)
Demote shader inputs and outputs that are not used in other stages.
static void store_fragdepth_layout (struct gl_shader_program *prog)
Store the gl_FragDepth layout in the gl_shader_program struct.
static bool check_resources (struct gl_context *ctx, struct gl_shader_program *prog)
Validate the resources used by a program versus the implementation limits.
void link_shaders (struct gl_context *ctx, struct gl_shader_program *prog)
Detailed Description
GLSL linker implementation.
Given a set of shaders that are to be linked to generate a final program, there are three distinct stages.
In the first stage shaders are partitioned into groups based on the shader type. All shaders of a particular type (e.g., vertex shaders) are linked together.
Undefined references in each shader are resolve to definitions in another shader.
Types and qualifiers of uniforms, outputs, and global variables defined in multiple shaders with the same name are verified to be the same.
Initializers for uniforms and global variables defined in multiple shaders with the same name are verified to be the same.
The result, in the terminology of the GLSL spec, is a set of shader executables for each processing unit.
After the first stage is complete, a series of semantic checks are performed on each of the shader executables.
Each shader executable must define a main function.
Each vertex shader executable must write to gl_Position.
Each fragment shader executable must write to either gl_FragData or gl_FragColor.
In the final stage individual shader executables are linked to create a complete exectuable.
Types of uniforms defined in multiple shader stages with the same name are verified to be the same.
Initializers for uniforms defined in multiple shader stages with the same name are verified to be the same.
Types and qualifiers of outputs defined in one stage are verified to be the same as the types and qualifiers of inputs defined with the same name in a later stage.
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Function Documentation
bool assign_attribute_or_color_locations (gl_shader_program * prog, unsigned target_index, unsigned max_index)
Assign locations for either VS inputs for FS outputs.
Parameters
prog Shader program whose variables need locations assigned
target_index Selector for the program target to receive location assignmnets. Must be either MESA_SHADER_VERTEX or MESA_SHADER_FRAGMENT.
max_index Maximum number of generic locations. This corresponds to either the maximum number of draw buffers or the maximum number of generic attributes.
Returns
If locations are successfully assigned, true is returned. Otherwise an error is emitted to the shader link log and false is returned.
References ir_variable::as_variable(), count_attribute_slots(), ir_variable::explicit_location, find_available_slots(), foreach_list, ir_variable::index, ir_var_shader_in, ir_var_shader_out, ir_variable::is_unmatched_generic_inout, linker_error(), ir_variable::location, ir_variable::mode, ir_variable::name, ir_hierarchical_visitor::run(), ir_variable::type, and find_deref_visitor::variable_found().
Referenced by link_shaders().
static bool check_resources (struct gl_context * ctx, struct gl_shader_program * prog) static
Validate the resources used by a program versus the implementation limits.
References linker_error(), and linker_warning().
Referenced by link_shaders().
unsigned count_attribute_slots (const glsl_type * t)
Determine the number of attribute slots required for a particular type.
This code is here because it implements the language rules of a specific GLSL version. Since it's a property of the language and not a property of types in general, it doesn't really belong in glsl_type.
References count_attribute_slots().
Referenced by assign_attribute_or_color_locations(), assign_varying_locations(), and count_attribute_slots().
bool cross_validate_globals (struct gl_shader_program * prog, struct gl_shader ** shader_list, unsigned num_shaders, bool uniforms_only)
Perform validation of global variables used across multiple shaders.
References glsl_symbol_table::add_variable(), ir_variable::as_variable(), ir_variable::centroid, ir_constant::clone(), ir_variable::constant_initializer, ir_variable::depth_layout, ir_variable::explicit_location, foreach_list, glsl_symbol_table::get_variable(), ir_variable::has_initializer, ir_constant::has_value(), ir_variable::invariant, ir_depth_layout_none, ir_var_temporary, ir_var_uniform, linker_error(), ir_variable::location, ir_variable::mode, mode_string(), ir_variable::name, ralloc_parent(), ir_variable::type, and ir_variable::used.
Referenced by cross_validate_uniforms(), and link_intrastage_shaders().
bool cross_validate_uniforms (struct gl_shader_program * prog)
Perform validation of uniforms used across multiple shader stages.
References cross_validate_globals().
Referenced by link_shaders().
void demote_shader_inputs_and_outputs (gl_shader * sh, enum ir_variable_mode mode)
Demote shader inputs and outputs that are not used in other stages.
References ir_variable::as_variable(), foreach_list, ir_var_auto, ir_variable::is_unmatched_generic_inout, and ir_variable::mode.
Referenced by link_shaders().
int find_available_slots (unsigned used_mask, unsigned needed_count)
Find a contiguous set of available bits in a bitmask.
Parameters
used_mask Bits representing used (1) and unused (0) locations
needed_count Number of contiguous bits needed.
Returns
Base location of the available bits on success or -1 on failure.
Referenced by assign_attribute_or_color_locations().
static ir_function_signature* get_main_function_signature (gl_shader * sh) static
Get the function signature for main from a shader.
References ir_function_signature::is_defined, and ir_function::matching_signature().
Referenced by link_intrastage_shaders().
static bool interstage_cross_validate_uniform_blocks (struct gl_shader_program * prog) static
Accumulates the array of prog->UniformBlocks and checks that all definitons of blocks agree on their contents.
References link_cross_validate_uniform_block(), linker_error(), and ralloc_array.
Referenced by link_shaders().
static struct gl_shader* link_intrastage_shaders (void * mem_ctx, struct gl_context * ctx, struct gl_shader_program * prog, struct gl_shader ** shader_list, unsigned num_shaders) static read
Combine a group of shaders for a single stage to generate a linked shader.
Note
If this function is supplied a single shader, it is cloned, and the new shader is returned.
References ir_function::as_function(), ir_function_signature::body, clone_ir_list(), cross_validate_globals(), ir_function::exact_matching_signature(), foreach_list, get_main_function_signature(), ir_function_signature::is_builtin, ir_function_signature::is_defined, link_function_calls(), link_uniform_blocks(), linker_error(), main(), move_non_declarations(), ir_function::name, ir_function_signature::parameters, populate_symbol_table(), ralloc_steal(), ir_hierarchical_visitor::run(), validate_intrastage_interface_blocks(), and validate_ir_tree().
Referenced by link_shaders().
void link_invalidate_variable_locations (gl_shader * sh, int input_base, int output_base)
References ir_variable::as_variable(), ir_variable::explicit_location, foreach_list, ir_var_shader_in, ir_var_shader_out, ir_variable::is_unmatched_generic_inout, ir_variable::location, ir_variable::location_frac, and ir_variable::mode.
Referenced by link_shaders().
void link_shaders (struct gl_context * ctx, struct gl_shader_program * prog)
References _mesa_reference_shader(), assign_attribute_or_color_locations(), assign_varying_locations(), check_resources(), cross_validate_outputs_to_inputs(), cross_validate_uniforms(), demote_shader_inputs_and_outputs(), detect_recursion_linked(), do_common_optimization(), do_dead_code(), interstage_cross_validate_uniform_blocks(), ir_var_shader_in, ir_var_shader_out, link_assign_uniform_locations(), link_intrastage_shaders(), link_invalidate_variable_locations(), linker_error(), lower_clip_distance(), lower_discard_flow(), lower_named_interface_blocks(), parse_tfeedback_decls(), ralloc_array, ralloc_context(), ralloc_free(), ralloc_strdup(), reparent_ir(), store_fragdepth_layout(), store_tfeedback_info(), update_array_sizes(), validate_fragment_shader_executable(), validate_interstage_interface_blocks(), and validate_vertex_shader_executable().
Referenced by main().
void linker_error (gl_shader_program * prog, const char * fmt, ...)
Referenced by assign_attribute_or_color_locations(), tfeedback_decl::assign_location(), assign_varying_locations(), check_resources(), cross_validate_globals(), cross_validate_outputs_to_inputs(), emit_errors_linked(), tfeedback_decl::find_candidate(), interstage_cross_validate_uniform_blocks(), link_intrastage_shaders(), link_shaders(), parse_tfeedback_decls(), tfeedback_decl::store(), validate_fragment_shader_executable(), validate_vertex_shader_executable(), link_uniform_block_active_visitor::visit(), link_uniform_block_active_visitor::visit_enter(), and call_link_visitor::visit_enter().
void linker_warning (gl_shader_program * prog, const char * fmt, ...)
Referenced by assign_varying_locations(), and check_resources().
static const char* mode_string (const ir_variable * var) static
Generate a string describing the mode of a variable.
References ir_var_auto, ir_var_const_in, ir_var_shader_in, ir_var_shader_out, ir_var_temporary, ir_var_uniform, ir_variable::mode, and ir_variable::read_only.
Referenced by cross_validate_globals().
exec_node* move_non_declarations (exec_list * instructions, exec_node * last, bool make_copies, gl_shader * target)
Move non-declarations from one instruction stream to another.
The intended usage pattern of this function is to pass the pointer to the head sentinel of a list (i.e., a pointer to the list cast to an exec_node pointer) for last and false for make_copies on the first call. Successive calls pass the return value of the previous call for last and true for make_copies.
Parameters
instructions Source instruction stream
last Instruction after which new instructions should be inserted in the target instruction stream
make_copies Flag selecting whether instructions in instructions should be copied (via ir_instruction::clone) into the target list or moved.
Returns
The new "last" instruction in the target instruction stream. This pointer is suitable for use as the last parameter of a later call to this function.
References ir_instruction::as_assignment(), ir_instruction::as_call(), ir_instruction::as_function(), ir_instruction::as_if(), ir_instruction::as_variable(), ir_instruction::clone(), foreach_list_safe, ir_var_temporary, ir_variable::mode, and remap_variables().
Referenced by link_intrastage_shaders().
long parse_program_resource_name (const GLchar * name, const GLchar ** out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
If an array index is present, out_base_name_end is set to point to the "[" that precedes the array index, and the array index itself is returned as a long.
If no array index is present (or if the array index is negative or mal-formed), out_base_name_end, is set to point to the null terminator at the end of the input string, and -1 is returned.
Only the final array index is parsed; if the string contains other array indices (or structure field accesses), they are left in the base name.
No attempt is made to check that the base name is properly formed; typically the caller will look up the base name in a hash table, so ill-formed base names simply turn into hash table lookup failures.
Referenced by tfeedback_decl::init().
static void populate_symbol_table (gl_shader * sh) static
Populates a shaders symbol table with all global declarations.
References ir_instruction::as_function(), ir_instruction::as_variable(), and foreach_list.
Referenced by link_intrastage_shaders().
void remap_variables (ir_instruction * inst, struct gl_shader * target, hash_table * temps)
Remap variables referenced in an instruction tree.
This is used when instruction trees are cloned from one shader and placed in another. These trees will contain references to ir_variable nodes that do not exist in the target shader. This function finds these ir_variable references and replaces the references with matching variables in the target shader.
If there is no matching variable in the target shader, a clone of the ir_variable is made and added to the target shader. The new variable is added to both the instruction stream and the symbol table.
Parameters
inst IR tree that is to be processed.
symbols Symbol table containing global scope symbols in the linked shader.
instructions Instruction stream where new variable declarations should be added.
References ir_instruction::accept(), ir_variable::clone(), copy(), ir_var_temporary, ir_variable::mode, ir_variable::name, ir_dereference_variable::var, ir_hierarchical_visitor::visit(), and visit_continue.
Referenced by move_non_declarations().
static void store_fragdepth_layout (struct gl_shader_program * prog) static
Store the gl_FragDepth layout in the gl_shader_program struct.
References ir_variable::as_variable(), ir_variable::depth_layout, foreach_list, ir_depth_layout_any, ir_depth_layout_greater, ir_depth_layout_less, ir_depth_layout_none, ir_depth_layout_unchanged, ir_var_shader_out, ir_variable::mode, and ir_variable::name.
Referenced by link_shaders().
static void update_array_sizes (struct gl_shader_program * prog) static
Update the sizes of linked shader uniform arrays to the maximum array index used.
From page 81 (page 95 of the PDF) of the OpenGL 2.1 spec:
If one or more elements of an array are active,
GetActiveUniform will return the name of the array in name,
subject to the restrictions listed above. The type of the array
is returned in type. The size parameter contains the highest
array element index used, plus one. The compiler or linker
determines the highest index used.  There will be only one
active uniform reported by the GL per uniform array.
References ir_variable::as_variable(), foreach_list, ir_var_shader_in, ir_var_shader_out, ir_var_uniform, ir_variable::is_in_uniform_block(), ir_variable::max_array_access, ir_variable::mode, ir_variable::name, ir_variable::num_state_slots, and ir_variable::type.
Referenced by link_shaders().
bool validate_fragment_shader_executable (struct gl_shader_program * prog, struct gl_shader * shader)
Verify that a fragment shader executable meets all semantic requirements.
Parameters
shader Fragment shader executable to be verified
References linker_error(), ir_hierarchical_visitor::run(), and find_assignment_visitor::variable_found().
Referenced by link_shaders().
bool validate_vertex_shader_executable (struct gl_shader_program * prog, struct gl_shader * shader)
Verify that a vertex shader executable meets all semantic requirements.
Also sets prog->Vert.UsesClipDistance and prog->Vert.ClipDistanceArraySize as a side effect.
Parameters
shader Vertex shader executable to be verified
References linker_error(), ir_hierarchical_visitor::run(), ir_variable::type, and find_assignment_visitor::variable_found().
Referenced by link_shaders().