Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_interface_blocks.cpp File Reference
Linker support for GLSL's interface blocks.
#include "ir.h"
#include "glsl_symbol_table.h"
#include "linker.h"
#include "main/macros.h"
Functions
bool validate_intrastage_interface_blocks (const gl_shader **shader_list, unsigned num_shaders)
bool validate_interstage_interface_blocks (const gl_shader *producer, const gl_shader *consumer)
Detailed Description
Linker support for GLSL's interface blocks.
Function Documentation
bool validate_interstage_interface_blocks (const gl_shader * producer, const gl_shader * consumer)
References glsl_symbol_table::add_interface(), ir_variable::as_variable(), foreach_list, glsl_symbol_table::get_interface(), ir_variable::interface_type, ir_var_shader_in, ir_var_shader_out, ir_var_uniform, and ir_variable::mode.
Referenced by link_shaders().
bool validate_intrastage_interface_blocks (const gl_shader ** shader_list, unsigned num_shaders)
References glsl_symbol_table::add_interface(), ir_variable::as_variable(), foreach_list, glsl_symbol_table::get_interface(), ir_variable::interface_type, and ir_variable::mode.
Referenced by link_intrastage_shaders().