Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_uniform_block_active_visitor.cpp File Reference
#include "link_uniform_block_active_visitor.h"
#include "program.h"
Functions
link_uniform_block_active * process_block (void *mem_ctx, struct hash_table *ht, ir_variable *var)
Function Documentation
link_uniform_block_active* process_block (void * mem_ctx, struct hash_table * ht, ir_variable * var)
References link_uniform_block_active::has_instance_name, ir_variable::interface_type, ir_variable::is_interface_instance(), rzalloc, link_uniform_block_active::type, and ir_variable::type.
Referenced by link_uniform_block_active_visitor::visit(), and link_uniform_block_active_visitor::visit_enter().