Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_varyings.h File Reference
Linker functions related specifically to linking varyings between shader stages.
#include "main/glheader.h"
Data Structures
struct tfeedback_candidate
Data structure describing a varying which is available for use in transform feedback.
class tfeedback_decl
Data structure tracking information about a transform feedback declaration during linking.
Macros
#define GLSL_LINK_VARYINGS_H
Functions
bool cross_validate_outputs_to_inputs (struct gl_shader_program *prog, gl_shader *producer, gl_shader *consumer)
Validate that outputs from one stage match inputs of another.
bool parse_tfeedback_decls (struct gl_context *ctx, struct gl_shader_program *prog, const void *mem_ctx, unsigned num_names, char **varying_names, tfeedback_decl *decls)
Parse all the transform feedback declarations that were passed to glTransformFeedbackVaryings() and store them in tfeedback_decl objects.
bool store_tfeedback_info (struct gl_context *ctx, struct gl_shader_program *prog, unsigned num_tfeedback_decls, tfeedback_decl *tfeedback_decls)
Store transform feedback location assignments into prog->LinkedTransformFeedback based on the data stored in tfeedback_decls.
bool assign_varying_locations (struct gl_context *ctx, void *mem_ctx, struct gl_shader_program *prog, gl_shader *producer, gl_shader *consumer, unsigned num_tfeedback_decls, tfeedback_decl *tfeedback_decls)
Assign locations for all variables that are produced in one pipeline stage (the "producer") and consumed in the next stage (the "consumer").
Detailed Description
Linker functions related specifically to linking varyings between shader stages.
Macro Definition Documentation
#define GLSL_LINK_VARYINGS_H
Function Documentation
bool assign_varying_locations (struct gl_context * ctx, void * mem_ctx, struct gl_shader_program * prog, gl_shader * producer, gl_shader * consumer, unsigned num_tfeedback_decls, tfeedback_decl * tfeedback_decls)
Assign locations for all variables that are produced in one pipeline stage (the "producer") and consumed in the next stage (the "consumer").
Variables produced by the producer may also be consumed by transform feedback.
Parameters
num_tfeedback_decls is the number of declarations indicating variables that may be consumed by transform feedback.
tfeedback_decls is a pointer to an array of tfeedback_decl objects representing the result of parsing the strings passed to glTransformFeedbackVaryings(). assign_location() will be called for each of these objects that matches one of the outputs of the producer.
When num_tfeedback_decls is nonzero, it is permissible for the consumer to be NULL. In this case, varying locations are assigned solely based on the requirements of transform feedback.
References ir_variable::as_variable(), varying_matches::assign_locations(), count_attribute_slots(), tfeedback_decl::find_candidate(), foreach_list, ir_variable::interface_type, ir_var_auto, ir_var_shader_in, ir_var_shader_out, ir_variable::is_unmatched_generic_inout, is_varying_var(), linker_error(), linker_warning(), lower_packed_varyings(), ir_variable::mode, ir_variable::name, tfeedback_candidate_generator::process(), ralloc_asprintf(), ralloc_strdup(), varying_matches::record(), varying_matches::store_locations(), tfeedback_candidate::toplevel_var, and ir_variable::type.
Referenced by link_shaders().
bool cross_validate_outputs_to_inputs (struct gl_shader_program * prog, gl_shader * producer, gl_shader * consumer)
Validate that outputs from one stage match inputs of another.
References glsl_symbol_table::add_variable(), ir_variable::as_variable(), ir_variable::centroid, foreach_list, glsl_symbol_table::get_variable(), ir_variable::interpolation, ir_variable::interpolation_string(), ir_variable::invariant, ir_var_shader_in, ir_var_shader_out, linker_error(), ir_variable::mode, ir_variable::name, and ir_variable::type.
Referenced by link_shaders().
bool parse_tfeedback_decls (struct gl_context * ctx, struct gl_shader_program * prog, const void * mem_ctx, unsigned num_names, char ** varying_names, tfeedback_decl * decls)
Parse all the transform feedback declarations that were passed to glTransformFeedbackVaryings() and store them in tfeedback_decl objects.
If an error occurs, the error is reported through linker_error() and false is returned.
References tfeedback_decl::init(), tfeedback_decl::is_same(), and linker_error().
Referenced by link_shaders().
bool store_tfeedback_info (struct gl_context * ctx, struct gl_shader_program * prog, unsigned num_tfeedback_decls, tfeedback_decl * tfeedback_decls)
Store transform feedback location assignments into prog->LinkedTransformFeedback based on the data stored in tfeedback_decls.
If an error occurs, the error is reported through linker_error() and false is returned.
References ralloc_free(), and rzalloc_array.
Referenced by link_shaders().