Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_uniforms.cpp File Reference
Assign locations for GLSL uniforms.
#include "main/core.h"
#include "ir.h"
#include "linker.h"
#include "ir_uniform.h"
#include "glsl_symbol_table.h"
#include "program/hash_table.h"
#include "program.h"
Data Structures
class count_uniform_size
Class to help calculate the storage requirements for a set of uniforms.
class parcel_out_uniform_storage
Class to help parcel out pieces of backing storage to uniforms.
Functions
static unsigned values_for_type (const glsl_type *type)
Count the backing storage requirements for a type.
int link_cross_validate_uniform_block (void *mem_ctx, struct gl_uniform_block **linked_blocks, unsigned int *num_linked_blocks, struct gl_uniform_block *new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
static void link_update_uniform_buffer_variables (struct gl_shader *shader)
Walks the IR and update the references to uniform blocks in the ir_variables to point at linked shader's list (previously, they would point at the uniform block list in one of the pre-linked shaders).
void link_assign_uniform_block_offsets (struct gl_shader *shader)
void link_assign_uniform_locations (struct gl_shader_program *prog)
Detailed Description
Assign locations for GLSL uniforms.
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Function Documentation
void link_assign_uniform_block_offsets (struct gl_shader * shader)
void link_assign_uniform_locations (struct gl_shader_program * prog)
References ir_variable::as_variable(), foreach_list, ir_var_uniform, link_set_uniform_initializers(), link_update_uniform_buffer_variables(), ir_variable::mode, ir_variable::name, count_uniform_size::num_active_uniforms, count_uniform_size::num_shader_samplers, count_uniform_size::num_shader_uniform_components, count_uniform_size::num_values, count_uniform_size::process(), ralloc_free(), rzalloc_array, parcel_out_uniform_storage::set_and_process(), parcel_out_uniform_storage::shader_samplers_used, parcel_out_uniform_storage::shader_shadow_samplers, count_uniform_size::start_shader(), parcel_out_uniform_storage::start_shader(), parcel_out_uniform_storage::targets, ir_variable::type, and parcel_out_uniform_storage::values.
Referenced by link_shaders().
int link_cross_validate_uniform_block (void * mem_ctx, struct gl_uniform_block ** linked_blocks, unsigned int * num_linked_blocks, struct gl_uniform_block * new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
Returns the index of the new block in the array.
References link_uniform_blocks_are_compatible(), ralloc_array, ralloc_strdup(), and reralloc.
Referenced by interstage_cross_validate_uniform_blocks().
static void link_update_uniform_buffer_variables (struct gl_shader * shader) static
Walks the IR and update the references to uniform blocks in the ir_variables to point at linked shader's list (previously, they would point at the uniform block list in one of the pre-linked shaders).
References ir_variable::as_variable(), foreach_list, ir_var_uniform, ir_variable::is_in_uniform_block(), ir_variable::is_interface_instance(), ir_variable::location, ir_variable::mode, ir_variable::name, and ir_variable::type.
Referenced by link_assign_uniform_locations().
static unsigned values_for_type (const glsl_type * type) static
Count the backing storage requirements for a type.