Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_uniform_initializers.cpp File Reference
#include "main/core.h"
#include "ir.h"
#include "linker.h"
#include "ir_uniform.h"
#include "glsl_symbol_table.h"
#include "program/hash_table.h"
Namespaces
namespace linker
Functions
gl_uniform_storage * linker::get_storage (gl_uniform_storage *storage, unsigned num_storage, const char *name)
void linker::copy_constant_to_storage (union gl_constant_value *storage, const ir_constant *val, const enum glsl_base_type base_type, const unsigned int elements)
void linker::set_uniform_initializer (void *mem_ctx, gl_shader_program *prog, const char *name, const glsl_type *type, ir_constant *val)
void link_set_uniform_initializers (struct gl_shader_program *prog)
Function Documentation
void link_set_uniform_initializers (struct gl_shader_program * prog)
References ir_variable::as_variable(), ir_variable::constant_value, foreach_list, ir_var_uniform, ir_variable::mode, ir_variable::name, ralloc_context(), ralloc_free(), linker::set_uniform_initializer(), and ir_variable::type.
Referenced by link_assign_uniform_locations().