Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
link_functions.cpp File Reference
#include "main/core.h"
#include "glsl_symbol_table.h"
#include "glsl_parser_extras.h"
#include "ir.h"
#include "program.h"
#include "program/hash_table.h"
#include "linker.h"
Data Structures
class call_link_visitor
Functions
static ir_function_signature * find_matching_signature (const char *name, const exec_list *actual_parameters, gl_shader **shader_list, unsigned num_shaders, bool use_builtin)
Searches a list of shaders for a particular function definition.
bool link_function_calls (gl_shader_program *prog, gl_shader *main, gl_shader **shader_list, unsigned num_shaders)
Function Documentation
ir_function_signature * find_matching_signature (const char * name, const exec_list * actual_parameters, gl_shader ** shader_list, unsigned num_shaders, bool use_builtin) static
Searches a list of shaders for a particular function definition.
References ir_function_signature::is_builtin, ir_function_signature::is_defined, and ir_function::matching_signature().
Referenced by call_link_visitor::visit_enter().
bool link_function_calls (gl_shader_program * prog, gl_shader * main, gl_shader ** shader_list, unsigned num_shaders)
References ir_hierarchical_visitor::run(), and call_link_visitor::success.
Referenced by link_intrastage_shaders().