Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
linker.h File Reference
Data Structures
class program_resource_visitor
Class for processing all of the leaf fields of a variable that corresponds to a program resource.
Macros
#define GLSL_LINKER_H
Functions
bool link_function_calls (gl_shader_program *prog, gl_shader *main, gl_shader **shader_list, unsigned num_shaders)
void link_invalidate_variable_locations (gl_shader *sh, enum ir_variable_mode mode, int generic_base)
void link_assign_uniform_locations (struct gl_shader_program *prog)
void link_set_uniform_initializers (struct gl_shader_program *prog)
int link_cross_validate_uniform_block (void *mem_ctx, struct gl_uniform_block **linked_blocks, unsigned int *num_linked_blocks, struct gl_uniform_block *new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
void link_assign_uniform_block_offsets (struct gl_shader *shader)
bool link_uniform_blocks_are_compatible (const gl_uniform_block *a, const gl_uniform_block *b)
int link_uniform_blocks (void *mem_ctx, struct gl_shader_program *prog, struct gl_shader **shader_list, unsigned num_shaders, struct gl_uniform_block **blocks_ret)
bool validate_intrastage_interface_blocks (const gl_shader **shader_list, unsigned num_shaders)
bool validate_interstage_interface_blocks (const gl_shader *producer, const gl_shader *consumer)
void linker_error (gl_shader_program *prog, const char *fmt,...)
void linker_warning (gl_shader_program *prog, const char *fmt,...)
unsigned count_attribute_slots (const glsl_type *t)
Determine the number of attribute slots required for a particular type.
Macro Definition Documentation
#define GLSL_LINKER_H
Function Documentation
unsigned count_attribute_slots (const glsl_type * t)
Determine the number of attribute slots required for a particular type.
This code is here because it implements the language rules of a specific GLSL version. Since it's a property of the language and not a property of types in general, it doesn't really belong in glsl_type.
References count_attribute_slots().
Referenced by assign_attribute_or_color_locations(), assign_varying_locations(), and count_attribute_slots().
void link_assign_uniform_block_offsets (struct gl_shader * shader)
void link_assign_uniform_locations (struct gl_shader_program * prog)
References ir_variable::as_variable(), foreach_list, ir_var_uniform, link_set_uniform_initializers(), link_update_uniform_buffer_variables(), ir_variable::mode, ir_variable::name, count_uniform_size::num_active_uniforms, count_uniform_size::num_shader_samplers, count_uniform_size::num_shader_uniform_components, count_uniform_size::num_values, count_uniform_size::process(), ralloc_free(), rzalloc_array, parcel_out_uniform_storage::set_and_process(), parcel_out_uniform_storage::shader_samplers_used, parcel_out_uniform_storage::shader_shadow_samplers, count_uniform_size::start_shader(), parcel_out_uniform_storage::start_shader(), parcel_out_uniform_storage::targets, ir_variable::type, and parcel_out_uniform_storage::values.
Referenced by link_shaders().
int link_cross_validate_uniform_block (void * mem_ctx, struct gl_uniform_block ** linked_blocks, unsigned int * num_linked_blocks, struct gl_uniform_block * new_block)
Merges a uniform block into an array of uniform blocks that may or may not already contain a copy of it.
Returns the index of the new block in the array.
References link_uniform_blocks_are_compatible(), ralloc_array, ralloc_strdup(), and reralloc.
Referenced by interstage_cross_validate_uniform_blocks().
bool link_function_calls (gl_shader_program * prog, gl_shader * main, gl_shader ** shader_list, unsigned num_shaders)
References ir_hierarchical_visitor::run(), and call_link_visitor::success.
Referenced by link_intrastage_shaders().
void link_invalidate_variable_locations (gl_shader * sh, enum ir_variable_mode mode, int generic_base)
void link_set_uniform_initializers (struct gl_shader_program * prog)
References ir_variable::as_variable(), ir_variable::constant_value, foreach_list, ir_var_uniform, ir_variable::mode, ir_variable::name, ralloc_context(), ralloc_free(), linker::set_uniform_initializer(), and ir_variable::type.
Referenced by link_assign_uniform_locations().
int link_uniform_blocks (void * mem_ctx, struct gl_shader_program * prog, struct gl_shader ** shader_list, unsigned num_shaders, struct gl_uniform_block ** blocks_ret)
References link_uniform_block_active::array_elements, ubo_visitor::buffer_size, GLSL_INTERFACE_PACKING_PACKED, GLSL_INTERFACE_PACKING_SHARED, GLSL_INTERFACE_PACKING_STD140, link_uniform_block_active::has_instance_name, ubo_visitor::index, count_block_size::num_active_uniforms, link_uniform_block_active::num_array_elements, ubo_visitor::process(), program_resource_visitor::process(), ralloc_array, ralloc_asprintf(), ralloc_strdup(), link_uniform_block_active::type, and visit_list_elements().
Referenced by link_intrastage_shaders().
bool link_uniform_blocks_are_compatible (const gl_uniform_block * a, const gl_uniform_block * b)
Referenced by link_cross_validate_uniform_block().
void linker_error (gl_shader_program * prog, const char * fmt, ...)
References ralloc_strcat(), and ralloc_vasprintf_append().
Referenced by assign_attribute_or_color_locations(), tfeedback_decl::assign_location(), assign_varying_locations(), check_resources(), cross_validate_globals(), cross_validate_outputs_to_inputs(), emit_errors_linked(), tfeedback_decl::find_candidate(), interstage_cross_validate_uniform_blocks(), link_intrastage_shaders(), link_shaders(), parse_tfeedback_decls(), tfeedback_decl::store(), validate_fragment_shader_executable(), validate_vertex_shader_executable(), link_uniform_block_active_visitor::visit(), link_uniform_block_active_visitor::visit_enter(), and call_link_visitor::visit_enter().
void linker_warning (gl_shader_program * prog, const char * fmt, ...)
References ralloc_strcat(), and ralloc_vasprintf_append().
Referenced by assign_varying_locations(), and check_resources().
bool validate_interstage_interface_blocks (const gl_shader * producer, const gl_shader * consumer)
References glsl_symbol_table::add_interface(), ir_variable::as_variable(), foreach_list, glsl_symbol_table::get_interface(), ir_variable::interface_type, ir_var_shader_in, ir_var_shader_out, ir_var_uniform, and ir_variable::mode.
Referenced by link_shaders().
bool validate_intrastage_interface_blocks (const gl_shader ** shader_list, unsigned num_shaders)
References glsl_symbol_table::add_interface(), ir_variable::as_variable(), foreach_list, glsl_symbol_table::get_interface(), ir_variable::interface_type, and ir_variable::mode.
Referenced by link_intrastage_shaders().