Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
loop_analysis.cpp File Reference
#include "glsl_types.h"
#include "loop_analysis.h"
#include "ir_hierarchical_visitor.h"
Data Structures
class loop_analysis
class examine_rhs
Functions
static bool is_loop_terminator (ir_if *ir)
Detect whether an if-statement is a loop terminating condition.
static bool all_expression_operands_are_loop_constant (ir_rvalue *, hash_table *)
static ir_rvalue * get_basic_induction_increment (ir_assignment *, hash_table *)
loop_state * analyze_loop_variables (exec_list *instructions)
Analyze and classify all variables used in all loops in the instruction list.
Function Documentation
bool all_expression_operands_are_loop_constant (ir_rvalue * ir, hash_table * variables) static
References ir_rvalue::accept(), and examine_rhs::only_uses_loop_constants.
Referenced by loop_analysis::visit_leave().
loop_state* analyze_loop_variables (exec_list * instructions)
Analyze and classify all variables used in all loops in the instruction list.
References loop_analysis::loops, and ir_hierarchical_visitor::run().
Referenced by do_common_optimization().
ir_rvalue * get_basic_induction_increment (ir_assignment * ir, hash_table * var_hash) static
References ir_instruction::as_constant(), ir_instruction::as_expression(), ir_rvalue::clone(), ir_binop_add, ir_binop_sub, ir_unop_neg, loop_variable::is_loop_constant(), ir_assignment::lhs, ir_expression::operands, ir_expression::operation, ralloc_parent(), ir_assignment::rhs, ir_rvalue::type, ir_rvalue::variable_referenced(), and ir_dereference::variable_referenced().
Referenced by loop_analysis::visit_leave().
bool is_loop_terminator (ir_if * ir) static
Detect whether an if-statement is a loop terminating condition.
Detects if-statements of the form
(if (expression bool ...) (break))
References ir_if::else_instructions, ir_instruction::ir_type, ir_type_loop_jump, ir_loop_jump::jump_break, ir_loop_jump::mode, and ir_if::then_instructions.
Referenced by loop_analysis::visit_leave().