Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
loop_unroll.cpp File Reference
#include "glsl_types.h"
#include "loop_analysis.h"
#include "ir_hierarchical_visitor.h"
Data Structures
class loop_unroll_visitor
class loop_unroll_count
Functions
static bool is_break (ir_instruction *ir)
bool unroll_loops (exec_list *instructions, loop_state *ls, unsigned max_iterations)
Function Documentation
static bool is_break (ir_instruction * ir) static
References ir_instruction::ir_type, and ir_type_loop_jump.
Referenced by ir_lower_jumps_visitor::get_jump_strength(), and loop_unroll_visitor::visit_leave().
bool unroll_loops (exec_list * instructions, loop_state * ls, unsigned max_iterations)
References loop_unroll_visitor::progress, and ir_hierarchical_visitor::run().
Referenced by do_common_optimization().