Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
loop_controls.cpp File Reference
#include <limits.h>
#include "main/compiler.h"
#include "glsl_types.h"
#include "loop_analysis.h"
#include "ir_hierarchical_visitor.h"
Data Structures
class loop_control_visitor
Functions
ir_rvalue * find_initial_value (ir_loop *loop, ir_variable *var)
Find an initializer of a variable outside a loop.
int calculate_iterations (ir_rvalue *from, ir_rvalue *to, ir_rvalue *increment, enum ir_expression_operation op)
bool set_loop_controls (exec_list *instructions, loop_state *ls)
Fill in loop control fields.
Function Documentation
int calculate_iterations (ir_rvalue * from, ir_rvalue * to, ir_rvalue * increment, enum ir_expression_operation op)
References ir_builder::add(), ir_rvalue::constant_expression_value(), ir_expression::constant_expression_value(), ir_builder::div(), ir_constant::get_bool_component(), ir_constant::get_int_component(), ir_binop_add, ir_binop_div, ir_binop_mul, ir_binop_sub, ir_unop_f2i, ir_builder::mul(), ralloc_context(), ralloc_free(), ir_builder::sub(), and ir_rvalue::type.
Referenced by loop_control_visitor::visit_leave().
ir_rvalue* find_initial_value (ir_loop * loop, ir_variable * var)
Find an initializer of a variable outside a loop.
Works backwards from the loop to find the pre-loop value of the variable. This is used, for example, to find the initial value of loop induction variables.
Parameters
loop Loop where var is an induction variable
var Variable whose initializer is to be found
Returns
The ir_rvalue assigned to the variable outside the loop. May return NULL if no initializer can be found.
References ir_instruction::as_assignment(), ir_builder::assign(), ir_assignment::condition, ir_instruction::ir_type, ir_type_assignment, ir_type_call, ir_type_function, ir_type_function_signature, ir_type_if, ir_type_loop, ir_type_loop_jump, ir_type_return, ir_assignment::lhs, exec_node::prev, ir_assignment::rhs, and ir_rvalue::whole_variable_referenced().
Referenced by loop_control_visitor::visit_leave().
bool set_loop_controls (exec_list * instructions, loop_state * ls)
Fill in loop control fields.
Based on analysis of loop variables, this function tries to remove sequences in the loop of the form
(if (expression bool ...) (break))
and fill in the ir_loop::from, ir_loop::to, and ir_loop::counter fields of the ir_loop.
In this process, some conditional break-statements may be eliminated altogether. For example, if it is provable that one loop exit condition will always be satisfied before another, the unnecessary exit condition will be removed.
References loop_control_visitor::progress, and ir_hierarchical_visitor::run().
Referenced by do_common_optimization().