Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_mat_op_to_vec.cpp File Reference
Breaks matrix operation expressions down to a series of vector operations.
#include "ir.h"
#include "ir_expression_flattening.h"
#include "glsl_types.h"
Data Structures
class ir_mat_op_to_vec_visitor
Functions
static bool mat_op_to_vec_predicate (ir_instruction *ir)
bool do_mat_op_to_vec (exec_list *instructions)
static bool has_matrix_operand (const ir_expression *expr, unsigned &columns)
Detailed Description
Breaks matrix operation expressions down to a series of vector operations.
Generally this is how we have to codegen matrix operations for a GPU, so this gives us the chance to constant fold operations on a column or row.
Function Documentation
bool do_mat_op_to_vec (exec_list * instructions)
References do_expression_flattening(), ir_mat_op_to_vec_visitor::made_progress, mat_op_to_vec_predicate(), and visit_list_elements().
Referenced by do_optimization().
static bool has_matrix_operand (const ir_expression * expr, unsigned & columns) static
References ir_expression::get_num_operands(), ir_expression::operands, and ir_rvalue::type.
Referenced by ir_mat_op_to_vec_visitor::visit_leave().
static bool mat_op_to_vec_predicate (ir_instruction * ir) static
References ir_instruction::as_expression(), ir_builder::expr(), ir_expression::get_num_operands(), ir_expression::operands, and ir_rvalue::type.
Referenced by do_mat_op_to_vec().