Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_if_to_cond_assign.cpp File Reference
This attempts to flatten if-statements to conditional assignments for GPUs with limited or no flow control support.
#include "glsl_types.h"
#include "ir.h"
#include "program/hash_table.h"
Data Structures
class ir_if_to_cond_assign_visitor
Functions
bool lower_if_to_cond_assign (exec_list *instructions, unsigned max_depth)
void check_control_flow (ir_instruction *ir, void *data)
void move_block_to_cond_assign (void *mem_ctx, ir_if *if_ir, ir_rvalue *cond_expr, exec_list *instructions, struct hash_table *ht)
Detailed Description
This attempts to flatten if-statements to conditional assignments for GPUs with limited or no flow control support.
It can't handle other control flow being inside of its block, such as calls or loops. Hopefully loop unrolling and inlining will take care of those.
Drivers for GPUs with no control flow support should simply call
lower_if_to_cond_assign(instructions)
to attempt to flatten all if-statements.
Some GPUs (such as i965 prior to gen6) do support control flow, but have a maximum nesting depth N. Drivers for such hardware can call
lower_if_to_cond_assign(instructions, N)
to attempt to flatten any if-statements appearing at depth > N.
Function Documentation
void check_control_flow (ir_instruction * ir, void * data)
References ir_instruction::ir_type, ir_type_call, ir_type_discard, ir_type_loop, ir_type_loop_jump, and ir_type_return.
Referenced by ir_if_to_cond_assign_visitor::visit_leave().
bool lower_if_to_cond_assign (exec_list * instructions, unsigned max_depth)
References ir_if_to_cond_assign_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
void move_block_to_cond_assign (void * mem_ctx, ir_if * if_ir, ir_rvalue * cond_expr, exec_list * instructions, struct hash_table * ht)
References ir_builder::assign(), ir_rvalue::clone(), ir_assignment::condition, foreach_list_safe, ir_binop_logic_and, ir_instruction::ir_type, ir_type_assignment, ir_assignment::lhs, ir_assignment::rhs, and ir_dereference::variable_referenced().
Referenced by ir_if_to_cond_assign_visitor::visit_leave().