Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_discard.cpp File Reference
This pass moves discards out of if-statements.
#include "glsl_types.h"
#include "ir.h"
Data Structures
class lower_discard_visitor
Functions
bool lower_discard (exec_list *instructions)
static ir_discard * find_discard (exec_list &instructions)
static void replace_discard (void *mem_ctx, ir_variable *var, ir_discard *ir)
Detailed Description
This pass moves discards out of if-statements.
Case 1: The "then" branch contains a conditional discard:
if (cond1) { s1; discard cond2; s2; } else { s3; }
becomes:
temp = false; if (cond1) { s1; temp = cond2; s2; } else { s3; } discard temp;
Case 2: The "else" branch contains a conditional discard:
if (cond1) { s1; } else { s2; discard cond2; s3; }
becomes:
temp = false; if (cond1) { s1; } else { s2; temp = cond2; s3; } discard temp;
Case 3: Both branches contain a conditional discard:
if (cond1) { s1; discard cond2; s2; } else { s3; discard cond3; s4; }
becomes:
temp = false; if (cond1) { s1; temp = cond2; s2; } else { s3; temp = cond3; s4; } discard temp;
If there are multiple conditional discards, we need only deal with one of them. Repeatedly applying this pass will take care of the others.
Unconditional discards are treated as having a condition of "true".
Function Documentation
static ir_discard* find_discard (exec_list & instructions) static
References ir_discard::as_discard(), and foreach_list.
Referenced by lower_discard_visitor::visit_leave().
bool lower_discard (exec_list * instructions)
References lower_discard_visitor::progress, and visit_list_elements().
Referenced by do_optimization().
static void replace_discard (void * mem_ctx, ir_variable * var, ir_discard * ir) static
References ir_discard::condition.
Referenced by lower_discard_visitor::visit_leave().