Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_packed_varyings.cpp File Reference
#include "glsl_symbol_table.h"
#include "ir.h"
#include "ir_optimization.h"
Data Structures
class lower_packed_varyings_visitor
Visitor that performs varying packing.
Functions
void lower_packed_varyings (void *mem_ctx, unsigned location_base, unsigned locations_used, ir_variable_mode mode, gl_shader *shader)
Function Documentation
void lower_packed_varyings (void * mem_ctx, unsigned location_base, unsigned locations_used, ir_variable_mode mode, gl_shader * shader)
References ir_function_signature::body, ir_function::matching_signature(), and lower_packed_varyings_visitor::run().
Referenced by assign_varying_locations().