Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_vector.cpp File Reference
IR lowering pass to remove some types of ir_quadop_vector.
#include "ir.h"
#include "ir_rvalue_visitor.h"
Data Structures
class lower_vector_visitor
Functions
bool is_extended_swizzle (ir_expression *ir)
Determine if an IR expression tree looks like an extended swizzle.
bool lower_quadop_vector (exec_list *instructions, bool dont_lower_swz)
Detailed Description
IR lowering pass to remove some types of ir_quadop_vector.
Author
Ian Romanick ian.d.nosp@m..rom.nosp@m.anick.nosp@m.@int.nosp@m.el.co.nosp@m.m
Function Documentation
bool is_extended_swizzle (ir_expression * ir)
Determine if an IR expression tree looks like an extended swizzle.
Extended swizzles consist of access of a single vector source (with possible per component negation) and the constants -1, 0, or 1.
References ir_instruction::as_constant(), ir_quadop_vector, ir_instruction::ir_type, ir_type_constant, ir_type_dereference_variable, ir_type_expression, ir_type_swizzle, ir_unop_neg, ir_constant::is_negative_one(), ir_constant::is_one(), ir_constant::is_zero(), ir_expression::operands, ir_expression::operation, ir_rvalue::type, and ir_dereference_variable::var.
Referenced by lower_vector_visitor::handle_rvalue().
bool lower_quadop_vector (exec_list * instructions, bool dont_lower_swz)
References lower_vector_visitor::dont_lower_swz, lower_vector_visitor::progress, and visit_list_elements().
Referenced by do_optimization().