Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_jumps.cpp File Reference
This pass lowers jumps (break, continue, and return) to if/else structures.
#include "glsl_types.h"
#include <string.h>
#include "ir.h"
Data Structures
struct block_record
struct loop_record
struct function_record
struct ir_lower_jumps_visitor
Enumerations
enum jump_strength {
strength_none, strength_always_clears_execute_flag, strength_continue, strength_break,
strength_return
}
Enum recording the result of analyzing how control flow might exit an IR node.
Functions
bool do_lower_jumps (exec_list *instructions, bool pull_out_jumps, bool lower_sub_return, bool lower_main_return, bool lower_continue, bool lower_break)
Detailed Description
This pass lowers jumps (break, continue, and return) to if/else structures.
It can be asked to:
Pull jumps out of ifs where possible
Remove all "continue"s, replacing them with an "execute flag"
Replace all "break" with a single conditional one at the end of the loop
Replace all "return"s with a single return at the end of the function, for the main function and/or other functions
Applying this pass gives several benefits:
All functions can be inlined.
nv40 and other pre-DX10 chips without "continue" can be supported
nv30 and other pre-DX10 chips with no control flow at all are better supported
Continues are lowered by adding a per-loop "execute flag", initialized to true, that when cleared inhibits all execution until the end of the loop.
Breaks are lowered to continues, plus setting a "break flag" that is checked at the end of the loop, and trigger the unique "break".
Returns are lowered to breaks/continues, plus adding a "return flag" that causes loops to break again out of their enclosing loops until all the loops are exited: then the "execute flag" logic will ignore everything until the end of the function.
Note that "continue" and "return" can also be implemented by adding a dummy loop and using break. However, this is bad for hardware with limited nesting depth, and prevents further optimization, and thus is not currently performed.
Enumeration Type Documentation
enum jump_strength
Enum recording the result of analyzing how control flow might exit an IR node.
Each possible value of jump_strength indicates a strictly stronger guarantee on control flow than the previous value.
The ordering of strengths roughly reflects the way jumps are lowered: jumps with higher strength tend to be lowered to jumps of lower strength. Accordingly, strength is used as a heuristic to determine which lowering to perform first.
This enum is also used by get_jump_strength() to categorize instructions as either break, continue, return, or other. When used in this fashion, strength_always_clears_execute_flag is not used.
The control flow analysis made by this optimization pass makes two simplifying assumptions:
It ignores discard instructions, since they are lowered by a separate pass (lower_discard.cpp).
It assumes it is always possible for control to flow from a loop to the instruction immediately following it. Technically, this is not true (since all execution paths through the loop might jump back to the top, or return from the function).
Both of these simplifying assumtions are safe, since they can never cause reachable code to be incorrectly classified as unreachable; they can only do the opposite.
Enumerator
strength_none
Analysis has produced no guarantee on how control flow might exit this IR node.
It might fall out the bottom (with or without clearing the execute flag, if present), or it might continue to the top of the innermost enclosing loop, break out of it, or return from the function.
strength_always_clears_execute_flag
The only way control can fall out the bottom of this node is through a code path that clears the execute flag.
It might also continue to the top of the innermost enclosing loop, break out of it, or return from the function.
strength_continue
Control cannot fall out the bottom of this node.
It might continue to the top of the innermost enclosing loop, break out of it, or return from the function.
strength_break
Control cannot fall out the bottom of this node, or continue the top of the innermost enclosing loop.
It can only break out of it or return from the function.
strength_return
Control cannot fall out the bottom of this node, continue to the top of the innermost enclosing loop, or break out of it.
It can only return from the function.
Function Documentation
bool do_lower_jumps (exec_list * instructions, bool pull_out_jumps, bool lower_sub_return, bool lower_main_return, bool lower_continue, bool lower_break)
References ir_lower_jumps_visitor::lower_break, ir_lower_jumps_visitor::lower_continue, ir_lower_jumps_visitor::lower_main_return, ir_lower_jumps_visitor::lower_sub_return, ir_lower_jumps_visitor::progress, ir_lower_jumps_visitor::pull_out_jumps, and visit_exec_list().
Referenced by do_common_optimization(), and do_optimization().