Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_output_reads.cpp File Reference
In GLSL, shader output variables (such as varyings) can be both read and written.
#include "ir.h"
#include "program/hash_table.h"
Data Structures
class output_read_remover
Functions
static unsigned hash_table_var_hash (const void *key)
Hash function for the output variables - computes the hash of the name.
static ir_assignment * copy (void *ctx, ir_variable *output, ir_variable *temp)
Create an assignment to copy a temporary value back to the actual output.
static void emit_return_copy (const void *key, void *data, void *closure)
Insert a copy-back assignment before a "return" statement.
static void emit_main_copy (const void *key, void *data, void *closure)
Insert a copy-back assignment at the end of the main() function.
void lower_output_reads (exec_list *instructions)
Detailed Description
In GLSL, shader output variables (such as varyings) can be both read and written.
However, on some hardware, reading an output register causes trouble.
This pass creates temporary shadow copies of every (used) shader output, and replaces all accesses to use those instead. It also adds code to the main() function to copy the final values to the actual shader outputs.
Function Documentation
static ir_assignment* copy (void * ctx, ir_variable * output, ir_variable * temp) static
Create an assignment to copy a temporary value back to the actual output.
Referenced by ir_function_signature::clone(), ir_function::clone(), clone_ir_list(), ir_function_signature::clone_prototype(), emit_main_copy(), emit_return_copy(), remap_variables(), call_link_visitor::visit_enter(), and import_prototype_visitor::visit_enter().
static void emit_main_copy (const void * key, void * data, void * closure) static
Insert a copy-back assignment at the end of the main() function.
References ir_function_signature::body, and copy().
Referenced by output_read_remover::visit_leave().
static void emit_return_copy (const void * key, void * data, void * closure) static
Insert a copy-back assignment before a "return" statement.
References copy().
Referenced by output_read_remover::visit_leave().
static unsigned hash_table_var_hash (const void * key) static
Hash function for the output variables - computes the hash of the name.
NOTE: We're using the name string to ensure that the hash doesn't depend on any random factors, otherwise the output_read_remover could produce the random order of the assignments.
NOTE: If you want to reuse this function please take into account that generally the names of the variables are non-unique.
References ir_variable::name.
Referenced by output_read_remover::output_read_remover().
void lower_output_reads (exec_list * instructions)
References visit_list_elements().