Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
lower_vec_index_to_swizzle.cpp File Reference
Turns constant indexing into vector types to swizzles.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_optimization.h"
#include "glsl_types.h"
#include "main/macros.h"
Data Structures
class ir_vec_index_to_swizzle_visitor
Visitor class for replacing expressions with ir_constant values.
Functions
bool do_vec_index_to_swizzle (exec_list *instructions)
Detailed Description
Turns constant indexing into vector types to swizzles.
This will let other swizzle-aware optimization passes catch these constructs, and codegen backends not have to worry about this case.
Function Documentation
bool do_vec_index_to_swizzle (exec_list * instructions)
References ir_vec_index_to_swizzle_visitor::progress, and ir_hierarchical_visitor::run().
Referenced by do_common_optimization(), and do_optimization().