Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
main.cpp File Reference
This file is the main() routine and scaffolding for producing builtin_compiler (which doesn't include builtins itself and is used to generate the profile information for builtin_function.cpp), and for glsl_compiler (which does include builtins and can be used to offline compile GLSL code and examine the resulting GLSL IR.
#include <getopt.h>
#include "ast.h"
#include "glsl_parser_extras.h"
#include "ir_optimization.h"
#include "ir_print_visitor.h"
#include "program.h"
#include "loop_analysis.h"
#include "standalone_scaffolding.h"
Functions
static void initialize_context (struct gl_context *ctx, gl_api api)
static char * load_text_file (void *ctx, const char *file_name)
void usage_fail (const char *name)
Print proper usage and exit with failure.
void compile_shader (struct gl_context *ctx, struct gl_shader *shader)
int main (int argc, char **argv)
Variables
int glsl_es = 0
int dump_ast = 0
int dump_hir = 0
int dump_lir = 0
int do_link = 0
struct option compiler_opts []
Detailed Description
This file is the main() routine and scaffolding for producing builtin_compiler (which doesn't include builtins itself and is used to generate the profile information for builtin_function.cpp), and for glsl_compiler (which does include builtins and can be used to offline compile GLSL code and examine the resulting GLSL IR.
Function Documentation
void compile_shader (struct gl_context * ctx, struct gl_shader * shader)
References _mesa_ast_to_hir(), _mesa_print_ir(), _mesa_shader_type_to_index(), do_common_optimization(), dump_ast, dump_hir, dump_lir, exec_node_data, foreach_list_const, glcpp_preprocess(), ast_node::print(), ralloc_free(), reparent_ir(), and validate_ir_tree().
Referenced by main().
static void initialize_context (struct gl_context * ctx, gl_api api) static
References _mesa_new_shader(), and initialize_context_to_defaults().
Referenced by main().
static char* load_text_file (void * ctx, const char * file_name) static
References ralloc_size().
Referenced by main().
int main (int argc, char ** argv)
References _mesa_glsl_release_functions(), _mesa_glsl_release_types(), compile_shader(), compiler_opts, do_link, glsl_es, initialize_context(), link_shaders(), load_text_file(), ralloc_free(), ralloc_strdup(), reralloc, rzalloc, and usage_fail().
Referenced by link_intrastage_shaders().
void usage_fail (const char * name)
Print proper usage and exit with failure.
References compiler_opts.
Referenced by extract_command_from_argv(), and main().
Variable Documentation
struct option compiler_opts[]
Initial value:
= {
   { "glsl-es",  0, &glsl_es,  1 },
   { "dump-ast", 0, &dump_ast, 1 },
   { "dump-hir", 0, &dump_hir, 1 },
   { "dump-lir", 0, &dump_lir, 1 },
   { "link",     0, &do_link,  1 },
   { NULL, 0, NULL, 0 }
}
Referenced by main(), and usage_fail().
int do_link = 0
Referenced by main().
int dump_ast = 0
Referenced by compile_shader().
int dump_hir = 0
Referenced by compile_shader().
int dump_lir = 0
Referenced by compile_shader().
int glsl_es = 0
Referenced by main().