Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
linker Namespace Reference
Functions
gl_uniform_storage * get_storage (gl_uniform_storage *storage, unsigned num_storage, const char *name)
void copy_constant_to_storage (union gl_constant_value *storage, const ir_constant *val, const enum glsl_base_type base_type, const unsigned int elements)
void set_uniform_initializer (void *mem_ctx, gl_shader_program *prog, const char *name, const glsl_type *type, ir_constant *val)
Function Documentation
void linker::copy_constant_to_storage (union gl_constant_value * storage, const ir_constant * val, const enum glsl_base_type base_type, const unsigned int elements)
References ir_constant_data::b, ir_constant_data::f, GLSL_TYPE_ARRAY, GLSL_TYPE_BOOL, GLSL_TYPE_ERROR, GLSL_TYPE_FLOAT, GLSL_TYPE_INT, GLSL_TYPE_INTERFACE, GLSL_TYPE_SAMPLER, GLSL_TYPE_STRUCT, GLSL_TYPE_UINT, GLSL_TYPE_VOID, ir_constant_data::i, ir_constant_data::u, and ir_constant::value.
Referenced by set_uniform_initializer().
gl_uniform_storage* linker::get_storage (gl_uniform_storage * storage, unsigned num_storage, const char * name)
Referenced by set_uniform_initializer().
void linker::set_uniform_initializer (void * mem_ctx, gl_shader_program * prog, const char * name, const glsl_type * type, ir_constant * val)
References gl_uniform_storage::active, gl_uniform_storage::array_elements, ir_constant::array_elements, ir_constant::components, copy_constant_to_storage(), get_storage(), GLSL_TYPE_SAMPLER, gl_uniform_storage::index, gl_uniform_storage::initialized, exec_node::next, ralloc_asprintf(), gl_uniform_storage::sampler, gl_uniform_storage::storage, gl_uniform_storage::type, and ir_rvalue::type.
Referenced by link_set_uniform_initializers().