Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_builder Namespace Reference
Data Structures
class operand
This little class exists to let the helper expression generators take either an ir_rvalue * or an ir_variable * to be automatically dereferenced, while still providing compile-time type checking.
class deref
Automatic generator for ir_dereference_variable on assignment LHS.
class ir_factory
Enumerations
enum writemask { WRITEMASK_X = 0x1, WRITEMASK_Y = 0x2, WRITEMASK_Z = 0x4, WRITEMASK_W = 0x8 }
Functions
ir_assignment * assign (deref lhs, operand rhs, int writemask)
ir_assignment * assign (deref lhs, operand rhs)
ir_swizzle * swizzle (operand a, int swizzle, int components)
ir_swizzle * swizzle_for_size (operand a, unsigned components)
Swizzle away later components, but preserve the ordering.
ir_swizzle * swizzle_xxxx (operand a)
ir_swizzle * swizzle_yyyy (operand a)
ir_swizzle * swizzle_zzzz (operand a)
ir_swizzle * swizzle_wwww (operand a)
ir_swizzle * swizzle_x (operand a)
ir_swizzle * swizzle_y (operand a)
ir_swizzle * swizzle_z (operand a)
ir_swizzle * swizzle_w (operand a)
ir_swizzle * swizzle_xy (operand a)
ir_swizzle * swizzle_xyz (operand a)
ir_swizzle * swizzle_xyzw (operand a)
ir_expression * expr (ir_expression_operation op, operand a)
ir_expression * expr (ir_expression_operation op, operand a, operand b)
ir_expression * add (operand a, operand b)
ir_expression * sub (operand a, operand b)
ir_expression * mul (operand a, operand b)
ir_expression * div (operand a, operand b)
ir_expression * round_even (operand a)
ir_expression * dot (operand a, operand b)
ir_expression * clamp (operand a, operand b, operand c)
ir_expression * saturate (operand a)
ir_expression * equal (operand a, operand b)
ir_expression * less (operand a, operand b)
ir_expression * greater (operand a, operand b)
ir_expression * lequal (operand a, operand b)
ir_expression * gequal (operand a, operand b)
ir_expression * logic_not (operand a)
ir_expression * logic_and (operand a, operand b)
ir_expression * logic_or (operand a, operand b)
ir_expression * bit_not (operand a)
ir_expression * bit_and (operand a, operand b)
ir_expression * bit_or (operand a, operand b)
ir_expression * lshift (operand a, operand b)
ir_expression * rshift (operand a, operand b)
ir_expression * f2i (operand a)
ir_expression * i2f (operand a)
ir_expression * i2u (operand a)
ir_expression * u2i (operand a)
ir_expression * f2u (operand a)
ir_expression * u2f (operand a)
ir_if * if_tree (operand condition, ir_instruction *then_branch)
ir_if * if_tree (operand condition, ir_instruction *then_branch, ir_instruction *else_branch)
Enumeration Type Documentation
enum ir_builder::writemask
Enumerator
WRITEMASK_X
WRITEMASK_Y
WRITEMASK_Z
WRITEMASK_W
Function Documentation
ir_expression * ir_builder::add (operand a, operand b)
References expr(), and ir_binop_add.
Referenced by calculate_iterations().
ir_assignment * ir_builder::assign (deref lhs, operand rhs, int writemask)
References ralloc_parent(), ir_builder::operand::val, and ir_builder::deref::val.
Referenced by assign(), variable_index_to_cond_assign_visitor::convert_dereference_array(), ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign(), ir_mat_op_to_vec_visitor::do_equal_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_vec(), emit_inline_record_constructor(), find_initial_value(), ir_call::generate_inline(), lower_vector_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), ir_expression_flattening_visitor::handle_rvalue(), move_block_to_cond_assign(), lower_discard_flow_visitor::visit_enter(), ir_mat_op_to_vec_visitor::visit_leave(), lower_texture_projection_visitor::visit_leave(), lower_clip_distance_visitor::visit_leave(), and ir_if_to_cond_assign_visitor::visit_leave().
ir_assignment * ir_builder::assign (deref lhs, operand rhs)
References assign(), ir_rvalue::type, and ir_builder::deref::val.
ir_expression * ir_builder::bit_and (operand a, operand b)
References expr(), and ir_binop_bit_and.
ir_expression * ir_builder::bit_not (operand a)
References expr(), and ir_unop_bit_not.
ir_expression * ir_builder::bit_or (operand a, operand b)
References expr(), and ir_binop_bit_or.
ir_expression * ir_builder::clamp (operand a, operand b, operand c)
References expr(), ir_binop_max, and ir_binop_min.
ir_expression * ir_builder::div (operand a, operand b)
References expr(), and ir_binop_div.
Referenced by calculate_iterations().
ir_expression * ir_builder::dot (operand a, operand b)
References expr(), and ir_binop_dot.
ir_expression * ir_builder::equal (operand a, operand b)
References expr(), and ir_binop_equal.
Referenced by vector_insert_visitor::handle_rvalue().
ir_expression * ir_builder::expr (ir_expression_operation op, operand a)
References ralloc_parent(), and ir_builder::operand::val.
Referenced by __read_expression(), add(), ir_rvalue::as_rvalue_to_saturate(), bit_and(), bit_not(), bit_or(), clamp(), ir_vec_index_to_cond_assign_visitor::convert_vector_extract_to_cond_assign(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), div(), do_assignment(), ir_mat_op_to_vec_visitor::do_mul_mat_mat(), ir_mat_op_to_vec_visitor::do_mul_mat_vec(), dot(), equal(), f2i(), f2u(), lower_clip_distance_visitor::fix_lhs(), fix_parameter(), gequal(), get_scalar_boolean_operand(), greater(), lower_vector_visitor::handle_rvalue(), lower_noise_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), lower_clip_distance_visitor::handle_rvalue(), i2f(), i2u(), lequal(), less(), logic_and(), logic_not(), logic_or(), lshift(), mat_op_to_vec_predicate(), s_pattern::match(), mul(), s_list::print(), ir_reader::read(), read_atom(), round_even(), rshift(), s_match(), saturate(), sub(), try_max_zero(), try_min_one(), u2f(), u2i(), verify_parameter_modes(), and lower_texture_projection_visitor::visit_leave().
ir_expression * ir_builder::expr (ir_expression_operation op, operand a, operand b)
References ralloc_parent(), and ir_builder::operand::val.
ir_expression * ir_builder::f2i (operand a)
References expr(), and ir_unop_f2i.
ir_expression * ir_builder::f2u (operand a)
References expr(), and ir_unop_f2u.
ir_expression * ir_builder::gequal (operand a, operand b)
References expr(), and ir_binop_gequal.
ir_expression * ir_builder::greater (operand a, operand b)
References expr(), and ir_binop_greater.
ir_expression * ir_builder::i2f (operand a)
References expr(), and ir_unop_i2f.
ir_expression * ir_builder::i2u (operand a)
References expr(), and ir_unop_i2u.
ir_if * ir_builder::if_tree (operand condition, ir_instruction * then_branch)
References ralloc_parent(), ir_if::then_instructions, and ir_builder::operand::val.
Referenced by vector_insert_visitor::handle_rvalue().
ir_if * ir_builder::if_tree (operand condition, ir_instruction * then_branch, ir_instruction * else_branch)
References ir_if::else_instructions, ralloc_parent(), ir_if::then_instructions, and ir_builder::operand::val.
ir_expression * ir_builder::lequal (operand a, operand b)
References expr(), and ir_binop_lequal.
ir_expression * ir_builder::less (operand a, operand b)
References expr(), and ir_binop_less.
Referenced by switch_generator::bisect().
ir_expression * ir_builder::logic_and (operand a, operand b)
References expr(), and ir_binop_logic_and.
ir_expression * ir_builder::logic_not (operand a)
References expr(), and ir_unop_logic_not.
ir_expression * ir_builder::logic_or (operand a, operand b)
References expr(), and ir_binop_logic_or.
ir_expression * ir_builder::lshift (operand a, operand b)
References expr(), and ir_binop_lshift.
ir_expression * ir_builder::mul (operand a, operand b)
References expr(), and ir_binop_mul.
Referenced by calculate_iterations().
ir_expression * ir_builder::round_even (operand a)
References expr(), and ir_unop_round_even.
ir_expression * ir_builder::rshift (operand a, operand b)
References expr(), and ir_binop_rshift.
ir_expression * ir_builder::saturate (operand a)
References expr(), ir_binop_max, ir_binop_min, ralloc_parent(), and ir_builder::operand::val.
ir_expression * ir_builder::sub (operand a, operand b)
References expr(), and ir_binop_sub.
Referenced by calculate_iterations().
ir_swizzle* ir_builder::swizzle (operand a, int swizzle, int components)
References ralloc_parent(), and ir_builder::operand::val.
Referenced by ir_vec_index_to_cond_assign_visitor::convert_vec_index_to_cond_assign(), swizzle_w(), swizzle_wwww(), swizzle_x(), swizzle_xxxx(), swizzle_xy(), swizzle_xyz(), swizzle_xyzw(), swizzle_y(), swizzle_yyyy(), swizzle_z(), and swizzle_zzzz().
ir_swizzle * ir_builder::swizzle_for_size (operand a, unsigned components)
Swizzle away later components, but preserve the ordering.
References ralloc_parent(), ir_rvalue::type, and ir_builder::operand::val.
ir_swizzle * ir_builder::swizzle_w (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_wwww (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_x (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_xxxx (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_xy (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_xyz (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_xyzw (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_y (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_yyyy (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_z (operand a)
References swizzle().
ir_swizzle * ir_builder::swizzle_zzzz (operand a)
References swizzle().
ir_expression * ir_builder::u2f (operand a)
References expr(), and ir_unop_u2f.
ir_expression * ir_builder::u2i (operand a)
References expr(), and ir_unop_u2i.