Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
opt_function_inlining.cpp File Reference
Replaces calls to functions with the body of the function.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_function_inlining.h"
#include "ir_expression_flattening.h"
#include "glsl_types.h"
#include "program/hash_table.h"
Data Structures
class ir_sampler_replacement_visitor
Replaces references to the "sampler" variable with a clone of "deref.".
Functions
static void do_sampler_replacement (exec_list *instructions, ir_variable *sampler, ir_dereference *deref)
bool do_function_inlining (exec_list *instructions)
static void replace_return_with_assignment (ir_instruction *ir, void *data)
Detailed Description
Replaces calls to functions with the body of the function.
Function Documentation
bool do_function_inlining (exec_list * instructions)
Referenced by do_common_optimization(), and do_optimization().
static void do_sampler_replacement (exec_list * instructions, ir_variable * sampler, ir_dereference * deref) static
References visit_list_elements().
Referenced by ir_call::generate_inline().
static void replace_return_with_assignment (ir_instruction * ir, void * data) static
References ir_instruction::as_return(), ir_dereference::clone(), exec_node::next, ralloc_parent(), and ir_return::value.
Referenced by ir_call::generate_inline().