Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
opt_structure_splitting.cpp File Reference
If a structure is only ever referenced by its components, then split those components out to individual variables so they can be handled normally by other optimization passes.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_print_visitor.h"
#include "ir_rvalue_visitor.h"
#include "glsl_types.h"
Functions
bool do_structure_splitting (exec_list *instructions)
Detailed Description
If a structure is only ever referenced by its components, then split those components out to individual variables so they can be handled normally by other optimization passes.
This skips structures like uniforms, which need to be accessible as structures for their access by the GL.
Function Documentation
bool do_structure_splitting (exec_list * instructions)
References ir_var_temporary, ralloc_array, ralloc_asprintf(), ralloc_context(), ralloc_free(), ralloc_parent(), and visit_list_elements().
Referenced by do_common_optimization(), and do_optimization().