Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
opt_constant_variable.cpp File Reference
Marks variables assigned a single constant value over the course of the program as constant.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_optimization.h"
#include "glsl_types.h"
Functions
static struct assignment_entry * get_assignment_entry (ir_variable *var, exec_list *list)
bool do_constant_variable (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
bool do_constant_variable_unlinked (exec_list *instructions)
Detailed Description
Marks variables assigned a single constant value over the course of the program as constant.
The goal here is to trigger further constant folding and then dead code elimination. This is common with vector/matrix constructors and calls to builtin functions.
Function Documentation
bool do_constant_variable (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References exec_node_data.
Referenced by do_common_optimization(), do_constant_variable_unlinked(), and do_optimization().
bool do_constant_variable_unlinked (exec_list * instructions)
References ir_instruction::as_function(), ir_function_signature::body, and do_constant_variable().
Referenced by do_common_optimization(), and do_optimization().
static struct assignment_entry* get_assignment_entry (ir_variable * var, exec_list * list) static read
References foreach_list_typed.