Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
opt_dead_code.cpp File Reference
Eliminates dead assignments and variable declarations from the code.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_variable_refcount.h"
#include "glsl_types.h"
#include "main/hash_table.h"
Functions
bool do_dead_code (exec_list *instructions, bool uniform_locations_assigned)
Do a dead code pass over instructions and everything that instructions references.
bool do_dead_code_unlinked (exec_list *instructions)
Does a dead code pass on the functions present in the instruction stream.
Variables
static bool debug = false
Detailed Description
Eliminates dead assignments and variable declarations from the code.
Function Documentation
bool do_dead_code (exec_list * instructions, bool uniform_locations_assigned)
Do a dead code pass over instructions and everything that instructions references.
Note that this will remove assignments to globals, so it is not suitable for usage on an unlinked instruction stream.
References ir_variable_refcount_entry::assign, ir_variable_refcount_entry::assigned_count, ir_variable::constant_value, debug, ir_variable_refcount_entry::declaration, ir_variable_refcount_visitor::ht, ir_var_function_inout, ir_var_function_out, ir_var_shader_out, ir_var_uniform, ir_variable::mode, ir_variable::name, ir_variable_refcount_entry::referenced_count, ir_hierarchical_visitor::run(), and ir_variable_refcount_entry::var.
Referenced by do_common_optimization(), do_dead_code_unlinked(), do_optimization(), and link_shaders().
bool do_dead_code_unlinked (exec_list * instructions)
Does a dead code pass on the functions present in the instruction stream.
This is suitable for use while the program is not linked, as it will ignore variable declarations (and the assignments to them) for variables with global scope.
References ir_instruction::as_function(), ir_function_signature::body, and do_dead_code().
Referenced by do_common_optimization(), and do_optimization().
Variable Documentation
bool debug = false static
Referenced by do_dead_code().