Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
opt_array_splitting.cpp File Reference
If an array is always dereferenced with a constant index, then split it apart into its elements, making it more amenable to other optimization passes.
#include "ir.h"
#include "ir_visitor.h"
#include "ir_rvalue_visitor.h"
#include "ir_print_visitor.h"
#include "glsl_types.h"
Data Structures
class opt_array_splitting::variable_entry
class ir_array_reference_visitor
This class does a walk over the tree, coming up with the set of variables that could be split by looking to see if they are arrays that are only ever constant-index dereferenced.
class ir_array_splitting_visitor
This class rewrites the dereferences of arrays that have been split to use the newly created ir_variables for each component.
Namespaces
namespace opt_array_splitting
Functions
bool optimize_split_arrays (exec_list *instructions, bool linked)
Variables
static bool debug = false
Detailed Description
If an array is always dereferenced with a constant index, then split it apart into its elements, making it more amenable to other optimization passes.
This skips uniform/varying arrays, which would need careful handling due to their ir->location fields tying them to the GL API and other shader stages.
Function Documentation
bool optimize_split_arrays (exec_list * instructions, bool linked)
References _mesa_print_ir(), opt_array_splitting::variable_entry::components, debug, ir_array_reference_visitor::get_split_list(), ir_var_temporary, opt_array_splitting::variable_entry::mem_ctx, ir_variable::name, ralloc_array, ralloc_asprintf(), ralloc_context(), ralloc_free(), ralloc_parent(), opt_array_splitting::variable_entry::size, ir_variable::type, opt_array_splitting::variable_entry::var, ir_array_reference_visitor::variable_list, and visit_list_elements().
Referenced by do_common_optimization().
Variable Documentation
bool debug = false static
Referenced by ir_array_reference_visitor::get_split_list(), and optimize_split_arrays().