Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
opt_dead_code_local.cpp File Reference
Eliminates local dead assignments from the code.
#include "ir.h"
#include "ir_basic_block.h"
#include "ir_optimization.h"
#include "glsl_types.h"
Functions
static bool process_assignment (void *ctx, ir_assignment *ir, exec_list *assignments)
Adds an entry to the available copy list if it's a plain assignment of a variable to a variable.
static void dead_code_local_basic_block (ir_instruction *first, ir_instruction *last, void *data)
bool do_dead_code_local (exec_list *instructions)
Does a copy propagation pass on the code present in the instruction stream.
Variables
static bool debug = false
Detailed Description
Eliminates local dead assignments from the code.
This operates on basic blocks, tracking assignments and finding if they're used before the variable is completely reassigned.
Compare this to ir_dead_code.cpp, which operates globally looking for assignments to variables that are never read.
Function Documentation
static void dead_code_local_basic_block (ir_instruction * first, ir_instruction * last, void * data) static
References ir_instruction::accept(), ir_instruction::as_assignment(), debug, exec_node::next, ir_instruction::print(), process_assignment(), ralloc_context(), and ralloc_free().
Referenced by do_dead_code_local().
bool do_dead_code_local (exec_list * instructions)
Does a copy propagation pass on the code present in the instruction stream.
References call_for_basic_blocks(), and dead_code_local_basic_block().
Referenced by do_common_optimization(), and do_optimization().
static bool process_assignment (void * ctx, ir_assignment * ir, exec_list * assignments) static
Adds an entry to the available copy list if it's a plain assignment of a variable to a variable.
References ir_rvalue::accept(), ir_instruction::as_dereference_variable(), ir_assignment::condition, debug, ir_assignment::lhs, ir_variable::name, ralloc_parent(), ir_assignment::rhs, ir_variable::type, ir_dereference_variable::var, ir_dereference::variable_referenced(), ir_assignment::whole_variable_written(), and ir_assignment::write_mask.
Referenced by dead_code_local_basic_block().
Variable Documentation
bool debug = false static
Referenced by dead_code_local_basic_block(), and process_assignment().