Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
program.h File Reference
#include "main/core.h"
Functions
void link_shaders (struct gl_context *ctx, struct gl_shader_program *prog)
void linker_error (gl_shader_program *prog, const char *fmt,...) PRINTFLIKE(2
void void linker_warning (gl_shader_program *prog, const char *fmt,...) PRINTFLIKE(2
void void long parse_program_resource_name (const GLchar *name, const GLchar **out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
Function Documentation
void link_shaders (struct gl_context * ctx, struct gl_shader_program * prog)
References _mesa_reference_shader(), assign_attribute_or_color_locations(), assign_varying_locations(), check_resources(), cross_validate_outputs_to_inputs(), cross_validate_uniforms(), demote_shader_inputs_and_outputs(), detect_recursion_linked(), do_common_optimization(), do_dead_code(), interstage_cross_validate_uniform_blocks(), ir_var_shader_in, ir_var_shader_out, link_assign_uniform_locations(), link_intrastage_shaders(), link_invalidate_variable_locations(), linker_error(), lower_clip_distance(), lower_discard_flow(), lower_named_interface_blocks(), parse_tfeedback_decls(), ralloc_array, ralloc_context(), ralloc_free(), ralloc_strdup(), reparent_ir(), store_fragdepth_layout(), store_tfeedback_info(), update_array_sizes(), validate_fragment_shader_executable(), validate_interstage_interface_blocks(), and validate_vertex_shader_executable().
Referenced by main().
void linker_error (gl_shader_program * prog, const char * fmt, ...)
References ralloc_strcat(), and ralloc_vasprintf_append().
void void linker_warning (gl_shader_program * prog, const char * fmt, ...)
References ralloc_strcat(), and ralloc_vasprintf_append().
void void long parse_program_resource_name (const GLchar * name, const GLchar ** out_base_name_end)
Given a string identifying a program resource, break it into a base name and an optional array index in square brackets.
If an array index is present, out_base_name_end is set to point to the "[" that precedes the array index, and the array index itself is returned as a long.
If no array index is present (or if the array index is negative or mal-formed), out_base_name_end, is set to point to the null terminator at the end of the input string, and -1 is returned.
Only the final array index is parsed; if the string contains other array indices (or structure field accesses), they are left in the base name.
No attempt is made to check that the base name is properly formed; typically the caller will look up the base name in a hash table, so ill-formed base names simply turn into hash table lookup failures.
Referenced by tfeedback_decl::init().