Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ralloc.h File Reference
ralloc: a recursive memory allocator
#include <stddef.h>
#include <stdarg.h>
#include <stdbool.h>
#include "main/compiler.h"
Macros
#define ralloc(ctx, type) ((type *) ralloc_size(ctx, sizeof(type)))
Allocate a new object chained off of the given context.
#define rzalloc(ctx, type) ((type *) rzalloc_size(ctx, sizeof(type)))
Allocate a new object out of the given context and initialize it to zero.
#define ralloc_array(ctx, type, count) ((type *) ralloc_array_size(ctx, sizeof(type), count))
Allocate an array of objects chained off the given context.
#define rzalloc_array(ctx, type, count) ((type *) rzalloc_array_size(ctx, sizeof(type), count))
Allocate a zero-initialized array chained off the given context.
#define reralloc(ctx, ptr, type, count) ((type *) reralloc_array_size(ctx, ptr, sizeof(type), count))
Resize a ralloc-managed array, preserving data.
Functions
void * ralloc_context (const void *ctx)
Allocate a new ralloc context.
void * ralloc_size (const void *ctx, size_t size)
Allocate memory chained off of the given context.
void * rzalloc_size (const void *ctx, size_t size)
Allocate zero-initialized memory chained off of the given context.
void * reralloc_size (const void *ctx, void *ptr, size_t size)
Resize a piece of ralloc-managed memory, preserving data.
void * ralloc_array_size (const void *ctx, size_t size, unsigned count)
Allocate memory for an array chained off the given context.
void * rzalloc_array_size (const void *ctx, size_t size, unsigned count)
Allocate a zero-initialized array chained off the given context.
void * reralloc_array_size (const void *ctx, void *ptr, size_t size, unsigned count)
Resize a ralloc-managed array, preserving data.
void ralloc_free (void *ptr)
Free a piece of ralloc-managed memory.
void ralloc_steal (const void *new_ctx, void *ptr)
"Steal" memory from one context, changing it to another.
void * ralloc_parent (const void *ptr)
Return the given pointer's ralloc context.
void * ralloc_autofree_context (void)
Return a context whose memory will be automatically freed at program exit.
void ralloc_set_destructor (const void *ptr, void(*destructor)(void *))
Set a callback to occur just before an object is freed.
char * ralloc_strdup (const void *ctx, const char *str)
Duplicate a string, allocating the memory from the given context.
char * ralloc_strndup (const void *ctx, const char *str, size_t n)
Duplicate a string, allocating the memory from the given context.
bool ralloc_strcat (char **dest, const char *str)
Concatenate two strings, allocating the necessary space.
bool ralloc_strncat (char **dest, const char *str, size_t n)
Concatenate two strings, allocating the necessary space.
char * ralloc_asprintf (const void *ctx, const char *fmt,...) PRINTFLIKE(2
Print to a string.
char char * ralloc_vasprintf (const void *ctx, const char *fmt, va_list args)
Print to a string, given a va_list.
bool ralloc_asprintf_rewrite_tail (char **str, size_t *start, const char *fmt,...) PRINTFLIKE(3
Rewrite the tail of an existing string, starting at a given index.
bool bool ralloc_vasprintf_rewrite_tail (char **str, size_t *start, const char *fmt, va_list args)
Rewrite the tail of an existing string, starting at a given index.
bool ralloc_asprintf_append (char **str, const char *fmt,...) PRINTFLIKE(2
Append formatted text to the supplied string.
bool bool ralloc_vasprintf_append (char **str, const char *fmt, va_list args)
Append formatted text to the supplied string, given a va_list.
Detailed Description
ralloc: a recursive memory allocator
The ralloc memory allocator creates a hierarchy of allocated objects. Every allocation is in reference to some parent, and every allocated object can in turn be used as the parent of a subsequent allocation. This allows for extremely convenient discarding of an entire tree/sub-tree of allocations by calling ralloc_free on any particular object to free it and all of its children.
The conceptual working of ralloc was directly inspired by Andrew Tridgell's talloc, but ralloc is an independent implementation released under the MIT license and tuned for Mesa.
The talloc implementation is available under the GNU Lesser General Public License (GNU LGPL), version 3 or later. It is more sophisticated than ralloc in that it includes reference counting and debugging features. See: http://talloc.samba.org/
Macro Definition Documentation
#define ralloc (ctx, type) ((type *) ralloc_size(ctx, sizeof(type)))
Allocate a new object chained off of the given context.
This is equivalent to:
((type *) ralloc_size(ctx, sizeof(type))
#define ralloc_array (ctx, type, count) ((type *) ralloc_array_size(ctx, sizeof(type), count))
Allocate an array of objects chained off the given context.
Similar to calloc, but does not initialize the memory to zero.
More than a convenience function, this also checks for integer overflow when multiplying sizeof(type) and count. This is necessary for security.
This is equivalent to:
((type *) ralloc_array_size(ctx, sizeof(type), count)
Referenced by add_uniform(), ast_process_structure_or_interface_block(), ir_variable::clone(), ir_constant::clone(), do_structure_splitting(), interstage_cross_validate_uniform_blocks(), ir_constant::ir_constant(), link_cross_validate_uniform_block(), link_shaders(), link_uniform_blocks(), optimize_split_arrays(), ralloc_strdup(), ralloc_strndup(), and ir_constant::zero().
#define reralloc (ctx, ptr, type, count) ((type *) reralloc_array_size(ctx, ptr, sizeof(type), count))
Resize a ralloc-managed array, preserving data.
Similar to realloc. Unlike C89, passing 0 for size does not free the memory. Instead, it resizes it to a 0-byte ralloc context, just like calling ralloc_size(ctx, 0). This is different from talloc.
More than a convenience function, this also checks for integer overflow when multiplying sizeof(type) and count. This is necessary for security.
Parameters
ctx The context to use for new allocation. If ptr != NULL, it must be the same as ralloc_parent(ptr).
ptr Pointer to the array to be resized. May be NULL.
type The element type.
count The number of elements to allocate.
Referenced by ast_struct_specifier::hir(), link_cross_validate_uniform_block(), main(), and link_uniform_block_active_visitor::visit_enter().
#define rzalloc (ctx, type) ((type *) rzalloc_size(ctx, sizeof(type)))
Allocate a new object out of the given context and initialize it to zero.
This is equivalent to:
((type *) rzalloc_size(ctx, sizeof(type))
Referenced by _mesa_new_shader(), loop_variable_state::insert(), main(), process_block(), and test_optpass().
#define rzalloc_array (ctx, type, count) ((type *) rzalloc_array_size(ctx, sizeof(type), count))
Allocate a zero-initialized array chained off the given context.
Similar to calloc.
More than a convenience function, this also checks for integer overflow when multiplying sizeof(type) and count. This is necessary for security.
This is equivalent to:
((type *) rzalloc_array_size(ctx, sizeof(type), count)
Referenced by link_assign_uniform_locations(), and store_tfeedback_info().
Function Documentation
void* ralloc_array_size (const void * ctx, size_t size, unsigned count)
Allocate memory for an array chained off the given context.
Similar to calloc, but does not initialize the memory to zero.
More than a convenience function, this also checks for integer overflow when multiplying size and count. This is necessary for security.
References ralloc_size().
char* ralloc_asprintf (const void * ctx, const char * fmt, ...)
Print to a string.
This is analogous to sprintf, but allocates enough space (using ctx as the context) for the resulting string.
Returns
The newly allocated string.
bool ralloc_asprintf_append (char ** str, const char * fmt, ...)
Append formatted text to the supplied string.
This is equivalent to
ralloc_asprintf_rewrite_tail(str, strlen(*str), fmt, ...)
See Also
ralloc_asprintf
ralloc_asprintf_rewrite_tail
ralloc_strcat
str will be updated to the new pointer unless allocation fails.
Returns
True unless allocation failed.
bool ralloc_asprintf_rewrite_tail (char ** str, size_t * start, const char * fmt, ...)
Rewrite the tail of an existing string, starting at a given index.
Overwrites the contents of *str starting at start with newly formatted text, including a new null-terminator. Allocates more memory as necessary.
This can be used to append formatted text when the length of the existing string is already known, saving a strlen() call.
See Also
ralloc_asprintf_append
Parameters
str The string to be updated.
start The index to start appending new data at.
fmt A printf-style formatting string
str will be updated to the new pointer unless allocation fails. start will be increased by the length of the newly formatted text.
Returns
True unless allocation failed.
void* ralloc_autofree_context (void)
Return a context whose memory will be automatically freed at program exit.
The first call to this function creates a context and registers a handler to free it using atexit. This may cause trouble if used in a library loaded with dlopen.
References autofree(), autofree_context, and ralloc_context().
void* ralloc_context (const void * ctx)
Allocate a new ralloc context.
While any ralloc'd pointer can be used as a context, sometimes it is useful to simply allocate a context with no associated memory.
It is equivalent to:
((type *) ralloc_size(ctx, 0)
References ralloc_size().
Referenced by _mesa_glsl_initialize_functions(), calculate_iterations(), dead_code_local_basic_block(), do_structure_splitting(), glsl_symbol_table::glsl_symbol_table(), has_recursion_visitor::has_recursion_visitor(), ir_array_reference_visitor::ir_array_reference_visitor(), ir_print_visitor::ir_print_visitor(), ir_variable_refcount_visitor::ir_variable_refcount_visitor(), link_set_uniform_initializers(), link_shaders(), optimize_split_arrays(), output_read_remover::output_read_remover(), ralloc_autofree_context(), and ir_reader::read().
void ralloc_free (void * ptr)
Free a piece of ralloc-managed memory.
This will also free the memory of any children allocated this context.
References get_header(), unlink_block(), and unsafe_free().
Referenced by _mesa_glsl_release_functions(), autofree(), calculate_iterations(), compile_shader(), dead_code_local_basic_block(), do_structure_splitting(), emit_errors_linked(), emit_errors_unlinked(), link_assign_uniform_locations(), link_set_uniform_initializers(), link_shaders(), main(), no_matching_function_error(), symbol_table_entry::operator delete(), ast_node::operator delete(), glsl_symbol_table::operator delete(), function::operator delete(), ast_type_qualifier::operator delete(), optimize_split_arrays(), program_resource_visitor::process(), ir_reader::read(), read_builtins(), store_tfeedback_info(), test_optpass(), glsl_symbol_table::~glsl_symbol_table(), has_recursion_visitor::~has_recursion_visitor(), ir_array_reference_visitor::~ir_array_reference_visitor(), ir_print_visitor::~ir_print_visitor(), ir_variable_refcount_visitor::~ir_variable_refcount_visitor(), loop_state::~loop_state(), and output_read_remover::~output_read_remover().
void* ralloc_parent (const void * ptr)
Return the given pointer's ralloc context.
References get_header(), ralloc_header::parent, and PTR_FROM_HEADER.
Referenced by ir_builder::assign(), ir_function_signature::constant_expression_value(), ir_expression::constant_expression_value(), ir_swizzle::constant_expression_value(), ir_dereference_variable::constant_expression_value(), ir_dereference_array::constant_expression_value(), convert_component(), variable_index_to_cond_assign_visitor::convert_dereference_array(), ir_vec_index_to_cond_assign_visitor::convert_vector_extract_to_cond_assign(), ir_vec_index_to_swizzle_visitor::convert_vector_extract_to_swizzle(), ir_swizzle::create(), lower_clip_distance_visitor::create_indices(), cross_validate_globals(), ir_builder::deref::deref(), dereference_component(), do_structure_splitting(), ir_builder::expr(), lower_clip_distance_visitor::fix_lhs(), assignment_generator::generate(), ir_call::generate_inline(), get_basic_induction_increment(), get_lvalue_copy(), lower_noise_visitor::handle_rvalue(), vector_insert_visitor::handle_rvalue(), ir_expression_flattening_visitor::handle_rvalue(), lower_clip_distance_visitor::handle_rvalue(), deref_replacer::handle_rvalue(), variable_index_to_cond_assign_visitor::handle_rvalue(), ir_builder::if_tree(), loop_variable_state::insert(), ir_dereference_array::ir_dereference_array(), ir_dereference_record::ir_dereference_record(), lower_discard_flow_visitor::lower_discard_flow_visitor(), ir_builder::operand::operand(), optimize_split_arrays(), process_assignment(), ir_sampler_replacement_visitor::replace_deref(), replace_return_with_assignment(), reralloc_size(), ir_builder::saturate(), switch_generator::switch_generator(), ir_builder::swizzle(), ir_builder::swizzle_for_size(), output_read_remover::visit(), ir_validate::visit(), lower_clip_distance_visitor::visit(), loop_unroll_visitor::visit_leave(), ir_mat_op_to_vec_visitor::visit_leave(), lower_texture_projection_visitor::visit_leave(), lower_clip_distance_visitor::visit_leave(), ir_validate::visit_leave(), ir_if_to_cond_assign_visitor::visit_leave(), and lower_discard_visitor::visit_leave().
void ralloc_set_destructor (const void * ptr, void(*)(void *) destructor)
Set a callback to occur just before an object is freed.
References ralloc_header::destructor, and get_header().
Referenced by glsl_symbol_table::operator delete(), glsl_symbol_table::operator new(), and loop_variable_state::operator new().
void* ralloc_size (const void * ctx, size_t size)
Allocate memory chained off of the given context.
This is the core allocation routine which is used by all others. It simply allocates storage for size bytes and returns the pointer, similar to malloc.
References add_child(), CANARY, ralloc_header::canary, get_header(), ralloc_header::parent, and PTR_FROM_HEADER.
Referenced by load_text_file(), symbol_table_entry::operator new(), glsl_symbol_table::operator new(), loop_variable_state::operator new(), function::operator new(), ralloc_array_size(), ralloc_context(), ralloc_vasprintf(), reralloc_size(), and rzalloc_size().
void ralloc_steal (const void * new_ctx, void * ptr)
"Steal" memory from one context, changing it to another.
This changes ptr's context to new_ctx. This is quite useful if memory is allocated out of a temporary context.
References add_child(), get_header(), ralloc_header::parent, and unlink_block().
Referenced by _mesa_read_profile(), link_intrastage_shaders(), and steal_memory().
bool ralloc_strcat (char ** dest, const char * str)
Concatenate two strings, allocating the necessary space.
This appends str to *dest, similar to strcat, using ralloc_resize to expand *dest to the appropriate size. dest will be updated to the new pointer unless allocation fails.
The result will always be null-terminated.
Returns
True unless allocation failed.
References cat().
Referenced by _mesa_glsl_msg(), linker_error(), linker_warning(), and prototype_string().
char* ralloc_strdup (const void * ctx, const char * str)
Duplicate a string, allocating the memory from the given context.
References ralloc_array.
Referenced by assign_varying_locations(), ast_interface_block::hir(), ir_dereference_record::ir_dereference_record(), ir_function::ir_function(), ir_variable::ir_variable(), link_cross_validate_uniform_block(), link_shaders(), link_uniform_blocks(), main(), program_resource_visitor::process(), s_expression::read_expression(), flatten_named_interface_blocks_declarations::run(), tfeedback_decl::store(), and lower_clip_distance_visitor::visit().
bool ralloc_strncat (char ** dest, const char * str, size_t n)
Concatenate two strings, allocating the necessary space.
This appends at most n bytes of str to *dest, using ralloc_resize to expand *dest to the appropriate size. dest will be updated to the new pointer unless allocation fails.
The result will always be null-terminated; str does not need to be null terminated if it is longer than n.
Returns
True unless allocation failed.
References cat().
char* ralloc_strndup (const void * ctx, const char * str, size_t n)
Duplicate a string, allocating the memory from the given context.
Like strndup, at most n characters are copied. If str is longer than n characters, n are copied, and a termining '\0' byte is added.
References ralloc_array.
Referenced by tfeedback_decl::init().
char char* ralloc_vasprintf (const void * ctx, const char * fmt, va_list args)
Print to a string, given a va_list.
This is analogous to vsprintf, but allocates enough space (using ctx as the context) for the resulting string.
Returns
The newly allocated string.
References printf_length(), and ralloc_size().
Referenced by ralloc_asprintf(), and ralloc_vasprintf_rewrite_tail().
bool bool ralloc_vasprintf_append (char ** str, const char * fmt, va_list args)
Append formatted text to the supplied string, given a va_list.
This is equivalent to
ralloc_vasprintf_rewrite_tail(str, strlen(*str), fmt, args)
See Also
ralloc_vasprintf
ralloc_vasprintf_rewrite_tail
ralloc_strcat
str will be updated to the new pointer unless allocation fails.
Returns
True unless allocation failed.
References ralloc_vasprintf_rewrite_tail().
Referenced by _mesa_glsl_msg(), linker_error(), linker_warning(), and ralloc_asprintf_append().
bool bool ralloc_vasprintf_rewrite_tail (char ** str, size_t * start, const char * fmt, va_list args)
Rewrite the tail of an existing string, starting at a given index.
Overwrites the contents of *str starting at start with newly formatted text, including a new null-terminator. Allocates more memory as necessary.
This can be used to append formatted text when the length of the existing string is already known, saving a strlen() call.
See Also
ralloc_vasprintf_append
Parameters
str The string to be updated.
start The index to start appending new data at.
fmt A printf-style formatting string
args A va_list containing the data to be formatted
str will be updated to the new pointer unless allocation fails. start will be increased by the length of the newly formatted text.
Returns
True unless allocation failed.
References printf_length(), ralloc_vasprintf(), and resize().
Referenced by ralloc_asprintf_rewrite_tail(), and ralloc_vasprintf_append().
void* reralloc_array_size (const void * ctx, void * ptr, size_t size, unsigned count)
Resize a ralloc-managed array, preserving data.
Similar to realloc. Unlike C89, passing 0 for size does not free the memory. Instead, it resizes it to a 0-byte ralloc context, just like calling ralloc_size(ctx, 0). This is different from talloc.
More than a convenience function, this also checks for integer overflow when multiplying sizeof(type) and count. This is necessary for security.
Parameters
ctx The context to use for new allocation. If ptr != NULL, it must be the same as ralloc_parent(ptr).
ptr Pointer to the array to be resized. May be NULL.
size The size of an individual element.
count The number of elements to allocate.
Returns
True unless allocation failed.
References reralloc_size().
void* reralloc_size (const void * ctx, void * ptr, size_t size)
Resize a piece of ralloc-managed memory, preserving data.
Similar to realloc. Unlike C89, passing 0 for size does not free the memory. Instead, it resizes it to a 0-byte ralloc context, just like calling ralloc_size(ctx, 0). This is different from talloc.
Parameters
ctx The context to use for new allocation. If ptr != NULL, it must be the same as ralloc_parent(ptr).
ptr Pointer to the memory to be resized. May be NULL.
size The amount of memory to allocate, in bytes.
References ralloc_parent(), ralloc_size(), and resize().
Referenced by reralloc_array_size().
void* rzalloc_array_size (const void * ctx, size_t size, unsigned count)
Allocate a zero-initialized array chained off the given context.
Similar to calloc.
More than a convenience function, this also checks for integer overflow when multiplying size and count. This is necessary for security.
References rzalloc_size().
void* rzalloc_size (const void * ctx, size_t size)
Allocate zero-initialized memory chained off of the given context.
This is similar to calloc with a size of 1.
References ralloc_size().
Referenced by ast_node::operator new(), ast_type_qualifier::operator new(), and rzalloc_array_size().