Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
switch_generator Struct Reference
Public Types
typedef assignment_generator TFunction
Public Member Functions
switch_generator (const TFunction &generator, ir_variable *index, unsigned linear_sequence_max_length, unsigned condition_components)
void linear_sequence (unsigned begin, unsigned end, exec_list *list)
void bisect (unsigned begin, unsigned end, exec_list *list)
void generate (unsigned begin, unsigned end, exec_list *list)
Data Fields
const TFunction & generator
ir_variable * index
unsigned linear_sequence_max_length
unsigned condition_components
void * mem_ctx
Member Typedef Documentation
typedef assignment_generator switch_generator::TFunction
Constructor & Destructor Documentation
switch_generator::switch_generator (const TFunction & generator, ir_variable * index, unsigned linear_sequence_max_length, unsigned condition_components) inline
References mem_ctx, and ralloc_parent().
Member Function Documentation
void switch_generator::bisect (unsigned begin, unsigned end, exec_list * list) inline
References ir_if::else_instructions, generate(), GLSL_TYPE_UINT, index, ir_binop_less, ir_builder::less(), mem_ctx, ir_if::then_instructions, and ir_variable::type.
Referenced by generate().
void switch_generator::generate (unsigned begin, unsigned end, exec_list * list) inline
References bisect(), linear_sequence(), and linear_sequence_max_length.
Referenced by bisect(), and variable_index_to_cond_assign_visitor::convert_dereference_array().
void switch_generator::linear_sequence (unsigned begin, unsigned end, exec_list * list) inline
References ir_rvalue::clone(), compare_index_block(), condition_components, assignment_generator::generate(), generator, index, assignment_generator::is_write, and mem_ctx.
Referenced by generate().
Field Documentation
unsigned switch_generator::condition_components
Referenced by linear_sequence().
const TFunction& switch_generator::generator
Referenced by linear_sequence().
ir_variable* switch_generator::index
Referenced by bisect(), and linear_sequence().
unsigned switch_generator::linear_sequence_max_length
Referenced by generate().
void* switch_generator::mem_ctx
Referenced by bisect(), linear_sequence(), and switch_generator().
The documentation for this struct was generated from the following file:
lower_variable_index_to_cond_assign.cpp