Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
glsl_symbol_table Struct Reference
Facade class for _mesa_symbol_table.
#include <glsl_symbol_table.h>
Public Member Functions
glsl_symbol_table ()
~glsl_symbol_table ()
void push_scope ()
void pop_scope ()
bool name_declared_this_scope (const char *name)
Determine whether a name was declared at the current scope.
void add_global_function (ir_function *f)
Add an function at global scope without checking for scoping conflicts.
Methods to add symbols to the table
There is some temptation to rename all these functions to add_symbol or similar.
However, this breaks symmetry with the getter functions and reduces the clarity of the intention of code that uses these methods.
bool add_variable (ir_variable *v)
bool add_type (const char *name, const glsl_type *t)
bool add_function (ir_function *f)
bool add_interface (const char *name, const glsl_type *i, enum ir_variable_mode mode)
Methods to get symbols from the table
ir_variable * get_variable (const char *name)
const glsl_type * get_type (const char *name)
ir_function * get_function (const char *name)
const glsl_type * get_interface (const char *name, enum ir_variable_mode mode)
Static Public Member Functions
static void * operator new (size_t size, void *ctx)
static void operator delete (void *table)
Data Fields
bool separate_function_namespace
Detailed Description
Facade class for _mesa_symbol_table.
Wraps the existing _mesa_symbol_table data structure to enforce some type safe and some symbol table invariants.
Constructor & Destructor Documentation
glsl_symbol_table::glsl_symbol_table ()
References ralloc_context(), and separate_function_namespace.
glsl_symbol_table::~glsl_symbol_table ()
References ralloc_free().
Member Function Documentation
bool glsl_symbol_table::add_function (ir_function * f)
References symbol_table_entry::f, ir_function::name, name_declared_this_scope(), separate_function_namespace, and symbol_table_entry::t.
Referenced by import_prototype_visitor::visit_enter().
void glsl_symbol_table::add_global_function (ir_function * f)
Add an function at global scope without checking for scoping conflicts.
References ir_function::name.
bool glsl_symbol_table::add_interface (const char * name, const glsl_type * i, enum ir_variable_mode mode)
Referenced by validate_interstage_interface_blocks(), and validate_intrastage_interface_blocks().
bool glsl_symbol_table::add_type (const char * name, const glsl_type * t)
Referenced by add_types_to_symbol_table().
bool glsl_symbol_table::add_variable (ir_variable * v)
References symbol_table_entry::f, ir_variable::name, name_declared_this_scope(), separate_function_namespace, symbol_table_entry::t, and symbol_table_entry::v.
Referenced by add_variable(), cross_validate_globals(), and cross_validate_outputs_to_inputs().
ir_function * glsl_symbol_table::get_function (const char * name)
References symbol_table_entry::f.
Referenced by no_matching_function_error(), and import_prototype_visitor::visit_enter().
const glsl_type * glsl_symbol_table::get_interface (const char * name, enum ir_variable_mode mode)
References symbol_table_entry::get_interface().
Referenced by validate_interstage_interface_blocks(), and validate_intrastage_interface_blocks().
const glsl_type * glsl_symbol_table::get_type (const char * name)
References symbol_table_entry::t.
Referenced by add_builtin_variable(), generate_110_uniforms(), and generate_common_ES_uniforms().
ir_variable * glsl_symbol_table::get_variable (const char * name)
References symbol_table_entry::v.
Referenced by cross_validate_globals(), and cross_validate_outputs_to_inputs().
bool glsl_symbol_table::name_declared_this_scope (const char * name)
Determine whether a name was declared at the current scope.
Referenced by add_function(), and add_variable().
static void glsl_symbol_table::operator delete (void * table) inline static
References ralloc_free(), and ralloc_set_destructor().
static void* glsl_symbol_table::operator new (size_t size, void * ctx) inline static
References ralloc_set_destructor(), and ralloc_size().
void glsl_symbol_table::pop_scope ()
void glsl_symbol_table::push_scope ()
Field Documentation
bool glsl_symbol_table::separate_function_namespace
Referenced by add_function(), add_variable(), and glsl_symbol_table().
The documentation for this struct was generated from the following files:
glsl_symbol_table.h
glsl_symbol_table.cpp