Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
ir_lower_jumps_visitor Struct Reference
Public Member Functions
ir_lower_jumps_visitor ()
void truncate_after_instruction (exec_node *ir)
void move_outer_block_inside (ir_instruction *ir, exec_list *inner_block)
void insert_lowered_return (ir_return *ir)
Insert the instructions necessary to lower a return statement, before the given return instruction.
void lower_return_unconditionally (ir_instruction *ir)
If the given instruction is a return, lower it to instructions that store the return value (if there is one), set the return flag, and then break.
ir_instruction * create_lowered_break ()
Create the necessary instruction to replace a break instruction.
void lower_break_unconditionally (ir_instruction *ir)
If the given instruction is a break, lower it to an instruction that sets the break flag, without consulting should_lower_jump().
void lower_final_breaks (exec_list *block)
If the block ends in a conditional or unconditional break, lower it, even though should_lower_jump() says it needn't be lowered.
virtual void visit (class ir_loop_jump *ir)
virtual void visit (class ir_return *ir)
virtual void visit (class ir_discard *ir)
enum jump_strength get_jump_strength (ir_instruction *ir)
bool should_lower_jump (ir_jump *ir)
block_record visit_block (exec_list *list)
virtual void visit (ir_if *ir)
virtual void visit (ir_loop *ir)
virtual void visit (ir_function_signature *ir)
virtual void visit (class ir_function *ir)
Public Member Functions inherited from ir_control_flow_visitor
virtual void visit (class ir_variable *)
virtual void visit (class ir_expression *)
virtual void visit (class ir_texture *)
virtual void visit (class ir_swizzle *)
virtual void visit (class ir_dereference_variable *)
virtual void visit (class ir_dereference_array *)
virtual void visit (class ir_dereference_record *)
virtual void visit (class ir_assignment *)
virtual void visit (class ir_constant *)
virtual void visit (class ir_call *)
Public Member Functions inherited from ir_visitor
virtual ~ir_visitor ()
virtual void visit (class ir_rvalue *)
Data Fields
bool progress
struct function_record function
struct loop_record loop
struct block_record block
bool pull_out_jumps
bool lower_continue
bool lower_break
bool lower_sub_return
bool lower_main_return
Constructor & Destructor Documentation
ir_lower_jumps_visitor::ir_lower_jumps_visitor () inline
References progress.
Member Function Documentation
ir_instruction* ir_lower_jumps_visitor::create_lowered_break () inline
Create the necessary instruction to replace a break instruction.
References loop_record::get_break_flag(), and loop.
Referenced by lower_break_unconditionally(), and visit().
enum jump_strength ir_lower_jumps_visitor::get_jump_strength (ir_instruction * ir) inline
References ir_instruction::ir_type, ir_type_loop_jump, ir_type_return, is_break(), strength_break, strength_continue, strength_none, and strength_return.
Referenced by lower_break_unconditionally(), lower_return_unconditionally(), should_lower_jump(), and visit().
void ir_lower_jumps_visitor::insert_lowered_return (ir_return * ir) inline
Insert the instructions necessary to lower a return statement, before the given return instruction.
References loop, loop_record::may_set_return_flag, and ir_return::value.
Referenced by lower_return_unconditionally(), and visit().
void ir_lower_jumps_visitor::lower_break_unconditionally (ir_instruction * ir) inline
If the given instruction is a break, lower it to an instruction that sets the break flag, without consulting should_lower_jump().
It is safe to pass NULL to this function.
References create_lowered_break(), get_jump_strength(), and strength_break.
Referenced by lower_final_breaks().
void ir_lower_jumps_visitor::lower_final_breaks (exec_list * block) inline
If the block ends in a conditional or unconditional break, lower it, even though should_lower_jump() says it needn't be lowered.
References ir_instruction::as_if(), ir_if::else_instructions, lower_break_unconditionally(), and ir_if::then_instructions.
Referenced by visit().
void ir_lower_jumps_visitor::lower_return_unconditionally (ir_instruction * ir) inline
If the given instruction is a return, lower it to instructions that store the return value (if there is one), set the return flag, and then break.
It is safe to pass NULL to this function.
References get_jump_strength(), insert_lowered_return(), ir_loop_jump::jump_break, and strength_return.
Referenced by visit().
void ir_lower_jumps_visitor::move_outer_block_inside (ir_instruction * ir, exec_list * inner_block) inline
Referenced by visit().
bool ir_lower_jumps_visitor::should_lower_jump (ir_jump * ir) inline
References get_jump_strength(), loop_record::in_if_at_the_end_of_the_loop, loop_record::loop, loop, lower_break, lower_continue, loop_record::nesting_depth, strength_break, strength_continue, strength_none, and strength_return.
Referenced by visit().
void ir_lower_jumps_visitor::truncate_after_instruction (exec_node * ir) inline
References progress.
Referenced by visit().
virtual void ir_lower_jumps_visitor::visit (class ir_loop_jump * ir) inline virtual
Implements ir_visitor.
References ir_loop_jump::is_break(), strength_break, strength_continue, and truncate_after_instruction().
virtual void ir_lower_jumps_visitor::visit (class ir_return * ir) inline virtual
Implements ir_visitor.
References strength_return, and truncate_after_instruction().
virtual void ir_lower_jumps_visitor::visit (class ir_discard * ir) inline virtual
Implements ir_visitor.
virtual void ir_lower_jumps_visitor::visit (ir_if * ir) inline virtual
Implements ir_visitor.
References ir_instruction::as_dereference_variable(), ir_instruction::as_if(), ir_if::condition, create_lowered_break(), ir_if::else_instructions, loop_record::execute_flag, loop_record::get_execute_flag(), get_jump_strength(), exec_list::head, loop_record::in_if_at_the_end_of_the_loop, insert_lowered_return(), ir_loop_jump::jump_break, ir_loop_jump::jump_continue, loop_record::loop, loop, lower_continue, block_record::may_clear_execute_flag, block_record::min_strength, move_outer_block_inside(), loop_record::nesting_depth, progress, pull_out_jumps, should_lower_jump(), strength_always_clears_execute_flag, strength_break, strength_continue, strength_none, strength_return, ir_if::then_instructions, truncate_after_instruction(), ir_dereference_variable::var, and visit_block().
virtual void ir_lower_jumps_visitor::visit (ir_loop * ir) inline virtual
Implements ir_visitor.
References ir_loop::body_instructions, loop_record::break_flag, ir_if::else_instructions, get_jump_strength(), ir_loop_jump::jump_break, loop_record::loop, loop, lower_break, lower_final_breaks(), lower_return_unconditionally(), loop_record::may_set_return_flag, block_record::min_strength, move_outer_block_inside(), loop_record::nesting_depth, strength_break, strength_continue, ir_if::then_instructions, and visit_block().
virtual void ir_lower_jumps_visitor::visit (ir_function_signature * ir) inline virtual
Implements ir_visitor.
References ir_function_signature::body, ir_function_signature::function_name(), get_jump_strength(), ir_instruction::ir_type, ir_type_return, loop_record::loop, loop, lower_main_return, lower_sub_return, ir_function_signature::return_type, and visit_block().
virtual void ir_lower_jumps_visitor::visit (class ir_function * ir) inline virtual
Implements ir_visitor.
References ir_function::signatures, and visit_block().
block_record ir_lower_jumps_visitor::visit_block (exec_list * list) inline
References block, block_record::block_record(), and foreach_list.
Referenced by visit().
Field Documentation
struct block_record ir_lower_jumps_visitor::block
Referenced by visit_block().
struct function_record ir_lower_jumps_visitor::function
struct loop_record ir_lower_jumps_visitor::loop
Referenced by create_lowered_break(), insert_lowered_return(), should_lower_jump(), and visit().
bool ir_lower_jumps_visitor::lower_break
Referenced by do_lower_jumps(), should_lower_jump(), and visit().
bool ir_lower_jumps_visitor::lower_continue
Referenced by do_lower_jumps(), should_lower_jump(), and visit().
bool ir_lower_jumps_visitor::lower_main_return
Referenced by do_lower_jumps(), and visit().
bool ir_lower_jumps_visitor::lower_sub_return
Referenced by do_lower_jumps(), and visit().
bool ir_lower_jumps_visitor::progress
Referenced by do_lower_jumps(), ir_lower_jumps_visitor(), truncate_after_instruction(), and visit().
bool ir_lower_jumps_visitor::pull_out_jumps
Referenced by do_lower_jumps(), and visit().
The documentation for this struct was generated from the following file:
lower_jumps.cpp