Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
test_optpass.h File Reference
Macros
#define TEST_OPTPASS_H
Functions
int test_optpass (int argc, char **argv)
Macro Definition Documentation
#define TEST_OPTPASS_H
Function Documentation
int test_optpass (int argc, char ** argv)
References _mesa_ast_to_hir(), _mesa_glsl_initialize_types(), _mesa_glsl_read_ir(), _mesa_new_shader(), _mesa_print_ir(), _mesa_shader_type_to_index(), do_optimization_passes(), glcpp_preprocess(), initialize_context_to_defaults(), ralloc_free(), read_stdin_to_eof(), and rzalloc.
Referenced by main().