Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
t_dd_dmatmp.h File Reference
Template for render stages which build and emit vertices directly to fixed-size dma buffers.
Macros
#define ELTS_VARS(buf)
#define ALLOC_ELTS(nr) 0
#define EMIT_ELT(offset, elt)
#define EMIT_TWO_ELTS(offset, elt0, elt1)
#define INCR_ELTS(nr)
#define ELT_INIT(prim)
#define GET_CURRENT_VB_MAX_ELTS() 0
#define GET_SUBSEQUENT_VB_MAX_ELTS() 0
#define RELEASE_ELT_VERTS()
#define EMIT_INDEXED_VERTS(ctx, start, count)
Functions
static __inline void *TAG() emit_verts (struct gl_context *ctx, GLuint start, GLuint count, void *buf)
static void TAG() render_points_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_lines_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_line_strip_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_line_loop_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_triangles_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_tri_strip_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_tri_fan_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_poly_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_quad_strip_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_quads_verts (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static void TAG() render_noop (struct gl_context *ctx, GLuint start, GLuint count, GLuint flags)
static tnl_render_func TAG (render_tab_verts)[GL_POLYGON+2]
static GLboolean TAG() validate_render (struct gl_context *ctx, struct vertex_buffer *VB)
Detailed Description
Template for render stages which build and emit vertices directly to fixed-size dma buffers.
Useful for rendering strips and other native primitives where clipping and per-vertex tweaks such as those in t_dd_tritmp.h are not required.
Produces code for both inline triangles and indexed triangles. Where various primitive types are unaccelerated by hardware, the code attempts to fallback to other primitive types (quadstrips to tristrips, lineloops to linestrips), or to indexed vertices.
Macro Definition Documentation
#define ALLOC_ELTS (nr) 0
Referenced by render_line_loop_elts(), render_line_loop_verts(), render_line_strip_elts(), render_line_strip_verts(), render_lines_elts(), render_points_elts(), render_poly_elts(), render_quad_strip_elts(), render_quad_strip_verts(), render_quads_elts(), render_quads_verts(), render_tri_fan_elts(), render_tri_fan_verts(), render_tri_strip_elts(), render_tri_strip_verts(), and render_triangles_elts().
#define ELT_INIT (prim)
Referenced by render_line_loop_elts(), render_line_loop_verts(), render_line_strip_elts(), render_line_strip_verts(), render_lines_elts(), render_points_elts(), render_poly_elts(), render_quad_strip_elts(), render_quad_strip_verts(), render_quads_elts(), render_quads_verts(), render_tri_fan_elts(), render_tri_fan_verts(), render_tri_strip_elts(), render_tri_strip_verts(), and render_triangles_elts().
#define ELTS_VARS (buf)
Referenced by render_quad_strip_verts(), and render_quads_verts().
#define EMIT_ELT (offset, elt)
Referenced by emit_consecutive_elts(), emit_elts(), render_tri_fan_verts(), and render_tri_strip_verts().
#define EMIT_INDEXED_VERTS (ctx, start, count)
Referenced by render_quad_strip_verts(), and render_quads_verts().
#define EMIT_TWO_ELTS (offset, elt0, elt1)
Referenced by render_quad_strip_verts(), and render_quads_verts().
#define GET_CURRENT_VB_MAX_ELTS () 0
Referenced by render_quad_strip_verts(), and render_quads_verts().
#define GET_SUBSEQUENT_VB_MAX_ELTS () 0
Referenced by render_quad_strip_verts(), render_quads_verts(), and validate_render().
#define INCR_ELTS (nr)
Referenced by render_quad_strip_verts(), and render_quads_verts().
#define RELEASE_ELT_VERTS ()
Referenced by render_quad_strip_verts(), and render_quads_verts().
Function Documentation
static __inline void* TAG() emit_verts (struct gl_context * ctx, GLuint start, GLuint count, void * buf) static
Referenced by render_line_loop_verts(), render_line_strip_verts(), render_lines_verts(), render_points_verts(), render_poly_verts(), render_quad_strip_verts(), render_quads_verts(), render_tri_fan_verts(), render_tri_strip_verts(), and render_triangles_verts().
static void TAG() render_line_loop_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, emit_verts(), INIT, LOCAL_VARS, MIN2, PRIM_BEGIN, PRIM_END, TAG(), and void.
static void TAG() render_line_strip_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, emit_verts(), INIT, LOCAL_VARS, MIN2, and TAG().
static void TAG() render_lines_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, emit_verts(), INIT, LOCAL_VARS, MIN2, and TAG().
static void TAG() render_noop (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
static void TAG() render_points_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, emit_verts(), INIT, LOCAL_VARS, MIN2, and TAG().
static void TAG() render_poly_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, emit_verts(), INIT, gl_context::Light, LOCAL_VARS, MIN2, render_tri_fan_verts(), gl_light_attrib::ShadeModel, TAG(), and void.
static void TAG() render_quad_strip_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, _TNL_ATTRIB_COLOR0, ALLOC_ELTS, ELT_INIT, ELTS_VARS, EMIT_INDEXED_VERTS, EMIT_TWO_ELTS, emit_verts(), GET_CURRENT_VB_MAX_ELTS, GET_SUBSEQUENT_VB_MAX_ELTS, INCR_ELTS, INIT, gl_context::Light, LOCAL_VARS, MIN2, RELEASE_ELT_VERTS, gl_light_attrib::ShadeModel, TAG(), and TNL_CONTEXT.
static void TAG() render_quads_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, ALLOC_ELTS, ELT_INIT, ELTS_VARS, EMIT_INDEXED_VERTS, EMIT_TWO_ELTS, emit_verts(), GET_CURRENT_VB_MAX_ELTS, GET_SUBSEQUENT_VB_MAX_ELTS, INCR_ELTS, INIT, LOCAL_VARS, MIN2, RELEASE_ELT_VERTS, TAG(), and void.
static void TAG() render_tri_fan_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, emit_verts(), INIT, LOCAL_VARS, MIN2, TAG(), and void.
Referenced by render_poly_verts().
static void TAG() render_tri_strip_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References __FUNCTION__, emit_verts(), INIT, LOCAL_VARS, MIN2, and TAG().
static void TAG() render_triangles_verts (struct gl_context * ctx, GLuint start, GLuint count, GLuint flags) static
References emit_verts(), INIT, LOCAL_VARS, MIN2, and TAG().
static tnl_render_func TAG (render_tab_verts) static
Referenced by init(), render_line_loop_elts(), render_line_loop_verts(), render_line_strip_elts(), render_line_strip_verts(), render_lines_elts(), render_lines_verts(), render_points_elts(), render_points_verts(), render_poly_elts(), render_poly_verts(), render_quad_strip_elts(), render_quad_strip_verts(), render_quads_verts(), render_tri_fan_elts(), render_tri_fan_verts(), render_tri_strip_elts(), render_tri_strip_verts(), render_triangles_elts(), and render_triangles_verts().
static GLboolean TAG() validate_render (struct gl_context * ctx, struct vertex_buffer * VB) static
References _TNL_ATTRIB_COLOR0, CLIP_CULL_BIT, GET_SUBSEQUENT_VB_MAX_ELTS, gl_context::Light, gl_context::Line, PRIM_MODE_MASK, gl_light_attrib::ShadeModel, and gl_line_attrib::StippleFlag.