Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vbo_save.c File Reference
#include "main/mtypes.h"
#include "main/bufferobj.h"
#include "main/imports.h"
#include "vbo_context.h"
Functions
static void vbo_save_callback_init (struct gl_context *ctx)
void vbo_save_init (struct gl_context *ctx)
Called at context creation time.
void vbo_save_destroy (struct gl_context *ctx)
void vbo_save_fallback (struct gl_context *ctx, GLboolean fallback)
Function Documentation
static void vbo_save_callback_init (struct gl_context * ctx) static
References dd_function_table::BeginCallList, gl_context::Driver, dd_function_table::EndCallList, dd_function_table::EndList, dd_function_table::NewList, dd_function_table::NotifySaveBegin, dd_function_table::SaveFlushVertices, vbo_save_BeginCallList(), vbo_save_EndCallList(), vbo_save_EndList(), vbo_save_NewList(), vbo_save_NotifyBegin(), and vbo_save_SaveFlushVertices().
Referenced by vbo_save_init().
void vbo_save_destroy (struct gl_context * ctx)
References vbo_save_context::arrays, gl_client_array::BufferObj, vbo_save_vertex_store::bufferobj, NULL, vbo_save_context::prim_store, vbo_save_vertex_store::refcount, vbo_save_primitive_store::refcount, vbo_context::save, VBO_ATTRIB_MAX, vbo_context(), and vbo_save_context::vertex_store.
Referenced by _vbo_DestroyContext().
void vbo_save_fallback (struct gl_context * ctx, GLboolean fallback)
References vbo_save_context::replay_flags, vbo_context::save, vbo_context(), and VBO_SAVE_FALLBACK.
void vbo_save_init (struct gl_context * ctx)
Called at context creation time.
References vbo_save_context::arrays, gl_client_array::BufferObj, vbo_save_context::ctx, dd_function_table::CurrentSavePrimitive, vbo_context::currval, gl_context::Driver, NULL, PRIM_OUTSIDE_BEGIN_END, vbo_context::save, VBO_ATTRIB_GENERIC0, VBO_ATTRIB_POS, vbo_context(), vbo_save_api_init(), vbo_save_callback_init(), VERT_ATTRIB_FF, VERT_ATTRIB_FF_MAX, VERT_ATTRIB_GENERIC, and VERT_ATTRIB_GENERIC_MAX.
Referenced by _vbo_CreateContext().