Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vbo_exec.h File Reference
#include "main/mtypes.h"
#include "vbo.h"
#include "vbo_attrib.h"
Data Structures
struct vbo_exec_eval1_map
struct vbo_exec_eval2_map
struct vbo_exec_copied_vtx
struct vbo_exec_context
Macros
#define VBO_MAX_PRIM 64
Max number of primitives (number of glBegin/End pairs) per VBO.
#define VBO_VERT_BUFFER_SIZE (1024*64) /* bytes */
Size of the VBO to use for glBegin/glVertex/glEnd-style rendering.
Enumerations
enum vp_mode { VP_NONE, VP_ARB }
Current vertex program mode.
Functions
void vbo_exec_init (struct gl_context *ctx)
void vbo_exec_destroy (struct gl_context *ctx)
void vbo_exec_invalidate_state (struct gl_context *ctx, GLuint new_state)
Really want to install these callbacks to a central facility to be invoked according to the state flags.
void vbo_exec_BeginVertices (struct gl_context *ctx)
Called upon first glVertex, glColor, glTexCoord, etc.
void vbo_exec_FlushVertices (struct gl_context *ctx, GLuint flags)
Called via ctx->Driver.FlushVertices()
void vbo_exec_vtx_init (struct vbo_exec_context *exec)
void vbo_exec_vtx_destroy (struct vbo_exec_context *exec)
void vbo_exec_vtx_flush (struct vbo_exec_context *exec, GLboolean unmap)
Execute the buffer and save copied verts.
void vbo_exec_vtx_map (struct vbo_exec_context *exec)
Map the vertex buffer to begin storing glVertex, glColor, etc data.
void vbo_exec_vtx_wrap (struct vbo_exec_context *exec)
Deal with buffer wrapping where provoked by the vertex buffer filling up, as opposed to upgrade_vertex().
void vbo_exec_eval_update (struct vbo_exec_context *exec)
void vbo_exec_do_EvalCoord2f (struct vbo_exec_context *exec, GLfloat u, GLfloat v)
void vbo_exec_do_EvalCoord1f (struct vbo_exec_context *exec, GLfloat u)
Macro Definition Documentation
#define VBO_MAX_PRIM 64
Max number of primitives (number of glBegin/End pairs) per VBO.
Referenced by vbo_exec_End().
#define VBO_VERT_BUFFER_SIZE (1024*64) /* bytes */
Size of the VBO to use for glBegin/glVertex/glEnd-style rendering.
Referenced by vbo_exec_vtx_flush(), vbo_exec_vtx_init(), vbo_exec_vtx_map(), vbo_exec_vtx_unmap(), vbo_exec_wrap_upgrade_vertex(), and vbo_use_buffer_objects().
Enumeration Type Documentation
enum vp_mode
Current vertex program mode.
Enumerator
VP_NONE
fixed function
VP_ARB
ARB vertex program or GLSL vertex shader.
Function Documentation
void vbo_exec_BeginVertices (struct gl_context * ctx)
Called upon first glVertex, glColor, glTexCoord, etc.
References vbo_exec_context::begin_vertices_flags, gl_context::Driver, vbo_context::exec, FLUSH_UPDATE_CURRENT, dd_function_table::NeedFlush, vbo_context(), and vbo_exec_vtx_map().
Referenced by vbo_exec_init().
void vbo_exec_destroy (struct gl_context * ctx)
References _ae_destroy_context(), gl_context::aelt_context, vbo_context::exec, NULL, vbo_context(), and vbo_exec_vtx_destroy().
Referenced by _vbo_DestroyContext().
void vbo_exec_do_EvalCoord1f (struct vbo_exec_context * exec, GLfloat u)
Vertex – EvalCoord1f is a noop if this map not enabled:
References _math_horner_bezier_curve(), ASSIGN_4V, vbo_exec_context::attrptr, vbo_exec_context::attrsz, CALL_Vertex3fv, CALL_Vertex4fv, COPY_SZ_4V, gl_1d_map::du, vbo_exec_context::eval, vbo_exec_eval1_map::map, vbo_exec_context::map1, gl_1d_map::Order, gl_1d_map::Points, vbo_exec_eval1_map::sz, gl_1d_map::u1, VBO_ATTRIB_TEX7, and vbo_exec_context::vtx.
Referenced by vbo_exec_EvalCoord1f().
void vbo_exec_do_EvalCoord2f (struct vbo_exec_context * exec, GLfloat u, GLfloat v)
Vertex – EvalCoord2f is a noop if this map not enabled:
References _math_de_casteljau_surf(), _math_horner_bezier_surf(), ASSIGN_4V, vbo_exec_context::attrptr, vbo_exec_context::attrsz, gl_eval_attrib::AutoNormal, CALL_Vertex3fv, CALL_Vertex4fv, COPY_SZ_4V, vbo_exec_context::ctx, gl_2d_map::du, gl_2d_map::dv, gl_context::Eval, vbo_exec_context::eval, vbo_exec_eval2_map::map, vbo_exec_context::map2, gl_2d_map::Points, vbo_exec_eval2_map::sz, gl_2d_map::u1, gl_2d_map::Uorder, gl_2d_map::v1, VBO_ATTRIB_NORMAL, VBO_ATTRIB_TEX7, gl_2d_map::Vorder, and vbo_exec_context::vtx.
Referenced by vbo_exec_EvalCoord2f().
void vbo_exec_eval_update (struct vbo_exec_context * exec)
References clear_active_eval1(), clear_active_eval2(), vbo_exec_context::ctx, gl_context::Eval, vbo_exec_context::eval, gl_context::EvalMap, gl_evaluators::Map1Color4, gl_eval_attrib::Map1Color4, gl_evaluators::Map1Normal, gl_eval_attrib::Map1Normal, gl_evaluators::Map1Texture1, gl_evaluators::Map1Texture2, gl_evaluators::Map1Texture3, gl_evaluators::Map1Texture4, gl_eval_attrib::Map1TextureCoord1, gl_eval_attrib::Map1TextureCoord2, gl_eval_attrib::Map1TextureCoord3, gl_eval_attrib::Map1TextureCoord4, gl_eval_attrib::Map1Vertex3, gl_evaluators::Map1Vertex3, gl_eval_attrib::Map1Vertex4, gl_evaluators::Map1Vertex4, gl_eval_attrib::Map2Color4, gl_evaluators::Map2Color4, gl_eval_attrib::Map2Normal, gl_evaluators::Map2Normal, gl_evaluators::Map2Texture1, gl_evaluators::Map2Texture2, gl_evaluators::Map2Texture3, gl_evaluators::Map2Texture4, gl_eval_attrib::Map2TextureCoord1, gl_eval_attrib::Map2TextureCoord2, gl_eval_attrib::Map2TextureCoord3, gl_eval_attrib::Map2TextureCoord4, gl_eval_attrib::Map2Vertex3, gl_evaluators::Map2Vertex3, gl_eval_attrib::Map2Vertex4, gl_evaluators::Map2Vertex4, vbo_exec_context::recalculate_maps, set_active_eval1(), set_active_eval2(), VBO_ATTRIB_COLOR0, VBO_ATTRIB_FIRST_MATERIAL, VBO_ATTRIB_NORMAL, VBO_ATTRIB_POS, and VBO_ATTRIB_TEX0.
Referenced by vbo_exec_EvalCoord1f(), and vbo_exec_EvalCoord2f().
void vbo_exec_FlushVertices (struct gl_context * ctx, GLuint flags)
Called via ctx->Driver.FlushVertices()
Parameters
flags bitmask of FLUSH_STORED_VERTICES, FLUSH_UPDATE_CURRENT
References gl_context::Driver, vbo_context::exec, FLUSH_UPDATE_CURRENT, dd_function_table::NeedFlush, vbo_context(), and vbo_exec_FlushVertices_internal().
Referenced by vbo_exec_init().
void vbo_exec_init (struct gl_context * ctx)
References _ae_create_context(), gl_context::aelt_context, dd_function_table::BeginVertices, vbo_exec_context::ctx, dd_function_table::CurrentExecPrimitive, gl_context::Driver, vbo_context::exec, dd_function_table::FlushVertices, dd_function_table::NeedFlush, PRIM_OUTSIDE_BEGIN_END, vbo_context(), vbo_exec_BeginVertices(), vbo_exec_FlushVertices(), vbo_exec_invalidate_state(), and vbo_exec_vtx_init().
Referenced by _vbo_CreateContext().
void vbo_exec_invalidate_state (struct gl_context * ctx, GLuint new_state)
Really want to install these callbacks to a central facility to be invoked according to the state flags.
That will have to wait for a mesa rework:
References _ae_invalidate_state(), gl_array_attrib::_DrawArrays, _NEW_ARRAY, _NEW_EVAL, _NEW_PROGRAM, gl_context::Array, vbo_exec_context::array, DRAW_ARRAYS, DRAW_NONE, vbo_exec_context::eval, vbo_context::exec, vbo_context::last_draw_method, NULL, vbo_exec_context::recalculate_inputs, vbo_exec_context::recalculate_maps, vbo_exec_context::validating, and vbo_context().
Referenced by _vbo_InvalidateState(), and vbo_exec_init().
void vbo_exec_vtx_destroy (struct vbo_exec_context * exec)
References _mesa_align_free(), vbo_exec_context::arrays, ASSERT, vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, gl_client_array::BufferObj, vbo_exec_context::bufferobj, vbo_exec_context::ctx, gl_context::Driver, Elements, IMM_BUFFER_NAME, gl_buffer_object::Name, NULL, dd_function_table::UnmapBuffer, and vbo_exec_context::vtx.
Referenced by vbo_exec_destroy().
void vbo_exec_vtx_flush (struct vbo_exec_context * exec, GLboolean keepUnmapped)
Execute the buffer and save copied verts.
Parameters
keep_unmapped if true, leave the VBO unmapped when we're done.
References __FUNCTION__, _mesa_update_state(), vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, vbo_exec_context::buffer_used, vbo_exec_context::bufferobj, vbo_exec_context::copied, vbo_exec_context::ctx, vbo_context::draw_prims, vbo_exec_context::max_vert, gl_context::NewState, vbo_exec_copied_vtx::nr, NULL, vbo_exec_context::prim, vbo_exec_context::prim_count, vbo_context(), vbo_copy_vertices(), vbo_exec_bind_arrays(), vbo_exec_debug_verts(), vbo_exec_vtx_map(), vbo_exec_vtx_unmap(), VBO_VERT_BUFFER_SIZE, vbo_exec_context::vert_count, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.
Referenced by vbo_exec_End(), vbo_exec_FlushVertices_internal(), and vbo_exec_wrap_buffers().
void vbo_exec_vtx_init (struct vbo_exec_context * exec)
References _mesa_align_malloc(), _mesa_noop_vtxfmt_init(), vbo_exec_context::active_sz, vbo_exec_context::arrays, ASSERT, vbo_exec_context::attrsz, vbo_exec_context::attrtype, vbo_exec_context::begin_vertices_flags, vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, gl_client_array::BufferObj, vbo_exec_context::bufferobj, vbo_exec_context::ctx, vbo_context::currval, Elements, FLUSH_UPDATE_CURRENT, vbo_exec_context::inputs, NULL, gl_shared_state::NullBufferObj, gl_context::Shared, VBO_ATTRIB_GENERIC0, VBO_ATTRIB_MAX, VBO_ATTRIB_POS, vbo_context(), vbo_exec_vtxfmt_init(), VBO_VERT_BUFFER_SIZE, VERT_ATTRIB_FF, VERT_ATTRIB_FF_MAX, VERT_ATTRIB_GENERIC, VERT_ATTRIB_GENERIC_MAX, VERT_ATTRIB_MAX, vbo_exec_context::vertex_size, vbo_exec_context::vtx, and vbo_exec_context::vtxfmt_noop.
Referenced by vbo_exec_init().
void vbo_exec_vtx_map (struct vbo_exec_context * exec)
Map the vertex buffer to begin storing glVertex, glColor, etc data.
References _mesa_error(), _mesa_install_exec_vtxfmt(), _mesa_using_noop_vtxfmt(), vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, vbo_exec_context::buffer_used, dd_function_table::BufferData, vbo_exec_context::bufferobj, vbo_exec_context::ctx, gl_context::Driver, gl_context::Exec, dd_function_table::MapBufferRange, MESA_MAP_NOWAIT_BIT, NULL, gl_buffer_object::Size, VBO_VERT_BUFFER_SIZE, vbo_exec_context::vtx, vbo_exec_context::vtxfmt, and vbo_exec_context::vtxfmt_noop.
Referenced by vbo_exec_BeginVertices(), and vbo_exec_vtx_flush().
void vbo_exec_vtx_wrap (struct vbo_exec_context * exec)
Deal with buffer wrapping where provoked by the vertex buffer filling up, as opposed to upgrade_vertex().
References vbo_exec_copied_vtx::buffer, vbo_exec_context::buffer_ptr, vbo_exec_context::copied, vbo_exec_context::max_vert, vbo_exec_copied_vtx::nr, vbo_exec_wrap_buffers(), vbo_exec_context::vert_count, vbo_exec_context::vertex_size, and vbo_exec_context::vtx.