Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vbo_save.h File Reference
#include "main/mtypes.h"
#include "vbo.h"
#include "vbo_attrib.h"
Data Structures
struct vbo_save_copied_vtx
struct vbo_save_vertex_list
struct vbo_save_vertex_store
struct vbo_save_primitive_store
struct vbo_save_context
Macros
#define VBO_SAVE_BUFFER_SIZE (8*1024) /* dwords */
#define VBO_SAVE_PRIM_SIZE 128
#define VBO_SAVE_PRIM_MODE_MASK 0x3f
#define VBO_SAVE_PRIM_WEAK 0x40
#define VBO_SAVE_PRIM_NO_CURRENT_UPDATE 0x80
#define VBO_SAVE_FALLBACK 0x10000000
Functions
void vbo_save_init (struct gl_context *ctx)
Called at context creation time.
void vbo_save_destroy (struct gl_context *ctx)
void vbo_save_fallback (struct gl_context *ctx, GLboolean fallback)
void vbo_loopback_vertex_list (struct gl_context *ctx, const GLfloat *buffer, const GLubyte *attrsz, const struct _mesa_prim *prim, GLuint prim_count, GLuint wrap_count, GLuint vertex_size)
void vbo_save_EndList (struct gl_context *ctx)
void vbo_save_NewList (struct gl_context *ctx, GLuint list, GLenum mode)
void vbo_save_EndCallList (struct gl_context *ctx)
void vbo_save_BeginCallList (struct gl_context *ctx, struct gl_display_list *list)
void vbo_save_SaveFlushVertices (struct gl_context *ctx)
GLboolean vbo_save_NotifyBegin (struct gl_context *ctx, GLenum mode)
Called via ctx->Driver.NotifySaveBegin() when a glBegin is getting compiled into a display list.
void vbo_save_playback_vertex_list (struct gl_context *ctx, void *data)
Execute the buffer and save copied verts.
void vbo_save_api_init (struct vbo_save_context *save)
Initialize the display list compiler.
GLfloat * vbo_save_map_vertex_store (struct gl_context *ctx, struct vbo_save_vertex_store *vertex_store)
void vbo_save_unmap_vertex_store (struct gl_context *ctx, struct vbo_save_vertex_store *vertex_store)
Macro Definition Documentation
#define VBO_SAVE_BUFFER_SIZE (8*1024) /* dwords */
Referenced by _save_compile_vertex_list(), _save_reset_counters(), _save_upgrade_vertex(), and alloc_vertex_store().
#define VBO_SAVE_FALLBACK 0x10000000
Referenced by vbo_save_EndCallList(), and vbo_save_fallback().
#define VBO_SAVE_PRIM_MODE_MASK 0x3f
Referenced by vbo_save_NotifyBegin().
#define VBO_SAVE_PRIM_NO_CURRENT_UPDATE 0x80
Referenced by _save_OBE_DrawArrays(), _save_OBE_DrawElements(), and vbo_save_NotifyBegin().
#define VBO_SAVE_PRIM_SIZE 128
Referenced by _save_compile_vertex_list(), and _save_reset_counters().
#define VBO_SAVE_PRIM_WEAK 0x40
Referenced by _save_OBE_DrawArrays(), _save_OBE_DrawElements(), _save_OBE_Rectf(), loopback_weak_prim(), vbo_loopback_vertex_list(), and vbo_save_NotifyBegin().
Function Documentation
void vbo_loopback_vertex_list (struct gl_context * ctx, const GLfloat * buffer, const GLubyte * attrsz, const struct _mesa_prim * prim, GLuint prim_count, GLuint wrap_count, GLuint vertex_size)
References loopback_attr::func, loopback_prim(), loopback_weak_prim(), loopback_attr::sz, loopback_attr::target, VBO_ATTRIB_MAX, VBO_SAVE_PRIM_WEAK, and vert_attrfunc.
Referenced by _save_compile_vertex_list(), and vbo_save_loopback_vertex_list().
void vbo_save_api_init (struct vbo_save_context * save)
Initialize the display list compiler.
Called during context creation.
References _mesa_dlist_alloc_opcode(), _mesa_noop_vtxfmt_init(), _save_current_init(), _save_vtxfmt_init(), vbo_save_context::arrays, vbo_save_context::ctx, gl_context::Driver, vbo_save_context::inputs, dd_function_table::NotifySaveBegin, vbo_save_context::opcode_vertex_list, VBO_ATTRIB_MAX, vbo_destroy_vertex_list(), vbo_print_vertex_list(), vbo_save_NotifyBegin(), vbo_save_playback_vertex_list(), and vbo_save_context::vtxfmt_noop.
Referenced by vbo_save_init().
void vbo_save_BeginCallList (struct gl_context * ctx, struct gl_display_list * list)
References gl_display_list::Flags, vbo_save_context::replay_flags, vbo_context::save, and vbo_context().
Referenced by vbo_save_callback_init().
void vbo_save_destroy (struct gl_context * ctx)
References vbo_save_context::arrays, gl_client_array::BufferObj, vbo_save_vertex_store::bufferobj, NULL, vbo_save_context::prim_store, vbo_save_vertex_store::refcount, vbo_save_primitive_store::refcount, vbo_context::save, VBO_ATTRIB_MAX, vbo_context(), and vbo_save_context::vertex_store.
Referenced by _vbo_DestroyContext().
void vbo_save_EndCallList (struct gl_context * ctx)
References gl_dlist_state::CallDepth, gl_context::ListState, vbo_save_context::replay_flags, vbo_context::save, vbo_context(), and VBO_SAVE_FALLBACK.
Referenced by vbo_save_callback_init().
void vbo_save_EndList (struct gl_context * ctx)
References _mesa_install_save_vtxfmt(), _mesa_prim::count, dd_function_table::CurrentSavePrimitive, vbo_save_context::dangling_attr_ref, gl_context::Driver, _mesa_prim::end, gl_context::ListState, gl_dlist_state::ListVtxfmt, vbo_save_context::prim, vbo_save_context::prim_count, PRIM_OUTSIDE_BEGIN_END, vbo_context::save, _mesa_prim::start, vbo_context(), vbo_save_SaveFlushVertices(), vbo_save_unmap_vertex_store(), vbo_save_context::vert_count, vbo_save_context::vertex_size, and vbo_save_context::vertex_store.
Referenced by vbo_save_callback_init().
void vbo_save_fallback (struct gl_context * ctx, GLboolean fallback)
References vbo_save_context::replay_flags, vbo_context::save, vbo_context(), and VBO_SAVE_FALLBACK.
void vbo_save_init (struct gl_context * ctx)
Called at context creation time.
References vbo_save_context::arrays, gl_client_array::BufferObj, vbo_save_context::ctx, dd_function_table::CurrentSavePrimitive, vbo_context::currval, gl_context::Driver, NULL, PRIM_OUTSIDE_BEGIN_END, vbo_context::save, VBO_ATTRIB_GENERIC0, VBO_ATTRIB_POS, vbo_context(), vbo_save_api_init(), vbo_save_callback_init(), VERT_ATTRIB_FF, VERT_ATTRIB_FF_MAX, VERT_ATTRIB_GENERIC, and VERT_ATTRIB_GENERIC_MAX.
Referenced by _vbo_CreateContext().
GLfloat* vbo_save_map_vertex_store (struct gl_context * ctx, struct vbo_save_vertex_store * vertex_store)
References vbo_save_vertex_store::buffer, vbo_save_vertex_store::bufferobj, gl_context::Driver, dd_function_table::MapBufferRange, NULL, gl_buffer_object::Size, and vbo_save_vertex_store::used.
Referenced by _save_compile_vertex_list(), vbo_save_NewList(), and vbo_save_playback_vertex_list().
void vbo_save_NewList (struct gl_context * ctx, GLuint list, GLenum mode)
References _save_reset_counters(), _save_reset_vertex(), alloc_prim_store(), alloc_vertex_store(), vbo_save_context::buffer_ptr, gl_context::Driver, vbo_save_context::prim_store, vbo_context::save, dd_function_table::SaveNeedFlush, vbo_context(), vbo_save_map_vertex_store(), vbo_save_context::vertex_store, and void.
Referenced by vbo_save_callback_init().
GLboolean vbo_save_NotifyBegin (struct gl_context * ctx, GLenum mode)
Called via ctx->Driver.NotifySaveBegin() when a glBegin is getting compiled into a display list.
Updating of ctx->Driver.CurrentSavePrimitive is already taken care of.
References _mesa_install_save_vtxfmt(), _mesa_prim::base_instance, _mesa_prim::begin, _mesa_prim::count, gl_context::Driver, _mesa_prim::end, _mesa_prim::mode, _mesa_prim::no_current_update, _mesa_prim::num_instances, vbo_save_context::out_of_memory, _mesa_prim::pad, vbo_save_context::prim, vbo_save_context::prim_count, vbo_save_context::prim_max, vbo_context::save, dd_function_table::SaveNeedFlush, _mesa_prim::start, vbo_context(), VBO_SAVE_PRIM_MODE_MASK, VBO_SAVE_PRIM_NO_CURRENT_UPDATE, VBO_SAVE_PRIM_WEAK, vbo_save_context::vert_count, vbo_save_context::vtxfmt, vbo_save_context::vtxfmt_noop, and _mesa_prim::weak.
Referenced by _save_OBE_DrawArrays(), _save_OBE_DrawElements(), _save_OBE_Rectf(), vbo_save_api_init(), and vbo_save_callback_init().
void vbo_save_playback_vertex_list (struct gl_context * ctx, void * data)
Execute the buffer and save copied verts.
This is called from the display list code when executing a drawing command.
References gl_vertex_program_state::_Enabled, gl_fragment_program_state::_Enabled, _mesa_error(), _mesa_update_state(), _playback_copy_to_current(), _mesa_prim::begin, vbo_save_vertex_store::buffer, vbo_save_context::buffer_ptr, vbo_save_vertex_list::count, DRAW_DISPLAY_LIST, vbo_context::draw_prims, gl_vertex_program_state::Enabled, gl_fragment_program_state::Enabled, end(), FLUSH_CURRENT, gl_context::FragmentProgram, gl_context::NewState, NULL, vbo_save_vertex_list::prim, vbo_save_vertex_list::prim_count, vbo_save_context::replay_flags, vbo_context::save, vbo_bind_vertex_list(), vbo_context(), vbo_draw_method(), vbo_save_loopback_vertex_list(), vbo_save_map_vertex_store(), vbo_save_unmap_vertex_store(), vbo_save_context::vertex_store, and gl_context::VertexProgram.
Referenced by vbo_save_api_init().
void vbo_save_SaveFlushVertices (struct gl_context * ctx)
References _save_compile_vertex_list(), _save_copy_to_current(), _save_reset_counters(), _save_reset_vertex(), dd_function_table::CurrentSavePrimitive, gl_context::Driver, vbo_save_context::prim_count, PRIM_MAX, vbo_context::save, dd_function_table::SaveNeedFlush, vbo_context(), and vbo_save_context::vert_count.
Referenced by vbo_save_callback_init(), and vbo_save_EndList().
void vbo_save_unmap_vertex_store (struct gl_context * ctx, struct vbo_save_vertex_store * vertex_store)
References vbo_save_vertex_store::buffer, vbo_save_vertex_store::bufferobj, gl_context::Driver, NULL, gl_buffer_object::Size, and dd_function_table::UnmapBuffer.
Referenced by _save_compile_vertex_list(), vbo_save_EndList(), and vbo_save_playback_vertex_list().