Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vbo.h File Reference
#include <stdbool.h>
#include "main/glheader.h"
Data Structures
struct _mesa_prim
struct _mesa_index_buffer
struct split_limits
Typedefs
typedef void(* vbo_draw_func)(struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *tfb_vertcount)
Functions
GLboolean _vbo_CreateContext (struct gl_context *ctx)
void _vbo_DestroyContext (struct gl_context *ctx)
void _vbo_InvalidateState (struct gl_context *ctx, GLuint new_state)
void vbo_initialize_exec_dispatch (const struct gl_context *ctx, struct _glapi_table *exec)
Initialize the dispatch table with the VBO functions for drawing.
void vbo_initialize_save_dispatch (const struct gl_context *ctx, struct _glapi_table *exec)
Initialize the dispatch table with the VBO functions for display list compilation.
void vbo_split_prims (struct gl_context *ctx, const struct gl_client_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits *limits)
GLboolean vbo_all_varyings_in_vbos (const struct gl_client_array *arrays[])
GLboolean vbo_any_varyings_in_vbos (const struct gl_client_array *arrays[])
void vbo_rebase_prims (struct gl_context *ctx, const struct gl_client_array *arrays[], const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLuint min_index, GLuint max_index, vbo_draw_func draw)
static int vbo_sizeof_ib_type (GLenum type)
void vbo_get_minmax_indices (struct gl_context *ctx, const struct _mesa_prim *prim, const struct _mesa_index_buffer *ib, GLuint *min_index, GLuint *max_index, GLuint nr_prims)
Compute min and max elements for nr_prims.
void vbo_use_buffer_objects (struct gl_context *ctx)
Tell the VBO module to use a real OpenGL vertex buffer object to store accumulated immediate-mode vertex data.
void vbo_always_unmap_buffers (struct gl_context *ctx)
If this function is called, all VBO buffers will be unmapped when we flush.
void vbo_set_draw_func (struct gl_context *ctx, vbo_draw_func func)
void vbo_check_buffers_are_unmapped (struct gl_context *ctx)
A debug function that may be called from other parts of Mesa as needed during debugging.
void vbo_bind_arrays (struct gl_context *ctx)
Examine the enabled vertex arrays to set the exec->array.inputs[] values.
size_t vbo_count_tessellated_primitives (GLenum mode, GLuint count, GLuint num_instances)
Figure out the number of transform feedback primitives that will be output considering the drawing mode, number of vertices, and instance count, assuming that no geometry shading is done and primitive restart is not used.
void vbo_try_prim_conversion (struct _mesa_prim *p)
In some degenarate cases we can improve our ability to merge consecutive primitives.
bool vbo_can_merge_prims (const struct _mesa_prim *p0, const struct _mesa_prim *p1)
Helper function for determining if two subsequent glBegin/glEnd primitives can be combined.
void vbo_merge_prims (struct _mesa_prim *p0, const struct _mesa_prim *p1)
If we've determined that p0 and p1 can be merged, this function concatenates p1 onto p0.
void vbo_sw_primitive_restart (struct gl_context *ctx, const struct _mesa_prim *prim, GLuint nr_prims, const struct _mesa_index_buffer *ib)
Handle primitive restart in software.
void GLAPIENTRY _es_Color4f (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void GLAPIENTRY _es_Normal3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _es_MultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
void GLAPIENTRY _es_Materialfv (GLenum face, GLenum pname, const GLfloat *params)
void GLAPIENTRY _es_Materialf (GLenum face, GLenum pname, GLfloat param)
void GLAPIENTRY _es_VertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void GLAPIENTRY _es_VertexAttrib1f (GLuint indx, GLfloat x)
void GLAPIENTRY _es_VertexAttrib1fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
void GLAPIENTRY _es_VertexAttrib2fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _es_VertexAttrib3fv (GLuint indx, const GLfloat *values)
void GLAPIENTRY _es_VertexAttrib4fv (GLuint indx, const GLfloat *values)
Typedef Documentation
typedef void(* vbo_draw_func)(struct gl_context *ctx, const struct _mesa_prim *prims, GLuint nr_prims, const struct _mesa_index_buffer *ib, GLboolean index_bounds_valid, GLuint min_index, GLuint max_index, struct gl_transform_feedback_object *tfb_vertcount)
Function Documentation
void GLAPIENTRY _es_Color4f (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void GLAPIENTRY _es_Materialf (GLenum face, GLenum pname, GLfloat param)
References vbo_Materialfv().
void GLAPIENTRY _es_Materialfv (GLenum face, GLenum pname, const GLfloat * params)
References vbo_Materialfv().
void GLAPIENTRY _es_MultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
void GLAPIENTRY _es_Normal3f (GLfloat x, GLfloat y, GLfloat z)
void GLAPIENTRY _es_VertexAttrib1f (GLuint indx, GLfloat x)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
void GLAPIENTRY _es_VertexAttrib1fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
void GLAPIENTRY _es_VertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
void GLAPIENTRY _es_VertexAttrib2fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
void GLAPIENTRY _es_VertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
void GLAPIENTRY _es_VertexAttrib3fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
void GLAPIENTRY _es_VertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
void GLAPIENTRY _es_VertexAttrib4fv (GLuint indx, const GLfloat * values)
References VertexAttrib4f_nopos().
Referenced by vbo_exec_vtxfmt_init().
GLboolean _vbo_CreateContext (struct gl_context * ctx)
References _ae_create_context(), _math_init_eval(), gl_context::aelt_context, gl_context::API, API_OPENGL_COMPAT, CALLOC_STRUCT, Elements, init_generic_currval(), init_legacy_currval(), init_mat_currval(), vbo_context::map_vp_arb, vbo_context::map_vp_none, NR_MAT_ATTRIBS, gl_context::swtnl_im, VBO_ATTRIB_MAT_FRONT_AMBIENT, vbo_exec_init(), vbo_save_init(), and VERT_ATTRIB_GENERIC.
void _vbo_DestroyContext (struct gl_context * ctx)
References _ae_destroy_context(), gl_context::aelt_context, gl_context::API, API_OPENGL_COMPAT, gl_client_array::BufferObj, vbo_context::currval, NULL, gl_context::swtnl_im, VBO_ATTRIB_MAX, vbo_context(), vbo_exec_destroy(), and vbo_save_destroy().
void _vbo_InvalidateState (struct gl_context * ctx, GLuint new_state)
References vbo_exec_invalidate_state().
GLboolean vbo_all_varyings_in_vbos (const struct gl_client_array * arrays[])
References VERT_ATTRIB_MAX.
void vbo_always_unmap_buffers (struct gl_context * ctx)
If this function is called, all VBO buffers will be unmapped when we flush.
Otherwise, if a simple command like glColor3f() is called and we flush, the current VBO may be left mapped.
References vbo_exec_context::begin_vertices_flags, vbo_context::exec, FLUSH_STORED_VERTICES, and vbo_context().
GLboolean vbo_any_varyings_in_vbos (const struct gl_client_array * arrays[])
References VERT_ATTRIB_MAX.
void vbo_bind_arrays (struct gl_context * ctx)
Examine the enabled vertex arrays to set the exec->array.inputs[] values.
These will point to the arrays to actually use for drawing. Some will be user-provided arrays, other will be zero-stride const-valued arrays. Note that this might set the _NEW_VARYING_VP_INPUTS dirty flag so state validation must be done after this call.
References _mesa_update_state(), vbo_exec_context::array, DRAW_ARRAYS, vbo_context::exec, gl_context::NewState, recalculate_input_bindings(), vbo_exec_context::recalculate_inputs, vbo_exec_context::validating, vbo_context(), and vbo_draw_method().
Referenced by vbo_draw_arrays(), vbo_draw_transform_feedback(), vbo_validated_drawrangeelements(), and vbo_validated_multidrawelements().
bool vbo_can_merge_prims (const struct _mesa_prim * p0, const struct _mesa_prim * p1)
Helper function for determining if two subsequent glBegin/glEnd primitives can be combined.
This is only possible for GL_POINTS, GL_LINES, GL_TRIANGLES and GL_QUADS. If we return true, it means that we can concatenate p1 onto p0 (and discard p1).
References _mesa_prim::base_instance, _mesa_prim::basevertex, _mesa_prim::begin, _mesa_prim::count, _mesa_prim::end, _mesa_prim::mode, _mesa_prim::num_instances, and _mesa_prim::start.
Referenced by merge_prims(), try_vbo_merge(), and vbo_merge_prims().
void vbo_check_buffers_are_unmapped (struct gl_context * ctx)
A debug function that may be called from other parts of Mesa as needed during debugging.
References vbo_exec_context::array, vbo_exec_context::bufferobj, check_buffers_are_unmapped(), vbo_context::exec, vbo_exec_context::inputs, vbo_context(), and vbo_exec_context::vtx.
size_t vbo_count_tessellated_primitives (GLenum mode, GLuint count, GLuint num_instances)
Figure out the number of transform feedback primitives that will be output considering the drawing mode, number of vertices, and instance count, assuming that no geometry shading is done and primitive restart is not used.
This is used by driver back-ends in implementing the PRIMITIVES_GENERATED and TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN queries. It is also used to pre-validate draw calls in GLES3 (where draw calls only succeed if there is enough room in the transform feedback buffer for the result).
void vbo_get_minmax_indices (struct gl_context * ctx, const struct _mesa_prim * prim, const struct _mesa_index_buffer * ib, GLuint * min_index, GLuint * max_index, GLuint nr_prims)
Compute min and max elements for nr_prims.
References _mesa_prim::count, MAX2, MIN2, _mesa_prim::start, and vbo_get_minmax_index().
void vbo_initialize_exec_dispatch (const struct gl_context * ctx, struct _glapi_table * exec)
Initialize the dispatch table with the VBO functions for drawing.
References gl_context::API, API_OPENGL_COMPAT, vbo_exec_DrawArrays(), vbo_exec_DrawArraysInstanced(), vbo_exec_DrawArraysInstancedBaseInstance(), vbo_exec_DrawElements(), vbo_exec_DrawElementsBaseVertex(), vbo_exec_DrawElementsInstanced(), vbo_exec_DrawElementsInstancedBaseInstance(), vbo_exec_DrawElementsInstancedBaseVertex(), vbo_exec_DrawElementsInstancedBaseVertexBaseInstance(), vbo_exec_DrawRangeElements(), vbo_exec_DrawRangeElementsBaseVertex(), vbo_exec_DrawTransformFeedback(), vbo_exec_DrawTransformFeedbackInstanced(), vbo_exec_DrawTransformFeedbackStream(), vbo_exec_DrawTransformFeedbackStreamInstanced(), vbo_exec_EvalMesh1(), vbo_exec_EvalMesh2(), vbo_exec_MultiDrawElements(), vbo_exec_MultiDrawElementsBaseVertex(), and vbo_exec_Rectf().
void vbo_initialize_save_dispatch (const struct gl_context * ctx, struct _glapi_table * exec)
Initialize the dispatch table with the VBO functions for display list compilation.
References _save_OBE_DrawArrays(), _save_OBE_DrawElements(), _save_OBE_DrawRangeElements(), _save_OBE_MultiDrawElements(), _save_OBE_MultiDrawElementsBaseVertex(), and _save_OBE_Rectf().
void vbo_merge_prims (struct _mesa_prim * p0, const struct _mesa_prim * p1)
If we've determined that p0 and p1 can be merged, this function concatenates p1 onto p0.
References _mesa_prim::count, _mesa_prim::end, and vbo_can_merge_prims().
Referenced by merge_prims(), and try_vbo_merge().
void vbo_rebase_prims (struct gl_context * ctx, const struct gl_client_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index, vbo_draw_func draw)
References __FUNCTION__, gl_array_attrib::_DrawArrays, ADD_POINTERS, gl_extensions::ARB_draw_elements_base_vertex, gl_context::Array, _mesa_prim::basevertex, _mesa_index_buffer::count, gl_context::Driver, gl_context::DriverFlags, gl_context::Extensions, dd_function_table::MapBufferRange, gl_buffer_object::Name, gl_driver_flags::NewArray, gl_context::NewDriverState, NULL, gl_shared_state::NullBufferObj, _mesa_index_buffer::obj, gl_buffer_object::Pointer, gl_client_array::Ptr, _mesa_index_buffer::ptr, gl_context::Shared, gl_buffer_object::Size, _mesa_prim::start, gl_client_array::StrideB, _mesa_index_buffer::type, and dd_function_table::UnmapBuffer.
void vbo_set_draw_func (struct gl_context * ctx, vbo_draw_func func)
References vbo_context::draw_prims, and vbo_context().
static int vbo_sizeof_ib_type (GLenum type) inline static
References GLubyte, and GLushort.
Referenced by vbo_get_minmax_index(), vbo_sw_primitive_restart(), and vbo_validated_multidrawelements().
void vbo_split_prims (struct gl_context * ctx, const struct gl_client_array * arrays[], const struct _mesa_prim * prim, GLuint nr_prims, const struct _mesa_index_buffer * ib, GLuint min_index, GLuint max_index, vbo_draw_func draw, const struct split_limits * limits)
References _mesa_prim::basevertex, _mesa_index_buffer::count, MAX2, split_limits::max_indices, split_limits::max_verts, vbo_split_copy(), and vbo_split_inplace().
void vbo_sw_primitive_restart (struct gl_context * ctx, const struct _mesa_prim * prims, GLuint nr_prims, const struct _mesa_index_buffer * ib)
Handle primitive restart in software.
This function breaks up calls into the driver so primitive restart support is not required in the driver.
References _mesa_primitive_restart_index(), ADD_POINTERS, _mesa_prim::count, _mesa_index_buffer::count, sub_primitive::count, vbo_context::draw_prims, gl_context::Driver, find_sub_primitives(), dd_function_table::MapBufferRange, MAX2, sub_primitive::max_index, MIN2, sub_primitive::min_index, gl_buffer_object::Name, NULL, _mesa_index_buffer::obj, gl_buffer_object::Pointer, _mesa_index_buffer::ptr, gl_buffer_object::Size, _mesa_prim::start, sub_primitive::start, _mesa_index_buffer::type, dd_function_table::UnmapBuffer, vbo_context(), and vbo_sizeof_ib_type().
Referenced by vbo_handle_primitive_restart().
void vbo_try_prim_conversion (struct _mesa_prim * p)
In some degenarate cases we can improve our ability to merge consecutive primitives.
For example: glBegin(GL_LINE_STRIP); glVertex(1); glVertex(1); glEnd(); glBegin(GL_LINE_STRIP); glVertex(1); glVertex(1); glEnd(); Can be merged as a GL_LINES prim with four vertices.
This function converts 2-vertex line strips/loops into GL_LINES, etc.
References _mesa_prim::count, and _mesa_prim::mode.
Referenced by merge_prims(), and try_vbo_merge().
void vbo_use_buffer_objects (struct gl_context * ctx)
Tell the VBO module to use a real OpenGL vertex buffer object to store accumulated immediate-mode vertex data.
This replaces the malloced buffer which was created in vb_exec_vtx_init() below.
References _mesa_align_free(), _mesa_error(), vbo_exec_context::buffer_map, vbo_exec_context::buffer_ptr, dd_function_table::BufferData, vbo_exec_context::bufferobj, gl_context::Driver, vbo_context::exec, IMM_BUFFER_NAME, dd_function_table::NewBufferObject, NULL, gl_shared_state::NullBufferObj, gl_context::Shared, vbo_context(), VBO_VERT_BUFFER_SIZE, and vbo_exec_context::vtx.