Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vbo_save_draw.c File Reference
#include "main/glheader.h"
#include "main/bufferobj.h"
#include "main/context.h"
#include "main/imports.h"
#include "main/mtypes.h"
#include "main/macros.h"
#include "main/light.h"
#include "main/state.h"
#include "vbo_context.h"
Functions
static void _playback_copy_to_current (struct gl_context *ctx, const struct vbo_save_vertex_list *node)
After playback, copy everything but the position from the last vertex to the saved state.
static void vbo_bind_vertex_list (struct gl_context *ctx, const struct vbo_save_vertex_list *node)
Treat the vertex storage as a VBO, define vertex arrays pointing into it:
static void vbo_save_loopback_vertex_list (struct gl_context *ctx, const struct vbo_save_vertex_list *list)
void vbo_save_playback_vertex_list (struct gl_context *ctx, void *data)
Execute the buffer and save copied verts.
Function Documentation
static void _playback_copy_to_current (struct gl_context * ctx, const struct vbo_save_vertex_list * node) static
After playback, copy everything but the position from the last vertex to the saved state.
References gl_client_array::_ElementSize, _mesa_update_color_material(), _NEW_CURRENT_ATTRIB, _NEW_LIGHT, gl_current_attrib::Attrib, vbo_save_vertex_list::attrsz, vbo_save_vertex_list::attrtype, vbo_save_vertex_list::buffer_offset, vbo_save_vertex_store::bufferobj, gl_light_attrib::ColorMaterialEnabled, vbo_save_vertex_list::count, gl_context::Current, vbo_save_vertex_list::current_data, vbo_save_vertex_list::current_size, dd_function_table::CurrentExecPrimitive, vbo_context::currval, gl_context::Driver, _mesa_prim::end, dd_function_table::GetBufferSubData, gl_client_array::Integer, gl_context::Light, _mesa_prim::mode, gl_context::NewState, vbo_save_vertex_list::prim, vbo_save_vertex_list::prim_count, PRIM_OUTSIDE_BEGIN_END, gl_client_array::Ptr, gl_client_array::Size, gl_client_array::Type, VBO_ATTRIB_COLOR0, VBO_ATTRIB_FIRST_MATERIAL, VBO_ATTRIB_LAST_MATERIAL, VBO_ATTRIB_MAX, VBO_ATTRIB_POS, vbo_attrtype_to_integer_flag(), vbo_context(), vbo_save_vertex_list::vertex_size, and vbo_save_vertex_list::vertex_store.
Referenced by vbo_save_playback_vertex_list().
static void vbo_bind_vertex_list (struct gl_context * ctx, const struct vbo_save_vertex_list * node) static
Treat the vertex storage as a VBO, define vertex arrays pointing into it:
References gl_vertex_program_state::_Current, gl_client_array::_ElementSize, gl_client_array::_MaxElement, _mesa_set_varying_vp_inputs(), vbo_save_context::arrays, vbo_save_vertex_list::attrsz, vbo_save_vertex_list::attrtype, gl_vertex_program::Base, vbo_save_vertex_list::buffer_offset, gl_client_array::BufferObj, vbo_save_vertex_store::bufferobj, vbo_save_vertex_list::count, vbo_context::currval, gl_context::DriverFlags, gl_client_array::Enabled, gl_client_array::Format, get_program_mode(), GLubyte, vbo_save_context::inputs, gl_program::InputsRead, gl_client_array::Integer, vbo_context::map_vp_arb, vbo_context::map_vp_none, MAT_ATTRIB_MAX, gl_driver_flags::NewArray, gl_context::NewDriverState, NULL, gl_client_array::Ptr, vbo_context::save, gl_client_array::Size, gl_client_array::Stride, gl_client_array::StrideB, gl_client_array::Type, VBO_ATTRIB_GENERIC0, VBO_ATTRIB_MAT_FRONT_AMBIENT, VBO_ATTRIB_MAX, VBO_ATTRIB_POS, vbo_attrtype_to_integer_flag(), vbo_context(), VERT_ATTRIB_FF_MAX, VERT_ATTRIB_GENERIC, VERT_ATTRIB_GENERIC0, VERT_ATTRIB_GENERIC_MAX, VERT_ATTRIB_MAX, VERT_BIT, VERT_BIT_GENERIC0, VERT_BIT_POS, vbo_save_vertex_list::vertex_size, vbo_save_vertex_list::vertex_store, gl_context::VertexProgram, VP_ARB, and VP_NONE.
Referenced by vbo_save_playback_vertex_list().
static void vbo_save_loopback_vertex_list (struct gl_context * ctx, const struct vbo_save_vertex_list * list) static
References vbo_save_vertex_list::attrsz, vbo_save_vertex_list::buffer_offset, vbo_save_vertex_store::bufferobj, gl_context::Driver, dd_function_table::MapBufferRange, vbo_save_vertex_list::prim, vbo_save_vertex_list::prim_count, gl_buffer_object::Size, dd_function_table::UnmapBuffer, vbo_loopback_vertex_list(), vbo_save_vertex_list::vertex_size, vbo_save_vertex_list::vertex_store, and vbo_save_vertex_list::wrap_count.
Referenced by vbo_save_playback_vertex_list().
void vbo_save_playback_vertex_list (struct gl_context * ctx, void * data)
Execute the buffer and save copied verts.
This is called from the display list code when executing a drawing command.
References gl_vertex_program_state::_Enabled, gl_fragment_program_state::_Enabled, _mesa_error(), _mesa_update_state(), _playback_copy_to_current(), _mesa_prim::begin, vbo_save_vertex_store::buffer, vbo_save_context::buffer_ptr, vbo_save_vertex_list::count, DRAW_DISPLAY_LIST, vbo_context::draw_prims, gl_vertex_program_state::Enabled, gl_fragment_program_state::Enabled, end(), FLUSH_CURRENT, gl_context::FragmentProgram, gl_context::NewState, NULL, vbo_save_vertex_list::prim, vbo_save_vertex_list::prim_count, vbo_save_context::replay_flags, vbo_context::save, vbo_bind_vertex_list(), vbo_context(), vbo_draw_method(), vbo_save_loopback_vertex_list(), vbo_save_map_vertex_store(), vbo_save_unmap_vertex_store(), vbo_save_context::vertex_store, and gl_context::VertexProgram.
Referenced by vbo_save_api_init().