Mesa Source Code Documentation
core | glapi | glsl | vbo | math | shader | swrast | swrast_setup | tnl | tnl_dd | gbm
vbo_noop.h File Reference
#include "main/mtypes.h"
Functions
void _mesa_noop_vtxfmt_init (GLvertexformat *vfmt)
Build a vertexformat of functions that are no-ops.
GLboolean _mesa_using_noop_vtxfmt (const struct _glapi_table *dispatch)
Is the given dispatch table using the no-op functions?
Function Documentation
void _mesa_noop_vtxfmt_init (GLvertexformat * vfmt)
Build a vertexformat of functions that are no-ops.
These are used in out-of-memory situations when we have no VBO to put the vertex data into.
References _mesa_CallList(), _mesa_CallLists(), _mesa_noop_ArrayElement(), _mesa_noop_Begin(), _mesa_noop_Color3f(), _mesa_noop_Color3fv(), _mesa_noop_Color4f(), _mesa_noop_Color4fv(), _mesa_noop_EdgeFlag(), _mesa_noop_End(), _mesa_noop_EvalCoord1f(), _mesa_noop_EvalCoord1fv(), _mesa_noop_EvalCoord2f(), _mesa_noop_EvalCoord2fv(), _mesa_noop_EvalPoint1(), _mesa_noop_EvalPoint2(), _mesa_noop_FogCoordfEXT(), _mesa_noop_FogCoordfvEXT(), _mesa_noop_Indexf(), _mesa_noop_Indexfv(), _mesa_noop_Materialfv(), _mesa_noop_MultiTexCoord1fARB(), _mesa_noop_MultiTexCoord1fvARB(), _mesa_noop_MultiTexCoord2fARB(), _mesa_noop_MultiTexCoord2fvARB(), _mesa_noop_MultiTexCoord3fARB(), _mesa_noop_MultiTexCoord3fvARB(), _mesa_noop_MultiTexCoord4fARB(), _mesa_noop_MultiTexCoord4fvARB(), _mesa_noop_Normal3f(), _mesa_noop_Normal3fv(), _mesa_noop_PrimitiveRestartNV(), _mesa_noop_SecondaryColor3fEXT(), _mesa_noop_SecondaryColor3fvEXT(), _mesa_noop_TexCoord1f(), _mesa_noop_TexCoord1fv(), _mesa_noop_TexCoord2f(), _mesa_noop_TexCoord2fv(), _mesa_noop_TexCoord3f(), _mesa_noop_TexCoord3fv(), _mesa_noop_TexCoord4f(), _mesa_noop_TexCoord4fv(), _mesa_noop_Vertex2f(), _mesa_noop_Vertex2fv(), _mesa_noop_Vertex3f(), _mesa_noop_Vertex3fv(), _mesa_noop_Vertex4f(), _mesa_noop_Vertex4fv(), _mesa_noop_VertexAttrib1fARB(), _mesa_noop_VertexAttrib1fNV(), _mesa_noop_VertexAttrib1fvARB(), _mesa_noop_VertexAttrib1fvNV(), _mesa_noop_VertexAttrib2fARB(), _mesa_noop_VertexAttrib2fNV(), _mesa_noop_VertexAttrib2fvARB(), _mesa_noop_VertexAttrib2fvNV(), _mesa_noop_VertexAttrib3fARB(), _mesa_noop_VertexAttrib3fNV(), _mesa_noop_VertexAttrib3fvARB(), _mesa_noop_VertexAttrib3fvNV(), _mesa_noop_VertexAttrib4fARB(), _mesa_noop_VertexAttrib4fNV(), _mesa_noop_VertexAttrib4fvARB(), and _mesa_noop_VertexAttrib4fvNV().
Referenced by vbo_exec_vtx_init(), and vbo_save_api_init().
GLboolean _mesa_using_noop_vtxfmt (const struct _glapi_table * dispatch)
Is the given dispatch table using the no-op functions?
References _mesa_noop_Begin().
Referenced by vbo_exec_vtx_map().